### ISSUE TITLE
How to set the max length number of one line in  monaco editor ?

### ISSUE THREAD

**Issue by cloudtrends** [Microsoft/monaco-editor#1]
hi all,

After past a very long one line text more than 300 ascii char into monaco , I fond that the line is wraped , but 300 is much more thant what I want .

How to set the max length number of one line in  monaco editor ? or set allow auto wrap according to the editor width as common html editor does.

thanks in advance .

**Comment by mbana** [comment]
Just searching the code-base alone: https://github.com/Microsoft/monaco-editor/search?utf8=%E2%9C%93&q=wrappingColumn. You can set it at creation or update it later - wrappingColumn, that is.

**Comment by egamma** [comment]
@mbana this is correct, thanks & closing.
