### ISSUE TITLE
How to use "showUnused" editor option?

### ISSUE THREAD

**Issue by yln99517** [Microsoft/monaco-editor#1000]
I tried the following snippet in the playground. but there is no fading for unused variable.

```javascript
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\tvar d;\n\talert('Hello world!');\n}",
	language: "typescript",
    showUnused: true
});
```

any working samples?

**Comment by alexandrudima** [comment]
This setting turns on the UI side of things. We also would need some language implementation to provide such diagnostics/markers. AFAIK none of the built-in languages provide "unused" diagnostics/markers.

**Comment by zewa666** [comment]
Using the typescript language server with the tsconfig setting `noUnusedLocals`, we do get red squiggles, so how would one map that to the `showUnused` feature?

**Comment by zewa666** [comment]
@alexandrudima thanks for pointing that out. Is there an existing issue for that which we can track?

**Comment by alexandrudima** [comment]
@zewa666 I don't think there is any issue to track specifically this. We keep issues for `monaco-typescript` in this repo with the label `monaco-typescript`.
