### ISSUE TITLE
How to scope intillisense down to just passed in `.d.ts` defs.

### ISSUE THREAD

**Issue by philcockfield** [Microsoft/monaco-editor#1001]
I’m looking at the configuration options for the VSCode MonacoEditor related to specifying intellisense via `.d.ts` definitions:

[Playground: Configure JS Defaults Example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults)

```js
// compiler options
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ES6,
    allowNonTsExtensions: true
});

// extra libraries
monaco.languages.typescript.javascriptDefaults.addExtraLib([
    'declare class Facts {',
    '    /**',
    '     * Returns the next fact',
    '     */',
    '    static next():string',
    '}',
].join('\n'), 'filename/facts.d.ts');

var jsCode = [
    '"use strict";',
    '',
    "class Chuck {",
    "    greet() {",
    "        return Facts.next();",
    "    }",
    "}"
].join('\n');

monaco.editor.create(document.getElementById("container"), {
    value: jsCode,
    language: "javascript"
});
```

I’m wondering if there is a way to scope intillisense down to just the types passed in via `addExtraLib` - at the moment the kitchen sink of ES6 is available in the dropdown lists, including all of HTML5 for the browser etc etc.

For my purposes, I’m having the editor run in a tightly constrained environment so most of the API surface area represented in these dropdowns in not relevant.

The `target` field of `setCompilerOptions` seems likely, but in playing around with that it doesn’t seem to have any effect on reducing scope, eg all of these options don't narrow scope at all:

![image](https://user-images.githubusercontent.com/185555/44065204-69a8fb8c-9fbd-11e8-9229-6bcd83396ab8.png)

ref [Playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults)

---

Any ideas?  It feels like this must be somewhere else in the API, yeah? 
Thanks 🌵

**Comment by yln99517** [comment]
You can pass 'nolib' option to setcompileroption.

**Comment by philcockfield** [comment]
Thanks @yln99517 - that's great.

Setting `nolib` to true seems to wipes out the HTML/Browser centric intillisense, and I am just getting my passed in `.d.ts`, however as a follow-on question, how would I go about dealing with this "No Promise" error:

![image](https://user-images.githubusercontent.com/185555/44118292-b67fc434-a069-11e8-86c3-2fe4b970e134.png)

I'm setting `noLib` and then passing in `ES2015` to `lib` as suggested, but no dice:

    typescript.typescriptDefaults.setCompilerOptions({
      noLib: true, // NB: This ensures
      lib: ['ES2015'],
      target: typescript.ScriptTarget.ES2017,
      allowNonTsExtensions: true,
    });

Any ideas?  Thanks!

**Comment by yln99517** [comment]
You need to extract required libs from default libs then pass to addExtraLib. It solves the problem.

**Comment by philcockfield** [comment]
Thanks @yln99517.  Where do I find the "default libs" to extract from?

**Comment by philcockfield** [comment]
I wonder if  you might be able to give me a brief code sample to get me going in the right direction please @yln99517 ?

**Comment by yln99517** [comment]
Hi , 
Goto [this](https://github.com/Microsoft/TypeScript/tree/master/lib). You can see lot of libs available. Pack required libs into one file or in a string. Pass the string to [addExtraLib](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults).
Hope this helps.
thanks

**Comment by philcockfield** [comment]
@yln99517 - sweet! That's perfect, thanks!
