### ISSUE TITLE
Hi I have a Question about addExtraLib API..

### ISSUE THREAD

**Issue by Kang-Jun-sik** [microsoft/monaco-editor#1002]
Thanks for providing excellent editing tool ~ :) it is the best code editor i think! 
Q. I have a one problem that I want to refresh addExtraLib content(ex d.ts)...
I want to use new d.ts content when i call the "addExtraLib" API...
but still remain previous data.... and i don't want to terminate my browser!
how can i do that... 
if it is possible, how can i access? .... 
thank you for reading!

**Comment by alexdima** [comment]
`addExtraLib` returns an `IDisposable`. You can call `.dispose()` on the returned object and then call `addExtraLib` again.
