### ISSUE TITLE
Creating an editor with the theme option triggers a tokenization update on all existing models 

### ISSUE THREAD

**Issue by mofux** [Microsoft/monaco-editor#1003]
monaco-editor version: 0.14.2
Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
OS: MacOS High Sierra (10.13.5)

------------
I am seeing all my editor instances recalculating the tokens (text gets uncolored for a short moment, then gets colorised again shortly after) whenever a new editor instance is spawned. Isolating this issue, it only happens if I provide a `theme` name in the editor constructor options. Luckily I've been able to create a reproducible minimal example.

Paste the following snippet in the [Hello World Playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world) and run it - watch the dev console output.

```javascript
const body = document.getElementsByTagName('body')[0];

// register own language to demonstrate the issue
monaco.languages.register({
    id: 'mylang'
});

// simple state for tokenizer
class State {
    clone() {
        return new State();
    }
    equals() {
        return true;
    }
}

// own tokens provider to demonstrate the issue
monaco.languages.setTokensProvider('mylang', {
    getInitialState: () => {
        return new State();
    },
    tokenize: (line) => {
        console.log('tokenize', line);
        return {
            endState: new State(),
            tokens: []
        };
    }
});

for (let i=1; i<=5; i++) {
    setTimeout(() => {
        const el = document.createElement('div');
        body.appendChild(el);
        monaco.editor.create(el, {
            theme: 'vs',
            language: 'mylang',
            value: `model ${i}`
        });
    }, i * 1000);
}
```

Running the example above will produce the following log output in the dev console:

```
tokenize model 1
tokenize model 1
tokenize model 2
tokenize model 1
tokenize model 2
tokenize model 3
tokenize model 1
tokenize model 2
tokenize model 3
tokenize model 4
tokenize model 1
tokenize model 2
tokenize model 3
tokenize model 4
tokenize model 5
```

Commenting out the `theme: 'vs'` option in line 37 of the snippet and re-running it will yield the following (expected) output:

```
tokenize model 1
tokenize model 2
tokenize model 3
tokenize model 4
tokenize model 5
```

**Comment by tevfik6** [comment]
Yeah, I noticed this and I was thinking; such a powerful editor would be able to set separate theme. 
But setting one theme for all, not ideal and useful at all.. I have two options either use without themes or move to Ace Editor back (and appreciate what I had there lol)
