### ISSUE TITLE
No infix matching of completion items after special characters

### ISSUE THREAD

**Issue by foxable** [Microsoft/monaco-editor#1007]
monaco-editor version: 0.14.2
Browser: Any
OS: Windows 10

Steps or JS usage snippet reproducing the issue:

1. Insert the snippet below into the [Monaco playground](https://microsoft.github.io/monaco-editor/playground.html), then run it.
```
monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function() {
        return [
            { label: "$bar" },
            { label: "$Bar" }
        ];
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\n}",
    language: "json"
});
```
2. Trigger IntelliSense within the curly brackets using Ctrl + Space. Both `$bar` and `$Bar` appear as completions.
3. Now filter the completions by typing `b`. Only `$Bar` remains as a match. Hower, my expectation is that both completion items match.

It seems that infix matching for completion items is (at least partially) based on camel-casing. E.g., `bar` matches `fooBar`, but not `foobar`. I think this helps to make matches more relevant in common scenarios. However, it prevents matching completion items with prefixes that may be omitted when using IntelliSense, like in my example.

One solution could be to adjust infix matching of completion items, or at least provide the ability to define "word-separators". Another solution would be to support multiple filterTexts for a single completion item.

**Comment by jrieken** [comment]
Yes, provide a `range` property in the completion items and make sure the `range` selects the correct prefix in the document. By default the word definition is used to figure out what the range is and that likely doesn't contain special characters.

**Comment by foxable** [comment]
Thank you for your quick reply. How am I supposed to solve this problem using a `range` on the completion item? According to the documentation, `range` only affects the insertion, not the filtering of completion items. In my example, the typed word `b` does not contain special characters, only the completion items does. But I couldn't get to match the infix `b` just like the `B` by providing a custom range.

**Comment by foxable** [comment]
I implemented the following workaround: The prefix is now included in the `filterText` only if it is not directly before the completion position within the model. Yet I would prefer a less restrictive infix matching for completion items.

**Comment by glacierck** [comment]
look~
special characters : "/"
---------------------------------------------------------------------------------------------
 monaco.languages.registerCompletionItemProvider('newlanguages', {
        provideCompletionItems: (model, position) => {
          let textUntilPosition = model.getValueInRange({
            startLineNumber: position.lineNumber,
            startColumn: position.column -2,
            endLineNumber: position.lineNumber,
            endColumn: position.column });
          let match = textUntilPosition.match(/\//);
          let suggestions = match ? self.suggestions:[{label: ''}];//[{label: ''}] hack !!! kill the quickSuggestions
          return {suggestions: suggestions};
        }
      });
