### ISSUE TITLE
Mac keyboard combination is unusual

### ISSUE THREAD

**Issue by babycannotsay** [Microsoft/monaco-editor#1010]
monaco-editor version: 0.13.1
Browser: Chrome(68.0.3440.106)
OS: Mac
Steps or JS usage snippet reproducing the issue:
In the [playground](https://microsoft.github.io/monaco-editor/playground.html), I can copy, paste, select all, undo, etc by `cmd + c`, `cmd + v`, `cmd + a`, `cmd + z`.
But when I developing **monaco-editor**, the key operations are strange in the browser.
copy by `cmd + c`,
paste by `cmd + v`,
above is ok.
but select all is by `ctrl + a` and undo is by `ctrl + z`.
`cmd + a` and `cmd + z` is failed.
Maybe is here having some prop to control it?

**Comment by babycannotsay** [comment]
By the way, `ctrl + c` and `ctrl + v` is failed.

**Comment by babycannotsay** [comment]
#681 the issue is similar.
I use React and Webpack which defines process result in above problem.Is here solution?

**Comment by babycannotsay** [comment]
What I do is define `process.nextTick` as other type  by `webpack-define-plugin` to make it usual.Maybe is here better solution?

**Comment by alexandrudima** [comment]
@babycannotsay Do you know what is the recommended way to identify the runtime correctly such that the source code is webpack compatible ?

**Comment by babycannotsay** [comment]
@alexandrudima 
let `if (typeof navigator === 'object')` in front of `else if (typeof process === 'object' && typeof process.nextTick === 'function' && typeof process.platform === 'string')`?

**Comment by babycannotsay** [comment]
I was a bit wrong before.
I read [webpack](https://webpack.js.org/configuration/node/) just now.
Just by the define some node's value in webpack would make  `typeof process === 'object' && typeof process.nextTick === 'function' && typeof process.platform === 'string'` be true.
The packaging tool I am using is again packaged by webpack.It set node's value to 'mock'.
