### ISSUE TITLE
Monarch Playground broken for HTML

### ISSUE THREAD

**Issue by fabsenet** [Microsoft/monaco-editor#1014]
monaco-editor version: latest(?)
Browser: firefox, chrome
OS: windows 7
Steps or JS usage snippet reproducing the issue:

- go to <https://microsoft.github.io/monaco-editor/monarch.html>
- select sample `html` from dropdown

see rendering stopping after line 9:
![image](https://user-images.githubusercontent.com/2065705/44347914-5c486500-a499-11e8-981d-9d346f898df9.png)

There is also an error in the console:
> Error: monarch-language-html: no rule containing nextEmbedded: "`@pop`" in tokenizer embedded state: embedded.style

**Comment by alexandrudima** [comment]
It is possible the sample is no longer good. You can use the one we actually ship for HTML from https://github.com/Microsoft/monaco-languages/blob/a3d4b50888f8ad49d5fc87d6add002b99809f4c9/src/html/html.ts#L67:L205
