### ISSUE TITLE
`go to line` widget at wrong place when there are multiple editors

### ISSUE THREAD

**Issue by troy351** [Microsoft/monaco-editor#1016]
monaco-editor version: 0.14.3
Browser: lateset stable Chrome
OS: Win10
Steps or JS usage snippet reproducing the issue:

- Go to `Diff Editor` at https://microsoft.github.io/monaco-editor/
- click left part and press Ctrl+G to activate `go to line` widget (hereinafter called the `GTL`)
- then click right part, the `GTL` in the left part should be hided
- press Ctrl+G in the right part, it seems the `GTL` shows in left part rather than right part
- further more, if we go to the standard `Editor` above and trigger `GTL` right now, it shows in `Diff Editor`

**Comment by alexandrudima** [comment]
I think the confusion comes from the fact that the go to line widget focuses the origin editor when it closes via focus loss due to clicking. When it closes due to focus loss due to clicking, it should not focus the origin editor.

**Comment by bpasero** [comment]
This should be fine with https://github.com/Microsoft/vscode/commit/9c2c8d9bb1e2808c9d5cfdd27241cfc246402be9
