### ISSUE TITLE
“Escape” key event propagation

### ISSUE THREAD

**Issue by nikhilexe** [Microsoft/monaco-editor#1017]
I have hosted Monaco editor in a panel which can be close using "Escape" key. Now if **Find widget** is open in the editor, pressing "Escape" should only close the widget but currently it closes panel as well. Need to stop event propagation here or please let me know how can i handle this

**Comment by alexandrudima** [comment]
You can add a command:

```
editor.addCommand(monaco.KeyCode.Escape, function() {
    alert('I should close my panel!');

}, '!findWidgetVisible && !inReferenceSearchEditor && !editorHasSelection') //....
```

You can fish for the full list by looking at vs code keybindings for escape, there are other cases where you would not want to handle escape...

**Comment by nikhilexe** [comment]
Thanks @alexandrudima, due to some other limitation i was not able to solve the issue, but this helps me to get direction.
