### ISSUE TITLE
Accessibility: Focus is not trapped with monaco editor

### ISSUE THREAD

**Issue by nikhilexe** [Microsoft/monaco-editor#1018]
I am using Panel to host Monaco editor, here is the sample codepen link https://codepen.io/nikhilexe/pen/yqyPyO. 

If you TAB inside the panel, focus goes like this
Button1 -> Button2 -> Editor -> then somewhere outside the panel

Not sure if this is the bug or i need to pass some editor options to control this.

Interestingly if i put another button below editor then everything works fine, see this link https://codepen.io/nikhilexe/pen/pOoBZj

Focus goes like this
Button1 -> Button2 -> Editor -> Button3 -> Button1

**Comment by alexandrudima** [comment]
@nikhilexe read only editors do not trap focus. You can add your own command listening on `Tab` to trap focus if you wish to do so.

**Comment by nikhilexe** [comment]
@alexandrudima Thanks, it worked with your suggestion
