### ISSUE TITLE
Read only for humans, but writable for API.

### ISSUE THREAD

**Issue by shoorlyne** [Microsoft/monaco-editor#1019]
monaco-editor version: 0.14.3
Browser: Chrome 67.0.3396.99
OS: macOS 10.12

We'd like to use Monaco to implement an edit player. That is, when a user edits, we save all the edits he makes to a file. Later when we want to replay such edits, we load them from the file, and feed all of them to Monaco editor.

This is fine with us, we have no issue with that. However, we'd like Monaco to block user inputs when in replay mode, as we don't want the user to mess around with the editor state. I have tried the `readOnly` flag when creating the editor, and it did prevent me from manually editing in the editor. However, it also succeeded in preventing us from updating the editor via calling `executeEdits`.

So, is it possible to put the editor into a state where it blocks human inputs, while accepting those from `executeEdits`?

Thanks!

**Comment by troy351** [comment]
if you don't want user to select code test either (just watch the animation).
How about blur the editor and set CSS `pointer-event: none`? This makes users unable to focus the editor so they can't typing

**Comment by alexandrudima** [comment]
@shoorlyne While an editor can be read only, a text buffer is always editable. i.e.

```js
	function executeEdits(edits, endCursorState) {
		editor.getModel().pushEditOperations(editor.getSelections(), edits, () => {
			return endCursorState ? endCursorState : null;
		});

		if (endCursorState) {
			editor.setSelections(endCursorState);
		}
	}
```

**Comment by hifall** [comment]
@alexandrudima, thanks for your suggestion. It works!

@troy351, thanks for your useful input too.

**Comment by shoorlyne** [comment]
Thanks @alexandrudima, it works!
