### ISSUE TITLE
registerHoverProvider typings make "no hover" impossible to express

### ISSUE THREAD

**Issue by fabsenet** [Microsoft/monaco-editor#1021]
monaco-editor version: [playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example)
Browser: firefox
OS: Windows 7
Steps or JS usage snippet reproducing the issue:
- open playground
- replace javascript with

```js
monaco.languages.register({ id: 'mySpecialLanguage' });

monaco.languages.registerHoverProvider('mySpecialLanguage', {
    provideHover: function (model, position) {
        if (position.lineNumber !== 3) return; 
        // ^^^^ this provider only works for line 3 but typescript fails here!!
        return {
            range: new monaco.Range(3, 1, 3, model.getLineMaxColumn(3)),
            contents: [
                { value: 'title' },
                { value: 'some text' }
            ]
        }
    }
}
);
monaco.editor.create(document.getElementById("container"), {
    value: 'abc\ndef\nHover ONLY over THIS text',
    language: 'mySpecialLanguage'
});

```
Result: Hovering works over line 3, does not do anything when hovering over line 1 or 2.

Simply returning or returning undefined or null or an empty object is not supported by the typings in editor.api.d.ts
```ts
 provideHover(model: editor.ITextModel, position: Position, token: CancellationToken): Hover | Thenable<Hover>;
```

Can you change the expected return type to: `Hover | Thenable<Hover> | null` ?
I cannot build a hover provider in typescript which does not provide hovers for everything.

**Comment by fabsenet** [comment]
Or better, the return type should be

`Hover | undefined | null | Thenable<Hover | undefined | null>`

I checked the using code and verified it with faking the result and it works so far.

"Faked" provider as a workaround:

```typescript
    monaco.languages.registerHoverProvider("myLang", {
      provideHover: function(model, position) {
        let ret: monaco.languages.Hover;
        if (position.lineNumber == 3) {
          ret = {
            range: new monaco.Range(1,1,1,4),
            contents: [{ value: "a" }, { value: "b" }],
          };
        }
        return ret!; // the ! tells the typescript compiler to shut up
      },
    });
```

**Comment by alexandrudima** [comment]
@fabsenet Can you make a PR please?

**Comment by fabsenet** [comment]
this issue is not fixed.

**Comment by alexandrudima** [comment]
@fabsenet Why is it not fixed ?

**Comment by fabsenet** [comment]
ah I have to apoligize. I looked at tha notifications and thought you were just closing it because of my build-braking PR. I did not see your own PR fixing the issue. Sorry!

Good work and thank you!
