### ISSUE TITLE
Find Widget undo/redo stack doesn't work properly in Chrome

### ISSUE THREAD

**Issue by EmpireJones** [microsoft/monaco-editor#1023]
monaco-editor version: 0.14.6(6c8f02b41db9ae5c4d15df767d47755e5c73b9d5) - or whatever https://microsoft.github.io/monaco-editor/index.html is using
Browser: recent Chrome / Chromium, e.g. Version 68.0.3440.106 (Official Build) (64-bit)
OS: Windows, Linux

Steps or JS usage snippet reproducing the issue:
- From https://github.com/Microsoft/vscode/issues/27035:
> Steps to Reproduce:
> 
> Press Ctrl-F
> Type something into the field
> Select some text in the file being edited
> Press Ctrl-F again
> Try to undo/redo using keyboard shortcuts

**Comment by alexdima** [comment]
Let's continue tracking in https://github.com/microsoft/vscode/issues/27035
