### ISSUE TITLE
Register Language Commands in Monaco

### ISSUE THREAD

**Issue by liz3** [Microsoft/monaco-editor#1025]
**NOTE:** I know that questions should go on Stackoverflow, but the "Monaco editor" tag on stackoverflow seams quite inactive, so i will also ask here, note i asked it on stackoverflow yesterday too.

In the Monaco documentation, exact: in [CompletionItem](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html), there is a property called [command](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html#command)(Description: A command that should be run upon acceptance of this item.). My question: where do i register these commands, if possible with a handler?

Regards.
Liz3

**Comment by rcjsuen** [comment]
See #900 and #942.

**Comment by liz3** [comment]
Thanks, saw the asnwer right away and forgot to close the issue!
The solution
```typescript
(editor as any)._commandService.addCommand({ 
		id: "command-id", 
		handler: (_: any, ...args: any[]) => {
			return myLspService.executeCommand("command-id", args);
		},
});```
