### ISSUE TITLE
About the comment error

### ISSUE THREAD

**Issue by lwinhong** [Microsoft/monaco-editor#1027]
monaco-editor version: 0.14.3
Browser:chrome
OS: win10
Steps or JS usage snippet reproducing the issue:

This comment is incorrect;
Comment the middle element first, then select the parent element to comment again;
As shown below
![image](https://user-images.githubusercontent.com/31954501/44570407-4e078b00-a7b0-11e8-962e-2df7ee40ddbf.png)

@alexandrudima

**Comment by alexandrudima** [comment]
The command is built to add `<!--` before the selection and `-->` after the selection. The command does not parse in any meaningful way the contents of the selection or anything like that.

**Comment by lwinhong** [comment]
Okay thanks @alexandrudima
