### ISSUE TITLE
Incorrect hover popover positioning.

### ISSUE THREAD

**Issue by shoorlyne** [microsoft/monaco-editor#1032]
monaco-editor version: 0.14.3
Browser: Chrome 67.0.3396.99
OS: macOS 10.12

A hover popover appears "squeezed" when showing up near the right boundary of the editor. See below:

<img width="662" alt="screen shot 2018-08-28 at 8 15 00 am" src="https://user-images.githubusercontent.com/20250340/44693736-6b807180-aa9c-11e8-8e25-4f1b2e7d3bb2.png">

This issue may be related to [#1028](https://github.com/Microsoft/monaco-editor/issues/1028). If you find they are the same issue, feel free to close one of them.

**Comment by shoorlyne** [comment]
This is by no means any bit of a push... but any chance you could share the priority of UI glitches like this one, [#1031](https://github.com/Microsoft/monaco-editor/issues/1031), and [#1032](https://github.com/Microsoft/monaco-editor/issues/1032)?

We are going to release a product based on Monaco soon. We'd like to release the product with as few UI glitches as possible, as they are quite visible from the end users' perspective, and frequent enough as well.

We try to align our development cycle with Monaco's. If the priority of such issues is high, we can wait until they are finished; otherwise, we will ship first, and fix these later.

Thanks!

**Comment by alexandrudima** [comment]
@shoorlyne PR welcome!

In my experience, if you manage to reproduce these issues in VS Code, you have a lot higher chance of them getting addressed.

**Comment by shoorlyne** [comment]
Is there a quick way to style the popover so that it extends outside the editor in order not to be squeezed? something like setting position to absolute?

**Comment by alexdima** [comment]
I believe this has been fixed in the meantime. The hover now can be positioned to the left of the symbol that is hovered e.g.
![image](https://user-images.githubusercontent.com/5047891/70722090-f8355a00-1cf6-11ea-9760-908b07f4cf19.png)
