### ISSUE TITLE
Incorporating monaco-editor into a bootstrap layout

### ISSUE THREAD

**Issue by renegadeandy** [microsoft/monaco-editor#1034]
Hi all.

I want to include monaco-editor into my Electron app based on the bootstrap UI.

At the moment, I can only get monaco-editor to work if my `<div>` container element for monaco is directly inside the `<body>` tag.

If I try this:

```
        <div id="step3-content" style="display:none;">
               <h1>Step 3</h1>
            <h1>Monaco Editor in Electron!</h1>
    <div id="dev-window" style="width:500px;height:300px;border:1px solid #ccc"></div>
          </div>
```

With the associated:

```
amdRequire(['vs/editor/editor.main'], function() {
			var editor = monaco.editor.create(document.getElementById('dev-window'), {
				value: [
					'function x() {',
					'\tconsole.log("Hello world!");',
					'}'
				].join('\n'),
				language: 'javascript'
			});
		});
```
If show my step3-content div, all I get is my 500x500 div with no monaco editor within it(and no errors as well!).

What special trick do I need to pull, to allow this to work?

**Comment by renegadeandy** [comment]
It seems after further investigation that this is linked to the style="display:none;", removing that resolves the issue, but breaks my application's flow. 

Even removing that style, and hiding the container after my own javascript has loaded recreates the problem. The only solution so far I have found is to remove any hiding of that container.

**Comment by alexandrudima** [comment]
@renegadeandy The editor does not automatically adjust its size. You need to manually call `editor.layout()` if you change the container size. i.e. when that div becomes visible, you need to relayout the editor. You an also call `editor.layout(w, h)`
