### ISSUE TITLE
Go To Symbol is Broken 

### ISSUE THREAD

**Issue by yln99517** [microsoft/monaco-editor#1037]
Hi, 
I think "Go To Symbol" is broken in latest version. Paste the below snippet in editor and press "CMD + Shift + o". It will not show "getName" and "getAge" in list. It used to work in previous versions.

``` javascript
function Employee() {

}

Employee.prototype = {
	getName: function() {

	},
	getAge: function() {

	}
};

```

-Thanks

**Comment by jrieken** [comment]
This requires a new/better TypeScript version
