### ISSUE TITLE
Editor view-line has width of 100% causing problems

### ISSUE THREAD

**Issue by renegadeandy** [microsoft/monaco-editor#1038]
In version 0.14.3 of monaco editor, I see the following when I load an any code into the editor:

![image](https://user-images.githubusercontent.com/831013/44782901-a360e500-ab80-11e8-9d55-9d4ca2e87952.png)

I have to add in this line to my css in order to get the lines to correctly start at the beginning of the line:

```
.view-line{
  width:auto !important;
}

```

Does anybody else have this? Is there a fix?

**Comment by alexandrudima** [comment]
@renegadeandy I believe you might have some CSS on your page which interacts with the editor's CSS.

**Comment by renegadeandy** [comment]
I would agree, yet it seems that it is the editor.main.css which has the rule:

![image](https://user-images.githubusercontent.com/831013/44793680-b71b4400-ab9e-11e8-9fbe-b06a0185a93a.png)

**Comment by alexandrudima** [comment]
That rule is correct. There must be **some other** CSS on your page that changes this or **some other** parent element's styling.

I think it is a coincidence that your removal of `width: 100%` helps in any way.

**Comment by xkisu** [comment]
I'm having the same issue, the 100% width on `.view-line` is causing the line contents to be displayed in the horizontal center of the line. Removing/setting the `width` to `auto` for `.view-line` fixes this.

![image](https://user-images.githubusercontent.com/28452108/57555024-e8e8cb00-7327-11e9-9154-480cf5805209.png)

This is in a brand new web app with almost no styling beyond colors, I tried removing all styles from the webapp and the problem persisted so I'm pretty sure it's not a parent element's styling causing it.
