### ISSUE TITLE
The overriden of editorService does not work when monaco-editor upgrate to V0.14.3

### ISSUE THREAD

**Issue by xutao1989103** [microsoft/monaco-editor#1042]
After I upgraded the monaco-editor version from 0.13.0 to 0.14.1, the override method of the editorService will no longer take effect:

`this.editor = context.monaco.editor.create(`
`this.containerElement,`
`        {value, language,},`
`        { editorService: this.getEditorService(handleOpenDefinition)}`
`      );`
`function getEditorService(callback) {`
`//open new model`
`}`
monaco-editor version: 0.14.3
Browser:chrome
OS: MAC
Steps or JS usage snippet reproducing the issue:

@alexandrudima 

thanks...

**Comment by alexandrudima** [comment]
See https://github.com/Microsoft/monaco-editor/issues/852#issuecomment-414984304
