### ISSUE TITLE
Crash on invoking function signature.

### ISSUE THREAD

**Issue by hifall** [Microsoft/monaco-editor#1045]
monaco-editor version: 0.14.3
Browser: Chrome 67.0.3396.99
OS: macOS 10.12

Okay, it seems like a VS Code issue from where the crash happens, but since I am using Monaco, I am filing it here.

I am using Monaco editor connected with a backend language server. When trying to invoke displaying the signature of a function, I am seeing a crash with the following call stack in the browser console:

```
errors.js:58 Uncaught Error: Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
    at ParameterHintsWidget.render (parameterHintsWidget.js:272)
    at parameterHintsWidget.js:182
    at Emitter.fire (event.js:105)
    at parameterHintsWidget.js:104
    at ParameterHintsWidget.render (parameterHintsWidget.js:272)
    at parameterHintsWidget.js:182
    at Emitter.fire (event.js:105)
    at parameterHintsWidget.js:104
    at errors.js:58
```

The Monaco client sends a request like this:

`{"jsonrpc":"2.0","id":6,"method":"textDocument/signatureHelp","params":{"textDocument":{"uri":"/home/model.r"},"position":{"line":36,"character":6}}}`

And the language server responds with:

`{"jsonrpc":"2.0","id":6,"result":{"signatures":[{"label":"paste(..., sep = \" \", collapse = NULL)"}],"activeSignature":0}}`

This happens because of the following line inside ParameterHintsWidget's render function:

`var hasParameters = signature.parameters.length > 0;`

This line assumes that `parameters` field always present inside `signature`, while in fact parameters is absent from the server response above. However, the LSP specification says SignatureInformation's parameters is optional. Therefore, the assumption doesn't seem correct.

**Comment by rcjsuen** [comment]
@hifall How are you hooking up the language server to your Monaco editor? Are you using TypeFox's `monaco-languageclient`?

**Comment by hifall** [comment]
@rcjsuen, yes.

**Comment by rcjsuen** [comment]
https://github.com/Microsoft/monaco-editor/blob/935bd5275a4e9170db586c514051936c0749237b/monaco.d.ts#L4763-L4783

@hifall As the API does not state that it is optional, I believe this is a bug in `monaco-languageclient`. See TypeFox/monaco-languageclient#112.

Of course, if the VS Code team wants to loosen up their API requirement, they are welcome to do so. Irregardless of their decision, we should fix `monaco-languageclient` in the meantime...

**Comment by hifall** [comment]
The official spec says it's optional: [LSP spec](https://microsoft.github.io/language-server-protocol/specification), search for `SignatureInformation`.

**Comment by rcjsuen** [comment]
@hifall That's the LSP specification and **not** the Monaco/VS Code API. They may look like they are 1-to-1 but they do not have to be 1-to-1.

It's up to bridges like the [TypeFox/monaco-languageclient](https://github.com/TypeFox/monaco-languageclient/) and [Microsoft/vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node) projects to alter LSP information into a way that is consumable by the client editor.
