### ISSUE TITLE
Monaco editor encodes URL when doing Ctrl + click to follow link

### ISSUE THREAD

**Issue by nikhilexe** [Microsoft/monaco-editor#1048]
See this code pen link https://codepen.io/nikhilexe/pen/RYwveN 

If you ctrl + click on the URL, browser will open with this URL https://abc.com/id//def/ghi basically it encodes %2F to /

If you paste this URL directly into the browser https://abc.com/id/%2Fdef%2Fghi nothing changes.

**Comment by Ajay-MS** [comment]
+1  
We are seeing a similar issue.

**Comment by jrieken** [comment]
duplicate of https://github.com/Microsoft/vscode/issues/25852
