### ISSUE TITLE
Escape key should hide/turn off widgets, and features in Chrome

### ISSUE THREAD

**Issue by mkapiczy** [Microsoft/monaco-editor#1049]
monaco-editor version: 0.14.3
Browser: Google Chrome Version 68.0.3440.106 
OS: macOS HighSierra 10.13.6 

Steps or JS usage snippet reproducing the issue:

I would expect `Esc` key to work as a cancel option on general basis (exactly as it is the case with Command Pallete). Fo instance, when find/replace widget is open and `Esc` is pressed the widget should be hidden. The same for other widgets.

The same thing is valid for for example multicursor. When multicursor option is on, and `Esc` is pressed the multicursor option should be off.

Instead, pressing `Esc` results in lost focus, but the additional widgets/options are still visible and on.
I though about just implementing a listener for `Esc` key event, but closing manually every possible widget/option seems like a wrong way to go.

Is this expected bahvior, and if so any recommendations how I could address my issue?

Thanks!

**Comment by alexandrudima** [comment]
@mkapiczy 

> Instead, pressing `Esc` results in lost focus, but the additional widgets/options are still visible and on.

That is not true AFAIK. Pressing `Esc` does not result in focus loss, but it results in the widgets closing, in the multicursor getting canceled, in the selection getting canceled, etc. You can try yourself at https://microsoft.github.io/monaco-editor/

**Comment by mkapiczy** [comment]
https://youtu.be/XqbUqhyuUag

Here you can see what I mean (I hope you can :) ). The moment when a mouse pointer disappears is the moment I press Esc.

**Comment by mkapiczy** [comment]
I was recording on monaco playground Hello-world example and I guess I found the source of the problem.

The behaviour which you described works fine in Firefox, but not in Google Chrome.

Try going to the playground in Chrome --> 
[](https://microsoft.github.io/monaco-editor/playground.html)

,and triggering Find Widget. ESC cancels it in Firefox but in Google Chrome it is still there. It's the same case for multi-cursor, and I assume other widgets/features.

**Comment by alexandrudima** [comment]
@mkapiczy I cannot reproduce what you are describing. I have now tested on Chrome on mac and on Chrome on Windows

When I press Escape, the find widget closes. I try to have the focus both in the find widget and in the editor when I press Escape and always the find widget closes:
![1049](https://user-images.githubusercontent.com/5047891/45479029-a98cbf00-b745-11e8-9fea-0a4484ed19be.gif)

Can you reproduce at a friend's computer? What is the difference between our setups?

**Comment by mkapiczy** [comment]
I've finally found out that it's a vimium plugin causing the issues. There is even related issue in their repo, though they are not really addressing the problem -> philc/vimium#499

Thanks for your help, and sorry for the problem. I'm closing the issue.
