### ISSUE TITLE
word or character position

### ISSUE THREAD

**Issue by reddys11** [microsoft/monaco-editor#1055]
How to get a character or word position in a line. is there any particular method to get position of a word or character. kindly provide an example.

**Comment by rcjsuen** [comment]
Try this API function maybe?

https://github.com/Microsoft/monaco-editor/blob/3a22d5db6d10b367fd5e2f06b39d02887d4f9baf/monaco.d.ts#L1627-L1633

**Comment by reddys11** [comment]
Thanks for the response. I am aware of this but this api will cursor positon word.

    Ex: i need to get double quotes position in the below string how could i.
  Hi sandy "how are you" today.
  I need the word present between double quotes,how can i get it. Kindly provide example for this scenario.

**Comment by rcjsuen** [comment]
@reddys11 You need to parse the document yourself to calculate such offsets.

**Comment by reddys11** [comment]
thanks for the response..
