### ISSUE TITLE
Read only particular conditions

### ISSUE THREAD

**Issue by reddys11** [microsoft/monaco-editor#1056]
Can we make particular conditions(pre defined conditions are there for my language) read only in editor. Is it possible. If yes can you please provide an example.

**Comment by alexandrudima** [comment]
@reddys11 What do you mean? Can you explain more clearly?

**Comment by reddys11** [comment]
i want few lines to be read only in my editor,is it possible?

**Comment by alexandrudima** [comment]
Let's track in #953
