### ISSUE TITLE
Two finger scrolling in Edge (Surfacebook PTP) does not follow system settings for direction

### ISSUE THREAD

**Issue by jayspadie** [microsoft/monaco-editor#1057]
monaco-editor version: 0.14.3
Browser: Edge
OS: Windows 10

Using a SurfaceBook and Precision Touchpad (PTP) with the Edge browser, two finger scrolling works as expected in Monaco when using the default system Trackpad Scrolling direction setting of "Down motion scrolls up".  However, changing this to "Down motion scrolls down" has no effect in Monaco on Edge.  Monaco continues to scroll up on a downward motion while any other scrollable region on the web page (and the page itself) scrolls down.  Monaco correctly scrolls in the specified direction in all cases when using Chrome.

**Default Trackpad Setting:**  Monaco works like any other page scrolling.
![image](https://user-images.githubusercontent.com/5246869/45220122-24a03200-b27b-11e8-94fb-a836554071c2.png)

**Switched Trackpad Setting:**  Monaco scrolling behavior in Edge remains unchanged from above.  It adjusts correctly in Chrome.
![image](https://user-images.githubusercontent.com/5246869/45220132-2d910380-b27b-11e8-9454-ce077f692861.png)

**Comment by alexdima** [comment]
Closing, as Microsoft Edge Legacy has reached end of support on March 9, 2021. See [the end of support for Microsoft Edge Legacy announcement](https://docs.microsoft.com/en-us/lifecycle/announcements/edge-legacy-eos-details)
