### ISSUE TITLE
New tokenization breaks bracketmatching

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/monaco-editor#1060]
The new tokenization API seem to break the bracket matching feature.

Here's the issue with a reproducible example: https://github.com/theia-ide/theia/issues/2835

**Comment by alexandrudima** [comment]
I cannot reproduce in https://microsoft.github.io/monaco-editor/

Can you please distill a reproducible case?

**Comment by svenefftinge** [comment]
Oh, I see Monarch is using `tokenize2`, too. 
Ok, then it might be something in our code. Thank you, I will verify and close.

**Comment by svenefftinge** [comment]
Ok, seems to be in monaco-textmate. The grammars and therefore the tokens don't have a proper languageid.
