### ISSUE TITLE
YAML syntax highlighting and red escaped characters

### ISSUE THREAD

**Issue by jayspadie** [microsoft/monaco-editor#1064]
monaco-editor version: 0.13.1
Browser:  Chrome, any
OS:  Windows 10

YAML language syntax highlighting applies a red color to all charaters preceded by '\\'.  Presumably, this is to indicate any escaped character (valid or invalid?) but it's getting applied for all cases in both double quotes (where escaping should apply) and single quotes (where escaping should not apply).  This is particularly noticeable in single-quoted file paths where escaping should not apply with the '\\' path separator. 

**Comparing Monaco to VS Code:**

**VS Code correctly** applies different colors to valid (normal dark red string color) and invalid (bright red) only to escaped characters within double quotes:
![image](https://user-images.githubusercontent.com/5246869/45501828-553b0c80-b750-11e8-8bf4-6f08428027d6.png)

**Monaco incorrectly** highlights every character following '\\' whether in single or double quotes:
![image](https://user-images.githubusercontent.com/5246869/45501845-6126ce80-b750-11e8-8f79-3141e3a32229.png)

**Comment by alexandrudima** [comment]
This would be a good opportunity for a first pull request.

The Monarch tokenizer is implemented here -- https://github.com/Microsoft/monaco-languages/blob/0aea831f058968319b8084421ce948e43fc1e969/src/yaml/yaml.ts#L159-L170 --

**Comment by arshadkazmi42** [comment]
@alexandrudima is this issue still available? I would like to work on this

**Comment by arshadkazmi42** [comment]
How to run it in my local machine to check the editor?

**Comment by rsemenov** [comment]
@arshadkazmi42 , to test your changes you probably need to run Monaco editor as AMD or ESM version as described [here](https://github.com/Microsoft/monaco-editor#documentation) with your updated version of monaco-languages package that you can generate and install locally without publishing. Let me know if you still working on this issue else I will pick it up.

**Comment by arshadkazmi42** [comment]
@rsemenov Thank you for the documentation. I will be working on it.

**Comment by arshadkazmi42** [comment]
@rsemenov I am a bit busy for few days. You can take it up if you want.

**Comment by nalinbhardwaj** [comment]
@rsemenov : hi, are you working on this issue? If not, I’d like to fix this.

**Comment by rsemenov** [comment]
@nalinbhardwaj, it is in my queue, but you can pick it up.

**Comment by grzegorz-wcislo** [comment]
I have submitted a [pull request](https://github.com/Microsoft/monaco-languages/pull/47) :)

**Comment by nalinbhardwaj** [comment]
@grzegorz-wcislo : I think you missed on fixing the part of the issue where in double quoted strings characters like "/m" are highlighted as invalid as well(the comment has a screenshot with an example of it)?

@rsemenov / @alexandrudima : since this issue was already fixed, I'd love to help contribute to the project if you have any other good starter issues in mind. Let me know of any. :)

**Comment by grzegorz-wcislo** [comment]
@nalinbhardwaj Incorrect excapes are recognized as such, but I don't know where is the code resonsible for styling. If you know where it is you can fix it :smile: or message me

**Comment by euler16** [comment]
has the issue been fixed?

**Comment by rsemenov** [comment]
the reason why invalid escape characters have the same foreground color as valid ones is that neither 'string.escape' nor 'string.escape.invalid' are defined in default vscode themes ([themes.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/standalone/common/themes.ts)) . And in both cases token theme parser returns default color. With proper schema these will be solved. So I think this issue can be solved now. @grzegorz-wcislo, thanks for the fix.

**Comment by rsemenov** [comment]
@alexandrudima , is it worth adding 'string.escape' and 'string.escape.invalid' to the default themes? Looks like multiple languages that use these tokens can benefit from it.

**Comment by alexdima** [comment]
OCR text content:

```yaml
variables:
  escDoubleQuotes: "path\to\my\solution.sln \t \n \a \x \c \\"
  escSingleQuotes: "path\to\my\solution.sln \t \n \a \x \c \\"

```

**Comment by alexdima** [comment]
This has actually been fixed in the meantime:

![image](https://user-images.githubusercontent.com/5047891/70921671-0d76f500-2025-11ea-8a2f-232dc86e1203.png)
