### ISSUE TITLE
content overflows into scrollbar

### ISSUE THREAD

**Issue by starpit** [microsoft/monaco-editor#1067]
monaco-editor version: 0.14.3
Browser: firefox, safari, chrome
OS:  macOS
Steps or JS usage snippet reproducing the issue:

note in this screenshot how, on narrower windows, the text content of the pane overflows into the scrollbar. the `\n}` suffix on line 7, and the `,` on line 6.

is this intentional? it seems buggy to me. the Playground shows this; the screenshot is from a straight load of the monaco editor playground, taken with a narrower window.

vscode also seems to have this issue --- though you have to disable minimaps; with minimaps enabled, the bug seems to be masked.

![screen shot 2018-09-17 at 14 27 03](https://user-images.githubusercontent.com/4741620/45642359-f514d500-ba85-11e8-9b79-982aae17e45a.png)

**Comment by alexandrudima** [comment]
This is intentional
