### ISSUE TITLE
Allow top-level return statements in JavaScript

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#1069]
Hi,

we would like to use the monaco-editor in a scripting environment where you only write the body of a function without having to specify/worry about the function signature itself. It is added on the server side before the code is executed. E.g.
```js
let result = 0;
// compute result
return result;
```

However, top-level return statements are reported as a syntax error (because they normally are). Is there a way to suppress this specific diagnostic?
```
A 'return' statement can only be used within a function body.
```

Being able to do this would make a lot of sense in scripting environments that use the monaco-editor, IMHO.

Thanks!

~P.S.: I found #45 as a possible workaround, though I haven't had the time to try that, yet. (And it uses non-API methods)~

**Comment by spahnke** [comment]
Since the methods mentioned in #45 seem to be gone, there is no obvious workaround for this. Is this the right place to ask, or is it rather a feature request for the TypeScript language server to have such an option?

**Comment by khmylov** [comment]
👍, this would be extremely useful for various embedded scripting scenarios. 
The only option I see for now is to listen to changes of editor's error markers and monkey-patch them to remove the ones we don't want to see :)
