### ISSUE TITLE
formatOnType option did not work when I used it  in my angular component

### ISSUE THREAD

**Issue by courage007** [Microsoft/monaco-editor#1078]
Context: I am referencing the monaco editor in Angular 5. However, I find 'formatOnType' does not work when using my angular-monaco-editor component. [ref angular-monaco-editor component](https://github.com/courage007/Angular-Monaco-Editor) ,[demo using the formatOnType option](https://github.com/courage007/Angular-Monaco-Editor/tree/formatOnType)
monaco-editor version: 0.14.3
Browser: Chrome
OS: Window 10
Steps reproducing the issue:
1. Create an Angular CLI Project;  
2. Using the angular-monaco-editor component in the Angular CLI Project;  
3. Set 'formatOnType' option in the angular CLI Project.  
PS: When running the angular cli project, "Format Document" shortcut can work.

**Comment by rcjsuen** [comment]
@courage007 I tried searching for `formatOnType` in your project and I couldn't find any trace of it. Am I looking at the wrong thing?

**Comment by courage007** [comment]
@rcjsuen So Sry about that. Becasue I still didn't find a graceful way to show demo in my github reposity, I did not update code into my master branch, just tested it in my local branch.   
I create a new branch to using formatOnType option in this [branch](https://github.com/courage007/Angular-Monaco-Editor/tree/formatOnType), and updated the issue i created. You can trace my option setting on this [page](https://github.com/courage007/Angular-Monaco-Editor/blob/formatOnType/src/app/app.component.ts).

**Comment by courage007** [comment]
Recently, I trid to use **editor.getAction('editor.action.formatDocument').run().then(() => console.log('format document done.'));** to format editor text according #32. It can‘t work when initilizing, but work after initilizing.

**Comment by courage007** [comment]
At last, I successfully format editor text when initilizing using async. Here is my source code: 
`    setTimeout(() => {
      this.Editor.trigger('anyString', 'editor.action.formatDocument');
    }, 200);
`
