### ISSUE TITLE
Doesn't Work With Parcel 

### ISSUE THREAD

**Issue by vedantroy** [Microsoft/monaco-editor#1080]
Monaco doesn't seem to work with parcel. I downloaded the browser-esm-parcel example from https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-parcel and ran the commands in index.html

However, I get the error.

`Error: ENOENT: no such file or directory, open '/home/username/Downloads/browser-esm-parcel/node_modules/monaco-editor/esm/vs/editor/editor.worker'`

The problem is stemming from the following lines of code in index.js:

```
self.MonacoEnvironment = {
	getWorker: function (moduleId, label) {
		if (label === 'json') {
			return new Worker('../node_modules/monaco-editor/esm/vs/language/json/json.worker')
		}
		if (label === 'css') {
			return new Worker('../node_modules/monaco-editor/esm/vs/language/css/css.worker')
		}
		if (label === 'html') {
			return new Worker('../node_modules/monaco-editor/esm/vs/language/html/html.worker')
		}
		if (label === 'typescript' || label === 'javascript') {
			return new Worker('../node_modules/monaco-editor/esm/vs/language/typescript/ts.worker')
		}
		return new Worker('../node_modules/monaco-editor/esm/vs/editor/editor.worker')
	}
}

```

**Comment by rebornix** [comment]
I already updated the sample to get rid of the error, please try the latest version.
