### ISSUE TITLE
Support showing the native context menu (with copy/paste)

### ISSUE THREAD

**Issue by tombenezra** [microsoft/monaco-editor#1084]
monaco-editor version: 0.12.0
Browser: Google Chrome
OS: macOS
Steps or JS usage snippet reproducing the issue:
When disabling context menu (`contextmenu: false`), highlighting a text and right clicking it will open context menu with missing actions (Cut/Paste/Copy/Select All)

![context](https://user-images.githubusercontent.com/42377243/46410211-b0916680-c720-11e8-8005-4086d88dd01a.png)

**Comment by kokris92** [comment]
Hi I would like to take a look into this, could you assign this to me?

**Comment by kokris92** [comment]
So just to clarify the missing actions (Cut/Paste/Copy/Select All), would still be available when (contextmenu: false)--is that correct?

**Comment by tombenezra** [comment]
When setting `contextmenu: false` text actions (copy, paste, etc..) are **not** available at all (even when highlighting a text)

this screenshot clarifies the issue better (reproduced on playground):
![screen shot 2018-10-08 at 10 52 12](https://user-images.githubusercontent.com/42377243/46597320-56a9eb80-cae8-11e8-8264-929f45ba1550.png)

**Comment by neptunian** [comment]
I don't want to use the custom Monaco menu so i set contextmenu: false.  But i want the native browser menu to still be able to copy paste.  Is this possible?

**Comment by alexandrudima** [comment]
Unfortunately not. The editor is not a native `<input>` or `<textarea>`, so the browsers, when you right click, do not offer any actions typical for those inputs.

**Comment by Menci** [comment]
But [ACE](https://ace.c9.io/) supports this.

**Comment by jeremyrsmith** [comment]
Setting `contenteditable="true"` on the `<div class="monaco-editor">` seems to bring copy and paste back to the native context menu (Mac Chrome) while surprisingly not harming everything else.

**Comment by elslooo** [comment]
> Setting `contenteditable="true"` on the `<div class="monaco-editor">` seems to bring copy and paste back to the native context menu (Mac Chrome) while surprisingly not harming everything else.

Unfortunately in WebKit / Safari, this does allow editing the content of tooltips too (e.g. error messages, hover tooltips).

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
