### ISSUE TITLE
Avoid empty lines turning into trailing whitespace lines on snippet insertion

### ISSUE THREAD

**Issue by gins3000** [microsoft/monaco-editor#1085]
monaco-editor version: 0.14.3

Try out this example in Monaco Playground:

```javascript
monaco.languages.registerCompletionItemProvider('plaintext', {
    provideCompletionItems: function () {
        return [{
            label: "threelines",
            kind: monaco.languages.CompletionItemKind.Snippet,
            documentation: "Three lines separated by empty lines",
            insertText: {
                value: "Snippet line 1: Next line should be empty, but contains the same indent as this line\n\nSnippet line 2: I want to retain the whitespace in the next line, because it is not really empty\n$0\nSnippet line 3"
            }
        }];
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "After this line, create some whitespace and insert the snippet 'threelines'\n  ",
    language: "plaintext"
});
```

If a snippet is inserted not in the beginning of a line, but following some whitespace, the rest of the snippet's lines will of course be indented with the same whitespace. So far so good.

However, if the snippet itself contains empty lines like in the example above, they too get prefixed, producing lines with trailing whitespace.

**Why this is not optimal:**
When I have a linter rule like "no trailing whitespace", I will immediately get annoying squiggly lines, and need to press auto-format to get rid of them. (I admit that's not the most terrible problem in the world, but with this suggestion it's a repeated keystroke that could be avoided.)

**Why just 'auto-format after snippet insertion' wouldn't be enough:**
In the example above, there is also a seemingly empty line, but it contains a tabstop (`$0`). So the whitespace SHOULD be inserted here, even though the line initially seems empty. Auto-format would destroy this tabstop.

**I wonder if it is possible to make this work, e.g. with one of these suggestions:**
a) based on the model's `trimAutoWhitespace` setting
b) provided as an option for the `CompletionItem`
c) always/by default
d) a combination of the above (e.g. default < `trimAutoWhitespace` < `CompletionItem` option)

I would be glad to provide more information/use cases if necessary. If I get opinions on the above suggestions, I could also look into submitting a pull request myself.

**Comment by rcjsuen** [comment]
See Microsoft/language-server-protocol#83 for what the future may hold for this auto-indentation feature.

**Comment by alexdima** [comment]
Indeed, I suggest to simply track in https://github.com/microsoft/language-server-protocol/issues/83

This is behavior that affects VS Code and LSP and is not Monaco Editor specific.
