### ISSUE TITLE
Managing Additional Type Script Definitions and source files.

### ISSUE THREAD

**Issue by rufio620** [Microsoft/monaco-editor#109]
Is there a way to add/update/remove additional typescript source file and definitions to the language service? Based on my initial review of the api it looks like there is a way to add additional library files via monaco.languages.typescript.typescriptDefaults.

E.g.
```javascript
monaco.languages.typescript.typescriptDefaults
                .addExtraLib("declare var externalLibVar: any;", "testlib.d.ts");
```

However this does not appear to allow adding additional source files (.ts) or updates / deletions to the existing library files. Is there a mechanism to manage the typescript project structure? If so can you please point me to some documentation on how to use this mechanism? Thanks.

**Comment by jrieken** [comment]
The call returns an `Disposable` type which you can use to unload the file
