### ISSUE TITLE
Autocomplete a suggested item by pressing various keys

### ISSUE THREAD

**Issue by mrWermut** [Microsoft/monaco-editor#1093]
Hello. Is there any way to make Monaco Editor complete a selected suggestion by pressing something other than enter or tab key?  

I'm trying to make auto completion works just the same way as in the Visual Studio 2017. For example if I print  "str" and then print "[", it will complete the suggestions as "string[]". Same for "(" and many other symbols. 

But as far as I can see, Monaco will autcomplete only with "tab" or "enter" keys.

**Comment by rcjsuen** [comment]
It is possible to define other characters via the `commitCharacters` field.

```JavaScript
function createProposals() {
    return [
        {
            label: 'string[]',
            insertText: 'string',
            commitCharacters: [ '[' ]
        }
    ];
}


monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        return createProposals();
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "json"
});
```

**Comment by mrWermut** [comment]
Many thanks, good sire!
