### ISSUE TITLE
Extending TypeScript support to allow for new syntax

### ISSUE THREAD

**Issue by sdegutis** [Microsoft/monaco-editor#1098]
monaco-editor version: Latest
Browser: Safari Latest
OS: macOS Latest
Steps or JS usage snippet reproducing the issue:

https://stackoverflow.com/q/52672353/3590058

Is it possible to accomplish what that StackOverflow question is aiming for? I'd like to add new syntax to Monaco's TypeScript support, and not just the syntax highlighting, but the linting ("diagnostics"), auto-completion ("suggestions"), I'd like to get *all* the IDE features of Monaco to support this new syntax, not just syntax highlighting. Is such a thing even possible?

**Comment by alexandrudima** [comment]
Architecturally, you can do the following:
* use `monaco-editor-core` directly
* define a new language to the editor
* fork monaco-typescript and change it to work with your newly defined langauge id. Then, modify the TS language host code to not pass the original models to TypeScript, but first run a preprocess which strips your custom language out of the text, and then only passes on valid TypeScript to the TS compiler. One idea is to replace each character that you remove with a space. This will leave all the position/offset computation work without any effort on your side.

Good luck!

**Comment by sdegutis** [comment]
Thanks @alexandrudima, this is very informative and helpful!
