### ISSUE TITLE
Perl syntax highlighting doesn't recognize regex delimiters other than /regex/

### ISSUE THREAD

**Issue by goober99** [Microsoft/monaco-editor#1101]
monaco-editor version: 0.14.3
Browser: Chromium 51
OS: Ubuntu 15.10
Steps or JS usage snippet reproducing the issue:

The Perl syntax highlighter doesn't recognize regex delimiters other than /regex/ for regular expressions. Perl allows the use of alternative delimiters such as m!regex!. This throws off the highlighting when using a character such an apostrophe (like m!can't!). The syntax highlighter thinks the apostrophe is the beginning of a single quote and highlights everything that comes after it as a string:

![monaco](https://user-images.githubusercontent.com/553660/46749456-5ee66000-cc7b-11e8-9cdf-c567611785e8.png)

**Comment by goober99** [comment]
I have submitted a [pull request](https://github.com/Microsoft/monaco-languages/pull/50).

**Comment by alexandrudima** [comment]
Thank you, fixed via https://github.com/Microsoft/monaco-languages/pull/50
