### ISSUE TITLE
How to add an IEditorContribution to monaco editor?

### ISSUE THREAD

**Issue by lidermanrony** [Microsoft/monaco-editor#1106]
Tried to ask on [stackoverflow ](https://stackoverflow.com/questions/46700245/how-to-add-an-ieditorcontribution-to-monaco-editor )but no answer...

I wrote a class that implements a monaco.editor.IEditorContribution. how can i register monaco to use it?
Currently i'm creating and disposing of it explicitly after creating the editor which isn't optimal (for example - i need to worry about disposing it).

**Comment by alexandrudima** [comment]
This is not part of the API... The point of those contributions is that the editor instantiates them whenever an editor gets instantiated... Since you are in charge of instantiating editors, you can manually manage and instantiate your own contributions.
