### ISSUE TITLE
markdown bug

### ISSUE THREAD

**Issue by czb** [Microsoft/monaco-editor#1107]
monaco-editor version: 0.14.2
Browser: Chrome
OS:  Win10 x60
Steps or JS usage snippet reproducing the issue:

Execute:

```
monaco.editor.create(document.getElementById("container"), {
	value: "{{{test}}}",
	language: "markdown"
});
```

on this webpage:

https://microsoft.github.io/monaco-editor/playground.html

The coloring is broken.

Change `vs/basic-languages/markdown/markdown.js`:

```
[/\{[^}]+\}/, 'string.target'],
```

into this:

```
[/\{+[^}]+\}+/, 'string.target'],
```

The coloring is fixed.

**Comment by AasthaGupta** [comment]
@alexandrudima I'd like to work on this. This seems like a change in the monaco-language repository (https://github.com/Microsoft/monaco-languages/blob/master/src/markdown/markdown.ts#L134)
<img width="937" alt="screen shot 2018-10-13 at 9 33 23 pm" src="https://user-images.githubusercontent.com/15193262/46907420-abf25c80-cf2f-11e8-853e-7cf43a1093bc.png">
