### ISSUE TITLE
False positive "red code" when code models are created in the "wrong" order

### ISSUE THREAD

**Issue by ulrichb** [microsoft/monaco-editor#1109]
When creating multiple TypeScript code models (using `monaco.editor.createModel(...)`) in the "wrong" order in means of dependencies (e.g. adding `a.ts` then `b.ts` and `a.ts` imports `b.ts`), then Monaco editor shows red squiggles in `a.ts`.

I assume this happens because the TS worker process immediately analyzes `a.ts` without having `b.ts`.

=> Is there a possibility to create models in a "transaction" (at once)?

=> Or (plan B): Is there a possibility trigger re-analyzing all code models (after adding the last one)?

**Comment by alexandrudima** [comment]
You can trick it to revalidate by changing the TS options. This is what I noticed:

https://github.com/Microsoft/monaco-typescript/blob/609b93eb011be5b9840d988249d4fbad012130ed/src/languageFeatures.ts#L139-L145

**Comment by ulrichb** [comment]
Thanks for sharing this workaround.
