### ISSUE TITLE
MAS 1.4.3: Elements must have sufficient color contrast (.mtk4:nth-child(25))

### ISSUE THREAD

**Issue by vaibhav1192** [Microsoft/monaco-editor#1118]
monaco-editor version: 0.X.Y
Browser: Chrome
OS: Windows 10
Steps or JS usage snippet reproducing the issue:
As per the recommendations here https://dequeuniversity.com/rules/axe/3.1/color-contrast, All text elements must have sufficient contrast between text in the foreground and background colors behind it. 

![image](https://user-images.githubusercontent.com/13259537/47007760-9448ed00-d156-11e8-92e3-e2535efe92aa.png)

**Comment by alexandrudima** [comment]
We are shipping with a High Contrast Theme

Please see https://github.com/Microsoft/monaco-editor/wiki/Accessibility-Guide-for-Integrators
