### ISSUE TITLE
Reloading d.ts definitions at runtime on a running Monaco instance

### ISSUE THREAD

**Issue by Zlatkovsky** [Microsoft/monaco-editor#112]
I am using the Monaco Editor to embed a typescript editor in a web browser.  It works great, but I’d like to be able to change out the referenced TypeScript definition types at runtime.  So that instead of statically specifying them as:

    monaco.languages.typescript.typescriptDefaults.addExtraLib(responses[0].text(), 'jquery.d.ts');
    monaco.languages.typescript.typescriptDefaults.addExtraLib(responses[1].text(), 'core-js.d.ts');

which only seems to work when added BEFORE `monaco.editor.create(...)`, I’d like to be able to change them out at runtime.

Two (rather imperfect) workarounds I can think of:

- Cache the libraries that I want into localStorage, and force a page reload (or at least an editor-re-creation).  But that seems super-heavy-weight, esp. the former.  And it means it would only work when I have all the libraries already assembled, as I wouldn’t want to force multiple refreshes, and so I can’t add them iteratively.

- Skip the d.ts extra-library-adding, and instead paste them into the bottom of the text in the editor.  This certainly works, except the snippets suddenly become 1000s of lines long, making scrolling difficult (and making the thing feel really heavy-weight, and sluggish)... so that’s not that great, either.

Is there some more subtle and tailored-for-the-job API that I’m missing?...

**Comment by Zlatkovsky** [comment]
... And on a very related note, how can I fully clear the extraLibs when re-initializing the editor (i.e., to remove "stale" items that I no longer want).  Essentially, I want to be able to 100% control what the current extraLibs are for the editor.

**Comment by jrieken** [comment]
> which only seems to work when added BEFORE monaco.editor.create(...), I’d like to be able to change them out at runtime.

We have fixed that

**Comment by Zlatkovsky** [comment]
@jrieken, could you elaborate on the fix?  I.e., what is the new API by which I can change the d.ts?
Also, where/when could I get this build?  I am currently pulling it from https://www.npmjs.com/package/monaco-editor

**Comment by jrieken** [comment]
We released a new version of the editor very recently. The API is still the same (`addExtraLib` returns `IDisposable` (**!**)) but a bug preventing it  was fixed.
