### ISSUE TITLE
outdentCurrentLine isn't implemented

### ISSUE THREAD

**Issue by reznikmm** [Microsoft/monaco-editor#1120]
It seems outdentCurrentLine not used anywhere in the code and so it doesn't work as described in documentation:
```
Defined in monaco.d.ts:4678
Describe whether to outdent current line.
```

monaco-editor version: 0.14.3
Steps or JS usage snippet reproducing the issue:

I've tried this configuration without success
```
                    {
                      beforeText: /^\s*(?:begin|private)/,
                      afterText: /\s*$/,
                      action:{
                        indentAction: monaco.languages.IndentAction.IndentOutdent,
                        outdentCurrentLine: true, appendText: "2"
                      }
                    },
```

**Comment by alexandrudima** [comment]
:+1: We should remove it from the `EnterAction`

**Comment by reznikmm** [comment]
Is it difficult to implement it instead of delete? I find it very useful for Ada formatting.

If you provide some direction I could try to implement it.

**Comment by alexandrudima** [comment]
I actually don't know of the top of my head why we had it in there. ping @rebornix maybe you remember, did we use to support that, or was it just added by accident ?

**Comment by reznikmm** [comment]
Can you suggest how to implement auto indentation without `IndentOutdent` for such Ada constructs:
```ada
package Pkg is
   A : Integer;  --  Here indent is 3
private  --  indent 0
   B : Integer;   --  Here indent is 3 again
end Pkg;

procedure Proc is
   A : Integer;  --  Here indent is 3
begin  --  indent 0
   null;   --  Here indent is 3 again
end Proc;
```

Ada has a lot of such constructs. I would define `IndentOutdent` for `begin` and `private` and this should work automatically.

**Comment by alexandrudima** [comment]
@reznikmm I would start with using `indentationRules` -- https://github.com/Microsoft/vscode/blob/2a891803f19ddd80affce9eecf7b293c913d1a61/src/vs/editor/common/modes/languageConfiguration.ts#L84:L105 and enabling the `autoIndent` option.

But @rebornix is the real expert on this area.
