### ISSUE TITLE
Typescript - Properties that start with numbers.

### ISSUE THREAD

**Issue by seanbotha123** [microsoft/monaco-editor#1137]
Hi

In VS Code we have the ability to create properties that start with numbers, and this gives intellisense as below:

![image](https://user-images.githubusercontent.com/5496698/47349430-e5effb00-d6b3-11e8-9e36-e08b13e78065.png)

but on monaco-editor the same scenario does not work:
![image](https://user-images.githubusercontent.com/5496698/47349544-22bbf200-d6b4-11e8-8a74-39bab2ace87e.png)

Code:

```ts
class Test {
	'22': string = 'hello';
	prop = 'hello';
}

var item = new Test();
item.
```
Is there any way to get the same functionality in monaco-editor?

Thanks in advance!
Sean

monaco-editor version: 0.14.3
Browser: Chrome
OS: Ubuntu / Windows
Steps or JS usage snippet reproducing the issue:

**Comment by seanbotha123** [comment]
Hi@jrieken, any feedback here?

**Comment by jrieken** [comment]
requires a new TypeScript version
