### ISSUE TITLE
Request: cut a new release

### ISSUE THREAD

**Issue by roperzh** [Microsoft/monaco-editor#1139]
Hello!

Thanks for sharing this awesome library 🤗 

I wanted to ask you if it's possible to cut a new release with all the new goodness and fixes for `monaco-editor-core` that are already in `master` of the vscode repo.

My request is particularly motivated from the need to include https://github.com/Microsoft/vscode/pull/57617 in `monaco-editor` since I haven't found a workaround to prevent the error from the external API.

Thanks!

**Comment by trevorade** [comment]
+1

@alexandrudima , can you see about this?

In particular, I need a release which includes:
https://github.com/Microsoft/vscode-loader/pull/15
