### ISSUE TITLE
provideSignatureHelp return type assumes success

### ISSUE THREAD

**Issue by AviVahl** [Microsoft/monaco-editor#1145]
monaco-editor version: 0.14.6
Browser: Chrome 70
OS: Fedora 28
Steps or JS usage snippet reproducing the issue:
```ts
provideSignatureHelp(model: editor.ITextModel, position: Position, token: CancellationToken): SignatureHelp | Thenable<SignatureHelp>
```
should be:
```ts
provideSignatureHelp(model: editor.ITextModel, position: Position, token: CancellationToken): SignatureHelp | undefined | Thenable<SignatureHelp | undefined>
```
I guess this project (and/or monaco-typescript) uses less strict mode of TypeScript, so this wasn't felt:
https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts#L222

**Comment by AviVahl** [comment]
`provideHover` has the same issue, although one could return `{contents:[]}` 

all these providers need to be able to return `undefined` in case of failure. The implementations today actually assume that.

**Comment by alexandrudima** [comment]
This has been addressed on `master`.

**Comment by AviVahl** [comment]
Glad to hear. I can see the `ProviderResult` change in the vscode repo :+1: 

Is there an expected date when this is going to land in `monaco-editor` or `monaco-editor-core`?
