### ISSUE TITLE
Page scrolling does not work

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#116]
Steps to reproduce:
1. go to https://microsoft.github.io/monaco-editor/;
2. hover over the editor;
3. try to scroll the page down;
4. it is not possible.

It will be nice if after the scroll bar reached the bottom (or the top) of the editor then a page scroll bar is used.

**Comment by svenefftinge** [comment]
I think that would be the natural behavior if the event was propagated.
Compare e.g. with the scolling behavior here https://codemirror.net/demo/complete.html

**Comment by alexandrudima** [comment]
Dup of #69 which just got fixed.
