### ISSUE TITLE
Ability to set CSS defaults for IntelliSense in HTML (much as you can set TypeScript default libraries)

### ISSUE THREAD

**Issue by Zlatkovsky** [Microsoft/monaco-editor#117]
For TypeScript IntelliSense, it's possible to add additional libraries outside of the editor itself, via

    monaco.languages.typescript.typescriptDefaults.addExtraLib(content, filename);

Is it possible to do the same for CSS, to expose some predefined classes to an HTML editor?

**Comment by aeschli** [comment]
@Zlatkovsky There are currently no APIs to replace or modify the list of known CSS selectors, properties or values. Is that what you meant?

**Comment by Zlatkovsky** [comment]
@aeschli , yes, that's what I mean.  I want to be able to declare (from an existing web source or whatever) a list of known classes, and get them to show up when I type in my HTML code.

I'm surprised when you say there is no API for this, though.  I thought VS Code uses Monaco editor... and there I _do_ get autocomplete in my html from referenced CSS files...

Thanks!

**Comment by aeschli** [comment]
@Zlatkovsky No, sorry, the Monaco HTML mode never had code completion for class names. Maybe you can add a screenshot of what you have seen?

**Comment by aeschli** [comment]
BTW, you want to file this request in the VSCode repo: https://github.com/Microsoft/vscode/issues.
VSCode and Monaco are the sharing most of the code and we use the VSCode repo to collect all requests.

**Comment by Zlatkovsky** [comment]
@aeschli, apologies, looks like I had imagined the CSS autocompletion feature!  As you correctly point out, it doesn't look like VSCode has it, either.

https://github.com/Microsoft/vscode/issues/1005#issuecomment-173395957 already describes the feature request, with a good screenshot detailing the problem.

**Comment by aeschli** [comment]
@Zlatkovsky Thanks for finding the issue in the vscode repro. Closing this one
