### ISSUE TITLE
[Feature] Ability to syntax-highlight text without having it in an editor instance

### ISSUE THREAD

**Issue by kobalicek** [Microsoft/monaco-editor#1171]
There are use-cases in which I would like to get a text (or only a part of a text) from the editor, format it into HTML, and append it to some div or something else. However, I haven't found a way how to do it (and I know it must be possible somehow as the editor supports syntax highlighting).

So the question/feature-request is how to do something like this [pseudo-snippet]:

```js
const editor = ... // my editor.
const log = ... // some HTML element;
const text = editor.getValue();

const html = howToConvertThatContentIntoFormattedHTML(text);
log.innerHTML += html;
```

There is a relevant question on SO, unfortunately unanswered:

  - https://stackoverflow.com/questions/52700307/how-to-use-monaco-editor-for-syntax-highlighting

There are possible workarounds like using another library to do syntax highlighting, however, it's not ideal as it's another dependency and its theme would have to be tuned to generate a comparable output as monaco editor.

**Comment by spahnke** [comment]
Hi,

does [this example](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-syntax-highlighting-for-html-elements) from the playground help? It colorizes text in a `pre` element using the Monaco editor.

Regards,
Sebastian

**Comment by kobalicek** [comment]
Thanks a lot! Not sure why I didn't find this API.
