### ISSUE TITLE
Diff navigator dose not always works

### ISSUE THREAD

**Issue by datou0412** [Microsoft/monaco-editor#1172]
I use `createDiffNavigator` method to create a navigator.
However, the navigator only works sometimes.
Most of the time` navigator.canNavigate()` return `false`;
I wonder `canNavigate()` return `false` in what case?

**Comment by alexandrudima** [comment]
When the diff editor is created, a web worker is started and it will compute asynchronously the diff between the original and modified models. For the duration of the initial computation, there is no diff and `canNavigate()` will possibly return false.
