### ISSUE TITLE
Cannot resolve dependency in monaco-editor/esm/vs/language/json/monaco.contribution.js

### ISSUE THREAD

**Issue by adam1658** [Microsoft/monaco-editor#1178]
**monaco-editor version:** 0.15.0
**Browser:** N/A
**OS:** macOS 10.12.6

**Steps or JS usage snippet reproducing the issue:**
After upgrading to 0.15.0 I can't build (with parcel) because of a weird looking import path in [node_modules/monaco-editor/esm/vs/language/json/monaco.contribution.js](https://unpkg.com/monaco-editor@0.15.0/esm/vs/language/json/monaco.contribution.js) - it starts as follows:
```js
import './....editoreditor.api.jsapi';
/* ... */
```

If I downgrade to 0.14.3 again it works. See the beginning of [monaco.contribution.js](https://unpkg.com/monaco-editor@0.14.3/esm/vs/language/json/monaco.contribution.js) in 0.14.3:
```js
import '../../editor/editor.api.js';
```

Is this the result of a dodgy build?

**Comment by alexandrudima** [comment]
That is definitely broken. This was the first built I did on Windows in quite a while, I guess some of the build scripts are not working so well.
