### ISSUE TITLE
[0.15.0] const enums are not being exported anymore

### ISSUE THREAD

**Issue by mofux** [Microsoft/monaco-editor#1179]
**monaco-editor version:** 0.15.0

With the new `0.15.0` release, `export const enum ...` are not getting exported in the standaloneEditor anymore. As an example, paste this code to the playground:

```javascript
require(['vs/base/common/scrollable'], ({ ScrollbarVisibility }) => {
    if (!ScrollbarVisibility) alert('ScrollbarVisibility has not been exported :(');
});
```

Looking at the sources, ScrollbarVisibility should get exported correctly:
https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/scrollable.ts

Reading the history of that file, it looks like the changes made in this commit are causing the problem:
https://github.com/Microsoft/vscode/commit/67eacaa4a856be0b90435c71de1996a12ff02f61#diff-c4d985a76a54961df57cff1260208b54

**Comment by alexandrudima** [comment]
This was never API and the change is intentional. We are moving our code base to use const enums internally because const enums get inlined in the generated JavaScript and they incur no overhead at runtime (i.e. there is no code generated for them, as you point out).

All the API enums that are present in `monaco.d.ts` are correctly exported, so I don't understand why you would reach for `ScrollbarVisibility` in `vs/base/common/scrollable` which is not API, instead of using `monaco.editor.ScrollbarVisibility` which is considered API and works.

**Comment by mofux** [comment]
Oh I see. Well in my special case I'm using the `DomScrollableElement` class to draw custom scrollbars on my own HTML elements in order to give them the same look & feel as the editor (overlay scrollbars that automatically hide when the element is not hovered).

Even though that might be a nasty grab to an internal API, I can still see valid use-cases for external contributions to access these kinds of enums. For example, if I want to define a custom content widget, I'd want to access the `ContentWidgetPositionPreference` from `vs/editor/browser/editorBrowser`, which also isn't exported any longer.

Wouldn't it be possible to still export these enums for the monaco-editor, while still inlining them at compile-time?

**Comment by mofux** [comment]
Oh never mind my last comment, I've read your answer incorrectly. Are all those enums accessible via monaco.editor.<enum>?

**Comment by alexandrudima** [comment]
Only the enums that are considered API. The API is in `monaco.d.ts` -- e.g. the core editor one is at https://github.com/Microsoft/vscode/blob/standalone/0.15.x/src/vs/monaco.d.ts

**Comment by mofux** [comment]
I see. I'd still prefer to have those enums accessible from their original sources (paths) because it makes troubleshooting against the vscode sources somewhat easier, plus it would allow accessing enums that have not been added to the monaco.d.ts file explicitly for those special edge-cases. 

It seems the Typescript compiler accepts a [flag](https://www.typescriptlang.org/docs/handbook/compiler-options.html) to enable this feature:

> --preserveConstEnums
> Do not erase const enum declarations in generated code.

Testing this functionality, it seems to inline the enums, while still exporting const enum declaration:

*index.ts*
```typescript
import { Test } from './enum';
if (1 === Test.Hello) console.log('Hello!');
```

*enum.ts*
```typescript
export const enum Test {
	Hello = 1,
	World = 2
}
```

Running `tsc --preserveConstEnums index.ts` results in:

*index.js*
```javascript
"use strict";
exports.__esModule = true;
if (1 === 1 /* Hello */)
    console.log('Hello!');
```

*enum.js*
```javascript
"use strict";
exports.__esModule = true;
var Test;
(function (Test) {
    Test[Test["Hello"] = 1] = "Hello";
    Test[Test["World"] = 2] = "World";
})(Test = exports.Test || (exports.Test = {}));
```

I can create a PR for this if you don't mind.

**Comment by alexandrudima** [comment]
I am sorry, but I would not accept such a PR.

I do not want our code to pay the cost at runtime of evaluating:
```
var Test;
(function (Test) {
    Test[Test["Hello"] = 1] = "Hello";
    Test[Test["World"] = 2] = "World";
})(Test = exports.Test || (exports.Test = {}));
```
for no good reason.

You are reaching into the editor internal implementation and you cannot complain when that changes or breaks. That is how libraries work, internal stuff can break or disappear at any time. We try as best we can to maintain our API surface in a backwards compatible way.
