### ISSUE TITLE
[Accessibility] A11y_.Net Editor: The shortcuts for the actions "Add Cursor Above" and "Add Cursor Below" i.e."Ctrl+Alt+UpArrow" and "Ctrl+Alt+DownArrow" are not performing the appropriate action when used.

### ISSUE THREAD

**Issue by LadyNaggaga** [Microsoft/monaco-editor#1181]
.NET Online REPL is having the following accessibility [issue.](https://github.com/dotnet/try/issues/122) Please see this issue . I have also included the details below

> **Environment Details**
> https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=4User
> Browser: Edge (41.16299.402.0)
> Chrome (67.0.3396.87)
> 
> **Additional Details:**
> MAS Violated: MAS2.1.1
> 
> **Repro steps:**
> Hit the URL https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/hello-world?tutorial-step=4User
> Tab till “Enter focus mode” and press enter
> Write a Sample program
> Now try the keyboard shortcuts for the actions "Add Cursor Above" and "Add Cursor Below" i.e."Ctrl+Alt+UpArrow" and "Ctrl+Alt+DownArrow" and verify whether the corresponding action is getting performed or not.
> 
> **Actual Result:**
> The Shortcuts "Ctrl+Alt+UpArrow" and "Ctrl+Alt+DownArrow" are not performing the intended action instead the screen orientation is getting changed because of the shortcut
> 
> **Expected Result:**
> All the shortcuts should work properly.
> 
> **User Impact:**
> A disabled user wouldn't be able to avail the functionality as a particular shortcut is not working.
> 
> **MAS Reference:**
> [https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7B8492c4eb-c179-40ae-8777-cd044ed725a2%7D)
> 
> [The shortcuts for the actions Add Cursor Above and Add Cursor Below i.e.Ctrl+Alt+UpArrow and Ctrl+Alt+DownArrow are not performing the appropriate action when used..pptx](https://github.com/dotnet/try/files/2191951/The.shortcuts.for.the.actions.Add.Cursor.Above.and.Add.Cursor.Below.i.e.Ctrl%2BAlt%2BUpArrow.and.Ctrl%2BAlt%2BDownArrow.are.not.performing.the.appropriate.action.when.used.pptx)

**Comment by alexandrudima** [comment]
This is not an accessibility issue. A driver you have installed on your system (most likely an Intel driver) takes over those keybindings.
