### ISSUE TITLE
Failing to close the detailed documentation view

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/monaco-editor#1185]
**monaco-editor version:** 0.15.1
**Browser:** Chrome version 70.0.3538.77
**OS:** Windows

**Steps or JS usage snippet reproducing the issue:**

Open the detailed documentation view.
Click on the 'x' icon to close it.
The view stays open.

![image](https://user-images.githubusercontent.com/17318937/48480447-25bd8480-e813-11e8-836a-83135713e283.png)

**Comment by joaomoreno** [comment]
Broken by https://github.com/Microsoft/vscode/commit/b77b9af3dab95ab7680a83ff4d22213addb1aabd#diff-caac303ecc98a837b262c2c9a093026d cc @bpasero
