### ISSUE TITLE
Detailed documentation view bug when moving between suggestions

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/monaco-editor#1186]
**monaco-editor version:** 0.15.1
**Browser:** Chrome version 70.0.3538.77
**OS:** Window

**Steps or JS usage snippet reproducing the issue:**

Open suggestions window and open a detailed documentation view.
Now go down with the arrow to different suggestion.
The detailed documentation view changes its position and freeze with the documentation of the first suggestion (doesn't show the documentation of the new suggestion).

![image](https://user-images.githubusercontent.com/17318937/48481876-aed6ba80-e817-11e8-89a3-8976997cfca3.png)

**Comment by joaomoreno** [comment]
Broken by https://github.com/Microsoft/vscode/commit/b77b9af3dab95ab7680a83ff4d22213addb1aabd#diff-caac303ecc98a837b262c2c9a093026d cc @bpasero @ramya-rao-a
