### ISSUE TITLE
Cannot create Uri using with method

### ISSUE THREAD

**Issue by Nishkalkashyap** [Microsoft/monaco-editor#1188]
**monaco-editor version:** 0.15.2
**Browser:** Chrome
**OS:** Windows

**dependencies:**
```
 "@angular/animations": "^7.0.3",
 "@angular/cdk": "^7.0.4",
 "@angular/common": "~7.0.3",
 "@angular/core": "~7.0.3",
 "@angular/forms": "~7.0.3",
 "@angular/http": "~7.0.3",
 "@angular/material": "^7.0.4",
 "@angular/platform-browser": "~7.0.3",
 "@angular/platform-browser-dynamic": "~7.0.3",
 "@angular/router": "~7.0.3",
```

**Steps or JS usage snippet reproducing the issue:**
```
const uri: monaco.Uri = new monaco.Uri().with({
   path : 'inmemory://abc'
});
```

Earlier, this used to work. Now it throws an error. Even with all the _optional_ parameters provided.

**Error:**

![capture](https://user-images.githubusercontent.com/32554850/48506074-a067bd80-e86e-11e8-8444-f57d632f5e8a.PNG)

**Comment by alexandrudima** [comment]
AFAIK this is intentional. URIs without a scheme are no longer allowed.

**Comment by jimmy29347** [comment]
I cannot load local files anymore. my file's original name was 'code.ts' now I renamed it to 'scheme://code.ts' then I cannot import it using import * from '.code'

**Comment by jrieken** [comment]
Yeah, we have enforce URI to have a scheme. You sample uses `path : 'inmemory://abc'` which is wrong. You likely wanna use `parse(yourString)`

**Comment by satya164** [comment]
What scheme should I use for local files? If I do `new Uri({ scheme: 'file', path: 'App.js' })`, the typescript worker complains that it cannot find the file. It used to work with `new Uri().with({ path })`.

**Comment by peterschussheim** [comment]
@jrieken @alexandrudima can you provide the correct way to load local files?

**Comment by windischb** [comment]
following is working for me:
```js
monaco.Uri.parse(`file://local/code.ts`)
```

**Comment by Nishkalkashyap** [comment]
@oldrich-s 
As for the Uri instead of doing this,

    const uri = monaco.Uri.from({ path: '/folder/index.ts', scheme: 'file' })

You can do this,  which automatically parses the path in the right format for you

    const uri = monaco.Uri.file('/folder/index.ts')

As far as is the case with `addExtraLib`,  I think it is very sensitive to the format of path that you add the lib with. I played with different formats for a few hours, and so far i have settled on this:

    const formattedPath = String().concat('file:///node_modules/@types/', path).replace(/[/\\]/g, '/')

**Comment by NarenShalem** [comment]
Just version change  "ngx-monaco-editor": "^7.0.0"  to  "ngx-monaco-editor": "^6.0.0",
And if you are using editor no need to pass uri as file you can pass it as unique id, i follwed it worked for me

**Comment by Spongman** [comment]
so how do we create relative Uris now?

**Comment by eakarpov** [comment]
> @oldrich-s
> As for the Uri instead of doing this,
> 
> ```
> const uri = monaco.Uri.from({ path: '/folder/index.ts', scheme: 'file' })
> ```
> 
> You can do this, which automatically parses the path in the right format for you
> 
> ```
> const uri = monaco.Uri.file('/folder/index.ts')
> ```
> 
> As far as is the case with `addExtraLib`, I think it is very sensitive to the format of path that you add the lib with. I played with different formats for a few hours, and so far i have settled on this:
> 
> ```
> const formattedPath = String().concat('file:///node_modules/@types/', path).replace(/[/\\]/g, '/')
> ```

The `rootUri` and `rootPath` properties remain `null`. Something is parsed wrong.

**Comment by sushantahirrao-gep** [comment]
import { Injectable } from '@angular/core';

@Injectable()
export class SharedService {
    public activeDropdown: any;

    testMethod() {
        console.log('hey');
    }

    newMethod() {
        console.log('newMethod');
    }
} 

How do I resolve '@angular/core' in above code sample? Please help.
