### ISSUE TITLE
API for extending monarch

### ISSUE THREAD

**Issue by JosefJezek** [microsoft/monaco-editor#1189]
I would like extend syntax of javascript language using monarch. How do it without fork?

**Comment by alexandrudima** [comment]
You could:
- use the webpack version and not include `javascript` and then define your own `javascript`.
- [or] define a new language `javascript2` with your changes
- [or] overwrite the built-in colorizer by calling `monaco.languages.setMonarchTokensProvider` after the built-in one has done so.

**Comment by troy351** [comment]
> * [or] overwrite the built-in colorizer by calling `monaco.languages.setMonarchTokensProvider` after the built-in one has done so.
How do we know the built-in one has done? Is there a hook?
@alexandrudima

**Comment by troy351** [comment]
Ended up with mixing  #115 and #884
