### ISSUE TITLE
[monaco-editor-core@0.15.3] issue with editor.api.d.ts

### ISSUE THREAD

**Issue by AviVahl** [Microsoft/monaco-editor#1195]
**monaco-editor version:** monaco-editor-core
**Browser:** chrome 70
**OS:** fedora 29

It appears the `editor.api.d.ts` file is not generated correctly and has many type errors/mistakes.
`Position` on `CompletionItemProvider`, for example, points to the `lib.dom.d.ts`'s `Position` interface, and not `monaco.Position`.

Only saw issue in `monaco-editor-core` package. `monaco-editor@0.15.4` (newer?) appears to be fine.

also, and unrelated, `insertText` should be optional on `CompletionItem`
EDIT: I see you actually use insertText and assume its defined. in TypeScript's API its optional (getCompletionsAtPosition), and if not defined, `label` is used instead. Will account for it in my provider.

**Comment by AviVahl** [comment]
you're looking at `monaco.d.ts`, while importing symbols (using esm) from 'monaco-editor-core' pointed typescript to `editor.api.d.ts` (which is where the `.d.ts` has errors).

**Comment by alexandrudima** [comment]
I still cannot reproduce. Here is what I get in `editor.api.d.ts`:

![image](https://user-images.githubusercontent.com/5047891/48695559-c16a3e80-ebdf-11e8-933d-e4674e0df8b9.png)

**Comment by AviVahl** [comment]
It looks like the issue is already fixed `monaco-editor-core@0.15.4`. I still see the error in `monaco-editor-core@0.15.3`.

The two versions have a different `editor.api.d.ts` file.

![screenshot from 2018-11-19 11-06-50](https://user-images.githubusercontent.com/8952081/48696781-8968f880-ebeb-11e8-95ea-41e5a760e721.png)
