### ISSUE TITLE
[0.15.0-0.15.5] monaco-editor/esm/vs/base/common/marked/marked.js doesn't ESM

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/monaco-editor#1196]
**monaco-editor version:** 0.15.5
**Browser:** none
**OS:** Windows 7

`monaco-editor\esm\vs\base\common\marked\marked.js` isn't ESM.

![image](https://user-images.githubusercontent.com/1937871/48657845-c19cf980-ea7a-11e8-8b9c-85ba4d20e34c.png)

On 0.14.3, it was below:

![image](https://user-images.githubusercontent.com/1937871/48657850-ed1fe400-ea7a-11e8-890e-c1f3d395fdbc.png)

This causes compile failure with Rollup.js.

**Steps or JS usage snippet reproducing the issue:**

1. Open `monaco-editor\esm\vs\base\common\marked\marked.js`

**Comment by veeramarni** [comment]
I have also noticed a few classes which were ESMed before was not found in `0.15.x`. For example, the following is missing in `textModel`.

`TextModelSnapshot`

**Comment by mysticatea** [comment]
Thank you so much!
