### ISSUE TITLE
0.15.* release nls bundles are not localized

### ISSUE THREAD

**Issue by pengx17** [Microsoft/monaco-editor#1201]
**monaco-editor version:** 0.15.x

I noticed that in latest versions (0.15.x) of monaco-editor, the nls packages contained in the libs are not localized, while they are localized in 0.14.x versions. I believe this is a bug when releasing the library.

eg. compare the two below:
- https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.15.0/min/vs/editor/editor.main.nls.zh-cn.js
- https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.14.0/min/vs/editor/editor.main.nls.zh-cn.js

**Comment by lwinhong** [comment]
我也发现了。无奈英语太烂，发帖不知怎么说

**Comment by dbaeumer** [comment]
Dups #822
