### ISSUE TITLE
Add .vue files as a supported language

### ISSUE THREAD

**Issue by jamesgibson14** [microsoft/monaco-editor#1204]
It would be great to select `language: 'vue'` as a supported language, with all the code completion and linting. It works great with vs codes so it would be nice in Monaco Editor for the browser.

**Comment by kingsylin** [comment]
I'm looking forward to have a good solution

**Comment by cron13** [comment]
any news?

**Comment by Dr-Harris** [comment]
Is there anything new?

**Comment by cron13** [comment]
> Is there anything new?

Hello!
You might be interested in my build codemirror editor for working with vue
This is not a fully designed project, now I have no time to do this :-(

Pay attention to the tern server, which is used by webworker to improve performance. it can be assembled using the config example from the webpack-config.js file

https://github.com/cron13/codemirror-vue-setup

**Comment by CuiZhengyang** [comment]
Is there anything new?

**Comment by y912765390** [comment]
Can Vue be directly supported now

**Comment by fish-uncle** [comment]
> Can Vue be directly supported now

How to configure

**Comment by y912765390** [comment]
First of all, it's a question. Not an answer. Secondly, Moanco 0.10 version can be implemented with plug-ins. Now what I'm doing is supporting Vue myself

**Comment by davojan** [comment]
@y912765390 can you please share monarch definition file for the vuejs language if you managed to create one?

**Comment by y912765390** [comment]
Instead of writing a component, I learned Vuter and wrote a Vue language into the Monaco-Editor. But the current support is not as perfect as Vuter

**Comment by denys119** [comment]
I’m also interested in this. Did someone find a solution that works and can share it?

**Comment by troy351** [comment]
https://github.com/Kingwl/monaco-volar

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
