### ISSUE TITLE
FoldingController throws Canceled promise error on startup

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/monaco-editor#1206]
1. Start simpleserver
2. Open http://localhost:8080/monaco-editor/test/?editor=src#Y___DefaultJS

Check the console.

![image](https://user-images.githubusercontent.com/22350/48836704-cc5dd400-ed83-11e8-934a-f36520c91eeb.png)

**Comment by alexandrudima** [comment]
I could only reproduce in `master`.

**Comment by alexandrudima** [comment]
I've fixed this.
