### ISSUE TITLE
Error in site example:  extending-language-services-custom-languages provideCompletionsItems is wrong

### ISSUE THREAD

**Issue by sarod** [Microsoft/monaco-editor#1207]
**monaco-editor version:** latest - playground
**Browser:** ALL
**OS:** All

**Steps or JS usage snippet reproducing the issue:**
1. Open the playground example (https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages)
2. The completion does not work

It seems that the provideCompletionItems code needs to be changed to wrap the returned array:

```javascript
	provideCompletionItems: () => {
		return [
			...
		]
	}
```
should become
```javascript
	provideCompletionItems: () => {
		return {
			suggestions: [
				...
			]
		}
	}
```

**Comment by alexandrudima** [comment]
Fixed via 9af2ead38d29e4211b1feef979f4dd76c1e2237f
