### ISSUE TITLE
When the ipad pro uses the Bluetooth keyboard, the cursor keys cannot be used.

### ISSUE THREAD

**Issue by yueqiumao** [Microsoft/monaco-editor#1209]
**monaco-editor version:** 0.X.Y
**Browser:ipad pro safari
**OS:ios 12.1

**Steps or JS usage snippet reproducing the issue:**

When the ipad pro uses the Bluetooth keyboard, the cursor keys cannot be used.

**Comment by Reflyer823** [comment]
It seems that it's caused by a bug in webkit. 
 https://bugs.webkit.org/show_bug.cgi?id=149054
This bug has existed from iOS 8, and it still hasn't been repaired in iOS 12.
