### ISSUE TITLE
How to get a current language for a model?

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#121]
Also should onDidChangeModelLanguage provide a new language.

**Comment by akosyakov** [comment]
I see there is a method: IReadOnlyModel.getModeId(). A bit confusing naming.

**Comment by 1nv1n** [comment]
An alternative would be just reading the value off of `monaco.editor.model._languageIdentifier.language`. But I don't think that's a good way to do that.

**Comment by skdblog1999** [comment]
`editor._configuration._rawOptions.language` . This works for me.
