### ISSUE TITLE
flatmap-stream@0.1.1

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/monaco-editor#1211]
The `package-lock.json` includes `flatmap-stream@0.1.1` which includes malicious code: [package-lock.json#L1090-L1095](https://github.com/Microsoft/monaco-editor/blob/9af2ead38d29e4211b1feef979f4dd76c1e2237f/package-lock.json#L1090-L1095).

See also: https://github.com/dominictarr/event-stream/issues/116

The `event-stream` package looks unsafe. It's better to find an alternative in my 2 cents.

**Comment by lmcarreiro** [comment]
After the mess, the dependency to `flatmap-stream` was removed and the `event-stream` is maintained by the NPM team now.

**Comment by alexandrudima** [comment]
Thank you for the heads up. I have locked the dependency to `event-stream@3.3.4` which gets rid of `flatmap-stream` from the dev dependencies.

**Comment by shivam183** [comment]
Hi, I'm new to MEAN stack and can anyone please tell me how to safely remove or update this dependency from package-lock.json using NPM

**Comment by KudMath** [comment]
@shivam183 here is how I did it : remove your `package-lock.json`, lock your dependency to `event-stream` at version `3.3.4` by adding `"event-stream": "3.3.4",` to your `package.json`run `npm i` (that should work if your flatmap-stream dependency comes from event stream, if not you can repeat those steps for the respective 'ancestors')
