### ISSUE TITLE
Displaying incorrect icons in DocumentSymbolProvider

### ISSUE THREAD

**Issue by BrotherhoodOfHam** [microsoft/monaco-editor#1214]
**monaco-editor version:** 0.14.3
**Browser:** Google Chrome
**OS:** Windows 10

When using the DocumentSymbolProvider, for certain SymbolKind values their icons seem to default to the Method icon despite the fact that the correct icons definitely do exist in monaco. CompletionItemKind doesn't have this issue and displays the correct icons.

I used this code to test each SymbolKind value.
```js
monaco.languages.registerDocumentSymbolProvider('plaintext', {
    provideDocumentSymbols(model, token)
    {
        let kinds = Object.keys(monaco.languages.SymbolKind)
            .map(e => monaco.languages.SymbolKind[e])
            .filter(e => !isNaN(e));
        
        return kinds.map(kind => ({
            name: kind.toString() + " " + monaco.languages.SymbolKind[kind],
            containerName: "",
            kind: kind
        }));
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "plaintext"
});
```

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/1bf341e6d2b0963e6260853e570d2655f987ffcb
