### ISSUE TITLE
Visual Basic grammar issue

### ISSUE THREAD

**Issue by 330218654** [microsoft/monaco-editor#1216]
This class library, in VB, no matter what code is placed behind End, always becomes highlighted.

**Comment by alexandrudima** [comment]
@330218654 Can you show a code snippet and a screenshot please?

**Comment by 330218654** [comment]
VB mode, no matter what code is placed after the end, it always becomes highlighted. I think only "Function, Sub, Class, Struect, Module, Property, Get, Set..." It should be highlighted.

**Comment by 330218654** [comment]
![1u 4igyonshimr t3ut q0](https://user-images.githubusercontent.com/17793049/49725410-933fc200-fca6-11e8-9f35-72ee41e581ed.png)

**Comment by alexandrudima** [comment]
Here is the OCR'd version:

```
Module Module1

	Sub Main()
		Dim a As New M8Ball
		
		Do While True 
			
			Dim q As String = ""
			Console.Write("ask me about the future... ")
			q = Console.ReadLine() 
			
			If q.Trim <> "" Then
				Console.WriteLine("the answer is... {0}", a.getAnswer(q))
			Else
				Exit Do
			End qweqweqweqweqwe'here always becomes highlighted Loop 
		Loop
	End Sub

End Module
```

I can only assume the issue is that the grammar will always colorize the first word after `End` as a keyword.
