### ISSUE TITLE
how to increase auto completion(intellisense) window size

### ISSUE THREAD

**Issue by reddys11** [Microsoft/monaco-editor#1219]
when i am typing in editor the matching element is displaying through intellisense but when it manches single element. The element is not showing properly as shown below. how can i increase the window size.

![image](https://user-images.githubusercontent.com/35195661/49431755-32ab1380-f7d4-11e8-8b6f-311b4c3cab45.png)

**Comment by rcjsuen** [comment]
@reddys11 What OS/browser version are you on? Can you try another browser?

**Comment by alexandrudima** [comment]
@reddys11 It also looks like you might have some CSS that ends up (by accident?) targeting the editor's dom node and using something like `overflow: scrollbar`. Can you reproduce when removing that CSS.

**Comment by reddys11** [comment]
thanks for the response. because of my local css file it's overlapping. i resolved issue.
