### ISSUE TITLE
adding colors to dynamically added tokens

### ISSUE THREAD

**Issue by reddys11** [microsoft/monaco-editor#1220]
for the first time all the tokens are getting color when the editor is loaded but when the user added new tokens dynamically then color is not applying to the recently created tokens,how can i update the tokens. can anyone help on this issue.

**Comment by alexandrudima** [comment]
@reddys11 I am not sure what you mean. Can you add some code sample showing the problem? A screenshot might also help.

**Comment by reddys11** [comment]
![color_issue](https://user-images.githubusercontent.com/35195661/49717396-003e6200-fc7d-11e8-88f7-ed59e825345f.png)

i am creating new variables and pushing to the already existing array,but i am not color to the created variable, the remaing elements(variables) which are present in the array are getting colors.

**Comment by alexandrudima** [comment]
> "and pushing to the already existing array"

Are you modifying the language definition data structure **after** you have called `monaco.languages.setMonarchTokensProvider`? i.e. 
```js
var foo = { ... };
monaco.languages.setMonarchTokensProvider(..., foo);
foo.bar.push(`baz`);
```
you should set the language grammar again if you are modifying it:
```js
var foo = { ... };
monaco.languages.setMonarchTokensProvider(..., foo);
foo.bar.push(`baz`);
monaco.languages.setMonarchTokensProvider(..., foo);
```
