### ISSUE TITLE
unable to integrate monaco editor with Angular 6+

### ISSUE THREAD

**Issue by prabal77** [Microsoft/monaco-editor#1221]
**monaco-editor version:** 0.15.6
**Browser:** All
**OS:** Windows

I am unable to run monaco-editor in my angular 6 application. I am trying to use ESM version of the editor, but not sure how to integrate with angular. The sample ESM code uses webpack config and requires web workers to work. But i couldn't find any sample/direction to use the same in angular.
From angular 6 onwards ng eject is also unavailable.
Not planning to use ng-monaco-editor or similar as those projects seems to be abandoned.
Any sample code or guide will be helpful.

Not an issue on code, but documentation is really lacking.

**Comment by vajahath** [comment]
Why this issue is closed?
ESM code code requires webpack, I don't where to set them in Angular. It would be helpful if the doc cover an example for Angular too.

@prabal77 How you managed to get this work?
