### ISSUE TITLE
Uncaught Error: Invalid start index: 2

### ISSUE THREAD

**Issue by INTACT180** [microsoft/monaco-editor#1222]
v - 0.14.3
browser - Chrome
os - Windows

Clicking item from suggestion dropdown that isn't the first item throws an exception.

"Uncaught Error: Invalid start index: 1\n\nError: Invalid start index: 1\n    at e.splice 

I suspect this is because onListSelection happens before onFocusChange when clicking.

**Comment by alexandrudima** [comment]
Can you please try 0.15.6? I think we fixed it with the latest release.

**Comment by INTACT180** [comment]
Sure, will upgrade soon :)
