### ISSUE TITLE
"out of memory" on azure pipelines 

### ISSUE THREAD

**Issue by atilkan** [Microsoft/monaco-editor#1223]
**monaco-editor version:** 0.15.6
**OS:** Azure pipelines

**Steps or JS usage snippet reproducing the issue:**
We have a project with webpack which works fine on our machine. But we can not make a build on azure pipelines. It returns out of memory. 
We used monaco-editor-webpack-plugin. https://github.com/Microsoft/monaco-editor-webpack-plugin
Do you have a recommendation?

**Comment by alexandrudima** [comment]
Isn't this more of an issue for webpack? I don't think we are doing anything memory intensive in our plugin. Perhaps other folks in that community have tips for how to reduce memory usage in webpack?

**Comment by atilkan** [comment]
@alexandrudima 
The only difference with working one and not working one is monaco-editor with webpack-plugin.
That is why i opened issue here. 
Thank you.

**Comment by alexandrudima** [comment]
I think you might have similar issues with webpack if you include any other multi-megabyte library, i.e. I think it has to do with the size, not with the content.

**Comment by atilkan** [comment]
You are right on the point. It is about the library size. But other people might have the same problem. I though you could give some tips.

**Comment by alexandrudima** [comment]
Yes, other people might have the same problem, but I think those people are far more likely to be found on the webpack issue tracker / forum / etc.

I am sorry, I really believe the project that allocates memory should know tweaks on how to reduce memory allocation. In this case, when you invoke `webpack`, it is `webpack` that allocates memory and not the source code that is being webpacked.

One thing I would try is to disable minification, AFAIK minification has a huge memory footprint regardless of using `webpack` or not. Perhaps you can webpack everything and then minify each file in a separate step.

**Comment by atilkan** [comment]
Thank you very much. That is more than i could expect.
