### ISSUE TITLE
JavaScript: if regular expression has ` will truncate the following code

### ISSUE THREAD

**Issue by lwinhong** [Microsoft/monaco-editor#1224]
**monaco-editor version:** 0.14.3 +
**Browser:** chrome 61
**OS:** win10

**Steps or JS usage snippet reproducing the issue:**

if regular expression has `  will truncate the following code 

**regular expression:**
```

 /^(?:\d+|[a-zA-Z]+|[\`\~\!\@\#\$\%\^\&\*\(\)\-\_\=\+\[\{\]\}\:\;\"\'\|\\\<\,\>\.\?\/]+){6,}$/

```

**in monaco editor↓** 
![image](https://user-images.githubusercontent.com/31954501/49486315-e239c180-f878-11e8-85e2-20684d430802.png)

**Ok in vscode ↓**
![image](https://user-images.githubusercontent.com/31954501/49486347-05fd0780-f879-11e8-9254-7eb9abe0c4bb.png)

@alexandrudima

**Comment by alexandrudima** [comment]
A minimal repro is:

```
var x = !/`/.test('a');
```

![image](https://user-images.githubusercontent.com/5047891/49547882-4b0a5380-f8e4-11e8-8748-509e5491a19a.png)

**Comment by lwinhong** [comment]
@alexandrudima thanks
