### ISSUE TITLE
Monaco transfer '\n' to '\r\n' which lead to getValueLength result is not equal to file content size

### ISSUE THREAD

**Issue by harbin1053020115** [microsoft/monaco-editor#1225]
monaco-editor version: 0.12.0
Browser: Chrome
OS: Mac

File content from git merge with conflicted, git will add Line break using '\n', monaco may transfer '\n' to '\r\n', which lead to getValueLength() is not equal to file content size

**Comment by harbin1053020115** [comment]
File content with git conflicted like this: 

```
package com.xxx.xxx;

<<<<<<< HEAD
master2-master
=======
master1-test
>>>>>>> test

public final class Lower extends XXX {
    public String evaluate(String s) {
        if (s == null) { return null; }
        return s.toLowerCase();
    }
}
```

**Comment by alexandrudima** [comment]
@harbin1053020115 Yes, that is kind of by design. The passed in content gets the EOL normalized. When a text buffer (model) is created, the end of line sequences are counted and the majority will be used as the one for the entire file. The idea is to avoid and actively remove the case of files with mixed line endings.

**Comment by harbin1053020115** [comment]
> @harbin1053020115 Yes, that is kind of by design. The passed in content gets the EOL normalized. When a text buffer (model) is created, the end of line sequences are counted and the majority will be used as the one for the entire file. The idea is to avoid and actively remove the case of files with mixed line endings.

Is there a configuration to avoid normalize the EOL when createModel in monaco-editor?

**Comment by pinksky** [comment]
> @harbin1053020115 Yes, that is kind of by design. The passed in content gets the EOL normalized. When a text buffer (model) is created, the end of line sequences are counted and the majority will be used as the one for the entire file. The idea is to avoid and actively remove the case of files with mixed line endings.

I have the same question with ermin.zem harbin1053020115.
When we are dealing with files from different operating system or different file system, inevitably, we will face with the case of files with mixed line endings.

And，do you have some solutions for this problem?

**Comment by l4wei** [comment]
> @harbin1053020115 Yes, that is kind of by design. The passed in content gets the EOL normalized. When a text buffer (model) is created, the end of line sequences are counted and the majority will be used as the one for the entire file. The idea is to avoid and actively remove the case of files with mixed line endings.

Avoiding mixed line endings may be a solution, But we cant find a way to judge if a file contains different EOL in monaco API document. There is a method to judge it?

**Comment by alexdima** [comment]
Let's track at https://github.com/microsoft/vscode/issues/127
