### ISSUE TITLE
Change font to one with ligatures

### ISSUE THREAD

**Issue by fdeitelhoff** [Microsoft/monaco-editor#123]
I'm trying to change the font of the monaco editor. I found some properties to achieve this:

fontFamily: "Times",
fontSize: 20,

But am not able to change that to a custom font like Hasklig (https://github.com/i-tu/Hasklig/). What am I missing. Should I access the font through the CSS classes?

**Comment by alexandrudima** [comment]
@fdeitelhoff Try first to use the font in a `div` or another element in your page to verify that the browser can correctly load the font. Then, use the same `fontFamily` on the editor creation options and it should behave the same.

**Comment by alexandrudima** [comment]
Maybe also try the option `fontLigatures: true`
