### ISSUE TITLE
How to compile multiple ts files with help of monaco editor and get output as single JS file in Angular 6

### ISSUE THREAD

**Issue by TanmayBit** [microsoft/monaco-editor#1231]
Description :

my 1st ts file contains below code:

```
  module utilityFunctions {  export class User { constructor(){}; 
  show():  void{alert('test');}; } }
```

2nd ts file contains below code:

```
import {User } from '/assets/script/utilityFunctions';
let u = new User();

function onChange_something() { 
u.show();
};
```

how i can compile both files together to generate single JS file using monaco editor in Angular 6 project? Currently i am using ngx-Monaco-editor.

i am able to set above ts files to different monaco editor models and get reference. But how i can compile the code with multiple TS file and import statements. 

Thanks.

**Comment by alexandrudima** [comment]
@TanmayBit I don't think this is a Monaco Editor specific question, if I were you I would load the TypeScript compiler and use its emitting API (https://github.com/Microsoft/monaco-typescript) independent of the Monaco Editor.

(The Monaco Editor does load the TypeScript language service API, but it does so in a web worker which runs in a separate context and is not available in the UI thread).
