### ISSUE TITLE
keyboard shortcuts 'ctrl+ spase' don't work

### ISSUE THREAD

**Issue by lwinhong** [Microsoft/monaco-editor#1232]
**monaco-editor version:** 0.15.6
**Browser:** chrome
**OS:** win10

**Steps or JS usage snippet reproducing the issue:**

use keyboard shortcuts 'ctrl+ spase' (Trigger Suggest) not work, but click command palette is ok

![image](https://user-images.githubusercontent.com/31954501/49776620-aea6dd80-fd37-11e8-9a62-e816ebdcc392.png)
@alexandrudima

**Comment by alexandrudima** [comment]
@lwinhong That is quite bizzare. Perhaps we are not receiving the keypress? What is the output when you press Ctrl+Space and include modifiers at https://unixpapa.com/js/testkey.html

![image](https://user-images.githubusercontent.com/5047891/50895303-02bfe300-1406-11e9-86b5-1b1613c31b50.png)

The second one is ctrl+space `keydown` being received correctly on my machine (as `keyCode=32` with modifiers `ctrlKey`). i.e. we would trigger suggestion on that one.
