### ISSUE TITLE
[Monarch] Empty Line Handling

### ISSUE THREAD

**Issue by zlstringham** [Microsoft/monaco-editor#1235]
**monaco-editor version:** 0.15.6
**Browser:** Chrome
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
There is no apparent way to match or handle empty lines in a language file.

The language I would like to highlight has the following semantics:
- Lines/Statements are terminated at EOL, not semi-colons.
- Lines may be continued by escaping the EOL.
- Escape-char "\\" may itself be escaped.

The following demonstrates expected semantics with single-line comments, though the same behavior would be expected with pre-processor directives, strings, etc.
```cpp
// This comment \
   continues on the following line

// This comment does NOT continue \\
   because the escape char was itself escaped

// This comment DOES continue because \\\
   the 1st '\' escapes the 2nd; the 3rd escapes EOL

// This comment continues to the following line \

But the line was empty. This line should not be commented.
```

I can achieve most of these semantics with this tokenizer definition:
```js
return {
  tokenizer: {
    root: [
      { include: '@comments' },
    ],

    comments: [
      [/\/\/$/, 'comment'], // empty single-line comment
      [/\/\//, 'comment', '@comment_cpp'],
    ],

    comment_cpp: [
      [/(?:[^\\]|(?:\\.))+$/, 'comment', '@pop'],
      [/.+$/, 'comment'],
      // No possible rule to detect an empty line and @pop?
    ],
  },
};
```

However, as noted, there does not seem to be any possible rule to achieve the last part:
```cpp
// This comment continues to the following line \

In Monarch, the above line seems unmatchable, so the @comment_cpp state continues to here.
```

**Comment by alexandrudima** [comment]
@zlstringham Thanks, this is a good find. After tweaking the monarch tokenizer and adding a rule to `comment_cpp` to target empty lines I could get this to work:
```js
{
  tokenizer: {
    root: [
      { include: '@comments' },
    ],

    comments: [
      [/\/\/$/, 'comment'], // empty single-line comment
      [/\/\//, 'comment', '@comment_cpp'],
    ],

    comment_cpp: [
      [/(?:[^\\]|(?:\\.))+$/, 'comment', '@pop'],
      [/.+$/, 'comment'],
	  [/$/, 'comment', '@pop']
      // No possible rule to detect an empty line and @pop?
    ],
  },
}
```

![image](https://user-images.githubusercontent.com/5047891/50904238-1d06ba80-1420-11e9-9a13-72153f715148.png)
