### ISSUE TITLE
Disable Command Pallete in context menu

### ISSUE THREAD

**Issue by XDfield** [Microsoft/monaco-editor#1237]
Hi! I use monaco to make a readOnly editor. Can I disable Comand Pallete in context menu? I found it designed to show in any situation. I don't want it to show to confuse my users.

I found that Command Pallete's  group id is 'z_command', can I disable the specified group id in context menu?

**Comment by alexandrudima** [comment]
Not at this time.

But since this is JS, you can try the hacky/unsupported way of poking into `require('src/vs/platform/actions/common/actions.ts').MenuRegistry` and messing with the `_menuItems`.

**Comment by XDfield** [comment]
By @alexandrudima 's advice, I modify `MenuRegistry.getMenuItems` function. It works! Thanks : )
