### ISSUE TITLE
How to show parameter hint for custom language

### ISSUE THREAD

**Issue by naumanumer** [Microsoft/monaco-editor#124]
I want to show parameter hint for a custom language. I set `parameterHints` to `true` but doesn't know what to do next.

**Comment by alexandrudima** [comment]
@naumanumer You need to follow a pattern similar to providing suggestions for example, but in your case it would be `monaco.languages.registerSignatureHelpProvider`

Example of completion item provider:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

Example of hover provider:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example
