### ISSUE TITLE
Multiple editors, keyboard blocked

### ISSUE THREAD

**Issue by malayka66** [microsoft/monaco-editor#1248]
**monaco-editor version:** 0.13.1
**Browser:** Chrome
**OS:** Windows
**Framework:** Knockout.js

**Steps or JS usage snippet reproducing the issue:**
Hi, I have multiple editors in the same page in different tabs and the keyboard is blocked in every editor except one (randomly, I always have to find which one) and I have to go to that tab and "rescue the cursor"/"unstuck the keyboard" to start typing in the other ones. This only happens when I enter the page.

I have the same class for each editor (a div) and I make a cycle over them to create each editor.

```Javascript
    $(".editor").each(function () {
        var language = $(this).data("language");
        var file = $(this).data("file");
        var me = this;
        //var content = $(this).html();
        $(this).empty();
        if (file) {
            var url = `/data/profiles/${profile}/layouts/${layout}/${file}`;
            if (isSandbox) {
                url = `/data/sandbox/${layout}/${file}`;
            }
            $.ajax(url, {
                dataType: 'text',
                success: function (data) {

                    let editor = monaco.editor.create(me, {
                        value: data,
                        language: language,
                        automaticLayout: true
                    });

                    // editor.addListener('didType', () => {
                    //     console.log(editor.getValue());
                    // });
                    //setTimeout(() => { editor.getAction('editor.action.formatDocument').run(); }, 1000);
                    editors.push(editor);
                }
            });
        } else {
            let editor = monaco.editor.create(me, {
                value: "",
                language: language,
                automaticLayout: true
            });
            //setTimeout(() => { editor.getAction('editor.action.formatDocument').run(); }, 1000);
            editors.push(editor);
        }
    });
```
Example of one editor (they have different IDs!!):
```html
<div class="mdl-tabs__panel" id="layout-panel">
	<div id="editor-layout" class="editor" data-language="html" data-file="layout.ejs"></div>
</div>
```

Besides this, the editor works fine.
Thank you

**Comment by datou0412** [comment]
I update my monaco-editor from 0.14.3 to 0.15.6, my typing events are blocked in my editor, even context menu `cut` dose not work. I`m pretty sure its not in readonly mode.

I have multiple editors in the same page too, but I`m not sure if its the same question with you @malayka66

**Comment by malayka66** [comment]
Hi, I made a video (it's not listed) illustrating the problem
https://www.youtube.com/watch?v=IPCAJApZhzE

It's random the tab where the cursor is being stuck.

**Comment by veeramarni** [comment]
Any update on it?

**Comment by ChangUk** [comment]
@malayka66 "container.addEventListener("mousedown", function (e) { e.stopPropagation(); });" will be helpful. But, it is just a kind of trick...
If you already solved the problem with a fancy way, please share it with me.

**Comment by alexdima** [comment]
In order to attempt to fix this we need a reproducible case.

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
