### ISSUE TITLE
Suggest-Widget shows weird color.

### ISSUE THREAD

**Issue by stealthzuk** [Microsoft/monaco-editor#1250]
![suggestwidget](https://user-images.githubusercontent.com/22783082/50534909-9ed42980-0b7e-11e9-90f0-665f3147b9e7.png)

The suggestion part is shown in a white background, while the remaining part is shown in its usual grey. This might be due to some overall CSS in our product changing background-color to transparent.

I am thinking of having CSS file to counter that, and I have located <div class="monaco-list-rows" DOM element but not able to identify elements inside (since mouse click inside Chrome developer tool will trigger event to remove them). Help on this is much appreciated.

**Comment by vasiltabakov** [comment]
@stealthzuk 

In Chrome Dev tools right click on the element 
![image](https://user-images.githubusercontent.com/1178309/50694305-37b4ea00-1042-11e9-9da4-2e65b18553c4.png)
then trigger the auto complete widget and in Chrome dev tools you will see:
![image](https://user-images.githubusercontent.com/1178309/50694382-67fc8880-1042-11e9-821d-2bf8c5a1b45b.png)
Resume the script execution a few times by clicking this button a few times:
![image](https://user-images.githubusercontent.com/1178309/50694406-7e0a4900-1042-11e9-9da4-c7755950e4bb.png)
the list will show and you can inspect it normally
![image](https://user-images.githubusercontent.com/1178309/50694457-a003cb80-1042-11e9-9e55-db12b8a9e860.png)

**Comment by stealthzuk** [comment]
@vasiltabakov Great! Many thanks, Vasil!
