### ISSUE TITLE
 About Markdown Text in Intellisense Monaco Editor

### ISSUE THREAD

**Issue by Kang-Jun-sik** [Microsoft/monaco-editor#1251]
**monaco-editor version:** 0.14.3(monaco-editor-sample)
**Browser:** Chrome
**OS:** : Window

**Steps or JS usage snippet reproducing the issue:**

Hi. I am a developer likes the Monaco editor.  
I am always thankful can use the Monaco editor.

**Q**. I Want to extend my Intellisense Text using **Markdown Format**
Like below pic. It works very Great in Playground.
![q1](https://user-images.githubusercontent.com/20898356/50556466-d7aa0500-0d1c-11e9-8b76-7c64c238dc08.png)

But the problem is monaco-editor-sample project in my local.
I pull monaco-editor-sample from git. It doesn't works... like below pic. 
(doesn't work markdown format in intellisense Box)
![q2](https://user-images.githubusercontent.com/20898356/50556531-ab42b880-0d1d-11e9-8f67-5bafb4a93ac6.png)

Here is the code the monaco-editor-sample in my project.
```
<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	<link rel="stylesheet" data-name="vs/editor/editor.main" href="../node_modules/monaco-editor/min/vs/editor/editor.main.css">
</head>

<body>

	<h2>Monaco Editor Sync Loading Sample</h2>
	<div id="container" style="width:800px;height:600px;border:1px solid grey"></div>

	<script>var require = { paths: { 'vs': '../node_modules/monaco-editor/min/vs' } };</script>
	<script src="../node_modules/monaco-editor/min/vs/loader.js"></script>
	<script src="../node_modules/monaco-editor/min/vs/editor/editor.main.nls.js"></script>
	<script src="../node_modules/monaco-editor/min/vs/editor/editor.main.js"></script>

	<script>
		var editor = monaco.editor.create(document.getElementById('container'), {
			value: [
				'function x() {',
				'\tconsole.log("Hello world!");',
				'}'
			].join('\n'),
			language: 'javascript'
		});

		monaco.languages.typescript.javascriptDefaults.addExtraLib(
`/**
   ---
* Function documentation **bold** _italics_.
*
* Example :
*
* \`\`\`
* myFunction(0);
* \`\`\`
*
* More markdown text
*
* @param num Parameter description
* @return Return type description.
*/
function myFunction(num: number): number;`,
		);

		monaco.languages.typescript.javascriptDefaults.setCompilerOptions({

			allowNonTsExtensions: true,
			checkJs: true,

		});

		monaco.editor.create(document.getElementById("container"), {
			value: "",
			language: "javascript"
		});

	</script>
</body>
</html>
```
What is the main difference between playground Editor & Monaco-editor-sample??
And Finally how to **apply Markdown Format in Monaco-Editor-Sample Project??**

Thx for reading any I really respect Monaco Editor Developer Team. 
Thanks for reading and i want to reply.

**Comment by spahnke** [comment]
Hi,

the Markdown formatting was added in version 0.15.* and you seem to use 0.14.3. If you update your local monaco package to the latest version it should work.

Regards,
Sebastian

**Comment by Kang-Jun-sik** [comment]
> Hi,
> 
> the Markdown formatting was added in version 0.15.* and you seem to use 0.14.3. If you update your local monaco package to the latest version it should work.
> 
> Regards,
> Sebastian

Thanks very much! happy new year spahnke!
