### ISSUE TITLE
How to display errors or warnings in the line area?

### ISSUE THREAD

**Issue by wupengFEX** [Microsoft/monaco-editor#1253]
How to display errors or warnings in the line area, as follows，i think this's clearer for developers.

![image](https://user-images.githubusercontent.com/8186657/50631018-d0356680-0f7d-11e9-9b9b-6bf487bca848.png)

**Comment by vasiltabakov** [comment]
@wupengFEX this area is called the 'margin' and you can have glyphs there. Check this:
https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin

**Comment by wupengFEX** [comment]
@vasiltabakov Excellent! Thanks a lot!
