### ISSUE TITLE
Can't click anywhere except last line, if embedded in WebKit controller on Mac

### ISSUE THREAD

**Issue by Zlatkovsky** [Microsoft/monaco-editor#1255]
**monaco-editor version:** 0.15.6 -- And any version > 0.10.1 
**Browser:** Webkit control
**OS:** Mac OS X 10.13.6

When embedded inside of a WebKit control on a Mac, the usability of the Monaco editor is severely broken, because you can only click into the editor on the very last line!  Clicking anywhere else does nothing (and also means you can't select text, etc.).  When run on pure Safari, it works fine, so it's something about WebKit.

Interestingly, version 0.10.1 **did** work fine inside of WebKit.  But newer versions of Monaco do not.  This is unfortunate for us, as we need a few fixes that newer versions of Monaco have, but without being able to properly interact with the editor, it's irrelevant for us.

(By "us":  we are the Script Lab team inside of Office.  Script Lab is an Office Add-in, and add-ins on the Mac run inside of a WebKit sandbox within Office).

I created a test page at <https://script-lab.azureedge.net/monaco-test.html>.  If you load it in Safari proper, you'll see a textbox for the Monaco URL.  Whether you keep the default one, or whether you substitute `https://unpkg.com/monaco-editor@0.15.6/min/vs` to use the latest, when you press "Go" it will load the page and mouse-clicking will work everywhere.  That's the "control" case.

By the way, the page that it creates is more-or-less a copy of https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-script-editor/index.html, just generated dynamically.  You can see exactly what it is in the console output.

... Anyway, to see a repro in a way that abstracts away any Office-specific things:  create a project in Xcode that does the following.  For convenience, I'm attaching a zip file with such project.

```
- (void)viewDidLoad {
    [super viewDidLoad];
    WKWebView *webView = [[WKWebView alloc] initWithFrame:NSMakeRect(0, 0, 400, 400)];
    [webView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:@"https://script-lab.azureedge.net/monaco-test.html"]]];
    [[self view] addSubview:webView];
}
```

[testWebkit.zip](https://github.com/Microsoft/monaco-editor/files/2725676/testWebkit.zip)

If you run this project and again use the default hard-coded version of Monaco (`https://unpkg.com/monaco-editor@0.10.1/min/vs`), everything will work fine.  But if you right-click to reload the page, and then change that version number to `0.15.6` (or `0.14.3`, or any of the others), and then load, you'll see that the editor is unresponsive **unless you click on the very last line**.  But you can't click elsewhere, nor select text on other lines via the mouse.

This is a blocker for us to move to a newer version of Monaco (and in turn, a blocker for releasing another feature for Script Lab on the Mac).  Any help would be greatly appreciated.  Since earlier versions of Monaco (0.10.1) did work with WebKit, it must be something in the JS that *could* be changed to make it work again.  Alternatively, if you think it's a bug with WebKit, we can try to work with Apple on fixing that (though that seems like a much longer route, just from the standpoint of how quickly users could get such fix deployed -- esp. since multiple steps are involved, from Apple fixing it, to Office taking in the fix, to users upgrading, etc...)

Thank you very much for your help!

**Comment by Zlatkovsky** [comment]
Thanks, @alexandrudima .  Just to clarify:  will the fix that you made in https://github.com/Microsoft/vscode/commit/b679274562347203f5185fd0dd2f80bea88b51f3 eventually make it into this repo / NPM package?  (It's unclear what the relationship between that other repo and this one is -- are files just copied over every so often?...)

If it will, then we can just wait another month or whatever until a new version of Monaco, incorporating the change, is ready for us to try.

**Comment by Hillyman** [comment]
Did anyone find a solution for this problem? Still getting the issue on version 0.17.0
