### ISSUE TITLE
Hover actions

### ISSUE THREAD

**Issue by vasiltabakov** [microsoft/monaco-editor#1257]
It would be great if hover popups had 'actions'. This would be a way to have custom icons/buttons somewhere in the popup and have code be executed when they're clicked.

One use case would be when the hover text is too big and is not easy to read in the popup. Here's an example from our app:
![image](https://user-images.githubusercontent.com/1178309/50693743-86fa1b00-1040-11e9-91d4-627082dda19f.png)

the text is long and is designed ot be read in a context where white space won't break the text.

Anyway there are probably many other interesting things that could be done if "hover actions" existed.

**Comment by jrieken** [comment]
You can use markdown and links, esp command links like `command:your-command-id` for this.
