### ISSUE TITLE
Wiki Update to Compare Monaco Editor features with other editors 

### ISSUE THREAD

**Issue by prasikumbhare** [microsoft/monaco-editor#126]
Following wiki page compares Javascript code editors available. However i do not see Monaco Editor features. Please update the wiki page for a fair comparision.

[https://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_source_code_editors](https://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_source_code_editors)

**Comment by alexandrudima** [comment]
I'm not sure how this works. Are project authors simply jumping and editing in there or is it that users should "objectively" fill the table in?
