### ISSUE TITLE
monaco doesn't support spellcheck anymore.

### ISSUE THREAD

**Issue by shi-yan** [Microsoft/monaco-editor#1260]
**monaco-editor version:** 0.15.6
**Browser:** chrome
**OS:** ubuntu 17

**Steps or JS usage snippet reproducing the issue:**

monaco.editor.create(document.getElementById("container"), {
	value: "sfaewfwef",
	language: "markdown"
});

judging from the image used for the github repo, monaco used to support spellchecking provided by the web browser.

![monaco]( https://cloud.githubusercontent.com/assets/5047891/19600675/5eaae9e6-97a6-11e6-97ad-93903167d8ba.png)

But the latest version doesn't.

I'm trying to build a markdown editor, spellcheck is a useful feature. Anyway this can be enabled? this should be an editor option.

**Comment by alexandrudima** [comment]
@shi-yan The editor never supported spell checking. What you see there is a semantic error coming in from the TypeScript compiler. It is possible to implement spellchecking by yourself, by reading the text buffer and splitting it into words and looking them up in some dictionary. Then, you can use markers to add warnings or errors.

**Comment by shi-yan** [comment]
Thank you for the answer, my own investigation reached the same conclusion. This can be closed.
