### ISSUE TITLE
IME is not work properly in Chrome 71.

### ISSUE THREAD

**Issue by Alecyrus** [Microsoft/monaco-editor#1261]
**monaco-editor version:** 0.15.6
**Browser:** Chrome 71
**OS:**  macOS mojave

**Steps or JS usage snippet reproducing the issue:**
Just use any  official [example](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options)

### Chrome 71 ( work not properly)
![chrome](https://user-images.githubusercontent.com/13865581/50735267-42f54a80-11e7-11e9-8833-1bf405d086db.gif)

### Safari (work properly)
![safrai](https://user-images.githubusercontent.com/13865581/50735270-51436680-11e7-11e9-974e-5cca2af423f5.gif)

### VsCode (Work perfectly)
![vscode](https://user-images.githubusercontent.com/13865581/50735273-5dc7bf00-11e7-11e9-99df-e3855088295b.gif)

### Need help to solve this weird issue in chrome. Anyone help? I am not sure the reason now, but I 'm gonna to figure it out.

**Comment by Alecyrus** [comment]
safari is ok

**Comment by rebornix** [comment]
@Alecyrus can you share the detailed Chrome version? I can't reproduce this issue on 71.0.3578.98 (Official Build) (64-bit) on Mojave (10.14.2 (18C54)).

**Comment by MutelyMilo** [comment]
请问这个问题是如何解决的？
