### ISSUE TITLE
How to implement Activate Editor from a specific line in Monaco Editor lasted version??

### ISSUE THREAD

**Issue by Kang-Jun-sik** [microsoft/monaco-editor#1262]
**monaco-editor version:** 0.15.*
**Browser:** : Chrome
**OS:** : Window

**Steps or JS usage snippet reproducing the issue:**

I knew the "setEditableRange" function has been removed in 0.15.* version...
**How to implement Activate Editor from a specific line in Monaco Editor lasted version??**
Is it possible in Monaco-editor current version??

**Comment by alexdima** [comment]
`setEditableRange` has been removed and there are no plans to add it back at this time.

**Comment by tavisca-ssharma** [comment]
Are there any other alternatives to setEditableRange in the current version of Monaco in order to disable some lines of text?
