### ISSUE TITLE
Integrate ESM version inside Angular app

### ISSUE THREAD

**Issue by darind** [Microsoft/monaco-editor#1267]
**monaco-editor version:** 0.15.6
**Browser:** Chrome
**OS:** Windows

**Steps or JS usage snippet reproducing the issue:**

I am having trouble integrating the ESM version of the editor with a newly created angular application.

Live sample illustrating the issue: https://stackblitz.com/edit/angular-j9g4da?file=src%2Fapp%2Fapp.component.ts

Steps to reproduce locally:

1. `npm i @angular/cli`
2. `./node_modules/.bin/ng new test-app`
3. `cd test-app`
4. `npm i monaco-editor@0.15.6 --save`
5. `npm i @angular-builders/custom-webpack lite-server --save-dev`
6. Inside `angular.json` replace `"builder": "@angular-devkit/build-angular:browser"` with `"builder": "@angular-builders/custom-webpack:browser"`
7. Inside `angular.json` add `"customWebpackConfig": { "path": "./extra-webpack.config.js" }` to the `"options"` element.
8. `extra-webpack.config.js`:
```javascript
const path = require("path");

module.exports = {
	entry: {
		"editor.worker": "monaco-editor/esm/vs/editor/editor.worker.js",
	},
	output: {
		globalObject: "self",
		filename: "[name].bundle.js",
		path: path.resolve(__dirname, "dist")
	}
};
```
9. `app.component.ts`:
```typescript
import { Component } from "@angular/core";

import "monaco-editor/esm/vs/editor/browser/controller/coreCommands.js";
import "monaco-editor/esm/vs/editor/contrib/find/findController.js";
import * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";
import "monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution";

@Component({
	selector: "app-root",
	templateUrl: "./app.component.html",
	styleUrls: ["./app.component.css"]
})
export class AppComponent {
	constructor() {
		window["MonacoEnvironment"] = {
			getWorkerUrl: () => {
				return "./editor.worker.bundle.js";
			}
		};

		monaco.editor.create(document.getElementById('container'), {
			minimap: { enabled: false },
			lineNumbers: "on",
			renderLineHighlight: "all",
			value: `alert("line 1");
alert("line 2");`,
			language: "javascript"
		});
	}
}
```
10. `index.html`:
```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Monaco Editor Test</title>
	<base href="/">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
	<app-root></app-root>
	<div id="container"></div>
</body>
</html>
```
11. `styles.css`:
```css
#container {
	position: absolute;
	left: 20px;
	width: 300px;
	height: 200px;
	border: 1px solid gray;
}
```
12. Build with: `./node_modules/.bin/ng build --watch`
13. Run with: `./node_modules/.bin/lite-server --baseDir="dist"`

The line numbers overflow under the editor and the cursor doesn't move correctly inside the editor:

![image](https://user-images.githubusercontent.com/270695/50959017-a8d52100-14ca-11e9-9deb-cd8b6445d3fd.png)

**Comment by alexandrudima** [comment]
I'm not 100% sure about the setup and the steps, but the root cause is that CSS is missing. On a regular monaco-editor build, for example, the `glyph-margin` dom node has the following rules that are matched:

![image](https://user-images.githubusercontent.com/5047891/50975426-d67f9180-14ed-11e9-8e5a-928563417524.png)

In your sample, the following rule is missing:
```
.monaco-editor .glyph-margin {
    position: absolute;
    top: 0;
}
```

e.g.:
![image](https://user-images.githubusercontent.com/5047891/50975464-f4e58d00-14ed-11e9-9659-77e03294ff83.png)


In fact it looks like most of the CSS is missing...

**Comment by darind** [comment]
@alexandrudima, thanks for spotting this. You are correct that the Monaco CSS files are missing from the final bundle. It appears that for some reason webpack CSS loader is stripping all the `import './xxxx.css';` from the Monaco ESM javascript files.

The issue only appears when using within an `@angular` app, it works fine in a plain js webpacked app.

**Comment by alexandrudima** [comment]
@darind Unfortunately I don't know sufficient about webpack to understand why that would happen. Don't you need to add a `style-loader` module or something like e.g. https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md#option-2-using-plain-webpack ?

**Comment by jcoutch** [comment]
@darind  - Did you figure out how to get CSS to import?  If so, could you provide an example of what needs to be added/changed?

**Comment by Cyrus-d** [comment]
same problem here with react.
