### ISSUE TITLE
Merge related color names (theming) does not work

### ISSUE THREAD

**Issue by matsgm** [microsoft/monaco-editor#1271]
**monaco-editor version:** 0.15.6
**Browser:** Google Chrome 71
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
- Using both local webpack and the Playground version of Monaco [link](https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-exposed-colors).
- Edit the 'merge.*' color names (for example: 'merge.currentHeaderBackground')
- Paste code with Git merge conflict does not work.

I don't find any reference in Monaco for 'merge.currentHeaderBackground', but in the Merge-Conflict extension in VS Code I can find a reference.

Should these "Color Names" related to merging work in Monaco?

**Comment by alexandrudima** [comment]
That is a VS Code extension. VS Code extensions are not shipped with the Monaco Editor, so there is no code shipped with the Monaco Editor doing what the Merge Conflict extension does in VS Code.

**Comment by alexandrudima** [comment]
This usually indicates some layer-breaking code... I suppose the color definitions are written in the editor, even through they are used by a VS Code extension. 

@aeschli Shouldn't these move to the extension itself?

**Comment by aeschli** [comment]
I assume the list of colors listed in https://github.com/Microsoft/monaco-editor/blob/master/website/playground/new-samples/customizing-the-appearence/exposed-colors/sample.js was retrieved from colorRegistry.ts

colorRegistry contains a set of colors that where intended to be used across UI parts. There might be more colors that don't appear in the Monaco editor. For the color documentation we probably need to be smarter and look for actual references or maybe put a system out to the color registry to see which colors are accessed.

That said, I agree that the merge colors shouldn't have been added to the comon colors and should be removed.

**Comment by alexandrudima** [comment]
I can remove the colors from the samples
