### ISSUE TITLE
getViewModel()

### ISSUE THREAD

**Issue by SteveMattar** [microsoft/monaco-editor#1275]
**monaco-editor version:** 0.15.6
**Browser:** chrome Version 71.0.3578.98
**OS:**  Windows 10

**New feature**
please add a more elegant way to access the viewModel from IEditor
just like you did with getModel()
need a function called getViewModel() that returns the editor._modelData.viewModel

**Comment by turbozv** [comment]
+1

**Comment by maximehamm** [comment]
+1

**Comment by MeetzhDing** [comment]
And now, we even can't access ' editor._modelData.viewModel ',
how can we get the line count including wrapped?

**Comment by buffaybu** [comment]
I tried 0.21.2 and it has `editor._getViewModel()`.
