### ISSUE TITLE
Refresh Azure Cloud Shell Editor via command-line option

### ISSUE THREAD

**Issue by scottaddie** [Microsoft/monaco-editor#1276]
The Cloud Shell Editor provides a refresh button in file explorer. Is it possible to refresh via the command line in the Cloud Shell instance instead?

With VS Code on my development machine, the following trick works today:

```bash
code -r .
```

Any plans to support something similar?

/cc: @CamSoper

**Comment by rebornix** [comment]
@scottaddie you may want to file issues against Cloud Shell ;)
