### ISSUE TITLE
Could not edit, even I set `editor_monaco.updateOptions({readOnly: true})`

### ISSUE THREAD

**Issue by wufeng87** [microsoft/monaco-editor#1277]
**monaco-editor version:** 0.15.6
**Browser:** chrome 71.xx
**OS:**  macOS High Sierra

I just run into a situation that my monaco-editor could not edit anymore, even I set `editor_monaco.updateOptions({readOnly: false})` on browser console.

I wonder if I could add some event to detect what's wrong with my editor.
Thanks

**Comment by rebornix** [comment]
Not sure if you miss typing but setting `editor_monaco.updateOptions({readOnly: true})` will make the editor readonly, does `editor_monaco.updateOptions({readOnly: false})` work for you ?

**Comment by wufeng87** [comment]
`editor_monaco.updateOptions({readOnly: false})` does not work for me, the editor is still not editable. It's not easy to reproduce the issue.

**Comment by chengtie** [comment]
I just have this issue as well.

I have an Excel add-in containing a monaco editor, it worked well before. But recently we could not edit the monaco editor anymore in Excel for Mac.

Does anyone know what happened?

**Comment by wufeng87** [comment]
@chengtie  I use reactjs, add editor.dispose() in `componentWillUnmount` solved this problem.
