### ISSUE TITLE
How to use monaco-editor with es6 and browserify ?

### ISSUE THREAD

**Issue by rkrishnasanka** [microsoft/monaco-editor#1279]
**monaco-editor version:**0.15.6
**Browser: **Chrome (latest)
**OS: ** MacOS - High Sierra

**Steps or JS usage snippet reproducing the issue:**

So I have been trying to use the` monaco-editor` in my project [3DuF](https://github.com/cidarlab/3duf).  

I used npm for the installing the dependency as follows:

`npm install monaco-editor`

And then I try to instantiate the editor in the project :

`import * as monaco from 'monaco-editor`

and build the project using the following browserify command:

`node_modules/.bin/browserify ./src/main.js -t babelify -v --outfile ./cc.js -d -t [ babelify ]`

But even with all of this, it cannot find the module : `monaco-editor`. 

I tried looking around but there's no direct documentation of how I'm supposed to do this. Any help would be really appreciated. I don't really want to modify my entire build process for this thing so please help me out.

Other variants I've tried out are :

`import monaco from 'monaco-editor/esm/vs/editor/editor.main'`

**Comment by DJBMASTER** [comment]
I have the same problem and I've being trying for two days to solve it. I'm trying to get a simple example in typescript running and my IDE complains that it cannot find 'monaco-editor' as a module. Other libraries that I install via npm (.e.g jquery) are found no problem.

**Comment by rkrishnasanka** [comment]
Yeah, I have like 3 projects that could use this editor if I can get this working with `browserify`. Alternatively, I need to explore `webpack`, which I'm not keen to tinker around with at the moment.

**Comment by alexdima** [comment]
Here you can find samples on how to integrate the Monaco Editor -- https://github.com/microsoft/monaco-editor-samples
