### ISSUE TITLE
json schema cpu The overflow

### ISSUE THREAD

**Issue by XTHP** [Microsoft/monaco-editor#1281]
**monaco-editor version:** 0.15.0
**Browser:**
Adding json schame test with setDiagnosticsOptions, json schama is looping nested. In the process of using the Monaco editor, the deep nesting of json will cause the prompt to change to a card, or even cause the browser CPU to run full, is there a solution????

**OS:** 

**Steps or JS usage snippet reproducing the issue:**

```
{
    "$schema": 'http://json-schema.org/schema',
    "uri": "http://test/page.json",
    "fileMatch": ["http://test/schemas/editor0"],
    "schema": {
        "type": "object",
        "properties":{
             "type":{
                   "type":"string",
                   "enum":["container"]
              },
              "body":{
                 $ref: "#"
            }
        }
    }
}
```

```
{
    type:"container",
   body:{
       type:"container",
       body:{
          type:"container",
                 ...
        }
   }

}
```

Lots of json schema cases and a bit more nesting

**Comment by aeschli** [comment]
This got fixed by https://github.com/Microsoft/vscode-json-languageservice/commit/5d2a3404cbcc02452cc4183ca5058ee309b45673
