### ISSUE TITLE
How to translate/localize Monaco Editor strings?

### ISSUE THREAD

**Issue by vingeeek** [Microsoft/monaco-editor#1283]
monaco-editor version:
0.15.6

Browser:
All

OS:
All

Hi, i would to know how to translate/localize Monaco Editor strings. 
I see an [example](https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-localized/index.html) that use this config but when i try to implementing it on my application it load the right "editor.main.nls.**lang**.js" but still remain in English.

I haven't found no more documentation that describe that.

**Comment by lwinhong** [comment]
`require.config({ paths: { 'vs': "monaco-editor/vs" } });
        require.config({
            'vs/nls': {
                availableLanguages: {
                    '*': "zh-cn"
                }
            }
        });`

like this

**Comment by vingeeek** [comment]
Hi @lwinhong, i've been tried this config but it doesn't work. The editor was shown in english.
I checked that all "editor.main.nls.**lang**.js" files have only english strings.

**Comment by alexandrudima** [comment]
Let's track in #822
