### ISSUE TITLE
global extralib

### ISSUE THREAD

**Issue by asifbakht** [microsoft/monaco-editor#1287]
**monaco-editor version:** 0.15.6
**Browser:** Chrome
**OS:** ubuntu 15

**Steps or JS usage snippet reproducing the issue:**

After update to 0.15.x

I am unable to set global library to be available for all editor instances that will be used. I have my own library that have custom functions only available to users. in 0.10 It was fine and my global library was available to all users. But after changing to 0.15 I have to set library every time when editors load.

There should be something like this if we do not want to dispose our library

monaco.languages.typescript.javascriptDefaults.addExtraLib('code', 'name uri', isDisposable);

**Comment by alexdima** [comment]
@asifbakht Can you provide a small sample that reproduces the problem?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
