### ISSUE TITLE
Groovy Support

### ISSUE THREAD

**Issue by jrieken** [microsoft/monaco-editor#129]
_From @soljin on June 29, 2016 21:43_

Add groovy because it's great.

_Copied from original issue: Microsoft/monaco-languages#4_

**Comment by brijeshb42** [comment]
@jrieken https://github.com/brijeshb42/monaco-ace-tokenizer

**Comment by Ruminat** [comment]
If someone doesn't want to use `monaco-ace-tokenizer`, there is my version of Groovy definition for monaco (it's not perfect though, but it works), any suggestions to make it better are welcome,  https://gist.github.com/Ruminat/42364312e90ba5d71875697ede66990e

**Comment by hediet** [comment]
Closing since @Ruminat provided a solution.
Will reopen if someone comes up with a PR.
