### ISSUE TITLE
[Feature Request] Expose way to provide different diffing engine.

### ISSUE THREAD

**Issue by implausible** [microsoft/monaco-editor#1291]
It would be awesome if it were possible to utilize different diff engines than the one currently provided by Monaco/VSCode. An API that allows for Monaco to provide 2 sides of a text and receive back a diff description that can be utilized in the diff view would be swell!

**Comment by hediet** [comment]
This is possible now! (related: #1463)

https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#XQAAAALUAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw417fQEChkl-Hmh5zFo96TZUrxSh_vVMds2o1NvhRn1Q_Jz_xiWcEWBYvsgRh_UGfb9aJC9keirPYccW0saZ5awhpaVVcZankE9SdtPokVpmHCPdEqdapUzjmxuNPN9L-JK7HfymYWEnVdATS-8WSEO1eFuEZE6-2uzSR8CEosNzvIRrAOlpRTUuP5Wl8LwWt3RhpfmSVEfy98Y88wYZ8MiWwLCEdnpfvxe34p8K0IvOnwLE725_Wb8fVwtK0njPRh_qg64OUkQrzrl5mP1VfZSwKhU0cKJP2G-sQARpeSUUC3AiA8mTbcQKaz41v6MzQO4Z8xHg3XqNhMjfl9cw-IcWwE5Rhv6ZMFFarIh8v3CycunqBAsiTwjc3QWJhnXCZkiHAyZPdSvBjdDYnO5G7htKwaOL63Kj5K3nz_HjYe2JoFLgxGBQYe6-imXI108WxVsHqu8v0wrfjqFzzTwYwCGjLw67nMGfm0rZpwyq4QVSSLfEbiyoK43gs1_KGdhkYnzb2k4SNfoy6dkd1MOwTTO-lD08bP5ih_OQ2JENL8D0P9B0tAIez3ewm02f9kyFD
