### ISSUE TITLE
Where is the source code for web based monaco-editor?

### ISSUE THREAD

**Issue by nbarkhina** [microsoft/monaco-editor#1293]
Does it just pull from the vscode repository? how do you separate that out from the thick client.. I'm just trying to understand this repo vs where the code is.

**Comment by hackape** [comment]
@alexandrudima I have a related question here, for a specific release version of `monaco-editor`, I want to locate the corresponding commit in vscode code. How can I do that?

**Comment by alexandrudima** [comment]
@hackape 

You can look at the `/min` version and check for the copyright header, that will contain the commit:

```
/*!-----------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Version: 0.15.5(3d42593a5844407ab71d47b348ea3a8de5fec848)
 * Released under the MIT license
 * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
 *-----------------------------------------------------------*/
```

**Comment by hackape** [comment]
I see, thanks! I suggest adding this information to README.
