### ISSUE TITLE
Template parse errors: Can't bind to 'options' since it isn't a known property of 'ngx-monaco-editor'. 1. If 'ngx-monaco-editor' is an Angular component and it has 'options' input, then verify that it is part of this module. 

### ISSUE THREAD

**Issue by tofiqquadri** [microsoft/monaco-editor#1299]
I have this error in Angular 7 application Integrating Manco edito, I have added the imports in the Modules as well:

Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'ngx-monaco-editor'.
1. If 'ngx-monaco-editor' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'ngx-monaco-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" [froalaEditor]="options" [(froalaModel)]="page.content"></div> -->
            <ngx-monaco-editor [ERROR ->][options]="options" [model]="model"></ngx-monaco-editor>

        </ng-container>
"): ng:///SharedModule/DynamicWizardComponent.html@34:31
Can't bind to 'model' since it isn't a known property of 'ngx-monaco-editor'.
1. If 'ngx-monaco-editor' is an Angular component and it has 'model' input, then verify that it is part of this module.
2. If 'ngx-monaco-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ions" [(froalaModel)]="page.content"></div> -->
            <ngx-monaco-editor [options]="options" [ERROR ->][model]="model"></ngx-monaco-editor>

        </ng-container>
"): ng:///SharedModule/DynamicWizardComponent.html@34:51
'ngx-monaco-editor' is not a known element:
1. If 'ngx-monaco-editor' is an Angular component, then verify that it is part of this module.
2. If 'ngx-monaco-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("          
            [ERROR ->]<ngx-monaco-editor [options]="options" [model]="model"></ngx-monaco-editor>

        </ng-container"): ng:///SharedModule/DynamicWizardComponent.html@34:12
    at syntaxError (compiler.js:2426)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:20600)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:26146)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:26133)
    at compiler.js:26076
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:26076)
    at compiler.js:25986
    at Object.then (compiler.js:2417)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:25985)

Let me know what is the possible solution.

**Comment by Azayzel** [comment]
Can you include your Module file too? You need the FormsModule imported too.

**Comment by tofiqquadri** [comment]
Yes I have FormsModule in the app.modules file. Here is the snippet of mu app.module file:

import { BrowserModule } from '@angular/platform-browser';
import { NgModule, APP_INITIALIZER, Inject, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

import { FormsModule } from '@angular/forms';
import { ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';

import { StoreModule, ActionReducerMap, Store } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';
import { StoreRouterConnectingModule, RouterStateSerializer } from '@ngrx/router-store';

import { ClarityModule } from "@clr/angular";
import { ClarityIcons } from '@clr/icons';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {NgxChartsModule} from '@swimlane/ngx-charts';
import "froala-editor/js/froala_editor.pkgd.min.js";
import { FroalaEditorModule, FroalaViewModule } from "angular-froala-wysiwyg";

import { AppComponent } from './app.component';

import { ReportEffects } from './state/effects/report';
import { ApploadEffects } from './state/effects/appload';

import { AuthGuard } from './_guards/auth.guard';
import { AuthenticationService } from './shared/services/authentication.service';

import { routes } from './routes';
import { reducers, metaReducers, CustomSerializer } from './state';
import { AppRoutingModule } from './app-routing.module';
import { State } from './state/index';
import * as AppActions from './state/actions/report';
import { filter, take } from 'rxjs/operators';
import { SharedModule } from './shared/shared.module';

import { MonacoEditorModule } from 'ngx-monaco-editor';

import '@clr/icons';
import '@clr/icons/shapes/all-shapes';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpClientModule,
    BrowserAnimationsModule,
    NgxChartsModule,
    SharedModule,
    AppRoutingModule,
    StoreModule.forRoot(reducers, {}), // reducers from app/state/index.ts
    StoreRouterConnectingModule.forRoot(),
    EffectsModule.forRoot([ApploadEffects, ReportEffects]),// register
    FroalaEditorModule.forRoot(), FroalaViewModule.forRoot(),
    StoreDevtoolsModule.instrument({
      maxAge: 25 // Retains last 50 states
    }),
    MenuModule,
    ClarityModule,
    MonacoEditorModule.forRoot()
  ],
  providers: [
    {
      provide: RouterStateSerializer, useClass: CustomSerializer
    },
    {
      provide: APP_INITIALIZER, 
      useFactory: initApplication,
      multi: true,
      deps: [[new Inject(Store)]]
    },
  
  ],
  bootstrap: [AppComponent],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})
export class AppModule { }

**Comment by Azayzel** [comment]
When I went down this path I had to import the config and pass that into .forRoot()

https://github.com/atularen/ngx-monaco-editor/blob/master/README.md

**Comment by tofiqquadri** [comment]
Yes, I tried that too but it still gave me same error.

**Comment by abhisekuit** [comment]
@tofiqquadri 
Were you able to resolve this issue?

**Comment by tofiqquadri** [comment]
@abhisekuit Yes, I solved this issue for my requirement.
