### ISSUE TITLE
Rust language support

### ISSUE THREAD

**Issue by jrieken** [Microsoft/monaco-editor#130]
_From @miqid on June 22, 2016 14:4_

Howdy.

Is somebody working on providing basic support for [Rust](https://www.rust-lang.org/) as a language option for the Monaco Editor? If not, I'm willing to throw my hat into the ring to give it a shot.

I've previously authored a Rust grammar package for the Atom editor, which is based on a TextMate-like system. However, it seems like the parser used to provide syntax highlighting for the Monaco Editor is more versatile.

_Copied from original issue: Microsoft/monaco-languages#3_

**Comment by jrieken** [comment]
_From @egamma on June 22, 2016 17:29_

I'm not aware of anybody building a colorzer for Rust. Here is the playground to get started with a colorizer https://microsoft.github.io/monaco-editor/monarch.html

**Comment by alexandrudima** [comment]
Thanks to @systemsoverload this has been implemented! :heart:
