### ISSUE TITLE
question, the editor api is same as the language server protocol ？

### ISSUE THREAD

**Issue by zgm4z** [Microsoft/monaco-editor#1302]
the editor api is same as the language server protocol ?
 can i think  editor.position == lsp.position?

**Comment by rcjsuen** [comment]
@zgm4z Line numbers start on 1 in Monaco whereas they start on 0 in the LSP so I definitely would not consider them to be the same.

**Comment by zgm4z** [comment]
@rcjsuen thanks reply，I get it。
