### ISSUE TITLE
Monaco Diff Editor incorrectly counting line changes

### ISSUE THREAD

**Issue by Azayzel** [microsoft/monaco-editor#1304]
**monaco-editor version:** 0.15.6
**Browser:** IE11
**OS:** Windows Server 2012 R2(win8.1$

**Steps or JS usage snippet reproducing the issue:**
Background: 
    I have a Linux machine that is posting files to a .net core API.
    The API reads the contents of the file and stores it as a byte array in SQL.
     * ASCII encoding
     * About 35k lines (1.6mb)
    The client go to view the diff in the web app (loading Monaco with AMD), Monaco displays the two files as having only one big diff. Not multiple like it does in vscode. 

If I copy+paste the first 100 lines into a string literal in .createModel() it displays correctly. Maybe a buffer thing?

I have tried normalizing EOL before feeding it to the creatModel() fn, to no avail. I’ve also tried writing the string to a UTF8 file and reading that file back in before sending up to the client(in hopes of letting Windows normalize the EOL).
I’ve went through every possible editor and diff editor options and nothing seems to work. If I copy and paste the code from the diff editor (in browser) into vscode, it shows the line changes correctly. Any ideas as to what the issue could be? 

See attached image for incorrect results. Thank you!!
![956536c2-8838-408b-a688-bab54483da82](https://user-images.githubusercontent.com/17281152/52302983-c4fa9f80-295c-11e9-939f-4ac5d2c77581.png)

**Comment by Azayzel** [comment]
It seems to compute the diffs correctly when I pass the first 500k characters (.subStr(0.500000)). After that it seems to fail and fail fast.

**Comment by Azayzel** [comment]
Is there a good method to feed or add to the model contents after the diff has been calculated?

I’m thinking I may have to loop the string and add in chunks, but I need to only calculate the diff of what’s being added, leaving the previous untouched.

**Comment by alexandrudima** [comment]
The diff algorithm is implemented to "give up" after 5 seconds of computation time. That means it will give perhaps useless, but still technical correct results, like in this case where it creates a huge diff hunk.

This is controlled by this constant here and is currently not configurable -- 
https://github.com/Microsoft/vscode/blob/0a4a3b98282175a82a819b70d2bbe46475e1ebd0/src/vs/editor/common/diff/diffComputer.ts#L10

**Comment by BitFlipp3r** [comment]
Are there any workarounds? Maybe some options to disable to speed up computation?

**Comment by nrayburn-tech** [comment]
@alexdima this looks like it is mostly setup to be passed as an option now, with one exception.
[diffComputer.ts](https://github.com/microsoft/vscode/blob/127c34484bca06c46b0345eb03f87e0ca70eaddc/src/vs/editor/common/diff/diffComputer.ts#L309) uses the min between the option and the value 5000.  [diffEditorWidget.ts](https://github.com/microsoft/vscode/blob/d6e842b665990c663ef21718a65e73c9bcc2d730/src/vs/editor/browser/widget/diffEditorWidget.ts#L256) sets a default of 5000, so there shouldn't be any issue with removing the min and the value 5000 from `diffComputer.ts`.  The only issue I can think of is if vscode uses the same `diffComputer.ts` file, but I can't tell if it does.

**Comment by hediet** [comment]
The diff editor now supports custom diff algorithms. This allows you to work around this limitation.
