### ISSUE TITLE
How I can override the allowed html tags

### ISSUE THREAD

**Issue by joekel** [microsoft/monaco-editor#1308]
Hi , 

I’m trying to use Monaco as an html editor and provide only some white listed tags (example allow only few tags and attributes)

I tracked down Monaco structure and found Monaco editor uses Monaco html and this one use the language service dependency.

Do I can overwrite the HTML_TAGS constant ? 

Thanks

**Comment by alexandrudima** [comment]
You can fork the `monaco-html` project and use directly the `monaco-editor-core` npm library and load your fork of `monaco-html` with `monaco-editor-core`. Here is some information on how the `monaco-editor` is built -- https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md
