### ISSUE TITLE
Efficient storing the ViewState (Folding State) of Monaco-editor

### ISSUE THREAD

**Issue by Nikolsi** [microsoft/monaco-editor#1311]
Dear all,

I am developing a tiny code editor aka Playground, which should visualize my seed projects.

Each seed project contains two models represented as Tabs: HTML & JS.
During changing the examples I reuse these two models and update them with the values of the selected example using *jsModel.setValue() & htmlMode.setValue()*. Each example might contain the #region block, which contains the already mentioned code in previous examples. I would like to hide it when an example is selected. Thus, I trigger '***editor.foldAllMarkerRegions***' handler.

All these steps produce unpleasant appearance: the code is shown -> the code block folded. However, I would like to see the code which has already folded!

A possible solution in my mind:

 - At initialize time

 - map between models
 - set model to the editor
 - trigger '***editor.foldAllMarkerRegions*** handler'
 - saveViewState to Map<example, viewState>

 - At run-time

 - get viewState for the selected example from Map
 - editor.restoreViewState

**The questions are:**

 - how to pre-set the folding state for each model so, that when I call *setModel()* the code will be already folded?
 - can I do it somehow on background, maybe second Monaco instance?
 - maybe easier way, e.g. how to trigger folding before rendering the model?

**monaco-editor version:** 0.15.5
**Browser:**
**OS:** 

**StackOverflow question: https://stackoverflow.com/questions/54633440/efficient-storing-the-viewstate-folding-state-in-monaco-editor**

**Comment by alexdima** [comment]
In the meantime, I believe `saveViewState()` and `restoreViewState()` now contain folding information. This can be seen when switching tabs on https://microsoft.github.io/monaco-editor/playground.html , the folded regions will be maintained.
