### ISSUE TITLE
No way of setting inline font size, even with decorations

### ISSUE THREAD

**Issue by javisperez** [microsoft/monaco-editor#1313]
**monaco-editor version:** 0.15.6
**Browser:** Chrome
**OS:**  macOS

Hello, I've been trying to mimic this UI (please notice the titles font sizes for `Support` and `Styling`):
![image](https://user-images.githubusercontent.com/4766570/52639537-df77d000-2eaa-11e9-9b75-8d9fba9deba3.png)

But I've tried with basically every example on the playground and for what I understand, seems like decorations are the way to go, but since decorations are overlays of the content, it won't actually affect the font size of it. 

I've tried checking the content on change and getting the line and column number dynamically from there to set the decoration and even though I was able to add a decoration, I'm worried about the performance for large documents (as I got the line number by splitting by `\n`, I didn't find a way on the API to get a line/column info based on content position).

Is there a clean way to achieve this? Thank you a lot.

**Comment by alexandrudima** [comment]
You can use inline decorations (`inlineClassName`) and change aspects of the font.

https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations

e.g.
![image](https://user-images.githubusercontent.com/5047891/53560668-36d59b80-3b4d-11e9-8e1e-09aef53ba1d5.png)
