### ISSUE TITLE
Wrong brackets completion

### ISSUE THREAD

**Issue by lgabryel** [microsoft/monaco-editor#1315]
**monaco-editor version:** 0.12.0
**Browser: chrome**
**OS: windows 10** 

When in invoke of function parameters use, other function, last typing of bracket was ignored and brackets was wrong closed, despite the odd number of brackets.

![brakets](https://user-images.githubusercontent.com/15322615/52697978-e66a1580-2f72-11e9-82dd-f0da819ce14d.gif)

**Comment by alexandrudima** [comment]
This is how this feature works ... it is simply overtyping closing brackets all the time. This can be disabled via `"autoClosingBrackets": "never"`
