### ISSUE TITLE
Can't register a code as snippet and make it works.

### ISSUE THREAD

**Issue by inocencio** [microsoft/monaco-editor#1316]
The following code: 

insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet, 

Isn't right, raising this error: Uncaught TypeError: Cannot read property 'InsertAsSnippet' of undefined. Rather that even I specify 4 for "insertTextRules" attribute nothing happens.

I need this attribute to "registerCompletionItemProvider".

**Comment by rcjsuen** [comment]
@inocencio I suggest you try to reproduce the problem in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html).

This code works fine for me.
```JavaScript
monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        return {
            suggestions: [
                {
                    label: '"options"',
                    kind: monaco.languages.CompletionItemKind.Function,
                    insertText: '"${1:option1}": "${2:option2}"',
                    insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet
                }
            ]
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "json"
});
```

**Comment by inocencio** [comment]
@rcjsuen 

Thank you for reply.

I'm trying to custom a language, so I configured the environment to run on Electron and Monaco Editor so far. Running your sample, it executes just fine, however, I cannot reproduce my code on Playground and I don't know why yet.

Basically, I'm loading from dev version:

`
const path = require('path');
const amdLoader = require('../node_modules/monaco-editor/dev/vs/loader.js');
const amdRequire = amdLoader.require;
const amdDefine = amdLoader.require.define;
`

The relative code to a snippet is:

`
			//Register the custom completion function into Monaco Editor
            monaco.languages.registerCompletionItemProvider(lang, {
                provideCompletionItems: function(model, position, context, token) {
                    // let textUntilPosition =
					// 	model.getValueInRange(new monaco.Range(1, 1, position.lineNumber, position.column))
					// 	model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column})

					//console.log('Text: ' + textUntilPosition)
                    return [
                        {
                            label: 'sop',
                            kind: monaco.languages.CompletionItemKind.Snippet,
                            documentation: "Show a debug message on console terminal",
                            insertText: 'show_debug_message($0);'
                        },
                        {
                            label: 'ifelse',
                            kind: monaco.languages.CompletionItemKind.Snippet,
                            insertText: [
                                'if ${1:condition} {',
                                '\t$0',
                                '} else {',
                                '\t',
                                '}'
                            ].join('\n'),
                            //insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                            documentation: 'If-Else Statement'
                        }
                    ];
                }
            });
`

If I uncomment this line: **//insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,**

it raises the error I mentioned before, even if I specify "insertTextRules: 4" for this attribute. If I remains it as commentary, it executes like a raw text, not a snippet.

**Comment by alexandrudima** [comment]
@inocencio Perhaps you are using an older version of the monaco editor? i.e. haven't upgraded to the latest one?
