### ISSUE TITLE
Delay hover cannot be changed

### ISSUE THREAD

**Issue by jenjen75** [Microsoft/monaco-editor#1318]
**monaco-editor version:** 0.15.6
**Browser:** Chrome 72.0.3626.81
**OS:** Debian 10 Buster

**Steps or JS usage snippet reproducing the issue:**

Hello,

I try to change hover delay (default 300ms) and according to the documentation, it can be change like that (hover set to 1000ms in exemple below) :
```
monaco.editor.create(document.getElementById("container"), {
    value: '\n\nHover over this text',
    language: 'mySpecialLanguage',
    hover: { delay: 1000, enabled: true }
});
```
But the hover delay is not changed, you can try with this link : https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example

Documentation link : https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorhoveroptions.html#delay

**Comment by alexandrudima** [comment]
This works when running out of sources.
