### ISSUE TITLE
CSS Inline coloring missing

### ISSUE THREAD

**Issue by jrieken** [Microsoft/monaco-editor#132]
_From @basarat on June 27, 2016 7:13_

Looking at the sample : https://microsoft.github.io/monaco-editor/index.html css no longer has the nice color inline widget that it used to :rose: 

![image](https://cloud.githubusercontent.com/assets/874898/16371330/548fb46e-3c89-11e6-9461-7de5f3a075e7.png)

refs https://github.com/Microsoft/vscode/issues/8172

_Copied from original issue: Microsoft/monaco-css#2_

**Comment by jrieken** [comment]
_From @alexandrudima on June 28, 2016 8:48_

We had to take it out briefly to not get blocked by this when we extracted monaco-css, but we plan to bring it back ASAP

**Comment by gimenete** [comment]
Any plans to put it back?

Also, any plans to add the color picket widget: https://twitter.com/code/status/897498143536758784

<img width="589" alt="screen shot 2017-09-01 at 11 06 12" src="https://user-images.githubusercontent.com/50486/29963006-987948fa-8f05-11e7-8713-a022cbf53f9a.png">

**Comment by glixlur** [comment]
Is there any way I can help with this?

**Comment by aeschli** [comment]
@glixlur Thanks for reminding, I pushed a fix
