### ISSUE TITLE
colorizing failed in function componentDidMount of React component

### ISSUE THREAD

**Issue by XDfield** [microsoft/monaco-editor#1323]
**monaco-editor version:** 0.15.6
**Browser:** chrome
**OS:** windows

**Steps or JS usage snippet reproducing the issue:**
I make a React component to show code snippet like this:
```javascript
class Snippet extends React.Component {
  constructor(props) {
    super(props);
    this.state = { context: props.context }
  }

  componentDidMount() {
    const {context} = this.state;
    const lang = getLang(context);
    monaco.editor.colorize(context, lang).then(result => {
      console.log(result);
      this.setState({ context: result });
    )
  }

  render() {
    return  <div dangerouslySetInnerHTML={{_html: this.state.context}} />
  }
}

class App extends React.Component {
  contructor(props) {
    super(props);
    this.state = { show: true };
    this.toggle = () => this.setState({ show: !this.state.show })
  }

  render() {
    return (
      <div>
        <button onClick={this.toggle}>toggle</button>
        {this.state.show && <Snippet context={this.props.context} />}
      </div>
    )
  }
}
```
When I render this component, the content of `context` shows, but it colorized failed. I print the colorized result and found that it has been converted to html code but not dyed.
Then I click the toggle button twice, the colorization of `Snippet` works fine.
I am very confused about the behavior of this same input producing different outputs.

**Comment by alexdima** [comment]
I have now pushed a change where languages tokenizers are registered earlier via https://github.com/microsoft/monaco-languages/commit/75cb14f8f020e1491cae6d101cdc06837e01df86

I believe that will make the colorizer more reliable, as it now knows if there are pending languages to be loaded or not.
