### ISSUE TITLE
[Regression in 0.15.0] Typescript suggestion icons disappear or render strangely when selected.

### ISSUE THREAD

**Issue by astegmaier** [Microsoft/monaco-editor#1324]
**monaco-editor version:** the issue is a regression that firs repros in `0.15.0`, but not `0.14.3`
**Browser:** Chrome, Firefox, Edge
**OS:** Windows 10

When upgrading monaco editor to version `0.15.6` from version `0.14.3` in my application, I noticed new behavior with icons disappearing from the suggestions menu (a.k.a "intellisense" or "autocomplete"). I can reproduce in the [monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html). Simply type something that triggers the autocomplete menu, and hit the 'up' and 'down' errors, and you should see icons sometimes disappear as they get selected:

![repro2](https://user-images.githubusercontent.com/1000369/53283474-ddf4a600-36fb-11e9-9aec-63417ae1245e.gif)

I see similar results in chrome, firefox, and edge.

I've only noticed the problem with TypeScript, and the kinds items affected seem to include:
- interfaces
- certain kinds of variables whose type is an inferred interface (see the example above).

The problem seems suspiciously similar to #553, although that issue is marked as fixed. The build where I can confirm the issue does not exist (`0.14.3`) was before the fix to that issue, so it's possible that this is a regression introduced by that fix? FWIW, it does not appear to repro in VSCode.

**Comment by astegmaier** [comment]
I have codepen repros that demonstrate that this is a regression introduced in version `0.15.0`:

- Here is version `0.15.0`, which shows the bug: https://codepen.io/astegmaier/pen/bZGgVq
- And here is version `0.14.3` which does not have the bug: https://codepen.io/astegmaier/pen/KEKavo

To see the issue, just type 'm' on a new line and scroll up and down with the arrow keys.

**Comment by alexandrudima** [comment]
I can reproduce on 0.15.x, but I can no longer reproduce on master.

**Comment by astegmaier** [comment]
I can confirm that this is fixed in 0.16.0 - see https://codepen.io/astegmaier/pen/pYaKOW

Thanks!
