### ISSUE TITLE
How to open files in monaco-editor ? Specially large files just like VS code does.

### ISSUE THREAD

**Issue by sameeravhad119** [microsoft/monaco-editor#1330]
"monaco-editor": "^0.15.6",
"monaco-editor-webpack-plugin": "^1.7.0",
 "OS":  windows and mac
 I am using electron . 

I am trying to display a file content in a monaco editor. All the examples I have seen so far has hard coded values . In all examples, '_model_' is created with hard coded '_value_' .like following example.

```
monaco.editor.create(document.getElementById("container"), {
	theme: 'vs',
	value: 'hard coded value that is to be display in editor'
});
```

So I  read a file first and saved the file content into string variable. And then assigned to _value_
attribute.  This is working fine in case of small files. But I have files with size > 100MB. In those cases , it is not working properly.

Is there a way to solve this ? How VS code open large files in a just a second with the help of monaco editor ?

**Comment by alexandrudima** [comment]
This is the method we use in VSCode -- https://github.com/Microsoft/vscode/blob/d6c200ea57fc3104af1c237dfd16ff0d83c3ad2a/src/vs/editor/common/model/textModel.ts#L48

**Comment by poly74yu** [comment]
Is this a code editor just like Visual Studio Code? I don't understand how to open it (and I am not sure I understand how to install it). Can you do Pyhon/R/Julia development just like in Visual Studio Code?

**Comment by liesislukas** [comment]
@poly74yu Visual Studio Code is IDE which uses monaco editor as one of the elements to make VS happen. It's like a super-smart "[textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea)" field that you can include on your website and have the editor functionalities. This won't deploy together all the stuff that VS offers but you will get the editor like you can see on the [readme](https://github.com/microsoft/monaco-editor/blob/master/README.md). 

![image](https://user-images.githubusercontent.com/2733862/64166613-1f56d280-ce50-11e9-8f91-ff73182e93be.png)

**Comment by Ricardo-Paul** [comment]
Than how can I open a project on it?
just like in Vs code we run code .

**Comment by rcjsuen** [comment]
@Ricardo-Paul You need to have a web server that is serving the files to your browser.

Perhaps you may be interested in [Gitpod](http://gitpod.io) and other such projects.
