### ISSUE TITLE
Error using JSON schema

### ISSUE THREAD

**Issue by fulldecent** [Microsoft/monaco-editor#1331]
# Test case:

```json
{
	"$schema": "http://json.schemastore.org/package"
}
```

# Error

> Unable to load schema from 'http://json.schemastore.org/package'. No schema request service available

**Comment by aeschli** [comment]
The JSON worker of the monaco editor does not try to load any references by default.
But if you enable the option [`enableSchemaRequest`](https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L5800), the browser's [fetch-API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is used.

**Comment by fulldecent** [comment]
Can this be enabled on https://microsoft.github.io/monaco-editor/?

**Comment by aeschli** [comment]
Not sure why you want this to be enabled.
But if you want to try it out, use this in the [playground](https://microsoft.github.io/monaco-editor/playground.html)

```
monaco.languages.json.jsonDefaults.diagnosticsOptions.enableSchemaRequest = true;

monaco.editor.create(document.getElementById("container"), {
	value: '{\n  "$schema": "https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/package.json",\n  "author": {}\n}',
	language: "json"
});
```

**Comment by aeschli** [comment]
BTW, the alternative of enabling loading is passing the schema through the configuration.
As you will see, there are restrictions on what web pages can load.

**Comment by fulldecent** [comment]
Very cool, thank you. I always use JSON with schema, very helpful.

**Comment by oldrich-s** [comment]
@aeschli When I include `monaco.languages.json.jsonDefaults.diagnosticsOptions.enableSchemaRequest = true;` I get:

```
Cannot assign to 'enableSchemaRequest' because it is a constant or a read-only property.

(property) monaco.languages.json.DiagnosticsOptions.enableSchemaRequest?: boolean | undefined

If set, the schema service would load schema content on-demand with 'fetch' if available`
```

Is that a bug?

**Comment by aeschli** [comment]
You are right, the default settings are not meant to be modified.
This is the currect code:
```ts
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({ validate: true, allowComments: false, schemas: [], enableSchemaRequest: true})

monaco.editor.create(document.getElementById("container"), {
	value: '{\n  "$schema": "https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/package.json",\n  "author": {}\n}',
	language: "json"
});
```
