### ISSUE TITLE
Is it possible to lazy load some features?

### ISSUE THREAD

**Issue by pomber** [microsoft/monaco-editor#1332]
#845 asks about lazy loading the editor. I want to load the editor and then lazy load some features.  

Currently I have a `features.js` file with something like this:
```js
import "monaco-editor/esm/vs/editor/editor.all.js";
import "monaco-editor/esm/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp.js";
import "monaco-editor/esm/vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard.js";
import "monaco-editor/esm/vs/editor/standalone/browser/inspectTokens/inspectTokens.js";
import "monaco-editor/esm/vs/editor/standalone/browser/quickOpen/gotoLine.js";
import "monaco-editor/esm/vs/editor/standalone/browser/quickOpen/quickCommand.js";
import "monaco-editor/esm/vs/editor/standalone/browser/quickOpen/quickOutline.js";
import "monaco-editor/esm/vs/editor/standalone/browser/referenceSearch/standaloneReferenceSearch.js";
import "monaco-editor/esm/vs/editor/standalone/browser/toggleHighContrast/toggleHighContrast.js";
```
And I create the editor with: 
```js
import * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";
import "./features";

const editor = monaco.editor.create(document.getElementById("container"), {});
```

I'm trying to lazy-load `features.js` so I change it to:
```js
import * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";

const editor = monaco.editor.create(document.getElementById("container"), {});

import("./features.js").then(() => {
  editor.updateOptions({});
  editor.render();
});
```

But it doesn't work.  
If I create the editor after loading `features.js` it does work:
```js
import * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";

import("./features.js").then(() => {
  const editor = monaco.editor.create(document.getElementById("container"), {});
});
```
But it isn't what I want. I want it to be interactive as soon as possible.

You can see the full code in this PR pomber/write-code-online#3

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
