### ISSUE TITLE
IntelliSense menu is blank

### ISSUE THREAD

**Issue by cd711** [microsoft/monaco-editor#1336]
**monaco-editor version:** 0.15.6
**Browser:** Chrome 72, Safari ie edge
**OS:** MacOS Window
**Steps or JS usage snippet reproducing the issue:**

typescript in react project
npm install monaco-editor

`
import * as monaco from "monaco-editor";
monaco.editor.create(document.getElementById("ide"), {
            value: "",
            language: "javascript"
        })
`
<img width="693" alt="qq20190301-122448 2x" src="https://user-images.githubusercontent.com/3389516/53616642-918af800-3c1e-11e9-9749-75153007579b.png">

**Comment by alexandrudima** [comment]
Perhaps there are some CSS clashes ?
