### ISSUE TITLE
Custom themes creation

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/monaco-editor#1338]
Currently creating a theme from scratch is a bit challenging. [Here](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/standalone/common/themes.ts) one can find the default themes and [here](https://github.com/brijeshb42/monaco-themes) there are some custom themes other people have made.

Custom themes, like [this one](https://github.com/brijeshb42/monaco-themes/blob/718a06000caa4ee21cd1ce4c5a1f5b2fe9acc0d1/themes/GitHub.json#L13), are theming tokens that aren't themed by the default themes. What's the deal with that? Did those token get deprecated at some point? Are they supported but undocumented?

Also it's a bit difficult to know what each token is going to theme sometimes, it would be _massively_ useful if a sample code snippet that used all the tokens were provided, so that one could easily and immediately see the changes.

**Comment by alexandrudima** [comment]
To date, the largest amount of tokenizers written for the Monaco Editor resides at https://github.com/Microsoft/monaco-languages/tree/master/src

Most of them are written to adhere to certain patterns, like using `comment` for comments. But sometimes, the people that write those like to go crazy and geek out on creating all kinds of interesting tokens, like e.g. `string.heredoc.delimiter`.

If you are writing a theme, and happen to really really want to customize ruby and its `string.heredoc.delimiter`, you can target that token in your theme. If the token is not produced by any other language, then it bears almost no cost (except a very small trie lookup cost when applying the theme to the tokens)...

**Comment by fabiospampinato** [comment]
Thanks for the explanation 👍
