### ISSUE TITLE
[Accessibility] Color Contrast: Color contrast ratio for numbers in light theme in the editor is 4.48:1 < 4.5:1

### ISSUE THREAD

**Issue by preetriti1** [microsoft/monaco-editor#1345]
**monaco-editor version:** 0.14.3
**Browser:** Chrome, version 72.0.3
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
1. Use the light theme for monaco editor.
2. Inspect the color contrast for number values in json.

This is less than the required contrast according to aria-rules which is 4.5:1

![image](https://user-images.githubusercontent.com/48265693/53864350-1a988b00-3fa1-11e9-9f1c-0e39e9210bea.png)

**Comment by alexdima** [comment]
The editor ships with a high contrast theme. The embedder can use it when desired, the editor switches to it when the OS has high contrast, and the end user can activate it via `F1 > Toggle High Contrast Theme`. See more at https://github.com/microsoft/monaco-editor/wiki/Accessibility-Guide-for-Integrators

**Comment by alexdima** [comment]
This has been fixed in the meantime, but my comment above is incorrect. 

The default color of number tokens inside the editor has been changed to `#098658` which has a contrast ratio of `4.599` against `#fffffe`. The fix is available in the latest monaco editor realease.
