### ISSUE TITLE
All i18n files became English since v0.15.0

### ISSUE THREAD

**Issue by troy351** [Microsoft/monaco-editor#1346]
**monaco-editor version:** 0.X.Y
**Browser:**
**OS:** 

**Steps or JS usage snippet reproducing the issue:**
@alexandrudima

**Comment by lwinhong** [comment]
@alexandrudima

**Comment by mattmasson** [comment]
I think this is tracked as #822

**Comment by troy351** [comment]
@mattmasson you are right, close this issue then.
