### ISSUE TITLE
Add documentation on how to build a realease to README.md

### ISSUE THREAD

**Issue by janhaertel** [Microsoft/monaco-editor#1348]
Hi I had to fiddle around a lot and only just now found out how to correctly build this project by reading CONTRIBUTING.md.
It would be way more convenient if this information was available on README.md, instead of browsing to issues and then trying to create a new issue where this info is firstly shown.

**Comment by alexandrudima** [comment]
Sorry, but this is already documented in the README.md:

![image](https://user-images.githubusercontent.com/5047891/54213046-0e9e5300-44e4-11e9-97f3-1051ccfc1de3.png)

**Comment by janhaertel** [comment]
Ah ok didn't see that, I'm used to just checking the README.md just for the build command and read the rest later. My fault.
