### ISSUE TITLE
Change shortcuts

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#1350]
**monaco-editor version:** 0.16.0

What's the recommend way to change a shortcut assigned to a default command?

Say I want to bind `ctrl+alt+r` to the `toggleFindRegex` command rather than the default one, how should I go about it?

**Comment by fabiospampinato** [comment]
I couldn't find a better way to do this, the only one I could find is patching the function that register those commands:

```js
import {Command} from 'monaco-editor/esm/vs/editor/browser/editorExtensions.js';

    const _register = Command.prototype.register;
    Command.prototype.register = function () {
      const patcher = patches[this.id];
      if ( patcher && patcher ( this ) === false ) return; // Disabled
      return _register.apply ( this, arguments );
    };

```

**Comment by hyvyys** [comment]
@fabiospampinato Can you elaborate?

What is `patches`? How do I get the command's `id`?

**Comment by hyvyys** [comment]
This worked for me, instead of the method above.

```js
      function changeCommandKeybinding(editor, id, keybinding) {
        editor._standaloneKeybindingService.addDynamicKeybinding('-' + id);
        editor._standaloneKeybindingService.addDynamicKeybinding(id, keybinding);
      }

      changeCommandKeybinding(
        editor,
        'editor.action.triggerSuggest', 
        monaco.KeyMod.CtrlCmd | monaco.KeyCode.US_SLASH
      );
```

**Comment by hyvyys** [comment]
Btw if anyone is looking for the names of the builtin commands, I modified the code from the OP to do this:

```
function (search) {
  const _register = Command.prototype.register;
  Command.prototype.register = function () {
    if (!search || this.id.toLowerCase().indexOf(search.toLowerCase()) > -1)
      console.log(this.id);
    return _register.apply(this, arguments);
  };
}
```

I couldn't find a list of commands anywhere, and didn't feel like taking guesses all night.

**Comment by alexdima** [comment]
Let's track in #102
