### ISSUE TITLE
Playground - completion-provider-example is missing 'range' property

### ISSUE THREAD

**Issue by oldrich-s** [microsoft/monaco-editor#1352]
I see that:

> CompletionItem.range is now mandatory. Most times, you can use model.getWordUntilPosition() to get a good range.

I have no idea how to use the `model.getWordUntilPosition()` so I thought I would find it in the playground example:

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

but it looks like the example was not updated yet.

**Comment by spahnke** [comment]
> so I thought I would find it in the playground example

That's what I hoped as well. Anyway, after a little experimentation I came up with the code below which seems to work for my use cases. I don't know if there is a better/more correct way to do that though.

```ts
provideCompletionItems: (model: monaco.editor.ITextModel, position: monaco.Position, context: monaco.languages.CompletionContext, token: monaco.CancellationToken) => {
	const word = model.getWordUntilPosition(position);
	const range: monaco.IRange = {
		startLineNumber: position.lineNumber,
		endLineNumber: position.lineNumber,
		startColumn: word.startColumn,
		endColumn: word.endColumn
	};
	...
}
```

Hope it helps!

**Comment by iknityanand** [comment]
@spahnke It worked! thanks a ton!.
