### ISSUE TITLE
Is it possible to find a position in the editor having only an original string and the indexes of beginning and ending?

### ISSUE THREAD

**Issue by PavelGriza** [Microsoft/monaco-editor#1359]
There might be a need to apply some changes from the server based on the original string and a sub string of it. There will be very useful to be able to get a position in the editor just using indexes of the original string.

For example I want to highlight a piece of code with setModelMarkers:

`setModelMarkers(model: ITextModel, owner: string, markers: IMarkerData[]): void`

But it requires IMarkerData items with specified start/end line/column.

Is there any way how to achieve such functionality?

**Comment by spahnke** [comment]
You can use `getPositionAt` on the model object to convert an offset to a position object. [See here.](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#getpositionat)

**Comment by PavelGriza** [comment]
@spahnke thank you very much for your help.
It works as needed.
