### ISSUE TITLE
Where is the complete source code of this editor?

### ISSUE THREAD

**Issue by Imputes** [microsoft/monaco-editor#1362]
# I wanna this monaco-editor newest version source code.

**Comment by blutorange** [comment]
From the readme:

> Please note that this repository contains no source code for the code editor, it only contains the scripts to package everything together and ship the monaco-editor npm module.

You can find an overview of the modules it uses  in https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md

**Comment by BeginnerGitHub** [comment]
Hello,

Thanks for the link given below ...
But I would like to know if you know where we can find the sources (TypeScript files) of monaco-editor-core...
In the link above there are only sourcemap of TypeScript files ...
Thank you.

**Comment by Imputes** [comment]
> Hello,
> 
> Thanks for the link given above ...
> But I would like to know if you know where we can find the sources (TypeScript files) of monaco-editor-core...
> In the link above there are only sourcemap of TypeScript files ...
> Thank you.

This is actually what I want to ask.
Maybe Microsoft stuffed something like a monitoring system, or something that they don’t want you to know.

**Comment by BeginnerGitHub** [comment]
> 
> This is actually what I want to ask.
> Maybe Microsoft stuffed something like a monitoring system, or something that they don’t want you to know.

I think there are several ways to recover TypeScript source files:

1- With a code that restores the source files from sourcemap (as do browsers).

2- Retrieve the list of files (in sourcemap) and copy the source files from the folder src in vscode.

Sorry my english is bad ..

**Comment by alexdima** [comment]
Here are the sources of the monaco editor core --> https://github.com/Microsoft/vscode This is explained in detail at https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md
