### ISSUE TITLE
Clicking at the end of a line that ends in whitespace does not position the cursor, in IE

### ISSUE THREAD

**Issue by roblourens** [Microsoft/monaco-editor#137]
I see Microsoft/vscode#2802 - this works in Edge, but not IE.

```
let x = 1; // trailing whitespace:             
let y = 2; // no trailing whitespace
```

If I click  after the end of line 1, the cursor disappears. If I click at the end of line 2, the cursor is placed at the end of the line correctly.

**Comment by alexandrudima** [comment]
Enabling stop on all exceptions, `TextRange.moveToPoint` throws when the mouse is after the line with trailing whitespace. This does not happen when `renderWhitespace` is off. I will completely disable `renderWhitespace` for IE11:

![image](https://cloud.githubusercontent.com/assets/5047891/18133359/99a3ce20-6f9a-11e6-8071-d292499227b0.png)

**Comment by alexandrudima** [comment]
I think I found a workaround and still allow `renderWhitespace` to work...
