### ISSUE TITLE
Object Expected error thrown in IE 11 in async.js call to this.doResolve!()

### ISSUE THREAD

**Issue by obeliskos** [microsoft/monaco-editor#1376]
**monaco-editor version:** 0.16.1
**Browser:**
IE 11
**OS:** 
Windows 10

**Steps or JS usage snippet reproducing the issue:**
Visit https://microsoft.github.io/monaco-editor/playground.html using IE 11
Open F12 tools to view console
Hover over a method or variable to get intellisense popup

Result : 
definition is shown but a console error is also thrown

In looking into this, the error thrown is raised from async.ts which comes from vscode repo and the relevant line is : 
https://github.com/Microsoft/vscode/blame/608fc2cee2f1a4c832d8c23b9d4e28805ddf6041/src/vs/base/common/async.ts#L211

It would seem they are using a non-null assertion operator which appears to only override compiler warnings, it does not seem to generate runtime checks : 
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator

Since I believe Monaco editor has shifted to new promise polyfill, I suspect there is issue causing those promises to not be defined.

**Comment by salileo** [comment]
I am seeing the same behavior on my end too. Could this please be prioritized, as it is triggering monitoring alerts due to this error which doesn't even seem to cause any user experience issues.
