### ISSUE TITLE
getTargetAtClientPoint returns wrong position with word wrap on

### ISSUE THREAD

**Issue by yishn** [microsoft/monaco-editor#1378]
**monaco-editor version:** 0.16.1
**Browser:** Chrome
**OS:** Windows

**Steps or JS usage snippet reproducing the issue:**

~~~js
let monacoEditor = monaco.editor.create(element, {
  wordWrap: 'on'
});

element.addEventListener('dragenter', evt => {
  monacoEditor.focus();
});

element.addEventListener('dragover', evt => {
  evt.preventDefault();

  let target = monacoEditor.getTargetAtClientPoint(evt.clientX, evt.clientY);
  this.monacoEditor.setPosition(target.position);
});
~~~

In the editor, type several really long sentences, so that `wordWrap` takes effect. When you try to drag some outside text onto Monaco, you see that the caret position does not match the mouse cursor position.

**Comment by lemming** [comment]
There is workaround, but I would not recommend to use it in production as it relies on internal implementation and may break over time. Tested on 0.17.1

Using snippet above:

```javascript
let monacoEditor = monaco.editor.create(element, {
  wordWrap: 'on'
});

element.addEventListener('dragenter', evt => {
  monacoEditor.focus();
});

element.addEventListener('dragover', evt => {
  evt.preventDefault();

  let target = monacoEditor.getTargetAtClientPoint(evt.clientX, evt.clientY);
  if (!target) return; // target is nullable
  const position = monacoEditor._modelData.view.outgoingEvents._convertViewToModelPosition(target.position);
  monacoEditor.setPosition(position);

});
```

Interesting bit is
```javascript
monacoEditor._modelData.view.outgoingEvents._convertViewToModelPosition(target.position)
```

As "_" implies, these methods and properties are private and also use unexposed types (for TypeScript) so use it with caution.
