### ISSUE TITLE
Monaco: Plans for publishing to Bower?

### ISSUE THREAD

**Issue by alexdima** [microsoft/monaco-editor#138]
Moved from Microsoft/vscode#7919

---

From @warrenbuckley

With Monaco now a separate project that can be used in sites with NPM, is there any plans to be able to fetch & install Monaco using Bower?

**Comment by mattgodbolt** [comment]
github user @michael-golfi has registered "monaco-editor" at https://github.com/michael-golfi/monaco-editor, which is a partial solution for now (I've asked him to track the same versions as here).

**Comment by michael-golfi** [comment]
@mattgodbolt Please see the PR, I've updated the solution, the corresponding bower package, and I also included the versions.

**Comment by alexdima** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
