### ISSUE TITLE
Strange performance in Microsoft Edge

### ISSUE THREAD

**Issue by Richasy** [microsoft/monaco-editor#1380]
**monaco-editor version:** 0.16.1
**Browser:** Microsoft Edge
**OS:** Win10 1809

**Steps or JS usage snippet reproducing the issue:**

This has nothing to do with how to use it. In fact, the editor of the official website can reproduce.

1. One character will be retained under Pinyin input method

I am a Chinese developer. I found that when I use the Pinyin input method that comes with the system, I press the delete button after typing a few characters, but the editor always keeps the first letter:

![monaco_edge_input01.gif](https://storage.live.com/items/51816931BAB0F7A8!12449?authkey=AO7QXpgYo7-5DUU)

2. When switching, there are a lot of unknown characters in the pinyin input.

When you use `Alt`+`Tab` to switch applications and switch back, if you start typing with Pinyin in one to two seconds, a lot of junk characters will be generated. Each time you press a button on the keyboard, a number of characters will be generated.

![monaco_edge_input02.gif](https://storage.live.com/items/51816931BAB0F7A8!12450?authkey=AO7QXpgYo7-5DUU)

These characters cannot be copied and pasted, so I don't know the meaning of these characters.

---

The above tests are only in the Edge browser and use the Microsoft Pinyin input method.

I didn't make any special settings for the editor because I can completely reproduce it [here](https://microsoft.github.io/monaco-editor/playground.html).

**Comment by alexdima** [comment]
Closing, as Microsoft Edge Legacy has reached end of support on March 9, 2021. See [the end of support for Microsoft Edge Legacy announcement](https://docs.microsoft.com/en-us/lifecycle/announcements/edge-legacy-eos-details)
