### ISSUE TITLE
Swift syntax highlighting error for multiline strings

### ISSUE THREAD

**Issue by dan-zheng** [microsoft/monaco-editor#1381]
**monaco-editor version:** 0.16.1
**Browser: Chrome**
**OS: macOS 10.14** 

Multiline strings (declared with `"""`) display incorrectly if they contain a `"` inside.

Example: (GitHub displays it correctly)
```swift
let quotation = """
Even though there's whitespace to the left,
the actual lines aren't indented.
Except for this line.
Double quotes (") can appear without being escaped.

I still have \(apples + oranges) pieces of fruit.
    """
```

![image](https://user-images.githubusercontent.com/5590046/54725829-c1e2f980-4b2d-11e9-8f23-5748daa1ce52.png)

**Comment by dan-zheng** [comment]
Note: the example shown is not ideal because the multiline string is actually invalid.
Here's the fixed version:

```swift
```

**Comment by nrayburn-tech** [comment]
@alexdima I believe I have a fix for this issue.  Should I just submit a PR against monaco-languages for you to review?

**Comment by alexdima** [comment]
@nrayburn-tech Yes, please. PR welcome
