### ISSUE TITLE
Monaco-editor got ERROR on SurfaceBook2

### ISSUE THREAD

**Issue by CharlesMoone** [microsoft/monaco-editor#1382]
**monaco-editor version:** 0.16.0
**Browser:** Chrome 73.0.3683.75 (64 bit)
**OS:** Windows 10 1809 (OS Build 17763.379)

**Steps or JS usage snippet reproducing the issue:**
![monaco editor bug](https://user-images.githubusercontent.com/17830748/54740627-ed7de680-4bf6-11e9-8f3d-c94eb7b5161d.png)

When I scroll through the page through the touch screen, if I touch the editor, the console will display an error message.

**Comment by joechung-msft** [comment]
Chrome 73 introduced a change which made certain event listeners passive by default.  To fix this, `monaco-editor` needs to declare event listeners passive explicitly.

https://developers.google.com/web/updates/2019/02/scrolling-intervention
