### ISSUE TITLE
Error: Unexpected usage (integration with vue)

### ISSUE THREAD

**Issue by soneway** [microsoft/monaco-editor#1385]
languageFeatures.js?810d:85 Error: Unexpected usage
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?8c76:468)
    at eval (webWorker.js?a9b4:39)

**Comment by Symbolk** [comment]
Looking for a solution...

**Comment by Symbolk** [comment]
My solution: Configure webpack-plugin in vue.config.js, instead of webpack.config.js:
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')

module.exports = {
  configureWebpack: {
   plugins: [
      new MonacoWebpackPlugin({
        // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
        languages: ['javascript', 'css', 'html', 'typescript', 'json']
      })
    ]
  }
```

**Comment by cdll** [comment]
same issue here when treating with `json`

**Comment by alexdima** [comment]
@soneway Have you resolved your issue?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by tjk** [comment]
Can this be reopened please? @Symbolk do you understand why making that changed fixed anything?

**Comment by wowtrxqn** [comment]
> My solution: Configure webpack-plugin in vue.config.js, instead of webpack.config.js:
> 
> ```
> const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')
> 
> module.exports = {
>   configureWebpack: {
>    plugins: [
>       new MonacoWebpackPlugin({
>         // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
>         languages: ['javascript', 'css', 'html', 'typescript', 'json']
>       })
>     ]
>   }
> ```

when i use this solution ，see https://github.com/microsoft/monaco-editor-webpack-plugin/issues/96
