### ISSUE TITLE
get matching bracket position

### ISSUE THREAD

**Issue by ArunPatal** [microsoft/monaco-editor#1386]
Let's say if i have position of open bracket, Is there a way to get the position of the matching (close) bracket on editor?

Thanks

**Comment by yln99517** [comment]
You can use https://blog.scottlogic.com/2015/01/20/typescript-compiler-api.html reference code

**Comment by alexdima** [comment]
There is an internal method on the model, i.e. `editor.getModel()`:

```
	/**
	 * Given a `position`, if the position is on top or near a bracket,
	 * find the matching bracket of that bracket and return the ranges of both brackets.
	 * @param position The position at which to look for a bracket.
	 * @internal
	 */
	matchBracket(position: IPosition): [Range, Range] | null;
```
