### ISSUE TITLE
Monaco Editor defined attributes and Method , invoke in your Specific Method

### ISSUE THREAD

**Issue by Haikelano** [microsoft/monaco-editor#1389]
I m create a custom Custom Language in Monaco Editor With Angular 7 . i defined my new attributes and Methods in file of configuration my new language . Now i have to declare new attributes for one Method.

example : when i insert "W" it text it inserted 'autocomplete' call "workflow("attribute") now i need to when user seizure Ctrl+space show different Methods that I declare it

**Comment by alexdima** [comment]
You can register a completion item provider - e.g. https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
