### ISSUE TITLE
addCommand with monaco.KeyCode.Unknown (0) throws an error

### ISSUE THREAD

**Issue by vasiltabakov** [microsoft/monaco-editor#1390]
In the code lens provider example:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example
![image](https://user-images.githubusercontent.com/1178309/55005063-07973a80-4fe4-11e9-9a6f-d1b376bc9684.png)

Also in real world apps `.addCommand(0, ...` produces a JS error. Commands which do not bind to keys should exist.

p.s.
We've temporarily switched to using `.MAX_VALUE` but this is not a stable solution

**Comment by foxable** [comment]
I can confirm the issue. I noticed the error after upgrading from 0.15.6 to 0.16.2. When I consulted the playground to reproduce the issue I also stumbled upon the broken example.

Thanks for sharing the workaround. However, I would also prefer restoring the previous behavior.
