### ISSUE TITLE
When I set the value, the cursor moves to the document header.

### ISSUE THREAD

**Issue by kagari2613** [Microsoft/monaco-editor#1397]
**monaco-editor version:** 0.16.2
**Browser:** Chrome
**OS:** windows 10

**Steps or JS usage snippet reproducing the issue:**
create  a editor with some default values,then i call monacoInstance.setValue('some text');the cursor always move to the head of the first line,i just want what after  i setValue,the cursor could be the end of the current line。 How should i do?
```
monacoInstance = monaco.editor.create(this.$refs['editor'], {
          value: 'some code',
          language: 'plaintext'
        });
monacoInstance .setValue('some text');
```

**Comment by kagari2613** [comment]
at the same time , the focus is blur. 
My purpose is to achieve the `v-model` in vue framework

**Comment by mkapiczy** [comment]
I guess you have a vue component in which you create a monaco editor sth like:
```
<template>
  <div id="code-editor" ref="editor">
  </div>
</template>
```

Pass the value property to that component:

**Comment by mkapiczy** [comment]
I think the outside calls to the setValue always move the cursor to the beginning. However, that's kind of intended. If you want a v-model like experience pass a value property to your component:
Pass the value property to that component. Then create the editor as follows:
```
this.editor = monaco.editor.create(this.$el, {
        value: this.value,
        readOnly: this.readOnly,
        ...this.options
      })
```

Then listen for the model change and emit input event on it:
```
this.editor.onDidChangeModelContent(() => {
        if (this.$emit) {
          const content = this.editor.getValue()
          this.$emit('input', content)
        }
      })
```

If you need to update code from outside do it in a value property watcher:
```
value(newVal) {
      if (newVal !== this.editor.getValue()) {
        this.editor.setValue(newVal)
      }
    },
```
I guess you could even try to get the cursor position before calling setValue in the watcher and set it by `this.editor.setPosition()`. This is a guess though.

**Comment by kagari2613** [comment]
> I think the outside calls to the setValue always move the cursor to the beginning. However, that's kind of intended. If you want a v-model like experience pass a value property to your component:
> Pass the value property to that component. Then create the editor as follows:
> 
> ```
> this.editor = monaco.editor.create(this.$el, {
>         value: this.value,
>         readOnly: this.readOnly,
>         ...this.options
>       })
> ```
> Then listen for the model change and emit input event on it:
> 
> ```
> this.editor.onDidChangeModelContent(() => {
>         if (this.$emit) {
>           const content = this.editor.getValue()
>           this.$emit('input', content)
>         }
>       })
> ```
> If you need to update code from outside do it in a value property watcher:
> 
> ```
> value(newVal) {
>       if (newVal !== this.editor.getValue()) {
>         this.editor.setValue(newVal)
>       }
>     },
> ```
> I guess you could even try to get the cursor position before calling setValue in the watcher and set it by `this.editor.setPosition()`. This is a guess though.

thx,it's worked after I add the `if` statement `if(newVal!==this.editor.getValue())`

**Comment by Oscarsgc** [comment]
I'm facing the same issue. I'm trying to update the editor value using buttons and manually inserting text, but I can't update the position. When I Use the `editor.setPosition({lineNumber:y, column:x});` method, it doesn't refresh the editor cursor. But if I use the `editor.getPosition()` it returns the correct values. Any Idea on what could be going wrong there @mkapiczy ?

**Comment by mkapiczy** [comment]
Try `editor.focus();` after setting the cursor's position

**Comment by Oscarsgc** [comment]
It doesn't works... The cursor keeps showing at the same position. I can reproduce it on the playground.
This is my code:
`editor.onDidChangeModelContent((e)=>{
    console.log("HERE");
     editor.setPosition({lineNumber:10, column:2});
     editor.focus();
})
`

I'm using this in the 'Revealing a position' example.

**Comment by mkapiczy** [comment]
So first of all I am not part of the monaco team, I am here randomly so my knowledge is pretty limited. Having said that, I think what is happening is that after the onDidChangeModelContent event monaco updates cursor position to match the content change, overriding your manual setPosition.

You can see it if you do sth like this:
```
editor.onDidChangeModelContent((e)=>{ 
    console.log("Model changed start", editor.getPosition());
    editor.setPosition({lineNumber:10, column:2}); 
    editor.focus(); 
    console.log("Model changed finished", editor.getPosition());
    });

    editor.onDidChangeCursorPosition(e => {
        console.log('Cursor changed', editor.getPosition());
    });
```

Maybe, try using executeEdits --> https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#executeedits

**Comment by petahbred** [comment]
Not sure if this is still an issue, but I was able to solve it using the following:

```
monacoEditor.setValue(output);
monacoEditor.focus();
monacoEditor.setPosition({
    column: 0,
    lineNumber: Infinity,
});
```
