### ISSUE TITLE
The editor.main file is almost 2MB and takes a lot of time to download it

### ISSUE THREAD

**Issue by sigalvo** [microsoft/monaco-editor#1399]
Is there a way to separate the editor.main to several files and load them asynchronously? or a way to reduce it's size?
The file is almost 2MB and it increases our application load time.

Thanks,
Violet.

**Comment by alexandrudima** [comment]
You can use webpack and split it into multiple pieces.

**Comment by sigalvo** [comment]
Thanks!
Is there an example of doing it?
Is it possible to do so using requirejs / grunt task?

Violet.

**Comment by mokimo** [comment]
I'd have it on a custom route and don't load it unless you are on this route.
This way your application only loads the resource upon request.

https://webpack.js.org/guides/code-splitting/

_Grunt won't work, as you have to tell webpack what part it **should not** load initially_

**Comment by sigalvo** [comment]
I don't quite understand how to split the file using the code-splitting.
Can you add an example of doing it?
I can't put it in a custom route. This is the core of our application and we need it in the initialization.

Violet.

**Comment by alexdima** [comment]
Unfortunately you need to consult the webpack documentation regarding code splitting into multiple files. I don't believe we have any sample at https://github.com/microsoft/monaco-editor-samples showing this exact scenario.
