### ISSUE TITLE
"Built-in AMD cross-domain web worker loading" documentation missing?

### ISSUE THREAD

**Issue by trevorade** [microsoft/monaco-editor#1400]
The [0.16.0 changelog](https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md#new--noteworthy) says: "Added built-in support for AMD cross-domain web worker loading."

I'm trying to track down what that specifically is new in 0.16.0.  The docs at https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md don't appear to have been updated recently to make use of the new "built-in support for AMD cross-domain web worker loading".

**Comment by rocallahan** [comment]
I think this commit is relevant: https://github.com/microsoft/vscode/commit/a02c4e72935304e618a7f2fe5d96fdbf51cf9ba6#diff-e84a1bdae687910fa860764374cd3ab0

**Comment by rocallahan** [comment]
Looks like it just automates Option 1 of https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md.
