### ISSUE TITLE
imported module turns to "not found" after limited editing

### ISSUE THREAD

**Issue by snoop244** [microsoft/monaco-editor#1401]
**monaco-editor version:** 016.2
**Browser:** Chrome (latest)
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**

I have a working Monaco editor.  I'm attempting to add both Typescript types and other modules to support code completion etc..

Types added through `addExtraLib()` work perfectly.  I have included a working call to addExtraLib, below.

Unfortunately, using `createModel` only works for the primary model that gets loaded into the visible editor.  When I create a second model that includes an exported class and then import it into the primary model's code, code completion works sporadically and usually fails the first time the editor picks up and highlights a syntax error with the red underline.  Any (unrelated) syntax error can cause the problem.  At that point, the imported module also gets the red underline with a `module not found` error on rollover on the module.  Again, this problem only crops up after a few successful uses of the module's exports... it works as expected, and then it doesn't.

```
  monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
    allowNonTsExtensions: true,
    allowJs: true,
    isolatedModules: true,
    outDir: "dummy"
  });
   monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
      noSemanticValidation: false,
      noSyntacticValidation: false
  }); 

monaco.languages.typescript.typescriptDefaults.addExtraLib( // works
  `
  /**
   * A function that adds numbers
   * @param a the first number 
   * @param b the second number 
   */
  export declare function add(a: number, b: number): number
  
  `,
  'file:///node_modules/@types/add/index.d.ts'
);

var secondaryModel = monaco.editor.createModel([ // Works for some edits in the primary model, then fails
  `
  export class Milestone {
    id: string;
    name: string;
  };
  `
].join('\n'), "typescript", monaco.Uri.file("test.ts"));

var primaryModel = monaco.editor.createModel(store.state.rawContentItem, 'typescript', monaco.Uri.parse('file:///main.tsx')) // Primary model that gets loaded to the editor and imports the exported class Milestone

```
Initially when the editor loads (working as expected):
![image](https://user-images.githubusercontent.com/7346594/55242050-d2246400-5212-11e9-91ef-3fd0281077c9.png)

After a few edits to the code (./test module no longer found):
![image](https://user-images.githubusercontent.com/7346594/55241773-3266d600-5212-11e9-9004-a4b8ffb81218.png)

**Comment by yln99517** [comment]
try the below statements after creating the model and before creating the editor

```
monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true);
```

this will sync the models when worker thread restarts

- thanks

**Comment by snoop244** [comment]
Thanks, but it didn't work. It worked for a bit longer, but on my second set of code edits where I used the imported class, it lost the module again.

**Comment by yln99517** [comment]
Same issue https://github.com/Microsoft/monaco-editor/issues/1310

**Comment by raedle** [comment]
I posted a workaround to this issue [here](https://github.com/microsoft/monaco-editor/issues/1310#issuecomment-522190060)

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/monaco-typescript/commit/14fbd7c2e09b5690f92d89348ea83539683cb206
