### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by netnr** [microsoft/monaco-editor#1403]
**monaco-editor version:** 0.16.2

- Language packs after version 0.14.3 have not been processed
- The version number of the comment in version 0.16.2 is still 0.16.1

Maybe the details are better?

**Comment by alexdima** [comment]
In the meantime, we now have language packs. The comment does not work 100% because sometime we generate the release after tagging, sometimes before tagging and that can make an off-by-on possible. But the API of 0.16.2 is usually 100% the same as the API of 0.16.1, etc.
