### ISSUE TITLE
Scrolling via wheel event stopped working in Firefox

### ISSUE THREAD

**Issue by hkarimian84** [Microsoft/monaco-editor#1404]
**monaco-editor version:** 0.16.2
**Browser:** Firefox
**OS:** Windows

After upgrading to 0.16.2 (from 0.14.3), it's no longer possible to scroll editor via mouse wheel in Firefox browser.

**Steps or JS usage snippet reproducing the issue:**

Scrolling doesn't work in editor's demo as well:
https://microsoft.github.io/monaco-editor/index.html

**Comment by spahnke** [comment]
Hi, this is a duplicate of #1353
