### ISSUE TITLE
Toggle View Zone on click of a glyph

### ISSUE THREAD

**Issue by garimagupta3** [microsoft/monaco-editor#1406]
Hi, is there a way to toggle viewzone on click of a glyph?
I am able to remove the added zone using removeZone but unable to get it back as the API removes my element entirely from DOM. Is there a way out of it?

**Comment by alexdima** [comment]
@garimagupta3 I don't quite understand what you mean. Do you have a sample JS to demonstrate your issue?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
