### ISSUE TITLE
Cmd+F12, Go to Definition Shortcut not working in browser

### ISSUE THREAD

**Issue by Aayush04** [microsoft/monaco-editor#1407]
**monaco-editor version:** 0.16.0
**monaco-editor version:** 0.14.0
**Browser:** Chrome
**OS:** MacOS

When running monaco-editor on browser
ShortCut for "Go to Definition" and "Go to Implementation" is same i.e. Cmd+F12
This can be seen in shortcut list also when pressing F1.

And due to this not able to trigger "Go to Definition" with Cmd+F12 , as "Go to Implentation" works instead.

I checked in the code it is written there also  

```
var goToDeclarationKb = platform.isWeb 
                     ? 2048 /* CtrlCmd */ | 70 /* F12 */ : 70 /* F12 */;

```
and for goToImplementation

```
 kbOpts: {
                kbExpr: EditorContextKeys.editorTextFocus,
                primary: 2048 /* CtrlCmd */ | 70 /* F12 */,
                weight: 100 /* EditorContrib */
 }
```

that for web Shortcut for GotToDefiniton will Cmd+F12 but same is also assigned to GoToImplementation.

**Comment by tsmaeder** [comment]
Any opinions on this from the development team?

**Comment by alexdima** [comment]
I believe this has been fixed in the meantime because now `cmd+f12` jumps to definition for me on mac/chrome when running from sources.
