### ISSUE TITLE
AutoCompletion of yaml files works in codepen but not working in ESM Module(Vuejs)

### ISSUE THREAD

**Issue by Alosies** [microsoft/monaco-editor#1409]
**monaco-editor version:** 0.16.2
**monaco-editor-webpack-plugin**: 1.7.0
**VueJS**: 2.6.6
**Browser:** Chrome
**OS:** OS X

**Issue**
I am able to implement auto-completion on Codepen for yaml files. But I am not able to implement the same in ESM Module in a basic Vue App. 

**Working Auto-completion in Codepen**
https://codepen.io/alosies/pen/KYPeYE
<img width="1440" alt="Screenshot 2019-04-01 at 2 12 56 PM" src="https://user-images.githubusercontent.com/24241029/55314714-5d5a5f80-5488-11e9-9227-5e752da150be.png">

**GitHub reproducing the issue:**
https://github.com/Alosies/Monaco-Editor-Vue
<img width="1440" alt="Screenshot 2019-04-01 at 1 58 07 PM" src="https://user-images.githubusercontent.com/24241029/55314791-8975e080-5488-11e9-9187-f80d7e8d8e55.png">

But the same is not working through ESM Module in Vue.

I think it might have something to do with workers. I went through some posts here and tried to implement the same. But none of them seem to get auto-completion to work. Any help on this is highly appreciated.

**Comment by alexdima** [comment]
The completion item provider does not return the expected result shape. https://github.com/Alosies/Monaco-Editor-Vue/blob/29aa39a89633e0d983c604f0ad643520df49b027/src/App.vue#L18-L27

```
      provideCompletionItems: (model, position) => {
        return [
          {
            label: "apiVersion",
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Defines the version of Api to create the object",
            detail: "Required Field"
          }
        ];
      }
```

should be

```
      provideCompletionItems: (model, position) => {
        return {
          suggestions: [
          {
            label: "apiVersion",
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Defines the version of Api to create the object",
            detail: "Required Field"
          }
          ]
        };
      }
```

The expected return type has been a breaking change introduced with the Monaco Editor v 0.15.0. This has been documented here -- https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md#0150-12112018

In the code pen you are using the editor at version `0.8.3`.
