### ISSUE TITLE
Can't overwrite seleted text on Microsoft Edge with Chinese IME

### ISSUE THREAD

**Issue by Vixb1122** [microsoft/monaco-editor#1410]
**monaco-editor version:** 0.16.2
**Browser:** Microsoft Edge ver: 44.17763.1.0
**OS:** Windows 10 ver1809 17763.379

**Steps or JS usage snippet reproducing the issue:**
1. Open `https://microsoft.github.io/monaco-editor/index.html` with Microsoft Edge
2. Change IME to `Microsoft Pinyin`
3. Select a word in the editor
4. Input text

![bug](https://user-images.githubusercontent.com/17810492/55326966-9a8c1500-54bb-11e9-8fb2-8f1f8fd03dbb.gif)

**Comment by alexdima** [comment]
Closing, as Microsoft Edge Legacy has reached end of support on March 9, 2021. See [the end of support for Microsoft Edge Legacy announcement](https://docs.microsoft.com/en-us/lifecycle/announcements/edge-legacy-eos-details)
