### ISSUE TITLE
Remove or disable keywords

### ISSUE THREAD

**Issue by Sieglain** [microsoft/monaco-editor#1411]
**monaco-editor version:** 0.X.Y
**Browser:* chrome*
**OS:*Windows-10* 

I'm trying to disable or remove the keywords of Javascript so i can only use my customs completion itens.
I used the 'noLib' to remove most of the things, but the 'if, for, async, etc' its still there, and i'm searching for a way to remove for a good while now, 
Anyone knows a way to do it? 
Thanks!

ps.: Sorry for my bad English, its not my first language.

**Comment by davidbonnet** [comment]
Look for the `suggest.filteredTypes` option, which has been added recently:
```js
monaco.editor.create(element, {
  suggest: { filteredTypes: { keyword: false } },
})
```
