### ISSUE TITLE
Get suggestions more then once on the same line

### ISSUE THREAD

**Issue by Sieglain** [microsoft/monaco-editor#1412]
**monaco-editor version:** 0.X.Y
**Browser:*Chrome*
**OS:*Windows 10* 

On my custom language everytime i try to open the suggestions for te second time on the same line, it's shows 'No suggestions.'
There is a way to make appear the same suggestions the shows on the first time?
If a try on other line, it works, but on the same line,  it only happens once.

**Comment by bmeritter** [comment]
I set `Tab` trigger suggestions, but `Space` after `:` also trigger it
And I want to disabled `Space` trigger

**Comment by wuyingyou** [comment]
I think I got the approach now. 
Refers to https://github.com/family2hu/react-monaco-demo.
(This demo can show up the suggestions wherever you hit ':' in the Monaco Editor)
Heads up for the deep clone of suggestions below.

 const suggestions = [
      {
        label: 'Label1',
        insertText: 'Label1', 
        detail: 'some tips'
      },
      {
        label: 'Label2',
        insertText: 'Label2',
        detail: 'tips'
      },
      {
        label: 'Label3',
        insertText: 'Label3',
        detail: 'tips'
      }
    ];

        provideCompletionItems() {
          return {
            suggestions: suggestions.map(item => ({
                  ...item,
                 kind: monaco.languages.CompletionItemKind.Variable})) // must be deep clone 
          };
        },
        triggerCharacters: [':'],
 }

**Comment by wuyingyou** [comment]
Mac OS, Chrome, Monaco Editor - "monaco-editor": "^0.15.6", "monaco-editor-webpack-plugin": "^1.7.0",

**Comment by alexdima** [comment]
@Sieglain Can you please provide a full working example so we can try to investigate?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
