### ISSUE TITLE
Preserve addition/deletions highlighting when selection highlighting

### ISSUE THREAD

**Issue by dimitrieh** [microsoft/monaco-editor#1413]
### Problem

Currently, when selecting text any styling prior to that selected text gets fully replaced by the highlighting styles applied when selecting.

### Proposal

When highlighting text through selection it would be a welcome to be able to continue to distinguish addition/deletions underneath it. 

### Additional information

Related to discussion at https://gitlab.com/gitlab-org/gitlab-ce/issues/47771#note_155442988

**Comment by alexdima** [comment]
The only thing I can think of is to make the selection transparent, e.g. of sample that runs at https://microsoft.github.io/monaco-editor/playground.html:

```js
var originalModel = monaco.editor.createModel("heLLo world!", "text/plain");
var modifiedModel = monaco.editor.createModel("heLLo world!\nhello orlando!", "text/plain");

monaco.editor.defineTheme('myCustomTheme', {
	base: 'vs', // can also be vs-dark or hc-black
	inherit: true, // can also be false to completely replace the builtin rules
    rules: [],
    colors: {
        'editor.selectionBackground': '#0000aa44'
    }
});

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
    theme: "myCustomTheme"
});
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});
```

It doesn't look great, but you can still tell a bit the green shades:

![image](https://user-images.githubusercontent.com/5047891/70615865-7c131780-1c0d-11ea-95c0-bacc4ac5922e.png)
