### ISSUE TITLE
Source code missing from release but was in prior versions?

### ISSUE THREAD

**Issue by guycreate** [microsoft/monaco-editor#1416]
**monaco-editor version:** 0.16.2
**Browser:** Chrome
**OS:**  Mac OS 10.14.3

`vs/base/parts/tree/browser/treeImpl.js` is missing some of the public API methods in ^0.16.x that were in ^0.15.x and that are still in the source code

### Expected source code at [Microsoft/vscode](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeImpl.ts)

```js
public getInput(): any {
		return this.model.getInput();
	}

	public refresh(element: any = null, recursive = true): Promise<any> {
		return this.model.refresh(element, recursive);
	}

	public expand(element: any): Promise<any> {
		return this.model.expand(element);
	}

```

### Actual transpiled code at [npm/monaco-editor@0.16.2](https://cdn.jsdelivr.net/npm/monaco-editor@0.16.2/esm/vs/base/parts/tree/browser/treeImpl.js)

```js
   Tree.prototype.getInput = function () {
        return this.model.getInput();
    };

    Tree.prototype.expand = function (element) {
        return this.model.expand(element);
    };
```

Note the missing functions do seem to be in the prior release at [npm/monaco-editor@0.15.6](https://cdn.jsdelivr.net/npm/monaco-editor@0.15.6/esm/vs/base/parts/tree/browser/treeImpl.js)

The functions missing seem to include those that return plain `Promises` that used to return WinJS Promises

**Comment by alexdima** [comment]
The Monaco Editor is extracted from VS Code sources via treeshaking. It is very likely those methods were not being used anywhere in the Monaco Editor and they have therefore been removed from the Monaco Editor distribution to save on the editor size. If you want, you can extract your own `monaco-editor-core` by running `/src/vscode> node_modules/.bin/gulp editor-distro` in the vscode repo.

Before doing so, you can tweak the treeshaking and change the treeshaking level to only shake files, and not class members here -- https://github.com/microsoft/vscode/blob/0e6515981419500f06f4397bb2bed074b3bc5a65/build/gulpfile.editor.js#L78
