### ISSUE TITLE
[Monarch] Rule without 'nextEmbedded: "@pop"' in a nextEmbedded state doesn't work

### ISSUE THREAD

**Issue by Menci** [microsoft/monaco-editor#1417]
For example, I want to match texts in `[]` and apply JavaScript's grammar on them. With this:

```javascript
return {
	tokenizer: {
		root: [
			[/\[/, { token: 'strong', next: 'inbracket', nextEmbedded: 'javascript' }]
		],

		inbracket: [
			[/\\\]/, { token: 'strong', log: 'It works!' }],
			[/\]/, { token: 'strong', next: '@pop', nextEmbedded: '@pop' }]
		]
	},
};
```

When processing `[function\]function]`, it's ***expacted*** to match the rule `/\\\]/` on `\]` and continue in JavaScript mode until `]` is found. But the rule `/\\\]/` on `\]` doesn't work.

**Comment by alexdima** [comment]
@Menci This appears to work for me:

![image](https://user-images.githubusercontent.com/5047891/70615116-12463e00-1c0c-11ea-9a04-83efd420485f.png)

Perhaps I am misunderstanding what do you mean?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
