### ISSUE TITLE
[Suggestion] An EventListener that fires IModelContentChangedEvent character by character

### ISSUE THREAD

**Issue by maxxcs** [microsoft/monaco-editor#1418]
This would be cool because it would allow easy integration with character-based libraries, such as a CRDT. Currently, integration with such algorithms requires a number of complex changes, such as getting a range from a selection of text removal and replacing each character of the range to an empty string of that position.

Scenario: `"aa"` → `"b"`.

Currently:
```javascript
{
  forceMoveMarkers: false,
  range: {
    endColumn: 3,
    endLineNumber: 1,
    startColumn: 1,
    startLineNumber: 1,
  }
  rangeLength: 2,
  rangeOffset: 0,
  text: "b" 
}
```
To:
```javascript
[{
  forceMoveMarkers: false,
  range: {
    endColumn: 3,
    endLineNumber: 1,
    startColumn: 2,
    startLineNumber: 1,
  }
  rangeLength: 1,
  rangeOffset: 1,
  text: "" 
},
{
  forceMoveMarkers: false,
  range: {
    endColumn: 2,
    endLineNumber: 1,
    startColumn: 1,
    startLineNumber: 1,
  }
  rangeLength: 1,
  rangeOffset: 0,
  text: "" 
},
{
  forceMoveMarkers: false,
  range: {
    endColumn: 1,
    endLineNumber: 1,
    startColumn: 1,
    startLineNumber: 1,
  }
  rangeLength: 0,
  rangeOffset: 0,
  text: "b" 
}]
```

**Comment by alexdima** [comment]
I don't think we will ever add this because that is not how the editor works. For example, it is possible to paste 20MB of text in the editor. The editor now fires one event letting everyone know what happened. We will not change this to fire 20 million events, one character at a time.
