### ISSUE TITLE
Changing Text Manually Crashes Context Generator

### ISSUE THREAD

**Issue by agahEbrahimi** [microsoft/monaco-editor#1419]
**monaco-editor version: 0.16.2** 
**Browser: Electron**
**OS: OSX High Sierra** 

After manually changing the value of the text for the editor as follows:
`this.monacoEditor.setValue(text)`
The context generates incorrectly as such: 

![image](https://user-images.githubusercontent.com/23368028/56327866-53a04f80-614a-11e9-8eb2-bbf40c4f3760.png)

If I save the text in the sessionStorage, quit the app, and then go back into it then the context is correct, but not if I continue on the same session.

**Comment by alexdima** [comment]
@agahEbrahimi  Can you please provide a running sample that executes at https://microsoft.github.io/monaco-editor/playground.html and demonstrates the problem?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
