### ISSUE TITLE
Editor always requesting workers form the server.

### ISSUE THREAD

**Issue by Bellski** [microsoft/monaco-editor#1421]
**monaco-editor version:** 0.16.2
**Browser:** Chrome 73.0.3683.103
**OS:**  Windows 10
I'm using monaco-webpack-plugin

Hello. Can't understand why monaco always getting *.worker.js from the server. I thought when worker already registered it shares for all editor instances, or i'm doing somthing wrong ?

**Comment by alexdima** [comment]
@Bellski I am not 100% what you mean. The editor will use `new Worker('path/to/worker.js')`. I believe browsers will use caching rules to determine if a new HTTP request is to be done or not. Perhaps you can host the editor at a unique path that changes with each version and then use `Expires` headers to indicate that it never expires ?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
