### ISSUE TITLE
JSON autocomplete adds too many }

### ISSUE THREAD

**Issue by domoritz** [microsoft/monaco-editor#1422]
**monaco-editor version:** VSCode 1.33.1
**Browser:**: Electron
**OS:**: MacOS

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "color" <--- autocomplete here
  }
}
```

When I type `:{`, VSCode autocompletes to `{}}`, which results in invalid JSON.

![editor](https://user-images.githubusercontent.com/589034/56474457-01537d00-642f-11e9-9a8d-abc667aa3af2.gif)

As a side note, if instead, I add a space after `:`, autocomplete is correct in VSCode but for some reason it is still wrong in Monaco. 

This causes https://github.com/vega/editor/issues/99

**Comment by algomaster99** [comment]
It is happening because pressing `{` once auto completes it to `{}` while the intellisense is on. But intellisense only highlights `{` because `}` is automatically generated as explained previously. So when <kbd>Enter</kbd> is pressed, Intellisense add `}` which was not highlighted.

**Comment by domoritz** [comment]
@alexandrudima could you help us with this issue? I'm happy to send a PR if you can give us some guidance.

**Comment by domoritz** [comment]
@aeschli could this be an issue specifically with the JSON plugin?

**Comment by aeschli** [comment]
This issue should filed against https://github.com/microsoft/vscode

That said, I can't reproduce it in the latest insiders. I know @alexandrudima has done some work with auto bracket completions.

Please try with the latest insiders and if you still see it, file an issue in https://github.com/microsoft/vscode

**Comment by domoritz** [comment]
That's great to hear. Do you have a link to the fix @alexandrudima?
