### ISSUE TITLE
create separate/hierarchical/multilevel suggestions dropdowns in Monaco editor

### ISSUE THREAD

**Issue by cirnatescu** [microsoft/monaco-editor#1424]
I want to group suggestions in separate lists and show them on different keystrokes. I need this for javscript language mostly but not only.
I want to be able to hit, for example, alt+s and to have in the drop down some suggestions and hit alt+g and have a drop down with some other suggestions. I know Monaco has registerCompletionItemProvider but does not seem to work the way I want. I know I can indicate trigger key(s) but:
- I don't know how to indicate something like ctrl+g not to mention sequences like: alt+s, alt+d;
- the trigger character remains in text and has to be deleted afterwards (very annoying);
- it seems not any character may be used as trigger (e.g. $ sign or dot/period);
- moreover, I would like the suggestions of those lists not to appear in the 'default' drop down which shows on ctrl+space.
    The most elegant solution would be with some hierarchical/multilevel drop downs. Another interesting solution would be: when I chose something from a drop down, the original drop down to close and another to appear with a 'child' list. Alternative: when i pick up something in a drop down, the content of the drop down to be replaced with other items, from the/a 'child' list.

**Comment by rcjsuen** [comment]
Regarding your second point, you can define arbitrary `triggerCharacters` to prompt content assist.

https://github.com/Microsoft/monaco-editor/blob/ce5a045dbd8773a89bd983db08410f545b85bd37/monaco.d.ts#L4849-L4850

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
