### ISSUE TITLE
Styles Proirity Bugs in Menu

### ISSUE THREAD

**Issue by ZsgsDesign** [microsoft/monaco-editor#1425]
**monaco-editor version:** 0.15.5
**Browser:** Chrome
**OS:** Windows 10

Right-click Monaco Editor and there would be a decoration under each <a> if global styles of `a: hover` is defined like Bootstrap.

I am currently using the style
```
a.action-menu-item:hover{
    text-decoration: none;
}
```
to fix that.

**Comment by alexdima** [comment]
IMHO we should not include a CSS reset snippet in our CSS. I also believe it is reasonable that the editor is using `<a>` for menu items.

In this case, the only thing is to go with the solution you propose to limit the impact of bootstrap.
