### ISSUE TITLE
Allow to replace/update the bundled TS language service

### ISSUE THREAD

**Issue by ulrichb** [microsoft/monaco-editor#1426]
This is a follow-up of #177.

Same issue, but now with the Monaco Editor-bundled version 3.3 (without e.g. `readonly` tuples feature) vs. current version 3.4.

Is there a possibility to use the TypeScript language service (`typescriptServices.js`) from the `typescript` npm package instead of the bundled one (`.../monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js`) _without forking Monaco Editor_?

**Comment by ulrichb** [comment]
@alexandrudima Is there any possibility? I'm really struggling with the semantic model errors when using TS 3.4 declarations containing `readonly` tuples and arrays...
 
... if there is no (easy) possiblity ... when can expect a Monaco Editor release containing TS 3.4 (or 3.5)?

**Comment by alexdima** [comment]
It is possible to fork `monaco-typescript` and publish it to npm as `monaco-typescript-fork`. Then, it is possible to fork this project and tweak the `monaco-typescript` plugin section here -- https://github.com/microsoft/monaco-editor/blob/d8296a49bb177b8b2c6332069e70cbc00b2ad646/metadata.js#L15-L26

You can then execute `gulp release` and you will get a monaco editor built with your custom `monaco-typescript`.
