### ISSUE TITLE
 Using the Chinese input method to enter characters on the Firefox browser will appear twice

### ISSUE THREAD

**Issue by wzqiang1332** [microsoft/monaco-editor#1428]
Using the Chinese input method to enter characters on the Firefox browser will appear twice.
But this problem does not occur on chrome

monaco-editor version:** 0.16.2
Browser: firefox 63.0.1
OS:win10 (17763)

![GIF](https://user-images.githubusercontent.com/20432873/56859480-2fe8cf00-69be-11e9-88f3-185eb324bed5.gif)

**Comment by alexdima** [comment]
@wzqiang1332 Can you reproduce in the editor at http://vscode-web-test-playground.azurewebsites.net/ ?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
