### ISSUE TITLE
 hide lines of code - angular 7

### ISSUE THREAD

**Issue by davidndigitalware** [microsoft/monaco-editor#1429]
Is there any way to hide code lines in the control in angular7? I could not implement setHiddenArea()

**Comment by alexdima** [comment]
@davidndigitalware Can you provide a reproducible sample that executes at https://microsoft.github.io/monaco-editor/playground.html for us to investigate?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
