### ISSUE TITLE
Word wrap deleted line in inline diff view

### ISSUE THREAD

**Issue by LasseNisted** [microsoft/monaco-editor#1432]
**monaco-editor version:** 0.X.Y
**Browser:** Chrome
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**

When using the Azure DevOps Pull Request feature it is possible to enable word wrapping in the "inline diff" mode. However, only the added text gets wrapped, and due to #570 no scrollbar is added.

![image](https://user-images.githubusercontent.com/16150076/57059422-9408dd00-6cb5-11e9-8920-4619b9f01dee.png)

I open the bug here with Monaco, since [Azure DevOps seems to indicate it is not an Azure DevOps issue](https://developercommunity.visualstudio.com/content/problem/299226/word-wrap-does-not-work-on-deleted-text.html).

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/dac897f3a10c1a8a317b62929e89b6fede28612c
