### ISSUE TITLE
Monaco-editor became non-editable (i.e. readonly) in Excel for Mac

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#1434]
I have made an Excel add-in, which includes a monaco-editor. It used to work well.

However, recently the monaco-editor became non-editable (i.e. readonly) in Excel for Mac; whereas it works fine in Excel Online or Excel for Windows.

Does anyone know what might be the reason?

Cheers

**Comment by alexdima** [comment]
I honestly have no idea, perhaps there is some kind of issue with the editor being embedded in a native browser view ?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
