### ISSUE TITLE
Unable to undo changes using ctrl + z after toggling to another file..

### ISSUE THREAD

**Issue by manideepmothe641** [microsoft/monaco-editor#1435]
**monaco-editor version:** ^6.0.0
**Browser:** chrome 74.0.3729.131
**OS:** windows

**Steps or JS usage snippet reproducing the issue:**

step 1 : go to some file i.e [file1] and do changes here

step 2 : go to another file i.e [file 2] and do some changes here

step 3 : go back to file1 and use ctrl + z. unable to undo changes

**Comment by manideepmothe641** [comment]
i dont see any method like undo() or redo() or saveViewState() or restoreViewState()

![Capture](https://user-images.githubusercontent.com/46887539/57227387-e851eb00-702e-11e9-8646-2b36a6119b1a.PNG)

**Comment by alexdima** [comment]
@manideepmothe641 Please see how the playground is implemented at https://microsoft.github.io/monaco-editor/playground.html

That shows an example of having tabs, and multiple models (one model per tab) and calling `editor.saveViewState()`, `editor.setModel()`, `editor.restoreViewState()`.
