### ISSUE TITLE
monaoc.editor.setTheme, bakcground in rules doesn't work

### ISSUE THREAD

**Issue by netweng** [microsoft/monaco-editor#1436]
```
monaco.editor.setTheme('custom-theme', {

    base: 'vs',
    inherit: true,
    rules: [ 
    { token: 'unsupport.character', foreground: '#FF5050' , background: '#FF9B00'}
    ]
})
```

of course i have make the rule of 'unsupport.character' by 'setMonarchTokensProvider'
the foreground work, but the background do not work. i check the css, and it just set the color without background.
and i check the[ source code ](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/supports/tokenization.ts#L402)

is it a bug? or i miss something?

**Comment by alexdima** [comment]
Let's track in #586
