### ISSUE TITLE
Issue with suggestions completion after using the executeEdits method

### ISSUE THREAD

**Issue by SofianeJamai** [microsoft/monaco-editor#1437]
monaco-editor version: 0.17.0
Browser:Chrome
OS:Windows 10

Hi eveyone, I'm in front of a strange bug.

After using the executeEdits to delete a word, I return an array of suggestions.
So when I match with a specific word, I delete it, and I show suggestions corresponding to the match.
So I see the suggestions list. Normally, when I start to write a word manually from this list, the suggestions list is reduced, showing only the words which corresponds with what you're writting.
The issue is here, I dont' know why,  some words of the list don't appear.

For instance, if I want to match with "_f", here is my code: 
```

  monaco.languages.registerCompletionItemProvider('myLanguage', {
    provideCompletionItems: function(model, position) {
	var cursorLine = position.lineNumber, cursorColumn = position.column;
        var textUntilPosition = model.getValueInRange({startLineNumber: position.lineNumber, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        
        var match1 = textUntilPosition.match(" _f") !=null | textUntilPosition.match("^_f") !=null ? true:false;
        if(match1){
            editor.executeEdits('', [{ range: new monaco.Range(cursorLine, cursorColumn - 2, cursorLine, cursorColumn), text: '  ' }]);
            return { suggestions: myArrayOfSuggestions()};
        } 
        else{ return { suggestions: otherArrayOfSuggestions()};}
    }
});

function myArrayOfSuggestions() {
    return [
        {
            label: 'name',
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: 'name'
        },
        {
            label: 'adress',
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: 'adress'
        },
        {
            label: 'city',
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: 'city'
        },
        {
            label: 'Accrual',
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: 'Accrual'
        }
    ];
```

Here, If I type "a" or "A",  "adress" will appear but "Accrual" won't.

Do you please have any idea what to do?

Best regards,
Sofiane Jamai

**Comment by SofianeJamai** [comment]
I add this picture to show you the problem

![monaco explication](https://user-images.githubusercontent.com/50359085/57289611-fdc12680-70bb-11e9-812b-c23459985ae5.png)

Best regards,
Sofiane Jamai

**Comment by jianhuifan** [comment]
I have the same problem
Why can trigger suggest only be normal in position. Column ==1 position
Once the snippet label appears, it no longer appears in the suggest list

**Comment by alexdima** [comment]
@SofianeJamai It is not expected for a completion item provider to invoke `executeEdits`. The completion item provider must return completion items and it is the editor's job to apply the completions if the user chooses the completion.
