### ISSUE TITLE
lagging the ui

### ISSUE THREAD

**Issue by Ahron333** [microsoft/monaco-editor#1441]
When i am loading monaco with a gif at the back it is taking so much cpu and lagging the ui
can i do something about it?

**Comment by alexdima** [comment]
@Ahron333 I am sorry I do not understand what you mean. Do you have more information or a sample editor usage demonstrating a bug?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
