### ISSUE TITLE
The scrollbar doesn't get auto-hidden sometimes

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#1442]
**monaco-editor version:** 0.7.0
**Browser:** Electron v3 and Electron v5
**OS:**  macOS 10.14

Sometimes the scrollbar doesn't get auto-hidden when exiting the editor with the mouse. Demo available [here](https://imgur.com/a/dSn5ZJy) and attached below.

[demo.mp4.zip](https://github.com/microsoft/monaco-editor/files/3189153/demo.mp4.zip)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/79857
