### ISSUE TITLE
One page has multiple editors, each with a different theme

### ISSUE THREAD

**Issue by sandy-shi** [microsoft/monaco-editor#1446]
One page has multiple editors, each with a different theme.
language: vue,
In the parent component, there are two editor sub-components A&B. The parent component passes the value to the editor component to change the theme. Click the B component's switching theme, and the theme of A also changes.

**Comment by sandy-shi** [comment]
@jonas @joaomoreno @avelino @jongalloway

**Comment by 2012shenghua** [comment]
me too, My project is also same problem，react

**Comment by alexdima** [comment]
Currently, all editors on a page must share the same theme. See #338
