### ISSUE TITLE
Programmatic way to find all required files

### ISSUE THREAD

**Issue by maxloh** [microsoft/monaco-editor#1447]
There are so many files in the vs/min/ folder. In some simple usage of the library, many of them are not required.

Is there a programmatic way to find and include only the necessary files in project folder, aside from using DevTools?

**Comment by alexdima** [comment]
- `vs/base/worker/workerMain.js` - needed for normal editor operation
- `vs/basic-languages/` - only loaded based on how you use the editor (what `language` you pick)
- `vs/editor/editor.main.js`, `vs/editor/editor.main.css`, `vs/editor/editor.main.nls.js` -- there are loaded in a normal editor
- `vs/editor/editor.main.nls.*` - only loaded if you configure the editor to be loaded with a different i18n language like German, Chinese, etc.
- `vs/language` - only loaded if you use those richer languages
- `loader.js` - normally used, but can be replaced by `require.js`.
