### ISSUE TITLE
Imported TypeScript models are lost after 60-90 sec if they are untouched

### ISSUE THREAD

**Issue by ulrichb** [microsoft/monaco-editor#1451]
**This is a follow-up of #461**

**monaco-editor version:** 0.17.0
**Browser:** Chrome
**OS:** Win

**Steps or JS usage snippet reproducing the issue:**

Use the following playground sample:
```TS
const editor = monaco.editor.create(document.getElementById("container"));

monaco.editor.createModel(`export const someConst = "someConst";
`, "typescript",
    monaco.Uri.file("/a.ts"));

editor.setModel(monaco.editor.createModel(`import { someConst } from "./a";

console.log("hello from main", someConst.length);
`,
    "typescript", monaco.Uri.file("/main.ts")));
```

=> Everything works, TS finds the imported module and also the completion on `someConst` works (suggests all `string` members):

![image](https://user-images.githubusercontent.com/388796/58170905-00fc0b00-7c95-11e9-8e25-5b0029b82e85.png)

**... after waiting for 60-90 secs ...** 

1. The completion on `someConst` stopped working
1. After any change in `main.ts` the import statement gets error squiggles.

![image](https://user-images.githubusercontent.com/388796/58170983-2db02280-7c95-11e9-8bdb-206ec3695a04.png)

----

The reason is the [`_checkStopModelSync()`](https://github.com/microsoft/vscode/blob/a5536b8f5a16a10d859f3dec1e59701671bf069e/src/vs/editor/common/services/editorWorkerServiceImpl.ts#L264) timer. See https://github.com/microsoft/monaco-editor/issues/461#issuecomment-494412045.

**Comment by yln99517** [comment]
Same as #1310

**Comment by ulrichb** [comment]
@yln99517 Thanks. Closing this issue.

**Comment by raedle** [comment]
I posted a workaround to this issue [here](https://github.com/microsoft/monaco-editor/issues/1310#issuecomment-522190060)
