### ISSUE TITLE
Further choosing not working while input multi same chars in Suggest Completion module

### ISSUE THREAD

**Issue by panjiang** [microsoft/monaco-editor#1457]
# Module
Suggest Completion

# Problem
Further choosing not working while input multi same chars

# Example
There are two options in suggestion dialog. 
1. Input `-` and ` `(space), option one was chosen.
2. Input `-` and `-`, option two can not be chosen.
```
- [ ] 
---\n
```

**Comment by alexdima** [comment]
I am sorry I do not understand your issue. Can you please add more information?

**Comment by panjiang** [comment]
Thanks for replay. It works now after updated to latest version.
