### ISSUE TITLE
Double click on find all references view throws exception

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/monaco-editor#146]
Moved from Microsoft/vscode#8381

---
From @isidorn

Refs: #8229

1. IE11 open https://microsoft.github.io/monaco-editor/index.html, TS sample
2. Find all references on something, double click inside find all references view
3. Notice exception in console

![screen shot 2016-06-28 at 16 21 27 1](https://cloud.githubusercontent.com/assets/1926584/16418992/6329f282-3d4c-11e6-8321-5778ba306f78.png)

**Comment by alexandrudima** [comment]
@isidorn  - This works for me now, not sure if it got fixed or we're doing things differently?

**Comment by isidorn** [comment]
@alexandrudima I am still getting this, I just double click inside the find all references view on IE11 and I get the exception in the console. Drop by my machine if you want to see it :)
