### ISSUE TITLE
Rollup plugin ?

### ISSUE THREAD

**Issue by NicoLaval** [microsoft/monaco-editor#1460]
[Issue](https://github.com/react-monaco-editor/react-monaco-editor/issues/210) redirecting by react-monaco-editor:

New version of react-monaco-editor seems to need MonacoWebpackPlugin to display tooltips when markers are hovered.

Is there an equivalent for a Rollup configuration?

**Comment by farskid** [comment]
Any ideas on how to write one? I'm keen to help.

**Comment by jeanbenitez** [comment]
I would like to see this! Anyone who has implemented monaco-editor in a rollup project successfully?

**Comment by khusamov** [comment]
+

**Comment by adykto** [comment]
+1

**Comment by beetaa** [comment]
rollup wanted +1

**Comment by brettwbyron** [comment]
+1 I'd love to use this in my rollup project

**Comment by TheComputerM** [comment]
+1, very useful indeed.

**Comment by chengcyber** [comment]
Hi all, I write a [rollup-plugin-monaco-editor](https://www.npmjs.com/package/rollup-plugin-monaco-editor). Hopes to help.

**Comment by suren-atoyan** [comment]
You can use [@monaco-editor/loader](https://github.com/suren-atoyan/monaco-loader) - to setup monaco without any configuration
And use [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react) - as a React wrapper that doesn't need configurations
