### ISSUE TITLE
Monaco editor suggest widget customization

### ISSUE THREAD

**Issue by vikasKacholia** [microsoft/monaco-editor#1462]
I want to customize suggest widget  of monaco editor and add a ? symbol with i symbol in suggest widget . and then on click event of i icon i want to open a html doc page . Could you please let me know how we can add the icon and how to add click event ?

my monaco version is  0.10.1

**Comment by griabcrh** [comment]
我是通过默认浏览器打开本地的html文档

**Comment by vikasKacholia** [comment]
Sorry ..I could not understand your comment?

**Comment by dipashriRapidqube** [comment]
I placed one button in html....when clicking on that button the font size should change . So how we customize the monaco  editor???

**Comment by dipashriRapidqube** [comment]
ok i love you

**Comment by rcjsuen** [comment]
@dipashriRapidqube Your question does not seem to be related to the original comment. Nonetheless, you should be using `setOptions(*)`. Here is some sample code for you to try in the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html).
```JavaScript
var editor = monaco.editor.create(document.getElementById("container"), {
    fontSize: 20,
    value: "Hello world",
});
setTimeout(function() {
    editor.updateOptions(
        {
            fontSize:15
        }
    )
}, 2000);
```

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
