### ISSUE TITLE
Accept Diff data format as input in Monaco Diff Editor

### ISSUE THREAD

**Issue by PAX523** [microsoft/monaco-editor#1463]
I refer to my following question on SO: [Is Monaco Diff Editor capable for Diff data format as input?](https://stackoverflow.com/questions/56183384/is-monaco-diff-editor-capable-for-diff-data-format-as-input)

In my scenario I don't have the Editor data for the left- and the right-hand side. Instead, I have the computed diff format of the comparison between the left- and the right-hand side data.

I would be glad if Monaco Diff Editor could also accept a diff as input.

**Comment by oldrich-s** [comment]
IMHO it is probably out of scope of this project. For Git diffs I use https://diff2html.xyz/

**Comment by PAX523** [comment]
This alternative has no minimap

**Comment by PAX523** [comment]
This alternative has no minimap. For very large diffs you need an overview about the location of differences. Or otherwise you have to implement actions that jump between the differences just like in known IDEs such as Eclipse, IntelliJ etc. That's not a really trivial task if you think about it.

I don't want to implement that myself. Monaco Diff Editor would fulfill all my requirements if it would be able to process diffs as input.

**Comment by vadimkantorov** [comment]
I have the same question.

I'm implementing user-controlled 3-way merges. Currently I'm using OpenBSD's diff + diff3prog + ed for merge. I'd like to graphically display the automatically produced merge for the user to inspect.

Alternatively, I could use Monaco's produced merges if there was a way to extract one: https://github.com/microsoft/monaco-editor/issues/2269

**Comment by hediet** [comment]
You can now tell the diff editor to use your own diff algorithm.
This would enable your use-case.

**Comment by vadimkantorov** [comment]
@hediet Do you know if there is a way to call the Monaco's diff algorithm (without actually trying to display the diff viewer)? Thank you!

**Comment by hediet** [comment]
You can do it like this:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#XQAAAALUAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw417fQEChkl-Hmh5zFo96TZUrxSh_vVMds2o1NvhRn1Q_Jz_xiWcEWBYvsgRh_UGfb9aJC9keirPYccW0saZ5awhpaVVcZankE9SdtPokVpmHCPdEqdapUzjmxuNPN9L-JK7HfymYWEnVdATS-8WSEO1eFuEZE6-2uzSR8CEosNzvIRrAOlpRTUuP5Wl8LwWt3RhpfmSVEfy98Y88wYZ8MiWwLCEdnpfvxe34p8K0IvOnwLE725_Wb8fVwtK0njPRh_qg64OUkQrzrl5mP1VfZSwKhU0cKJP2G-sQARpeSUUC3AiA8mTbcQKaz41v6MzQO4Z8xHg3XqNhMjfl9cw-IcWwE5Rhv6ZMFFarIh8v3CycunqBAsiTwjc3QWJhnXCZkiHAyZPdSvBjdDYnO5G7htKwaOL63Kj5K3nz_HjYe2JoFLgxGBQYe6-imXI108WxVsHqu8v0wrfjqFzzTwYwCGjLw67nMGfm0rZpwyq4QVSSLfEbiyoK43gs1_KGdhkYnzb2k4SNfoy6dkd1MOwTTO-lD08bP5ih_OQ2JENL8D0P9B0tAIez3ewm02f9kyFD
