### ISSUE TITLE
Error at npm run prepublish

### ISSUE THREAD

**Issue by aryabharat** [microsoft/monaco-editor#1466]
All the npm command executed successfully, but when npm run prepublish was running it gave following error:

npm.debug.log file:
4 verbose stack Error: missing script: prepublish
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/share/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/share/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/share/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/share/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /home/bharat/Desktop/node_project/monaco-json
6 error Linux 4.15.0-50-generic
7 error argv "/usr/bin/node" "/usr/bin/npm" "run" "prepublish"
8 error node v8.10.0
9 error npm  v3.5.2
10 error missing script: prepublish
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by alexdima** [comment]
```
error missing script: prepublish
```
Our `package.json` does not have a `prepublish` script. See https://github.com/microsoft/monaco-editor/blob/d8296a49bb177b8b2c6332069e70cbc00b2ad646/package.json#L8-L17
