### ISSUE TITLE
Disable autocomplete of all used words

### ISSUE THREAD

**Issue by sam-1994** [microsoft/monaco-editor#1467]
If there is returned an empty array from provideCompletionItems, the autocompletion suggests all already used words. Can I disable this behaviour?

I recreated the behaviour in the monaco playground example:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

```
function createDependencyProposals() {
    // returning a static list of proposals, not even looking at the prefix (filtering is done by the Monaco editor),
    // here you could do a server side lookup
    return [
    ];
}


monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        // find out if we are completing a property in the 'dependencies' object.
        var textUntilPosition = model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        var match = textUntilPosition.match(/"dependencies"\s*:\s*{\s*("[^"]*"\s*:\s*"[^"]*"\s*,\s*)*("[^"]*)?$/);
        var suggestions = match ? createDependencyProposals() : [];
        return {
            suggestions: suggestions
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json"
});
```

![image](https://user-images.githubusercontent.com/16835447/58813963-2427a280-8625-11e9-8adc-3e930967ad60.png)

**Comment by brijeshb42** [comment]
Use [`wordBasedSuggestions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#wordbasedsuggestions) options to disable this.

**Comment by sam-1994** [comment]
@brijeshb42 Ok thank you, the option solved the behaviour :)
