### ISSUE TITLE
Suggestions disappers after some time

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [microsoft/monaco-editor#1468]
Here i am tried to build suggestion for model, It worked fine initially but after 5 to 10 min it disappeared. Is i am missing anything?

Before:
<img width="1680" alt="monacoissue" src="https://user-images.githubusercontent.com/31442844/58939720-6b34a580-8795-11e9-81b7-f72ee600db77.png">

After 10min:
<img width="1680" alt="monacoissue1" src="https://user-images.githubusercontent.com/31442844/58939835-ab942380-8795-11e9-8985-660cfdf29d81.png">

Moreover if i try cmd+click on HelloDude import, below error appears
<img width="1680" alt="monacoissue2" src="https://user-images.githubusercontent.com/31442844/58960832-933bfd00-87c5-11e9-8936-216bdab58808.png">

monaco-editor version:0.17.0

Browser: firefox 67.0 64-bit

Os: Mac v10.14

**Comment by KarthikNedunchezhiyan** [comment]
Any updates regarding above issue?

**Comment by yln99517** [comment]
same as #1310

**Comment by alexdima** [comment]
@KarthikNedunchezhiyan Can you please provide a copy-paste friendly repro? The only thing I can think of that might be relevant is the auto-shutdown of web workers after being idle for a while. Perhaps that is not working correctly for TS in the context of extra libs?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
