### ISSUE TITLE
is monoca-editor support  LineDecoration hoverMessage

### ISSUE THREAD

**Issue by misshy** [microsoft/monaco-editor#1469]
**monaco-editor version:** 0.X.Y
**Browser:** chrome
**OS:** 

**Steps or JS usage snippet reproducing the issue:**
is monoca-editor support  LineDecoration hoverMessage, not glyphMarginHoverMessage
![image](https://user-images.githubusercontent.com/20111050/59016319-97265880-8873-11e9-904e-4e364f4e9b22.png)

**Comment by alexdima** [comment]
@misshy I'm sorry I don't understand exactly what you mean. Can you please describe more what the issue is?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
