### ISSUE TITLE
How to add simple custom language support?

### ISSUE THREAD

**Issue by Beyerheiser** [microsoft/monaco-editor#1477]
For example I want to parse something like this: _equals('somestring') | equals('anotherstring') | ..._ 

1. Syntax should be checked with error suggestions.
2. Autocomplete.
3. Highlighting.

Especially interested in the first. Or this isn't straightforward?

**Comment by rcjsuen** [comment]
@Beyerheiser You need to use the `setModelMarkers` function in `monaco.editor`.

https://github.com/microsoft/monaco-editor/blob/0e0cf007e200ee1ee4a3ea55aa9210a54a78f7d5/monaco.d.ts#L852-L855

Please use the following code in the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html) to get started.
```JavaScript
let model = monaco.editor.createModel(
    'This line is okay.\nThis line has a warning.\nThis line has an error.'
);

monaco.editor.create(document.getElementById("container"), {
	model
});

monaco.editor.setModelMarkers(model, "owner", [
    {
        startLineNumber: 2,
        startColumn: 17,
        endLineNumber: 2,
        endColumn: 24,
        message: 'Warning!',
        severity: monaco.MarkerSeverity.Warning
    },
    {
        startLineNumber: 3,
        startColumn: 18,
        endLineNumber: 3,
        endColumn: 23,
        message: 'Erorr!',
        severity: monaco.MarkerSeverity.Error
    }
]);
```

**Comment by Beyerheiser** [comment]
Thank you!
