### ISSUE TITLE
How to check syntax and show errors?

### ISSUE THREAD

**Issue by Beyerheiser** [microsoft/monaco-editor#1478]
For example for this https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages. How to add checking that [Sun Mar 7 16:05:49 2004**]** has closed bracket and followed by [info] or [notice] or [error]. Where in code I should add this? All examples are only about highlighting and autocomplete.

**Comment by rcjsuen** [comment]
@Beyerheiser I suggest you contain your questions in #1477 instead of opening new issues as your (current) question is simply a clarification of what you asked in #1477.

**Comment by lwinhong** [comment]
https://github.com/vuejs/eslint-plugin-vue
