### ISSUE TITLE
TS/JS division symbol interpreted as regex start (syntax highlighting)

### ISSUE THREAD

**Issue by njbraun** [microsoft/monaco-editor#1479]
**monaco-editor version:** 0.16.2
**Browser:** any
**OS:** any

**Steps or JS usage snippet reproducing the issue:**
Type the following:

```tsx
let foo = 1 * 1; // hello
let bar = 1 / 1; // hello
```

`// hello` should look the same on both lines, but the syntax highlighting interprets the division symbol as the start of a regex that doesn't end until the first forward slash in the comment.  See below:

![image](https://user-images.githubusercontent.com/154621/59371887-0af4b500-8cfb-11e9-8543-b814d64f5820.png)

Feel free to try it out for yourselves here: https://microsoft.github.io/monaco-editor/playground.html

**Comment by alexburner** [comment]
This in now visible in the new TS playground, too: 

![Screenshot](https://imgur.com/n6j1cNH.png)

https://www.typescriptlang.org/play/#code/DYUwLgBAZg9jEF4IHIBGBDATsg3BA9PhABYjDDwDuMmwAJgFCiQaaIQBMBnehJZFCNVqMGQA

**Comment by Guocover** [comment]
have the same problem...
