### ISSUE TITLE
Server side coloration

### ISSUE THREAD

**Issue by lcswillems** [microsoft/monaco-editor#1480]
Hi,

I would like to colorize some code on my NodeJS server.

Here is my NodeJS code:

```
import monaco from 'monaco-editor';

monaco.editor.colorize(
    "function hello() {\n\talert('Hello world!');\n}",
    "javascript",
    {}
)
.then(html => console.log(html));
```

But I get this error:

```
Rollup: Parse Error
Unexpected token (Note that you need plugins to import files that are not JavaScript)

node_modules/monaco-editor/esm/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp.css
  | 4:  *--------------------------------------------------------------------------------------------*/
  | 5:
  | 6: .monaco-editor .accessibilityHelpWidget {
  | ^
  | 7:   padding: 10px;
  | 8:   vertical-align: middle;

```

Do you know what I should modify to colorize the code on server side?

**Comment by chrstntdd** [comment]
Have you tried using [`ignore-styles`](https://www.npmjs.com/package/ignore-styles) yet? It looks like the error is related to the CSS being requested within node.

**Comment by jaydenseric** [comment]
Even if you setup Webpack with the appropriate loaders for CSS, you get runtime errors such as `ReferenceError: document is not defined`.

It's a pity you can't just do something like:

```js
const colorize = require('monaco-editor/colorize')
```

Or even better:

```js
const colorize = require('monaco-editor-colorize')
```

A lightweight dependency that just works in Node.js without Webpack, etc. would be great; I'm trying to make a Babel plugin that colorizes code strings at build time. The use case being syntax highlighting code examples in a documentation site, matching popular VS Code syntax themes.

I can't even tell what [`colorize()`](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#colorize) actually does, the docs are very skimpy. I'm assuming it wraps parts of the syntax in the input string in spans with class names for styles to target. Also, it's `languageId` parameter is only documented as being a string; so what are the right ID's to use for a given language?

**Comment by jaydenseric** [comment]
Related:

- https://github.com/Microsoft/monaco-editor/issues/420
- https://github.com/microsoft/monaco-editor/issues/438

**Comment by alexdima** [comment]
Let's track in #420
