### ISSUE TITLE
Editor props/extends the actual width of the parent that is a flexbox item

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/monaco-editor#1482]
**monaco-editor version:** 0.17.0 (latest)
**Browser:** Edge dev 76.0.182.6
**OS:** Windows 10

When the editor is placed inside a flexbox item, it will prop the item horizontally and actually the flexbox item (and eventually the editor) cannot shrink back with `editor.layout()`, unless we explicitly specify a smaller width in `layout` method.

**Steps or JS usage snippet reproducing the issue:**
Go to https://microsoft.github.io/monaco-editor/playground.html , then enter the following code and click "run" button.

### JS
```javascript
var edt = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
    automaticLayout: true
});
```

### CSS
```css
/*
.monaco-editor {
    position: absolute;
}
*/
```

### HTML
```html
<div style="display: flex; background-color: #CCCCFF">
    <div style="background-color: #CCCCCC;">--- Test ---</div>
    <div id="container" style="flex: 1 1 auto; border: 2px solid red; height: 100px"></div>
</div>
```

Resize the window. When the window is shrinking in width, **the editor cannot shrink accordingly**. Actually the `container` has been propped by the editor horizontally.

![image](https://user-images.githubusercontent.com/50703224/59619780-26d3ce80-90e0-11e9-98e7-6ea0b87b1da1.png)
![image](https://user-images.githubusercontent.com/50703224/59619815-38b57180-90e0-11e9-9b48-7f171b1e89ae.png)

Remove the comment marks in "CSS" tab, click "Run", and resize the window again. This time the editor can resize properly.
![image](https://user-images.githubusercontent.com/50703224/59619855-4d920500-90e0-11e9-827f-f16e45f3ec00.png)

**Comment by redbullmarky** [comment]
Hey, found this issue due to the same problem. Also found a (lucky solution) whilst I still had the tab open :) Below is my rough structure

#code_editor below is what monaco is set up to use. I put an overflow:hidden on the 'main' panel's div. and voila! Both method for resizing (manual via window resize listener, as well as Monaco's automaticLayout) worked perfectly; the latter being somewhat 'smoother'

```html
<div class="ide">
   <div class="ide-main" style="overflow: hidden;">
      <div class="ide-editor-wrapper">
         <div class="ide-editor" id="code_editor"></div>
      </div>
      <div class="ide-console"></div>
   </div>
   <div class="ide-sidebar">
      ...sidebar content...
   </div>
```

```css
.ide { display:flex; flex-direction:row; }
.ide-main { flex:3; display:flex; flex-direction:column; }
```

**Comment by chenxinyanc** [comment]
@redbullmarky `overflow:hidden` will also trim the auto-completion and syntax hint popups, which is not desirable. Actually, I closed this issue because later I found out it's not really a *problem* with the implementation of monaco-editor, but there is no rule to restrict `div.container` (as in my example above) from not being extended by the content. If you check out example code on the web, all the containers of monaco-editor have explicitly specified width.

Actually, if you replace the HTML field in my example above with
```html
<div style="display: flex; background-color: #CCCCFF">
    <div style="background-color: #CCCCCC; width: 20%;">--- Test ---</div>
    <div id="container" style="flex: 1 1 auto; border: 2px solid red; height: 100px; width: 100%;"></div>
</div>
```

You will find the editor resizing without any problem even though there is no `position: absolute` applied, and this should be the correct fix to solve the root cause of the problem.

And I don't think `position: absolute` is a correct "fix", either. If you replace the HTML field in my example above with, and enable `position: absolute` for `.monaco-editor`
```html
<div style="height: 100%; overflow-y: auto;">
	<div style="height: 100px; background-color: #FFFFCC;">drag the scroll bar and see what happens</div>
	<div style="display: flex; background-color: #CCCCFF;">
		<div style="background-color: #CCCCCC; width: 20%;">--- Test ---</div>
		<div id="container" style="flex: 1 1 auto; border: 2px solid red; height: 100px; width: 100%;"></div>
	</div>
	<div style="height: 2000px; background-color: #FFFFCC;">very long div</div>
</div>
```
You will see the editor won't align with the container when you scroll the div.

![image](https://user-images.githubusercontent.com/50703224/60485273-fb033c00-9cce-11e9-8461-aef9cddad059.png)

Though you can still use `position: relative` container to fix this issue, but it is somewhat too far from "using monaco-editor natually" and IMO it is too much of hacking.
