### ISSUE TITLE
Possible to Trigger Show More / Show Less in Intellisense Tips?

### ISSUE THREAD

**Issue by justin2taylor** [microsoft/monaco-editor#1487]
I tried:

editor.ui.trigger('anyString', 'editor.action.readMore', {});
and
editor.ui.trigger('anyString', 'editor.action.triggerReadMore', {});

but no dice. Wasn't sure if this is possible or not. Thanks!

**Comment by Reusjs** [comment]
I also met the same demand. Have you solved it?

**Comment by alexdima** [comment]
`toggleSuggestionDetails`
