### ISSUE TITLE
Focusing on a line in IE (11)

### ISSUE THREAD

**Issue by Hillyman** [microsoft/monaco-editor#1488]
Currently I am implementing monaco within my project that it is required to work within both IE and Chrome.
However I am currently having the problem where I cannot change the cursor position within IE when clicking on lines with code. The event onDidChangeCursorPosition is never fired.
I can focus on the editor by clicking below all of the lines but within the editor.

![clickIssue](https://user-images.githubusercontent.com/9124092/59772929-972b4d00-92a4-11e9-99aa-464d630aca1b.gif)

In the above GIF I loop though clicking each line one by one with right click then left click.
This issue does not occur in the 'Monaco Editor Playground'.

Anyone else has similar issues as this?

**Comment by jhlee8804** [comment]
+1

**Comment by Hillyman** [comment]
Turned out to be position:absolute issues. Changed everything to be position relative at it started working again.
