### ISSUE TITLE
someone have tokens provider for highlight groovy language?

### ISSUE THREAD

**Issue by MorganaUzhgorod** [microsoft/monaco-editor#1490]
Hi 🖖
maybe someone have tokens provider for highlight groovy language?

**Comment by vasiltabakov** [comment]
Check these:
https://github.com/NeekSandhu/monaco-textmate
https://github.com/Jakehp/language-groovy/blob/master/grammars/groovy.cson
https://github.com/gluons/cson-json-converter

**Comment by alexdima** [comment]
Let's track in #129
