### ISSUE TITLE
IConfigurationChangedEvent.tabFocusMode never resets to false

### ISSUE THREAD

**Issue by mattmasson** [microsoft/monaco-editor#1493]
**monaco-editor version:** 0.17.0
**Browser:** Edge (Chromium) Version 77.0.189.3 (Official build) dev (64-bit)
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**

1. add handler for `onDidChangeConfiguration`
2. on editor surface, press Ctrl+M to toggle tab focus mode change
3. event is raised and `IConfigurationChangedEvent.tabFocusMode` will be true, as expected
4. on editor surface, press Ctrl+M again to toggle tab focus mode (back to false)
5. `IConfigurationChangedEvent.tabFocusMode` is still true

issue can be reproduced in the playground.

```javascript
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

editor.onDidChangeConfiguration((e) => {
    alert("Tab focus mode is " + e.tabFocusMode);
});
```

**Comment by alexdima** [comment]
The change event contains only booleans. The booleans indicate which properties have changed, so `IConfigurationChangedEvent.tabFocusMode` means:
- true when `tabFocusMode` has changed from false->true or from true->false
- false when `tabFocusMode` has remained unchanged false->false or true->true.
