### ISSUE TITLE
Two-finger scrolling in Edge breaks when a swipe action is cancelled

### ISSUE THREAD

**Issue by brkerr** [microsoft/monaco-editor#1494]
**monaco-editor version:** 0.17.1 and older
**Browser:** Edge (44.17763.1.0)
**OS:** Windows 10

This one is slightly obscure, but can block two-finger scroll in monaco until you reload the tab in Edge.

1. Go here - https://microsoft.github.io/monaco-editor/
2. Start a two-finger swipe right to go back in Edge but don't complete it, so that it remains on the same page
3. Hover over the Monaco window
4. Repeat step 2
5. The Monaco window no longer responds to two-finger scrolling gestures (click and drag and mousewheel both work)

**Comment by noshlag** [comment]
I have been experiencing this issue for a while when reviewing pull requests with microsoft.visualstudio.com.  In step5, I think @brkerr may have mean to write that 

> click and drag and mousewhell both **don't** work

**Comment by brkerr** [comment]
The only repros that I could get would cause finger gestures to stop working but other forms of scrolling worked fine.

**Comment by alexdima** [comment]
Closing, as Microsoft Edge Legacy has reached end of support on March 9, 2021. See [the end of support for Microsoft Edge Legacy announcement](https://docs.microsoft.com/en-us/lifecycle/announcements/edge-legacy-eos-details)
