### ISSUE TITLE
Do not skip closing parentheses if syntax error is present.

### ISSUE THREAD

**Issue by DrSammyD** [microsoft/monaco-editor#1495]
**monaco-editor version:** 3.1.0
**Browser: Chrome **
**OS: Windows 10** 

**Steps or JS usage snippet reproducing the issue:**
Write javascript;
```js
var funk = "some stack";
var str = ("some string" + func && (" some other string" + func))
```

Press `(` in front of `func &&`

```js
var func = "some stack";
var str = ("some string" + (func && (" some other string" + func))
```

Move to end of second set of parentheses `(" some other string" + func)`
Press `)`.

Commit your code, watch as validation doesn't catch it until your CI board goes red with a runtime syntax error.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/issues/37315
