### ISSUE TITLE
How to set viewport for hint?

### ISSUE THREAD

**Issue by grindpride** [microsoft/monaco-editor#1496]
**monaco-editor version:** 0.14.1

Looks like hint position calucated relative to viewport by default. How can I set the calculation so that the position of the hint is calculated relative to the editor div? 
![image](https://user-images.githubusercontent.com/25076736/60167846-96e30280-980c-11e9-8b71-f6edd430aaf9.png)

**Comment by alexdima** [comment]
@grindpride Can you provide some self-contained HTML that reproduces the problem?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
