### ISSUE TITLE
Gutter highlights issues: Highlights appear on subsequent line after clicking line number in gutter or selecting multiple lines

### ISSUE THREAD

**Issue by dakotareier** [microsoft/monaco-editor#1499]
**monaco-editor version:** 0.17.0
**Browser: 75.0.3770.100 (Official Build) (64-bit)**
**OS: Mac OS X 10.14.4** 

**Steps or JS usage snippet reproducing the issue:**
Gutter highlighting appears to be strictly based on cursor position. This leads to two unexpected behaviors: 

1) After clicking a line number in the gutter, the line is highlighted and the cursor moves to the subsequent line. As a result, the gutter highlight moves to the subsequent line. If the user clicks on the current line number, the cursor moves the another line. That seems mildly surprising. 

2) When dragging to highlight several lines of text, only the final line's gutter is highlighted (because that's where the cursor ended up). In some other editors (like Atom), the gutters for all selected lines are highlighted, not just the final line in the selection. 

This shows both (minor) issues:
![monaco-gutter-highlights](https://user-images.githubusercontent.com/205031/60280726-2221ce00-98c9-11e9-9a2d-0389587eeff8.gif)

**Comment by dakotareier** [comment]
Compare behavior with multiple line gutter highlighting in Atom: 
![65814280_896814027319337_4815429590388310016_o](https://user-images.githubusercontent.com/205031/60280842-5b5a3e00-98c9-11e9-8cfa-5c019a6a3e77.jpg)

**Comment by alexdima** [comment]
Current line highlighting should be disabled when having a selection, can you reproduce at https://microsoft.github.io/monaco-editor/ ?

![image](https://user-images.githubusercontent.com/5047891/70640799-da0b2380-1c3c-11ea-9622-020433cb38dd.png)

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
