### ISSUE TITLE
Context menu padding/margin error when used with fabric ui

### ISSUE THREAD

**Issue by andrejohansson** [microsoft/monaco-editor#1502]
**monaco-editor version:** 0.17.0
**Browser:** Firefox Developer Edition 68.0b14 (64-bit) & Chrome 75.0.3770.100 (Official Build) (64-bit)
**OS:** Windows

I'm trying to use the monaco editor in a typescript app I have, together with [Fabric UI](https://developer.microsoft.com/en-us/fabric#/controls/web). I have not done any special css customization to either of them but they seem to share some css classes since the context menu gets quite a lot of margin/padding. 

Any guidance to how I can enforce the default look and feel of the menu? Which css classes etc should I target?

**Context Menu**
Too much space!

![image](https://user-images.githubusercontent.com/2828428/60497342-f0d44400-9cb4-11e9-8109-aed21738951d.png)

**Command Palette**
Looks fine!

![image](https://user-images.githubusercontent.com/2828428/60497745-bb7c2600-9cb5-11e9-8f87-cbd7251c5093.png)

**Comment by alexdima** [comment]
I believe there are CSS styles from your stylesheet which end up targeting dom nodes from the context menu. Please comment out your CSS and then slowly add it back in or use the inspect element from Developer Tools on those dom nodes to discover which CSS is affecting the monaco-editor dom nodes.
