### ISSUE TITLE
change  fontFamily with Microsoft Yahei for  Line feed length   error

### ISSUE THREAD

**Issue by tongbinzuo** [microsoft/monaco-editor#1505]
**monaco-editor version:** 0.16.2
**Browser:**
**OS:** 

**Steps or JS usage snippet reproducing the issue:**

I  use   api  editor.updateOptions({ fontFamily:‘Microsoft Yahei’ }),
after updating the font Line feed length error with in Out of the screen for after 
editor.config：
   wordWrap: 'bounded',

**Comment by tongbinzuo** [comment]
Input  content   ‘@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@’
compute  Line feed length error

**Comment by alexandrudima** [comment]
@tongbinzuo I cannot reproduce what you describe. I have executed the following sample:
```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
editor.updateOptions({ fontFamily: "Microsoft Yahei" });
```
at https://microsoft.github.io/monaco-editor/playground.html and it works for me:
![image](https://user-images.githubusercontent.com/5047891/70448909-5a951d00-1aa1-11ea-9274-037387394aaf.png)

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
