### ISSUE TITLE
Get html formatted selected text with wrapped lines

### ISSUE THREAD

**Issue by Micbu** [microsoft/monaco-editor#1506]
**monaco-editor version:** 0.15.4
**Browser:** Chrome
**OS:** Windows

I’m looking for a way to get programatically html formatted selected text in Monaco editor.

I'm using (According to [this question](https://github.com/Microsoft/monaco-editor/issues/866)):
`viewModel.getHTMLToCopy([currentCommandRange]); `
when `currentCommandRange` based on `editor.getSelection` method.

It works well, but for **wrapped lines** it’s broken.
While getSelection and other Monaco editor methods consider one long line (which displayed in a few lines) as 1 line, getHtmlToCopy consider it as multiple lines. 
Therefore the returned value from  getHtmlToCopy is truncated.

For example:
For the following selected text – 
![image](https://user-images.githubusercontent.com/22526773/61048645-136c0880-a3eb-11e9-9876-56f5055f24a8.png)

`getSelection` considers the 3 first lines as 1 line, and `currentCommandRange `value is: Range {startLineNumber: 1, startColumn: 1, endLineNumber: 3, endColumn: 12}

But `viewModel.getHTMLToCopy([currentCommandRange])`  returns the displayed 3 lines (highlighted):
![image](https://user-images.githubusercontent.com/22526773/61048672-2bdc2300-a3eb-11e9-9bd3-9e5ece21298e.png)

How can I get the formatted selected text?
Can I get selection for displayed wrapped lines?

Thanks!

**Comment by alexandrudima** [comment]
@Micbu The view model (which is not public API) uses view coordinates. View coordinates are considered editor implementation detail, same as the view model.

If you have taken the brave route of accessing things outside of the API, you can convert model coordinates to view coordinates using `viewModel.coordinatesConverter.convertModelRangeToViewRange` and pass the view range to `viewModel.getHTMLToCopy`

**Comment by michal-ayash** [comment]
Thanks @alexdima 
I'm not sure how to get the model range for the display text (also for wrapped text as I mentioned above).

Here is the current code, but it's broken for wrapped text: 
   
```
        const viewModel = (editor as any)._modelData.viewModel;

        const fun = viewModel.getHTMLToCopy.bind(viewModel);

        const selectedTextAndPosition = this.$monacoEditorHelper.getSelectedQueryTextAndPosition();

        const startPosition = selectedTextAndPosition.startPosition;

        const endPosition = selectedTextAndPosition.endPosition;

        const currentCommandRange = new monaco.Range(startPosition.lineNumber, startPosition.column, endPosition.lineNumber, endPosition.column);

        const queryText = selectedTextAndPosition.text;

        const queryHtml = fun([currentCommandRange]);`
```

Can you please fix this snippet code to have the right range please?

Thanks,
Michal

**Comment by alexdima** [comment]
@michal-ayash Can you please provide a sample that is self-contained and which executes at https://microsoft.github.io/monaco-editor/playground.html

**Comment by michal-ayash** [comment]
@alexdima , We have some methods which provide the selected text position, but it's based on '\n' which is irrelevant for wrapped text.
How can I get the right position for wrapped text (one long line which will be displayed in multiple lines)?

**Comment by alexdima** [comment]
@michal-ayash 

* `editor.getSelection()` and `editor.getModel().getFullModelRange()` return model coordinates, just like all the public editor API.
* the internal call to `editor._modelData.viewModel.getHTMLToCopy()` expects view coordinates.
* it is possible to use another internal call to convert from model coordinates to view coordinates -- e.g. -- `editor._modelData.viewModel.coordinatesConverter.convertModelRangeToViewRange`

**Comment by alexdima** [comment]
FYI The internal `getHTMLToCopy` will accept model ranges in the next editor release. This will not be documented in the changelog because it is not API.
