### ISSUE TITLE
monaco-editor creates global variable---define, which lead to the conflicts with CodeMirror

### ISSUE THREAD

**Issue by amily666** [microsoft/monaco-editor#1508]
monaco-editor creates some global variables,  define, which lead to the conflicts with CodeMirror:
CodeMIrror is not defined

**Comment by oldrich-s** [comment]
Try to use parcel to bundle monaco. That should help. 

https://github.com/microsoft/monaco-editor/blob/master/docs/integrate-esm.md#using-parcel

**Comment by kagol** [comment]
@amily666 have you solve your problem?

**Comment by alexdima** [comment]
You can also try to load the editor via webpack which does not create any globals. The `define` is the AMD `define` and it respects the spec. Alternatively, you can try to first load `require.js`, which defines `define`, and then the Monaco Editor will pick that up and not overwrite it.
