### ISSUE TITLE
Can not resolve ts modules correctly

### ISSUE THREAD

**Issue by xiaoxiyao** [microsoft/monaco-editor#1511]
**monaco-editor version:** 0.17.0
**Browser:** chrome 75.0.3770.142
**OS:** windows 10

copy follow code to the [playground](https://microsoft.github.io/monaco-editor/playground.html)
```javascript
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
	target: monaco.languages.typescript.ScriptTarget.ES6,
    isolatedModules: true
});

let model = monaco.editor.createModel([
    "import {A} from './script2'",
	"let a = new A();"
].join('\n'),'typescript', monaco.Uri.file('/script.ts'));

let editor = monaco.editor.create(document.getElementById("container"), {
	model: model,
	language: "typescript"
});

let model2 = monaco.editor.createModel("export class A {}",'typescript',monaco.Uri.file('/script2.ts'));
```
At first it works:
![image](https://user-images.githubusercontent.com/12003562/61347819-f0c96c00-a890-11e9-9c84-2569990c25fe.png)
But after a while (several minutes), I start to edit the code, the module can not be found:
![image](https://user-images.githubusercontent.com/12003562/61347948-66353c80-a891-11e9-897a-9c51d9d4777c.png)

**Comment by yln99517** [comment]
duplicate
#1310

**Comment by xiaoxiyao** [comment]
@yln99517 Thanks, close this issue
