### ISSUE TITLE
Strange white mask in diff editor

### ISSUE THREAD

**Issue by Symbolk** [microsoft/monaco-editor#1515]
**monaco-editor version:** 0.17.1
**Browser:** Chromium
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
Recently I developed a tool for developers named SmartCommit based on Electron and Vue (https://github.com/Symbolk/SmartCommit ), which takes over the job of git-status, git-diff, git-add, git-commit and git-push commands. I provide two kinds of diff views with monaco diff editor in the two tabs of a modal r: side by side and inline diff. 

However, I found a strange bug with it: the default diff view is ok (Figure 1), but when switching to the other diff view, there will be a strange white mask with a close button  (Figure 2) at the top-right corner, which must be clicked to see the diff view  (Figure 3).

Figure 1
![image](https://user-images.githubusercontent.com/14107297/61586516-fd0f3b00-aba8-11e9-8ac7-79bd57c8ea52.png)
Figure 2
![image](https://user-images.githubusercontent.com/14107297/61586520-0c8e8400-aba9-11e9-983e-a61264ecf10b.png)
Figure 3
![image](https://user-images.githubusercontent.com/14107297/61586526-2def7000-aba9-11e9-816b-342ba8a31b0b.png)

Related code are open sourced at https://github.com/Symbolk/SmartCommit, which is easy to compile and inspect. Thanks for any help!

**Comment by mattduffield** [comment]
Hi @Symbolk, did you ever figure this out? I am getting the same thing.

**Comment by Symbolk** [comment]
> Hi @Symbolk, did you ever figure this out? I am getting the same thing.

Unfortunately not.

**Comment by mattduffield** [comment]
I just figured it out on my side. By adding a `layout()` on the editor, I was able to get it to render properly. Hopefully, that will get you working as well.

**Comment by Symbolk** [comment]
@mattduffield Seems like it does not work for me. I put two diff editors in two tabs of a Vue componment called SweetModal (https://sweet-modal-vue.adepto.as/). When the modal is open, the editor in the default tab is always ok, but the editor in the other tab is always covered by the white mask.

**Comment by mattduffield** [comment]
Hmm, I also have a regular editor and then I allow the user to launch a diff editor. By calling `layout()`, it now works fine. Previously, it was covered like you are describing. I hope you figure it out.

**Comment by mattduffield** [comment]
![Screen Shot 2019-09-03 at 7 57 55 AM](https://user-images.githubusercontent.com/903534/64184629-9bd1bd00-ce20-11e9-9a86-50f5b139ad3b.png)

**Comment by alexdima** [comment]
Do you have a standalone reproducible case? That looks like the diff review which is available when pressing F7 (it is an accessible friendly way to navigate a diff).

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
