### ISSUE TITLE
能不能把官方文档重写一下啊，给一堆API那叫什么玩意啊

### ISSUE THREAD

**Issue by BinghuiXie** [microsoft/monaco-editor#1516]
**monaco-editor version:** 0.X.Y
**Browser:**
**OS:** 

**Steps or JS usage snippet reproducing the issue:**

**Comment by gitdust** [comment]
看不懂就去学英文，别在这丢人现眼

**Comment by GaryChangCN** [comment]
monaco 的文档还不够好？？？

**Comment by Kang-Jun-sik** [comment]
should write in english....

**Comment by 646602196** [comment]
你自己看不明白就别BB

**Comment by pinksky** [comment]
> monaco 的文档还不够好？？？

没有旧版本的api，打开官网直接是最新版，去tag中找，也是链接到最新版的，找不到旧版本的。
另外，旧版本和最新版之间api还有break升级，请问这个问题你是怎么解决的啊？是随时保持更新到最新版本吗？

**Comment by gitdust** [comment]
> > monaco 的文档还不够好？？？
> 
> 没有旧版本的api，打开官网直接是最新版，去tag中找，也是链接到最新版的，找不到旧版本的。
> 另外，旧版本和最新版之间api还有break升级，请问这个问题你是怎么解决的啊？是随时保持更新到最新版本吗？

不建议使用旧版吧，更新最新版就好了。

**Comment by lwinhong** [comment]
我每次升级都要改代码

**Comment by rebornix** [comment]
Please read our [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) when creating issues.
