### ISSUE TITLE
monaco.KeyMod.chord improperly typed

### ISSUE THREAD

**Issue by gperl27** [microsoft/monaco-editor#1518]
`monaco.KeyMod.chord` yields Typescript error `error TS2554: Expected 2 arguments, but got 1.` when using like the example in the playground - https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance.

Using a workaround that looks like this for now:

```
// good
monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_S, monaco.KeyCode.Unknown)

// TS error
monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_S)
```

A possible solution would be to make the second parameter in the definition optional, but not sure if that would have side effects down the line. 

Currently, it requires 2 params:
https://github.com/microsoft/monaco-editor/blob/dfaf55beb9561c2bbbc8b23574f005d5d22947f4/monaco.d.ts#L380

**Comment by alexandrudima** [comment]
@gperl27 I'm not 100% sure what the problem is. `monaco.KeyMod.chord` appears to be properly typed:
```ts
	export class KeyMod {
		static readonly CtrlCmd: number;
		static readonly Shift: number;
		static readonly Alt: number;
		static readonly WinCtrl: number;
		static chord(firstPart: number, secondPart: number): number;
	}
```
To create a chord keybinding, you need to specify the first part **and** the second part.

**Comment by gperl27** [comment]
@alexandrudima you are correct. However the example in the playground (link above) implements a `chord` without the second parameter, indicating that the interface for chord's second parameter could be optional.

Hence, updating `secondPart` in the interface to be an optional number could be the correct interface.

Or the example could correctly implement the `chord` (even if it's not getting type-checked).

**Comment by alexandrudima** [comment]
@gperl27 The sample that is linked uses `monaco.KeyMod.chord` with two arguments:

```js
	// An optional array of keybindings for the action.
	keybindings: [
		monaco.KeyMod.CtrlCmd | monaco.KeyCode.F10,
		// chord
		monaco.KeyMod.chord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_K, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_M)
	],
```

**Comment by gperl27** [comment]
Ah you're right, my apologies.
