### ISSUE TITLE
Issue with Link Provider's resolveLink method

### ISSUE THREAD

**Issue by chc5** [microsoft/monaco-editor#1520]
**monaco-editor version:** 0.17.0
**monaco-editor-webpack-plugin:** 1.7.0
**Browser:** Chrome
**OS:** -

**Steps or JS usage snippet reproducing the issue:**
1. Register a Link Provider for monaco-editor
```
    monaco.languages.registerLinkProvider('json', {
      provideLinks:
          (model: monaco.editor.ITextModel, token: monaco.CancellationToken):
              monaco.languages.ProviderResult<monaco.languages.ILinksList> => {
            return {
              links: [{
                range: {
                  startLineNumber: 1,
                  startColumn: 1,
                  endLineNumber: 2,
                  endColumn: 10,
                }
              }]
            };
          },
      resolveLink:
          (link: monaco.languages.ILink, token: monaco.CancellationToken):
              monaco.languages.ProviderResult<monaco.languages.ILink> => {
            // Call method to set position on the editor
            return {range: link.range};
          }
    });
```
2. Click on the link on the monaco editor.
3. This results with the following error:
```
ERROR Error: missing

Error: missing
    at eval (getLinks.js:123)
    at ZoneDelegate.invoke (zone.js:390)
    at Object.onInvoke (VM5290 core.js:17652)
    at ZoneDelegate.invoke (zone.js:389)
    at Zone.run (zone.js:149)
```

I want to implement a feature that redirects these links to a specific line number on the editor. To do so, I passed in a method in resolveLink that allows me to set the position on the editor. 

The resolveLink method gets called when a url is not provided in monaco.languages.ILink in the provideLinks method. However, monaco-editor throws an error when a url is not provided when returning the link in resolveLink method. If I provide a url in the resolveLink method, the resolveLink will not be called again when the same link is clicked again. If I don't provide a url, it works perfectly as expected by allowing me to redirect this link to a specific line number multiple times, but it throws the same error above on the console.

**Comment by rcjsuen** [comment]
@chc5 Sounds to me like you should use a `DefinitionProvider` or something else instead of a `LinkProvider` if you're trying to navigate to places in the current file.

**Comment by mmulet** [comment]
Looks like this is an error in [links.ts ](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/links/links.ts)
Line 301:
```typescript
err => {
			// different error cases
			if (err === 'invalid') {
				this.notificationService.warn(nls.localize('invalid.url', 'Failed to open this link because it is not well-formed: {0}', link.url!.toString()));
			} else if (err === 'missing') {
				this.notificationService.warn(nls.localize('missing.url', 'Failed to open this link because its target is missing.'));
			} else {
				onUnexpectedError(err);
			}
		});
	}
```
It compares the rejected promise errors to 'invalid' and 'missing', but in [getLinks.ts](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/links/getLinks.ts)
it rejects an Error not a string
Line 61:
```typescript
return Promise.resolve(this._provider.resolveLink(this._link, token)).then(value => {
				this._link = value || this._link;
				if (this._link.url) {
					// recurse
					return this.resolve(token);
				}

				return Promise.reject(new Error('missing'));
			});
```
So instead of the warning in throws an error. The code in links.ts should be:
```typescript
err => {
			// different error cases
                       const errorMessage = err ? err.message : undefined;
			if (errorMessage === 'invalid' || err === 'invalid') {
				this.notificationService.warn(nls.localize('invalid.url', 'Failed to open this link because it is not well-formed: {0}', link.url!.toString()));
			} else if (errorMessage === 'missing' || err === 'missing') {
				this.notificationService.warn(nls.localize('missing.url', 'Failed to open this link because its target is missing.'));
			} else {
				onUnexpectedError(err);
			}
		});
	}
```

**Comment by mmulet** [comment]
I opened an [issue in the vscode repo](https://github.com/microsoft/vscode/issues/78731) addressing this

**Comment by mmulet** [comment]
Added [vscode pull request](https://github.com/microsoft/vscode/pull/78732)

**Comment by chc5** [comment]
@rcjsuen Yes, I am trying to navigate to places in the current file. However, ```DefinitionProvider```'s ```provideDefinition``` method and ```LinkProvider```'s ```provideLink``` method requires me to provide a Uri to make the links on the editor work. Currently, I found an alternative solution by taking advantage of ```resolveLink``` method and this allows me to navigate in the current file on my own.
