### ISSUE TITLE
Using Monaco for syntax highlighting?

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#1521]
I'd like to experiment with using Monaco for syntax highlighting, the kind that's usually implemented via [Prism](https://github.com/PrismJS/prism) or [highlight.js](https://highlightjs.org/).

Has this been tried before? Would this be doable in a performant manner?

**Comment by spahnke** [comment]
You can have a look at the `colorize` or `colorizeElement` API, see https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#colorize

**Comment by fabiospampinato** [comment]
@spahnke thank you so much! There's almost no documentation about it but it seems like that method could be used as a replacement for Prism or highlight.js indeed, have you done that in the past? Any drawbacks worth mentioning?

**Comment by spahnke** [comment]
I used it to replace highlight.js in our documentation because we used Monaco already. Nothing big enough though to notice any drawbacks.

**Comment by fabiospampinato** [comment]
Great, thanks for the info!
