### ISSUE TITLE
"Peek Definition" no longer works with latest version of Monaco

### ISSUE THREAD

**Issue by ayoob-lfc** [microsoft/monaco-editor#1522]
**monaco-editor version:** 0.17.1
**Browser:** Chrome
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**

1.  Goto https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance
2. Right-click on "Person" (line 7 in the preview box)
3. Select "Peek Definition":

![image](https://user-images.githubusercontent.com/46787382/61994744-74940d00-b076-11e9-955b-3621bb64cb20.png)

Expected outcome would be to see the peek definition widget, but what actually happens is nothing

**Comment by donnisnoni95** [comment]
I have same issue too...

**Comment by spahnke** [comment]
The following error is thrown if you enable `Pause on caught exceptions`
```
Error: [createInstance] ReferenceWidget depends on UNKNOWN service IPeekViewService.
```
The "Peek references" command has the same issue.

**Comment by alexdima** [comment]
I can no longer reproduce, so I think this has been fixed in the meantime.
