### ISSUE TITLE
EnterRules - before & afterText no multiline?

### ISSUE THREAD

**Issue by Jan-M-B** [microsoft/monaco-editor#1523]
Monaco-Editor Version: 0.17.1
Browser: Firefox
OS: Windows 10

Hi,

currently I am trying to auto complete  (real autocomplete, so no widget with suggestions) the creation of a Sub in a VisualBasic like language. 
Please paste the following code in to the Playground editor (https://microsoft.github.io/monaco-editor/playground.html):
```
monaco.editor.create(document.getElementById("container"), {
	value: "Sub XYName",
	language: "vb"
});

monaco.languages.setLanguageConfiguration('vb', {
	onEnterRules:[
        {
           beforeText: /^\s*(?:sub)\s*\w+/i,
            action: {
                indentAction: monaco.languages.IndentAction.Indent,
				appendText: "	\nEnd Sub"
            }
        }
		
    ]
});
```
Click on the Run button and place your cursor to the end of the code line and press Enter. A line with an intent and the "End Sub" statement was appended. To avoid that the lines are appended again, I have to check with the afterText option if the next lines already contain the End Sub statement. But here is the problem: the before & afterText options only seem to support one line, so the regex expression of afterText is only applied to the text next to "Sub XYName" - in my case an empty string.

Anybody knows whether this is the normal behaviour or has another idea to solve my problem?

Jan

**Comment by alexandrudima** [comment]
@Jan-M-B That is how the enter rules work. They are very localized and can only target the text on the line before the <kbd>Enter</kbd> and the text on one line above the <kbd>Enter</kbd>
