### ISSUE TITLE
readOnly mode allows 'Dead' keys to be inputted to the editor

### ISSUE THREAD

**Issue by jonybur** [microsoft/monaco-editor#1524]
**monaco-editor version:** 0.17.1
**Browser:** Chrome
**OS:** macOS

**Steps or JS usage snippet reproducing the issue:**
1: Go to https://microsoft.github.io/monaco-editor/playground.html
2: Set up the `readOnly` property to `true`
3: Type a key that has a "Dead" code* (try with key on the keyboard to the left of number "1", on top of "Tab") , the key will be inputted in Monaco, when it shouldn't be allowed.

Keyboard setup:
<img width="780" alt="Screen Shot 2019-07-30 at 14 16 04" src="https://user-images.githubusercontent.com/11148144/62150845-63950700-b2d5-11e9-96e6-359642f4fdad.png">

Gif showing bug:
![monacoReadOnly](https://user-images.githubusercontent.com/11148144/62150839-60018000-b2d5-11e9-98aa-2fab44c3f26c.gif)

* from [W3.org](https://www.w3.org/TR/uievents-key/#keys-composition)
> A dead key combining key. It may be any combining key from any keyboard layout. For example, on a	PC/AT French keyboard, using a French mapping and without any modifier activiated, this is the key value U+0302 COMBINING CIRCUMFLEX ACCENT. In another layout this might be a different unicode combining key.
For applications that need to differentiate between specific combining characters, the associated compositionupdate event’s data attribute provides the specific key value.

**Comment by alexdima** [comment]
This has been fixed in the meantime because now the `<textarea>` gets `readonly='true'` when the editor is read only.
