### ISSUE TITLE
How to run a headless Monaco Editor?

### ISSUE THREAD

**Issue by cx3k** [microsoft/monaco-editor#1525]
I'm trying to communicate with an ITextModel without using an editor. My environment can't performantly render HTML so I'd like to render natively and communicate over javascript with a model, forwarding/receiving events like render, scroll, type, selection, completion etc.

Realizing this is not the intended use, I'd still like to tap in to the API with as little as possible private API use.

First hurdle is understanding the scrolling/visible text region/font rendering cycle. Can anyone point me at the right direction for where this is set up in relation to the model?

**Comment by rebornix** [comment]
You may need to shim `window`, `global`, etc to run Monaco Editor in a pure JS environment.

**Comment by alexdima** [comment]
The unit tests of `monaco-languages` at https://github.com/microsoft/monaco-languages/tree/master/test execute in nodejs with the help of a jsdom mock.
