### ISSUE TITLE
automaticLayout not working on Firefox

### ISSUE THREAD

**Issue by ThePeach** [microsoft/monaco-editor#1526]
**monaco-editor version:** 0.15.6
**Browser:** Firefox 68.0.1
**OS:** Mac OSX 10.14.5

**Steps or JS usage snippet reproducing the issue:**
as suggest in many places, in order to have the editor take as much vertical space as possible, it's been recommended to set the wrapper div to `height: 100%` and create the editor with `automaticLayout: true`. This works without problems on Webkit browsers (tested on Chrome 75).
It seems it does _not_ work as expected on Firefox; the editor has the window height increased infinitely.

**Comment by alexdima** [comment]
@ThePeach I am having trouble reproducing this. Could you please include a self-contained HTML that demonstrates the problem?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
