### ISSUE TITLE
how to enable syntax error checking automatically?

### ISSUE THREAD

**Issue by datavisorfrankhe** [microsoft/monaco-editor#1527]
Hello,
May I ask if monaco can automatically check the syntax error?
For example, I am using it to provide sql support, and if I typed in

wrong_select * form field

I want the wrong_select to be indicated as wrong. and if I mouse hovering, suggestion for fix will appear.

Can this feature be supported? and I believe it is there already, just can not find it.

Thanks for your help.

**Comment by rcjsuen** [comment]
@datavisorfrankhe Maybe #1477 will help you.

**Comment by datavisorfrankhe** [comment]
I checked 147, and I don't think the syntax error is automatically detected. when calling setModelMarkers, the data passed in contains the error display position and contents.

Does this mean the syntax error can not be detected automatically by Monaco?

**Comment by rcjsuen** [comment]
@datavisorfrankhe Monaco is simply an editor. It is not an AST parser or syntax error checker. If you want to check for errors, you need to:

1. Listen to changes in the backing model (the textual content of the editor).
1. Identify relevant errors in the text.
1. Notify Monaco about such errors so it can render them to the user. #1477 showed how to do this with hard-coded values but it is possible to do this dynamically.

**Comment by datavisorfrankhe** [comment]
Thanks for your clarification, now I know how to do this.
