### ISSUE TITLE
Editor displaying Â on carriage return

### ISSUE THREAD

**Issue by MonstaApps** [microsoft/monaco-editor#1535]
**monaco-editor version:** 0.14.6
**Browser:** Firefox
**OS:** Windows 10

When you press enter you get the Â character display on the new line. When you start typing, the character disappears.

My html page already had this code: 
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`

but I added this as well:
`<meta charset="UTF-8">`

Still the problem persists. The issue is unique to the server I'm on because on other servers I don't have this problem at all.

**Comment by alexandrudima** [comment]
@MonstaApps Could you provide some standalone HTML which reproduces the problem? I am unable to reproduce.

**Comment by alexandrudima** [comment]
Possibly related -- #1608

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
