### ISSUE TITLE
Backspace doesn't work in Android browser

### ISSUE THREAD

**Issue by freeqaz** [microsoft/monaco-editor#1538]
**monaco-editor version:** 0.17.1
**Browser:** Chrome on Android, also Brave on Android
**OS:** Android 9.0, Pixel 2 XL

**Steps or JS usage snippet reproducing the issue:**
1. Open the (Monaco Playground)[https://microsoft.github.io/monaco-editor/playground.html] on your Android device
2. Select some text in the editor
3. Press backspace on virtual keyboard

I don't see it deleting. My friend also confirmed this issue. There were some older issues around this, it seems like. So probably just not the right keyboard event being listened to?

Thank you!

**Comment by rcjsuen** [comment]
@freeqaz Monaco is not expected to work on mobile platforms. See #246, #1365, #1504, and I'm sure there are many more out there.

**Comment by freeqaz** [comment]
Ah, gotcha. We love Monaco overall -- it's a great editor! I'll think about if there are any ways to fix this on our end (swapping out for something else on mobile).

What are your thoughts on what is preventing the mobile keyboard from working? What are a high level list of steps one could do to go hack this support in?

Thanks, @rcjsuen

**Comment by rcjsuen** [comment]
@freeqaz Unfortunately, I am not a developer on the Monaco project. I do not speak for or work for Microsoft. I was just pointing you to other issues opened by other people in the past.

**Comment by orta** [comment]
These issues are well described in https://github.com/microsoft/monaco-editor/issues/562 and https://github.com/microsoft/monaco-editor/issues/563 (which has a workaround for old copies of monaco)
