### ISSUE TITLE
Description for all shortcuts menu in monaco editor is not defined

### ISSUE THREAD

**Issue by sumkumsum** [microsoft/monaco-editor#1539]
In Monaco Editor we have command palette (launched on click of F1 on Monaco-Editor) Monaco 

Editor Version: 0.15.6
Browser : Chrome/Firefox ESR
OS: Windows

We have multiple shortcuts menu, but there is no detail mentioned like what they do, how they behave and benefits? No Documents for following shortcuts and their functionality.

Actions like :

1) Developer: Inspect Tokens --> It opens a window but then it can't be closed 
2) Trigger Symbol Highlight 
3) Shrink Select 
4) Expand Select 
5) Format Selection --> doesn't do anything 
6) Format Document --> doesn't do anything 
7) Unfold All Regions 
8) Fold All Regions 
9) Move Caret Left 
10) Move Caret Right 
11) Copy with Syntax Highlighting 
12) Find with Selection 
13) Find Next Selection 
14) Find Previous Selection 
15) Go to Previous Problem (Error) 
16) Go to Previous Problem in Files (Error) 
17) Go to Next Problem (Error)

I have tried after 
1) Integrating it with angular project and 
2) on Monaco editor playground 
but issue is , some doesn't do anything(Format), some does something which we cant differentiate (Move Caret Left/Right), Some has issues (Developer: Inspect Tokens)

Details of these shortcut menu should be provided, so if end user uses it then we can explain the functionality.

**Comment by sumkumsum** [comment]
@alexandrudima ...could you please comment on this

**Comment by alexdima** [comment]
@sumkumsum There does not exist any detailed documentation that explains each action and what it does. You can consult the codebase and VS Code to try them out. Possible helpful links:

- https://code.visualstudio.com/docs (general documentation for VS Code, which refers to a number of the actions)
- https://code.visualstudio.com/updates/ (monthly release notes where we often document new added actions)
- https://github.com/microsoft/vscode (the actual source where you can search for by action name)
