### ISSUE TITLE
No api for old version monaco, Can you add the api for old version?

### ISSUE THREAD

**Issue by pinksky** [microsoft/monaco-editor#1545]
We had used many verisons of monaco in different systems we maintained, such as V0.9.0, V0.12.0, V0.14.3, V0.15.6. We are faced with some difficulties, and need the api doc. However,
**we can't find the old version api.** 

There is only the newest version api for 0.17.1 on the official website : https://microsoft.github.io/monaco-editor/. 

And we found that there are many break upgrades for monaco, so it's not convenient for us to upgrade the monaco...
And we think it's not friendly at all...

So can you add the api for old version monaco? or where can we users find the api doc for old version, and how can we maintain the old version monaco editor...

**Comment by alexandrudima** [comment]
The API doc is completely generated from `monaco.d.ts`. That file is available in the `.tar.gz` from npm.
