### ISSUE TITLE
are typings correct to expect null at so many places

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#1550]
New APIs return null in many places. Are typings correct? Could it really be that `getPosition` or `getSelection`, `getModel` or `saveViewState` return `null`?

cc @alexandrudima @rebornix

**Comment by alexandrudima** [comment]
Yes, that is possible when calling `editor.setModel(null)`... i.e. it is possible to have an editor without a model. Such an editor does not have a view, nor a cursor.
