### ISSUE TITLE
Code in hover provider value md code block is not syntax-highlighted on first hover

### ISSUE THREAD

**Issue by postatum** [microsoft/monaco-editor#1555]
**monaco-editor version:** 0.17.1
**Browser:** Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
**OS:** Linux Mint 18.3 Cinnamon 64-bit
Users on other browsers and OSs reported this issue as well.

**Steps or JS usage snippet reproducing the issue:**
Try running this code snippet in [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example):
```js
const editorLanguage = 'xml';
const tooltipLanguage = 'json';

monaco.languages.registerHoverProvider(editorLanguage, {
  provideHover: function (model, position) {
    return {
      contents: [
        { value: '```' + tooltipLanguage + '\n{"foo":"bar"}\n```' }
      ]
    }
  }
});

monaco.editor.create(document.getElementById("container"), {
  value: 'anything',
  language: editorLanguage
});
```

**Issue:**:
When editor language (`const editorLanguage`) and markdown code block language in a value returned by hover provider (`const tooltipLanguage`) differ, the code in the markdown code block is only syntax-highlighted starting with *second* hover.

In this particular example, on first hover, the code in a tooltip has no syntax highlighting. On second and consecutive hovers, the code in a tooltip is properly highlighted.

Also when `editorLanguage` and `tooltipLanguage` have the same value, the code in a tooltip is highlighted properly on first hover.

I've been able to reproduce this issue both in Monaco Playground and locally using version 0.17.1.

**Comment by rcjsuen** [comment]
This sounds very familiar but I can't find the other bug...

**Comment by rcjsuen** [comment]
@postatum Found it. See #812.

**Comment by postatum** [comment]
@rcjsuen got it, thanks.
