### ISSUE TITLE
cannot close reference peek with esc without focusing an editor

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#1557]
It seems that the reference peek widget handles esc key before the keybinding service.

**Comment by akosyakov** [comment]
Ii still cannot get why it works VS Code, but not in Monaco. In both cases bubbling event handler is installed. The only difference that in VS Code on window, in Monaco on the standalone editor node. But it should not be matter since the target element belongs to the editor node and should respond first. In Monaco it happens, so esc does not close the reference peek, but in VS Code it does not hit.

@alexandrudima maybe you can give a hint how to fix? Would it be alright to install capturing event handler for Monaco or it will break some overlay widgets?

**Comment by akosyakov** [comment]
`editor.stablePeek` should be set to `false`

**Comment by akosyakov** [comment]
It is repoducible on the playground with 0.18.0.

**Comment by alexdima** [comment]
@akosyakov I am sorry I am not 100% of the precise steps. I have opened find all references and tried the following:
- focused the outer editor and pressed Escape => the embedded editor closed
- focused the embedded editor and pressed Escape => the embedded editor closed

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
