### ISSUE TITLE
Follow the library refrence tree when wokring with languages?

### ISSUE THREAD

**Issue by aloksharma1** [microsoft/monaco-editor#1558]
[Suggestion for Intellisense Enhancement]
Hi Team,
right now we are using codemirror & ace-editor for our online editing uses. recently i came to know about this great editor and i am very happy with the capabilities your tool have. we are working on a online language editor and runner and i was going through moncao editor demo and documentation but i am unable to find some procedural call or functionality that will enable to editor to understand the library language tree to not repeat same stuff over and over after dot (.) operator.
for e.g. if i am using c# :
`
using System.`

should pull what comes after the system instead of showing complete list including system, i suggest if you can make a language definition file either in json or js or xml whatever you see fits to match with the language package/library tree as refrence it would be a great help.
if this can be exposed as a plugin file , where we as users can contribute and add our own will be added advantage.

i am going through docs for references on how to build plugins but so far its a bumpy ride to find any decent tutorial. ;)

regards

**Comment by rcjsuen** [comment]
You may want to take a look at the [TypeFox/monaco-languageclient](https://github.com/TypeFox/monaco-languageclient/
) project.
