### ISSUE TITLE
Korean IME does not work in Firefox

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/monaco-editor#156]
file:///C:/Alex/src/vscode/src/vs/editor/test/browser/controller/imeTester.html

![image](https://cloud.githubusercontent.com/assets/5047891/17921327/a137509c-69d9-11e6-9fdd-9154804e7dbf.png)

**Comment by rebornix** [comment]
@alexandrudima I'm trying to verify all IME related bugs and seeing this one marked as `August` but still open, will you fix this for this sprint?

**Comment by alexandrudima** [comment]
I will try fixing it today, if there is enough time, otherwise I may postpone it (as I don't think it ever worked).

**Comment by alexandrudima** [comment]
This is because Firefox emits a composition end after `gk` even though typing `sr` still composes the first glyph. I am certain this never worked and would need to be handled especially from all other inputs.

**Comment by rebornix** [comment]
I tested Firefox 52 and now it works well. If we set any conditional breakpoint then it will break the composition state but if there is no breakpoint at all, it looks good.

**Comment by alexandrudima** [comment]
Closing per @rebornix last comment
