### ISSUE TITLE
How to get current model indent?

### ISSUE THREAD

**Issue by purocean** [microsoft/monaco-editor#1565]
**monaco-editor version:** 0.17.1
**Browser:** Chrome
**OS:**  Window 10

**Steps or JS usage snippet reproducing the issue:**

I used to use [`getOneIndent` line 2268](https://unpkg.com/monaco-editor@0.8.3/monaco.d.ts). But now it's removed. What API instead it?

**Comment by spahnke** [comment]
Does this help https://microsoft.github.io/monaco-editor/api/classes/monaco.editor.textmodelresolvedoptions.html? You can get these by calling `editor.getModel().getOptions()`

**Comment by purocean** [comment]
@spahnke Thank you. I'll implement it by myself.

```ts
	public getOneIndent(): string {
		this._assertNotDisposed();
		let tabSize = this._options.tabSize;
		let insertSpaces = this._options.insertSpaces;

		if (insertSpaces) {
			let result = '';
			for (let i = 0; i < tabSize; i++) {
				result += ' ';
			}
			return result;
		} else {
			return '\t';
		}
	}
```

https://github.com/microsoft/vscode/blob/24f62626b222e9a8313213fb64b10d741a326288/src/vs/editor/common/model/textModel.ts#L663
