### ISSUE TITLE
Filed test with monaco-editor (Unexpected token {)

### ISSUE THREAD

**Issue by perryutkonos** [microsoft/monaco-editor#1566]
**monaco-editor version:** 0.17.1
**Browser:** Google Chrome 76
**OS:** MacOS 10.14

this code in file monaco-editor/esm/vs/editor/editor.api.js filed in test 
`import { EDITOR_DEFAULTS } from './common/config/editorOptions.js';`
because babel don't compile node_modules.
Why do you use ESM in module? It's incorrect

**Comment by goharanwar** [comment]
@perryutkonos Were you able to figure out the way round to fix this at your end or are your tests still failing?

**Comment by alexdima** [comment]
@perryutkonos the folder `/esm/` contains files which use EcmaScript Modules. That is the reason that folder exists in our folder. The folder `/dev/` or `/min/` contain files which are in ES5.
