### ISSUE TITLE
getProxy() execution is too slow，lasting about 4s

### ISSUE THREAD

**Issue by Moon-R** [microsoft/monaco-editor#1569]
![image](https://user-images.githubusercontent.com/26536371/63928080-8dcb1780-ca81-11e9-8948-3eb1608959e1.png)

![image](https://user-images.githubusercontent.com/26536371/63928185-bc48f280-ca81-11e9-94cd-8382904dbda4.png)

hello，I add a custom language worker，but find the return object of monaco.editor.createWebWorker() has a method call getProxy executing lasting about 4s for the first time which means I have to wait about 4s before I could see the suggested complete Items in editor. Is there any way to speed it up or avoid it?

**Comment by alexandrudima** [comment]
That is the time it takes to create a web worker (which will make HTTP requests) and until the web worker is loaded... So that time depends on the network conditions.
