### ISSUE TITLE
 functional requirement

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#1570]
I want to refer to an object or a class. When instantiated, input assistance can prompt his attributes. What should we do?

**Comment by alexandrudima** [comment]
@y912765390 I'm sorry, I don't understand what you mean exactly. Could you please be more specific?

**Comment by y912765390** [comment]
I'm sorry, my English is not very good.Let me give you an example.
//a.js
  export default {
     name:"ming",
     age:18
}
// b.js
 import people from "./a.js"
///////////
I hope when we input "people." Input assistance can prompt "name" "age"
How to do  it?  Thank you wery much 
I am looking forward to your reply

**Comment by alexdima** [comment]
Please see https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults for a way to add `.d.ts` files.
