### ISSUE TITLE
Schemas containing circular references cannot be used

### ISSUE THREAD

**Issue by pimterry** [microsoft/monaco-editor#1571]
**monaco-editor version:** 0.17.1
**Browser:** Chrome
**OS:** Linux

Any schemas that contain circular references don't work, due to a use of `JSON.stringify` when sending this data to the workers (see `SimpleWorkerProtocol._send`). Circular references are pretty common in substantial JSON schemas so this is causing me some problems.

Although I can't easily test it, it seems this is already fixed in the VSC source: https://github.com/microsoft/vscode/commit/2eb1b4d9a86787a39e47693de25533f221e12894. That removes the JSON.stringify to pass data through pushMessage directly, which can handle this by itself no problem.

Does that sound accurate? If so, would it be possible to do an updated release sometime soon? It's been a couple of months since that last one, and it would be really useful to get changes like this released (assuming this does actually fix the problem).

**Comment by aeschli** [comment]
> Circular references are pretty common in substantial JSON schemas so this is causing me some problems.

I assume you are passing a schema with `monaco.languages.json.DiagnosticsOptions`. 
The schema you pass in there must not contain any circular references, but must look like a schema one defines in a JSON file (using '$ref' for references). 

The circular references only appear once a schema is resolved, that's when the schema service follows the `$ref` properties.

**Comment by aeschli** [comment]
The circular references are not just a serialization issue but also something our schema service doesn't expect. It expects 'unresolved' schema, which is the JSON of JSON document as specified by the [JSON schema spec](https://json-schema.org/draft/2019-09/json-schema-core.html).
