### ISSUE TITLE
Scrolling does not work in IE 11

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#1573]
**monaco-editor version:** 0.18.0
**Browser:** IE 11
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
Reproducible on the [Monaco Website](https://microsoft.github.io/monaco-editor/) and in the playground.

It works with the keyboard (Ctrl+Up/Down), but not with the scroll wheel.

**Comment by ulrichb** [comment]
Related: In Firefox it works now, but scrolling is very "slow" (in comparison to Chrome).

**Comment by brijeshb42** [comment]
For the same amount of scroll (or wheel), firefox is firing the event very infrequently and with very low `deltaY` compared to chrome.

**Comment by ulrichb** [comment]
=> #1575

**Comment by alexandrudima** [comment]
Duplicate of #1575
