### ISSUE TITLE
Scrolling slow on Ubuntu 16.04 + Firefox 68.0.2

### ISSUE THREAD

**Issue by marechal-p** [microsoft/monaco-editor#1575]
**monaco-editor version:** 0.17.0/0.18.0?
**OS:** Ubuntu 16.04

On Firefox (68.0.2) the mouse scroll is really slow (maybe 10 times slower?)

I tried capturing a gif, but I cannot scroll fast enough for it to show on the capture.

Chrome (76.0.3809.132) is not affected.

Tested on the playground as well: https://microsoft.github.io/monaco-editor/playground.html

**Comment by joechung-msft** [comment]
It seems to be scrolling by pixel instead of by line of text.
