### ISSUE TITLE
Can we get the type of variable written in the script editor?

### ISSUE THREAD

**Issue by Kang-Jun-sik** [microsoft/monaco-editor#1578]
**monaco-editor version:** 0.18.0
**Browser:** : Chrome
**OS:** : Windows

**Steps or JS usage snippet reproducing the issue:**
Hi team. Always appreciate for your help.
I should know the type of written word or variable in script editor.
In the monaco Editor, I can know the type using mouse hover Event.

![Q1](https://user-images.githubusercontent.com/20898356/64497474-64b04f80-d2e9-11e9-8519-d040b6de977b.png)

For Example Above picture, I will Get **_local_**(Type) from **_aaa_** (Variable) 
through hovering the mouse specific word.
but Can i get the type of word or variable written in monaco-editor??(not using mouse hover)

I want to know some API or Access Way.

Thx

**Comment by jrieken** [comment]
That information is provided by the typescript smarts (via the HoverProvider API). We cannot expose that information and you would need to use the typescript smarts yourself.
