### ISSUE TITLE
Electron nodeIntegrationInWorker lead diffEditor doesn't work(color)

### ISSUE THREAD

**Issue by Bear1110** [microsoft/monaco-editor#1579]
**monaco-editor version: 0.18.0
**Browser: Electron 4.2.10
**OS:* windows 10

When I set 
```new BrowserWindow({webPreferences: { nodeIntegrationInWorker: true  } })```
 The diff editor show like this
![image](https://user-images.githubusercontent.com/14165451/64597842-2ef29000-d3e9-11e9-8db6-7bca3712c0e5.png)

The adding or removing color are disappear.

This is the picture when I set
```new BrowserWindow({webPreferences: { nodeIntegrationInWorker: false  } })```
![image](https://user-images.githubusercontent.com/14165451/64597899-4cbff500-d3e9-11e9-9563-210f2d39120b.png)

I find a related  issue is #1076 .

Is any way to resolve this?

Thanks.

I include editor in electron like this way 

https://github.com/microsoft/monaco-editor-samples/blob/master/electron-amd/electron-index.html
```
const amdLoader = require('./node_modules/monaco-editor/min/vs/loader.js')
const amdRequire = amdLoader.require
const amdDefine = amdLoader.require.define
function uriFromPath(_path) {
    var pathName = path.resolve(_path).replace(/\\/g, '/')
    if (pathName.length > 0 && pathName.charAt(0) !== '/') {
        pathName = '/' + pathName
    }
    return encodeURI('file://' + pathName)
}
amdRequire.config({
    baseUrl: uriFromPath(path.join(__dirname, './node_modules/monaco-editor/min'))
})
amdRequire(['vs/editor/editor.main'], function() {
    monaco.editor.setTheme('vs-dark')
})
self.module = undefined
```

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
