### ISSUE TITLE
Focus issue after closing inline errors via keyboard

### ISSUE THREAD

**Issue by orta** [microsoft/monaco-editor#1580]
**monaco-editor version:** 0.18.0
**Browser:** N/A
**OS:** N/A

**Steps or JS usage snippet reproducing the issue:**

1) Hit the URL "https://microsoft.github.io/monaco-editor/index.html"​​
3) Type any wrong code. ​
4) Press F8 or Shift+F8 to open the errors​
5) Press Shift+Tab key to go to close button of the error tooltip. When focus comes to close button press enter key. 
5) Focus should go back to the editor

**Comment by sandy081** [comment]
Tracked here - https://github.com/microsoft/vscode/issues/83979
