### ISSUE TITLE
How to extend built-in language

### ISSUE THREAD

**Issue by MBarnech** [microsoft/monaco-editor#1581]
**monaco-editor version: 0.17.0**
**Browser: Chrome**
**OS: Windows 10** 

Hello! 
I'm building a special css language where there are properties values in this format: $name.value. This is the only one difference between css and my language so i think the best option is to extend the existing definition.
Normal css doesn't support this and i'm getting an error with te language in monaco editor.

How can i do that? Is it possible?

**Comment by alexandrudima** [comment]
@MaxiBarnech 
- you can fork https://github.com/Microsoft/vscode-css-languageservice and add your custom CSS syntax to the parser, etc.
- then you can fork https://github.com/Microsoft/monaco-css and change it to use your forked `vscode-css-languageservice` module
- finally, you can fork this repository and change it to use your forked `monaco-css` module
