### ISSUE TITLE
Add internal link support in markdown rendering

### ISSUE THREAD

**Issue by BennyHinrichs** [microsoft/monaco-editor#1583]
Monaco@0.18.0
Chrome@76.0
Ubuntu@18.04.3

In the picture below, I would love if you could click `[[Forms]]` and `[[Record]]` and the docs for them would populate into the widget. Is there already a way to do that?

![monacoHover](https://user-images.githubusercontent.com/35133653/64813864-93cff680-d55f-11e9-9830-2218088ea808.png)

**Comment by alexandrudima** [comment]
@BennyHinrichs The hover is computed by a language service, so if the language service would know how to interpret that comment, then IMHO the rendering would not be a problem. 

If that a screenshot of TypeScript, then maybe you can open a feature request directly against TypeScript at https://github.com/microsoft/typescript
