### ISSUE TITLE
How can I hide the "any" tag?

### ISSUE THREAD

**Issue by iamaddy** [microsoft/monaco-editor#1584]
```
monaco.languages.registerHoverProvider('javascript', {
        provideHover: function (model, position) {
            var detail = findAIP(wordInfo.word, words[words.length - 1]);
            if(detail){
                return {
                    contents: [
                        { value: '**SOURCE**' },
                        { value: detail }
                    ]
                };
            }
        }
    });
```
![image](https://user-images.githubusercontent.com/3387191/65020210-4ee10100-d95f-11e9-8e2c-53e58ae4823b.png)

**Comment by alexandrudima** [comment]
The `any` comes from the `monaco-typescript` hover (https://github.com/Microsoft/monaco-typescript). There is no option to disable the hover contributed by it. You could fork `monaco-typescript` and package a custom version of it with your application.
