### ISSUE TITLE
ViewZone area's last line reports the next line number in the MouseDown event

### ISSUE THREAD

**Issue by code2be** [microsoft/monaco-editor#1585]
**monaco-editor version:** 0.18.0
**Browser:** Google Chrome 76.0.3809.132 64bit
**OS:** Ubuntu 18.04.3

**Steps or JS usage snippet reproducing the issue:**
1. Initialize a Monaco editor instance.
2. Add a ViewZone using `changeAccessor.addZone()`
3. Set a `editor.onMouseDown()`.
4. Try making `console.log()` for the `e.target.position.lineNumber` while clicking on the last line inside the ViewZone area.
5. You'll get the number of the next line, not the one having the ViewZone.

**Comment by alexdima** [comment]
The mouse position returns the line above the view zone when the mouse is in the first half of the view zone and the line below the view zone when the mouse is in the second half of the view zone.
