### ISSUE TITLE
filteredTypes disable interfaces does not work

### ISSUE THREAD

**Issue by crazyfx1** [microsoft/monaco-editor#1586]
**monaco-editor version:** 0.18.0
**Browser:** Chrome
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
The new feature filteredTypes does not work with interfaces.
Using the Monaco playground:
https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world

Use this testcode:
```JavaScript
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	suggest: { filteredTypes: { interface: false } },
	language: "javascript"
});
```

Open the suggestions in the editor and the interfaces are still visible.
![image](https://user-images.githubusercontent.com/9930385/65039213-02db8f80-d952-11e9-9c08-dbe87d8ef726.png)

**Comment by spahnke** [comment]
My guess here is that's because those aren't only interfaces. If you look into `lib.dom.d.ts` you'll find two definitions of e.g. `AbortController`. One is an interface the other one is a variable declaration:
```ts
/** A controller object that allows you to abort one or more DOM requests as and when desired. */
interface AbortController {
    /**
     * Returns the AbortSignal object associated with this object.
     */
    readonly signal: AbortSignal;
    /**
     * Invoking this method will set this object's AbortSignal's aborted flag and signal to any observers that the associated activity is to be aborted.
     */
    abort(): void;
}

declare var AbortController: {
    prototype: AbortController;
    new(): AbortController;
};
```

If you test with the following code, the interface `Test` is not shown in the suggestion list:
```js
monaco.editor.create(document.getElementById("container"), {
	value: "interface Test {}\n\nfunction hello() {\n\talert('Hello world!');\n}",
	suggest: { filteredTypes: { interface: false } },
	language: "typescript"
});
```

However, I don't know if there is another filter you could apply to hide those members.

**Comment by spahnke** [comment]
You can see all suggestion items and their corresponding icons by adopting https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example and replacing `createDependencyProposals` like this:

```js
function createDependencyProposals() {
    // returning a static list of proposals, not even looking at the prefix (filtering is done by the Monaco editor),
    // here you could do a server side lookup
    return Object.keys(monaco.languages.CompletionItemKind).filter(kind => Number.isNaN(Number(kind))).map(kind => {
        return {
            label: kind,
            kind: monaco.languages.CompletionItemKind[kind]
        }
    });
}
```

**Comment by crazyfx1** [comment]
You are right, the suggestions show the global vars and not the interface. I saw it by mistake because it correctly shows "interface" as type of the variable.
