### ISSUE TITLE
WordWrap option does not work properly on the css mode.

### ISSUE THREAD

**Issue by ChangUk** [microsoft/monaco-editor#1587]
**monaco-editor version:** 0.18.0
**Browser:** Chrome 77
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**

The horizontal scrollbar is visible even when the 'wordWrap' option is set to 'on'.
This bug can be easily verified on the playground.

**Comment by alexandrudima** [comment]
@ChangUk Can you please include a screenshot?

**Comment by ChangUk** [comment]
![](https://user-images.githubusercontent.com/4004891/65160296-6a87fc80-da70-11e9-9d54-7510e5814d50.gif)

**Comment by alexandrudima** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/32856
