### ISSUE TITLE
The new "Rename" refactoring destroys the undo stack

### ISSUE THREAD

**Issue by ulrichb** [microsoft/monaco-editor#1591]
**monaco-editor version:** 0.18.1
**Browser:** Chrome
**OS:** Win 10

**Steps or JS usage snippet reproducing the issue:**
* Use the following sample (in the playground)
```TS
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');}\n\nhello()\n",
	language: "typescript"
});
```
* Go to the `hello` symbol; hit F2 (#300) and change the name

=> **Expected:** `Crtl + Z` works (and undos the change)

=> **Actual:** `Crtl + Z` does nothing

Note: At the moment the rename feature only works in the _current_ model, so IMO there is no reason to destroy the undo stack.

**Comment by spahnke** [comment]
I think this is a duplicate of #1548

**Comment by ulrichb** [comment]
Ah thanks. => Closing.

**Comment by spahnke** [comment]
I edited the other issue to clarify that maybe edit operations of language providers are affected in general.

**Comment by ulrichb** [comment]
Cool. Thanks!
