### ISSUE TITLE
Using monaco editor in production?

### ISSUE THREAD

**Issue by clement911** [microsoft/monaco-editor#1592]
We'd love to start using Monaco in our app to provide a SQL editor with colorization, formatting, auto-completion, etc...
But we're a bit worried that the current version is 0.18.1

Does this mean that it's not quite ready to use in production?
Are there expected major API changes?

**Comment by rebornix** [comment]
@clement911 Monaco Editor is being used in VS Code, Azure portal, VSTS and quite a bunch of third party applications so IMO it's ready for production use. However, there might be some breaking API change but we will always document them in our release [changelog](https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md)

**Comment by clement911** [comment]
Good to hear, thanks!
