### ISSUE TITLE
how to overwrite the monaco native  triggerCharacters ?

### ISSUE THREAD

**Issue by xiaoxiao426** [microsoft/monaco-editor#1593]
**monaco-editor version:** 0.10.1
**Browser:** 76.0.3809.100（正式版本） （64 位）
**OS:**  windows 7 64位

**Steps or JS usage snippet reproducing the issue:**
I use the interface of "provideCompletionItems", and set triggerCharacters=["a", "b"]. under these circumstances， when i input "a", the event of provideCompletion was triggered twice. I analyse the reason is that: the native triggerCharacters contains "a",my own triggerCharacters also contains "a". that leads twice trigger. I want to overwrite the native triggerCharacters，so the provideCompletionItems only triggered by my customized characters.

**Comment by alexdima** [comment]
@xiaoxiao426 I am sorry I do not understand the problem. Can you provide a reproducible sample that runs at https://microsoft.github.io/monaco-editor/playground.html and which demonstrates the issue?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
