### ISSUE TITLE
Edits from a CodeAction can be applied although the editor is readonly

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#1596]
**monaco-editor version:** 0.17.1-0.18.1
**Browser:** Chrome/Firefox/Edge Dev
**OS:** Windows 10

If you register a `CodeActionProvider` that applies an edit operation, the quickfix can be applied if the editor is readonly.

1. Run the code below in the [playground](https://microsoft.github.io/monaco-editor/playground.html)
2. Place the cursor inside the string
3. Apply the provided code action through the lightbulb icon

The edit is applied. This only happens if the editor is set readonly by updating the editor options
```js
editor.updateOptions({ readOnly: true });
```
If you set the editor readonly in the `create` API call the lightbulb is not shown and the edit cannot be applied. I expect the same thing to happen when using the `updateOptions` API.

Also notice that the shortcut associated with the lightbulb (Ctrl+.) does not trigger any quickfixes in both scenarios. So it seems to be only the lightbulb feature itself.

**Playground:**
```js
const markerRange = new monaco.Range(2, 8, 2, 22);

monaco.languages.registerCodeActionProvider("javascript", {
    provideCodeActions(model, range, context, token) {
        /** @type {monaco.languages.CodeAction[]} */
        const codeActions = [];
        for (const marker of context.markers) {
            /** @type {monaco.languages.TextEdit} */
            const fix = {
                range: markerRange,
                text: '"Hello world!"'
            };
            codeActions.push({
                title: `Fix: ${marker.message}`,
                diagnostics: [marker],
                edit: {
                    edits: [{
                        edits: [fix],
                        resource: model.uri,
                    }],
                },
                kind: "quickfix" // not sure if necessary / what value should be used
            });
        }
        return { actions: codeActions, dispose() {} };
    }
});

const editor = monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript",
    lightbulb: { enabled: true },
    // readOnly: true,
});

editor.updateOptions({ readOnly: true });

monaco.editor.setModelMarkers(editor.getModel(), "ESLint", [{
    message: "Strings must use doublequote.",
    startLineNumber: markerRange.startLineNumber,
    startColumn: markerRange.startColumn,
    endLineNumber: markerRange.endLineNumber,
    endColumn: markerRange.endColumn,
    source: "ESLint",
    severity: monaco.MarkerSeverity.Warning
}]);
```

**Comment by jrieken** [comment]
Yeah, that's the current design and there are no plans to change that. "Readonly" currently means that the editor doesn't show a cursor, but there is no readonly notion on the text document.

**Comment by spahnke** [comment]
>but there is no readonly notion on the text document

I'm fine with that part, which, if I understand correctly, means that any edits are just applied? But what is the difference between `readOnly: true` in the creation options of the editor and using `editor.updateOptions({ readOnly: true })` after creating the editor?

In the first case no lightbulb is shown and I can't apply the edits in the first place; in the second case a lightbulb is shown. This is the essence of the issue.

**Comment by spahnke** [comment]
@jrieken Friendly ping because I don't know if you unsubscribe from these as you do with VS Code issues. Sorry if this causes additional noise 🙇
