### ISSUE TITLE
Weird behavior only when typing <span in HTML 

### ISSUE THREAD

**Issue by YipYipX4** [Microsoft/monaco-editor#16]
Steps to reproduce, using Chrome Version 50.0.2661.102 m (64-bit):
1. Go to https://microsoft.github.io/monaco-editor/index.html
2. Change language to HTML.
3. Click at the end of <body> and press Enter.
4. Type "<span" and notice how it suddenly becomes "span    <" (before even pressing space). If I backspace, it goes back to "<spa".  If I type "<spandex", it will show as "spandex     <".  After pressing space or ">", the cursor jumps past the "<", but the problem remains.  Similar behavior occurs when trying to type the closing tag "</span>", so trying to type "<span></span>" becomes "span    span    <> </>".

I was also able to reproduce this in IE11.  

I am not able to reproduce this with _any_ other tag.  Typing "<div" or "<spin" or anything that doesn't start with "<span" does not cause the problematic behavior.

**Comment by nikikante** [comment]
![zajeta slika](https://cloud.githubusercontent.com/assets/20074193/16248066/38a3731a-380d-11e6-927a-2bce7314561c.PNG)
editor brokes in firefox.

**Comment by alexandrudima** [comment]
Nice find! This is a conflict with bootstrap that contains this rule:
```css
[class*="span"] {
    float: left;
    min-height: 1px;
    margin-left: 30px;
}
```

and the html tokenizer generates the following class name:
```html
<span class="token entity name tag tag-span">span</span>
```
