### ISSUE TITLE
Missing default range for hovers

### ISSUE THREAD

**Issue by jrieken** [Microsoft/monaco-editor#160]
When a hover provider fails to provide a range we ignore its result. In VS Code we will in a default (word range or the position) and should do the same for Monaco

**Comment by sandyarmstrong** [comment]
In VS Code, there is a `HoverAdapter` that fills in missing ranges: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L208

It seems that in Monaco, there is no such adapter (?), so the range is missing and the result is ignored: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/hover/common/hover.ts#L29

You can reproduce by going to https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example and deleting the `range` in line 12.
