### ISSUE TITLE
Editor inserts a `.` after pressing space twice

### ISSUE THREAD

**Issue by svenefftinge** [microsoft/monaco-editor#1600]
**monaco-editor version:** https://microsoft.github.io/monaco-editor/playground.html
**Browser:** chrome
**OS:** os x

**Steps or JS usage snippet reproducing the issue:**
- Open https://microsoft.github.io/monaco-editor/playground.html
- go to the last line type a `|` (heppens with other characters as well)
- press space twice and see the following:

```
| . 
```

**Comment by orta** [comment]
Can confirm this is an OS X feature: the same thing happens in this text input
`|. `
