### ISSUE TITLE
Is there any way to switch to one-line mode?

### ISSUE THREAD

**Issue by JamesChenX** [microsoft/monaco-editor#1601]
monaco-editor version: 0.18.1
Monaco editor is powerful but I want to use it in one-line mode(no multiline).
And I didn't find any relevant options for it.
So, did I miss something?

**Comment by alexandrudima** [comment]
Such a mode is not built-in, but you can build it yourself... It is possible that you size the editor in such a way that it has precisely the height of one line, and that you hide the scrollbars, and that you override <kbd>Enter</kbd> to not insert `\n`, and that you listen on content changes and strip `\n` if they are introduced via pasting, etc...

**Comment by mx2323** [comment]
Would there be a way to still show the autocomplete drop down even if it is one line?

**Comment by alexdima** [comment]
Yes, there would be no problem and autocomplete would continue to work.
