### ISSUE TITLE
playground, symbols provider example: does not typecheck

### ISSUE THREAD

**Issue by larshp** [microsoft/monaco-editor#1602]
Hi,
The example https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-symbols-provider-example does not typecheck in typescript,

The `DocumentSymbolProvider` returns an array of `DocumentSymbol`, for which `detail`, `tags`, and `selectionRange` are mandatory, see https://github.com/microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L912

Related commit: https://github.com/microsoft/monaco-editor/commit/02fb6bfd43b5ddcff36c1a1303e4aac623deff2e

I guess the example should be updated? Alternatively, change the type definition?

**Comment by alexandrudima** [comment]
Yes, the example should be updated...
