### ISSUE TITLE
Plans to add registerDiagnosticsProvider?

### ISSUE THREAD

**Issue by larshp** [microsoft/monaco-editor#1604]
Hi,
There are multiple register* methods to support language features, https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html

However it seems that the registerDiagnosticsProvider/registerMarkerProvider is missing? Any plans to implement it or is there a story behind it?

Looking at the json and typescript examples, it calls register* everything, but the diagnostics/markers follows a different pattern,
https://github.com/microsoft/monaco-json/blob/58c8efef502b431a567dd051d5bc5981203c9a54/src/jsonMode.ts#L59
https://github.com/microsoft/monaco-typescript/blob/7d4d30f874d81a7d43ff5a3b538bfa7588e63342/src/tsMode.ts#L68

**Comment by alexandrudima** [comment]
That is because diagnostics are "pushed" from language servers, not "pulled"

**Comment by larshp** [comment]
okay, thanks, closing
