### ISSUE TITLE
Code highlighting is off

### ISSUE THREAD

**Issue by ahqardah** [microsoft/monaco-editor#1605]
When I try to highlight some code I pass the start line number, column, end line number and column, (verified that they are correct). it highlights another section of the code. Here is what I am doing
Chrome OS, Windows

```

private _setSelection(selectionRange: TextRange) {
        if (this._editor) {
            const range: monaco.IRange = {
                endColumn: selectionRange.end.character,
                endLineNumber: selectionRange.end.line,
                startColumn: selectionRange.start.character,
                startLineNumber: selectionRange.start.line,
            };
            this._editor.setSelection(range);

            this._editor.focus();
        }
      }

```

**Comment by rcjsuen** [comment]
@ahqardah Can you reproduce this with some code by running it in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html)?

**Comment by ahqardah** [comment]
Fixed the issue, it was related to monaco being 0 index based.
