### ISSUE TITLE
Line break show 'A' caracter

### ISSUE THREAD

**Issue by telnetserbia** [microsoft/monaco-editor#1608]
**monaco-editor version:** 0.18.1
**Browser:** Chrome 72
**OS:** Ubuntu 16.04

Hello, I am using the Monaco editor for angular 2+ version ('ngx-monaco'), and in the development mode the editor is working like a charm, but in production, it show some wired characters like 'A'. I found a similar question and the answer was that the meta charset needs to be set to utf-8, but it has not helped me. 
![monaco](https://user-images.githubusercontent.com/44179829/66130346-e0a06d80-e5f1-11e9-817c-334a46760619.jpg)

**Comment by alexandrudima** [comment]
@telnetserbia This is the first time I see such a behavior... Are you using editor API to configure the editor value? How do those `A` characters appear? Do they appear at the end of each line? Do they appear when you press <kbd>Enter</kbd> ?

**Comment by karreiro** [comment]
Hi @alexandrudima @telnetserbia 

I'm having the same issue:
![2019-11-01 14 18 11](https://user-images.githubusercontent.com/1079279/68042803-89ee8800-fcb2-11e9-9d1f-b00be8359011.gif)

<img width="1888" alt="Screen Shot 2019-11-01 at 14 20 23" src="https://user-images.githubusercontent.com/1079279/68042923-d934b880-fcb2-11e9-9380-d2820ab6b8b9.png">


I'm still setting the charset into header
```
<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
<meta charset="UTF-8">
```

I'm not sure if there's any workaround for this 🤔

**Comment by karreiro** [comment]
Hi @alexandrudima @telnetserbia I've noticed the issue only happens when I use the minified version from [webjars.org](https://www.webjars.org). I've replaced the `/min' by '/dev' and everything works fine.. I'm going to minify it myself for now :-)

**Comment by alexandrudima** [comment]
@karreiro Can you please share a full working HTML sample that reproduces the problem? Perhaps there is a problem with webjars.org and their charset headers?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
