### ISSUE TITLE
Suggestion: Highlight JSX in pure Monaco

### ISSUE THREAD

**Issue by sdegutis** [microsoft/monaco-editor#1609]
Right now, Monaco does not highlight any JSX, and relies on the JavaScript worker to do this. But it can be done in pure Monaco also, for those situations where the worker is not used but the token provider is, e.g. when Monaco is used as a plain syntax highlighter. By putting the name of the current opening JSX tag (replacing dots with \_\_DOT__) in a secondary state, it can also match closing tags to pop out, and highlight non-matching closing tags as 'invalid' tokens starting at the first non-matching character in the string (using a regex in a case that makes use of $S2 and $0) for increased user-friendliness.

**Comment by alexdima** [comment]
Let's track in #264
