### ISSUE TITLE
ThirdPartyNotices.txt needed

### ISSUE THREAD

**Issue by sandyarmstrong** [Microsoft/monaco-editor#161]
Due to the way monaco is built, I find it very hard to tell what dependencies (if any) are being bundled into the final distribution.

This makes it impossible to do proper license attribution when shipping monaco in another application.

VS Code has https://github.com/Microsoft/vscode/blob/master/ThirdPartyNotices.txt. It would be nice if monaco maintained a similar file.

**Comment by sandyarmstrong** [comment]
And if there's a policy that only MS-copyrighted dependencies are brought in (such as winjs), and therefore it's kosher to simply refer to monaco's license for the whole bundle, it would be good if that was stated somewhere.

**Comment by alexandrudima** [comment]
The npm module has a ThirdPartyNotices.txt.
![image](https://cloud.githubusercontent.com/assets/5047891/18173946/fe631dee-706b-11e6-953e-40010b0754b3.png)

This repository does not contain the actual source code, just the bundling scripts, therefore this repository does not technically need a ThirdPartyNotices.txt.

**Comment by sandyarmstrong** [comment]
Oh, great! Thank you. :-D

**Comment by sandyarmstrong** [comment]
Right here for anybody else who's curious https://github.com/Microsoft/vscode/blob/master/build/monaco/ThirdPartyNotices.txt.

**Comment by alexandrudima** [comment]
Please note that is correct for the npm module `monaco-editor-core`.

At this time, the one for the npm module `monaco-editor` contains the one you point to and this one -- https://github.com/Microsoft/monaco-languages/blob/master/ThirdPartyNotices.txt

**Comment by alexandrudima** [comment]
I've extract #162 to improve these files to explictly mention the winjs and the typescript projects and give proper credits to them too.
