### ISSUE TITLE
Monaco to provide a way to trigger folding evaluation programatically

### ISSUE THREAD

**Issue by LucioMS** [microsoft/monaco-editor#1610]
**monaco-editor version:** 0.18.1
**Browser:**
**OS:** 

**Steps or JS usage snippet reproducing the issue:**
When working with a parser, typically on model (content) change parsing starts on a promise.
When parsing is done, I want to trigger the folding based on the parsing results.
Currently folding is auto-triggered on model change, which is too early to have the parsing information.
I don't think there is much harm in the model change folding trigger, it is useful for most scenarios that don't need parsing, but I need to do it when the parsing promise is resolved.

**Comment by alexdima** [comment]
@LucioMS You can register a custom `FoldingRangeProvider` for your custom language. That can return in a promise what are the folding ranges.
