### ISSUE TITLE
Documentation: links to type descriptions are not clickable when followed by []

### ISSUE THREAD

**Issue by hyvyys** [microsoft/monaco-editor#1611]
![image](https://user-images.githubusercontent.com/20814638/66172364-d57a2b80-e64b-11e9-8aa1-d2ae19b9e4e1.png)

**Comment by alexdima** [comment]
@hyvyys Our documentation is generated using typedoc, perhaps support for this needs to be added in typedoc.

**Comment by hediet** [comment]
Fixed.
