### ISSUE TITLE
`getWordAtPosition` doesn't respect wordSeparators creation option

### ISSUE THREAD

**Issue by hyvyys** [microsoft/monaco-editor#1613]
I am creating the editor with option

```
{
  wordSeparators: ' `~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?'.replace(/[#/]/g, ''),
},
```

i.e., excluding `#` character. As a result, keyboard navigation and selection, as well as selecting by double click, work correctly, treating `#` as part of the word. The ITextModel method `getWordAtPosition` treats # as word separator and doesn't return it with the adjacent word characters.

**Comment by alexandrudima** [comment]
The `ITextModel.getWordAtPosition` uses the word definition that comes in via the language configuration. Each language has its own language configuration... See e.g. here for TS -- https://github.com/microsoft/monaco-languages/blob/0ed9a6c3e90a24375fab54f7205fb76ce992f117/src/typescript/typescript.ts#L15

**Comment by hyvyys** [comment]
Thanks!
