### ISSUE TITLE
Setting tabSize to 0 causes infinite loop or other issues

### ISSUE THREAD

**Issue by hyvyys** [microsoft/monaco-editor#1614]
Settings model property tabSize to 0 causes unexpected behavior. Sometimes the editor and the whole page freezes, at other times pressing Backspace deletes the following character instead of previous or appears to not delete anything or causes caret to jump around. Actually the latter happens in the Playground, and in my app developed locally the whole app just freezes, so maybe I am doing something else wrong there (I use a custom language).

If this value is not supported, it should be checked against.

I know this is a weird way to set this setting, but I was hoping to use it as a way of hiding tab stop rulers as I want to replace tab stops with arbitrary number of spaces on my end, contextually.

```
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

editor.getModel().updateOptions({
    tabSize: 0,
});
```

**Comment by spahnke** [comment]
>hiding tab stop rulers

If you mean the indent guides, you can hide those by setting `renderIndentGuides` to `false`.
