### ISSUE TITLE
Undo is not granular: all subsequent repetitions of custom command undone at once

### ISSUE THREAD

**Issue by hyvyys** [microsoft/monaco-editor#1615]
A minimal example, runnable in the Playground:

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_B, indent);

function indent() {
    const pos = editor.getPosition();
    pushEdit({ text: ' '.repeat(4), range: new monaco.Selection(
        pos.lineNumber, pos.column, pos.lineNumber, pos.column
    )});
}


function  pushEdit({ text, range }, newPosition) {
    if (!range) {
    range = editor.model.getFullModelRange();
    }
    if (!newPosition) {
    newPosition = { lineNumber: range.endLineNumber, column: range.startColumn + text.length };
    }
    const selection = editor.getSelection();
    const beforeCursorState = [ selection ];
    const cursorStateComputer = (inverseEditOperations) => {
    let newSelection = new monaco.Selection(
        newPosition.lineNumber,
        newPosition.column,
        newPosition.lineNumber,
        newPosition.column
    );
    return [newSelection];
    }
    //[ newPosition ] = 
    editor.getModel().pushEditOperations(
    beforeCursorState,
    [ { text, range } ],
    cursorStateComputer,
    );
    if (newPosition) {
        editor.setPosition(newPosition);
    }
}
```

Before you ask, I implemented custom indenting algorithm that aligns words across lines. This is just a dumber example to demonstrate the issue.

After pressing Ctrl+B I am able to add 4 spaces to current cursor position. But pressing Ctrl+Z to undo it reverts all repetitions of that operation. For instance, if I apply some repetitions of the custo indent, then make some other edits, type something, then apply indent again, then undo it one thing after another, the undo works fine with the exeception that all uninterrupted repetitions of my custom command are undone at once.

I suppose the edit operation class is called `IIdentifiedSingleEditOperation` not without a reason, and I am creating it incorrectly as a plain object. Does it have a constructor or a factory function? If so, could you provide such information in its doc page? https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.iidentifiedsingleeditoperation.html

**Comment by hyvyys** [comment]
Btw, why am I required to setPosition manually after the edit is pushed, if I have to provide a cursorStateComputer? I thought the values it returns should be applied automatically after the edit is applied, but they're not. If I don't setPosition manually, the current selection is expanded to contain the edited range, and I just want to push it after it (zero length, just position).

**Comment by alexdima** [comment]
If you have a model that is attached to an editor, the easier way to edit the model is through the editor. Models can be edited outside of an editor and it appears you have chosen that path.

The easier way would be to use `editor.executeEdits('something', edits, endSelection)`
