### ISSUE TITLE
Decoration Custom Metadata

### ISSUE THREAD

**Issue by asciiansi** [microsoft/monaco-editor#1621]
Is there a way to set custom data on a decorator? 

I've tried via Typescript to set my own decorator type by implementing the `IModelDecoration` interface and by just passing a map augmented with my own custom keys set. In both cases, custom keys get wiped out as I would probably expect given the typing, lack of a tolerant reader, and the calls through `editor.deltaDecorations`. Maybe I am just missing something obvious that doesn't require any kind of patching/internals?

contrived lazy example:

```typescript
const testDecoration = {
  range: new monaco.Range(selection.startLineNumber, selection.startColumn, 
  selection.endLineNumber, selection.endColumn),
  options: {
      inlineClassName: 'underline',
      stickiness: monaco.editor.TrackedRangeStickiness.NeverGrowsWhenTypingAtEdges,
  },
  //custom data below
  meta: {a: 1, b: 2}
 };

//later, add the decoration
editor.deltaDecorations([], [testDecoration]);

 //later, iterate decorators and access decorator.meta
```

The use case would be to implement a way of doing custom marking/selections that requires some minimal metadata. I would like to iterate through the decorations when marking items visually (ex: underline, background color changes, etc) and differentiate safely and quickly between my custom marks and any other non-mark decorations. 

I can differentiate between decoration types via css classes, but this seems like a massive hack and doesn't allow me to add any real metadata. I can also add elements via the DOM and read those, but it's also hacky and additional overhead.  Instead, I'd prefer to have something built-in like an optional map property where I can just add any required metadata to each decoration.

Is this/should this be possible without patching any functions? If not, any plans to implement a way of attaching metadata to a range of text via decorators or some other feature? Thanks.

**Comment by alexdima** [comment]
Yes, you should use decoration ids to accomplish this. When you use decorations via the `deltaDecorations` API you get back a list of strings. That list uniquely identifies the decorations you have added.

At a later time, if you use `model.getDecorationsInRange` or other such methods you can figure out which decorations belong to you by using the `id` field and correlating that with the `id` that was returned via `deltaDecorations`.
