### ISSUE TITLE
Misplaced cursor on Windows

### ISSUE THREAD

**Issue by asadm** [microsoft/monaco-editor#1626]
**monaco-editor version:** 0.18.1
**Browser:** Chrome
**OS:** Windows

The cursor position and selection is not accurate on Windows sometimes (when using custom font and editor width is small). 
Here is a the jsfiddle that reproduces the issue for me (only on Windows): https://jsfiddle.net/rjLqs03v/

A screenshot of the issue:
![](https://i.imgur.com/DKIM2pG.png)

The bug also happens on 0.17.1 but not on 0.14

**Workaround:** Setting `fontFamily` to just `monospace` fixes it for now.

**Comment by alexdima** [comment]
@asadm I could not reproduce on my machine. I believe the editor reads the font information and caches it at a time when the custom font is not finished loading. In this case, please use `monaco.editor.remeasureFonts()` once the custom font has finished loading
