### ISSUE TITLE
Editor throws RegExp too big exception if content length is longer than 32767 characters

### ISSUE THREAD

**Issue by o-su** [microsoft/monaco-editor#1628]
monaco-editor version: tested on 0.15.6 and latest
Browser: Google Chrome (latest), Firefox (latest), Internet Explorer 11
OS: Windows 10

**Steps or JS usage snippet reproducing the issue:**
1. Open Monaco editor playground: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages
2. Paste more than 32767 characters into Monaco editor
3. Click outside of the editor (lose focus)
4. click inside the editor (focus)
5. Open developer tools (F12) -> console

errors.ts:22 Uncaught Error: Invalid regular expression: 
RegExp too big
    at RegExp.exec (<anonymous>)
    at e.next (textModelSearch.ts:540)
    at e.findMatchesInNode (pieceTreeBase.ts:507)
    at e.findMatchesLineByLine (pieceTreeBase.ts:549)
    at e.findMatchesLineByLine (pieceTreeTextBuffer.ts:410)
    at o.findMatchesLineByLine (textModel.ts:938)
    at o.findMatches (textModel.ts:960)
    at wordHighlighter.ts:133
    at errors.ts:22

**Comment by rebornix** [comment]
I didn't reproduce this issue but based on the call stack, it's definitely possible that sometimes we try to create regex which is too long.

**Comment by alexdima** [comment]
I could also not reproduce, I have tried with a word that is very long (48k characters).

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by o-su** [comment]
I'm sure it didn't work in 0.15.6. I was able to reproduce it at any time. The latest version (0.19.0) looks good.
