### ISSUE TITLE
Cannot edit code in safari

### ISSUE THREAD

**Issue by ahqardah** [microsoft/monaco-editor#1629]
"@types/react-monaco-editor": "^0.16.0",
"monaco-editor-webpack-plugin": "^1.7.0",
"monaco-editor": "^0.18.1",
"react-monaco-editor": "^0.31.0",

OS: Mac OS MoJave 10.14.6

We are using Monaco as an editor for inkling language [](https://docs.bons.ai/guides/inkling-guide.html
)

now the editor works as expected in Chrome, but fails to work on safari, unable to click on the editor to edit the code. If you carefully put the curser just before the first char on the first line, it lets us edit, otherwise, it doesn't.

**Comment by spahnke** [comment]
Can you reproduce it in the [playground](https://microsoft.github.io/monaco-editor/playground.html)? It's working fine for me in Safari 13.0.2 and Catalina 10.15.

**Comment by ahqardah** [comment]
it turned out that we had ‘user-select: none’ on our body tag which was causing the behavior that Ahmad described. So this was largely a false alarm, however something to keep in mind if you hear of similar issues on Safari.

**Comment by rebornix** [comment]
If you need to set `user-selection: none` on the body, you can revert that on the editor to ensure that you can edit in Monaco.
