### ISSUE TITLE
hello！I want to know how to support Vue grammar detection or which libraries can validate Vue text

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#1630]
**monaco-editor version:** 0.X.Y
**Browser:**
**OS:** 

**Steps or JS usage snippet reproducing the issue:**

**Comment by mofux** [comment]
This is not an easy task to do. 

First, you will have to implement syntax highlighting support via [monaco-editor-textmate](https://github.com/NeekSandhu/monaco-editor-textmate#readme).

Next, you have to implement language server support, check [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) for that. Once that's done, there is the [vue language server](https://github.com/vuejs/vetur/tree/master/server) that you have to implement.

[codesandbox](https://github.com/codesandbox/codesandbox-client) has a working implementation for that, you might get some inspiration from their code.
