### ISSUE TITLE
Uncaught Error: Cannot read property value of null\n\nTypeError: Cannot read property value of null\

### ISSUE THREAD

**Issue by uraniaWz931018** [microsoft/monaco-editor#1633]
**monaco-editor version:** 0.0.9
**Browser:Chrome
**OS:** Mac OS X/Win

**Steps or JS usage snippet reproducing the issue:**

we have use monaco-editor in our recent repo and it has caused problem:
**"Uncaught Error: Cannot read property 'value' of null\n\nTypeError: Cannot read property 'value' of null\n    at ..... t.get [as value] .....at t.addToHistory.....**

I have tracked error line in inputBox.ts file in monaco-editor package as the following:
 
public addToHistory(): void {
                                **if (this.value && this.value !== this.getCurrentValue()) {**
                                                this.history.add(this.value);
                                }
                }
 
do you have ideas how it happens?

**Comment by alexdima** [comment]
@uraniaWz931018 I cannot reproduce. Do you have any steps?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
