### ISSUE TITLE
First time typing to overwrite selected text with Chinese IME on Edge actually does nothing

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/monaco-editor#1634]
**monaco-editor version:** 0.18.1 (on playground)
**Browser:** Edge/18.18362
**OS:** Windows 10
![temp](https://user-images.githubusercontent.com/50703224/66920515-0861ed80-f056-11e9-90b5-0acd1f3c42c3.gif)

**Steps or JS usage snippet reproducing the issue:**
* Make sure the editor has just got focus. E.g. click outside the editor first, and continue with the next step.
* Select some text inside editor.
* Type something with Chinese IME (MSPY). Press `Space` or `Enter` to commit it.
    * You will see nothing actually committed to the editor.
* Type something again with IME. Press `Space` or `Enter` to commit it.
    * You will see the characters committed to the editor now.

**Comment by alexdima** [comment]
Let's track in #1410
