### ISSUE TITLE
The Find dialog will reopen after closing it with ESC when pressing Enter in edit mode (only in Firefox)

### ISSUE THREAD

**Issue by kilroy42** [microsoft/monaco-editor#1637]
**monaco-editor version:** 0.18.1
**Browser:** Firefox 69.0.2 (no plugins installed)
**OS:** Linux (Ubuntu 19.04) / Windows (2012 R2)

Use Firefox to open the playground: https://microsoft.github.io/monaco-editor/playground.html

 * Click into the editor
 * Press Ctrl-F to open the find dialog
 * Press ESC to close the find dialog
 * Press Enter to start a new line -> the find dialog re-opens
 * From now on, it is impossible to use the enter key in editing

If you use the "X" to close the find dialog, everything works as expected. Seems like ESC doesn't close the find dialog correctly.

**Comment by hediet** [comment]
Cannot reproduce:

![firefox_QrpNfQbrDK](https://user-images.githubusercontent.com/2931520/224342304-6b29814f-46c0-4c1a-8542-2a823ac97558.gif)
