### ISSUE TITLE
Errors on the console with TypeScript code fixes

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#1638]
**monaco-editor version:** > 0.18.1 (not released yet)
**Browser:** Chrome/Edge
**OS:** Windows 10

**Steps or JS usage snippet reproducing the issue:**
https://github.com/microsoft/monaco-typescript/pull/40 added support for code fixes which is not released yet. You can play around with that however in the TypeScript playground. Using the following code I get errors on the console when moving the cursor on either side of the last semicolon:
```js
const test = 'foobar';
throw new Error(test);
test;
```
Playground link:
http://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/MYewdgzgLgBFCm0YF4YHIBmIQCMCGATmgNwBQUAFgSAO4xjx0CiB1BAFAtAJRldTEgA

![grafik](https://user-images.githubusercontent.com/25029871/67191548-16b35f00-f3f2-11e9-8795-9137a2cb3454.png)

/cc @orta

**Comment by alexdima** [comment]
I can reproduce also with the TS `3.7.3`. I suggest to file an issue directly against https://github.com/microsoft/Typescript

cc @orta

**Comment by orta** [comment]
Confirmed, this feels like my bug yeah 👍

**Comment by orta** [comment]
Yeah, it's in the monaco-typescript implementation, the compiler didn't get the same issue with

```ts
/// <reference path="fourslash.ts" />

//// const test = 'foobar';
//// throw new Error(test);
//// test;

verify.codeFixAll({
  fixId: "addMissingNewOperator",
  fixAllDescription: "Add missing 'new' operator to all calls",
  newFileContent:
`class C {
  constructor(num?: number) {}
}
var a = new C();
var b = new C(3);`
});

```
