### ISSUE TITLE
Monaco editor is showing a default line on top without number, in React application

### ISSUE THREAD

**Issue by himanshu9891** [microsoft/monaco-editor#1639]
Hi,

I am using Monaco editor in my react application. It is showing a default line on top without number. Line no 1 is starting after this default line. 

I tried many examples where it is not showing default line in demo but for me always showing default line.

![image](https://user-images.githubusercontent.com/32285576/67208641-7f6efb80-f433-11e9-898c-8ede25a602e9.png)

Using below code in App.js
`import MonacoEditor from 'react-monaco-editor';`
.
.
.
`<MonacoEditor
                  width="100%"
                  height="500"
                  language="sql"
                  theme="vs-dark"
                  value={code2}
                  options={options}
                  editorDidMount={this.editorDidMount}
                />`

Not able to show glyphMargin on default line.

Please let me know if any thing is missed or done wrong.

monaco-editor version: 0.17.1
Browser: Chrome
OS: win 8

**Comment by alexdima** [comment]
I cannot reproduce what you describe.

IMHO this is a problem with the CSS of your HTML interacting with the dom elements of the editor. Please try to comment out all your custom CSS and start adding it back progressively to determine which rules are to blame...

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
