### ISSUE TITLE
Scroll position not saved when switching models

### ISSUE THREAD

**Issue by npenin** [Microsoft/monaco-editor#164]
Hi,

As far as I understood, the goal to have an editor with multiple files is to have only one editor and swtich the models on this editor. I did this, but when switching from a model to another, the scroll position is reset to top. Is there is any configuration on the editor that could help ?

Thanks,
Nicolas

**Comment by alexandrudima** [comment]
Hi, you can save the view state associated to a model, store it somewhere (it is serializable with JSON.serialize) and then retrieve it:

```
var oldModel = editor.getModel();
var oldViewState = editor.saveViewState()
editor.setModel(newModel);

// ...

editor.setModel(oldModel);
ed.restoreViewState(oldViewState);
```
