### ISSUE TITLE
"setModelMarkers()" is not showing message on highlighted markers in Monaco editor implemented in React application

### ISSUE THREAD

**Issue by himanshu9891** [microsoft/monaco-editor#1640]
Hi,
I am using "setModelMarkers()" to highlight the syntax errors in Monaco editor implemented in React application.
The message added to the marker is not getting displayed on hovering over the highlighted text.

It is working fine in play ground.

![image](https://user-images.githubusercontent.com/32285576/67209388-e2ad5d80-f434-11e9-920d-0d1f940a07e6.png)

Please let me know if any thing is missed or done wrong.

monaco-editor version: 0.17.1
Browser: Chrome
OS: win 8

**Comment by alexdima** [comment]
@himanshu9891 It is not possible for us to help you without a reproducible case. Please share with us a self-contained HTML page demonstrating the problem.

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
