### ISSUE TITLE
angular 7 editor.setTheme is not a function

### ISSUE THREAD

**Issue by GrantWD** [microsoft/monaco-editor#1641]
**monaco-editor version:** 8.1.0
**Browser:**chrome
**OS:** windows

**Steps or JS usage snippet reproducing the issue:**

html
` <ngx-monaco-editor [options]="editorOptions" [(ngModel)]="code" (onInit)="onInit($event)"></ngx-monaco-editor>`

**.component.ts
  onInit(editor) {
    editor.setTheme('vs');
  }
``

browser
 ERROR TypeError: editor.setTheme is not a function

**How should I use method setTheme?**

**Comment by brijeshb42** [comment]
`setTheme` is not an editor method. Its a global function that you can call using `monaco.editor.setTheme(themeName)`
