### ISSUE TITLE
Monaco editor has removed viewModel in the latest version

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/monaco-editor#1642]
Now there seems to be no way to get the line count including line wraps.
Before we had editor.viewModel.getLineCount()
Is there any plan to add this feature in the future? Why was it removed?

Calculating it on our end is very hard, as we need to take into account the font size, font family, and size of the editor.

**Comment by rebornix** [comment]
You can still access it from `editor._modelData.viewModel`.
