### ISSUE TITLE
HTML - highlighting and auto-suggestion setup

### ISSUE THREAD

**Issue by MarshyMimz** [microsoft/monaco-editor#1644]
Hi,

I'm completely new to Monaco Editor and trying to re-create similar to the image on https://github.com/microsoft/monaco-editor however using my own language.

I have followed this https://github.com/microsoft/monaco-languages to create the language and added my release file according to this https://stackoverflow.com/questions/50606676/how-do-i-add-a-new-language-syntax-to-monaco-editor
 
What I am struggling to figure out is where to find or how to setup the index.html file for highlighting and auto-complete suggestion for my own language

Thanks in advance! Apologies for the inconvenience.

**Comment by alexdima** [comment]
@MarshyMimz I would recommend to start with a sample from https://github.com/Microsoft/monaco-editor-samples

Once you have the editor up and running in a HTML page, you can begin to exercise the editor API to register a new language, define the tokens for it, etc. There are many examples in the playground samples at e.g. https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

**Comment by MarshyMimz** [comment]
Hi,

Thanks for suggestion, managed to get things sorted
