### ISSUE TITLE
Can't scroll in firefox

### ISSUE THREAD

**Issue by zhixzhan** [microsoft/monaco-editor#1645]
**monaco-editor version:** 
0.17.2
**Browser:**
FireFox 69.0.3
**OS:** 
Windows 10

**Steps or JS usage snippet reproducing the issue:**
1. checkout monaco-editor-sample here
https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack

2. npm install monaco-editor@latest

3. open firefox, then can't scroll in editor

**Comment by spahnke** [comment]
That's already fixed in the latest version.

**Comment by zhixzhan** [comment]
> That's already fixed in the latest version.

Yes, It works fine in 0.18.1, thanks @spahnke

**Comment by onlySparrow** [comment]
Have you solved the bug?
