### ISSUE TITLE
[Intellisense] Special Characters like "[" could not be matched in completion item.

### ISSUE THREAD

**Issue by luomoyuyi** [microsoft/monaco-editor#1646]
I hava a bunch of completion items start with the character "[" such as [ValidFrom, when I type the character "[" there are several completion items shown as intellisense but the ones that with "[" prefix have not been filtered out. The cause is that monaco editor did not match the input "[" with the "[" chatacter in completion item.  As you can see below.

![image](https://user-images.githubusercontent.com/9990601/67370804-edd7c900-f5ad-11e9-83e7-37044cad8fae.png)

**Comment by luomoyuyi** [comment]
Any ideas ?

**Comment by blois** [comment]
You can explicitly specify the range for the completion item to include the `[`: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html#range
