### ISSUE TITLE
How to check the state of the completion widget?

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#165]
I have `onKeyDown` handler that changes an editor content when a user presses up or down. It breaks navigation up and down in the completion widget, so i want to propagate a keyboard event if the completion widget is activated. How can I check it?

**Comment by akosyakov** [comment]
I found out that I can check like that: `this.editor._view.contentWidgets._widgets["editor.widget.suggestWidget"].isVisible`

Do you have plans to make default widgets public API? Also provide API to access registered content widgets?

**Comment by akosyakov** [comment]
I see in VS code there are contexts and for actions when-clause can be provided to activate them, e.g. an action can be activated when 'suggestWidgetVisible' context is not activated. It would be nice to have ability to compose such expressions for monaco also and get access to contexts of default content widgets.

**Comment by alexandrudima** [comment]
The recommended way to participate in keybinding dispatching is via `editor.addCommand`, but just now I noticed that in the latest version this fails due to a refactoring we did. The sample is at https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-key-events

I am looking into a fix.

**Comment by akosyakov** [comment]
I am not sure that it will help me. I want to prevent my handler for up and down arrows if the suggest widget is visible.

**Comment by akosyakov** [comment]
Can i do something like:
```typescript
this.editor.addCommand(monaco.KeyCode.UpArrow, ()=>{...}, '!suggestWidgetVisible');
this.editor.addCommand(monaco.KeyCode.DownArrow, ()=>{...}, '!suggestWidgetVisible');
```

**Comment by akosyakov** [comment]
ok, it does work but still would be nice to have a reference to 'suggestWidgetVisible' const

**Comment by alexandrudima** [comment]
@akosyakov Agreed, but you'd also have to build the strings yourself '!' + constants. It is perfectly fine to depend on these, as they are "sort of API", as they appear in the `keybindings.json` in VSCode and folks write keybinding rules that depend on them, so we will probably never rename them.

**Comment by akosyakov** [comment]
@alexandrudima I have a command for UpArrow that should be executed only if a cursor at the start position of a document; otherwise the default command should be used. How can I register it?   Is it possible to call the default command from a custom?

**Comment by alexandrudima** [comment]
Please see https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance

You can add a command that has as condition "atStartOfDocument". You can then create a context key "atStartOfDocument" and listen to `onDidPositionChange` and update the context key value appropriately.
