### ISSUE TITLE
Document suggestion

### ISSUE THREAD

**Issue by iamwelk** [microsoft/monaco-editor#1650]
The document is too hard to read and use now. Could you make it more simple and clear?
BTW, the editor is awesome!

**Comment by alexdima** [comment]
I'm not sure, what do you mean by "document" ?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
