### ISSUE TITLE
Display Issue for Line Numbers with 2 Digits

### ISSUE THREAD

**Issue by amichael7** [microsoft/monaco-editor#1653]
**monaco-editor version:**  "monaco-editor-webpack-plugin": "1.7.0" from NPM
**Browser:** Chrome
**OS:** Windows 10

![image](https://user-images.githubusercontent.com/37033538/67886803-16b10e80-fb18-11e9-9390-ccfbd05c6340.png)

Hi, I'm bringing this bug over from [Polynote Issue #559](https://github.com/polynote/polynote/issues/559).  The bug only seems to be affecting Google Chrome on Windows 10.  The Polynote team is using a Monaco node module to set up an editor.  The following is the Typescript snippet used to produce the issue (from [this code](https://github.com/polynote/polynote/blob/master/polynote-frontend/polynote/ui/component/cell.ts)):

```typescript
// set up editor and content
this.editor = monaco.editor.create(this.editorEl, {
    value: initContent,
    language: highlightLanguage,
    codeLens: false,
    dragAndDrop: true,
    minimap: { enabled: false },
    parameterHints: {enabled: true},
    scrollBeyondLastLine: false,
    theme: 'polynote',
    fontFamily: 'Hasklig, Fira Code, Menlo, Monaco, fixed',
    fontSize: 15,
    fontLigatures: true,
    contextmenu: false,
    fixedOverflowWidgets: true,
    lineNumbers: 'on',
    lineNumbersMinChars: 1,
    lineDecorationsWidth: 0,
    renderLineHighlight: "none"
});
```

In the Chrome inspector, the `width` attribute on the `div` containing the digits is fixed at `15px` which isn't enough to display 2 digit numbers (`<div class="line-numbers" style="left:0px;width:15px;">11</div>`). If I remove the width restriction, the number expands to display on a single line.  Any help with this issue would be much appreciated!

**Comment by alexdima** [comment]
@amichael7 I believe it has to do with font loading. I think perhaps `Hasklig` is loaded via a CSS font-face and that the editor measures the width of numbers at a time when the font has not finished loading. 

So the editor has wrong font measurements... You can use `monaco.editor.remeasureFonts()` to ask the editor to remeasure the font metrics it needs.

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
