### ISSUE TITLE
Luminosity ratio is less than 4.5:1 for text present under "Code editor" screen.

### ISSUE THREAD

**Issue by sagar17sep** [microsoft/monaco-editor#1654]
**OS version:** 1903 (OS Build: 18326.295)
**Browser:** Edge(Microsoft Edge 44.18362.267.0)
**Tool:** Colour Contrast Analyser.

**User Experience:** 
If Low vision user navigate to the page and luminosity ratio is less than as required (4.5:1) for "Text" so it would be difficult for the users to read the text with an ease.

**Steps or JS usage snippet reproducing the issue:**
1) Luminosity ratio is less than 4.5:1 for text present under "Code editor".

**Actual Result:**
Luminosity ratio is less than 4.5:1 for text present under "Code editor" screen.

**Expected Result:**
Luminosity ratio should be greater than 4.5:1 or equal for text present under "Code editor" screen.

**Please find the attachments**
![MAS1 4 3_Portal - Code Editor_ themes](https://user-images.githubusercontent.com/38970470/67929666-d8812100-fbe3-11e9-9887-a1f3cf850c3d.png)
![MAS1 4 3-Code editor](https://user-images.githubusercontent.com/38970470/67929670-dc14a800-fbe3-11e9-800a-09cf11fbba07.png)

**Comment by alexdima** [comment]
The Monaco Editor ships with a special high contrast theme. This theme can be chosen by the embedder or enabled by the end user via `F1 > Toggle High Contrast Theme`.
