### ISSUE TITLE
how to launch after install

### ISSUE THREAD

**Issue by jinfagang** [microsoft/monaco-editor#1659]
how to launch after install

**Comment by spahnke** [comment]
Please read the documentation section of the README on how to use the editor https://github.com/microsoft/monaco-editor#documentation. There are plenty of examples.

**Comment by jinfagang** [comment]
@spahnke  Thanks for reply.

I mean not embed in js. I wanna try a text editor which runs in chrome brower, does there any application for that?

**Comment by rcjsuen** [comment]
@jinfagang I'm not sure I follow. Chrome renders webpages and you can embed the Monaco Editor in a webpage, no?

**Comment by jinfagang** [comment]
I mean, handle local file system such as open a directly on my local machine and then edit it just like vscode. Wonder if there is a app support it or not using this lib. This could be useful when I am not want using vscode or I want edit some file on remove server.

**Comment by rcjsuen** [comment]
@jinfagang But if the editor runs in the browser, how would it talk to your local file system? You have to have another process that's serving files to the browser.

Point being, Monaco is simply the shell of an editor and your additional requirements cannot be satisfied with just this library.
