### ISSUE TITLE
An idea for LSP Service

### ISSUE THREAD

**Issue by quank123wip** [microsoft/monaco-editor#1662]
Just an idea:)
Pack a minimal Linux file system into one single file, Compile LSP Service as Webassembly. Override All read actions into the Linux FS, and redirect the websocket connection into the editor directly.

Is that possible to do that? Many people would like to edit their code in browser with auto-complete:)

**Comment by mofux** [comment]
Check out the `codesandbox.io` sources. They "simulate" a node environment in a web worker and then run language servers inside that web worker. More precisely, they run the vscode extension host process in the worker, which allows them to run the built-in vscode language servers in the browser. A good starting point can be found here: https://github.com/codesandbox/codesandbox-client/tree/76aa31442496025f8da488cff3d7cab555dace37/packages/app/src/app/vscode/extensionHostWorker

**Comment by quank123wip** [comment]
> Check out the `codesandbox.io` sources. They "simulate" a node environment in a web worker and then run language servers inside that web worker. More precisely, they run the vscode extension host process in the worker, which allows them to run the built-in vscode language servers in the browser. A good starting point can be found here: https://github.com/codesandbox/codesandbox-client/tree/76aa31442496025f8da488cff3d7cab555dace37/packages/app/src/app/vscode/extensionHostWorker

Maybe it's a good way to run the language server inside the browser, the only problem now is make a minimal Linux FS and redirect all the actions into the FS
