### ISSUE TITLE
iOS 13.2 Chinese input randomly can not input characters

### ISSUE THREAD

**Issue by Brooooooklyn** [microsoft/monaco-editor#1663]
**monaco-editor version:** 0.18.1
**Browser:**
Safari
**OS:** 
iOS 13.2

**Steps or JS usage snippet reproducing the issue:**
Playground

**Comment by Brooooooklyn** [comment]
In iOS 13.2, System Chinese input will trigger an additional `CompositionEvent` with `empty data` after input some words.

![ios-monaco-bug 2019-11-07 18_24_49](https://user-images.githubusercontent.com/3468483/68381037-e7d80f80-018b-11ea-8c4a-906673721634.gif)

**Comment by rcjsuen** [comment]
@Brooooooklyn The Monaco Editor doesn't support mobile platforms at the moment.

See #246, #1365, #1504, and I'm sure there are many more out there.

**Comment by Brooooooklyn** [comment]
iPad OS 13.2 has the same issue, even with physical keyboard. So I think it's worth to fix it.

**Comment by rebornix** [comment]
Thanks I can confirm that Safari on iOS emits double composition end events

Safari on macOS catalina
![image](https://user-images.githubusercontent.com/876920/68411489-6bb7da80-013f-11ea-8a26-8cc5076d4e07.png)

Safari on iOS13 emulator
![image](https://user-images.githubusercontent.com/876920/68411592-9013b700-013f-11ea-87a8-10ea403fa8fd.png)

@Brooooooklyn can you provide more details about how to reproduce the issue you described "randomly can not input characters" as I can't reproduce this issue from my side. Once a good reproduce step is provided, we can move this issue to VS Code repo.

**Comment by Brooooooklyn** [comment]
The screenshot below is running monaco editor playground on iOS 13.2 emulator
I can't find the step which can stablely input words success or fail.
But I found that simply return when `compositionend` event emmited with empty string could fix this issue: https://github.com/microsoft/vscode/pull/84121/files#diff-b57d2c0cf11cc9d73357705196b8b3cbR276-R278
![monaco-ios-bug](https://user-images.githubusercontent.com/3468483/68446047-8b6e0200-0216-11ea-9157-fe4708eb66e9.gif)
