### ISSUE TITLE
javascript and variables / function

### ISSUE THREAD

**Issue by GlauberF** [microsoft/monaco-editor#1664]
Hello, I'm new here and I'm sorry if the question is too basic.

I use the monaco editor with the angular and created a component for it and everything works 100%.

I am a doubt and searched several places and did not find.

I will explain my scenario.

I retrieve a json in the database that is in string format and some possibilities can get variable reference function.
My doubt how I can inject and make available in the editor the scope (with variables and function), so I can reference in my json within the editor.
because the monaco component is a modal, so when i click edit it opens this modal and i pass the json code etc ..
I would need to inject the local variables, too, for reference inside.

Briefly, imagine the following.
`const testVar = () => 3;`

My javascript/json:

```javascript
[ 
   { 
      "key":testVar
   }
]
```

In the above scenario it works, because everything is in the same scope, now if I click on edit I am taking only the json and with that will return err, because there in the scope of the editor does not exist **testVar**

if anyone can help :)

**Comment by IamFonky** [comment]
Hello!
If you use javascript language you can give the editor a typescript definition lib

``` javascript
monaco.languages.typescript.javascriptDefaults.addExtraLib("declare const testVar : () => 3", "yourlibname.d.ts")
```
The variable will be accepted by the editor now :sunglasses: 

Hope it helped you!

**Comment by GlauberF** [comment]
Thanks
