### ISSUE TITLE
Focus is moving to some hidden elements on the Monaco editor screen in Scan mode.

### ISSUE THREAD

**Issue by sagaranandani17** [microsoft/monaco-editor#1666]
**OS version:** 1903 (OS Build: 18326.295)
**Browser:** Edge(Microsoft Edge 44.18362.267.0)

**User Experience:** 
Users using narrator as screen reader, will not be able to identify and interact with the elements properly, if narrator focus is going on hidden elements in Monaco editor in scan mode

**Steps reproducing the issue:**
We are showing Css in Monaco editor and on pressing tab focus is going in hidden element inside monaco editor and it says blank blank..

**Actual Result:**
Narrator focus is moving to some hidden elements on the screen in Scan mode.

**Expected Result:**
Narrator focus should not move to some hidden elements on the screen in Scan mode.

**Please find the attached video and screenshot for more details**
![image](https://user-images.githubusercontent.com/57341535/68452905-e2290b00-0219-11ea-8a72-0dded73db54e.png)

[MAS4.2.10_Portal - Code Editor.zip](https://github.com/microsoft/monaco-editor/files/3823140/MAS4.2.10_Portal.-.Code.Editor.zip)

**Comment by alexdima** [comment]
I have spent an entire morning trying to understand what causes Narrator to read "blank" for a lot of time before hitting our `<textarea>`.

I have tried various things, like removing almost all dom nodes, using `aria-hidden` on absolutely every dom node except the `<textarea>`, Narrator continues to read blank, blank in scan mode before hitting the `<textarea>`.

At this point, I admit defeat, maybe someone else has some ideas?

**Comment by alexdima** [comment]
Others appear to hit this too -- it looks like scan mode is (intentionally?) reading things that use `aria-hidden="true"` -- https://stackoverflow.com/questions/34752318/wai-aria-event-if-aria-hidden-true-ms-windows-narrator-reads-text-from-ui

**Comment by alexdima** [comment]
Closing, as Microsoft Edge Legacy has reached end of support on March 9, 2021. See [the end of support for Microsoft Edge Legacy announcement](https://docs.microsoft.com/en-us/lifecycle/announcements/edge-legacy-eos-details)
