### ISSUE TITLE
[Question] Location of builtin autocompletion configuration

### ISSUE THREAD

**Issue by celian-garcia** [microsoft/monaco-editor#1672]
Hi guys, I tried to ask my question on stackoverflow without any answer https://stackoverflow.com/questions/57921084/where-is-the-monaco-editor-autocompletion-located

So I ask again here :

---

I'm creating a [PromQL language support](https://github.com/celian-garcia/monaco-languages-promql) for monaco-editor and **I'd want to send you a PR to integrate it as a default language**.

That said, nice work ! It took me a while to understand the tokenizer, but the result fits perfectly our needs.

It's basically composed by two main configuration objects: 
- Syntax highlighting (``ILanguage``)
- Code auto-completion (``CompletionItemProvider ``)

### [ok] Syntax highlighting 

I found that the languages definition and **syntax highlighting definition** are located in this repository : https://github.com/microsoft/monaco-languages

### [??] Auto completion
I didn't manage to find where are located the default **autocompletion definitions** for these languages ?
Where should I send the PR to add a new language autocomplete ?

### Further searches
I found that some languages have some specific repositories which contains well some completion items, like:

- **typescript** https://github.com/microsoft/monaco-typescript
- **css** https://github.com/microsoft/monaco-css
- ...
Now what about the other languages, like Java, Python ... ?

Thanks !

**Comment by rcjsuen** [comment]
@celian-garcia I believe Monaco only comes with support for JavaScript/TypeScript, CSS, JSON, and HTML by default and that is why those `monaco-abc` repositories exist. There is no code completion for other languages such as Java and Python by default.

**Comment by celian-garcia** [comment]
Ah okay I see, thanks for your quick answer :)

So if I understood correctly, I will keep my repository as separated and people who need it just have to use it as a plugin. 

Last question : do you think it's worth it to follow some guidelines/architecture in the repo https://github.com/celian-garcia/monaco-languages-promql to facilitate the integration for somebody who want to use it ? 
I thrown an eye to the monaco-abc repositories which are very more complex that my little one ^^

**Comment by rcjsuen** [comment]
@celian-garcia Yes, I think a separate repository makes sense as it would be consistent with the other repositories out there.

I've never integrated other languages into Monaco so I can't speak for the difficulty of it. I am sure whatever documentation you can provide would be much appreciated by the wider community though. :)

**Comment by celian-garcia** [comment]
Okay, I will try to be as closest as possible to these repos and make more documentation on the "vanilla" integration. (since I already did the angular and react integration).

Thank you for your time !
