### ISSUE TITLE
Monaco-Editor not working with Web Component

### ISSUE THREAD

**Issue by mittalalok** [microsoft/monaco-editor#1676]
**monaco-editor version:0.18.1
**Browser: Chrome
**OS:**

**Steps or JS usage snippet reproducing the issue:**

I am trying to use a monaco-editor in Web Component (shadow root). I see that it pollute the dom (body) outside of a shadow root. For example, it adds "&lt;div class=&quot;monaco-aria-container&quot;&gt;" to the body.

Could you please share some insights about this?

**Comment by alexdima** [comment]
This is currently not supported. Let's track in #619
