### ISSUE TITLE
How to run Python code in manaco-editor

### ISSUE THREAD

**Issue by mengayng** [microsoft/monaco-editor#1677]
**monaco-editor version:** 0.18.1
**Browser:**
**OS:** 

**Steps or JS usage snippet reproducing the issue:**

**Comment by rcjsuen** [comment]
@mengayng Monaco is simply an editor in the browser. Presumably if you want to run the Python code you would need some backend environment that retrieves the code the user is editing and then executes it.

You may also be interested in looking at alternatives and [running Python in the browser](https://pythontips.com/2019/05/22/running-python-in-the-browser/) directly perhaps. It really depends on your exact use cases and how big your Python files will be. You should also keep in mind whether your users will be doing stuff like `import os` or not.

**Comment by mengayng** [comment]
@rcjsuen thanks, you've really been a big help
