### ISSUE TITLE
Add support for Scala language

### ISSUE THREAD

**Issue by brandonk3nt** [microsoft/monaco-editor#1678]
Scala is not a [currently supported language](https://github.com/microsoft/monaco-languages), can we fix please?

**Comment by Kowills** [comment]
Scala is not a currently supported language, can we fix please?

**Comment by f7753** [comment]
Looking forward to this feature.
Want to use monaco-editor as a wed notebook for Spark/Flink apps.
:)

**Comment by mulderbaba** [comment]
created a [PR](https://github.com/microsoft/monaco-languages/pull/97) for this one
