### ISSUE TITLE
Inconsistent line-end matching in tokenizer

### ISSUE THREAD

**Issue by boydc2014** [microsoft/monaco-editor#1685]
I was struggling trying to match a single line break using the following minimal tokenizer
```javascript
// Register a tokens provider for the language
monaco.languages.setMonarchTokensProvider('mySpecialLanguage', {
	tokenizer: {
		root: [
			[/$/, {token: "lineEndtoken", log: "line end"}]
		]
	}
});
```
This wouldn't print any log, but if i switch to
```
    [/.$/, {token: "lineEndtoken", log: "line end"}] // adding a "." before "$" will correctly match line end
```

I wonder what's the best way to do that? am i missing anything from document. 

The reason i want match line end is i want to create a tokenizer for some expression language which push to some state when encounter "@" and pop when "line end", then in the middle, i can leverage any patterns to generate tokens i want, things like this
```
@foo(a, b, c) 
@bar(1)
@(foo(1) + bar(1))
```
in a word, the combination in the middle is a little bit complicated, so it's hard to enumerate that at top level. 

Any ideas would be appreciated.

**Comment by alexdima** [comment]
@boydc2014 I wonder if you could use the parens as indicators when to leave the state? Here is an example for counting how many parens are open/closed: https://github.com/microsoft/monaco-languages/blob/0ed9a6c3e90a24375fab54f7205fb76ce992f117/src/razor/razor.ts#L245-L251

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
