### ISSUE TITLE
Why es6 in esm code with only `import` or `export` ?

### ISSUE THREAD

**Issue by wang12124468** [microsoft/monaco-editor#1687]
**monaco-editor version:** *
**Browser:** *
**OS:** *

**Steps or JS usage snippet reproducing the issue:**
1. I find monaco-editor with esm that used es5 to write but only `import` or `export` is es6. When i use it with es5, must compile to es5 because of `import` or `export`!!!  Such as:

```
// In my config with compile exclude `node_modules` but only include `monaco-editor`.
import { Range } from 'monaco-editor/esm/vs/editor/common/core/range';
function append(editor, value, prefix, suffix) {
    const { lineNumber, column } = editor.getPosition();
    const range = new Range(lineNumber, column, lineNumber, column);
    const text = prefix + value + suffix;
    editor.executeEdits(`append ${text}`, [{ text, range, forceMoveMarkers: true }]);
    editor.focus();
}
```
![](https://raw.githubusercontent.com/wang12124468/img/master/issue/2.png)

2. How about all is es5?

**Comment by alexdima** [comment]
@wang12124468 In the `esm/` folder you find the editor that uses the EcmaScript Module syntax (`ESM`) which means it uses `import` and `export` statements. In the `amd/` folder you can find the editor that uses amd and is es5.
