### ISSUE TITLE
[diff editor] option to remove 'diffOverviewRuler'

### ISSUE THREAD

**Issue by vince-fugnitto** [microsoft/monaco-editor#1689]
**Feature Request**

I'd like to know if it is possible to add an option to be able to remove the `diffOverviewRuler` when creating `Diff Editors`. 

If not, is there a recommended way to remove the `diffOverviewRuler`?

<div align='center'>

<img width="1228" alt="Screen Shot 2019-11-28 at 6 42 59 PM" src="https://user-images.githubusercontent.com/40359487/69835356-ef308d00-120e-11ea-80c3-392379843e6e.png">

</div>

**Additional Information**

**monaco-editor version:** 0.18.1
**Browser:** Chrome v.78
**OS:** macOS Mojave 10.14.6

**Comment by sorahn** [comment]
I was also trying to remove this.  There is an option for `overviewRulerLanes` but setting that to 0 doesn't seem to do the trick. 

For our application we're only using the editor, and not the entire layout, so I was able to kind of hack this with CSS.

I set the `diffOverview` div to `display: none;` and then set the width of the entire editor to `calc(100% + 30px)` (`30px` being the default width of the ruler)

I'm not sure if that is helpful in your case since you have the rest of the application visible.

**Comment by vince-fugnitto** [comment]
> I was also trying to remove this. There is an option for `overviewRulerLanes` but setting that to 0 doesn't seem to do the trick.
> 
> For our application we're only using the editor, and not the entire layout, so I was able to kind of hack this with CSS.
> 
> I set the `diffOverview` div to `display: none;` and then set the width of the entire editor to `calc(100% + 30px)` (`30px` being the default width of the ruler)
> 
> I'm not sure if that is helpful in your case since you have the rest of the application visible.

Thanks for the reply! 
I've also noticed others using CSS to remove it, but I'd rather only do so if absolutely necessary. 
I feel as though if many are attempting to remove it, it'd be better to support it out of the box through an option. This way everyone won't need to be hacking it out :(

**Comment by sorahn** [comment]
I discovered yesterday while doing some more CSS tweaking that `overviewRuler` and `diffOverview` are different things.  Setting `overviewRulerLanes` does in fact remove the lanes from the `overviewRuler`.

**Comment by vince-fugnitto** [comment]
> Setting overviewRulerLanes does in fact remove the lanes from the overviewRuler.

Do you mean you've set the `overviewRulerLanes` to 0 when creating diff editors?

**Comment by sorahn** [comment]
> Do you mean you've set the overviewRulerLanes to 0 when creating diff editors?

Yes.  But the overviewRuler is not the scroller that has the diff changes in it.  It's the tiny ruler just inside it that shows the cursor location.

The bottom picture has `overviewRulerLanes: 0`

![Screen_Shot_2019-12-05_at_3_47_00_PM](https://user-images.githubusercontent.com/588852/70245803-fc9dc800-1776-11ea-9ed6-0e9b9f3fe3d4.png)

**Comment by vince-fugnitto** [comment]
> > Do you mean you've set the overviewRulerLanes to 0 when creating diff editors?
> 
> Yes. But the overviewRuler is not the scroller that has the diff changes in it. It's the tiny ruler just inside it that shows the cursor location.
> 
> The bottom picture has `overviewRulerLanes: 0`
> 
> ![Screen_Shot_2019-12-05_at_3_47_00_PM](https://user-images.githubusercontent.com/588852/70245803-fc9dc800-1776-11ea-9ed6-0e9b9f3fe3d4.png)

Ah I see. I'm more looking for an option to remove the scrollbar with the diff changes.
At the moment, the only way to remove it as far as I know is to hack it out using CSS.
I propose that it should be configurable through an option :)

**Comment by sorahn** [comment]
Yes, totally.  I also want to remove the diffBar.  Thats how I ended up in your issue.  
AFAIK the only way to do that right now is with some CSS hacks.  Which isn't great, but doable.  Hopefully someone from the VSCode notices. :)

**Comment by zeevmoney** [comment]
In case someone bumps into this question - there is an option now called `renderOverviewRuler`, it removes the diff changes scrollbar / overview ruler.

![image](https://user-images.githubusercontent.com/7361100/145686398-f78c977d-e40f-47af-90ab-3dab14790166.png)
