### ISSUE TITLE
Uncaught Error: Unexpected usage

### ISSUE THREAD

**Issue by sdrebel** [microsoft/monaco-editor#1690]
Hi I'm getting this below error , when I add language option. Kindly let us know how do I resolve it.

          errors.js:15 Uncaught Error: Unexpected usage
          Error: Unexpected usage
               at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:673)
               at webWorker.js:76
               at errors.js:15

My method to initialize the code editor

     import * as monaco from 'monaco-editor';

     let monacoEd = monaco.editor.create(document.getElementById(containerId), {
        value: val,
        language: "javascript", //'text/html'
        lineNumbers: "on",
        roundedSelection: false,
        scrollBeyondLastLine: false,
        readOnly: false,
        theme: theme,
        wordWrap: 'wordWrapColumn',
        wordWrapColumn: 50,
        scrollbar: {
            horizontal: 'visible',
        },
        letterSpacing: 1,
        useTabStops: true
    });

Thank You

**Comment by alexandrudima** [comment]
@sdrebel This looks like an integration problem, your snippet looks OK. What is the HTML around that code snippet ?

**Comment by sdrebel** [comment]
@alexandrudima, HTML is surrounded by a modal popup. We are using grapesjs framework and our application is built on react.

**Comment by sdrebel** [comment]
I have tried with 'react-monaco-editor' also. This issue is only when I add language option. Else there is no issue at all.

**Comment by alexandrudima** [comment]
@sdrebel Without a reproducible sample, I cannot really help. The only thing I can say for sure is that web workers are misconfigured. Do you define the worker paths correctly? Have you seen all the samples at https://github.com/microsoft/monaco-editor-samples ?

**Comment by alexdima** [comment]
Have you seen https://github.com/microsoft/monaco-editor/issues/1385 ?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
