### ISSUE TITLE
Context Menu triggers editor scrolling

### ISSUE THREAD

**Issue by rebornix** [microsoft/monaco-editor#1692]
**monaco-editor version:** 0.18.1
**Browser:** Chrome
**OS:**  macOS

![contextmenu](https://user-images.githubusercontent.com/876920/70194732-4d022080-16b8-11ea-83f2-89004ba12a57.gif)

**Comment by nrayburn-tech** [comment]
I don't think this is still occurring, but it is possible I am testing it incorrectly.

![scrolling](https://user-images.githubusercontent.com/52075362/77832771-6404cc80-7106-11ea-83d2-293d56623b54.gif)

**Comment by sbatten** [comment]
@rebornix to verify that this is fixed in latest release
