### ISSUE TITLE
memory leakage

### ISSUE THREAD

**Issue by yangyangyihao** [microsoft/monaco-editor#1693]
Creating Monaco constantly will cause memory leakage. With editor. Dispose(), the memory is still not released. What should I do

**Comment by alexandrudima** [comment]
@yangyangyihao Can you please provide a self-contained HTML page which demonstrates the memory leak?

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!
