### ISSUE TITLE
set Editable Range

### ISSUE THREAD

**Issue by pradeepmdk** [microsoft/monaco-editor#1694]
I want to editable range for the Specific area. that area  only programmer must be write the code. In newer version not able to find the set edit range. is there any another method is available or how can be achieve this one?

**Comment by rcjsuen** [comment]
See #874, #953, #1056, and their many duplicates.

**Comment by alexandrudima** [comment]
This used to be a feature supported by the Monaco Editor, but it is no longer supported and there are no plans to bring it back.

We were not using editable ranges and found the burden of maintaining that too high, especially as we reimplemented the text buffer -- code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation

**Comment by alexandrudima** [comment]
Let's continue tracking the feature request in #953
