### ISSUE TITLE
Show an Image on Hover

### ISSUE THREAD

**Issue by tomenden** [microsoft/monaco-editor#1700]
According to [the docs](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.hover.html#contents), monaco-editor's HoverProvider supports Markdown. Is there a way for it to display an image? I tried this in the playground (based on the [HoverProvider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example)) and it doesn't work:

```js

monaco.languages.register({ id: 'mySpecialLanguage' });

monaco.languages.registerHoverProvider('mySpecialLanguage', {
    provideHover: function (model, position) {
        return xhr('../playground.html').then(function (res) {
            return {
                range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
                contents: [
                    { value: '<img src="https://www.sciencemag.org/sites/default/files/styles/inline__450w__no_aspect/public/dogs_1280p_0.jpg?itok=4t_1_fSJ"/>', isTrusted: true }
                ]
            }
        });
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: '\n\nHover over this text',
    language: 'mySpecialLanguage'
});

function xhr(url) {
    var req = null;
    return new Promise(function (c, e) {
        req = new XMLHttpRequest();
        req.onreadystatechange = function () {
            if (req._canceled) { return; }

            if (req.readyState === 4) {
                if ((req.status >= 200 && req.status < 300) || req.status === 1223) {
                    c(req);
                } else {
                    e(req);
                }
                req.onreadystatechange = function () { };
            }
        };

        req.open("GET", url, true);
        req.responseType = "";

        req.send(null);
    }, function () {
        req._canceled = true;
        req.abort();
    });
}
```

It just displays the content as a string

**Comment by vasiltabakov** [comment]
You could base64 encode the image:
```typescript
const pictureMarkDown= `![monaco-img-preview](data:image/png;base64,${base64})`;
...
contents: [
    { value: pictureMarkDown, isTrusted: true}
]
```

You could also try an URL with `isTrusted: true`, not sure if it would work tho.

**Comment by alexandrudima** [comment]
@tomenden This is possible, but you must use markdown syntax to do so, e.g.:

```js
monaco.languages.register({ id: 'mySpecialLanguage' });

monaco.languages.registerHoverProvider('mySpecialLanguage', {
    provideHover: function (model, position) {
        return {
            range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
            contents: [
                { value: '![monaco-img-preview](https://www.sciencemag.org/sites/default/files/styles/inline__450w__no_aspect/public/dogs_1280p_0.jpg?itok=4t_1_fSJ)', isTrusted: true }
            ]
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: '\n\nHover over this text',
    language: 'mySpecialLanguage'
});
```

![image](https://user-images.githubusercontent.com/5047891/70523996-861d1380-1b44-11ea-8a0d-2b28ed8b1acc.png)

**Comment by tomenden** [comment]
Thank you very much! @alexdima @vasiltabakov 
Is the monaco markdown format documented somewhere?

**Comment by vasiltabakov** [comment]
Under the hood the following JS lib is used:
https://github.com/markedjs/marked

For more details you can explore the `renderMarkdown` function (https://github.com/microsoft/vscode/blob/a868166d9ece2af3be2579ce5c873117790db87b/src/vs/base/browser/markdownRenderer.ts). You will find that the raw markdown string is parsed with `marked` but then sanitized via `insane` (https://github.com/bevacqua/insane).

So I would say you provide any "standard markdown" (not sure even if a lot of dialects exist in the first place), but then the resulting HTML is sanitized in specific ways.

You might noticed that in the Marked Options `sanitize` is always forced to 'true' which would explain your `<img...` code not working as no default sanitizer is passed to the options.
