### ISSUE TITLE
CompletionItem  documentation MarkdownString support command arguments

### ISSUE THREAD

**Issue by zhengjiaqi** [microsoft/monaco-editor#1704]
**monaco-editor version:** 0.18.1

    [Run it](command:myCommandId)

Does it support args? like use the query-part of the uri in VScode?

I tried

         monaco.languages.registerCompletionItemProvider('javascript', {
             triggerCharacters: ['.'],
             provideCompletionItems(model, position) {
                 const params = encodeURIComponent(JSON.stringify({ a: true }));
                 return {
                     suggestions: [{
                           insertText: 'text',
                           documentation: {
                                isTrusted: true,
                                value: `[Run it](command:vs.editor.ICodeEditor:1:doc?${params})`
                           },
                     }]
                };
            }
        });

and

    monaco.languages.registerCompletionItemProvider('javascript', {
             triggerCharacters: ['.'],
             provideCompletionItems(model, position) {
                 const args = [{ a: 1 }];
                 const stageCommandUri = monaco.Uri.parse(
                     `command:vs.editor.ICodeEditor:1:doc?${encodeURIComponent(JSON.stringify(args))}`
                );
                 return {
                     suggestions: [{
                           insertText: 'text',
                           documentation: {
                                isTrusted: true,
                                value: `[Run it](${stageCommandUri})`
                           },
                     }]
                };
            }
        });

then I addAction, but I can't get the parameters

    editor.addAction({
         id: 'doc',
         label: 'doc',
         run: function (params, params2, params3) {
            console.log('###params:', params, params2, params3);
            // print `editor, undefined, undefined`
         }
    });

But in VScode we can get the parameters with query-part .
[https://code.visualstudio.com/api/extension-guides/command](https://code.visualstudio.com/api/extension-guides/command)

<img width="769" alt="屏幕快照 2019-12-14 下午2 20 21" src="https://user-images.githubusercontent.com/9691438/70844536-64da6100-1e7d-11ea-91cb-333f0ca0b2d9.png">
<img width="775" alt="屏幕快照 2019-12-14 下午2 20 27" src="https://user-images.githubusercontent.com/9691438/70844540-8dfaf180-1e7d-11ea-96e9-d120d9e04214.png">

How could I get the parameters with command ? Please help me.

**Comment by alexdima** [comment]
@zhengjiaqi I am slightly confused by your example. In the `vscode` API you show the usage of commands in hovers. But in monaco API you are using the completion item provider.

Have you tried using a command with args in the completion item provider in `vscode`?

**Comment by zhengjiaqi** [comment]
> @zhengjiaqi I am slightly confused by your example. In the `vscode` API you show the usage of commands in hovers. But in monaco API you are using the completion item provider.
> 
> Have you tried using a command with args in the completion item provider in `vscode`?

@alexdima I do tried using a command with args in the completion item provider in `vscode` like is :

    class TestProvider implements vscode.CompletionItemProvider {

      constructor() { }

      provideCompletionItems (document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken): Thenable<vscode.CompletionItem[]> {
        return new Promise((resolve, reject) => {
            const item = new vscode.CompletionItem('doc', vscode.CompletionItemKind.Snippet);
            const args = [{ a: true }];
            const stageCommandUri = vscode.Uri.parse(
              `command:doc?${encodeURIComponent(JSON.stringify(args))}`
	   );
            const contents = new vscode.MarkdownString(`[Run it](${stageCommandUri})`);
            contents.isTrusted = true;
            item.documentation = contents;
            item.insertText = 'doc-test';
            return resolve([item]);
        });
      }
    }

    let provider = new TestProvider();
    vscode.languages.registerCompletionItemProvider('javascript', provider);

    let disposable = vscode.commands.registerTextEditorCommand('doc', (textEditor, edit, params3) => {
       console.log('###params3:', params3)
       // print `{a: true}`
    });
    context.subscriptions.push(disposable);

and I can get params3 with `{a: true}`.  
The point is how can I do the same thing in monaco. It is important to me, please help me. 
Thanks.

**Comment by alexdima** [comment]
Unfortunately I am not the developer that wrote that and I lack the expertise to help you, sorry about that.

**Comment by zhengjiaqi** [comment]
@alexdima I have found a way to support command arguments in CompletionItem documentation MarkdownString, this is my [PR](https://github.com/microsoft/vscode/pull/87677), I really hope monaco can support this useful feature.
Thanks.
