### ISSUE TITLE
Is there a way to disable numberlines and minimap?

### ISSUE THREAD

**Issue by SadafKhurramIBM** [microsoft/monaco-editor#1712]

**Comment by rcjsuen** [comment]
@SadafKhurramIBM You can disable them by configuring your editor's options. Try running the following code in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options).
```JavaScript
monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript",
    minimap: {
        enabled: false
    },
    lineNumbers: "off",
});
```
