### ISSUE TITLE
Can not create two editor with different theme

### ISSUE THREAD

**Issue by WangYuLue** [microsoft/monaco-editor#1713]
**monaco-editor version:** 0.14.2 & 0.18.1
**Browser: chrome 69**
**OS: macOS Mojave 10.14**
**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
        theme: 'vs-light',
	language: "javascript"
});


monaco.editor.create(document.getElementById("container1"), {
	value: "function hello() {\n\talert('Hello Monaco!');\n}",
        theme: 'vs-dark',
	language: "javascript"
});
```

```html
<div id="container" style="height:30%;"></div>
<hr>
<div id="container1" style="height:30%;"></div>
```

![屏幕快照 2019-12-18 下午7 45 58](https://user-images.githubusercontent.com/19245919/71083932-160b2f00-21cf-11ea-85cb-2976c9961ad6.png)

I set dark theme and light theme, but all show dark theme

**Comment by yunliang-ding** [comment]
You can try..
const ed1 = monaco.editor
const ed2 = monaco.editor  // Other monaco
ed1.create(...)
ed2.create(...)

**Comment by shmish111** [comment]
I can report the same thing, @yunliang-ding your solution didn't seem to work. In my case I am actually calling `create` at two different times:
```javascript
exports.create_ = function (monaco, nodeId, languageId, themeName) {
  console.log(nodeId);
  console.log(languageId);
  console.log(themeName);
  const editor = monaco.editor.create(nodeId, {
    value: [
      'Close'
    ].join('\n'),
    language: languageId,
    theme: themeName,
  });
  return editor;
}
```
Note here that `monaco` references the same object coming from webpack entry point:
```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
global.monaco = monaco;
```
This is a real issue for me now 😢

**Comment by shmish111** [comment]
Also note that all other things that depend on `languageId` seem to work just fine (TokensProvider, DocumentFormattingEditProvider etc). For example, for one of the editors I provide a DocumentFormattingEditProvider but for the other I do not. If I press f1 on each editor then only 1 has access to "Format Document" as expected.

**Comment by shmish111** [comment]
Ah, I discovered that `setTheme` exists but it is a global thing: https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#settheme

so this issue then is a feature request to move `setTheme` to https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html or some other way of achieving the same thing.

**Comment by bodinsamuel** [comment]
+1 on this, could be cool (not critical though)

**Comment by 10229428** [comment]
+1 on this, has any solution?

**Comment by shmish111** [comment]
I've been changing the theme every time I switch, not ideal though and it only works for me since I never have 2 editors on screen at the same time

**Comment by zuiidea** [comment]
+1 on this

**Comment by SPERONIS** [comment]
+1 on this

**Comment by fomenyesu** [comment]
+1 on this

**Comment by 14glwu** [comment]
the same problem, how to solve?

**Comment by Oleksandr-Silin** [comment]
Is it planned to be fixed?

**Comment by joaohenrifranco** [comment]
Have you guys found any workarounds?

**Comment by keyon17** [comment]
how to solve?

**Comment by praylee** [comment]
I am also here to look for solutions. Didn't work for me at v0.36.1. Any solutions?

**Comment by zerobytes** [comment]
This is related.
https://github.com/Microsoft/monaco-editor/issues/338#issuecomment-1553847664
