### ISSUE TITLE
is it possible to load monaco within a VSCode Extension?

### ISSUE THREAD

**Issue by shanejonas** [microsoft/monaco-editor#1714]
I'm using the monaco-editor-webpack-plugin to load monaco within a `vscode` extension, but I'm running into an error around the webworkers when it loads the json language:

```
Uncaught ReferenceError: importScripts is not defined
```

![image](https://user-images.githubusercontent.com/364566/71124102-007b1280-2199-11ea-92bd-437e470a85ba.png)

is just not supported?

**Comment by rebornix** [comment]
AFAIK, Webview doesn't allow web workers being loaded. Please continue the discussion in the VS Code issue you created, thanks!

**Comment by shanejonas** [comment]
shouldn’t it fall back to something? for example the json one shouldn’t be able to fall back?
