### ISSUE TITLE
Use vscode-html-languageservice options to allow custom elements

### ISSUE THREAD

**Issue by bioub** [microsoft/monaco-editor#1723]
I'm thinking of the easiest way to supports collections of custom elements.

`vscode-html-languageservice` offers the ability to register custom tags and attributes here : 
https://github.com/Microsoft/vscode-html-languageservice/blob/62efc4b0768640e0c1f5f67974205e0c4abbfaf7/src/htmlLanguageService.ts#L46

What would you think about adding and option to `htmlDefaults` like this ?

```js
monaco.languages.html.htmlDefaults.setOptions({
  customTags: {
    'staytuned-player': {
      label: 'Staytuned.io podcast player',
      attributes: ['src', 'fixed'],
    },
  },
});
```

Tell me if you'd like me to do the PR.

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/monaco-editor/issues/2284

I added new API to allow configuring the HTML and CSS language supports with custom data. 
See https://github.com/microsoft/monaco-editor/issues/2284#issuecomment-858872212 for details.
