### ISSUE TITLE
undo, redo doesn't work

### ISSUE THREAD

**Issue by iWun** [microsoft/monaco-editor#1724]
**monaco-editor version:** 0.17.1
**Browser:chrome 
**OS:mac
**Playground code that reproduces the issue:**

To perform undo/redo operation , I call
```js
 editor.trigger('whatever...', 'undo')
 editor.trigger('whatever...', 'redo')
```
but it doesn' work for me.
By the way ,Cmd+z Cmd+Shift+z works.

**Comment by alexdima** [comment]
@iWun Can you please provide a full sample that we can paste at https://microsoft.github.io/monaco-editor/playground.html

**Comment by iWun** [comment]
I fixed it.
A colleague accidentally made a mistake
