### ISSUE TITLE
Angular project build error

### ISSUE THREAD

**Issue by blueiceprj** [microsoft/monaco-editor#1727]
**monaco-editor version:** 0.19.0
**Browser:** Chrome
**OS:** MACOS
**Playground code that reproduces the issue:**

ERROR in node_modules/monaco-editor/monaco.d.ts:50:13 - error TS1086: An accessor cannot be declared in an ambient context.

50         get token(): CancellationToken;
               ~~~~~
node_modules/monaco-editor/monaco.d.ts:125:13 - error TS1086: An accessor cannot be declared in an ambient context.

125         get fsPath(): string;
                ~~~~~~

```js
```

**Comment by alexdima** [comment]
This works fine for me. Do you perhaps use an older TS version? In VS Code we use 3.7.2

**Comment by blueiceprj** [comment]
Thank you for your answer. Angular using typescript 3.5.3 version.
