### ISSUE TITLE
nls error on reload page - from time to time - vers 0.19.0

### ISSUE THREAD

**Issue by cintaccs** [microsoft/monaco-editor#1728]
<img width="1301" alt="Screenshot 2019-12-22 at 07 12 05" src="https://user-images.githubusercontent.com/4300051/71318007-a923bd80-248a-11ea-81d6-22b19b331fac.png">

Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
Windows 10 Pro: 1909

Doesn't always occur - but on many fast reloads - running in Webpack debug mode.

```
nls.js:47 Uncaught TypeError: Cannot read property 'replace' of undefined
    at n (nls.js:47)
    at Object.localize (nls.js:85)
    at folding.ts:869
    at Function.t._invokeFactory (loader.js:1036)
    at t.complete (loader.js:1046)
    at s._onModuleComplete (loader.js:1660)
    at s._onModuleComplete (loader.js:1666)
    at s._onModuleComplete (loader.js:1666)
    at s._resolve (loader.js:1578)
    at s.defineModule (loader.js:1266)
```

BTW: pretty cool with all the closed issues and fixes! Well done! :-)

**Comment by cintaccs** [comment]
<img width="1289" alt="Screenshot 2019-12-22 at 07 26 55" src="https://user-images.githubusercontent.com/4300051/71318105-737fd400-248c-11ea-8ac5-7c8b23c75a1b.png">

**Comment by alexdima** [comment]
@cintaccs The first stack trace leads to here -- https://github.com/microsoft/vscode/blob/7400168b53411a48ec345218e765c83e1a97b6b8/src/vs/editor/contrib/folding/folding.ts#L876 -- but that one calls `nls.localize` with a defined string. I wonder if you have done something custom around `nls` that might lead to a timing error where your nls strings are not ready sometimes?

**Comment by cintaccs** [comment]
```

**Comment by alexdima** [comment]
From your snippet, it appears you are loading things very much like in this simple sample -- https://github.com/microsoft/monaco-editor-samples/blob/master/browser-amd-editor/index.html

I have executed that repeatedly/reloaded repeatedly and cannot reproduce any exception. The only explanation I have is that somehow the editor installation is corrupt, or that an older version of `editor.main.nls.js` is loaded with a newer version of `editor.main.js`. I have seen this happen when the server is written incorrectly and the browser caches the files indefinitely, so it might fetch `editor.main.js` from `monaco-editor@0.19.0` and `editor.main.nls.js` from cache at `monaco-editor@0.18.1` or something like that...

**Comment by cintaccs** [comment]
@alexdima - sure! Thanks a lot for the feedback! will do and let you know!

**Comment by cintaccs** [comment]
@alexdima : Cleared all cache - upgraded from 18.1 to 19.2. Now I get when loading a CSS editor:

<img width="1164" alt="Screenshot 2020-01-06 at 17 00 14" src="https://user-images.githubusercontent.com/4300051/71830014-1861fa00-30a6-11ea-9a9c-3ff1f1f026c4.png">

and after that - a page reload gives:

<img width="1166" alt="Screenshot 2020-01-06 at 17 01 12" src="https://user-images.githubusercontent.com/4300051/71830048-2adc3380-30a6-11ea-9b04-fb481dcbccf6.png">

a Ctrl Refresh (on latest Chrome) gets rid of the nls error.

Loading the CSS editor - brings back the "completionItems" error. And a normal Page reload will then bring back the nls error again.

Not sure whether it is related - but loading a SQL mode editor in the same context seems to work...??

**Comment by cintaccs** [comment]
it also appears to have an issue when in HTML mode:

<img width="1160" alt="Screenshot 2020-01-06 at 17 11 23" src="https://user-images.githubusercontent.com/4300051/71830701-95da3a00-30a7-11ea-9978-71d059cb06d0.png">

FYI: I am using CSS, HTML, SQL modes from the same initial loader in a SPA.

**Comment by cintaccs** [comment]
what is super weird - I can reload the page many times without the nls error - and then suddenly it comes back again.

**Comment by cintaccs** [comment]
<img width="607" alt="Screenshot 2020-01-06 at 17 38 55" src="https://user-images.githubusercontent.com/4300051/71832538-6decd580-30ab-11ea-8d66-74c555816ba1.png">

FYI - I only "copy" these folders from the npm node-modules into the application.

**Comment by alexdima** [comment]
@cintaccs The stack traces you have are just not possible and again indicative of mixin files from two distinct editor versions.

Let's take the stack you have in `htmlMode.ts`, in the `setupMode` function.

* `Cannot read property 'completionItems' of undefined`
* The line of the error is here -- https://github.com/microsoft/monaco-html/blob/c4d683af71ad4d61b58fc67c839d889e3078f95a/src/htmlMode.ts#L63
* The `undefined` variable must be `modeConfiguration`, which comes from `defaults.modeConfiguration`.
* `defaults` is an argument passed in to `setupMode`
* The `setupMode` is called here and always with defaults which contain the field `modeConfiguration` -- https://github.com/microsoft/monaco-html/blob/c4d683af71ad4d61b58fc67c839d889e3078f95a/src/monaco.contribution.ts#L125-L133


The property `modeConfiguration` has been recently added, see https://github.com/microsoft/monaco-html/blame/master/src/monaco.contribution.ts#L18 .
This finally 100% convinces me that you have mixed up files, i.e. `editor.main.js` from a certain editor version, and `htmlMode.js` from a newer editor version. 

Please do the following:
1. delete all the contents of `min`, `min-maps` or anything you have in your project regarding the monaco editor.
2. download again and unpack the editor files
3. clear your caches or reconfigure your server to do correct caching

I am sorry, at this point I am 100% convinced you are loading an older version of `vs/editor/editor.main.js` with a newer version of `vs/language/html/htmlMode.js`. Please open those files in the dev tools and look at their headers. Do they look like this:

* `editor.main.js`:
```
/*!-----------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Version: 0.19.2(6dc59eb294d3df102203e7a04fde6f032157ff51)
 * Released under the MIT license
 * https://github.com/Microsoft/vscode/blob/master/LICENSE.txt
 *-----------------------------------------------------------*/
```

* `htmlMode.js`:
```
/*!-----------------------------------------------------------------------------
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * monaco-html version: 2.6.0(c4d683af71ad4d61b58fc67c839d889e3078f95a)
 * Released under the MIT license
 * https://github.com/Microsoft/monaco-html/blob/master/LICENSE.md
 *-----------------------------------------------------------------------------*/
```

**Comment by cintaccs** [comment]
@alexdima Hi again - and thanks a lot for looking into this!! I really appreciate it!
I have now reset my browser cache and all related web data again + removed my monaco "copy" from npm node_modules + made a new fresh copy after checking that the package-lock.json and package.json is indeed 19.2. During my various checking I see the following:

**Comment by cintaccs** [comment]
the workers are having 2 different versions:

<img width="1058" alt="Screenshot 2020-01-07 at 12 30 02" src="https://user-images.githubusercontent.com/4300051/71892544-7a277000-3149-11ea-8be7-40ed0852c3a0.png">
<img width="1129" alt="Screenshot 2020-01-07 at 12 29 50" src="https://user-images.githubusercontent.com/4300051/71892550-7eec2400-3149-11ea-9650-e3b4788b184b.png">

I don't think I am loading any of that in "my" part of the code - but i will double check again.

**Comment by cintaccs** [comment]
btw: I tried to remove the esm and dev folders from the monaco-editor folder. Currently and in the results above I have them in (the monaco-editor folder I "serve" = the node_modules/monaco-editor) I assume that these 2 folders are only needed for development versions of monaco-editor and not needed during production builds. However when removing them (leaving min and min-maps in the folder) I began to see the nls error again.

**Comment by alexdima** [comment]
Well, that is the problem. In your browser, on your machine, when loading your application, you have editor files loaded from mixed versions. If they look fine on disk, perhaps it is the browser cache that is broken, or your web server.

Have you tried reproducing on another browser, or with Chrome with a fresh user data profile? If the problem reproduces on another browser, then this is an issue with your files on disk or server implementation, which is probably serving different files than the ones you are editing. If you can reproduce in another browser, then install an HTTP proxy and look at the HTTP requests going from the browser to your server and check if your server is broken and responding with old content to new HTTP requests.

You can also try renaming the folder on disk to `monaco-editor-0.19.2` and load it from that path, that might help with caching problems.

I have to say, at this point, I am 99.99% convinced this is not a Monaco Editor issue and pursuing this here further is not helping our community.

Good luck to you!

**Comment by cintaccs** [comment]
Thanks for your help!
