### ISSUE TITLE
monaco-editor-core@0.19.0: broken typescript types

### ISSUE THREAD

**Issue by AviVahl** [microsoft/monaco-editor#1729]
New release of `monaco-editor-core` (0.19.0) has broken typescript types.
`monaco-editor` package appears to be fine.

Steps to reproduce:
```sh
mkdir monaco-test
cd monaco-test
yarn init -yp
yarn add typescript monaco-editor-core
yarn tsc --init
echo "import 'monaco-editor-core';" > a.ts
yarn tsc --noEmit
# see type errors
```

**monaco-editor-core version:** 0.19.0
**Browser:** irrelevant
**OS:** irrelevant

**Comment by rebornix** [comment]
Didn't see any error with 0.18.x
