### ISSUE TITLE
Immediate propagation of a keyboard event should be stopped

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#173]
Currently only the default behaviour is prevented for a keyboard event if a command is resolved. It is not enough. If there are other listeners for the same DOM node, they should not be invoked after a command execution, since it causes unexpected behaviour.

**Comment by alexandrudima** [comment]
I believe you can check this on your side via `e.defaultPrevented`

**Comment by akosyakov** [comment]
@alexandrudima if you are in the control of the code then yes, if it is done by 3rd party library it gets a bit difficult
