### ISSUE TITLE
How to get auto completion work with old and new keywords?

### ISSUE THREAD

**Issue by minm2015** [microsoft/monaco-editor#1739]
So my problem is that my auto completion doesn't work properly. It only works for the keywords I defined but not for the variables I declared or some other stuff which worked before my new registration. I want to get those auto completion combined with the new ones I registered worked. This is my code to register items for auto completion.

![image](https://user-images.githubusercontent.com/19508192/71575983-ed1d5f00-2b29-11ea-8e95-84d3bd13c528.png)

**Comment by yunliang-ding** [comment]
Maybe you can refer to  https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example  It might help you.

**Comment by rebornix** [comment]
@minm2015 can you provide more detailed information like examples of which parts don't work? I can' tell from the screenshot posted above.

**Comment by minm2015** [comment]
> @minm2015 can you provide more detailed information like examples of which parts don't work? I can' tell from the screenshot posted above.
Like him
https://stackoverflow.com/questions/59472082/how-to-get-auto-completion-work-with-old-and-new-keywords

**Comment by alexdima** [comment]
@minm2015 The monaco editor does not offer built-in support for python intellisense, you need to build it by yourself.

**Comment by minm2015** [comment]
> @minm2015 The monaco editor does not offer built-in support for python intellisense, you need to build it by yourself.

I created it myself, but it overrides the default prompt. How do I not override the default prompt

**Comment by minm2015** [comment]
> @minm2015 The monaco editor does not offer built-in support for python intellisense, you need to build it by yourself.
@alexdima 
I created it myself, but it overrides the default prompt. How do I not override the default prompt

**Comment by alexdima** [comment]
I think perhaps you mean that the word based completions no longer come up? If that's what you mean, I think you could simply compute the word suggestions by yourself. You can use `model.getValue()` and split in words, dedup uniques and offer them as word suggestions from your completion item provider.
