### ISSUE TITLE
Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/goToDefinition/goToDefinitionCommands'

### ISSUE THREAD

**Issue by wind-hx** [microsoft/monaco-editor#1740]
66 .  [20:10:10] Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/goToDefinition/goToDefinitionCommands'
67	[20:10:10] Require stack:
68	[20:10:10] - /root/workspace/test_ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.7.0@monaco-editor-webpack-plugin/index.js
69	[20:10:10] - /root/workspace/test_ems-user-web/build/webpack.base.conf.js
70	[20:10:10] - /root/workspace/test_ems-user-web/build/webpack.test.conf.js
71	[20:10:10] - /root/workspace/test_ems-user-web/build/build.js
72	[20:10:10]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
73	[20:10:10]     at Function.resolve (internal/modules/cjs/helpers.js:21:19)
74	[20:10:10]     at resolveMonacoPath (/root/workspace/test_ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.7.0@monaco-editor-webpack-plugin/index.js:21:18)
75	[20:10:10]     at /root/workspace/test_ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.7.0@monaco-editor-webpack-plugin/index.js:134:51
76	[20:10:10]     at Array.map (<anonymous>)
77	[20:10:10]     at createLoaderRules (/root/workspace/test_ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.7.0@monaco-editor-webpack-plugin/index.js:134:31)
78	[20:10:10]     at MonacoWebpackPlugin.apply (/root/workspace/test_ems-user-web/node_modules/_monaco-editor-webpack-plugin@1.7.0@monaco-editor-webpack-plugin/index.js:71:19)
79	[20:10:10]     at Compiler.apply (/root/workspace/test_ems-user-web/node_modules/_tapable@0.2.9@tapable/lib/Tapable.js:375:16)
80	[20:10:10]     at webpack (/root/workspace/test_ems-user-web/node_modules/_webpack@3.12.0@webpack/lib/webpack.js:33:19)
81	[20:10:10]     at /root/workspace/test_ems-user-web/build/build.js:24:3
82	[20:10:10]     at next (/root/workspace/test_ems-user-web/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:83:7)
83	[20:10:10]     at CB (/root/workspace/test_ems-user-web/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:119:9)
84	[20:10:10]     at /root/workspace/test_ems-user-web/node_modules/_rimraf@2.7.1@rimraf/rimraf.js:145:14
85	[20:10:10]     at FSReqCallback.oncomplete (fs.js:148:21)

**monaco-editor version:** 0.19.0
**Browser:** chrome
**OS:** macos
**Playground code that reproduces the issue:**

```js
npm run build:test
```

**Comment by rebornix** [comment]
This module is already removed and the contrib name is now `goToSymbol`.

**Comment by huntbao** [comment]
So how to fix this problem?
