### ISSUE TITLE
Removing the tooltip on the read-only editor that says 'cannot edit in read-only editor'

### ISSUE THREAD

**Issue by rakhtar92** [microsoft/monaco-editor#1742]
Hi,
I tried to remove the tooltip that says 'cannot edit in a read-only editor using CSS. But, it seems that the CSS although applied is not working.

Given below is the screenshot of the issue that I am facing:

![image](https://user-images.githubusercontent.com/20411595/71613806-64a4ca00-2bce-11ea-9e8e-e7912a33e2f6.png)

Below given is the editor options that I am setting

`value: this.configOriginal,
    language: 'json',
    theme: this.theme,
    scrollBeyondLastLine: false,
    contextmenu: false,
    readOnly: true,
    cursorWidth: 0,`

And given below is the CSS that I am trying to use to hide the tooltip:
`.monaco-alert {
  display: none !important;
  visibility: hidden !important;
}`

Can anyone please help me solve this? I have been struggling with this since a long time.

Thank you so much.

**Comment by kubocob** [comment]
It would be nice, if the message tooltip could be customisable. This could be used for explanation of the "custom" reason, why the editor is in read-only state: 
- "You need to save the file locally before editing"
- "Text is locked for editing"
- "You are previewing the previous version of the file"

**Comment by brijeshb42** [comment]
@kubocob Here is something that I tried and should work for your use case.

```js
const editor = /* your editor instance */;
const messageContribution = editor.getContribution('editor.contrib.messageController');
const diposable = editor.onDidAttemptReadOnlyEdit(() => {
  messageContribution.showMessage('Your reason to not allow editing.', editor.getPosition());
});
```

This code will immediately override the default `Cannot edit read-only editor` with your custom message.

**Comment by brijeshb42** [comment]
@rakhtar92 for your requirement, you can do this - 

```js
const editor = /* your editor instance */;
const messageContribution = editor.getContribution('editor.contrib.messageController');
const diposable = editor.onDidAttemptReadOnlyEdit(() => {
  messageContribution.closeMessage();
});
```

This will hide the tootltip immediately. There isn't even a flicker for a moment when closing the tooltip.

**Comment by rakhtar92** [comment]
@kubocob & @brijeshb42  thanks for the help but it did not work out.
The `editorr.getContribution()` returns of type `IEditorContribution` and I checked the d.ts file for monaco-editor there is no such method `closeMessage()` for `IEditorContribution`


![image](https://user-images.githubusercontent.com/20411595/74877169-fb9a3100-538a-11ea-8d21-9c3db528f59f.png)

![image](https://user-images.githubusercontent.com/20411595/74877086-d5749100-538a-11ea-8c80-f249dd3072bd.png)

**Comment by kubocob** [comment]
@rakhtar92 Yeah, typings are not complete also in my project (`"monaco-editor": "^0.18.1",` - could be fixed in `0.20.0`). Therefore I'm ignoring it for now, and retyping to`any`.

```typescript
(editor as any).onDidAttemptReadOnlyEdit(() => {
      (messageContribution as any).showMessage('Reason for blocked edit',  editor.getPosition());
});
```

**Comment by zeevmoney** [comment]
> @rakhtar92 for your requirement, you can do this -
> 
> ```js
> const editor = /* your editor instance */;
> const messageContribution = editor.getContribution('editor.contrib.messageController');
> const diposable = editor.onDidAttemptReadOnlyEdit(() => {
>   messageContribution.closeMessage();
> });
> ```
> 
> This will hide the tootltip immediately. There isn't even a flicker for a moment when closing the tooltip.

I was trying to remove the tooltip, this solution works but I see a flickering. If I override the msg with an empty string, like this:  ` (messageContribution as any).showMessage('',  editor.getPosition());`, it's a little better. 

Eventually this is what worked for me (without any flickering):

```typescript
const messageContribution = editor.getContribution(
  "editor.contrib.messageController"
);
editor.onDidAttemptReadOnlyEdit(() => {
  messageContribution.dispose();
});
```

**Comment by bsun94** [comment]
Is there a way to access the harness for the tooltip for unit tests?

**Comment by hediet** [comment]
With https://github.com/microsoft/vscode/commit/052f02175f4752c36024c18cfbca4e13403e10c3, you can just skip the `readOnlyMessage` contribution (in particular when using the webpack plugin) and provide your own.

This will be available in the next monaco editor release.

**Comment by makandre** [comment]
@hediet how do you skip the contribution?  I tried to find some documentation on that but couldn't.

As for other suggestions on this thread, somehow none of them worked for me: setting to empty string pops up an empty tooltip, using `closeMessage` has flicker, and using `dispose` actually causes the tooltip stay on the screen.

On the other hand, `.monaco-editor-overlaymessage { display: none !important; }` works and I'll use it as a workaround until I can find a proper solution.
