### ISSUE TITLE
Closing braces on the same line

### ISSUE THREAD

**Issue by Alim-El** [microsoft/monaco-editor#1743]
Is it possible to change folding style to something idea-like with closing braces on the same line as opening?

### **Expected:**
```javascript
function add(x, y) { ... }
```

![image](https://user-images.githubusercontent.com/43091114/71621989-02ef5a80-2be4-11ea-88ac-7f90120ada36.png)

### **Actual:**
```javascript
function add(x, y) { ... 
}
```

![image](https://user-images.githubusercontent.com/43091114/71621983-ece19a00-2be3-11ea-9212-3930009ece6f.png)

**Comment by Alim-El** [comment]
UP

**Comment by Alim-El** [comment]
@alexdima up

**Comment by hediet** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/3352
