### ISSUE TITLE
Theme color

### ISSUE THREAD

**Issue by yangyangyihao** [microsoft/monaco-editor#1744]
Hello, I want to know where your theme color is defined. How the color of the token keyword is defined. Because method name, class name and so on do not change color. I want them to change color

**Comment by rebornix** [comment]
@yangyangyihao could you please provide more info about what project you are working on, what language it is and what you attempt to do. With more context we can know what's going on there.

**Comment by yangyangyihao** [comment]
I want to implement a function to provide highlight color for JavaScript method.For example, 'function onclick() {}'
I want 'onlick' to change color.
I'm sorry my English is not very good.
Thank you very much

**Comment by alexdima** [comment]
@yangyangyihao Here is an example -- https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

Specifically, this is the tokenizer:

```
monaco.languages.setMonarchTokensProvider('mySpecialLanguage', {
	tokenizer: {
		root: [
			[/\[error.*/, "custom-error"],
			[/\[notice.*/, "custom-notice"],
			[/\[info.*/, "custom-info"],
			[/\[[a-zA-Z 0-9:]+\]/, "custom-date"],
		]
	}
});
```

There is a special playground to help you develop a tokenizer -- https://microsoft.github.io/monaco-editor/monarch.html

**Comment by yangyangyihao** [comment]
Thank you very much. I signed up for a new language at your suggestion, but I want a feature like JavaScript. For example, AAA. Can prompt all variables of the current page. Let me give you a specific example. "Let some ='11 '; function hello() {}; KKK." I know that "KKK" is a wrong use, but at this time I will prompt "some and hello" as input AIDS. I want to know how this is implemented in JavaScript. It seems that JavaScript relies on typescript to implement functions. But I didn't find out how to implement it.


My English is not very good, please forgive me a lot

**Comment by yangyangyihao** [comment]
If I want to register a language but I want it to have the same input assist as JavaScript. What should I do? For an array type, when I press'. ', I will be prompted with ['splice', 'length'...]

Thank you very much for your reply

**Comment by alexdima** [comment]
@yangyangyihao You can use `monaco-editor-core` instead of `monaco-editor` (it is the editor without any language defined).

Then, you can fork the `monaco-typescript` project and modify it to work like you wish.

Finally, you can put it back together using the scripts in this repository (specifically the `metadata.js` file at the root of the repository) and create your custom variant of the monaco editor with your custom variant of the monaco typescript plugin.

**Comment by yangyangyihao** [comment]
Thank you very much. Now I want to simply support Java. We support that if we input some words before and then input again, there will be input friendly prompt. But when I use the registercompletionitemprovider API, I won't be able to give a friendly hint of the words I've written. It's strange that this problem doesn't exist in JS.


Finally, I hope that I can use the registercompletionitemprovider to add the content that needs to be prompted, and input the auxiliary prompts for the words that have been written.How should I achieve it
