### ISSUE TITLE
addAction not working after v0.6 (context menu)

### ISSUE THREAD

**Issue by AndersMad** [Microsoft/monaco-editor#175]
Goto https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance

Right click an identifier or keyword as the sample suggest: **The action is missing in the context menu**.

Pressing CTRL + F10 does work / executes the action.

Also: How to place the action after the `contextMenuGroupId` has been removed? Before I would `contextMenuGroupId: "4_tools"`.

**Comment by alexandrudima** [comment]
Yep, that got lost with the menu work we did in vscode. We need to figure out how to bring it back. Sorry about it!
