### ISSUE TITLE
Incomplete IndentGuides display

### ISSUE THREAD

**Issue by pengxiaotian** [microsoft/monaco-editor#1750]
**monaco-editor version:** 0.19.0
**Browser:** Google
**OS:** win10
**Playground code that reproduces the issue:**

I'm fine on the playground, but not in my vue project.
Only the first column has IndentGuides.

![image](https://user-images.githubusercontent.com/27847994/71725960-9937b080-2e70-11ea-8540-23d30b8c5434.png)

There is really only one node in html.
![image](https://user-images.githubusercontent.com/27847994/71726172-3f83b600-2e71-11ea-960a-67dc69788472.png)

```js
import * as monaco from 'monaco-editor';

const arr = [
  {
    "value": "",
    "url": ""
  }
]

export default {
 mounted() {
    this.$nextTick(() => {
      this.editor = monaco.editor.create(this.$el, {
         value: JSON.stringify(arr, null, 2),
	 language: "json",
         theme: 'vs-dark',
      });
    });
  },
}

```

**Comment by rebornix** [comment]
@pengxiaotian can you share where you play around with your Vue project and how it's being setup? I'd like to have it reproduced locally first.

**Comment by alexdima** [comment]
I also cannot reproduce given the provided code snippet.

```js
const arr = [
  {
    "value": "",
    "url": ""
  }
]

monaco.editor.create(document.getElementById("container"), {
	value: JSON.stringify(arr, null, 2),
	language: "json",
    theme: 'vs-dark'
});
```

I have pasted and ran at https://microsoft.github.io/monaco-editor/playground.html and it looks fine for me:
![image](https://user-images.githubusercontent.com/5047891/71818559-aa0f3e80-3089-11ea-989d-a40cdefd4289.png)

**Comment by pengxiaotian** [comment]
I found the reason. The code I gave earlier is incorrect. If the default value is a string, eg: "[]"
```js

const arr = [
  {
    "value": "",
    "url": ""
  }
]

 this.editor = monaco.editor.create(this.$el, {
         value: "[]",
	 language: "json",
         theme: 'vs-dark',
      });

this.editor.setValue(JSON.stringify(arr, null, 2));

```

**Comment by alexdima** [comment]
That has to do with indentation settings.

When creating the editor with the value `[]`, the string `[]` has no indentation, so the editor cannot guess what your indentation is. It falls back to the default settings, `tabSize: 4, insertSpaces: true`. So an indent guide is rendered every 4 spaces.

You can define this explicitly via `tabSize: 2`, e.g.:

```
const arr = [
    {
        "value": "",
        "url": ""
    }
]

let editor = monaco.editor.create(document.getElementById("container"), {
    tabSize: 2,
    value: "[]",
    language: "json",
    theme: 'vs-dark',
});

editor.setValue(JSON.stringify(arr, null, 2));
```

**Comment by pengxiaotian** [comment]
thank you very much.
