### ISSUE TITLE
vue project build error

### ISSUE THREAD

**Issue by layzynice** [microsoft/monaco-editor#1758]
vue project  developemnt is ok , after build  is error

![微信图片_20200109112458](https://user-images.githubusercontent.com/30991649/72038987-547f9f80-32de-11ea-83cb-481f0b8f4e0c.jpg)

**monaco-editor version:** 0.19.2
**Browser:** chrome
**OS:**
**Playground code that reproduces the issue:**

```js
```

**Comment by alexdima** [comment]
We do not accept issues in this format.
