### ISSUE TITLE
the `tabFocusMode` option/config removed in v0.6

### ISSUE THREAD

**Issue by AndersMad** [Microsoft/monaco-editor#176]
How to set this >= v0.6?

It can still be toggled from the commands pallet / CTRL + M - but I need it as default on for many scenarios.

It is a very handy option for small snippets of text/code in a form. I am queries to why this handy option was removed (no notes in the commits or changelog)? Hope to see it back or an alternative :)

Read only mode will make this true by default.

**Comment by alexandrudima** [comment]
The `tabFocusMode` was an option driving the context key `editorTabMovesFocus` used basically by the `tab` and `shift+tab` keybindings. You can emulate this on your side via `editor.createContextKey('editorTabMovesFocus', true)`

**Comment by AndersMad** [comment]
thanks - works after setting it very late in the init/create process.. old option was more elegant though :) i see that it was moved to `InternalEditorOptions` for some reason

**Comment by AndersMad** [comment]
**FYI v1.8.x**: it seems like `tabFocusMode` is back again and the above should be disregarded (as it does not work)
