### ISSUE TITLE
Support for loading in NWJS with --enable-node-worker

### ISSUE THREAD

**Issue by mploscos** [microsoft/monaco-editor#1760]
Hello.

I have modified the package.json file in the [example](https://github.com/microsoft/monaco-editor-samples/tree/master/nwjs-amd) so that the workers run in the context of nodejs. I need this change because I have other workers that handle datagram sockets (dgram lib).

Is it possible to load Monaco Editor with this option in nwjs?

Thanks in advance.

**Comment by mploscos** [comment]
package.json content:

{
  **"chromium-args": "--enable-node-worker",**
  "main": "index.html",
  "name": "MW",
  "nodejs": true,
  "window": {
    "position": "center"
  }
}

**Comment by mploscos** [comment]
I tried it and it seems to work but the worker who checks the language does not load.

**Comment by djmisterjon** [comment]
@alexdima 
https://github.com/suren-atoyan/monaco-react/issues/115#issuecomment-701270893
it would have saved me a serious headache, it would be a good idea to add it to the doc !
Also in the demo doc, it say `nwjs-amd` not work but `nwjs-amd-v2` work.
for me it's the opposite,  `nwjs-amd` work , and `nwjs-amd-v2` not work.
thanks for all your work guys.

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
