### ISSUE TITLE
with monaco-languageclient v0.10.2, the monaco-editor v0.19.2 throws error in dev console 

### ISSUE THREAD

**Issue by OliverwengFiltered** [microsoft/monaco-editor#1763]
with monaco-languageclient v0.10.2, the monaco-editor throws error in dev console.

To reproduce, you have to have a language server connection built based on `monaco-languageclient`
basically, the error happens when you try to connect with a language server.

it's not happening in monaco-editor version 0.17.1

Wondering if anyone has any insight around it.

![Screen Shot 2020-01-13 at 5 35 11 PM](https://user-images.githubusercontent.com/28814939/72297975-127e9280-362b-11ea-8cbf-8aa8eed4d468.png)

**Comment by rcjsuen** [comment]
@OliverwengFiltered Generally speaking `monaco-languageclient` has to move in lock step with `monaco-editor`. 0.19.x is not supported at the moment. See TypeFox/monaco-languageclient#194.

**Comment by OliverwengFiltered** [comment]
@rcjsuen 

I see, thank you.

**Comment by alexdima** [comment]
Closing in favor of https://github.com/TypeFox/monaco-languageclient/issues/194
