### ISSUE TITLE
Not able to suppress the suggestwidget on autoCompletion call

### ISSUE THREAD

**Issue by sumkumsum** [microsoft/monaco-editor#1764]
**monaco-editor version:** 0.15.6
**Browser:** Chrome
**OS:** Windows

**Issue Description:**

There is no option to suppress the suggest widget.

I have implemented auto suggestion in monaco editor and using ajax call to show data in suggest widget.

What I want is on opening of monaco editor I want to send dummy call at the backend so that I can do some processing at backend and don't want to show suggest widget on front end.

But If I am sending a dummy request then it shows the suggestwidget with "No Suggestion".

**Expectation:**

Suggest widget should not be shown for these cases.

**Observation:**

Suggest widget is visible where I don't want it to show. And There is no point to customize that. User has to explicitly press escape key to continue working on editor.

**Note:** If I am sending same request on press of ";" char, then window is not shown. But in both cases that is onLoad or ";" press I am returning emty ([]) suggestion from backend.

**Code for reference:**
```

private triggerCharactersArray = ['.', ';', '/', '{', '}', '(', ')']; 

this._registerCompletionItemProviderRef = languages.registerCompletionItemProvider("java", {
            triggerCharacters: this.triggerCharactersArray, /** Triggering character to invoke auto completion */
            provideCompletionItems: function (model, position) {
                return this.getAutoCompleteData(model, position).then(function (res) {
                    /** Get completion response from websocket */
                    let completionListSuggestion = getCompletionList(res ? JSON.parse(res) : null);

                    /** Return suggestion list to GUI */
                    return {
                        incomplete: true, // So that autocompletion request is sent on every char
                        suggestions: completionListSuggestion.map(item => ({ ...item }))
                    };
                }.bind(this));
            }.bind(this)
        });


getAutoCompleteData(model, position) {
        return new Promise(function (resolve, reject) {
            this._autocompleteWSSubscr = this._wsObject.subscribe(
                data => {
                    resolve(data);
                },
                error => {
                    console.log('Error in autocomplete recieved from WS :' + JSON.stringify(error));
                    reject(error);
                }
            );

            this.sendAutoCompletionData(model, position);

        }.bind(this));
    }

sendAutoCompletionData(model, position) {

<Logic to send token and position to the websocket>

}

getCompletionList(data) {
    const completionItemList: CompletionItem[] = [];
    // parse the data and load completion list
     return completionItemList;
}


```

@alexdima

**Comment by alexdima** [comment]
It is not nice, but you can invoke the command that closes the suggest widget:

```
setTimeout(() => editor.trigger('', 'hideSuggestWidget', null)
```

**Comment by sumkumsum** [comment]
> It is not nice, but you can invoke the command that closes the suggest widget:
> 
> ```
> setTimeout(() => editor.trigger('', 'hideSuggestWidget', null)
> ```

Thanks @alexdima for the reply
Already tried above option but there will be flickering in the editor. Suggestwidget will show and then it will be removed.

There should be way to avoid that. Don't you think so please?

**Comment by alexdima** [comment]
@sumkumsum Then I don't understand what exactly it is you are wishing for. Do you want to have the suggestion widget show only when you know you have results?

Why don't you then remove the trigger characters for the completion item provider, such that the suggest widget does not show by itself. Then, you can listen to content changes on the editor by yourself, compute if you have suggestions or not, and only if you know you have suggestions to show, then you can trigger the suggest widget via `editor.trigger('', 'editor.action.triggerSuggest', null)`
