### ISSUE TITLE
Xsd schema code completion feature request

### ISSUE THREAD

**Issue by chiefruds** [microsoft/monaco-editor#1765]
In visual studio code it is possible to attach an xsd to your xml file for autocompletion.
I noticed that this feature is not available in the monaco-editor. Therefore I would like to make a feature request for autocompletion based on an xsd schema.

visual studio code examples:

![autocomplete1](https://user-images.githubusercontent.com/38459075/72357740-c34c6680-36eb-11ea-8e4c-4cf78f760746.png)

![autocomplete2](https://user-images.githubusercontent.com/38459075/72357743-c6475700-36eb-11ea-9912-0e3c08df4bcf.png)

It would help me out a lot if you could implement this feature into the monaco-editor.

**Comment by rcjsuen** [comment]
I don't believe there is that kind of support for XML and XSD files in Visual Studio Code by default.

Did you install [Red Hat's XML language support extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml)?

**Comment by chiefruds** [comment]
You are right, I installed the Red Hat's XML language support extension.

**Comment by Pranomvignesh** [comment]
> I don't believe there is that kind of support for XML and XSD files in Visual Studio Code by default.
> 
> Did you install [Red Hat's XML language support extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml)?

Does VSCode extensions are fully compatible with monaco-editor
Like is it possible to write an extension which adds these functions to monaco-editor ?

**Comment by rcjsuen** [comment]
> > I don't believe there is that kind of support for XML and XSD files in Visual Studio Code by default.
> > Did you install [Red Hat's XML language support extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml)?
> 
> Does VSCode extensions are fully compatible with monaco-editor

@Pranomvignesh No. Given that Visual Studio Code runs on your local file system, there is no guarantee that an arbitrary extension would be able to run on Monaco with zero modifications to the code.

> Like is it possible to write an extension which adds these functions to monaco-editor ?

It is certainly possible. You can take a look at the [sample code online](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) for a rough idea of what would be required to add code completion support to a Monaco editor running on the browser.

**Comment by Pranomvignesh** [comment]
@rcjsuen Thanks for the clarification. It seems like [this js](https://github.com/kripken/xml.js) does the xsd schema validation which I expect. I will try to Browserify this js and add model markers to monaco editor based on its output

**Comment by herrKlein** [comment]
This plugin does xml completion from csd
[XML complete](marketplace.visualstudio.com › items Web results Xml Complete - Visual Studio Marketplace)

**Comment by nbelyh** [comment]
I have tried to start this thing for SVG (stalled now though, as found a ready-to-go extension), but maybe could be generalized or used as a start point: https://github.com/nbelyh/editsvgcode/tree/master/src

Also, check out this article on doing custom schema (also in specific case, and a bit outdated, but can be fixed, check out the fixes in the above repo): https://mono.software/2017/04/11/custom-intellisense-with-monaco-editor/

**Comment by hediet** [comment]
I think this could be provided by a npm package!

---

We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
