### ISSUE TITLE
`contentHeight` returned with EditorLayoutInfo is incorrect when content is larger than viewport

### ISSUE THREAD

**Issue by mofojed** [microsoft/monaco-editor#1767]
**monaco-editor version:** 0.19.3
**Browser:** Chrome Version 79.0.3945.88 (Official Build) (64-bit)
**OS:** macOS Catalina 10.15.2 (19C57)
**Playground code that reproduces the issue:**

```js
// Add more new lines until content it larger than the viewport
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "Look in console output\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSome more content}",
	language: "javascript"
});

console.log('contentHeight is ', editor.getLayoutInfo().contentHeight);

```

**Comment by alexdima** [comment]
@mofojed I think you might be looking for `editor.getScrollHeight()`

**Comment by mofojed** [comment]
Thanks @alexdima! My initial post was unclear, I was looking for a way to find the height of the content (eg. from top line to last line). `contentHeight` doesn't seem to match that (it seems to just be the height in the viewport available for content); `editor.getScrollHeight()` only works if the content is larger than the viewport.

In any case, to find the actual height of the content I ended up doing:
```
const lineCount = model.getLineCount();
const columnCount = model.getLineMaxColumn(lineCount);
const lastCharTop = this.commandEditor.getTopForPosition(
    lineCount,
    columnCount
);
const contentHeight = lastCharTop + LINE_HEIGHT;
```

**Comment by alexdima** [comment]
:+1: In the next version of the editor, there will be `editor.getContentHeight()` for this use-case. -- https://github.com/microsoft/vscode/commit/97005d89b9d139d7de9195f3476a66ac49555d77
