### ISSUE TITLE
registerCompletionItemProvider is not working for yaml

### ISSUE THREAD

**Issue by simplejason** [microsoft/monaco-editor#1768]
**monaco-editor version:** 0.X.Y
**Browser:**
**OS:**
**Playground code that reproduces the issue:**

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

```js
function createDependencyProposals(range) {
    // returning a static list of proposals, not even looking at the prefix (filtering is done by the Monaco editor),
    // here you could do a server side lookup
    return [
        {
            label: '"lodash"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "The Lodash library exported as Node.js modules.",
            insertText: '"lodash": "*"',
            range: range
        },
        {
            label: '"express"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Fast, unopinionated, minimalist web framework",
            insertText: '"express": "*"',
            range: range
        },
        {
            label: '"mkdirp"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Recursively mkdir, like <code>mkdir -p</code>",
            insertText: '"mkdirp": "*"',
            range: range
        },
        {
            label: '"my-third-party-library"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Describe your library here",
            insertText: '"${1:my-third-party-library}": "${2:1.2.3}"',
            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
            range: range
        }
    ];
}


monaco.languages.registerCompletionItemProvider('yaml', {
    provideCompletionItems: function(model, position) {
        // find out if we are completing a property in the 'dependencies' object.
        var textUntilPosition = model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        var match = textUntilPosition.match(/"dependencies"\s*:\s*\{\s*("[^"]*"\s*:\s*"[^"]*"\s*,\s*)*([^"]*)?$/);
        if (!match) {
            return { suggestions: [] };
        }
        var word = model.getWordUntilPosition(position);
        var range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn
        };
        return {
            suggestions: createDependencyProposals(range)
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "yaml"
});

```

**Comment by alexdima** [comment]
@simplejason Your sample works for me. Please note that the completion provider has a lot of logic to only show those completions on line 3. For a real-life (not-toy) completion item provider, those checks (that look for `"dependencies"` etc.) should be removed:

![image](https://user-images.githubusercontent.com/5047891/72512378-4553a100-384c-11ea-853a-f867ef375cec.png)

**Comment by simplejason** [comment]
> @simplejason Your sample works for me. Please note that the completion provider has a lot of logic to only show those completions on line 3. For a real-life (not-toy) completion item provider, those checks (that look for `"dependencies"` etc.) should be removed:
> 
> ![image](https://user-images.githubusercontent.com/5047891/72512378-4553a100-384c-11ea-853a-f867ef375cec.png)

Can you replace the codes with above? It's ok with json, but not with yaml.
code changes:
```
language: "json"  ->     language: "yaml"
monaco.languages.registerCompletionItemProvider('json'   ->  monaco.languages.registerCompletionItemProvider('yaml'
```

**Comment by alexdima** [comment]
I have replaced with `yaml` and it works for me. Here is json, notice how the json coloring makes the string red:

![image](https://user-images.githubusercontent.com/5047891/72526468-c324a600-3866-11ea-99db-a41103bda5a3.png)

**Comment by rcjsuen** [comment]
@alexdima When I try with @simplejason's code, I don't get code completion either. I'm on macOS and I tried with Safari, Chrome, and Firefox. 🤔

**Comment by alexdima** [comment]
I tried on Windows and Edge and worked for me, I can also try on mac os.

**Comment by alexdima** [comment]
macOS/Safari also works for me

![image](https://user-images.githubusercontent.com/5047891/72533355-5533ab00-3875-11ea-8af0-a14eb51988e0.png)
