### ISSUE TITLE
Section 508 502.3.1: (Azure IoT explorer/edit 'Editor content;Press Alt+F1 for Accessibilit...) The BoundingRectangle property must represent an area of at least 25 pixels.

### ISSUE THREAD

**Issue by Amit8527510735** [microsoft/monaco-editor#1769]
**Application:** 
Azure IoT explorer has the following accessibility issue that needs investigation.

**Issue Details**
Modify the BoundingRectangle property so that its width and height define an area of at least 25 pixels.

**Element path:**
 edit 'Editor content;Press Alt+F1 for Accessibilit...

To Reproduce and How to Fix guidance: Please open the attached Accessibility Insights for Windows Test File (*.a11ytest) to reproduce the error in Accessibility Insights for Windows.

**Repro steps:**
1. Launch 'Azure IoT explorer' app from start menu.
2. 'App Configurations' pop up appears, navigate all controls of it.
3. Enter valid connection string and select connect button.
4. 'Azure IoT explorer'  home page launched, navigate to the table and Select any created Device added from Home page.
5. Navigate to the 'Digital Twin' under navigation menu.
6. Navigate all the controls under digital twin and expand first button under digital twin.
7. Navigate to 'Interface' link and select it.
8. Verify the issue.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information & download this tool at https://aka.ms/AccessibilityInsights.
![5812481](https://user-images.githubusercontent.com/53263029/72591277-bfa42400-3925-11ea-96ac-ed2a0eeb34b0.png)

**Comment by alexdima** [comment]
This is intentional and is a false positive from the tool.
