### ISSUE TITLE
Integrating new TypeScript versions into the Monaco editor

### ISSUE THREAD

**Issue by Zlatkovsky** [Microsoft/monaco-editor#177]
Per TypeScript team's https://github.com/Microsoft/TypeScript/issues/1664,

> Async function support for target ES3/ES5 is now available in typescript@2.1.0-dev.20160907 and later.

Is there a set of instructions for how to integrate a new version of TypeScript (which, in this case, supports the long-awaited Async/Await) into Monaco?

**Comment by alexandrudima** [comment]
TS/JS support comes in from https://github.com/Microsoft/monaco-typescript

I am unsure what our timeline is on adopting TS 2.0 in `monaco-typescript`, @jrieken can answer that.

You could do it today by forking that project and updating the `package.json` and you can run `gulp import-typescript` to fetch the latest versions from the node module and "massage" the scripts such that they are AMD ready. You can then see if there are any compilation errors (breaking changes) and try to adopt them. I think @jrieken would be happy if it would culminate with a PR :).

**Comment by Zlatkovsky** [comment]
An update with my findings:

It turns out that just purely for getting **syntax highlighting and syntax-recognition** of the `async` and `await` keywords, I actually didn't need to do _anything_  I merely included my TypeScript compiler reference (which I already needed anyway), and everything "just worked".

    <script src="//unpkg.com/typescript@2.1.0-dev.20160908/lib/typescript.js"></script>
    <script src="vs/loader.js"></script>

I did not try any scenario beyond that (I'm already doing compiling via my own call to tsc, outside of Monaco), and nothing jumped out as obviously broken when I did this.

**Comment by jrieken** [comment]
Once TypeScript 2.0 shipped we can think about a timeline for adopting it. Currently no plans for that

**Comment by jrieken** [comment]
we are now on TypeScript 2.1.5
