### ISSUE TITLE
Word wrapping wraps at incorrect location when custom font family set

### ISSUE THREAD

**Issue by mofojed** [microsoft/monaco-editor#1771]
- VSCode Version: 1.41.1
- OS Version: Mac OS Catalina 10.15.2

Steps to Reproduce:
1. In Preferences, set wordWrap to 'on', and fontFamily to a custom font eg. 'Arial'
2. Type in an editor until it wraps. It will not wrap at the correct location.

Does this issue occur when all extensions are disabled?: Yes
It also occurs in Monaco, easy to reproduce in the playground: https://microsoft.github.io/monaco-editor/playground.html

In the CSS tab, put: `@import url('https://fonts.googleapis.com/css?family=Major+Mono+Display');`

In the JS tab, put:
```
monaco.editor.create(document.getElementById("container"), {
	value: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac fermentum ex, eget porttitor tellus. Nulla facilisi. Cras semper pretium mi, ut interdum ex. Fusce vulputate dignissim turpis vel tincidunt. Aenean volutpat, massa quis luctus ultricies, magna nibh ultricies purus, a interdum nisi est posuere leo. Integer accumsan eros laoreet, tempor ligula vitae, dictum nunc. Nunc maximus velit elit, non efficitur augue tempor id. Aliquam at augue in urna tempor rutrum vitae vitae odio. Donec ac tortor quis nisl dictum posuere. Etiam tincidunt augue eget ultricies volutpat. Fusce tempus felis id risus commodo ultrices at sit amet ipsum. Maecenas rhoncus quis ipsum sed egestas.",
	language: "javascript",
    wordWrap: 'on',
    fontFamily: 'Fira Mono'
});
```
![image](https://user-images.githubusercontent.com/4505624/72449420-9ef19800-3786-11ea-86de-95ece3c35224.png)

**Comment by alexdima** [comment]
You need to call `monaco.editor.remeasureFonts()` once the custom font finishes loading.
