### ISSUE TITLE
Would like Python's Jinja2 templating lanquage to be supported.

### ISSUE THREAD

**Issue by wjohnston888** [microsoft/monaco-editor#1772]
Would like to be edit Python's Templating lanquage Jinja2.   It uses {{}}, {% %}, {# #} {% endif %} etc.

**Comment by buremba** [comment]
Is there anyone working on this?

**Comment by hopeng** [comment]
can we please add support for JInja2?

**Comment by hediet** [comment]
Unfortunately, we currently don't have the resources to add support for Jinja2.

However, we are open for pull requests by the community!

**Comment by goudarzi** [comment]
@hediet if you help setting me on the right path, I'd me more than happy to contribute.

**Comment by hediet** [comment]
See here for the existing languages: https://github.com/microsoft/monaco-languages/tree/main/src

Here is a playground you can use: https://microsoft.github.io/monaco-editor/monarch.html

**Comment by buremba** [comment]
Twig is pretty similar to Jinja, I suppose: https://github.com/microsoft/monaco-languages/tree/main/src/twig
It would be great to a language server on top of a highlighter, in that case, we need a Jinja compiler in JS. I found [this one](https://github.com/sstur/jinja-js) which might be a good start.

**Comment by goudarzi** [comment]
Working on this.. will update as I progress through this awesomeness.

To give us a bit of background, I have been in need of a decent Jinja2 template editor myself at work. VSCode is the obvious favourite if it supports it.

I have done plenty with Jinja, so hopefully that experience will be helpful here.🤷🏻‍♂️

This will be my first open source contribution, ever. ❤️😅

**Comment by hediet** [comment]
@goudarzi Awesome, thank you!

However, please note that a monarch language syntax definition will only be available in the standalone monaco editor, not in VS Code.

You need a textmate grammar to support VS Code (if there is not already an extension that provides one)!

**Comment by goudarzi** [comment]
@hediet I should thank you. 🙏🏻

I understand. Good call out. I've worked with monaco-editor before to integrate it into systems (usually for custom rules engines with a custom DSL... I know... reinvention of the wheel... say that to the product owners..)

So.. I realise that this new addition will only be available in monaco-editor, and not in VSCode (as that integration requires a new extension if I understand it correctly. Hopefully for future contributions! 😅)

At this point, I've setup both monaco-editor and monaco-languages reps locally, and I'm trying to point the generated pages (under tests in monaco-editor rep) at the monaco languages repo, to load my jinja2 entry..

I understand this can be done by customising the initialisation of monaco-editor within the HTML page to point it at a different source (for language extensions), but I can't find a good reference in the docs to verify what I'm doing is correct.. my gut feeling is, there has to be a more automated/test oriented way? This is for interacting with the editor only though. I understand the new lang comes with its own tests too.

Am I on the right path so far?

**Comment by hediet** [comment]
See this search: https://github.com/microsoft/monaco-languages/search?q=apex

You need
* `src/monaco.contribution.ts` to mention your language
* `src/{your-language}/apex.contribution.ts` to register your language
* `src/apex/apex.test.ts` to test your language. `*.test.ts` files should run automatically.

**Comment by goudarzi** [comment]
Already done that.

Now, I'm trying to load the new language entry (jinja2) in monarch, and connect its languages source to my languages repo (that has the new lang).

Not sure if the following is the right approach to "test" and interact with my new language though...

I'm looking at the [`metadata.js file`](https://github.com/microsoft/monaco-editor/blob/5bb59bb0b1d1896297db5620cdb07bdaca6cdf68/metadata.js#L63) in `monaco-editor` rep, and I'm thinking the following `paths.src` value should be pointing at my custom `monaco-languages` repo, and when recompiled, monarch will include my new language in its generated tests pages...

```
,
			{
				name: 'monaco-languages',
				contrib: 'vs/basic-languages/monaco.contribution',
				modulePrefix: 'vs/basic-languages',
				thirdPartyNotices: 'node_modules/monaco-languages/ThirdPartyNotices.txt',
				paths: {
					**src: '/monaco-languages/release/dev',**
					'npm/dev': 'node_modules/monaco-languages/release/dev',
					'npm/min': 'node_modules/monaco-languages/release/min',
					esm: 'node_modules/monaco-languages/release/esm',
				}
			}
```

Am I making sense?

**Comment by goudarzi** [comment]
To clarify further, I'm trying to load my new jinja2 lang in here pointed at my local `monaco-languages` repo (with its own sample code):

![image](https://user-images.githubusercontent.com/10061151/124570163-b9e42a80-de9a-11eb-8e9b-1ebd8d45bde9.png)

**Comment by hediet** [comment]
Afaik that should work. Make sure that you build monaco-languages.

**Comment by goudarzi** [comment]
I understand [why you're suggesting a linked playground..].

No worries. Let me see how I go. If any screws pop out of the engine, I will give us a shout here.

Thanks for your help!

**Comment by rcjsuen** [comment]
> So.. I realise that this new addition will only be available in monaco-editor, and not in VSCode (as that integration requires a new extension if I understand it correctly. Hopefully for future contributions! 😅)

The language server protocol was created specifically to solve this "N language support to M editor client implementations" problem. Of course, implementing semantic tokens through code is going to be completely different from creating a Monarch and/or TextMate grammar.

**Comment by goudarzi** [comment]
@hediet local setup with monarch is now working loading jinja2 (new language) with a sample file. Had to do a linked playground for now, mainly because of the two different ecosystems (requirejs and webpack compilation between monaco-editor, and monaco-languages repos)

@buremba I'm reviewing `https://github.com/sstur/jinja-js/blob/master/lib/jinja.js`, and agreed it's a good place to start. Thank you for sharing that.

I am also reviewing twig's syntax definition, and it seems to have limitations with the surrounding tags (it assumes the template is HTML, since twig is written for PHP..). Jinja's syntax can be applied to any text format - so I will need to extend the definition to not assume the template is HTML for example.. food for thought for now, but if you have another example from the existing langs where the surrounding template syntax can be anything, that could point me towards the right syntax definition.

If not, that's okay too. I will be updating twig's syntax to be more relaxed with the non-jinja parts of the template file.

**Comment by goudarzi** [comment]
Guys, probably a dumb question - what's the branching policy here? I don't see any feature branches in the origin.

Should I just keep my changes local, and according to the contribution guide, just kick up the packages version and publish them when ready?

**Comment by goudarzi** [comment]
So far I have this.. there are few issues, and some extensions needed in the syntax definition - but it should be fine.

![image](https://user-images.githubusercontent.com/10061151/124594970-87472b80-deb4-11eb-87ff-eaa323a383f5.png)

Will get back to it before the end of this week.. thanks again.

**Comment by waleburg** [comment]
Hey @rikkigouda, did you have any success with Jinja2 for Monaco? Any update available?

**Comment by rikkigouda** [comment]
> Hey @rikkigouda, did you have any success with Jinja2 for Monaco? Any update available? 

It's been a while. 😄 

I remember setting it up, getting a very basic syntax working, but had trouble configuring the language server and autocompletion working.

I need some motivation to get back to it. Life's been busy.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Comment by r0b3r4** [comment]
sad story
