### ISSUE TITLE
Expose mouse wheel events

### ISSUE THREAD

**Issue by lmvco** [microsoft/monaco-editor#1774]
I am trying to implement the editor zoom updating the fontSize option as suggested in https://github.com/Microsoft/monaco-editor/issues/196.

Besides the CTRL + NUMPAD_ADD / NUMPAD_SUBTRACT shortcut keys, I would like to set the zoom level using CTRL + Mouse Wheel. From one hand, I did not find in Monaco API a way to listen mouse wheel events. On the other hand, listening those events in a monaco wrapper does not work also because Monaco is stop this event propagation.

Is there any workaround?

**Comment by alexdima** [comment]
@lmvco Have you tried using the option `mouseWheelZoom: true`. The editor listens to ctrl + mouse wheel by itself, but that is just turned off because on macOS the trackpad is very sensitive.

**Comment by lmvco** [comment]
I have already tried using mouseWheelZoom option. I just have 2 concerns:
1. I would like to be notified when the user changes the zoom level (in order to store it in user preferences)
2. I would like to provide a zoom level when creating the editor

Does the Monaco API support both scenarios?

**Comment by alexdima** [comment]
@lmvco No, unfortunately there is no API for that.

Then I suggest that you add a capture mousewheel listener on the editor's container and then compute a zoom level on your own which you can then use as a multiplier for `fontSize`.
