### ISSUE TITLE
Intellisense for C# model attributes

### ISSUE THREAD

**Issue by tavisca-ysant** [microsoft/monaco-editor#1775]
I want to achieve intellisense for C# (only models and their corresponding attributes, after typing a period character all attributes should appear as a dropdown list). Is there any way to achieve it only using Monarch?

**Comment by alexdima** [comment]
No, Monarch cannot help with computing suggestions. That is something you would need to implement by yourself.

**Comment by tavisca-ysant** [comment]
so implementation can happen only through language server right?

**Comment by alexdima** [comment]
@tavisca-ysant The Monaco Editor gives a hook via a completion item provider that you can show whatever completions you want.

You can compute the completions in various ways:
- by returning always a fixed set
- by parsing the current file
- by making a server request and parse the file on the server side
- by creating a web worker and parsing the current file
- by creating a web worker and using the LSP protocol as the communication vehicle between the UI side and the web worker side.

**Comment by tavisca-ysant** [comment]
@alexdima 

Thank you for your inputs.
