### ISSUE TITLE
Two finger scrolling in IE11 not working 

### ISSUE THREAD

**Issue by jnavaratnam** [microsoft/monaco-editor#1776]
Expected: 2 finger scrolling is expected to work in all browsers when content is larger than the editor window.
Actual: In IE11 and select laptops (high resolution) 2 finger scrolling is not working.

Repro steps:
1. Use a laptop with high resolution (such as 4K display)
2. Use IE11 on Windows 10
3. Goto https://microsoft.github.io/monaco-editor/index.html
4. Mouse the mouse over the editor window
5. Use the 2 finger scrolling to move up the editor content
6. Notice the editor content is not moving but the entire page is
7. Seems the trackpad events (MSGesture?) are not fired in this case?

* Edge browser and chrome browser works in the above situation
* Using an external mouse to scroll (using the mouse wheel) works in IE11
* I couldn't repro this on an older laptop - so I assumed it was the new laptop with the high-resolution screen is issue here, but it could be due to the newer trackpads as per this post: https://blogs.windows.com/msedgedev/2017/12/07/better-precision-touchpad-experience-ptp-pointer-events/

**Comment by alexdima** [comment]
Let's track in #325

**Comment by jnavaratnam** [comment]
Thanks @alexdima, my only concern is https://github.com/microsoft/monaco-editor/issues/325 opened 3 years ago and I noticed Edge is not a problem in my case (though I didn't test on Surface Book) - so I wonder if things are changed in code (in terms of handling touch events) and it worked for Edge but not yet for IE11?

**Comment by alexdima** [comment]
AFAIK it must be that Edge fixed something, so 3 years ago things were broken both in IE11 and Edge. I believe in the meantime Edge pushed an update that fixed something. Perhaps that fix never made to IE11.
