### ISSUE TITLE
"Uncaught Error: Cannot read property 'kind' of undefined" on import statement

### ISSUE THREAD

**Issue by muliawanw** [microsoft/monaco-editor#1779]
Very easy to reproduce.

monaco-editor version: 0.19.3
Browser: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
OS: Windows 10
**Playground code that reproduces the issue:**
Open Playground

1. Open the Monaco Playground: https://microsoft.github.io/monaco-editor/playground.html
2. Select all the javascript code on the right (function hello()) and replace it with the following 3 
import statements below.

```javascript
import {Event, Context} from "lambda";
import {Item, Result} from "models";
import * as R from "ramda";
```

3. Observe in the Chrome console the following Uncaught Error .

VM309 editor.main.js:53 Uncaught Error: Cannot read property 'kind' of undefined

TypeError: Cannot read property 'kind' of undefined
    at Object.e.isImportClause (tsWorker.js:21)
    at Object.n.deleteDeclaration (tsWorker.js:21)
    at r (tsWorker.js:21)
    at n.finishDeleteDeclarations (tsWorker.js:21)
    at n.getChanges (tsWorker.js:21)
    at Function.n.with (tsWorker.js:21)
    at Object.getCodeActions (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.n.getFixes (tsWorker.js:21)
    at errors.ts:22

Try to move the mouse cursor to the last import statement and use arrow keys left and right if it does not happens.

**Comment by muliawanw** [comment]
[microsoft.github.io-1579901296041.log](https://github.com/microsoft/monaco-editor/files/4111039/microsoft.github.io-1579901296041.log)

Attached log file from Chrome console. The errors was from Monaco playground by executing steps to reproduce above in the description. They are other error as well but last one is the 'Cannot read property of 'kind' of undefined'.

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/33726
