### ISSUE TITLE
[question] Is folding supported?

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/monaco-editor#178]
In vscode i can define 'foldingStartMarker' and 'foldingStopMarker' in the language definition file. Is there a way to enable folding with monaco?

**Comment by svenefftinge** [comment]
I figured there is a generic indentation-based strategy. The documentation of the option says it defaults to true, which isn't the case.

**Comment by smellai** [comment]
Me also, I'd like to know if it's possible to collapse/uncollapse blocks of code

**Comment by Zlatkovsky** [comment]
@alexandrudima or @svenefftinge:  am I understanding correctly that as of right now, the standalone Monaco editor does not allow the collapse/uncollapse features that, say, VSCode does?

**Comment by alexandrudima** [comment]
Folding is off by default. It can be turned on via editor option `folding: true`. It defaults to true in vscode and to false in monaco-editor

**Comment by JacobEvelyn** [comment]
@alexandrudima to clarify, is my understanding correct that nothing in a Monarch language specification allows one to customize code folding behavior outside of the default behavior that you get from `folding: true`?

**Comment by rikakomoe** [comment]
@alexandrudima however the api docs here https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#folding says it defaults to "true", should that be corrected?

**Comment by alexandrudima** [comment]
@rikakomoe This has been changed in the meantime and `folding` does default to true now. i.e. the documentation is correct.

**Comment by rikakomoe** [comment]
@alexandrudima But I don't see it enables the folding feature unless passing `folding: true` in options, check here https://jsfiddle.net/e5x1qn73/
