### ISSUE TITLE
intelliense root properties repeats as in sub property.

### ISSUE THREAD

**Issue by karayakar** [microsoft/monaco-editor#1783]
I have only tested Monaco Editor 0.19.3 online @ https://microsoft.github.io/monaco-editor/
Json object has string property of "one" as you continue click "." intellisense provides root properties as sub object properties. 
JsonObject doesn't have one.one ?

![image](https://user-images.githubusercontent.com/2394360/73148635-4f1aa700-408b-11ea-8417-4f932cddbd5e.png)

Comparing same functionality with ace-tern. which is not doing the same. It is providing correct properties.

![image](https://user-images.githubusercontent.com/2394360/73148690-9ef96e00-408b-11ea-9a1e-71879c56120d.png)

**Comment by mofux** [comment]
What you are seeing are the "word based suggestions". You can disable them in the editor configuration by setting `wordBasedSuggestions: false`.

**Comment by karayakar** [comment]
@mofux  Make sense, thank you. I 'll try it. Closing the issue.
