### ISSUE TITLE
Please add a way (or document it) to download monaco releases for specific TypeScript versions

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/monaco-editor#1786]
In https://github.com/iobroker/iobroker.javascript we use the monaco editor to power the JS and TS editing experience. I'd like to keep a bit more up to date with TypeScript, but to me the versions of monaco-editor are a bit like a black box. Is there any way to get working monaco builds for a specific TS version, say 3.7.x?

The TypeScript team seems to be able to, since their bot can now create links to playgrounds with prerelease versions in their PRs.

**Comment by orta** [comment]
We have a key store of monaco versions to their typescript releases (note that you are getting older monaco versions for older TS versions: 

```js
const versions = {
  Nightly: { monaco: 'next', module: '@typescript-deploys/monaco-editor' },
  '3.7.5': { monaco: '3.7.5', module: '@typescript-deploys/monaco-editor' },
  '3.8-Beta': { monaco: '3.8.0-beta', module: '@typescript-deploys/monaco-editor' },
  '3.7-Beta': { monaco: '3.7.2', module: '@typescript-deploys/monaco-editor', hide: true },
  '3.6.3': { monaco: '0.18.1', module: 'monaco-editor' },
  '3.5.1': { monaco: '0.17.1', module: 'monaco-editor' },
  '3.3.3': { monaco: '0.16.1', module: 'monaco-editor' },
  '3.1.6': { monaco: '0.15.6', module: 'monaco-editor' },
  '3.0.1': { monaco: '0.14.3', module: 'monaco-editor' },
  '2.8.1': { monaco: '0.13.1', module: 'monaco-editor' },
  '2.7.2': { monaco: '0.11.1', module: 'monaco-editor' },
  '2.4.1': { monaco: '0.10.0', module: 'monaco-editor' },
}```

Given that we need more monaco releases (we do daily and PR builds etc) then there's a lot more TS-oriented infra which you can read about here: https://github.com/orta/make-monaco-builds/

**Comment by AlCalzone** [comment]
I'll go with downloading the relevant tarball for `@typescript-deploys/monaco-editor` from npm for now - seems like the easiest way to do. 
Thanks!
