### ISSUE TITLE
How to hide a cursor?

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#179]
I would like to hide a cursor if an editor is read only. Is there API for it?

**Comment by alexandrudima** [comment]
Hmm, I don't think so. Only through CSS...

**Comment by czb** [comment]
Any news on that? It would be nice if readonly mode actually looked like readonly mode to not confuse the people using it.

**Comment by alexandrudima** [comment]
Read only is differentiated out-of-the-box by the cursor not blinking. Further customizations can be achieved via the `cursorStyle` editor option and CSS
