### ISSUE TITLE
findWidget css error

### ISSUE THREAD

**Issue by ramki2486** [microsoft/monaco-editor#1792]
ERROR in ./node_modules/monaco-editor/esm/vs/editor/contrib/find/findWidget.css (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/lib??postcss!./node_modules/sass-loader/lib/loader.js??ref--5-3!./node_modules/monaco-editor/esm/vs/editor/contrib/find/findWidget.css)
 Module build failed (from ./node_modules/sass-loader/lib/loader.js):
 	transform: translateY(Calc(-100% - 10px)); /* shadow (10px) */
                            ^
       Incompatible units: 'px' and '%'.

**Comment by ramki2486** [comment]
please change the capital C to small C in transform property then it works well.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/pull/89156
