### ISSUE TITLE
Focusing the editor and pressing a single key enters multiple characters

### ISSUE THREAD

**Issue by vbabich** [microsoft/monaco-editor#1794]
**monaco-editor version:** 0.19.3
**Browser:** Chrome, Firefox, Safari
**OS:** MacOS
**Playground code that reproduces the issue:**
N/A

Steps to reproduce the bug on the playground page:
1. Open https://microsoft.github.io/monaco-editor/playground.html
2. Click on the first line of any editor **before the first character**
3. Type a single char, i.e. `1`
4. Focus out by clicking on white background above the editor
5. Focus on the editor again by clicking **after** the previously entered `1`
6. Press `1` again

Expected result:
- A single `1` added on step 6

Actual result
- Step 6 adds two characters - `11`

Repeating steps 4, 5, 6 will add more and more characters with each iteration. After 4 iterations the first line will have 15 `1`s entered, instead of expected 4.
Entering any other character or clicking to focus on a different position stops this behavior.

**Comment by dsmmcken** [comment]
![Jan-30-2020 16-49-41](https://user-images.githubusercontent.com/1576283/73493349-956c5080-4380-11ea-983c-ac03974c5b22.gif)

Confirming, I see the same issue. Here's a gif. After each focus and typing a single character, it is repeated multiple times.
