### ISSUE TITLE
Documentation doesn't make sense, looks like a typo mistake

### ISSUE THREAD

**Issue by ayumi-cloud** [microsoft/monaco-editor#1797]
Link: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html#autoindent

![image](https://user-images.githubusercontent.com/57409060/73560702-5fe26880-444f-11ea-973f-938d8a9e8e3a.png)

> Enable auto indentation adjustment. Defaults to false.

`false` is not listed above as an option!

Surely, the doc's mean this:

> Enable auto indentation adjustment. Defaults to NONE.

or

> autoIndent: "FALSE" | "none" | "keep" | "brackets" | "advanced" | "full"

but then you should add `true` and `false` as options.

**Comment by ayumi-cloud** [comment]
Also:

![image](https://user-images.githubusercontent.com/57409060/73561616-332f5080-4451-11ea-90d8-333d3646969c.png)

Says: `Defaults to true.` 

BUT `true` doesn't work, it's actually using `on` and `off` and the default seems to be `on`.

**Comment by rebornix** [comment]
Thanks, the jsdoc comment for them should be updated.
