### ISSUE TITLE
Get access to JSON schema hover context

### ISSUE THREAD

**Issue by gempain** [microsoft/monaco-editor#1798]
I would like to customize the JSON schema hover provider to display more information than the JSON schema definition description of the hovered property . Currently, I need to register a custom `HoverProvider` and figure out the currently hovered JSON property by manually parsing the highlighted text. I feel like this is reinventing the wheel as the native JSON hover provider has all the necessary contextual information. Would it be possible to have access to that information ? All I really need is the currently matched JSON schema definition.

Keep up the great work !

**Comment by alexdima** [comment]
fyi @aeschli

**Comment by aeschli** [comment]
The JSON language service runs in its own worker thread. Adding APIs to accessing its information at runtime is difficult. Also, we rather not add new API that might be hard to maintain.
But you can use the same library that the JSON language service uses: [jsonc-parser](https://www.npmjs.com/package/jsonc-parser). `getLocation` gives you the property at a given location.
