### ISSUE TITLE
Read Evaluate Print Loop using Monaco Editor 

### ISSUE THREAD

**Issue by ganeshs-ezdi** [Microsoft/monaco-editor#180]
Hi, I wanted to create a REPL editor using Monaco Editor, How do I enable only last line for editing and rest text as read only?

**Comment by alexandrudima** [comment]
You could use two editors, one for the output and another "one-line" for the input. You can also try using the undocumented `editor.getModel().setEditableRange()` (undocumented == not supported == might be removed at any time).

**Comment by ganeshs-ezdi** [comment]
Great thanks, this is working.
`var lineCount = editor.getModel().getLineCount();
    editor.getModel().setEditableRange(new monaco.Range(lineCount,1,lineCount,2))
`
Only the last line is edting.

**Comment by LoganDark** [comment]
I need to make the first line of a document read-only.

setEditableRange has disappeared, is there any alternative to it now?
