### ISSUE TITLE
[Screen Reader - Azure Cosmos DB - Data Explorer ] Pressing CTRL+H opens a blank webpage instead of a webpage that provides more information about editor accessibility

### ISSUE THREAD

**Issue by sonimishra** [microsoft/monaco-editor#1801]
**User Experience:**
While select CTRL +H on editor and blank page open then user who are visually impaired might get effected. 

**Pre-Requisite:**
Select "Core(SQL)" in API combo box while creating the Cosmos DB.

**Repro-Steps:**
1. Open URL: https://ms.portal.azure.com
2. Login via valid credentials
3. Navigate to "Azure Cosmos DB" from left pane and select it.
4. Navigate to any of the Azure Cosmos DB which is already created and select it.
5. Navigate to "Data Explorer" from the left and select it.
6. Navigate to "Azure SQL Tree" More button and select any query.
7. Navigate to editor and press Alt + F and then select Ctrl + H key.
8. Verify, the issue..

**Actual Result:**
Pressing CTRL+H on editor a blank page open and does not contain any information about editor accessibility.

**Expected Result:**
Pressing CTRL+H on editor blank page should not open and a complete web page should open and provide meaningful information.

**MAS Reference:**
MAS 1.3.1 - Info and Relationships

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier

External Bug Process: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug.
For more information please use this Link.
[[Screen Reader - Azure Cosmos DB - Data Explorer ] Pressing CTRL+H opens a blank webpage instead of a webpage that provides more information about edi.zip](https://github.com/microsoft/monaco-editor/files/4147373/Screen.Reader.-.Azure.Cosmos.DB.-.Data.Explorer.Pressing.CTRL%2BH.opens.a.blank.webpage.instead.of.a.webpage.that.provides.more.information.about.edi.zip)

**Comment by alexdima** [comment]
@sonimishra I cannot reproduce with the given steps on https://microsoft.github.io/monaco-editor/

When I open the editor in the vanilla Monaco Editor homepage, Ctrl+H opens the find widget.
