### ISSUE TITLE
Hardcoded styles in scrollbar again

### ISSUE THREAD

**Issue by lmvco** [microsoft/monaco-editor#1802]
**monaco-editor version:** 0.19.0
**Browser**: Chrome
**OS**: Windows
**Playground code that reproduces the issue:**: https://codesandbox.io/s/monaco-hide-cursor-ruler-tdu4u

--

In 2017, it was created an issue regarding the top and left border of the scroll bar - https://github.com/Microsoft/monaco-editor/issues/422

The issue was closed assuming that the prop `hideCursorInOverviewRuler` with the value `true` allows us to hide that border.

Anyway, I did a test with a recent version of Monaco - 0.19.0 - and this prop is not hiding the border. See a demo [here](https://codesandbox.io/s/monaco-hide-cursor-ruler-tdu4u).

![image](https://user-images.githubusercontent.com/1884391/73649287-5e938480-4677-11ea-87ab-47a3a8548f8f.png)

**Comment by alexdima** [comment]
Have you tried `overviewRulerBorder: false`?

**Comment by lmvco** [comment]
It worked! Thanks
