### ISSUE TITLE
Esc doesn't close Search

### ISSUE THREAD

**Issue by moshfeu** [microsoft/monaco-editor#1803]
monaco-editor version: 0.19.3
Browser: Chrome 69.0.2
OS: Mac OS 10.15.3 

Open the playground: https://microsoft.github.io/monaco-editor/playground.html

1. Click into the editor
2. Press Ctrl-F to open the find dialog
3. Press ESC to close the find dialog

**Expected result**
The search will closed

**Actual result**
The editor is losing the browser focus but the search result remain opened

![video1](https://user-images.githubusercontent.com/3723951/73658583-4171ac80-469d-11ea-8dae-7c1d40e9fdb5.gif)

**Comment by alexdima** [comment]
@moshfeu I could not reproduce. I tried with macOS + Chrome and cmd+f, followed by Escape brings focus back to the editor.

**Comment by moshfeu** [comment]
Sorry 🤭,
It was the [Vimuim](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) extension. Shame on me..
