### ISSUE TITLE
Mention F1's Inspect Tokens in Monarch docs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/monaco-editor#1805]
I'm trying to target different syntax trivia in custom themes and finding it difficult to tell which trivia classes map to what. This HTML in development corresponds to some C++ code:

```html
<span>
  <span class="mtk12">int</span>
  <span class="mtk1">&nbsp;main</span>
  <span class="mtk17">()</span>
  <span class="mtk1">&nbsp;</span>
  <span class="mtk17">{</span>
</span>
```

It'd be useful when developing to, maybe:
* Medium? size: surface what token types the classes such as `mtk12` map to
* Large? size: provide some kind of [astexplorer.net](https://astexplorer.net)-style visualizer for tokens parsed from text

Is there some way this experience could be made better? 🙏

**Comment by alexdima** [comment]
Have you tried `F1 > Developer: Inspect Tokens`?

![image](https://user-images.githubusercontent.com/5047891/73697500-fed0c400-46de-11ea-835b-7c08b1b69502.png)

**Comment by JoshuaKGoldberg** [comment]
😭 @alexdima this is amazing, thank you! I pored over the [monarch.html](https://microsoft.github.io/monaco-editor/monarch.html) docs and had no idea this existed.

Updating the title of this issue to reflect a real request: can this be mentioned in the docs? 🙏

**Comment by alexdima** [comment]
@JoshuaKGoldberg :+1: Sorry about that!

Would you please like to create a PR to document it?
