### ISSUE TITLE
No way to target default token color in specific language

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/monaco-editor#1806]
**monaco-editor version:** 0.X.Y
**Browser:** Google Chrome
**OS:** Mac
**Playground code that reproduces the issue:**

```js
const theme = {
  base: "vs",
  inherit: true,
  rules: [
    {
      token: "",
      foreground: "#ff0000"
    },
    {
      token: ".html",
      foreground: "#00ff00"
    }
  ]
};

monaco.editor.defineTheme("theme", theme);
monaco.editor.setTheme("theme");

let editor = monaco.editor.create(document.getElementById("container"), {
  value: "<h1>Hello</h1>",
  language: "html"
});
```

I'd like to target the default token color for just the `html` language. I've tried every variant of `"html"`, `"*.html"`, etc. I can think of no way to do this. Could such a thing be added (or mentioned here)? 🙏 

Unclear if this is a bug or feature request...?

**Comment by rebornix** [comment]
The theme itself is language agnostic so if a token has no type (for example, `hello` in your case), it will only use the token color defined in 

`rules: [
    {
      token: "",
      foreground: "#ff0000"
    }
]`

One way to solve this problem from your end is extending the HTML grammar https://github.com/microsoft/monaco-languages/blob/master/src/html/html.ts#L68 to give it a default token like `invalid`.

**Comment by JoshuaKGoldberg** [comment]
Thanks for the info. This is a feature request then 😃.
