### ISSUE TITLE
Providing container for 'overFlowingContentWidgets'

### ISSUE THREAD

**Issue by svenefftinge** [microsoft/monaco-editor#181]
When using Monaco in a context where the parent nodes use 'overflow:hidden' the contents from overFlowContentWidgets gets truncated. Unfortunately in our case it's not possible to change the outside context.
Is there a way or could you consider to provide the parent node of the overFlowingContentWidgets div, such that a client could hang it into e.g. `<body>`?

**Comment by svenefftinge** [comment]
I mean if I could pass a provider for the node where 'this.contentWidgets.overflowingContentWidgetsDomNode' would be attached to, I could atach it to some parent, so it can overflow.
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/view/viewImpl.ts#L281

**Comment by alexandrudima** [comment]
I suggest the following workaround:
* the view gets created after each `setModel()` call.
* after each `setModel()` call you can grab the overflowingContentWidgetsDomNode straight from the DOM and reparent it to the `<body>`.
* maybe this will work for you?

**Comment by svenefftinge** [comment]
Thank you. I will try tomorrow and report.

**Comment by svenefftinge** [comment]
I tried, but it is unfortunately not so easy, because the position is based on the viewport in tghe rendering context. So the popups show up in odd locations.

**Comment by jchomicki** [comment]
I am also hitting this issue and changing the containing structure is very non-trivial. The popover is already being absolutely positioned, it seems like it should not be according to the editor position.

**Comment by svenefftinge** [comment]
The positioning strategy can be changed by setting the `fixedOverflowWidgets: true` option.
With that moving the elements up should be easier, however I managed to fix the overlaying issues by adjusting the z-index of the focussed editor branch.

**Comment by sertand** [comment]
I've just hit this issue as well and I did try setting fixedOverflowWidgets to true. However, it seems like tooltips created via glyphMarginHoverMessage ignores this setting. Is this intentional?

**Comment by paranoidjk** [comment]
+1 same problem here

**Comment by alexdima** [comment]
Starting with the next release, there will be a new editor constructor option called `overflowWidgetsDomNode`. This will be used as a parent node for all editor content widgets that are marked as overflowing.
