### ISSUE TITLE
Prevent selecting text after pushEditOperations on the model

### ISSUE THREAD

**Issue by raedle** [microsoft/monaco-editor#1811]
**monaco-editor version:** 0.19.3
**Browser:** Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
**OS:** macOS Catalina Version 10.15.3
**Playground code that reproduces the issue:** see below

## tl;dr
I need to set a new editor value, but want to preserve the undo/redo stack.

## Context
According to the documentation, [`pushEditOperations`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#pusheditoperations) is the preferred way to edit the model.
>Push edit operations, basically editing the model. This is the preferred way of editing the model. The edit operations will land on the undo stack.

However, the editor auto-selects content when pushing edit operations on the model (`ITextModel.pushEditOperations`). I don't want that, and it doesn't do that when setting the value on the editor directly (see playground example code for comparison between `editor.setValue` and `model.pushEditOperations`).

I've tried several variation on the `pushEditOperations` parameters without any luck. For example, setting `beforeCursorState` to `[]` or returning null for the `cursorStateComputer` in the `pushEditOperations` did not seem to have any effect on the outcome of the selection.

I'm not sure if I'm misinterpreting the API or if it is a bug. Any thoughts and comments are appreciated :)

```html
<div id="container1" style="height:50%;"></div>
<div id="container2" style="height:50%;"></div>
```

```js
const newEditorValue = `{
    "name": "hello"
}`

const createEditorExample = (containerId, updateCallback) => {
    const editor = monaco.editor.create(document.getElementById(containerId), {
        value: '',
        language: "json",
        lineNumbers: 'off',
        minimap: { enabled: false },
    });

    setTimeout(() => updateCallback(editor), 2000);
}

createEditorExample('container1', (editor) => {
    editor.setValue(newEditorValue);
});

createEditorExample('container2', (editor) => {
    const model = editor.getModel();
    // This will preserve the undo stack.
    model.pushEditOperations(
        [],
        [{ range: model.getFullModelRange(), text: newEditorValue }],
        () => null,
    );
});
```

**Comment by alexdima** [comment]
@raedle A model can be attached to 0, 1, or more editors. When a model is attached to an editor, it is preferable to execute the edits you want through the editor. The editor associates a selection state to the model.

So it would be best to `editor.executeEdits`. Then you can pass in the desired end selection for the editor on which you invoke. 

If you wish to have two editors display the same model (it appears from your sample that you try to have two editors in sync), it would be easier to use `monaco.editor.createModel` to create yourself a model and then `monaco.editor.create(..., { model: model })` to create an editor attached to your model.

**Comment by raedle** [comment]
@alexdima Thanks for your quick response!

The model will only be attached to one editor. 

The behavior I'm describing is that the editor selects all or parts of the inserted text when pushing updated text to the model. The issue is illustrated in the attached picture where the editor in the top replaces text by `editor.setValue` and the bottom editor replaces text by `model.pushEditOperations`. We need to use the latter to preserve the undo stack.

Is there a way to prevent the selection from expanding, but keep the editor selection(s) in the same place?

A workaround for now is to store the selection before change and set it after the change.

```js
const selection = editor.getSelection();
const model = editor.getModel();
editor.executeEdits('update-value', [{
    range: model.getFullModelRange(),
    text: newEditorValue,
    forceMoveMarkers: true
}]);
editor.setSelection(selection);
```

![Screen Shot 2020-02-05 at 10 19 47 AM](https://user-images.githubusercontent.com/489051/73890579-28950280-4827-11ea-94e5-520b6a63f52b.png)

**Comment by alexdima** [comment]
@raedle Yes, that is a good way forward. Normally, the selection stays put. I need to quickly explain how this works so you have a mental model of what's going on. The selection works by creating two markers in the text buffer, one for the start of the selection and one for the end of the selection. These markers are created even when the selection is collapsed. The markers are defined to stick with their surrounding. 

So for example, `is` is selected below:
```
this ]is[ a text
```

When doing an edit somewhere in the text, and not defining what the resulting selection should be, the selection will be "recovered" from these markers. The markers will flow with the text and the selection will "stick" with its text, e.g. inserting hello at the beginning:

```
hello this ]is[ a text
```

When doing an edit inside the selection, the markers will also flow with the text. e.g. inserting hello in the middle

```
this ]ihellos[ a text
```

But sometimes there are edge cases. When doing an edit precisely at the markers position, it is not so clear where the selection should end up, like inserting `hello` at the end of the selection. Currently, this results in:

```
this ]ishello[ a text
```

So you can think that the selection start marker sticks with the space before it, and the selection end marker sticks with the space after it. There are even more edge cases, like the one you are pointing to. When having an empty text buffer, the selection still has two markers: one which sticks with the beginning of the text buffer, and one which sticks with the end of the text buffer.

```
][
```

So when text is being inserted, like hello, the same happens:
```
]hello[
```

And I hope that explains why things get selected.

You can:
1. Compute by yourself exactly where you want the end selection to be. You have the initial selection, the edits you want to apply, and you know and understand the semantics of what it is you are doing, so you can compute by yourself what you would like the resulting selection to be. I suggest you do this by using the last argument of `editor.executeEdits`, not by using `editor.executeEdits`+`editor.setSelection`. Using the `editor.executeEdits` has the advantage that an undo + redo puts the selection where you want it.

2. Try to communicate to the editor more about your edit. The only extra available to you is to set `forceMoveMarkers` to the edit you pass in. I believe that will result in this case that the selection moves to the end of the file, as if the user typed in the text you do:

```
hello][
```
