### ISSUE TITLE
ipad "show keyboard" button does not show up in ios 13

### ISSUE THREAD

**Issue by riknoll** [microsoft/monaco-editor#1812]
Steps to reproduce

1. Open the monaco-editor homepage in safari on an ipad with ios 13+ installed
2. Note that the "show keyboard" button does not appear in the bottom right of the screen

In the following screenshot, the left side is an ipad simulator with ios 12.4 and the right side is an ipad simulator with ios 13.3. The keyboard button is visible in the left and not on the right.

<img width="1312" alt="Screen Shot 2020-02-05 at 3 30 10 PM" src="https://user-images.githubusercontent.com/13754588/73892899-f6869f00-482c-11ea-8005-36078df82d8a.png">

**monaco-editor version:** 0.19.3
**Browser:** Safari
**OS:** ios 13.3

The cause is that the user agent string for safari in ios 13 was changed to mimic the user agent for desktop safari.

**Comment by alexdima** [comment]
@riknoll Is there any other tell-tale that the current page is Safari on iOS than the user agent? 

Currently, here we decide to show the keyboard icon if the browser is an iPad -- https://github.com/microsoft/vscode/blob/b8cace23ff07521a17df6c07ecb3becdb6db8d46/src/vs/editor/standalone/browser/iPadShowKeyboard/iPadShowKeyboard.ts#L26-L29

And here is where we check if it is an iPad -- https://github.com/microsoft/vscode/blob/b8cace23ff07521a17df6c07ecb3becdb6db8d46/src/vs/base/browser/browser.ts#L123

Do you know alternative ways to do this?

**Comment by nrayburn-tech** [comment]
@alexdima I am not sure how to detect a difference between iPhone and iPad, but checking for navigator.maxTouchPoints > 0 should work for a check between desktop and mobile Safari.

**Comment by riknoll** [comment]
Yep, I used `navigator.maxTouchPoints > 0` to detect it in MakeCode. I think that might also trigger if they have a touch screen monitor connected to their mac but that seems like a pretty niche scenario.
