### ISSUE TITLE
Fidelity with line endings

### ISSUE THREAD

**Issue by vbcodec** [microsoft/monaco-editor#1813]
Currently editor ends each line with CRLF, despite that pushed text have other endings (CR or LF alone). For my need (and I think others) I want editor should keep these endingd, and not replace it with CRLF. This should work also for paste text and searching. I think that IStandaloneEditorConstructionOptions should get new property like OriginalLineEndings (true / false), to activate this mode.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/127

**Comment by vbcodec** [comment]
so, most users just want it, any hopes to implement it ?
