### ISSUE TITLE
Parameter description are treated as plain text

### ISSUE THREAD

**Issue by clentfort** [microsoft/monaco-editor#1814]
**monaco-editor version:** 0.19.3
**Browser:** Firefox 72.0.2
**OS:** MacOS
**Playground code that reproduces the issue:**

```js
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
	noSemanticValidation: true,
	noSyntaxValidation: false
});

monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
	target: monaco.languages.typescript.ScriptTarget.ES6,
	allowNonTsExtensions: true
});

monaco.languages.typescript.javascriptDefaults.addExtraLib([
	'declare class Facts {',
	'    /**',
    '     * @param t **Some bold text** Some other text',
	'     */',
	'    static next(t:string):string',
	'}',
].join('\n'), 'ts:filename/facts.d.ts');

var jsCode = "return Facts.next(/* hit ctrl + shift + space */);";

monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

```

**Description**
The description of the parameter on function `next` is treated as plain text when just showing the description of the parameter. Additionally, the displayed comment is missing a leading `*`. It says `*Some bold text**`. It should be `**Some bold text**`

![image](https://user-images.githubusercontent.com/1284808/73951388-56e11380-48f5-11ea-9dfe-61fd29431f7b.png)

The incorrect parsing issue also arises when hovering the method directly. Here the text is treated as markdown, but because a leading `*` was stripped, the result is wrong. The text `Some bold text` should be **bold** and not *cursive*
![image](https://user-images.githubusercontent.com/1284808/73951433-64969900-48f5-11ea-8602-7086fa253104.png)

**Expected behaviour:**

The description of the parameter is not missing the leading `*`, when showing the hint on the parameter it should be treated as markdown and rendered accordingly.

**Comment by alexdima** [comment]
Fixed by https://github.com/microsoft/monaco-typescript/pull/66
