### ISSUE TITLE
monaco-json hover provider not interpreting markdown

### ISSUE THREAD

**Issue by gempain** [microsoft/monaco-editor#1816]
Related to:
- #1798 opened by myself
- an unanswered [SO question](https://stackoverflow.com/questions/55879659/how-to-customize-the-json-schema-hover) from someone else

The default JSON hover from monaco-json displays the JSON schema definition `description` corresponding to the hovered property. When the description contains markdown, it is interpreted as raw text. I am assuming this is due to the `isTrusted` property of `Hover` being set to `false`. Surprisingly, indents of 4 spaces are interpreted as code blocks.

Would it be possible to trust the JSON schema description ? Is this a bug or an intended feature ?

Keep up the great work !

**Comment by aeschli** [comment]
As `description` is part of the standard JSON schema format we assume it is raw text.
For markdown descriptions, the VSCode/MonacoJSON language service looks for the property `markdownDescription`. That's not standardized, but if you don't mind, use it.

**Comment by gempain** [comment]
@aeschli thanks for the tip ! I didn't find this in the docs, but am glad to see this feature already exists.
