### ISSUE TITLE
Grammatical nit in Monarch docs

### ISSUE THREAD

**Issue by bolinfest** [microsoft/monaco-editor#1819]
From https://microsoft.github.io/monaco-editor/monarch.html:

> Usually, we need to use a `next` attribute too to switch to a state where we can tokenize the foreign code.

Perhaps the word "too" is in there deliberately, but it feels like an error. Strike it? Or choose a different construction that doesn't result in two homophones in a row?

I've been spending a lot of time in the `nextEmbedded` docs recently and have been reading this over and over...

**Comment by alexdima** [comment]
@bolinfest Would you consider submitting a PR to fix it?

The file lives at https://github.com/microsoft/monaco-editor/blob/master/website/monarch.html
