### ISSUE TITLE
Link to examples of Monarch grammars

### ISSUE THREAD

**Issue by bolinfest** [microsoft/monaco-editor#1820]
Neither of these:

* https://github.com/microsoft/monaco-editor/blob/master/README.md
* https://microsoft.github.io/monaco-editor/monarch.html

References this:

https://github.com/microsoft/monaco-languages

Although [the Monarch docs](https://microsoft.github.io/monaco-editor/monarch.html) are very thorough, what is even better is more examples! It is a little surprising that https://github.com/microsoft/monaco-languages is a separate repo, so it would help to make it easier to find.

**Comment by bolinfest** [comment]
Similarly, https://github.com/microsoft/monaco-editor/ tells me that this repo does not contain the code for Monaco, yet it does not link directly to a place where I can actually find the code.

https://github.com/microsoft/monaco-editor/blob/master/CONTRIBUTING.md has most of the information I want, but it isn't obvious that's where I should be looking.

**Comment by alexdima** [comment]
@bolinfest Would you please consider creating PRs to improve things?
