### ISSUE TITLE
Support .Rmd as an R syntax

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/monaco-editor#1821]
[.Rmd](https://rmarkdown.rstudio.com/authoring_quick_tour.html) is a reasonable expected format for R syntax highlighting. In fact, Monaco already supports it!*

![Screenshot of Codecademy using R syntax in Monaco](https://user-images.githubusercontent.com/3335181/74058446-0d0b3280-49b4-11ea-9af9-5b1ef37131e5.png)

I'd be happy to send a quick PR to add `.Rmd` and `.rmd` as supported language extensions!

*Edit: to be clear, when the language is set to R, the `.Rmd`-style syntax actually works out of the box. The issue is just that Monaco doesn't know to use R syntax when the language is `.Rmd` -- there is no out-of-the-box alias set up.

**Comment by alexdima** [comment]
PR welcome.
