### ISSUE TITLE
monaco editor wordWrap problem

### ISSUE THREAD

**Issue by hellobugme** [microsoft/monaco-editor#1822]
![GIF](https://user-images.githubusercontent.com/9287109/74070202-6cf8ec00-4a3b-11ea-91f8-8ff1d21a8a09.gif)
![snipaste_20200208_062430](https://user-images.githubusercontent.com/9287109/74070392-e395e980-4a3b-11ea-868d-a2c4c55d5e94.jpg)
![snipaste_20200208_062555](https://user-images.githubusercontent.com/9287109/74070398-e690da00-4a3b-11ea-8762-22aea0c82ea3.jpg)
```html
<div style="width: 100%; height: 100%">
  <monaco-editor></monaco-editor>
</div>
```
My editor options:
```javascript
{
  // 布局自适应
  automaticLayout: true,
  // 自动换行
  wordWrap: true,
  // 折叠
  folding: false,
  // 小地图
  minimap: {
    enabled: false
  },
  // 底部滚动超出
  scrollBeyondLastLine: false,
  // 行号
  lineNumbers: false,
  // 只读
  readOnly: false,
  // 字体
  fontFamily: '微软雅黑',
  fontSize: 20
}
```
Does anyone know why? please help me~

==============================

I tried again. If the font is Microsoft Yahei, just enter a long "======" and it will appear. If it is the default font, it will also appear in many Chinese cases. It seems that both font and character type have an effect.

**Comment by alexdima** [comment]
@hellobugme With the upcoming editor release (0.20.x), there will be a new editor option, `wrappingStrategy`. You can then set that to `advanced` and your use-case will work correctly.

**Comment by hellobugme** [comment]
> @hellobugme With the upcoming editor release (0.20.x), there will be a new editor option, `wrappingStrategy`. You can then set that to `advanced` and your use-case will work correctly.

Hi alexdima, thanks for the reply.
But when I upgraded to 0.20.0, I got an error, this is the error message:
![snipaste_20200211_095259](https://user-images.githubusercontent.com/9287109/74206118-f6ffb980-4cb4-11ea-94ac-0b00f721e276.jpg)
And 0.19.3 is working well.

**Comment by alexdima** [comment]
@hellobugme Perhaps you have a caching issue or some other kind of problem? `getMassagedFontFamily` is defined on the class `BareFontInfo` and everything works fine for me.

**Comment by hellobugme** [comment]
> @hellobugme Perhaps you have a caching issue or some other kind of problem? `getMassagedFontFamily` is defined on the class `BareFontInfo` and everything works fine for me.
Should be caused by caching. I removed monaco-editor package and added it again, and it worked.
Thank you very much!
