### ISSUE TITLE
Quick fix underline still shown when 'lightbulb' option is disabled

### ISSUE THREAD

**Issue by AndrewSverdrup** [microsoft/monaco-editor#1823]
**monaco-editor version:** 0.19.3
**Browser:** Chrome Version 79.0.3945.130 (Official Build) (64-bit)
**OS:** Linux
**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}\n\nmodule.exports = hello;",
    language: "javascript",
    lightbulb: { enabled: false },
    hover: { enabled: false },
    quickSuggestions: false,
});
```
The three dots indicating a quick fix are shown even when the hover and lightbulb options are disabled. Is there a way to disable the dotted underline?

![Screenshot from 2020-02-08 18-44-36](https://user-images.githubusercontent.com/17505741/74095276-57b7a800-4aa3-11ea-94d6-88def0256382.png)

**Comment by spahnke** [comment]
The three dots do not indicate a quickfix but rather a `Hint` level diagnostic. In this case the hint diagnostic just states `File is a CommonJS module; it may be converted to an ES6 module.(80001)`. A quickfix may be associated to a diagnostic (like it is here) but that's not mandatory.

I don't know if it's possible to filter diagnostics by severity level, you can however choose to ignore specific diagnostics coming from the TypeScript language server by doing the following. If this is feasible for you depends on the number of diagnostics you need to suppress of course.
```js
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
    diagnosticCodesToIgnore: [80001]
});
```

Hope that helps!

**Comment by AndrewSverdrup** [comment]
@spahnke Ah ok, thanks for explaining that! I've disabled all the diagnostics for now using `noSuggestionDiagnostics: true`.
