### ISSUE TITLE
Registercompletionitemprovider will make some functions disappear

### ISSUE THREAD

**Issue by yangyangyihao** [microsoft/monaco-editor#1825]
Hello, I want to simply support Java. We support that if we input some words before and then input again, there will be input friendly prompt. But when I use the registercompletionitemprovider API, I won't be able to give a friendly hint of the words I've written. It's strange that this problem doesn't exist in JS.

**Comment by alexdima** [comment]
@yangyangyihao Please see https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

You can hook into the editor suggest widget and offer your completions.

Once you do that, you own the intellisense experience and can return word suggestions if you wish to do so.

**Comment by yangyangyihao** [comment]
I  know  that,but  if  i  do.  It  will  don,t  other  text  prompt  .------------------ 原始邮件 ------------------
发件人: "Alexandru Dima"<notifications@github.com>
发送时间: 2020年2月10日(星期一) 晚上10:39
收件人: "microsoft/monaco-editor"<monaco-editor@noreply.github.com>;
抄送: "yangyangyihao"<780987924@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [microsoft/monaco-editor] Registercompletionitemprovider willmake some functions disappear (#1825)



@yangyangyihao Please see https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
 
You can hook into the editor suggest widget and offer your completions.
 
Once you do that, you own the intellisense experience and can return word suggestions if you wish to do so.
 
&mdash;

**Comment by alexdima** [comment]
@yangyangyihao You can use the code the editor uses as a starting point -- https://github.com/microsoft/vscode/blob/8bae8bb13ed14af50cfa84c7aba8697fcf594750/src/vs/editor/common/services/editorSimpleWorker.ts#L156-L216

**Comment by yangyangyihao** [comment]
Thank you very much for your reply. Sorry, I may not know what you mean, but after I try to do that, I have an original function, such as I input a variable 'ABCD'. When I type again, I want to prompt 'ABCD'.Thank you again. We like Monaco so much that we are constantly using it. I am honored by your team's reply and more confident to make a better project. Last time I asked you how to support a new language, and you gave me your reply, but maybe I was dull and didn't try very successfully. I'm looking forward to your more detailed steps to support a new language. Thank you very much.
Simple support for a language can be basically realized through the API you give, but it has always been a difficulty for me when it comes to the semantic parsing of input vocabulary at runtime. I hope you can give me some advice. Thank you for taking the time out of your busy schedule to answer my questions

**Comment by alexdima** [comment]
@yangyangyihao I am happy to give you advice about how to use the Monaco Editor API, because I hope you to be successful in using the Monaco Editor.

But I am sorry, I just do not have sufficient time to solve the problem you have for you. I suggest you try at StackOverflow or perhaps on programming forums. Computing words in a string of text is not a problem specific to the Monaco Editor or its API, it is a generic JavaScript programming task.

**Comment by yangyangyihao** [comment]
Hello.I'd like to know how to add input aids to quotes, which are lines of string classes. Just like the path of vscode, '. /' can have input assistance.
