### ISSUE TITLE
API documentation is missing as of 0.20

### ISSUE THREAD

**Issue by russelltg** [microsoft/monaco-editor#1826]
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Windows

The API documentaiton seems to be missing on the website...

https://microsoft.github.io/monaco-editor/api/index.html

**Comment by trananhmanh89** [comment]
same

please check

**Comment by nrayburn-tech** [comment]
The index response from [https://microsoft.github.io/monaco-editor/api/index.html](https://microsoft.github.io/monaco-editor/api/index.html) is about 100 lines shorter than it is when running the server locally at [http://localhost:8080/monaco-editor-website/api/index.html](http://localhost:8080/monaco-editor-website/api/index.html).
