### ISSUE TITLE
Add EditorService API

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/monaco-editor#183]
We need to have the full EditorService API (currently replaced with empty EditorOverrideService interface) to provide a strategy for opening editors. Or is there already a way to do it?

**Comment by alexandrudima** [comment]
@svenefftinge Can you try:

```
monaco.editor.create(container, opts, {
  editorService: myEditorService
})
```

Is this no longer working?

**Comment by svenefftinge** [comment]
I think it should work, it is just that the interface IEditorService is not there. So are you going to expose this as API in a future release?

**Comment by alexandrudima** [comment]
I am trying to add cut-off points to our API.

Adding all the services as API will make breaking changes occur **very** often, it would mean exposing all the types related to service injection and I am weary of doing that, as IMHO services don't need to be customized in most use-cases.

**Comment by mbana** [comment]
I'd like to vote for this as well; we sorta trying to implement a distrubted compile.
We're creating language server to do the compilation and validation etc, however the required bits of `vscode` are not exposed.

Not to sound negative, the samples currently available use the standalone languages.  When I first tried it I thought it would be using the full-blown language service as provided by, say, `vscode`. This wasn't the case.

I really would like to see more parts opened up...

Thanks,

**Comment by alexandrudima** [comment]
All code is available, we simply don't spec it in the `.d.ts` file as we don't want to make it API and we consider it implementation detail. You can always `require(...)` to get to all our code... Not sure what you'd want more to get from `vscode`, in `vscode` the runtime is nodejs or any other process (e.g. the OmniSharp language server is written in C#, etc.) meanwhile here the runtime is a browser.
