### ISSUE TITLE
Old data(data from previous call) is visible in suggestwidget of autocompletion, if backend responds slowly

### ISSUE THREAD

**Issue by sumkumsum** [microsoft/monaco-editor#1830]
**monaco-editor version**: 0.15.6
**Browser**: Chrome
**OS**: Windows

**Issue Description:**

Steps:
1) Implement AutoCompletion-api by fetching data from backend (rest/websocket), I am using websocket.
2) Keep flag - > incomplete: true in registerCompletionItemProvider(*)
3) Now try to type quickly in editor and that will lead to multiple calls to fetch data from backed.
4) In network tab, you can see that multiple call are going simultaneously, and response is coming at its own pace.
5) Now in this scenario user might be expecting different data but user will be seeing the result of the first call out of these multiple calls. which is wrong.
6) _Please Note_ : We are using promise in provideCompletionItems.

**Result:**
Old data is visible in suggest widget

**Expectation:**
Latest data should be visible.

**Use Case**
1) When user is tying a character I want to show classes suggestions 
2) And in continuation when user types "." , I want to show function suggestions. 
3) But even if user is expecting function suggestions, suggest widget is showing class suggestions though correct data is retrieved from backed (function data)
4) Means data is not getting updated on each retrieval from backend by suggest widget, if calls are made simultaneously.
5) Although everything is working fine if calls are made individually. (getting right suggestion at right time)

**Code for reference:**
```

private triggerCharactersArray = ['.', ';', '/', '{', '}', '(', ')']; 

this._registerCompletionItemProviderRef = languages.registerCompletionItemProvider("java", {
            triggerCharacters: this.triggerCharactersArray, /** Triggering character to invoke auto completion */
            provideCompletionItems: function (model, position) {
                return this.getAutoCompleteData(model, position).then(function (res) {
                    /** Get completion response from websocket */
                    let completionListSuggestion = getCompletionList(res ? JSON.parse(res) : null);

                    /** Return suggestion list to GUI */
                    return {
                        incomplete: true, // So that autocompletion request is sent on every char
                        suggestions: completionListSuggestion.map(item => ({ ...item }))
                    };
                }.bind(this));
            }.bind(this)
        });


getAutoCompleteData(model, position) {
        return new Promise(function (resolve, reject) {
            this._autocompleteWSSubscr = this._wsObject.subscribe(
                data => {
                    resolve(data);
                },
                error => {
                    console.log('Error in autocomplete recieved from WS :' + JSON.stringify(error));
                    reject(error);
                }
            );

            this.sendAutoCompletionData(model, position);

        }.bind(this));
    }

sendAutoCompletionData(model, position) {

<Logic to send token and position to the websocket>

}

getCompletionList(data) {
    const completionItemList: CompletionItem[] = [];
    // parse the data and load completion list
     return completionItemList;
}

```

**Data from network**
1) Snapshot of current output:
Left pane, you can see class suggestions are coming and right pane you can see two calls in "green" color are made simultaneously and response is recieved one after the other (in white color)
![image](https://user-images.githubusercontent.com/32838906/74313489-cb0a3400-4d99-11ea-9e50-3b99158fe25b.png)

2) Current data which is being showed in Editor
![image](https://user-images.githubusercontent.com/32838906/74313700-2e946180-4d9a-11ea-9453-34581d146417.png)

3) Expected data which should come in suggest widget

![image](https://user-images.githubusercontent.com/32838906/74313760-4f5cb700-4d9a-11ea-9425-1950b19a521a.png)

Correct data is not shown even if retrieved from backend as above.

4) If I try the call individually, keeping in mind so that no simultaneous calls are made then correct data is coming, which should also happen in simultaneous calls. Please see snapshot of result below.
![image](https://user-images.githubusercontent.com/32838906/74314286-31438680-4d9b-11ea-8212-6fbf435f4765.png)

Conclusion : Suggest widget should update the result. Please let me know if anything is not clear

@alexdima 
@jrieken

**Comment by jrieken** [comment]
>  Suggest widget should update the result. 

It does that - you can see it working (and I just tested that) when doing completions for `dependencies` or `devDependencies` in package.json files. There we use incomplete results, fetch more from npm as you type, and the UX update correctly

Please make your sample so that it I can run it and that I can reproduce this
