### ISSUE TITLE
Cannot change theme of diff editor

### ISSUE THREAD

**Issue by loilo** [microsoft/monaco-editor#1832]
This seems to be a regression of #387.

---

**monaco-editor version:** 0.20.0
**Browser:** discovered in Chrome, tested in Firefox as well
**OS:** macOS 10.14.6
**Playground code that reproduces the issue:** —

---

> 1. Try to reproduce in VS Code [...]
> 2. Otherwise, provide steps that reproduce the problem in VS Code web [...]

I can't because I don't know how to access the equivalent APIs.

---

> 3. Otherwise, provide steps that reproduce the problem at the Monaco Editor homepage

Here you go:

The theme of the diff editor on the Monaco Editor homepage should be adjustable with the following snippet:

```js
diffEditor.updateOptions({
  theme: 'vs-dark'
});
```

But this does not apply the new theme. To actually do that, I had to call the `setTheme` method on the private theme service:

```js
diffEditor._themeService.setTheme('vs-dark');
```

**Comment by alexdima** [comment]
A complete repro:
```js
const editor = monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript"
});
editor.updateOptions({ theme: 'vs-dark' });
```

A workaround is to use the API `monaco.editor.setTheme('vs-dark');`
