### ISSUE TITLE
Add API for checking if completion is active

### ISSUE THREAD

**Issue by maxim-belugin** [microsoft/monaco-editor#1836]
Please make a documented way  to check whether code completion popup is active or not.

see also this [question](https://github.com/microsoft/monaco-editor/issues/165)

I want to integrate monaco editor into existing application and  it already processed Esc key to close the form. In my code I want the following behaviour: 
  1. If code completion is currently opened I want Esc key to close code completion (and prevent default behavior from topmost container)
  2. If code completion is not opened I want Esc key to close the form  

Adding own command seem not working for me since I want to prevent default behavior of container, not add my own behavior into editor.

**Comment by alexdima** [comment]
Escape is used in the editor for a lot more things than closing the suggest widget:
* canceling a rename (F2)
* closing the find widget (Ctrl+F)
* closing the inline error view (F8)
* closing the embedded code editor of peek definition/references
* removing multiple cursors
* collapsing the selection
etc etc etc

If you wish to do something with escape, I can recommend to add a keydown listener to the editor's container. The editor will stop propagation of the Escape key down events it consumes, so if you receive a keydown event, it means the editor didn't handle it.

Alternatively, you can add a command for Escape with a `when` context that excludes all other cases.

**Comment by maxim-belugin** [comment]
Hello, 

My current code is the following, and my task is not to pervent **editor** proprocessing esc, but prevent one of ancestor containers to process.  But only if monaco did not consume it for it's own  needs.

Now we prevent it always:

```js
 function keyDownHandler(evt) {
            // Allow enter to create new line in monaco editor
            if ($dyn.util.isShortcutKeyPressed(evt, { keyCode: $dyn.ui.KeyCodes.enter })) {
                // Prevent the keyDown from bubbling for the Enter key so the form level enter shortcut is prevented. 
                // See documentation on this behavior in $dyn.ui.Control constructor. 
                evt.stopPropagation();
                $dyn.log.stopPropagation && $dyn.log.stopPropagation('Prevent form level Enter shortcut.');
            }
                // Esc will cancel suggestion instead of exiting the form.
            else if ($dyn.util.isShortcutKeyPressed(evt, { keyCode: $dyn.ui.KeyCodes.esc })) {
                evt.stopPropagation();
                $dyn.log.stopPropagation && $dyn.log.stopPropagation('Prevent form level ESC shortcut.');
            }
        }
```

**Comment by alexdima** [comment]
IMHO you have two options:
1. add a command to the editor and use `when` conditions, e.g.
```
editor.addCommand(monaco.KeyCode.Escape, function() {
    alert('my command is executing and the suggest widget is not visible!');
}, '!suggestWidgetVisible')
```
2. listen on the editor container for `keydown` events. You will receive only keydown events which have not been handled. If the suggest widget is visible, and Escape is pressed, the editor will handle the keydown event and will call `e.stopPropagation()` so the event will not reach your container.
