### ISSUE TITLE
[JSON] Support for editor.create(element, { model }) in test/index.html

### ISSUE THREAD

**Issue by WhileTrueEndWhile** [microsoft/monaco-editor#1837]
**Feature Request**

It was pretty easy to clone and run [monaco-json](https://github.com/microsoft/monaco-json).

But I could not create a **model-based** test HTML (see [test/index.html](https://github.com/microsoft/monaco-json/blob/master/test/index.html)) using `editor.create(element, { model })`  instead of `editor.create(element, { value })`:

<details>
<summary>test/model-based-index.html</summary>
<p>

```HTML
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link
      rel="stylesheet"
      data-name="vs/editor/editor.main"
      href="../node_modules/monaco-editor-core/dev/vs/editor/editor.main.css"
    />
  </head>
  <body>
    <h2>Monaco Editor JSON test page</h2>
    <div
      id="container"
      style="width:800px;height:600px;border:1px solid grey"
    ></div>

    <script>
      // Loading basic-languages to get the json language definition
      var paths = {
        "vs/basic-languages": "../node_modules/monaco-languages/release/dev",
        "vs/language/json": "../release/dev",
        vs: "../node_modules/monaco-editor-core/dev/vs"
      };
      if (document.location.protocol === "http:") {
        // Add support for running local http server
        let testIndex = document.location.pathname.indexOf("/test/");
        if (testIndex !== -1) {
          let prefix = document.location.pathname.substr(0, testIndex);
          paths["vs/language/json"] = prefix + "/release/dev";
        }
      }
      var require = {
        paths: paths
      };
    </script>
    <script src="../node_modules/monaco-editor-core/dev/vs/loader.js"></script>
    <script src="../node_modules/monaco-editor-core/dev/vs/editor/editor.main.nls.js"></script>
    <script src="../node_modules/monaco-editor-core/dev/vs/editor/editor.main.js"></script>

    <script>
      require([
        "vs/basic-languages/monaco.contribution",
        "vs/language/json/monaco.contribution"
      ], function() {
        var modelUri = "test://model.json";
        var schema = { "type": "object" };
        var data = {};
        var jsonDefaults = monaco.languages.json.jsonDefaults;
        var options = {
          validate: true,
          schemas: [
            {
              uri: modelUri,
              fileMatch: [modelUri],
              schema: schema
            }
          ]
        };
        jsonDefaults.setDiagnosticsOptions(options);
        var uri = monaco.Uri.parse(modelUri);
        var editor = monaco.editor;
        var model = editor.createModel(data, "json", uri);
        // --------------------------------------------------------
        var instance = editor.create(viewElement, { model: model });
        // --------------------------------------------------------
      });
    </script>
  </body>
</html>
```
</p>
</details>

I get the following error message:

```
TypeError: factory.create is not a function
```
<details>
<summary>at vs/editor/common/model/textModel.ts:50:16</summary>
<p>

```JavaScript
export function createTextBuffer(value: string | model.ITextBufferFactory, defaultEOL: model.DefaultEndOfLine): model.ITextBuffer {
    const factory = (typeof value === 'string' ? createTextBufferFactory(value) : value);
    return factory.create(defaultEOL);
//         ~~~~~~~~~~~~~~
}
```
</p>
</details>

<details>
<summary>I tried to solve the problem by adding...</summary>
<p>

```JavaScript
"vscode-textbuffer": "1.0.0"
```
... to [package.json](https://github.com/microsoft/monaco-json/blob/master/package.json#L29), ...

```JavaScript
{
    name: 'vscode-textbufffer',
    location: path.join(REPO_ROOT, 'node_modules/vscode-textbuffer/lib'),
    main: 'index'
}
```

... to [bundle.js](https://github.com/microsoft/monaco-json/blob/master/scripts/bundle.js#L57) and ...

```JavaScript
'vscode-textbuffer/lib': 'vscode-textbufffer'
```
to [release.js](https://github.com/microsoft/monaco-json/blob/master/scripts/release.js#L31) ...

... which seems to be required to use the model-based API, but the error still remains.

</p>
</details>

Any ideas?

Thanks in advance.

**Comment by alexdima** [comment]
Running `monaco-json` from source is a bit tricky and difficult, sorry about that. Here are the steps:

1. clone `https://github.com/microsoft/monaco-json`
2. run `npm install`
3. run `npm run prepublishOnly`
4. open `~/test/index.html`

If a change is made to a `.ts` file, it is unfortunately necessary again to execute `npm run prepublishOnly`. This is not ideal, and I appologize for that. But may I ask what do you plan to do in `monaco-json` since it is just mostly "glue code"?

(fyi @aeschli)

**Comment by WhileTrueEndWhile** [comment]
Thanks a lot. It works now. It was my all my fault.
My `var data = {}` caused this error. It should be `var data = "{}"`.
See also https://github.com/WhileTrueEndWhile/monaco-json/commit/4bb288c3e2c2351a71f5ef568322cf5b44fcb8c5.
My test setup is ready and I'm happy :)
