### ISSUE TITLE
Add support for importing scoped packages

### ISSUE THREAD

**Issue by ErkoKnoll** [microsoft/monaco-editor#1838]
Not sure if it is a bug or missing feature, but there does not seem to be a native way to define imports via `addExtraLib` to use scoped packages.

Using regular way of declaring imports works:
`monacoEditor.languages.typescript.typescriptDefaults.addExtraLib(content, 'file:///node_modules/@types/test/file.d.ts')` for example.

But when I want to use a scoped package, for example `@scope/test/file` then setting the path as
`file:///node_modules/@types/@scope/test/file.d.ts` does not seem to work, nor does work the following: `file:///node_modules/@scope/test/file.d.ts`

Latter also should require modifying compiler options to use `typeRoots` option as following:
```
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
            target: monaco.languages.typescript.ScriptTarget.ES2016,
            module: monaco.languages.typescript.ModuleKind.ES2015,
            allowNonTsExtensions: true,
            noLib: true,
            sourceMap: true,
            lib: ['es2018'],
            typeRoots: ['node_modules/@types', 'node_modules/@scope']
        });
```

but I also noticed that `typeRoots` actually does not seem to do anything, if I remove `node_modules/@types` or/and add something extra, it still continues to look up types only from `node_modules/@types` path.

The only way I managed to get `@scope/test/file` resolved were if I wrapped the type definition inside `declare module '@scope/test/file' { ... }`.

Is there a better way of doing this? Because using existing type definitions for scoped packages have to be wrapped accordingly which just seems excessive.

**Comment by alexdima** [comment]
I have to be honest and say that you already appear to know more about how this works than I do, so maybe @orta has more ideas, but, honestly, I have no idea how the TS language service decides to look for imports.

Perhaps you can find more documentation on the TS project itself at http://www.typescriptlang.org/. , but this appears to be a question for the TS team more than the Monaco Editor...

**Comment by orta** [comment]
The folder structure for a scoped package doesn't include the extra `@` because that's not a legit npm identifier (and couldn't be deployed to npm), here's a working example: `@babel/core` -> `@types/babel__core` - https://yarnpkg.com/package/@types/babel__core
