### ISSUE TITLE
how to change the editor's locale?

### ISSUE THREAD

**Issue by lin-chao** [Microsoft/monaco-editor#185]
hi 

i want to know how to change editor's locale?

eg: change en-us to zh-cn

thanks

**Comment by alexandrudima** [comment]
Please see https://github.com/Microsoft/monaco-editor-samples/tree/master/sample-localized

**Comment by lin-chao** [comment]
get~

thanks

**Comment by nhuurnink** [comment]
Link is broken, any suggestions?

**Comment by tom-s** [comment]
Also how could we achieve localization with the esm import ?

**Comment by FAKER-A** [comment]
> hi
> 
> i want to know how to change editor's locale?
> 
> eg: change en-us to zh-cn
> 
> thanks

你好，我想问一下你知道 monaco-editor 在esm版本下如何汉化吗？

**Comment by kingolio** [comment]
> Link is broken, any suggestions?

It's now under [https://github.com/microsoft/monaco-editor-samples/blob/master/browser-amd-localized/index.html](https://github.com/microsoft/monaco-editor-samples/blob/master/browser-amd-localized/index.html)
