### ISSUE TITLE
Letters with diacritics are incorrectly doubled when using the "US International - PC" macOS keyboard layout

### ISSUE THREAD

**Issue by pquentin** [microsoft/monaco-editor#1851]
**monaco-editor version:** 0.20.0
**Browser:** Firefox 73.0.1, but **not** Safari 13.0.5/Chrome 80.0.
**OS:** macOS 10.15.3, with the "US International - PC" keyboard layout
**Playground code that reproduces the issue:** N/A

Steps to reproduce:

 * On macOS, use the "US International - PC" keyboard layout
 * Type the `'` dead key, then `e`

Expected results:

I would expect to see `é`, as that's how that keyboard layout works everywhere else.

What happens instead:

I see the letter twice: `éé`.

Does not reproduce in https://vscode-web-test-playground.azurewebsites.net/, but reproduces in https://microsoft.github.io/monaco-editor/ (0.20.0 at the time of writing) and https://microsoft.github.io/monaco-editor/playground.html. The issue also occurs in Google Colab, where I noticed it originally.

Related issues: https://github.com/microsoft/monaco-editor/issues/1524, https://github.com/microsoft/monaco-editor/issues/1794 and https://github.com/microsoft/vscode/issues/42251.

**Comment by MaximeCheramy** [comment]
I can also reproduce with Firefox on Linux Ubuntu 20.04.

**Comment by NicoK** [comment]
Same on Firefox, openSUSE Tumbleweed x86_64, German with dead keys keyboard layout

**Comment by alexdima** [comment]
I have verified that his is fixed on master with the fix for https://github.com/microsoft/vscode/issues/106392
