### ISSUE TITLE
Cannot disable fetching of the "$schema" field when editing JSON

### ISSUE THREAD

**Issue by Nic0S** [microsoft/monaco-editor#1852]
When using the Monaco editor for JSON, I'm having trouble preventing it from trying to fetch a schema from the URL in the $schema field. I am supplying a schema manually, so I'd like "$schema" to be completely ignored.

This can be replicated here: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

Steps to reproduce:

Configure the setting enableSchemaRequest to 'false' on the left side and run:
```
...
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    enableSchemaRequest: false,
    validate: true,
...
```

Paste this content into the editor:
```
{
    "$schema": "do.not.fetch"
}
```

This results in the error message:

> Unable to load schema from '/do.not.fetch'. No schema request service available

Configuring enableSchemaRequest to 'true' results in:

> Unable to load schema from '/do.not.fetch': Failed to fetch.

Is it possible to simply ignore the $schema field?

**Comment by zammit123** [comment]
This is still an issue... is there a workaround for this?

**Comment by aeschli** [comment]
The latest vscode-json-languageservice/ has a setting for it: https://github.com/microsoft/vscode-json-languageservice/blob/9ac8f6ebfa797bfb5a0a1398a3b8b605b1c7ce1f/src/jsonLanguageTypes.ts#L141

Need to be adopted by monaco-json

**Comment by zammit123** [comment]
Until it is adopted, is there a workaround or this a bug that only allows external schemas to be loaded?

**Comment by aeschli** [comment]
A workaround is to add a dummy schema to the hardcoded schemas:

```
var jsonCode = [
    '{',
    '    "$schema": "do.not.load"',
    "}"
].join('\n');
var modelUri = monaco.Uri.parse("a://b/foo.json"); 
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "do.not.load",
        schema: {}
    }]
});

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```

**Comment by zammit123** [comment]
@aeschli I've been trying to get this workaround working with react but I can't seem to fix it using your example above.

Just to clarify:
- I request a json schema from an API which returns a blob which I need to parse.
- I am then trying to use the schema like this:

`
schema.$schema = 'do.not.load';
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
      validate: true,
      schemas: [{
        uri: "do.not.load",
        schema: schema
      }],
      enableSchemaRequest: false
    });
`

I don't full understand from your example above, are you suggesting having a local file with the schema? In my case I request the schema so it changes.
`var modelUri = monaco.Uri.parse("a://b/foo.json"); `

**Comment by aeschli** [comment]
Here's what I understand
- You load a schema from some some place: `schema`.
- that schema has a $schema which can not be resolved, so you set it to `do.not.load'`
- the you use the schema to validate a document with the schema

`schema.$schema` is the schema of the schema and not required to validate the document (only if you validate the schema)
You can leave it there, or delete it.

Can you make a more complete playground example that shows the problem?

**Comment by aeschli** [comment]
Closing as more information is required.
