### ISSUE TITLE
default hover event prevents page scroll when multiple editor instances in one page

### ISSUE THREAD

**Issue by gerard0315** [microsoft/monaco-editor#1853]
I'm currently implementing a diff tool for notebook using monaco.
It seems that the default editor scroll event is overwriting the scroll event on the browser level.
for example if i hover the cursor in one cell and it immediately changes to the text selection style, which prevents the default browser page scroll event

this is my editor option

```
this.monacoEditor = monaco.editor.create(document.getElementById(_id), {
              language,
              lineNumbers: 'on',
              scrollBeyondLastLine: false,
              readOnly: true,
              fontSize: '14px',
              lineNumbersMinChars: 3,
              lineDecorationsWidth: 10,
              dragAndDrop: false,
              scrollbar: {
                useShadows: false,
                verticalHasArrows: true,
                horizontalHasArrows: true,
                vertical: 'hidden',
                horizontal: 'hidden',
                verticalScrollbarSize: 0,
                horizontalScrollbarSize: 17
              },
              minimap: {
                enabled: false
              }
            });
```

**monaco-editor version:** 0.20.0
**Browser: ** Chrome 80.0.3987.122
**OS: ** MacOS 10.15.3

**Comment by alexdima** [comment]
@gerard0315 Did you try `editor.scrollbar.alwaysConsumeMouseWheel: false` ?

**Comment by gerard0315** [comment]
> editor.scrollbar.alwaysConsumeMouseWheel: false

thanks, it worked

**Comment by Priyank780** [comment]
@alexdima I tried with editor.scrollbar.alwaysConsumeMouseWheel: false option but looks like there are two wheel events binded with default configuration,

![image](https://user-images.githubusercontent.com/635239/78627030-19c1df00-78ae-11ea-9a55-ba46de92bc23.png)

And as per 0.20.0 version code, I need to turn off editor.scrollbar.handleMouseWheel option as well to stop listening mouse wheel scrolling event from scrollableElements.js.

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html#scrollbar documentation needs to be updated accordingly. Currently, it doesn't have any specification mentioned.

Ref code of scrollableElements.js:
`// -------------------- mouse wheel scrolling --------------------
    AbstractScrollableElement.prototype._setListeningToMouseWheel = function (shouldListen) {
        var _this = this;
        var isListening = (this._mouseWheelToDispose.length > 0);
        if (isListening === shouldListen) {
            // No change
            return;
        }
        // Stop listening (if necessary)
        this._mouseWheelToDispose = dispose(this._mouseWheelToDispose);
        // Start listening (if necessary)
        if (shouldListen) {
            var onMouseWheel = function (browserEvent) {
                _this._onMouseWheel(new StandardWheelEvent(browserEvent));
            };
            this._mouseWheelToDispose.push(dom.addDisposableListener(this._listenOnDomNode, isEdgeOrIE ? 'mousewheel' : 'wheel', onMouseWheel, { passive: false }));
        }
    };`

**Comment by alexdima** [comment]
@Priyank780 
* The option `scrollbar.handleMouseWheel`: When it is set to `true` (the default), the editor will listen to mouse wheel events and call `preventDefault()` on those events as prescribed by `alwaysConsumeMouseWheel`. When it is set to `false`, the editor will not listen to mouse wheel events at all.
* The option `alwaysConsumeMouseWheel`: When it is set to `true` (the default), the editor will call `preventDefault()` on all mouse wheel events. When it is set to `false`, the editor will only call `preventDefault()` if it could scroll in the direction indicated by the mouse wheel.

If you wish to improve the doc, PR welcome in vscode sources.
