### ISSUE TITLE
automaticLayout broken on master?

### ISSUE THREAD

**Issue by orta** [microsoft/monaco-editor#1855]
Repro: 

- Working:  Drag the sidebar left of right on [3.7.5](http://www.typescriptlang.org/v2/play?ts=3.7.5)
- Not Working: [3.8.3](http://www.typescriptlang.org/v2/play?ts=3.8.3) 

3.7.5 is from about a month ago, 3.8.3 is from yesterday.

They both have the same outer code for the playground, but refer to different Monaco-editors and Monaco TypeScripts. I'll know I can move off `automaticLayout` by telling the editor when the sidebar changes, but I'll leave it this way for a few days so there's a a working repro.

**Comment by alexdima** [comment]
It is possible that https://github.com/microsoft/vscode/pull/90111 has broken things. On `master` the editor now tries to use a `MutationObserver` to decide if it should rescan the container dom node.

Do you have a pointer to the outer code?

**Comment by orta** [comment]
The code is a little complex because there's a few moving parts...

- [This is the playground page](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/templates/play.tsx#L62) which grabs monaco, then [creates for a typescript-sandbox](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/templates/play.tsx#L80)
- The sandbox [creates and sets up a monaco](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/sandbox/src/index.ts#L106-L113) instance with [these settings](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/sandbox/src/index.ts#L49)
- The editor's containing div is [then edited via it's CSS directly](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/index.ts#L212-L213) inside the playground's JS

Monaco lives in a `#monaco-editor-embed` which is a child of `#playground-container` (because it also has the toolbar of the same width) - so changes in width are applied 2 divs up, and then the toolbar and monaco would be resized to fit using CSS block's usual "fill the whole thing horizontally"

**Comment by alexdima** [comment]
Aha! I believe this is due to the usage of `calc` here -- https://github.com/microsoft/TypeScript-Website/blob/0babe4b37d3d82485138d908065798926acbd018/packages/playground/src/index.ts#L212-L213

So the height of the container can change without any properties being changed...

**Comment by orta** [comment]
Nice sleuthing, I'm open to this issue being closed - I'm not really sure what else you could do from Monaco's side for something like this other than have an optional fallback to the old mode

**Comment by alexdima** [comment]
Well, I think we're using the wrong concept. I just found https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by nrayburn-tech** [comment]
Resize Observer is the best way to do it, but lacks Safari support and I think at the time Monaco was still supporting IE, which also doesn’t support Resize Observer.
Maybe we should implement Resize Observer and then use the interval timer as a fallback for Safari?

**Comment by rcjsuen** [comment]
See #1884 for another issue that seems to be related to `automaticLayout`.

**Comment by nrayburn-tech** [comment]
I’ll try to get a PR submitted this weekend to work as described above.

**Comment by aeremin** [comment]
Any chance for a new bugfix release including the fix above?
AFAIU version in master branch of this repo still has this problem (but maybe I don't understand how   microsoft/vscode and  microsoft/monaco-editor relation works).
