### ISSUE TITLE
More descriptive announcement for the accessibility help dialog for screen readers

### ISSUE THREAD

**Issue by getroyer** [microsoft/monaco-editor#1856]
Azure Notebooks at Microsoft is using Monaco Editor and I am working on an accessibility bug which came up during accessibility testing.

The bug is regarding the accessibility help dialog brought up by pressing alt-f1 in an editor while using the screen reader. The bug creator expected the screen reader to announce the dialog: "accessibility window opened, scroll down to read details", followed by the data in the editor.

If you can access the links:
bug -
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1059972/

He or she cited the following MAS references:
MAS 1.3.1
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

MAS 2.4.2:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={c74ff881-82b6-4401-92cf-8919f9bffaf2}

**Comment by alexdima** [comment]
Alt+F1 reads a message specifically built for users with Screen Readers. The message is 100% intended for users of screen readers. There is no need to do meta announcements like "there is now a dialog opened for you", since the dialog itself is the message. In other words, the issue makes no sense.
