### ISSUE TITLE
Triggering command from hover popup not working (command in md link not recognized)

### ISSUE THREAD

**Issue by N8th8n8el** [microsoft/monaco-editor#1857]
I am trying to get a command to fire when clicking on a markdown link inside a hover-popup.
For the link I tried using `command:id` as described in #1257.
This does not seem to work though, the text is not clickable.
Is this a bug or am I missing something?
Thanks.

**monaco-editor version:** 0.20.0
**Browser:**  Safari 13.0.5 (15608.5.11) and Chrome 80.0.3987.132 (Official Build) (64-bit)
**OS:** macOS 10.15.3
**Playground code that reproduces the issue:**

```js
monaco.languages.register({ id: 'mySpecialLanguage' });

const editor = monaco.editor.create(document.getElementById("container"), {
    value: '\n\nHover over this text',
    language: 'mySpecialLanguage'
});

const commandId = editor.addCommand(0, () => alert("working"));

monaco.languages.registerHoverProvider('mySpecialLanguage', {
    provideHover: function (model, position) {
        return {
            range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
            contents: [
                { value: `**Test Command with id ${commandId}**` },
                { value: `[Execute](command:${commandId})` },
                { value: `[Google](http://www.google.com)` }
            ]
        }
    }
});
```

**Comment by alexdima** [comment]
There are two problems:
- the hover needs to be marked as trusted (I don't know why... :))
- dynamic commands cannot be opened via the opener service because of an implementation detail.

So your sample should be:
```js
monaco.languages.register({ id: 'mySpecialLanguage' });

const editor = monaco.editor.create(document.getElementById("container"), {
    value: '\n\nHover over this text',
    language: 'mySpecialLanguage'
});

const commandId = editor.addCommand(0, () => alert("working"));

monaco.languages.registerHoverProvider('mySpecialLanguage', {
    provideHover: function (model, position) {
        return {
            range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
            contents: [
                { isTrusted:true, value: `**Test Command with id ${commandId}**` },
                { isTrusted:true, value: `[Execute](command:${commandId})` },
                { isTrusted:true, value: `[Google](http://www.google.com)` }
            ]
        }
    }
});
```

But still, the command is not found when clicked.

**Comment by N8th8n8el** [comment]
Thanks for the quick response. Is there a way to create a static command? If so, what is the difference between a dynamic and a static command?

**Comment by alexdima** [comment]
This is just some debt... It used to be that commands were scoped per editor instance, but now all commands are global. That explains the weird `addCommand` method that exists on an editor instance... In order to maintain compatibility, the standalone editor has this notion of a dynamic command that it uses...

There is no API to define a global, regular command.. So you would need to go to JS 

```
const CommandRegistry = require('vs/platform/commands/common/commands').CommandsRegistry;
CommandsRegistry.registerCommand('myId', () => alert('hello'));
```

**Comment by N8th8n8el** [comment]
This workaround seems to work, thanks!
