### ISSUE TITLE
tabSize has been ignored when using Template Literals

### ISSUE THREAD

**Issue by moshfeu** [microsoft/monaco-editor#1859]
When I create a model with content as Template Literal the `tabSize` has been ignored even with `detectIndentation: false`

**monaco-editor version:** latest
**Browser:** Chrome
**OS:** mac os 10.15
**Playground code that reproduces the issue:**

```js
var originalModel = monaco.editor.createModel(
`<h1>
  title
</h1>`,
"text/html"
);

// tabSize respect this version
// var modifiedModel = monaco.editor.createModel(
//   "<h2>\n\ttitle\n</h2>",
//   "text/html"
// );

var modifiedModel = monaco.editor.createModel(
`<h2>
  title
</h2>`,
"text/html"
);

var diffEditor = monaco.editor.createDiffEditor(
    document.getElementById("container")
);
diffEditor.setModel({
    original: originalModel,
    modified: modifiedModel
});
diffEditor
    .getModifiedEditor()
    .getModel()
    .updateOptions({ tabSize: 10, detectIndentation: false });
```
https://codesandbox.io/s/solitary-forest-34eif

**Comment by alexdima** [comment]
How exactly is that not working? When I press `tab`, I get 10 spaces inserted, so `updateOptions` appears to work fine.

**Comment by moshfeu** [comment]
Thank you for the response. I meant to the initial state. I was expecting that the code in the editor will be 

```html
<h2>
          title
</h2>
```
The way it would when I use the commented code 

```javascript
 var modifiedModel = monaco.editor.createModel(
   "<h2>\n\ttitle\n</h2>",
   "text/html"
 );
```

**Comment by alexdima** [comment]
OK, I think I understand what you want. But a call to `updateOptions` does not edit the model and does not replace the 2 space indentation with 10 spaces. The call to `updateOptions` just changes the `tabSize` of the model, such that further edits will use the new tab size.
