### ISSUE TITLE
please publish monaco type definitions to typings registry

### ISSUE THREAD

**Issue by prasikumbhare** [microsoft/monaco-editor#186]
if i run the following command to lookup and install typedefinitions for monaco editor, it doesn't return anything

typings search monaco-editor
typings install monaco-editor

Usually, for popular projects, we do find typings e.g. typings search ace does return typings for ace-editor. Similar should be provided for monaco as well.

**Comment by alexandrudima** [comment]
@prasikumbhare Do you know how I can do that? https://github.com/typings/typings only shows how to use typings, I don't know what I need to do on my side?

**Comment by npenin** [comment]
AFAIK, it's pretty the same as npm publish

**Comment by prasikumbhare** [comment]
@alexandrudima  

This is what [npm/thypings](https://www.npmjs.com/package/typings) mentions about publishing :
The [public registry ](https://github.com/typings/registry) is maintained by the community, and is used to resolve official type definitions for JavaScript packages.

**Comment by alexdima** [comment]
The typings are now shipping with the npm package
