### ISSUE TITLE
Does addExtraLib support .ts file? Or should I use createModel instead

### ISSUE THREAD

**Issue by RuoniWang** [microsoft/monaco-editor#1863]
I am trying to import external files as modules and accidentally discovered that addExtraLib works as well for my external .ts files (not definition files). 

The standard practice seems to be to use addExtraLib for .d.ts files and use createModel for non definition files. But for createModel, we need to refresh the secondary model every 50 seconds to "keep it working"; so addExtralib seems to be more lightweight. Is there any danger/downsides to using it?

**Comment by alexdima** [comment]
You can use `addExtraLib`.

Or you can continue using a model and `monaco.languages.typescript.typescriptDefaults.setEagerModelSync` rather than changing it all the time.
