### ISSUE TITLE
Setting ScrollType to smooth does not give expected results

### ISSUE THREAD

**Issue by bcolloran** [microsoft/monaco-editor#1865]
**monaco-editor version:** 0.20.0 (which is the version at https://microsoft.github.io/monaco-editor/playground.html as of 2020-03-10)

**Browser:** tested Chromium and Firefox

**OS:** Linux

**Playground code that reproduces the issue:**

the following playground code is adapted from:
https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-revealing-a-position

It fires `revealPositionInCenter` with `monaco.editor.ScrollType.Smooth` every 1.5s.

The expected behavior is that the editor will scroll smoothly between locations; the observed behavior is that it jumps from one location to the next.

```js
var jsCodeArr = [
	'// ------------------------------',
	'// ------------------------------',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};',
	'',
	''
];

jsCodeArr = jsCodeArr.concat(jsCodeArr.slice(0));
jsCodeArr = jsCodeArr.concat(jsCodeArr.slice(0));
jsCodeArr = jsCodeArr.concat(jsCodeArr.slice(0));

jsCodeArr[49] += 'And this is some long line. And this is some long line. And this is some long line. And this is some long line. And this is some long line. ';

var editor = monaco.editor.create(document.getElementById("container"), {
    value: jsCodeArr.join('\n'),
    language: "javascript"
});

setInterval(
    () => {
        lineNumber = Math.ceil(Math.random()*90)
        column = Math.ceil(Math.random()*60)
        editor.revealPositionInCenter(
            { lineNumber, column },
            monaco.editor.ScrollType.Smooth
        );
    },
    1500)
```

**Comment by alexdima** [comment]
@bcolloran The reveal will be smooth or not based on that type but also based on the option `smoothScrolling`. So you would need to create the editor with `smoothScrolling: true`.
