### ISSUE TITLE
Allow using the tokenizer outside of the editor

### ISSUE THREAD

**Issue by buremba** [microsoft/monaco-editor#1868]
It would be great if Monaco can expose a method that allows us to run syntax highlighter outside of the editor. It would allow us to highlight our code in an easy way similar to `Codemirror.runMode`. Please see [https://codemirror.net/demo/runmode.html](https://codemirror.net/demo/runmode.html ) as an example.

**Comment by spahnke** [comment]
You can already do that, see #1521

**Comment by buremba** [comment]
Hmm, thanks for the info @spahnke! What should the best approach in order to understand the codebase of Monaco? It looks like we only have the [API docs](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#colorize), right?

**Comment by spahnke** [comment]
Yeah, I mostly browse the API docs, the code completion for monaco, and the issues here if I have a question. The [samples repository](https://github.com/Microsoft/monaco-editor-samples/) and the [playground](https://microsoft.github.io/monaco-editor/playground.html) can also be helpful resources.

**Comment by buremba** [comment]
Thanks!
