### ISSUE TITLE
Manually trigger an downarrow keyboard event in Monaco Editor?

### ISSUE THREAD

**Issue by freddyboucher** [microsoft/monaco-editor#1872]
Hi,
I already posted this question on [Stackoverflow](https://stackoverflow.com/questions/60648444/how-to-manually-trigger-an-downarrow-keyboard-event-in-monaco-editor) but I haven't received any pertinent answer yet.

So I'm in charge of testing (with selenium) a Monaco editor field in our webapp. I know how to trigger the completions dropdown with:
`editor.trigger('', 'editor.action.triggerSuggest')`

But the completion list is big and I'd like to navigate in this list by using the downarrow key. How can I fire this event? I tried with no luck:
`editor.trigger('', 'type', monaco.KeyCode.DownArrow)`

<img width="680" alt="7B90u" src="https://user-images.githubusercontent.com/695120/76712552-269b5900-676e-11ea-89f3-ba9379d3a661.png">

Thank you

**Comment by alexdima** [comment]
I think you could try to create an arrow down key event in selenium...

You could also try `editor.trigger('', 'selectNextSuggestion')`.

**Comment by freddyboucher** [comment]
> editor.trigger('', 'selectNextSuggestion')

it totally works! Thanks @alexdima 

Just a side note, you can also fire selenium keyboard events on the embedded textarea of your Monaco element:
`$(monaco_element).find("textarea").get(0).sendKeys(Keys.ARROW_DOWN);`
