### ISSUE TITLE
Readonly tooltip ("Cannot edit in read-only editor") doesn't show up

### ISSUE THREAD

**Issue by kstarzyk** [microsoft/monaco-editor#1873]
**monaco-editor version:** 0.20.0
**Browser: Chrome**
**OS: macOS Mojave* 10.15.6*
**Playground code that reproduces the issue:**

```js
var editor = monaco.editor.create(document.getElementById("container"), {
	readOnly: true,
});

```

I wanted to edit the tooltip message (#1742) but it doesn't longer show up at all and I can't find any mention in change log about it (works in VSCode)

**Comment by alexdima** [comment]
It looks like that is caused by this -- https://github.com/microsoft/vscode/blob/265fb8d44e08006db32583781caf3b0367a364d2/src/vs/editor/browser/controller/textAreaHandler.ts#L132-L134

On the web, for screen readers and accessibility purposes we mark the input `<textarea>` with the attribute readonly for readonly editors. It appears that prevents any `input` from being produced, so we never receive an `input` or `type` event and we therefore don't render anything since the input is stopped earlier by the DOM itself.

**Comment by MichelJansson** [comment]
> It looks like that is caused by this -- https://github.com/microsoft/vscode/blob/265fb8d44e08006db32583781caf3b0367a364d2/src/vs/editor/browser/controller/textAreaHandler.ts#L132-L134

How do we get around this?
It's quite confusing now for a user to know that the editor is in read-only mode. No message, no "disabled look". It just doesn't work.

**Comment by spahnke** [comment]
This is a regression from 0.19.*

**Comment by Tayyab-athar** [comment]
any idea when will this fix?

**Comment by alexdima** [comment]
This can be done on your side pretty straight-forward. It is not clear we ever want to move away from the readonly `<textarea>` since that is correct from an accessibility point of view. e.g.:

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
    readOnly: true
});
editor.onKeyDown((e) => {
    if (!e.ctrlKey && !e.altKey && !e.metaKey) {
        if (usuallyProducesCharacter(e.keyCode)) {
            editor.trigger('', 'type', { text: 'nothing' });
        }
    }
});

/**
 * @param keyCode {monaco.KeyCode}
 */
function usuallyProducesCharacter(keyCode) {
    if (keyCode >= monaco.KeyCode.KEY_0 && keyCode <= monaco.KeyCode.KEY_9) {
        return true;
    }
    if (keyCode >= monaco.KeyCode.NUMPAD_0 && keyCode <= monaco.KeyCode.NUMPAD_9) {
        return true;
    }
    if (keyCode >= monaco.KeyCode.KEY_A && keyCode <= monaco.KeyCode.KEY_Z) {
        return true;
    }
    switch(keyCode) {
        // case monaco.KeyCode.Tab:
        case monaco.KeyCode.Enter:
        case monaco.KeyCode.Space:
        case monaco.KeyCode.Delete:
        case monaco.KeyCode.US_SEMICOLON:
        case monaco.KeyCode.US_EQUAL:
        case monaco.KeyCode.US_COMMA:
        case monaco.KeyCode.US_MINUS:
        case monaco.KeyCode.US_DOT:
        case monaco.KeyCode.US_SLASH:
        case monaco.KeyCode.US_BACKTICK:
        case monaco.KeyCode.US_OPEN_SQUARE_BRACKET:
        case monaco.KeyCode.US_BACKSLASH:
        case monaco.KeyCode.US_CLOSE_SQUARE_BRACKET:
        case monaco.KeyCode.US_QUOTE:
        case monaco.KeyCode.OEM_8:
        case monaco.KeyCode.OEM_102:
            return true;
    }
    return false;
}
```

**Comment by hediet** [comment]
This seems to work now:

![image](https://user-images.githubusercontent.com/2931520/180439137-85887374-29b8-4fcc-9c4d-1591abd13e58.png)
