### ISSUE TITLE
Adopt shared quick pick from platform (Go to line, Go to symbol, Commands)

### ISSUE THREAD

**Issue by bpasero** [microsoft/monaco-editor#1874]
This is a result of https://github.com/microsoft/vscode/issues/69955. A couple of quick pick providers will be shared between editor and workbench:
* Go to symbol in file
* Go to line
* Commands

As such the experience has slightly changed:
* there is now also a quick way to switch from one provider to the other in the standalone editor
* background color is the typical editor widget background
* visually looking the same (e.g. commands keybindings)

![Kapture 2020-03-16 at 15 20 51](https://user-images.githubusercontent.com/900690/76767374-cb7f5b80-6799-11ea-9ed8-e50d940413bf.gif)

All commands have been updated to point to the new solution and the old quick open has been deleted from the standalone editor.

//cc @alexdima @rebornix

**Comment by alexdima** [comment]
This is great, thank you! 🎉🎉🎉
