### ISSUE TITLE
Cannot scroll the page if the mouse is over at the editor

### ISSUE THREAD

**Issue by dominikfoldi** [microsoft/monaco-editor#1875]
**monaco-editor version:** 0.19.0 <=
**Browser:** all desktop browsers
**OS:** all desktop OSs

I have a page that has a much higher height than the monaco-editor in it, so I have to scroll the entire page to reach its bottom. I have used monaco-editor@0.18.1 first and I have been able to scroll the entire page when I have moved the mouse cursor on the top of the editor after it reached the last line of code.

Now I upgraded to 0.20.0 (then I tried 0.19.0 as well) and now if I use the mouse wheel when my cursor is on the top of the editor with the intention to scroll the entire page then it does not work. It scrolls down to the last line in the editor and nothing happens after. I have to move the cursor off from the editor to the side to be able to scroll the entire page. 

This is the case only on desktop, on mobile I am able to drag the entire page after the editor reached the last line of code in it.

You can try this at https://microsoft.github.io/monaco-editor/ on any desktop browser.

I do not know if it is a feature or a bug but as I said it was working until 0.18.1 and you have not put anything about this change into the changelog so I assume that this is a bug.

**Comment by stefandobre** [comment]
The following worked for me:
https://github.com/microsoft/monaco-editor/issues/1853#issuecomment-593484147

**Comment by dominikfoldi** [comment]
Thank you @stefandobre, it also worked for me!
