### ISSUE TITLE
monaco nested/embedded language not taking into account tokenize rules fully

### ISSUE THREAD

**Issue by boomyjee** [microsoft/monaco-editor#1877]
while searching through tokenizer rules for one to exit embedded mode only rules with nextEmbedded==@pop are considered

https://github.com/microsoft/vscode/blob/master/src/vs/editor/standalone/common/monarch/monarchLexer.ts#L492

that leads to impossibility to ignore comments/string literals while looking for closing rule, for example ignoring strings like <script>var someEmbeddedJS = "</script>"; var someMoreJs; </script>

the issue can be reproduced in playground official sample (html mode example):
https://microsoft.github.io/monaco-editor/monarch.html

![2020-03-19_08-25-25](https://user-images.githubusercontent.com/764058/77034516-44a9c900-69bb-11ea-869f-1f415c90c627.png)

**Comment by alexdima** [comment]
This is driven by popular languages, such as HTML, PHP or ASP/Razor where the leaving string forces leaving even if the embedded language is in an invalid construct. You can try this by yourself in a browser:

Just don't trust GitHub's or your editor's coloring and make an HTML file and try it out in any web browser:
```HTML
<script>var someEmbeddedJS = "</script>"; var someMoreJs; </script>
```
![image](https://user-images.githubusercontent.com/5047891/78257761-93e31400-74fa-11ea-935a-7388ef45b0f3.png)

### correct highlighting in the monaco editor:
![image](https://user-images.githubusercontent.com/5047891/78257833-af4e1f00-74fa-11ea-9cec-5954b81321c2.png)

### incorrect highlighting in GitHub:
![image](https://user-images.githubusercontent.com/5047891/78257903-c3921c00-74fa-11ea-9797-9e39506246a4.png)

### incorrect highlighting in VSCode:
![image](https://user-images.githubusercontent.com/5047891/78257944-d3116500-74fa-11ea-9113-755eb7f4eda1.png)

You can now report bugs to a ton of other software! :heart:

**Comment by boomyjee** [comment]
It's not a bug I just see around "</script>" tags. Rules inside embedded languages (except ones that do nextEmbedded=@pop) are ignored in monarch and it should be working according to documentation
https://microsoft.github.io/monaco-editor/monarch.html#nextEmbedded

there is a code in sample

`css_block: [`
`  [/[^"<]+/, ''],`
`  [/<\/style\s*>/, { token: '@rematch', next: '@pop', nextEmbedded: '@pop' }],`
`  [/"/, 'string', '@string' ],`
`  [/</, '']`
`]`

and all rules except second one are ignored during lexer process with current monaco version
why giving examples that don't work?
i struggled with my own syntax highlighter and debugged into monarch code
lexer should work as a state machine inside embedded language too (according to docs)

if you think that it is "as designed", pls correct docs
but i think that approach with _findLeavingNestedModeOffset is incorrect, lexer should tokenize code the same way inside nested mode, waiting for nextEmbedded: '@pop'
And it was working in previous versions of monaco here
https://github.com/microsoft/vscode/blob/6681a2a7d6317cb8945e5ab1a69f6b8cbbae5053/src/vs/editor/common/modes/monarch/monarchLexer.ts

That is why documentation is written as it is and with examples of correct handling closing tag inside a string. I see that you are the author of _findLeavingNestedModeOffset function, but don't take it personal.
