### ISSUE TITLE
Auto width editor Not Working in v0.20.0

### ISSUE THREAD

**Issue by M-Husein** [microsoft/monaco-editor#1878]
I have an html element that can change the width and the Monaco editor inside the div. When I resize the container dynamically version 0.20.0 doesn't automatically width.

**monaco-editor version:** 0.20.0
**Browser:** Chrome, Firefox
**OS:** Windows 10

**Comment by rators** [comment]
seems to be alot of issue with this release 0.20. same issue on my side.

**Comment by maltenuhn** [comment]
We've similarly had this issue and reverted to 0.19.3. Our implementation has a user-resizeable pane that contains the editor. On 0.19.3 this would resize the editor correctly, but bumping the dependency broke that.

**Comment by orta** [comment]
Likely related: https://github.com/microsoft/monaco-editor/issues/1855
