### ISSUE TITLE
Add ability to toggle standalone editor into a diff editor

### ISSUE THREAD

**Issue by buremba** [microsoft/monaco-editor#1881]
It would be great we if can just switch from `IStandaloneCodeEditor` to `IStandaloneDiffEditor` by providing an extra model that points to the `original`.

We use Monaco in our app and highlight the diffs as line decorators. When the user clicks the decorator we want to toggle a side editor that shows the diffs inside `IStandaloneDiffEditor`. I believe that this is not possible since `IStandaloneDiffEditor` works in standalone mode.

**Comment by alexdima** [comment]
It is possible to use the exact same model instance in an editor and then switch to a standalone editor and use the exact same model instance as the modified model of a diff editor, so I'm not sure what is missing?

**Comment by buremba** [comment]
@alexdima that's correct but destroying the `IStandaloneCodeEditor` and creating another `IStandaloneDiffEditor` is slow. I was wondering if there's any way to make Monaco reuse the `IStandaloneCodeEditor` and add the `DiffEditor` by computing the diff and shrinking the `IStandaloneCodeEditor`. Does that make sense?

**Comment by alexdima** [comment]
well, the diff editor is already implemented by taking two code editors and shrinking them, but it is not written to "adopt" another editor instance, it makes its own instances... I suppose you could try JS hacks to override diff editor methods to not allocate a new modified editor and to use your initial instance, but I'm very confused as to why you'd wanna do that.

When you say creating a standalone diff editor is slow, what exactly do you mean by slow? I guess depending what's acceptable for your application will drive the effort you want to put into it.

**Comment by buremba** [comment]
The `IStandaloneCodeEditor` performs expensive DOM operations since it creates an actual editor, destroying the DOM elements and creating another editor based on `IStandaloneCodeEditor` is not a cheap operation. It's probably not a common use-case so let me explain our use-case:

1. We have a web-based editor based on Monaco and I added line decorations that indicate the local changes as follows:
![image](https://user-images.githubusercontent.com/82745/78259494-75364a80-7505-11ea-8267-16b1108e3de7.png)

2. When the user clicks the line decorator, I basically destroy the `IStandaloneCodeEditor` and create an `IStandaloneDiffEditor` and highlight the change over there. When the user switches to the edit mode, I destroy the Diff Editor and use the `IStandaloneCodeEditor`.

It's probably no optimum way because the UX feels sluggish since I need to compute the diff again and add the line decorators, editor actions in each switch in addition to these expensive DOM operations.

VSCode has this feature out of the box with GIT extension but I couldn't find a way to make it work in Monaco. One other alternative is to enable the edit mode in DiffEditor but it's not really designed for edit mode as it adds overlay widgets and shows the 2 editors at the same time.

Is there any other way to implement the line decorators in Monaco similar to VSCode's line decorators as seen in the following screenshot?
![image](https://user-images.githubusercontent.com/82745/78261269-b3346e00-7507-11ea-8af5-df39351b7e38.png)

**Comment by alexdima** [comment]
I see two options to get that feature:

1. copy-paste the code from VS Code and adjust it.

2. implement from scratch by: 
  - adding a view zone which reserves 7 lines, 
  - adding an overlay widget that is rendered perfectly on top of that view zone (using view zone callbacks which indicate the `top` and `height`).
  - creating a diff editor and attaching it to the overlay widget
  - in the diff editor using the same model as the outer editor

Since this is not an issue with the Monaco Editor itself, I will close for now. Good luck!
