### ISSUE TITLE
fixedOverflowWidgets does not work for CodeActions

### ISSUE THREAD

**Issue by ErkoKnoll** [microsoft/monaco-editor#1882]
`fixedOverflowWidgets` works perfectly fine for regular suggestions when the container is wrapped inside `overflow: hidden`:
<img width="599" alt="Screenshot 2020-03-23 at 15 44 25" src="https://user-images.githubusercontent.com/9930079/77323238-9afd6b80-6d1d-11ea-8da7-a29f34974f84.png">
but the same behaviour is not applied to CodeActions that gets clipped:
<img width="279" alt="Screenshot 2020-03-23 at 15 44 51" src="https://user-images.githubusercontent.com/9930079/77323294-afd9ff00-6d1d-11ea-90aa-34f94a3ae283.png">
Code for reproducing in:
https://microsoft.github.io/monaco-editor/playground.html
HTML:
```
<div id="container" style="height:100px; border: 1px solid black; overflow: hidden"></div>
```
JS
```
class CodeActionProvider {
    provideCodeActions(document, range, context, token) {
        return {
            actions: [{
                title: 'Title 1'
            }, {
                title: 'Title 2'
            }, {
                title: 'Title 3'
            }]
        }
    }
}

monaco.languages.registerCodeActionProvider('typescript', new CodeActionProvider())

const editor = monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "typescript",
    fixedOverflowWidgets: true
});
```

**Comment by hediet** [comment]
Seems like this works now:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAKwAgAAAAAAAABBqQkHQ5NjdQS0WlU4WDmTRXNuTfnoBAhm7hasbKCuA-Xn2CWEcQNiZX9dThG1OFfyaPV4USyTHVhtH1m8s8uTCz6pM2f0H2D7T57PXZ_wgR6uPSl5wlkA50hFipB12Y_-ODz_9eEDOQ8qli7SEPihQCvLF4JSyGhKtTqOLDMgGHt0z1J4WN3gYtUsqgaglXjiwD88tPBwdBPFcmUnLmbY7ZkSVx2DkA7ns3MfkXuu2bW6_hrpxBmS3Wldh89cbH0sVFLXg4UAycDxPP-NoQJ15qSU02CriXyiaMaJCC7J1lyU1n2o79SHW_rfaUgFMKWaBDUc0AOCBjwH2zaFGZnSiruRNxi8PGu2uboDyqMPyL1Z2qGINGfWOv6KPkUZEl_kQyBEXBtMmnCy5e3xshqaDVsKOiT8Q-aJFQXCopl3OS_BBNySF5NTMayoSpObs_BxMWTH4tPf5IEjf7V-gwgEb07K1ZI_FXh8sfWpZIN7_NquKsdUp6aPNvU2ymm3_2lsOQA

![image](https://user-images.githubusercontent.com/2931520/221891146-277ae496-6f76-4687-9522-95161a2b1c0c.png)
