### ISSUE TITLE
setEOL not respected on future setValue's

### ISSUE THREAD

**Issue by asadm** [microsoft/monaco-editor#1886]
**monaco-editor version:** 0.20.0
**code that reproduces the issue:** https://jsfiddle.net/1bq8jk97/3/

Hi, 

If I do `editor.model.setEOL(0)` to set the EOL to `LF`, it fixes the existing code from `CRLF` to `LF` correctly. But any future `editor.model.setValue(codeWithCRLF)` does not 'normalize' the given code from `CRLF` to `LF` before setting it to the editor. 

Is this expected?
Thanks

**Comment by alexdima** [comment]
Yes, `setValue` is a very destructive call (kind of like a reset), it removes decorations, undo/redo buffer, and resets the EOL to the one of the passed in text.
