### ISSUE TITLE
Fetch completionItem documentation on demand

### ISSUE THREAD

**Issue by lmvco** [microsoft/monaco-editor#1887]
The `CompletionItem` object has a property `documentation` - [here](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html#documentation
) - which is used to provide additional information about the correspondent item. However, this information is sent in the `provideCompletionItems` response. Due to performance issues, it would be great to fetch also this information when the user clicks in the "Read more" icon.

![image](https://user-images.githubusercontent.com/1884391/77643226-e64e8e80-6f56-11ea-8b69-786f6a00f288.png)

**Comment by rcjsuen** [comment]
@lmvco I don't understand your question. Can you further explain what the problem is by using or changing the code in the [Completion provider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example)?

**Comment by lmvco** [comment]
In the [Completion provider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example), the documentation for each item is returned in the response of the `createDependencyProposals` function.  When these items are fetched from a remote service, considering a scenario of many items, the response can be very large. Hence, my suggestion is to expose a method in Monaco API to fetch the description when the user request it (when clicking in the "Read more" icon of a completion item)

**Comment by rcjsuen** [comment]
> Considering a scenario where these items are fetched from a remote service, if there are many items, the response can be very large. Hence, my suggestion is to expose a method in Monaco API to fetch the description when the user request it (when clicking in the "Read more" icon of a completion item)

@lmvco I think what you are looking for is already there. That is what the [`resolveCompletionItem` function ](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitemprovider.html#resolvecompletionitem) is for.

```JavaScript
function createDependencyProposals() {
    return [
        {
            label: '"lodash"',
            kind: monaco.languages.CompletionItemKind.Function,
            insertText: '"lodash": "*"'
        }
    ];
}


monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        return {
            suggestions: createDependencyProposals()
        };
    },

    resolveCompletionItem: function(model, position, item) {
        item.documentation = "Updated";
        return item;
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json"
});
```

**Comment by lmvco** [comment]
Thanks. It is exactly what I was looking for.
