### ISSUE TITLE
website: dropdown needs a background color

### ISSUE THREAD

**Issue by jasonLaster** [microsoft/monaco-editor#189]
![screen shot 2016-09-14 at 4 51 02 pm](https://cloud.githubusercontent.com/assets/254562/18529485/430ea2ea-7a9b-11e6-9a1c-160ff3a74705.png)

**Comment by alexandrudima** [comment]
@jasonLaster What browser / OS are you on?

**Comment by jasonLaster** [comment]
chrome / mac

**Comment by alexdima** [comment]
This has been fixed in the meantime.
