### ISSUE TITLE
Selected completion item is hidden

### ISSUE THREAD

**Issue by lmvco** [microsoft/monaco-editor#1894]
**monaco-editor version:** 0.20.0
**Browser:** Chome
**OS:** Windows
**Playground code that reproduces the issue:** https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

Repro steps:
1. Resize the window to be small
2. Open the example below
3. Type CTRL + Space to open the completion menu
4. Start navigate through the completion items using up/down keys

Result: While we are navigating in the visible items, we can see the current/selected item. However, after start selecting the overflow/hidden items, we are not able to see which item we are selecting (hence the completion does not work in this scenario)

![completion-items](https://user-images.githubusercontent.com/1884391/78058441-35922600-7380-11ea-8731-7d9cb5d89775.gif)

**Comment by spahnke** [comment]
I think that's because the playground uses iframes to display the editors. For other cases where that happens in a container on your site, you can set `fixedOverflowWidgets: true` in the editor creation settings.

**Comment by lmvco** [comment]
Yes, using `fixedOverflowWidgets` option with value `true` solved the issue. Thanks
