### ISSUE TITLE
IMarker should extend IRange

### ISSUE THREAD

**Issue by hawkerm** [microsoft/monaco-editor#1898]
**monaco-editor version:** 0.20.0

IMarker contains the same fields as IRange, but doesn't extend IRange.

**Comment by alexdima** [comment]
These types are generated from the vscode sources, and it is not the intent that an `IMarker` is passed around as an `IRange`. They have structural inheritance, but there is no logical inheritance, therefore I would not make `IMarker extends IRange`.
