### ISSUE TITLE
Intellisense tips like webstorm

### ISSUE THREAD

**Issue by GlauberF** [microsoft/monaco-editor#1900]
I don't know if Intellisense already exists, but I miss how the webstorm works. He gives tips to simplify / improve the code.

See the example below, ignore the simplicity, because I just want to show the tip that the webstorm with Intellisense brings.

Writing roughly, by a junior developer: (javascript/typescript)
```javascript
const t = 'teste';
const testFn = () => {
    if (t && t === 'teste') {
        return true;
    } else {
        return false;
    }
};
```
webstorm tip
![edit-1](https://user-images.githubusercontent.com/11314585/78395532-03710600-75c4-11ea-8309-b858fd999b02.png)

after the tip the webstorm gave:
![edit-2](https://user-images.githubusercontent.com/11314585/78395537-066bf680-75c4-11ea-9160-02a3e1ca5594.png)

how do you activate something like that in monaco?
or if you don’t have it, you can create a custom configuration to do this and how I would configure it and get the result suggested above by the webstorm.

**Comment by rcjsuen** [comment]
@GlauberF That looks similar to code actions I suppose. You can see a sample in my [online Dockerfile editor](https://rcjsuen.github.io/dockerfile-language-service/).

```Dockerfile
FROM alpine


run echo "Hello world!"
```

<img width="373" alt="image" src="https://user-images.githubusercontent.com/15629116/78397867-023dda00-75c0-11ea-9326-2800ed541226.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/15629116/78397881-09fd7e80-75c0-11ea-8643-ac58301ae3f5.png">

**Comment by GlauberF** [comment]
@rcjsuen  they are different things, in your case it is really a mistake and in my case it is not a mistake.
If I write the first way or the way the webstorm suggested me, both work.
However what I want is the part of Intellisense that gives me tips on how to simplify or improve something that would already work the way I am writing.
If not, how could I create these hint rules and how to create a rule for the example I put at the beginning of the issue.

@alexdima would you know how I can activate or do this?

**Comment by rcjsuen** [comment]
> @rcjsuen they are different things, in your case it is really a mistake and in my case it is not a mistake.
> If I write the first way or the way the webstorm suggested me, both work.
> However what I want is the part of Intellisense that gives me tips on how to simplify or improve something that would already work the way I am writing.
> If not, how could I create these hint rules and how to create a rule for the example I put at the beginning of the issue.

@GlauberF Sorry for being unclear. What I'm trying to say is code actions are what you want to implement to get what you want. I'm not trying to argue whether the code is good or bad and whether it is similar or not, my point is simply that the code actions feature will let you create a light bulb and prompt a user to make changes to the text in the editor. My screenshots were purely intended as a visual example of what is possible.

**Comment by GlauberF** [comment]
@rcjsuen I'm sorry, I didn't understand.
thinking about it then, how could I implement it in practice to get the result and tip of the webstorm, for the example above?

**Comment by rcjsuen** [comment]
@GlauberF You'll need to a) create some model markers and b) create the code action and its corresponding edit. Run this code in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html) to see a sample.

```JavaScript
monaco.languages.register({ id: 'demoLanguage' });
const uri = monaco.Uri.parse("inmemory://test");
monaco.languages.registerCodeActionProvider("demoLanguage", {
    provideCodeActions() {
        return {
            actions: [
                {
                    title: "lowercase",
                    edit: {
                        edits: [
                            {
                                resource: uri,
                                edit: {
                                    text: "abcde",
                                    range: {
                                        startLineNumber: 1,
                                        startColumn: 1,
                                        endLineNumber: 1,
                                        endColumn: 6,
                                    }
                                }
                            }
                        ]
                    }
                }
            ],
            dispose: () => {}
        }
    }
});

const model = monaco.editor.createModel("ABCDE", "demoLanguage", uri);
editor = monaco.editor.create(document.getElementById("container"), {
    model: model,
    lightbulb: {
        enabled: true
    },
});
monaco.editor.setModelMarkers(model, "owner", [
    {
        message: "Sample error message",
        severity: monaco.MarkerSeverity.Error,
        startLineNumber: 1,
        startColumn: 1,
        endLineNumber: 1,
        endColumn: 1,
    }
]);
```

**Comment by GlauberF** [comment]
@rcjsuen  sorry for my ignorance.

it seems that I started to understand, but I would really like some help to set up something, analyzing the scenario for which I opened the issue:

1 - How to set the following validation, it will not be for a custom language, but for javascript.
2 - How to dynamically identify this code below
```javascript
const testFn = () => {
    if (t && t === 'teste') {
        return true;
    } else {
        return false;
    }
};
```
and suggest a change to this format:
```javascript
const testFn = () => {
   return t && t === 'teste';
};
```

**Comment by rcjsuen** [comment]
@GlauberF I can't help you with that bit as I don't know how Monaco's JavaScript/TypeScript support works.

**Comment by GlauberF** [comment]
thanks @rcjsuen .
can you help me @alexdima ?

**Comment by GlauberF** [comment]
can you help me @alexdima ?

**Comment by alexdima** [comment]
@GlauberF You need to implement this by yourself. You need to find an AST parser, you can use the one from the TypeScript project, or get another one and then you would need to walk the AST and search for this pattern `x && x=='y'`. This is something that you need to figure out and is not related to the Monaco Editor. @rcjsuen has done a fantastic job of showing you how to plug into the editor your semantic analysis, once you have implemented it.
