### ISSUE TITLE
Ctrl-Space is not caught

### ISSUE THREAD

**Issue by zgordan-vv** [microsoft/monaco-editor#1901]
**monaco-editor version:** 0.19.3
**Browser:** Google Chrome Version 80.0.3987.149 (Official Build) (64-bit) 
**OS:** MacOS Catalina 10.15.4
**Playground code that reproduces the issue:**

I am trying to override monaco default behaviour when pressing Ctrl-Space (the final intetntion is to make custom suggestions in special cases) but it doesn't work. The code:

```
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {alert('Hello world!');}",
	language: "javascript"
});

editor.addCommand(monaco.KeyMod.chord(monaco.KeyCode.Ctrl, monaco.KeyCode.Space), () => alert("Gotcha"))
```

And this code works (when pressing Space + S):

```
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {alert('Hello world!');}",
	language: "javascript"
});

editor.addCommand(monaco.KeyMod.chord(monaco.KeyCode.KEY_S, monaco.KeyCode.Space), () => alert("Gotcha"))
```

So Ctrl doesn't react at all. Is it ok?

**Comment by spahnke** [comment]
Does this work for you? The keybindings work by combining a key modifier with an actual key using a bitwise or `|` as those are essentially bitmasks. What you registered was a *chord* i.e. a keybinding comprised of two separate key strokes (e.g. Cmd-K, Cmd-I for show hover). I don't think the first part of a chord can be just a modifier which is why your first example doesn't work. Your second example works because it is a chord comprised of first typing `s` followed by typing Space.

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {alert('Hello world!');}",
	language: "javascript"
});

editor.addCommand(monaco.KeyMod.WinCtrl | monaco.KeyCode.Space, () => alert("Gotcha"))
```
> Note: I used the `WinCtrl` modifier because you're on macOS and that's the Ctrl key there (^)

**Comment by zgordan-vv** [comment]
> Does this work for you? The keybindings work by combining a key modifier with an actual key using a bitwise or `|` as those are essentially bitmasks. What you registered was a _chord_ i.e. a keybinding comprised of two separate key strokes (e.g. Cmd-K, Cmd-I for show hover). I don't think the first part of a chord can be just a modifier which is why your first example doesn't work. Your second example works because it is a chord comprised of first typing `s` followed by typing Space.
> 
> ```js
> const editor = monaco.editor.create(document.getElementById("container"), {
> 	value: "function hello() {alert('Hello world!');}",
> 	language: "javascript"
> });
> 
> editor.addCommand(monaco.KeyMod.WinCtrl | monaco.KeyCode.Space, () => alert("Gotcha"))
> ```
> 
> > Note: I used the `WinCtrl` modifier because you're on macOS and that's the Ctrl key there (^)

Yep, WinCtrl did the trick. Thank you!
