### ISSUE TITLE
virtual file system provider

### ISSUE THREAD

**Issue by karikera** [microsoft/monaco-editor#1904]
I'm trying to create lite IDE
![image](https://user-images.githubusercontent.com/6016498/78472120-6e137480-7771-11ea-82c6-a0d9d7e2e584.png)
But It seems it needs to put all sources into models. 
instead, I just want to provide file system functions to monaco editor

**Comment by alexdima** [comment]
@karikera The API of the Monaco Editor is documented at https://microsoft.github.io/monaco-editor/api/index.html and that is all there is to it. The Monaco Editor is not an IDE and does not offer file system functions.

**Comment by karikera** [comment]
I want to offer file system functions to The Monaco Editor.
For making IDE
