### ISSUE TITLE
Last completion item is being wrongly selected

### ISSUE THREAD

**Issue by lmvco** [microsoft/monaco-editor#1905]
**monaco-editor version:** 0.20.0
**Browser:**: Chrome
**OS:**: Windows
**Playground code that reproduces the issue:**

[completionItem.txt](https://github.com/microsoft/monaco-editor/files/4439059/completionItem.txt)

**Repro steps:**
1. Open https://microsoft.github.io/monaco-editor/playground.html
2. Apply the code in the attached  completionItem.txt file
3. Open autocomplete with CTRL+Enter
4. Choose "Option 4"
5. Clear the text
6. Open autocomplete again with CTRL+Enter

**Result:**
"Option 4" is selected and it shouldn't . 
When there are many results and a scroll bar is show, the scenario is worst because the option list jumps to the last selected item (and it's not easy to understand why)

![completion-item](https://user-images.githubusercontent.com/1884391/78571253-e3d51a00-781d-11ea-9783-d1ab34379c2c.gif)

**Comment by aldwong** [comment]
You can pass in `suggestSelection: "first"` as part of your  `IStandaloneEditorConstructionOptions` to make it default to the first suggestion

**Comment by lmvco** [comment]
Thanks a lot. It worked.
