### ISSUE TITLE
getModelMarker behavior inside editor.onDidChangeModelContent

### ISSUE THREAD

**Issue by jpeterson** [microsoft/monaco-editor#1906]
**Observed Behavior** 
Using `getModelMarkers()` when handling the `onDidChangeModelContent` event of `editor` does not include any ModelMarkers that were introduced by the change being handled. 

It does, however, include any ModelMarkers that existed before the current change.

**Expected Behavior**
When called inside the editor's `onDidChangeModelContent` handler, `getModelMarkers()` should include any ModelMarkers that were introduced by the change being handled.

**monaco-editor version:** 0.20.0

**Browser:** Chrome

**OS:** MacOS Mojave

**Playground code that reproduces the issue:**

https://codesandbox.io/s/monaco-editor-1906-zh7yx

```js
var editor = monaco.editor.create(
    document.getElementById("container"),
    {
    value: `{ "json": true }`,
    language: "json"
    }
);

editor.onDidChangeModelContent(ev => {
    const markers = monaco.editor.getModelMarkers();

    // Note that a marker is only logged when it existed in the previous model content change
    // Shouldn't markers include the ModelMarker that was just typed?
    console.log(markers);
});
```

**Comment by geddski** [comment]
Same issue here

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/monaco-editor/issues/2138
