### ISSUE TITLE
[Folding] Suggestions and questions regarding custom folding range providers.

### ISSUE THREAD

**Issue by chadsowald** [microsoft/monaco-editor#1907]
Hi.  I have a few questions/suggestions regarding code folding. 

**Playground repro**
```
var json = {
    "key1": "a",
    "key2": "a",
    "obj1": {
        "key3": "a",
        "key4": "a",
        "key5": "a",
	},
    "key8": "a",
    "key9": "a"
};

const editor = monaco.editor.create(document.getElementById("container"), {
    value: JSON.stringify(json, null, '\t'),
    language: "json"
});

const foldAll = editor.getAction('editor.foldAll');
const foldRegions = editor.getAction('editor.foldAllMarkerRegions');
const unfoldAll = editor.getAction('editor.unfoldAll');

foldAll.run();

window.setTimeout(() => 
{
    monaco.languages.registerFoldingRangeProvider(
        'json',
        {
            provideFoldingRanges: function(model, context, token) {
                return [
                    { start: 2, end: 10, kind: monaco.languages.FoldingRangeKind.Region }
                ]; }
        }
    );
}, 1500);

//doesn't do what I expect
//which is to update folding and show my one region I marked for folding
window.setTimeout(() => foldRegions.run(), 1500);

//this works but causes screen flicker as everything has to unfold and then refold.
//It's especially noticable in larger json documents
window.setTimeout(() => 
{
    unfoldAll.run().then(() =>
        foldRegions.run()
    );
}, 3000);
```

**Summary**
I want to do custom folding within a JSON editor if the user has enabled an option, so I've created a custom FoldingRangeProvider and attached it to the JSON language.  Additionally, I want to update what's folded programmatically when something outside of the editor changes.  In short:

1. Toggle custom folding on and off
---- to do this I register my FoldingRangeProvider whenever the user turns on the option and I dispose of it when they turn off the option.  Registering a folding provider gets it called immediately to update folding, so that works for me.
2. Update that custom folding based on an external (to the editor) action.
---- to do this I was hoping for something like an ```editor.updateFoldingRanges``` method or something, but it doesn't exist AFAICT, so I instead again dispose of my custom provider and re-register it to get it called again.  On top of that, I have to also un-fold all the code and re-fold it via actions (e.g. ```editor.unfoldAll``` then ```editor.foldAllRegions```).  I've tried just re-folding (without the un-folding first) and it only works in some scenarios.  It's much nicer as there's no flicker as the code un-folds and folds again.  However, in some scenarios it doesn't work because of https://github.com/microsoft/vscode/blob/4a7a581b851dbe64e05b335f305c50c805c504ae/src/vs/editor/contrib/folding/foldingModel.ts#L398 where it appears that the editor won't try to toggle a region that's already collapsed.

In addition to those things, I can't seem to disable the built in JSON folding when my custom folding provider is installed.

I'm half looking for suggestions and half trying to give some feedback:
- Is there some way to disable the default JSON folding while still adding my own folding provider?
- Is there a clean way to update folding?  It would be nice if in addition to a folding provider returning the folding ranges it could also return a boolean such as ```foldImmediately``` and Monaco would immediately fold all the regions I returned.  Or, it could be more fine grained (more fine grained than I need) and be per folding range.

**monaco-editor version: 0.19.1** 
**Browser: Chrome latest**
**OS: Win 10 Enterprise**

**Comment by terpimost** [comment]
I have the same question

**Comment by alexdima** [comment]
fyi @aeschli 

I think there is API in `monaco-json` to allow you to turn off its folding provider -- `monaco.languages.json.jsonDefaults.setModeConfiguration({ foldingRanges: false })`.

AFAIK there is no API to update folding, but from a quick read of the code you could edit the content of the file (adding a newline at the end and removing it immediately). That would trigger a model content change event which would lead I believe to the folding areas getting refreshed.

**Comment by aeschli** [comment]
Yes, turning off the json folding provider is the right thing to do. Otherwise things get unclear as both provider get merged, where duplicate regions are eliminated and intersecting ones discarded.

Updating also happens when you register/deregister a folding provider.

Let me know if that was helpful...
