### ISSUE TITLE
CodeLenses do not get computed in DiffEditor

### ISSUE THREAD

**Issue by x24git** [microsoft/monaco-editor#1909]
When registering a code lens provider, I am unable to get the code lens to appear on an IStandaloneDiffEditor despite setting the option to show code lens to true. From debugging it appears that the `provideCodeLenses` function of the CodeLensProvider that I am trying to register never gets called when the DiffEditor loads. 

It was not clear from the documentation that CodeLenses were even intended to be shown on the DiffEditor, however the option to show and hide CodeLens on the construction options tends to make it appear that CodeLenses are supported by the DiffEditor. 

**monaco-editor version:** 0.20.0
**Browser:** Chrome 80.0.3987.149
**OS:** Windows 10
**Playground code that reproduces the issue:**

```js
var value = [
		'',
		'class Example {',
		'\tprivate m:number;',
		'',
		'\tpublic met(): string {',
		'\t\treturn "Hello world!";',
		'\t}',
		'}'
	].join('\n')

var originalModel = monaco.editor.createModel(value, 'typescript');
var modifiedModel = monaco.editor.createModel(value.replace('public', 'private'), 'typescript');

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
	enableSplitViewResizing: false,
        codeLens:true,
	renderSideBySide: true
});
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});

var commandId = diffEditor.addCommand(0, function () {
    // services available in `ctx`
    alert('my command is executing!');

}, '');

monaco.languages.registerCodeLensProvider('typescript', {
    provideCodeLenses: function (model, token) {
        return {
            lenses: [
                {
                    range: {
                        startLineNumber: 2,
                        startColumn: 1,
                        endLineNumber: 3,
                        endColumn: 1
                    },
                    id: "First Line",
                    command: {
                        id: commandId,
                        title: "First Line"
                    }
                }
            ]
        };
    },
    resolveCodeLens: function (model, codeLens, token) {
        return codeLens;
    }
});

```

**Comment by alexdima** [comment]
It looks like code lenses are hard coded to be disabled in diff editors [here](https://github.com/microsoft/vscode/blob/6d70b4f04271dfd5c9f0693a4c7952fdc9c72b7d/src/vs/editor/browser/widget/diffEditorWidget.ts#L1051). Maybe we can add an option to enable them if necessary. I believe the thinking at the time was that people want to use the diff editor to review changes and not find references, test executions or other things that appear in code lenses.

**Comment by x24git** [comment]
I don't mind if the default action is to disable code lenses, however I think it would great if we could manually reactive code lenses for the sub-editors within the diff editor. The use case I am trying to support is code lens information gets displayed on the left-hand (read-only) editor, while the user can make edits on the right-hand editor that doesn't have the code lens information displayed.

This is especially useful for adding or removing hunks for a interactive merge.

**Comment by ludokx** [comment]
I have the exact same use case as @x24git for removing hunks and instead of adding a button somewhere it would be awesome to be able to use the code lens to handle that.

**Comment by ludokx** [comment]
I created [PR #97640](https://github.com/microsoft/vscode/pull/97644) for vscode.
There's a couple things I need to clarify before updating that PR so that checks are all good and it can get merged. Once that's done I can update `monaco-editor` to support that change.
