### ISSUE TITLE
Set schema of JSON content without $schema property

### ISSUE THREAD

**Issue by Hirse** [Microsoft/monaco-editor#191]
In [monaco-json](https://github.com/Microsoft/monaco-json), it is possible to[ assign json schemas](https://github.com/Microsoft/monaco-json/blob/master/src/monaco.d.ts#L27) (for validation and code hints) to json files (file-names), however when running monaco stand alone in a browser, I don't have any filenames.

How can I select a schema to use for a json editor instance?

Using the `$schema` property works in theory, but gives problems if the schema doesn't allow this property in the root scope. See the following example modified from the [Monaco Editor Playground JSON example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults):
```js
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
	schemas: [{
        uri: "http://myserver/foo-schema.json",
        schema: {
            properties: {
                p1: {}
            },
            additionalProperties: false
        }
    }]
});

var jsonCode = [
	'{',
	'    "$schema": "http://myserver/foo-schema.json"',
	"}"
].join('\n');

monaco.editor.create(document.getElementById("container"), {
	value: jsonCode,
	language: "json"
});
```

![2016-09-15_16-12-08](https://cloud.githubusercontent.com/assets/2564094/18553042/4ee83a8a-7b5f-11e6-996d-5a9efbcb28dc.png)

--
monaco-editor npm version: 0.6.1
Browser: All
OS: All

**Comment by aeschli** [comment]
Here's a example on how to do it. In the file match you can also use patterns like `*.json`, or `foo*.json`.


```typescript

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	schemas: [{
      fileMatch: ['foo.json'],
      schema: {
            type: "object",
            properties: {
                p1: {
                    enum: [ "v1", "v2"]
                }
            }
        }
    }]
});


var jsonCode = [
	'{',
	"}"
].join('\n');

var model = monaco.editor.createModel(jsonCode, 'json', 'internal://server/foo.json');

monaco.editor.create(document.getElementById("container"), {
	model: model
});
```

**Comment by Hirse** [comment]
@aeschli Thanks for the explanation. I couldn't find the information about the name as identifier before.

**Comment by apalsapure** [comment]
@aeschli Thanks for the sample. 
Please add `uri` as parameter while defining `schema` as mentioned [here](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.json.diagnosticsoptions.html#schemas).
When there are multiple schemas; if you don't specify `uri`, monaco editor will pick last schema added to `schemas` array.

**Comment by viccsjain** [comment]
@apalsapure ,

If we do not specify URI, then will it take last schema ?
I added following code, but schema is not reflected in editor:

``` 
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    schemas: [{
      schema: {
            type: "object",
            properties: {
                p1: {
                    enum: [ "v1", "v2"]
                }
            }
        }
    }]
});


var jsonCode = [
    '{',
    "}"
].join('\n');

var model = monaco.editor.createModel(jsonCode, 'json');
monaco.editor.setModelLanguage()

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```
