### ISSUE TITLE
quick suggestion make me into the shadow, later canot see suggestion

### ISSUE THREAD

**Issue by ZhangMingZhao1** [microsoft/monaco-editor#1911]
![2020-04-08 15 48 30](https://user-images.githubusercontent.com/29058747/78758519-d603ce00-79b0-11ea-8629-d7cc3a54889e.gif)

[demo link](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults)
```javascript
// Configures two JSON schemas, with references.

var jsonCode = [
    '{',
    '    "p1": "v3",',
    '    "p2": false',
    "}"
].join('\n');
var modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "http://myserver/foo-schema.json", // id of the first schema
        fileMatch: [modelUri.toString()], // associate with our model
        schema: { 
            type: "object",
            properties: {
                p1: {
                    enum: ["v1", "v2"]
                },
                p2: {
                    $ref: "http://myserver/bar-schema.json" // reference the second schema
                }
            }
        }
    }, {
        uri: "http://myserver/bar-schema.json", // id of the first schema
        schema: {
            type: "object",
            properties: {
                q1: {
                    enum: ["x1", "x2"]
                }
            }
        }
    }]
});

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```

When I input p1, and i got schema snippet, but as the same time, i into the shadow, when i input p2, there no suggestion because i into the shadown mode，unless i click up or down or tab key
to escape shadow，then when i input p2, there is suggestion snippet.

![2020-04-08 15 58 50](https://user-images.githubusercontent.com/29058747/78759238-eec0b380-79b1-11ea-9929-77e3ef9b0855.gif)

so, what is shadow, It interferes with the user's smart prompt，how to solve it? options?

**Comment by alexdima** [comment]
I think the grey thing is a snippet stop which grows as you type in it. Since this reproduces in VS Code, I suggest you create an issue with VS Code specific steps (like typing in your `keybindings.json` file) against the VS Code repository at https://github.com/microsoft/vscode

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)
