### ISSUE TITLE
Alignment in `Command Palette` is not optimal

### ISSUE THREAD

**Issue by dschiller** [microsoft/monaco-editor#1917]
1. Try to reproduce in VS Code and file issue directly at:
 None

2. Otherwise, provide steps that reproduce the problem in VS Code web at:
- Impement it via ESM and WebPack Plugin
- Press `F1` to open the Command Palette

![image](https://user-images.githubusercontent.com/3144986/79032985-d667b900-7baa-11ea-9e41-2ecc931e9e06.png)

3. Otherwise, provide steps that reproduce the problem at the Monaco Editor homepage
None

4. Otherwise, provide a Playground code snippet
None

5. Otherwise, provide a self-contained git repository / HTML page
None

**monaco-editor version:** 0.30.0
**Browser:** Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:**
None

**Comment by dschiller** [comment]
I think it has todo with other CSS code in the Project. Unfortunetly I can not inspect the Command Palette as soon as I open the Inspector from the Chrome Developer Tools the Command Palette disappears.

**Comment by alexdima** [comment]
Indeed, this is caused by other CSS on the page.
