### ISSUE TITLE
Autocomplete is not optimal

### ISSUE THREAD

**Issue by dschiller** [microsoft/monaco-editor#1918]
1. Try to reproduce in VS Code and file issue directly at:
None

2. Otherwise, provide steps that reproduce the problem in VS Code web at:
- Implement ESM Monaco Editor
- Use WebPack Plugin
- Open Editor as `python` Language
- Type some Text like `import time`
- Goto new Line
- Press `Ctrl+Space` to open Autocomplete

![image](https://user-images.githubusercontent.com/3144986/79034487-7e36b400-7bb6-11ea-861d-c3397be3142d.png)

3. Otherwise, provide steps that reproduce the problem at the Monaco Editor homepage
None

4. Otherwise, provide a Playground code snippet
None

5. Otherwise, provide a self-contained git repository / HTML page
None

**monaco-editor version:** 0.30.0
**Browser:** Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:**
None

**Comment by rcjsuen** [comment]
@dschiller Inspect your DOM and a) verify that the text is actually there and b) check for conflicting CSS rules that is causing your text to not be rendered.

**Comment by dschiller** [comment]
I wanted to do that but I can not inspect the Autocomplete because it disappears when I use Chrome Inspector. Should be obvious.

**Comment by dschiller** [comment]
Does someone know how I can inspect the Autocomplete Dropdown ?

**Comment by alexdima** [comment]
When running from sources, there is a flag that can be set -- https://github.com/microsoft/vscode/blob/231e2b28805e0f6ac47c5ac4e21dbe84d0fb8e0c/src/vs/editor/contrib/suggest/suggestController.ts#L49

Perhaps that flag survives in the esm build and could be set to true. Then, the widget will not hide itself on focus lost.
