### ISSUE TITLE
How to change/update a single line

### ISSUE THREAD

**Issue by naumanumer** [Microsoft/monaco-editor#192]
i use `editor.getValue` to get the editor text, made some changes and then use `editor.setValue` to update the editor text but when file are too large this technique fails because the whole file is highlighted again. 

so, i want to know is there any way to just current line and then update it.

**Comment by itskhurram** [comment]
one way of doing is 
  for (var linenumber = 0; linenumber < editor.model._lines.length; linenumber++)
 {
            editor.model._lines[linenumber]._text = "some text";
}

**Comment by hediet** [comment]
An other way is to use `editor.executeEdits`:
```typescript
editor.executeEdits("my-source", 
    [{ identifier: "my-ident", range: new monaco.Range(1, 1, 1, 1), text: "text" }]);
```

**Comment by naumanumer** [comment]
and how can i get current line

**Comment by itskhurram** [comment]
editor.getPosition().lineNumber

**Comment by alexandrudima** [comment]
To edit a model:
* if the model is attached to an editor and you want undo to work:
  * `editor.executeEdits` combined with `editor.pushUndoStop` as desired (before or after or both)
* if the model is not attached to an editor
  * `model.pushEditOperations`
* if you don't care about the undo stack:
  * `model.applyEdits`

I would really not recommend using `editor.getModel()._lines[linenumber]._text`. This will edit the text, but it will not send out correct events to the view, it will not update markers, and it will not update the tokenization state correctly. As a general rule, doing anything that implies accessing things with `_` in their name should be avoided at all cost.
