### ISSUE TITLE
Can I add css and html autocompletion in javascript?

### ISSUE THREAD

**Issue by jdsxzhao** [microsoft/monaco-editor#1920]
I want to edit jsx file in monaco editor. Following [this](https://github.com/microsoft/monaco-editor/issues/264#issuecomment-575144625), I have made some highlight syntax for jsx. But there is only the autocompletion for js. How can I add html and css autocompletion when the language is javascript or typescript? (css usually shows like <div style={{color: '#333'}} />)

**Comment by alexdima** [comment]
You would need to implement that by yourself. There is no out-of-the-box support for that in the Monaco Editor.
