### ISSUE TITLE
hide minimap in the editor + line numbering column

### ISSUE THREAD

**Issue by Crare** [microsoft/monaco-editor#1921]
I could rant about this a long text, but to simplify what I want to say:
The minimap takes a lot of space, I don't need it, ever. I want more space to see the code instead.

To understand where this request is coming from:
I'm doing Azure tutorials, and they use cloud shell embedded in web-page with this editor in it. This splits the view horizontally to tutorial text on the left and the shell on the right, making them quite squeeze to read. (I need to make another feature request to be able to resize those windows too..)

I would like to have easy way to hide the minimap. Either through the command palette, or just right clicking on the minimap and having selection to hide it.

Also option to hide the line numbering column(more space for code) would be nice improvement.

**Comment by spahnke** [comment]
The editor already provides an option that determines if the minimap should be shown or not and you can also add a custom command to toggle the minimap. Providing these tools, however, is the job of the embedder, AFAICT.

[Playground code](https://microsoft.github.io/monaco-editor/playground.html):
```js
let showMinimap = false;
const editor = monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript",
    minimap: {
        enabled: showMinimap
    }
});

// Ctrl/Cmd+Shift+M to toggle the minimap
editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.KEY_M, () => {
    showMinimap = !showMinimap;
    editor.updateOptions({ minimap: { enabled: showMinimap } });
});
```
