### ISSUE TITLE
Cannot close the peek window with ESC

### ISSUE THREAD

**Issue by FutureXiang** [microsoft/monaco-editor#1923]
Cannot close the peek window with ESC directly without focus. Same as [this issue](https://github.com/microsoft/monaco-editor/issues/1557#issue-481864895).
**Sorry** to open a duplicate issue, but that issue has been **locked** and the problem has not been fixed. Now detailed information is provided here.
- **Cannot** reproduce in VS Code (behaving as expected in VS Code)
- **Can** reproduce in both [Monaco Editor homepage](https://microsoft.github.io/monaco-editor/) and [Playground](https://microsoft.github.io/monaco-editor/playground.html)
- **monaco-editor version:** same as the Playground
- **Browser:** Safari 13.1 / Chrome 81
- **OS:** macOS  / Windows

**How to reproduce the issue:**
1. Open the [Playground](https://microsoft.github.io/monaco-editor/playground.html).
2. Add a function call `hello()` on the right side.
![](https://github.com/FutureXiang/Pictures/blob/master/屏幕快照%202020-04-15%2023.57.45.png?raw=true)
3. Right click the `hello()` and click `Go to References`.
![](https://github.com/FutureXiang/Pictures/blob/master/屏幕快照%202020-04-15%2023.59.51.png?raw=true)
4. Press `ESC` directly (**without** focusing on the outer editor or the embedded editor).
- The peek window cannot be closed by `ESC`.
- After a click on either editor, pressing `ESC` can close it.
- In VS Code, the window can be directly closed without focus.

@alexdima Could you please give a hint about how to solve this? Is this a bug or a feature? Any help would be appreciated.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/b89779ea91fe400070903b7ef8b3f3c32595f39b
