### ISSUE TITLE
Monaco Adding bunch of <style> tags in document.head 

### ISSUE THREAD

**Issue by mittalalok** [microsoft/monaco-editor#1925]
Hi,

I am loading the monaco-editor in shadow dom. [Thank you! for starting support on this from 0.20.0 version]

I am creating the Monaco bundle using webpack (entry: monaco-editor/esm/vs/editor/editor.main.js).

I have added this bundle to the web component. When I am loading the component it adding a bunch of style tags in document.head. 

How can we stop adding this style tags in document.head? The style tags should be there in shadow root only.

**monaco-editor version:** 0.20.0
**Browser:**
**OS:**
**Playground code that reproduces the issue:**

```js
```

**Comment by alexdima** [comment]
That should not happen. Are you certain you are creating a new editor inside a shadow dom? AFAIK the editor will probe and see where it is created and then use that shadow root as the place where it creates the `<style>` tag. Here is a test page I was using to get things going -- https://github.com/microsoft/monaco-editor/blob/master/test/shadow-dom.html
