### ISSUE TITLE
How to extend new tokenizers to javascript

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#1927]
I tried adding some keywords to javascript language to support my custom objects. But the highlights are not getting added. Please correct me if i'm doing something wrong

![image](https://user-images.githubusercontent.com/29809906/79474146-ac3b4e80-8023-11ea-9a91-b45e79f59a2c.png)
Why the string 'myObj' didn't turn red?

I tried it in my local machine with monaco-editor version 0.20.0 , OS : Mac 
That too yields the same result

***It is working as expected if i create a new language, but why it is not working for built-in language***
![image](https://user-images.githubusercontent.com/29809906/79480557-e01a7200-802b-11ea-8118-2123eab4ef23.png)

**Comment by pankajk07** [comment]
@Pranomvignesh since monaco also tries to register the token provider for `javascript` language, hence your token provider registration is getting overridden by the default implementation. Refactor the code so that your registration happens after monaco has completed it's work.

**Comment by Pranomvignesh** [comment]
@pankajk07 Thanks for your response. As you said, let us assume, that i have registered my token provider after monaco has completed it's work, will **my tokenizer override the monaco editor's tokenizer** ? If so, that is not what i am expecting, I need a way to extend javascript tokenizer not to replace it completely.
_(Use case : I need to add custom syntax highlighting for some of my objects in javascript and i also need javascript's default syntax highlighting)_

And is there any callback (or) events thrown after monaco has completed it's work, so that i can call all those tokenizers in that function

**Comment by MicheleRosito** [comment]
Hi, it's a problem that afflicts me too.
Is there any way to add Monarch tokens to a predefined language?
I would like to trivially extend the YAML language, I don't want to overwrite it.

A possible solution to the problem could be:
1) Look at the definition of language in
https://github.com/microsoft/monaco-languages/blob/master/src/yaml/yaml.ts
2) Register a new language (with a different name) with the definitions seen above
3) Add personal tokens

@alexdima @Hirse @pankajk07 is there a way to avoid language redundancy?
The danger is not to correctly set all the parameters of YAML in the new language created.

**Comment by alexdima** [comment]
You are correct. The only tow possibilities available today is to either overwrite the built-in tokenizer or to define a new language. It is not possible to "tweak" an existing Monarch grammar, you need to copy it and change it on your side.

**Comment by Pranomvignesh** [comment]
>The only two possibilities available today is to either overwrite the built-in tokenizer or to define a new language

@alexdima Thanks for the clarification

**Comment by Pranomvignesh** [comment]
> You are correct. The only two possibilities available today is to either overwrite the built-in tokenizer or to define a new language. It is not possible to "tweak" an existing Monarch grammar, you need to copy it and change it on your side.

@alexdima I have found a way to extend the language configuration

- I took the language configuration object from monaco.languages.getLanguages()
- filtered out javascript
- Then from the loader() method i got the language object which holds the default monarch tokenizers for javascript 
- Then I modified it with my custom monarch tokens 

This seems to work, but i'm not sure whether this will behave as a workaround
You can find the demo [here](https://monaco-editor-extend-lang-conf.vercel.app/)
Please let me know your thoughts on this, the documentation and repository link of the demo is available in the site

**Comment by alexdima** [comment]
:+1: Yes, this can work, but beware that it might be broken by a future update since that is not public API.

**Comment by Pranomvignesh** [comment]
> 👍 Yes, this can work, but beware that it might be broken by a future update since that is not public API.

@alexdima Thanks for warning me about this. 
I thought `monaco.languages.getLanguages()` was a public API , as it was mentioned in the docs https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#getlanguages

**Comment by alexdima** [comment]
Yes, that one is in the API, but that returns the following:

```
export interface ILanguageExtensionPoint {
    id: string;
    extensions?: string[];
    filenames?: string[];
    filenamePatterns?: string[];
    firstLine?: string;
    aliases?: string[];
    mimetypes?: string[];
    configuration?: Uri;
}

declare namespace monaco.languages {
    export function getLanguages(): ILanguageExtensionPoint[];
}
```

So this line:
```
const { conf, language: jsLang } = await allLangs.find(({ id }) => id === 'javascript').loader();
```
Uses a property (`loader`) that is outside the API.

**Comment by Pranomvignesh** [comment]
> Uses a property (loader) that is outside the API.
@alexdima Thanks for the clarification ... I will check the availability of the loader method , whenever I update versions

**Comment by Pranomvignesh** [comment]
@alexdima Can this [semantic-tokens-provider](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example) be used to provide our custom tokenizers ?

I mean the extending of custom keywords and libs in an existing language tokenizer (like javascript) and highlighting them by custom theme

**Comment by alexdima** [comment]
You can use it in any way you want to. The purpose is for rich languages to enrich the tokens computed via Monarch through the use of their ASTs / semantic knowledge.

**Comment by Pranomvignesh** [comment]
Thanks for the clarification @alexdima
