### ISSUE TITLE
TypeError: Cannot read property 'getFormattingOptions' of null

### ISSUE THREAD

**Issue by xulijing626** [microsoft/monaco-editor#1931]
![image](https://user-images.githubusercontent.com/47960302/79821007-3ab32580-83c0-11ea-883a-4a978810600f.png)
![image](https://user-images.githubusercontent.com/47960302/79821045-50284f80-83c0-11ea-8163-38c06e25d50d.png)
![image](https://user-images.githubusercontent.com/47960302/79821063-57e7f400-83c0-11ea-89a7-29171af25d8b.png)

**Comment by alexdima** [comment]
@xulijing626 Do you perhaps have more steps?
