### ISSUE TITLE
How to auto convert indentation to space?

### ISSUE THREAD

**Issue by hhking** [microsoft/monaco-editor#1932]
monaco-editor version: 0.19.0

while copy some code and paste it to monaco-editor，I don't know what type indent (space or tab)  it use. And it may cause some issue

how to show whitespace characters in monaco-editor?
Is there any way to auto convert indentation to space?

**Comment by rcjsuen** [comment]
@hhking Use the `renderWhitespace` option.
```JavaScript
monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n       \n\t}\n}\n",
    language: "json",
    renderWhitespace: true
});
```
<img width="246" alt="image" src="https://user-images.githubusercontent.com/15629116/79871135-ef921600-83b1-11ea-848c-7636bbde8298.png">

**Comment by hhking** [comment]
@rcjsuen thanks，and is there any way to convert tab to space?

**Comment by hhking** [comment]
I got the solution！
1、Use the `renderWhitespace` option can show whitespace characters
2、The way to convert indentation can be：
```js
editor.addAction({
  id: 'convertIndentation',
  label: 'Convert indentation to space',
  contextMenuGroupId: 'control',
  run(IEditor) {
    const model = IEditor.getModel();
    if (model) {
      const preVal = model.getValue();
      let result = '';
      for (let i = 0; i < preVal.length; i++) {
        result += model.normalizeIndentation(preVal.charAt(i));
      }
      model.setValue(result);
    }
  },
});
```

**Comment by lmvco** [comment]
@hhking , in your solution, why did you iterate over all characters of the `prevVal` ? Shouldn't the `normalizeIndentation` functions work properly with strings (in this case, with `prevValue`) ?

**Comment by hhking** [comment]
@lmvco `normalizeIndentation` only convert the first `indentation` in the string.
