### ISSUE TITLE
Binding data to lines

### ISSUE THREAD

**Issue by worksofliam** [microsoft/monaco-editor#1934]
I am trying to find the best solution to bind properties to each line in my editor instance. 

When that line changes, the property which is attached to the line is updated.

This is what I have so far based on what I did with Ace.

```js


var jsCode = [
    '"use strict";',
    'function Person(age) {',
    '   if (age) {',
    '       this.age = age;',
    '   }',
    '}', '',
    'Person.prototype.getAge = function () {',
    '   return this.age;',
    '};',
    '};',
    '};',
    '};',
    '};',
    '};',
    '};',
    '};',
    '};',
].join('\n');

var sourceDates = Array(jsCode.split('\n').length).fill('000000');

var editor = monaco.editor.create(document.getElementById("container"), {
    value: jsCode,
    language: "text",
    lineNumbers: lineNumbersFunc
});

editor.getModel().onDidChangeContent(event => {
    const change = event.changes[0];
    const line = change.range.startLineNumber;

    console.log(change);
    if (change.text === '\n') {
        sourceDates.splice(line, 0, '111111');
        return;
    }

    sourceDates[line-1] = '111111';
});

console.log(sourceDates);
function lineNumbersFunc(originalLineNumber) {
    //console.log(editor.getModel().getLineDecorations(originalLineNumber));
    console.log('a');
    return sourceDates[originalLineNumber-1];
}
```

The issue I am having here is that the `onDidChangeContent` isn't showing me the start and end lines so I am unable to insert or remove the correct amount of items into my `sourceDates` array.

I saw an older issue where a method called `getLineContext` existed, but I guess that doesn't exist anymore.

Thanks!

**Comment by worksofliam** [comment]
Looking at CodeMirror, I see it has something called `getLineHandle` which looks like it's kind of what I am searching for - but in Monaco.

**Comment by worksofliam** [comment]
I've got to the point where I can so this:

`editor._modelData.view._context.model.lines.lines[line].date = '111111'`

But sadly the assignment is also assigning to every element in the `lines` array.

**Comment by alexdima** [comment]
@worksofliam You could try using decorations (which flow with the text) to keep track of how characters move in the editor, but I have to be honest, I don't understand what you are trying to do. -- https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations
