### ISSUE TITLE
provideCompletionItems not invoked due to non-ending string in Dockerfile

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/monaco-editor#1935]
**monaco-editor version:** Reproducible in the Monaco Editor Playground
**Browser:** Chrome 80.0.3987.149
**OS:** macOS Catalina 10.15.1
**Playground code that reproduces the issue:**

1. Paste the code into the [Monaco Editor Playground] and launch it.
1. Open the debugger and dock it to the side.
1. Also open up the console.
1. Follow the instructions and type on the 4th, 6th, and 7th line. I only get print statements for the 4th and 7th line but not the 6th line.
```JavaScript
const content = 
`# type on line 4, it works
# type on line 6, it fails
# type on line 7, it works

RUN \\'e\\'

`;
const language = "dockerfile";
monaco.languages.registerCompletionItemProvider(language, {
    provideCompletionItems: function(_model, position) {
        console.log(`provideCompletionItems called on line ${position.lineNumber} character ${position.column}`)
        return {
            suggestions: []
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: content,
    language: language
});
```

**Comment by rcjsuen** [comment]
VS Code behaves slightly differently. See microsoft/vscode#95924.

**Comment by alexdima** [comment]
I think this is also a problem of coloring, where the monarch definition for docker is not aware of an initial `\'`. -- https://github.com/microsoft/monaco-languages/blob/618f2cff2d8e72f04fe9d63085a0c5118b80e8a0/src/dockerfile/dockerfile.ts#L40
