### ISSUE TITLE
Problem when bundling Project Monaco with WebPack with a LibraryTarget

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/monaco-editor#1939]
**monaco-editor version:** 0.19.0
**Browser:** Chrome and Edge latest versions
**OS:** Windows 10

My problem is that if I export Project Monaco as a library (because I need to reference it from other JavaScript files, starting from the window object), I don't find my code if I reference the JavaScript files in my index.html in the suggested order:

	<script type="text/javascript" src="codeEditor/app.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/editor.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/json.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/css.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/html.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/ts.worker.CodeEditor.js"></script>

It seems to me that the additional files are not extending the MyCodeEditor namespace, but just replacing it.
In fact, if I reference the files in another order, it works:

	<script type="text/javascript" src="codeEditor/editor.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/json.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/css.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/html.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/ts.worker.CodeEditor.js"></script>
	<script type="text/javascript" src="codeEditor/app.CodeEditor.js"></script>

So here my questions:
* is it a bug, or am I doing anything wrong, because to find my custom code, I need to reference app.CodeEditor.js as the last one?
* eventually, would it be possible to merge all these files in one single one?

**Comment by alexdima** [comment]
I am sorry, I don't understand what you are doing. The worker files should not be loaded on the UI thread via a `<script>` tag, so I'm afraid I cannot answer the question since there should never be `<script>` tags to bundled workers. Please also see https://github.com/microsoft/monaco-editor/issues/1938#issuecomment-627552457
