### ISSUE TITLE
Triggering ColorPresentation using programmatic API

### ISSUE THREAD

**Issue by tomrav** [microsoft/monaco-editor#1940]
I am currently integrating an LSP we created and trying to test out the various integrations.
I've been able to trigger or collect every capability, with the exception of `provideColorPresentations`.

- I have a running instance of `monaco-editor` in my tests, and I trigger most commands, such as `hover` by using the `triggerAction`:
```ts
editor.getAction('editor.action.showHover').run()
```

However, I can't seem to find a way to trigger the color picker to open, and to trigger the color presentation edits.

- I've also tried dispatching a `MouseMove` event on the relevant color square span, or container - but that didn't work either. Hovering manually with the mouse does appear to work.

- I've also considered using the `executeCommand` method with the `_executeColorPresentationProvider` command, but couldn't figure out what to pass as the `ICommand` argument that's required.

I would appreciate any help making sense of how I can open the widget and trigger the color presentation edits.

**Comment by alexdima** [comment]
@tomrav The following works for me:

```
const ed = monaco.editor.create(document.getElementById("container"), {
    value: "body { background: red; }",
    language: "css"
});
setTimeout(() => {
    ed.setPosition(new monaco.Position(1, 21));
    ed.getAction('editor.action.showHover').run();
}, 1000);
```

![Kapture 2020-09-04 at 16 09 31](https://user-images.githubusercontent.com/5047891/92248485-123c4b80-eec9-11ea-94dd-e573d0d5bd5b.gif)
