### ISSUE TITLE
Object's prototype functions are not listed in autocompletions

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#1944]
**monaco-editor version:0.20.0
**Browser:Chrome
**OS:Mac
**Playground code that reproduces the issue:**

<img width="658" alt="Screen Shot 2020-04-28 at 12 23 43 PM" src="https://user-images.githubusercontent.com/29809906/80456659-9dba3480-894b-11ea-87d8-d3d99d65fdaf.png">
I am expecting the below auto suggestions for the above declared syntax.
<img width="539" alt="Screen Shot 2020-04-28 at 12 24 12 PM" src="https://user-images.githubusercontent.com/29809906/80456670-a14dbb80-894b-11ea-8e7c-0584c6e5ab22.png">
Note : For type 'Array' , auto completions are working properly

**Comment by alexdima** [comment]
The completions are computed 100% by TypeScript. I believe it is in their philosophy that you use Object Oriented Programming and those properties come from the Object prototype chain and that is why they are not offered. To be honest, in my personal programming, 99% of the time I would find those suggestions to get in the way. So I guess they have decided to only suggest the methods that you have added to objects. But they don't show a squiggle when you use one of the properties coming from the Object prototype. In any case, maybe there should be an option for this, but I don't know if the TypeScript services supports that.

**Comment by Pranomvignesh** [comment]
@alexdima Is it like  `{} !== new Object()` according to TypeScript autocompletion services ? ( correct me if i misunderstood what you said )
I'm confused about this, as the autocompletions for arrays declared with `[ ]`, provides proper result

<img width="841" alt="Screen Shot 2020-09-04 at 7 57 00 PM" src="https://user-images.githubusercontent.com/29809906/92250522-3576f300-eee9-11ea-956c-2f029361986b.png">

<img width="832" alt="Screen Shot 2020-09-04 at 7 57 13 PM" src="https://user-images.githubusercontent.com/29809906/92250536-39a31080-eee9-11ea-8928-ce92c81d2b08.png">

**Comment by alexdima** [comment]
I am sorry I don't have enough knowledge about the internals of the TypeScript compiler to answer your questions. Please take a look at their project page and follow any guidance there for getting help with their language service.

**Comment by Pranomvignesh** [comment]
@alexdima Can you please share the link to the Typescript compiler project page?

**Comment by Pranomvignesh** [comment]
As this issue is tagged as `Working as indented` in https://github.com/microsoft/TypeScript/issues/42086 , I am closing this issue now
