### ISSUE TITLE
Links in Code do not work in Electron

### ISSUE THREAD

**Issue by DrNiels** [microsoft/monaco-editor#1945]
**monaco-editor version:** 0.20.0
**Browser:** Electron 8.2.4
**OS:** Windows 10
**Playground code that reproduces the issue:** 

```js
// http://www.google.de
```

The displayed code is shown in Monaco as Link. I can Ctrl+click it to open the link in a new tab. This works great in the browser. In Electron however, a white window is opened and the main window with the editor shows an error in the developer console:

```
window-setup.ts:133 LocationProxy: failed to parse string  TypeError: Failed to construct 'URL': Invalid URL
    at LocationProxy.getGuestURL (window-setup.ts:131)
    at LocationProxy.set [as href] (window-setup.ts:80)
    at Object.set href [as href] (window-setup.ts:96)
    at Object.t.windowOpenNoOpener (dom.ts:1144)
    at Object.openExternal (openerService.ts:105)
    at e.<anonymous> (openerService.ts:164)
    at marked.js:8
    at Object.next (marked.js:8)
    at s (marked.js:8)
```

This can easily be reproduced in the monaco-editor-samples/electron-amd, with or without updating the editor and/or monaco to the most current version.

**Comment by alexdima** [comment]
I think we call `window.open` with the URL. I don't know what would be the exact problem here. Did you try to check what we call it with?
```
window.open = function() { console.log(`called with `, arguments); }
```

**Comment by DrNiels** [comment]
It seems like it was an issue in Electron. Nowadays, I use Electron 10.1.1 and everything is working as expected.

**Comment by zhixzhan** [comment]
I also met this. here is arguments: 
<img width="575" alt="image" src="https://user-images.githubusercontent.com/49866537/94238577-2c56d000-ff43-11ea-93c1-265045f47496.png">

My goal is open links in default browser instead of open in electron new-window, it requires give all detected links a option `target=_blank`, can I do that by some configuration?
