### ISSUE TITLE
Paste

### ISSUE THREAD

**Issue by baubeis** [microsoft/monaco-editor#1946]
When I right click I should be able to 'paste' what i copied or cut.  simple.

**Comment by pankajk07** [comment]
@baubeis, try adding action to the editor with `addAction` api.

**Comment by bpasero** [comment]
I think with @alexdima work recently this works now:

![image](https://user-images.githubusercontent.com/900690/91402685-6e57fd80-e841-11ea-9532-fa9d3b2e3981.png)

**Comment by Pranomvignesh** [comment]
@bpasero Can you please share the link to the above image that you have mentioned ?


> I think with @alexdima work recently this works now:
> 
> ![image](https://user-images.githubusercontent.com/900690/91402685-6e57fd80-e841-11ea-9532-fa9d3b2e3981.png)

**Comment by bpasero** [comment]
Yeah the related issue in vscode is: https://github.com/microsoft/vscode/issues/82604

**Comment by Pranomvignesh** [comment]
@bpasero ,
I went through this [PR Link](https://github.com/microsoft/vscode/pull/104646)
 
I have certain doubts regarding this , 
1. When will this be available in monaco-editor ?
2. Will this paste the text copied from anywhere (say as content from some other browser tab) ?
3. Will this prompt about permission like how [this website of google chrome ](https://googlechrome.github.io/samples/async-clipboard/) does  ?

**Comment by bpasero** [comment]
1. as soon as we do a new release with the "August" bits of VSCode
2. this relies on `navigator.clipboard.readText` support from the browser
3. yes a prompt will appear if `navigator.clipboard.readText` is triggered

But maybe Alex can chime in too.

**Comment by alexdima** [comment]
That is correct, this will come out with the editor August release.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/monaco-editor/issues/2074
