### ISSUE TITLE
Showing hover tooltip on key binding   

### ISSUE THREAD

**Issue by zzat** [microsoft/monaco-editor#195]
How can I show the tooltip shown on hovering over a text using a key binding.

**Comment by alexandrudima** [comment]
out of the box it is bound to `ctrl+k ctrl+d`. Would you want a different keybinding? Currently, there is no API to customize default keybindings we ship with.

**Comment by zzat** [comment]
Yeah I wanted a different binding. Either a way to customize the keybinding or showing a custom tooltip on some keypress works for me. 
I tried pressing `ctrl+k` followed by` ctrl+d` but it just highlighted the text at the cursor position. Am I missing something here? I tried this on the hover provider example page in the playground.

**Comment by alexandrudima** [comment]
I'm sorry I mixed up the keybindings. `ctrl+k ctrl+i` it is.
