### ISSUE TITLE
C++ raw literals confused by two literals in a row

### ISSUE THREAD

**Issue by mattgodbolt** [microsoft/monaco-editor#1951]
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Linux
Link to issue exhibiting: https://godbolt.org/z/bxpqKi

With c++ code like:

```cpp
int main()
{
    using namespace std::literals;
    auto sv = R"({ "message": "Hello World" })""\n"sv;
    // This is a comment, not a string
}
```

The raw literal is not terminated (though this is valid code), and the lines following the `auto sv` are erroneously tagged as being still part of the raw literal.

**Comment by beached** [comment]
If the second one is raw, it is ok.  It is when the first is a raw literal it gets confused.  The sv user defined literal isn't at play either
