### ISSUE TITLE
Import statement throws error

### ISSUE THREAD

**Issue by murisceman** [microsoft/monaco-editor#1952]
**monaco-editor version:** 0.20.0
**Browser:** Chrome 81
**OS:** macOS 10.15.4
**Playground code that reproduces the issue:**

```js
import * as jQuery from "jquery";
```
Throws `Uncaught Error: Cannot read property 'kind' of undefined` when the cursor is positioned at the end of the line.

**Comment by alexdima** [comment]
This is also fixed by https://github.com/microsoft/monaco-typescript/commit/0ac03ae5cd15be689e7806c038269eb162bc5bf0
