### ISSUE TITLE
automaticLayout strange behavior

### ISSUE THREAD

**Issue by ZsgsDesign** [microsoft/monaco-editor#1954]
**monaco-editor version:** 0.20.0
**Browser: Chrome80**
**OS: Win10**

```js
automaticLayout: true
```

automaticLayout sets to true could make the element resize with its container before, but today after I updated the monaco-editor I found that option doesn't always work:

1. When resizing the browser window, it always worked;
2. When makes the browser window maximum or minimum or normal, it always changes to last stages, like it's currently not full screen, it is ok, and when I maximized the window, it kept the size before, and when I exit full screen, it changes to full size.
3. When opening the Chrome DevTools and dock it then resize it, it sometimes works and always mismatches the size when resize stoped.

I found some issues related and learned the `automaticLayout` was implemented by `setInterval`. So I tried this:

```js
setInterval(()=>{
    editor.layout();
},100);
```
Though it's not efficient, the code solved my problem temporally. But still, I wonder is there a modification for the implementation regarding `automaticLayout` or it's the problem of the new Chrome?

**Comment by spahnke** [comment]
This is a duplicate of #1878

**Comment by ZsgsDesign** [comment]
@spahnke Thank you so much, I am going to close this issue.
