### ISSUE TITLE
Add support for quick help in monaco-json

### ISSUE THREAD

**Issue by buremba** [microsoft/monaco-editor#1955]
I would like to add support for quick help in JSON language support if a JSON schema is provided for the JSON file the user is editing. Here is an example: 

![Screen Recording 2020-05-05 at 08 23 PM](https://user-images.githubusercontent.com/82745/81097699-e906b100-8f10-11ea-8ed8-8d97565371cc.gif)

It's possible to implement it using overlay widgets but the language support doesn't work on the main thread and instead runs under the LSP. Ideally, we can send a message from the WebWorker to the main thread and create an overlay widget for the editors if a flag is enabled. 

The main problem is that the LSP doesn't really have an access to the editor, I can work on this feature and create a PR on `monaco-json` if there's interest, I already have a prototype but couldn't really find a way to make this feature embedded into `monaco-json` as we don't have access to the created editors. Instead, I'm creating an overlay widget in my editor separately talking to the language server.

**Comment by buremba** [comment]
![Screen Recording 2020-05-05 at 08 23 PM](https://user-images.githubusercontent.com/82745/81097544-bd83c680-8f10-11ea-93b5-5f5177d1d8a2.gif)

**Comment by alexdima** [comment]
fyi @aeschli

**Comment by aeschli** [comment]
IMO adding to monaco-json is not the right approach as this is quite a specific feature. Instead you could be looking into having your own monaco-json and replace the original one.

**Comment by buremba** [comment]
@aeschli thanks for the answer. What would be the right approach to implement such a feature based on my previous message?

**Comment by aeschli** [comment]
@buremba Sorry, can you be more specific what information you need?

**Comment by buremba** [comment]
I forked monaco-json and implemented `getSchema(uri: Uri, position: Position)``monaco.languages.json.getWorker()` and implemented an overlay widget using [json-schema-visualizer](https://github.com/buremba/json-schema-visualizer). It looks to be the convenient way for this use-case. Thanks!
