### ISSUE TITLE
Would like to completely remove the margin

### ISSUE THREAD

**Issue by elsigh** [microsoft/monaco-editor#1960]
I see how to set glyphMargin to false, but that still renders a "margin" node. I tried setting marginClassName and then setting the node with the `margin` class to `display: none` but that somehow still causes a 26px wide zone of unclickability in the place where the margin would have been.

Is there any way to completely disable the margin?

**Comment by paranoidjk** [comment]
+1 same problem here

**Comment by alexdima** [comment]
Did you try
```
{ 
"glyphMargin": false,
"folding": false,
"lineNumbers": "off",
"lineDecorationsWidth": 0,
"lineNumbersMinChars": 0
}
```
