### ISSUE TITLE
Create OnDidMarkerChange Event

### ISSUE THREAD

**Issue by dsm0880** [microsoft/monaco-editor#1966]
I'm seeing some interesting behavior where the OnDid(EventNames) do not capture when the validation takes place in Monaco. My specific situation is using the
 ```json
monaco.editor.getModelMarkers({})
```

The issue is the first time the editor loads. If I add a simple timeout (~2 seconds) and attempt to get the markers then they are there. After the initial load all is well and I don't have the issue. Maybe I'm missing the right subscription, but I hate using a timeout and instead would like to subscribe to the proper event.

**Comment by everhardt** [comment]
Isn't this a duplicate of #313?

**Comment by dsm0880** [comment]
@everhardt yes, closing
