### ISSUE TITLE
Add vscode-oniguruma as an alternative to Monarch

### ISSUE THREAD

**Issue by bmarkovic** [microsoft/monaco-editor#1967]
Since you've recently replaced the [oniguruma implementation](https://code.visualstudio.com/updates/v1_45#_faster-syntax-highlighting) inside the VS.Code and VS.Code Web with your own WASM implementation, and given how you've decided not to support IE11 anymore, maybe it would be about time to reconsider offering that implementation as an alternative (to Monarch) syntax option for monaco-editor as well.

**Comment by alexdima** [comment]
Please see #2150 1915
