### ISSUE TITLE
Access active monaco editor instance within a vscode extension

### ISSUE THREAD

**Issue by aloncarmel** [microsoft/monaco-editor#1970]
When developing a vscode extension, it would be great if I can access the underlying monaco editor and apis. Reason behind it is to make https://github.com/FirebaseExtended/firepad/blob/master/lib/monaco-adapter.js firepad adapter work with monaco editor. currently the vscode does not expose the monaco active editor and most commands differ from the monaco documents.

**Comment by alexdima** [comment]
This will not happen, simply because of VS Code's architecture. In VS Code, the Monaco Editor is loaded and executes on the main UI thread, while extensions are executed on another process, called the extension host process.
