### ISSUE TITLE
Document "Editor#onDidAttemptReadOnlyEdit"

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#1971]
**monaco-editor version:** 0.20.0

The `onDidAttemptReadOnlyEdit` event is undocumented and not exposed via the TypeScript.

**Comment by fabiospampinato** [comment]
By the way it's not triggered when I attempt to manually edit a read-only editor, what am I missing? 🤔

**Comment by alexdima** [comment]
We can expose it in the API. I have no idea what would be wrong, do you have a repro?

**Comment by spahnke** [comment]
> By the way it's not triggered when I attempt to manually edit a read-only editor

Is that maybe caused by #1873 ? The workaround mentioned there works.

**Comment by fabiospampinato** [comment]
@alexdima Repro:

```javascript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
    readOnly: true
});

editor.onDidAttemptReadOnlyEdit ( () => {
    console.log ( 'attempted edit' );
});
```

Just try to edit something in the editor and notice how the callback is not called.

> Is that maybe caused by #1873 ?

@spahnke yeah that does look like the same issue 🤔

**Comment by alexdima** [comment]
Indeed, let's track in #1873. I've added the method to the API.
