### ISSUE TITLE
Add support for elastic tabstops

### ISSUE THREAD

**Issue by edjroot** [microsoft/monaco-editor#1973]
(There's a long-running feature request on the [vscode repo](https://github.com/microsoft/vscode/issues/3932), but I thought maybe it would be more appropriate to ask about it here since I assume it would require lower-level changes.)

There's significant interest, so I think the most common stopper is expressed in [this comment](https://github.com/microsoft/vscode/issues/3932#issuecomment-624998721):

> **Do we have an idea of the work breakdown required to actually implement this functionality?**

---

About elastic tabstops:

Excerpts from [the original proposal](http://nickgravgaard.com/elastic-tabstops/):

> Using spaces to align columns is obviously a kludge, but tabs as they stand now are broken.
>
> We're using tabs and spaces to format text for aesthetic reasons rather than treating them semantically - tabs are for indenting and aligning text, spaces are for separating keywords.
>
> The simple solution is to redefine how tabs are interpreted by the text editor. **Rather than saying that a tab character places the text that follows it at the next Nth column, we should say that a tab character is a delimiter between table cells** in a manner more reminiscent of how they're used in tab-separated value (TSV) files.

Arguments in defense of elastic tabstops:

> you don't need to reindent every time the length of the longest line changes so you have nice diffs AND always perfect columns [[source]](https://github.com/microsoft/vscode/issues/3932#issuecomment-457418755)

> [The biggest issue with space aligment is] it assumes monospace font which is an absolute deal-breaker for anyone who likes to use proportional fonts [[source]](https://github.com/microsoft/vscode/issues/3932#issuecomment-551971679)

> Elastic tabstops would be then an absolute killer feature for markdown tables — one could use proportional fonts and align table columns without needing to adjust all other rows [[source]](https://github.com/microsoft/vscode/issues/3932#issuecomment-551971679)

**Comment by hediet** [comment]
> here since I assume it would require lower-level changes.

Monaco is built from VS Code, not the other way round, thus closing this issue.
