### ISSUE TITLE
Completion item provider does not work

### ISSUE THREAD

**Issue by YevhenKap** [microsoft/monaco-editor#1976]
**monaco-editor version:** 0.20.0
**Browser:** all browsers.
**OS:**: MacOS 10.15.4
**Playground code that reproduces the issue:**

Editor is initialized through function.

```js
export async function buildAndMountEditor(setEditor, currentTheme, id) {
  const monaco = await import("monaco-editor");
  setEditor(monaco.editor);
  const content = restoreContent(); // content that will be passed to editor
  monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
    noSemanticValidation: true,
    noSyntaxValidation: true
  });
  monaco.languages.registerHoverProvider("javascript", { provideHover });
  monaco.languages.registerCompletionItemProvider("javascript", {
    triggerCharacters: ["."],
    provideCompletionItems: (model, position, context, token) => ({ suggestions: [{label: 'findArray', kind: monaco.languages.CompletionItemKind.Function}] })
  });
  monaco.editor.defineTheme("dark", DARK_THEME);
  monaco.editor.defineTheme("light", LIGHT_THEME);
  const editorContainer = document.getElementById(id);
  const editor = monaco.editor.create(editorContainer, {
    value: content,
    theme: currentTheme,
    language: "javascript",
    minimap: { enabled: false }
  });
  const model = editor.getModel();
  const handler = createLogicHandler(monaco, model); // Show diagnostic of code validation
  model.onDidChangeContent(handler);
  handler();
}
```

When I type first symbol `f`, completion is triggered, but Monaco does not show `findArray` suggestion item. When I type second letter `i`, then fourth argument of `provideCompletionItems`  is available and equals to
```js
{
isCancellationRequested: true,
_emitter: null,
// and methods
}
```

I have tried [official example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) and it also does not work.

**Comment by rcjsuen** [comment]
> I have tried [official example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) and it also does not work.

@YevhenKap Seems to work for me but maybe I'm misunderstanding something.

![image](https://user-images.githubusercontent.com/15629116/82656397-b091f300-9bf1-11ea-892b-38c09add5016.png)

```JavaScript
  monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
    noSemanticValidation: true,
    noSyntaxValidation: true
  });
  monaco.languages.registerCompletionItemProvider("javascript", {
    triggerCharacters: ["."],
    provideCompletionItems: (model, position, context, token) => (
        {
            suggestions: [
                {
                    label: 'findArray',
                    kind: monaco.languages.CompletionItemKind.Function
                }
            ]
        }
    )
  });

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "javascript"
});
```

**Comment by YevhenKap** [comment]
Strange... Except of `findArray` item you have other suggest items that monaco shows. Maybe there is a problem?

**Comment by rcjsuen** [comment]
> Strange... Except of `findArray` item you have other suggest items that monaco shows. Maybe there is a problem? Because I haven't any suggestion at all...

@YevhenKap When you try the code I pasted you see nothing?

**Comment by YevhenKap** [comment]
@rcjsuen Unfortunately, yes( 
```js
export async function buildAndMountEditor(id) {
  const monaco = await import("monaco-editor");
  monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
    noSemanticValidation: true,
    noSyntaxValidation: true
  });
  monaco.languages.registerCompletionItemProvider("javascript", {
    triggerCharacters: ["."],
    provideCompletionItems: (model, position, context, token) => (
        {
            suggestions: [
                {
                    label: 'findArray',
                    kind: monaco.languages.CompletionItemKind.Function
                }
            ]
        }
    )
  });

monaco.editor.create(document.getElementById(id), {
    value: "",
    language: "javascript"
});
}
```
I modified function with your code and see nothing(

<img width="827" alt="Bildschirmfoto 2020-05-22 um 20 34 39" src="https://user-images.githubusercontent.com/28602579/82694526-0e632100-9c6c-11ea-9ec9-dc2a8304bdc2.png">

**Comment by rcjsuen** [comment]
@YevhenKap No idea. I guess you could start by checking if the `provideCompletionItems` function is even getting called.

**Comment by YevhenKap** [comment]
> @YevhenKap No idea. I guess you could start by checking if the `provideCompletionItems` function is even getting called.

It is invoked because I wrote already that after typing second letter cancellation token. is arrived. Also I check a function call by simply passing *console.log* into.

**Comment by YevhenKap** [comment]
`provideCompletionItems` function invokes only on first letter, but no more(

**Comment by alexdima** [comment]
@YevhenKap IIRC completion results have a flag where you can say that the result is complete or incomplete. If you say the result is complete, once you type additional letters, the result will be filtered and the completion provider will not be called again. if you say the result is incomplete, the provider will be called for each additional typed letter.
