### ISSUE TITLE
Prefix changed lines with +/- in addition to color in the Diff Editor

### ISSUE THREAD

**Issue by jayspadie** [Microsoft/monaco-editor#198]
To provide improved accessibility, it would be great to have the option for the Monaco Diff Editor to prefix added lines with "+" and removed lines with "-" instead of relying exclusively on the green and red background colors which aren't well discernible by all.  Although a custom addition of a line decoration might be implemented on the new lines to prefix with a "+" image, there is no way to similarly add a "-" for the deleted line when the diff is shown inline.  Custom styling with content also does not work since it changes the position of text and affects text selection.

We currently implement something similar with our own custom viewer in VSTS, as shown below:
![image](https://cloud.githubusercontent.com/assets/5246869/18678050/cae5a100-7f28-11e6-8e9e-54feb24f0049.png)

... and GitHub also has something similar:
![image](https://cloud.githubusercontent.com/assets/5246869/18678072/dfae48a8-7f28-11e6-9226-d825d80783be.png)

**Comment by seanmcbreen** [comment]
Hey Alex just assigning as discussed so it does not get lost :)

**Comment by jayspadie** [comment]
@alexandrudima , any update on this request for +/- in diffs?

**Comment by alexandrudima** [comment]
@jayspadie It is fully implemented, I need to make a release of the editor in the following days.
