### ISSUE TITLE
Javascript does not honor wordBasedSuggestions = false

### ISSUE THREAD

**Issue by AndersMad** [microsoft/monaco-editor#1980]
**monaco-editor version:** v0.20.0

**ISSUE:** Can we have suggest any word suggestions turned off? It confuses. Below repro in playground:
```js
function a() { let myVar; }
myV| // CTRL + SPACE here should not suggest myVar as type any-word
```

**NOTE:** This works in Typescript - only Javascript has the issue. It says its fixed here but its not: https://github.com/microsoft/monaco-editor/issues/907). I assume the `wordBasedSuggestions` is meant to turn this off. 

Thanks!

**Comment by alexdima** [comment]
I think this is how TypeScript works. When the language is set to JavaScript, it offers word completions from its side. We just forward them through `monaco-typescript`.

**Comment by os-lmo** [comment]
I am also facing this issue. Is there any to plan to fix it soon?

**Comment by hediet** [comment]
@orta I think this due to the implementation of suggestions in TypeScript/JavaScript?

**Comment by hediet** [comment]
Duplicate of #2136.

See https://github.com/microsoft/monaco-editor/issues/2136#issuecomment-886025174.

**Comment by AndersMad** [comment]
TIP: this annoying bug can be fixed with option `suggest: { showFiles: false }` - yes, file 🙄
