### ISSUE TITLE
Impossible to use @ symbol in Monarch language definitions

### ISSUE THREAD

**Issue by klaasgeldof** [microsoft/monaco-editor#1981]
**monaco-editor version:** 0.20.0
**Browser:** Chrome 83.0.4103.61
**OS:** macOS

I'm trying to create a custom language for the Laravel Blade syntax. This syntax has a lot of directives starting with the @ symbol, for example:

```php
@if ($someCondition)
    ...
@endif
```

Now, the problem is that the @ symbol is used by Monarch itself. When I try to match `@if`:

```js
[/@if \(/, { token: '@rematch', switchTo: '@phpInSimpleState.root' }],
```

I get this error:

```
language definition does not contain attribute 'if', used at: ^(?:@if ()
```

I tried to escape the @ symbol as `\@` and `@@` but with no luck...

Is there a way to use @ in the language definitions?

**Comment by AndersMad** [comment]
maybe try `[@]if`

**Comment by klaasgeldof** [comment]
This works, thank you!

**Comment by JunaidQadirB** [comment]
@klaasgeldof will you be making the blade syntax highlight available (Open Source or paid)?
