### ISSUE TITLE
workerMain.js is getting loaded twice

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#1983]
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Mac OS

index.html : 
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./style.css">
    <title>Monaco Editor WorkerMain Issue</title>
    <script type="text/javascript" src="./node_modules/monaco-editor/min/vs/loader.js"></script>
    <script type="text/javascript" src="./script.js"></script>
</head>
<body>
    <div id="editor"></div>   
</body>
</html>
```

script.js : 
```js
window.addEventListener('DOMContentLoaded', (event) => {
    require.config({
        paths: {
            vs: "./node_modules/monaco-editor/min/vs"
        }
    })

    require(["vs/editor/editor.main"], function(){
        const sampleJs = `
            const value = function(){
                console.log('test');
            }
        `
        const jsModel = monaco.editor.createModel(sampleJs, "javascript");
        const jsContainer = monaco.editor.create(document.getElementById("editor"), {
            wordWrap: 'on'
        })
        jsContainer.setModel(jsModel);
    })
});
```
Screenshot of the browser's network tab : 
<img width="1680" alt="screenshotOfBrowser'sNetworkTab" src="https://user-images.githubusercontent.com/29809906/82821903-86c31f80-9ec2-11ea-9f8f-5ee753eab628.png">

Why workerMain.js is getting downloaded twice
Correct me if I am doing anything wrong.
You can see the refer the code in this [github repo](https://github.com/Pranomvignesh/monacoEditorWorkerMainIssue)

**Comment by alexdima** [comment]
> Correct me if I am doing anything wrong

![image](https://user-images.githubusercontent.com/5047891/92260731-a8c43900-eed8-11ea-8276-c1b5a0662d54.png)

**Comment by Pranomvignesh** [comment]
I guess disable cache, **will not solve the issue** , as the **network call is initiated from monaco** and disable cache just gets the response directly from server and not looks into browser cache

<img width="1680" alt="Screen Shot 2020-09-04 at 9 41 19 PM" src="https://user-images.githubusercontent.com/29809906/92261893-e5ebf380-eef7-11ea-8db4-daf22fdeeb5c.png">
