### ISSUE TITLE
Signature Help highlighting wrong parameter

### ISSUE THREAD

**Issue by aldwong** [microsoft/monaco-editor#1986]
The bug in Signature Help happens when you have 2 different parameters where the first parameter is a substring of the second parameter. Signature Help will underline the second parameter's substring when the active parameter is the first.

To replicate using playground code:

- type `function(` in editor

- The Signature Help will show with underline on second parameter with docs for first parameter.

**monaco-editor version:** 0.20.0
**Browser: Chrome**
**OS: Windows 10**
**Playground code that reproduces the issue:**

```js
monaco.languages.registerSignatureHelpProvider('javascript', {
    signatureHelpTriggerCharacters:["(", ","],
	provideSignatureHelp: function(model, position) {
            return {
                value: {
                    signatures: [{
                        label: "test(param, parameter)",
                        parameters: [{
                            label: "param",
                            documentation: "param 1"
                        },
                        {
                            label: "parameter",
                            documentation: "param 2"
                        }]
                    }],
                    activeSignature: 0,
                    activeParameter: 0
                },
            	dispose: () => {}
         };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "javascript"
});
```

**Comment by alexdima** [comment]
I could reproduce in vscode, so let's track in https://github.com/microsoft/vscode/issues/106129
