### ISSUE TITLE
Reduce the memory consumption of the javascript worker

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#1987]
The Javascript worker seems to take a runtime memory of about ~25MB .
It will be better if there is any possibility to reduce that memory consumption

<img width="1680" alt="Screen Shot 2020-05-28 at 11 22 19 AM" src="https://user-images.githubusercontent.com/29809906/83105776-e5fa7d00-a0d8-11ea-9257-328e701db875.png">

Also ,Is there any options present to pause/stop and restart the worker whenever needed.
setMaximumWorkerIdleTime doesn't seem to solve my issue
And the docs for that API is saying `No-op.`
Does this mean , this API is deprecated ?
The parameter value also doesn't specify whether we have to give time in milliseconds (or) seconds
 
<img width="827" alt="Screen Shot 2020-05-28 at 12 25 18 PM" src="https://user-images.githubusercontent.com/29809906/83109149-7e473080-a0de-11ea-950b-d4d619fc4295.png">

**Comment by alexdima** [comment]
@Pranomvignesh That memory is consumed by the TypeScript compiler and language services, which is loaded when creating a JavaScript file. If you want to reduce the memory usage, then you can use directly the npm module `monaco-editor-core`, which does not contain `monaco-typescript`, which is the project that defines TypeScript workers for javascript.

**Comment by Pranomvignesh** [comment]
@alexdima  If i use this `npm module monaco-editor-core` , will i be able to get the auto-completions for javascript language ?

**Comment by alexdima** [comment]
The method `setMaximumWorkerIdleTime` does not do anything. It is deprecated.

**Comment by Pranomvignesh** [comment]
> The method `setMaximumWorkerIdleTime` does not do anything. It is deprecated.

@alexdima Thanks for your response

>  If I use this npm module Monaco-editor-core, will I get the auto-completion for javascript language
 
What about this one?

**Comment by alexdima** [comment]
> If I use this npm module Monaco-editor-core, will I get the auto-completion for javascript language

No, the module `monaco-editor-core` contains the core editor, without any languages.
