### ISSUE TITLE
error when selecting all of editor's contents when language is typescript, assignment doesn't match specified type, and editor has multiple lines

### ISSUE THREAD

**Issue by clumsycomputer** [microsoft/monaco-editor#1988]
#### conditions
- language === typescript
- assignment doesn't match specified type _(e.g. const foo: number = '')_
- editor has multiple lines
- selecting all of an editor's contents

#### result
<img width="422" alt="Monaco-editor error" src="https://user-images.githubusercontent.com/65958896/83156512-5bedec80-a0b7-11ea-8daf-f9b6a4174fe2.png">

#### additional notes
- have reproduced on both chrome and safari, in both the typescript playground and monaco editor homepage

**monaco-editor version:** 0.20.0
**Browser:** Chrome 81.0.4044.138  and Safari 12.1.2 _(haven't tested on other browsers)_
**OS:** macOS 0.14.6
**Playground code that reproduces the issue:**

```js
// need multiple lines and occurs when selecting all of editor's contents
const foo: string = 0
```

**Comment by alexdima** [comment]
@clumsycomputer I could not quite reproduce. Here is what I have tried:
* open https://microsoft.github.io/monaco-editor/playground.html
* paste 
```
var tsCode = `
// need multiple lines and occurs when selecting all of editor's contents
const foo: string = 0
`;

var editor = monaco.editor.create(document.getElementById("container"), {
    value: tsCode,
    language: "typescript"
});
```
* press Run
* do cmd+a in the right hand side editor
