### ISSUE TITLE
Customizing the context menu 

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/monaco-editor#199]
With the removal of shouldShowInContextMenu and contextMenuGroupId from IActionDescriptor in version 0.6.0, how can we edit what commands get shown in the context menu, and how do we include our own custom commands in there? 

monaco-editor npm version: 0.6.0
Browser: Chrome
OS: Windows

**Comment by alexandrudima** [comment]
Sorry about that, we need to bring back that functionality.

**Comment by alexandrudima** [comment]
Let's track in #175
