### ISSUE TITLE
Events and getter on whether model markers are up-to-date

### ISSUE THREAD

**Issue by everhardt** [microsoft/monaco-editor#1991]
I'd like to block certain actions in my web app based on whether there are errors in the code the user provided in a monaco editor and planned to use `monaco.editor.getModelMarkers({})` for that.

I notice that the obtained model markers are not always up to date. I'd therefore like to know when the typescript worker moves in and out of the state that it is still processing the model, so that I can wait for that. 

I think this can be addressed by adding event callbacks (and keeping a status variable) at the start and end of [_doValidate](https://github.com/microsoft/monaco-typescript/blob/v3.7.0/src/languageFeatures.ts#L163) and making those events and the status variable publicly accessible.

**Comment by everhardt** [comment]
I think #313 is related but different: the `onDidChangeModelMarkers`-event of that feature request would be called at the end of a `_doValidate` run, but only if the markers actually changed.

**Comment by geddski** [comment]
@everhardt did you find a good way to do this?

**Comment by everhardt** [comment]
Unfortunately not..

**Comment by hediet** [comment]
The monaco editor should not be used as model for typescript diagnostics. Rather, use the typescript worker directly.
