### ISSUE TITLE
When the display of the container is none, the content is not displayed completely after the content is updated through executeEdits

### ISSUE THREAD

**Issue by fpsqdb** [microsoft/monaco-editor#1994]
**monaco-editor version:** 0.20.0
**Browser:** Chrome Version 83.0.4103.61 (Official Build) (64-bit)
**OS:** codesandbox
**Playground code that reproduces the issue:**
[codesandbox sample](https://codesandbox.io/s/monaco-editor-sample-xe65v?file=/src/index.js)

**Steps:**

1. Hide container with `display="none"`
2. Use `executeEdits` to change content to a long string
3. Show container with `display=""`

**Actual:**
The horizontal scrllbar is not visible, can't view the rest of the text. try to call `layout()` method but not working.
![GIF 2020-6-2 14-40-16](https://user-images.githubusercontent.com/6482819/83488243-17ab8380-a4df-11ea-822e-13b888dfa577.gif)

**Expected:**
It should be possible to browse the rest through the horizontal scrollbar.
![GIF 2020-6-2 14-40-16](https://user-images.githubusercontent.com/6482819/83488799-031bbb00-a4e0-11ea-8d62-8334972bb868.gif)

**Comment by alexdima** [comment]
It is unexpected that the editor is hidden while it displays a file (while its view is up and running). Before hiding the editor's container, please detach the model from the editor. You can use the following code pattern:
```
const viewState = editor.saveViewState();
const model = editor.getModel();
editor.setModel(null);
// hide the container
// ...
// restore the container
editor.setModel(model);
editor.restoreViewState(viewState);
```
