### ISSUE TITLE
Language syntax VB: backslash is not an escape character

### ISSUE THREAD

**Issue by pablonete** [microsoft/monaco-editor#1996]
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Windows
**Playground code that reproduces the issue:**

Open https://microsoft.github.io/monaco-editor/
Select Language vb

```
Print "Hola" & "\" & Name
' This line should be green. \ is not an escape in VB.
```

The backslash is not an escape character, so ending quote should be considered.

**Comment by kinloongTong** [comment]
I have the same problem.

**Comment by chilipepperpizza** [comment]
Looks like there is a PR for this issue - https://github.com/microsoft/monaco-languages/pull/90

**Comment by fowl2** [comment]
this issue is a duplicate of #1958
