### ISSUE TITLE
addExtraLib() is not working as expected after disposing the previously added library

### ISSUE THREAD

**Issue by jithamanyumanne** [microsoft/monaco-editor#1998]
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** macOS High Sierra

I am adding extraLibrary to the monaco using the following code
```
const carDisposable = monaco.languages.typescript.javascriptDefaults.addExtraLib("declare class Car{ 
start()
stop()
 }", "Car");
```

The code in the editor is as follows
``` const myCar = new Car();```

Now I want to dispose the same and add again with the new methods
```
carDisposable.dispose();
monaco.languages.typescript.javascriptDefaults.addExtraLib("declare class Car {  
start() 
applyBreak()
accelerate()
 }", "Car");
```

Now in the editor if I am using `myCar.`  then I am getting  start() and stop(). Ideally I should get start(), applyBreak() and accelerate().

**Comment by paranoidjk** [comment]
+1 same problem here

**Comment by wenshiqi0** [comment]
There is a time racing here.

```js
	addExtraLib(content: string, _filePath?: string): IDisposable {
		let filePath: string;
		if (typeof _filePath === 'undefined') {
			filePath = `ts:extralib-${Math.random().toString(36).substring(2, 15)}`;
		} else {
			filePath = _filePath;
		}

		if (this._extraLibs[filePath] && this._extraLibs[filePath].content === content) {
			// no-op, there already exists an extra lib with this content
			return {
				dispose: () => { }
			};
		}

		let myVersion = 1;
		if (this._extraLibs[filePath]) {
			myVersion = this._extraLibs[filePath].version + 1;
		}

		this._extraLibs[filePath] = {
			content: content,
			version: myVersion,
		};
		this._fireOnDidExtraLibsChangeSoon();

		return {
			dispose: () => {
				let extraLib = this._extraLibs[filePath];
				if (!extraLib) {
					return;
				}
				if (extraLib.version !== myVersion) {
					return;
				}

				delete this._extraLibs[filePath];
				this._fireOnDidExtraLibsChangeSoon();
			}
		};
	}
```

If you use the same specific filePath to add content, and not listen to the `OnDidExtraLibsChange` Event, you will bit this problem.

**Comment by wenshiqi0** [comment]
And the code comes from `monaco-typescript`.

**Comment by alexdima** [comment]
You could make the second call to use `"Car2"` or you can simply leave empty that argument. I think the problem is that removing + adding another lib will make it that there still is the lib at version 1. So the TS worker does not refresh the content of that lib.
