### ISSUE TITLE
Mouse operations fail when the editor is hosted inside a fixed container

### ISSUE THREAD

**Issue by gusdaud** [Microsoft/monaco-editor#2]
Hey, thanks for the excelent work.

Monaco editor selection doesn't work properly when it's inside a div with position fixed/absolute and document has being vertically scrolled.

<body scrollTop="> 0">
  <dialogboxdiv style='position: fixed'>
     <MonacoEditor/>

My workaround is to manually change body scroll top to 0 when dialogbox is shown.

**Comment by alexandrudima** [comment]
@gusdaud Can you please provide a minimal HTML page or snippet that reproduces the problem and name the browser/browsers versions that show it?

**Comment by gusdaud** [comment]
![sample](https://cloud.githubusercontent.com/assets/13708461/16216215/616056fc-373f-11e6-849f-e512dc1a706d.gif)

**Comment by gusdaud** [comment]
@{Layout = "";}
<html>
<head>
    <script src="/Scripts/Vendor/monaco-editor/dev/vs/loader.js"></script>
    <script>
        require.config({ paths: { 'vs': '/Scripts/Vendor/monaco-editor/min/vs' } })
        require(['vs/editor/editor.main'], function() {
            window.editor = window.monaco.editor.create(document.getElementById('Editor'),
            {
                value: document.documentElement.innerHTML,
                language: 'xml'
            });
            setTimeout(function() { window.scroll(0, 200) }, 2000);
        });
    </script>
</head>
<body style="height:2000px">
<div style="position: fixed; left: 20%; top: 20%; right: 20%; height: 400px; border:1px solid silver" id="Editor">
</div>
</body>
</html>

**Comment by gusdaud** [comment]
```html
<html>
<head>
    <script src="/Scripts/Vendor/monaco-editor/dev/vs/loader.js"></script>
    <script>
        require.config({ paths: { 'vs': '/Scripts/Vendor/monaco-editor/min/vs' } })
        require(['vs/editor/editor.main'], function() {
            window.editor = window.monaco.editor.create(document.getElementById('Editor'),
            {
                value: document.documentElement.innerHTML,
                language: 'xml'
            });
            setTimeout(function() { window.scroll(0, 200) }, 2000);
        });
    </script>
</head>
<body style="height:2000px">
<div style="position: fixed; left: 20%; top: 20%; right: 20%; height: 400px; border:1px solid silver" id="Editor">
</div>
</body>
</html>
```

**Comment by gusdaud** [comment]
There you go. I hope it helps.
