### ISSUE TITLE
Ability to grab contents of editor as text.

### ISSUE THREAD

**Issue by aarinsmith** [Microsoft/monaco-editor#20]
Is this a possibility? Say I wanted to include the contents of the editor as part of a form and submit the entered text? Codemirror supports this by allowing you to bind the editor to a textarea. Binding it like this is not really necessary in my specific situation but an easy call to grab the contents of the editor as text would be helpful. Is this possible?

**Comment by MohammadYounes** [comment]
Yes, Try this in the [playground](https://microsoft.github.io/monaco-editor/playground.html)

```js
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
console.log(editor.getValue())
```

**Comment by aarinsmith** [comment]
Awesome thanks for the quick response. I had assumed there was a simple solution to this but was for some reason unable to find it.

**Comment by M-Yankov** [comment]
So, it's not OK to put the editor inside a `<form>` and expect to get the full content to be send to the server. The value should be retrieved with `editor.getValue()` just before submit the form.
