### ISSUE TITLE
using code after saving from the editor

### ISSUE THREAD

**Issue by GlauberF** [microsoft/monaco-editor#2003]
First I apologize if my question is too obvious, I am new to this.

Today, I have an internal CMS inside the company, which some pages have editable javascript.
So, when the user edits / creates I take the final result which is a code string and save it in the database and if afterwards he goes to edit again, I take that string in the database and start the editor again.

My question, is there a way to convert this string into code, because inside the editor everything is a big string.
however for me to use this javascript code, it cannot be a string.

today i use `eval()`, to convert this javascript string to javascript code.
is there any other way to do this?

**Comment by martin-pabst** [comment]
You should use window.Function() instead of eval(), [see Article here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!).

**Comment by martin-pabst** [comment]
If i understand aright your data flows like this:

a1) Text inside monaco-editor in Browser -> b1) server-side database -> c1) Text inside monaco-edtor in Browser (to edit again) or alternatively

a2) Text inside monaco-editor in Browser -> b2) server-side database -> c2) executed javascript-Program in Browser

Does your question concern the transition b2) -> c2)? Then couldn't you simply write a servlet which retrieves the script text from your database and serves it to the client? Client-side you then embed the script by calling this servlet inside a script-tag (<script src="URL of your servlet"></script>). That way it gets compiled at page load time.

**Comment by GlauberF** [comment]
@martin-pabst so, i thought that maybe there was something in the monaco editor itself, to extract / recover the content that is in string for javascript code.

I have little knowledge of servlet, do you have an article?

**Comment by luminaxster** [comment]
@GlauberF what do you mean by: 
>the content that is in string for javascript code

 or 

>for me to use this javascript code, it cannot be a string

Do you need to wrap into a module to use it in a running web app?  How is the code from the editor going to be injected somewhere? Maybe you need [Babel](https://babeljs.io/docs/en/babel-standalone) to transpile, polyfill and bundle it as a module. Like this:
```js
        Babel = await import('@babel/standalone');
        const options = {
            presets: [
                'env',
                'react',
            ],
            plugins: Object.keys(Babel.availablePlugins)
                .filter(key =>
                    key === pluginName ||
                    key.includes('proposal-') &&
                    !key.includes('proposal-decorators') &&
                    !key.includes('proposal-pipeline-operator')
                )
        };
        const transform = sourceCode => Babel.transform(sourceCode, options);
```

 Then you can add it the transpiled code to you web app:
```js
const appendScript = (doc = document, script) => {
    const scriptEl = doc.createElement("script");
    scriptEl.type = 'text/javascript';
    doc.body.appendChild(scriptEl);
    scriptEl.innerHTML = script;
};
// like this perhaps
appendScript(document, transform(monacoEditorContentStringFromDatabase));
```

**Comment by martin-pabst** [comment]
@GlauberF : What language do you use server-side?

**Comment by GlauberF** [comment]
@martin-pabst PHP (Laravel)

**Comment by GlauberF** [comment]
@luminaxster I will study babel and see if I can find a way to do that.
Why I care about performance, because my step-by-step until rendering is:

1 - User clicks on any system module.
2 - Frontend opens the module immediately and the screen is loaded with skeleton format.
3 - Frontend calls api (laravel / php) and looks for the code that is in the database (mongodb) in string format.
4 - Frontend converts string to code with eval ().
5 - I render the code and remove the load.

if i use babel, i will have to create one more API call, to convert, this would cause one more step and delay the workflow.
I don't know if it's possible, but maybe I could use babel in the web application without having to create another API to generate this conversion.

But then I have another challenge, including the babel, my final bundle can increase dramatically

**Comment by luminaxster** [comment]
@GlauberF I see, perhaps go the Babel way on the backend, not the client since the frontend calls the backend to read the latest from the server anyways. Actually, for better performance create a babel bundle service on the server and then send it to the client, it will make be your code robust due to polyfill to mention one of the benefits. You may need express.js to create the backend service to get the bundled code. That is, your step 3 will now send a JSON file containing the bundle, and in step 4 don't use eval but append a script or a function like @martin-pabst  suggested. There are several ways you can about this, I do it client-side, but others (CodeSandBox) do it server-side.

**Comment by GlauberF** [comment]
I will close the issue, I believe I already know the right approach.
