### ISSUE TITLE
Improve SQL syntax highlighting

### ISSUE THREAD

**Issue by dubchenko** [microsoft/monaco-editor#2004]
I notice that words like `INTEGER` and `VARCHAR` are picked up as keywords and highlighted in blue instead of being normal text. However, neither `BOOL` nor `BOOLEAN` seem to be identified as keywords which seems a little strange

``` SQL
INTEGER VARCHAR BOOL BOOLEAN
```

![image](https://user-images.githubusercontent.com/11248989/84415006-d3c12880-ac1a-11ea-9f92-5b818d99701d.png)

**Comment by AndersMad** [comment]
maybe you are using `SQL` and not `MYSQL`? the first has no `BOOL` - see https://github.com/microsoft/monaco-languages/blob/master/src/mysql/mysql.ts vs. https://github.com/microsoft/monaco-languages/blob/master/src/sql/sql.ts

**Comment by dubchenko** [comment]
@AndersMad you're right, thank you!
