### ISSUE TITLE
Cmd+Scroll to zoom on a mac

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/monaco-editor#201]
Most mac users would be used to using Cmd + Key for their shortcuts. 
Cmd+Scroll doesn't work on a mac. Although Ctrl+Scroll works. 

monaco-editor npm version: 0.6.1
Browser: Safari + Chrome
OS: Mac OSX

**Comment by alexandrudima** [comment]
@microsoftsam Is it that all apps on mac zoom with cmd+scroll and not with ctrl+scroll?

@weinand maybe you also know?

**Comment by microsoftsam** [comment]
It's not common for applications to use Ctrl/Cmd + Scroll to zoom on a mac. Sublime Text and Textmate both only support Cmd + Plus/Minus to zoom in/out. (No scroll zoom)
I guess that's more of an argument to support keyboard shortcuts to zoom in / out in monaco. However, since monaco already supports Ctrl+Scroll to zoom. I would say the Cmd+Scroll is more appropriate for a mac user.
