### ISSUE TITLE
editor.action.selectAll is missing

### ISSUE THREAD

**Issue by briankwon21** [microsoft/monaco-editor#2010]
Hi, I'm trying to run Select All programmatically, and `editor.action.selectAll` is missing.

**monaco-editor version:** 0.20.0

Here are all the available monaco editor actions I see:
![image](https://user-images.githubusercontent.com/1195873/84839665-76e6b900-aff2-11ea-9330-33b5c1379876.png)
![image](https://user-images.githubusercontent.com/1195873/84839686-7fd78a80-aff2-11ea-958d-bcf832e316c1.png)
![image](https://user-images.githubusercontent.com/1195873/84839708-8bc34c80-aff2-11ea-8b40-a73da79c0274.png)
![image](https://user-images.githubusercontent.com/1195873/84839713-91209700-aff2-11ea-8527-e5bcc7526009.png)

**Comment by brijeshb42** [comment]
You can create full range and set selection using -

```js
const range = editor.getModel().getFullModelRange();
editor.setSelection(range);
```

**Comment by briankwon21** [comment]
Thanks @brijeshb42, that does the trick!
