### ISSUE TITLE
is there a method or api to perform find/replace operation without showing the  find/replace  widget 

### ISSUE THREAD

**Issue by asthaaaaaa** [microsoft/monaco-editor#2011]
I am trying to perform Find/Replace operation without showing the widget.
I tried by editor.getAction('actions.find').run() and editor.getAction('editor.action.startFindReplaceAction').run()  but they open the widget to perform the actions.

I also found `**editor.trigger(monaco.KeyMod.CtrlCmd + monaco.KeyCode.KEY_P, 'type', { text: 'hello' })**`; but this pastes the test direct in the editor.
I am looking for a way I can trigger a find action and pass the payload as the "search text".

**Comment by spahnke** [comment]
You can use https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#findmatches to search for matches. From there you can use the returned objects to do replace operations by using appropriate methods on the model.
