### ISSUE TITLE
<input> tag incorrectly auto-formatted

### ISSUE THREAD

**Issue by dominykasraila** [microsoft/monaco-editor#2013]
![image](https://user-images.githubusercontent.com/26777152/84876523-faa2b300-b08f-11ea-9c3c-be88d20c91b5.png)
Lines 24-25 are incorrectly auto-formatted.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
