### ISSUE TITLE
Public API for controlling the EOL style

### ISSUE THREAD

**Issue by mrozekma** [microsoft/monaco-editor#2019]
For cross-platform reasons (see FirebaseExtended/firepad#315), I need to force the editor to use a particular line ending. I see [setEOL](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#seteol)/[pushEOL](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#pusheol) on the model, but that seems to change the current contents of the editor but not set the EOL permanently -- if the editor is cleared or replaced with other text, the set EOL can be lost.

From poking around the code, I found that the default EOL comes from `SimpleResourcePropertiesService.getEOL`, and varies by platform, but first it tries to read the `files.eol` configuration value. Thus I can fix the problem by setting that value:

```js
import { StaticServices } from 'monaco-editor/esm/vs/editor/standalone/browser/standaloneServices';
StaticServices.configurationService.get().updateValue('files.eol', '\r\n');
```

This works, but I don't think this is supposed to be a public interface. Can some better way to enforce a particular line ending be added to the editor or text model?

**Comment by brijeshb42** [comment]
What we used as a solution was to replace all `setValue` calls with -

```js
function newSetValue(model, newValue) {
  model.applyEdits([{ text: newValue, range: model.getFullModelRange()}]);
}
```

**Comment by alexdima** [comment]
Yes, `setValue` calls will reset the EOL to the new content passed in. The solution is to change the EOL after calling `setValue` or to use `applyEdits` to change the contents.
