### ISSUE TITLE
Better docs on website

### ISSUE THREAD

**Issue by athyuttamre** [microsoft/monaco-editor#2020]
In implementing a project using Monaco,  I've found the lack of dedicated docs (quickstarts, guides, references, recipes, etc.) a problem. I've mostly found my way around by reading old issues, StackOverflow answers, and searching in the API reference, but more prose would have been helpful.

Is there a plan to create a dedicated docs site? https://docusaurus.io makes this somewhat easy, if we wanted to use it. I'm happy to help contribute some initial text.

**Comment by AmyQianqianwang** [comment]
Not only that，I also think Monaco can provide developers with  the new feature introduction of different versions.

**Comment by LeoDog896** [comment]
Hello! This issue is quite stale, but I would like to bring it up again -- would pull requests for quickstarts and others be integrated into monaco's documentation website?

**Comment by hediet** [comment]
We currently don't plan to add more docs.
