### ISSUE TITLE
Quick Suggestions with loading message

### ISSUE THREAD

**Issue by ivhanvillapando** [microsoft/monaco-editor#2021]
Hello, 

I am trying to create an intellisense / code completion using CompletionItemProvider and I would like to display the "loading..." message when I press the triggered character which is dot ('.') just like what happened on the GIF below after I type FROM and then ctr+space the loading message is displayed then the completion items afterwards. I added a timeout there that's why it shows the loading message before the completion items and I would like to to the same thing when I pressed dot ('.') after a word.

![myFile](https://user-images.githubusercontent.com/67623061/86087983-00f54e00-bad8-11ea-85cb-8b6be234710d.gif)

**Comment by alexdima** [comment]
I think that suggestions have two big modes of working. 

One is that they are triggered manually, by the user. So the user presses ctrl+space to see suggestions. In that case, the suggestion widget renders `Loading...` while the results are computed. This is to give the user assurance that their command has been interpreted and the results are computing. 

The automatic triggers, like pressing `.` are not indicative of a user explicitly asking for suggestions. It is possible that the user keeps on typing after `.` and does not want to see a `Loading...` message in their face. So in this case the suggestions render directly when the result came in.
