### ISSUE TITLE
context menu gets scrollbar when not needed

### ISSUE THREAD

**Issue by dsmmcken** [microsoft/monaco-editor#2022]
**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:**
https://microsoft.github.io/monaco-editor/

Shorten your browser window, and scroll the monaco editor on the playground to be mostly at the bottom of the screen. Context menu click in a location similar to in screen shot.

Results: the context menu flips to draw upward, as there isn't room below, but it still uses its previous small height and overflow scroll bar.

Expected result: menu occupies full space upwards as there is room to display the menu.

![image](https://user-images.githubusercontent.com/1576283/86145760-5411d580-bac5-11ea-9740-cf082d6c1d2f.png)

**Comment by sbatten** [comment]
@alexdima this issue appears to be fixed when running out of sources, but I think there may be a separate issue with fonts in the shadow dom element. how should I coordinate a fix for that and the release with you?

**Comment by alexdima** [comment]
@sbatten Thanks for looking into this. I am planning to create a new editor release based off the branch `standalone/0.21.x` -- https://github.com/microsoft/vscode/tree/standalone/0.21.x . If you would like to push a fix for it also to the upcoming editor 0.21 release, then please cherry pick and push to that branch (no PR needed).

**Comment by alexdima** [comment]
I think this was fixed before the endgame freeze, because I cannot reproduce running from `standalone/0.21.x`:

![image](https://user-images.githubusercontent.com/5047891/92727347-3f787600-f36f-11ea-8323-44d15d606299.png)
