### ISSUE TITLE
File `min/vs/editor/editor.main.js` has a different whitespace in npm and unpkg.

### ISSUE THREAD

**Issue by djy0** [microsoft/monaco-editor#2025]
**monaco-editor version:** 0.20.0(6363745c0a33c27b149b89342a7b96d354fb554c)
**Browser:** any
**OS:** any
**Playground code that reproduces the issue:** currently no

### Reproduction steps:

diff compare files from unpkg:
**https://unpkg.com/monaco-editor@0.20.0/min/vs/editor/editor.main.js**
and the one installed with yarn:
**node_modules/monaco-editor/min/vs/editor/editor.main.js**

You can see they diff in one character (the white space between `<span><span>` and `</span></span>`),
this character is U+00A0 in the file installed by yarn and U+0020 for unpkg version.

The U+00A0 no break white space charactor would cause html files that's haven't specified a charset to display Â(U+00C2) on empty lines on windows 10 os chrome or firefox browser.

**Comment by alexdima** [comment]
I believe this is a problem with `unpkg`. They should not touch JS code before serving it. But I will remove the usage in our code base to avoid this.

**Comment by djy0** [comment]
Thank you
