### ISSUE TITLE
Make column selection mode available in Monaco code editor

### ISSUE THREAD

**Issue by planger** [microsoft/monaco-editor#2035]
It looks like the standalone Monaco code editor doesn't support the _column selection mode_, which is available however in VSCode (command "Toggle Column Selection Mode"). Since this is a plain code-editor--related capability and one of the few plain editor-related capabilities that appear to be missing, I was wondering whether it wouldn't make sense to have that as a standalone Monaco feature too.

Is there a particular reason that I'm missing, why it shouldn't be part of the standalone Monaco editor?
Please let me know what you think! Thanks a lot!

**Comment by rcjsuen** [comment]
![image](https://user-images.githubusercontent.com/15629116/87332833-36536000-c50a-11ea-8b05-9405075bc8b9.png)

@planger It seems like you can still start it up with hotkeys though. 🤔

**Comment by planger** [comment]
@rcjsuen Yeah, you are right!  <kbd>Alt</kbd>+<kbd>Shift</kbd> works fine in plain Monaco. I think most of the capabilities seem to be already there!

However, the property appears to be missing in the [Monaco editor options](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#editoroptions), while the property obviously [exists in VSCode](https://github.com/microsoft/vscode/blob/d17550f4a8249baab72afe551f67c4c997bd2315/src/vs/editor/common/config/editorOptions.ts#L340). Also there appears to be no Monaco command for toggling column selection mode, which then would sort-of behave like automatically pressing <kbd>Alt</kbd>+<kbd>Shift</kbd> while dragging with the mouse (but not while just clicking, which resets the selection; also using the cursors is slightly different than keeping <kbd>Alt</kbd>+<kbd>Shift</kbd>).

Thanks for the lightning fast comment, btw! :-)

**Comment by nrayburn-tech** [comment]
It looks like it is how the action is registered.  I will see if I can make a PR for it.

Here is the doc that explains why it isn't available.
```
	 * Registers a workbench action to the platform. Workbench actions are not
	 * visible by default and can only be invoked through a keybinding if provided.
	 * @deprecated Register directly with KeybindingsRegistry and MenuRegistry or use registerAction2 instead.
	 
```

**Comment by alexdima** [comment]
The option will be available with the upcoming release -> it is called `columnSelection` and can be set to `true` (it is `false` by default)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/monaco-editor/issues/2074
