### ISSUE TITLE
registerCompletionItemProvider callBack

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2038]
I don't know whether we didn't provide it or I didn't find such an interface. My functional requirement is that you can insert text in a certain line by using the Enter key, and then you can get the content selected in the auxiliary list and insert it in another line.

For example, during java development, we input a class name below and use input assistance to import this class above. However,through 'registercompletionitemprovider',I can't do it.
So，I want to get a little help on how to do this

**Comment by rcjsuen** [comment]
@y912765390 Did you check out the [example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example)?
