### ISSUE TITLE
How to create cursor's nameTag?

### ISSUE THREAD

**Issue by anhminhtran235** [microsoft/monaco-editor#2039]
Hi, I'm trying to create a nameTag like this: 

![nameTag](https://user-images.githubusercontent.com/54651212/87607270-ce3f7e00-c6b1-11ea-91cd-27c404ed15f3.PNG)

I have successfully created a cursor by following [#366](https://github.com/microsoft/monaco-editor/issues/366) and [line and inline decoration](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations), but to my understanding, decoration will only style the 'box' that each char is in. The nametag, however, is outside that 'box'. How can we achieve this?

Thank you

**Comment by spahnke** [comment]
This example shows the use of content widgets and view zones https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-mouse-events. Does that help?

**Comment by anhminhtran235** [comment]
Hi, that is very helpful. Is there a way to add a widget that will move as I type - similar to the way decoration does? (I can certainly write some code to make it behaves as I want but I'm just wondering if that is an option)

**Comment by anhminhtran235** [comment]
I found a way (doesn't look as good as content widget but simpler): Simply add 'hoverMessage' to decoration. When we hover on that decoration, the name will appear.
