### ISSUE TITLE
monaco-json npm install fails

### ISSUE THREAD

**Issue by Hirse** [Microsoft/monaco-editor#204]
monaco-json version: 1.0.5-next.1
node version: 6.5.0
OS: Win 10

--
When following the [monaco-json dev setup guide](https://github.com/Microsoft/monaco-json/#dev-running-monaco-json-from-source) the `npm install` step fails because the `gulp release` task fails with the following message:
> [13:40:41] Starting 'release'...
Error: Error: ENOENT: no such file or directory, open 'c:\out\vscode-uri.js'
In module tree:
    vs/language/json/jsonWorker
      vscode-json-languageservice
        vscode-json-languageservice/services/jsonSchemaService

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by alexandrudima** [comment]
@Hirse Thanks for the heads up, I adopted the same thing monaco-html does in that area and it seems to get it bundling again
