### ISSUE TITLE
Scrollbar state confused when Monaco is used within a custom element shadowRoot context

### ISSUE THREAD

**Issue by klebba** [microsoft/monaco-editor#2040]
**monaco-editor version:** 0.20.0
**Browser:** Chrome 83.0.4103
**OS:** macOS 10.15.5

### Issue:
When Monaco is rendered inside a custom element with a shadowRoot, the scrollbar scrollState is confused when the cursor leaves the footprint of the Monaco editor, causing the scrollbar to jump throughout the file unexpectedly. 

Curiously the issue is not present in Firefox 78.0.2, but does occur similarly in Safari 13.1.1.

### Video demo:
https://streamable.com/r374vd

### Live demo:
https://klebba.github.io/monaco-editor-scrolling-bug/src/

### Source of repro case:
https://github.com/klebba/monaco-editor-scrolling-bug/tree/master/src

Thanks in advance for investigating!

Casey

cc @codeStryke @erahhal

**Comment by klebba** [comment]
@alexdima can you give some indication of the project priority for addressing the `editor-shadow-dom` group of issues? Should we expect Monaco to eventually function in a shadow root context? Thanks!

**Comment by alexdima** [comment]
No.

**Comment by klebba** [comment]
Ok, no problem — thanks for taking a look.
