### ISSUE TITLE
 setModelMarkers. add 700 markers ，But The part that exceeds 500 is not displayed

### ISSUE THREAD

**Issue by chenxilin951207** [microsoft/monaco-editor#2042]
monaco-editor version: 0.17.1~0.19.3
Browser: Chrome
OS: Windows 10

I added 700 markers successfully, but the 500th and subsequent markers are not displayed on the page. 

```
          let markers = []
			for(let i=0;i<700;i++){
				markers.push({
					message: "Strings must use doublequote.",
					startLineNumber: i+1,
					startColumn: 1,
					endLineNumber: 200,
					endColumn: i+1,

					severity: monaco.MarkerSeverity.Warning
				})
			}
			monaco.editor.setModelMarkers(diffEditor.modifiedEditor.getModel(), "", markers);
```

**Comment by chenxilin951207** [comment]
I read the source code and find this code in markerDecorationServicelmpl.js.


```
 MarkerDecorationsService.prototype._updateDecorations = function (markerDecorations) {
        var _this = this;
        // Limit to the first 500 errors/warnings
        var markers = this._markerService.read({ resource: markerDecorations.model.uri, take: 500 });
        var newModelDecorations = markers.map(function (marker) {
            return {
                range: _this._createDecorationRange(markerDecorations.model, marker),
                options: _this._createDecorationOption(marker)
            };
        });
        markerDecorations.update(markers, newModelDecorations);
        this._onDidChangeMarker.fire(markerDecorations.model);
    };
```
how to change take:500
```
    var markers = this._markerService.read({ resource: markerDecorations.model.uri, take: 500 });
```

**Comment by alexdima** [comment]
This is a limit hard coded in the marker service. The idea is that it is of 0 value to an end user to present them with error number 501, 502, etc. if there are 500 errors in a text model. This most likely indicates some configuration problem and if that's not the case, then the end user can go and fix the first problem, the second problem, etc.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
