### ISSUE TITLE
The `monaco-editor-webpack-plugin` can't compile with this version(`monaco-editor@0.19.0`)

### ISSUE THREAD

**Issue by wang12124468** [microsoft/monaco-editor#2046]
**monaco-editor version:** 0.19.0
**Browser:** *
**OS:** *
**Playground code that reproduces the issue:**

The `monaco-editor-webpack-plugin` can't compile with this version(`monaco-editor@0.19.0`).

![image](https://user-images.githubusercontent.com/17714343/87773168-590cae00-c855-11ea-89bd-941fdc445bd6.png)

**Comment by alexdima** [comment]
Please see https://github.com/microsoft/monaco-editor-webpack-plugin/#version-matrix

![image](https://user-images.githubusercontent.com/5047891/92652830-c84ecd80-f2ed-11ea-813a-ec59ecb3dfd0.png)
