### ISSUE TITLE
What should be used as IIdentifiedSingleEditOperation?

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#205]
I use `null`  for `IIdentifiedSingleEditOperation` and it seems to work, but the property is not marked as an optional. I wonder what actually should be used.

**Comment by alexandrudima** [comment]
:+1: I need to clean that up. I use that as an `id` that is found again in the inverse edit operations ... Imagine pushing 200 edits and getting 200 inverse edits (undo edits), it's like some sort of correlation token, inverse edit `A` corresponds to edit `A`, etc.

I need to clean that up, using `null` should be fine (I think) :)
