### ISSUE TITLE
Accessibility need: tabindex change to pass html attributes to markup from API use.

### ISSUE THREAD

**Issue by lee-leonardo** [microsoft/monaco-editor#2050]
PWABuilder issue listed here: https://github.com/pwa-builder/PWABuilder/pull/985

Essentially the api doesn't allow us access to the html below which can cause problems with experiences that include modals. Where we would like to disable the code editor temporarily so that the modal can receive focus easier.

Steps to repro:
1. navigate to pwabuilder.com
2. type in a url (pwa or not).
3. navigate to the manifest section
4. open the images tab
5. click the upload button
6. use TAB to try to navigate to the modal input. Notice once the editor gains focus, it doesn't lose it, the editor is being edited.

We are using a component that wraps the editor, but here's our end of the usage:
https://github.com/pwa-builder/PWABuilder/pull/985/files

**Comment by alexdima** [comment]
@lee-leonardo I'm not quite sure what it is you are asking for. Can you please explain in greater detail what you mean that the API doesn't allow access to the html below?
