### ISSUE TITLE
Trigger Hovers Programmatically

### ISSUE THREAD

**Issue by bitjson** [microsoft/monaco-editor#2052]
I'm trying to implement end-to-end visual difference testing for an application which uses Monaco Editor extensively ([Bitauth IDE](https://github.com/bitauth/bitauth-ide)), and I'm having trouble triggering hover behaviors. The Cypress testing framework [does not yet support triggering native hover events](https://github.com/cypress-io/cypress/issues/10), so hover behavior must be be tested with JS or CSS emulation.

<details>
<summary>(Screenshot of a visible hover in Bitauth IDE)</summary>
<img width="1492" alt="Screen Shot 2020-07-23 at 6 28 45 PM" src="https://user-images.githubusercontent.com/904007/88344893-a768f380-cd12-11ea-85a1-81bbb9d4db40.png">
</details>

Is it possible to trigger a hover via the exposed editor API?

I can't seem to trigger the hover with either the Cypress-emitted events or events emitted via:
```js
temp1.dispatchEvent(new MouseEvent('mouseover', {bubbles: true}))
```

It seems like I need to be able to call `ViewController.emitMouseMove` from my application, but I'm having trouble figuring out if/where it is exposed in the API.

I also found [a test which triggers `CoreNavigationCommands.MoveTo` in `findModel.test.ts`](https://github.com/microsoft/vscode/blob/3bd820b15c79eebf0d5a86e53d8ca189b7a98c6b/src/vs/editor/contrib/find/test/findModel.test.ts#L323-L325), but this also doesn't display the hover tooltip:
```js
editor.trigger('mouse', '_moveTo', { position: { lineNumber: 1, column: 1 }});
```

How can hovers can be triggered in Monaco Editor?

**Comment by alexdima** [comment]
You can do something like:

```
const ed = monaco.editor.create(document.getElementById("container"), {
    value: "body { background: red; }",
    language: "css"
});
setTimeout(() => {
    ed.setPosition(new monaco.Position(1, 21));
    ed.getAction('editor.action.showHover').run();
}, 1000);
```

See https://github.com/microsoft/monaco-editor/issues/1940#issuecomment-687169572
