### ISSUE TITLE
"Cannot read property 'kind' of undefined" is thrown by declaring unassigned constants after exported const in JS

### ISSUE THREAD

**Issue by jpinilloslr** [microsoft/monaco-editor#2058]
**monaco-editor version:** 0.20.0
**Browser:** Google Chrome, Safari, Microsoft Edge
**OS:** MacOS Catalina 10.15.6

1. Open the Monaco Editor homepage: https://microsoft.github.io/monaco-editor/
2. Select `javascript` or `typescript` language.
3. Paste this code:

```js
export const foo = 1;
const bar
```

Actual result: The following error is printed to the browser console:
```
Uncaught Error: Cannot read property 'kind' of undefined

TypeError: Cannot read property 'kind' of undefined
    at Object.e.isImportClause (tsWorker.js:21)
    at Object.n.deleteDeclaration (tsWorker.js:21)
    at r (tsWorker.js:21)
    at n.finishDeleteDeclarations (tsWorker.js:21)
    at n.getChanges (tsWorker.js:21)
    at Function.n.with (tsWorker.js:21)
    at Object.getCodeActions (tsWorker.js:21)
    at tsWorker.js:21
    at Object.e.flatMap (tsWorker.js:21)
    at Object.n.getFixes (tsWorker.js:21)
    at errors.ts:22
```

Expected result: No errors are shown in the browser console.

Screenshot:
![image](https://user-images.githubusercontent.com/36177784/88700318-d0212c80-d108-11ea-8293-6723e06f7803.png)

**Comment by rcjsuen** [comment]
@jpinilloslr Sounds like #1779.

**Comment by jpinilloslr** [comment]
That's right @rcjsuen, it looks like the same issue. Tracked by microsoft/TypeScript#33726.
