### ISSUE TITLE
Monaco-editor Smart prompt box style is incorrect

### ISSUE THREAD

**Issue by Beck-WuYu** [microsoft/monaco-editor#2059]
This is my code

webpack.conf.js
----------
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

 new MonacoWebpackPlugin({
      languages: ["xml"],
      features: ["coreCommands", "find"]
})
```

MonacoEditor.js
----------
```
import * as monaco from 'monaco-editor'
this.xmlEditor = monaco.editor.create(this.xmlDom, {
            value: value,
            language: "xml",          
            theme: "vs-dark",          
            //automaticLayout: true,     
            readOnly: false,
 });
```

final effect
![企业微信截图_15959923749186](https://user-images.githubusercontent.com/11955454/88752522-bcb7a500-d18c-11ea-8e79-352dd3e17b94.png)

but monaco home effect
![企业微信截图_1595992841991](https://user-images.githubusercontent.com/11955454/88752942-a231fb80-d18d-11ea-82ab-bfa7155c19bf.png)

Is this something wrong?

**Comment by Beck-WuYu** [comment]
i think i konw what's problem happen. The style “main” name is very common。My project style conflicts with monoca。I suggest monoca style have unique name。

**Comment by alexdima** [comment]
The current solution is to attempt to write CSS on your side that doesn't target the editor. The other solution is to use shadow DOM and load the editor in a shadow root node.
