### ISSUE TITLE
JSON Schema suggestion after dot

### ISSUE THREAD

**Issue by wupengFEX** [microsoft/monaco-editor#2062]
I need to have such a function and I don’t know if it can be realized, so let me talk about the specific needs: When i type dot in value, it can show a list from remote or local value obtained by calculation. @rcjsuen @alexdima 

![image](https://user-images.githubusercontent.com/8186657/88920119-e3660080-d29e-11ea-99b5-f346c2f95517.png)

At the same time i try to use `registerCompletionItemProvider`, but it didn't come true, could you give me an example for this, thanks a lot!

**Comment by WhileTrueEndWhile** [comment]
Try to build your own monaco-json. It has it's own build process to create an independent bundle.
See https://github.com/microsoft/monaco-json/blob/master/src/languageFeatures.ts#L248

Good luck ;-)

**Comment by wupengFEX** [comment]
> Try to build your own monaco-json. It has it's own build process to create an independent bundle.
> See https://github.com/microsoft/monaco-json/blob/master/src/languageFeatures.ts#L248
> 
> Good luck ;-)

I understand that what you said is the same as [this example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example), but it cannot achieve the effect I said. Even if I return new suggestions after entering a word, he will not show a list of suggestions

**Comment by alexdima** [comment]
I'm sorry, I have no idea. The best is to fork `monaco-json` and implement your own custom completion item provider, as was suggested above.
