### ISSUE TITLE
Start and end line numbers of "undo"/"redo" actions are not showing correctly. 

### ISSUE THREAD

**Issue by DineshKarri443** [microsoft/monaco-editor#2063]
I am looking for a way to get the range that will be inserted/deleted, when monaco editors "undo" action is performed.

Ideally I use the onDidChangeModelContent to get the range that has been pasted, entered, removed. But for undo/redo action, although I can get hold of isUndoing/isRedoing on the event, the startLineNumber and endLineNumbers are always showing the line where the undo action is being performed. But it does not show the actual lines and positions where the undo action is going to happen.
```
this.editor.onDidChangeModelContent(e => {
    if(e.isUndoing){
    const {startLineNumber,endLineNumber}   = e.changes[0].range;
       // performing my logic on these line numbers here.
   }
```

![image](https://user-images.githubusercontent.com/68352790/89029562-5d07f800-d34c-11ea-8929-8a645929855f.png)

How can I get hold of these start and end line numbers on undo/redo actions ?

**Comment by alexdima** [comment]
The events fire after the edit has occurred. The event is called `onDidChangeModelContent`. It is not possible to participate before the `undo`/`redo` actions execute, you can only observe their edits. So if a user types `a` at position (1,1), then the undo will show a deletion of range (1,1,1,2), etc.

**Comment by DineshKarri443** [comment]
@alexdima  To put things this way. I am showing custom glyph markers, I am able to move the markers on the line numbers when a user clicks on Enter, Remove or Delete. But when a user clicks on "Undo"/"Redo" I am not able to get hold of the linenumbers that were inserted or deleted. 

Is there a way in which I can get hold of the range of linenumbers that were inserted/deleted when an undo/ redo action is performed. 

For example from the below screenshot you can observe that the highlighted range I deleted, once I undo, the undo event on "onDidChangeModelContent" is not giving me the line numbers that are being inserted back. So my expectation is 
On Undo --> I need to know the start linenumber/end line number of the word(s)/line(s) that were undone. 

![image](https://user-images.githubusercontent.com/68352790/92924276-4e862380-f456-11ea-8804-02ef3eedc202.png)


Example of Pasting :- 

On pasting I get the range of line numbers that the user pasted from the event onDidPaste and I can compute my logic as can be shown below.

   ```  
this.editor.onDidPaste(e => {
      const {startLineNumber, endLineNumber} = e.range;  
      const addedRangeOfLines = this.getRange(startLineNumber, endLineNumber);
      const indexOffset = 1;
      this.updateAllLineNumberAfter(startLineNumber, endLineNumber, addedRangeOfLines, indexOffset);
    }); 
```

**Comment by alexdima** [comment]
`onDidChangeModelContent` contains all the information of the edit that was applied to the editor. A change event consists always of a range (which can be collapsed) and of a text (which can be empty).

e.g.
* deleting `aaa` is represented as a replacement of a range of 3 characters with ''
* inserting `aaa` is represented as a replacement of a collapsed range with `aaa`

The event `onDidChangeModelContent` describes completely the change that happened to the text model. It is not necessary to use additional listeners, such as `onDidPaste` or others.

**Comment by DineshKarri443** [comment]
@alexdima sorry, I am a bit lost here. Suppose I delete 2 lines ( lines 3 and 4 per say ) and perform an "undo" action, I want to know that the lines being undone are startLineNumber : 3, endLineNumber: 4. Is there any way I can get the line numbers being done ?

**Comment by alexdima** [comment]
@DineshKarri443  I'm really sorry, but I cannot help you further. As I wrote above, all the information that describes how the model is changed (including when undoing) is contained in the change event. I am sorry that I am not explaining this well enough, but I don't understand what you're not understanding. I cannot offer more help than this, please consider asking your question on StackOverflow.
