### ISSUE TITLE
drag and drop ContentWidget?

### ISSUE THREAD

**Issue by TerryChan** [microsoft/monaco-editor#2067]
I added a content widget (IContentWidget) to monaco editor (the "hello world" green box in the image below), and I want to implement drag and drop the content widget, so that user can move the content widget with mouse (drag and drop). Does monaco editor support this? If not, do you know any other method to implement this? Thanks in advance. 
![image](https://user-images.githubusercontent.com/5396286/89317806-7a242a00-d6b0-11ea-90b5-2e46f555cea5.png)

**Comment by ry7791** [comment]
Go to monaco playground
[https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-mouse-events](url)

And copy & paste this code to the editor.onMouseMove function . this code will help you to move the content widget with mouse

> editor.onMouseMove(function (e) {
	//console.log(e.target.position.lineNumber)
     var contentWidget = {
	domNode: null,
	getId: function() {
		return 'my.content.widget';
	},
	getDomNode: function() {
		if (!this.domNode) {
			this.domNode = document.createElement('div');
			this.domNode.innerHTML = 'My content widget';
			this.domNode.style.background = 'grey';
		}
		return this.domNode;
	},
	getPosition: function() {
		return {
			position: {
				lineNumber: e.target.position.lineNumber,
				column: e.target.position.column
			},
			preference: [monaco.editor.ContentWidgetPositionPreference.ABOVE, monaco.editor.ContentWidgetPositionPreference.BELOW]
		};
	}
};
    editor.layoutContentWidget(contentWidget)
});
