### ISSUE TITLE
Regression: CompletionItem ranges can no longer overwrite previous text

### ISSUE THREAD

**Issue by JacobEvelyn** [microsoft/monaco-editor#2070]
**monaco-editor version:** 0.20.0
**Browser:** Safari
**OS:** macOS
**Playground code that reproduces the issue:**

```js
monaco.languages.register({ id: "testlang" });

monaco.languages.registerCompletionItemProvider("testlang", {
    triggerCharacters: ["+"],
    provideCompletionItems: function(model, position) {
        var word = model.getWordUntilPosition(position);
        var range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,// - 1, // UNCOMMENT THIS AND IT BREAKS
            endColumn: word.endColumn
        };
        return {
            suggestions: [
                {
                    label: "test1",
                    insertText: "test1",
                    range: range
                },
                {
                    label: "test2",
                    insertText: "test2",
                    range: range
                }
            ]
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    language: "testlang"
});
```

I encountered this regression when updating my website from using a much older version of Monaco (0.14.6) to the latest release (0.20.0). The above playground snippet works fine if you type `+` and then choose a completion item to insert. However, if you change the range's `startColumn` to `word.startColumn - 1`, suggestions no longer appear (but no errors are in the console). It's important for my app that completions can replace earlier text (including the trigger characters), and this code used to work fine.

I'm aware that the API does describe [`additionalTextEdits`](https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L5321) that can be used in completions, which I could try using to replicate the previous behavior, but I don't see a good reason why the new behavior should be the way it is so I assume fixing this is preferable.

EDIT:

1. It appears that using `additionalTextEdits` does work as a workaround.
2. I just noticed that #1889 is describing the same issue.
3. As suggested in #1889 I did try to reproduce this in `vscode` as an extension (I modified the `completions-sample` in https://github.com/microsoft/vscode-extension-samples) but was unable to, making me think this is either already fixed in upstream `vscode` or is a Monaco-specific problem.

**Comment by DineshKarri443** [comment]
@JacobEvelyn  Could you please let me know how using additionalTextEdits helped resolve this? Any sample monaco-editor code would be really helpful.

**Comment by alexdima** [comment]
It looks like [this piece of code](https://github.com/microsoft/vscode/blob/40ebb1a8530fdf976b3dd204fef5698c5ac9f7ed/src/vs/editor/contrib/suggest/suggest.ts#L76-L102) probably marks your completion items invalid and then they are removed from the suggestions. Unfortunately I lack the understanding to say if this was changed recently or what is the intent there.

**Comment by jrieken** [comment]
Not actionable/stale -> closing
