### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by KamranAsif** [microsoft/monaco-editor#2074]
The last version was created in February. There are some fixes in `vscode` that I'd like to be able to use.

The https://github.com/microsoft/monaco-editor/blob/master/CONTRIBUTING.md documentation has instructions for updating, but I don't believe I have access to publish via npm.

**Comment by bodinsamuel** [comment]
+1 on this 🙏

**Comment by paranoidjk** [comment]
+1 on this 🙏

the automaticLayout bug is very annoying 😢 
https://github.com/microsoft/monaco-editor/issues/1916
https://github.com/microsoft/monaco-editor/issues/2057

**Comment by paranoidjk** [comment]
cc/ @alexdima is there any plan for 0.21.0 ?

**Comment by stefandobre** [comment]
I'd also like to know if bringing `vscode-oniguruma` to monaco is on the roadmap.

**Comment by pusztaienike** [comment]
+1

**Comment by huszerlbence** [comment]
+1

**Comment by martin-ericsson** [comment]
+1

**Comment by rcjsuen** [comment]
For everyone on this ticket, the latest official word we have regarding this is https://github.com/microsoft/monaco-editor/issues/1946#issuecomment-681816909.

**Comment by oldrich-s** [comment]
Anyone knows what version of monaco the typescript website playground uses? They have ts 4.0.2.

**Comment by stefandobre** [comment]
Seems an update is in the works: https://github.com/microsoft/monaco-editor/milestone/25

**Comment by alexdima** [comment]
`0.21.0` is now available.

**Comment by bodinsamuel** [comment]
Amazing, thanks a lot for this ❤️
