### ISSUE TITLE
Chrome latest version -  registerCompletionItemProvider is not working for yaml 

### ISSUE THREAD

**Issue by AloneFire** [microsoft/monaco-editor#2077]
**monaco-editor version:** 0.20.0
**Browser:** Chrome 84.0.4147.125 or Firefox 79.0 
**OS:** Windows 10 
**Playground code that reproduces the issue:**

```js
monaco.languages.registerCompletionItemProvider('yaml', {
                provideCompletionItems: () => {
                    return {
                        suggestions: [
                            {
                                label: 'Async Block',
                                kind: monaco.languages.CompletionItemKind.Snippet,
                                documentation: 'Add an async block',
                                insertText: [
                                    '(async () => {',
                                    '\t',
                                    '})()'].join('\n')
                            }
                        ]
                    }
                }
            })

monaco.editor.create(document.getElementById("container"), {
    value: "",
    language: "yaml"
});
```

**Comment by pankajk07** [comment]
@AloneFire You need to add trigger characters to let monaco when to suggest options. Try adding `triggerCharacters:[' ', ':'],` to the code.

**Comment by zhaofinger** [comment]
Same question!
Open [Playground completion-provider-example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) , replace 'json' to 'yaml', not work.

json 👍
![image](https://user-images.githubusercontent.com/31442077/102196256-9d7ea180-3efa-11eb-80d4-d86baae47412.png)

yaml 👎
![image](https://user-images.githubusercontent.com/31442077/102196210-8a6bd180-3efa-11eb-96f4-a77d8e77b7f0.png)


OS: macOS Big Sur
Browser: 87.0.4280.88 (x86_64)

**Comment by joebnb** [comment]
same with me,could investigate this

**Comment by alexdima** [comment]
This works fine for me:

* open https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
* change `json` to `yaml` in the provider registration
* change `json` to `yaml` in the editor language

![image](https://user-images.githubusercontent.com/5047891/103306627-4d313480-4a0e-11eb-85f6-c6ba4d0fa3ac.png)

**Comment by zhaofinger** [comment]
This is the video of my operation.

https://user-images.githubusercontent.com/31442077/105931586-6b7a6680-6086-11eb-8469-3d91d3b67856.mov

**Comment by alexdima** [comment]
Let's continue in https://github.com/microsoft/monaco-editor/issues/2273#issuecomment-768229942 where I now understand what the problem is. Sorry about my lack of understanding, I am not a big user of the auto-intellisense popup, I always press Ctrl+Space when I want to see Intellisense.
