### ISSUE TITLE
Shortcut command with 'Tab' key 

### ISSUE THREAD

**Issue by mittalalok** [microsoft/monaco-editor#2079]
**monaco-editor version:** 0.20.0
**Browser: Chrom
**OS: MacOs
**Playground code that reproduces the issue:**

```js
```
Hi,
We have added some shortcut command with 'Tab' key like below:

editor.addCommand(monaco.KeyCode.Tab, someFunction);

But when we are doing the 'Toggle Tab Key Moves Focus' and pressing 'Tab' the editor is not taking focus to the next focusable element. It just adds the tab in the text.

if there anyways we can add shortcut command with 'Tab' key, which works only when 'Tab Key Moves Focus' is disabled.

Thanks,
Alok Mittal

**Comment by mittalalok** [comment]
the same issue can be seen in the Monaco example. 

https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance

if you do 'Toggle Tab Key Moves Focus' and then 'tab' the custom command will be called and it will not move the focus to the next element.

**Comment by alexdima** [comment]
the command works with our builtin tab handler. You would need to define a context with your command. You can use `!editorTabMovesFocus` i.e. `editor.addCommand(monaco.KeyCode.Tab, someFunction, '!editorTabMovesFocus');`
