### ISSUE TITLE
Force refresh of IntelliSense markings after adding/disposing "addExtraLibs"

### ISSUE THREAD

**Issue by Zlatkovsky** [Microsoft/monaco-editor#208]
Suppose I have a running Monaco editor.  On some external event (button press, etc.), I want to refresh the default libraries that I reference

```
monaco.languages.typescript.typescriptDefaults.addExtraLib(response.data, response.url);
```

Likewise, I may want to dispose of existing previously-added libraries, only adding the new libs.

Right now, when I dispose any s, the Editor does not get immediately updated.  For example, if I had object XYZ defined already, then dispose and add new libraries, the code editor makes the XYZ object look as "any" on mouse-over, but nothing else.  Only on touching the editor (e.g.: adding a new line) does the IntelliSense re-scan get triggered, and now I see the new squiggle lines.

I tried calling `this._monacoEditor.render();` after adding the libraries, but it doesn't seem to make any difference.

monaco-editor npm version: 0.6.1
Browser:  Chrome
OS:  Windows

**Comment by alexandrudima** [comment]
Perhaps the `DiagnostcsAdapter` should loop over all models again in case of options changed.

**Comment by jrieken** [comment]
We now dispose and recompute all diagnostics on change of any of the default options
