### ISSUE TITLE
Find references dialog shows without preview when automaticLayout: true

### ISSUE THREAD

**Issue by lsim** [microsoft/monaco-editor#2082]
#### Reproduce
On an instance of monaco with the `automaticLayout` setting set to true:

1. Move cursor to `foo` in the code snippet
2. Press Shift + F12

Expected: Find references popup should display a preview of the selected reference
Actual: The preview area of the popup is blank

#### Observations
If you press Shift + F12 again, the popup will move to another reference and will now show the preview correctly.

I can simulate the setting and trigger the bug at https://microsoft.github.io/monaco-editor/ by setting a breakpoint in dev tools at [this line](https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/editor/browser/config/configuration.ts#L344) and manually executing the line from inside the conditional: ```this._elementSizeObserver.startObserving();```

Note that this appears to be a regression since 0.19.3 where this bug is not seen.

**monaco-editor version:** 0.20.0
**Browser:** Chrome 84
**OS:** OSX 10.15.3
**Playground code that reproduces the issue:**
```js
var foo = 1;
foo;
```

**Comment by alexdima** [comment]
This has been fixed on `master`, probably via https://github.com/microsoft/vscode/pull/93630
