### ISSUE TITLE
TypeScript 3.9 (or top level await)

### ISSUE THREAD

**Issue by samdoeswork** [microsoft/monaco-editor#2083]
Hi,
It would be excellent to upgrade TypeScript to a version which allows top-level await.
This is a major feature, and it would be great to reflect that in the editor.

Thanks in advance. :)

**Comment by samdoeswork** [comment]
Hi Alex, thank you for closing this issue! Is this something we can access already by updating npm version? HUGE thanks for the work on Monaco it's amazing

**Comment by alexdima** [comment]
We plan to make a new editor release soon (0.21.x).

**Comment by samdoeswork** [comment]
Great. I've subscribed to be notified. Thank you

**Comment by samdoeswork** [comment]
Hi Alexandru,
I updated Monaco to 0.21.2 and still see “ ‘await’ expression is only allowed within an async function”.
Is there a setting I need to change in addition to updating to 0.21.2 ?

Thank you in advance,
Sam

[cid:image001.png@01D6974C.CE972950]<http://www.instant.marketing/>
MAJOR UPDATES: Watch this 6 minute video for EVERY update we announced at our Instant Innovation event.
Watch the recap summary video<https://www.linkedin.com/posts/samsmithmarketer_eloqua-instantmarketing-ugcPost-6693133987138805760-0JmT>
Please note: Just Add Features is now Instant Marketing ⚡
www.instant.marketing<http://www.instant.marketing/>

**Comment by spahnke** [comment]
I get these error messages in the playground with the code `await Promise.resolve(1);`
![image](https://user-images.githubusercontent.com/25029871/94726005-eba0f180-035c-11eb-975c-d10333ee320f.png)
Following the directions in the error messages, this code works:
```js
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
    noSyntaxValidation: false,
    noSemanticValidation: false
});

monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ESNext,
    module: monaco.languages.typescript.ModuleKind.ESNext,
    allowNonTsExtensions: true
});

monaco.editor.create(document.getElementById('container'), {
    value: `await Promise.resolve(1);

export {}`,
    language: 'javascript'
});
```
