### ISSUE TITLE
monaco-editor registerCompletionItemProvider creating duplicate values of my suggestions

### ISSUE THREAD

**Issue by pk091990** [microsoft/monaco-editor#2084]
monaco-editor version : 0.14.3 with SPFX 1.11
Using monaco editor I'm displaying all suggestions on a Panel  which is opening on button click. So suggestions showing duplicate items depends on how many times I'm opening that panel. For ex. if I'm opening panel 4 times then it will show same value four times and it shows correct value as soon I'm refreshing my page and open the panel again.

Calling **Monaco.languages.registerCompletionItemProvide**r on button click inside setState only and also disposing editor object on close panel and componentWillUnmount function

![image](https://user-images.githubusercontent.com/46436213/90649088-ecbc0a80-e257-11ea-89a9-7cfa9ef7b727.png)

I've tried with latest monaco-editor@0.20.0 also but it was throwing below errors, so could not proceed. Please let me know what i'm missing here.
![image](https://user-images.githubusercontent.com/46436213/90649270-2a209800-e258-11ea-82a9-473cedf89413.png)

**Comment by alexdima** [comment]
It looks like you have a problem with your project set up, I cannot say from the given information what the problem is.

**Comment by pd1246** [comment]
I have a similar situation where when I repeatedly enter the component, my custom prompt is displayed repeatedly, and when I enter it several times, the prompt is repeated several times.

When I enter the component twice.
![01](https://user-images.githubusercontent.com/52770443/93155773-67822380-f739-11ea-9272-fbeaa76776a9.png)
When I enter the component three times.
![02](https://user-images.githubusercontent.com/52770443/93155789-77016c80-f739-11ea-9153-f81449240ac5.png)

**Comment by spahnke** [comment]
That's because registering a completion item provider, or any kind of language provider, is global state which gets not disposed if you only dispose the editor instance. Consider a page where you have multiple editors. If you dispose one of them you don't want to lose your completion provider for the other one. You have two options
1. Either also dispose your completion provider (the `registerCompletionItemProvider` method returns a `Disposable`), or
1. make sure to only register your completion provider once.

For the latter one I found the `monaco.languages.onLanguage` event helpful which gets fired once when a language (e.g. `javascript`) is loaded for the first time.

Here is a playground example showcasing your problem. Your component registers the completion provider every time it creates an editor, but only disposes the editor on unmount. This then leads to duplicate entries
![grafik](https://user-images.githubusercontent.com/25029871/93180502-8a133d00-f737-11ea-9059-f0a4459ed0d2.png)

```js
function createDependencyProposals(range) {
    // returning a static list of proposals, not even looking at the prefix (filtering is done by the Monaco editor),
    // here you could do a server side lookup
    return [
        {
            label: '"lodash"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "The Lodash library exported as Node.js modules.",
            insertText: '"lodash": "*"',
            range: range
        },
        {
            label: '"express"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Fast, unopinionated, minimalist web framework",
            insertText: '"express": "*"',
            range: range
        },
        {
            label: '"mkdirp"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Recursively mkdir, like <code>mkdir -p</code>",
            insertText: '"mkdirp": "*"',
            range: range
        },
        {
            label: '"my-third-party-library"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Describe your library here",
            insertText: '"${1:my-third-party-library}": "${2:1.2.3}"',
            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
            range: range
        }
    ];
}

// mount
monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        // find out if we are completing a property in the 'dependencies' object.
        var textUntilPosition = model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        var match = textUntilPosition.match(/"dependencies"\s*:\s*\{\s*("[^"]*"\s*:\s*"[^"]*"\s*,\s*)*([^"]*)?$/);
        if (!match) {
            return { suggestions: [] };
        }
        var word = model.getWordUntilPosition(position);
        var range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn
        };
        return {
            suggestions: createDependencyProposals(range)
        };
    }
});

const editor = monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json"
});

// unmount
editor.dispose();

// mount again
monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        // find out if we are completing a property in the 'dependencies' object.
        var textUntilPosition = model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        var match = textUntilPosition.match(/"dependencies"\s*:\s*\{\s*("[^"]*"\s*:\s*"[^"]*"\s*,\s*)*([^"]*)?$/);
        if (!match) {
            return { suggestions: [] };
        }
        var word = model.getWordUntilPosition(position);
        var range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn
        };
        return {
            suggestions: createDependencyProposals(range)
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json"
});

```

**Comment by pd1246** [comment]
@spahnke  Sorry, I don't quite understand what you mean. What should I do to solve this problem?thank you.

**Comment by spahnke** [comment]
Again, you have two options
1. Dispose your completion provider (the `registerCompletionItemProvider` method returns a `Disposable`) every time you dispose your editor, or
2. make sure to only call `registerCompletionItemProvider` once in your application and not every time you create an editor.

The second option probably is the preferred one. Sorry, but I can't help you more than that because I a) don't know your project setup/application and b) only have a limited amount of time in my day to comment on issues like these.

**Comment by pd1246** [comment]
Thank you for your help, I see what you mean,Thank you.

**Comment by pd1246** [comment]
@spahnke  I tried to make the call only once, but the editor I created later could not modify the data in the custom prompt. By default, it was the data I passed in the first call, which was a headache.
   Do you know what method can destroy my registration (registerCompletionItemProvider).

**Comment by alexdima** [comment]
@pd1246 `registerCompletionItemProvider` returns an `IDisposable` object, which has a method called `.dispose()`. You need to call that in order to remove the completion provider.

**Comment by pd1246** [comment]
@alexdima  
Thank you. I ignored it earlier.
 Problem solved.
