### ISSUE TITLE
R syntax highlighting with `roxygen` comments

### ISSUE THREAD

**Issue by stla** [microsoft/monaco-editor#2086]
Hello,

 Thank you for this amazing library.

I encountered an issue with the R syntax highlighting when there are `roxygen` comments (lines which tart with `#'`).

**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById("container"), {
	value: [
        "#' Title",
        "#'",
        "#' @importFrom shiny tags",
        "#' @export",
        "myfunction <- function(x){",
        "  return(x+1)",
        "}"
    ].join("\n"),
	language: "r"
});
```

Here is the output:

![monacoRissue](https://user-images.githubusercontent.com/4466543/90764652-e7f36700-e2e8-11ea-931c-a9406ad663df.png)

The `@importFrom` should be highlighted like the `@export`. Inserting a white space at the previous line yields the correct highlighting:

```js
	value: [
        "#' Title",
        "#' ", // white space here
        "#' @importFrom shiny tags",
        "#' @export",
        "myfunction <- function(x){",
        "  return(x+1)",
        "}"
    ].join("\n")
```

Moreover, the first line of code `myfunction <- function(x){` should not be green, this is not a comment. Adding a white space at the end of the previous line yields the correct highlighting:

```js
	value: [
        "#' Title",
        "#' ",
        "#' @importFrom shiny tags",
        "#' @export ", // white space here
        "myfunction <- function(x){",
        "  return(x+1)",
        "}"
    ].join("\n")
```

So it is possible to get the correct highlighting by adding white spaces, but I think this is not an expected behavior.

**Comment by hediet** [comment]
Fixed by #148.
