### ISSUE TITLE
Official Web Component

### ISSUE THREAD

**Issue by max-pub** [microsoft/monaco-editor#2088]
Are there any plans to release monaco-editor as a WebComponent?

Maybe along the lines of https://github.com/vanillawc/wc-monaco-editor, but up-to-date with every release.

Style options could be adjustable via CSS-variables, other options via element-attributes.

All languages, themes and features (like miniMap) could be loaded on-demand only.

```html
<script type="module" src="https://github.com/microsoft/monaco-editor/monaco-editor.js"></script>

<monaco-editor language="typescript" theme="vs-dark" mini-map="true">
	class Demo {
		hello(name: String) {
			console.log(`Hi ${name}`)
		}
	}
</monaco-editor>

<style>
	monaco-editor {
		--font-size: 14px;
		--tab-size: 4;
	}
</style>
```

**Comment by hediet** [comment]
We have a demo here:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAIFBAAAAAAAAABBqQkHQ5NjdYzqEXhNewrSKZslyM_G2I4bTkHQYW1lB1MplPA6z0speGDFvgRIQQx0HI9zdEFZdk3ipJqwzu6RT44vPXZPcpCKxnvgE9TYAtuAi9VQr3EAhbQJCn4JPD8EaFYCtRcYWa8_pnHjN-uDjxrhmN3g8tmx0iWUz1zF7VMROnGNjfHj2TFmcBooqFj0KG-T22ZTMhTuebWAKwtN_PzaTmIn83sxr9iG_rCToVGZ0s8Aqq4FCtsWBjMFVvarCcsgdWatYDG40I2zD8RTtWuNHNnY7c7IoNZIQlbLuUY6eiWdTFPiXUP1O8oaah0Csz8RlRcIa1l9lhCgWLmDqqOL08Y3F0K8dVIo69eyZtcffV2oBXpdc3VTcdsCp1Y898LUMwBEQMRkIvbz7CBuaqOSacXtrQdqhAqjekP8a0fHRClj00Ayniiid1DDyNpyEfu6SGdPfBH6LkLC5i7FXsHHUvO1GnCc1irro7YZl39IXXoeMqNUFgbEUptiN43oiqtTzYUtpRD_hLxuaVJ3UBWtHaMFjPD1kiQWekYju4V_l4LrUn6-kyOw7QUwiPlt7ljIjAAdnoanwDrlkEMdEUK0bYRb7stBpL36u_IfrqKwRX66TqjGZFKZjd4wpg9wQ_V08GvGVO_sZ-vV8jiQVjqz6p76A1HXqKVruW_iDZcR4kOjwCipGlD-wPPGPsb6tkJb7u1HivuQXwLwrFXSnGNcWqPpEkEj4QmkPJ7Q9vEEgKJzRf_uUJ3h

However, we don't plan at the moment to ship a web component version of the monaco editor.
