### ISSUE TITLE
Duplicate definition warnings: vscode-languageserver-types

### ISSUE THREAD

**Issue by isidorn** [Microsoft/monaco-editor#209]
monaco-editor npm version: latest
Browser: chrome
OS: OS X El Capitan

Refs: https://github.com/Microsoft/vscode/issues/12691
1. Open `monaco-editor/test/index.html`
2. Open developer tools -> notice duplicate definition warnings

![screen shot 2016-09-27 at 09 45 30](https://cloud.githubusercontent.com/assets/1926584/18864629/86b16a0e-8497-11e6-8ca6-b332f516e9bd.png)

**Comment by alexlur** [comment]
I can reproduce this issue with 0.7.0.
