### ISSUE TITLE
Cannot set minimap background

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/monaco-editor#2090]
**monaco-editor version:** 0.20.0
**Browser:** any browser (tested with FF, Chrome + Safari)
**OS:** macOS
**Playground code that reproduces the issue:**

Go to the playground page: https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-exposed-colors.

Change the theme definition code to:

```js
monaco.editor.defineTheme('myTheme', {
    base: 'vs',
    inherit: true,
    rules: [{ background: 'EDF9FA' }],
    colors: {
        'editor.foreground': '#000000',
        'editor.background': '#EDF9FA',
        'editorCursor.foreground': '#8B0000',
        'editor.lineHighlightBackground': '#0000FF20',
        'editorLineNumber.foreground': '#008800',
        'editor.selectionBackground': '#88000030',
        'editor.inactiveSelectionBackground': '#88000015',
        "minimap.background": "#FF0000",
        "minimap.selectionHighlight": "#00FF00",
    }
});
```

As you can see I added two minimap settings. The selection highlight works as expected, while the minimap background color does not change. The same setting works in vscode, so I assume something went wrong when extracting Monaco from there:

<img width="945" alt="minimap background" src="https://user-images.githubusercontent.com/2398704/91053864-c1ed0000-e623-11ea-80eb-b27da8a73395.png">

**Comment by mike-lischke** [comment]
I just found this patch from @alexdima https://github.com/microsoft/vscode/commit/3e500bb935ff3f5254a40aeca511ba0f71fd6b01, which adds support for this background to vscode. Inspecting the sources of Monaco shows that this has not been taken over, even though this patch was added 6 months ago.

**Comment by spahnke** [comment]
There hasn't been a new version since February (see #2074). So I guess you could try this again whenever a new version is released that includes that patch. I don't know about any workarounds in the meantime unfortunately, but I also never used the themeing support myself 😅

**Comment by alexdima** [comment]
Let's track via https://github.com/microsoft/monaco-editor/issues/2074
