### ISSUE TITLE
"Add period with double space" macos feature does not work

### ISSUE THREAD

**Issue by Amithab** [microsoft/monaco-editor#2093]
**monaco-editor version:** 0.20.0 (latest)
**Browser:** Chrome
**OS:** MacOS
**Playground code that reproduces the issue:**
At https://microsoft.github.io/monaco-editor/

Type two spaces quickly after the brace on line 8
Result: A dot should appear if mac's add dot after double space is turned on

This doesn't happen in firefox. Is it possible to remove this? so it's not dependent on user settings?

**Comment by Pranomvignesh** [comment]
**I'm also puzzled , how firefox is handling this. But when i disabled the text settings in mac, it seems to work fine**

I think it is not the issue of monaco editor, refer stackoverflow answer [here](https://stackoverflow.com/questions/51828157/monaco-editor-double-space-produces-a-period)

You can find the way to disable it [here](https://osxdaily.com/2019/03/27/disable-period-typing-shortcut-mac/)

**Comment by Pranomvignesh** [comment]
**I think firefox is handling textarea differently, refer w3schools example [here](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea)**

- Try opening the mentioned link in chrome and firefox 
- Remove the dot at the end of the paragraph and type double space 
- Chrome adds '.' but firefox doesn't

**As monaco editor also uses textarea, I guess this is not an issue of monaco editor**

**Comment by Amithab** [comment]
I checked with codemirror (https://codemirror.net/), and it doesn't have the same issue. Do you know if they also use textarea?

**Comment by Pranomvignesh** [comment]
Code Mirror seems to process all the text which we enter and convert it to `span` tags inside `pre` tags
Unlike monaco, they are not using textarea , thats why you were not able to see the period after double space
<img width="1525" alt="CodeMirrorScreenShot" src="https://user-images.githubusercontent.com/29809906/91629177-510f6480-e9e4-11ea-8480-e78cea8017f3.png">

**Comment by Amithab** [comment]
I see. Ace editor seems to have the same textarea problem. I think this can be a common issue when editing code. The real question is if there's a workaround I could add into monaco?

**Comment by Pranomvignesh** [comment]
> The real question is if there's a workaround I could add into monaco?

I think @alexdima will be the right person to anwer this

**Comment by alexdima** [comment]
This might be because we only "render" the last word in the input textarea. This feature relies on the input textarea having the previously typed space and the previous word.

You can run the editor with the option `accessibilitySupport: "on"`, i.e. at https://microsoft.github.io/monaco-editor/playground.html:
```
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
	accessibilitySupport: "on"
});
```

This will make it such that we will write more text in the input textarea and macos will trigger the replacement of the first space with a dot:

![Kapture 2020-09-17 at 18 04 44](https://user-images.githubusercontent.com/5047891/93497063-4aec1400-f910-11ea-9514-1bf1c6b47f12.gif)

**Comment by hediet** [comment]
Closing since there exists a workaround and we deliberately only render the last word in the input textarea.
