### ISSUE TITLE
Select and Scroll in Iframe

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2096]
I'm using 
**Monaco Editor version** : 0.20.0
**OS** : Mac OS 
**Browser** : Chrome 

I am using monaco editor inside **iframe** without src attribute , And i made the monaco editor **cover the complete width and height of the iframe**.Now when i tried to select and **scroll beyond the editable area** of the monaco editor, it is not selecting continuously

`This feature works fine, when the monaco editor is added inside iframe with src attribute`

I dont know why the src attribute of iframe matters much ... Without another html file , As i am going to add only one div to the iframe i used to manipulate the iframe's document using contentDocument itself, but this seems to have side effects like this. Can anyone explain, why it is happening like this

**Comment by alexdima** [comment]
Do you perhaps have a simple repro? We have some special code to handle the mouse coordinates transformation when the editor is embedded in an iframe and that code might not be prepared to work with `data:` URI iframes.

**Comment by Pranomvignesh** [comment]
I have edited the Monaco-editor-samples repository to mock the behavior 
You can see the repository file changes [here](https://github.com/Pranomvignesh/monaco-editor-samples/commit/010f9495c058c26741d2d248c928efedccd80ddd)

Changed File : **monaco-editor-samples/browser-amd-iframe/index.html**
```javascript 
var myIframe4 = document.getElementById('myIframe4');
myIframe4.onload = function () {
  const longText = `function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}function x() {\n\tconsole.log("Hello world!");\n}function x()
  {\n\tconsole.log("Hello world!");\n}`;
  const iframeDoc = myIframe4.contentDocument;
  const iframeWin = myIframe4.contentWindow;
  const injectSourceFiles = function () {
    iframeWin.require.config({
      paths: {
        vs: '../node_modules/monaco-editor/min/vs'
      }
    });

    iframeWin.require(['vs/editor/editor.main'], function () {
      const container = iframeDoc.createElement('div');
      container.setAttribute('id', 'container');
      container.style.height = '100vh';
      iframeDoc.body.appendChild(container);
      var editor = iframeWin.monaco.editor.create(
        iframeDoc.getElementById('container'),
        {
          value: longText,
          language: 'javascript'
        }
      );

      iframeWin.onresize = function () {
        editor.layout();
      };
    });
  };
  const script = iframeDoc.createElement('script');
  script.src = '../node_modules/monaco-editor/min/vs/loader.js';
  script.onload = injectSourceFiles;
  iframeDoc.head.appendChild(script);
};
```


![final_5f23cd88c866030015a0d1e7_416602](https://user-images.githubusercontent.com/29809906/92954765-a1c19b80-f481-11ea-8137-8533746af904.gif)

#### I gave a `dummy file path (like src='sample.html') where sample.html doesn't exists.` For this case, the scroll seems to work properly
#### I'm curious to know why select and scroll is not working for the iframe which is not having an src tag

**Comment by Pranomvignesh** [comment]
Thanks @alexdima
