### ISSUE TITLE
JSON Schema Relative Imports Broken

### ISSUE THREAD

**Issue by wmain** [microsoft/monaco-editor#2097]
**monaco-editor version:** >=0.19.0
**Browser:** Any
**OS:** Any
**MRE Repository:** https://github.com/wmain/monaco-bug

Version `0.19.0` introduces a change that breaks JSON schema's ability to utilize relative imports for `$ref` properties. This is an important use case for anyone who serves their client code from different environments/hosts. After some digging I believe I've traced the issue to `vscode-uri`, specifically in the migration/change referenced [here](https://github.com/microsoft/vscode-uri/blame/master/src/index.ts#L492), as defaulting to the `file` protocol will throw CORS errors.

**Comment by aeschli** [comment]
@wmain Can you share a small code sample that contains the schema similar to this: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults ?

**Comment by wmain** [comment]
@aeschli I'm not sure I follow. The provided repository has a full code sample and schema in it.

**Comment by aeschli** [comment]
Thanks, now I see.

I pushed a fix. This kind of worked by coincidence before. Now we properly resolve the relative ref to the URI of the schema. So in your example we will try to fetch `http://myserver/relative.json` as that the schema has URI `http://myserver/foo-schema.json`

**Comment by wmain** [comment]
Thanks for the fix!
