### ISSUE TITLE
Any way to have access to under manager ?

### ISSUE THREAD

**Issue by npenin** [Microsoft/monaco-editor#21]
Dear team,

I am in the process of replacing ace editor with monaco, but there are some features which I don't know how to translate them.

Could you please tell me how to access the undo manager or whatever name it is in monaco ?

The purpose would be to know where I am in the stack so that at which point of the undo stack the file was saved.

Thanks,
Nicolas

**Comment by alexandrudima** [comment]
in vscode, we manage to get it done with `IModel.getAlternativeVersionId()`:

```typescript
        /**
         * Get the current version id of the model.
         * Anytime a change happens to the model (even undo/redo),
         * the version id is incremented.
         */
        getVersionId(): number;
        /**
         * Get the alternative version id of the model.
         * This alternative version id is not always incremented,
         * it will return the same values in the case of undo-redo.
         */
        getAlternativeVersionId(): number;
```

**Comment by npenin** [comment]
Perfect, thanks !
