### ISSUE TITLE
Could not create web workers warning

### ISSUE THREAD

**Issue by isidorn** [Microsoft/monaco-editor#210]
monaco-editor npm version: latest
Browser: chrome
OS: OS X El Capitan

Refs: https://github.com/Microsoft/vscode/issues/12691

1. Open `monaco-editor/test/index.html`
2. Open developer tools -> notice can not create worker warnings
3. Not sure if this is expected?

![screen shot 2016-09-27 at 09 49 46](https://cloud.githubusercontent.com/assets/1926584/18864717/d57289ca-8497-11e6-9172-728ed312371b.png)

**Comment by alexandrudima** [comment]
Yeah, it is expected when web workers are misconfigured or cannot start, such as when running from the file protocol
