### ISSUE TITLE
 Indentation settings of the editor are not applied when the HTML content is formatted.

### ISSUE THREAD

**Issue by pankajk07** [microsoft/monaco-editor#2101]
**Steps to reproduce**

1.  Go to the playground 
2. Add the code snippet provided below
3. Right-click and select Format option from the context menu
4. The content will be formatted with `tab` as the indent type.

**What was expected**

Since in the options `insertSpaces` is set to true, the content should have been formatted with indent type as `spaces`.

The issue seems to be in `monaco-html`. https://github.com/microsoft/monaco-html/blob/master/src/htmlWorker.ts#L42
Instead of taking passed in options, the global options are taken into consideration to format the content. 
 
![image](https://user-images.githubusercontent.com/44100113/92264779-66acee80-eefc-11ea-85b9-c1b2821c831d.png)

**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** macOS
**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById("container"), {
	value: "<html><head></head><body><div><div><div></div></div></div></body></html>",
	language: "html",
    insertSpaces: true,
    tabSize: 2,
    renderWhitespace: true,
});
```

**Comment by pankajk07** [comment]
@alexdima Let me know if you guys are willing to accept a PR for this.

**Comment by aeschli** [comment]
@pankajk07 Thanks for looking into this, PR is welcome!

**Comment by pankajk07** [comment]
@aeschli https://github.com/microsoft/monaco-html/pull/12
