### ISSUE TITLE
"Module not found" building Vue package with Monaco Editor

### ISSUE THREAD

**Issue by kerbal** [microsoft/monaco-editor#2104]
Hi guys

I need your help!

I'm trying to create a new language and language service with Monaco Editor. I want to make an Vue editor component that contains language service of my language (autocomplete, jump to definition, etc) as an npm package (host on my private Github repo). But when I install my editor component package on my project, error happens:

```
Failed to compile with 64 errors 

These relative modules were not found:

* ./abap.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./apex.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./azcli.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./bat.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./cameligo.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./clojure.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./coffee.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./cpp.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./csharp.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
* ./csp.js in ./node_modules/@holistics/aml-editor/dist/aml-editor.common.js
...
```
![image](https://user-images.githubusercontent.com/33062751/92297534-8e3aa000-ef6a-11ea-8619-6a69e75bf1c4.png)

I check the common.js file, there are many lines of code trying to import language file, which doesn't appear in the `dist` folder.
![image](https://user-images.githubusercontent.com/33062751/92297711-55032f80-ef6c-11ea-8cd3-f5461299862e.png)
![image](https://user-images.githubusercontent.com/33062751/92297785-04400680-ef6d-11ea-85ef-740943129df0.png)

How to fix that error? Please help me! Thank you so much. Nice weekend. :D

I imported monaco editor from `'monaco-editor/esm/vs/editor/editor.api'`

My `vue.config.js`:
```javascript
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = {
  productionSourceMap: false,
  configureWebpack: {
    plugins: [
      new MonacoWebpackPlugin({
        languages: [],
      }),
    ],
  },
};


```

**monaco-editor version:** 0.20.0

```js
```

**Comment by khanh-tran-quoc** [comment]
Prolem solved
