### ISSUE TITLE
Specify icon/variable type in json schema

### ISSUE THREAD

**Issue by LoneDev6** [microsoft/monaco-editor#2105]
Would be really helpful to be able to specify the type of variable in custom json schemas.
This would allow anyone to show different icon for each property of the json schema to help the end user recognizing the functionality of each property.

Right now we cannot change the icon nor specify the variable type, right?
Check this screenshot:
![image](https://user-images.githubusercontent.com/27242001/92314879-2faf0980-efde-11ea-8d21-c8967b37026f.png)

Thanks!

**Comment by LoneDev6** [comment]
I manually edited the json schema logic adding a new attribute "kind" to force the entry to get a different icon.

**Comment by rcjsuen** [comment]
@LoneDev6 What line of code and file did you change?

**Comment by LoneDev6** [comment]
"node_modules\monaco-yaml\lib\esm\_deps\yaml-language-server\out\server\src\languageservice\services\yamlCompletion.js"

around line 220 I added this, so now I can add a "kind" attribute to my schema and specify the icon value I want (type).

```
kind: propertySchema.kind ? propertySchema.kind : this.getSuggestionKind(propertySchema.type),
```

**Comment by rcjsuen** [comment]
@LoneDev6 Thank you for sharing your solution!
