### ISSUE TITLE
Conditional json schema attributes

### ISSUE THREAD

**Issue by LoneDev6** [microsoft/monaco-editor#2107]
Would be nice to get support for this json schema feature: https://json-schema.org/understanding-json-schema/reference/conditionals.html?highlight=options#applying-subschemas-conditionally

**Comment by aeschli** [comment]
We already have support for `if then else`. We probably need to update the version of the json-languageservice.

**Comment by LoneDev6** [comment]
Let me know how it goes, it's a really cool feature which would make the editor even more advanced.

Thanks a lot

**Comment by aeschli** [comment]
Available in the meantime
