### ISSUE TITLE
Can't scroll to the right position when selecting text outside editor under brower scrollbar(with overflow: hidden)

### ISSUE THREAD

**Issue by cqby** [microsoft/monaco-editor#2108]
**monaco-editor version:** 0.20.0
**Browser:** chrome
**OS:** win 10
**Playground code that reproduces the issue:**

```js
const ed = monaco.editor.create(document.getElementById("container"), {
    value: "alert('Hello world!');\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nconsoloe.log('cant scroll to select line')",
    language: "javascript",
    scrollbar: {
        vertical: 'auto',
        handleMouseWheel: true,
        alwaysConsumeMouseWheel: false,
    },
    scrollBeyondLastLine: false,
});

ed.layout({
    height: 1000,
    width: 500
})
```

Try to select lines and move mouse outside the editor contiainer.
Presumably, the viewport shloud scroll up/down and select&focus lines which were originally outside the viewport. But it is not.

The playground is using iframe, which may have more issues to concern. 
You can also reproduce with a plain html:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Parcel Sandbox</title>
    <meta charset="UTF-8" />
  </head>

  <style>
    body {
      height: 100vh;
    }
  </style>
  <body>
    <div
      id="container"
      style="
        width: 800px;
        height: 400px;
        border: 1px solid grey;
        overflow: auto;
        margin: 20px;
      "
    ></div>
    <script src="https://unpkg.com/monaco-editor/min/vs/loader.js"></script>
    <script>
      require.config({
        paths: { vs: 'https://unpkg.com/monaco-editor/min/vs' },
      });
      require(['vs/editor/editor.main'], function () {
        const ed = monaco.editor.create(document.getElementById('container'), {
         // add some line to fill height
          value:
            "alert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\nalert('Hello world!');\n",
          language: 'javascript',
          scrollbar: {
            vertical: 'auto',
            handleMouseWheel: true,
            alwaysConsumeMouseWheel: false,
          },
          scrollBeyondLastLine: false,
        });

        ed.layout({
          height: 1000,
          width: 500,
        });
      });
    </script>
  </body>
</html>
```

**Comment by alexdima** [comment]
This is caused by the incorrect editor layout call:

![image](https://user-images.githubusercontent.com/5047891/93568893-1bc9b700-f991-11ea-8dee-5a058ad35392.png)

As you can see, the editor is made to be 1000px high, but the iframe around it is only about 250px high, so the editor gets clipped by the iframe. When selecting and dragging, the editor will not scroll because the end of its viewport is not reached with the mouse.

The solution is to never render an editor in a clipped iframe.

**Comment by cqby** [comment]
@alexdima Thank you for your reply. My question is, if you try my HTML code above, it's not just clipped iframe, clipped dom will also have such problem.

**Comment by alexdima** [comment]
Yes, but the editor is not meant to be hosted in a clipped way. You need to call `layout` every time you change the container of the editor such that the editor gets the size of its container or you can use the option `automaticLayout`.

**Comment by cqby** [comment]
It absolutely makes sense that the editor is not meant to be hosted in a clipped way. 

Just FYI, my team is building some programing educaiton product which need students fill in some part of the code. 

And since the readOnly lines feature was removed(#953 ), we have to use several editors together with some of them read only. Thus, we did the clipped way since we don't want too may scrollbars.

Selecting text is not a big issue, but for better user experience, I may try to fork or see if there is a hacking approach to do it. So, it will be very appreciated if you could offer me some hint/advice on the codebase.
