### ISSUE TITLE
Playground: Can't scroll left with Mac trackpad on Chrome

### ISSUE THREAD

**Issue by stowball** [microsoft/monaco-editor#211]
When the playground editors have horizontal scroll, you can't scroll left in Chrome on Mac as it triggers the back gesture.

**Expected behavior:**

When I 2-finger swipe to left, the editor should scroll.

**Actual behavior:** 

Back gesture is triggered

OS X 10.11.6
Chrome 52.0.2743.116 (64-bit)

**Comment by JKillian** [comment]
Users might be able to avoid this behavior by disabling this option in their trackpad settings:

![image](https://user-images.githubusercontent.com/1400151/28281148-2ae4a062-6af4-11e7-83f5-06cd58d0168c.png)

Nonetheless, it'd be great if monaco could fix this by default!

**Comment by Nikolsi** [comment]
Hello all,
I am developing a small playground with your amazing editor. I came up with this issue as well.
Safari works - Chrome does not!

I was trying to stop event propagation over the main container. However, it did not work :c
Is there any quick fix for that?

Mac OS X 10.13.6
Chrome Version 71.0.3578.98 (64-bit)
