### ISSUE TITLE
Add more kinds of underline colour

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2116]
I'm using Monaco Editor to make my own IDE. I use `provideHover` to underline certain kinds of code. It seems that different `DiagnosticCategory` or `MarkerSeverity` have impact to the colour of the underline. At the moment, it seems that there are only 4 kinds of underline colours.

```
enum DiagnosticCategory {
    Warning = 0,
    Error = 1,
    Suggestion = 2,
    Message = 3
}
````

Does anyone know how to add more kinds of underline colour?

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
