### ISSUE TITLE
Not show marker.message and marker.code in hover message

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2117]
I'm using Monaco Editor to make my own IDE. I use `provideHover` over certain kinds of code.

I realize that the hover window shows several texts. One kind of texts come from [contents](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.hover.html#contents); another kind of texts consist of `marker.message` and `marker.code` (https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imarker.html).

Does anyone know if it is possible to not show these the texts consisting of `marker.message` and `marker.code`?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/CJsI4.png

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
