### ISSUE TITLE
Handlebars brackets agresively colored

### ISSUE THREAD

**Issue by isidorn** [Microsoft/monaco-editor#212]
Refs: https://github.com/Microsoft/vscode/issues/12691

monaco-editor npm version: latest
Browser: chrome
OS: os sierra

Paste the following handlebars code into the editor. Notice that the editor now aggressivly colors each bracket in red. This is different than previous behavior but the reason why I am creating this issue is because the color feels too strong for a bracket and feels distracting imho

```handlebars
<div class="entry">
	<h1>{{title}}</h1>
	{{#if author}}
	<h2>{{author.firstName}} {{author.lastName}}</h2>
	{{else}}
	<h2>Unknown Author</h2>
	{{/if}}
	{{contentBody}}
</div>
```

![screen shot 2016-09-27 at 12 36 36](https://cloud.githubusercontent.com/assets/1926584/18870026/28eca574-84af-11e6-9e49-6a51c555e5d7.png)

**Comment by alexandrudima** [comment]
Fixed with Microsoft/monaco-languages@ac89ee029e6c2105a352078ce51bfab47792ddb9
