### ISSUE TITLE
How to get the horizontal position (left offset) for the colunm?

### ISSUE THREAD

**Issue by TerryChan** [microsoft/monaco-editor#2126]
I need to convert the [lineNmber, column] coordinate to [x, y] pixel coordinate to the top-left, and I found API getTopForLineNumber and getTopForPosition to convert the lineNumber to vertical pixel coordinate, but I didn't find any API to convert column to horizontal pixel coordinate. Is there any method to convert column to horizontal pixel coordinate?

**Comment by alexdima** [comment]
You can use [`getOffsetForColumn`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#getoffsetforcolumn).

**Comment by TerryChan** [comment]
> You can use [`getOffsetForColumn`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#getoffsetforcolumn).

@alexdima  Great, thanks
