### ISSUE TITLE
The decoration hoverMessage is not displayed 

### ISSUE THREAD

**Issue by bleathem** [microsoft/monaco-editor#2128]
I can't get the `hoverMessage` to display for a line decoration.  I reproduced it on this Monaco editor playground page:
https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin

by adding the line:
```js
hoverMessage: {value: 'test'}
```

Is there something more I should add to get the `hoverMessage` to display?

**monaco-editor version:** 0.20.0
**Browser:** Chrome 85
**OS:** Mac OS 10.15.6
**Playground code that reproduces the issue:**

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript",
	glyphMargin: true
});

var decorations = editor.deltaDecorations([], [
	{
		range: new monaco.Range(3,1,3,1),
		options: {
			isWholeLine: true,
			className: 'myContentClass',
			glyphMarginClassName: 'myGlyphMarginClass',
                        hoverMessage: {value: 'test'}
		}
	}
]);

// You can now use `decorations` to change or remove the decoration

```

**Comment by bleathem** [comment]
`glyphMarginHoverMessage` works:

```
var decorations = editor.deltaDecorations([], [
	{
		range: new monaco.Range(3,1,3,1),
		options: {
			isWholeLine: true,
			className: 'myContentClass',
			glyphMarginClassName: 'myGlyphMarginClass',
			glyphMarginHoverMessage: {value: 'test'}
		}
	}
]);
```

**Comment by alexdima** [comment]
The hover message will render only on the defined range. In this case it was `new monaco.Range(3,1,3,1)`, which is a collapsed range. If you change that to something like `range: new monaco.Range(3,1,3,10)`, then the message renders when hovering over the line:

![image](https://user-images.githubusercontent.com/5047891/93466320-5b8a9300-f8ec-11ea-80c1-0abdab41c8f8.png)

**Comment by lmvco** [comment]
Hi @alexdima,

I understand your point of view. Anyway, since this is a whole line decoration, I would like to see the hover message even when the mouse is hovering the line but not over any text. Is it possible?

**Comment by alexdima** [comment]
That does not currently work because it is unexpected that hovering over empty space shows a hover. Usually people see source code or symbols and they want to hover on the source code to learn more, etc. If you wish to do something special, you could directly use mouse events to render a widget or your own dom node near the mouse position, etc.
