### ISSUE TITLE
Monarch documentation refers monarch.css which is absent in download package

### ISSUE THREAD

**Issue by AxCoder** [Microsoft/monaco-editor#213]
[Monarch docs](https://microsoft.github.io/monaco-editor/monarch.html) contains phrase 

> Note: The token classes in the third column are currently only highlighted correctly if you include the monarch.css style file (Aug 2012).

But I can not find where is official place for it:
- tgz does not contain it
- documentation does not provide any hint where to finds it

monaco-editor tgz version: 0.6.1
Browser: Any
OS: Any

**Comment by alexandrudima** [comment]
The contents of that file have been inlined into the bundled editor.main.css.

**Comment by AxCoder** [comment]
It means, that documentation should be changed, I think
