### ISSUE TITLE
Monaco editor nightwatch e2e testcase is behaving very strange

### ISSUE THREAD

**Issue by GNSubrahmanyam** [microsoft/monaco-editor#2134]
**monaco-editor version:** any
**Browser:** Chrome
**OS:**
**Playground code that reproduces the issue:**

```js
module.exports = {
  'Open Intellisense IDE': function (browser) {
    browser.url("https://microsoft.github.io/monaco-editor/index.html")
      .pause(1000)
      .setValue('#editor > div > div.overflow-guard > textarea', 'console.log("Hello")')
      .pause(1000)
      .keys([browser.Keys.CONTROL, browser.Keys.SPACE])
      .pause(2000)
      .keys(browser.Keys.ARROW_DOWN)
      .pause(3000)
      .keys(browser.Keys.ENTER)
      .keys(browser.Keys.ENTER)
      .setValue('#editor > div > div.overflow-guard > textarea', 'console.log("world")')
      .pause(8000)
      .end()
      
  },
};
```

**Comment by alexdima** [comment]
Please ask your question on [StackOverflow](https://stackoverflow.com/questions/tagged/monaco-editor). We have a great community over [there](https://stackoverflow.com/questions/tagged/monaco-editor). They have already answered hundreds of questions and are happy to answer yours as well. You can also try [searching through existing issues](https://github.com/microsoft/monaco-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+), looking at [API usage samples](https://microsoft.github.io/monaco-editor/playground.html) or at [integration samples](https://github.com/Microsoft/monaco-editor-samples). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by GNSubrahmanyam** [comment]
@alexdima If i write testcases in selenium it works fine. But it behaves strange in nightwatch.js

**Comment by alexdima** [comment]
I'm sorry, I'm not familiar with `nightwatch.js`. Please try to demonstrate an editor problem.
