### ISSUE TITLE
Get selected completion/get code as if it was selected

### ISSUE THREAD

**Issue by tpetricek** [microsoft/monaco-editor#214]
I'm experimenting with using Monaco zones for live-previewing data that is calculated in the script written in my language hosted in Monaco editor. It all works neatly :).

The one thing that is tricky is that when you are typing code and using auto-completion, you often end up with invalid code (that's fine, I can deal with that), but when the user is selecting option in auto-complete, I would like to be notified about it and get code "as if the option was selected". A gif to illustrate this:

![untitled](https://cloud.githubusercontent.com/assets/485413/19017534/1d1c74ca-8835-11e6-8b5f-a15d03ba058e.gif)

As you can see, the zone displays preview based on the current cursor position. When you start typing, it still parses the code, but it has no idea about the selected option in the auto-complete.

Is there a way to get the current selection so that I can render preview based on the selected option?

**Comment by alexandrudima** [comment]
AFAIK the suggest widget does not expose in any API the current selected suggestion. fyi @jrieken @joaomoreno

**Comment by hediet** [comment]
You could use the resolve command for that, though it might have some quirks.
