### ISSUE TITLE
the "padding" option was not work on editor create

### ISSUE THREAD

**Issue by MRchenkuan** [microsoft/monaco-editor#2141]
![image](https://user-images.githubusercontent.com/9814867/93657918-5010a680-fa69-11ea-9542-82bb5c344064.png)

am i use it wrong way?

**Comment by alexdima** [comment]
0.21 was not released yet due to a late discovered bug https://github.com/microsoft/monaco-editor/issues/2140.

You can subscribe to https://github.com/microsoft/monaco-editor/issues/2074
