### ISSUE TITLE
There is a deployment error here:Cannot find module 'vs/editor/standalone/browser/quickOpen/gotoLine'

### ISSUE THREAD

**Issue by lcandmmn** [microsoft/monaco-editor#2143]
**monaco-editor version:** 0.21.0
**Browser:**Chrome
**Reason:**Maybe the problem is that the package of monaco-editor-core is updated to version 0.21.0，so I tried to find the problem from 'https://github.com/microsoft/vscode/tree/master/src/vs/editor/standalone/browser', but I didn't find the quickOpen file
**OS:**
**Playground code that reproduces the issue:**

```js
```

**Comment by alexdima** [comment]
@lcandmmn I'm not sure I understand, what is the problem exactly ?

**Comment by lcandmmn** [comment]
Thank you for the quick answer.
I used package in my project 'monaco-editor-webpack-plugin@1.9.0'. The deployment error is "cannot find module 'vs/editor/standalone/browser/quickOpen/gotoLine' ".
If I have installed 'monaco-editor@0.20.0', it will be normal. so, I think it may be some compatibility problems after the update of monaco-editor version. 
I'm sorry, I don't know if it has been described clearly

**Comment by alexdima** [comment]
Thanks for the extra information. For `monaco-editor@0.21.0`, you will have to use `monaco-editor-webpack-plugin@2.0.0`:

Please see https://github.com/microsoft/monaco-editor-webpack-plugin#version-matrix

![image](https://user-images.githubusercontent.com/5047891/93820802-fc1ae300-fc5d-11ea-8247-839afcac6ec9.png)
