### ISSUE TITLE
Command palette option Developer: Inspect Tokens is not toggleable

### ISSUE THREAD

**Issue by flokol120** [microsoft/monaco-editor#2146]
**monaco-editor version:** 0.21.0
**Browser:** Google Chrome, Firefox, Edge
**OS:** Windows 10
**Playground code that reproduces the issue:**

```js
**any**
```

1. Go to https://microsoft.github.io/monaco-editor/
2. open the command palette via f1
3. search for _Developer: Inspect Tokens_ and click it
4. try to disable it by searching for _Developer: Inspect Tokens_ again and clicking it
--> the inspector does not close.

**Comment by alexdima** [comment]
Escape will close the widget. This is the case with multiple editor widgets, like the find widget (cmd+F), rename (F2), suggest (ctrl+space), etc.
