### ISSUE TITLE
Hide a string value somewhere in marker

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2151]
I would like to know in marker https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imarkerdata.html, whether we could store a string value somewhere and do not show it in the diagnostic popup window.

`message` and `code` are all shown in the diagnostic popup window. `message` in `relatedInformation` is displayed as well. It seems that nowhere we could hide a string value.

Could anyone help?

**Comment by stefandobre** [comment]
I don't see `message` nor `messageText` in relatedInformation appearing in the diagnostic popup...

But if you're in a Javascript context (I suppose in Typescript an error would be raised?), you could just assign your value to an unused key, eg:

```
monaco.editor.setModelMarkers(editor.getModel(), 'my-markers', [{
    message: 'message',
    startColumn: 1,
    endColumn: 30,
    startLineNumber: 2,
    endLineNumber: 2,
    relatedInformation: {
        secret: 'my-secret'
    }
}]);
```

I am able to then access this value via `monaco.editor.getModelMarkers('my-markers')`

**Comment by chengtie** [comment]
> I don't see `message` nor `messageText` in relatedInformation appearing in the diagnostic popup...
> 
> But if you're in a Javascript context (I suppose in Typescript an error would be raised?), you could just assign your value to an unused key, eg:
> 
> ```
> monaco.editor.setModelMarkers(editor.getModel(), 'my-markers', [{
>     message: 'message',
>     startColumn: 1,
>     endColumn: 30,
>     startLineNumber: 2,
>     endLineNumber: 2,
>     relatedInformation: {
>         secret: 'my-secret'
>     }
> }]);
> ```
> 
> I am able to then access this value via `monaco.editor.getModelMarkers('my-markers')[0].relatedInformation.secret`

Thank you... But I'm writing TypeScript. Is it possible to dismiss this kind of error?

**Comment by chengtie** [comment]
I do write TypeScript.

I could use `//@ts-ignore` to ignore errors.

If I put `secret: 'my-secret'` inside `relatedInformation`. `relatedInformation` will be displayed in the popup window (without `my-secret`), which is still not what I want.

If I put `secret: 'my-secret'` under the marker object, my tests showed that `getModelMarkers` could not get the field `secret`.

**Comment by alexdima** [comment]
Other fields from markers do not survive setting and getting (`setModelMarkers`, `getModelMarkers`) because new objects get created [here](https://github.com/microsoft/vscode/blob/73b33dcbc8204c23ae30b53ce129b32c6da98197/src/vs/platform/markers/common/markerService.ts#L191-L224). But you can use the `owner` field to identify and get only the markers that you have created before.

**Comment by chengtie** [comment]
It seems that the only places where I see the value of `owner` are

```
monaco.languages.register({
  id: LANGUAGE_ID, // value of owner
  extensions: [],
  aliases: [],
  mimetypes: [],
});
```

and

```
monaco.languages.onLanguage(valueOfOwner, () => {
  return setupMode();
});
```

We want to hide a string value that changes very often. It seems that `owner` is not a good place.

**Comment by alexdima** [comment]
What you want is not possible. You can add decorations to the editor by yourself, in parallel to the markers, markers are just decorations. So when you set the markers, you can create decorations (without any rendering) and then you can read the decorations from the editor back to get the new ranges.
