### ISSUE TITLE
Store information in model when using diagnostics and hover together

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2152]
I'm writing my own IDE by Monaco Editor.

First, I have diagnostics which sets markers from the result of `optimizeFormula(text, "A1")`:

```
export class DiagnosticsAdapter {

    private async _doValidate(model: monaco.editor.ITextModel): Promise<void> {
        if (model.isDisposed()) {
            // model was disposed in the meantime
            return;
        }

        const promises: Promise<Diagnostic>[] = [];

        let text = model.getValue();

        let resultA = optimizeFormula(text, "A1"); 

        resultA.forEach(resultA1 => {
            promises.push(Promise.resolve({ // see "interface Diagnostic" and "interface DiagnosticRelatedInformation" above
                category: DiagnosticCategory.Warning, // DiagnosticCategory.Suggestion, category: DiagnosticCategory.Error,
                code: utilities.codeFromRule(resultA1.rule), 
                file: undefined,
                length: resultA1.ending - resultA1.start,   
                messageText: utilities.diagnosticMessageFromResult(resultA1),
                start: resultA1.start + 1,
            }))    
        });

        const diagnostics = await Promise.all(promises);

        if (!diagnostics || model.isDisposed()) {
            // model was disposed in the meantime
            return;
        }

        const markers = diagnostics
            .map(d => this._convertDiagnostics(model, d));

        monaco.editor.setModelMarkers(model, this._selector, markers);
    }
}
```

Because we could write markdown in the popup window of hover, I also use hover, which are made from markers generated earlier.

```
public async provideHover(model: monaco.editor.ITextModel, position: monaco.Position, token: CancellationToken): Promise<monaco.languages.Hover | undefined> {

        let contents : any[] = [];
        monaco.editor.getModelMarkers({}).forEach(marker => {
	    let markerStart = new monaco.Position(marker.startLineNumber, marker.startColumn);
	    let markerEnd = new monaco.Position(marker.endLineNumber, marker.endColumn);
            if (markerStart.isBeforeOrEqual(position) && position.isBeforeOrEqual(markerEnd) && marker.code != undefined) {  
                contents.push({ value: utilities.contentMarkdownFromCodeMessage(marker.code, marker.message), isTrusted: false })
            }
        })
        return { contents: contents };
}
```

However, I would prefer to directly build the contents of hover from the result of `optimizeFormula(text, "A1")` as how we build markers. But I don't want to run `optimizeFormula(text, "A1")` once again.

So ideally I would like to calculate the result of `optimizeFormula(text, "A1")` in ` _doValidate` once for all, save it somewhere in the model, then get it in `provideHover`.

Is it possible?

**Comment by alexdima** [comment]
You can create a cache map that you share between your two providers. 

You can then use the model uri as a cache key and you can also store in the cache value the model version and the computed result. Then, you can check if your cache is still valid by checking if the model changed in the meantime using the model version.

**Comment by chengtie** [comment]
Thank you.

I see that model could have different versions (https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#getversionid).

But I don't understand the purpose of the model uri... If it is another kind of versioning, I don't see any unique value in such a value: https://ibb.co/6B0y8hK

Additionally, where should I store the cache map shared between providers and diagnostics? Do you happen to have an example?

**Comment by alexdima** [comment]
You need to use `model.uri.toString()`. No example, sorry I have limited time and cannot help with general programming problems. You can structure your code however you wish.
