### ISSUE TITLE
item.dispose is not a function

### ISSUE THREAD

**Issue by kerbal** [microsoft/monaco-editor#2153]
**monaco-editor version:** 0.20.0
**OS: Ubuntu 18**
**Playground code that reproduces the issue:** https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example

I use codelens provider and it throw this error everytime the content changes
![image](https://user-images.githubusercontent.com/33062751/94133841-64024100-fe8b-11ea-9573-d3dd36e69638.png)

How to solve this?
Thank you!

**Comment by alexdima** [comment]
The sample didn't return a correct `CodeLensList`:

```
	export interface CodeLensList {
		lenses: CodeLens[];
		dispose(): void;
	}
```

It must return an array of `lenses`, and also a `dispose` method. I'm not quite sure when this was added, I think it must have been even before the recent 0.21.0 release.
