### ISSUE TITLE
Suggestions are not aligned to the Center.

### ISSUE THREAD

**Issue by SAIPRANAY-GANGULA** [microsoft/monaco-editor#2154]
As Iam increasing the font-size, suggestions are clearly visible. But on smaller font-size I cannot clearly see suggestions.
Is there a way to resolve this issue? If yes please suggest me the one. Thanks in advance.
![image](https://user-images.githubusercontent.com/56952302/94261516-9ecdad00-ff4f-11ea-9d04-dae60c9a6a22.png)
![image](https://user-images.githubusercontent.com/56952302/94261571-b0af5000-ff4f-11ea-9b4b-35484064adac.png)

**Comment by alexdima** [comment]
It looks like you have CSS on your page that is selecting and modifying the content of the editor. You can:
- load the editor via shadow dom
- investigate and remove your CSS that is selecting dom nodes of the editor.

**Comment by SAIPRANAY-GANGULA** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/56952302/96106738-2d06d480-0ef9-11eb-835b-1c006ad84bd1.png)
 **" 
   .label-name {
    line-height: normal;
  }
"**

Yes, CSS on my page that is selecting and modifying the content of the editor. So, added above styling for editor.
