### ISSUE TITLE
Hover message hides when trying to move the mouse to it using overflowWidgetsDomNode

### ISSUE THREAD

**Issue by pankajk07** [microsoft/monaco-editor#2156]
1. Go Monaco playground
2. Add the code snippet attached below
3. Hover over function name `hello`
4. Move the mouse to the popover
5. The popover disappears

Expectation:
The popover should not disappear when the mouse moves to it

**monaco-editor version:** 0.21.1
**Browser:** Chrome
**OS:** MacOS
**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById("container"), {
    language: "javascript",
    overflowWidgetsDomNode: document.querySelector('body'),
    fixedOverflowWidgets: true,
    value: `
/**
 * sample doc
 */
function hello() {
	alert('Hello world!');
}`
});
document.querySelector('body').classList.add('monaco-editor');
```

**Comment by alexdima** [comment]
The hover listens to mouse events from the editor, and since it is now rooted outside the editor, it does not receive the editor mouse events anymore.

**Comment by AndersMad** [comment]
on another (old) note - I was hoping `overflowWidgetsDomNode` would solve this: https://github.com/microsoft/monaco-editor/issues/70 - but the "F1 Command Palette" is still not useable in small editors.

**Comment by blutorange** [comment]
Related issue and probably caused by the same event-handling cause is that pressing F2 to rename a symbol does not work either -- the rename overflow widget appears but immediately disappears again (Chrome 92.0.4515.107)

**Comment by mifopen** [comment]
@alexdima I've seen that you've been refactoring this part a lot during the last weeks. Does it make sense for me to repeat that exact solution from @lengthmin in another PR?
