### ISSUE TITLE
Renew Completion Item Provider feature

### ISSUE THREAD

**Issue by calebeaires** [microsoft/monaco-editor#2159]
Evert time we user monaco.languages.registerCompletionItemProvider the list previouly sent to suggestion is replicated if you send the same array, (but with more itens). I was looking to an way to not add itens, but renew the already added list

**Comment by rcjsuen** [comment]
@calebeaires Did you try cloning/duplicating the array?

**Comment by calebeaires** [comment]
Yes, like this

```
  this.$data.language = monaco.languages.registerCompletionItemProvider('sql', {
            triggerCharacters: ['.'],
            provideCompletionItems: () => {
                return {
                    suggestions: Object.assign([], this.$data.suggestions),
                };
            },
        });

```

I use a component multiple times on page. Suggestions array are sent to this component. The suggestion is not renewed, but added. 

A **un**register function would be great to control how custom suggestion are implemented.

**Comment by calebeaires** [comment]
I end up doing this action outside the vue instance. This way the monaco is created just once.
