### ISSUE TITLE
How to make a custom completion item also prompt when assigning a value

### ISSUE THREAD

**Issue by jiazhuangzhexiaozhang** [microsoft/monaco-editor#2160]

**Comment by rcjsuen** [comment]
@jiazhuangzhexiaozhang Can you elaborate on your question with some screenshots? I'm not sure I understand what you're asking for here.

**Comment by jiazhuangzhexiaozhang** [comment]
> @jiazhuangzhexiaozhang您可以用一些屏幕截图详细说明您的问题吗？我不确定我在这里了解您的要求。

> 
![微信图片1](https://user-images.githubusercontent.com/31621564/94506959-3299c480-0241-11eb-8dcf-c492408fb135.png)
![微信图片2](https://user-images.githubusercontent.com/31621564/94506969-36c5e200-0241-11eb-976c-a1920dccf1a6.png)

**Comment by jiazhuangzhexiaozhang** [comment]
> @jiazhuangzhexiaozhang Can you elaborate on your question with some screenshots? I'm not sure I understand what you're asking for here.

I sent！
