### ISSUE TITLE
[error]about monaco editor language registerSignatureHelpProvider 

### ISSUE THREAD

**Issue by cxwSuperman** [microsoft/monaco-editor#2164]
**monaco-editor version: 0.20.0**
**Browser: Google Chrome**
**OS: Windows**
**Playground code that reproduces the issue:**

When I use this method, the first time I start the function with "Ctrl+Shift+Space" there is no problem, but when I enable it again, the following problems will occur:
Uncaught Error: this._value.dispose is not a function
```
TypeError: this._value.dispose is not a function
     at MutableDisposable.set [as value] (lifecycle.js:159)
     at ParameterHintsModel.<anonymous> (parameterHintsModel.js:235)
     at step (parameterHintsModel.js:60)
     at Object.next (parameterHintsModel.js:41)
     at fulfilled (parameterHintsModel.js:32)
     at errors.js:12
```

Then I removed **this._value.dispose()** in **lifecycle.js** and found that it can be used normally
![image](https://user-images.githubusercontent.com/48375394/94416459-7513c080-01b1-11eb-8af1-bfd13926c491.png)

**Comment by alexdima** [comment]
Can you please provide a snippet of code which reproduces the problem at https://microsoft.github.io/monaco-editor/playground.html ?

**Comment by cxwSuperman** [comment]
> Can you please provide a snippet of code which reproduces the problem at https://microsoft.github.io/monaco-editor/playground.html ?
**Add the following code under Custom languages**
`monaco.languages.registerSignatureHelpProvider('mySpecialLanguage', {
				// signatureHelpTriggerCharacters: ['(',','],
				provideSignatureHelp(model, position) {
					console.log('Signature Help');
					return {
						value: {
							activeParameter: 0,
							activeSignature: 0,
							signatures: [
								{
									label: 'string substr(string $string, int $start [, int $length])',
									parameters: [
										{
											label: 'string $string',
											documentation: 'The input string. Must be one character or longer.',
										},
										{
											label: 'int $start',
											documentation:
												"If $start is non-negative, the returned string will start at the $start'th position in string, counting from zero. For instance, in the string 'abcdef', the character at position 0 is 'a', the character at position 2 is 'c', and so forth.\r\nIf $start is negative, the returned string will start at the $start'th character from the end of string. If $string is less than $start characters long, FALSE will be returned.",
										},
										{
											label: 'int $length',
											documentation:
												'If $length is given and is positive, the string returned will contain at most $length characters beginning from $start (depending on the length of $string) If $length is given and is negative, then that many characters will be omitted from the end of $string (after the start position has been calculated when a start is negative). If $start denotes the position of this truncation or beyond, FALSE will be returned. If $length is given and is 0, FALSE or NULL, an empty string will be returned. If $length is omitted, the substring starting from $start until the end of the string will be returned.',
										},
									],
								},
							],
						},
					};
				},
			});`

**Comment by cxwSuperman** [comment]
**Trigger "Ctrl+Shift+Space" multiple times and only the first time will be effective**
![image](https://user-images.githubusercontent.com/48375394/94503712-aafc8780-0239-11eb-8d9d-0653dcb67ba0.png)

**Comment by cxwSuperman** [comment]
**I originally thought it might be a problem with the monaco-editor version, but I used version 0.20.0. So I guess the upgrade version can be solved, but then my project can not start, it will show that the following files cannot be found**
![image](https://user-images.githubusercontent.com/48375394/94503897-22cab200-023a-11eb-93b1-f0f829998902.png)

**Comment by cxwSuperman** [comment]
I just tried this in the playground and found that there is still a problem, so I guess this bug has not been fixed.

**Comment by cxwSuperman** [comment]
My initial solution is to comment out lines 157 to 159 in lifecycle.js, and it can be used normally. I haven't tested any problems after commenting out.
![image](https://user-images.githubusercontent.com/48375394/94530908-5b847e80-026e-11eb-87d9-07c6891c3607.png)

**Comment by alexdima** [comment]
@cxwSuperman It looks like the return value is not correct:
```ts
    /**
     * The signature help provider interface defines the contract between extensions and
     * the [parameter hints](https://code.visualstudio.com/docs/editor/intellisense)-feature.
     */
    export interface SignatureHelpProvider {
        readonly signatureHelpTriggerCharacters?: ReadonlyArray<string>;
        readonly signatureHelpRetriggerCharacters?: ReadonlyArray<string>;
        /**
         * Provide help for the signature at the given position and document.
         */
        provideSignatureHelp(model: editor.ITextModel, position: Position, token: CancellationToken, context: SignatureHelpContext): ProviderResult<SignatureHelpResult>;
    }

    export interface SignatureHelpResult extends IDisposable {
        value: SignatureHelp;
    }

    export interface IDisposable {
        dispose(): void;
    }
```

So you need to return an object with a `value` field and with a `dispose` method.
