### ISSUE TITLE
Add contentWidget by pixel coordinate instead of [lineNUmber, column]?

### ISSUE THREAD

**Issue by TerryChan** [microsoft/monaco-editor#2165]
I added a ContentWidget with the code below:
```
modifiedEditor.addContentWidget(widget)
```
And the widget constructed with position like below:
```
getPosition: function () {
        return {
          position: {
            lineNumber,
            column,
          },
          preference: [monaco.editor.ContentWidgetPositionPreference.BELOW],
        }
      },
```
I found it can only be added by [lineNumber, column] position, how can I add by [x, y] pixel position? Is it feasible? If not, is there any walkaround to add by [x, y] pixel position?

**Comment by alexdima** [comment]
Yes, you can add an overlay widget, which does not flow with the text and which you can position whichever way you want (e.g. the find widget is an overlay widget).

**Comment by TerryChan** [comment]
@alexdima But overlay widget cannot meet my requirement, I need the content widget move with the editor when scroll the editor. ContentWidget is just what I need, but I can't change its position by pixel immediately after it's added.

**Comment by alexdima** [comment]
You can listen to scroll events and position the widget when the scroll changes as you desire.
