### ISSUE TITLE
Why cannot move ContentWidget by pixel immediately?

### ISSUE THREAD

**Issue by TerryChan** [microsoft/monaco-editor#2166]
I added a ContentWidget with [lineNumber, column] position, and I tried to move the ContentWidget dom node by style.top and style.left to a target position immediately after calling modifiedEditor.addContentWidget(widget), but it didn't work. I tried two methods:
1. Call widget.getDomNode().style.left = '500px' after modifiedEditor.addContentWidget(widget), didn't work.
2. Use querySelectorAll API to retrieve the widget dom node, then set its left and top. It didn't work if I set immediately after modifiedEditor.addContentWidget(widget), but if I set several seconds later after modifiedEditor.addContentWidget(widget), its position changed. Looks like I can't change its position immediately after addContentWidget(), any body know why?  and how can I change the content widget's position immediately after it's added? Thanks in advance.

**Comment by alexdima** [comment]
A content widget is supposed to be positioned by the editor. If you don't want the editor to position it, then please use an overlay widget.
