### ISSUE TITLE
How to copy the text in viewZone of inline-diff-editor?

### ISSUE THREAD

**Issue by chenmy0917** [microsoft/monaco-editor#2167]
version: 0.20.0
browser: Google Chrome 85.0.4183.121

![image](https://user-images.githubusercontent.com/22138217/94511515-2830f800-024c-11eb-8ede-042735d79207.png)

**Comment by chenmy0917** [comment]
version: 0.20.0
browser: Google Chrome 85.0.4183.121

![image](https://user-images.githubusercontent.com/22138217/94511515-2830f800-024c-11eb-8ede-042735d79207.png)

**Comment by alexdima** [comment]
Let's track in #1035

**Comment by chenmy0917** [comment]
> Let's track in #1035

get, thank you!
