### ISSUE TITLE
URL underline and click-to-open stops at escaped quote

### ISSUE THREAD

**Issue by kvchen** [microsoft/monaco-editor#2170]
We sometimes encounter URLs that use escaped double-quotes (instead of url-encoding to `%22`). Browsers still typically accept these URLs, but Monaco stops parsing the URL when it encounters a double-quote. An example can be seen in the repro.

**monaco-editor version:** 0.21.2
**Browser:** Google Chrome
**OS:** MacOS 10.15.6
**Playground code that reproduces the issue:**

```js
"https://www.foo.com?bar=\"baz\""
```

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/monaco-editor/issues/2145
