### ISSUE TITLE
expandSuggestionDocs auto and inline

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/monaco-editor#2177]
Hi , it possible to provide option to allow inline documentations and also auto expand suggest box?
I find it a bit of a shame to inform the user to use ctrl + space to expand more doc.

i try `monaco.editor.create(document.getElementById("container"), {
  expandSuggestionDocs:true,`
but seem no effect, is only allow of disable doc.

plz see this for inline example.
https://github.com/microsoft/monaco-editor/issues/501

**Comment by xintaoLi** [comment]
this.editor.getContribution("editor.contrib.suggestController").widget.value._setDetailsVisible(true);

this work for me
