### ISSUE TITLE
Editor action is run twice in Firefox

### ISSUE THREAD

**Issue by PyvesB** [microsoft/monaco-editor#2178]
**monaco-editor version:** 0.21.x
**Browser:** Firefox (reproduced in version 68.0.1 and 81.0.1)
**OS:** macOS (reproduced in Mojave 10.14.6 and Big Sur 11.0 Beta)
**Playground code that reproduces the issue:**

```js
editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
editor.addAction({
    id: "some-id",
    label: "some example",
    contextMenuGroupId: "1_menu",
    run: function() {
      console.log(Date.now() + " - running action");
    }
});
```

If you  load the above code in the playground, open the Firefox debug console, click right inside the document and select the "some example" action, you'll notice that the action log is displayed twice in a row.

Note that this doesn't seem to be reproducible in Chrome. In Firefox, this worked fine in Monaco Editor version 0.20.0, but broke in version 0.21.0. It can still be reproduced in the latest release at the time of writing, 0.21.2.

Thanks for reading, let me know if you need any more information.

**Comment by spahnke** [comment]
**Slight addition:** For me this only reproduces if you *click* the item in the context menu. Using `Shift+10` to open the context menu and selecting the item by keyboard seems to work fine. This also seems to work correctly if you define a keybinding and use that to trigger the action, or if you trigger the action by selecting it in the command palette.

**Comment by kevinvalk** [comment]
> 
> 
> **Slight addition:** For me this only reproduces if you _click_ the item in the context menu. Using `Shift+10` to open the context menu and selecting the item by keyboard seems to work fine. This also seems to work correctly if you define a keybinding and use that to trigger the action, or if you trigger the action by selecting it in the command palette.

Can confirm this behavior in FireFox 81.0.1 (64-bit)

**Comment by StefanRetief** [comment]
Also ran into this issue with the quickfix light bulb #2223.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/issues/108621
