### ISSUE TITLE
Expose VS Code UI Widgets (With Type Declarations)

### ISSUE THREAD

**Issue by StefanRetief** [microsoft/monaco-editor#2180]
I was digging through the monaco-editor package and noticed quite a few UI components located under esm/vs/base/browser/ui. Almost all of them seem usable, though they are lacking typescript support. It may be useful for developers that are attempting to keep the same styling as vs-code, to be able to use these same UI components.

**Comment by orta** [comment]
I'm kinda interested in how much these are considered "public" API too. 

I've started exploring re-using the monaco copy of `Tree` to show a file browser in the TypeScript playground https://github.com/microsoft/TypeScript-Website/pull/1237 - my plan is to definitely consider digging into the modules as an implementation detail (and thus could be broken at any time in the future) but @StefanRetief all of the underlaying types are available in the vscode codebase

**Comment by StefanRetief** [comment]
@orta I have a similar objective to what you have done in your PR. I can work with them not being "public" for the moment, although, looking through your code, I see that you reference ```/vs/base/parts/tree/browser/treeImpl``` and ```/vs/base/parts/tree/browser/treeDefaults```. Both of these are absent in the current version of monaco-editor. Are there any plans to restore these modules and those similar to them?

I'd be interested in collaborating on my own time to get this issue off the ground, given that I need some help to get started.

**Comment by orta** [comment]
I use the minimized AMD builds of monaco, where these files exist in-memory - if you're looking at basing your work in esm, then I'd use https://github.com/BlueMagnificent/monaco-tree as a reference.

**Comment by hediet** [comment]
/duplicate https://github.com/microsoft/monaco-editor/issues/1635
