### ISSUE TITLE
Markdown code blocks issue

### ISSUE THREAD

**Issue by stla** [microsoft/monaco-editor#2181]
Hello,

  From the Pandoc manual:

![pandocManual](https://user-images.githubusercontent.com/4466543/95397250-05b17580-0903-11eb-9f4e-e691e028d7a6.png)

However the syntax highlighting does not work with the second option:

![MonacoMarkdown](https://user-images.githubusercontent.com/4466543/95397307-2c6fac00-0903-11eb-9335-edf0033c7507.png)

**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById("container"), {
	value: [
        "# Markdown",
        "",
        "```r",
        "## Below is a R function",
        "f <- function(x){",
        "  y <- paste(",
        "    x, 'hello'",
        "  )",
        "  return(y)",
        "}",
        "```",
        "",
        "``` {.r}",
        "## Below is a R function",
        "f <- function(x){",
        "  y <- paste(",
        "    x, 'hello'",
        "  )",
        "  return(y)",
        "}",
        "```"
    ].join("\n"),
	language: "markdown"
});
```

**Comment by Prinzhorn** [comment]
What type of Markdown extension uses this syntax? Can you link a specification?

Monaco supports a subset of the [GitHub Flavored Markdown](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks) syntax (your first example). I haven't seen the other syntax you've posted and it's not GitHub Flavored Markdown.

If you want to contribute a different syntax this is the place to look https://github.com/microsoft/monaco-languages/blob/be30e69ac268f58777a4f89a35ee9ceee28ce0f9/src/markdown/markdown.ts#L100-L101

**Comment by stla** [comment]
Hello,

 Will take a look at your link later.

 This syntax is used by **Pandoc**, which is widely used for converting Markdown to various file formats (html, tex, docx, and more).

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
