### ISSUE TITLE
ECMAScript typings get lost after certain operations in JavaScript code

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#2182]
**monaco-editor version:** 0.21.2
**Browser:** Edge (Chromium) 85, Chrome 85, Firefox 81
**OS:** Windows 10
**Playground code that reproduces the issue:**

- run the following code
- do a "Peek Definition" on `isNaN` (if you use Firefox use the shortcut to do this instead of clicking in the context menu because of #2178)
- close the peek widget
- type a space behind the semicolon to trigger diagnostics

-> error on `Number` appears. This doesn't seem to happen for `language: "typescript"`.
![grafik](https://user-images.githubusercontent.com/25029871/95430048-809e7e80-094b-11eb-9031-b47508b85794.png)

If you do the "Peek Definition" on `Number` you get the error on `isNaN` afterwards:
![grafik](https://user-images.githubusercontent.com/25029871/95430724-729d2d80-094c-11eb-8677-4f10c7039655.png)

```js
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ESNext,
    allowNonTsExtensions: true,
});

monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
    noSyntaxValidation: false,
    noSemanticValidation: false,
    noSuggestionDiagnostics: false,
});

monaco.editor.create(document.getElementById("container"), {
    language: "javascript",
    value: "Number.isNaN(1);"
});
```

**Comment by spahnke** [comment]
I should say that the errors just make it more prominent that something is strange, but you can even see that without those settings. Using the following simpler code and executing the "Peek Definition" action on `isNaN`, you get `any` in the hover of `isNaN` afterwards.
```js
monaco.editor.create(document.getElementById("container"), {
    language: "javascript",
    value: "Number.isNaN(1);"
});
```

**Before Peek Definition**
![grafik](https://user-images.githubusercontent.com/25029871/95431190-18509c80-094d-11eb-882d-1d1bec91587a.png)

**After Peek Definition**
![grafik](https://user-images.githubusercontent.com/25029871/95431236-27cfe580-094d-11eb-9769-d14cf5726454.png)

**Comment by spahnke** [comment]
It seems like all definitions are removed except for those that are defined in the model/extra lib you see in the peek window. For example, if you open the peek window for the `flat` method in the code `[].flat` then you see the model for `lib.es2019.array.d.ts`. After you close the peek window all definitions are gone except for `flat` and `flatMap` as you can see by opening the suggestions for the array. I hope I described this somewhat understably 😅
![image](https://user-images.githubusercontent.com/25029871/95485960-b3b83080-0992-11eb-84a7-a41e5414eab7.png)

**Comment by spahnke** [comment]
Another example I found which is even more impacting:
- Run the following code in the playground
- Hover on `fromCodePoint` to get the documentation
- Press <kbd>Ctrl+Space</kbd> while the hover is shown to show completions

-> No completions are shown and both `String` and `fromCodePoint` are now typed as `any`.

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "String.fromCodePoint(32)",
	language: "javascript"
});

editor.setPosition({lineNumber: 1, column: 8});
editor.focus();
```

![grafik](https://user-images.githubusercontent.com/25029871/98097498-60e87080-1e8d-11eb-8f00-3bf1f6654e16.png)
![grafik](https://user-images.githubusercontent.com/25029871/98097531-6e055f80-1e8d-11eb-9dcc-19de58b4b779.png)
![grafik](https://user-images.githubusercontent.com/25029871/98097569-7bbae500-1e8d-11eb-88b3-f669900908f6.png)

**Comment by alexdima** [comment]
Alternative repro:

```
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "String.fromCodePoint(32)",
	language: "javascript"
});
```

* ctrl+hover over `fromCodePoint`.
* this leads to the instantiation of a text model with the contents of some `lib.d.ts` file
* this immediately causes that all base libs are somehow unloaded
