### ISSUE TITLE
unable to remove codelenses

### ISSUE THREAD

**Issue by rwalle** [microsoft/monaco-editor#2189]
**monaco-editor version:** 0.21.2
**Browser:** Firefox, Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:**

Based on the [codelens provider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example), with slight modifications
```js
document.getElementById("container").style = "height: 400px;"; // so that the button can show up

var editor = monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json"
});

var commandId = editor.addCommand(0, function () {
    // services available in `ctx`
    alert('my command is executing!');

}, '');

let p = monaco.languages.registerCodeLensProvider('json', {
    provideCodeLenses: function (model, token) {
        return {
            lenses: [
                {
                    range: {
                        startLineNumber: 1,
                        startColumn: 1,
                        endLineNumber: 2,
                        endColumn: 1
                    },
                    id: "First Line",
                    command: {
                        id: commandId,
                        title: "First Line"
                    }
                }
            ],
            dispose: () => {}
        };
    },
    resolveCodeLens: function (model, codeLens, token) {
        return codeLens;
    }
});

let b = document.createElement('button');
b.innerText = 'remove Lenses';
b.onclick = () => {
    p.dispose();
}

document.getElementById("container").parentNode.appendChild(b);
```

Alternatively, look at this [jsfiddle](https://jsfiddle.net/Lq237oj8/4/)

===

Not sure if this is a bug in the source code, but at least the example code (which is under this repository) does not seem to do its job.

So basically, I was trying to add a "remove code lens" functionality to the editor. When I use the `dispose` method of the `Disposable` and keep the same `provideCodeLens` source code in the example, the code lens commands are disabled, but the texts are still there. If I instead comment out the `dispose: () => {}` function in line 32, the texts do disappear as I would expect, but the browser throws an error
```
Uncaught Error: i.dispose is not a function

TypeError: i.dispose is not a function
```

I am unable to find any documentation or examples that talk about this. I happen to have written an extension for VSCode that would remove codelenses in some cases, but the API is quite different -- For VSCode APIs, there is no `dispose` method of a [`CodeLens`](https://code.visualstudio.com/api/references/vscode-api#CodeLens) object. And when I invoke the `dispose` method on the `Disposable` returned by `registerCodeLensProvider`, all the code lenses just disappear without any issue.

**Comment by christiankaseburg** [comment]
I’m having the same issue. I have a toggle able code lens, and when I turn it off the command is disabled, and the text does not disappear. I would expect for a code lens that got disposed to remove the inline text. Does anyone know how to remove the inline code lens text on dispose?

**Comment by alexdima** [comment]
The `dispose` method on the code lens is supposed to be called by the editor. You can remove code lenses in various ways:
1. update editor options and configure `codeLens: false`.
2. (or) you can implement an `onDidChange` event on your `CodeLensProvider` and emit an event when the code lenses have changed and then, when the editor will request them again, you can return an empty result.
