### ISSUE TITLE
versions 0.21.2 A lot of actions missing

### ISSUE THREAD

**Issue by zerooverture** [microsoft/monaco-editor#2195]
monaco-editor version:  0.21.2
Browser: chrome 85.0.4183.102
OS: windows 10
Playground code that reproduces the issue:
```js
const m = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
console.log(m)
setTimeout(()=>{
    m.trigger('editor','editor.action.selectAll')
    m.trigger('editor','editor.action.clipboardCutAction')
},3000)
```

When I upgraded the project to the new version, I found that many of the actions did not exist, so I went back to version 0.20.0 and everything worked fine.

Please guide me: How does the new version invoke cut, copy, paste, and so on?

**Comment by apisim** [comment]
Similar experience here. These work with 0.20.0 but not with 0.21.2:
```
editor.action.clipboardCopyAction
editor.action.clipboardCutAction
'undo'
'redo'
```
Using the keyboard shortcuts (e.g. Ctrl + Z for 'undo') works, though.

The following actions do work in 0.21.2 for me:
```
editor.action.formatDocument
editor.action.indentLines
editor.action.outdentLines
```

**Comment by zerooverture** [comment]
> Similar experience here. These work in monaco-yaml with 0.20.0 but not with 0.21.2:
> 
> ```
> 
> editor.action.clipboardCopyAction
> 
> editor.action.clipboardCutAction
> 
> 'undo'
> 
> 'redo'
> 
> ```
> 
> Using the keyboard shortcuts (e.g. Ctrl + Z for 'undo') works, though.
> 
> 
> 
> The following actions do work in 0.21.2 for me:
> 
> ```
> 
> editor.action.formatDocument
> 
> editor.action.indentLines
> 
> editor.action.outdentLines
> 
> ```


But I wanted to do that with custom buttons

**Comment by apisim** [comment]
I'm with you, @zerooverture - the command palette buttons with the actions I listed in my comments don't work for me anymore with 0.21.2. I was just providing additional info that the same actions work with keyboard shortcuts.

**Comment by zerooverture** [comment]
> I'm with you, @zerooverture - the command palette buttons with the actions I listed in my comment don't work for me anymore with 0.21.2. I was just providing additional info that the same actions work with keyboard shortcuts.
> 
> 
> 
> 
> 
> 

thx，I'm currently trying to use 'addAction' for this functionality.

**Comment by zerooverture** [comment]
I tried to implement clipboard using `addAction`,But don't know how to implement `undo` && `redo`.

**Comment by zerooverture** [comment]
Attempts have been made to re-add `clipboard`, as well as `undo` and `redo` board features.
```
    monacoEditor.addAction({
      id: 'undo',
      label: 'Undo',
      run: () => {
        monacoEditor?.focus()
        if (!document.execCommand('undo')) {
          monacoEditor.getModel()?.undo()
        }
      },
    })
    monacoEditor.addAction({
      id: 'redo',
      label: 'Redo',
      run: () => {
        monacoEditor?.focus()
        if (!document.execCommand('redo')) {
          monacoEditor.getModel()?.redo()
        }
      },
    })

    monacoEditor.addAction({
      id: 'editor.action.clipboardCutAction',
      label: 'Cut',
      run: () => {
        monacoEditor?.focus()
        document.execCommand('cut')
      },
    })
    monacoEditor.addAction({
      id: 'editor.action.clipboardCopyAction',
      label: 'Copy',
      run: () => {
        monacoEditor?.focus()
        document.execCommand('copy')
      },
    })
    monacoEditor.addAction({
      id: 'editor.action.clipboardPasteAction',
      label: 'Paste',
      run: () => {
        monacoEditor?.focus()
        document.execCommand('paste')
      },
    })
```
