### ISSUE TITLE
Monaco editor conflict

### ISSUE THREAD

**Issue by kerbal** [microsoft/monaco-editor#2197]
Hi there. I need some helps.

I am using monaco editor as an official editor for my new programming language. I publish this as a NPM package. The problem seems to happen when I install and use my editor package (which contains monaco editor) and monaco editor package on my web project (vue) at the same time.

There are two pages where I use monaco editor. I use the editor from my package at page A, and from monaco editor on page B. At page B, I register another language, when I switch to page A, then switch back to page B, my language registered at page B disapear.

Can you help me solve this problem? Thank you very much.

**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Ubuntu

**Comment by alexdima** [comment]
If you believe this is a bug with the monaco editor, please provide reproducible steps in the form of a code sample that executes at https://microsoft.github.io/monaco-editor/playground.html
