### ISSUE TITLE
Duplicated codelens

### ISSUE THREAD

**Issue by kerbal** [microsoft/monaco-editor#2198]
I am developing an language which can embed and run SQL inside. I use codelens to execute the SQL. I register codelens to the editor on the left, the codelens also appear on the editor on the right. I click the codelens on the right, it throws an error message.

![image](https://user-images.githubusercontent.com/33062751/96417384-6b630300-121b-11eb-9bb0-f6fbd154357f.png)

Can you help me solve this? Thank you very much!

**monaco-editor version:** 0.20.0
**Browser:** Chrome
**OS:** Ubuntu

**Comment by alexdima** [comment]
If you believe this is a bug with the monaco editor, please provide reproducible steps, like a code sample that can be executed at https://microsoft.github.io/monaco-editor/playground.html
