### ISSUE TITLE
Folding Glyph hidden on FF

### ISSUE THREAD

**Issue by ptyork** [Microsoft/monaco-editor#22]
The +/- glyph appears not to show up in Firefox v47 (fine in Edge+Chrome). Tracked down to:

.monaco-editor .margin-view-overlays .folding::after {
  z-index: -1;
}

Remove that line (or set z-index to auto) and it shows fine. Not sure what effect that might have on other / older browsers, though.

**Comment by alexandrudima** [comment]
The fix is out with monaco-editor@0.5.1

![image](https://cloud.githubusercontent.com/assets/5047891/16351674/c10b8dee-3a67-11e6-95e8-a8ed3a96df01.png)
