### ISSUE TITLE
Add custom explanation in IntelliSense

### ISSUE THREAD

**Issue by zuznow** [Microsoft/monaco-editor#220]
Hi
We integrated the editor
I added jquery and custom functions via monaco.languages.typescript.javascriptDefaults.addExtraLib
It works great
I want to add explanation to the functions and variables 
How can I add it?
Thanks
Orly

monaco-editor npm version: 0.5.3
Browser: N/A
OS:  N/A

**Comment by alexandrudima** [comment]
Edit the `.d.ts` files you feed to `addExtraLib` and change their jsdoc to improve it.
