### ISSUE TITLE
auto import is not the same path for @types

### ISSUE THREAD

**Issue by fred8617** [microsoft/monaco-editor#2200]
![image](https://user-images.githubusercontent.com/35049517/96566744-8a839280-12f8-11eb-95e8-fbf4d6a05b85.png)

i want to infer import from module "react" not "./node_modules/react/index"

**monaco-editor version:** 0.21.2
**Browser:**
**OS:**
**Playground code that reproduces the issue:**

```js
```

**Comment by fred8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/96566950-c6b6f300-12f8-11eb-8688-366276644fd6.png)

**Comment by alexdima** [comment]
@fred8617 Can you please provide a sample that can be used to reproduce the behavior at https://microsoft.github.io/monaco-editor/playground.html ?
