### ISSUE TITLE
Monarch - simple example with entities & methods

### ISSUE THREAD

**Issue by bsoulier** [microsoft/monaco-editor#2201]
I am trying to build my own language definition.

The very simple example I am trying to build is:

- have set of defined entities to which I assign methods,
- to have those methods to have defined parameters,
- get proper errors when names or entities or methods (including param types) don't match.

I actually want to use Monarch with this custom language definition to validate custom expressions for an app I am building.

Thanks!

**Comment by alexdima** [comment]
Here is relevant documentation -- https://microsoft.github.io/monaco-editor/monarch.html
