### ISSUE TITLE
Cannot read property 'getText' of null at Object.t.getFoldingRanges

### ISSUE THREAD

**Issue by izikl** [microsoft/monaco-editor#2208]
Hey vscode-json-languageservice team, 

A web site I am working on (https://dataexplorer.azure.com/) has few instances of monaco-editor and occasionally I am getting this error: 
```
Error: Cannot read property 'getText' of null TypeError: Cannot read property 'getText' of null at Object.t.getFoldingRanges   
(http://localhost:3000/monaco-editor/min/vs/language/json/jsonWorker.js:7:123135) at e.getFoldingRanges  
(http://localhost:3000/monaco-editor/min/vs/language/json/jsonWorker.js:7:131109) at t.fmr  
(http://localhost:3000/monaco-editor/min/vs/base/worker/workerMain.js#json:159:47) at e._handleMessage  
(http://localhost:3000/monaco-editor/min/vs/base/worker/workerMain.js#json:99:687) at Object.handleMessage  
(http://localhost:3000/monaco-editor/min/vs/base/worker/workerMain.js#json:99:303) at e._handleMessage  
(http://localhost:3000/monaco-editor/min/vs/base/worker/workerMain.js#json:97:170) at e.handleMessage 
(http://localhost:3000/monaco-editor/min/vs/base/worker/workerMain.js#json:96:729) at e.onmessage 
(http://localhost:3000/monaco-editor/min/vs/base/worker/workerMain.js#json:99:382) at self.onmessage 
(http://localhost:3000/monaco-editor/min/vs/base/worker/workerMain.js#json:159:717)
```

I guess it happens because [document is passed as null from monaco-editor which causes document.getText](https://github.com/microsoft/vscode-json-languageservice/blob/2ea5ad3d2ffbbe40dea11cfe764a502becf113ce/src/services/jsonFolding.ts#L14) to throw this error. 

The ask is to add a small check in getFoldingRanges to verify if document is null and if so return an empty list. 

Have you encounter a scenario where monaco-editor was passing a null document? Any ideas when that might happen?

**Comment by aeschli** [comment]
@izikl If you have reproducible steps to get the error, that would be great.

**Comment by RorschachZ** [comment]
I meet this question today when I use monaco-editor with language property valued "json". And the reproducible steps to get the error is still not sure.  What should I do?

**Comment by aeschli** [comment]
@RorschachZ If you can debug it in the dev tools, that would be great. It would be interesting to see what he URI of the document is.
