### ISSUE TITLE
Editor Content Would Overlap on the Right-side Canvas with class decorationsOverviewRuler

### ISSUE THREAD

**Issue by Jing29** [microsoft/monaco-editor#2218]
**monaco-editor version:** 0.18.1
**Browser:** Chrome + Edge
**Playground code that reproduces the issue:**

```js

monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "plaintext",
    minimap: {
        enabled: false
    },
    lineDecorationsWidth: 0
});

```

![image](https://user-images.githubusercontent.com/19400548/99073903-be995d00-25f1-11eb-821b-622cd74c72a0.png)

**Comment by acblacktea** [comment]
I will follow this issue transfer by @Jing29, @alexdima any update for this bug fix? thanks

**Comment by hediet** [comment]
This is by design.
