### ISSUE TITLE
'MonacoEnvironment' was also declared here.

### ISSUE THREAD

**Issue by kmaiya** [microsoft/monaco-editor#2219]
ERROR in node_modules/monaco-editor/monaco.d.ts:11:13 - error TS2451: Cannot redeclare block-scoped variable 'MonacoEnvironment'.

11 declare let MonacoEnvironment: monaco.Environment | undefined;
               ~~~~~~~~~~~~~~~~~

  node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:12:9
    12     let MonacoEnvironment: Environment | undefined;
               ~~~~~~~~~~~~~~~~~
    'MonacoEnvironment' was also declared here.

This error is fairly easily resolved by deleting line 11 from monaco.d.ts

**Comment by alexdima** [comment]
@kmaiya This looks like you are importing the editor both as ESM and as AMD (via globals) at the same time in your project. Can you please provide a reproducible sample?

**Comment by linfanxxxx** [comment]
when I install `monaco-yaml` and `@materia-ui/ngx-monaco-editor` , I have the same problem .


below is error log

`
ERROR in node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:12:9 - error TS2451: Cannot redeclare block-scoped variable 'MonacoEnvironment'.

12     let MonacoEnvironment: Environment | undefined;
           ~~~~~~~~~~~~~~~~~

  node_modules/@materia-ui/ngx-monaco-editor/lib/interfaces/monaco.d.ts:11:13
    11 declare let MonacoEnvironment: monaco.Environment | undefined;
                   ~~~~~~~~~~~~~~~~~
    'MonacoEnvironment' was also declared here.
node_modules/@materia-ui/ngx-monaco-editor/lib/interfaces/monaco.d.ts:11:13 - error TS2451: Cannot redeclare block-scoped variable 'MonacoEnvironment'.

11 declare let MonacoEnvironment: monaco.Environment | undefined;
               ~~~~~~~~~~~~~~~~~

  node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:12:9
    12     let MonacoEnvironment: Environment | undefined;
               ~~~~~~~~~~~~~~~~~
    'MonacoEnvironment' was also declared here.`
