### ISSUE TITLE
Getting 'undefind' error evaluating 'new a.Renderer'

### ISSUE THREAD

**Issue by alwinlubbers** [microsoft/monaco-editor#2221]
I've loaded Monaco inside an iFrame, the scripts are loaded using a custom URL.
I'm using the AMD version with the requirejs library.

While editing, i will randomly get this error:
![Screen Shot 2020-11-15 at 12 49 38](https://user-images.githubusercontent.com/31679714/99184236-ab95a280-2741-11eb-8b7f-8f2f8d794c35.png)

It is most likely appears when Monaco tries to bring up the autocomplete box. (so when typing '` = new`' in JavaScript for example). I'm getting this error on Safari and Chrome.

```javascript
require.config({ paths: { 'vs': 'https://vscode.cdn.servconnect.net/vs' } });

window.MonacoEnvironment = {
    getWorkerUrl: function (workerId, label) {
        return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
        self.MonacoEnvironment = {
          baseUrl: 'https://vscode.cdn.servconnect.net/'
        };
        importScripts('https://vscode.cdn.servconnect.net/vs/base/worker/workerMain.js');`
        )}`;
    }
};

require(["vs/editor/editor.main"], () => {
    monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
        target: monaco.languages.typescript.ScriptTarget.ES6,
        allowNonTsExtensions: true
    });
});
```

I've tried implementing code documentation when Monaco is suggesting code. Which would not work. The documentation (embedded in the `monaco.addExtraLib()`) would not show up at all, neither did my definition document. When i click on 'Go to definition' Monaco says that there is no def. found, even tough it can suggest my `monaco.addExtraLib()` code correctly.

**Comment by alwinlubbers** [comment]
To make the whole `monaco.addExtraLib()` thing more clear; this is what i mean by saying the documentation does not show up. I'm getting the `new a.Renderer` error when Monaco tries to show the documentation.
<img width="779" alt="Screen Shot 2020-11-15 at 13 01 41" src="https://user-images.githubusercontent.com/31679714/99184452-2f03c380-2743-11eb-9b62-490048536220.png">

Also, i've tried my code at Monaco Playground, and it works fine!
<img width="598" alt="Screen Shot 2020-11-15 at 13 04 10" src="https://user-images.githubusercontent.com/31679714/99184449-24e1c500-2743-11eb-8699-f264eb714097.png">

**Comment by alwinlubbers** [comment]
Well, i'm 99.9% certain this has something to do with the marked.js library. Since i had to source that file from the Marked Repo. I can't seem to find the good version because i'm still seeing the `undefined` error. I fixed the Web Worker myself by adding CORS rules.

**Comment by alwinlubbers** [comment]
A couple of days passed, and i still haven't got any clue how i'm supposed to solve this. I'm not familiar with the source code nor TypeScript in general. It's sad, but i'm ready to switch over to another code editor. 

This is how i try to load Monaco:
My webpage loads an iframe and adds the `loader.js` from another domain. Everything works except for the documentation of my API's. It just won't show, and throws an error saying `TypeError: undefined is not an object (evaluating 'new marked.Renderer') at markdownRenderer.ts:84`.

**Comment by mofux** [comment]
Could you provide a minimal example that reproduces the error in the Monaco Playground (https://microsoft.github.io/monaco-editor/playground.html)?

**Comment by alwinlubbers** [comment]
> Could you provide a minimal example that reproduces the error in the Monaco Playground (https://microsoft.github.io/monaco-editor/playground.html)?

I can't. My code works perfectly fine in the Monaco Playground. When i download Monaco from the website (no NPM) and try to initialize it on my website, i get an error saying that it can't find /vs/base/common/marked/marked.js. If i source marked.js myself, it shows the `TypeError: undefined is not an object (evaluating 'new marked.Renderer') at markdownRenderer.ts:84` error.

**Comment by alwinlubbers** [comment]
So, a couple of days have passed. And i just moved to another code editor. I'm sorry, i never found the problem.
