### ISSUE TITLE
[Firefox] Quick fix lightbulb applies fix twice

### ISSUE THREAD

**Issue by StefanRetief** [microsoft/monaco-editor#2223]
Applying a quick fix to code via the light bulb will apply the fix twice. In the example below, the issue in the code is that there is an unused variable. The quickfix will attempt the remove the offending line since it is not necessary. However, when applied, the quick fix will remove the offending line and the line that follows. Only happens in firefox; works perfectly in chrome.

Undoing once will reveal that two actions have occurred rather than just one.

**monaco-editor version:** 0.21.2
**Browser:** Firefox
**OS:** Windows 10
**Playground code that reproduces the issue:**

```js
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "function testFn() {\n    const test = ''\n}",
	language: "typescript"
});

monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
    noSemanticValidation: false,
    noSuggestionDiagnostics: false,
    noSyntaxValidation: false,
})

```

**Comment by StefanRetief** [comment]
I've found that some other commands are also executing twice in firefox. For example, if you were to use  the playground sample for adding an action (https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance), running the 'MyLabel!!!' command will show two alert windows, one after another.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/issues/108621
