### ISSUE TITLE
Use executeEdits to insert value, no trigger history stack

### ISSUE THREAD

**Issue by fulus06** [microsoft/monaco-editor#2225]
**monaco-editor version:** 0.19.3
**Browser:** chrome
**OS:** window 10
**jsfiddle:**
0.8.3 https://jsfiddle.net/g4eLjuq9/22/
0.19.3 https://jsfiddle.net/Lnopw1a7/2/
```js




  editor.executeEdits(null, [{
          range: selection,
          text: `${Math.random()}`,
          forceMoveMarkers: true
        }]);

// ================================

 editor.onDidChangeModelContent(e => {
    let len = editor.getModel()['_commandManager'].past.length
    let len2 = editor.getModel()['_commandManager'].future.length
    console.log('history：', len, len2)
  });
```
![11](https://user-images.githubusercontent.com/12890684/99522304-6d61e280-29d0-11eb-85b1-05a92dcd11fc.gif)

**Comment by alexdima** [comment]
The sample you have linked to uses `monaco-editor@0.8.3`, released in March 2017.
The code sample is also accessing editor internals that change from one version to another.

**Comment by fulus06** [comment]
use 0.19.3
https://jsfiddle.net/Lnopw1a7/2/

![image](https://user-images.githubusercontent.com/12890684/100036524-57727880-2e3b-11eb-84db-0c5b963fe520.png)

**Comment by alexdima** [comment]
The undo/redo stack elements no longer reside in the command manager. They have been pulled out in the `IUndoRedoService`. You can get ahold of that in JS via `editor.getModel()._undoRedoService`. That is shared across all models and their undo/redo elements are grouped in the member `_editStacks`. 

That being said, I have answered this time, but please be aware that using editor internals is not supported and you need to figure things out on your own if you are going to do that. I can only offer to help if you stick to the editor API. Good luck!
