### ISSUE TITLE
Monaco code diff editor: Vertical line separator starts disappearing when scrolling to right in side by side diff view

### ISSUE THREAD

**Issue by harshadsindhav** [microsoft/monaco-editor#2226]
Hi guys,

Hope you all are doing well during this pandemic!

Just observing a bit odd appearance when user scrolls to right in monaco code diff editor, it also removes very first vertical line which also serves as a separator between line number and editor content resulting bit odd look.

Can we handle it to make monaco better and better?

**monaco-editor version:** 0.21.2
**Browser:** any
**OS:**any
**Playground code that reproduces the issue:**
var originalModel = monaco.editor.createModel("{\n\t\"parameters\":\n\t{\n\t\t\"id\":{\n\t\t\t\"widgetId\":{\n\t\t\t\t\"id\":\"10000\"\n\t\t}\n\t}\n\t}\n}", "json");
var modifiedModel = monaco.editor.createModel("{\n\t\"parameters\":\n\t{\n\t\t\"id\":{\n\t\t\t\"widgetId\":{\n\t\t\t\t\"id\":\"10000\"\n\t\t\t}\n\t\t}\n\t}\n}", "json");

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
	// You can optionally disable the resizing
	enableSplitViewResizing: false,

	// Render the diff inline
	renderSideBySide: true
});
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});

![vertical scroll bar appearing without scroll](https://user-images.githubusercontent.com/13543626/99769439-559f7100-2b2c-11eb-8f1e-fd155fb47aa5.jpg)
![vertical scroll bar not appearing on scroll](https://user-images.githubusercontent.com/13543626/99769442-56d09e00-2b2c-11eb-903e-ca209ef1f173.jpg)

```js
```

**Comment by alexdima** [comment]
Hi, that is not a separator. Those are indent guides and they scroll with the content.
