### ISSUE TITLE
Strange behavior for widgets after setting fixedOverflowWidgets: true

### ISSUE THREAD

**Issue by hacker0limbo** [microsoft/monaco-editor#2229]
**monaco-editor version:** 0.21.0
**Browser:** Chrome
**OS:** MacOS
**Playground code that reproduces the issue:**

To fix some layout issue, i just give monaco editor parent container with `overflow: hidden`, and give `fixedOverflowWidgets: true` when setup the monaco editor to try to solve widgets display issue. However my editor behaves strangely for all related widgets. Because of some reason i am not able to show code, the screenshot are listed:

**Before i set `fixedOverflowWidgets: true`**, since i am adding `overflow: hidden`, this behaves normally(widgets get hidden) as expected:
<img width="797" alt="Screen Shot 2020-11-19 at 8 41 30 PM" src="https://user-images.githubusercontent.com/36297538/99937668-3a896700-2da1-11eb-919b-0f002e8a05c4.png">

**After i add `fixedOverflowWidgets: true`** try to solve problems caused by `overflow: hidden`:

<img width="776" alt="Screen Shot 2020-11-23 at 3 32 04 PM" src="https://user-images.githubusercontent.com/36297538/99937734-5d1b8000-2da1-11eb-8d8a-63ac0b068c68.png">

<img width="884" alt="Screen Shot 2020-11-23 at 3 31 31 PM" src="https://user-images.githubusercontent.com/36297538/99937762-6dcbf600-2da1-11eb-8b48-0c9896769df6.png">

Although The suggestion widgets and hover widgets can fully displayed, the are now moving far away from my text input. I have no idea why this happens. Is there any solutions to fix this behavior or is there alternative ways to solve widgets displaying problems when i am setting `overflow: hidden` to the parent element of monaco editor?

Cheers!

**Comment by alexdima** [comment]
@hacker0limbo Can you please provide a sample on how you are instantiating the editor? You can use one of the samples at https://github.com/microsoft/monaco-editor-samples and modify it to illustrate the usage.

**Comment by hacker0limbo** [comment]
@alexdima well i think i solved the problem. Although i am not sure what cause it but now everything works well. Thanks for your comment and this project, gonna close this issue.

**Comment by weizhang-ms** [comment]
@hacker0limbo may I ask how you fixed this? I'm placing monaco-editor inside fluent Callout control and see the same behavior

**Comment by hacker0limbo** [comment]
> @hacker0limbo may I ask how you fixed this? I'm placing monaco-editor inside fluent Callout control and see the same behavior

@weizhang-ms hello, actually i didn't solve it perfectly, what i did was avoid using `fixedOverflowWidgets: true` and conditionally set `overflow: hidden`. It's a little bit complicated to explain this since there is no context and sample code provided. A pseudo code in my project might looks like this

```js
if (conditionA && B && c) {
  // set overflow: hidden 
} else {
  // don't touch this attribute
}
```

It's been a while ago since i encountered this issue, i am not sure if they fix it, and hope this helps. If you still unsure what to do, open a new issue with more details and providing some sample code, they will give you advice immediately.

**Comment by turbozv** [comment]
@hacker0limbo I see, thanks for the info!

I created a new issue with sample repro code: https://github.com/microsoft/monaco-editor/issues/2503
