### ISSUE TITLE
Unable to start the editor as ES module due to invalid CSS import

### ISSUE THREAD

**Issue by jarrodek** [microsoft/monaco-editor#2232]
I am using Monaco inside an ES module. Inside this module after adding the following line:
```javascript
import * as monaco from 'monaco-editor'; 
```
the browser prints a number of errors related to incorrect mime types:
```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.  iPadShowKeyboard.css:1 
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.  inspectTokens.css:1 
....
```

The server used in the back is the `ers-dev-server`. Potentially I could try to write middleware to force the `application/javascript` mime type but it feels like a workaround and it definitely doesn't scale (there are few modules using monaco). I track the issue to the CSS files being directly used as imports. This is an invalid approach as ES does not support that (yet). I believe there's an issue with the ES build of Monaco where CSS files are not properly bundled and distributed. The browser still wants to download them as ES module but the dev server (as it should) returns `text/css` mime type. At this point, I am not even should what would happen if a different mime was returned. These files are not correct JS files so they would throw an error regardless.

This can be reproduced in this repo: https://github.com/advanced-rest-client/body-editor#development

When I first developed this module some month ago it was working as expected. Today, after cloning the repo and installing dependencies everything stopped working. Not really sure why.

**Comment by alexdima** [comment]
Let's track in #886
