### ISSUE TITLE
TextMate grammar not applying correctly to minimap

### ISSUE THREAD

**Issue by bolinfest** [microsoft/monaco-editor#2239]
As of https://github.com/microsoft/monaco-editor/commit/47ffd256b99e4245cc1768a3c0e32fa1648567fc, I seem to have the distinction of being the example for how to leverage TextMate grammars in standalone Monaco. Recently, someone noticed that the colors in the minimap do not match those of the editor when TextMate grammars are used!

I just updated my demo page to enable the minimap for an easier repro:
https://github.com/bolinfest/monaco-tm/commit/256705b1dc4129bd9ed969762f3dfe8168077e97

And yes, this is on `monaco-editor@0.21.2`:
https://github.com/bolinfest/monaco-tm/commit/e213ab514499ad119bd539f43011809aa7dd9902

![Screen Shot 2020-12-01 at 10 27 53 PM](https://user-images.githubusercontent.com/655869/100836665-892fa480-3424-11eb-9e16-2689a9c6a5ac.png)

@alexdima I see that the minimap is a `<canvas>` element, so if you have any pointers at where to start looking to debug this, I'd really appreciate it!

**monaco-editor version:** 0.21.2
**Browser:** Google Chrome Version 87.0.4280.67
**OS:** macOS Catalina

**Comment by bolinfest** [comment]
@alexdima I suspect this code is related?

https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L302-L317

In particular, I see a call to `TokenizationRegistry.setColorMap(colorMap);`, but I think that may not be exposed in the public Monaco API?

**Comment by bolinfest** [comment]
OK, I finally had time to investigate this today and I believe I have The Answer:

- `import {TokenizationRegistry} from 'monaco-editor/esm/vs/editor/common/modes.js';`
- `import {Color} from 'monaco-editor/esm/vs/base/common/color.js';`
- Using the `Registry` from `vscode-textmate`, call `registry.getColorMap()` to get a `string[]` and map that using `Color.Format.CSS.parseHex` to get a `Color[]` for use with both `TokenizationRegistry.setColorMap()` and `generateTokensCSSForColorMap()`

It's a little unfortunate that this requires so much digging into non-public APIs of Monaco, as this solution feels brittle.

**Comment by bolinfest** [comment]
I just landed a fix for this in monaco-tm: https://github.com/bolinfest/monaco-tm/commit/2f39a9947ea22bc1abac12f6697e132acecb8528.

**Comment by alexdima** [comment]
I've pushed https://github.com/microsoft/vscode/commit/67bff68034ce7c5ca6123d5c4703a0d4f6bfae98 which adds `monaco.editor.setColorMap`. Once a new version is out (this or next week), and if you adopt this, you won't have to generate CSS / update `TokenizationRegistry` by yourself.

**Comment by oldrich-svec** [comment]
It seems that `setColorMap` breaks dark mode.

![image](https://user-images.githubusercontent.com/44394662/111430902-5a9bb800-86fb-11eb-8a05-91a556f408a6.png)

Before I used the following to get CSS:

```
function generateTokensCSSForColorMap(colorMap: string[]) {
  const pre = '.monaco-ts .monaco-editor .mtk'
  let rules = []
  for (let i = 2, len = colorMap.length; i < len; i++) {
    let color = colorMap[i]
    rules[i] = `${pre}${i} { color: ${color}; }`
  }
  rules.push(`${pre}i { font-style: italic; }`)
  rules.push(`${pre}b { font-weight: bold; }`)
  const text = `${pre}u { text-decoration: underline; text-underline-position: under; }`
  rules.push(text)
  return rules.join('\n')
}
```

Now, I do:

```
const colorMap = registry.getColorMap()
monaco.languages.setColorMap(colorMap)
```

Any idea, what could go wrong?
