### ISSUE TITLE
I hope that after scrolling to the bottom in the editor area, continuing to scroll can make the body scroll down

### ISSUE THREAD

**Issue by chenmy0917** [microsoft/monaco-editor#2243]
test link: [https://microsoft.github.io/monaco-editor/index.html](https://microsoft.github.io/monaco-editor/index.html)

The feature I want is as shown below:
![image](https://user-images.githubusercontent.com/22138217/101143771-54a13000-3652-11eb-89a7-aa5a9e3a4656.png)

Thank you for viewing and look forward to your reply🥰

**Comment by Pranomvignesh** [comment]
I think onchanging `alwaysConsumeMouseWheel` value to false, You might get what you want.
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorscrollbaroptions.html#alwaysconsumemousewheel

**Comment by chenmy0917** [comment]
> I think on changing `alwaysConsumeMouseWheel` value to false, You might get what you want.
> https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorscrollbaroptions.html#alwaysconsumemousewheel

I tried it without success. My method of use is shown below:

![image](https://user-images.githubusercontent.com/22138217/101158105-2a596d80-3666-11eb-8e02-c654bbee1e21.png)

**Comment by Pranomvignesh** [comment]
Take a look at this comment [here](https://github.com/microsoft/monaco-editor/issues/1853#issuecomment-593484147)

So I guess you have to do it this way,
```javascript
this.diffEditor = monaco.editor.createDiffEditor(
	document.getElementById('diff-editor'), { 
	scrollbar: { 
		alwaysConsumeMouseWheel: false
	} 
});
```

**Comment by chenmy0917** [comment]
> Take a look at this comment [here](https://github.com/microsoft/monaco-editor/issues/1853#issuecomment-593484147)
> 
> So I guess you have to do it this way,
> 
> ```js
> this.diffEditor = monaco.editor.createDiffEditor(
> 	document.getElementById('diff-editor'), { 
> 	scrollbar: { 
> 		alwaysConsumeMouseWheel: false
> 	} 
> });
> ```

Wu~~~ It's work! Thank you very much! 🌹
