### ISSUE TITLE
Programmatically triggering undo or redo doesn't work anymore

### ISSUE THREAD

**Issue by DaanVandenBosch** [microsoft/monaco-editor#2247]
IEditor.trigger('', 'undo', undefined) doesn't work anymore.

**monaco-editor version:** 0.21.0, 0.21.1, 0.21.2
**Browser:** Chrome, Firefox
**OS:** Windows 10
**Playground code that reproduces the issue:**

Editing the code in the editor generated by this code will not be undone even though we trigger undo every 2 seconds. This worked in version 0.20.0 and is broken since 0.21.0.

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

setInterval(() => editor.trigger('', 'undo', undefined), 2000);
```

**Comment by Pranomvignesh** [comment]
I too faced the same issue, Check this [comment](https://github.com/microsoft/monaco-editor/issues/2195#issuecomment-711471692) to get a workaround until this issue gets fixed
