### ISSUE TITLE
Uncaught (in promise) Error: Could not find source file: 'inmemory://model/1'.

### ISSUE THREAD

**Issue by zenboss** [microsoft/monaco-editor#2249]
**monaco-editor version:** current version
**Browser:** Edge
**OS:** macOS
**Playground code that reproduces the issue:**

```js
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({ noLib: true });
// ☝️👆⬆️ 🔼 Monaco-editor occurs an error when I put the above code into configuration.


monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

```
<img width="1593" alt="Screen Shot 2020-12-07 at 3 24 56 PM" src="https://user-images.githubusercontent.com/928027/101302577-d5ee0200-38a0-11eb-99e8-87e39e0b1c1f.png">

**Comment by zenboss** [comment]
Solved!

```js
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
  noLib: true,
  allowNonTsExtensions: true, // 👈 add this line
});
```

**Comment by ssaylo** [comment]
> Solved!
> 
> ```js
> monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
>   noLib: true,
>   allowNonTsExtensions: true, // 👈 add this line
> });
> ```

Just trying to use it, but I don't know why we can solve it by this. Any further information?
