### ISSUE TITLE
how to to run an action

### ISSUE THREAD

**Issue by nmanumr** [microsoft/monaco-editor#225]
as monaco have already too many actions provided in actionbar how can i trigger these action and also the actions that are custom defined.
For example we have an action "Add Cursor Above". I want to trigger is pragmatically and also want to disable action bar means nothing will happen if "F1" is pressed.

**Comment by naumanumer** [comment]
Sorry , I found the answer:
```javascript
editor.getActions() // returns all actions
editor.getAction([id]) // returns action by id
```
But one thing more How to get key binding for example we have following data returned from `getAction` method 
``` javascript
_actual : t
_contextKeyService : t
_editor : t
_instantiationService : t
alias : "Toggle Line Comment"
id : "editor.action.commentLine"
label : "Toggle Line Comment"
__proto__ : e
```
here we have every thing but where is the shortcut key that we define using `keybindings` while defining an action.
