### ISSUE TITLE
Completion items for JSON Schema enum values depend on leading double quote

### ISSUE THREAD

**Issue by infonea** [microsoft/monaco-editor#2251]
monaco-editor version: 0.21.2
Browser: Any
OS: Windows 10

Steps to reproducing the issue:

1. Run the following snippet within the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html)

```javascript
var jsonCode = [
    '{','"p":','}'
].join('\n');
var modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "http://myserver/foo-schema.json", // id of the first schema
        fileMatch: [modelUri.toString()], // associate with our model
        schema: {
            type: "object",
            properties: {
                p: {
                    enum: ["xy","qqqq xy", "(xy)", "qqqq (xy)"]
                }
            }
        }
    }
    ]
});

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```
2. The list of completion items when editing the value of property p depend on a leading double quote

For the full list there is no difference
![Bild1](https://user-images.githubusercontent.com/73350036/101396417-9688db00-38cb-11eb-87f0-0999b34d1b63.png)
![Bild2](https://user-images.githubusercontent.com/73350036/101396452-a0124300-38cb-11eb-8100-2784f966e1b7.png)

For letter "x" without double quotes "(xy)" and "qqqq (xy)" are missing
![Bild3](https://user-images.githubusercontent.com/73350036/101396461-a3a5ca00-38cb-11eb-8316-6b7b14e7d877.png)
![Bild4](https://user-images.githubusercontent.com/73350036/101396470-a6082400-38cb-11eb-9649-6e78134c62bb.png)

But for "(x" the missing items appear
![Bild5](https://user-images.githubusercontent.com/73350036/101396474-a7d1e780-38cb-11eb-87c9-850860cc6112.png)
![Bild6](https://user-images.githubusercontent.com/73350036/101396481-aa344180-38cb-11eb-9bf2-f7f13e3dc310.png)

For letter "y" without double quotes there are no completion items
![Bild7](https://user-images.githubusercontent.com/73350036/101396486-ad2f3200-38cb-11eb-95b6-637c9aa88cd4.png)
![Bild8](https://user-images.githubusercontent.com/73350036/101396495-af918c00-38cb-11eb-93f1-d4c8578e0e63.png)

**Comment by aeschli** [comment]
That's related to the filtering that is done in the suggest widget.

**Comment by jrieken** [comment]
> That's related to the filtering that is done in the suggest widget.

@aeschli I don't know how you came to that conclusion. 

@infonea  I don't see anything suggest related here. Please provide repro steps for VSCode, using a vscode extension sample

**Comment by infonea** [comment]
VSCode shows exactly the same behavior. 

Save the following schema as "enum-schema.json":

{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "p": {
            "enum": ["xy","qqqq xy", "(xy)", "qqqq (xy)"]
        }        
    }
}

Save a json file with the following content in the same directory:
{
    "$schema": "./enum-schema.json",
    "p": ""
}

The list of completion items for the property value of p is exactly the same as in Monaco.

VSCode Version used:

Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by aeschli** [comment]
> @aeschli I don't know how you came to that conclusion.

I verified that the JSON completion provider returns 4 proposals for all the examples above. The replace-range covers the full property value.

**Comment by infonea** [comment]
I checked the examples in the current playground (0.31,1) again. The examples with "x" now work as expected but the ones with "y" still behave different:

Type {"p": and than open the completions drop down with Strg+Space
- typing x shows the 4 proposals with the x highlighted
- typing y shows the 4 proposals but the y is not highlighted

Further more

- if I paste {"p":x and than press Strg+Space I get 4 proposals with the x highlighted
- if I paste {"p":y and than press Strg+Space I still get "No suggestions"
