### ISSUE TITLE
Converting a CommonJS module to ES6 module via QuickFix generates invalid code in Firefox

### ISSUE THREAD

**Issue by Udith** [microsoft/monaco-editor#2257]
**monaco-editor version:** 0.21.2
**Browser:** Firefox (83.0)
**OS:** MacOS, Windows

If a CommonJS module such as below is converted to an ES6 module using the QuickFix feature, it generates invalid code on Firefox browser. But works correctly on Google Chrome.
```
exports.foo = async (e) => {
   // Some code
}
```
This is how it is converted to invalid code on Firefox
![es6_convert_firefox](https://user-images.githubusercontent.com/1328634/101736499-83ebed00-3ae9-11eb-8016-b27f5c9df924.gif)

This is how it works correctly on Google Chrome
![es6_convert_chrome](https://user-images.githubusercontent.com/1328634/101736484-7cc4df00-3ae9-11eb-97f8-1ddcca0f64c2.gif)

**Comment by alexdima** [comment]
@Udith I could not reproduce with the following snippet at https://microsoft.github.io/monaco-editor/playground.html:

```js
monaco.editor.create(document.getElementById("container"), {
	value: `exports.foo = async (e) => {\n   // Some code\n}`,
	language: "javascript"
});
```

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/106204150-cdd58300-61bc-11eb-976a-581bbd50d18e.gif)

**Comment by Udith** [comment]
@alexdima Thanks for looking into this. I experienced this issue on `0.21.2` version. But now the playground is running on `0.22.1` version and the issue is no longer reproducible. So I guess it has been fixed in this newer version.
