### ISSUE TITLE
require `vs/editor/contrib/quickOpen/quickOpen` stops wokring after `v0.21.0`

### ISSUE THREAD

**Issue by JounQin** [microsoft/monaco-editor#2259]
![image](https://user-images.githubusercontent.com/8336744/101862418-4781c500-3bad-11eb-9a2e-c80ef5833f4b.png)

**monaco-editor version:** 0.21.2
**Browser:** Chrome 87.0.4280.88
**OS:** macOS
**Playground code that reproduces the issue:**

```js
require(['vs/editor/contrib/quickOpen/quickOpen', 'vs/editor/contrib/hover/getHover'])
```

**Comment by alexdima** [comment]
Yes, it looks like it was removed from the vscode sources. When you use editor internals, you need to figure things out on your own. Good luck!
