### ISSUE TITLE
Java language service

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/monaco-editor#226]
hi, I wrote a java to typescript and java to JavaScript compiler that runs natively in browser, using pegjs and my custom parser. Now I would like to add the language support to Monaco editor, such as intellisense, go to definition and class structure. I saw some bit on how this can be done in vs code, but how can I natively add this in browser?

**Comment by alexandrudima** [comment]
@tomitrescak You can register rich language features providers via the methods under `monaco.languages`. Here are some examples of how you can register supports for a language:

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

You would need to register such a completion item provider for 'java' and then implement it by calling into your compiler / parser. I would also recommend that you do this in a web worker with the help of `monaco.editor.createWebWorker`. You can use as a reference the way javascript or typescript providers are implemented in `monaco-typescript`: https://github.com/Microsoft/monaco-typescript/tree/master/src
