### ISSUE TITLE
Formatting breaks on self-closing tags (e.g. <br />)

### ISSUE THREAD

**Issue by msklvsk** [microsoft/monaco-editor#2266]
**monaco-editor version:** 0.21.2
**Browser:** Chrome 87.0.4280.88
**OS:** macOS 10.15.7
**Playground code that reproduces the issue:**

```html
<div>line<br />
		    </div>
```

**repro:** copypaste the snippet and format the code
**actual:** nothing happens
**expected:** the code gets formatted as follows:
```html
<div>line<br />
</div>
```

**Comment by aeschli** [comment]
It's fixed with the latest vscode-html-languageservice.

**Comment by aeschli** [comment]
Marking as fixd
