### ISSUE TITLE
html format error

### ISSUE THREAD

**Issue by sinbo520** [Microsoft/monaco-editor#227]
monaco-editor npm version: 0.7.3
Browser: chrome 53
OS: macOS
![image](https://cloud.githubusercontent.com/assets/3760086/19211596/e0c8b4be-8d72-11e6-89a5-1d3b6eaf115c.png)

**Comment by alexandrudima** [comment]
This has already been fixed in `monaco-html` and the fix will be included with the v0.8.x release
