### ISSUE TITLE
Add intellisense for yaml

### ISSUE THREAD

**Issue by joebnb** [microsoft/monaco-editor#2273]
**monaco-editor version:** 0.21.2
**Browser:** chrome
**OS:** macos big sur
**Playground code that reproduces the issue:**
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

change lang `json` to `yaml` ,code suggest will not working

maybe some configuration wrong,like worker etc. ,could show some example.

#2077 
#1768 

this is my worker configuration
```js
 getWorkerUrl: function (moduleId, label) {
            if (label === "json") {
                return "./worker-json.js";
            }
            if (label === "css") {
                return "./worker-css.js";
            }
            if (label === 'html') {
                return './worker-html.js';
            }
            if (label === 'typescript' || label === 'javascript') {
                return './worker-javascript.js';
            }
           
            return "./worker-editor.js";
        },
```

**Comment by alexdima** [comment]
This works fine for me:

* open https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
* change `json` to `yaml` in the provider registration
* change `json` to `yaml` in the editor language

![image](https://user-images.githubusercontent.com/5047891/103306627-4d313480-4a0e-11eb-85f6-c6ba4d0fa3ac.png)

**Comment by joebnb** [comment]
> This works fine for me:
> 
> * open https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
> * change `json` to `yaml` in the provider registration
> * change `json` to `yaml` in the editor language
> 
> ![image](https://user-images.githubusercontent.com/5047891/103306627-4d313480-4a0e-11eb-85f6-c6ba4d0fa3ac.png)

working in json
![image](https://user-images.githubusercontent.com/1646883/103598575-e9db6100-4f3d-11eb-9cc8-051f7e4d6484.png)

yaml still not working

![image](https://user-images.githubusercontent.com/1646883/103598615-05df0280-4f3e-11eb-8fd7-5e687e5dff58.png)

chrome(Version 87.0.4280.88 (Official Build) (x86_64)) on macos bigsur 11.1

**Comment by alexdima** [comment]
I tried on chrome + big sur and it works for me:


https://user-images.githubusercontent.com/5047891/105859859-4685e500-5fed-11eb-9722-0f5c9b476bff.mp4

**Comment by zhaofinger** [comment]
> I tried on chrome + big sur and it works for me:
> 
>  Kapture.2021-01-26.at.15.43.18.mp4

This is the video of my operation. @alexdima 

https://user-images.githubusercontent.com/31442077/105931775-c6ac5900-6086-11eb-83a8-691a4966863d.mov

**Comment by joebnb** [comment]
now work with me,chrome 88 + big sur 11.1

![2021-01-27 14-04-14 2021-01-27 14_06_17](https://user-images.githubusercontent.com/1646883/105950224-fa987600-60a8-11eb-8013-8e110f7e7d1b.gif)

**Comment by spahnke** [comment]
Changing `json` to `yaml` works for me but the difference is that the suggest widget opens automatically when typing `lo` in `json` but it does not in `yaml`. In `yaml` you have to manually trigger it by using `Ctrl+Space`. Is this where the confusion comes from?

**Comment by alexdima** [comment]
> In yaml you have to manually trigger it by using Ctrl+Space. Is this where the confusion comes from?

Oh I see. Sorry I misunderstood.

**Comment by aeschli** [comment]
@alexdima Debugging the example above I see that with json it's a 'other' token, while in yaml a string token.
The editor doesn't show quick suggestions when in a string token.

**Comment by rcjsuen** [comment]
> @alexdima Debugging the example above I see that with json it's a 'other' token, while in yaml a string token.
> The editor doesn't show quick suggestions when in a string token.

Interesting. This reminds me of https://github.com/microsoft/monaco-editor/issues/1935 and https://github.com/microsoft/vscode/issues/95924.

**Comment by alexdima** [comment]
Thanks for figuring this out @aeschli . I think the solution is to configure the editor with `quickSuggestions: { other: true, strings: true }`.
