### ISSUE TITLE
typeRoots does not work as expected?

### ISSUE THREAD

**Issue by tuebben** [microsoft/monaco-editor#2274]
Hi,

Please forgive my ignorance, but isn't **typeRoots** for loading d.ts declarations automatically?

If so, then it does not work as I expect it to.

This is my code:

```
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		<link
			rel="stylesheet"
			data-name="vs/editor/editor.main"
			href="node_modules/monaco-editor/min/vs/editor/editor.main.css"
		/>
	</head>
	<body>
		<div id="container" style="width: 800px; height: 600px; border: 1px solid grey"></div>
		<script>
			var require = { paths: { vs: './node_modules/monaco-editor/min/vs' } };
		</script>
		<script src="./node_modules/monaco-editor/min/vs/loader.js"></script>
		<script src="./node_modules/monaco-editor/min/vs/editor/editor.main.nls.js"></script>
		<script src="./node_modules/monaco-editor/min/vs/editor/editor.main.js"></script>
		<script>
			monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
				allowNonTsExtensions: true,
				typeRoots: ['./node_modules/@types']
			});
			var editor = monaco.editor.create(document.getElementById('container'), {
				value: ['var t:Tabulator;'].join('\n'),
				language: 'typescript'
			});
		</script>
	</body>
</html>
```

Although the @types folder contains the declaration for tabulator-tables (".\node_modules\\@types\tabulator-tables\index.d.ts"), the Monaco editor displays `var t:Tabulator` as incorrect:

![image](https://user-images.githubusercontent.com/6094731/102634723-8803b480-4152-11eb-89a1-3755dc54a570.png)

When I open the folder with VSC, Tabulator is recognized correctly:

![image](https://user-images.githubusercontent.com/6094731/102636022-6acfe580-4154-11eb-8afe-1657ea6d8134.png)

Thanks in advance & Greetings ... Peter

**Comment by alexdima** [comment]
AFAIK supporting `typeRoots` means that the node module lookup algorithm must be implemented. AFAIK this cannot be implemented in a web browser because it needs complete `fs` access.

**Comment by tuebben** [comment]
@alexdima : Thank you for the explanation. Now I know at least that I have not made a mistake. 

Greetings ... Peter

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
