### ISSUE TITLE
Keys added after Object creation are not present in suggestion - javascript

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2278]
**monaco-editor version:** 0.21.2
**Browser: Chrome**
**OS: Mac OS**
**Playground code that reproduces the issue:**

```js
var someObject = {
	key1 : {
		subkey1 : 'value_1'
	},
	key2 : 'value_2'
}
someObject.key3 = {
	subkey3 : 'value_3'
}

```

<img width="833" alt="Screen Shot 2020-12-21 at 1 53 02 PM" src="https://user-images.githubusercontent.com/29809906/102755320-3c404d80-4394-11eb-9c65-e2280edefd54.png">

In the image, the `key3` is not present in the suggestions as a `property`, It is only present in the suggestions as a matching literal. 
Please update me, is there any configuration that I have to do to achieve this ?

**Comment by Pranomvignesh** [comment]
## Update on issue 
### I think the way in which we declare the object matters for suggestions of its keys

1. When an empty object is given for initialization and then if the value of the object is resetted, the complete reset to the object is omitted and only the partial change is getting reflected in the suggestions
<img width="845" alt="Screen Shot 2020-12-21 at 8 35 48 PM" src="https://user-images.githubusercontent.com/29809906/102791038-69a8ed80-43cc-11eb-8bdc-cf2c234085ff.png">

---
2. When an empty object is given for initialization and all its keys are declared individually, the suggestion seems to work perfectly fine
<img width="832" alt="Screen Shot 2020-12-21 at 8 36 37 PM" src="https://user-images.githubusercontent.com/29809906/102791049-6f063800-43cc-11eb-9fbf-2de41612cd3f.png">

I request monaco-editor / vscode team to fix this issue

**Comment by alexdima** [comment]
The intellisense in the monaco editor for JavaScript is computed by the TypeScript compiler. So I suggest we track this at https://github.com/microsoft/TypeScript/issues/42071
