### ISSUE TITLE
Monaco Editor appears broken (console errors, failed load) with 0.7.0 update

### ISSUE THREAD

**Issue by Zlatkovsky** [Microsoft/monaco-editor#228]
On updating from 0.6.1 to 0.7.0, get issues on IE 11 (but not Chrome or Edge).  See image below.

![image](https://cloud.githubusercontent.com/assets/2230453/19221499/7de5b892-8df9-11e6-9707-ccb9e443f46e.png)

monaco-editor npm version: 0.7.0
Browser: IE 11
OS: Windows 10

**Comment by alexandrudima** [comment]
@Zlatkovsky Is it possible you were running into some caching issues?

**Comment by Zlatkovsky** [comment]
Doesn't repro anymore.  Closing.
