### ISSUE TITLE
Event handler when changing tabSize / indentSize?

### ISSUE THREAD

**Issue by hacker0limbo** [microsoft/monaco-editor#2280]
I am wondering if there exists an event handler when changing the editor's `tabSize` / `indentSize`, something like `onDidChangeTabSize` or `onDidChangeIndentSize`?

For example, when i open the command palette and choose `indent using tabs` command, it then allows me to change tabSize for current editor.

![Screen Shot 2020-12-22 at 3 38 50 PM](https://user-images.githubusercontent.com/36297538/102862712-78df7800-446c-11eb-8bf1-3d819f8d25a7.png)

However, there is no related **event handler API** for me to triggered when i **select** a tab size, it might looks like this:

```javascript
editor.onDidChangeTabSize(event => {
  console.log(editor.getModel().getOptions().tabSize) // latest tabSize
  console.log(event.tabSize) // get latest tabSize from event
})
```

I might missing some API from docs, not sure if there actually exists any way to do this?

**Comment by alexdima** [comment]
The indentation settings for a particular file are stored on the text model instance. So the text model object emits that event:
e.g.
```
editor.getModel().onDidChangeOptions((e) => console.log(e))
```
