### ISSUE TITLE
Error: Can only have one anonymous define call per script file

### ISSUE THREAD

**Issue by stagefright5** [microsoft/monaco-editor#2283]
Dynamically requiring the `strong-soap` module causes this error. [Please read on].

This happens when I try to dynamically import `strong-soap` module and  the `monaco-editor` is included.
If any other module is dynamically required or if the monaco-editor component is not included.

The steps to reproduce is mention in this [repo's](https://github.com/stagefright5/strong-soap-dynamic-module-load-issue) README.md file
I have raised the issue in `strong-soap` repo too ([here](https://github.com/strongloop/strong-soap/issues/304)). Any help is appreciated.

**monaco-editor version:** 0.20.0
**Browser:** Electron v9
**OS:** Any
**Playground code that reproduces the issue:** https://github.com/stagefright5/strong-soap-dynamic-module-load-issue#strong-soap-dynamic-module-load-issue  
**Related issue:**  https://github.com/strongloop/strong-soap/issues/304

![error](https://user-images.githubusercontent.com/15051871/103040929-e8ec1c00-459a-11eb-9a8c-92e2a0ab9a09.jpeg)

**Comment by alexdima** [comment]
This usually indicates that a script which was not loaded via the AMD loader invokes `define`. If the script you are trying to load is authored with UMD (probes for existance of `define` and then invokes it), you can do the following:
- ensure that the script is loaded before `loader.js`
- (or) undefine `global.define` before loading the script and redefine it after the script has finished loading
- (or) give up on using AMD and use the ESM variant of the monaco editor
