### ISSUE TITLE
Why monaco-editor doesn't work well in electron? 

### ISSUE THREAD

**Issue by Fangrengehua** [microsoft/monaco-editor#2285]
I'm trying to get monaco-editor to work with react and electron, I get the following error in console when I set language to javascript (the web worker that needed is loaded successfully):
`errors.js:12 Uncaught Error: Unexpected usage

Error: Unexpected usage
at EditorSimpleWorker.loadForeignModule (http://localhost:3000/static/js/2.chunk.js:103397:27)
at _foreignProxy._getProxy.then.proxy (http://localhost:3000/static/js/2.chunk.js:106231:22)setTimeout @ errors.js:12`

And when I set language to html, json, there's no error in console. Also i've tried to make monaco-editor work without react, I also get the same error.

**Comment by alexdima** [comment]
Please take a look at the ESM integration guide: https://github.com/microsoft/monaco-editor/blob/master/docs/integrate-esm.md . You can use the `monaco-editor-webpack-plugin` or you can use a webpack config directly, but you need to define `self.MonacoEnvironment.getWorkerUrl` to let the editor know to what files you have bundled the web workers.

**Comment by Fangrengehua** [comment]
```
errors.js:22 Uncaught Error: Unexpected usage
Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (webpack:///../node_modules/_monaco-editor@0.21.2@monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js?:475:31)
    at _foreignProxy._getProxy.then (webpack:///../node_modules/_monaco-editor@0.21.2@monaco-editor/esm/vs/editor/common/services/webWorker.js?:42:30)setTimeout @ errors.js:22
6index.js:322 Uncaught ReferenceError: isWebpackCompileError is not definedhandleRuntimeError @ index.js:322handleError @ ErrorOverlayEntry.js:80errorHandler @ errorEventHandlers.js:23
```
I'm sure i've used the `monaco-editor-webpack-plugin` correctly, but i still got the error in my react-electron project. What confused me is that everything goes well in browser, i only get the error when i set language to javascript and typescript in electron. I also have tried to use the _browser-esm-webpack-typescript-react_ example you provided in electron, but the error still exists.
Here is the console in browser and electron:
browser:
![console_in_browser](https://user-images.githubusercontent.com/52040232/103327351-26671280-4a8f-11eb-8315-b8fef3f3fd49.png)
electron:
![console_in_electron](https://user-images.githubusercontent.com/52040232/103327359-2ebf4d80-4a8f-11eb-8a7d-0d7f14630226.png)

**Comment by alexdima** [comment]
@Fangrengehua I have just created another sample, which shows electron + ESM + webpack: https://github.com/microsoft/monaco-editor-samples/tree/master/electron-esm-webpack

![image](https://user-images.githubusercontent.com/5047891/103341218-94f3a280-4a86-11eb-8ca1-edee461d63e3.png)
