### ISSUE TITLE
fix Missing Import bug

### ISSUE THREAD

**Issue by McvCar** [microsoft/monaco-editor#2286]
1. Try to reproduce in VS Code and file issue directly at:
![屏幕快照 2020-12-26 上午1 42 34](https://user-images.githubusercontent.com/66513806/103140080-588a1480-471d-11eb-9f3e-68c8d6ae0ba1.png)

This code makes the relative path generated by the fix Missing Import for the size sensitive file path much longer

![屏幕快照 2020-12-26 上午2 03 14](https://user-images.githubusercontent.com/66513806/103140195-d7cc1800-471e-11eb-8670-8832fe76c8c2.png)

**monaco-editor version: 0.21.2
**Browser: Google
**OS:** Mac
**Playground code that reproduces the issue:**

```js
```

**Comment by alexdima** [comment]
@McvCar Do you have any steps? It looks like you have taken screenshots from a portion of code from the typescript services, but other than that I don't know from the screenshots what could be wrong, especially given that the code belongs to the TypeScript compiler.
