### ISSUE TITLE
Text Alignment of Monaco editor messing up

### ISSUE THREAD

**Issue by Woundrite** [microsoft/monaco-editor#2289]
I am making an code editor... so I decided to use Monaco as... well it is pretty obvious so as to why one would like to use Monaco in their editor... but it messes up the text alignment in the editor... the source code is at https://github.com/Woundrite/Scarlet if you would like to look at it...
![image](https://user-images.githubusercontent.com/46297894/103278101-a8542e80-49f0-11eb-9cb0-a98e8a7f4686.png)
any ideas on how to fix this..?

**Comment by alexdima** [comment]
Your CSS is selecting dom nodes of the editor. You need to make sure your css only targets the dom nodes you create. e.g.

![image](https://user-images.githubusercontent.com/5047891/103288244-c0be4c00-49e4-11eb-90e7-716e98fc4987.png)
