### ISSUE TITLE
How to disable signature help and other things on focus lost

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/monaco-editor#229]
Reproduce :
- go to https://microsoft.github.io/monaco-editor/playground.html
- trigger signature help in one of the editors
- focus the other editor

The signature pop up will be kept open. Interestingly this is not true for suggestions.

I would like to close all pop ups and ideally even remove any selections (parenthesis matching, mark occurences, etc.) when I leave the editor. 
Is that possible? How?

**Comment by alexandrudima** [comment]
you could listen to the blur event:

```
ed.onDidBlurEditor(() => {
  ed.setPosition({lineNumber:1, column:1})
});
```

**Comment by svenefftinge** [comment]
Thank you, that's exactly what I did. 
It works somehow, but you need to reset the old position on focus again (possibly overwriting any positions that have been set in the meantime.
