### ISSUE TITLE
Serializing folding ranges state

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#2293]
I'd be useful to be able to serialize and deserialize which folding ranges are currently expanded/collapsed.

**Comment by alexdima** [comment]
AFAIK this is already saved via `editor.saveViewState()` / `editor.restoreViewState()` e.g. --https://github.com/microsoft/vscode/blob/d21d85a3fc2685de8632b32e27985d710384cb6a/src/vs/editor/contrib/folding/folding.ts#L143
