### ISSUE TITLE
Models with "@" in their name do not resolve as dependencies

### ISSUE THREAD

**Issue by lukasbach** [microsoft/monaco-editor#2295]
The following code examples can be copied into https://microsoft.github.io/monaco-editor/playground.html for verification.

I'm trying to specify dependencies manually via ``monaco.editor.createModel()``, which works fine for dependency outside of organizations, but if a package is defined within a organization, i.e. has a name like ``@org/packagename`` and thus contains a @-character, it breaks. To me it looks like this is due to Monaco changing the @-character to ``%40``.

The following code (which does not contain @) works fine:

```js
monaco.editor.create(document.getElementById("container"), {
    model: monaco.editor.createModel(
        "import * as t from 'test';\nt.X.toExponential();\nt.Y; // Error", 
        "typescript",
        monaco.Uri.parse("file://root/test.ts")
    )
});

monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
  ...monaco.languages.typescript.typescriptDefaults.getCompilerOptions(),
  moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs
});

monaco.editor.createModel(
    JSON.stringify({
        name: "test", version: "1.0.0",
        typings: "./lib/index.d.ts"
    }), 
    "typescript",
    monaco.Uri.parse("file://root/node_modules/test/package.json")
);

monaco.editor.createModel(
    "export const X = 1;", 
    "typescript",
    monaco.Uri.parse("file://root/node_modules/test/lib/index.d.ts")
);

console.log(
    "Works:",
    monaco.editor.getModel("file://root/node_modules/test/lib/index.d.ts").uri.toString()
);
```

However, on this code (containing a @) it breaks;

```js
monaco.editor.create(document.getElementById("container"), {
    model: monaco.editor.createModel(
        "import * as t from '@org/test';\nt.X.toExponential();\nt.Y; // Error", 
        "typescript",
        monaco.Uri.parse("file://root/test.ts")
    )
});

monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
  ...monaco.languages.typescript.typescriptDefaults.getCompilerOptions(),
  moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs
});

monaco.editor.createModel(
    JSON.stringify({
        name: "@org/test", version: "1.0.0",
        typings: "./lib/index.d.ts"
    }), 
    "typescript",
    monaco.Uri.parse("file://root/node_modules/@org/test/package.json")
);

monaco.editor.createModel(
    "export const X = 1;", 
    "typescript",
    monaco.Uri.parse("file://root/node_modules/@org/test/lib/index.d.ts")
);

console.log(
    "Does not work, but should:",
    monaco.editor.getModel("file://root/node_modules/@org/test/lib/index.d.ts")?.uri.toString()
);

console.log(
    "Does work, but doesnt help:",
    monaco.editor.getModel("file://root/node_modules/%40org/test/lib/index.d.ts").uri.toString()
);
```

**monaco-editor version:** 0.21.2
**Browser:** Chrome
**OS:** Windows 10

Is this an issue with Monaco or with my approach? Is there a workaround for this problem? Let me know if you need more details.

**Comment by zerdos** [comment]
try to add them whithout the /lib/ subdir, so your index.d.ts whill work here:
file://root/node_modules/@org/test/index.d.ts

**Comment by zerdos** [comment]
also, I think, it should be 
```file:///...```
instad of 
```file://```

**Comment by lukasbach** [comment]
Hi @zerdos, thanks for your response and suggestions! Unfortunately, they did not work in the playground for me, I still get the same issue. As I've mentioned before, I suspect the issue lies somewhere around the fact that monaco changes the @-character to ``%40`` when making the path accessible, which I am unsure on how to work around and why that happens in the first place.

**Comment by ErkoKnoll** [comment]
I once had a similar issue. I can't find the original issue but the way to make scope packages to work is to remove `@` from the path and replace first `/` with `__`. Following code should fix your paths:
```
const fixedName = name.startsWith('@') ? name.slice(1).replace('/', '__') : name
```

And the full file path should be: `file:///node_modules/@types/${fixedName}`

**Comment by nissoh** [comment]
> I once had a similar issue. I can't find the original issue but the way to make scope packages to work is to remove `@` from the path and replace first `/` with `__`. Following code should fix your paths:
> 
> ```
> const fixedPackageName = name.startsWith('@') ? name.slice(1).replace('/', '__') : name
> ```
> 
> And the full file path should be: `file:///node_modules/@types/${fixedPackageName}/...`

@ErkoKnoll i believe this might work using `addExtraLib` but will fail with `editor.createModel`

**Comment by SamVerschueren** [comment]
The problem here is that if you don't add it to your models, you will not be able to peek the definition. So for that, you need to add it to both the extra lib and the model.

So after debugging this issue for half a day and trying to come up with a solution, which I didn't, I found out that the problem can basically be tracked down to this method.

![image](https://user-images.githubusercontent.com/1913805/123622700-d6ce8d00-d80c-11eb-92b4-c7e113a6097c.png)

So it tries to remove the `@types` prefix, which it fails to do here because the `@` is encoded. I then tried to modify that code so it also strips off `%40types/`, but then I ended up with two suggestions.

![image](https://user-images.githubusercontent.com/1913805/123623689-0b8f1400-d80e-11eb-8f0e-3999c6d5b2c1.png)

So I basically gave up on this and instead I do not add the `@types` type definitions to the models. So peek definition and what not works for all unscoped packages but not for scoped packages unfortunately.

**Comment by lstkz** [comment]
I am also having this issue.
code
```ts
  editor.createModel(
      source,
      'typescript',
      this.monaco.Uri.parse(`file:///node_modules/@reduxjs/toolkit/index.d.ts`)
    )
```

```ts
// this works
import { createSlice } from '%40reduxjs/toolkit';

// this gives an error
import { createSlice } from '@reduxjs/toolkit';
```

It's a big deal for me because code written in my editor won't be the same as code written in native VSCode.

**Comment by lstkz** [comment]
A full example that can be pasted in https://microsoft.github.io/monaco-editor/playground.html

```ts
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.Latest,
    allowNonTsExtensions: true,
    moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
    module: monaco.languages.typescript.ModuleKind.ESNext,
    noEmit: true,
    esModuleInterop: true,
    strict: true,
    jsx: monaco.languages.typescript.JsxEmit.React,
    reactNamespace: 'React',
    allowJs: true,
    isolatedModules: true, 
})

monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true);

const instance = monaco.editor.create(document.getElementById("container"), {
    language: 'typescript', 
    model: null,   
});

monaco.editor.createModel(
    'export const foo = {bar: 123};',
    'typescript',
    this.monaco.Uri.parse(`file:///node_modules/@reduxjs/toolkit/index.d.ts`)
)


const model = monaco.editor.createModel(
    `import {foo} from "@reduxjs/toolkit"

console.log(foo.bar);
`,
    'typescript',
    this.monaco.Uri.parse(`file:///index.ts`)
)

instance.setModel(model)

```

![image](https://user-images.githubusercontent.com/4478684/132701489-78f02e2d-1638-486f-ab78-2db1e126d1c7.png)

Changing `@ -> %40` works

![image](https://user-images.githubusercontent.com/4478684/132701576-f93bed6f-dd54-4e38-bca6-9f9d5ea6022c.png)


cc @orta

**Comment by dameemshahabaz** [comment]
Any update on this? I also have the same issue

**Comment by bsorrentino** [comment]
Hi

I've worked trying to understand the problem and finally I found out.

I've submitted PR #3057
