### ISSUE TITLE
Intellisense of variables

### ISSUE THREAD

**Issue by cwoolumtechnossus** [Microsoft/monaco-editor#23]
Is it possible to have intellisense for child properties of variables? I have a few select C# models that I want to use in the editor and intellisense for all the properties is necessary for the functionality I am looking to implement.

**Comment by alexandrudima** [comment]
@cwoolumtechnossus We do not ship any intellisense provider for c# with the editor, but if you have a backend where you use maybe Roslyn or something, you can easily hook that into the editor via `monaco.languages.registerCompletionItemProvider`.

You can find an example at https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages or an async one for hover at https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example

**Comment by jpsfs** [comment]
@alexandrudima Can you please point to an example with Roslyn integration?

It would be very cool to have a C# editor, embedded in a web application, that is aware of custom C# classes that I have available on the back-end.

**Comment by alexandrudima** [comment]
Sorry, you would need to find Roslyn specific documentation on that. 

From the editor point of view, the idea is that you can hook into all the right places (register yourself as a *Provider) and then you get called by the editor when the user wants suggestions, for example. Then, you would need to do an XHR call to your backend where you can have Roslyn running and analyzing the source and which can then reply with relevant suggestions.

I can help you on the editor side, and that basically consists of you registering as a completion item provider for example `monaco.languages.registerCompletionItemProvider`. The object you pass in must have the right provider shape and a method called `provideCompletionItems` will be called on it. It is up to you how you come up with those completions.
