### ISSUE TITLE
'invalid marker service state' on `monaco.editor.setModelMarkers`

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#230]
See the attachment, `MapMap.remove` seems to be inconsistent.
<img width="1435" alt="screen shot 2016-10-10 at 18 29 16" src="https://cloud.githubusercontent.com/assets/3082655/19243343/93743066-8f17-11e6-9324-0afff5345d6e.png">

**Comment by akosyakov** [comment]
Seems to be a dup of https://github.com/Microsoft/vscode/issues/13548.

**Comment by alexandrudima** [comment]
I'm not sure of the severity of this issue -- do we need to ship a new version of the editor? (@jrieken)

**Comment by akosyakov** [comment]
@alexandrudima in our case the console is full of such errors

**Comment by JKillian** [comment]
This is affecting me as well, a 7.0.1 release would be fantastic

**Comment by alexandrudima** [comment]
The fix will come out with 0.8.x
