### ISSUE TITLE
Can't scroll on the scrollable dom that as zone add to editor

### ISSUE THREAD

**Issue by chenmy0917** [microsoft/monaco-editor#2308]
**monaco-editor version:** v0.21.2
**Browser:** Google Chrome v87.0.4280.141(x86_64)
**OS:** macOS
**Playground code that reproduces the issue:**

```js
var originalModel = monaco.editor.createModel("This line is removed on the right.\njust some text\nabcd\nefgh\nSome more text", "text/plain");
var modifiedModel = monaco.editor.createModel("just some text\nabcz\nzzzzefgh\nSome more text\nThis line is removed on the left.", "text/plain");

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
	// You can optionally disable the resizing
	enableSplitViewResizing: false,

	// Render the diff inline
	renderSideBySide: false
});
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});
var modifiedEditor = diffEditor.getModifiedEditor();
var div = document.createElement('div');
var child = document.createElement('div');
div.style.height = '50px';
div.style['overflow-y'] = 'scroll';
child.style.height = '100px';
div.appendChild(child);
modifiedEditor.changeViewZones((accessor) => {
    accessor.addZone({
        afterLineNumber: 2,
        heightInPx: 50,
        domNode: div
    });
})
```
![image](https://user-images.githubusercontent.com/22138217/104723611-78d05080-576a-11eb-847b-fc7bfa36531d.png)

**Comment by chenmy0917** [comment]
@alexdima hello, looking forward to your reply~

**Comment by alexdima** [comment]
@chenmy0917 The purpose of a view zone is to reserve space and maybe render some background content that is not interacted with. The pattern we have used in the editor in case of content that needs to be interacted with is to always pair a view zone with either a content widget or an overlay widget.

Two examples from the editor core:
#### CodeLens: view zone + content widget:
![image](https://user-images.githubusercontent.com/5047891/105370509-f16c5c80-5c03-11eb-8517-14134601005d.png)

#### Inline Find all References: view zone + overlay widget:
![image](https://user-images.githubusercontent.com/5047891/105370610-0943e080-5c04-11eb-82fa-c48d85a0744d.png)

You can take inspiration from our own implementation of `ZoneWidget` at https://github.com/microsoft/vscode/blob/ad437ef958c8d8ce8fdbb04d99fdfd4aa2f8d7b4/src/vs/editor/contrib/zoneWidget/zoneWidget.ts#L160

**Comment by chenmy0917** [comment]
> @chenmy0917 The purpose of a view zone is to reserve space and maybe render some background content that is not interacted with. The pattern we have used in the editor in case of content that needs to be interacted with is to always pair a view zone with either a content widget or an overlay widget.
> 
> Two examples from the editor core:
> 
> #### CodeLens: view zone + content widget:
> ![image](https://user-images.githubusercontent.com/5047891/105370509-f16c5c80-5c03-11eb-8517-14134601005d.png)
> 
> #### Inline Find all References: view zone + overlay widget:
> ![image](https://user-images.githubusercontent.com/5047891/105370610-0943e080-5c04-11eb-82fa-c48d85a0744d.png)
> 
> You can take inspiration from our own implementation of `ZoneWidget` at https://github.com/microsoft/vscode/blob/ad437ef958c8d8ce8fdbb04d99fdfd4aa2f8d7b4/src/vs/editor/contrib/zoneWidget/zoneWidget.ts#L160

**Comment by chenmy0917** [comment]
@alexdima Thank you very much for your reply, but I still have question and look forward to your help.
### The feature I want is shown below: 
![image](https://user-images.githubusercontent.com/22138217/105701457-49c59600-5f45-11eb-8e0b-a9f04379a53b.png)


### Widget can't meet my requirements because it floats on the editor and can't separate line from line, it will obscure the line of code so I cann't see the code: 
![image](https://user-images.githubusercontent.com/22138217/105700292-9dcf7b00-5f43-11eb-95e2-83b39b779bb7.png)

**Comment by alexdima** [comment]
> The purpose of a view zone is to reserve space and maybe render some background content that is not interacted with. The pattern we have used in the editor in case of content that needs to be interacted with is to always pair a view zone with either a content widget or an overlay widget.

@chenmy0917 You can add **both** a content/overlay widget and a view zone. You add the view zone to reserve the space and then position the widget precisely on top of the view zone.

**Comment by chenmy0917** [comment]
@alexdima OK , I will try it, thank you~

**Comment by ricenoddle** [comment]
Hi @alexdima , I tried to use ViewZone + OverlayWidget, but I can't scroll the widget as `Find all References` did. Is there any config I missed ?
![image](https://user-images.githubusercontent.com/13479751/148712329-15026485-7363-495d-8f74-1a72cfbd48d5.png)

**Comment by ricenoddle** [comment]
> Hi @alexdima , I tried to use ViewZone + OverlayWidget, but I can't scroll the widget as `Find all References` did. Is there any config I missed ? ![image](https://user-images.githubusercontent.com/13479751/148712329-15026485-7363-495d-8f74-1a72cfbd48d5.png)

I guess I need to do something like this 
```ts
domNode.onwheel = function (e) {
      e.stopPropagation();
};
```
Is this how you implement in `Find all References` ?

**Comment by ricenoddle** [comment]
But the problem of `stopPropagation` is I cannot scroll the editor when I scrolled to the bottom of my OverlayWidget
