### ISSUE TITLE
Only first file extension for a monaco-language is colorized

### ISSUE THREAD

**Issue by JKillian** [Microsoft/monaco-editor#231]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: OSX

I was playing around with the new YAML highlighting support and noticed that only files with `.yaml` extensions are colorized, but not files with `.yml` extensions. However, [the both extensions are correctly specified in monaco-languages](https://github.com/Microsoft/monaco-languages/blob/db5dfea6bcb61e046e15eb2e6eb177d1a1025673/src/monaco.contribution.ts#L252).

I tested with XML files as well and noticed that only files with a `.xml` extension get colorized, and not files with any of the other extensions.

**Comment by alexandrudima** [comment]
This worked correctly for me:

```
let uri = monaco.Uri.file('/blah/file.yml');
let model = monaco.editor.createModel([
	'%TAG ! tag:clarkevans.com,2002:',
	'--- !shape',
	'  # Use the ! handle for presenting',
	'  # tag:clarkevans.com,2002:circle',
	'- !circle',
	'  center: &ORIGIN {x: 73, y: 129}',
	'  radius: 7',
	'- !line',
	'  start: *ORIGIN',
	'  finish: { x: 89, y: 102 }',
	'- !label',
	'  start: *ORIGIN',
	'  color: 0xFFEEBB',
	'  text: Pretty vector drawing.',
].join('\n'), null, uri);

monaco.editor.create(document.getElementById('Editor'), {
	model: model
});
```
