### ISSUE TITLE
background color doesn't work/update for dark mode all the time

### ISSUE THREAD

**Issue by vinuthakaranth** [microsoft/monaco-editor#2310]
**monaco-editor version:"^0.18.1"
**Browser:** : chrome
**OS:** : windows
**Playground code that reproduces the issue:**

I am trying to change the theme multiple times and when I set to vs-dark, it doesn't update the background color.
It can be reproduced when we play with switching theme multiple times. I can see in the class of monaco-editor 'vs-dark' is added (shows that I have updated the theme to vs-dark when app theme is changed). I can also see that in the styles section background color is #fffffe for vs-dark mode, which is not correct.

![image](https://user-images.githubusercontent.com/33799331/105109367-43c94400-5a71-11eb-9553-bfdab1f9a522.png)

Please let me know if more details is required.

```js
```

**Comment by alexdima** [comment]
Could you please provide a JS snippet demonstrating the problem which executes at https://microsoft.github.io/monaco-editor/playground.html ?

**Comment by vinuthakaranth** [comment]
Snippet
monaco.editor.create(document.getElementById("file-editor"), {
	value: "content test",
        language: "text",
        readOnly: false,
        theme: getMonacoTheme("dark"),
        minimap: {
          enabled: false
        },
        automaticLayout: true,
        renderLineHighlight: "none",
        scrollBeyondLastLine: false,
        fixedOverflowWidgets: true,
        wordWrap: "on"
});

function getMonacoTheme(theme) {
    switch (theme) {
      case "light":
        return "vs";
      case "dark":
        return "vs-dark";
      case "highContrast":
        return "hc-black";
      default:
        return "vs";
    }
  }


Please find the attached screen shot for styles from monaco package. We can see that there are two .monaco-editor styles and one is getting overridden. One refreshing page, one of them gets overridden.
I'm not overriding it anywhere in my code.
![image](https://user-images.githubusercontent.com/33799331/105428906-40ff5800-5c05-11eb-9094-0444db3b8cf2.png)

**Comment by alexdima** [comment]
@vinuthakaranth I am not sure I understand the problem. Thanks for the snippet, I could try it out (with a slight modification) at https://microsoft.github.io/monaco-editor/playground.html :
```js
monaco.editor.create(document.getElementById("container"), {
    value: "content test",
    language: "text",
    readOnly: false,
    theme: getMonacoTheme("dark"),
    minimap: {
        enabled: false
    },
    automaticLayout: true,
    renderLineHighlight: "none",
    scrollBeyondLastLine: false,
    fixedOverflowWidgets: true,
    wordWrap: "on"
});

function getMonacoTheme(theme) {
    switch (theme) {
        case "light":
            return "vs";
        case "dark":
            return "vs-dark";
        case "highContrast":
            return "hc-black";
        default:
            return "vs";
    }
}
```

For me, the editor is rendered with a good (dark) background color:

![image](https://user-images.githubusercontent.com/5047891/105516365-13361400-5cd6-11eb-8d8e-26e6126821bc.png)

The developer tools screenshots appear to show multiple `<style>` tags that define contradicting `background-color` rules, but I cannot reproduce that:
![image](https://user-images.githubusercontent.com/5047891/105516640-690abc00-5cd6-11eb-9fed-f733277bda0d.png)

**Comment by 929853209** [comment]
the same question. and the code was not good to reproduce the problem. use this:    
js  
```
monaco.editor.create(document.getElementById("container"), {
    value: "content test",
    language: "text",
    readOnly: false,
    theme: getMonacoTheme("dark"),
    minimap: {
        enabled: false
    },
    automaticLayout: true,
    renderLineHighlight: "none",
    scrollBeyondLastLine: false,
    fixedOverflowWidgets: true,
    wordWrap: "on"
});
monaco.editor.create(document.getElementById("container2"), {
    value: "content test",
    language: "text",
    readOnly: false,
    theme: getMonacoTheme("light"),
    minimap: {
        enabled: false
    },
    automaticLayout: true,
    renderLineHighlight: "none",
    scrollBeyondLastLine: false,
    fixedOverflowWidgets: true,
    wordWrap: "on"
});

function getMonacoTheme(theme) {
    switch (theme) {
        case "light":
            return "vs";
        case "dark":
            return "vs-dark";
        case "highContrast":
            return "hc-black";
        default:
            return "vs";
    }
}
```  
html  
```
<div id="container" style="height:50%;"></div>

<div id="container2" style="height:50%;"></div>
```   
I hope these two editor has different theme. But the css was overridden.   
 It's not good for two editor with different theme, and not good for theme change with different lazy bundle。

**Comment by 929853209** [comment]
> **monaco-editor version:"^0.18.1"
> **Browser:** : chrome
> **OS:** : windows
> **Playground code that reproduces the issue:**
> 
> I am trying to change the theme multiple times and when I set to vs-dark, it doesn't update the background color.
> It can be reproduced when we play with switching theme multiple times. I can see in the class of monaco-editor 'vs-dark' is added (shows that I have updated the theme to vs-dark when app theme is changed). I can also see that in the styles section background color is #fffffe for vs-dark mode, which is not correct.
> 
> ![image](https://user-images.githubusercontent.com/33799331/105109367-43c94400-5a71-11eb-9553-bfdab1f9a522.png)
> 
> Please let me know if more details is required.

I have met a same problem. I think It's caused by different Instance of monaco. In my program, there is an npm package with monaco which has defined a theme by itself. I used to resolve it by `window.monaco` (v-0.20.0),but it's not work for hight version. You can find out the different Instance of monaco and only use one of them.  

I also think it's not a good idea that control the theme with global `<style>`tag.

**Comment by vinuthakaranth** [comment]
I agree with @929853209 . It is quite difficult to handle monaco themes if there are two or more instances of monaco. Mine was the same case another package was overriding my manoco themes.

**Comment by alexdima** [comment]
Thank you for the extra information. It looks like we already have an issue tracking this feature request at https://github.com/microsoft/monaco-editor/issues/1713

**Comment by 929853209** [comment]
> I agree with @929853209 . It is quite difficult to handle monaco themes if there are two or more instances of monaco. Mine was the same case another package was overriding my manoco themes.


I resolve this problem by this: `import * as monaco from '@my-package/my-editor/node_modules/monaco-editor/esm/vs/editor/editor.api';` it's not a good idea and don't support more package, but useful
