### ISSUE TITLE
Different colors for different brackets. 

### ISSUE THREAD

**Issue by DineshKarri443** [microsoft/monaco-editor#2312]
Hi, Is there a way to set different colors for matching brackets ( in a custom language ).

I am looking for something like the screenshot below :- 
![image](https://user-images.githubusercontent.com/68352790/105323089-bbbd7880-5bef-11eb-9881-989703d9651d.png)

Is there a way to achieve these colors for different brackets ? 

Also I would like to know if there is a way to find and throw an error for a bracket that hasn't been closed .

**Comment by wrisov** [comment]
Hey, can I work on adding this feature?

**Comment by DineshKarri443** [comment]
@alexdima  I found a vs-code extension that does something similar. Here is the extension - https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer

Here is their github link -https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/tree/develop/src

Any idea/suggestions on how I can use some of the inputs from this code in tandem with Monaco's api to get it to work ? 

@wrisov

**Comment by noook** [comment]
Very good feature idea ! Can't wait to use that one

**Comment by tjx666** [comment]
That extension [Bracket-Pair-Colorizer-2](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2)had been deprecated.

**Comment by Hfutsora** [comment]
I have set 
```ts
bracketPairColorization: {
  enabled: true
}
```
in `editor.IStandaloneEditorConstructionOptions`, but it doesn't work.

**Comment by yogabonito** [comment]
@Hfutsora, this has worked for me:

    "bracketPairColorization.enabled": true

**Comment by yogabonito** [comment]
Is there a way to set a custom color for each level?

**Comment by hediet** [comment]
This is now built in.

Themes can change the colors.

**Comment by yogabonito** [comment]
Thank you @hediet! :slightly_smiling_face:

I am already using a theme where I set various colors (e.g., `"editor.selectionHighlightBackground": "#ff00"`), however, I don't know how refer to the different levels of brackets. Is there a list of names that includes these different levels of brackets?

**Comment by hediet** [comment]
This is documented in VS Code.
