### ISSUE TITLE
Enable suggestion details by default

### ISSUE THREAD

**Issue by martonlanga** [microsoft/monaco-editor#2316]
## Feature Request

I would like enable suggestion details by default.

https://github.com/microsoft/vscode/blob/dcce02644eac4e2dd749480b471a331928a7639c/src/vs/editor/contrib/suggest/suggestWidget.ts#L661-L675

### Approaches

1. [Overriding `storageService` didn't work for me](https://stackoverflow.com/questions/54795603/always-show-the-show-more-section-in-monaco-editor). Got:
```
Uncaught TypeError: e.remove is not a function
```

2. Also tried manually triggering `toggleSuggestionDetails` on mount with no success:
```js
editor.trigger('', 'editor.action.triggerSuggest', {})
editor.trigger('', 'toggleSuggestionDetails', {})
editor.trigger('', 'hideSuggestWidget', {})
```

---

Is there a way to achieve this with the current version? Maybe by using some private API?

### Related:
- #2177
- #501

**Comment by alexdima** [comment]
See https://github.com/microsoft/monaco-editor/issues/2241#issuecomment-764694521
