### ISSUE TITLE
Is there a way to prevent cursor/editor focus from being lost on clicking outside the editor

### ISSUE THREAD

**Issue by DineshKarri443** [microsoft/monaco-editor#2318]
Is there a way to prevent cursor/editor focus from being lost on clicking outside the editor. 

My scenario :- I have a list of items in a dropdown that is outside the editor , user can select a dropdown item and I am calling executeEdits to paste this selected text in the editor's previous cursor position. 

When the user opens the dropdown the focus from the editor is lost, user is now not sure where his selected dropdown value will be inserted. 

Is there a way in which I can prevent the editor from losing it's focus on blur. ?

**Comment by alexdima** [comment]
@DineshKarri443 No, you cannot prevent the editor from losing its focus, because the editor respects the `blur` event that comes in from the browser. But you can simply call `editor.focus()` before executing your edits if you want the focus to be in the editor at the end of your operation.

**Comment by DineshKarri443** [comment]
@alexdima Okay Thanks, that's exactly what I am doing now. Manually calling editor.foucs() but after executing the edits.  ( For people trying to implement this in Vue :  calling editor.focus() as soon as execute edits is done will not work; you will have to call Vue.nextTick() and then focus();
