### ISSUE TITLE
New tokens

### ISSUE THREAD

**Issue by tssobe** [microsoft/monaco-editor#2321]
I am using Monaco editor in our project and I have issue I am not able to overcome.
At our scenario , user can add new words to the editor once he clicks on a button, for example, user has editor with language javascript and he now wants to add new word 'workTest', it should be highlighted in custom color.
How do I add new tokens to the editor with highlighted colors?
I already have my 'newTheme' with rules {token: 'asToken', foreground: 'FFA500', fontStyle: 'bold'}
How do I add the tokens to an existing language? I tried everything and nothing works.

**Comment by alexdima** [comment]
You have around three options:

#### 1. Use tokenization
You would need to write your own grammar for the language you want to do i.e. `monaco.languages.setMonarchTokensProvider`. See [an example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages). You can take our existing JS tokenizer and copy-paste that to your project. When a user defines a new keyword, you would dispose the registration and register a new monarch tokens provider with a keyword list that contains the new added keyword.

#### 2. Use semantic tokens
Semantic tokens can be defined for a language and they will be rendered "on top" of syntactical tokens. [See example here](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example)

#### 3. Use text decorations
You can use editor APIs to listen to text buffer changes and then remove any previous decorations and add new decorations on the word ranges you want to colorize. See [an example for inline decorations](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations)
