### ISSUE TITLE
Is there way to programmatically change zoom level?

### ISSUE THREAD

**Issue by ZResnick** [microsoft/monaco-editor#2322]
Does any API exist on for zooming in / out programmatically?  I know you can turn on mouseWheelZoom, but lets say we wanted to increase the zoom to 150% of the default after some timeout, say:
```
const editor = monaco.editor.create(myContainer, {
	value: `Hello, World!`,
	language: "plaintext",
        mouseWheelZoom: true,
});

setTimeout(function() {
    editor.updateOptions({zoomLevel: 150})
}, someTimeout);
```
is there a way to do that?

Furthermore, but not as important to my current use case, is there any way to get the current zoom level should one zoom in or out using the mouse wheel?

**Comment by alexdima** [comment]
The zoom level of ctrl + mouse scroll is [just a multiplier](https://github.com/microsoft/vscode/blob/20f8e59d696141e005931c300e628be8179f65a1/src/vs/editor/common/config/fontInfo.ts#L60-L62) applied to `fontSize`. So you can simply change the `fontSize` option to get the same behavior.

There is no getter for that in the API. You can of course access the JS objects directly if you want to.

**Comment by ZResnick** [comment]
Hmmm.  I've actually tried using ` fontSize` to replicate this same behavior, but through basic usage determined that they are not actually the same thing.

For example, consider the following use case:
    1.  Create an editor where the `fontSize` is 14
    2.  Create a timeout for 3 or 4 seconds that will update the `fontSize`  "back" to 14 as well as `alert` or `console.log` or something, just so you know the `setTimeout` actually fired.
    3. Once the editor loads, immediately zoom in or out significantly using the mouse wheel. 
    4. You'll see that "updating" the `fontSize` doesn't actually change the appearance at all.  

You can copy/paste the following code [here](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options) to test this out.

```
const editor = monaco.editor.create(myContainer, {
	value: `Hello, World!`,
	language: "plaintext",
        mouseWheelZoom: true,
        fontSize: 14,
});

setTimeout(function() {
        editor.updateOptions({fontSize: 14})
        console.log("SetTimeout Fired")
}, 5000);
```

I would try to use `zoomLevel`, but it's readonly.  Any ideas?

**Comment by alexdima** [comment]
There is no API for this, but if you really really want to do this you can use JS. e.g. `require('vs/editor/common/config/editorZoom').EditorZoom.getZoomLevel()` or `setZoomLevel()`.
