### ISSUE TITLE
Where to find Monaco editor supported browsers list?

### ISSUE THREAD

**Issue by nmkedziora** [microsoft/monaco-editor#2324]
Hi,
at https://microsoft.github.io/monaco-editor/ there's infomration about supported browsers, but those are just names.
Where can I find information about exact/minimal browsers' versions?
I've searched the repo, but didn't find any information on this
> supports Classic Edge, Edge, Chrome, Firefox, Safari and Opera

**Comment by alexdima** [comment]
@nmkedziora We support only the latest versions of these browsers.

**Comment by nmkedziora** [comment]
Thank you @alexdima :)
