### ISSUE TITLE
monaco-typescript doesn't provide trigger reasons in signature help

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/monaco-editor#2325]
In https://github.com/microsoft/TypeScript/issues/42361, a user reported that signature help pop-ups were showing up unnecessarily in the TypeScript Playground. I believe that this is because monaco-typescript doesn't funnel along a signature help trigger reason, and I think the existing code confirms that:

https://github.com/microsoft/monaco-typescript/blob/5a17ea5a5db63dc63a3c8741db1ce4ed71cb69ee/src/tsWorker.ts#L216-L221

Please let me know if I'm mistaken - I'm not that familiar with the codebase!

**Comment by alexdima** [comment]
Yes, it looks like this new API was added 2 years ago and never adopted in `monaco-typescript`.

**Comment by DanielRosenwasser** [comment]
Thanks for the fast turnaround @alexdima!

**Comment by MrAndersen1** [comment]
User with issue reporting in :) I doubt I can be of assistance but if I can let me know, since several people have issues reproducing it. I have no issue reproducing it in the playground or vscode.
I will at the very least report back here when it works :)

**Comment by MrAndersen1** [comment]
The original issue works fine now in VScode 1.53.0! :)
I do have a followup issue however, but I have no idea if it's directly related so I left it in the other thread.
