### ISSUE TITLE
multiple editor

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2326]
Creating multiple Monaco-Editors within the same page is both performance and memory intensive. If you want to create and destroy multiple Monaco-editors on the same page frequently. Any suggestions

**Comment by alexdima** [comment]
@y912765390 What are you trying to accomplish? Do you need that all editors are visible all the time? Usually, when having a tab like system, only one editor is really instantiated per tab. e.g. even if there are 5 tabs in this screenshot, there are only 2 editors instantiated:

![image](https://user-images.githubusercontent.com/5047891/106249938-4404d480-6213-11eb-87f7-5da254ab365a.png)

**Comment by y912765390** [comment]
What if I want to display them all together? For example, I want to display 10 editors at the same time. Is there a good way for me to refer to? And I'm also curious about what you just said so if I click toggle back do you want to say setModel directly or do you want some other way to implement five tags but only two Editors.

What I really want to know is if there is a good way to deal with this problem of displaying multiple editors at the same time because if you create multiple editors at the same time and destroy them frequently then recycling is not as friendly

**Comment by y912765390** [comment]
Editor creation requires binding of DOM elements. So when I switch the tags, the DOM element has changed how can I still use the original editor. Thank you very much for your answer, which gives me a great direction of thinking, but I still cannot solve this problem

**Comment by alexdima** [comment]
Yes, the tabs in VS Code use `setModel` so there are 5 models instantiated, but only 2 editors. The tabs basically end up calling `setModel`.

If you need to display 10 editors at the same time, then you must have 10 dom nodes where you want the editors to be created and then you must instantiate 10 editors. But it also matters how you create them. Do you pass in a `dimension`? If you do not, then each editor must measure its container which will cause a DOM sync layout and will slow things down.

**Comment by y912765390** [comment]
That's right. If you have 10 DOMs and 10 Editors and you're constantly creating and destroying things like that, it's not very friendly to recycle memory. Thanks again for your help to give me great ideas and thoughts
