### ISSUE TITLE
Icons don't have colors anymore in suggest and symbol widgets

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#2329]
**monaco-editor version:** 0.22.1
**Browser:** Firefox, Chrome, Edge (current stable version)
**OS:** Windows

If you open the suggest widget in a TypeScript sample in the playground, or you select "Go to Symbol..." from the context menu, the icons don't have color anymore. I confirmed this locally so it seems to be an issue with the editor, and not with the playground itself.

**Comment by alexdima** [comment]
published `monaco-editor@0.22.3`
