### ISSUE TITLE
Auto complete function with its  all params

### ISSUE THREAD

**Issue by subash1** [microsoft/monaco-editor#2331]
**monaco-editor version:** 0.22.3
**Browser:** Chrome
**OS:** Ubuntu

Hi Team, i have doubt in auto completion. in the suggestion popup, when i choose a function, how to populate those function with its params.

![tst](https://user-images.githubusercontent.com/6370601/106598835-4c943c80-657e-11eb-88ff-474ac6351eae.png)

in this case, when i hit enter, its only populate `chunk.test`
but how to populate `chunk.test(param1, param2)`

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
