### ISSUE TITLE
Is there a way to add diff decorations in the margin while using a standalone editor?

### ISSUE THREAD

**Issue by ZResnick** [microsoft/monaco-editor#2332]
I would like to highlight the changes between the current value and the "original" value similar to the way VSCode GIT extension highlights changes. I'm aware that there is DiffEditor in Monaco, however I don't need to compare the versions side by side, I just want to give the visual feedback to the user similar to this example:

<img width="406" alt="mPEiI" src="https://user-images.githubusercontent.com/48109104/106629247-a2e68880-6548-11eb-830b-9e8fc394b8df.png">

I've been able to come up with a somewhat viable method using `editor.onDidChangeModelContent(evt => { // do stuff with deltaDecorations})`, however it's quite difficult to perfectly mimic the nature of a git diff using this method.

Is there some API or built in way of doing this, or will replicating this behavior require a custom implementation?

**Comment by alexdima** [comment]
@ZResnick [Here](https://github.com/microsoft/vscode/blob/6ca7afa84fbe888b8eb682331fdb1f0036d46079/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L886-L1272) is the VS Code implementation. You could use that as an example. Basically the idea is to compute a diff between the original text and the current text and then add decorations to the editor where there are changes, using different colors for additions, modifications, or deletions. Unfortunately, `IEditorWorkerService.computeDirtyDiff` is not exposed in the monaco API, so your only chance to get something easy to work is to use JS and go into the internals of the editor to reach that service and be able to call methods on it.
