### ISSUE TITLE
Suggestions do not reappear correctly when interrupted

### ISSUE THREAD

**Issue by klaasgeldof** [microsoft/monaco-editor#2336]
**monaco-editor version:** 0.22.0
**Browser:** Google Chrome
**OS:** macOS

I created a completion provider and registered it with `registerCompletionItemProvider`. It works as expected, but I noticed some strange behavior while typing.

Below I do 3 times the same:
1. Trigger the autocomplete => suggestions appear ✅
2. Type some letters => suggestions get filtered ✅
3. Click away (put cursor in different position) => suggestions disappear ✅
4. Put cursor back in previous position and continue typing => suggestions should reappear correctly

Step 4 works like it should in the `css` language:

![CleanShot 2021-02-04 at 20 41 24](https://user-images.githubusercontent.com/35819/106951902-a6d4ff00-6730-11eb-8b69-feb88812af7b.gif)

However, when I do exactly the same in the `html` language, step 4 does not work:

![CleanShot 2021-02-04 at 20 42 56](https://user-images.githubusercontent.com/35819/106952207-177c1b80-6731-11eb-96c4-8d31ab94a52e.gif)

When I change the html a bit (remove the `div` and put `class` in front), it works:

![CleanShot 2021-02-04 at 20 44 36](https://user-images.githubusercontent.com/35819/106952271-2f539f80-6731-11eb-8782-163bfecb248f.gif)

When it's working, my `provideCompletionItems` function gets called with context `CompletionContext.triggerKind = CompletionTriggerKind.Invoke (0)`. When it's not working, `provideCompletionItems` is not called.

It's certainly possible to get it working in every situation, because it works perfectly on https://play.tailwindcss.com/ for example.

I have no clue why it's not working in certain situations in my app...
Has anyone an idea about this?
Thanks in advance!

**Comment by alexdima** [comment]
@klaasgeldof By default the suggest widget does not automatically open when typing inside a string. The differences you observe are caused by typing in a string or not (you can use `F1 > Developer: Inspect Tokens` to validate this).

You can configure the suggest widget to automatically open even when typing inside a string:
```
monaco.editor.create(document.getElementById("container"), {
    // ...
    quickSuggestions: {
        comments: false,
        strings: true,
        other: true
    }
});
```

The default is `quickSuggestions: { other: true }`.

**Comment by klaasgeldof** [comment]
Wow, thank you so much Alex!
