### ISSUE TITLE
Types: are they exposed somewhere?

### ISSUE THREAD

**Issue by mbana** [Microsoft/monaco-editor#234]
Are the types exposed in the built JS library? I'm using ES6 and cannot include TypeScript just yet. I am trying to avoid having to use anonymous objects in the API calls, say.

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example

```javascript
monaco.languages.registerHoverProvider('mySpecialLanguage', {
	provideHover: function(model, position) {
		return xhr('../playground.html').then(function(res) {
			return {
				range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
				contents: [
					'**SOURCE**',
					{ language: 'html', value: res.responseText.substring(0, 200) }
				]
			}
		});
	}
});
```
I'd much rather do the below:

```javascript
class QuickInfoAdapter extends monaco.languages.HoverProvider {
	provideHover(model, position, token {
	}
}
```

Thank you,

**Comment by alexandrudima** [comment]
The `*Provider` are all interfaces, and you can definitely write classes for the providers, you can even write a single class that implements all providers you wish.

e.g. https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts#L292
