### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by LLZWWY** [microsoft/monaco-editor#2340]
How to create a new language in Monaco editor? (create a new language without using the original language)

**Comment by mbscreater** [comment]
It is my question too😏!

**Comment by luminaxster** [comment]
This is a good start: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

**Comment by LLZWWY** [comment]
> https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

Thank you very much! Do you have anything more comprehensive? There is no completion prompt and hover prompt for this link.

**Comment by rcjsuen** [comment]
> There is no completion prompt and hover prompt for this link.

@LLZWWY Did you check out the separate [completion provider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) and [hover provider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example)?

**Comment by LLZWWY** [comment]
Now part of the framework is out. At present, there is a problem (input # if), in which # this symbol cannot be added to code completion and syntax highlighting.

**Comment by LLZWWY** [comment]
Now part of the framework is out. At present, there is a problem (input # if), in which # symbol cannot be added to code completion and syntax highlighting.

**Comment by LLZWWY** [comment]
Another problem is how to customize the display graphics of completionitemkind?

**Comment by alexdima** [comment]
> Another problem is how to customize the display graphics of completionitemkind?

@LLZWWY AFAIK there is no API to customize those. You could attempt tweaking the icons using CSS.
