### ISSUE TITLE
It not work in EDGE

### ISSUE THREAD

**Issue by cn17173** [microsoft/monaco-editor#2342]
SCRIPT5674: SCRIPT5674: Invalid regular expression: invalid escape in unicode pattern
editor.main.js (613,412)

**Comment by alexdima** [comment]
Please use an older version of the `monaco-editor`. Going forward, we will no longer support Classic Edge. See also https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge#what-is-the-lifecycle-policy-for-microsoft-edge

> End of support for the legacy version of the Microsoft Edge desktop app is on March 9, 2021. This means that Microsoft Edge Legacy will not receive security updates after that date. Go here to learn more.

**Comment by cn17173** [comment]
Thank you very much!
