### ISSUE TITLE
Selecting using mouse doesn't work on some lines with transform: scale

### ISSUE THREAD

**Issue by svick** [microsoft/monaco-editor#2347]
**monaco-editor version:** latest on Playground
**Browser:** Edgium
**OS:** Windows
**Playground code that reproduces the issue:**

JS:
```js
monaco.editor.create(document.getElementById("container"), {
	value: `using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;`,
	language: "csharp"
});
```

CSS:
```css
body {
    transform: scale(0.8);
}
```

With the above CSS, selecting some lines of code using the mouse does not work. Specifically, it happens for me for line 8 in the above code.

**Comment by sajeerAhamed15** [comment]
I faced the same issue. The cursor position is also not aligned properly. This is the [monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html) code I used to recreate the issue.

HTML
```html
<div id="container" style="transform: scale(0.8);height:100%;"></div>
```

JS
```js
monaco.editor.create(document.getElementById("container"), {
	value: "console.log('hello')",
	language: "javascript"
});
```

**Comment by jankurianski** [comment]
I have the same issue in my app.  Would anyone with knowledge of the VS code internals be interested in a bug bounty for this?

I think the issue occurs with any CSS transform rule, so it appears to be the same issue as https://github.com/microsoft/monaco-editor/issues/531 which contains a tip from @alexdima on where to start.

**Comment by farukparhat** [comment]
Hitting the same issue as we are using zoom-pan-pinch to allow the user to zoom in and out.
Currently there are severe issues with cursor and selection positioning within the editor when the CSS scale is not 1

**Comment by somebee** [comment]
This is related to https://github.com/microsoft/vscode/issues/139281 and related PR https://github.com/microsoft/vscode/pull/139282. It fixes the rendering of decorations, carets etc in a scaled element.
