### ISSUE TITLE
Tabstops in Snippets do not work!

### ISSUE THREAD

**Issue by REDEAKAA** [microsoft/monaco-editor#2349]
**monaco-editor version:** 0.22.3
**Browser:** Chrome Version 88.0.4324.104
**OS:** Win 10
**Playground code that reproduces the issue:** https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

So I've been trying to implement tabstops in my custom snippets but to no avail. I also tried it in the playground provided by monaco-editor, still to no avail.

When i place a tabstop say.. `${1}` or `${1:value}` or `$1`, they just get printed out. Saw a comment that says to pass the `insertText` property an object containing a property `value`, but this didn't work either. It doesn't even output the snippet itself not to talk about placing a tabstop, it just gives an error

```js
// this just spits out the snippet with no tabstop....just plain
{
    label: 'function',
    documentation: "JavaScript Function Defination",
    insertText: 'function ${1:name}(${2:args}){\n\t\n};'
}

// this gives an error..
{
    label: 'function',
    documentation: "JavaScript Function Defination",
    insertText:  { value: 'function ${1:name}(${2:args}){\n\t\n};' }
}

```

Snippets are less fun with tabstops ☹. Would really appreciate some help. Thank you.

**Comment by rcjsuen** [comment]
> **Playground code that reproduces the issue:** https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

@REDEAKAA The linked code you have here has the solution hidden. :)

You are missing `insertTextRules` in your returned items.

```
insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet
```

**Comment by REDEAKAA** [comment]
@rcjsuen Yooooooo! it actually worked! Thanks alot sir. Very grateful.

I hope you don't mind if i come running to you with more issues in the future when they arise? 😁
