### ISSUE TITLE
Editor UI Themes

### ISSUE THREAD

**Issue by JKillian** [Microsoft/monaco-editor#235]
I've been working on my own editor UI theme, and I've run into an issue where some styles seem to be core styles whereas other styles are surprisingly defined only in the theme.

For example, the `.redsquiggly` class, which is applied to error underlines, only seems to appear in theme CSS. So if I apply my own custom theme to VS and forget to define `.redsquiggly`, all of the sudden, error marks are invisible. On the other hand, red error marks show up in the scrollbar regardless of whether my custom theme defines anything about them.

I think there are a few possible solutions here:
- a well-defined list of selectors that custom themes need to implement styles for
- Or, the core editor has styles for all features, custom themes only override these styles

If I'm misunderstanding something here, any recommendations on the best way to make a custom UI theme?

**Comment by alexandrudima** [comment]
I would suggest that you set the theme to `vs my-custom` and then you'll get all the `vs` selectors kick in + you can overwrite via `my-custom`.

**Comment by JKillian** [comment]
Thanks, I'll give that a shot and see how it works out. Small sidenote, [the documentation](https://github.com/Microsoft/monaco-editor/blob/77e9dcdca46d5dbbf6d4424611b12d99c91c60c9/website/playground/monaco.d.ts.txt#L1109L1113) seems to be a touch out of date then:

```
/**
* Theme to be used for rendering. Consists of two parts, the UI theme and the syntax theme,
* separated by a space.
* The current available UI themes are: 'vs' (default), 'vs-dark', 'hc-black'
* The syntax themes are contributed. The default is 'default-theme'
*/
theme?: string;
```

I don't believe the UI theme vs. syntax theme distinction actually exists, and I don't think 'default-theme' actually exists either?

**Comment by JKillian** [comment]
Closing this as I think it's answered

**Comment by anztrax** [comment]
thanks @JKillian :+1:
