### ISSUE TITLE
Inline replacements preview

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#2353]
I'd like to be able to show replacement previews like vscodes does:

![image](https://user-images.githubusercontent.com/1812093/108072089-60e83700-705e-11eb-8902-77262b4bfb72.png)

But inside the editor.

Is this something doable already maybe somehow?

**Comment by alexdima** [comment]
I think this is implemented by using ::before decorations.

**Comment by fabiospampinato** [comment]
`::before` decorations on custom markers? Like vscode doesn't implement that in the editor as far as I know 🤔 I want to get that implemented inside the editor itself, for the in-editor find widget.
