### ISSUE TITLE
Calling `textModel.setValue` with undefined throws an error

### ISSUE THREAD

**Issue by nathggns** [microsoft/monaco-editor#2354]
**monaco-editor version:** 0.22.3
**Browser:** Chrome
**OS:** Mac
**Playground code that reproduces the issue:**

```js
const instance = monaco.editor.create(document.getElementById("container"));
const textModel = monaco.editor.createModel("function foo() {}", "javascript", monaco.Uri.parse("foo.js"));

instance.setModel(textModel);
textModel.setValue(undefined);
```

This causes the following error

```
TypeError: Cannot read property 'create' of undefined
    at N (VM72 editor.main.js:548)
    at W.setValue (VM72 editor.main.js:549)
    at eval (eval at window.load (playground-runner.html:27), <anonymous>:5:11)
    at eval (<anonymous>)
    at window.load (playground-runner.html:68)
    at HTMLIFrameElement.<anonymous> (playground.html:647)
```

The reason this matters is that JSON.stringify can sometimes return undefined (which most people don't seem to know – I certainly didn't) – which can make this bug really hard to track down.

The implementation of `setValue` makes `setValue(null)` seemingly a no-op. While I'm not sure that's ideal (I think it should probably be equivalent to `setValue("")`, it seems Monaco should do the same for `setValue(undefined)` to be consistent. 

```js
    setValue(value) {
        this._assertNotDisposed();
        if (value === null) {
            // There's nothing to do
            return;
        }
        const { textBuffer, disposable } = createTextBuffer(value, this._options.defaultEOL);
        this._setValueFromTextBuffer(textBuffer, disposable);
    }
```

The cause of this bug is because `createTextBuffer` assumes it is either passed an already created factory, or a string – if it's not a string it calls `value.create` – which obviously doesn't exist on `undefined`. 

```js
export function createTextBuffer(value, defaultEOL) {
    const factory = (typeof value === 'string' ? createTextBufferFactory(value) : value);
    return factory.create(defaultEOL);
}
```

**Comment by alexdima** [comment]
This is working as expected. The method is typed to expect a `string` as an argument. See [here](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#setvalue) generated from the .d.ts [here](https://github.com/microsoft/monaco-editor/blob/c854fa1/monaco.d.ts#L1658). So passing `undefined` is a mistake on your part.

**Comment by nathggns** [comment]
I accept that undefined is not a valid type to pass, but you check for null, so it seems sensible to check for undefined, especially when JSON.stringify  can return undefined in some unexpected circumstances (which typescript does *not* tell you about - the type for stringify is string!).

Otherwise, setValue(JSON.stringify(...)) is broken in ways neither typescript or Monaco warns you about.
