### ISSUE TITLE
Webpack error on CSS for sash.css

### ISSUE THREAD

**Issue by chadsowald** [microsoft/monaco-editor#2359]
**monaco-editor version:** 0.22.3
**monaco-editor-webpack-plugin version:** 3.0.0
**Browser:** N/A
**OS:** Win 10 Enterprise x64
**Playground code that reproduces the issue:** N/A

Hi I'm using both of the latest packages for the monaco editor and the monaco editor webpack plugin.  Upon running ```node node_modules/webpack-cli``` on my webpack I get this error 
![image](https://user-images.githubusercontent.com/165767/108324689-10b3c680-717d-11eb-8f25-667a17593269.png)

I was able to fix it by changing 4 lines where it looks like ```-calc(....)``` is being used instead of ```calc(calc(...) * -1)```.  Oddly other nearby lines do it the other way so I'm not sure why there are differences within this single file.  Nonetheless, these 4 **bolded** changes below fix my issue.

In sash.css:
<pre>
.monaco-sash.orthogonal-start.vertical::before {
	<b>left: calc(calc(var(--sash-size) / 2) * -1);</b>
	top: calc(var(--sash-size) * -1);
}
.monaco-sash.orthogonal-end.vertical::after {
	<b>left: calc(calc(var(--sash-size) / 2) * -1);</b>
	bottom: calc(var(--sash-size) * -1);
}
.monaco-sash.orthogonal-start.horizontal::before {
	<b>top: calc(calc(var(--sash-size) / 2) * -1);</b>
	left: calc(var(--sash-size) * -1);
}
.monaco-sash.orthogonal-end.horizontal::after {
	<b>top: calc(calc(var(--sash-size) / 2) * -1);</b>
	right: calc(var(--sash-size) * -1);
}
</pre>

I suspect that if I updated my webpack infrastructure (many loaders and plugins) that I might also be able to fix this, but just those 4 little changes were all that was needed.  Would it be possible to make that change?

**Comment by zoxiyo** [comment]
I also have the same situation.How to resolve this problem?

**Comment by zoxiyo** [comment]
> **monaco-editor version:** 0.22.3
> **monaco-editor-webpack-plugin version:** 3.0.0
> **Browser:** N/A
> **OS:** Win 10 Enterprise x64
> **Playground code that reproduces the issue:** N/A
> 
> Hi I'm using both of the latest packages for the monaco editor and the monaco editor webpack plugin. Upon running `node node_modules/webpack-cli` on my webpack I get this error
> ![image](https://user-images.githubusercontent.com/165767/108324689-10b3c680-717d-11eb-8f25-667a17593269.png)
> 
> I was able to fix it by changing 4 lines where it looks like `-calc(....)` is being used instead of `calc(calc(...) * -1)`. Oddly other nearby lines do it the other way so I'm not sure why there are differences within this single file. Nonetheless, these 4 **bolded** changes below fix my issue.
> 
> In sash.css:
> 
> .monaco-sash.orthogonal-start.vertical::before {
> 	left: calc(calc(var(--sash-size) / 2) * -1);
> 	top: calc(var(--sash-size) * -1);
> }
> .monaco-sash.orthogonal-end.vertical::after {
> 	left: calc(calc(var(--sash-size) / 2) * -1);
> 	bottom: calc(var(--sash-size) * -1);
> }
> .monaco-sash.orthogonal-start.horizontal::before {
> 	top: calc(calc(var(--sash-size) / 2) * -1);
> 	left: calc(var(--sash-size) * -1);
> }
> .monaco-sash.orthogonal-end.horizontal::after {
> 	top: calc(calc(var(--sash-size) / 2) * -1);
> 	right: calc(var(--sash-size) * -1);
> }
> I suspect that if I updated my webpack infrastructure (many loaders and plugins) that I might also be able to fix this, but just those 4 little changes were all that was needed. Would it be possible to make that change?

I have resolved this problem.Beacause I used less-loader to compile *.less and *.css files, so I seperate these `test: /\.(css|less)$/` to `test:/.css$/` and `test:/.less$/`,this problems is resovled.But the real reason of the problem I have don't know.

**Comment by moliyu** [comment]
you need to update postcss@8.x.x
