### ISSUE TITLE
How can I detect a parsing error in my editor?

### ISSUE THREAD

**Issue by rbadapanda** [Microsoft/monaco-editor#236]
I am currently doing the following:
**in parser:**        defaultToken: 'invalid',

**in EditorModel.onDidChangeContent:**
         var editorHasInvalidItems = $('#container') && $('#container').find('.invalid').length !== 0

**Issue is:** This is not stable, due to what seems like a race condition between 

> when editorHasInvalidItems is evaluated

 and 

> when the css is attached in the editor.

What is a better way to handle this case?

**Comment by alexandrudima** [comment]
We currently don't have API to read markers, we should add that. Let's track in #30
