### ISSUE TITLE
Add a way to annotate global 'this' type in JS/TS

### ISSUE THREAD

**Issue by Thomasan1999** [microsoft/monaco-editor#2361]
I want to use Monaco Editor to write body of a Vue component method. Therefore, `this` should refer to the Vue component itself but in the editor `this` refers to the `window` object and I did not find a way to annotate the `this` type globally. I could use another variable instead of `this` but that still leaves me with wrong autocomplete and TS errors when using `this`.

**Comment by y912765390** [comment]
Has it been resolved? I have the same problem

**Comment by hediet** [comment]
Duplicate of https://github.com/microsoft/monaco-editor/issues/1661
