### ISSUE TITLE
I cant add a dynamic keyword like LAST_N_FISCAL_​YEARS:n where n is a positive integer number

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/monaco-editor#2363]
I cant add a dynamic keyword like LAST_N_FISCAL_​YEARS:n where n is a positive integer number

I need it for this type of language

````sql
SELECT Id FROM Account WHERE CreatedDate = LAST_N_WEEKS:52
````

**monaco-editor version:** 0.22.0
**Browser:** Chrome
**OS:** Windows 10

**Comment by alexdima** [comment]
@AllanOricil You can define a custom language e.g. https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages . You can use the SQL language as an example if your language is similar to SQL https://github.com/microsoft/monaco-languages/blob/main/src/sql/sql.ts

**Comment by AllanOricil** [comment]
Amazing solution!
