### ISSUE TITLE
Ability to remove actions from context menu

### ISSUE THREAD

**Issue by LLZWWY** [microsoft/monaco-editor#2367]
How to modify the right-click menu information in the edit box and add or delete functions?

**Comment by alexdima** [comment]
Currently, it is possible to only add new actions e.g. https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance

**Comment by LLZWWY** [comment]
> Currently, it is possible to only add new actions e.g. https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance

The connection cannot be opened, indicating that the connection has been reset. Do you have anything else?

**Comment by alexdima** [comment]
> The connection cannot be opened, indicating that the connection has been reset. Do you have anything else?

Sorry, I don't know what you mean.

**Comment by LLZWWY** [comment]
> > The connection cannot be opened, indicating that the connection has been reset. Do you have anything else?
> 
> Sorry, I don't know what you mean.

The connection can't be opened

**Comment by alexdima** [comment]
Do you mean you cannot access https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance ?

**Comment by LLZWWY** [comment]
> Do you mean you cannot access https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance ?

yes

**Comment by alexdima** [comment]
Please contact your ISP.

**Comment by alexdima** [comment]
See also https://github.com/microsoft/monaco-editor/issues/1567#issuecomment-777876361
