### ISSUE TITLE
Add property to IEditorOptions to disable tab trapping

### ISSUE THREAD

**Issue by Taljjaa** [microsoft/monaco-editor#2373]
Is it possible to add a property on IEditorOptions to permanently disable Tab Trapping? In our current design when the browser refreshes or a new window is opened the user would have to toggle the trapping off with ```Ctrl + M```

**Comment by alexdima** [comment]
You can do the following:

```
editor.createContextKey('editorTabMovesFocus', undefined).set(true);
```

**Comment by Taljjaa** [comment]
Thank you for the response, `editor.createContextKey('editorTabMovesFocus', true);` worked for me!
