### ISSUE TITLE
Show Fixes keyboard shortcut not working in Chrome

### ISSUE THREAD

**Issue by SamVerschueren** [microsoft/monaco-editor#2374]
**monaco-editor version:** 0.22.3
**Browser:** Google Chrome
**OS:** macOS Big Sur
**Playground code that reproduces the issue:**

[Open in TypeScript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHIBGcUAFAJQBcyAbusACYDcuAvrrggDZwDOfZACFSyYAFsADtwjiI4QRix52uIA)

```js
interface Foo {
    bar(): void;
}

class Bar implements Foo {

}
```

When having this code, it shows a red underline under `Bar` because the class doesn't implement the interface correctly.

![image](https://user-images.githubusercontent.com/1913805/109923773-911b1100-7cbf-11eb-851a-42c248120d0f.png)

When putting the cursor on the `Bar` word, it shows the lightbulb on the left which when clicked shows the `Implement interface 'Foo'` action.

![image](https://user-images.githubusercontent.com/1913805/109923842-ad1eb280-7cbf-11eb-8877-f71ff69bf29c.png)

When hovering over the lightbulb, it also shows the keyboard shortcut (<kbd>⌘</kbd>+<kbd>.</kbd>), but when pressed in Chrome, it doesn't work. In Safari however, this works correctly. Untested in Firefox.

**Comment by SamVerschueren** [comment]
After some more testing it works on Linux with <kbd>Ctrl</kbd>+<kbd>.</kbd>.

It works on macOS as well if you put the cursor at the end of the word, so placing the cursor after the `r` of `Bar` and press the shortcut, then it works as expected.

**Comment by alexdima** [comment]
@SamVerschueren I cannot reproduce. <kbd>cmd</kbd>+<kbd>.</kbd> works for me on macOS on Chrome. Are you using the US keyboard layout or something else?

**Comment by SamVerschueren** [comment]
Ok, this is super weird. So yesterday it wasn't working for me, only if I placed my cursor and the end of the word. I let someone else test this on mac OS, he had the exact same problem. Someone else tested it on Linux and he confirmed that it worked for him. So I assumed this was a Chrome thing on macOS. But when testing it again, it suddenly works. For me, as well as for the person who had the exact same issue.

Let me close this for now, if it pops up again, I can reopen it or something. I was testing different versions monaco, maybe something got corrupted or something.

Thanks for the quick response from your end 🙏 .
