### ISSUE TITLE
LSP semantic tokens dont work 

### ISSUE THREAD

**Issue by Vadimtro** [microsoft/monaco-editor#2378]
I have semantic tokens working in vscode (LSP protocol circa 3.16+). It doesn't appear working in Monaco. All other LSP messages, such as hover, folding, etc are fine in both products. 

The playground example (url=https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example) implements highlighting at the client side, but the `provideDocumentSemanticTokens` method should clearly get the info from LSP call.

**Comment by rcjsuen** [comment]
> I have semantic tokens working in vscode (LSP protocol circa 3.16+). It doesn't appear working in Monaco. All other LSP messages, such as hover, folding, etc are fine in both products.
> 
> The playground example (url=https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example) implements highlighting at the client side, but the `provideDocumentSemanticTokens` method should clearly get the info from LSP call.

@Vadimtro The Monaco editor in its out-of-the-box form does not support the language server protocol. How are you connecting your language server with the Monaco editor?

**Comment by Vadimtro** [comment]
https://github.com/TypeFox/monaco-languageclient

**Comment by rcjsuen** [comment]
> https://github.com/TypeFox/monaco-languageclient
> 
> I have modified example/client.ts to open websockets connection to language server. I presume the aforementioned semantic tokens provider example can be adopted to be fed from language server messages.

You should open an issue in the [TypeFox/monaco-languageclient repository](https://github.com/TypeFox/monaco-languageclient) then.
