### ISSUE TITLE
Instance-specific CompletionItemProvider

### ISSUE THREAD

**Issue by prostgles** [microsoft/monaco-editor#2379]
Thanks a lot for developing this awesome tool!

As detailed in [this issue](https://github.com/microsoft/monaco-editor/issues/2084) the completions are global for each language.
Is there a way to have non global language completion providers?
My use-case involves two SQL editors connected to different databases with different schemas

**Comment by alexdima** [comment]
I think you could do the following:
- use `monaco.editor.createModel(...)` to manually create your text models (text buffers) and give them distinct URLs.
- use `{ model: model }` when constructing the editor to prevent it from creating its own text model
- in the completion item provider, you can look at the passed in model and behave differently based on that.

**Comment by prostgles** [comment]
I'll try this. At the moment I'm just keeping track of the focused editor to amend results.

Thanks!
