### ISSUE TITLE
errors.ts:33 Uncaught Error: Cannot read property 'startLineNumber' of undefined

### ISSUE THREAD

**Issue by gujiman** [Microsoft/monaco-editor#238]
`monaco-editor` npm version: 0.7.0
Browser: Chrome
OS: Windows 7

Hi Team,

Steps to create the error:
1) goto https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-tokens-and-colors
2) right-click in the preview window and select "Format Code"
3) look at the console for the following error:

errors.ts:33 Uncaught Error: Cannot read property 'startLineNumber' of undefined(…)(anonymous function) @ errors.ts:33

**Comment by alexandrudima** [comment]
yeah, looks like html format is broken

**Comment by JKillian** [comment]
dupe of #227 for reference

**Comment by aeschli** [comment]
I updated the version of monaco-html that contains the fix (and more). @alexandrudima Want to publish an update monaco-editor?

**Comment by alexandrudima** [comment]
@aeschli Release notes text?

**Comment by aeschli** [comment]
Just bug fixes

**Comment by alexandrudima** [comment]
This is already fixed in `monaco-html` and the fix will come out with the v0.8.x release
