### ISSUE TITLE
Apache FreeMarker Language Support

### ISSUE THREAD

**Issue by melloware** [microsoft/monaco-editor#2383]
Syntax highlighting for Apache Freemarker template language would be excellent.

See: https://freemarker.apache.org/

See: https://freemarker.apache.org/editors.html

See: https://freemarker.apache.org/docs/dgui_template_overallstructure.html

**Comment by stolp** [comment]
+1. I am also missing Freemarker support.

**Comment by jepsar** [comment]
Would be awesome. Subscribing!

**Comment by melloware** [comment]
Also reported on the FreeMarker JIRA in case one of their devs wants to add the support: https://issues.apache.org/jira/browse/FREEMARKER-180

**Comment by FlipWarthog** [comment]
+1 as well. This would be a great addition.

**Comment by rawdog71** [comment]
I could use Freemarker and Velocity.

**Comment by blutorange** [comment]
we might need this too, I started taking a look at this. I made [a first  (not yet complete) draft](https://github.com/blutorange/monaco-editor/commits/lang-freemarker) based on the JavaCC grammar from FreeMarker. That grammar is pretty horrible though. Also, there's no the FreeMarker syntax, there's a couple of different syntaxes with some legacy options thrown into the mix a well (e.g. in `${...}` mode `[=...]` is just plain text and vice versa, and there's also the legacy `#{...}`) And it's also got an "auto" mode where it tries to auto-detect the syntax...

Not sure yet, but I'm thinking legacy settings should be ignored, which leaves 2 expression (dollar and bracket) * 3 directive (auto, square bracket, angle bracket) syntaxes... which would result in 6 different language mode variations, hmm...

**Comment by melloware** [comment]
I vote to ignore the legacy settings.  No point in supporting something considered legacy only the newest FreeMarker syntax.

**Comment by brendonparker** [comment]
Is there some documentation on how I might leverage this in monaco-editor?

I'm using react with the `MonacoWebPackPlugin`:
```javascript
new MonacoWebpackPlugin({
    languages: ['xml', 'freemarker2'],
})
```

But it doesn't seem to get picked up

**Comment by blutorange** [comment]
Haven't use the webpack plugin yet, so not sure about that, but doesn't add only include freemarker support?

Works on the playground if you specify the language when creating an editor

```javascript

monaco.editor.create(document.getElementById('container'), {
	value: "",
	language: 'freemarker2'
});
```

![image](https://user-images.githubusercontent.com/2456413/154280851-e25811f4-6f90-48aa-825f-bfd0e5d1abda.png)

**Comment by blutorange** [comment]
Yeah would be great if that were possible, but (a) freemarker can be used for any text content, so we'd have to create a different language mode for each embedded language, and (b) there's no guarantee that the plain text without free marker directives and interpolations is valid in the embedded language, e.g. this is perfectly a legal freemarker document

```plaintext
<div>
${"<span"}></span>
</div>
```

That looks light a nightmare to write a highlighter for.

That's why I decided we should focus on highlighting freemarker syntax. But if anybody has an idea and/or wants to contribute, feel free to.
