### ISSUE TITLE
Customization With Delta Decorations

### ISSUE THREAD

**Issue by kvinuvineeth89** [microsoft/monaco-editor#2387]
Some manual keywords to the editor is highlighted using delta decorations, Problem facing is last applied delta decoration css class is overwriting the existing highlights like 'select', 'aggregate functions'. Please suggest me how to solve this.

To Reproduce the issue with Monaco Playground
https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations

Then delete the existing contents in the editor and write simple query . The default behavior is overwritten with the provided decorations class rules.
 
![image](https://user-images.githubusercontent.com/80463466/110790623-42f5a700-8297-11eb-9498-23b02bd3d771.png)

**Comment by spahnke** [comment]
You can use the `stickiness` option for this:

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

var decorations = editor.deltaDecorations([], [
	{ range: new monaco.Range(3,1,5,1), options: { isWholeLine: true, linesDecorationsClassName: 'myLineDecoration', stickiness: monaco.editor.TrackedRangeStickiness.NeverGrowsWhenTypingAtEdges }},
	{ range: new monaco.Range(7,1,7,24), options: { inlineClassName: 'myInlineDecoration', stickiness: monaco.editor.TrackedRangeStickiness.NeverGrowsWhenTypingAtEdges }},
]);

```

**Comment by kvinuvineeth89** [comment]
@spahnke ,
 
 Thank you, It solved my concern

**Comment by n-dragon** [comment]
@kvinuvineeth89 how do you get the position of the token (that you use in range) you want to highlight ?
