### ISSUE TITLE
ShadowDOM issues

### ISSUE THREAD

**Issue by vchinaski** [microsoft/monaco-editor#2396]
Greetings! I'm using Monaco Editor + a lot of custom CSS styles in my project. The problem is that "quick fix" feature (languages.CodeActionProvider) uses ShadowDOM for showing a quick fix suggestions dropdown. Because of that, I cannot override any CSS-styles of this component due to ShadowDOM encapsulation feature.

Does Monaco Editor provide any API/workaround/etc. in order to not use ShadowDOM?

Thanks in advance

**Comment by alexdima** [comment]
There will be a new editor option called `useShadowDOM` that can be set to `false` to disable the usage of shadow dom in the editor.
