### ISSUE TITLE
Is it possible to provide a custom `openEditorDelegate`?

### ISSUE THREAD

**Issue by JKillian** [microsoft/monaco-editor#240]
In my hunt around monaco-related code in the vscode repo, I found this intriguing [`setOpenEditorDelegate`](https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/editor/browser/standalone/simpleServices.ts#L103) method. Is it possible somehow to provide my own `openEditorDelegate` function?

For context, I need to implement custom behavior in my app when a user clicks the title in a Peek panel or clicks a reference in the results of a "Find References" command. If I could override the default behavior (which seems to throw an error for me) it would be great.

Thanks!

**Comment by alexandrudima** [comment]
You could create the editor and pass as the last argument an object containing a custom implementation of an `editorService` that respects [IEditorService ](https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/platform/editor/common/editor.ts#L15) perhaps inspired by the [SimpleEditorService ](https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/editor/browser/standalone/simpleServices.ts#L89). [This is where we set it up](https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/editor/browser/standalone/standaloneEditor.ts#L45)

**Comment by JKillian** [comment]
Thanks, this seems like a potentially good option. I notice that if I steal most of the `SimpleEditorService` code, I'd also have to have access to `SimpleModel`, `SimpleEditor`, `TPromise`, etc. As far as I can tell, those aren't accessible from the monaco-editor pacakge, correct? So I would need to reimplement those things as well most likely?
