### ISSUE TITLE
Go To Definition does not work?

### ISSUE THREAD

**Issue by ivan-prodanov** [microsoft/monaco-editor#2402]
I was reading [this issue (#291)](https://github.com/microsoft/monaco-editor/issues/291) as I was having the same problem. Essentially my DefinitionProvider calls monaco.editor.createModel with a uri and code and then returns this uri in the Location object. However, the editor won't switch to the newly created model. Go to Definition only works in peek definition.

I found [this fix](https://github.com/microsoft/monaco-editor/issues/935#issuecomment-440786796), which is quite impractical as I'm using TypeScript. 

I also found [this suggestion](https://github.com/microsoft/monaco-editor/issues/291#issuecomment-437875711) from @alexdima.

Last but not least, I saw what the Eclipse guys are doing with Theia. Pretty much manually adding the [type definitions](https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/typings/monaco/index.d.ts).

I was thinking the last several days what the most pragmatic and practical solution could be. Is this a bug in Monaco? If it's not a bug and we are required to extend the current services, can we get the type definitions, perhaps, in a separate package?

Context about my project: Static Monaco webpage running OmniSharp's roslyn backend (The C# extension for VS Code) in WebAssembly within a worker. The editor communicates directly with WebAssembly for every single provider available through the worker. It all works like magic, except "Go To Definition" :(

Edit: I'm specifically talking about intermodel "Go To Definition". The feature works very well if the definition is within the the current model.

**Comment by spahnke** [comment]
See https://github.com/microsoft/monaco-editor/issues/2000#issuecomment-649506233 for thoughts on this and a possible workaround for you. Basically, there currently is no official API to do this in a meaningful way and without breaking most (I think) use-cases.

**Comment by ivan-prodanov** [comment]
@spahnke thank you, this somewhat works. I opened [another issue](https://github.com/microsoft/monaco-editor/issues/2407) because line/column is not respected from the DefinitionProvider.
