### ISSUE TITLE
Formatting for C# doesn't work

### ISSUE THREAD

**Issue by HEBOS** [microsoft/monaco-editor#2403]
monaco-editor version:** 0.23.0
Browser: Chrome
OS: Windows
Playground code that reproduces the issue:
If you go to https://microsoft.github.io/monaco-editor and select "csharp" language and paste the bellow code snippet, you will see that the indentation doesn't work. Also there is no Format Document option when context menu is displayed using the right click. 
I use the following code to trigger code formatting programmatically and everything works perfectly for Javascript and JSON. Both syntax colorizing and formatting. For C# I get syntax colorized correctly, but the formatting doesn't work.

this.myMonacoEditor.editor.getAction('editor.action.formatDocument').run()

**C# code snippet:**
```
using System.ComponentModel.DataAnnotations;
using SampleNamespace.BaseDomain.Enums;
using SampleNamespace.BaseDomain.Interfaces;
using SampleNamespace.BaseDomain.CustomTypes;

namespace SampleNamespace.BaseDomain.Entities.Person
{
    public partial class BaseAddress : IBaseEntity
    {
public int AddressID { get; set; }

public string AddressLine1 { get; set; }

public string AddressLine2 { get; set; }

public string City { get; set; }

public int StateProvinceID { get; set; }

public string PostalCode { get; set; }

public Guid Rowguid { get; set; }

public DateTime ModifiedDate { get; set; }
    }
}
```

**Comment by rcjsuen** [comment]
@HEBOS Monaco does not come with a C# formatter.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/monaco-editor/issues/572
