### ISSUE TITLE
Question: Where to get started to write a custom completion provider?

### ISSUE THREAD

**Issue by nottoseethesun** [Microsoft/monaco-editor#241]
I'd like to write a custom completion provider, to supplement other completion providers active in the editor.  Where is Monaco's API for this, and what is an example?

monaco-editor npm version: 0.X.Y
Browser:
OS:

**Comment by JKillian** [comment]
You can call [`monaco.langauges.registerCompletionItemProvider`](https://github.com/Microsoft/monaco-editor/blob/9ff02988e64369aeffcfe30a60e52ffc6906aa56/website/playground/monaco.d.ts.txt#L3863), to which you provide a language id and a `CompletionItemProvider`. Your `CompletionItemProvider` should just implement [this interface](https://github.com/Microsoft/monaco-editor/blob/9ff02988e64369aeffcfe30a60e52ffc6906aa56/website/playground/monaco.d.ts.txt#L3994L4007). It should be fairly straightforward from there, looking over that typings file is often really helpful.

**Comment by alexandrudima** [comment]
There is also a full working example at https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
