### ISSUE TITLE
Trigger find dialog and set word to find 

### ISSUE THREAD

**Issue by batata004** [microsoft/monaco-editor#2410]
I am having a really hard time to do something that I am pretty sure I must be doing something stupid or most likely is a bug. I just want to trigger the find dialog, set a word in it and make it find that word in the monaco editor. So far I came up with:

```
editor.focus();
editor.trigger('','actions.find');
$(".monaco-findInput").find("textarea").val("WORD");
```

The code above causes this to happen:

![image](https://user-images.githubusercontent.com/8988923/112555391-df936b00-8da6-11eb-9e48-f6ca88e5aee7.png)

Great, the textarea gets populated with the WORD that I want to search. Now I tried to trigger the mousedown/mouseup/click event on the `Next match (Enter)` element but nothing happens. So how do I trigger the find dialog to find the first occurrence of the WORD?

Thanks a lot in advance. I searched a lot on SO and Google but I couldnt find anything about this. I found other people having the same problem, trying other alternatives to fix the problem but none worked on latest version of Monaco Editor.

**Comment by jbharatrhodes** [comment]
May be try this
editor.focus();
editor.trigger('','actions.find');
$(".monaco-findInput").find("textarea").val("WORD");
editor.getAction('actions.findWithSelection').run();

**Comment by batata004** [comment]
@jbharatrhodes thank you so much. I tried your code and it works fine but it does not search for the `WORD` in the document. Actually it looks like 'editor.getAction('actions.findWithSelection').run();` is doing nothing, it does not trigger the "find" or "search" algorithm. Do you have any other suggestion?

**Comment by jbharatrhodes** [comment]
@batata004 I used the following syntax and it is triggering the search
  let range = editor.getModel().findMatches('word')[0].range;
                                editor.setSelection(range);
                                 editor.getAction('actions.findWithSelection').run();

But it is not working for multiple words

**Comment by batata004** [comment]
@jbharatrhodes your suggestion worked PERFECTLY!!! It's a shame that monaco editor does not provide an action specific to do that and the user has to use an alternative method to find some content.

Anyway, I am very glad you helped me, thank you so much!!!
