### ISSUE TITLE
Set language mode popup

### ISSUE THREAD

**Issue by Sparkenstein** [microsoft/monaco-editor#2412]
Currently I don't see the popup to select language in the editor itself.
not sure how vscode does it. I want to have this kind of language selection.

![image](https://user-images.githubusercontent.com/24642451/112712385-36a75600-8ef5-11eb-88d6-da22127b3394.png)

is this doable ootb? According to `microsoft/monaco-languages` it should be doable

**Comment by Sparkenstein** [comment]
I see  #683 is open, I believe this is the same issue. 
So currently there's no way to get this working?

**Comment by alexdima** [comment]
Let's track in #683
