### ISSUE TITLE
Performing TextEdits in custom quickfixes does nothing

### ISSUE THREAD

**Issue by PAX523** [microsoft/monaco-editor#2413]
https://microsoft.github.io/monaco-editor/playground.html

**monaco-editor version:** 0.23.0
**Browser:** Chrome
**OS:** Windows 10
**Description:** I'm trying to provide customized quickfixes for specific circumstances. Even other examples don't work, e.g.: #1548

**Steps to reproduce:**

- Run the snippet
- Hover over `MyClass`
- Perform quickfix `Add import...`
- Expectation: Additional code content was added to the beginning of the document model
- Result: Nothing happens (no changes)

**Playground code that reproduces the issue:**

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "// First line\nfunction hello() {\n\talert('Hello world!');\n}\n// Last line\n\nMyClass",
	language: "typescript",
	scrollBeyondLastLine: false,
	theme: "vs-dark"
});

monaco.languages.registerCodeActionProvider("typescript", {
    provideCodeActions(model, range, context, token) {
        /** @type {monaco.languages.CodeAction[]} */
        const codeActions = [];
        for (const marker of context.markers) {
            const startOffset = model.getOffsetAt({ column: marker.startColumn, lineNumber: marker.startLineNumber});
            const endOffset = model.getOffsetAt({ column: marker.endColumn, lineNumber: marker.endLineNumber});
            const text = model.getValue().substr(startOffset, endOffset - startOffset);

            const markerRange = new monaco.Range(1, 1, 1, 1);
            /** @type {monaco.languages.TextEdit} */
            const importFix = {
                range: markerRange,
                text: `import ${text} = com.example.${text}\n`
            };
            codeActions.push({
                title: `Add import: com.example.${text}`,
                diagnostics: [marker],
                edits: {
                    edit: {
                        edits: [importFix],
                        resource: model.uri,
                    },
                },
                kind: "quickfix"
            });
        }
        return { actions: codeActions, dispose() {} };
    }
});
```

**Comment by spahnke** [comment]
That's because there was a breaking API change in 0.20.0 IIRC. The following works for me in 0.23.0
```js
const editor = monaco.editor.create(document.getElementById("container"), {
    value: "// First line\nfunction hello() {\n\talert('Hello world!');\n}\n// Last line\n\nMyClass",
    language: "typescript",
    scrollBeyondLastLine: false,
    theme: "vs-dark"
});

monaco.languages.registerCodeActionProvider("typescript", {
    provideCodeActions(model, range, context, token) {
        /** @type {monaco.languages.CodeAction[]} */
        const codeActions = [];
        for (const marker of context.markers) {
            const startOffset = model.getOffsetAt({ column: marker.startColumn, lineNumber: marker.startLineNumber });
            const endOffset = model.getOffsetAt({ column: marker.endColumn, lineNumber: marker.endLineNumber });
            const text = model.getValue().substr(startOffset, endOffset - startOffset);

            const markerRange = new monaco.Range(1, 1, 1, 1);
            /** @type {monaco.languages.TextEdit} */
            const importFix = {
                range: markerRange,
                text: `import ${text} = com.example.${text}\n`
            };
            codeActions.push({
                title: `Add import: com.example.${text}`,
                diagnostics: [marker],
                edit: {
                    edits: [{
                        edit: importFix,
                        resource: model.uri,
                    }],
                },
                kind: "quickfix"
            });
        }
        return { actions: codeActions, dispose() { } };
    }
});
```

**Comment by PAX523** [comment]
Thanks, Sebastian!

**Comment by y912765390** [comment]
`

monaco.languages.register({ id: 'mySpecialLanguage' });

monaco.languages.registerHoverProvider('typescript', {
    provideHover: function (model, position) {
        return xhr('../playground.html').then(function (res) {
            return {
                range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
                contents: [
                    { value: '**SOURCE**' },
                    { value: '' }
                ]
            }
        });
    }
});
monaco.languages.registerCodeActionProvider("typescript", {
    provideCodeActions(model, range, context, token) {
        return xhr('../playground.html').then(function (res) {
            const codeActions = [];
            for (const marker of context.markers) {
                const startOffset = model.getOffsetAt({ column: marker.startColumn, lineNumber: marker.startLineNumber });
                const endOffset = model.getOffsetAt({ column: marker.endColumn, lineNumber: marker.endLineNumber });
                const text = model.getValue().substr(startOffset, endOffset - startOffset);

                const markerRange = new monaco.Range(1, 1, 1, 1);
                /** @type {monaco.languages.TextEdit} */
                const importFix = {
                    range: markerRange,
                    text: `import ${text} = com.example.${text}\n`
                };
                codeActions.push({
                    title: `Add import: com.example.${text}`,
                    diagnostics: [marker],
                    edit: {
                        edits: [{
                            edit: importFix,
                            resource: model.uri,
                        }],
                    },
                    kind: "quickfix"
                });
            }
            return { actions: codeActions, dispose() { } };
        });
        /** @type {monaco.languages.CodeAction[]} */
    }
});
monaco.editor.create(document.getElementById("container"), {
    value: '\n\nHover over this text',
    language: 'typescript'
});

function xhr(url) {
    var req = null;
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve('')
        }, 1000)
    })
}

`
If the request takes an unusually long time to get a result, say 1000ms, then moving the mouse will sometimes result in "editor.main.js:8 Uncaught (in promise) Canceled: Canceled." Is there any good way to do that
