### ISSUE TITLE
Custom code indent

### ISSUE THREAD

**Issue by LLZWWY** [microsoft/monaco-editor#2415]
Please tell me how to set custom code indentation according to your own requirements.

**Comment by alexdima** [comment]
I'm not sure what you mean. Do you have a code snippet demonstrating the problem?

**Comment by LLZWWY** [comment]
> 我不太明白你的意思。你有演示这个问题的代码片段吗？



> I'm not sure what you mean. Do you have a code snippet demonstrating the problem?

No code. What I mean is how to set the required code indentation when adding custom syntax?

**Comment by LLZWWY** [comment]
> I'm not sure what you mean. Do you have a code snippet demonstrating the problem?

No code. What I mean is how to set the required code indentation when adding custom syntax?
