### ISSUE TITLE
blang syntax highlighting

### ISSUE THREAD

**Issue by Ganesha2282882** [microsoft/monaco-editor#2422]
# <a href="https://github.com/Ganesha2282882/blang">blang</a> support

blang is a new programming language that I made (yes, it's all `lower()`). Can you add syntax highlighting for it (colors, etc)? I have a mockup made in Google Slides:
![Untitled presentation](https://user-images.githubusercontent.com/59745725/113519623-6ab8f180-955b-11eb-8472-8de894937870.png)
I know that the colors are not exact.
But, blang gets updated way more than Windows 10 Dev insider builds. It's also written in Python 3.

**Comment by Prinzhorn** [comment]
You could add it here https://github.com/microsoft/monaco-languages/tree/main/src but I'm not sure if your own language that is not very widespread will be integrated.

If you want syntax highlighting locally in your Monaco instance you can add a custom language using Monarch https://microsoft.github.io/monaco-editor/monarch.html

**Comment by alexdima** [comment]
I recommend to define the language locally on your side. e.g. https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages
