### ISSUE TITLE
Monaco Editor Home page breaks in Firefox version 77

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2423]
**monaco-editor version:** 0.23.0
**Browser:** Firefox version <= 77 
**OS:** Mac OS

Monaco Editor Home page breaks in Firefox version 77

<img width="1487" alt="Screen Shot 2021-04-05 at 6 30 11 PM" src="https://user-images.githubusercontent.com/29809906/113576561-67963200-963d-11eb-8aba-c923c35de1e5.png">

This seems to be a Bug of Firefox which is reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1361876
And This bug was resolved in Firefox version 78 , Refer the release notes here (https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/78#javascript)

As in my application, we are providing support for Firefox version 77 and due to the above mentioned bug from Firefox, I am not able to include monaco editor into my application 

**Is there any possibility of having a workaround for this issue in monaco editor, So that I can use monaco editor in Firefox version 77 ?** 

_PS : It will be helpful, If there is a table in monaco editor documentation, showing the versions of different browsers from which monaco editor is supported_

**Comment by alexdima** [comment]
I'm sorry it doesn't work in Firefox 77, but we only offer support for the latest browsers. Defining a version matrix is not really possible, as each browser ships new updates every month and we support the latest versions.

If you can track down this issue to a specific regex of the Monaco editor, we are more than welcoming a PR by the community!

I'll close this issue, but if you have specific follow up questions, we'll try to help as good as we can given the limited resources that we have.

Thanks for your understanding!
