### ISSUE TITLE
0.23.0 breaks razor syntax highlighting

### ISSUE THREAD

**Issue by crackalak** [microsoft/monaco-editor#2424]
**monaco-editor version:** 0.23.0
**Browser:** Chrome, Firefox
**OS:** Window 10
**Fiddle that reproduces the issue:**

Monaco 0.23.0 (Broken):
https://jsfiddle.net/3Lrc0q5s/2/

Monaco 0.22.3 (Working):
https://jsfiddle.net/3Lrc0q5s/1/

Syntax highliting for Razor is also broken on the homepage https://microsoft.github.io/monaco-editor/

**Comment by alexdima** [comment]
This is caused by https://github.com/microsoft/vscode/commit/538f72e2a7bbe025363aa4689a2a27d75f5dcac7
