### ISSUE TITLE
completion search

### ISSUE THREAD

**Issue by wanpengxyzz** [microsoft/monaco-editor#2425]
**monaco-editor version:** 0.20.0
**Browser:**chrome
**OS:**windows
**Playground code that reproduces the issue:**

```js
```
in vscode，the completion can input any charactors in the items
![image](https://user-images.githubusercontent.com/1539435/113808183-0df64a80-9798-11eb-82a9-b7337d531fd9.png)

but in monaco-editor, it not works.I must input the first charactors of the items,otherwise the item will disappears.
![image](https://user-images.githubusercontent.com/1539435/113808511-b73d4080-9798-11eb-83cc-ce3d7986b21a.png)

now I just use the filterText to resolve this problem.
Just let filterText = label.split("").join("_")
This is not a good idea.

**Comment by wanpengxyzz** [comment]
Is filterText just support 128 length string? 
the over part does not work.

**Comment by wanpengxyzz** [comment]
Code
`function createDependencyProposals(range) {
    // returning a static list of proposals, not even looking at the prefix (filtering is done by the Monaco editor),
    // here you could do a server side lookup
    return [
        {
            label: '"lodash"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "The Lodash library exported as Node.js modules.",
            insertText: '"lodash": "*"',
            filterText: 'm_a_k_e_g_e_t_r_e_f_u_n_d_b_y_r_e_f_u_n_d_n_o_r_e_q_u_e_s_t_m_a_k_e_g_e_t_rfdasd_e_f_u_n_d_b_y_r_e_f_u_n_d__d_d_1_D_a_o_a_b_d_d_d_d_2',
            range: range
        },
        {
            label: '"express"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Fast, unopinionated, minimalist web framework",
            insertText: '"express": "*"',
            range: range
        },
        {
            label: '"mkdirp"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Recursively mkdir, like <code>mkdir -p</code>",
            insertText: '"mkdirp": "*"',
            range: range
        },
        {
            label: '"my-third-party-library"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "Describe your library here",
            insertText: '"${1:my-third-party-library}": "${2:1.2.3}"',
            insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
            range: range
        }
    ];
}


monaco.languages.registerCompletionItemProvider('json', {
    provideCompletionItems: function(model, position) {
        // find out if we are completing a property in the 'dependencies' object.
        var textUntilPosition = model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        var match = textUntilPosition.match(/"dependencies"\s*:\s*\{\s*("[^"]*"\s*:\s*"[^"]*"\s*,\s*)*([^"]*)?$/);
        if (!match) {
            return { suggestions: [] };
        }
        var word = model.getWordUntilPosition(position);
        var range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn
        };
        return {
            suggestions: createDependencyProposals(range)
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "{\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "json"
});
`
If I input "d1",it works.
If I input "d2",it does not work.

**Comment by wanpengxyzz** [comment]
Can I modify like this?
![image](https://user-images.githubusercontent.com/1539435/113991677-458ef080-9885-11eb-812e-50ffac864e0f.png)
from 128 to 512? is that ok?

**Comment by wanpengxyzz** [comment]
Can monaco editor support an option to modify the max-length?

**Comment by alexdima** [comment]
@wanpengxyzz I'm sorry, but I don't understand what the problem is.
