### ISSUE TITLE
GetPositionAt always returns lineNumber: 1

### ISSUE THREAD

**Issue by andrzejolszak** [microsoft/monaco-editor#2428]
The `ITextModel.getPositionAt(offset: number): Position` seems to always return positions having `lineNumber: 1`, as if disregarding newlines in the text.

**monaco-editor version:** 0.23.0
**Browser:** Chrome  89.0.4389.114
**OS:** Windows 10
**Playground code that reproduces the issue:**
The easiest way to reproduce this is with your "Hello world" sample
```js
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
```
and then try running the below in the js console and notice the resulting wrong lineNumber (and column) for offset 40:
```js
monaco.editor.getModels()[2].getPositionAt(1)
```
> {lineNumber: 1, column: 2}

```js
monaco.editor.getModels()[2].getPositionAt(40)
```
> {lineNumber: 1, column: 41}

**Comment by spahnke** [comment]
The following code works for me. Maybe this construct `monaco.editor.getModels()[2]` returns the wrong model for you?

```js
const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

const model = editor.getModel();
console.log(model.getPositionAt(1));
console.log(model.getPositionAt(40));

// Object { lineNumber: 1, column: 2 }
// Object { lineNumber: 2, column: 22 }
```

**Comment by andrzejolszak** [comment]
You're right, everything is fine when done like in your example!

I think I was getting the model for the "JavaScript" editor instead of for the "result" editor. Actually, it seems the "result" model is not available when running `monaco.editor.getModels()` from the browser's js console, but that's not a problem. Thanks for help, and sorry for misreporting this.
