### ISSUE TITLE
Parameter hints in Monaco editor

### ISSUE THREAD

**Issue by swmachan** [Microsoft/monaco-editor#243]
monaco-editor npm version: 0.6.1
Browser: IE/Chrome
OS: Windows

Issue:

I am looking to implement parameter hints in Monaco editor and found the right APIs to solve this and followed the completion item suggestion example. However, I am unable to achieve what I want so it would be great if you could help me out. I have seen the VSCode parameter hints and it’s very cool so I would like to know how that is implemented.

Here’s some hardcoded example that you can paste in the Monaco playground:

```js
monaco.languages.registerSignatureHelpProvider('csharp', {

	signatureHelpTriggerCharacters: ['('],
	provideSignatureHelp: function(model, position) {

		var textUntilPosition = model.getValueInRange({
			startLineNumber: 1,
			startColumn: 1,
			endLineNumber: position.lineNumber,
			endColumn: position.column
		});

		var match = textUntilPosition.match("(");

		if (match) {
			return [{
				signatures: [{
					label: "parameter1",
					documentation: " this method does blah",
					parameters: [{
						label: "ParamInfo1",
						documentation: "this param does blah"
					}]
				}],

				activeSignature: 1,
				activeParameter:1
			}];
		}
		return [];
	}
});

monaco.editor.create(document.getElementById("container"), {
	value: "",
	language: "csharp",
	parameterHints: true
});
```

**Comment by alexandrudima** [comment]
The `registerSignatureHelpProvider` is the right path here. It is up to you to figure out how to implement this for C# (i.e. create an AST, resolve types, and finally propose the signatures). Here is for example how JavaScript/TypeScript parameter hints are registered to the monaco editor:

https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts#L241
