### ISSUE TITLE
cursor positon wrong or word wrap on wrong posotion 

### ISSUE THREAD

**Issue by MisterTaki** [microsoft/monaco-editor#2430]
**monaco-editor version:** 0.23.0
**Browser:** google
**OS:** only windows
**Playground code that reproduces the issue:**

when I config font family: DejaVuSansMonoBold and on windows platform, this bug will happen...

> cursor positon wrong
![a02eb0a3-aa4f-47c3-83d0-05d12d9a33bb](https://user-images.githubusercontent.com/15980621/114124856-eafaa080-9927-11eb-884f-9486f8ea934d.gif)

> word wrap on wrong posotion
![c6fb0351-b633-4a55-b4a7-d0e8c1332c03](https://user-images.githubusercontent.com/15980621/114124782-c43c6a00-9927-11eb-97e9-c42dde132f58.gif)

```js
// cursor positon wrong
monaco.editor.create(document.getElementById('monaco-editor'), {
  theme: 'vs-dark',
  fontFamily: '"DejaVuSansMonoBold", "Consolas", "Courier New", "Lucida Console", "Microsoft YaHei", "微软雅黑"',
  fontSize: 28,
  minimap: {
    enabled: false,
  },
  scrollBeyondLastLine: false,
  occurrencesHighlight: false,
  matchBrackets: 'never',
  automaticLayout: true,
  wordWrap: 'on',
  selectOnLineNumbers: false,
  renderLineHighlight: 'all',
  renderIndentGuides: false,
  highlightActiveIndentGuide: false,
  renderWhitespace: 'none',
  scrollbar: {
    verticalScrollbarSize: 4,
    horizontal: 'hidden',
  },
  disableMonospaceOptimizations: false,
});

// word wrap on wrong posotion
monaco.editor.create(document.getElementById('monaco-editor'), {
  theme: 'vs-dark',
  fontFamily: '"DejaVuSansMonoBold", "Consolas", "Courier New", "Lucida Console", "Microsoft YaHei", "微软雅黑"',
  fontSize: 28,
  minimap: {
    enabled: false,
  },
  scrollBeyondLastLine: false,
  occurrencesHighlight: false,
  matchBrackets: 'never',
  automaticLayout: true,
  wordWrap: 'on',
  selectOnLineNumbers: false,
  renderLineHighlight: 'all',
  renderIndentGuides: false,
  highlightActiveIndentGuide: false,
  renderWhitespace: 'none',
  scrollbar: {
    verticalScrollbarSize: 4,
    horizontal: 'hidden',
  },
  disableMonospaceOptimizations: true,
});
```

**Comment by alexdima** [comment]
@MisterTaki The editor caches font measurements. When you are using custom fonts, it is possible that the editor is created before the font is finished loading by the browser. In such a case, you can add an event listener to find out when the font finished loading and you can use `monaco.editor.remeasureFonts()`. There are other issues here that describe the technique.
