### ISSUE TITLE
Race condition in showing and hiding the suggestions widget

### ISSUE THREAD

**Issue by limitedmage** [microsoft/monaco-editor#2437]
We are using Monaco to provide syntax highlighting and autocomplete for a search bar. This issue popped up when upgrading from Monaco from 0.18.1 to 0.23.0. When typing very quickly, the Monaco suggestions widget will sometimes get stuck in an empty state when it should be hidden.

Here is a normal screenshot of our autocomplete:

![image](https://user-images.githubusercontent.com/206864/114790608-e1af7080-9d39-11eb-99a4-05f25889fd28.png)

Here is a screenshot of when this bug happens:

![image](https://user-images.githubusercontent.com/206864/114790577-d6f4db80-9d39-11eb-8f93-3f97aa82abb8.png)

I have narrowed down the issue to a race condition in `suggestionWidget.ts`. When showing the widget, [there is a 100ms timeout](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/suggestWidget.ts#L493). However, [hiding is immediate](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/suggest/suggestWidget.ts#L443). Therefore, typing very fast could cause the hiding to happen before the showing.

I was able to fix this by modifing `suggestionWidget.ts` to not add the `visible` class if the widget is in a hidden state. 

```diff
private _show(): void {
	this._status.show();
	this._contentWidget.show();
	this._layout(this._persistedSize.restore());
	this._ctxSuggestWidgetVisible.set(true);

	this._showTimeout.cancelAndSet(() => {
+		if (this._state !== State.Hidden)
			this.element.domNode.classList.add('visible');
			this._onDidShow.fire(this);
+		}
	}, 100);
}
```

**monaco-editor version:** 0.23.0
**Browser:** Latest Chrome/Edge
**OS:** masOS 11
**Playground code that reproduces the issue:** I am still working on a minimal repro for this in the playground.

**Comment by limitedmage** [comment]
Thanks @jrieken for helping get this into vscode! @alexdima what is the process for getting a new monaco-editor release with this fix? Is there a regular train?

**Comment by limitedmage** [comment]
@connor4312 What is needed to get a new Monaco release out with this fix?

**Comment by alexdima** [comment]
We will create a new `monaco-editor` release in the following days.
