### ISSUE TITLE
TypeError: (0 , _stateLocal.create) is not a function 

### ISSUE THREAD

**Issue by MdAbuDarda** [microsoft/monaco-editor#2441]
I am using @monaco-editor/react@3.7.4
![Screen Shot 2021-04-19 at 10 32 39 AM](https://user-images.githubusercontent.com/50475070/115182045-0e2d0900-a0fb-11eb-8ceb-c081f716dd16.png)
 This is my simple code below

```
import MonacoEditor from "@monaco-editor/react";

function CodeEditor() {
  return <MonacoEditor height="400px" />;
}

export default CodeEditor;
```

**Comment by Prinzhorn** [comment]
I _think_ the `@monaco-editor` organization on npm is _not_ official. So your bug report is probably better off in the actual repository at https://github.com/suren-atoyan/monaco-react and not here

**Comment by HristijanGjorgjioski** [comment]
Hello, I issued the same error. Did you solve it?

**Comment by jide** [comment]
I had the same issue. It is caused by monaco-react having an unpinned dep to package state-local. Unfortunately, although the package had minor updates, its api broke.

To fix it, use yarn "resolutions" field: https://classic.yarnpkg.com/en/docs/selective-version-resolutions :

```
{
  ...
  "dependencies": {
    ...
    "state-local": "1.0.1"
  }
  ...
  "resolutions": {
    "@monaco-editor/react/state-local": "1.0.1"
  }
}
```

**Comment by alexdima** [comment]
Please report against the `@monaco-editor/react` npm module / github repo.

**Comment by NinjaAniket** [comment]
try this it will fix the issue. yarn add @monaco-editor/react
