### ISSUE TITLE
How to programmatically trigger "View Problem (Alt + F8)" command?

### ISSUE THREAD

**Issue by dehoward** [microsoft/monaco-editor#2444]
![image](https://user-images.githubusercontent.com/52973358/115326476-2ecc8180-a142-11eb-8841-e8b81a8c7267.png)

There doesn't seem to be an easy way to trigger the Alt+F8 command, am I missing something here?

Similarly, is there a way to trigger the above Problem hover window?

**Comment by jbharatrhodes** [comment]
> ![image](https://user-images.githubusercontent.com/52973358/115326476-2ecc8180-a142-11eb-8841-e8b81a8c7267.png)
> 
> There doesn't seem to be an easy way to trigger the Alt+F8 command, am I missing something here?
> 
> Similarly, is there a way to trigger the above Problem hover window?

I am also looking for similar solution. Did you have any luck?

**Comment by alexdima** [comment]
I think you could try to execute the command `editor.action.marker.next` directly. e.g.
```js
editor.trigger('anystring', `editor.action.marker.next`)
```

**Comment by dehoward** [comment]
awesome, that does it!

for anyone wondering, I found out you can close the marker window using:
```tsx
editor.trigger('', 'closeMarkersNavigation')
```
