### ISSUE TITLE
how to set contextMenu with chinese language when I use ES6;

### ISSUE THREAD

**Issue by DanielDemi** [microsoft/monaco-editor#2446]
![image](https://user-images.githubusercontent.com/20706012/115377136-eaa0b600-a201-11eb-8aba-04de97b1dad9.png)

**Comment by lhpy1986** [comment]
require.config({ 'vs/nls': { availableLanguages: { '*': 'zh-cn' } } });

**Comment by DanielDemi** [comment]
> require.config({ 'vs/nls': { availableLanguages: { '*': 'zh-cn' } } });

I have also see the demo, but it is use with requirejs. I want to use in react with esm mode.
![image](https://user-images.githubusercontent.com/20706012/115514935-35303a00-a2b7-11eb-96b7-fba8a0560906.png)

**Comment by y912765390** [comment]
You will see that the ESM package does not have a Chinese name at all, so I think the ESM format does not support Chinese culture

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/monaco-editor/issues/1514

**Comment by chanelnumberseven** [comment]
I find a way by using 
copy-webpack-plugin https://github.com/chanelnumberseven/monaco-editor-locale/blob/main/README.md
it work for me
