### ISSUE TITLE
TypeError: (0 , _stateLocal.create) is not a function

### ISSUE THREAD

**Issue by darda-ergo** [microsoft/monaco-editor#2447]
![Screen Shot 2021-04-19 at 10 32 39 AM](https://user-images.githubusercontent.com/61325474/115422782-0c5c6600-a21f-11eb-8254-218840b0aff9.png)
I am using react with typescript and monaco@3.7.4 and getting this issue: 

this my simple code:
```
import MonacoEditor from "@monaco-editor/react";

function CodeEditor() {
  return <MonacoEditor height="90vh" />;
}

export default CodeEditor;
```

**Comment by UnkleTayo** [comment]
I am also getting this error using the same version

**Comment by alexdima** [comment]
This looks like an issue for the `@monaco-editor/react` npm module, which is not part of this project.

I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community!

I'll close this issue, but if you have specific follow up questions, we'll try to help as good as we can given the limited resources that we have.

Thanks for your understanding!
