### ISSUE TITLE
Superfluous horizontal scrollbar is shown for hover dialog boxes

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/monaco-editor#245]
monaco-editor npm version: 0.7.0
Browser: IE11/Edge 14
OS: Windows 10 Version 1607

Hi,

I noticed that after updating the Monaco Editor to Version 0.7.0, IE11 and Edge sometimes show a horizontal scroll bar when hovering over variables in TypeScript Mode.

1. Open https://microsoft.github.io/monaco-editor/index.html with IE11 or Edge 14
1. In the Monaco Editor, scroll down to line 111
1. Hover on `canvas`
1. Notice that the dialog box has a horizontal scrollbar with which you can scroll 1 pixel:
![monaco-editor-scrollbar](https://cloud.githubusercontent.com/assets/13289184/19677878/a8694bc0-9a9b-11e6-818b-c72f0fcab613.png)

This does not occur on Chrome or Firefox.

Thanks!

**Comment by alexandrudima** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
Moved to Microsoft/vscode#14541
