### ISSUE TITLE
Monaco > 0.22.0 fails to load in WKWebView on macOS <= 10.15

### ISSUE THREAD

**Issue by andreasbeier** [microsoft/monaco-editor#2457]
I am working on a macOS application (using Objective-C) that uses the WKWebView class to display the Monaco editor. Starting v0.22.0 this stopped working on macOS versions older than 11 (Big Sur). I noticed that on older systems not even Safari can run Monaco, not even on the Playground page.

macOS 11.x: Safari [14.0.3 (16610.4.3.1.7)] & WKWebView work with all Monaco versions.

macOS 10.15.7: Only Safari [14.0.3 (15610.4.3.1.7, 15610)] works with Monaco v0.23.0, WKWebView only works up to v0.21.3.

macOS 10.13.6: Neither Safari [13.1.2 (13609.3.5.1.5)] nor WKWebView work with Monaco v0.23.0. WKWebView only works up to v0.21.3.

A demo project (source [WKWebVIew_Monaco_Test.zip](https://github.com/microsoft/monaco-editor/files/6369605/WKWebVIew_Monaco_Test.zip)) is attached to demonstrate the situation. The app is able to display "every" webpage but fails to display any page including a Monaco editor (if macOS < 11). For example, loading the Playground page shows the loading animation indefinitely.

AppleWebKit seems to be at 605.1.15 for all macOS versions tested (according to the user-agent string).

The Xcode version used to compile the app does not make any difference (tested with Xcode 10.1, 11.6, 12.4).

The only possible problem I could detect so far is an "Invalid regular expression:…" in editor.main.js.
![Loading_Monaco_in_Safari](https://user-images.githubusercontent.com/46492015/115959492-bf251080-a50c-11eb-8df7-5013f3c6d91b.png)

**monaco-editor version:** >= 0.22.0
**Browser:** Safari 13.1.2 / WKWebView
**OS:** macOS < 11

**Comment by Prinzhorn** [comment]
#2432 ?

**Comment by andreasbeier** [comment]
Thanks for directing my to #2432. I have already seen it and I do not think is the same problem. I need Monaco to work in a WKWebView – and I doesn't even load any page with Monaco on it. I mentioned Safari only to point out that Safari shares the same problem.

**Comment by alexdima** [comment]
I think this issue shares the same root cause as #2432
