### ISSUE TITLE
Playground - Semantic token provider - SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by JeanPerriault** [microsoft/monaco-editor#2459]
Hello,
When opening https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-semantic-tokens-provider-example in Safari (version 14 or previous), I have this "SyntaxError: Invalid regular expression: invalid group specifier name" displayed in editor.

This seems linked to "Lookbehind in JS regular expressions", not supported in Safari.
https://caniuse.com/js-regexp-lookbehind

If replacing
```js
const tokenPattern = new RegExp('(?<=\\[)([a-zA-Z]+)((?:\\.[a-zA-Z]+)*)(?=\\])', 'g');
```
with simpler
```js
const tokenPattern = new RegExp('([a-zA-Z]+)((?:\\.[a-zA-Z]+)*)', 'g');
```
this works (at least in Chrome and Safari for macOS).

I could PR this but I'm not sure why brackets are used in original regex.

**monaco-editor version:** 0.23.0
**Browser:** Safari 14.1
**OS:** macOS Catalina 10.15.7

**Comment by hediet** [comment]
Thanks for pointing this out! That playground demo is an example, and in this particular implementation only text within brackets should be highlighted.

As this is not relevant for demoing the semantic tokenization, feel free to file a PR! We'd be happy to merge your fix.
