### ISSUE TITLE
Monaco Editor throws error in Safari Version <= 13.1.2 and fails to load

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2461]
**monaco-editor version:** 0.23.0
**Browser:** Safari
**OS:** Mac OS High Serra 10.13.6 

Home Page of Monaco Editor breaks 

<img width="1663" alt="Screen Shot 2021-04-29 at 5 42 50 PM" src="https://user-images.githubusercontent.com/29809906/116549006-98067e80-a912-11eb-865f-26e598f77c90.png">

This seems to be occurring due to a feature ( escaped character for unicode pattern ) that is not supported by Safari in its previous versions.
 However, the issue is fixed in Safari Version 14.0.3.

**Comment by johnnypesola** [comment]
Latest working release of `monaco-editor` seems to be `0.21.3`

**Comment by Pranomvignesh** [comment]
Oh.. Thanks, @johnnypesola for updating me. 
I guess if I downgrade monaco to 0.21.3, it may throw some error in my application as I am using `monaco.editor.onDidChangeMarkers` which is released in 0.22.0 
So I can't use 0.21.3

**Comment by hediet** [comment]
I think this is related to #2465.

**Comment by alexdima** [comment]
This will be fixed via https://github.com/microsoft/vscode/commit/195d369ad64887bfe1cfd98044b7ea976a7c3a2c
