### ISSUE TITLE
Java validation and LSP support

### ISSUE THREAD

**Issue by suneethar** [microsoft/monaco-editor#2462]
Hi,

How can I add java language support for monaco editor, is it possible to write linter and use that for java.
Can I connect LSP for java with monaco

Thanks,
Suneetha R

**Comment by rcjsuen** [comment]
> How can I add java language support for monaco editor, is it possible to write linter and use that for java.

This is doable but a lot of work.

> Can I connect LSP for java with monaco

I imagine most people go down this route instead and leverage the [TypeFox/monaco-languageclient project](https://github.com/TypeFox/monaco-languageclient).

**Comment by y912765390** [comment]
Can you teach me how to use LSP I know this but I can't use it

**Comment by y912765390** [comment]
> Hi,
> 
> How can I add java language support for monaco editor, is it possible to write linter and use that for java.
> Can I connect LSP for java with monaco
> 
> Thanks,
> Suneetha R
Can you teach me how to use LSP I know this but I can't use it
