### ISSUE TITLE
webpack build failed when chunks monaco-editor 

### ISSUE THREAD

**Issue by yazansalhi** [microsoft/monaco-editor#2465]
Build failed with errors.
ERROR in chunk 43
static/js/[id].[chunkhash].js
SyntaxError: Invalid regular expression: /(\p{Ll})(\p{Lu})/: Invalid escape

--
I found it caused by
 editor.main.js 

`.replace(/(\p{Ll})(\p{Lu})/gmu, '$1_$2')
  .replace(/([^\b_])(\p{Lu})(\p{Ll})/gmu, '$1_$2$3')
  .toLocaleLowerCase());`

**monaco-editor version: 0.22.* or 0.23.*
**monaco-editor-webpack-plugin: 3.*.*

its build and worked fine with chunks on other old versions of monaco-editor and monaco-editor-webpack-plugin

**Comment by alexdima** [comment]
This will be also fixed by https://github.com/microsoft/vscode/commit/195d369ad64887bfe1cfd98044b7ea976a7c3a2c
