### ISSUE TITLE
Provide a way to customize the CSS "cursor" controlling the mouse pointer image

### ISSUE THREAD

**Issue by octogonz** [microsoft/monaco-editor#2467]
I'm trying to implement a feature that hides the mouse cursor while the person is typing, to avoid an annoyance where you cannot see what you are typing when the mouse cursor is in the way.

Could we provide an API for customizing the mouse pointer image for the Monaco editor?

## Details
The CSS [cursor](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) property for the Monaco editor seems to be always hard-wired to `monaco-mouse-cursor-text` [by this code](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/editor/browser/viewParts/lines/viewLines.ts#L138):
```ts

		PartFingerprints.write(this.domNode, PartFingerprint.ViewLines);
		this.domNode.setClassName(`view-lines ${MOUSE_CURSOR_TEXT_CSS_CLASS_NAME}`);
		Configuration.applyFontInfo(this.domNode, fontInfo);
```

It would be nice if there was an API for reassigning this value.

I tried to override it using `deltaDecorations()` but it does not work for empty regions outside the editor text content.

**Comment by spahnke** [comment]
AFAICT the DOM node for the view lines that has the mouse cursor class is only added once. So would something like this work where you just remove the standard class and add a class for a hidden cursor while the user is typing (replace the interval with your "the user is currently typing" logic)?
```js
const editor = monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript"
});

let shouldShowCursor = true;
setInterval(() => {
    shouldShowCursor = !shouldShowCursor;
    showCursor(shouldShowCursor);
}, 3000);

function showCursor(value) {
    const standardCursorClass = 'monaco-mouse-cursor-text';
    const hiddenCursorClass = 'monaco-mouse-cursor-text-hidden';
    const editorDom = editor.getDomNode();
    const viewLines = editorDom.querySelector('.view-lines');
    viewLines.classList.add(value ? standardCursorClass : hiddenCursorClass);
    viewLines.classList.remove(value ? hiddenCursorClass : standardCursorClass);
}
```

And corresponding CSS
```css
.monaco-mouse-cursor-text-hidden {
    cursor: none;
}
```

**Comment by hediet** [comment]
I think something similar to what @spahnke suggested is the way to go.
Unless there is a high demand for this feature, I don't think this use case alone justifies another config option, especially if there is a workaround.
Please let us know if @spahnke's suggestion works for you!
