### ISSUE TITLE
Title of Keybindings are not OS specific

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2468]
**monaco-editor version:** 0.23.0
**Browser:** Chrome
**OS:** Mac OS

In the title of the Keybinding, the `Option` Key in the Mac OS is labeled as `Alt`

### Screenshot from monaco editor homepage:

<img width="831" alt="Screen Shot 2021-05-05 at 6 10 21 PM" src="https://user-images.githubusercontent.com/29809906/117142923-e235a700-adcd-11eb-8025-ccc1bb387422.png">

**Comment by andreasbeier** [comment]
alt is used on older keyboards. Why not get rid of the tooltip? The picts speak for themselves.
