### ISSUE TITLE
automatic folding 

### ISSUE THREAD

**Issue by alexec** [microsoft/monaco-editor#2469]
I've some code that I present either as JSON or YAML. It is a Kubernetes manifest. In v1.16 of Kubernetes they introduced a feature called `managed fields` which 3x the size of the document, but users cannot edit it. I'd like to have it automatically folded out of sight.

Any suggestions on how I could do this please?

**Comment by hediet** [comment]
You can implement a [folding range provider](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.foldingrangeprovider.html#providefoldingranges).

Then you can use one of the [`editor.fold*`](https://code.visualstudio.com/api/references/commands) commands to toggle the folding state.
