### ISSUE TITLE
keybindingContext not working

### ISSUE THREAD

**Issue by gujiman** [Microsoft/monaco-editor#247]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: windows 7

Hi,

I'm trying to set:

keybindingContext: "Ctrl+/",

into the following example:

https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance

but it doesn't seem to show up in the contextmenu.

Infact keybindingContext doesnt seem to be defined in the main monaco script, but its documented in monaco.d.ts.

**Comment by gujiman** [comment]
I also noticed that setting context menu item still gets displayed in readOnly mode when setting contextMenuGroupId: '1_modification'.

**Comment by alexandrudima** [comment]
`keybindingContext` can be used to define a condition when the keybinding should be triggered

e.g. `keybindingContext: "findWidgetVisible"` will make the keybinding of the action you add run only if the find widget is visible.
