### ISSUE TITLE
Syntax error is gone when adding new line

### ISSUE THREAD

**Issue by galyech** [microsoft/monaco-editor#2472]
**monaco-editor version: 0.23.0**
**Browser: Chrome Version 90.0.4430.93 (Official Build) (32-bit)**
**OS: Windows 10**

When typing a syntax error :
![image](https://user-images.githubusercontent.com/29915265/117570915-0991ba00-b0d5-11eb-9509-09ffc34c3ded.png)

And then adding new lines and typing a new syntax error:
![image](https://user-images.githubusercontent.com/29915265/117570917-10203180-b0d5-11eb-8e43-9e0aa0ff7bf3.png)

I see that the first syntax error is gone and never returns , even when I move the focus back to the first word. 
![image](https://user-images.githubusercontent.com/29915265/117570933-25955b80-b0d5-11eb-9653-1ab7829dcfa5.png)

This is very confusing. can you please fix that? it will be very appreciated.

**Comment by rcjsuen** [comment]
![image](https://user-images.githubusercontent.com/15629116/117575591-81012280-b0b0-11eb-9e59-3a10b0f1b330.png)

@galyech The error checking function seems fine to me. How can your error be reproduced?

**Comment by galyech** [comment]
Thanks for your quick reply
we use the monaco editor for running Kusto queries. 

here's a [link ](https://logsextension.hosting.portal.azure.net/logsextension/az/1.0.2339.0/blades/DemoLogsBlade.en.html?clientOptimizations=false&l=en.en-us&trustedAuthority=https%3A%2F%2Fms.portal.azure.com&azscript=https%3A%2F%2Fms.portal.azure.com%2FContent%2FDynamic%2F_K4Y8JVgCMFQ.js&extensionName=Microsoft_Azure_Monitoring_Logs#%7B%7D)to our demo environment where it reproduces. please let me know if you are able to reproduce it. 
I also see it in other website that uses Kusto over monaco. can it be related to the language setting?

**Comment by rcjsuen** [comment]
@galyech Yes, I can reproduce it. However, without knowing what your code looks like it is hard to comment. Sounds more like an issue with the Kusto integration to me.
