### ISSUE TITLE
Can't open links from hover popup when inside an Iframe

### ISSUE THREAD

**Issue by galyech** [microsoft/monaco-editor#2474]
**monaco-editor version:** 0.15.4
**Browser: Chrome Version 90.0.4430.93 (Official Build) (32-bit)**
**OS: Windows 10**
**Playground code that reproduces the issue:**
```js
export var svgNS = 'http://www.w3.org/2000/svg';
```

![image](https://user-images.githubusercontent.com/29915265/117634633-c8a6ad80-b187-11eb-89a6-ba234f909787.png)

When I open links from popup hover, I get the following error:
The frame attempting navigation is sandboxed and is trying to navigate a popup, but is not the popup's opener and is not set to propagate sandboxing to popups.
 
windowOpenNoOpener @ dom.js:862
global-errors.service.ts:29 Error: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to 'http://www.w3.org/2000/svg'.
 
Error: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to 'http://www.w3.org/2000/svg'.
    at Module.windowOpenNoOpener (dom.js:862)
    at Object.openExternal (openerService.js:116)
    at OpenerService.<anonymous> (openerService.js:174)
    at Generator.next (<anonymous>)

the exception is thrown from this location:
![image](https://user-images.githubusercontent.com/29915265/117632538-e83cd680-b185-11eb-9e61-3e29821dd2df.png)

I can't repro it in Monaco playground as our website is located in a sandboxed IFrame. 
Is there a possibility to add configuration for us to open it in the standard way (window.open()) ?it works that way for us.

**Comment by spahnke** [comment]
Regarding the fix @alexdima:

The `windowOpenNoOpener` function has a boolean return value that's determined by the return value of `window.open()`. But according to the linked MDN article (https://developer.mozilla.org/en-US/docs/Web/API/Window/open#noopener) "[...] the window.open() call will also return null, so the originating window will not have access to the new one either". What implications does this have for callers of the `windowOpenNoOpener` function that will now presumably get the return value `false` even if the window/tab was opened successfully?

```ts
export function windowOpenNoOpener(url: string): boolean {
	// By using 'noopener' in the windowFeatures argument, the newly created window will
	// not be able to use window.opener to reach back to the current page.
	// See https://stackoverflow.com/a/46958731
	// See https://developer.mozilla.org/en-US/docs/Web/API/Window/open#noopener
	const newTab = window.open(url, '_blank', 'noopener');
	if (newTab) {
		return true;
	}
	return false;
}
```

**Comment by alexdima** [comment]
@spahnke Thank you for catching this, this is indeed an oversight.
