### ISSUE TITLE
Type disappearing when nested

### ISSUE THREAD

**Issue by bodinsamuel** [microsoft/monaco-editor#2478]
**monaco-editor version:** 0.24.0
**Browser:** Chrome Version 90.0.4430.212 (Official Build) (x86_64)
**OS:** mac OS 11.3.1
**Playground code that reproduces the issue:** https://github.com/bodinsamuel/monaco-editor-test
```
git clone
yarn
yarn start
http://localhost:3000
```

--- 
Hello,

I'm don't know if it's a bug or something wrong with my setup, probably the later but I ran out of ideas.
I have setup a repo to test some stuff more quickly than in my work monorepo at Algolia.
I mostly played around loading external packages and stuff, so that we can improve our usage of monaco in our dashboard.

I came across something weird, I load the newest version of cheerio which has built-in Typescript definition.
When I import it in my main editor the type is there and works perfectly,
however when I import it in an other d.ts file, the type become `: any`. 

<img width="702" alt="Screen Shot 2021-05-13 at 23 37 15" src="https://user-images.githubusercontent.com/1637651/118191159-73e38b00-b444-11eb-978e-0f358bb723cc.png">
<img width="460" alt="Screen Shot 2021-05-13 at 23 37 36" src="https://user-images.githubusercontent.com/1637651/118191155-72b25e00-b444-11eb-9d33-c28b558fa62b.png">

As you can see the import works:
```ts 
import { CheerioAPI, load} from 'cheerio';
```
but `$` is typed `any` whereas it import the same package.

If I replace the nested import by an other package or an other type it works (I tried with a random one `parse-json`).
I don't know what is wrong and I don't know how to access debug information (if any, can you provide a way to access that please 🥺).
Maybe it's perfectly normal maybe not, I really don't know and no error are triggered or anything.

---
 
Second note: While trying to find more info, I saw that the playground of typescriptlang.org seems to use TSVFS, 
should I just switch to that?

--- 

Thanks a lot for any future help.
Best Regards,

**Comment by bodinsamuel** [comment]
Turns out importing with `/tmp/config` instead of `./tmp/config` was wrong 🤦🏻 
I don't get why, because `/` is the root of the virtual FS I suppose, but it seems not

**Comment by alexdima** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community!

Thanks for your understanding!

**Comment by bodinsamuel** [comment]
No worries, completely understandable. 
I'll close anyway, my immediate problem is solved. 
There might be a confusion with the in the code or documentation about the root `/` and its behavior, but nothing breaking.
