### ISSUE TITLE
KeyCode for the `Control` key in MacOS

### ISSUE THREAD

**Issue by Nirajn2311** [microsoft/monaco-editor#2479]
Is there a KeyCode for the `Control` key in Mac Devices as `CtrlCmd` recognizes only the `Command` key and `Ctrl` keycode wasn't being recoginzed.

**Comment by spahnke** [comment]
Something like `monaco.KeyMod.WinCtrl | monaco.KeyCode.KEY_F` should work. `CtrlCmd` means the Ctrl key on Windows  and the command key on macOS. `WinCtrl` means the Windows key on Windows and the control (^) key on macOS, IIRC.

**Comment by Nirajn2311** [comment]
Ahh, didn't realise `WinCtrl` was `Control` in Mac.

**Comment by alexdima** [comment]
PR welcome to improve the docs. That particular symbol is defined [here](https://github.com/microsoft/vscode/blob/414e5dbf1f870bc527ebc587cbbb5f6eee9bfba6/src/vs/editor/common/standalone/standaloneBase.ts#L20).
