### ISSUE TITLE
.rst (restructured text) files freezes the page

### ISSUE THREAD

**Issue by AlexandraVarfolomeyeva37** [microsoft/monaco-editor#2484]
Reproduces at the Monaco Editor homepage:
 -- https://microsoft.github.io/monaco-editor/
**Browser:** Edge, Chrome
**OS:** Windows 10
**Playground code that reproduces the issue:** 
Restructured file:
```restructured file
some property = Text::ProxyLibrary::ProxyInterfaceTest::DeleteProxyInterface();
```
Causes the UI to become unresponsive or event to freeze and after some time web browser pops up a modal dialog “Page isn’t responding - Wait - Exit Page”.
![image](https://user-images.githubusercontent.com/79906530/118506897-64ab5880-b736-11eb-9d7c-8663f192f86a.png)

In a long file, it takes a lot of time to load even if you choose the _wait_ option several times.

**Comment by alexdima** [comment]
By breaking the JS execution, I could see the tokenizer is stuck on this rule -- https://github.com/microsoft/monaco-languages/blob/319a1ddf568438d59a3851784b092cdf1f88e29e/src/restructuredtext/restructuredtext.ts#L127

It looks like that particular regular expression is suffering from catastrophic backtracking.

**Comment by qwefgh90** [comment]
I will find out how this bug can be fixed.
