### ISSUE TITLE
Problems pop-up gets cutoff if parent div has overflow: hidden

### ISSUE THREAD

**Issue by dehoward** [microsoft/monaco-editor#2485]
We have a use case similar to Azure DevOps where we render the editor within a card `div` that applies `overflow: hidden`.
This causes the below problem where the Problems pop-up gets cutoff by the parent `div`:
![image](https://user-images.githubusercontent.com/52973358/118588379-1e182700-b753-11eb-8d17-d19cf48b1179.png)

Is there any possible workaround for fixing this? We want to avoid overriding internal classes of the editor if we can.

HTML to reproduce in playground:
```html
<div style="margin: 3rem; overflow: hidden; height:100%;">
    <div id="container" style="height:100%;"></div>
</div>
```

**Comment by spahnke** [comment]
You can set `fixedOverflowWidgets: true` in the editor options.
