### ISSUE TITLE
API for getting Line and Column given (x, y) mouse position

### ISSUE THREAD

**Issue by sergiusignacius** [Microsoft/monaco-editor#249]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Windows

Hey guys,

I'm currently embedding Monaco inside a WPF control. This control handles all drag and drop behaviors and needs to ask the editor, on demand, what is the text Position (line and column) given a (x, y) mouse coordinate.

I previously used Ace in this control, which I am ditching for Monaco - which kicks its ass in many ways -, but had an API for this specific use case.

Could such an API exist?

Thanks,

**Comment by ChrisFan** [comment]
Come across the same issue, it would be nice that Monaco could offers such kind of APIs.
I think there're two workarounds:

1. fake the drag/drop，which means we can trigger the 'mouseover' event on the other hand
2. calculate the lineNumber/column based on current x, y by analyzing the editor Dom elements

Tried a little bit of workarounds 2:
```jsx
import React from 'react';
import { findDOMNode } from 'react-dom';
import { DropTarget as dropTarget } from 'react-dnd';
import throttle from 'lodash.throttle';
import styles from './Editor.css';

const DRAG_DROP_TYPE = 'COMPONENTS';
let $$linesData = window.$$linesData; // need to clear when editor scroll/zoom
const getLinesDataFromEditorDom = () => {
  if (!$$linesData) {
    $$linesData = {
      lines: [],
    };
    const viewLinesWrapper = document.getElementsByClassName('view-lines')[0];
    if (viewLinesWrapper.children) {
      for (let i = 0, len = viewLinesWrapper.children.length; i < len; i++) {
        $$linesData.lines.push({
          top: viewLinesWrapper.children[i].style.top,
          height: viewLinesWrapper.children[i].style.height,
          lineNumber: viewLinesWrapper.children[i].attributes.linenumber.value,
        });
      }
    }
  }

  return $$linesData;
};

let throttled;
const targetSpec = {
  hover(props, monitor, component) {
    const lines = getLinesDataFromEditorDom().lines;
    const clientOffset = monitor.getClientOffset();
    const componentRect = findDOMNode(component).getBoundingClientRect();
    const x = clientOffset.x - componentRect.left - 46; // TODO
    const y = clientOffset.y - componentRect.top;

    const currentLine = lines[Math.floor(y / parseInt(lines[0].height, 10))];
    if (!currentLine) return;

    const lineNumber = parseInt(currentLine.lineNumber, 10);
    const column = Math.floor(x / 7.22);  // TODO;
    if (!throttled) {
      throttled = throttle(
        props.setCursor,
        100
      );
    }
    throttled(lineNumber, column);
  },
};

const collect = (connect, monitor) => {
  return {
    connectDropTarget: connect.dropTarget(),
  };
};

class EditorDropLayer extends React.Component {
  render() {
    return this.props.connectDropTarget(
      <div className={styles.editorContainer}>
        {this.props.children}
      </div>
    );
  }
}

export default dropTarget(DRAG_DROP_TYPE, targetSpec, collect)(EditorDropLayer);
```

The main problem of workarounds 2 is column calculation is not accurate!  It totally depends on fonts. Looks like workarounds 1 would be better ? Haven't dig into Monaco's source code, maybe there's better solutions ?

**Comment by sergiusignacius** [comment]
Hey @ChrisFan,

I was thinking about digging a bit on Monaco's source code to see how, for example, the tooltips are rendered when you hover on an identifier (e.g. the ones that show the type of a given symbol). They need to render close to where the mouse is, so maybe that's a good clue.

I'll likely start exploring the code a bit on Friday.

Also, would be nice to hear from Monaco guys on this. :)

**Comment by joaomoreno** [comment]
This information seems to only be available through the mouse events the editor emits. The method [`createMouseTarget`](https://github.com/Microsoft/vscode/blob/scm-api/src/vs/editor/browser/controller/mouseTarget.ts#L222) is able to return `IMouseTarget` objects with this information, but it currently requires an instance of `EditorMouseEvent` as a parameter, which is tough to get from a simple `x,y` pair.

Digging deeper, the only properties needed out of the `EditorMouseEvent` instance are:

```
posx
posy
editorPos.top
editorPos.left
viewportx
viewporty
```

You could create an interface `IEditorMouseSource` with those properties and make the whole stack starting from `createMouseTarget` accept that instead of `EditorMouseEvent`.

Then you'd just have to find a way to construct one of those babies our of a `x,y` pair. That shouldn't be too hard. 👍

**Comment by sergiusignacius** [comment]
Thanks João.

I've done what you suggested. So far so good!

From what I gathered, the logic that creates the correct editor position is at MouseEventFactory [_unsafeCreateMouseTarget](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/controller/mouseTarget.ts#L231). There seem to be a lot of different cases for creating an IEditorMouseSource (related to hit testing). I can't simply move this to the editor... Am I missing something?

Thanks!
