### ISSUE TITLE
npm module require

### ISSUE THREAD

**Issue by EvgeniBR** [microsoft/monaco-editor#2490]
Hi , is there away to load npm packages by using Monaco editor? 
![monaco capture](https://user-images.githubusercontent.com/68813924/118967162-0c14cf00-b973-11eb-8790-61f3cbaf77e6.PNG)

**Comment by orta** [comment]
Yep, you'd need to bundle the JS and set up the runtime for it to run. Then for auto-complete you need to add the node_modules to Monaco's file maps for the JS language.

**Comment by EvgeniBR** [comment]
can you send a screen shot or code example?

**Comment by hediet** [comment]
I'm sorry, but there is nothing we can do about it in the monaco editor.
Feel free to ask your question on StackOverflow!

@orta's approach could work though.
