### ISSUE TITLE
C++ comment highlighing doesn't support continuation backslashes 

### ISSUE THREAD

**Issue by mattgodbolt** [microsoft/monaco-editor#2497]
Code such as:

```c++
// I am a comment \
and this is still part of the comment
```

...is not interpreted as a two-line comment.

See compiler-explorer/compiler-explorer#2682

**Comment by hediet** [comment]
Thanks for reporting! This is a bug in the [C++ tokenizer](https://github.com/microsoft/monaco-languages/blob/main/src/cpp/cpp.ts).

Unfortunately, we don't have the resources to address this right now, but we're more than happy to accept a PR for this!

**Comment by alexdima** [comment]
This was fixed in the meantime via https://github.com/microsoft/monaco-languages/pull/143
