### ISSUE TITLE
Keybinding & bubbling

### ISSUE THREAD

**Issue by ptyork** [Microsoft/monaco-editor#25]
If, for example, I bind a command to Ctrl+S:

```
var myBinding = editor.addCommand([monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_S], function() {
    alert('SAVE pressed!');
});
```

The command runs, but the key combination also bubbles up to the browser, prompting me to save the page. Does the same thing if I use addAction as well. Tried returning false, etc. Any way to prevent bubbling?

For what it's worth, I tried:

```
    editor.onKeyDown(function (e) {
      if (e.ctrlKey && e.keyCode === monaco.KeyCode.KEY_S) {
        e.preventDefault();
      }
    });
    editor.onKeyUp(function (e) {
      if (e.ctrlKey && e.keyCode === monaco.KeyCode.KEY_S) {
        e.preventDefault();
      }
    });
```

**Comment by alexandrudima** [comment]
@ptyork Your code works for me if I don't use an array:

```js
var myBinding = editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_S, function() {
    alert('SAVE pressed!');
});
```

**Comment by ptyork** [comment]
Let me clarify that this is with FF. Seems to work without issue in Chrome and Edge (Edge seemingly not pre-binding Ctrl+S). And works with or without the array for me anyway.

Incidentally, while I think this may be a real bug, is there a discussion forum for this so that I don't clutter the issue log with other questions?

**Comment by alexandrudima** [comment]
Ok, I could reproduce in FF. I have debugged into the `keybindingServiceImpl` and we do call `e.preventDefault()`. Here is what I could find, seems to be a problem with FF and calling `alert`: http://stackoverflow.com/questions/14860759/cant-override-ctrls-in-firefox-using-jquery-hotkeys/14861031#14861031

So changing your snippet to the following works for me:
```js
var myBinding = editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_S, function() {
    console.log('SAVE pressed!');
});
```

We haven't set up a forum, so please feel free to continue creating issues. I don't think that is a problem, the main advantage is that they are searchable.

**Comment by ptyork** [comment]
Ah, good find! Works perfectly for me, as well. Thanks!!

**Comment by ChrisFan** [comment]
is it possible to bind `[⌘K W]` ?

```javascript
editor.addCommand(CtrlCmd | KEY_K | KEY_W, () => {
  // this is not working
});
```

**Comment by alexandrudima** [comment]
@ChrisFan You can do a chord like this:

```js
var KM = monaco.KeyMod;
var KC = monaco.KeyCode;
editor.addCommand(KM.chord(KM.CtrlCmd | KC.KEY_K, KM.CtrlCmd | KC.KEY_M), function() {
 //...
});

```

**Comment by manideepmothe641** [comment]
THANKS & IT WORKS LIKE CHARM
