### ISSUE TITLE
No word-wrapping on error quickinfo 

### ISSUE THREAD

**Issue by kpreisser** [microsoft/monaco-editor#250]
monaco-editor npm version: 0.7.0
Browser: Chrome, Firefox, Edge, IE 11
OS: Windows 10

Hi,
I noticed that in Monaco Editor 0.7.0, when using TypeScript mode and hovering about a error marker, the editor seems to cut the line at a fixed position, instead of doing word-wrapping like in the previous version.
1. Open https://microsoft.github.io/monaco-editor/index.html
2. In the editor, write the following script:

``` typescript
class A  {
    constructor() {
        let package;
    }
}
```

3. Hover over the red marker at `package`
4. Notice that the word **"mode"** is cut:
![monaco-hover-wordwrap](https://cloud.githubusercontent.com/assets/13289184/19830690/4fcd12c0-9dfd-11e6-9268-74665b563d3d.png)

Note: Where the line is cut may depend on the used browser and font settings.

Thanks!

**Comment by alexandrudima** [comment]
I cannot reproduce this anymore.
