### ISSUE TITLE
JavaScript without the TypeScript worker

### ISSUE THREAD

**Issue by pimterry** [microsoft/monaco-editor#2501]
I'd like to support JavaScript in my editor, but the TypeScript worker is _enormous_ and uses quite a bit of memory too (#2419, #1987). I'm happy to concede features for this: really I just want basic syntax highlighting and syntax errors for plain JavaScript, I don't need any of the autocomplete or actual type information at all.

Is there any way at all to do this? If not today, is this something you might be open to in future?

**Comment by orta** [comment]
I'm afraid this isn't feasible because the JavaScript worker and the TypeScript worker are the same thing just with a different name and compiler settings, you'd need to create new JS language support completely if you wanted a bared down version

**Comment by pimterry** [comment]
Are you open to making it that easier? It's clearly causing problems for other users too, as in the issues linked above. I suspect lightweight syntax editing for JS is a fairly common use case which doesn't seem especially unreasonable imo.

I've looked at monaco-typescript to try and do this for myself, but it appears to just be one monolithic 8MB file, so I'm not sure where to start! Any tips would be very welcome :smiley:.

**Comment by orta** [comment]
I don't maintain Monaco-editor, so I can't speak for them, but shipping with working JS/CSS/JSON/HTML support makes a lot of sense for Monaco-editor. I'd be requesting a version of Monaco-editor which ships with no language support, and that you're expected to add any language support yourself.

You'd basically want to replace monaco-typescript completely, you'd need to write your own AST parser and syntax errors etc - it's a lot of work but maybe you could just throw eslint + prettier in there and call it a day. Personally, I wouldn't recommend it, but I work on TypeScript, so I'm biased.

**Comment by hediet** [comment]
As @orta pointed out, this is not that easy to do.

You can reuse the syntax highlighting from [monaco-languages](https://github.com/microsoft/monaco-languages), but for syntax errors you have to either use the full blown TypeScript parser or something else.

Unfortunately, this is nothing on our roadmap.
