### ISSUE TITLE
renderWhitespace defaults to "selection", not "none"

### ISSUE THREAD

**Issue by richardtallent** [microsoft/monaco-editor#2502]
The documentation says that `renderWhitespace` defaults to `none`.

However, I noticed in my code that it is defaulting to `selection`. I confirmed this by opening an empty playground and selecting some text. Setting this option to `none` manually resulted in the expected behavior.

**monaco-editor version:** 0.24.0
**Browser:** Chrome (latest)
**OS:** Windows 10
**Playground code that reproduces the issue:** https://microsoft.github.io/monaco-editor/playground.html

**Comment by hediet** [comment]
Nice catch and thanks for reporting! Feel free to do a PR on the VS Code repository that fixes the documentation! I'll help you to get it merged.

**Comment by richardtallent** [comment]
Thanks @hediet, I'd be happy to!

I would have already, but I can't actually *find* the repository that houses the docs. It's not listed in the contribution guidelines, doesn't appear to be in this repo, and I struck out searching for it:

https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md
https://github.com/microsoft?q=monaco&type=&language=&sort=

Here's where it appears in the docs, but there's also no GitHub link there:

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#renderwhitespace

**Comment by hediet** [comment]
Awesome! This repo does not contain the actual source code, it is all in the VS Code repo (the contribution guidelines should say so, if not, we need to update that).

I guess you mean the JS Doc? I think the source for it is [here](https://github.com/microsoft/vscode/blob/fe1eafc80c07608de52a2f9c99fee103dea77f5e/src/vs/editor/common/config/editorOptions.ts#L570).

**Comment by richardtallent** [comment]
Thanks! That makes more sense now. I saw that file, but thought it was auto-generated from something else. Always a challenge to find one's way around a massive codebase for the first PR! :)

**Comment by hediet** [comment]
Understandably. Feel free to ping me in your PR against the VS Code repository!
