### ISSUE TITLE
fixedOverflowWidgets=true makes suggestion widget shows at a wrong location when monaco-editor is hosted inside fluent Callout control

### ISSUE THREAD

**Issue by weizhang-ms** [microsoft/monaco-editor#2503]
https://codesandbox.io/s/affectionate-satoshi-ywlnk?file=/src/App.js

The Monaco-editor is placed inside a fluent Callout control (https://developer.microsoft.com/en-us/fluentui#/controls/web/callout)

**fixedOverflowWidgets=true** - suggestion widget shows at a wrong location (left is correct, top is incorrect)

![image](https://user-images.githubusercontent.com/81582911/119740217-619c2080-be38-11eb-9b4b-ccfcb7881aba.png)

**fixedOverflowWidgets=false** - suggestion widget shows at the right position, but it doesn't show complete...

![image](https://user-images.githubusercontent.com/81582911/119739948-e175bb00-be37-11eb-82c6-1dc59eef0c6d.png)

**Comment by weizhang-ms** [comment]
My workaround is to change the Callout style to `overflow: 'visible'`, and set monaco-editor options `fixedOverflowWidgets: false`

```
                    <Callout
                      styles={{
                        root: {
                          width: 400,
                          padding: 20
                        },
                        calloutMain: {
                          // NOTE: This is a workaround to show formula bar inside Callout
                          overflow: 'visible'
                        }
                      }}
```

**Comment by dehoward** [comment]
We're noticing the same issue when using the [fluent Panel](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel).

[sandbox](https://codesandbox.io/s/strange-worker-4669l?file=/src/App.js)

Notice that when the Editor is inside the Panel, the read-only widget appears in the wrong place:
![image](https://user-images.githubusercontent.com/52973358/132071492-a84d52b8-332d-42e9-bbad-7617e63be966.png)

But when outside, the widget is correctly placed:
![image](https://user-images.githubusercontent.com/52973358/132071555-2c92b38b-b4b1-4523-83c6-6c51c4f26608.png)

**Comment by y6936** [comment]
After some investigation I found out that the animation on the callout/panel is causing the issue.
As a workaround you could set the animationName to 'none' on the Panel or Callout styles to get rid of the 
animation which fixes the problem.

**Comment by silverwind** [comment]
`transform: translate(0px)` set on any editor parent element also triggers this bug.

**Comment by hediet** [comment]
Thanks for reporting this! I'm not sure, but this actually might be a duplicate.
In case it is not, please create an new issue and provide a reproducible example in the monaco editor. Thanks!

**Comment by silverwind** [comment]
There are two reproducible examples in this issue. They could be more minimal but do showcase the issue.
