### ISSUE TITLE
maybe it can support Groovy code highlighting & code completion.

### ISSUE THREAD

**Issue by PisecesPeng** [microsoft/monaco-editor#2504]
Hi 👋
Does [monaco-editor](https://github.com/microsoft/monaco-editor) support Groovy code highlighting and code completion ?
maybe it can support Groovy code highlighting and code completion.

**Comment by rcjsuen** [comment]
> Does [monaco-editor](https://github.com/microsoft/monaco-editor) support Groovy code highlighting and code completion ?

It does not have out-of-the-box support for Groovy.

> maybe it can support Groovy code highlighting and code completion.

You can implement this by yourself or you can try plugging in a language server with the help of the [TypeFox/monaco-languageclient project](https://github.com/TypeFox/monaco-languageclient).

**Comment by PisecesPeng** [comment]
@rcjsuen  Actually my front-end is not good 😅, but thank you for your suggestions, I can try to understand.

**Comment by hediet** [comment]
Thanks for answering, @rcjsuen!
