### ISSUE TITLE
Cannot set an active line number color in theme

### ISSUE THREAD

**Issue by Surm4** [microsoft/monaco-editor#2507]
According to the https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-exposed-colors
I can't set an active line number color in `monaco.editor.defineTheme` I can change just the non-active line numbers via `editorLineNumber.foreground`

**Comment by hediet** [comment]
You can use `editorActiveLineNumber.foreground`. In general, you can use all editor colors that are available to VS Code themes.

Feel free to open a PR to update the example, we'd be very happy to merge it!
