### ISSUE TITLE
Add native GitHub security and versioning dependency alerts

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/monaco-editor#2508]
- [Dependabot](https://dependabot.com/) alerts on updates for the project's dated and vulnerable dependencies and automatically creates PRs to easily update them

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by hediet** [comment]
Thank you for your suggestion!

This repository contains no source code for the code editor, it only contains the scripts to package everything together and ship the monaco-editor npm module.
Thus, this does not make sense for this repository.
