### ISSUE TITLE
Add native GitHub continuous code security and quality analysis

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/monaco-editor#2510]
- [CodeQL](https://github.com/github/codeql) is an open source code scanning tool for discovering vulnerabilities across a codebase

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by hediet** [comment]
Thank you for your suggestion!

This repository contains no source code for the code editor, it only contains the scripts to package everything together and ship the monaco-editor npm module.
Thus, code analysis does not make sense for this repository.
