### ISSUE TITLE
CompletionItemProvider invocation is not based on triggerCharacters

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2518]
**monaco-editor version:** 0.24.0
**Browser:** Chrome
**OS:** Mac OS
**Playground code that reproduces the issue:**

```js
function createDependencyProposals(range) {
    // returning a static list of proposals, not even looking at the prefix (filtering is done by the Monaco editor),
    // here you could do a server side lookup
    return [
        {
            label: '"lodash"',
            kind: monaco.languages.CompletionItemKind.Function,
            documentation: "The Lodash library exported as Node.js modules.",
            insertText: '"lodash": "*"',
            range: range
        }
    ];
}

monaco.languages.registerCompletionItemProvider('javascript', {
    triggerCharacters : ['1'],
    provideCompletionItems: function(model, position) {
        console.log('Came to provideCompletionItems');
        // find out if we are completing a property in the 'dependencies' object.
        var textUntilPosition = model.getValueInRange({startLineNumber: 1, startColumn: 1, endLineNumber: position.lineNumber, endColumn: position.column});
        var match = textUntilPosition.match(/"dependencies"\s*:\s*\{\s*("[^"]*"\s*:\s*"[^"]*"\s*,\s*)*([^"]*)?$/);
        if (!match) {
            return { suggestions: [] };
        }
        var word = model.getWordUntilPosition(position);
        var range = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn
        };
        return {
            suggestions: createDependencyProposals(range)
        };
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: "var json = {\n\t\"dependencies\": {\n\t\t\n\t}\n}\n",
    language: "javascript"
});

```
### Video Explaining the issue 

https://user-images.githubusercontent.com/29809906/121363002-2deee980-c954-11eb-9e8f-71515b5a99fd.mov

### Description 

The significance of adding the trigger characters in CompletionProvider is a little bit unclear for me. I thought, the `provideCompletionItems` will fire only when the entry in trigger characters is pressed. But the invocation of the provideCompletionItems seems to happen even when the trigger characters are not pressed. 

Thus the suggestions are shown, even before pressing the trigger characters.

This makes it difficult for me to fetch data and send the suggestions inside the provideCompletionItems function.

**Comment by alexdima** [comment]
I'm not entirely sure what is going on. I think the completion item provider registered by you is on equal footing (priority-wise) with the built-in javascript completion item provider and perhaps the faster one is chosen. cc @jrieken if you have any insights.

**Comment by jrieken** [comment]
> I thought, the provideCompletionItems will fire only when the entry in trigger characters is pressed. But the invocation of the provideCompletionItems seems to happen even when the trigger characters are not pressed.

Trigger characters are just another, additional, source of trigger reasons. Others are: typing at word ends or explicit invocation (via ctrl+space). The typical use-cases for trigger character are non-word characters that have a meaning, like the `.` for member completions. 

However, when you register a completion item provider you must expect it to be called in all circumstances and its up to the provider to figure out if a position is a good position for completion. Iff not, it should return `undefined` and an empty result

**Comment by PisecesPeng** [comment]
Hi @Pranomvignesh , I also encountered the same situation. 
issues #2530 may help you.

> maybe CompletionItemProvider invocation is not based on triggerCharacters, 
> but you need to trigger the label by **typing letters**, like [completion-provider-example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example)
