### ISSUE TITLE
Override tokenization for built-in language

### ISSUE THREAD

**Issue by JKillian** [microsoft/monaco-editor#252]
monaco-editor npm version: 0.7.0

I've found that `monaco.languages.setMonarchTokensProvider` doesn't work for languages that are already defined in `monaco-languages`. Is there a way to override the definitions in `monaco-languages`?

This seemed to work for me, but it does cause a (hopefully harmless) console error:

```ts
const sqlLang = monaco.languages.getLanguages().filter(l => l.id ==="sql")[0];
delete (sqlLang as any).module;
monaco.languages.setMonarchTokensProvider("sql", sqlHighlighter);
```

I've also found this works, but it's quite hacky:

```ts
monaco.languages.onLanguage("sql", () => {
    // waits til after monaco tries to register things itself
    setTimeout(() => {
        monaco.languages.setMonarchTokensProvider("sql", sqlHighlighter);
        monaco.languages.setLanguageConfiguration("sql", sqlConf);
    }, 100);
});
```

**Comment by alexandrudima** [comment]
You could simply [register a new language](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#register) (e.g. `sql2`) which would avoid the built-in `sql` configuration / tokens provider from kicking in.

**Comment by JKillian** [comment]
Thanks @alexandrudima, that seems like an idea worth trying. Unfortunately, it seems like files with a `.sql` extension will still default to being part of the `sql` language and not the `sql2` language, so that means the language would just have to be manually set.

**Comment by Menci** [comment]
For current version of monaco-editor, you should override the function `langauge.loader` instead of `delete language.module`:

```js
var overrideLangauges = [
  'cpp',
  'c',
  'csharp',
  'haskell',
  'java',
  'javascript',
  'pascal',
  'python',
  'ruby',
  'markdown'
];

monaco.languages.getLanguages().forEach(function (lang) {
  if (overrideLangauges.includes(lang.id)) {
    lang.loader = function () {
      return { then: function () {} };
    };
  }
});
```
