### ISSUE TITLE
ContentWidget diappears to early

### ISSUE THREAD

**Issue by andres-kovalev** [microsoft/monaco-editor#2520]
I have a zone to reserve some space for my ContentWidget located in the same place (occupies 3 lines below line 3):
![image](https://user-images.githubusercontent.com/2773159/121527283-87a9ef00-c9fa-11eb-9742-3997d26d6c5f.png)

When i scroll editor to hide only first corresponding line (line 3) whole content widget disappears:
![image](https://user-images.githubusercontent.com/2773159/121527497-c17af580-c9fa-11eb-9bdf-75dac56eaa35.png)

I assume monaco editor doesn't take into account the size of widget. Is there any way to provide this information?

Is there any way to prevent it?

**monaco-editor version:** 0.24.0
**Browser:** Google Chrome
**OS:** macOS
**Playground code that reproduces the issue:**

```js
var jsCode = [
   '"use strict";',
   'function Person(age) {',
   '   if (age) {',
   '       this.age = age;',
   '   }',
   '}',
   'Person.prototype.getAge = function () {',
   '   return this.age;',
   '};'
].join('\n');
 
var editor = monaco.editor.create(document.getElementById("container"), {
   value: jsCode,
   language: "javascript",
   glyphMargin: true,
   contextmenu: false
});
 
// Add a zone to make hit testing more interesting
var viewZoneId = null;
editor.changeViewZones(function(changeAccessor) {
       var domNode = document.createElement('div');
       domNode.style.background = 'lightgreen';
       viewZoneId = changeAccessor.addZone({
                   afterLineNumber: 3,
                   heightInLines: 3,
                   domNode: domNode
       });
});
 
// Add a content widget (scrolls inline with text)
var contentWidget = {
   domNode: null,
   getId: function() {
       return 'my.content.widget';
   },
   getDomNode: function() {
       if (!this.domNode) {
           this.domNode = document.createElement('div');
           this.domNode.innerHTML = 'My content widget';
           this.domNode.style.background = 'grey';
       }
       return this.domNode;
   },
   getPosition: function() {
       return {
           position: {
               lineNumber: 3,
               column: 8
           },
           preference: [monaco.editor.ContentWidgetPositionPreference.BELOW]
       };
   }
};
editor.addContentWidget(contentWidget);
```

**Comment by alexdima** [comment]
The content widget gets only rendered when the position it returns in `getPosition` is in the viewport. If you want to line-up a view zone with another widget, I recommend looking into using an overlay widget. The view zone offers callbacks (`onDomNodeTop`, `onComputedHeight`) which can be used to effectively line up an overlay widget on top of a view zone. That is what we use for these e.g. :
![image](https://user-images.githubusercontent.com/5047891/121584640-fa828c80-ca31-11eb-926b-c70a738dc87b.png)
