### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined at decorators.ts

### ISSUE THREAD

**Issue by softmarshmallow** [microsoft/monaco-editor#2522]
Using monaco editor with https://github.com/abraham/reflection/ throws `Uncaught TypeError: Cannot read property 'value' of undefined`

![](https://user-images.githubusercontent.com/16307013/120513707-7fa0ec80-c407-11eb-9e7a-12eb5b0d2fbb.png)

Original issues: 

- https://github.com/abraham/reflection/issues/630
- https://github.com/suren-atoyan/monaco-react/issues/237

**Comment by alexdima** [comment]
@softmarshmallow I think the vscode decorator implementation is correct. Here is the TS documentation: https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators

Notice how the `descriptor` is not documented or typed to ever be `undefined`:
![image](https://user-images.githubusercontent.com/5047891/121646623-ce98f280-ca95-11eb-8bb0-ff1cbd0420b6.png)

Since this NPE does not reproduce without `abraham/reflection`, I believe this is a problem with that package, which perhaps misses a case (or something).

**Comment by softmarshmallow** [comment]
> @softmarshmallow I think the vscode decorator implementation is correct. Here is the TS documentation: https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators
> 
> Notice how the `descriptor` is not documented or typed to ever be `undefined`:
> ![image](https://user-images.githubusercontent.com/5047891/121646623-ce98f280-ca95-11eb-8bb0-ff1cbd0420b6.png)
> 
> Since this NPE does not reproduce without `abraham/reflection`, I believe this is a problem with that package, which perhaps misses a case (or something).

I'll take another deep look, but reflection is not that a complex package and i don't see any malicious implementations.
I'm humbly requesting to check if the vscode side can allow descriptor to be null?

Thanks :)

**Comment by alexdima** [comment]
> I'm humbly requesting to check if the monaco side can allow descriptor to be null?
:+1: Yes, that's what I've done. I've looked at the code which has been slightly modified on `main`, but I can see that this particular descriptor called `memoize` is only ever used on methods in classes. I've then proceeded to read about their constraints and they should always be invoked by TypeScript with the `descriptor` argument.

This can also be seen in the generated JS. [Here](https://github.com/microsoft/vscode/blob/012b14606f75ec4fed90d7ab4154f63dffab9503/src/vs/base/common/linkedText.ts#L20) is an example of using that particular decorator in TypeScript. And here is the generated JS:

```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
define(["require", "exports", "vs/base/common/decorators"], function (require, exports, decorators_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.parseLinkedText = exports.LinkedText = void 0;
    class LinkedText {
        constructor(nodes) {
            this.nodes = nodes;
        }
        toString() {
            return this.nodes.map(node => typeof node === 'string' ? node : node.label).join('');
        }
    }
    __decorate([
        decorators_1.memoize
    ], LinkedText.prototype, "toString", null);
    exports.LinkedText = LinkedText;
    //...
});
```

From my reading of that method (`__decorate`), it looks like `desc` is passed in as `null`, but then it gets assigned to `desc = Object.getOwnPropertyDescriptor(target, key)`. So `desc` is always defined. If a global called `Reflect` is defined (which is what I guess this other package is doing), then decorating gets delegated to that global using `Reflect.decorate(decorators, target, key, desc)`. IMHO at that point `desc` is always set. I don't know how this other npm package implements `Reflect`, but I would expect it should carry over the `desc` argument and pass it on to the decorator.

**Comment by softmarshmallow** [comment]
Ok, Thanks for the detailed explanations :)
