### ISSUE TITLE
Not able to type certain characters in non-US keyboards

### ISSUE THREAD

**Issue by Nirajn2311** [microsoft/monaco-editor#2533]
One of our users at freeCodeCamp faced an issue in typing certain characters while using their Czech keyboard in their Mac. In the Czech keyboard the only way to type `[` or `]` is <kbd>Option</kbd> + <kbd>[</kbd> or <kbd>Option</kbd> + <kbd>]</kbd>. You can type those characters easily in VSCode and in any other app in MacOS but in monaco-editor playground and in our editor UI, which uses monaco-editor, it doesn't work. Nothing gets typed when you try to type those two characters.

Discourse link to our forum about the issue - https://forum.freecodecamp.org/t/cannot-type-the-inside-exercises/465050 

**monaco-editor version:** 0.25.1
**Browser:** All browsers
**OS:** MacOS
**Playground code that reproduces the issue:**

**Comment by alexdima** [comment]
This is actually caused by the default keybinding for `editor.action.inlineSuggest.showPrevious` which lacks a proper `when` clause:

```
[KeybindingService]: | Resolving alt+[
[KeybindingService]: \ From 1 keybinding entries, matched editor.action.inlineSuggest.showPrevious, when: !editorReadonly, source: built-in.
```

**Comment by hediet** [comment]
@alexdima should I do another patch release for this?

**Comment by hediet** [comment]
We just published the recovery release "0.25.2" that should fix this issue.
You can try out the updated editor here: https://microsoft.github.io/monaco-editor/playground.html.

We would appreciate if you could verify that this solves the issue!

**Comment by alexdima** [comment]
@hediet I just verified. The fix is great.

**Comment by Nirajn2311** [comment]
Thanks for fixing the issue y'all. I just checked it in the playground and it works.
