### ISSUE TITLE
How to hide "View Problems (Alt+F8)" line in 0.25.2?

### ISSUE THREAD

**Issue by weizhang-ms** [microsoft/monaco-editor#2537]
**monaco-editor version:** 0.25.2
**Playground code that reproduces the issue:**
1) go to https://microsoft.github.io/monaco-editor/
2) just type "aaaaa" in the default "typescript" editor
3) hover on "aaaaa"

Is there a way to hide the  "View Problems (Alt+F8)" line in newer version of monaco-editor? (We used to use 0.17.1, which doesn't have that line)

![image](https://user-images.githubusercontent.com/81582911/122632650-24b6f880-d089-11eb-9fe5-ce95b1938882.png)

**Comment by alexdima** [comment]
There is no API to hide that. Hiding it would not be very friendly towards users with screen readers, who can use the hover to discover `Alt+F8` which renders the error in a box that is screen reader accessible.

**Comment by weizhang-ms** [comment]
Thanks @alexdima ! 

The issue I have is the "Problem list" UI is shown inside the monaco-editor (not a popup as suggestion widget), the user experience for my one-line code editor is really bad, please see repro below.

If there is no way to hide it, is there a way to make it a popup (show complete UI outside of the editor)?

![repro](https://user-images.githubusercontent.com/81582911/122807204-21399200-d280-11eb-9141-6900f2d69d86.gif)

**Comment by hediet** [comment]
Can you use the decorations API directly to render the problem, instead of reporting diagnostics? Then you are in control of the hover.

**Comment by weizhang-ms** [comment]
Thanks! Do you have any examples of using decorations APIs?

**Comment by alexdima** [comment]
@weizhang-ms  Here is a complete example that you can execute at https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations:
```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

var decorations = editor.deltaDecorations([], [
	{ 
        range: new monaco.Range(7,1,7,24), 
        options: {
            className: "squiggly-error",
            minimap: {
                color: {id: "minimap.errorHighlight"},
                position: monaco.editor.MinimapPosition.Inline
            },
            overviewRuler: {
                color: {id: "editorOverviewRuler.errorForeground"},
                position: monaco.editor.OverviewRulerLane.Right
            },
            showIfCollapsed: true,
            stickiness: monaco.editor.TrackedRangeStickiness.NeverGrowsWhenTypingAtEdges,
            zIndex: 30,
            hoverMessage: { value: 'this is an **error**', isTrusted: false }
        }
    }
]);

```

![image](https://user-images.githubusercontent.com/5047891/125239539-130fec00-e2e9-11eb-8ad0-a9f1e31a3943.png)

**Comment by weizhang-ms** [comment]
@alexdima Thank you!!
![image](https://user-images.githubusercontent.com/81582911/125330221-507d7500-e2fb-11eb-851a-12334db4673a.png)
