### ISSUE TITLE
Have you tried `F1 > Developer: Inspect Tokens`?

### ISSUE THREAD

**Issue by AlexeyZvezdin** [microsoft/monaco-editor#2538]
Hello guys, I don't know where else to ask, but if I want to change the color of "Other" tokens, which is in html is basically all text inside brakets, I use kind of a hack selecting it like token: "".
Maybe there is another way to do it? 

_Originally posted by @alexdima in https://github.com/microsoft/monaco-editor/issues/1805#issuecomment-581654990_

**Comment by alexdima** [comment]
:+1: Yes, that is the way to do it.

The default theme also does it like that https://github.com/microsoft/vscode/blob/b6f87798570cef6d99554fe10c747e9f6b02a274/src/vs/editor/standalone/common/themes.ts#L15
