### ISSUE TITLE
Change the request url of the monaco files

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2539]
### Description
I have an application that requests the static js files from a different domain, So I have to modify the script sources accordingly before hitting the request
To be precise, the URL path has to be modified from 
`<application-domain>/monaco/min/vs/editor/editor.main.js` => `<static-server-domain>/monaco/min/vs/editor/editor.main_<hash>.js`

### What I need : 
```js
// After loading loader.js from monaco
require.config({
  constructPath : function(url){
     // assuming url = "vs/editor/editor.main"
    // My Logic to get the corresponding static hashed file path from the map
   // I will be returning "<static-server-domain>/monaco/min/vs/editor/editor.main_<hash>.js" from here
  }
})
```
This constructPath function should get called whenever a dependency file is loaded via define function

PS: I am not able to use the browser [script editor version of the monaco editor sample](https://github.com/microsoft/monaco-editor-samples/blob/main/browser-script-editor/index.html) it is also having the same issue as some js files are loaded on demand

Please update me whether this feature is already available / any other ways to achieve my use case

**Comment by alexdima** [comment]
I think you can use something like this:
```
require.config({
  paths: {
    'vs/editor/editor.main': 'vs/editor/editor.main_YOUR_HASH_HERE'
  }
});
```

**Comment by Pranomvignesh** [comment]
@alexdima  Thanks for your response, There are two things that are stopping me from doing this

- Hash is not static in my case
- I will not get a hold to modify the URL for the files which `editor.main.js` is going to request when the editor instance is created and language configuration changes ( for files like tsMode.js, workerMain.js )

**Comment by alexdima** [comment]
@Pranomvignesh The editor is distributed as AMD or as ESM. The AMD variant of the editor (which you appear to be using) can be loaded by any AMD spec compliant loader. A very well know AMD loader is `require.js` -- https://requirejs.org/ . A self-contained sample on how to use `require.js` is available at https://github.com/microsoft/monaco-editor-samples/tree/main/browser-amd-requirejs . Maybe the `require.js` loader contains the feature that you are looking for?

Alternatively, you can use the ESM variant and use an ESM bundler.

If none of these work for you, then you can also generate the `<script>` tags by yourself e.g. https://github.com/microsoft/monaco-editor-samples/tree/main/browser-script-editor

**Comment by Pranomvignesh** [comment]
@alexdima, Unfortunately, ESM Version and Normal Script Version will not resolve my issue ( I already tried those ). Will check `require.js`. Once again Thank you
