### ISSUE TITLE
Using a new version of the monaco-editor and monaco-editor-webpack-plugin will still cause errors

### ISSUE THREAD

**Issue by xinshemeigui** [microsoft/monaco-editor#2542]
**monaco-editor version:0.23.0** 
**monaco-editor-webpack-plugin version:3.1.0** 
**Browser: chrome**
**OS:win10**
**Playground code that reproduces the issue:**

```js
```
See other issues. I used the plugin of the corresponding version, but still reported an error
![image](https://user-images.githubusercontent.com/40166570/123032448-89bb7700-d418-11eb-8fca-662f5ec671b6.png)

**Comment by alexdima** [comment]
This is fixed with `monaco-editor@0.25.x` and `monaco-editor-webpack-plugin@4.x.x`
