### ISSUE TITLE
Can't access payload in action method

### ISSUE THREAD

**Issue by adamjimenez** [microsoft/monaco-editor#2547]
The payload shows as undefined. This is my playground code.

```
var editor = monaco.editor.create(document.getElementById("container"));

editor.addAction({
    id: 'insert',
    label: 'insert',
    run: function(editor, payload) {
        console.log(payload);
    }
});

editor.trigger('', 'insert', {text: 'yo'});
```

The docs are rather vague on how to use the args.
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.iactiondescriptor.html#run

**Comment by hediet** [comment]
I guess the payload should be passed in here @alexdima?

https://github.com/microsoft/vscode/blob/main/src/vs/editor/browser/widget/codeEditorWidget.ts#L1039
