### ISSUE TITLE
Is there an API to create a directory?

### ISSUE THREAD

**Issue by huanghantao** [microsoft/monaco-editor#2558]
just like VS Code:

![image](https://user-images.githubusercontent.com/22836925/124241167-17e8d900-db4e-11eb-8983-9ef967e1b901.png)

**Comment by rcjsuen** [comment]
@huanghantao The Monaco Editor project just covers the editor. It doesn't expose any APIs for working with files and folders.

**Comment by hediet** [comment]
@huanghantao See @rcjsuen`s answer.

@rcjsuen thanks for helping out!
