### ISSUE TITLE
Breakpoint marker

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/monaco-editor#256]
Is it possible to set the breakpoint marker closer to line numbers?
When I enable glyph margin it is rendered way too far away. When I check VS Code, breakpoints are rendered much much closer.

**In another words, how can I set the width of line-numbers and glyph margin?**

[EDIT]
I have found lineNumbersWidth property, but it is readonly.

**Comment by microsoftsam** [comment]
lineNumbersMinChars in the editor config might help you out here.

**Comment by tomitrescak** [comment]
Thanks @microsoftsam was very helpful indeed!
