### ISSUE TITLE
Missing Swift fileprivate access modifier

### ISSUE THREAD

**Issue by RubenRBS** [microsoft/monaco-editor#2560]
**monaco-editor version:** 0.25.2

As of the latest release, the Swift access modifier `fileprivate` is missing proper tokenization (https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID5)

First reported in https://github.com/compiler-explorer/compiler-explorer/issues/2751

**Comment by hediet** [comment]
Unfortunately, we don't have the resources to address this right now, but we're more than happy to accept a PR for this!
