### ISSUE TITLE
Custom Attribute suggestions are not getting populated on auto complete

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#2564]
**monaco-editor version:** 0.25.2
**Browser:** Chrome
**OS:** Mac OS
**Playground code that reproduces the issue:**

```js
const data = {
	"version": 1.1,
	"tags": [
	  {
		"name": "foo",
		"description": "The foo element",
		"attributes": [
		  { "name": "bar" },
		  {
			"name": "baz",
			"values": [
			  {
				"name": "baz-val-1" 
			  }
			]
		  }
		]
	  }
	],
	"globalAttributes": [
	  { "name": "fooAttr", "description": "Foo Attribute" },
	  { "name": "xattr", "description": "X attributes", "valueSet": "x" }
	],
	"valueSets": [
	  {
		"name": "x",
		"values": [
		  {
			"name": "xval",
			"description": "x value"
		  },
          {
			"name": "xy-val",
			"description": "x value"
		  },
          {
			"name": "xyx-val",
			"description": "x value"
		  },
          {
			"name": "z-val",
			"description": "x value"
		  }
		]
	  }
	]
  }


monaco.languages.html.htmlDefaults.setOptions({data: { useDefaultDataProvider: true, dataProviders: [ data ]}});

var template = `
<html>
    <head>
    </head>
    <body>
    </body>
</html>`;

monaco.editor.create(document.getElementById('container'), {
	value: template,
	language: 'html'
});

```
_Sample Code taken from this issue_ : #2284
_Added new entries in `valueset x` and gave `true` to `useDefaultDataProvider` in options

### Description 
When I type `xa` , the autocomplete perfectly suggests the globalAttributes, but the suggestion for the value of the attribute is not shown when i continue typing ( I think it is because of the selection )
**It will be better if the autocomplete suggestion for the attribute values are shown right after the attribute name is selected from the list**

### Current Behaviour
The suggestions are provided only after removing the quotes and retriggering the value suggestions by typing next to the `=` character

### Expected Behaviour
The suggestions for values has to be provided immediately after the attribute name is autocompleted

### Video Explaining the issue

https://user-images.githubusercontent.com/29809906/124463128-10c10580-ddb0-11eb-9e14-ffd4b55f75bb.mov

**Comment by aeschli** [comment]
Thanks for reporting. Value sets with global attributes didn't work.
Fixed in the language service. Not sure how quick it will be in the monaco build.

**Comment by Pranomvignesh** [comment]
@aeschli  Thanks for this quick response . `Value sets with global attributes didn't work.` - Actually it is not about global attributes (or) Value sets, It didn't work when I tried the below snippet

```js
const data = {
	"version": 1.1,
	"tags": [
	  {
		"name": "foo",
		"description": "The foo element",
		"attributes": [
		  { "name": "bar" },
		  {
			"name": "baz",
			"values": [
			  { "name": "baz-val-1" },
                          { "name": "baz-val-2" }
			]
		  }
		]
	  }
     ]
}
```

I hope this gets fixed in https://github.com/microsoft/vscode-html-languageservice/commit/77e44833eac686d68bc91da4684aeab306553cb8

**Comment by aeschli** [comment]
For me there were no proposals at all as I tried with a tag other than `foo`. That's fixed now.

Your concern was that code completion automatically opens again (retriggers) after completing an attribute name?
I pushed a fix that too.

**Comment by Pranomvignesh** [comment]
@aeschli Thanks for this feature https://github.com/microsoft/monaco-html/commit/04c34d444ab9e2a19d6c14e3ad30e53d05dea7f9. I will try this once it gets released in monaco-editor
