### ISSUE TITLE
html customData

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2565]
``{
 		"tags": [
				{
					"name": "foo",
					"description": "The foo element",
					"attributes": [
						{ "name": "bar" },
						{
							"name": "baz",
							"values": [
								{
									"name": "baz-val-1"
								}
							]
				}
			],
			"globalAttributes": [
				{ "name": "fooAttr", "description": "Foo Attribute" },
				{ "name": "xattr", "description": "X attributes", "valueSet": "x" }
			],
			"valueSets": [
				{
					"name": "x",
					"values": [
						{
							"name": "xval",
							"description": "x value"
						}
					]
				}
			]
		}
]
monaco.languages.html.htmlDefaults.setOptions({data: { useDefaultDataProvider: false, dataProviders: [ data ]}});
I want to add two fields

1 the name here is the label and we want to put an insertText in there. For example, I think an insert with a tag that has several attributes would need to do this.

2 I think properties and events should be distinguished so that they have different signs of kind

So I think there should be an event as well as an attribute

**Comment by aeschli** [comment]
See https://github.com/microsoft/monaco-editor/issues/2284#issuecomment-874532859

Feature requests for custom data would have to go against https://github.com/microsoft/vscode-custom-data (which defines the data format) and the https://github.com/microsoft/vscode-html-languageservice, which consumes the data and creates proposals with labels etc.
That said, we currently don't have any resources or plans to extend the custom data syntax. Help is wanted, if you are interested to help, let me know.
