### ISSUE TITLE
How to kill this 'any'

### ISSUE THREAD

**Issue by xinshemeigui** [microsoft/monaco-editor#2569]
playground:
```js
var value =`return id`

monaco.editor.create(document.getElementById("container"), {
    value: value,
    language: "javascript"
});

monaco.languages.registerHoverProvider('javascript', {
    provideHover: (model, position) => {
        let valRange = model.getWordAtPosition(position) // 通过行和列来获取当前hover的值
        return {
            range: new monaco.Range(position.lineNumber, valRange.startColumn, position.lineNumber, valRange.endColumn),
            contents: [
                {
                value:'```ts\n'  +
                        'boolean\n'  +
                        '```\n',
                isTrusted: false
                },
                {
                value:'```ts\n'  +
                        '(property) XXX: boolean\n'  +
                        '```\n',
                isTrusted: false
                }
            ]
        }
    }
})
```
'id' is a variable that I define elsewhere. I want to control what is displayed, but there will always appear an ‘any’
How to kill this 'any'?
I don't want to register a new language because I need the default prompt for javascript
![image](https://user-images.githubusercontent.com/40166570/125043878-fcda1400-e0cd-11eb-96dc-768d2bddd1c1.png)

**Comment by hediet** [comment]
Unfortunately I don't think you can remove the `any`. The javascript language feature also registers an hover provider for type information. It thinks `id` is of type `any`.

You can either fork the javascript language feature (we don't provide support for that) or you can try to set a global d.ts file to declare the type of `id`.
