### ISSUE TITLE
Unexpected go to definition on pressing Ctrl button

### ISSUE THREAD

**Issue by kerbal** [microsoft/monaco-editor#2571]
Hi.

I setup the monaco editor for my custom language with definition provider. Whenever I press `Ctrl` while hovering a symbol, it jumps to the symbol's definition. How to disable this behavior?

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/33062751/125064753-2e0d1100-e0db-11eb-96de-02496a342483.gif)

Thank you so much.

**monaco-editor version:** 0.21.2
**Browser:** Chrome
**OS:** Ubuntu

**Comment by hediet** [comment]
Thanks for reporting this bug! Can you provide an example for the monaco playground so I can try to reproduce your issue?

**Comment by kerbal** [comment]
Hi. Thank you for replying. I cannot find the playground link. I use this API https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.definitionprovider.html#providedefinition

**Comment by hediet** [comment]
This is the playground: https://microsoft.github.io/monaco-editor/playground.html

**Comment by kerbal** [comment]
Hi. I am so sorry. I figured out that was my bug. The monaco-editor is working fine. Thank you for replying.
