### ISSUE TITLE
Bug when triggering autocomplete suggestions programmatically

### ISSUE THREAD

**Issue by mureytasroc** [microsoft/monaco-editor#2572]
I wrote some code to get the autocomplete suggestion box to show up when a new key is being defined in the Monaco json editor (so you don't have to start typing to see suggestions, you can just see suggested keys available to you when you first type the quotes of the key). This code programmatically triggers the suggestions box to show up using the code pasted [here](https://github.com/microsoft/monaco-editor/issues/74#issuecomment-239797397) by @alexdima. 

Unfortunately, this code exposes a bug: if you trigger the suggestions box programmatically, then start typing (which would trigger the suggestions box to show up anyway) and then accept a suggestion, the auto-fill gets messed up. In the Monaco sandbox, it seems to remove the first character after the autofill insertion. In my environment, for some reason it inserts an extra double-quote character right after the autofill insertion (gifs attached below). But I'm guessing these issues are related, so the sandbox code and replication instructions are included below.

As you can see in the attached gifs, triggerSuggest is only triggered when the empty quotes are first added (which is the desired behavior) -- afterwards when you are typing and accept the suggestion, the console does not print "TRIGGER". So for some reason, programmatically triggering autocomplete suggestions causes some delayed effect if coupled with typing out part of the suggestion (which should trigger the suggestions list to show up on its own) to mess up the autocomplete code insertion. I wonder if it's some sort of interaction/interence between the typing-triggered suggestions and the programmatically-triggered suggestions?

Does anyone have any suggested workaround for this?

**GIFs of the bug in my environment, plus console output:**

Bug (note the "TRIGGER" printout in the console):
<img src="https://s6.gifyu.com/images/MonacoBug.gif" width="1000" />

Normal Behavior:
<img src="https://s6.gifyu.com/images/MonacoWorking.gif" width="1000" />

**Playground code that reproduces the issue:**
(Note: to reproduce, try adding the "description" key by first adding the open quotes "" and then typing out "desc" and then accepting the suggestion -- the bug won't occur if you accept the suggestion before typing anything... then comment out lines 51-54 and the bug will disappear)
[https://microsoft.github.io/monaco-editor/playground.html](https://microsoft.github.io/monaco-editor/playground.html)
```js
const editor = monaco.editor.create(document.getElementById('container'), {
  model: monaco.editor.createModel('{}', 'json', monaco.Uri.parse('file:///resource.json')),
  automaticLayout: true,
  quickSuggestions: { other: true, strings: true },
});

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
  enableSchemaRequest: false,
  validate: true,
  schemas: [
    {
      uri: 'file:///resource.json#schema',
      fileMatch: ['file:///resource.json'],
      schema: {
        $schema: 'http://json-schema.org/draft-07/schema#',
        $id: 'https://schema.com/config/analytics/insight',
        $version: '1',
        type: 'object',
        title: 'Insight',
        description: 'Configures an analytics insight.',
        properties: {
          $id: {
            type: 'string',
            minLength: 1,
            maxLength: 97,
            description: 'The unique identifier for the insight resource.',
          },
          $schema: {
            const: 'https://schema.com/config/analytics/insight/v1',
          },
          name: {
            type: 'string',
            minLength: 1,
            maxLength: 100,
            description: 'The human-readable name of the insight.',
          },
          description: {
            type: 'string',
            minLength: 1,
            maxLength: 500,
            description: 'A description of the insight.',
          },
        },
      },
    },
  ],
});

editor.onDidChangeModelContent((event) => {
  const value = editor.getValue();
  if (isDefiningNewKey(event, value)) {
    editor.trigger('', 'editor.action.triggerSuggest');
    console.log('TRIGGER');
  }
});

/**
 * This function infers whether the change corresponding to the given event is defining a
 * new json key.
 *
 * @param {IModelContentChangedEvent} event the change event
 * @param {string} value the editor's current value
 * @return {boolean} true if the change is defining a new key, false otherwise
 */
function isDefiningNewKey(event, value) {
  if (
    event['isFlush'] ||
    event['isRedoing'] ||
    event['isUndoing'] ||
    event['changes'].length !== 1
  ) {
    return false;
  }
  const change = event['changes'][0];
  if (
    change['range']['startLineNumber'] !== change['range']['endLineNumber'] ||
    change['text'] !== '""'
  ) {
    return false;
  }

  // Get the change position (subtract 1 to convert to 0-index)
  const lineNumber = change['range']['startLineNumber'] - 1;
  const columnNumber = change['range']['startColumn'] - 1;

  // Get the text strictly before the change position
  const lines = value.split('\n');
  const lastLine = lines[lineNumber].slice(0, columnNumber);
  const textToSearch = lines.slice(0, lineNumber).join('') + lastLine; // ignore \n

  const lastNonWhitespace = unpackOrNull(textToSearch.match(LAST_NON_WHITESPACE_REGEX));
  if (lastNonWhitespace === '{') {
    return true;
  } else if (lastNonWhitespace === ',') {
    // We could be in an array
    let netLeftCurlyBracketCount = 0;
    let netLeftSquareBracketCount = 0;
    for (let i = textToSearch.length - 1; i >= 0; i -= 1) {
      switch (textToSearch.charAt(i)) {
        case '{':
          netLeftCurlyBracketCount += 1;
          break;
        case '}':
          netLeftCurlyBracketCount -= 1;
          break;
        case '[':
          netLeftSquareBracketCount += 1;
          break;
        case ']':
          netLeftSquareBracketCount -= 1;
          break;
      }
      if (netLeftCurlyBracketCount === 1) {
        break; // Found the beginning of the object we are in
      }
    }
    return netLeftCurlyBracketCount === 1 && netLeftSquareBracketCount <= 0;
  }
  return false;
}
// Helper regex and functions for isDefiningNewKey
const LAST_NON_WHITESPACE_REGEX = /[^\s](?![\S\s]*[^\s])/; // matches the last non-whitespace character
const unpackOrNull = (array) => (array && array.length > 0 ? array[0] : null);
```

**Comment by jrieken** [comment]
@mureytasroc Why aren't you using trigger characters for this?
