### ISSUE TITLE
monaco diffeditor can support invalid blank in a line highlight？

### ISSUE THREAD

**Issue by qcscofield** [microsoft/monaco-editor#2574]

**Comment by hediet** [comment]
Can you please provide more information?

**Comment by qcscofield** [comment]
![image](https://user-images.githubusercontent.com/31910172/125717589-155944de-0d46-4123-84e5-901946c61864.png)
like this. there is 4 invalid blank in the code. Can monaco diffeditor find out it and highlight ?

**Comment by hediet** [comment]
Sorry, I still don't understand the issue.

Can you provide an example in the monaco playground?

**Comment by qcscofield** [comment]
Hi
According to the code specification, invalid spaces in a line are not allowed. Is there any way for Monaco to automatically identify invalid spaces and highlight them

**Comment by hediet** [comment]
Can you clarify what you mean with invalid spaces?

> code specification

Which code specification?

**Comment by qcscofield** [comment]
For example, if there is a line in a. C file that has nothing but four spaces, it is considered to be nonstandard. I want to identify it through Monaco

**Comment by rcjsuen** [comment]
> For example, if there is a line in a. C file that has nothing but four spaces, it is considered to be nonstandard. I want to identify it through Monaco

@qcscofield Sounds like you want the red squiggly lines like for flagging syntax errors?

![image](https://user-images.githubusercontent.com/15629116/125941915-ad4cddee-8d07-401c-b4a3-a3e3ae1a3c98.png)

**Comment by qcscofield** [comment]
@rcjsuen almost，can it identify invalid spaces or useless indentation? how to do it ?

**Comment by rcjsuen** [comment]
> @rcjsuen almost，can it identify invalid spaces or useless indentation? how to do it ?

@qcscofield That's on you to implement it. The Monaco Editor will not arbitrarily flag whitespace as being "unnecessary" with red squiggly lines.

This playground example may help you.

```JavaScript
monaco.languages.register({ id: 'demoLanguage' });
const uri = monaco.Uri.parse("inmemory://test");
const model = monaco.editor.createModel("", "demoLanguage", uri);

function getMarkers() {
    const lines = model.getLinesContent();
    const markers = [];
    for (let i = 0; i < lines.length; i++) {
        if (lines[i] === "abc") {
            markers.push({
                message: "Sample error message",
                severity: monaco.MarkerSeverity.Error,
                startLineNumber: i + 1,
                startColumn: 1,
                endLineNumber: i + 1,
                endColumn: 1,
            })
        }
    }
    return markers;
}

model.onDidChangeContent(e => {
    monaco.editor.setModelMarkers(model, "owner", getMarkers());
});
model.setValue("abc\ndef\nghi\nabc\ndef")

monaco.editor.create(document.getElementById("container"), {model: model});
```

**Comment by qcscofield** [comment]
@rcjsuen  Thanks, but he doesn't seem to work in diffeditor

**Comment by rcjsuen** [comment]
@qcscofield I've never seen red squiggly lines in the diff editor.

@hediet Do you know if this is possible?

**Comment by qcscofield** [comment]
@rcjsuen 
I implemented diffeditor to work, but it has to be in "readOnly:false" case to work.
if readOnly:true it can't work
`var originalModel = monaco.editor.createModel("This line is removed on the right.\njust some text\nabcd\nefgh\nSome more text", "text/plain");
var modifiedModel = monaco.editor.createModel("just some text\nabc\nzzzzefgh\nSome more text.\nThis line is removed on the left.", "text/plain");
monaco.editor.setModelMarkers(modifiedModel, "owner", getMarkers());
var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), {
    readOnly:false
});

function getMarkers() {
    const lines = modifiedModel.getLinesContent();
    const markers = [];
    for (let i = 0; i < lines.length; i++) {
        if (lines[i] === "abc") {
            markers.push({
                message: "Sample error message",
                severity: monaco.MarkerSeverity.Error,
                startLineNumber: i + 1,
                startColumn: 1,
                endLineNumber: i + 1,
                endColumn: 1,
            })
        }
    }
    return markers;
}

diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});


`

**Comment by hediet** [comment]
Afaik there is a setting to render diagnostics in readonly editors.

**Comment by spahnke** [comment]
@qcscofield `renderValidationDecorations: "on"` should do the trick. Then the editor can be readonly.

**Comment by qcscofield** [comment]
Thanks spahnke. It work for me. :)
Thanks hediet and rcjsuen.
Grateful everyone. You are very nice.
