### ISSUE TITLE
typescript compiler options don't effective

### ISSUE THREAD

**Issue by Erchoc** [microsoft/monaco-editor#2576]
**monaco-editor version:** 0.20.0
**Browser:** chrome87
**OS:** macos
**Playground code that reproduces the issue:**

```js
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
  // anything doesn't usefully
});
```

**Comment by Erchoc** [comment]
and default, the editor can't discern ES6 code effective，for `[].includes()`

**Comment by hediet** [comment]
Can you elaborate your issue?

> // anything doesn't usefully

What do you mean with that?

**Comment by Erchoc** [comment]
#2182

I find the problem, thanks
