### ISSUE TITLE
quickSuggestions do not trigger when defining a new JSON key

### ISSUE THREAD

**Issue by mureytasroc** [microsoft/monaco-editor#2579]
In a .json file in VSCode, when you type "" to define a new json key, autocomplete suggestions are triggered. This makes sense, as it gives you key suggestions before you type anything (which can limit your suggestions). Can Monaco follow this same behavior when [quickSuggestions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#quicksuggestions) are enabled? This would preclude hacky workarounds like the one described in [this bug report](https://github.com/microsoft/monaco-editor/issues/2572#issue-943886939).

**Comment by alexdima** [comment]
cc @aeschli

**Comment by hujiulong** [comment]
@aeschli hi, when do you plan to release the new version? Is there any way to modify `triggerCharacters` before the new version is released?

**Comment by aeschli** [comment]
I believe there will be a new Monaco release in the coming week. (@hediet correct me if wrong)
