### ISSUE TITLE
► How to get the editor instance from an existing model

### ISSUE THREAD

**Issue by Danny-Engelman** [Microsoft/monaco-editor#258]
Question

Office365 uses the Monaco editor.

I can successfully window.open() an HTML file from a SharePoint Document Library, using the correct URL

I can run code to insert a fragment:

```
function insertFragment(html,line){
    var model=monaco.editor.getModels()[0];
    var range=new monaco.Range(line, 1, line, 1);
    var e=[{ "identifier": "insert"+line, "range": range, "text": html }];
    model.pushEditOperations({},e);
}
var line=5;
insertFragment('<DIV class="muxPart">\n</DIV>\n',line);
```

But where is the ``getPosition()`` method to get the current cursor location/active line number?

Issue 192 says its: ``editor.getPosition().lineNumber``

But monaco.editor doesn't have that method, neither has ``monaco.editor.getModels()[0]``

tnx

**Comment by microsoftsam** [comment]
You'll need an editor instance to call getPosition(). 
If you created your editor like one of the samples: 
https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-editor/index.html

you should be able to just call editor.getPosition();

**Comment by Danny-Engelman** [comment]
This editor/page is created by Office365/SharePoint, not by me

``editor`` is not defined on the global scope, but I can get ``monaco.editor.getModels[0]``
note: ``monaco.editor`` does **not** have a method getPosition()


![](http://i.imgur.com/uRINLTR.jpg)

**Comment by akosyakov** [comment]
@Danny-Engelman I don't think it is possible to get an editor from a model, since a model can exist without an editor at all or be shared by several editors.

You can try to have a look at internals of Monaco/VSCode whether they keep all editors somewhere or keep track of them yourself.

**Comment by Danny-Engelman** [comment]
I get a page that's it, I do not instantiate anything myself.

But I do want to interact with that editor
Because this editor is way-cool to edit existing HTML5 in a SharePoint environment.

I was thinking a brute-force approach, loop every object in memory and see where there is a getPosition method.

**Comment by alexandrudima** [comment]
Please reach out to the SharePoint team and ask them for guidance.
