### ISSUE TITLE
Open JSON autocomplete suggestions based on JSON schema after quotation mark.

### ISSUE THREAD

**Issue by 3da** [microsoft/monaco-editor#2584]
How to open suggestions automatically after writing quotation mark?

In this example it only works with CTRL+SPACE
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Comment by hediet** [comment]
You can configure the quotation mark as trigger character!

**Comment by 3da** [comment]
> You can configure the quotation mark as trigger character!
How to configure this? Couldn't find in documentation or google.

**Comment by tslater** [comment]
I'm not seeing any code completion in JSON even using ctrl or cmd + space. Am I missing something...Looking at the  example with registering json-schemas:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/monaco-editor/issues/2579
