### ISSUE TITLE
Display cursor position (column number too)

### ISSUE THREAD

**Issue by saghan** [microsoft/monaco-editor#2588]
The ability to view the current cursor position would be really useful. I know we can see line number, but if we could also see column number, it would be very useful. Like how chrome developer tools, notepad, vs code and most text editors show this.

![image](https://user-images.githubusercontent.com/3251436/127073275-511ae7cd-b6f4-47b9-8d02-d2f04f3c8c4f.png)

**Comment by spahnke** [comment]
You can also implement this yourself pretty easily by listening on the `editor.onDidChangeCursorPosition` event (https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#ondidchangecursorposition).
