### ISSUE TITLE
Can't open CodeAction error for attachShadow

### ISSUE THREAD

**Issue by hawkerm** [microsoft/monaco-editor#2589]
After registering a CodeAction and trying to click the light-bulb which appears in the editor this is outputted to the console:

```
Exception was thrown at line 331, column 571 in ms-appx-web://258ac4a1-cff0-4f92-9a16-26577934a89f/Monaco/monaco-editor/min/vs/editor/editor.main.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'attachShadow'
```

Would instead expect the command menu to appear (but it doesn't).

**monaco-editor version:** 0.21.3
**Browser:** UWP WebView (Edge Legacy)
**OS:** 20H2 19042.1110
**Playground code that reproduces the issue:** Is there a way to load the playground with a specific version of Monaco? Code from this comment is the example: https://github.com/microsoft/monaco-editor/issues/1890#issuecomment-886996311

It's working fine in playground with latest Monaco in latest Edge, but not within a WebView component. As far as I'm aware version 21.3 is the last version to support that browser. However, WebView with Edge Legacy should still be under support with the OS/Windows SDK.

It appears this may be trying to use the Shadow DOM? However, that's not an Edge Legacy feature that's available. So what is the last version tested and supported with Legacy Edge?

**Comment by alexdima** [comment]
Edge Legacy is no longer supported. The changelog document contains the relevant information regarding that.

`attachShadow` throws because the editor has began using shadow DOM for the context menu. This can be disabled using an option called `useShadowDOM` which can be set to `false` to disable this.

**Comment by hawkerm** [comment]
@alexdima the version I was using 0.21.3 was shipped two months before the end for Edge Legacy support, but still enabled the Shadow DOM which would have been unsupported.

The `useShadowDOM` flag wasn't added until two months after the version you said would no longer support Edge Legacy. So neither of those things helps.

At least `WebView2` is coming to UWP now though... https://github.com/microsoft/microsoft-ui-xaml/issues/5610
