### ISSUE TITLE
How to control the tab size for different type of files?

### ISSUE THREAD

**Issue by PinkyJie** [Microsoft/monaco-editor#259]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: macOS 10.11

I found sometimes the tab size is 2, sometimes the tab size is 4, even is one file, the tab size is different. Is there a API to set tab size for different files?

**Comment by philcchen** [comment]
I think you might be looking for [updateOptions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#updateoptions) where you can pass in options for tabSize.

Additionally, there is also 

- [detectIndentation](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#detectindentation)
- [getOneIndent](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#getoneindent)
- [normalizeIndentation](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#normalizeindentation)

**Comment by PinkyJie** [comment]
@philcchen Thanks, I'll check it.

**Comment by PinkyJie** [comment]
@philcchen I'm still a little confused. It seems there is no direct option for `updateOptions` to set tabSize.
