### ISSUE TITLE
[Suggestion] Bundle marked as ES module instead of UMD module

### ISSUE THREAD

**Issue by yfwz100** [microsoft/monaco-editor#2591]
At present, the bundled marked is in UMD module format, which will cause problems for ESM bundlers like esbuild and vite to use the monaco editor.

I suggest to use an ESM version of marked to support esbuild or other pure ESM bundlers.

**Comment by hediet** [comment]
Thanks for reaching out! We don't have the ressources to address this right now, but we are open for PRs by the community!

At some point we want to provide a solid ES module solution though.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/monaco-editor/issues/2671
