### ISSUE TITLE
Monaco validates invalid JSON as valid and allowComments has no effect

### ISSUE THREAD

**Issue by aeneasr** [microsoft/monaco-editor#2593]
**monaco-editor version:** Version available on https://microsoft.github.io/monaco-editor/playground.html
**Browser:** Safari & Chrome
**OS:** macOS
**Playground code that reproduces the issue:**

The following code is not valid JSON (it has a trailing comma see #2400) and additionally a comment, which was turned off using `allowComments: false`. However, monaco validates this as valid JSON, which it is not.

```js
var jsonCode = `{
    "p1": "v3",
    // should not validate
    "p2": false,
}`

var modelUri = monaco.Uri.parse("a://b/foo.json"); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, "json", modelUri);

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    allowComments: false
});

monaco.editor.create(document.getElementById("container"), {
    model: model
});
```

<img width="1392" alt="Bildschirmfoto 2021-07-31 um 16 23 44" src="https://user-images.githubusercontent.com/3372410/127742879-04d6ff82-9f92-4376-958f-b884322dbb8c.png">

**Comment by aeschli** [comment]
When I try the steps above, I see the expected errors. Tried on Firefox and Edge.

- open https://microsoft.github.io/monaco-editor/playground.html
- paste the code snippet above, press run

![image](https://user-images.githubusercontent.com/6461412/129571173-86b21900-85f2-448b-8fb6-3cfe8776f150.png)

Maybe a new Monaco version with a fix got deployed?

Please reopen if you still see the issue

**Comment by aeneasr** [comment]
Indeed!
