### ISSUE TITLE
No default prepopulated values when enums used in JSON Schema

### ISSUE THREAD

**Issue by mohdashraf010897** [microsoft/monaco-editor#2594]
**monaco-editor version:** 0.21.0
**Browser:** Google Chrome Version 92.0.4515.107 (Official Build) (x86_64)
**OS:** macOS Big Sur version 11.4
**Playground code that reproduces the issue:** https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Issue Description**: When specifying a JSON property with `enum`, no pre-population of the default value is done as in other cases like `type: string` or `type: object`, etc. 

**Replicate the issue**: 

1. Go to the [monaco playground: JSON defaults](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults). 

2. On the right side, inside the editor, remove the prepopulated properties and trigger autosuggest to see properties: `p1`, `p2` suggested, click on say `p1`. 
![image](https://user-images.githubusercontent.com/57627350/127813758-b0a9d58f-b660-4e23-aede-6a6cfa3799e1.png)

**`Result`**: ![image](https://user-images.githubusercontent.com/57627350/127814037-f7afe412-b46d-439e-80d2-b80b0b245bc7.png)

**`Expected`**: 
![image](https://user-images.githubusercontent.com/57627350/127814200-086fc7ea-113d-45c3-a16b-d820fac068d9.png)

https://www.loom.com/share/387a3b367fa64878a176061f3db8aec3

**Comment by aeschli** [comment]
The idea is that instead of entering a value, code completion is re-triggered automatically.

That's currently not implemented in the monaco json editor. I added support withhttps://github.com/microsoft/monaco-json/commit/c7c029db8e955092b148d0d0963849665fd1be68. It will be in next month's release.
