### ISSUE TITLE
Improve import suggestions module path.

### ISSUE THREAD

**Issue by ErkoKnoll** [microsoft/monaco-editor#2596]
Currently (on version 0.25.1) Monaco seems to be able to provide import suggestions automatically as following:
<img width="1105" alt="Screenshot 2021-08-03 at 15 48 28" src="https://user-images.githubusercontent.com/9930079/128019219-1e3ca683-3bfa-43f9-9027-70896ea7037e.png">
However, import suggestions use internal path name that needs to be used with `addExtraLib`, which is fine but it would be really nice if the import suggestions would default to shorter and prettier path, which would be `@avst-api/jira-cloud-v3/definitions/PageOfCommentsAsResponse` for the example above.

**Comment by orta** [comment]
This is probably coming with the 4.4 TS update: https://twitter.com/atcb/status/1419745504351555611

**Comment by lstkz** [comment]
@orta 
monaco-editor@0.27.0 uses TS 4.3.2. Are there any plans to use 4.4? Is it possible to use a different version of TS without forking monaco-editor?

**Comment by orta** [comment]
4.4 isn't publicly released yet, but yeah, you'd need a fork of Monaco-editor to use your own pre-release version of TypeScript. You can read the referenced js scripts in https://github.com/microsoft/TypeScript-Make-Monaco-Builds/blob/master/.github/workflows/nightly.yml to learn how to do it yourself - and/or use https://www.npmjs.com/package/@typescript-deploys/monaco-editor which is a npm mirror of our infra.

**Comment by ErkoKnoll** [comment]
Any progress getting Monaco shipped with TS 4.4?

**Comment by hediet** [comment]
The latest version of monaco ships with TS 4.5.5
