### ISSUE TITLE
JSX part of React component without error

### ISSUE THREAD

**Issue by hmelenok** [microsoft/monaco-editor#2599]
Didn't seem to find a duplicate.

Situation: 
- Regular component written with JSX
- All imports and all 
- Seems working pretty fine with whole module
```jsx 
import React from 'react';

export default class AdminTableMobile extends React.Component {
  render() {
    const rows = get(this, 'props.rows', []);
    const headers = get(this, 'props.headers', {});
    const manageUsers = get(this, 'props.manageUsers', false);
    const toRender = keys(headers);

    return (
      <div>
        {map(rows, row => (
          <div key={row._id}>
            {row.map(value, key) => (
              <div>
                <div>{`${key}.text`}</div>
                <div>{value}</div>
              </div>
            ))}
            <div>{row.action}</div>
          </div>
        ))}
      </div>
    );
  }
}
AdminTableMobile.displayName = 'AdminTableMobile';

```
But for educational purposes, we need to safely show only few lines of component like this:

```jsx
  {row.map(value, key) => (
    <div>
      <div>{`${key}.text`}</div>
      <div>{value}</div>
    </div>
  ))}
  <div>{row.action}</div>
```

like all components defined but the active editable part is only part of it. 

So are there a feature that will allow doing next:
- Render only focused part of the whole code without syntax errors (like you have a code scope but it collapsed or hidden)?
- Render component but with editable only center part?

**Comment by rcjsuen** [comment]
@hmelenok See #45 and #953.

**Comment by hmelenok** [comment]
Thanks @rcjsuen you are the best!
