### ISSUE TITLE
what is the languageId for .mm file?

### ISSUE THREAD

**Issue by TerryChan** [microsoft/monaco-editor#2606]
What is the languageId for .mm file  - Objective-C++, for example: https://github.com/Tencent/MMKV/blob/master/iOS/MMKV/MMKV/libMMKV.mm
I need to give correct languageId to the method below for .mm file, to get the highlight work.

`
    export function setModelLanguage(model: ITextModel, languageId: string): void;
`

By the way, is there a languageId list to file extension (or programming language) map?

**Comment by rcjsuen** [comment]
The language ids that Monaco has out-of-the-box is coming from the [microsoft/monaco-languages repository](https://github.com/microsoft/monaco-languages) as far as I know. Based on its [`src`](https://github.com/microsoft/monaco-languages/tree/c31d1933fa9cb0b6bb3d19d109728f58bc885742/src) folder, I don't see Objective-C++ mentioned anywhere so maybe it's not available.
