### ISSUE TITLE
trailingCommas missing in monaco.languages.json.DiagnosticsOptions

### ISSUE THREAD

**Issue by ckorherr** [microsoft/monaco-editor#2608]
`trailingCommas` is missing in `monaco.languages.json.DiagnosticsOptions`, even though it can be used:

```js
monaco.editor.create(document.getElementById("container"), {
  value: '{\n  "a": 1,\n}',
  language: "json"
});

monaco.languages.json.jsonDefaults.diagnosticsOptions.trailingCommas = 'error';
```

(https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.json.diagnosticsoptions.html)

**Comment by aeschli** [comment]
I tried this with the latest deployed version of the monaco editor and this seems to work:
![image](https://user-images.githubusercontent.com/6461412/129687791-d04b651e-4273-4bec-9a48-483c3c9f4800.png)

I see code assist for `trailingCommas` and I see it working e.g. when by setting
`monaco.languages.json.jsonDefaults.diagnosticsOptions.trailingCommas = 'ignore';`

**Comment by wegry** [comment]
If you're like me and using `react-monaco-editor`, it looks like `monaco-editor@0.26.1` doesn't have `trailingCommas` in the typings.

```
yarn why monaco-editor
├─ my-project@workspace:.
│  └─ monaco-editor@npm:0.27.0 (via npm:^0.27.0)
│
├─ react-monaco-editor@npm:0.44.0
│  └─ monaco-editor@npm:0.26.1 (via npm:^0.26.1)
│
└─ react-monaco-editor@npm:0.44.0 [7e7f8]
   └─ monaco-editor@npm:0.26.1 (via npm:^0.26.1)
```

I'm going to try overriding the pinned version, I think.
