### ISSUE TITLE
Ability to load as a global with old-school script tags.

### ISSUE THREAD

**Issue by coolaj86** [microsoft/monaco-editor#2610]
Similar to the issue about ES Modules (https://github.com/microsoft/monaco-editor/issues/2335), but just using the old school, tried-and-true script tags:

```html
<script type="text/javascript" src="https://unpkg.com/monaco-editor@latest/min/vs/whatever-is-needed-for-create.js"></script>
<script>
    window.Monaco.editor.create(...);
</script>
```

**Why not AMD?**

"AMD" seems like the worst of all worlds - pollutes the global namespace with things I don't want, and doesn't let me know when the thing is loaded and ready to use.

A decent workaround might be providing some sort of `Promise` to at least know when loading has finished, which I guess is easy enough to wrap.

**Why not ESM?**

The problem with ESM is that it gives you the whole "what color is your function" problem, but for modules.

**The other 50%**

I realize that the ~50% of web developers still using JavaScript and jQuery who aren't really part of "the JavaScript community" isn't really the target audience for this... but I thought I'd throw it out there anyway. 'Simple is nice' and all that.

**Comment by stoanarrr** [comment]
we're using the monaco editor like so.
```pug
doctype html
html(lang="en")
	head(lang="en")
	//....
	body

		script.
			var require = {paths: {'vs': '<your cdn>/monaco-editor/min/vs'}};
		script(src="<your cdn>/monaco-editor/min/vs/loader.js")
		script(src="<your cdn>/monaco-editor/min/vs/editor/editor.main.nls.js")
		script(src="<your cdn>/monaco-editor/min/vs/editor/editor.main.js") 
```
with this method you do have the monaco object attached to the window.

**Comment by alexdima** [comment]
There is a sample for this at https://github.com/microsoft/monaco-editor-samples/blob/main/browser-script-editor/index.html
