### ISSUE TITLE
Editor logs error in chrome 83 and older versions

### ISSUE THREAD

**Issue by saghan** [microsoft/monaco-editor#2611]
Steps to reproduce:
Open monaco playground.

**monaco-editor version:** 0.25.2
**Browser:** chrome 83
**OS:** windows 10
**Playground code that reproduces the issue:** https://microsoft.github.io/monaco-editor/playground.html
![image](https://user-images.githubusercontent.com/3251436/129076591-f2940845-1e4c-4ab4-842b-46353fd5882b.png)

**Comment by alexdima** [comment]
No, we only support the latest version.

**Comment by hediet** [comment]
@saghan I'm sorry, but as Alex said, we don't support that version.

If you figure out why it is broken and if it is a simple change that does not have technical implications, feel free to submit a pull request!
