### ISSUE TITLE
Disable Command palette

### ISSUE THREAD

**Issue by Womercode** [microsoft/monaco-editor#2619]
Hey guys,

I'm creating an electron app and I use monaco-editor. My app has his own command palette and I want to disable the default palette. I already saw issue #419 but I didn't really understand how he did.

Thanks

**Comment by oldrich-s** [comment]
I did not test it but I think it would work to addEventListener on the monaco div element with capture: true. This way, your callback will be called before monaco and you can do stopImmediatePropagation to block the monaco action.

**Comment by Womercode** [comment]
I tried what you did but I have an idea, can someone give me the command palette class

**Comment by Womercode** [comment]
Finally I found by myself. I hid the command palette in css with that code :

```css    
.monaco-quick-open-widget {
    display: none;
}
```
