### ISSUE TITLE
Multiple Monaco Editors on the same HTML page

### ISSUE THREAD

**Issue by johnfn** [Microsoft/monaco-editor#262]
monaco-editor npm version: latest
Browser: Chrome
OS: MacOS Sierra

I am trying to have more than 1 monaco editor open on the same page. However, just copy and pasting the code to create an editor seems to make both of them use the same context or something. 

E.g. when editing TypeScript:

```
	require([
		'vs/language/typescript/src/monaco.contribution'
	], function() {
		var editor = monaco.editor.create(document.getElementById('container1'), {
			value: [
				'console.log("const x = 1")'
			].join('\n'),
			language: 'typescript'
		});

		var editor = monaco.editor.create(document.getElementById('container2'), {
			value: [
				'console.log("const x = 1")'
			].join('\n'),
			language: 'typescript'
		});
	});
```

This will show an error in `container2` because `const x` has already been defined in `container1`.

How can I get both editors to operate under separate contexts? 

I tried using an iframe, and it seems to work. However, it feels like a hack and it is incredibly laggy on load.

**Comment by rsbondi** [comment]
This works for me if I use `var editor2` for the second one, I am not using typescript but I don't imagine that to be an issue

**Comment by stefan-lacatus** [comment]
I can also reproduce this issue.  In the application that we are developing need to have multiple editors open at the same time, with different contexts.

By context sharing means that variables that are declared in one editor are available for autocomplete in the other. See the example below:
```
var editor = monaco.editor.create(document.getElementById('container1'), {
    value: [
        'var test: number;'
    ].join('\n'),
    language: 'typescript'
});

var editor2 = monaco.editor.create(document.getElementById('container2'), {
    value: [
        'var test: string;'
    ].join('\n'),
    language: 'typescript'
});
```
In the second editor, the `test `variable appears already defined as number. 
This issue applies to both javascript and typescript. My assumption is that all the editors share a single typescript worker. When using them in iframes, they would use separate workers. 
So, is there any way to have multiple editors on the same page, with different contexts?

**Comment by stefan-lacatus** [comment]
I've had some more time to look into this and managed to find a solution that works in my scenario. 
There were three ways of fixing this issue:
1.  Having each editor use a different typescript webworker: This would have involved patching monaco-typescript and I think it would have brought with it a performance penalty.
2. Add a new line at the start of every editor to mark that it does not export any symbols (something along the lines of `module.exports=undefined;`
3. Patching typescriptServices.js to automatically mark all the models that have an uri that contains `inmemory` (this are the uris generated by monaco) as non-global. For this i've patched the function `setExternalModuleIndicator` and added this at the end:
```
 if(sourceFile.fileName.indexOf("inmemory") != -1) {
         sourceFile.externalModuleIndicator = sourceFile;
}
```
While this is a very ugly hack, it works in my environment.

**Comment by jrieken** [comment]
> Having each editor use a different typescript webworker: This would have involved patching monaco-typescript and I think it would have brought with it a performance penalty.

Yes, the monaco-typescript language isn't designed for having multiple contexts running on different *projects*. It's kept simple and operates only on a single virtual project. At the moment we have no plans of making monaco-typescript more powerful in that respect.

**Comment by johnfn** [comment]
Fair enough, but should you really close this issue if it hasn't been solved? :P

**Comment by jrieken** [comment]
I am not planning to solve this issue. I think it's fair to have it closed when no code changes are to be expected.
