### ISSUE TITLE
Monaco cannot properly consume low-speed two finger scroll events

### ISSUE THREAD

**Issue by Chigusa0w0** [microsoft/monaco-editor#2623]
**monaco-editor version:** Self-hosted 0.26.1 & Monaco Playground 0.27.0
**Browser:** Edge 92
**OS:** Windows 20H2
**Playground code that reproduces the issue:**

1. Navigate to https://microsoft.github.io/monaco-editor/playground.html

2. Run the following code in the left panel of the playground.
```js
monaco.editor.create(document.getElementById("container"), {
	value: "aaaa" + "\n".repeat(100) + "aaaa", // or any other value that makes the editor scrollable
	scrollbar: { alwaysConsumeMouseWheel: false }, // <- this option is necessary
	language: "text"
});
```

3. Inspect page element `<body>`, set `element.style` `overflow: unset; height: 3000px;` (or any other value that makes the page scrollable)
![image](https://user-images.githubusercontent.com/9378097/129978716-48610d2c-5e1b-45e9-a6dc-98d8d9a1f112.png)

4. Now, when scrolling in the right panel of the playground with trackpad two-finger scrolling, there is a chance that the whole page scrolls instead of the editor. (Although the editor still have some lines not yet displayed on the scrolling direction)

5. This unexpected behavior has a higher reproduction chance when scrolling downward at low-speed. The browser's Inertial Scrolling may also trigger this behavior.

6. This behavior cannot reproduce when `alwaysConsumeMouseWheel: true`. But with `always...: true`, the Monaco editor will not respond to low-speed two-finger scrolling.

**Comment by hediet** [comment]
Unfortunately, we don't have the resources to address this right now, but we're more than happy to accept a PR that fixes this!

**Comment by Chigusa0w0** [comment]
@hediet In local install VSCode 1.59 & Web Test Playground VSCode 1.60, slow downward trackpad two-finger scrolling are ignored/not-consumed by VSCode too.

After play with VSCode Playground for a while, now I can confirm that this is a floating point rounding problem in the VSC codebase.

A PR will come in later.
