### ISSUE TITLE
Add usage with Vite

### ISSUE THREAD

**Issue by thien-do** [microsoft/monaco-editor#2629]
Are you open to have a section regarding Vite js in the [INTEGRATE ESM](https://github.com/microsoft/monaco-editor/blob/main/docs/integrate-esm.md) doc? It would be short since Viet supports Monaco's workers out of the box: https://github.com/vitejs/vite/discussions/1791#discussioncomment-321046

**Comment by alexdima** [comment]
PR welcome.
