### ISSUE TITLE
Disposables in setupMode in official plugins are unused

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/monaco-editor#2642]
**monaco-editor version:** 0.27.0
**Browser:** N/A
**OS:** N/A
**Playground code that reproduces the issue:** N/A

In `monaco-css`, `monaco-html`, `monaco-json`, and `monaco-typescript`, there is a function named [`setupMode`](https://github.com/microsoft/monaco-json/blob/main/src/jsonMode.ts#L13). This function sets up editor features, then returns a disposable, which combines a number of collected disposables. However, where `setupMode` is used in [`contribution.monaco.ts`](https://github.com/microsoft/monaco-json/blob/main/src/monaco.contribution.ts#L217), the return value is unused.

I’m wondering if if the disposables are supposed to be used or if the return value, and therefor the array of disposables should be removed.

**Comment by alexdima** [comment]
We've never implemented the ability to "unload" a language, so the disposables are never called.

**Comment by remcohaszing** [comment]
Is this something that’s planned? Otherwise I’m going to remove the disposable logic from [`monaco-yaml`](https://github.com/remcohaszing/monaco-yaml)

**Comment by alexdima** [comment]
There's no plans to add unloading a language.

**Comment by remcohaszing** [comment]
I’ll leave this open so you can use it to track removal of disposables in the official monaco plugins. Otherwise feel free to close this issue.
