### ISSUE TITLE
Suggestions do not auto trigger when word begins with a digit

### ISSUE THREAD

**Issue by MakullaMa** [Microsoft/monaco-editor#265]
Hey,

I am using monaco-editor as an editor for a custom DSL with syntax highlighting and a custom `completionItemsProvider`.

Now when I start typing a word beginning with a non digit character the suggestions widget automatically opens and my provider is asked for suggestions. However this does not occur when the I start with a digit - unfortunately my DSL supports words starting with digits or words containing digits only.

I was able to track down the source of this behavior to the following lines in the `SuggestModel`:

```javascript
Context.prototype.shouldAutoTrigger = function () {
	if (this.wordBefore.length === 0) {
		// Word before position is empty
		return false;
	}
	if (!isNaN(Number(this.wordBefore))) {
		// Word before is number only
		return false;
	}
	if (this.wordAfter.length > 0) {
		// Word after position is non empty
		return false;
	}
	return true;
};
```

There it says that suggestions do not auto trigger when the word is number only. I would like to understand this - or like to know if there is a way to change this default behavior.

Thanks!

monaco-editor npm version: 0.7.0
Browser: IE11, Edge, Chrome 54, Firefox 49
OS: Windows 10

**Comment by jrieken** [comment]
Yeah, the code above outlines a part of our quick suggestions logic, that is 24x7 IntelliSense as you type, and we figured that it's not appreciated to see IntelliSense pop up on certain character classes, like numbers or separator characters. 

IntelliSense can always be manually triggered via Ctrl+Space or via trigger character which in return can be numbers or anything else.
