### ISSUE TITLE
Autocomplete is not showing properly

### ISSUE THREAD

**Issue by firescrypt** [microsoft/monaco-editor#2651]
Hey hi I am trying to use monaco editor but the autocomplete is not showing properly. Moreover I can't replicate the same in another HTML page

![Screenshot from 2021-09-05 13-03-45](https://user-images.githubusercontent.com/83104991/132119295-5f232e67-ba12-4a71-82b9-11f9588ff4c8.png)

**Comment by rcjsuen** [comment]
@firescrypt Looks like an issue with your CSS.
