### ISSUE TITLE
import hooks

### ISSUE THREAD

**Issue by chenqiangkobe** [microsoft/monaco-editor#2653]
addExtralib method can perform the intellisense, but  too many files to get by HTTP. Is there any hooks when i used import to load file on-demand？
for example, in editor：
import { FrameContext } from '@farris/devkit';
how to get file '@farris/devkit' when i enter the code above，Is there any hooks？

**Comment by egorsmth** [comment]
Are there any way to handle this case right now? May be some event like onImportError?

**Comment by chenqiangkobe** [comment]
editor.onDidChangeModelContent , editor.getValue() can get the codes in the editor. 

var exp = /import\s*[\s\S]*?\s*from\s+'(.+)'/g;

  onInit(editor) {
    const monaco: any = (window as any).monaco;
      editor.editor.onDidChangeModelContent(e => {
        const code = editor.getValue();
           let importArray,list;
          // list = libs name
          while ( (importArray = exp.exec(code)) ) {
            if (importArray && importArray.length > 0) {
              importArray.forEach((element, index) => {
                if ( index % 2 === 1) {
                   list[element] = element;
                }
              });
            }
          }
      });
    }
  }
