### ISSUE TITLE
Add support for custom completion item icons

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/monaco-editor#2654]
The current icon set available for code completion items is pretty limited and mostly designed for programming languages. However there can be many other use cases where the defined icons do not match, for instance database objects (schemas, tables, indexes etc.).

That's why I would like to ask for a way to define own icons for completion items. At least allow arbitrary codicons (even though they are limited as well, e.g. there's no schema icon).

**Comment by Jacob273** [comment]
I'd like to have different icons for some of the enum values which are displayed in suggestions list.
e.g:

ICON1 Default
ICON2 Info
ICON3 Warning
ICON4 Danger
ICON5 OtherValue1
ICON5 OtherValue2
ICON5 OtherValue3

I'd like to use five different icons. How I can achieve that at the moment?

**Comment by daman-xgen** [comment]
Any updates on this?

**Comment by jrieken** [comment]
There are no plans to do this
