### ISSUE TITLE
Support for lines having different heights

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#2657]
I work on a Markdown-based note-taking app, and one of the requests I'm hearing most frequently is being able to have headings in the editor is a bigger font, so that they are easier to spot and more closely resemble their look once rendered.

For example a competitor app can do this because they are using CodeMirror:

<img width="1440" alt="Screen Shot 2021-09-11 at 15 17 10" src="https://user-images.githubusercontent.com/1812093/132949149-c7280b35-fffc-4714-beba-fa65970554e8.png">

While mine, which uses Monaco, can't do the same:

<img width="1280" alt="Screen Shot 2021-09-11 at 15 18 42" src="https://user-images.githubusercontent.com/1812093/132949241-d47dc4d1-3c58-4609-9ff5-9b5881b2fa4e.png">

Another somewhat subtle but noticeable improvement deriving from being able to do this is that the height of the Markdown text and the height of the HTML document can match much more closely, which leads to buttery-smooth synchronized scrolling. If the height of headings don't match at all the scrolling gets a little bit wobbly.

It'd be really nice to have this capability in Monaco. I understand that Monaco is perhaps more geared toward code than CodeMirror is, but Markdown is perhaps what every programmer uses too and this would be a nice improvement for them.

**Comment by hediet** [comment]
Let's track this in https://github.com/microsoft/vscode/issues/147067.

**Comment by sagarkardani** [comment]
@fabiospampinato
Have you somehow achieved variable line heights ?
I have some different line padding related requirements [here](https://github.com/microsoft/monaco-editor/issues/3481).

**Comment by fabiospampinato** [comment]
@sagarkardani no I'm not aware of a reasonable way of doing it.
