### ISSUE TITLE
Model Markers not getting completely removed 

### ISSUE THREAD

**Issue by vivekburman** [microsoft/monaco-editor#2659]
![image](https://user-images.githubusercontent.com/29746680/133206087-08bfdf21-493d-4665-8281-28f160f03f5f.png)
![image](https://user-images.githubusercontent.com/29746680/133206126-f7fe9695-4e2e-4861-9d68-2c3e6259a9b9.png)

As you can see from above images, even after deleting content under marker region the marker still remains... How can i resolve this???
![image](https://user-images.githubusercontent.com/29746680/133206214-bdbe7f3e-0874-4fb2-bb95-8fd0893dbe5c.png)

**Comment by rcjsuen** [comment]
@vivekburman You need to call `setModelMarkers(*)` again with the appropriate markers (in this case, with an empty array).

**Comment by vivekburman** [comment]
Yup, as of now hooking into onDidModelContentChange and doing the same. But its weird behaviour that it partially clears up when deleting content. But just stays for that one character. As you can see in above image its range has reduced to 1 automatically by using backspaces but getting down to zero

**Comment by rcjsuen** [comment]
> But its weird behaviour that it partially clears up when deleting content. But just stays for that one character. As you can see in above image its range has reduced to 1 automatically by using backspaces but not getting down to zero

I think the expectation is that you update the model with `setModelMarkers(*)` when the model gets changed. It also allows you to use a zero-length marker for marking words without knowing the length of the word.

**Comment by vivekburman** [comment]
this sample code base has no such implementation. Only one time setting model markers as shown in above screenshot. Post that i just backspace that region of text.

**Comment by rcjsuen** [comment]
> this sample code base has no such implementation.

I recognize that. What I mean is that I think the expectation is that `setModelMarkers(*)` is used when the content is changed so the fact that it highlights "nothing" even when there is nothing there is not a critical issue.

If you are going to let users edit something, if they fix the problem the error should go away, but if they introduce a problem the error should show up. Hence it does not seem reasonable to expect you to respond to content changes and update the markers of the model accordingly.
