### ISSUE TITLE
Issue with `NodeIntegrationInWorker` set to True

### ISSUE THREAD

**Issue by rroessler** [microsoft/monaco-editor#2675]
Similar to issues [2344](https://github.com/microsoft/monaco-editor/issues/2344) and [2282](https://github.com/microsoft/monaco-editor/issues/2282), where setting `NodeIntegrationInWorker` to true results in any auto-completion and hover instances for in-built languages to fail.

This issue can be reproduced by adding the `nodeIntegrationInWorker: true` option to the [electron-amd-nodeintegration](https://github.com/microsoft/monaco-editor-samples/tree/main/electron-amd-nodeIntegration) example.

Are there any known workarounds? At this stage since I am using a a web worker to handle a chokidar instance I am needing to have this option set to true, and my only solution at this stage is to scrape node integration in workers and use dummy window instances to coordinate this, however this may lead to more problems down the line in terms of total opened windows. Any solutions?

**Comment by alexdima** [comment]
This should now work thanks to:
* https://github.com/microsoft/vscode-loader/commit/c40026872b356f891f9b3e0e1b9bcd8789437d2a , 
* https://github.com/microsoft/vscode-loader/commit/2ba8ee2ffb2f6630382b6e62ef2934384f0fc123 , 
* https://github.com/microsoft/vscode-loader/commit/89814b82f28d8a39116782147ac075dfa6e7c5d2 , 
* https://github.com/microsoft/vscode-loader/commit/ff669e7ea3af7b76b983b69873304405132f6fdb
