### ISSUE TITLE
Support Java 17 highlighting

### ISSUE THREAD

**Issue by aaaaaa2493** [microsoft/monaco-editor#2677]
monaco-editor version: 0.28.0
Browser: Chrome
OS: Windows

Java 17 is out and it's LTS release. Many projects will transit form Java 11 to Java 17. However, it seems that monaco doesn't support Java 12 to 17 syntax features.

1. Text Blocks ([JEP 378](https://openjdk.java.net/jeps/378))

The entire string should be colored in the same color (brown in `Visual Studio` theme).

Examples:

```java
String iliadQuote = """
                "But raging still, amidst his navy sat
                The stern Achilles, stedfast in his hate;
                Nor mix’d in combat, nor in council join’d;
                But wasting cares lay heavy on his mind:
                In his black thoughts revenge and slaughter roll,
                And scenes of blood rise dreadful in his soul."
                """;

String query = """
                SELECT "EMP_ID", "LAST_NAME" FROM "EMPLOYEE_TB"
                WHERE "CITY" = 'INDIANAPOLIS'
                ORDER BY "EMP_ID", "LAST_NAME";
                """;

String html = """
            <html>
                <body>
                    <p>Hello, world</p>
                </body>
            </html>
              """;

String example = """
                 You can use "single" or ""double"" quotes any time you like. 
                 But you must escape one if you want triple quotes: \""""
                 or \"\""" if you want four. 
                 The line after me will be directly concatenated onto the same line\
                 But this line will preserve a single trailing space at the end\s
                 And this line will keep six trailing spaces     \s 
                 """;
```

2. Various keywords for other features.

Other features seem to be fine, except the new keywords isn't highlighted properly.

Examples:
a. `yield` in switch expressions ([JEP 361](https://openjdk.java.net/jeps/361)). Should be the same color as `break` and `return`

```java
String group = switch (planet) {
  case EARTH, MARS -> {
    System.out.println("inner planet");
    System.out.println("made up mostly of rock");
    yield "inner";
  }
  case JUPITER, SATURN -> {
    System.out.println("outer planet");
    System.out.println("ball of gas");
    yield "outer";
  }
};
```

b. `record` in records ([JEP 395](https://openjdk.java.net/jeps/395)). Should be the same color as `class`

```java
record Point(int x, int y) { }

public void withLocalRecord() {
  record Point(int x, int y) { };
  Point p = new Point(1, 2);
}
```

c. `sealed`, `permits`, `non-sealed` in sealed classes ([JEP 409](https://openjdk.java.net/jeps/409)).
`sealed` and `non-sealed` should be the same color as `public`, `abstract` etc.
`permits` should be the same color as `extends` and `implements`.

```java
public sealed class Parent
  permits ChildA, ChildB, ChildC { ... }

sealed interface Parent
  permits ChildA, ChildB, ChildC { ... }

sealed class C permits D, E {}

non-sealed class D extends C {}
```

**Comment by rcjsuen** [comment]
The Monarch syntax definition file for Java can be found [here](https://github.com/microsoft/monaco-languages/blob/1b8581c9aa6b47fa0e3003498e3e756a3d55f2b1/src/java/java.ts) if you would like to try making changes to it.
