### ISSUE TITLE
Incorrect character width measured while using a webfont

### ISSUE THREAD

**Issue by hillin** [microsoft/monaco-editor#2689]
When using a (remote) webfont, the width of certain characters, namely the whitespace and the tab arrow, are incorrectly measured.

In the playground example below you can see that when the text is selected, the spaces and tabs will be rendered in incorrect width.

A brief debugging shows that by the time monaco measures the character widths (in `DomCharWidthReader`), the webfont is not loaded yet, therefore a fallback font is used for the measurement, yielding incorrect results. I suppose monaco should wait for the [`document.fonts.ready`](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/ready) event before actually measuring the characters.

For now a workaround is:
- Attach an element which uses the webfont to the document, make it as small as possible, but it has to be visible. This tells the browser to load the webfont;
- Create the monaco editor in the `document.fonts.ready` callback

**monaco-editor version:** 0.27.0
**Browser:** Chrome 93
**OS:** Windows 10
**Playground code that reproduces the issue:**
**HTML**
```html
<link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/Iosevka/6.0.0/iosevka-etoile/iosevka-etoile.min.css">

<div id="container" style="height:100%;"></div>
```
**JS**
```js
monaco.editor.create(document.getElementById('container'), {
    value: `separated         by        spaces\nseparated\t\tby\t\ttabs`,
    fontFamily: 'Iosevka Etoile Web'
});
```

**Comment by alexdima** [comment]
We have added API for this case -> `monaco.editor.remeasureFonts()`.

**Comment by hillin** [comment]
Thanks, that worked!
