### ISSUE TITLE
Webpack compilation warning in 0.29.0 with DOMPurify

### ISSUE THREAD

**Issue by akphi** [microsoft/monaco-editor#2691]
Hi,

I just installed version `0.29.0` with `monaco-editor-webpack-plugin@5.0.0` and when I start my application with `webpack-dev-server` I start seeing the following warnings:

```
Compiled with problems:

WARNING in ../../node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js 250:4-21

export 'addHook' (imported as 'dompurify') was not found in './dompurify/dompurify.js' (possible exports: default)


WARNING in ../../node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js 269:4-21

export 'addHook' (imported as 'dompurify') was not found in './dompurify/dompurify.js' (possible exports: default)


WARNING in ../../node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js 281:15-33

export 'sanitize' (imported as 'dompurify') was not found in './dompurify/dompurify.js' (possible exports: default)


WARNING in ../../node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js 284:8-28

export 'removeHook' (imported as 'dompurify') was not found in './dompurify/dompurify.js' (possible exports: default)


WARNING in ../../node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js 285:8-28

export 'removeHook' (imported as 'dompurify') was not found in './dompurify/dompurify.js' (possible exports: default)
```

I used version 0.28.0 and never bumped into this error so I reckon this must come from the latest release, this is a warning so it's not a blocker, but it's quite inconvenient for developers using `webpack` and `webpack-dev-server`. Do you have plan to fix this (I'm not so sure, since this seems like code of `DOMPurify` and not `vscode`) or suggest any workaround for us?

Thank you so much!

**Comment by igarashitm** [comment]
This ends up as a build error for me. I used create-react-app. Downgraded to monaco-editor@0.28.1 + monaco-editor-webpack-plugin@4.2.0 then a build succeeded.
