### ISSUE TITLE
Custom JSON schema validation isn't working when using special characters in model URI

### ISSUE THREAD

**Issue by AnnaPerry** [microsoft/monaco-editor#2697]
Custom validation fails when provided model URI contains `#` or `?`:
![image](https://user-images.githubusercontent.com/16089760/137415956-5f93dcc2-9dbc-44e9-8b7c-bf99df814341.png)
![image](https://user-images.githubusercontent.com/16089760/137416002-72e1e355-67d2-43be-87ba-955898fcc67c.png)

A [playground](https://microsoft.github.io/monaco-editor/playground.html) code snippet:
```js
var jsonCode = [
    '{',
    '    "p1": "v3",',
    '    "p2": false',
    "}"
].join('\n');
//var modelUri = monaco.Uri.parse("a://b/foo.json"); 
var modelUri = monaco.Uri.parse("a://b/IhaveFragment#foo.json"); 
var model = monaco.editor.createModel(jsonCode, "json", modelUri);
var schema = {
        uri: "http://myserver/foo-schema.json", 
        fileMatch: [modelUri.toString()],
        schema: {
            type: "object",
            properties: {
                p1: {
                    enum: ["v1", "v2"]
                }
            }
        }
    }

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [schema]
});
const editor = monaco.editor.create(document.getElementById("container"), {
    model: model
});


```
We used to create URIs with `monaco.Uri.from()`, providing it `path` and `fragment`, so when `fragment` was actually present, our custom validation would stop working.
The workaround for us was to switch to `monaco.Uri.parse()` and use `encodeURIComponent()`. The characters that `encodeURIComponent()` doesn't handle, don't cause this issue.

**Comment by aeschli** [comment]
Don't use fragments (`#foo.json`) and queries in model URIs. 
Fragments and queries are ignored when the `fileMatch` pattern are matched.
Also note that  `fileMatch` is actually a file name or file path glob pattern. Putting an URI works if it only consists of scheme, authority, and path.
