### ISSUE TITLE
Add `editor.contentLeftPadding` to add padding between the `editorGutter` and `editor`.

### ISSUE THREAD

**Issue by shujaatak** [microsoft/monaco-editor#2698]
I am not describing this issue/feature request here to avoid redundancy as I have already mentioned this issue/feature request in VS Code project here https://github.com/microsoft/vscode/issues/135114. 

Please visit the above linked issue and check the **description and specially _SCREENSHOTS_** to better understand my point of view.

I am posting this feature request here too **because I don't know which team**(VS Code or Monaco-Editor) is responsible to resolve this issue.

**Comment by alexdima** [comment]
:+1: Let's track at https://github.com/microsoft/vscode/issues/135114
