### ISSUE TITLE
How to set tab width ?

### ISSUE THREAD

**Issue by lc-soft** [Microsoft/monaco-editor#270]
monaco-editor npm version: 0.7.0
Browser: Chrome 54.0.2840.99 
OS: Windows 10

I want custom code tab width, use 2 spaces or 8 spaces.

**Comment by alexlur** [comment]
Paging @alexandrudima.

**Comment by alexandrudima** [comment]
[`model.updateOptions({ tabSize: 8 })`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#updateoptions). You can create a model yourself via [`monaco.editor.createModel(...)`](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#createmodel) or use the one created by the editor on your behalf [`editor.getModel()`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#getmodel)

**Comment by alexlur** [comment]
Thanks a lot!

**Comment by chinchang** [comment]
@alexandrudima Is your solution deprecated now? Because for me it works when I call `updateOptions` on the editor itself, not on the model.

**Comment by ddemark** [comment]
@chinchang seems that tabSize is a language consideration rather than the editor itself: 
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.formattingoptions.html

**Comment by alexandrudima** [comment]
@chinchang `tabSize` is a model property, so one must call `updateOptions` on the model instance in order to change `tabSize`.
