### ISSUE TITLE
setWorkerOptions of customWorkerPath does not work in ESM version

### ISSUE THREAD

**Issue by weareoutman** [microsoft/monaco-editor#2705]
I tried the example from [this PR](https://github.com/microsoft/monaco-typescript/pull/65), but it didn't work, the custom worker never get loaded.

And after digging into it, I found the reason maybe [the function `create` in ts-worker](https://github.com/microsoft/monaco-typescript/blob/85d22afc032e67cb504979a28a7eb39d1107299c/src/tsWorker.ts#L474-L496) doesn't work in ESM version of monaco-editor. The `create` method seems to be ignored in  ESM version, See [relevant code in editorSimpleWorker.ts](https://github.com/microsoft/vscode/blob/cfcda1c0484974c757c7ed589ab3ad5afdf639e6/src/vs/editor/common/services/editorSimpleWorker.ts#L639-L648).

It would be great if this feature also works for ESM version, thank you.

**monaco-editor version:** 0.29.1
**Browser:** Chrome 95
**OS:** MacOS 11.6
**Playground code that reproduces the issue:**

```js
import * as monaco from "monaco-editor/esm/vs/editor/editor.api";
monaco.languages.typescript.typescriptDefaults.setWorkerOptions({ customWorkerPath });
```

**Comment by okikio** [comment]
@alexdima Yeah, I'm having the same problem, the entire `tsWorker.js` file, as well as the `create()` method are completely missing in `v0.31.0`
