### ISSUE TITLE
Separate sqlite and mssql in sql language

### ISSUE THREAD

**Issue by MasterOdin** [microsoft/monaco-editor#2711]
**monaco-editor version:** 0.29.1
**Browser:** Chrome
**OS:** macOS 11.6
**Playground code that reproduces the issue:**

```js
monaco.editor.create(document.getElementById("container"), {
	value: "RAISERROR",
	language: "sql"
});
```

----

The [sql](https://github.com/microsoft/monaco-languages/blob/main/src/sql/sql.ts) language in monaco contains keywords for both SQLite _and_ SQL Server with no way to differentiate. For example, `RAISEERROR` is a SQL Server only keyword that does not exist in most (any) other SQL dialects.

For using monaco in a general SQL editor, it would be preferable (I think) to see that the SQL Server stuff gets separated out into its own language similar to mysql, postgresql, and redshift. May also make sense to separate out SQLite into its own language and have `sql` just be the implementation as described by the ISO / ANSI standard?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Comment by MasterOdin** [comment]
Would a community pull request be accepted that does this? Or just a PR that adds a separate `sqlite` and `sqlserver` language definitions? I plan to do this anyway since it improves how @popsql works as an editor, but just want to make sure I land this work in the best place, be it in this repo specifically, or in a third-party one.

**Comment by MasterOdin** [comment]
To confirm what you'd accept, do you want me to leave `sql` like it is, make it just `sqlite` or `sqlserver`, or make it just the ANSI sql?

**Comment by hediet** [comment]
Thinking about it, we should only support ANSI sql. Because there are so many SQL dialects, consumers of the monaco editor should contribute their own SQL dialect.

Feel free to create a PR to remove the keywords that are not ANSI sql.
