### ISSUE TITLE
No support for `nextEmbedded` in `colorize`

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/monaco-editor#2712]
**monaco-editor version:** 0.29.1
**Browser:** Chrome 92.0.4515.159
**OS:** Ubuntu 20.04.3 LTS
**Playground code that reproduces the issue:**

1. Clone mermaid-js/mermaid#2449
2. Run `python -m http.server -d docs/`
3. Open [`http://localhost:8000/#/?id=git-graph-exclamation-experimental`](http://localhost:8000/#/?id=git-graph-exclamation-experimental)
4. Notice that the JSON isn't highlighting

![Screenshot from 2021-11-01 21-13-45](https://user-images.githubusercontent.com/53054099/139785921-085c70a7-fe90-4a02-b931-a4248b9e713c.png)

It worked when I tried it out as an editor.

**Comment by hediet** [comment]
Please share an example that reproduces in the monaco-editor playground. Thanks!
