### ISSUE TITLE
Re-using exports across multiple SQL dialects

### ISSUE THREAD

**Issue by MasterOdin** [microsoft/monaco-editor#2716]
While looking at adding a new SQL dialect to [monaco-languages](https://github.com/microsoft/monaco-languages), I was wondering why there was so much repetition in the existing dialects. Each dialect exports the exact same `conf` object that each has independently defined. pgsql and redshift seemingly export the same `language` object with the exception of `keywords` and `builtinFunctions`. I could not find any docs or text on why each language would have its own language definition, so I'm not sure if it's just something that's just not been done yet as most languages are unique enough to warrant not sharing definitions, or if it's expressly forbidden. Is this a concern to avoid importing multiple languages if just need one language, and so should a minimal core file with the exports be created that all other languages can import?

**Comment by hediet** [comment]
It is not forbidden, but I don't think it will improve the product much.
