### ISSUE TITLE
Diff Editor: Add convenient way to support a diff line merge

### ISSUE THREAD

**Issue by aib628** [microsoft/monaco-editor#2717]
Similar issue, but i have not found the final conclusion from it  : https://github.com/microsoft/monaco-editor/issues/2269

Example image of how to merge a diff line, it's expect to achive it by some simple system config:
![image](https://user-images.githubusercontent.com/18046946/140276495-a861e07f-afb9-4b2a-899a-242d3cda36ad.png)

**Comment by hediet** [comment]
This is supported now.

**Comment by aib628** [comment]
> This is supported now.

cool
