### ISSUE TITLE
Allow specifying custom node_modules path

### ISSUE THREAD

**Issue by neoncom** [microsoft/monaco-editor#2719]
I have a custom fork of the monaco editor in my own npm scope which resides at a different node_modules path after installing and I would like to use this plugin without forking this plugin too :)

**Comment by hediet** [comment]
You can use `monacoEditorPath` for that.

https://github.com/microsoft/monaco-editor/blob/4a80f8e85250b80d44d2249076ba5afba6721db5/webpack-plugin/src/index.ts#L154
