### ISSUE TITLE
How to add a DOM listener to a content widget?

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#272]

**Comment by alexandrudima** [comment]
What sort of DOM listener?

**Comment by akosyakov** [comment]
@alexandrudima we have custom content widgets and it is handy to use such modules as `vscode/src/vs/base/browser/dom` to implement them, e.g. `addDisposableListener`. We ended up copying it.

**Comment by alexandrudima** [comment]
Oh, I see. We consider `vs/base/browser/dom` to be implementation detail and we don't want to expose such "dom utils" APIs, there are very many JS libraries that can help with that and we'd like to focus on our value prop of a code editor.
