### ISSUE TITLE
Possible Looser Coupling with monaco-editor

### ISSUE THREAD

**Issue by joehuntosu** [microsoft/monaco-editor#2726]
Since the last version of `monaco-editor` to support IE11 is `0.18.1` I cannot upgrade and therefor I am stuck with `1.7.0` of `monaco-editor-webpack-plugin` because of the tight coupling. However I need access to options that were introduced in `1.8.X` (`filename`, `publicPath`). Shouldn't access to these options be accessible regardless of the version of `monaco-editor`?

I've forked locally and cherry-pick'd the commits ([3bab...](https://github.com/microsoft/monaco-editor-webpack-plugin/commit/3bab84bf28998b551e29940dc4bad14fca652fd2#diff-2d58925d187c94ca40e6fd145b57934fR69), [dfa3...](https://github.com/microsoft/monaco-editor-webpack-plugin/commit/dfa3f22cc6bda73609e3db5175146c1ced85f538)) that introduced these features to unblock myself. I imagine others will run into this limitation.

**Comment by hediet** [comment]
The coupling is much looser now.
