### ISSUE TITLE
markers hidden by decorations

### ISSUE THREAD

**Issue by jrieken** [Microsoft/monaco-editor#273]
_From @anatsegev on November 23, 2016 15:49_

- Monaco Editor Version: 0.7.0
- OS Version: Chrome

Hi,

We create an editor for a custom language.
The editor holds queries, separated by empty lines.
We use changeDecorations in order to highlight the current query according to the user cursor position.
The decoration use a class that sets the background-color.
I'm working on adding a validation check that will mark errors in the query. I'm using setModelMarkers for that.

It seems that the error marker is 'hidden' by the decoration. 

How do I use both markers and decorations for the same position?

Thanks,
Anat

_Copied from original issue: Microsoft/vscode#15972_

**Comment by anatsegev** [comment]
Any update on this issue?

**Comment by alexandrudima** [comment]
@anatsegev Both decorations are rendered. It is impossible for the editor to decide which decoration should sit on top of which. You can use an `rgba` color in your decoration. Playground e.g.:

![image](https://cloud.githubusercontent.com/assets/5047891/22056129/e158adc6-dd5e-11e6-8e9f-a55357ea4957.png)


```css
.myContentClass {
	background: rgba(0,0,255,0.2);
}
```

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) { !@#',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "typescript"
});

var decorations = editor.deltaDecorations([], [
	{
		range: new monaco.Range(3,1,3,1),
		options: {
			isWholeLine: true,
			className: 'myContentClass',
		}
	}
]);

```
