### ISSUE TITLE
`monaco-editor/esm/vs/editor/editor.api` is transformed into `cjs` instead of `esm` any more

### ISSUE THREAD

**Issue by JounQin** [microsoft/monaco-editor#2735]
With regards to the common js usage warnings, it seems that MonacoEditorWebpackPlugin is augmenting the source of Monaco Editor and adding CJS modules.

https://github.com/microsoft/monaco-editor/blob/a5298e13bba5ab5d97ccef97c7b56df9cec489ce/webpack-plugin/src/loaders/include.ts#L29-L36

**Comment by titouanmathis** [comment]
I tested a fix on a fork which seems to work : https://github.com/titouanmathis/monaco-editor/commit/424abe722e5b2c3d72ce60a3b2cb7b67ddc475b6

Tests are ok when I run them, maybe someone else could confirm?
