### ISSUE TITLE
Cannot read property 'dispose' of null

### ISSUE THREAD

**Issue by PinkyJie** [Microsoft/monaco-editor#274]
monaco-editor npm version: 0.7.0
Browser: Electron 1.4.6
OS: macOS 10.11

I registered an auto-complete item and unregister it on window unload.
```
var unregister = monaco.languages.registerCompletionItemProvider('javascript', {
    provideCompletionItems: function (model, position) {
        ....
        return xxx;
    }
});
window.addEventListener('beforeunload', function () {
  unregister.dispose();
});
```
But I got the following errors:

![image](https://cloud.githubusercontent.com/assets/551329/20598888/4125164e-b286-11e6-8160-8b9aea7b0b0e.png)

Do I forget something?

**Comment by PinkyJie** [comment]
more details:

The error happens right after I select the suggested snippet, and snippet can be correctly inserted into the editor, but I fond the background can not disappear automatically.

![image](https://cloud.githubusercontent.com/assets/551329/20613612/8e22ba80-b300-11e6-9cff-7a25d002febe.png)

Notice the blue background, it stay here forever.

**Comment by alexandrudima** [comment]
Seems to be already fixed on master:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippetController.ts#L551
```
if (this._currentController) {
	this._currentController.dispose();
	this._currentController = null;
}
```

**Comment by PinkyJie** [comment]
Is there a plan to put this fix on NPM?

**Comment by alexandrudima** [comment]
Yes, I will publish a new version of the editor in the following days.

**Comment by PinkyJie** [comment]
@alexandrudima Thank you very much!
