### ISSUE TITLE
Plugin does not work in PWA VueJS Project

### ISSUE THREAD

**Issue by Catutigernos** [microsoft/monaco-editor#2744]
Hi,
I try to use monaco editor in my PWA VueJS project. Plugin can not install workers. I create second non-pwa project.

vue.config.js
```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
module.exports = {
  transpileDependencies: [
    'vuetify'
  ],
  configureWebpack: {
    plugins: [
      new MonacoWebpackPlugin()
    ]
  }
}
```

MonacoEditor.vue
```
<template>
  <div ref="editor" style="height:100%"></div>
</template>

<script>
import * as monaco from 'monaco-editor'
export default {
    mounted() {
            this.editor=monaco.editor.create(this.$refs.editor, {
      theme:"vs-dark",
      value: "function hello() {\n\talert('Hello world!');\n}",
      language: "javascript",
    });
    },
    data() {
        return {
            editor:undefined
        }
    },
}
</script>

<style>

</style>
```

These codes works in non-pwa project, does not work in pwa project. I used exactly same codes in the projects.

```
simpleWorker.js?1b1f:18 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
simpleWorker.js?1b1f:20 monaco_editor_esm_vs_editor_editor_worker_worker__WEBPACK_IMPORTED_MODULE_11__.default is not a constructor
simpleWorker.js?1b1f:20 monaco_editor_esm_vs_language_typescript_ts_worker_worker__WEBPACK_IMPORTED_MODULE_15__.default is not a constructor
editorSimpleWorker.js?ccf6:450 Uncaught (in promise) Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?ccf6:450)
    at eval (webWorker.js?af50:38)
errors.js?fdcc:8 Uncaught Error: Unexpected usage

Error: Unexpected usage
    at EditorSimpleWorker.loadForeignModule (editorSimpleWorker.js?ccf6:450)
    at eval (webWorker.js?af50:38)
    at eval (errors.js?fdcc:8)
```
I get these errors in pwa project. How can I integrate monaco editor to pwa project by using webpack-plugin. I will be glad to help me about it.

Thanks in advance.

**Comment by DarknessChaser** [comment]
version ?

try to monaco-editor-webpack-plugin@^6.0.0 + monaco-editor@^0.30.1

**Comment by DarknessChaser** [comment]
version?

**Comment by nwtgck** [comment]
I had the same problem. Finally, I found the solution!

I added the following option to `vue.config.js`.
```js
...
  pwa: {
    workboxOptions: {      
      maximumFileSizeToCacheInBytes: Number.MAX_SAFE_INTEGER,
    },
  },
...
```
actual commit: https://github.com/nwtgck/nipp/commit/e593b9c882105a96e61dc099be524a7c672d9d55

You can change `Number.MAX_SAFE_INTEGER` to proper size for your app.


Workbox has `maximumFileSizeToCacheInBytes`, which is 2MB by default. However, ts.worker.js is about 4.7MB. That is why the cache is not available.
[document](https://developer.chrome.com/docs/workbox/reference/workbox-build/#:~:text=be%20applied%20first.-,maximumFileSizeToCacheInBytes,-number%C2%A0optional)

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
