### ISSUE TITLE
📢 Merging monaco repositories

### ISSUE THREAD

**Issue by alexdima** [microsoft/monaco-editor#2746]
In order to simplify the `monaco-editor` release process (through automation) we have decided to merge all the various repositories that come together for shipping the npm package `monaco-editor`.

**Comment by CareyJWilliams** [comment]
What's the recommended way to build the various components now?

After a root level 'npm install' I have the following commands working:
- npm run prepublishOnly --prefix monaco-css
- npm run prepublishOnly --prefix monaco-languages
- npm run prepublishOnly --prefix monaco-typescript

And another two working after patchingt their src/workerManager.ts files (change _idleCheckInterval's type to NodeJS.Timer instead of number):
- npm run prepublishOnly --prefix monaco-json
- npm run prepublishOnly --prefix monaco-html

I can't however seem to get the 'monaco-editor' component to build.

**Comment by alexdima** [comment]
I'm sorry things are not yet working completely. We are still working on the packaging scripts.

**Comment by CareyJWilliams** [comment]
No worries at all! Thank you for clarifying :)

**Comment by kaphula** [comment]
This is good news! Do you have any rough estimation how long will it take to get this task finished? Are we talking about days or months here?

**Comment by MasterOdin** [comment]
With the condensing down to a monorepo, are the individual components going to keep having new versions published to npm?

My immediate use case would be that I am planning on starting a new project that would have just imported `monaco-languages` as I wanted to directly use some bits of it for tokenization, and I'd like to avoid dragging it all the other monaco pieces that I don't need.

**Comment by alexdima** [comment]
@MasterOding we will stop publishing individual packages to `npm`. Going forward, we think of reducing the npm packages to `monaco-editor-core` and `monaco-editor`. We are also thinking of including `monaco-editor-webpack-plugin` inside `monaco-editor` since it needs to be updated in lock-step with the `monaco-editor`. Further out, we are thinking of merging various folders in here, as there is a bit of code duplication between these plugins.

To consume only parts of the `monaco-editor` in your project, it will still be possible to use e.g. the webpack plugin and cherry-pick the languages / features that you want.

**Comment by MasterOdin** [comment]
> To consume only parts of the monaco-editor in your project, it will still be possible to use e.g. the webpack plugin and cherry-pick the languages / features that you want.

This workflow makes it messy to then to work as part of a library. At that point, I guess the option would be to just wholesale copy/paste the bits I need out of this repo into my project and just put a notice at the top with regards to license. This does answer my question though to avoid having any monaco plugin bits as dependencies unless I was looking to add/use the entire `monaco-editor`, and only as an end project, not a library. Thanks for answering the question, good luck with the merge!

**Comment by mike-lischke** [comment]
Since I did this switch recently, you might want to change `_idleCheckInterval` once and for all, and avoid that extra patch step. This works for me both in a browser and Node.js (vscode):

```typescript
const timer: ReturnType<typeof setTimeout> | null;
```

**Comment by AndersMad** [comment]
I can no longer create the `WorkerManager` from/for e.g. CSS as its hidden/not exported now.. Will this change?.. I am using this for mixed/embedded languages - css completion inside custom variant of xml and sudo model for css inline (no classes) colors and completion..

**Comment by alexdima** [comment]
@AndersMad Could you please create a separate issue with more information? I think you might be hitting something similar to https://github.com/microsoft/monaco-editor/issues/2820 which is about the ESM variant where the workers are now shipped bundled, but for CSS?

**Comment by alexdima** [comment]
The merge is complete.
