### ISSUE TITLE
How implement Find In Files

### ISSUE THREAD

**Issue by vkalpias** [microsoft/monaco-editor#2747]
Hello,

Is there a way that we can customize the Find widget to search in multiple files? 

I guess ideally we'd want to hook into the Find widget and provide the search results ourselves (e.g. we can have a worker searching multiple files in the background - those files might not be Editor models yet but might come from the network). 

After providing the search results we'd need a way to respond to clicking on each result i.e. to open the respective file and go to the desired match.

**Comment by CareyJWilliams** [comment]
I don't believe so, but even if there were, I think it makes sense that the in-editor widget only applies to the active file/model.

Look at vscode itself for example, it separates the global search out into the sidebar. You can create your own similar "project-wide" search atop of the [findMatches](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#findmatches) API.

**Comment by vkalpias** [comment]
I see OK thank you :)
