### ISSUE TITLE
Detailed documentation view of completion item redesign

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/monaco-editor#275]
monaco-editor npm version: 0.7.0

Hi,

We would like to have more seamless transition from suggestions list in the completion item provider to the detailed documentation view of this item.
When user clicks on the info icon to read more documentation about an item, we suggest that the item will appear in the header of the detailed documentation window as before, and the rest of the documentation will be underneath.

See picture:

![image](https://cloud.githubusercontent.com/assets/17318937/20669916/47874646-b57f-11e6-95dc-edd084964f8e.png)

Thanks,
Anat

**Comment by joaomoreno** [comment]
What is the added benefit?

**Comment by ramya-rao-a** [comment]
With the changes from earlier this year, the details appear to the side.
That should help.

I'd suggest to close this issue as there hasnt been activity here.

**Comment by joaomoreno** [comment]
Sounds good, thanks @ramya-rao-a!
