### ISSUE TITLE
Automatically trigger scroll in Monaco Editor

### ISSUE THREAD

**Issue by jbharatrhodes** [microsoft/monaco-editor#2761]
I am working on a Monaco editor to automatically trigger scroll events. So far example if I press 'a' then it will automatically trigger scrolling until another key is pressed. The code works fine in a plain html page but when monaco editor is used it is not working. This is the code in jsfiddle.

    var speed = 100;
    function pageScroll() {
        if(speed == 0) return;
        document.getElementById("container").scrollBy(0,50); 
        setTimeout('pageScroll()',speed);
    }
Full code on jsfiddle

https://jsfiddle.net/L7uekp2b

Can anyone suggest me what's wrong with the code.

**Comment by CareyJWilliams** [comment]
Use the scrollBy property on Monaco Editor object:

E.g.
```
var speed = 100;
interval = setInterval(function() { myeditor.setScrollTop(myeditor.getScrollTop() + 1) }, speed);
```

**Comment by jbharatrhodes** [comment]
Thanks @CareyJWilliams for the solution
It is working when I scroll down but it will not stop 
and also I tried to use 

`    var speed = 100; `
 `   interval = setInterval(function() { myeditor.setScrollTop(myeditor.getScrollTop() -1 ) }, speed); `

to move up, but not working as well

**Comment by CareyJWilliams** [comment]
You'll need to clear the interval: https://developer.mozilla.org/en-US/docs/Web/API/clearInterval

**Comment by jbharatrhodes** [comment]
Perfect. Thank you
