### ISSUE TITLE
monaco.d.ts: import syntax

### ISSUE THREAD

**Issue by mbana** [Microsoft/monaco-editor#278]
Hi, how would one use something like the below for importing?

```javascript
import * as ls from 'vscode-languageserver-types';
import { Promise, Uri, IDisposable } from 'monaco';
import { IModel, IModelContentChangedEvent2} from 'monaco/editor';
```

instead of https://github.com/Microsoft/monaco-css/blob/master/src/cssMode.ts#L12:

```javascript
import Promise = monaco.Promise;
import Uri = monaco.Uri;
import IDisposable = monaco.IDisposable;
```

**Comment by alexandrudima** [comment]
Once the editor is loaded, it defines a global, `monaco`. Perhaps if `vs/editor/editor.main` would export the same global, this way of consuming the editor could work

**Comment by alexandrudima** [comment]
so something in the following shape should work now:
```
import * as monaco from 'vs/editor/editor.main`
```

**Comment by TedDriggs** [comment]
Is there a way for this import to also import the type information? Right now, I don't see any of the interfaces when I use the import from @alexandrudima.

**Comment by alexandrudima** [comment]
@TedDriggs You could try:
```
declare module 'vs/editor/editor.main {
 // paste in here almost the entire monaco.d.ts
}
```
