### ISSUE TITLE
Parcel bundler sample broken

### ISSUE THREAD

**Issue by cmoog** [microsoft/monaco-editor#2783]
**monaco-editor version:** 0.30.1
**Browser:** Chrome 96
**OS:** macOS 12.0.1
**Playground code that reproduces the issue:** N/A

Using the build and serve scripts from https://github.com/microsoft/monaco-editor/blob/main/samples/browser-esm-parcel/package.json, the page loads with a fatal error. To reproduce on a fresh clone, run:

```sh
git clone https://github.com/microsoft/monaco-editor
cd monaco-editor/samples/browser-esm-parcel
npm ci
cd .. && npm ci && cd -
npm run build
npm run simpleserver
```

Visit `localhost:9999` and the following error is written to the console at startup.
```
marked.js:2984 Uncaught TypeError: Cannot read properties of undefined (reading 'Parser')
    at marked.js:2984
```

**Comment by cmoog** [comment]
As a temporary measure, I've downgraded to `0.28.1` which appears to have solved the issue.

**Comment by alexdima** [comment]
I have also noticed this a few days ago. It is already fixed on `main` and the fix will ship with the next editor release. (fixed via https://github.com/microsoft/vscode/commit/0e233cca9c8994377e89bfa8033658b895a1df7b)
