### ISSUE TITLE
Incorrect positioning/Overlap for codelens in diff viewer

### ISSUE THREAD

**Issue by dhruvit-r** [microsoft/monaco-editor#2786]
There's an overlap when we add a codelens to a line directly below a "removed code" block in the diff viewer (see screenshot). Ideally, the codelens should be in it's own separate line (which is above the "removed code" block.

<img width="817" alt="Screenshot 2021-11-22 at 2 00 01 PM" src="https://user-images.githubusercontent.com/5932865/142828866-c242355c-b042-4759-8e62-16bf21e54ba1.png">

**monaco-editor version:** 0.30.1
**Browser:** Chrome 95.0.4638.69 (arm64)
**OS:** macOS 
**Playground code that reproduces the issue:**

```js
var originalModel = monaco.editor.createModel(
	'This line is removed on the right.\nThis line is removed on the right.\nThis line is removed on the right.\njust some text\nabcd\nefgh\nSome more text',
	'text/plain'
);
var modifiedModel = monaco.editor.createModel(
	'This line is removed on the right.\nefgh\nSome more text',
	'text/plain'
);

var diffEditor = monaco.editor.createDiffEditor(document.getElementById('container'), {
    readOnly: false,
    automaticLayout: true,
    scrollBeyondLastLine: false,
    wordWrap: "on",
    codeLens: true,
    diffCodeLens: true,
    originalEditable: true,
    lineNumbersMinChars: 7,
});
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});



var commandId = diffEditor.addCommand(
	0,
	function () {
		alert('my command is executing!');
	},
	''
);

monaco.languages.registerCodeLensProvider('*', {
	provideCodeLenses: function (model, token) {
		return {
			lenses: [
				{
					range: {
						startLineNumber: 2,
						startColumn: 1,
						endLineNumber: 2,
						endColumn: 2
					},
					id: 'First Line',
					command: {
						id: commandId,
						title: 'First Line'
					}
				}
			],
			dispose: () => {}
		};
	},
	resolveCodeLens: function (model, codeLens, token) {
		return codeLens;
	}
});
```

**Comment by hediet** [comment]
Does this also reproduce in VS Code (extensions can contribute code lens providers)?

**Comment by dhruvit-r** [comment]
@hediet I'm not sure, I work with monaco-editor directly. I'm not familiar with the VSCode API, but do let me know if this is something you need me to check and I'll try and hack up a little demo.

**Comment by hediet** [comment]
If this is a bug in VS Code, we can better prioritize it.

**Comment by dhruvit-r** [comment]
@hediet Seems like VSCode is impacted as well (Codelens in VSCode is disabled by default, `diffEditor.codeLens` needs to be enabled).

I've uploaded the source code for reproducing the issue here: https://github.com/dhruvit-r/codelens-issue-reproduction

<img width="1771" alt="Screenshot 2021-11-22 at 4 33 36 PM" src="https://user-images.githubusercontent.com/5932865/142850475-7a571c6d-0daf-4eea-9451-d63d613a282e.png">

**Comment by hediet** [comment]
Thank you! Can you open an issue in the Vs Code Repo and ping me (@hediet)?

**Comment by dhruvit-r** [comment]
@hediet Created an issue [here](https://github.com/microsoft/vscode/issues/137655), thanks!

**Comment by hediet** [comment]
Let's track this issue in the vscode repo.
