### ISSUE TITLE
Suggest widget stays forever after programmatically opened

### ISSUE THREAD

**Issue by aaliakseyenka** [microsoft/monaco-editor#2787]
By default suggest widget works as expected:  when it is triggered by trigger character or `ctrl+Space`, once you type unknown character - widget is hidden automatically.
If you use `editor.trigger('', 'editor.action.triggerSuggest', {})`, whatever you type inside never hides widget. 
Example below reproduces the issue: just type anything in the sandbox and observer that widget never hides.
**Any chance to workaround that?**

**monaco-editor version:** 0.29.1
**Browser:** Chrome
**OS:** MacOs
**Playground code that reproduces the issue:**

```js

monaco.languages.registerCompletionItemProvider('javascript', {
	provideCompletionItems: function (model, position) {
		var word = model.getWordUntilPosition(position);
		var range = {
			startLineNumber: position.lineNumber,
			endLineNumber: position.lineNumber,
			startColumn: word.startColumn,
			endColumn: word.endColumn
		};
        
		return {
			suggestions: [{
			label: 'customtest',
			kind: monaco.languages.CompletionItemKind.Function,
			insertText: 'customtest',
			range: range
		}]
		};
	}
});

const editor = monaco.editor.create(document.getElementById('container'), {
	value: 'customt\n ',
	language: 'javascript'
});


setTimeout(() => {
  editor.setPosition({column: 8, lineNumber: 1})
editor.trigger('', 'editor.action.triggerSuggest', {})
}, [1000])

```

Video examples:
Good:

https://user-images.githubusercontent.com/1570982/142926761-99086c13-91bb-435a-8d62-cf2501b2f3b4.mov

Bad:

https://user-images.githubusercontent.com/1570982/142926785-1f0bcc9c-2bed-4e9f-9eaf-17fbaa856339.mov

**Comment by jrieken** [comment]
When triggering completions manually we never hide the widget. Instead the widget goes into a "freeze mode" - you can see that the highlights aren't bold anymore, instead the last matching highlights are frozen. When showing completions automatically, e.g while typing or with trigger characters, we do hide the widget automatically because we showed it automatically. The `editor.action.triggerSuggest` defaults to manual triggered mode but (since very recent) you can invoke it with `{auto: true}` so that it behaves as if it would have been trigger automatically

**Comment by aaliakseyenka** [comment]
@jrieken  thanks for the explanation. Maybe you could share the link to docs or source file,  which defines other params that could be passed to the widget? 
we are trying to do small customization of suggestions and any docs would be helpful

**Comment by aaliakseyenka** [comment]
@jrieken also if you could comment about `since very recent)` would be helpful. I am now on `0.30.1` and seems `auto: true` doesn't have any effect

**Comment by yuyiRai** [comment]
version: 0.31.1
editor._triggerCommand('editor.action.triggerSuggest', { auto: true })
