### ISSUE TITLE
Download link broken on https://microsoft.github.io/monaco-editor/ + version mismatch

### ISSUE THREAD

**Issue by JeanPerriault** [microsoft/monaco-editor#2800]
Hi,
The download link on https://microsoft.github.io/monaco-editor/ seems to be broken, it opens https://registry.npmjs.org/monaco-editor/-/monaco-editor-0.31.0.tgz, displaying `{"error":"Not found"}` message.
Moreover, the release version number on website is 0.31, while on this repo tags and in changelog, the last reference is 0.30.1.

**Comment by cnryb** [comment]
It looks like 0.31.0, not released yet.
Maybe it's still on the road.
