### ISSUE TITLE
warning: Experimental support for decorators is a feature that is subject to change in a future release

### ISSUE THREAD

**Issue by chenqiangkobe** [microsoft/monaco-editor#2801]
monaco: v0.31.0
warning: 'Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning',

How to remove this warning？
my code : 
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
      noSemanticValidation: true,
      noSyntaxValidation: false
    });
    // compiler options
    monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
      target: monaco.languages.typescript.ScriptTarget.ES6,
      declaration: false,
      module: monaco.languages.typescript.ModuleKind.ES2015,
      moduleResolution: monaco.languages.typescript.ModuleResolutionKind.NodeJs,
      emitDecoratorMetadata: true,
      importHelpers: true,
      experimentalDecorators: true,
      allowNonTsExtensions: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      noImplicitAny: true,
      allowJs: true,
      checkJs: true,
      noUnusedLocals: true,
      noFallthroughCasesInSwitch: true,
      noImplicitThis: true,
      lib: ['ES2016'],
      typeRoots: ['node_modules/@farris']
    });

this does not work.

**Comment by chenqiangkobe** [comment]
mg code: main.ts
import { Injectable } from '@angular/core';
import { ApplicationParamService } from '@farris/command-services';
import { HttpClient, HttpHeaders } from '@angular/common/http';
@Injectable()
export class List1FrmWebcmpService {
    constructor(private obj: ApplicationParamService, private http:HttpClient) {
        this.obj.parseParams;
    }
    private get() { }
    set() { }
}
' List1FrmWebcmpService ' has underline&warning: ' Experimental support for decorators is a feature that is subject to change in a future release'
how to remove the warning?

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community!

I'll close this issue, but if you have specific follow up questions, we'll try to help as good as we can given the limited resources that we have.

Thanks for your understanding!
