### ISSUE TITLE
HoverProvider for object

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2803]
I know that ordinary suspension prompts can prompt text, and even I can prompt markdown and pictures by looking at some questions. But I see that vscode prompts the structure of an object. And this object can be expanded layer by layer. I want to know how to do this. Can our Monaco do i
![aa](https://user-images.githubusercontent.com/34642268/144795747-b80831e2-6440-40f0-86e7-c9f514696426.png)
t

**Comment by rcjsuen** [comment]
> But I see that vscode prompts the structure of an object. And this object can be expanded layer by layer. I want to know how to do this. Can our Monaco do i !

Are you asking how to show the content of a JavaScript object in a hover or how to create expandable things in a hover?

**Comment by y912765390** [comment]
Yes, when I use "hoverprovider", I can only display some strings, not the object structure as in the screenshot, and it can be clicked. If I don't use "hoverprovider" to build a page with HTML, it will be very complicated (I know Monaco can create a drawing board to display a function similar to pop-up window)

**Comment by y912765390** [comment]
Yes, when I use "hoverprovider", I can only display some strings, not the object structure as in the screenshot, and it can be clicked. If I don't use "hoverprovider" to build a page with HTML, it will be very complicated (I know Monaco can create a drawing board to display a function similar to pop-up window)

**Comment by alexdima** [comment]
It is not possible to render a tree widget using the hover provider. The debugger in vscode hides the markdown hover and implements its own hover for inspecting objects.
