### ISSUE TITLE
Website does not pick up new tokenizers

### ISSUE THREAD

**Issue by hediet** [microsoft/monaco-editor#2807]
when building the website locally it always used the old version of tokenizers, I even tried resetting the repo, running install, release, build-website, simpleserver and it would still pick up the old version. Is there an option to build from local files?

(from #2806, @jonatanklosko)

**Comment by jonatanklosko** [comment]
Ah, and also I needed to manually create `test/manual/generated`, most likely because the directory is assumed to exist here: https://github.com/microsoft/monaco-editor/blob/86cff7499956ce6b96e2d3130c09bf51e620ee37/build/simpleserver.js#L53-L56

Thanks!

**Comment by alexdima** [comment]
@hediet the website reflects the latest (stable) released editor, it does not reflect the sources in the `main` branch of this repository, nor the nightly npm releases. The website is the equivalent of `vscode.dev`, not of `insiders.vscode.dev`.

But @jonatanklosko you are correct, there is a `mkdir` missing somewhere in there.

**Comment by jonatanklosko** [comment]
@alexdima makes sense, thanks! For the record, it would be helpful to have an option of running the latest version locally, especially for verifying highlighting.

**Comment by alexdima** [comment]
@jonatanklosko I agree, to verify highlighting currently the following is possible:
* `npm run simpleserver`
* open http://127.0.0.1:8080/monaco-editor/test/manual/#sample%20-%20elixir

I will take a look to fix http://127.0.0.1:8080/monaco-editor/website/ which looks like it got broken during the repo merge.

**Comment by alexdima** [comment]
Now the following should work too:
* `npm run simpleserver`
* `npm run release`
* open http://127.0.0.1:8080/monaco-editor/website/

**Comment by jonatanklosko** [comment]
Fantastic, both of these work for me now, thanks :D
