### ISSUE TITLE
Experimental support for decorators is a feature that is subject to change in a future release

### ISSUE THREAD

**Issue by chenqiangkobe** [microsoft/monaco-editor#2808]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
	noSemanticValidation: true,
	noSyntaxValidation: false
});

// compiler options
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
	target: monaco.languages.typescript.ScriptTarget.ES2015,
	allowNonTsExtensions: true
});


var jsCode = [
    'import { Injectable } from \'@angular/core\';',
    'import { ApplicationParamService } from \'@farris/command-services\';',
    'import { HttpClient, HttpHeaders } from \'@angular/common/http\';',
    '@Injectable()',
    'export class List1FrmWebcmpService {',
        'constructor(private obj: ApplicationParamService, private http:HttpClient) {',
            'this.obj.parseParams;',
        '}',
        'private get() { }',
        'set() { }',
    '}'
].join('\n');

monaco.editor.create(document.getElementById('container'), {
	value: jsCode,
	language: 'typescript'
});
```

### Actual Behavior

'List1FrmWebcmpService' has underline&warning ' Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning '

### Expected Behavior

how to remove this warning ?

**Comment by alexdima** [comment]
@chenqiangkobe This error message comes from the TypeScript language service and is a direct consequence of your chosen TypeScript compiler options. I suggest that you:
1. Search with a search engine for "Experimental support for decorators is a feature that is subject to change in a future release" and read the published blog posts on this matter.
2. If no solutions are found, ask your question on StackOverflow

Thank you!

**Comment by chenqiangkobe** [comment]
https://github.com/microsoft/TypeScript/issues/47084
