### ISSUE TITLE
[Feature Request] Add an allowOverflowViewZone property

### ISSUE THREAD

**Issue by ricenoddle** [microsoft/monaco-editor#2812]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Hi there, I'm not sure if you have already implemented this or I have another way to do this. Because I cannot find a way to do this and I noticed that there is a property called `allowEditorOverflow` can make my `ContentWidget` overflow.

The screenshot may make you have a better understanding.
![image](https://user-images.githubusercontent.com/13479751/145534683-7be17279-907a-4a41-b8c6-424ba8f05bee.png)

I'd appreciated for your replay

**Comment by alexdima** [comment]
The purpose of view zones is to create vertical gaps with the text. View zones scroll with the text and behave similarly to lines of text. We will not add support for them to overflow the editor container.

I believe we have a similar need in our codebase. We solve this by adding two things at the same time: a view zone and an overlay widget. We then use the view zone APIs (`onDomNodeTop`, `onComputedHeight`) to move and position the overlay widget perfectly on top of the view zone. You can try to take inspiration from the code we have [here](https://github.com/microsoft/vscode/blob/69dcf8b0f6c9e32d521cdb81e6a6641cfd019229/src/vs/editor/contrib/zoneWidget/zoneWidget.ts#L166).

**Comment by ricenoddle** [comment]
> The purpose of view zones is to create vertical gaps with the text. View zones scroll with the text and behave similarly to lines of text. We will not add support for them to overflow the editor container.
> 
> I believe we have a similar need in our codebase. We solve this by adding two things at the same time: a view zone and an overlay widget. We then use the view zone APIs (`onDomNodeTop`, `onComputedHeight`) to move and position the overlay widget perfectly on top of the view zone. You can try to take inspiration from the code we have [here](https://github.com/microsoft/vscode/blob/69dcf8b0f6c9e32d521cdb81e6a6641cfd019229/src/vs/editor/contrib/zoneWidget/zoneWidget.ts#L166).
> 
> Possible similar question at #2308

Hi, @alexdima, sorry to bother you again. Thank you for that `view zone` + `overlay widget` works for me. But here I met another problem. I found that when my code snippet collapsed, the height of view zone under that line will change to 0. Is there a better way to keep the height of view zone ?
![image](https://user-images.githubusercontent.com/13479751/145775839-9423fccc-b255-49b2-a59d-00f215879dfe.png)
 
![image](https://user-images.githubusercontent.com/13479751/145776132-923ba945-ee3e-4f63-8201-5f94ec6a9685.png)

I'm not sure if this is my wrong use of view zone ?

**Comment by ricenoddle** [comment]
To make you better understand what my problem is, you can look at this screenshot
![image](https://user-images.githubusercontent.com/13479751/145777030-80184408-1d14-4374-9afd-5d1be5d79d17.png)

**Comment by alexdima** [comment]
View zones behave like lines of code so they get collapsed with the other code when folding ranges. There is no way to have a view zone which is "folding-resistant". To workaround this, one idea would be to detect this case and call revealLine on the line where the view zone is when the height becomes 0. IIRC this would force the folding range to unfold.

**Comment by ricenoddle** [comment]
> View zones behave like lines of code so they get collapsed with the other code when folding ranges. There is no way to have a view zone which is "folding-resistant". To workaround this, one idea would be to detect this case and call revealLine on the line where the view zone is when the height becomes 0. IIRC this would force the folding range to unfold.

Okkkkk, I'll try that!  Thank you sooooo much lol

**Comment by ricenoddle** [comment]
Hi bro @alexdima. Yeah it's me again .... I'm now using APIs (`onDomNodeTop` & `onComputedHeight`) to move and position my overlay widget, but I'm a little confused about the top of view zone. It performed different in the playground demo and my own code. 

Monaco Version: `0.26.1`

Look at this picture, and my code snippet is as following, looks like it's just a simple code
```js
var viewZoneId = null;
editor.changeViewZones(function (changeAccessor) {
	var domNode = document.createElement('div');
	domNode.style.background = 'lightgreen';
	viewZoneId = changeAccessor.addZone({
		afterLineNumber: 3,
		heightInPx: 130,
		domNode: domNode,
                onDomNodeTop: (top) => {
                    console.log('top: ', top);
                    viewZoneTop = top;
                },
                onComputedHeight: (height) => { 
                    console.log('height: ', height); 
                    viewZoneHeight = height; 
                },
	});
});
```
![image](https://user-images.githubusercontent.com/13479751/145946511-e61cc5ef-efc9-4f52-bef8-d7706c2079d2.png)
The top of the view zone will change to -100000 when my code is folded which is correct.

But here in my code, also the same code snippet
```ts
public onEditorReady(event: monacoEditor.editor.IStandaloneCodeEditor): void {
    event.changeViewZones(function (changeAccessor) {
      var domNode = document.createElement('div');
      domNode.style.background = 'lightgreen';
      changeAccessor.addZone({
        afterLineNumber: 6,
        heightInPx: 130,
        domNode: domNode,
        onDomNodeTop: (top) => {
          console.log(top);
        },
        onComputedHeight: (height) => {
          console.log(height);
        },
      });
    });
  }
```
![image](https://user-images.githubusercontent.com/13479751/145946833-e5bd179b-c143-4407-8d45-4fba077b8d1d.png)
My top of view zone not change when code folded.

**Comment by alexdima** [comment]
@ricenoddle Unfortunately we just don't have the time to offer such individual debugging. Here we can offer general advice and maybe some code snippets, but not troubleshoot individual cases that only occur in your project. 

For example, you mention that you are using `0.26.1`. That release is 5 months old compared to the playground, maybe that is what is causing the difference. But again, you will need to figure this out on your own.
