### ISSUE TITLE
[Bug] Completion list is missing background

### ISSUE THREAD

**Issue by jonatanklosko** [microsoft/monaco-editor#2816]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

On the main Monaco website open the completion with `Ctrl + Space`:

![image](https://user-images.githubusercontent.com/17034772/145659643-73dc825a-186e-40bb-8138-2ce7be51891b.png)

Interestingly see these two:

![image](https://user-images.githubusercontent.com/17034772/145659657-aed25d05-3d7c-46a6-99b4-20b62c39807b.png)

![image](https://user-images.githubusercontent.com/17034772/145659669-ceeabd98-ac95-45af-a00f-c2c7d0ccb48f.png)

**Comment by rcjsuen** [comment]
@jonatanklosko Could you share your browser version and OS version? Does this happen with other browsers?

**Comment by imario42** [comment]
I can reproduce that e.g. on

https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-tokens-and-colors

with Safari 15.1, Firefox 95.0 and Chrome 96.0.4664.93 on macOS 12.0.1

As a workaround it seems to be possible to reconfigure the variable
  --vscode-editorSuggestWidget-background
in your css.

**Comment by jonatanklosko** [comment]
I'm on Ubuntu 21.10 and can reproduce in Chrome 96.0.4664.45, Firefox 95.0 and Brave 1.27.109.

**Comment by alexdima** [comment]
Let's track in #2822
