### ISSUE TITLE
[Bug] webpack-plugin 7.0.0 does not work with webpack 4

### ISSUE THREAD

**Issue by ValeraS** [microsoft/monaco-editor#2817]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

error:

```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.main.js
Module build failed (from ./node_modules/monaco-editor-webpack-plugin/out/loaders/include.js):
TypeError: this.getOptions is not a function
    at Object.pitch (./node_modules/monaco-editor-webpack-plugin/out/loaders/include.js:5:63)
```

In webpack 4, `loaderContext` does not have `getOptions` and `utils`.

### Expected Behavior

works with webpack 4

**Comment by hediet** [comment]
Thanks for reaching out and your PR!
Has this always been a problem with the webpack plugin or is this a regression?
Can you try out older versions?

**Comment by ValeraS** [comment]
it is a regression. Versions 6 and bellow work with webpack 4.

**Comment by hediet** [comment]
When it worked [before](https://github.com/ValeraS/monaco-editor/blame/b4178b11900f0f8e9897ea377deaffa24c6ff4b3/monaco-editor-webpack-plugin/src/loader-utils.d.ts), why are the additions to loader-utils now required?

**Comment by isublimity** [comment]
+1, have problem webpack 4

**Comment by lmcsu** [comment]
Not working anyway.

```
 ERROR  Failed to compile with 1 error                                                                                                                                            7:06:54 PM

 error  in ./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js

Module parse failed: Unexpected token (160333:49)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       return [];
|     }
>     const preferences = this._inlayHintsOptions ?? {};
|     const span = {
|       start,
```

**Comment by ValeraS** [comment]
> Not working anyway.

To fix this error, you can include the path `. / Node_modules / monaco-editor / esm / vs / language` into your js rule with appropriate loaders.

**Comment by perryhong** [comment]
> > Not working anyway.
> 
> To fix this error, you can include the path `. / Node_modules / monaco-editor / esm / vs / language` into your js rule with appropriate loaders.
what loaders how can i use?
