### ISSUE TITLE
Using setPosition in onDidChangeModelContent has no effect

### ISSUE THREAD

**Issue by GirlDebug** [microsoft/monaco-editor#2821]
I want to make some content replacement. But **setPosition**  inside doesn't work
Here is a simple example, please point out the problem

```
this.editor = window.editor = monaco.editor.create(
        document.querySelector("#editor-wrap"), {
        value: "",
        theme: "vs-dark",
        automaticLayout: true,
        language: "javascript",
        fontSize: 12,
        minimap: {
            enabled: false,
        },
        wordWrap: "on",
        mouseWheelZoom: true,
        "bracketPairColorization.enabled": true
    });

editor.onDidChangeModelContent(function (event) {
    // event.isUndoing = ctrl + z
    // event.isRedoing = ctrl + y

    if (event.isUndoing || event.isRedoing || !event.changes[0].text) {
        return;
    }

    const changes = event.changes[0];
    const {
        range
    } = changes;

    if (changes.text == "123") {
        changes.text += "456";

        range.endColumn += changes.text.length;
        editor.executeEdits("", [changes]);

        editor.setPosition({
            lineNumber: range.startLineNumber,
            column: range.endColumn + 3,
        });
    }
});

```

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!

**Comment by GirlDebug** [comment]
@hubgit Thank you for your answer

**Comment by sarensw** [comment]
@GirlDebug Did you create a question on SO? I'm running into the same issue and want to know whether you received an answer that solved the issue. I searched SO, but couldn't find any related question.

**Comment by sarensw** [comment]
So I have set up the monaco dev env locally and walked through the code until `_emitStateChangedIfNecessary`. All the parameters that are used to create an instance of `CursorStateChangedEvent` when `eventsCollector.emitOutgoingEvent` is called seem to be correct. `oldSelections` contains the old position, and `selections` contains the new position. But I struggle to understand the event emitter. Not sure where to go on from now. Do you have any tips?

Also adding @alexdima to this thread as you have done most of the changes in the past to `cursort.ts` and all related files. Maybe you have an idea or can give me a hint on the event emitter?
