### ISSUE TITLE
[Bug] Completion list colors don't match VS Code and are unreadable (black text on dark background)

### ISSUE THREAD

**Issue by letmaik** [microsoft/monaco-editor#2822]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/530988/145710980-8828689c-bd74-424e-ae38-5c19bad2ecfb.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/530988/145710968-29066cb3-e313-4222-8cc5-2a056ca0ce40.png)

This is VS Code with the "Light (Visual Studio)" theme which is supposed to match the default monaco theme.

**Comment by blutorange** [comment]
The background is actually transparent -- it's really unreadable when you already have text below the suggestions window:

![image](https://user-images.githubusercontent.com/2456413/145881544-020b949b-dc1b-40f6-9e5c-007cd4fb5f4a.png)

**Comment by alexdima** [comment]
The root cause is the tree shaker which removes these color registrations:

![image](https://user-images.githubusercontent.com/5047891/146019464-e1519aec-938e-4b27-955f-c828d9d51563.png)
