### ISSUE TITLE
[Bug] findMatches regex search inconsistently applies regex when passing in a string

### ISSUE THREAD

**Issue by tom-james-watson** [microsoft/monaco-editor#2824]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.registerLinkProvider('plaintext', {
    provideLinks: async (model) => {
        const matches = model.findMatches(
            "\s",
            true,
            true,
            false,
            null,
            true
        );

        console.log({ matches });

        return {
            links: [],
        }
    },
    resolveLink: (link) => link,
});

monaco.editor.create(document.getElementById('container'), {
    value: "test test test test",
    language: 'plaintext'
});
```

### Actual Behavior

```
{
  "matches": [
    {
      "range": {
        "startLineNumber": 1,
        "startColumn": 3,
        "endLineNumber": 1,
        "endColumn": 4
      },
      "matches": [
        "s"
      ]
    },
    {
      "range": {
        "startLineNumber": 1,
        "startColumn": 8,
        "endLineNumber": 1,
        "endColumn": 9
      },
      "matches": [
        "s"
      ]
    },
    {
      "range": {
        "startLineNumber": 1,
        "startColumn": 13,
        "endLineNumber": 1,
        "endColumn": 14
      },
      "matches": [
        "s"
      ]
    },
    {
      "range": {
        "startLineNumber": 1,
        "startColumn": 18,
        "endLineNumber": 1,
        "endColumn": 19
      },
      "matches": [
        "s"
      ]
    }
  ]
}
```

### Expected Behavior

```
{
  "matches": [
    {
      "range": {
        "startLineNumber": 1,
        "startColumn": 5,
        "endLineNumber": 1,
        "endColumn": 6
      },
      "matches": [
        " "
      ]
    },
    {
      "range": {
        "startLineNumber": 1,
        "startColumn": 10,
        "endLineNumber": 1,
        "endColumn": 11
      },
      "matches": [
        " "
      ]
    },
    {
      "range": {
        "startLineNumber": 1,
        "startColumn": 15,
        "endLineNumber": 1,
        "endColumn": 16
      },
      "matches": [
        " "
      ]
    }
  ]
}
```

### Additional Context

It looks like the `isRegex` parameter is meant to drive whether the `searchString` is applied as a regex or not, but it doesn't seem to work consistently.

If you pass `"."` as the `searchString` in my playground code, you will correctly get a match for every single character. However when passing in `"\s"` you get matches for the letter `s`, instead of for spaces. The issue is not limited to this example, it's just an example case.

There's actually a workaround - it seems like if you pass in a `RegExp`, e.g. `/\s/` in my example, it works consistently as expected. However, both [the documentation](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ITextModel.html#findMatches) and the types suggest that this parameter only accepts a `string`.

**Comment by alexdima** [comment]
@tom-james-watson In JavaScript strings, backslashes (`\`) need to be escaped. Please see [this article on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#:~:text=JavaScript%20special%20characters). 

I think you might want to use `"\\s"` in your code instead of `"\s"` which is parsed by JS VMs as `"s"`.

**Comment by tom-james-watson** [comment]
Ugh yes, stupid oversight on my part :facepalm:
