### ISSUE TITLE
[Feature Request] Listen to custom hover's mouse click

### ISSUE THREAD

**Issue by CoderLim** [microsoft/monaco-editor#2826]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Provide a custom hover, and click variable or type, then do something, just like the codemirror example，click variable or type, then open right sidebar:

https://user-images.githubusercontent.com/13973117/145996545-6cf46d07-1307-4953-9d43-f51e56d7e98d.mov

**Comment by hediet** [comment]
I think this feature should be driven by a corresponding VS Code feature.
Also, it can be implemented using content widgets.
