### ISSUE TITLE
There was a problem when I used the input method to enter the code

### ISSUE THREAD

**Issue by lc-soft** [Microsoft/monaco-editor#283]
monaco-editor npm version: 0.7.0
Browser: chrome 54.0.2840.99 
OS: Windows 10

Problem recurrence method:
Switch to the PinYin input method, enter `number`, then press the space, the `number` will be repeated once.

![code-editor-ime-bug](https://cloud.githubusercontent.com/assets/1730073/20911195/6527c52c-bba1-11e6-92c6-435c464af5c3.gif)

**Comment by alexandrudima** [comment]
Already fixed on master (Microsoft/vscode#15765)
