### ISSUE TITLE
[Bug] CSS WorkerManager is no longer accessible/public

### ISSUE THREAD

**Issue by AndersMad** [microsoft/monaco-editor#2834]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Additional Context

As mentioned here: https://github.com/microsoft/monaco-editor/issues/2746#issuecomment-994927923

OLD
====

I use CSS completion from HTML. To do so I have done this:
```js
languageId = "html";
require(['vs/language/css/cssMode', 'vs/language/css/cssWorker'], (mode: any, workerMod: any) => {
	// THIS no longer works
	const workerManager = require('vs/language/css/workerManager');
	const worker = function () {
		return client.getLanguageServiceWorker.apply(client, arguments);
	}
	// THIS no longer works
	const languageFeatures = require('vs/language/css/languageFeatures');
	monaco.languages.registerCompletionItemProvider(languageId, new languageFeatures.CompletionAdapter(worker));
```

HACK
====

To make it work I go to `cssMode.js` and add: 
```js
__export(cssMode_exports, {
	setupMode: () => setupMode,
	// THIS makes it work
	WorkerManager: () => WorkerManager,
	CompletionAdapter: () => CompletionAdapter,
});
```

Then I can replace the `= requre(` with this:
```js
const workerManager = mode;
const languageFeatures = mode;
```

FIX
====

Can I have the WorkerManager adapters to becomes "public" again?

This is my first encounter, I will test the other languages and extensions to see if there are more. I know this is not in the public documented stuff - but it would be really nice to have access to these advanced features.

Thanks

**Comment by mifopen** [comment]
The same with `monaco-editor/esm/vs/language/typescript/languageFeatures`.
I use all those adapters in my custom workers with some preprocessing of the models.

**Comment by aeschli** [comment]
Maybe @alexdima knows more what has changed. But yes, all these modules are not API. 

So you get CSS proposals everywhere in the HTML file?

**Comment by alexdima** [comment]
This is a side-effect from bundling the AMD variants with ESBuild. The conceptual difference is that now `vs/language/css/workerManager` is no longer exposed as an AMD module, it gets completely inlined inside `vs/language/css/cssMode`.

**Comment by AndersMad** [comment]
@aeschli ye, but I do believe a some of us are using them and are ok with the cheese being move - but not when it goes away :) I just think its a regression (from your perspective) due to the new build tooling.. and no - I only get CSS completion and colors inside `<style>` and `style="here"` + lint and completion for my own language + XSD schema completion and linting 🕺

**Comment by alexdima** [comment]
To clarify, this is not a regression because these classes were internal and not part of the API described in `monaco.d.ts`. But I also don't think it is a problem for us to re-export these classes from `cssMode.ts`.

**Comment by mifopen** [comment]
Could you also consider re-exporting ts/languageServices?

**Comment by mifopen** [comment]
@alexdima Those adapters are really helpful for us :(

**Comment by mifopen** [comment]
Sorry, I've meant this file https://github.com/microsoft/monaco-editor/blob/main/src/typescript/languageFeatures.ts

**Comment by alexdima** [comment]
@mifopen I've also pushed a change to export those classes in `vs/language/typescript/tsMode.js`

**Comment by AndersMad** [comment]
@alexdima Sry if I was not clear enough - I only meant from YOUR (users) perspective 😊 I do use a lot of inner stuff not in the `monaco.d.ts` to make cool thing happen, but maybe I should investigate just using the typescript source instead as my project is TS already - don't know if that is event possible.. And thanks!

**Comment by mifopen** [comment]
@alexdima When will you have a chance to release a new version of the lib with this fixed? Is it possible till tomorrow?

**Comment by mifopen** [comment]
@alexdima ping? :) btw, what release policy do you use? Shouldn't such bugs just produce new patch version?

**Comment by mifopen** [comment]
@alexdima Sorry for bothering you again and again, but the fix becomes more and more crucial for us :( Could you please release something with it?

**Comment by mifopen** [comment]
@hediet tagging you just in case as I'm not aware about who's responsible for that and what is the process

**Comment by AndersMad** [comment]
@mifopen please read my initial post - under "hack" headline

**Comment by hediet** [comment]
> @alexdima Sorry for bothering you again and again, but the fix becomes more and more crucial for us :( Could you please release something with it?

We usually release the monaco editor shortly after the VS Code release. That will be in about three weeks - that way, the editor will be part of our thorough testing process.

You can either roll back to an old version of the monaco editor or build the editor yourself.
