### ISSUE TITLE
[Bug] suggestions are sometimes not properly ordered by sortText

### ISSUE THREAD

**Issue by tom-james-watson** [microsoft/monaco-editor#2835]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.registerCompletionItemProvider('sql', {
    provideCompletionItems: function (model, position) {
        return {
            triggerCharacters: ["."],
            "suggestions": [
                                {
                    "insertText": "event_id",
                    "sortText": "1",
                    "kind": 14,
                    "range": {
                        "startLineNumber": 1,
                        "endLineNumber": 1,
                        "startColumn": 45,
                        "endColumn": 49
                    },
                    "detail": "event_id",
                    "documentation": "Column in my_fake_table_name_1234",
                    "label": {
                        "label": "event_id",
                        "description": "column in my_fake_table_name_1234"
                    }
                },
                {
                    "insertText": "get_events",
                    "sortText": "3",
                    "kind": 1,
                    "range": {
                        "startLineNumber": 1,
                        "endLineNumber": 1,
                        "startColumn": 45,
                        "endColumn": 49
                    },
                    "detail": "mock detail",
                    "documentation": "mock documentation",
                    "label": {
                        "label": "get_events",
                        "description": "mock description"
                    }
                },
                {
                    "insertText": "client_event_id",
                    "sortText": "2",
                    "kind": 14,
                    "range": {
                        "startLineNumber": 1,
                        "endLineNumber": 1,
                        "startColumn": 45,
                        "endColumn": 49
                    },
                    "detail": "client_event_id",
                    "documentation": "Column in my_fake_table_name_1234",
                    "label": {
                        "label": "client_event_id",
                        "description": "column in my_fake_table_name_1234"
                    }
                },
            ]
        }
    }
});

monaco.editor.create(document.getElementById('container'), {
    value: 'select * from my_fake_table_name_1234 where e',
    language: 'sql'
});
```

### Actual Behavior

Order:
1. `event_id`
2. `get_events`
3. `client_event_id`

![image](https://user-images.githubusercontent.com/3852719/146344493-d94a919d-3ef4-4504-80ce-14dfa45f76e8.png)

### Expected Behavior

Order:
1. `event_id`
2. `client_event_id`
3. `get_events`

![image](https://user-images.githubusercontent.com/3852719/146345370-8edd7bf9-e536-4c62-8b47-545625eddf47.png)

### Additional Context

I expect the `sortText` parameter to drive the order that results are displayed and, for the most part, this seems to be the case. There does however seem to be some edge cases that cause the suggestions to not be displayed in alphabetical order according to their `sortText`.

It seems like maybe there are multiple heuristics influencing the sorting. In this case, updating the `label`->`label` of the last suggestion to `foo_event_id` seems to cause them to be ordered correctly, though I'm not sure why. [The docs](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.CompletionItem.html#sortText) mention that `label` is used if the `sortText` value is falsy, but that isn't the case here.

![image](https://user-images.githubusercontent.com/3852719/146346271-dc2663a6-cf44-449e-af4a-5b2b1551def4.png)

Playground for that:

```ts
monaco.languages.registerCompletionItemProvider('sql', {
    provideCompletionItems: function (model, position) {
        return {
            triggerCharacters: ["."],
            "suggestions": [
                                {
                    "insertText": "event_id",
                    "sortText": "1",
                    "kind": 14,
                    "range": {
                        "startLineNumber": 1,
                        "endLineNumber": 1,
                        "startColumn": 45,
                        "endColumn": 49
                    },
                    "detail": "event_id",
                    "documentation": "Column in my_fake_table_name_1234",
                    "label": {
                        "label": "event_id",
                        "description": "column in my_fake_table_name_1234"
                    }
                },
                {
                    "insertText": "get_events",
                    "sortText": "3",
                    "kind": 1,
                    "range": {
                        "startLineNumber": 1,
                        "endLineNumber": 1,
                        "startColumn": 45,
                        "endColumn": 49
                    },
                    "detail": "mock detail",
                    "documentation": "mock documentation",
                    "label": {
                        "label": "get_events",
                        "description": "mock description"
                    }
                },
                {
                    "insertText": "client_event_id",
                    "sortText": "2",
                    "kind": 14,
                    "range": {
                        "startLineNumber": 1,
                        "endLineNumber": 1,
                        "startColumn": 45,
                        "endColumn": 49
                    },
                    "detail": "client_event_id",
                    "documentation": "Column in my_fake_table_name_1234",
                    "label": {
                        "label": "FOO_event_id",
                        "description": "column in my_fake_table_name_1234"
                    }
                },
            ]
        }
    }
});

monaco.editor.create(document.getElementById('container'), {
    value: 'select * from my_fake_table_name_1234 where e',
    language: 'sql'
});
```

**Comment by jrieken** [comment]
A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.

**Comment by tom-james-watson** [comment]
I'm sorry but I don't think that addresses the issue. I have no issues with filtering, only with the ordering of the suggestions and you haven't mentioned sorting at all in your response )which appears to just be a copy-paste from https://github.com/microsoft/monaco-editor/issues/2070)?

In my playground code all three suggestions should match upon adding a `v` to the end of the pre-filled `select * from my_fake_table_name_1234 where e`. All three suggestions show as expected, however the *sort order* of the suggestions is not following the specified `sortText` values.

Note that in my playground code I had the range slightly wrong, but that does not affect the output. I have updated from `"endColumn": 49` to `"endColumn": 46`.

**Comment by jrieken** [comment]
Sorry, forgot the also paste the sortText explainer: https://github.com/microsoft/vscode/blob/ab80daed7409a4ec2c6c86be1f850600931c9177/src/vscode-dts/vscode.d.ts#L4116-L4129

**Comment by tom-james-watson** [comment]
OK, thanks.

Maybe I am just failing to understand the documentation, but with my example is there just no way to actually programmatically control the order of the suggestions once you start filtering by typing?

Also, the documentation you have linked to is not actually the current documentation or types. The latest seem to be here: https://github.com/microsoft/monaco-editor/blob/3afc60f1ac37a0e630453246b2fc43132a656932/website/typedoc/monaco.d.ts#L5896-L5907. For example the docs you link to show `range` as being optional, which is no longer true.

**Comment by jrieken** [comment]
> there just no way to actually programmatically control the order of the suggestions once you start filtering by typing?

Yes, there is no way to enforce a constant sort order. It's the user input that resorts and they do it typing matching prefixes.

**Comment by tom-james-watson** [comment]
OK. I would consider it a bug that none of this information is in the current docs or typings, though.
