### ISSUE TITLE
[Feature Request] Monaco editor with custom language for angular with antlr4 support and features like syntax highlighting and validation.  

### ISSUE THREAD

**Issue by sandeepkopparam** [microsoft/monaco-editor#2837]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

**Comment by hediet** [comment]
This feature request is out of scope for this project.
