### ISSUE TITLE
[Bug] 0.31.0 broke the parcel esm css.worker.js build

### ISSUE THREAD

**Issue by Prinzhorn** [microsoft/monaco-editor#2838]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
N/A
```

### Actual Behavior

> /node_modules/monaco-editor/esm/vs/language/css/css.worker.js: Unexpected token: punc (.)

### Expected Behavior

Successful build

### Additional Context

I'm probably on a pretty outdated setup, but I wouldn't expect this to break without a breaking change in the changelog.

```sh
npm i monaco-editor@0.31.0
npx parcel-bundler@1 build ./node_modules/monaco-editor/esm/vs/language/css/css.worker.js --no-source-maps
```

Changing out `0.31.0` with `0.30.1` runs successfully.

**Comment by hediet** [comment]
> /node_modules/monaco-editor/esm/vs/language/css/css.worker.js: Unexpected token: punc (.)

Does it show the line/column number? Can you paste the relevant source code of css.worker.js and help us debugging this issue?

**Comment by Prinzhorn** [comment]
> Does it show the line/column number?

It does not unfortunately. This is the full error (anything beyond the error message I posted doesn't seem to contain any useful info)

```
 $ npx parcel-bundler@1 build ./node_modules/monaco-editor/esm/vs/language/css/css.worker.js 
🚨  /tmp/monkas/node_modules/monaco-editor/esm/vs/language/css/css.worker.js: Unexpected token: punc (.)
    at Z.get (/home/alex/.npm/_npx/03f9bb732e844be5/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (/home/alex/.npm/_npx/03f9bb732e844be5/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (/home/alex/.npm/_npx/03f9bb732e844be5/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (/home/alex/.npm/_npx/03f9bb732e844be5/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Bundler.loadAsset (/home/alex/.npm/_npx/03f9bb732e844be5/node_modules/parcel-bundler/src/Bundler.js:577:19)
    at async Bundler.processAsset (/home/alex/.npm/_npx/03f9bb732e844be5/node_modules/parcel-bundler/src/Bundler.js:557:5)
    at async PromiseQueue._runJob (/home/alex/.npm/_npx/03f9bb732e844be5/node_modules/parcel-bundler/src/utils/PromiseQueue.js:48:7)
```

Diffing `css.worker.js` between the two versions shows that there has been a drastic change.

![Selection_1039](https://user-images.githubusercontent.com/679144/146749538-12a201e1-0502-4fad-9868-95693c7d86db.png)

But it's the same for the other workers, so I guess there has been some bundling changes / refactoring for them.

# Anyway

I was about to say I don't have time to bisect the file and track the line down but the first code block I removed was the right one, so yeah. The issue is the optional chaining in these two lines (coming from `src/css/cssWorker.ts`):

```
this._ctx = ctx;
this._languageSettings = createData.options;
this._languageId = createData.languageId;
const data = createData.options.data;
const useDefaultDataProvider = data?.useDefaultDataProvider; // <==========================
const customDataProviders = [];
if (data?.dataProviders) {  // <==========================
  for (const id in data.dataProviders) {
    customDataProviders.push(newCSSDataProvider(data.dataProviders[id]));
  }
}
const lsOptions = {
  customDataProviders,
  useDefaultDataProvider
};
```

I guess Parcel 1 by default doesn't have the required stuff to parse that. But like I said until 0.31.0 everything compiled fine.

I assume the problem is on my end, maybe add "Dropped Parcel 1 support" as a breaking change to 0.31.0 (https://github.com/microsoft/monaco-editor/commit/32f9897bf284a772689b4ab9e98887c63fcba399)

**Comment by alexdima** [comment]
This indeed looks like a breaking change, caused by us switching to esbuild. We are invoking `esbuild` with [`target: 'esnext'`](https://esbuild.github.io/api/#target) over [here](https://github.com/microsoft/monaco-editor/blob/6389400e105b4310b5c2463bbf20b976ae4b8b00/build/utils.js#L199). This leads to `a?.b` being outputted using `a?.b`. [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) appears to be supported in all modern browsers, but it might not be supported by parcel 1.

**Comment by alexdima** [comment]
I've pushed a change to document that the JS we ship now makes use of newer JS features that might break older parsers, like the one used in parcel v1.
