### ISSUE TITLE
[support] How to mark errors in a new language?

### ISSUE THREAD

**Issue by krzychukula** [Microsoft/monaco-editor#284]
I'm working on on my own language support in monaco-editor and while adding tokenizer was pretty easy I'm not sure how can I show errors.
```
        const TokensProvider = {
            tokenize: (line) => {
                const tokens = tokenize(line)
                return {
                    tokens
                };
            }
        };

        monaco.languages.setTokensProvider('myLanguage', TokensProvider);
```

I was going throgh api and code and so far found info about Markers and Diagnostics. 

For now I'm going to go with something like:
```
  const TokensProvider = {
            tokenize: (line) => {
                const tokens = tokenize(line)
                const markers = tokens.map(({startIndex, scopes, text}) => {
                    if (scopes === 'error') {
                        return {
                            severity: monaco.Severity.Error,
                            startLineNumber: 1,
                            startColumn: startIndex + 1,
                            endLineNumber: 1,
                            endColumn: startIndex + 1 + text.length,
                            message: 'Error \n'
                        };
                    }
                }).filter(exist => exist);

                monaco.editor.getModels()
                   .forEach(model => monaco.editor.setModelMarkers(model, '', markers));

                return {
                    tokens
                };
            }
        };

        monaco.languages.setTokensProvider('myLanguage', TokensProvider);
```

But I'm sure if it's the best place, on the other hand I would like to run `tokenize` only once. 

Any suggestions?

**Comment by krzychukula** [comment]
1. I have realized that I don't have `startLineNumber` or `endLineNumber` in there so it's probably wrong place. Still I'm not sure how to reuse tokenization if I put it in some other place.


2. I have noticed that content flashes inside of the editor. 

It seems that tokenization is ignored entirely when I press a new key.
If I put a breakpoint in tokenize function then I see a reason. 
For a really short that editor renders:
```
<div linenumber="1" style="top:0px;height:23px;" class="view-line"><span>
<span class="token ">and&nbsp;somee</span>
</span></div>
```
After tokenization I get:
```
<div linenumber="1" style="top:0px;height:23px;" class="view-line"><span>
<span class="token operator-word">and</span>
<span class="token whitespace">&nbsp;</span>
<span class="token operator-word">some</span>
<span class="token unknown">e</span>
</span></div>
```
Because I have colors assosiaciate with `.operator-word` it flashes every time rendering switches between tokenized and untokenized versions.
Any suggestions?

**Comment by krzychukula** [comment]
3. Last question. My context is a little different because I want to have editor for single line of code with folding. If I understand correctly Monaco editor has been build to be used as a editor window, but is it possible to react to how many folded lines there are and to expand the height of the editor?

Basically: have one one of text visible on the page but if it starts to fold - display two lines of text etc.

Thanks!

**Comment by alexandrudima** [comment]
The recommended way to set errors/warnings is via [`monaco.editor.setModelMarkers`](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodelmarkers). These will then be rendered via squiggles. Here is for example [`how errors are set for TypeScript/JavaScript`](https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts#L123).

You can listen to [`editor.onDidScrollChange`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#ondidscrollchange) and check if `e.scrollHeightChanged`. Then, you could deduce that wrapping has occurred and then use `editor.getLayoutInfo()` to look at the `lineHeight` and then recompute a good height which can then be set via `editor.layout({ width: w, height: h});`.

**Comment by krzychukula** [comment]
Thanks
