### ISSUE TITLE
[Bug] Missing Codicon classes

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#2842]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var jsCode = [
    '"use strict";',
    'function Person(age) {',
    '	if (age) {',
    '		this.age = age;',
    '	}',
    '}',
    'Person.prototype.getAge = function () {',
    '	return this.age;',
    '};'
].join('\n');

var editor = monaco.editor.create(document.getElementById('container'), {
    value: jsCode,
    language: 'javascript',
    glyphMargin: true
});

var decorations = editor.deltaDecorations(
    [],
    [
        {
            range: new monaco.Range(3, 1, 3, 1),
            options: {
                isWholeLine: true,
                glyphMarginClassName: 'codicon-light-bulb'
            }
        },
        {
            range: new monaco.Range(4, 1, 4, 1),
            options: {
                isWholeLine: true,
                glyphMarginClassName: 'codicon-debug-breakpoint'
            }
        },
        {
            range: new monaco.Range(5, 1, 5, 1),
            options: {
                isWholeLine: true,
                glyphMarginClassName: 'codicon-debug-stackframe'
            }
        }
    ]
);
```

### Actual Behavior

The `debug-*` codicons do not show up.

### Expected Behavior

The `debug-*` codicons do show up.

### Additional Context

I have been using some codicon CSS classes for e.g. a debug UI. These seem to be missing now with 0.31.1. I suspect tree-shaking of the `public static` fields of `vs/base/common/codicons.ts` as there are a lot less codicons overall registered in this release. It would be nice to get all the registrations back into Monaco (not just the debug ones).

To work around that I could define those classes myself, but that requires a lookup and duplicating of code for the actual font characters. It would be nice to not need that.
```css
.codicon-debug-stackframe::before {
    content: '\eb8b';
}
```

**Comment by alexdima** [comment]
It looks like since https://github.com/microsoft/vscode/commit/cfebd1d0be3c1c56812d6843a124407d424a33d5 codicons are exclusively defined in code (not in CSS anymore), and I can confirm that some of the code gets tree-shaken.
