### ISSUE TITLE
[Bug] shell syntax colors the "-bar" part of "foo-bar" as an attribute

### ISSUE THREAD

**Issue by starpit** [microsoft/monaco-editor#2851]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

Use language=shell and this content:

```shell
foo-bar --baz gorp
```

### Actual Behavior

<img width="312" alt="Screen Shot 2021-12-23 at 2 43 23 PM" src="https://user-images.githubusercontent.com/4741620/147285443-48b76539-895a-4e44-a91d-03735e9f1da6.png">

### Expected Behavior

<img width="313" alt="Screen Shot 2021-12-23 at 2 43 52 PM" src="https://user-images.githubusercontent.com/4741620/147285472-285a4164-a2ef-4127-95d9-8a0072c0430b.png">

### Additional Context

The relevant regexp is here: https://github.com/microsoft/monaco-editor/blob/main/src/basic-languages/shell/shell.ts#L162

Perhaps the regexp, instead of `/-+\w+/` should have a whitespace positive lookbehind? e.g. `(?<=\s)-+\w+`. I realize that this runs into problems with Safari and old IE... I am not familiar with the internals of monaco-editor, but perhaps there are already runtime guards in place that could be used here.

Or maybe something like `[/(\s)(-+[\w-]+/, ["white","attribute.name"]]`... but here my knowledge of monaco-editor source is too shallow at the moment to say with any certainty.

fwiw, vscode's markdown preview does not syntax color anything...
<img width="694" alt="Screen Shot 2021-12-23 at 2 44 46 PM" src="https://user-images.githubusercontent.com/4741620/147285562-219353e8-7a79-4032-8576-6523cd08b122.png">

**Comment by hediet** [comment]
Thanks for reporting this! We're more than happy to accept a PR for this!
