### ISSUE TITLE
[Feature Request] Update Swift language specification to version 5.5

### ISSUE THREAD

**Issue by philipturner** [microsoft/monaco-editor#2854]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Syntax coloring specifications for Swift ([swift.ts](https://github.com/microsoft/monaco-editor/issues)) are out of date and appear to be from Swift 4 (the most recent version is 5.5). For example, here is a short list of keywords not indexed:
- `@differentiable(reverse)`
- `async`
- `@escaping`
- `@inlinable`
- `await`
- `associatedtype`
- `@unchecked`
- `rethrows`

A list of language keywords can be found [here](https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#:~:text=Keywords%20reserved%20in%20particular%20contexts,unowned%20%2C%20weak%20%2C%20and%20willSet%20.), although the keywords that start with `@` are not listed. There are numerous `@` keywords, and it isn't feasible to include all of the ones starting with underscores. However, the ones that start with alphabetic characters should be possible to tabulate.

Monaco is the engine behind Google Colab's syntax coloring, and I am concerned because my effort to [revive Swift support](https://github.com/philipturner/swift-colab) is negatively impacted by incorrect syntax coloring. Colab is currently restricted to Monaco 0.27.0, so it won't benefit from this correction immediately (the currently version is 0.31.0). Since 0.27.0 was released a few months ago, I expect Google to update to a newer version in the time frame of a few months.

**Comment by hediet** [comment]
Thanks for the PR! Can you fix the CI issue? (prettier)

**Comment by philipturner** [comment]
@hediet I don't exactly understand what you mean by the CI issue. Could you please clarify?

**Comment by hediet** [comment]
Please use prettier to format the files you touched.

**Comment by philipturner** [comment]
I’m asking where to find prettier

**Comment by hediet** [comment]
You should be able to simply run `npm run prettier` in the root directory of this repo.
