### ISSUE TITLE
[Feature Request] Display a table in diagnostic window of Monaco Editor

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2856]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

(* I don't know if it is an existing feature or not *)

In [this sample of Monaco Editor](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example), when we hover on the `Hover over this text`, we could see markdown result in the diagnostic window. The contents of the window are provided by the code:

```
	contents: [
	    { value: '**SOURCE**' },
		{ value: '```html\n' + res.responseText.substring(0, 200) + '\n```' }
	]
```

I'm wondering if it is possible to draw a table in the diagnostic window.

[![enter image description here][1]][1]

I tried to add ` { value: '|   a | b  | c  | d  | e  | |---|---|---|---|---| |  1 | 2  | 3  | 4  | 5  |'}`, it did not work.

Could anyone help?
 

  [1]: https://i.stack.imgur.com/RR5v3.png

**Comment by rcjsuen** [comment]
> I tried to add ` { value: '| a | b | c | d | e | |---|---|---|---|---| | 1 | 2 | 3 | 4 | 5 |'}`, it did not work.

@chengtie You can achieve this with raw HTML and specifying `supportHtml`. You may also be interested in #801.

![image](https://user-images.githubusercontent.com/15629116/147425637-42f5afc7-a0d5-4562-a222-4f13d6887def.png)

```CSS
table, th, td {
  border: 1px solid black;
}
```
```JavaScript
monaco.languages.register({ id: 'mySpecialLanguage' });

monaco.languages.registerHoverProvider('mySpecialLanguage', {
    provideHover: function (model) {
        return {
            range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
            contents: [
                {
                    value: "<table><tr><td>abc</td><td>123</td></tr><tr><td>abc</td><td>123</td></tr></table>",
                    supportHtml: true
                },
            ]
        }
    }
});

monaco.editor.create(document.getElementById("container"), {
    value: '\n\nHover over this text',
    language: 'mySpecialLanguage'
});
```

**Comment by chengtie** [comment]
@rcjsuen Thank you, that works great!

Additionally, i guess it is impossible to use table solutions like https://github.com/handsontable/handsontable here?

**Comment by spahnke** [comment]
You can use a template string for that (the line breaks are important for the table rendering).

CSS (augmented from post above):
```css
.monaco .hover-content table, th, td {
    border: 1px solid black;
}
```

Hover element:
```js
contents: [
    { value: '**SOURCE**' },
    { value: `
| a | b | c | d | e |
|---|---|---|---|---|
| f | g | h | i | j |` 
    }
]
```

**Comment by chengtie** [comment]
@spahnke it works, thank you!

Again, i guess it is impossible to use table solutions like https://github.com/handsontable/handsontable here?

**Comment by alexdima** [comment]
@chengtie It is not possible to render a special table widget inside the hover via the hover provider.
