### ISSUE TITLE
Unable to change the label of an action

### ISSUE THREAD

**Issue by niratch** [Microsoft/monaco-editor#286]
monaco-editor npm version: 0.7.0
Browser: Edge
OS: Windows 10 Pro 64-bit

I have added the following action to a Monaco editor that toggles its label text every time the action is executed:

```
editor.addAction({
    id: 'myaction',
    label: 'A',
    contextMenuGroupId: 'menu',
    run: function (ed) {
        var action = editor.getAction('myaction');
        if (action.label.indexOf('A') >= 0)
        {
            action.label = 'B';
        }
        else
        {
            action.label = 'A'
        }
    }
})
```

I can confirm that the run method of the action gets called and the label is set (and persisted across calls) correctly. However, despite the label changing, the actual text that is drawn on-screen for the action is always the same initial text. This used to work in the previous version of Monaco we were using (0.6.0?), but seems to have been broken by some recent changes.

**Comment by alexandrudima** [comment]
Just pushed a change that makes `addAction` return an `IDisposable`. This will allow you to remove an action and register a new one (even possibly with the same id). I have tested the below code after adding the method and it works as expected:

```
var actionRegistration = null;
function switchAction(currentLabel) {
	let newLabel = (currentLabel && currentLabel.indexOf('A') >= 0) ? 'B' : 'A';
	if (actionRegistration) {
		actionRegistration.dispose();
	}
	actionRegistration = editor.addAction({
		id: 'myaction',
		label: newLabel,
		contextMenuGroupId: 'menu',
		run: function (ed) {
			switchAction(this.label);
		}
	})
}
switchAction('B');
```
