### ISSUE TITLE
[feature request] jsonnet support

### ISSUE THREAD

**Issue by GideonSenku** [microsoft/monaco-editor#2860]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

for some reason we want to use jsonnet on `monaco-editor`, is it possible to support this language?

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

Thanks for your understanding!
