### ISSUE TITLE
[Feature Request] Support syntax highlighting of <custom-component>in markdown

### ISSUE THREAD

**Issue by andrewspy** [microsoft/monaco-editor#2863]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Currently, markdown only supports html/tag without `-`, which does not support `<custom-component>` `</custom-component>` properly.

```html
<!-- correct syntax highlighting in markdown -->
<div></div>

<!-- incorrect syntax highlighting in markdown -->
<x-div></x-div>
```

**Comment by rcjsuen** [comment]
@andrewspy I have opened #2864 to try and fix this.
