### ISSUE TITLE
[Bug] Colorization

### ISSUE THREAD

**Issue by da0ka** [microsoft/monaco-editor#2867]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
for example, bellow's colorization is not correct after slash. looks like comment.
var a=/\//,b=a;
```

**Comment by hediet** [comment]
The monaco editor playground code does not compile. Please follow the form to help us processing your issue!
