### ISSUE TITLE
[Bug] font variant ligatures can interfere with cursor placement on click

### ISSUE THREAD

**Issue by skortchmark9** [microsoft/monaco-editor#2868]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

With `font-variant-ligatures: common-ligatures;` set on the element (or in my case, higher in the DOM), clicking on the exclamation point here results in the cursor placement seen below:
![image](https://user-images.githubusercontent.com/6496811/147869003-f0a1c8b2-af9f-47ab-92bf-759f8b21839a.png)

I was doing this in the context of shadow DOM, and the repro is based on the amd-shadow-dom sample. I wonder if shadow DOM might be related to why I wasn't able to reproduce it in the playground. The issue looks pretty similar to #1618 (also on mac) but I did try calling `monaco.editor.remeasureFonts()` and it didn't fix the issue.

Overall it's a pretty minor bug and was trivial for me to work around once I'd understood what the cause was, but I wanted to create the issue because I was very mystified and basically had to bisect my entire app to figure it out.

### Expected Behavior

Cursor is in correct place

**Comment by alexdima** [comment]
When doing DOM measurements to establish if the configured font family is monospace or not, the editor briefly creates a `<div>` with thousands of `a`s, `m`s, etc. and places that as a child of the `<body>`. The extra `font-variant-ligatures: common-ligatures;` does not therefore make it to this measurement `<div>` and the editor ends up believing the font is monospace. In such cases (manipulating the font of the editor through parent CSS rules), the editor needs to be created with `disableMonospaceOptimizations: true`.
