### ISSUE TITLE
How to disable default keybindings?

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#287]

**Comment by rebornix** [comment]
from @dengkunli 

> I read through the API doc (monaco.d.ts) but cannot find a way to disable predefined shortcuts shipped with Monaco. Am I missing something ? How can we disable a shortcut (for example ctrl/cmd + e) ?

> If there's no interface for disabling shortcut currently, will it be supported in the near future ? Having no such interface makes the editor much less customizable.

**Comment by czb** [comment]
Any news on that? I would like to disable ctrl+F keybinding and give it back to browser ;)

**Comment by ledbit** [comment]
Not sure about how to give the functionality back to the browser part, but I found that you can disable the ctrl+F binding by adding your own `noop` one, as follows:

```
editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_F, function() {});
```

**Comment by vlad-shatskyi** [comment]
A workaround to unbind default keybindings using a private API:

```js
editor._standaloneKeybindingService.addDynamicKeybinding("-editor.action.outdentLines");
```

Replace `"editor.action.outdentLines"` with the action you want to unbind. Unlike the @ledbit solution, it doesn't prevent the event from bubbling up.

**Comment by czb** [comment]
@vlad-shatskyi : Thanks 👍 `editor._standaloneKeybindingService.addDynamicKeybinding("-actions.find")` did the job

**Comment by roboslone** [comment]
It doesn't seem to work with `Ctrl/Cmd+L`:
```
Object.keys(editor._actions).forEach(
    k => {
        editor._standaloneKeybindingService.addDynamicKeybinding(`-${k}`)
    }
)
```

After this magic some keybindings are gone (Cmd+F doesn't work, for example), but Cmd+L still expands selection to a next line.

**Comment by donaldpipowitch** [comment]
@roblourens , did you ever found a solution for Cmd+L?

**Comment by jessermejia** [comment]
to unbind Cmd+L try this:

```
editor._standaloneKeybindingService.addDynamicKeybinding('-expandLineSelection');
``` 

i determined which command to unbind by seeing that [this method](https://github.com/microsoft/vscode/blob/960f567da7ab501b9be41b3fc0d3e65c8ba539af/src/vs/platform/keybinding/common/abstractKeybindingService.ts#L157) returned `true`. for Cmd+L, the `resolveResult` found something [here](https://github.com/microsoft/vscode/blob/141617c5b5793b2f7313e8295581afdf88480014/src/vs/platform/keybinding/common/keybindingResolver.ts#L276)


fwiw, the default keybindings can (currently) be listed like this:

```
editor._standaloneKeybindingService._getResolver()._defaultKeybindings
```

`expandLineSelection` gets registered when pulling in `coreCommands` [here](https://github.com/microsoft/vscode/blob/a3e98848e91ca41c6d75d35e6478b3c8fc4eb61d/src/vs/editor/browser/controller/coreCommands.ts#L1371-L1377).

**Comment by alexdima** [comment]
Let's track in #102
