### ISSUE TITLE
[Bug] Completion list rendering broken in custom demo website

### ISSUE THREAD

**Issue by letmaik** [microsoft/monaco-editor#2870]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// see Additional Context below
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/530988/147933083-2b9b71f4-a863-4e89-88c7-23befc119f95.png)

The completion list seems broken in three parts with white in the middle. Also, the symbol to display the help/description text is missing.

### Expected Behavior

![image](https://user-images.githubusercontent.com/530988/147933284-1a617919-7515-452b-8432-87873f9f23fd.png)

### Additional Context

This seems to happen when putting Monaco in a certain HTML/CSS structure, hence it is not reproducible in the monaco playground. The example below demonstrates it and is I think fairly minimal/small. The HTML is fully self-contained for easy hacking.

Stand-alone HTML example:
https://github.com/covjson/playground/blob/7a87cbfdc570b5f81c161a299b2771df19dc2110/repros/playground-simple.html

Live:
https://raw.githack.com/covjson/playground/7a87cbfdc570b5f81c161a299b2771df19dc2110/repros/playground-simple.html

**Comment by matthiasg** [comment]
How is this working anyway ?

When using:

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

What is anybody supposed to do in the json on the right to trigger completion ?

**Comment by hediet** [comment]
There's a reason why we usually don't investigate issues that don't reproduce in the playground...

![image](https://user-images.githubusercontent.com/2931520/224349711-544bc65b-3839-4914-b8de-9d28be396336.png)
