### ISSUE TITLE
[Bug] Unable to update `unicodeHighlight` options after initialization

### ISSUE THREAD

**Issue by CGNonofr** [microsoft/monaco-editor#2873]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
const editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

editor.updateOptions({
    unicodeHighlight: {
        allowedCharacters: {},
        ambiguousCharacters: true,
        includeComments: "inUntrustedWorkspace",
        invisibleCharacters: true,
        nonBasicASCII: "inUntrustedWorkspace"
    }
})
```

### Actual Behavior

An error appears: `TypeError: Cannot read properties of undefined (reading 'allowedCharacters')`

### Expected Behavior

No error

### Additional Context

It only crashes if `unicodeHighlight` is not provided at first, then updated

**Comment by hediet** [comment]
[Fixed](https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.0-dev.20230313#XQAAAALiAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0JraoEChkkcQLjeoXvBZ8P6RMIE6r27RV74d9EXG9PHWAqIhRkGslfPzJAeCBXWYSf72VyTyhpeqb_FX1H8BB233nEuVqzPdubjOtfT91NqaHB142iCOOJrNDCTd2HaDcxcYaK9KUsWgmVk7Z_Pdvt4qA-jL9L6oFEa9u5LoJiqsybxcLWHgw64URQLmVDhQZYo2lUCOl-8EolcYQNt_bNm9ZFpI_H7ME45rZU3skx4uLnvK6WsEuiqsfK45zKy7B5BrxdXUTwl4lHFA6PXoNjg98kgfDcqg3j4A93mjup3cYleWvwhBz5GTDEAImOUgJi6vlUXyZP_aQrBM_tBHeGxXO3TnNav7cE3G)

**Comment by CGNonofr** [comment]
Yes, since the 0.34.0 it seems, thanks!
