### ISSUE TITLE
[Feature Request] enable user to customize CompletionItemKind

### ISSUE THREAD

**Issue by NingJing94** [microsoft/monaco-editor#2876]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

monaco.languages.CompletionItemKind provides near 30 completion item kinds, is there any chance to extend it to customize my own completion item kind? I'm working on a sql editor, and I'd like to customize some icons and styles like below.
Thanks a lot.
![截屏2022-01-04 上午11 29 27](https://user-images.githubusercontent.com/4077902/148005873-d4bdbd93-faba-4ef6-b47a-b892b20684e0.png)

**Comment by jo0ger** [comment]
I want that feature too...

**Comment by Mark-1994** [comment]
请问这个问题解决了吗？
