### ISSUE TITLE
[Feature Request] MAC Doublespace 

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2878]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

In MAC Double spaces will add a '.' I know all editors do this. It comes with Mac However, this shortcut key is filtered out in the vscode editor I wonder how this is done or whether Monaco can filter out this function in MAC I don't want this'. '

**Comment by hediet** [comment]
Are you saying this works in VS Code on mac, but not monaco-editor (in chrome or safari)?
