### ISSUE TITLE
CompletionItemProvider not firing correctly

### ISSUE THREAD

**Issue by jefflevinson** [Microsoft/monaco-editor#288]
monaco-editor npm version: 0.7.0
Browser: Chrome/Edge
OS: Win10

I just updated to the latest version of the Monaco editor and went to test my code and discovered that the trigger characters were not actually working in the CompletionItemProvider – they weren’t trying to complete at the right point and seem to be ignoring that character altogether. I have this screenshot illustrating the problem:

 
![image1](https://cloud.githubusercontent.com/assets/16088053/20986417/7c975114-bc7d-11e6-9ee8-50eab52b8e56.png)

I typed a “W” and this completion provider fired. As can be seen, no periods used anywhere.
And when I actually use a period (as shown here), nothing fires:

 
![image2](https://cloud.githubusercontent.com/assets/16088053/20986420/7f02f016-bc7d-11e6-9d90-552fa7e02d82.png)

This code used to work fine, so what changed that I missed and how do I fix it?

**Comment by StanislawSwierc** [comment]
I've just run into the same problem when I was working on OData language service for VS Code. For this language I need to open window with suggestions for `&` character.

**Comment by alexandrudima** [comment]
ping @jrieken

**Comment by jrieken** [comment]
I typed a “W” and this completion provider fired. As can be seen, no periods used anywhere.

> Typing a `W` is interpreted as starting to type a word and the *quick suggestions* start. That is IntelliSense as you type, but IntelliSense on trigger characters.  

> And when I actually use a period (as shown here), nothing fires:

We don't account the period as being part of a word and therefore nothing happens *unless* you provide the period as explicit trigger character when registering your provider. 

@jefflevinson Please attach the code which registers that completion item provider, it should have a list of trigger characters, like so:

```ts
registerCompletionItemProvider('fooLang', {
  triggerCharacters: ['.', ':'],
  // ...
});
```

**Comment by diegosiao** [comment]
I think it is a connected issue... **Can't we use words as triggers?**

**Comment by jrieken** [comment]
> I think it is a connected issue... Can't we use words as triggers?

No, but you can use the last characters of those words and then your provider must check the words
