### ISSUE TITLE
[Feature Request] Monarch: matching the start of the file

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#2887]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Looking at the provided [`html`](https://microsoft.github.io/monaco-editor/monarch.html) grammar the question is: is it possible to style `<!DOCTYPE html>` specially _only_ if it's at the start of the document?

I have a similar need with trying to match the frontmatter section in a Markdown document, and it just doesn't seem possible to match the start of the document in any way.

**Comment by CareyJWilliams** [comment]
A monarch grammar always starts in the "root" state. You can use that fact to have specific "top of the document" behaviour:
```
  tokenizer: {
    root: [
      { regex: /<!DOCTYPE html>/, token: 'keyword', action: { token: 'keyword', switchTo: "@root2" } },
      { regex: /.*/, switchTo: "@root2" }
    ],
    root2: [
      // identifiers and keywords
      [/[a-z_$][\w$]*/, { cases: { '@typeKeywords': 'keyword',
                                   '@keywords': 'keyword',
                                   '@default': 'identifier' } }],
...
...
```
<img width="527" alt="Screenshot 2022-01-11 at 23 24 16" src="https://user-images.githubusercontent.com/3001447/149037139-1dfeef7c-5bd9-4ebc-9834-201225ff9204.png">

**Comment by fabiospampinato** [comment]
@CareyJWilliams Awesome! Thanks for taking a look at this.

I'm guessing that if no rule matches from the current position then Monarch is going to increment the position by one and loop again the set of rules, if in this case `root2` doesn't match anything would Monarch loop back root2 or root? 🤔  I should probably just test this rather than speculating.

**Comment by CareyJWilliams** [comment]
> @CareyJWilliams Awesome! Thanks for taking a look at this.
> 
> I'm guessing that if no rule matches from the current position then Monarch is going to increment the position by one and loop again the set of rules, if in this case `root2` doesn't match anything would Monarch loop back root2 or root? 🤔  I should probably just test this rather than speculating.

"switchTo" unlike "next" swaps state without modifying the state stack, so I _think_ you'd never end up back at root via @pop and @popall. But I'm assuming that root isn't added to the stack by default at the start, based on the wording of "next":

```
next: state
(string) If defined it pushes the current state onto the tokenizer stack and makes state the current state.
```

**Comment by fabiospampinato** [comment]
Yeah it seems to work like that as far as I can see.
