### ISSUE TITLE
怎么导入一个包,利用包里写好的内容实现代码提示和鼠标移入显示提示语

### ISSUE THREAD

**Issue by yhj0409** [microsoft/monaco-editor#2889]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

想在js的基础上新增一个扩展包,添加新的代码提示和鼠标移入显示的提示语

**Comment by hediet** [comment]
Please use English language. Thank you.
