### ISSUE TITLE
monaco.languages.typescript.getTypeScriptWorker() ... getEmitOutput

### ISSUE THREAD

**Issue by AviPi** [Microsoft/monaco-editor#289]
monaco-editor npm version: 0.7.0
Browser: all
OS: Windows Server 2012 R2

I need to access to output which is the JS emitted by the TypeSript language service. My app used getEmitOutput with an old version of monaco but I can make heads and tails of the new API.

            var backgroundEditor = monaco.editor.create($('<div/>').get(0), {
                value: visualTS,
                language: "typescript"
            });
            result.promise = monaco.languages.typescript.getTypeScriptWorker();
            result.promise.then((worker: Worker) => {
                worker.then(function(client) {
                    client.getEmitOutput(model.uri.toString()).then((output: monaco.editor.IModeOutput) => {
                        backgroundEditor.dispose();
                    });
                });
            });

**Comment by grovesNL** [comment]
I am doing it like this, not sure if it's helpful:

```
const output = ts.transpileModule(editor.getValue(), {
    module: ts.ModuleKind.CommonJS,
    target: ts.ScriptTarget.ES5,
    noLib: true,
    noResolve: true,
    suppressOutputPathCheck: true
})
```

**Comment by jrieken** [comment]
There is `monaco.languages.typescript.get[Type|Java]ScriptWorker` which returns a promise which resolves to a proxy of the TypeScript language service API

**Comment by czb** [comment]
@jrieken : could you please be more explicit? I also have no idea how to proceed. When I call

    monaco.languages.typescript.getTypeScriptWorker().then((worker) => { console.log(worker) })

I get back

    function (e){for(var t=[],n=1;n<arguments.length;n++)t[n-1]=arguments[n];return s.getLanguageServiceWorker.apply(s,[e].concat(t))}

What shall I do with that function?

**Comment by joewood** [comment]
In case other stumble on this, you can do (where `uri` is the `monaco.Uri` of the main code file):

```typescript
const worker = await monaco.languages.typescript.getTypeScriptWorker();
const client = await worker(uri);
const result = await client.getEmitOutput(uri.toString());
```

**Comment by rjamesnw** [comment]
Why is a `uri` required just to get access to the code in the editor?  I don't have a `uri` to any code file, so none of this makes any sense.  I don't know why it has to be so difficult just to get the transpiled output.

**Comment by rjamesnw** [comment]
Ok, It was not clear before, but I see now that a model is the code in the editor.  You can create models, or you can create an editor with a default model it seems; so `monaco.editor.create()` returns an editor, and you can use `editor.getModel()` to get the model associated with the editor.  The model then has `model.uri`, which I guess is the file reference ID of sorts.
