### ISSUE TITLE
[Bug] Command palette and search not working well on Vite builds

### ISSUE THREAD

**Issue by L1ghtingBolt** [microsoft/monaco-editor#2890]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [x] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
Not reproducible.
```

### Actual Behavior

Everything works completely fine on dev mode using Vite and Monaco, but when I build it, gives this error each time you open command palette
`iconLabels.js:22 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at FP (iconLabels.js:22:14)
    at fb.getCodeEditorCommandPicks (commandsQuickAccess.js:21:24)
    at fb.<anonymous> (standaloneCommandsQuickAccess.js:45:25)
    at Generator.next (<anonymous>)
    at standaloneCommandsQuickAccess.js:20:71
    at new Promise (<anonymous>)
    at qhe (standaloneCommandsQuickAccess.js:16:12)
    at fb.getCommandPicks (standaloneCommandsQuickAccess.js:44:16)
    at fb.<anonymous> (commandsQuickAccess.js:53:48)
    at Generator.next (<anonymous>)
FP @ iconLabels.js:22
getCodeEditorCommandPicks @ commandsQuickAccess.js:21
(anonymous) @ standaloneCommandsQuickAccess.js:45
(anonymous) @ standaloneCommandsQuickAccess.js:20
qhe @ standaloneCommandsQuickAccess.js:16
getCommandPicks @ standaloneCommandsQuickAccess.js:44
(anonymous) @ commandsQuickAccess.js:53
(anonymous) @ commandsQuickAccess.js:20
F8 @ commandsQuickAccess.js:16
_getPicks @ commandsQuickAccess.js:51
(anonymous) @ pickerQuickAccess.js:70
(anonymous) @ pickerQuickAccess.js:11
G1 @ pickerQuickAccess.js:7
a @ pickerQuickAccess.js:60
provide @ pickerQuickAccess.js:197
doShowOrPick @ quickAccess.js:111
show @ quickAccess.js:33
run @ standaloneCommandsQuickAccess.js:82
runEditorCommand @ editorExtensions.js:207
(anonymous) @ editorExtensions.js:165
invokeFunction @ instantiationService.js:47
invokeWithinContext @ codeEditorWidget.js:240
runCommand @ editorExtensions.js:159
handler @ editorExtensions.js:62
invokeFunction @ instantiationService.js:47
executeCommand @ simpleServices.js:182
_doDispatch @ abstractKeybindingService.js:184
_dispatch @ abstractKeybindingService.js:94
(anonymous) @ simpleServices.js:199
Promise.then (async)
d @ pickerQuickAccess.js:10
(anonymous) @ pickerQuickAccess.js:11
G1 @ pickerQuickAccess.js:7
a @ pickerQuickAccess.js:60
provide @ pickerQuickAccess.js:197
doShowOrPick @ quickAccess.js:111
show @ quickAccess.js:33
run @ standaloneCommandsQuickAccess.js:82
runEditorCommand @ editorExtensions.js:207
(anonymous) @ editorExtensions.js:165
invokeFunction @ instantiationService.js:47
invokeWithinContext @ codeEditorWidget.js:240
runCommand @ editorExtensions.js:159
handler @ editorExtensions.js:62
invokeFunction @ instantiationService.js:47
executeCommand @ simpleServices.js:182
_doDispatch @ abstractKeybindingService.js:184
_dispatch @ abstractKeybindingService.js:94
(anonymous) @ simpleServices.js:199`
Plus, when you open search using Ctrl + F, it is in chinesse
![image](https://user-images.githubusercontent.com/82386159/149501510-7baae868-fabf-4a69-bb4e-f68464ad5541.png)
And the command palette looks like this:
![image](https://user-images.githubusercontent.com/82386159/149501554-cb2cbdde-934f-425d-b489-717d990c804c.png)

It works on dev mode, why doesn't it when built?

### Expected Behavior

The command palette should see like this:
![image](https://user-images.githubusercontent.com/82386159/149501691-26470675-5a24-4e23-b7ba-1d13c8875948.png)
And the search should be like this:
![image](https://user-images.githubusercontent.com/82386159/149501729-e9d8e317-5741-45d1-9ec3-45f2423b4144.png)

### Additional Context

You can find the complete code on https://github.com/L1ghtingBolt/codeebox
If you click the error from the console:
![image](https://user-images.githubusercontent.com/82386159/149502093-e4f3554e-74aa-45e6-affc-f621eef0f414.png)

### EDIT:
Solved, it was because I was using monaco vite plugin NLS, changed it to https://www.npmjs.com/package/vite-plugin-monaco-editor and now it works fine!

**Comment by littleCareless** [comment]
不使用monaco vite plugin NLS，如何解决本地化的？

**Comment by littleCareless** [comment]
> ### Reproducible in vscode.dev or in VS Code Desktop?
> ### 在 vscode.dev 或 VS 代码桌面中可重现？
> * [x]  Not reproducible in  不能复制[vscode.dev](https://vscode.dev) or VS Code Desktop 或 VS 代码桌面
> 
> ### Reproducible in the monaco editor playground?
> ### 在摩纳哥编辑的游乐场上可以复制吗？
> * [x]  Not reproducible in  不能复制[the monaco editor playground 摩纳哥编辑游乐场](https://microsoft.github.io/monaco-editor/playground.html)
> 
> ### Monaco Editor Playground Code
> ### 摩纳哥编辑游乐场代码
> ```ts
> Not reproducible.
> ```
> 
> ### Actual Behavior
> ### 实际行为
> Everything works completely fine on dev mode using Vite and Monaco, but when I build it, gives this error each time you open command palette `iconLabels.js:22 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf') at FP (iconLabels.js:22:14) at fb.getCodeEditorCommandPicks (commandsQuickAccess.js:21:24) at fb.<anonymous> (standaloneCommandsQuickAccess.js:45:25) at Generator.next (<anonymous>) at standaloneCommandsQuickAccess.js:20:71 at new Promise (<anonymous>) at qhe (standaloneCommandsQuickAccess.js:16:12) at fb.getCommandPicks (standaloneCommandsQuickAccess.js:44:16) at fb.<anonymous> (commandsQuickAccess.js:53:48) at Generator.next (<anonymous>) FP @ iconLabels.js:22 getCodeEditorCommandPicks @ commandsQuickAccess.js:21 (anonymous) @ standaloneCommandsQuickAccess.js:45 (anonymous) @ standaloneCommandsQuickAccess.js:20 qhe @ standaloneCommandsQuickAccess.js:16 getCommandPicks @ standaloneCommandsQuickAccess.js:44 (anonymous) @ commandsQuickAccess.js:53 (anonymous) @ commandsQuickAccess.js:20 F8 @ commandsQuickAccess.js:16 _getPicks @ commandsQuickAccess.js:51 (anonymous) @ pickerQuickAccess.js:70 (anonymous) @ pickerQuickAccess.js:11 G1 @ pickerQuickAccess.js:7 a @ pickerQuickAccess.js:60 provide @ pickerQuickAccess.js:197 doShowOrPick @ quickAccess.js:111 show @ quickAccess.js:33 run @ standaloneCommandsQuickAccess.js:82 runEditorCommand @ editorExtensions.js:207 (anonymous) @ editorExtensions.js:165 invokeFunction @ instantiationService.js:47 invokeWithinContext @ codeEditorWidget.js:240 runCommand @ editorExtensions.js:159 handler @ editorExtensions.js:62 invokeFunction @ instantiationService.js:47 executeCommand @ simpleServices.js:182 _doDispatch @ abstractKeybindingService.js:184 _dispatch @ abstractKeybindingService.js:94 (anonymous) @ simpleServices.js:199 Promise.then (async) d @ pickerQuickAccess.js:10 (anonymous) @ pickerQuickAccess.js:11 G1 @ pickerQuickAccess.js:7 a @ pickerQuickAccess.js:60 provide @ pickerQuickAccess.js:197 doShowOrPick @ quickAccess.js:111 show @ quickAccess.js:33 run @ standaloneCommandsQuickAccess.js:82 runEditorCommand @ editorExtensions.js:207 (anonymous) @ editorExtensions.js:165 invokeFunction @ instantiationService.js:47 invokeWithinContext @ codeEditorWidget.js:240 runCommand @ editorExtensions.js:159 handler @ editorExtensions.js:62 invokeFunction @ instantiationService.js:47 executeCommand @ simpleServices.js:182 _doDispatch @ abstractKeybindingService.js:184 _dispatch @ abstractKeybindingService.js:94 (anonymous) @ simpleServices.js:199` Plus, when you open search using Ctrl + F, it is in chinesse ![image](https://user-images.githubusercontent.com/82386159/149501510-7baae868-fabf-4a69-bb4e-f68464ad5541.png) And the command palette looks like this: ![image](https://user-images.githubusercontent.com/82386159/149501554-cb2cbdde-934f-425d-b489-717d990c804c.png)
> 
> 在使用 Vite 和 Monaco 的开发模式下，一切都运行良好，但当我构建它时，每次在 fb 打开命令面板 iconLabels.js: 22 Uncaught (in promise) TypeError: Can not read properties of undefined (read‘ indexOf’) at FP (iconLabels.js: 22:14) at fb.getcodeeditorcommandpices (commandsqudaccessick.js: 21:24)时都会出现这个错误。匿名 > (standaloncommandsquickaccess.js: 45:25) at standaloncommandsquickaccess.js: 20:71 at new Promise (< anonymous >) at qhe (standaloncommandsquickaccess.js: 16:12) at fb.getCommandPicks (standaloncommandsquickaccess.js: 44:16) at fb。Generator 的 < anonymous > (commandsQuickAccess.js: 53:48)。下一页(< anonymous >) FP@iconLabels。22 getCodeEditorCommandPicks@commandsQuickAccess.Js: 21(anonymous)@standaloncommandsquickaccess.45(anonymous)@standaloncommandsquickaccess.20 qhe@standaloncommandsquickaccess.16 getCommandPicks@standaloncommandsquickaccess.Js: 44(anonymous)@commandsQuickAccess.Js: 53(anonymous)@commandsQuickAccess.20 f 8@commandsQuickAccess.16 getPicks@commandsQuickAccess.Js: 51(anonymous)@pickerQuickAccess.Js: 70(anonymous)@pickerQuickAccess.11 g 1@pickerQuickAccess.7 a@pickerQuickAccess.60提供@pickerQuickAccess。197 doShowOrPick@quickAccess.111 show@quickAccess.33 run@standaloncommandsquickaccess.82 runEditorCommand@editorExtensions.Js: 207(anonymous)@editorExtensions.165 invokeFunction@instinationservice.47 invokeWithinContext@codeEditorWidget.240 runCommand@editorExtensions.159 handler@editorExtensions.62 invokeFunction@instinationservice.47 executeCommand@simpleServices.182 doDispatch@abstractKeybindingService.184 dispatch@abstractKeybindingService.Js: 94(anonymous)@simpleeservices.199 Promise.然后(async) d@pickerQuickAccess。10(anonymous)@pickerQuickAccess.11 g 1@pickerQuickAccess.7 a@pickerQuickAccess.60提供@pickerQuickAccess。197 doShowOrPick@quickAccess.111 show@quickAccess.33 run@standaloncommandsquickaccess.82 runEditorCommand@editorExtensions.Js: 207(anonymous)@editorExtensions.165 invokeFunction@instinationservice.47 invokeWithinContext@codeEditorWidget.240 runCommand@editorExtensions.159 handler@editorExtensions.62 invokeFunction@instinationservice.47 executeCommand@simpleServices.182 doDispatch@abstractKeybindingService.184 dispatch@abstractKeybindingService.Js: 94(anonymous)@simpleeservices.199另外，当你使用 Ctrl + f 打开搜索时，它是 chinesse命令面板看起来像这样:
> 
> It works on dev mode, why doesn't it when built?
> 
> ### Expected Behavior
> The command palette should see like this: ![image](https://user-images.githubusercontent.com/82386159/149501691-26470675-5a24-4e23-b7ba-1d13c8875948.png) And the search should be like this: ![image](https://user-images.githubusercontent.com/82386159/149501729-e9d8e317-5741-45d1-9ec3-45f2423b4144.png)
> 
> ### Additional Context
> You can find the complete code on https://github.com/L1ghtingBolt/codeebox If you click the error from the console: ![image](https://user-images.githubusercontent.com/82386159/149502093-e4f3554e-74aa-45e6-affc-f621eef0f414.png)
> 
> ### EDIT:
> Solved, it was because I was using monaco vite plugin NLS, changed it to https://www.npmjs.com/package/vite-plugin-monaco-editor and now it works fine!

How do you solve localisation without using `vite-plugin-monaco-editor-nls`.

**Comment by L1ghtingBolt** [comment]
> How do you solve localisation without using `vite-plugin-monaco-editor-nls`.

I didn't. The problem was BECAUSE of `vite-plugin-monaco-editor-nls`. I solved it by removing `vite-plugin-monaco-editor-nls`.
