### ISSUE TITLE
editor.getAction('editor.action.formatDocument') returns null in Monaco Editor 0.31.1

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2892]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

(* this is not a feature request *)

I'm upgrading Monaco Editor from "^0.20.0" to "^0.31.1".

With "^0.20.0", `this.editor.getAction('editor.action.formatDocument')` returned well the formatting action. However, now with "^0.31.1", `this.editor.getAction('editor.action.formatDocument')` returns null. I tried also `this.editor.getSupportedActions()`, it returns null too.

Does anyone know what might be the cause?

**Comment by hediet** [comment]
Please use the bug report issue template. Thank you!

**Comment by JiquanWang99** [comment]
I met the same problem when I updated to the latest version. Now I have fallback to 0.25.2 version, it can work well in this version
