### ISSUE TITLE
setModel does not work anymore after upgrading Monaco Editor

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2893]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

(* this is not a feature request *)

I have an editor built with Monaco Editor and [React Monaco Editor](https://github.com/react-monaco-editor/react-monaco-editor).

It worked quite well with Monaco Editor 0.20.0. The following code prints well `logs inside onLanguage`. And when we hover on a text, `logs inside provideHover` is well printed. `logs before setModel` and `logs after setModel` are always printed.

```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
const MonacoEditor = lazy(() => import('react-monaco-editor'));

const LANGUAGE_ID_A1 = 'formula_A1';
const value = `123`;

monaco.languages.register({ id: LANGUAGE_ID_A1, extensions: [], aliases: [], mimetypes: [], });
console.log("logs outside monaco.languages.getLanguages", monaco.languages.getLanguages())
monaco.languages.setLanguageConfiguration(LANGUAGE_ID_A1, formula.conf);
monaco.languages.setMonarchTokensProvider(LANGUAGE_ID_A1, formula.language);

class ResizableMonacoEditor extends React.Component {

  _handleEditorDidMount(editor) {

    monaco.languages.onLanguage(LANGUAGE_ID_A1, () => {
      console.log("logs inside onLanguage");
    });

    monaco.languages.registerHoverProvider(LANGUAGE_ID_A1, {
      provideHover: (model, position, token) => {
        console.log("logs inside provideHover")
      }
    });

    this.monacoFormulaModel_A1 = monaco2.editor.createModel(value, LANGUAGE_ID_A1);
    console.log("logs before setModel")
     
    editor.setModel(this.monacoFormulaModel_A1)
    console.log("logs after setModel")
  }
   
  render() {
    return <Suspense>
      <MonacoEditor {...this.props} editorDidMount={this._handleEditorDidMount.bind(this)} />
    </Suspense>
  }
}
```

However, after I upgraded the version of Monaco Editor to 0.31.1, launching the website raised an error:

[![enter image description here][1]][1]

It seems that it is `setModel` that raised the error. I cannot find `setModel` in https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html. Does anyone know how to fix it?

PS: in `package-lock.json`:

```json
    "monaco-editor": {
      "version": "0.31.1",
      "resolved": "https://registry.npmjs.org/monaco-editor/-/monaco-editor-0.31.1.tgz",
      "integrity": "sha512-FYPwxGZAeP6mRRyrr5XTGHD9gRXVjy7GUzF4IPChnyt3fS5WrNxIkS8DNujWf6EQy0Zlzpxw8oTVE+mWI2/D1Q=="
    },
    "react-monaco-editor": {
      "version": "0.35.0",
      "resolved": "https://registry.npmjs.org/react-monaco-editor/-/react-monaco-editor-0.35.0.tgz",
      "integrity": "sha512-iQbJykYPgKko0yqphTVWi1vHFokFShv5qpWnFV2TvtliKG45x2LVF4/HC06MDVK4fBfp2lCrun+NUcEYMzAnNQ==",
      "requires": {
        "@types/react": "^15.x || ^16.x",
        "monaco-editor": "*",
        "prop-types": "^15.7.2"
      }
    },
```

  [1]: https://i.stack.imgur.com/wdKk7.png

**Comment by mortada-codes** [comment]
have you found a solution? i am facing the same error

**Comment by hediet** [comment]
Can you try to reproduce it in the monaco playground without react?

**Comment by chengtie** [comment]
I could not reproduce the problem any more... sorry about that...
