### ISSUE TITLE
Turn off word highlight by default

### ISSUE THREAD

**Issue by Peter-Juhasz** [Microsoft/monaco-editor#290]
monaco-editor npm version: 0.7.0
Browser: Chrome 54
OS: Windows 10

Highlight only symbol references and do not highlight words by default. This is completely useless:

![image](https://cloud.githubusercontent.com/assets/9047283/21131329/5fb5697e-c10e-11e6-831b-afec417cb662.png)

This is not a feature but a bug. At least provide an option to disable this behavior.

**Comment by alexandrudima** [comment]
@Peter-Juhasz There exists such an option that you can use when creating the editor: `selectionHighlight: false`

---

Please refer to this project's [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) for further participation.
