### ISSUE TITLE
provideDocumentRangeSemanticTokens is not getting triggered after registering registerDocumentRangeSemanticTokensProvider

### ISSUE THREAD

**Issue by ManojkumarV** [microsoft/monaco-editor#2900]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

**Comment by hediet** [comment]
Please provide an example to reproduce the bug.
