### ISSUE TITLE
[Feature Request] change readonly tooltip label "cannot edit read-only editor" when used "createDiffEditor"

### ISSUE THREAD

**Issue by Jinzm** [microsoft/monaco-editor#2906]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

when i use 'createDiffEditor' && 'readonly' to compared two code diff, "cannot edit read-only editor" will show if i input something. I want to change the tip

**Comment by hediet** [comment]
With https://github.com/microsoft/vscode/commit/052f02175f4752c36024c18cfbca4e13403e10c3, you can just skip the `readOnlyMessage` contribution and provide your own.

This will be available in the next monaco editor release.
