### ISSUE TITLE
[Bug] Uncaught SyntaxError: Unexpected token '?' In Chrome 78

### ISSUE THREAD

**Issue by Julinear** [microsoft/monaco-editor#2908]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco-editor 0.31.1
Browser:Chrome 78.0.3904.97 64bit
OS: Windows

The monaco doesn't work in Chrome 78 in playground!!  The js error is 'Uncaught SyntaxError: Unexpected token '?''.
```

### Actual Behavior

![error](https://user-images.githubusercontent.com/33052315/150503918-43a42bb8-66f8-4ad8-9131-36db535a16ed.PNG)

### Expected Behavior

monaco-editor is supposed to load normally in chrome 78

**Comment by hediet** [comment]
Chrome 78 is more than 2 years old. We only support the most recent browsers.

Maybe you can use esbuild/webpack to transpile the monaco code to ECMAScript 2019 that should be compatible with chrome 78.

**Comment by zhangyfan** [comment]
I noticed that is cause by ?? syntax whichi is supported by Chrome 80. So, I want to disable this ES feature in WebPack5. Working on this...

**Comment by Julinear** [comment]
> I noticed that is cause by ?? syntax which is supported by Chrome 80. So, I want to disable this ES feature in WebPack5. Working on this...

I compiled file to js in Babel homepage, and then replace it in node_module，it worked. Another way is to use monaco-editor with a lower version. But both of them are not the best way to solve this problem.
