### ISSUE TITLE
[Feature Request] Highlight Keywords like in Baretail

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/monaco-editor#2914]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I like a feature like in Baretail where you can Highlight some Keywords or a RegEx via a defined color.
Same like the "search" does, but via an API

**Comment by hediet** [comment]
We don't know Baretail. Please open a feature request that is more specific and self-containing. Thanks for understanding!
