### ISSUE TITLE
[Feature Request] Hide vertical lines indicating scope of functions

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#2916]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I would like to know which option is to hide vertical lines in grey which indicate scope of functions.

Could anyone help?

![Screenshot 2022-01-24 at 23 05 28](https://user-images.githubusercontent.com/774409/150873118-02c32790-4349-4b57-ae54-6c1b5e361f8f.png)

**Comment by rcjsuen** [comment]
Those are [indentation guides](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IGuidesOptions.html#indentation).

```JavaScript
monaco.editor.create(document.getElementById('container'), {
    value: "function hello() {\n\talert('Hello world!');\n\n\n\n\n}",
    language: 'javascript',
    guides: {
        indentation: false
    }
});
```

**Comment by chengtie** [comment]
> Those are [indentation guides](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IGuidesOptions.html#indentation).
> 
> ```js
> monaco.editor.create(document.getElementById('container'), {
>     value: "function hello() {\n\talert('Hello world!');\n\n\n\n\n}",
>     language: 'javascript',
>     guides: {
>         indentation: false
>     }
> });
> ```

Thank you, it works.
