### ISSUE TITLE
[Feature Request] Ability to show diff information in the single editor

### ISSUE THREAD

**Issue by skymansandy** [microsoft/monaco-editor#2917]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Capability to show the diff in the single editor instead of 2 split editors would be great. Does this feature already exist?

<img width="1263" alt="Iec8g" src="https://user-images.githubusercontent.com/17377683/151058246-20d1253b-f0ab-4269-8315-2af6f8f9c26a.png">

**Comment by spahnke** [comment]
See https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-inline-diff-example

**Comment by skymansandy** [comment]
Hey @spahnke .. thanks for the link.. is there a way to only show the diff on clicking of some button in but left gutter area?

**Comment by spahnke** [comment]
Not out of the box, but you can probably build that yourself using editor APIs. It's a bit of work, but AFAIK it's the same process e.g. the peek definition/peek references view does under the hood.

1. Add a viewzone to the editor at the desired position (https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneCodeEditor.html#changeViewZones). A viewzone reserves space between editor lines.
2. Add a content widget in the exact same position and dimensions as the viewzone (https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneCodeEditor.html#addContentWidget). A content widget is a DOM node you control. The editor then renders it at the correct place inside the editor.
3. Create a diff editor inside the DOM node of your content widget.

Examples to viewzones and content widgets: https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-mouse-events

**Comment by skymansandy** [comment]
Awesome. thanks for the detailed explanation @spahnke  :)
