### ISSUE TITLE
[Feature Request] do not auto select first completion item in suggestion dialog

### ISSUE THREAD

**Issue by lidermanrony** [microsoft/monaco-editor#2918]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Currently suggestion dialog will select first completion item by default:
![image](https://user-images.githubusercontent.com/199509/151068054-0348b399-5669-43d6-99b5-4c65a09331ac.png)

In our scenario we want to be very aggressive about triggering the suggestion dialog, thus we'd like the user to "opt out" from the suggestion dialog by pressing ENTER, otherwise users that would like to go to the next line will get unwanted completion items instead.

the suggestion is as follows:
 - when suggestion dialog is opened, no item is selected. pressing enter will close the suggestion dialog without any text inserted. pressing the down arrow instead will cause the first item to get selected.

**Comment by rcjsuen** [comment]
It sounds like you may be looking for https://github.com/microsoft/vscode/issues/139825?

**Comment by lidermanrony** [comment]
sounds like it!
