### ISSUE TITLE
[Bug] Wrong highlight for TypeScript

### ISSUE THREAD

**Issue by nuang-ee** [microsoft/monaco-editor#2919]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// Used editor demo in the home page: https://microsoft.github.io/monaco-editor/index.html
// Not on playground!!!

type UserType = 'ORGANIC' | 'PAID'

const foo = 1;
const type: UserType = 'ORGANIC';
const interface = 'interface'


function handleUser(normalParamName: string, type: UserType) {
    switch (type) {
        case 'ORGANIC':
            // do something
            break;
        case 'PAID':
            // do something
            break;
        default:
            break;
    }
    return normalParamName;
}
```

### Actual Behavior

![image](https://user-images.githubusercontent.com/50770626/151091675-5262d1e2-412d-41ce-849e-e0954090dacb.png)

As you can see, `type` and `interface` can be used as keyword name, but they are highlighted as keywords when used as a variable names.

### Expected Behavior

TypeScript keywords that can be used as variable name should be highlighted like variable name when used as variable name.

Example:

![image](https://user-images.githubusercontent.com/50770626/151091712-e9d205c6-dad8-49b5-8002-5d513b618125.png)

**Comment by hediet** [comment]
This is a shortcoming of the monaco typescript tokenizer (which is different from the textmate grammar used in VS Code).

**Comment by rcjsuen** [comment]
> This is a shortcoming of the monaco typescript tokenizer (which is different from the textmate grammar used in VS Code).

@hediet Is there a reason why Monaco doesn't use semantic tokens? That would solve this issue, correct?

**Comment by hediet** [comment]
This is the source of the TS monarch tokenizer:
https://github.com/microsoft/monaco-editor/blob/main/src/basic-languages/typescript/typescript.ts

> @hediet Is there a reason why Monaco doesn't use semantic tokens? That would solve this issue, correct?

Performance. The typescript tokenizer depends on the parser and vice versa. Thus, you need full (incremental) parsing for accurate tokens. If you provide them synchronously, you might run into performance issues.

**Comment by stefandobre** [comment]
@rcjsuen do feel free to give this issue a thumbs up.
https://github.com/microsoft/monaco-editor/issues/2872
