### ISSUE TITLE
[Bug] automaticLayout doesnt shrink to container

### ISSUE THREAD

**Issue by rice-cracker-2234** [microsoft/monaco-editor#2920]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Additional Context

monaco editor only resizes when container's size grew with automaticLayout set to true

**Comment by hediet** [comment]
Thanks for reporting this! However, it will take us much longer to fix this without a minimum reproducible example.
