### ISSUE TITLE
[Bug] Docs do not document indent guides (though it still works). 

### ISSUE THREAD

**Issue by 7ombie** [microsoft/monaco-editor#2927]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

The [official docs for creating an editor][1] do not mention indent guides. However, the actual `editor` constructor still respects an `options` hash with `renderIndentGuides: Boolean`.

[1]: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneEditorConstructionOptions.html

### Expected Behavior

The docs would match the code.

**Comment by 7ombie** [comment]
P.S. It was awkward to report this. The process does not provide an obvious path for reporting issues in documentation.

**Comment by hediet** [comment]
`renderIndentGuides` is deprecated. You should use `guides.highlightActiveIndentation` instead.
There you can also enable bracket pair indent guides.
