### ISSUE TITLE
[Bug] Monaco renders four dots under some variables, and it cannot be disabled??

### ISSUE THREAD

**Issue by 7ombie** [microsoft/monaco-editor#2928]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
void function(foo) {

    const x = fooo;
    const f = bar => barr;
}
```

### Actual Behavior

There are four little dots under the first two characters of `fooo` and `barr`. These dots appear whenever the variable is similar but not correct, like a fuzzy spellchecker.

The [`IStandaloneEditorConstructionOptions`][1] do not contain an option for disabling the dots.

[1]: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IStandaloneEditorConstructionOptions.html

### Expected Behavior

The `IStandaloneEditorConstructionOptions` do contain an option for disabling the dots.

### Additional Context

I'm working on a webapp, reusing Monaco in a configuration that is graphically very plain. These dots could be a useful way to indicate issues. However, they're not documented anywhere.

If I could customize when the dots appear (and maybe other things about the dots), they could be really useful for indicating and locating issues. As it stands, I just want to disable them.

**Note**: I'm sure I can find a way to make the dots invisible in CSS, but that would be a pretty nasty workaround, as the code would still be running in the background.

**Comment by 7ombie** [comment]
P.S. It'd be really handy if VSCode/Monaco had a page in the docs that documented each part of the UI with PNG and GIF examples, so users could easily learn the UI nomenclature.

**Comment by hediet** [comment]
Can you show a screenshot of those dots?

**Comment by oldrich-s** [comment]
It is a spelling quickfix?

![image](https://user-images.githubusercontent.com/37391/152484335-8872b178-0de8-4fb4-bd48-ea681d67c3be.png)

**Comment by hediet** [comment]
These three dots indicate that quick fixes are available (in this case a spelling quick-fix by typescript).

**Comment by spahnke** [comment]
You can control that on the language side (I'm assuming JS)

```js
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({
    noSuggestionDiagnostics: true
});
```

**Comment by 7ombie** [comment]
Yes and yes. That's it. Thank you. That's exactly what I was looking for.

Sorry I didn't respond sooner. Thanks again.

**Comment by 7ombie** [comment]
P.S. There were four dots. If that's relevant, I can grab a screenshot and share some code *et cetera*.
