### ISSUE TITLE
.hidden should not be in global css space

### ISSUE THREAD

**Issue by h8liu** [Microsoft/monaco-editor#294]
monaco-editor npm version: 0.7.0
Browser: any
OS: any

I am using monaco editor in a div (rather than in an iframe). Loading the editor will load a `main.css`, which contains a global `.hidden { display: none !important; visibility: none !important; }` This breaks my existing styles because I also have `.hidden` classes with css animated transitions (e.g. fading out), but the `!important` in `main.css` overwrote them, and it took me a long time to debug the broken animation.

Please consider move the `.hidden` inside to some monaco specific classes, so that they are not intrusive. Thanks.

**Comment by alexandrudima** [comment]
@bpasero This comes in from https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/builder.css#L6

**Comment by alexandrudima** [comment]
Thank you! ❤️
