### ISSUE TITLE
[Bug] XXX depends on UNKNOWN service YYY.

### ISSUE THREAD

**Issue by oldrich-s** [microsoft/monaco-editor#2941]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Additional Context

After update to the latest version 0-32-0 (from yesterday) I get the following errors. I build monaco using esbuild. Version 0-31-1 did not have these crashes. Do you know what could go wrong or how to debug / investigate this issue?

![image](https://user-images.githubusercontent.com/37391/152483562-162da48d-b8f8-4101-91bf-0b3e3a2cfc81.png)

EDIT:

this is our build.js script

```
const esbuild = require('esbuild');
const path = require('path');

build({
	entryPoints: ['./node_modules/monaco-editor/esm/vs/editor/editor.main.js'],
	bundle: true,
	format: 'iife',
	outdir: path.join(__dirname, 'dist'),
	loader: { '.ttf': 'file' },
	globalName: 'monaco',
});

build({
	entryPoints: [
		'./node_modules/monaco-editor/esm/vs/language/json/json.worker.js',
		'./node_modules/monaco-editor/esm/vs/language/css/css.worker.js',
		'./node_modules/monaco-editor/esm/vs/language/html/html.worker.js',
		'./node_modules/monaco-editor/esm/vs/language/typescript/ts.worker.js',
		'./node_modules/monaco-editor/esm/vs/editor/editor.worker.js',
	],
	bundle: true,
	format: 'iife',
	outdir: path.join(__dirname, 'dist'),
	loader: { '.ttf': 'file' },
});

function build(opts) {
	esbuild.build(opts).then((result) => {
		if (result.errors.length > 0) {
			console.error(result.errors);
		}
		if (result.warnings.length > 0) {
			console.error(result.warnings);
		}
	});
} 
```

and this is a minimal example that produces the error:

```
globalThis.MonacoEnvironment = {
  getWorkerUrl: function (_moduleId: string, label: string) {
    if (label === 'typescript') {
      return Path.join(dirPath, `language/typescript/ts.worker.js`)
    }

    return Path.join(dirPath, 'editor/editor.worker.js')
  },
}

const editor = monaco.editor.create($div, { language: 'typescript' })

editor.setValue('const x = 5')
```

**Comment by hediet** [comment]
This does not make so much sense. I wonder why it says `CodeLensContribution2` and not `CodeLensContribution`, there is no such `CodeLensContribution2` in the code base.

Also, the implementation for `ICodeLensCache` is registered in the same module where the service is defined, thus it shouldn't be unknown.

**Comment by oldrich-s** [comment]
Before you fixed https://github.com/microsoft/monaco-editor/issues/2877 there was also LanguageServiceDefaultsImpl2 in the codebase. So it might be that  CodeLensContribution2 is also a duplicate implementation and renamed by esbuild.

**Comment by oldrich-s** [comment]
I guess that `CodeLensContribution2` is there because esbuild compiles the code into `var CodeLensContribution = class CodeLensContribution2 {`.

I have just tried to build and run example from `/samples/browser-esm-esbuild/` and got the same errors:

![image](https://user-images.githubusercontent.com/37391/152528573-81a6e928-420f-4717-b81e-c6e7a367b71a.png)

**Comment by alexdima** [comment]
In `0.32.0` we have aligned the service setup in the editor to be based on [registering services](https://github.com/microsoft/vscode/blob/5329f57d340de59b9943818048aac8583e275572/src/vs/editor/standalone/browser/standaloneServices.ts#L940-L970), while before we would be manually 'newing' up each service. Maybe eslint is removing those classes because it can't find references to `new X`?

**Comment by alexdima** [comment]
I was able to reproduce. This is because the [service collection initialization code](https://github.com/microsoft/vscode/blob/e22b2569421d198c7cb3399cb59450b2204ed7f5/src/vs/editor/standalone/browser/standaloneServices.ts#L978-L981) executes before the `ICodeLensCache` service has had a chance to be defined.
