### ISSUE TITLE
Add a version number to the Monaco runtime

### ISSUE THREAD

**Issue by orta** [microsoft/monaco-editor#2948]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I think the crux of this is an upstream issue, as I think it revolves around monaco-editor-core realistically, but there's an issue with the TS playground https://github.com/microsoft/TypeScript-Website/issues/2247 where we need to be able to provide different API shapes to the inlay provider API in Monaco.

I can bake the version number into our deploy process in [ts/make-monaco-builds](https://github.com/microsoft/TypeScript-Make-Monaco-Builds) but it feels like something which is just generically useful everywhere.

**Comment by hediet** [comment]
Nice to see you still active here ;)

I don't fully understand the issue though. Why is the static version number of the installed monaco-editor package not enough? Cannot you do something ala `require('monaco-editor/package.json').version`?

**Comment by orta** [comment]
👋🏻 - I can bundle the version in myself with everything that's in the package.json today (the nightly TS process binds the latest version of Monaco with the latest version of Monaco to aim for best compat) but the playground can be running any version of Monaco which can change at runtime when you change the version of TS - at that point we don't have access to a package.json (and thus the version) inside the UMD builds of monaco.

Yeah, this has been the first time we've needed to handle two separate API shapes in Monaco, so really the first time I've had to think about it

**Comment by hediet** [comment]
Cannot you have the same typescript monaco contribution for all versions of TypeScript?

Then you don't need to chose a different monaco version when changing the typescript version.

**Comment by orta** [comment]
We could yep, and that's basically what we're doing now by locking to a Monaco commit in the build process - but letting the Monaco version fall behind also has its own tradeoffs

**Comment by hediet** [comment]
Closing this as there is a workaround and this problem seems to be very specific.
