### ISSUE TITLE
[Bug] resolveCompletionItem not waiting for promise to resolve

### ISSUE THREAD

**Issue by zaccharles** [microsoft/monaco-editor#2949]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
const suggestion =  {
    label: 'example',
    kind: monaco.languages.CompletionItemKind.Snippet
}  

monaco.languages.registerCompletionItemProvider('json', {
	provideCompletionItems: function () {
		return {
			suggestions: [
               suggestion
            ]
		};
	},

    resolveCompletionItem: function(item) {
        const promise = new Promise((resolve) => {
            setTimeout(() => {
                item.insertText = "resolved text";
                item.documentation = "resolved documenration";
                resolve(item);
            }, 500)
        });
        
        return promise;
    }
});

monaco.editor.create(document.getElementById('container'), {
	value: '',
	language: 'json'
});
```

### Actual Behavior

The first time the "example" snippet is used, an error is logged to the console.
Trying again after 500ms results in "resolved text" being inserted.

### Expected Behavior

I expected Monaco to not try to action the completion item until it has been resolved.

### Additional Context

It appears that `resolveCompletionItem` is only applicable to `documentation` and `detail`?

If this is intentional, is there any way to asynchronously resolve a snippet? I have a long list of snippets and ideally only want to populate them when they're used.

**Comment by jrieken** [comment]
> I expected Monaco to not try to action the completion item until it has been resolved.

We cannot do that. Accepting a completion is synchronous and "normal typing" must complete after that independent of an unresolve resolve completion item

The applied logic is explained here: https://github.com/microsoft/vscode/blob/17ed7bf82c385b9b29a458109c6d6a76049856c7/src/vscode-dts/vscode.d.ts#L4358-L4376
