### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by monopollly** [Microsoft/monaco-editor#295]
monaco-editor npm version: 0.X.Y
Browser: safari
OS: mac

I am newbie in js
I open json file in editor and want to save changes... 
how I can get editor value for save it to file, which variable I need?
thank you!

**Comment by krzychukula** [comment]
What you need is probably something like this:
```
editor.onDidChangeModelContent(function(event) {
      var value = editor.getValue();
});
```

Based on: https://github.com/superRaytin/react-monaco-editor/blob/master/src/index.js
