### ISSUE TITLE
[Feature Request] expose MarkdownRenderer as public api

### ISSUE THREAD

**Issue by ayroblu** [microsoft/monaco-editor#2954]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

It would be very useful to be able to render markdown outside of Monaco with the same library, handling syntax highlighting etc. As of now, to make a markdown previewer, we need to download and use another library, basically duplicating code with inconsistencies

**Comment by mjbvz** [comment]
Not a good idea IMO. Right now markdown rendering is something we can update freely without worrying about breaking plugins. Making it public api would not allow this

Shipping your own markdown renderer seems like the correct approach
