### ISSUE TITLE
[Bug] `getDocumentSymbols` is no longer accessible

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/monaco-editor#2959]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

In `monaco-editor` 0.32.0 `monaco-editor/esm/vs/editor/contrib/documentSymbols/documentSymbols.js` has been renamed to `monaco-editor/esm/vs/editor/contrib/documentSymbols/browser/documentSymbols.js` and `getDocumentSymbols()` no longer exists.

### Expected Behavior

In `monaco-editor` 0.31.0 it was possible to get document symbols using:

```ts
import { editor } from 'monaco-editor';
import { CancellationToken } from 'monaco-editor/esm/vs/base/common/cancellation';
import { getDocumentSymbols } from 'monaco-editor/esm/vs/editor/contrib/documentSymbols/documentSymbols';

const ed = editor.create(/* options */);

async function main() {
  const symbols = await getDocumentSymbols(ed.getModel(), false, CancellationToken.None);
}
```

### Additional Context

Because of #2450 it’s not clear if this is supposed to be part of the public API.

It’s used [here](https://github.com/remcohaszing/monaco-yaml/blob/main/examples/demo/src/index.ts#L176-L202) to create the breadcrumbs on https://monaco-yaml.js.org

**Comment by topliceanurazvan** [comment]
Seems like right now the `languageFeatures` is not found inside `common/services/` ... any help with this?

**Comment by remcohaszing** [comment]
It’s there for me using `monaco-editor` 0.34.1. Are you using 0.34.0? Did you delete it on accident?

**Comment by topliceanurazvan** [comment]
My bad, I was using 0.32.0 as I saw it mentioned in the first comment. Thank you @remcohaszing, looks like it's working right now! 🙌🏻
