### ISSUE TITLE
microsoft.github.io/monaco-editor's editing can't be escaped with keyboard

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/monaco-editor#296]
*(is this the right place to post issues about microsoft.github.io/monaco-editor?)*

On microsoft.github.io/monaco-editor, if you start typing in any of the editors, you can't make focus escape using only the keyboard. Since `tab` and `shift+tab` are taken by Monaco, perhaps `escape` (move focus away from the editor) and `f6` (section switching) should be implemented?

This is an accessibility problem.

**Comment by alexandrudima** [comment]
In any editor instance, you can press <kbd>Ctrl</kbd>+<kbd>M</kbd> to escape focus trapping.

**Comment by JoshuaKGoldberg** [comment]
@alexandrudima is that documented anywhere? Better, is that documented on the main site?
