### ISSUE TITLE
[Bug] Smoke test requires npm i in /webpack-plugin

### ISSUE THREAD

**Issue by luisscholl-at-software-ag** [microsoft/monaco-editor#2978]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

Need to run `npm i` in monaco-editor/webpack-plugin in order to be able to run smoke tests successfully.

### Expected Behavior

Be able to follow instructions in the [Contributing.md](https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md) to execute smoke tests.

**Comment by hediet** [comment]
`npm ci` is being used instead.
