### ISSUE TITLE
Programatcially get symbols

### ISSUE THREAD

**Issue by mi5ha** [Microsoft/monaco-editor#298]
Does anyone knows if its possible to programmatically get symbols of the current model? All classes, members, functions and their positions in the file?

Basically to use Monaco to tokenize code.

Thank you,
Misha

**Comment by alexandrudima** [comment]
with the upcoming `0.8.x`, there is a new API `monaco.editor.tokenize`:

```
    /**
     * Tokenize `text` using language `languageId`
     */
    export function tokenize(text: string, languageId: string): Token[][];
```

**Comment by mi5ha** [comment]
Awesome, thanx!
