### ISSUE TITLE
[Feature Request] Allow to register a language provider using a language selector instead of a single language

### ISSUE THREAD

**Issue by CGNonofr** [microsoft/monaco-editor#2985]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

all `register*Provider` methods in monaco.languages take a `languageId` as first parameter.

However, they are just calling the `register` method from `LanguageFeatureRegistry` which can take a whole `LanguageSelector` as parameter.

**Comment by hediet** [comment]
A reasonable feature request, thanks for also providing the PR. What is your use-case?
