### ISSUE TITLE
How to replace editor value and preserve undo stack?

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/monaco-editor#299]
Hi, I have added a "beautify" command to the editor for my java code.
The problem is that after I `setValue()` the undo stack is destroyed, I even tried to `setModel()` with the same result.

So how can I replace the value in the editor and preserve the undo actions?

**Comment by tomitrescak** [comment]
Just in case anyone stumbles on the same issue, I'm sure it can be handled more graciously, so I'll leave this open for now:

```
// remove breakpoints
oldDecorations = activeEditor.deltaDecorations(oldDecorations, []);

activeEditor.executeEdits('beautifier', [{ identifier: 'delete' as any, range: new monaco.Range(1, 1, 10000, 1), text: '', forceMoveMarkers: true }]);
activeEditor.executeEdits('beautifier', [{ identifier: 'insert' as any, range: new monaco.Range(1, 1, 1, 1), text: text, forceMoveMarkers: true }]);
activeEditor.setSelection(new monaco.Range(0, 0, 0, 0));
activeEditor.setPosition(currentPosition);
// activeEditor.executeEdits('beautifier', [{ identifier: 'movecursor' as any, range: new monaco.Range(currentPosition.lineNumber, currentPosition.column, currentPosition.lineNumber, currentPosition.column), text: '', forceMoveMarkers: false }]);

// add breakpoints
oldDecorations = activeEditor.deltaDecorations(oldDecorations, breakPoints);
```

**Comment by scgm11** [comment]
@tomitrescak dont you find slow when you have for example more than 1000 lines?

**Comment by tomitrescak** [comment]
Didn't have this problem as I'm not dealing with very large files. What can be done us to omit the delete line and do the insert with the same range as delete. That replaces the whole buffer as well.

**Comment by scgm11** [comment]
I did use only the replace but the write is slow for a large number of lines

**Comment by alexandrudima** [comment]
As @tomitrescak mentions,
[`editor.executeEdits`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#executeedits) (preferred if the model is attached to an editor) or [`model.pushEditOperations`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#pusheditoperations) (if the model is not attached to an editor) are good ways to do this.

**Comment by scniro** [comment]
@tomitrescak FWIW, I needed a beautify command as well. I piggy-backed off the VS Code Alt+Shift+F functionality of "format document" by running the following...

    editor['_actions']['editor.action.formatDocument']._run()

I might be overlooking a cleaner exposed API but this is giving me good results for now. Though I would be curious if any contributors know if there is a cleaner way to invoke this

**Comment by hamzahik** [comment]
@scniro try 

```javascript
editor.getAction('editor.action.formatDocument').run();
```

More info about the API on the [doc](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#getaction).
