### ISSUE TITLE
[Bug] #2650 is still present

### ISSUE THREAD

**Issue by firstdorsal** [microsoft/monaco-editor#2997]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

The Scrollbar and minimap cant be styled
#2650 is still present

### Expected Behavior

They should be styleable (especially as this cannot be overriden with css as it is a canvas element)

**Comment by hediet** [comment]
I reopenend the original bug report.
