### ISSUE TITLE
Html workers

### ISSUE THREAD

**Issue by gusdaud** [Microsoft/monaco-editor#3]
Hi, is html workers coming to this package ? 

I've managed to make they work by copying the missing files from the demo pages to the same folders in my project.

It did great except for inline css and javascript and script tags which didn't work.

**Comment by alexandrudima** [comment]
@gusdaud I am not sure what you mean. https://microsoft.github.io/monaco-editor/index.html uses the `monaco-editor` npm modules as it is shipped and has a HTML example:

![image](https://cloud.githubusercontent.com/assets/5047891/16194255/f894a20e-36f3-11e6-854f-299c761558a8.png)

Are you running your sample pages on a real protocol (such as `http` or `https`) or are you using the `file` protocol (the latter does not allow for web workers to be created).

> [1] Chrome and Opera give an error "Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///Path/to/worker.js' cannot be accessed from origin 'null'." when you try to run a worker locally. It needs to be on a proper domain.
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Browser_compatibility

**Comment by gusdaud** [comment]
Hey Alex. I'm running on http localhost and on google Chrome.

I've managed to make auto complete and other features provided by the workers to function by  manually copying some files to my project such as: 

\min\vs\languages\html\common\htmlWorker.js
\min\vs\languages\html\common\htmlWorker.nls.js
\min\vs\base\worker\workerMain.js

That didn't come when I NPM INSTALL Monaco.

(I had to debug the online samples to figure which files were missing)

**Comment by pierogitus** [comment]
It looks like https://microsoft.github.io/monaco-editor/index.html is running something different than what's in NPM. The variable for setting the cross origin worker path should be GlobalEnvironment, not MonacoEnvironment. See this commit https://github.com/Microsoft/vscode/commit/70072cbedb7326f5dbcd316464e9fc14931d4235

In the NPM code its using GlobalEnvironment as can be seen here https://npmcdn.com/monaco-editor@0.4.0/min/vs/editor/editor.main.js

**Comment by alexandrudima** [comment]
brought back in https://github.com/Microsoft/vscode/commit/50fabe9c15774f51a5389681e96df6b7478e7407

**Comment by mmendescortes** [comment]
> 
> 
> The sample code for running cross origin is wrong. The variable for setting the cross origin worker url should be GlobalEnvironment, not MonacoEnvironment. See this commit [Microsoft/vscode@70072cb](https://github.com/Microsoft/vscode/commit/70072cbedb7326f5dbcd316464e9fc14931d4235)

Nice! Fixed here!
