### ISSUE TITLE
Rename not available in monaco-typescript

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/monaco-editor#300]
@mhegazy

monaco-editor npm version: 0.7.0
Browser: Any
OS: Any

![image](https://cloud.githubusercontent.com/assets/972891/21372148/4fe98aea-c6ca-11e6-9f5c-402bdd2bb967.png)

**Comment by ulrichb** [comment]
Any chance to get this (and other refactorings / quick fixes) working in Monaco editor?

At the moment the "Ctrl+. infrastructure" (showing the menu, executing them and displaying errors) isn't available in Monaco editor, right?

**Comment by ulrichb** [comment]
@alexandrudima and @spahnke: Wow, this is really great! Many thanks!
