### ISSUE TITLE
[Feature Request] Add option to IMarkerData to grey out View Problems in the hover box

### ISSUE THREAD

**Issue by Ananya-Gupta24** [microsoft/monaco-editor#3000]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

**Problem** 
I am currently using setModelMarkers to squiggle out erroneous text. When I hover over the squiggle, there's a "View Problems" link at the bottom of the hover box. If I click on it, it renders the same error(s) from the hover box inside the editor. This becomes a UI issue when the size of the editor is small.

**Feature Request**
A boolean flag in IMarkerData that sets the visibility of "View Problems" and either makes it clickable or greys it out depending on the value.

**Additional Context**
- I am currently using deltaDecorations to not show "View Problems" but I can't replicate the experience I get with setModelMarkers without introducing additional state management
- In this stackoverflow post- https://stackoverflow.com/questions/57994101/show-quick-fix-for-an-error-in-monaco-editor, the dev uses setModelMarkers, but, for some reason the hover box doesn't have a "View Problems" link in it. How might this be achieved? If there is an existing mechanism to do that, this feature request would no longer be needed

**Comment by hediet** [comment]
Closing, as we discussed how this can be achieved by using deltaDecorations directly.
