### ISSUE TITLE
[Bug] `renderLineHighlightOnlyWhenFocus: true` does not work when leaving the editor with context menu open

### ISSUE THREAD

**Issue by FSDRE** [microsoft/monaco-editor#3009]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
    renderLineHighlightOnlyWhenFocus: true
});
```

### Actual Behavior

In the playground do the following steps with the above code running:

1. Click into editor in order to focus it (blinking cursor)
2. Click outside of the editor (browser address bar for example)
3. The cursor and line highlighting disappear in the editor (expected)
4. Focus editor again and click right in order to open the context menu
5. Now with the context menu open focus the browser address bar by clicking it

=> Cursor and line highlighting are shown despite the editor not having focus

### Expected Behavior

With `renderLineHighlightOnlyWhenFocus: true` the editor should never show the cursor or line highlighting if not focussed.

**Comment by hediet** [comment]
I cannot reproduce.

**Comment by FSDRE** [comment]
Can confirm that this actually got fixed somehow. There were changes regarding the context menu, so maybe someone deleted the right code line 😄
