### ISSUE TITLE
Mac keybindings

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/monaco-editor#301]
Monaco by default sets only windows key bindings, is it possible to simply rebind everything to mac when mac is detected?Thanks.

**Comment by alexandrudima** [comment]
@tomitrescak It should already do that. Do you think our platform detection code is somehow wrong?

**Comment by tomitrescak** [comment]
@alexandrudima well on my mac it work  only with ctrl and does not allow me to copy paste with cmd

**Comment by alexandrudima** [comment]
@tomitrescak Can you please be more specific? Do you mean `cmd+c` and `cmd+v` do not execute copy/paste for you on the mac. In what browser?

**Comment by tomitrescak** [comment]
Sorry, that would be all standard mac key bindings as cmd + v in Mac OS capitan in safari and chrome with the latest Monaco editor. If you ping me to os detection code that sets key bindings I can let you know what is happening

**Comment by alexandrudima** [comment]
@jrieken Can you please try copying/pasting in Safari and Chrome at https://microsoft.github.io/monaco-editor/

**Comment by jrieken** [comment]
Yeah, works

**Comment by alexandrudima** [comment]
@tomitrescak 

Do `cmd+c` or `cmd+v` work for other webpages for you? Do you perhaps have something custom on your system that would interfere with clipboard operations?

@jrieken just confirmed that this is not a general problem with the editor.

**Comment by tomitrescak** [comment]
I was working with 0.7.0, upgrading to 0.8.0 solved the problem. Thanks!
