### ISSUE TITLE
[Bug] Option `bracketPairColorization` does not work

### ISSUE THREAD

**Issue by FSDRE** [microsoft/monaco-editor#3013]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
    value: '(((()))){{{{}}}}[[[[]]]]',
    language: 'csharp',
    bracketPairColorization: {
        enabled: true
    }
});
```

### Actual Behavior

Bracket pair colorization does not work, no matter what language is set.

### Expected Behavior

Brackets being colorized

### Additional Context

I have tried languages: csharp, css, html, javascript

**Comment by eric183** [comment]
How about 'cpp', have you tried?
`var editor = monaco.editor.create(document.getElementById('container'), {
    value: '(((()))){{{{}}}}[[[[]]]]',
	language: 'cpp',

	lineNumbers: 'off',
	roundedSelection: false,
	scrollBeyondLastLine: false,
	readOnly: false,
	theme: 'vs-dark',
        bracketPairColorization: {
        enabled: true
    }
});`

**Comment by FSDRE** [comment]
It does not matter what language you specify, bracket colorization never works as far as I can tell.

**Comment by hediet** [comment]
This works, against the typing:
```ts

monaco.editor.create(document.getElementById('container'), {
    value: '(((()))){{{{}}}}[[[[]]]]',
    language: 'csharp',
    'bracketPairColorization.enabled': true,
});

```

This is definitely a bug though.

**Comment by FSDRE** [comment]
@hediet Confirmed! Is there a way to make this work via a typing extension for Typescipt? So I don't have to cast to `any`...

**Comment by cetinsert** [comment]
> This works, against the typing:

What is the typing!?

**Comment by hediet** [comment]
> What is the typing!?

I was referring to the typescript types.

**Comment by caramboleyo** [comment]
When i post it into the [playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options), the colored braces appear for a second, then they disappear again. Its like its rendered correctly and then immediately rerendered wrong.

**Comment by caramboleyo** [comment]
Also the matchBrackets functionality seems broken.

**Comment by IT-CASADO** [comment]
Same for me! 

bracketPairColorization and matchBrackets doesn't work at all :(

**Comment by ColinBradley** [comment]
Aye, bracketPairColorization and matchBrackets both don't work. Rolling back to 0.31.0 works fine

**Comment by caramboleyo** [comment]
@ColinBradley how did you roll back? git tags are not set for 0.31.0 or even 0.34.0

**Comment by mattgodbolt** [comment]
Also hit this (cc @jeremy-rifkin )

**Comment by hediet** [comment]
![image](https://user-images.githubusercontent.com/2931520/224659581-f86a4b87-47b4-4431-bc1e-cf0ba4260f66.png)

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAL8AAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscovwBTfVOOo4AuRGzYGy8DBvknaaXft9rWb1w8nFlXgKvv6gQ-8WWRoaJxf4YK1BpWeTgWlwgQ6ptrf92RgJkcqUajbS4XqzFrCLmx5_4QNJ_DBYNOj-yKrNBpQncSILkuwvv_ShU7Ckbk0xmZkfvpI28LzEsC64RngK1a5vZvIZ9fxSJikM-hHPX__94zwAA

Works now

**Comment by jeremy-rifkin** [comment]
Hi @hediet, shouldn't the bracket pairs be colored differently when `enabled` is `false`?

![image](https://user-images.githubusercontent.com/51220084/224781368-d861e183-1bf3-475e-874e-44781b1b3393.png)

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAL9AAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscoyOBTfVOOo4AuRGzYGy8DBvknaaXft9rWb1w8nFlXgKvv6gQ-8WWRoaJxf4YK1BpWeTgWlwgQ6ptrf92RgJkcqUajbS4XqzFrCLmx5_4QNJ_DBYNOj-yKrNBpQncSILkuwvv_ShU7Ckbk0xmZkfvpI28LzEsC634vuMIi_K1lRocBCleP79lIPgCzn_7CNEA

**Comment by hediet** [comment]
see https://github.com/microsoft/monaco-editor/issues/3829
