### ISSUE TITLE
[Bug] Why did monaco-editor getValue() return an unexpected length

### ISSUE THREAD

**Issue by eric183** [microsoft/monaco-editor#3014]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [x] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var value = `asfdasfsa\n\nasdfasdfasdfal;k l;'k \r\n \r\n  \r\n   k 'a\r\n  skd \r\n   a\r\n   d \r\n    \r\n     sas\r\n      dffa\r\n       sd\r\n         fsd\r\n          f\r\n          sfasfdasfasfdasdffasfaf\n\n          fa ljjflkajl\n\n          false\n\n\r\n\n          A\r\n          jpakfafafafaffaffaffafafewfwe\n          `;

console.log(value.length); // 280
var editor = monaco.editor.create(document.getElementById('container'), {
	value: value,
	language: 'javascript',

	lineNumbers: 'off',
	roundedSelection: false,
	scrollBeyondLastLine: false,
	readOnly: false,
	theme: 'vs-dark'
});

console.log(editor.getValue().length) // 290
```

### Actual Behavior

editor.getValue().length return  290

### Expected Behavior

editor.getValue().length return 280

### Additional Context

It might be a stupid question, but it has been bothering me for a long time and I still haven't found the answer

the getValue() method returns an unexpected result, I'm not sure if it's a bug.

Can somebody help answer this question ah, thank you so much~~

**Comment by hediet** [comment]
Can you compare the string values? I think the difference will be whitespace.

**Comment by eric183** [comment]
> Can you compare the string values? I think the difference will be whitespace.

Yes, I have already tried.

But it still didn't work.

Here is the screenshot

![image](https://user-images.githubusercontent.com/10773980/157278326-03db8c75-c0ed-4032-ad1e-d6a059041239.png)

**Comment by stefandobre** [comment]
All instances of `\n` become `\r\n`. `\r\n` remains `\r\n`.
Your initial value contains a mix of both `\n` and `\r\n`.

**Comment by eric183** [comment]
> All instances of `\n` become `\r\n`. `\r\n` remains `\r\n`. Your initial value contains a mix of both `\n` and `\r\n`.
> 
> ```
> initialValue: `asfdasfsa\n\nasdfasdfasdfal;k l;'k \r\n \r\n  \r\n   k 'a\r\n  skd \r\n   a\r\n   d \r\n    \r\n     sas\r\n      dffa\r\n       sd\r\n         fsd\r\n          f\r\n          sfasfdasfasfdasdffasfaf\n\n          fa ljjflkajl\n\n          false\n\n\r\n\n          A\r\n          jpakfafafafaffaffaffafafewfwe\n          `
> newValue:     `asfdasfsa\r\n\r\nasdfasdfasdfal;k l;'k \r\n \r\n  \r\n   k 'a\r\n  skd \r\n   a\r\n   d \r\n    \r\n     sas\r\n      dffa\r\n       sd\r\n         fsd\r\n          f\r\n          sfasfdasfasfdasdffasfaf\r\n\r\n          fa ljjflkajl\r\n\r\n          false\r\n\r\n\r\n\r\n          A\r\n          jpakfafafafaffaffaffafafewfwe\r\n          `
> ```

wow~

Thank you for your attention! 

I just called a method to value.replace(/\r/gm, '\n'), then its return value fixed!

Thank you for your big help again!!!
