### ISSUE TITLE
[Bug] Styling broken for Shadow DOM

### ISSUE THREAD

**Issue by philkunz** [microsoft/monaco-editor#3017]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
const template = document.createElement('template');
template.innerHTML = `
<style>
    #innercontainer {
        height: 100%;
    }
</style>
<div id="innercontainer">
  
</div>`;

class MonacoWC extends HTMLElement {
    constructor() {
        super();
        this.attachShadow({ mode: 'open' });
        this.shadowRoot.appendChild(template.content.cloneNode(true));
    }

    connectedCallback() {
        const innercontainer = this.shadowRoot.getElementById('innercontainer');
        monaco.editor.create(innercontainer, {
            value: "function hello() {\n\talert('Hello world!');\n}",
            language: 'javascript'
        });
    }

    render() {

    }
}
window.customElements.define('monaco-wc', MonacoWC);
const container = document.getElementById('container');
const wcEditor = document.createElement('monaco-wc');
container.append(wcEditor);

```

### Actual Behavior

editor is loaded, however styling is off. lines change order upon scrolling

### Expected Behavior

editor should load normally, woth scrolling not affecting lines order.

**Comment by hediet** [comment]
I marked this as question as we don't have the resources to investigate issues in third party source code.
Please provide a minimal example that is reproducible in the monaco editor playground.

**Comment by philkunz** [comment]
@hediet Please see the updated issue. I created a Playground example that shows the issue. Just replace the Javascript in the HelloWorld example. Thank you!

**Comment by hediet** [comment]
Thanks for the example! I can reproduce, it looks completely broken.

**Comment by cameronbraid** [comment]
I found a workaround : include the `monaco-editor/min/vs/editor/editor.main.css` styles in the shadow dom

**Comment by philkunz** [comment]
@cameronbraid nice, I confirm that this works.
Also I created a simple to use lit based web component, that works out of the box: https://gitlab.com/designestate/dees-editor 

Simply put the <dees-editor></dees-editor> component anywhere where you want to have a monaco editor.
The API will get more features over the next few days.

**Comment by hediet** [comment]
[Check out this example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAIFBAAAAAAAAABBqQkHQ5NjdYzqEXhNewrSKZslyM_G2I4bTkHQYW1lB1MplPA6z0speGDFvgRIQQx0HI9zdEFZdk3ipJqwzu6RT44vPXZPcpCKxnvgE9TYAtuAi9VQr3EAhbQJCn4JPD8EaFYCtRcYWa8_pnHjN-uDjxrhmN3g8tmx0iWUz1zF7VMROnGNjfHj2TFmcBooqFj0KG-T22ZTMhTuebWAKwtN_PzaTmIn83sxr9iG_rCToVGZ0s8Aqq4FCtsWBjMFVvarCcsgdWatYDG40I2zD8RTtWuNHNnY7c7IoNZIQlbLuUY6eiWdTFPiXUP1O8oaah0Csz8RlRcIa1l9lhCgWLmDqqOL08Y3F0K8dVIo69eyZtcffV2oBXpdc3VTcdsCp1Y898LUMwBEQMRkIvbz7CBuaqOSacXtrQdqhAqjekP8a0fHRClj00Ayniiid1DDyNpyEfu6SGdPfBH6LkLC5i7FXsHHUvO1GnCc1irro7YZl39IXXoeMqNUFgbEUptiN43oiqtTzYUtpRD_hLxuaVJ3UBWtHaMFjPD1kiQWekYju4V_l4LrUn6-kyOw7QUwiPlt7ljIjAAdnoanwDrlkEMdEUK0bYRb7stBpL36u_IfrqKwRX66TqjGZFKZjd4wpg9wQ_V08GvGVO_sZ-vV8jiQVjqz6p76A1HXqKVruW_iDZcR4kOjwCipGlD-wPPGPsb6tkJb7u1HivuQXwLwrFXSnGNcWqPpEkEj4QmkPJ7Q9vEEgKJzRf_uUJ3h).

You have to include the CSS in the web component.
