### ISSUE TITLE
[Bug] Sometimes banner gets removed from the editor.

### ISSUE THREAD

**Issue by swaprenge** [microsoft/monaco-editor#3018]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

We are using VueJs and tried to integrate the Monaco editor. When we set the banner to the original editor and modified editor, in some cases it gets removed from the modified editor.
I am attaching the screenshots and code snippets of the same.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/60922859/157800387-646ffce3-aa38-40d4-8e92-a39444a66959.png)
(While rendering the editor, the banner is set)

After mounting the editor, the banner disappears from the editor and is removed from the DOM.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/60922859/157800493-e18e7ee9-1a44-4e23-a82d-9935827c864f.png)

### Expected Behavior

The banner should be preserved always in both the editor. (original and modified)

### Additional Context

![set banner code](https://user-images.githubusercontent.com/60922859/157800741-7873609b-eeca-4efe-9e2c-2969d807dd0c.png)

This is a code snippet, we have written in Vue to set the banner for both the editors.

**Comment by hediet** [comment]
Does this reproduce without Vue?
