### ISSUE TITLE
[Bug] Setting `maxTokenizationLineLength` has no effect

### ISSUE THREAD

**Issue by jonatanklosko** [microsoft/monaco-editor#3025]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
  value: "[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]",
  language: 'javascript',
  maxTokenizationLineLength: 4,
});
```

### Actual Behavior

The line gets tokenized and highlighted.

**Note:** when hovering over the line it actually says that tokenization was skipped.

### Expected Behavior

Tokenization should be skipped.

### Additional Context

The default `maxTokenizationLineLength` value is `20_000`. When I paste a longer line into https://vscode.dev it isn't highlighted, however it gets highlighted in the Monaco playground.

Since Monaco handles highlighting separately, my guess would be that this option is not taken into account.

The on-hover messages is added [here](https://github.com/microsoft/vscode/blob/7104e8fcf43136054261575c8ec311e0238a8fbb/src/vs/editor/contrib/hover/browser/markdownHoverParticipant.ts#L75-L82) (for both Monaco and VSCode) and the TextMate tokenization is skipped [here](https://github.com/microsoft/vscode/blob/7104e8fcf43136054261575c8ec311e0238a8fbb/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L440-L443).

**Comment by Lazyuki** [comment]
This is causing `monaco-editor` to freeze up the entire UI for a few seconds making the browser unresponsive when it was tokenizing a log line containing 50k+ characters with a number of custom tokenizers that aren't cheap.
