### ISSUE TITLE
[Bug] Missing `model.onDidChangeContentFast` listener

### ISSUE THREAD

**Issue by Pranomvignesh** [microsoft/monaco-editor#3033]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

const instance = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

const model = instance.getModel()

model.onDidChangeContentFast(function(){}) // -> this throws error
```

### Actual Behavior

I have used the `onDidChangeContentFast` event of the editor model in [constrained editor plugin](https://github.com/Pranomvignesh/constrained-editor-plugin/blob/7384e0e480ab0dc478ad9f605a46af26dc2829e1/src/constrainedModel.js#L402) which attempts to solve this issue https://github.com/microsoft/monaco-editor/issues/953 

But in one of the recent commits in textModel.ts that events listener is removed. https://github.com/microsoft/vscode/commit/a9002ffa96ef08e709bd5a680f97923e3df5fc2a#diff-fc0b9cbcda54fc52f7f1eb424b1945ca6e6c81c73c0efc18c6b2e48ec7755b02L251 

### Screenshot of the error in monaco editor playground :

<img width="1680" alt="Screenshot 2022-03-23 at 2 58 55 PM" src="https://user-images.githubusercontent.com/29809906/159667207-a6799a81-8381-45b9-9413-94fb9027a037.png">

### Expected Behavior

I need an alternative for that listener. So, Is there any alternative for that listener exists? 

Can I replace onDidChangeContentFast with onDidChangeContent ? 

As onDidChangeContent uses **this._eventEmitter.slowEvent** and onDidChangeContentFast used **this._eventEmitter.fastEvent** , will it create any problem in my existing behaviour, if I replace those in my code?

### Additional Context

I would recommend the developers to add an **entry in the changelog** of monaco editor saying this event listener is **deprecated** / **removed.**
I searched for`ITextModel.onDidChangeContentFast` in the logs but couldn't find any of them.

_Note:  Although the source of the issue is from vscode repo's textModel.ts, I have checked Not reproducible in [vscode.dev](https://vscode.dev/) or VS Code Desktop, because an user using vscode won't face this issue, but an user using monaco editor will be facing these problems_

**Comment by hediet** [comment]
I think `onDidChangeContentFast` was not meant to be exposed as monaco API, it is an internal event. `Fast` just means that this event is called before the other one.
You should just use `onDidChangeContent`.

**Comment by Pranomvignesh** [comment]
Hi @hediet, Thanks for the clarification.
By convention, I have refrained from using the methods inside model instance starting with an underscore assuming those are internal methods.

but  `onDidChangeContentFast` didn't have underscore preceding it, so I thought that it was an exposed listener.

From now on, I will use `onDidChangeContent`
