### ISSUE TITLE
[Bug] Paste file to monaco editor

### ISSUE THREAD

**Issue by yangyangFE** [microsoft/monaco-editor#3037]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
All. It's a general question.
```

### Actual Behavior

First, copy a file. Then, paste to monaco editor, It can't paste file name to monaco editor.

### Expected Behavior

paste file name to monaco editor.

### Additional Context

First, copy a file. Then, paste to monaco editor, It can't paste file name to monaco editor.

**Comment by hediet** [comment]
I cannot reproduce - it works on Windows/Chrome.
