### ISSUE TITLE
[Feature Request] Mark a position between 2 characters

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#3039]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I often use markers to underline a part of code (e.g., to invite users to hover on it and see hints). Most of time, we want to underline at least one characters. But sometimes, we may want to underline the position between two characters. For instance, given a formula `fg(23,)`, I want to underline the position between `,` and `)`, then hovering on it shows `a non-empty argument is expected here`.

It seems that the following code in the [playground](https://microsoft.github.io/monaco-editor/playground.html) can achieve this more or less.

    var ed = monaco.editor.create(document.getElementById("container"), {
        value: "fg(23,)",
        language: "javascript"
    });
    
    monaco.editor.setModelMarkers(ed.getModel(), 'test', [{
        startLineNumber: 1,
        startColumn: 7,
        endLineNumber: 1,
        endColumn: 7,
        message: "a non-empty argument is expected here",
        severity: 8
    }])

However, setting `startColumn` same as `endColumn` does not always do the trick. For instance, I cannot underline the position between `(` and `2`; setting `startColumn: 4, endColumn: 4` does not work.

So does anyone know how to mark a position between 2 characters? We are not limited to underlining, other ways like highlighting are welcomed as well.

(* Link on StackOverflow: https://stackoverflow.com/questions/71617919 *)

**Comment by hediet** [comment]
I think the marker API highlights the entire word if its span was collapsed and contained in a word:
```ts
var ed = monaco.editor.create(document.getElementById("container"), {
    value: "fg(12345,)",
    language: "javascript"
});

monaco.editor.setModelMarkers(ed.getModel(), 'test', [{
    startLineNumber: 1,
    startColumn: 4,
    endLineNumber: 1,
    endColumn: 4,
    message: "a non-empty argument is expected here",
    severity: 8
}])
```

![image](https://user-images.githubusercontent.com/2931520/160167450-d707aedc-aa96-4781-8d84-1ac88889927f.png)


Maybe you can work around this by not using markers, but rather the decoration API directly.

**Comment by chengtie** [comment]
> decoration API

Thank you. I found [this sample](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations) and [IModelDecorationOptions](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IModelDecorationOptions.html). Could you tell me which element could be used to mark the position between 2 characters?

**Comment by chengtie** [comment]
Here is a working solution: https://stackoverflow.com/a/71667770/702977
