### ISSUE TITLE
[Feature Request] Allow semantic token provider access to editor state (cursor location)

### ISSUE THREAD

**Issue by paf31** [microsoft/monaco-editor#3044]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I am using the `SemanticTokenProvider` API and I would like to be able to use the current cursor location to influence semantic highlighting. Right now, the `SemanticTokenProvider` API does not have access to the editor state of the buffer being tokenized.

I can invalidate the semantic tokens when the cursor location changes by using `onDidChange` with `editor.onDidChangeCursorSelection`, but I can't read the current selection when the provider is invoked. My current workaround is to create one language per editor instance, and to pass the editor into the constructor of the semantic token provider, but this seems like a horrible hack and it would be much simpler if the `provideDocumentSemanticTokens` function could read the cursor position directly.

Possibly related SO question: https://stackoverflow.com/questions/69664000/monaco-editor-how-to-recompute-and-redraw-semantic-highlighting-data

**Comment by hediet** [comment]
This sounds like you should use the decoration API, not semantic tokens.

**Comment by hediet** [comment]
Maybe. SemanticTokenProvider's are not supposed to depend on the cursor position.
While it might work somehow, we don't support that scenario.
