### ISSUE TITLE
[Bug] SuggestController.onDidSelect fires only on mouse click

### ISSUE THREAD

**Issue by dluksza** [microsoft/monaco-editor#3046]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var editor = monaco.editor.create(document.getElementById('container'), {
	value: '"".',
	language: 'javascript'
});

var suggestControllerWidget = editor.getContribution('editor.contrib.suggestController').widget.value;

suggestControllerWidget.onDidSelect((a) => alert(a.index));
```

### Actual Behavior

Opening suggestions with `<ctrl>+<space>` and selecting an item with `<enter>` key do not triggers `onDidSelect` callback. But when suggested item is selected with mouse click the `onDidSelect` fires and shows the alert window.

### Expected Behavior

`onDidSelect` fires always when suggestion is chosen, no matter if that was using keyboard or mouse.

**Comment by jrieken** [comment]
Yes. Keyboard events aren't handled by widgets but by an outside services. Selecting an item or pressing the keybinding invoke a different function on the suggest controller

**Comment by dluksza** [comment]
@jrieken, thank you for a quick response. Do you know what would be the way of getting information about suggestion being selected using keyboard? I'm mostly interested in the index of selected option.

I've looked at `SuggestController` and couldn't find any API that would provide the selected option index.

**Comment by jrieken** [comment]
Yeah, there is no such API

**Comment by jrieken** [comment]
But if it's your completions you can use an completion item command to which item was inserted
