### ISSUE TITLE
Hex-Editor Support

### ISSUE THREAD

**Issue by fdeitelhoff** [microsoft/monaco-editor#305]
monaco-editor npm version: 0.0.7
Browser: Electron (Chromium)
OS: Windows

Is there support to use monaco as an hex editor? I want to display many hex values like

`4C 45 47 4F 44 00 00 00 68 00 03 00 00 00 00 00 `

I can change the line numbers to show offset values but is there support for more? Like column headings or something like that.

Did someone implement syntax highlighting for hex codes?

Thanks
Fabian

**Comment by egamma** [comment]
@fdeitelhoff (I understand that this isn't the monaco editor proper) but you might get some inspiration from this VS Code extension https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-hexdump

**Comment by fdeitelhoff** [comment]
@egamma Thanks for your help!

I'm using some JavaScript libraries right now to provide the functionality I need (see screenshot).
![simplex](https://cloud.githubusercontent.com/assets/1618135/22043073/450affa0-dd0e-11e6-86de-e5eee95ddfa4.png)

Especially the library "hexy" is very useful.

Is it possible to increase the left margin for the line numbers? As the screenshot shows I'm using only 6 digits right now but I want to use 8. I can try to change the CSS but I think I must adjust many more styles (for example for the complete content pane).

Maybe there's a faster/better solution.

**Comment by alexandrudima** [comment]
@fdeitelhoff You can use the [`lineNumbersMinChars`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#linenumbersminchars) option.

**Comment by fdeitelhoff** [comment]
@alexandrudima Thanks again. Working like a charm!
