### ISSUE TITLE
[Documentation] `IEditorOptions.automaticLayout` uses `ResizeObserver`

### ISSUE THREAD

**Issue by mhsdesign** [microsoft/monaco-editor#3051]
sorry, im no maintainer, but this concerns neither feature nor bug but documentation.... so i choose a freeform template ...

the api docs for `IEditorOptions.automaticLayout` say:
`Enable that the editor will install an interval to check if its container dom node size has changed.`
https://github.com/microsoft/monaco-editor/blob/290a62d/website/typedoc/monaco.d.ts#L2954

which sounded scary to me performance wise (also because the next line suggests so...) - it let me believe it might be using `setInterval` for browser compatibility ...

but i looked into the source:
https://github.com/microsoft/vscode/blob/93aad560e1190f81b456b09d0b05bca4382c1033/src/vs/editor/browser/config/elementSizeObserver.ts

its using a "performant" `ResizeObserver` and not `setInterval`

so i would change that line into:
`Enable that the editor will install a ResizeObserver to check if its container dom node size has changed.`

**Comment by hediet** [comment]
Thanks for your suggestion! Feel free to create a PR!
