### ISSUE TITLE
Is that possible to add any control like edit box inside editor

### ISSUE THREAD

**Issue by gvcode1** [microsoft/monaco-editor#3059]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

These added edit box actually flow with text inside the editor, but not over lay the text .

I am not sure whether it is possible, please help a little bit.

Thanks

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
