### ISSUE TITLE
Dynamically typed tokens

### ISSUE THREAD

**Issue by viridium** [Microsoft/monaco-editor#306]
Apologies; I don't know of a discussion forum for this baby.

How does one define languages for which the type of token depends on information supplied by the user externally to the editor?

Suppose I wanted to write English language. There's inherent ambiguity in English that a static language definition file (like Monarch) can't capture:

> We saw her duck.

For the above sentence, the user will need to provide missing information for the syntax to be disambiguated. How does one leverage Monaco to make something like this work?

Note that that externally-supplied information would have to be associated with the token for the duration of its lifetime.

**Comment by alexandrudima** [comment]
To colorize a programming language, you can use either Monarch or a hand-written tokenizer via [`setTokensProvider`](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#settokensprovider).

You can also use decorations ([on the model](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#deltadecorations) to get them show up in all editors displaying the model or [on the editor](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#deltadecorations) to get them show up only in the current editor instance).

There are examples for using decorations:
* https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin
* https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations

And you can find code examples for implementing a manual tokens provider:
* https://github.com/Microsoft/monaco-typescript/blob/master/src/tokenization.ts#L14

**Comment by viridium** [comment]
In my use case, the token types depend on more than the text itself. How does a tokenizer store and access the additional information in Monaco? Is there a way to associate information with a token that can be used in tokenization to compute the token's type? How does token identity work in such cases? Is editing allowed in the middle of the token? Does the token retain its associated information (really, its identity) when that happens?

**Comment by alexandrudima** [comment]
The tokens themselves are not meant to hold anything more than a string type and a start index.

Tokenization is meant to be a top-down process, with states saved between lines (usually to represent things such as multiline comments, multiline strings, etc.). It also assumes that it is only taking the text as the input (and a tokens provider is therefore invoked again when the text changes, etc.). I don't think what you're trying to do fits with this model. 

Perhaps you can resort then to decorations.

**Comment by viridium** [comment]
Sounds like the exact solution that they recommend in CodeMirror; there, they call them "text markings".

But this approach deals with the problem outside the syntax, which is wrong: whether a token is a verb or a noun is a matter of syntax. We're effectively invited to dumb down the tokenizer (return just WORD as token type) and handle the part-of-speech assignments downstream. We should allow tokenizers to be stateful and maybe even give them support in tokenizing smartly and remembering previously made choices, perhaps in the form of incremental tokenization, or information about their previous tokenization decisions.

That said, where can I read more about decorations? In particular, how does token identity work with decorations? If a decorated token is split in two by inserting a space, what happens to its decoration? What if the token is expanded? Are there callbacks for clients to decide the fate of the decoration in the face of such events?

**Comment by alexandrudima** [comment]
@viridium 

Did you go through the playground examples at https://microsoft.github.io/monaco-editor/playground.html

Did you go through the public API (either in its .d.ts form or in the generated doc at https://microsoft.github.io/monaco-editor/api/index.html)

I am happy to answer specific questions, but please take the time to read existing documentation first.
