### ISSUE TITLE
[Bug] bracket pair colorization has higher priority than semantic token provider

### ISSUE THREAD

**Issue by FSDRE** [microsoft/monaco-editor#3068]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
const regEx = new RegExp(/(\{\{bar\}\})/gu);

monaco.languages.registerDocumentSemanticTokensProvider('html', {
    getLegend: function () {
        return {
            tokenTypes: [
                'customToken'
            ]
        };
    },
    provideDocumentSemanticTokens: function (model, lastResultId, token) {
        const lines = model.getLinesContent();

        const data = [];

        let prevLine = 0;
        let prevChar = 0;

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];

            for (let match = null; match = regEx.exec(line);) {
                data.push(
                    i - prevLine,
                    prevLine === i ? match.index - prevChar : match.index,
                    match[0].length,
                    0,
                    0
                );

                prevLine = i;
                prevChar = match.index;
            }
        }
        return {
            data: new Uint32Array(data),
            resultId: null
        };
    },
    releaseDocumentSemanticTokens: function (resultId) { }
});

monaco.editor.defineTheme('html', {
    base: 'vs',
    inherit: true,
    colors: {},
    rules: [
        { token: 'customToken', foreground: 'ff0000' }
    ]
});

const editor = monaco.editor.create(document.getElementById('container'), {
    value: [
        'foo {{bar}} foo'
    ].join('\n'),
    language: 'html',
    theme: 'html',
    'bracketPairColorization.enabled': true,
    'semanticHighlighting.enabled': true
});
```

### Actual Behavior

The brackets of `{{bar}}` get colorized by the internal bracketPairColorization option despite the fact that the semantic token provider says they should be red.

### Expected Behavior

The semantic token provider shoud be prioritized higher than bracket pair colorization and therefor `{{bar}}` should be completely red.

**Comment by hediet** [comment]
I'm very sure this also reproduces in VS Code, I think there actually is an issue for this already. If not, please create one in the VS Code repository!

Also, there are currently no plans to address this issue as this is caused by (bracket pair) decorations overriding (semantic) tokens.
