### ISSUE TITLE
[Bug] `editor.action.toggleHighContrast` overrides the user theme

### ISSUE THREAD

**Issue by CGNonofr** [microsoft/monaco-editor#3069]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
const editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

editor.getAction('editor.action.toggleHighContrast').run()
monaco.editor.setTheme('vs-dark')
editor.getAction('editor.action.toggleHighContrast').run()
```

### Actual Behavior

The resulting theme is the default light `vs` theme

### Expected Behavior

The resulting theme should be the `vs-dark` theme

### Additional Context

Some other related issues:
- When the high contrast mode is autodetected, there is no way to disable it
- If the theme is set while the high contrast mode is active, the high contrast mode is disabled
- It seems there is some code referring to a light HC theme, but it doesn't seem it can be used

**Comment by aeschli** [comment]
The toogle command should look at the current theme and toggle based on whether it is high contrast or not. I pushed a fix.

The IGlobalEditorOptions have an option `autoDetectHighContrast`.

We now also have a light HC light theme, but it's currently not yet used by the toggle command.

**Comment by CGNonofr** [comment]
Hi @aeschli, I think you are talking about https://github.com/microsoft/vscode/commit/176257ec89695ce97c2933385862b8e68fd8a94d. It probably fix the main issue indeed, but there is a few other issues related to it

What about my PR?

**Comment by aeschli** [comment]
Hi @CGNonofr, thanks for the PR, I didn't see it at the time when I pushed my fix.
IMO the base issue is now fixed in that the toggle action now looks at the current theme.
What your PR adds is awareness of the light HC theme. That would be great to have, so if you are interested on working on that (not just for the toggle action) that would be great. A separate new PR would be the preferred way.
