### ISSUE TITLE
Expose blur function or equivalent.

### ISSUE THREAD

**Issue by krzychukula** [Microsoft/monaco-editor#307]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Mac

What I want to do is to blur editor and invoke actions when user click outside of editor. Problem is that I would like to prevent anything else from happening. Basically the same way you would close modal window, but it's not so simple in my context. 

What would help me a lot is one of those:

1. Monaco can expose `blur()` function - that would be consistent with existing `editor.focus()`. I could blur editor myself but it's not the best solution.
2. When creating editor pass `clickOutsideAlwaysBlursEditor: true` that if set would catch clicks outside of editor or popups/suggestions etc and call `event.stopPropagation();`
3. Expose `onMouseUpOutside` and similar functions that I could use to reliably know when user clicked outside of editor and popup windows.

**Comment by alexandrudima** [comment]
@krzychukula 

I agree that 1. could be added, but it is trivial to implement on your side via `editor.isFocused()` and `document.activeElement.blur()`.

I'm sorry, but I don't understand neither 2 nor 3. The editor only listens on its dom node. The only case it adds a global mouse move listener is in the clicking + dragging case which is done to allow for behaviours similar to clicking + dragging in a `<textarea>`.

**Comment by krzychukula** [comment]
Thanks!

**Comment by DevidCIC** [comment]
In Angular 4 and TypeScript it is:

```typescript
if (document.activeElement instanceof HTMLElement) {
             document.activeElement.blur();
 }
```
