### ISSUE TITLE
cdn: https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/loader.js

### ISSUE THREAD

**Issue by mbana** [Microsoft/monaco-editor#309]
hi,

is it safe to link to these libraries directly?
if not, is there a cdn available that one could use?
i don't think a lot of people are going to be changing the src?

cheers,

**Comment by alexlur** [comment]
[This](https://unpkg.com/monaco-editor@0.7.0/min/vs/loader.js) one is.

**Comment by alexandrudima** [comment]
@alexlur thank you, I didn't know about that one, I can use it for the website.
