### ISSUE TITLE
[Bug] Keyboard  shortcut "⌘ /" interferes with the core Chrome/Firefox shortcuts

### ISSUE THREAD

**Issue by intoku** [microsoft/monaco-editor#3091]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

There is an issue with the behaviour of the keyboard shortcut on Mac. The "Comment / uncomment line* shortcut  ⌘ /". interferes with the core Chrome/Firefox keyboard shortcuts. When pressed (⌘ + Shift + /) the browser opens Help>Search dialogue from the menu in both browsers. 
Installing chrome shortcut extensions does not help, as they just disable those key combination.

### Expected Behavior

(⌘ + Shift + /) should comment/uncomment line, instead of opening browser menu.

**Comment by CGNonofr** [comment]
AFAIK, the default keybindings are designed for windows on a qwerty keyboard. I had the same issue as you on linux/firefox with ctrl+/.

There is a `KeyboardLayoutService` service in vscode which is responsible to transform the keybindings based on the OS and the keyboard layout, but unfortunately, this service is not present in Monaco.

One solution I can suggest is to use [@codingame/monaco-vscode-api](https://www.npmjs.com/package/@codingame/monaco-vscode-api) to put back the vscode services into monaco:

```typescript
import getKeybindingServiceOverride from 'vscode/service-override/keybindings'

monaco.editor.createEditor(domNode, options, {
   ...getKeybindingServiceOverride(),
})
```

It's maybe overkill, and I can't garantee it'll solve your issue but you can give it a try

⚠️ it only works with the ESM version of monaco editor

**Comment by alexdima** [comment]
There is not a lot we can do on our side. The browser eats up `⌘ + Shift + /` on macOS by default, therefore it cannot be used by websites. We don't have plans to find another alternative default keybinding here, but you can do so on your page via `monaco.editor.addKeybindingRule`
