### ISSUE TITLE
[Bug] unexcpected typing behavior on android browser

### ISSUE THREAD

**Issue by thewh1teagle** [microsoft/monaco-editor#3097]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
When I type from android browser, it sometimes not typing
```

### Actual Behavior

the cursor become sometimes blurry and when I type some character it just not type it

### Expected Behavior

when I type it will just type it so I can code fast from my mobile phone

**Comment by hediet** [comment]
The monaco editor is not supported on Android.
