### ISSUE TITLE
Any plans to add a showcase section to the repo README

### ISSUE THREAD

**Issue by terrchen** [microsoft/monaco-editor#31]
Hi,

Will there be any plans to include showcases for products/tools that uses the Monaco Editor?  I figure this would be a mutually beneficial for both parties since it provides advertisement for the creators and provides more examples for what you can do with the editor.

Cheers

**Comment by alexandrudima** [comment]
I think that's a good idea, also on the website. @egamma, thoughts?

**Comment by egamma** [comment]
I agree this is  a good idea.

**Comment by terrchen** [comment]
Great.  Also, if there are branding guidelines and recommended ways for providing attributions, you way want to make that easy to find in the README and/or website as well.  Right now, my tool just mentions that it uses the Monaco Editor in the bottom right hand corner, and provides a link to the Monaco Editor website.

https://gitsense.com/insight?c=bitbucket:gitsense/contexts:gs_contexts::default.ccf#b=github:Microsoft/monaco-editor:master::github:Microsoft/vscode:master&q=action:M&dr=72hours&dl=&dp=

Cheers

**Comment by MohammadYounes** [comment]
Just published the [playground](http://rtlcss.com/playground/) for [rtlcss](http://rtlcss.com) :smile:

**Comment by pierogitus** [comment]
Here's my web IDE using monaco http://run.primoca.com
Use the "fork this" link at the top to explore the internals.
