### ISSUE TITLE
_setText(newValue) function is not update on the editor.

### ISSUE THREAD

**Issue by powerumc** [Microsoft/monaco-editor#310]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Windows 10

I'm working to monaco editor adapter of ot.js.

If `monaco.editor.getModels()[0]._lines[lineIndex]._setText(newValue)`, `newValue` is not update on the editor (screen).
But, when I input some text on the keyboard on current position, it's update on the editor (screen).

**Comment by powerumc** [comment]
Self answer.
reference #192

**Comment by alexandrudima** [comment]
Accessing methods or fields that start with `_` will never do what you want (it is our internal guideline for private properties).
