### ISSUE TITLE
[Feature Request] model addaction

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#3104]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I noticed that when models in different languages are set, such as editor Right click setmodel() to display different actions But Addaction can only be added on the editor. I want to know what to do for  add different actions for different models on the same editor

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
