### ISSUE TITLE
[Bug] findNextMatch return null when search string contains '\r' (in windows)

### ISSUE THREAD

**Issue by yzsind** [microsoft/monaco-editor#3108]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

var editor=monaco.editor.create(document.getElementById('container'), {
	value: "a\r\nb",
	language: 'javascript'
});

--test1
var findMatch1=editor.getModel().findNextMatch('a\r\nb', (1, 1), false, false, null, false);
alert(findMatch1);//found null

--test2
var findMatch2=editor.getModel().findNextMatch('a\nb', (1, 1), false, false, null, false);
alert(findMatch2);//found object
```

### Actual Behavior

when s
findMatch1:null
findMatch2:found result

### Expected Behavior

findMatch1:found result
findMatch2:null

### Additional Context

When using Windows, newlines in editors always include \r\n

**Comment by hediet** [comment]
This is by design:
https://github.com/microsoft/vscode/issues/19225
