### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ChenGuanglin0924** [microsoft/monaco-editor#3109]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

I use monaco-editor with plugin `MonacoWebpackPlugin` the same as [sample](https://github.com/microsoft/monaco-editor/tree/main/samples/browser-esm-webpack-monaco-plugin), the difference is that i added the json schema. 
```
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
  validate: true,
  schemas: [
    {
      uri: 'xxx',
      schema: {...},
    },
  ],
});
```
So it doesn't work with the below error.
![image](https://user-images.githubusercontent.com/22443356/168969874-736433ab-0aff-497c-9721-df969d6af007.png)

**Comment by hediet** [comment]
I cannot find the string "RefreshReg" anywhere in our codebase...
Why would the json worker import keyCodes.js?
