### ISSUE TITLE
[Bug] Close parenthesis in warning message accidentally ends markdown link

### ISSUE THREAD

**Issue by arucil** [microsoft/monaco-editor#3115]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
function hello() {
	alert('Hello world)))))))）!');
}
```

### Actual Behavior

An ambiguous character warning will show at the penultimate close parenthesis, which reads `The character U+ff09 "）" could be confused with the character U+0029 ")", which is more common in source code. Adjust settings%22%2C%22notAmbiguousInLocales%22%3A%5B%22ja%22%2C%22zh-hant%22%5D%7D%2C%22inComment%22%3Afalse%2C%22inString%22%3Atrue%7D)`. As you can see, some weird text is shown after the `Adjust settings` button. This problem is caused by a close parenthesis in the warning message accidentally ending the markdown link, which is constructed at line 409 in `monaco-editor/esm/vs/editor/contrib/unicodeHighlighter/browser/unicodeHighlighter.js`:

```typescript
408 const contents = [{
409    value: `${reason} [${adjustSettings}](command:${ShowExcludeOptions.ID}?${encodeURIComponent(JSON.stringify(adjustSettingsArgs))})`,
410     isTrusted: true,
411 }];
412 result.push(new MarkdownHover(this, d.range, contents, index++));
```

`encodeURIComponent` doesn't escape parentheses in `adjustSettingsArgs`.

### Expected Behavior

close parentheses in `adjustSettingsArgs` are correctly escaped in the markdown text.

**Comment by hediet** [comment]
This is already fixed in VS Code. The bugfix will ship in the next monaco editor release. Thanks for reporting!
