### ISSUE TITLE
[Bug] Updating the editor value causes color flickering

### ISSUE THREAD

**Issue by javiercoll** [microsoft/monaco-editor#3119]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// Through the options literal, the behaviour of the editor can be easily customized.
// Here are a few examples of config options that can be passed to the editor.
// You can also call editor.updateOptions at any time to change the options.

var text = "// First line\nfunction hello() {\n\talert('Hello world!');\n}\n// Last line";
var editor = monaco.editor.create(document.getElementById('container'), {
	value: text,
	language: 'javascript',

	readOnly: true,
	theme: 'vs-dark'
});
var interval = setInterval(function() {
    text += text;
    editor.setValue(text);
}, 500)

setTimeout(function() {
    clearInterval(interval);
}, 10000)
```

### Actual Behavior

Each time the editor.setValue() method is called, the actual code in the edior flickers. More text causes longer flickers. 

### Expected Behavior

No flickering when calling the editor.setValue() method.

### Additional Context

I'm guessing it's due to the editor language being updated each time the editor.setValue() method is called.

**Comment by hediet** [comment]
This is because the text needs to be retokenized.

**Comment by javiercoll** [comment]
Thanks @hediet ,

What does 'the text needs to be retokenized' mean? It's something that has to be implemented in VSCode or something that can be handled in the editor instance?

Thanks!

**Comment by hediet** [comment]
It is done automatically, but asynchronously. Thus you see flickering. No way around it.

**Comment by javiercoll** [comment]
Sorry, I didn't get that last part. What do you mean with a more precise edit?

**Comment by hediet** [comment]
Don't replace the entire text, but use the `applyEdit` API (maybe it has a different name). Then you can specify a list of edits (each edit has a range to replace and a replace text).
The sum of all these ranges should be minimal.

**Comment by javiercoll** [comment]
I see, so the idea is to go line by line checking for changes and apply it only where needed. Makes sense and may work for my scenario. I think pushEditOperations will fit better: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ITextModel.html#pushEditOperations

Thanks again!

**Comment by javiercoll** [comment]
Working code for reference:

```
var text = "// First line\nfunction hello() {\n\talert('Hello world!');\n}\n// Last line";
for (var i = 0; i < 5; i++) {
    text += "\n" + text;
}

var editor = monaco.editor.create(document.getElementById('container'), {
	value: text,
	language: 'javascript',
	readOnly: true,
	theme: 'vs-dark'
});

setTimeout(function() {
    var model = editor.getModel();

    var operation = {
        forceMoveMarkers: true,
        identifier: "mychange",
        range: {
            startLineNumber: 1,
            endLineNumber: 1,
            startColumn: 1,
            endColumn: 1000,
        },
        text: "// This has been replaced on the fly"
    }

    model.applyEdits([operation])
}, 2500);
```
