### ISSUE TITLE
[Bug] :The selected character in the monaco editor cannot be deleted

### ISSUE THREAD

**Issue by JohnWang99** [microsoft/monaco-editor#3120]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

In React, the useState parameter is used to control the display of the monaco editor and another component. 
If another component is displayed first, when switching to the monaco editor, select the character in the monaco editor and press the Delete key, nothing happens.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/43070398/170472864-6a8ea098-042b-44b8-b66d-3dfae1ca807c.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/43070398/170473181-da0ec18f-fa20-4621-b3ba-11f0527c2cf4.png">

### Expected Behavior

It is expected that no matter how many sibling components there are, the monaco editor will display when displayed and function normally

**Comment by hediet** [comment]
Please reproduce this issue in the playground. We cannot help you otherwise.
