### ISSUE TITLE
[Bug] scrolling empty Editor when using paddingTop

### ISSUE THREAD

**Issue by tabydabi** [microsoft/monaco-editor#3124]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
<Editor
          options={{
           padding: { top: '16px' },
          }}
        />
```

### Actual Behavior

If you use a padding top, then the editor will scroll even when empty

### Expected Behavior

If you use a padding top, then the editor will scroll even when empty

### Additional Context

![image](https://user-images.githubusercontent.com/69752848/171383618-6bd52be1-aba6-4af0-a5e6-beb560a34557.png)

https://user-images.githubusercontent.com/69752848/171388516-998fa0f7-2db1-4ed0-8142-2b6a5608a2e0.mp4

**Comment by hediet** [comment]
This looks like a bug in vscode. Can you create the issue there?
