### ISSUE TITLE
Add onDidChangeModelMarkers to IEditor interface

### ISSUE THREAD

**Issue by gatesn** [microsoft/monaco-editor#313]
Similar methods such as setModelLanguage have emitters:

[setModelLanguage](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodellanguage)
[onDidChangeModelLanguage](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#ondidchangemodellanguage)

It would be useful to have the same for modelMarkers:

[setModelMarkers](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#setmodelmarkers)
onDidChangeModelMarkers

**Comment by gatesn** [comment]
Closed for https://github.com/Microsoft/vscode/issues/18465

**Comment by alexandrudima** [comment]
Let's keep the issue in the monaco-editor repository as it is about the standalone editor and has no impact on vscode.

**Comment by stoetti** [comment]
Will this feature be added some time?

**Comment by vorobeez** [comment]
@alexandrudima hello!
I would like to implement this feature. Can I start working on it?
