### ISSUE TITLE
[Bug] `Range` does not treat surrogate pairs as a single column

### ISSUE THREAD

**Issue by debevv** [microsoft/monaco-editor#3134]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var text = [
    'Latin text',
    'نص عربي',
    '𠀤𠀤中文文本',
].join('\n');

var editor = monaco.editor.create(document.getElementById('container'), {
    value: text
});

var decorations = editor.deltaDecorations(
	[],
	[
		{
			range: new monaco.Range(1, 1, 1, 2),
			options: { inlineClassName: 'redText' }
		},
        {
			range: new monaco.Range(2, 1, 2, 2),
			options: { inlineClassName: 'redText' }
		},
        {
			range: new monaco.Range(3, 1, 3, 2),
			options: { inlineClassName: 'redText' }
		},
	]
);
```

### Actual Behavior

The character in the first column of line 3, `𠀤`, is not being rendered in red like the characters in first columns of the other lines, even if the `redText` class is specified on the same range for all three lines.
![Screenshot from 2022-06-08 15-17-05](https://user-images.githubusercontent.com/8508972/172625998-3c14f53f-2fb4-4744-90fc-1e610a5df888.png)

### Expected Behavior

The `redText` class should be applied to the `𠀤` character, hence it should be rendered in red.

### Additional Context

I'm fairly new to the monaco API, and after reading the `Class Range` documentation I understood that the unit of a range, on the same line, is a column, which I suppose is also the unit of movement of the blinking cursor, which in turn (i guess) corresponds to a single rendered Unicode grapheme cluster.
So I would expect, given the same 1,2 range to all three lines, to see all their first characters (columns) in red.  

My suspect is that `Range` is not actually working with columns, but single UTF16 code units. For this reason the `𠀤` character, which is a surrogate pair (2 UTF16 code units), is not being included into the range.  

Specifying `1-3` as range does in fact make the first character red. `1-4` does not make the second `𠀤` red, `1-5` does. `1-6` makes the third character `中` red, which is made of a single code unit instead.

Are my assumptions correct? Or is this the intended behavior and I am missing something from the docs?

**Comment by hediet** [comment]
> My suspect is that Range is not actually working with columns, but single UTF16 code units. 

This is correct.

> Are my assumptions correct?

I think so.
