### ISSUE TITLE
ctx.isAutoWhitespaceCommand = true; it's should be move to configuration settings.

### ISSUE THREAD

**Issue by powerumc** [Microsoft/monaco-editor#314]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Windows 10

I'm working to ot.js monaco-adapter.js for real time collaboration.
there is defined the `ctx.isAutoWhitespaceCommand = true;` oneCursor.ts:1401 file.

when it set `false` value, not more occurred error in ot adapater.. (ot's baseLength not equals targetLength error)

So, I think `ctx.isAutoWhitespaceCommand` property should be move to editor configuration settings.

**Comment by alexandrudima** [comment]
`isAutoWhitespaceCommand` is a command specific option and cannot be an editor configuration setting. Is `ot.js` using model content change events to synchronize, those contain all changes executed on a model.
