### ISSUE TITLE
[Bug] editor.setValue crash in vue3 + vite

### ISSUE THREAD

**Issue by tjx666** [microsoft/monaco-editor#3154]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

When I call setValue, the web page crashed and not responsed.

OS: MacOS12.4
Browser: chrome102

### Expected Behavior

I can set the content of editor by call editor.setValue(newContent).

### Additional Context

Reproduce:

1. gir clone `git@github.com:tjx666/vue-vite-monaco-issue.git`
2. `pnpm install`
3. `pnpm start`
4. open `http://localhost:3000`,
5. page will crash after 3 seconds

core code:

```typescript
const editorContainer = ref<HTMLDivElement | null>(null);
const editor = ref<Editor | null>(null);

onMounted(() => {
    editor.value = monaco.editor.create(editorContainer.value!, {
        value: source.value,
        language: language.value,
        theme: 'vs-dark',
        minimap: {
            enabled: false,
        },
    });
});

watch(source, (newSource, oldSource) => {
    if (newSource !== oldSource) {
        console.log('change value');
        editor.value?.setValue(newSource);
    }
});
```

**Comment by tjx666** [comment]
@alexdima

**Comment by tjx666** [comment]
> Don’t let your editor instance be a reactive variable, but as an ordinary variable change const editor = ref<Editor | null>(null); to let editor:monaco.editor.IStandaloneCodeEditor|null = null

You are right!

**Comment by ma-x-x** [comment]
您好，我已经收到您的来件，我会尽快处理的。祝您工作生活愉快。                                              ——BastogneYu

**Comment by ma-x-x** [comment]
您好，我已经收到您的来件，我会尽快处理的。祝您工作生活愉快。                                              ——BastogneYu
