### ISSUE TITLE
Add setModeConfiguration to monaco.languages.typescript.javascriptDefaults

### ISSUE THREAD

**Issue by naptestdev** [microsoft/monaco-editor#3155]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I want to create a custom formatter using registerDocumentFormattingEditProvider

If I'm using HTML, is can use:
```javascript
const htmlDefaults = monaco.languages.html.htmlDefaults;
htmlDefaults.setModeConfiguration({
   ...htmlDefaults.modeConfiguration,
   documentFormattingEdits: false,
   documentRangeFormattingEdits: false,
});
```
to disable the default formatter.

But there isn't any option like that in monaco.languages.typescript.javascriptDefaults. Hope that you could add this option

**Comment by joecarl** [comment]
I think this can be closed now.
