### ISSUE TITLE
[Bug] onDidAttemptReadOnlyEdit is not triggered by commands that edit

### ISSUE THREAD

**Issue by the21st** [microsoft/monaco-editor#3159]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

const editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript',
    readOnly: true
});

editor.onDidAttemptReadOnlyEdit(() => alert("onDidAttemptReadOnlyEdit"))
```

### Actual Behavior

Pressing Tab key or `cmd+/` to comment the current line doesn't trigger the browser alert.

### Expected Behavior

Pressing Tab key or `cmd+/` to comment the current line should trigger the browser alert.

### Additional Context

N/A

**Comment by hediet** [comment]
At least the command does not show in the command palette anymore.
Probably that's also the reason why the keybinding doesn't do anything, because it is conditionally.
Then it is not possible to show a warning.

But I think this issue also applies to VS Code.

**Comment by the21st** [comment]
@hediet thanks for the explanation. I understand your rationale for the `cmd+/` command, but pressing tab to add indentation to the code is not a command, is it? That's typing the `\t` character.

As for your recommendation to open an issue in VS Code, how do I provide a reproduction for this if I first need to set up monaco's `onDidAttemptReadOnlyEdit` ?

**Comment by hediet** [comment]
I think pressing tab invokes a command actually.

> As for your recommendation to open an issue in VS Code, how do I provide a reproduction for this if I first need to set up monaco's onDidAttemptReadOnlyEdit ?

VS Code shows a read only message when trying to write to read only documents (e.g. default keyboard shortcuts).
