### ISSUE TITLE
TypeScript/EcmaScript tokenization classes for function names, variables and accessors

### ISSUE THREAD

**Issue by grovesNL** [Microsoft/monaco-editor#316]
In the tokenizer for TypeScript/EcmaScript, it would be very useful for styling if we could identify function names, variables and accessors with CSS classes like VS Code does. Currently it's difficult to style function names, variables and accessors because they're indistinguishable between other identifiers.

i.e. I would like to style `test`, `canvas` and `width` differently in the text below:
`function test() { canvas.width = 300; }`

I'd be happy to help out with this if a convention could be agreed upon and if somebody could guide me in updating [tokenization.ts](https://github.com/Microsoft/monaco-typescript/blob/master/src/tokenization.ts)

**Comment by alexandrudima** [comment]
TypeScript and JavaScript tokenization are today implemented by using the TypeScript lexer API (the same that TypeScript uses to parse TS/JS code).

I do not think the TypeScript team would want to enhance their lexer.

You could implement a custom colorizer in [Monarch](https://microsoft.github.io/monaco-editor/monarch.html) from scratch (it is not that hard) and use that instead of the one we ship with. VS Code uses a TextMate grammar for TypeScript.

**Comment by grovesNL** [comment]
@alexandrudima: I think the lexer and tokenizer already recognize those tokens, but don't receive specific CSS classes so they can't be styled in custom themes.

To clarify I'm talking about the CSS class assignment at the [bottom of tokenization.ts](https://github.com/Microsoft/monaco-typescript/blob/master/src/tokenization.ts#L123). It appears the standard Monarch token CSS classes (i.e. those listed under [Creating a tokenizer](https://microsoft.github.io/monaco-editor/monarch.html)) don't uniquely identify those tokens, so I can't style them differently without creating my own Monarch definition as you mentioned. I'm wondering whether we can add more 'standard' CSS classes to Monarch to be closer to VS Code styling.

As an example, consider the default Monaco style and VS Code styles:

![image](https://cloud.githubusercontent.com/assets/2113872/22034324/2d0ff906-dca9-11e6-866e-4caca029d791.png)

The VS Code styling is much richer, but as I understand it, most of these tokens are already parsed by the same tokenizer. The only restriction is that specific CSS classes aren't being applied in Monaco.

**Comment by alexandrudima** [comment]
Tokens Providers are expected to go from the top of the file, line-by-line, tokenize, and potentially save some state at the end of the line (e.g. in multiline comment, in multiline string, etc.). Both Monarch and manual tokens providers must abide by this limitation. The idea is that tokenization should be very fast and predictable in the sense that changing a line will result most of the time in only that line getting different tokens and sometimes in the lines below getting new tokens (the insertion of a /* for example), but never in the lines above getting different tokens. 

I think I understand what you want. You can implement that quite straight-forward by:
1. register a model change listener
2. use the TS API to create an AST over the model text
3. walk the TS AST and collect certain ranges (such as type names, etc.)
4. add decorations to the model based on those ranges.

Preferably, you would execute steps 2 and 3 asynchronously, on a web worker (to not block/freeze the UI) and would check that the model did not change in the meantime via model.getVersionId() or by cancelling/debouncing your requests on subsequent edits, etc.

There are 2 or 3 samples involving decorations in the editor playground.

**Comment by grovesNL** [comment]
@alexandrudima: This is super useful information! Thanks for all the help.

Definitely agreed on tokenization speed. In my case the code samples will be extremely small, so I'd like to supplement the formatting with some extra AST information where possible. I will check out the samples and try out the approach you mentioned.
