### ISSUE TITLE
[Feature Request] can i change the theme of suggestions part, such as the color

### ISSUE THREAD

**Issue by jelly-shang** [microsoft/monaco-editor#3167]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

can i change the theme of suggestions part, such as the color

**Comment by favorite58** [comment]
我碰到这个问题了，一个页面上有两个编辑器，希望设置不同的主题，但是目前主题配置是全局的，希望能支持主题单独设置
