### ISSUE TITLE
[Bug] Tooltip use pageX/pageY for tooltip instead of clientX/clientY

### ISSUE THREAD

**Issue by TNtube** [microsoft/monaco-editor#3168]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

Actual behavior :
![image](https://user-images.githubusercontent.com/51389578/176449638-bbc306db-408a-4b95-8a74-97514866fbff.png)

### Expected Behavior

Expected behavior for this :
![image](https://user-images.githubusercontent.com/51389578/176449553-f9f04325-b5af-4d1a-a2a8-c70ef1fd8bbf.png)

### Additional Context

I'm writting a tool using monaco, and for the tools purposes, my pageX/pageY are far different than my clientX/clientY with my mouse (the page is scrolled on the X and Y axis). The issues is that when I'm hovering a syntax highlight, the corresponding tooltip appear on my screen at the page coordinates, and not the client.

**Comment by TNtube** [comment]
Update: reproductible in the monaco editor playground

![image](https://user-images.githubusercontent.com/51389578/177747543-2c1aa3b7-2787-44c5-8e41-11d6b02b75fc.png)

**Comment by hediet** [comment]
Can you share the code of the reproduction example?

**Comment by TNtube** [comment]
I already shared it above. I just edited the style property on the `Completion Provider Example` in the monaco editor playground like in the screenshot above

**Comment by hediet** [comment]
I mean in a way that I can copy the code. You just shared a screenshot.

**Comment by TNtube** [comment]
Oh okay. 
Here you go : 
```html
<div id="container" style="position: fixed; left: 500px; height: 100%; width: 50%"></div>
```
In the HTML section of the `Completion provider example` of monaco editor playground

**Comment by hediet** [comment]
Seems to work for me:

![image](https://user-images.githubusercontent.com/2931520/179974296-86dc1083-06c7-44a4-8f7a-1206a54c3568.png)

![image](https://user-images.githubusercontent.com/2931520/179974316-0ac382e4-5bbc-492a-8e81-8191ef04499d.png)

**Comment by TNtube** [comment]
This is not the same example as mine 🤔
The bug is still [here](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) replacing the html section by the one given above
