### ISSUE TITLE
[Feature Request] Allow selecting monaco version on playground

### ISSUE THREAD

**Issue by Prinzhorn** [microsoft/monaco-editor#3169]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

For debugging and bisecting which version introduced a bug it would be really helpful if we could select the Monaco version in the playground. I'm very used to the Svelte REPL (https://svelte.dev/repl) where you can choose any Svelte version. This is incredibly valuable when tracking down bugs and making things reproducible after an update. With the current playground repros will break after a new release because now they don't repro the bug any longer on playground.

Let's say 0.32.0 introduced a bug which is still present. Now it repros on playground with 0.33.0 as well. However, I would like to quickly switch to 0.31.1 to make sure my minimal repro does exactly what I intend and that it actually works with 0.31.1. Setting things up locally turns this from seconds into minutes. So instead of setting up a local demo and then stopping bundler, editing package.json, `npm install`, starting bundler, waiting, refresh browser I can just change the version on the playground.

**Comment by hediet** [comment]
Work in progress:

![recording](https://user-images.githubusercontent.com/2931520/181610970-83ce2f71-1332-43bf-8ceb-b0ae7573e183.gif)

The CDN is slow for uncached versions though.

**Comment by Prinzhorn** [comment]
Nice!

> The CDN is slow for uncached versions though.

If the current default use-case (most recent version) doesn't regress, I don't see a problem. If there's a spinner after selecting a different version then that's just the way it is :shrug: 

Pls make `?version=` or similar select the version as well and bi-directionally change the URL via `replaceState`. So that we can have repo URLs that keep working.

**Comment by hediet** [comment]
Done. Urls look like this: https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#example-creating-the-editor-hello-world

Also, there are launch configs for both the monaco-editor and the vscode repository to run the monaco editor in the playground from sources.

There is also a bisect feature to find the first of the monaco editor where some feature breaks.

**Comment by Prinzhorn** [comment]
Nice work!
