### ISSUE TITLE
sql书写区域，sql下拉框展示空白 

### ISSUE THREAD

**Issue by mrcluo** [microsoft/monaco-editor#3175]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

**技术栈**
主应用： qiankun + vue
子应用:   qiankun + datart

**场景：**
本地打开项目，展示是正常的
发布到线上环境，sql的下拉框展示空白，但是是可以点击的。功能正常，只是ui不展示。如下图

[
![image](https://user-images.githubusercontent.com/40492120/177079916-7ac7800e-0a52-4e52-82af-e3702515e7c2.png)
](url)

**尝试解决：**
控制台没有报错提示

**感谢大佬，期望翻牌**

**Comment by modou15** [comment]
问题解决了么，我也遇到了同样的问题，但是搜遍全网都没找到答案

**Comment by hediet** [comment]
Unfortunately, we only accept issues in English. Please create a new issue in English.
However, your screenshot does not seem to be related to the monaco editor.
