### ISSUE TITLE
[Bug] monaco editor word-break problem when set wordWrap 'on'

### ISSUE THREAD

**Issue by Albert-cord** [microsoft/monaco-editor#3177]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.
// add word or char behide 文章, their behavior is weird.
monaco.editor.create(document.getElementById('container'), {
    value: "测试文章1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111",
    wordWrap: 'on'
});
```

### Actual Behavior

word break at character and numbers, ah, it is difficult to discribe in word, I add a video to discribe it

https://user-images.githubusercontent.com/31922224/177363485-161e4fe7-0e55-41c4-b36e-f9f18456dd1d.mp4

.

### Expected Behavior

not to break word, wanna wrap line just  when word overflow viewport.

**Comment by hediet** [comment]
> * [ ]  Not reproducible in vscode.dev or VS Code Desktop

Please create the issue in the vscode repository in this case.
