### ISSUE TITLE
Dispose Worker

### ISSUE THREAD

**Issue by meriturva** [Microsoft/monaco-editor#318]
monaco-editor npm version: 0.7.0
Browser: Chrome
OS: Windows

We are integrating monaco editor into an angular 2 component and we have to create and destroy monaco editor every time component is created and destroyed.
Main problem is that we call:
```
public ngOnDestroy() {
        if (this.typescriptExtraLibs !== null) {
            this.typescriptExtraLibs.forEach(model => model.dispose());
        }

        if (this.codeEditor) {
            this.codeEditor.getModel().dispose();
            this.codeEditor.dispose();
        }
    }
```
but worker still present:
![worker](https://cloud.githubusercontent.com/assets/5664195/21993981/c5ff0008-dc1d-11e6-9a9f-e8284d356270.PNG)

We just would like to know how to correctly dispose all workers.
So thanks.
Diego

**Comment by alexandrudima** [comment]
The `editorWorkerService` worker will kill itself after 5 minutes of inactivity.

We could shut it down when no more code editor instances are alive.

**Comment by meriturva** [comment]
Thanks @alexandrudima !
Any way to expose methods to permit dispose programmatically?

**Comment by alexandrudima** [comment]
That is possible for workers created via `monaco.editor.createWebWorker`. This web worker is created by the editor to provide basic functionality such as word completions, diffing, link detection, etc. It is therefore considered implementation detail and is now correctly disposed when there are no more alive models. As mentioned, it is also disposing itself after 5 minutes of inactivity.

**Comment by mohamedmansour** [comment]
@alexandrudima  I am getting the same issue after I dispose right away:
```
    at Renderer.disposeTemplate (editor.main.js:102769)
    at PipelineRenderer.disposeTemplate (editor.main.js:24341)
    at editor.main.js:16068
    at Map.forEach (<anonymous>)
    at RowCache.garbageCollect (editor.main.js:16064)
    at RowCache.dispose (editor.main.js:16076)
    at editor.main.js:4023
    at Array.forEach (<anonymous>)
    at Object.dispose (editor.main.js:4023)
    at ListView.dispose (editor.main.js:23703)
```

I am doing the following:


```
    ngOnDestroy() {
        if (this._editor) {
            this._editor.getModel().dispose();
            this._editor.dispose();
        }
    }
```
