### ISSUE TITLE
[Bug] multi editor and different themes causes color flickering

### ISSUE THREAD

**Issue by FoSuCloud** [microsoft/monaco-editor#3181]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
Create 200 editors and have two different themes
I use requestIdleCallBack to create editors one by one
When I create an editor with a different theme from the current one, the content of the previous editor will change and black text will flash
```

### Actual Behavior

dom.runAtThisOrScheduleAtNextAnimationFrame(this._onRenderScheduled.bind(this), 100)

_consumeViewEventQueue:16
listener ViewTokensColorsChangedEvent cause flickering

### Expected Behavior

no flickering
Now I can solve the problem of flicker by using the same theme for these 200 editors

### Additional Context

monaco-editor： 0.30.1

**Comment by hediet** [comment]
This is a duplicate. It is not supported to have two different editors with different themes.
