### ISSUE TITLE
[Question] Include only fetch in globalThis

### ISSUE THREAD

**Issue by Satont** [microsoft/monaco-editor#3183]
Yes, i'm already asked this question at [stackoverflow](https://stackoverflow.com/questions/72758331/include-only-fetch-in-globalthis), left 2 weeks, i still doesnt get the any help. 

How to include only `fetch` autocomplitions for typescript in monaco editor?
Tried to set it up for hours, but it never worked.

**Comment by hediet** [comment]
I suggest to add more details to your question on stackoverflow!

Unfortunately, we don't have the resources to research/answer questions.
