### ISSUE TITLE
[Feature Request] Align with another line to bring the diff back in sync

### ISSUE THREAD

**Issue by jussen** [microsoft/monaco-editor#3188]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

The result of the comparer is sometimes insufficient. 

In some cases we have an additional and similar code block on one file which leads to the issue that the similar content will be compared and it will not be recognized as additional block. This leads to a diff which is out of sync.

Another case is a differentiation of the order of the file content like shown below. 

For both cases I would like to have the option to select a line on each side and start the comparison again from that line. From my understanding this will sync the diff again.

We currently use Beyond Compare and the option "Align With" another line on the other file to achieve that. Our goal is to integration the Monaco Editor as a comparer in our software. 

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/32816888/178662815-f3e9d1c1-ccf6-41e4-af15-fc5ac62666ac.png">

**Comment by hediet** [comment]
Can you please create an issue in the VS Code repository?
Can you also share your example file?

We are currently investigating how we can improve the diffing/merging experience by tweaking the diffing algorithm. Your example file could be very useful.

**Comment by jussen** [comment]
Sure. Created.
