### ISSUE TITLE
Syntax validation for ECMAScript 5

### ISSUE THREAD

**Issue by martinhiller** [Microsoft/monaco-editor#319]
Does Monaco support syntax validation for ECMAScript 5 code?

My naive impression was that using `language: "javascript"` during editor creation and setting the ScriptTarget to ES5 would do the trick:

```javascript
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
	target: monaco.languages.typescript.ScriptTarget.ES5,
});

monaco.editor.create(document.getElementById("container"), {
	language: "javascript"
});
```

However, the editor still lets me use ES6 features and even Typescript-specific syntax (i.e., type annotations) without complaining. Am I just misunderstanding what these configuration options do?

**Comment by jrieken** [comment]
Yes, the `target` property determines only what environment you have access to, like `Map`, `Set` or `String.startsWith`. The syntax kind cannot be validated and our implementation doesn't allow for that. It should come from the outside using a linter
