### ISSUE TITLE
[Bug] 编辑器在qiankun中的微应用使用的时候，会出现无法加载worker的问题。此微应用单独使用的时候不会出现问题

### ISSUE THREAD

**Issue by jiaruifeng1** [microsoft/monaco-editor#3192]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

![image](https://user-images.githubusercontent.com/46318244/179215081-bbd2f544-8ccf-429c-a1b8-020e9694ebfc.png)

**Comment by hediet** [comment]
Please provide reproduction steps and fill out as much fields in the form as possible.
