### ISSUE TITLE
Manually execute "Format Code" action

### ISSUE THREAD

**Issue by MohammadYounes** [Microsoft/monaco-editor#32]
Is it possible to manually execute the "Format Code" action ? and How ?

Thanks!

**Comment by MohammadYounes** [comment]
Found it!

```js
editor.getAction('editor.action.format').run()
```

Thanks.

**Comment by risfeng** [comment]
I press your code and I'll make a mistake.
`editor.getAction('editor.action.format').run()`
The execution editor command should be like this：
- format doc
` editor.trigger(‘anyString’, 'editor.action.formatDocument');`
- selected char to lower case
`  editor.trigger(‘anyString’, 'editor.action.transformToLowercase');`

Like this command `editor.action.transformToLowercase` , You can search in the file `XX/editor/editor.main.js`
vs code online demo ：https://toolbag.online/home/index/online-vscode.html

**Comment by rart** [comment]
`editor.getAction('editor.action.formatDocument').run()` works for me.

**Comment by CoderPoet** [comment]
`editor.getAction('editor.action.format') ` return null

**Comment by squareCY** [comment]
@CoderPoet 
add this in your js:
let editor=monaco.editor.create(doc, {
            value: this.ngModel,
            language: 'sql',
            formatOnType: true//!important
        });
monaco.languages.registerDocumentFormattingEditProvider('sql', {
                provideDocumentFormattingEdits: function (model, options, token) {
                    return [
                        {
                            range: {
                                startLineNumber: 1,
                                startColumn: 1,
                                endLineNumber: 1,
                                endColumn: 1
                            },
                            text: 'a'
                        }
                    ];
                }
            });

**Comment by lmxx1234567** [comment]
editor.getAction('editor.action.formatDocument').run();
