### ISSUE TITLE
[Bug] Diff editor could not be calculated if long time no interact with the editor.

### ISSUE THREAD

**Issue by pvnamGit** [microsoft/monaco-editor#3201]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual (Problematic) Behavior

I created a diff editor to integrate with Git. Like `VSCode`, if there are any changes from the editor, the source control section will show diff editors. It works well.
![Screenshot from 2022-07-19 21-54-09](https://user-images.githubusercontent.com/105837512/179781318-6dbf5d1f-d4c9-40bf-8983-bdd59b52f55a.png)
But when I don't interact with the editor for a time, the editor does not detect diff value.
![Screenshot from 2022-07-19 22-11-08](https://user-images.githubusercontent.com/105837512/179785222-e16162d6-b5f7-4a60-ab60-460f5753f77a.png)

**Comment by hediet** [comment]
> But when I don't interact with the editor for a time, the editor does not detect diff value.

What do you mean with "long" time?

**Comment by pvnamGit** [comment]
I checked and realized that about 10 minutes, if I didn't interact with an editor, it can not be able to calculated the differences between original model and modified model. I have no idea why it shows two editor but does not calculate the difference.

**Comment by hediet** [comment]
I cannot verify. I left the tab open for 2 hours, and diffing still works.
