### ISSUE TITLE
First opening of error/warning widget causes uncaught JS error "Cannot read property 'heightInLines' of null

### ISSUE THREAD

**Issue by mattgodbolt** [Microsoft/monaco-editor#321]
monaco-editor npm version: 0.7.0
Browser: Google Chrome 55.0.2883.87 (Official Build) unknown (64-bit)
OS: 64-bit Linux Ubuntu 16.10

Pressing F8 to bring up the error widget gives the following javascript error:

```
TypeError: Cannot read property 'heightInLines' of null
    at t.e._relayout (zoneWidget.ts:298)
    at t._relayout (gotoError.ts:440)
    at gotoError.ts:400
    at n.Class.define.cancel.then (winjs.base.raw.js:1566)
...
```

This is trivially reproducible by:

* Visiting https://microsoft.github.io/monaco-editor/
* Typing something that is an error (e.g. "broken123") at the top of the document
* Pressing F8
* Checking the JS console output.

**Comment by mattgodbolt** [comment]
Confirmed on Firefox (OS and version as above); FF v50.1.0

**Comment by alexandrudima** [comment]
This NPE appears to be already fixed on master
