### ISSUE TITLE
style is overridden

### ISSUE THREAD

**Issue by lyp000119** [microsoft/monaco-editor#3212]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

![image](https://user-images.githubusercontent.com/32259371/180422186-d45ac878-a7ac-41fa-b0f5-dae7dbcf129b.png)
![image](https://user-images.githubusercontent.com/32259371/180422233-22e4e546-26c6-4cdf-93a1-2718d08cd9d0.png)
![image](https://user-images.githubusercontent.com/32259371/180422311-b35d4ede-7119-4fbd-abf3-c801acd0d491.png)
![image](https://user-images.githubusercontent.com/32259371/180423197-b98578b0-f917-4527-b673-66d777d8b145.png)
![image](https://user-images.githubusercontent.com/32259371/180423368-633443d0-b82d-4e39-82df-7625d35f061d.png)

### Actual (Problematic) Behavior

There are two editors on the same page, their themes are different, and the styles will be overwritten

### Expected Behavior

styles will not be overridden

### Additional Context

not

**Comment by hediet** [comment]
This is a duplicate, the problem has been reported before.

**Comment by lyp000119** [comment]
how to solve it, do you have a link?

**Comment by lyp000119** [comment]
@hubgit
