### ISSUE TITLE
[Bug] Editor dispose erroring in async.ts

### ISSUE THREAD

**Issue by kazepreaux** [microsoft/monaco-editor#3218]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

const mon = monaco.editor.create(document.getElementById('container'),  {
                autoClosingBrackets: "never",
                autoClosingQuotes: "never",
                automaticLayout: true, // severe performance impact, but avoiding CSS for now
                language: 'csharp',
                lineNumbers: "off",
                minimap: {
                    enabled: false,
                },
                renderValidationDecorations: "off",
                scrollbar: {
                    alwaysConsumeMouseWheel: false,
                },
                suggest: {
                    showStatusBar: true,
                    showWords: false, // There is a weird interaction between editors without this being set to false.
                    snippetsPreventQuickSuggestions: false,
                },
                theme: "vs",
                value: "22",
            });


mon.dispose();
```

### Reproduction Steps

Paste the code on the playground
Open a console and put a breakpoint in async.ts line 274 in the cancel() method:
```typescript
cancel(): void {
  this.cancelTimeout();
  
  if (this.completionPromise) {
	  if (this.doReject) {
		  this.doReject(new CancellationError());  // HERE
	  }
	  this.completionPromise = null;
  }
}
```
Press the Run button

It should hit the breakpoint

### Actual (Problematic) Behavior

The actual problem is that it would cause a memory leak, which we could see when testing

### Expected Behavior

The async dispose should happen correctly, not reject.

**Comment by hediet** [comment]
Can you elaborate why you think this causes a memory leak?

**Comment by kazepreaux** [comment]
Hi,

We use Monaco editor as part of one of our components written in AngularJS.

For every of our components, we add a tag onto the scope so that we can detect if anything is left over after destroying the scope.

Part as part of our destroy, we dispose of the monaco editor, however, when we run our tests, we find tags left over, with a promise help for async.js. How we do it is we run our tests, open de dev tools, perform a gc (click few the button), then perform a heap snapshot. We then search for tag, and find leftover tags. 

![image](https://user-images.githubusercontent.com/26405651/182184954-fd7c9dbb-f5bb-4691-b4d2-ad8642a66b0d.png)

I hope this helps.

Louis

**Comment by hediet** [comment]
Can you provide steps of how to reproduce the memory leak in the playground?

**Comment by kazepreaux** [comment]
I will spend some time on it and try to get the leak on the playground.
It might take some time hehe.
