### ISSUE TITLE
How to build against the next version?

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#323]
I would like to test our application against the next version (v.8.0.x). Could you consider to publish it, e.g with `next` tag?

**Comment by alexandrudima** [comment]
I just finished doing a pass through the issues, I plan to begin smoke testing and creating npm modules today. You can do this yourself (without npm publishing steps) following https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md. It would be helpful to know if that document is complete / good enough.
