### ISSUE TITLE
[Question] how can i show the execute query tips like graphql in vscode when selection changed

### ISSUE THREAD

**Issue by KamiC6238** [microsoft/monaco-editor#3234]
![image](https://user-images.githubusercontent.com/23523595/183557080-3ba455dc-a1a5-4885-aef1-6c688b3cee87.png)

I want to show the execute tips when selection changed in monaco-editor，but i dont know what api can be use for it.

**Comment by spahnke** [comment]
Those are codelenses. See https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registerCodeLensProvider and the example here https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example.

**Comment by KamiC6238** [comment]
> Those are codelenses. See https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registerCodeLensProvider and the example here https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example.

thanks a lot, its very helpful for me
