### ISSUE TITLE
[Feature Request] How to set the abc completion function of the code?

### ISSUE THREAD

**Issue by frontendWangqun** [microsoft/monaco-editor#3246]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

How to set the abc completion function of the code?
<img width="879" alt="image" src="https://user-images.githubusercontent.com/43572671/184589873-f8be3dc3-1aa6-4e64-9f41-eb5f4f7a6307.png">

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
