### ISSUE TITLE
Cannot scroll in IE11 using Surface Book touchpad

### ISSUE THREAD

**Issue by alexdima** [microsoft/monaco-editor#325]
on master. also on v0.7.x

**Comment by alexandrudima** [comment]
Seems to be a well known Edge issue. IE11/Edge do not fire wheel events when scrolling with two fingers on a Precision Touchpad:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/

**Comment by alexandrudima** [comment]
It appears that Edge has shipped something that would make it possible to listen to the Precision Touch Pad via pointer events. https://blogs.windows.com/msedgedev/2017/12/07/better-precision-touchpad-experience-ptp-pointer-events/

**Comment by alexdima** [comment]
The Monaco Editor is generated from the source code of VS Code and in order to improve VS Code we must be able to use modern browser features, like Flexbox, which has a number of bugs that we cannot workaround in IE11.

We have investigated the cost of fixing all the problems of IE11 and have decided to discontinue support for IE 11. The last Monaco Editor version that was tested on IE 11 is `0.18.1`.

Thank you for your understanding.
