### ISSUE TITLE
Can't find variable: Intl error on Safari

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/monaco-editor#327]
monaco-editor npm version: 0.8.0
Browser: Safari
OS: Mac

<img width="289" alt="screen shot 2017-01-19 at 11 23 30 am" src="https://cloud.githubusercontent.com/assets/16690124/22121672/caebe108-de39-11e6-9077-5bb6a7791261.png">

Repro: Visit https://microsoft.github.io/monaco-editor/playground.html on Safari

**Comment by alexandrudima** [comment]
Caused by #18539

@bpasero Can you please try running the editor in Safari, it appears `Intl` is not defined there.

**Comment by bpasero** [comment]
@alexandrudima I pushed a workaround, note that Intl is defined in Safari 10 (from 2014), so at some point we have to decide what we want to support on macOS.

**Comment by alexandrudima** [comment]
@bpasero Many thanks.

@microsoftsam What Safari version do you have?

**Comment by microsoftsam** [comment]
Safari Version 9.0.3

**Comment by microsoftsam** [comment]
Repro's on 9.1.2 as well. Looks like this has been fixed in the vscode repo. @alexandrudima is there going to be an 8.1 that will include this fix?

**Comment by alexandrudima** [comment]
@microsoftsam Yes, we are now in endgame and just did a test pass to uncover more bugs. 0.8.1 will come out, hopefully we can wrap it up at the end of this week.

**Comment by sandyarmstrong** [comment]
@bpasero @alexandrudima fwiw, this bug exists when using monaco-editor 0.8.0 in a webkit webview even on macOS 10.11 with Safari 10 installed. Hopefully monaco-editor will continue to support Safari 9 for the embedded scenario.
