### ISSUE TITLE
[Bug] 0.34.0: option matchBrackets doesn't work

### ISSUE THREAD

**Issue by ralder** [microsoft/monaco-editor#3280]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
  value: "function hello() {\n\talert('Hello world!');\n}",
  language: 'javascript',
  readOnly: false,
  theme: 'vs-dark',
  matchBrackets: 'always'
});
```

### Actual (Problematic) Behavior

The paired brackets are not highlighted

### Expected Behavior

The paired brackets are highlighted

### Additional Context

at previous version 0.33.0 it works by default

**Comment by liuyike98** [comment]
seem to me
