### ISSUE TITLE
[Bug] Model paths with windows drive letter cause error in Typescript Worker

### ISSUE THREAD

**Issue by mofux** [microsoft/monaco-editor#3281]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
const uri = monaco.Uri.file('c:\\test.js');
const model = monaco.editor.createModel('console.log("hi")', 'javascript', uri);
monaco.editor.create(document.getElementById('container'), { model });
```

### Reproduction Steps

Run the reproduction code in playground, then hover a keyword, e.g. `console` and inspect the error in the developer console: 

```
Uncaught Error: Could not find source file: 'file:///c%3A%5Ctest.js'.

Ve@../../../vs/language/typescript/tsWorker.js:256:8493
An@../../../vs/language/typescript/tsWorker.js:256:14561
getQuickInfoAtPosition@../../../vs/language/typescript/tsWorker.js:33956:3428
fmr@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:22:33695
_handleMessage@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:22:17684
handleMessage@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:22:17309
_handleRequestMessage@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:22:14120
_handleMessage@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:22:13570
handleMessage@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:22:13458
onmessage@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:22:17401
c/</</</self.onmessage@https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/base/worker/workerMain.js#javascript:12:431
```

### Actual (Problematic) Behavior

The error gets thrown, and the quick info will not show up. Other language features also seem to fail.

**Comment by mofux** [comment]
Duplicate of https://github.com/microsoft/monaco-editor/issues/1306

**Comment by mofux** [comment]
Actually, #1306 was fixed via https://github.com/microsoft/monaco-editor/pull/3057, this seems to be a different problem. I'm pretty sure this is a regression in a recent monaco version, as I believe this worked before...

Is there a way to load the playground with a different monaco-editor version, so I can test it?

**Comment by rroessler** [comment]
I have just encountered this issue as well. When setting model URI values with Windows drive letters causes the colon character to be encoded. This then results in the TypeScript worker failing to find the original source files.
