### ISSUE TITLE
Model Markers

### ISSUE THREAD

**Issue by fdeitelhoff** [Microsoft/monaco-editor#329]
monaco-editor npm version: 0.8.0
Browser: Chromium (Electron)
OS: Windows 10

I'm currently playing with model markers to display errors within monaco. For example with the following code:

`markers.push({code: "test2", source: "test",

    severity: monaco.Severity.Error,
    startColumn: error.column, endColumn: error.column+1,
    startLineNumber: error.line, endLineNumber: error.line,
    message: error.message});`

The problems I'm facing are:

- The source-property is displayed in the error view (F8). The code property is still missing.
- The message isn't wrapped at all. So the text get's cut off.

What are the code and source properties for and is there a way to format the message with newlines?

**Comment by jrieken** [comment]
Yes, that is the design. The message cannot be wrapped because compiler errors are often ASCII-arti'sh formatted and us adding line wrapping would break such formatting. We keep the request about showing error code in mind, this is the first time got such a request.
