### ISSUE TITLE
different javascript defaults base on uri match

### ISSUE THREAD

**Issue by npenin** [Microsoft/monaco-editor#33]
Hi Team,

I would like to know if (and how) this is possible to have 2 default libs sets (eg. one for client and one for server). The feature for 1 default libs set already exists in the playground (https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults), but I cannot see any way to do it with another libs set. The perfect feature would be to make an extra lib base on some criteria like uri match or function call. 

Thanks,
Nicolas

**Comment by jrieken** [comment]
Sorry, that isn't possible and there no plans to add support for 'projects'.
