### ISSUE TITLE
model.onDidChangeContent is what problems.

### ISSUE THREAD

**Issue by powerumc** [Microsoft/monaco-editor#330]
monaco-editor npm version: 0.8.0
Browser: Chrome
OS: MacOS Sierra

I'm working ot.js monaco editor adapater.

Step 1. Selection 3 line using mouse or keyboard.
Step 2. input Ctrl+/ for the comments.

![](https://content.screencast.com/users/POWERUMC/folders/Snagit/media/6be382a2-56d7-4141-84cb-eb2223c58ba8/2017-01-21_18-36-23.png)

I expected following's model.getValue()

1.
```js
function x() {
    console.log("Hello World");
// }
```

2.
```js
function x() {
//     console.log("Hello World");
// }
```

3.
```js
// function x() {
//     console.log("Hello World");
// }
```

So, ot.js monaco editor adapater's synchronization is breaks.
I think about this is the bug.

**Comment by alexandrudima** [comment]
@powerumc 

Here is what I have tried:
```js
let ed = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
ed.onDidChangeModelContent((e) => {
    console.log(JSON.stringify(e, null, '\t'));
});
```

And then I've selected the three lines and pressed <kbd>Ctrl</kbd>+<kbd>/</kbd>

Results:
```json
{
	"range": {
		"startLineNumber": 3,
		"startColumn": 1,
		"endLineNumber": 3,
		"endColumn": 1
	},
	"rangeLength": 0,
	"text": "// ",
	"eol": "\n",
	"versionId": 2,
	"isUndoing": false,
	"isRedoing": false
}
{
	"range": {
		"startLineNumber": 2,
		"startColumn": 1,
		"endLineNumber": 2,
		"endColumn": 1
	},
	"rangeLength": 0,
	"text": "// ",
	"eol": "\n",
	"versionId": 3,
	"isUndoing": false,
	"isRedoing": false
}
{
	"range": {
		"startLineNumber": 1,
		"startColumn": 1,
		"endLineNumber": 1,
		"endColumn": 1
	},
	"rangeLength": 0,
	"text": "// ",
	"eol": "\n",
	"versionId": 4,
	"isUndoing": false,
	"isRedoing": false
}
```

Explanation:

| Range | Content | Explanation
|---|---|---|
| <code>(3,1)->(3,1)</code> | <code>"// "</code> | Inserted <code>"// "</code> at position <code>(3,1)</code> |
| <code>(2,1)->(2,1)</code> | <code>"// "</code> | Inserted <code>"// "</code> at position <code>(2,1)</code> |
| <code>(1,1)->(1,1)</code> | <code>"// "</code> | Inserted <code>"// "</code> at position <code>(1,1)</code> |

**Comment by powerumc** [comment]
Hmm...
I dont need changed event values.
I need to obtain model.getValue().

That issue is occurred to all of multi line events.
(Multiline undo, redo, comments, Ctrl+d change, and etc...)
