### ISSUE TITLE
[Bug] Monaco themes leaks between more instances

### ISSUE THREAD

**Issue by vadimpopa** [microsoft/monaco-editor#3300]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});


// Register a new language
monaco.languages.register({ id: 'log' });

// Register a tokens provider for the language
monaco.languages.setMonarchTokensProvider('log', {
    tokenizer: {
        root: [
            [/(\[|\|)\s?ERROR\s?(\]|\|).*/, 'custom-error'],
            [/(\[|\|)\s?WARN\s?(\]|\|).*/, 'custom-warn'],
            [/(\[|\|)\s?INFO\s?(\]|\|).*/, 'custom-info'],
            [/^(\[|DS)[0-9- 0-9:,]+(\]|)/, 'custom-date'],
            [/^((?!ERROR|TRACE|DEBUG|WARN|INFO).)*$/, 'custom-error'],
        ],
    },
});

// Define a new theme that contains only rules that match this language
monaco.editor.defineTheme('logTheme', {
    base: 'vs',
    inherit: false, // IF I MAKE IT TRUE, THEN WORKS, BUT IT SHOULD WORK WITH FALSE AS WELL ?!
    colors: {},
    rules: [
        { token: 'custom-info', foreground: '228B22' },
        { token: 'custom-error', foreground: 'ff0000', fontStyle: 'bold' },
        { token: 'custom-warn', foreground: 'FFA500' },
        { token: 'custom-date', foreground: '008800' },
    ],
});


monaco.editor.create(document.getElementById('container1'), {
    value: "[2022-09-06 19:45:08] [ INFO] CaraWorkerProcessor.java:214 - processMethodQueueItem - Executing method cara_user_membership_sync.",
    language: 'log',
    theme: 'logTheme'
});
```

### Reproduction Steps

Notice in logTheme if I `inherit: true`, then both instances highlight the keywords accordingly. But it should work with false too I think, as logTheme doesn't need inheritance from 'vs'.

### Actual (Problematic) Behavior

Last instance's theme leaks into first instance and changes keyword highlights.
See screenshot

![Uploading Screenshot 2022-09-08 at 10.21.03.png…]()

### Expected Behavior

Instance's themes should affect the other instances. 
Should be like in screenshot.

<img width="782" alt="Screenshot 2022-09-08 at 10 24 05" src="https://user-images.githubusercontent.com/3592131/189060708-282babf7-d1d8-428c-9e7c-2a7ac9c3465b.png">

**Comment by hediet** [comment]
This is a duplicate. All editors share the same theme.
