### ISSUE TITLE
[Bug] Updating to v0.34.0 shows non-existent spaces or padding

### ISSUE THREAD

**Issue by szenzaro** [microsoft/monaco-editor#3310]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
	value: "test",
	fontFamily: "IFAOGrec",
});
```

### Reproduction Steps

1. define the font in css as

```
@font-face {
    font-family: "IFAOGrec";
    src: url(assets/fonts/IFAOGrec.woff2) format("woff2"), url(assets/fonts/IFAOGrecBold.woff2) format("woff2"),
        url(assets/fonts/IFAO-Grec-Exposant.woff2) format("woff2");
}
```

2. create an instance of the monaco editor

### Actual (Problematic) Behavior

Typing text adds some padding that moves the cursor away from the actual writing position.

![image](https://user-images.githubusercontent.com/4067028/189875778-adccc133-05aa-417e-b8aa-4686fcf108f0.png)
(there are no characters after the word "test")

### Expected Behavior

To have the cursor aligned with the writing position as usual

### Additional Context

This bahaviour appeared after updating to version 0.34.0 of the "monaco-editor" package. 
The previous version 0.33.0 had not such unexpected behaviour.

[IFAOGrec.zip](https://github.com/microsoft/monaco-editor/files/9556003/IFAOGrec.zip)
this is the font I used

**Comment by hediet** [comment]
I cannot reproduce.
Please make the example self contained, I cannot install fonts on my machine.
