### ISSUE TITLE
[Bug] SQL dialect does not work

### ISSUE THREAD

**Issue by nfiacco** [microsoft/monaco-editor#3311]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
	value: "",
	language: 'sql'
});
```

### Reproduction Steps

Simply type `select * from f` in the playground editor.

### Actual (Problematic) Behavior

The editor suggests "from" when you type the "f", which doesn't make sense. "Select" and "from" are not autosuggested.

### Expected Behavior

"Select" and "from" should be suggested, and table names (if provided) should be suggested after "from".

**Comment by Prinzhorn** [comment]
> The editor suggests "from" when you type the "f", which doesn't make sense.

You can disable it via `wordBasedSuggestions: false`

> "Select" and "from" should be suggested, and table names (if provided) should be suggested after "from".

This can be implemented using a `CompletionItemProvider`, it's nothing Monaco has built in

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.CompletionItemProvider.html

**Comment by nfiacco** [comment]
That makes sense, but shouldn't it work given that the SQL option is available?

**Comment by Prinzhorn** [comment]
This `language` option is for syntax highlighting https://microsoft.github.io/monaco-editor/monarch.html
Autocomplete is an entirely separate thing. You can't expect Monaco to ship with autocomplete support for every language and every SQL flavor.

From the website https://microsoft.github.io/monaco-editor/

![image](https://user-images.githubusercontent.com/679144/190845718-848ba0a5-1198-4a96-bbe0-4d42a94cf093.png)

**Comment by nfiacco** [comment]
That makes sense, I guess why is there any autocomplete whatsoever? Wouldn't it be better if it didn't suggest anything?

**Comment by rcjsuen** [comment]
> That makes sense, I guess why is there any autocomplete whatsoever? Wouldn't it be better if it didn't suggest anything?

Depends who you ask. I imagine there are users that like word-based suggestions which is why it is enabled by default.

**Comment by hediet** [comment]
This is out of scope.
