### ISSUE TITLE
How to access model tokens and their types?

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#332]
We make use of `ITokenizedModel.tokenIterator` internal API to access token types. After switching to v.8.0.x it seems to produce different results, e.g. `ITokenInfo.type` used to be the name of a type, now we get a number.

**Comment by alexandrudima** [comment]
The model no longer holds on to token types as strings, so it can't be used to get at a token type.

For each token it stores:
* language id
* foreground color
* background color
* font style: underline, bold, italics
* token type: one of regex, string, comment, other.

Please see the new API `monaco.editor.tokenize` for getting the token types as strings. This is explained in the CHANGELOG

**Comment by akosyakov** [comment]
@alexandrudima thx, I've ended up building my own API to iterate tokens on the top of `monaco.editor.tokenize` API.
