### ISSUE TITLE
[Bug] JSON schema field missing in suggestion dropdown

### ISSUE THREAD

**Issue by mesudip** [microsoft/monaco-editor#3339]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// Configures two JSON schemas, with references.

var jsonCode = ['{', '}'].join('\n');
var modelUri = monaco.Uri.parse('a://b/foo.json'); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, 'json', modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [
		{
			uri: 'http://myserver/foo-schema.json', // id of the first schema
			fileMatch: [modelUri.toString()], // associate with our model
			schema: {
				type: 'object',
				properties: {
                                        constructor: {type: "integer",required:true},
                                        fields: {
                                            type: "array",
                                            items: {
                                                type: "string",
                                            }, 
                                            required: true
                                        }
                                },
                                "additionalProperties": false,

			}
		},
	]
});

monaco.editor.create(document.getElementById('container'), {
	model: model
});
```

### Reproduction Steps

if you type `"` between the curly braces, the suggestion dropdown pops up but it only contains `fields` property. the `constructor` property is missing.

### Actual (Problematic) Behavior

`constructor` is missing in the field suggestion

**Comment by tamayika** [comment]
I made a fix [PR](https://github.com/microsoft/vscode-json-languageservice/pull/155) for vscode-json-languageservice.

**Comment by aeschli** [comment]
This got fixed by https://github.com/microsoft/vscode-json-languageservice/pull/155 (thanks @tamayika)
