### ISSUE TITLE
Setting wordBasedSuggestions to false has no effect

### ISSUE THREAD

**Issue by MakullaMa** [Microsoft/monaco-editor#334]
Hey, 

I am using a custom language with a monarch tokens provider and implemented a custom CompletionItemsProvider. In some cases my provider returns an empty array and then the word based suggestions kick in but I would rather like to see the "no suggestions" hint from the suggestions widget.

Setting `wordBasedSuggestions: false` when creating an editor for my language does not seem to have any effect. Some debugging led me to a completion provider in `EditorWorkerServiceImpl` where the following lines suggest that I should be able to turn off word based suggestions for my scenario:
```
if (configurationService.lookup('editor.wordBasedSuggestions').value) {
  return _this._workerManager.withWorker().then(function (client) { 
    return client.textualSuggest(model.uri, position); });
}
```

Unfortunately `configurationService.lookup('editor.wordBasedSuggestions').value` is always true, regardless of the setting I provided when creating the editor.

For now I worked around the issue by setting the global default for wordBasedSuggestions to false.

monaco-editor npm version: 0.8.0
Browser: IE11
OS: Windows 10

**Comment by e9gille** [comment]
I have the same problem now. In version 0.10.1 the wordBasedSuggestions were always off due to a bug. In version 0.11.1 the bug was fixed and it now picks up the default true value even if I set the option to false when creating an editor.

@MakullaMa how do I set a global flag to turn this feature off?
