### ISSUE TITLE
[Bug] incomplete demo in playground?

### ISSUE THREAD

**Issue by KshZh** [microsoft/monaco-editor#3347]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-color-provider-example
```

### Reproduction Steps

1. open https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-color-provider-example
2. notice the `endColumn` in the array returned from `provideDocumentColors` are all set as 0, thus I can't see the color picker on the right preview editor.

### Actual (Problematic) Behavior

no color picker on the right preview editor

### Expected Behavior

color picker appear while hovering text

**Comment by rcjsuen** [comment]
I was able to reproduce this and have opened #3348 to fix the example.
