### ISSUE TITLE
[Bug] Can't access "peek definition" action programmatically anymore (0.35.0-dev)

### ISSUE THREAD

**Issue by spahnke** [microsoft/monaco-editor#3349]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
const editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

editor.setPosition({lineNumber: 1, column: 11});
editor.focus();

const action = editor.getAction("editor.action.peekDefinition");
console.log(action);
setTimeout(() => action.run(), 500);
```

### Reproduction Steps

Run the above code with 0.35.0-dev.

### Actual (Problematic) Behavior

The `getAction` method returns `null`.

### Expected Behavior

The action is not `null` and can be run (after a timeout because this requires language service support).

### Additional Context

This is a regression in 0.35.0-dev so not *currently* reproducible in the playground (which is still on 0.34.0), but the code is still the same.

It was possible to get the `editor.action.peekDefinition` action by its action name and run it. As of 0.35.0-dev this is no longer possible.

I suspect this change https://github.com/microsoft/vscode/commit/099cfa996e9ff833c020eb5b29204c8365cc23e6 that switched using `registerInstantiatedEditorAction`[1] to `registerAction2`[2] which apparently does not register the action with the standalone editor anymore. The same will probably be true for all other "goto ..." actions.

[1] https://github.com/microsoft/vscode/blob/c9338005f7210e26c529891f21a85d26a2bebc87/src/vs/editor/browser/editorExtensions.ts#L471
[2] https://github.com/microsoft/vscode/blob/c9338005f7210e26c529891f21a85d26a2bebc87/src/vs/editor/contrib/gotoSymbol/browser/goToCommands.ts#L347

**Comment by jrieken** [comment]
These aren't editor actions anymore but normal commands, like those that are attached to code lenses or code actions.
