### ISSUE TITLE
[Bug] Opening links in the same window

### ISSUE THREAD

**Issue by AlinaKuzm** [microsoft/monaco-editor#3354]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
	value: "function example() {\n ref$: 'https://microsoft.github.io/monaco-editor/' \n}",
	language: 'javascript'
});
```

### Reproduction Steps
1) Open example on [Monaco Editor Playground Code](https://microsoft.github.io/monaco-editor/playground.html)
2) Follow 'https://microsoft.github.io/monaco-editor/' link

### Actual (Problematic) Behavior

Our Monaco Editor is a part of SPA. We use relative paths and we don't intend to switch tabs. 
Found WA: https://stackoverflow.com/questions/46746798/monaco-editor-follow-link-hook, it works, but we would like you to fix it

### Expected Behavior

If link navigate to the same origin -> it will be open in the same window
If link navigate to another origin -> it will be open in the new tab

**Comment by tamayika** [comment]
Another WA is to replace `openExternal` function. (I'm using)

```js
const editor = monaco.editor.create(document.getElementById('container'), {
	value: "function example() {\n ref$: 'https://microsoft.github.io/monaco-editor/' \n}",
	language: 'javascript'
});
editor.getContribution('editor.linkDetector').openerService._defaultExternalOpener.openExternal = function(url) {
    // need origin check
    window.location.assign(url);
};
```

Playground uses iframe, so only the right pane's url will be changed.

**Comment by spahnke** [comment]
We also use the Monaco editor inside an SPA and we *never ever* want the editor to change the page in the same tab when the user clicks a link. Because then you explicitly have to prevent losing unsaved changes (especially in the case of an accidental click). That said, we also have the need to handle some links differently and we hook into the `LinkDetector` contribution. That has an `openerService` with a list of "openers". Our util function gives us the ability to handle links first and if we handled them, indicate to Monaco that the default opener does not have to act anymore. Using a `Disposable` as return value we can also easily unregister a handler again. (CAUTION: unofficial APIs)

So I would rather a) see a setting that lets me choose between the current behavior (new tab) or your proposed behavior, or b) have an official API to hook into this. Just changing the behavior would probably break a lot of users.

```js
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

const editor = monaco.editor.create(document.getElementById('container'), {
    value: "function hello() {\n\talert('Hello world!'); // https://microsoft.github.io/monaco-editor/playground.html\n}",
    language: 'javascript'
});

/**
 * Registers a handler that is called when a link is opened. The handler callback should return `true` if the link was handled and `false` otherwise.
 * The handler that was registered last will be called first when a link is opened.
 *
 * Returns a disposable that can unregister the opener again.
 *
 * CAUTION: Uses internal unofficial APIs
 * 
 * @param {monaco.editor.IStandaloneCodeEditor} editor
 * @param {{open: (resource: monaco.Uri) => bool}} opener
 * @returns {monaco.IDisposable}
 */
function registerLinkOpener(editor, opener) {
    const linkDetector = editor.getContribution("editor.linkDetector");
    /** @type {(() => void) | undefined} */
    let remove = linkDetector?.openerService._openers.unshift({
        async open(resource) {
            if (typeof resource === "string")
                resource = monaco.Uri.parse(resource);
            return opener.open(resource);
        }
    });
    return {
        dispose() {
            remove?.();
            remove = undefined;
        }
    };
}

const opener = registerLinkOpener(editor, {
    open(resource) {
        console.log(resource);
        return true; // handled
    }
});

// opener.dispose(); // to unregister
```

**Comment by mofojed** [comment]
I've noticed email addresses attempt to open in the same window instead of in a new window, which seems inconsistent. Perhaps with @spahnke 's PR this point will be moot, as we can handle them however we want to make the behaviour consistent.
