### ISSUE TITLE
[Bug] Validation of json code doesn't work if url has fragment

### ISSUE THREAD

**Issue by kaermorchen** [microsoft/monaco-editor#3362]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// Configures two JSON schemas, with references.

var jsonCode = ['{', '    "p1": "v3",', '    "p2": false', '}'].join('\n');
var modelUri = monaco.Uri.parse('a://b/foo.json#hello'); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, 'json', modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [
		{
			uri: 'http://myserver/foo-schema.json', // id of the first schema
			fileMatch: [modelUri.toString()], // associate with our model
			schema: {
				type: 'object',
				properties: {
					p1: {
						enum: ['v1', 'v2']
					},
					p2: {
						$ref: 'http://myserver/bar-schema.json' // reference the second schema
					}
				}
			}
		},
		{
			uri: 'http://myserver/bar-schema.json', // id of the second schema
			schema: {
				type: 'object',
				properties: {
					q1: {
						enum: ['x1', 'x2']
					}
				}
			}
		}
	]
});

monaco.editor.create(document.getElementById('container'), {
	model: model
});
```

### Actual (Problematic) Behavior

`modelUri` has fragment `#hello` and the validation doesn't work.

### Additional Context

The validation will work if remove `#hello` from url or change `fileMatch` from `[modelUri.toString()]` to `modelUri.toString()`

**Comment by aeschli** [comment]
Don't add a fragment to a model URI. You are asking for trouble.

**Comment by kaermorchen** [comment]
But fragment is [a part of URI](https://github.com/microsoft/monaco-editor/blob/366b9c3/website/typedoc/monaco.d.ts#L81)

**Comment by aeschli** [comment]
The fragment is used to identify a portion of the document identified by the URI. The document itself is identified by the scheme, authority, and the path (*).
That why in the JSON language service, when matching a resource against a pattern, we clear out `query` and `fragment`: https://github.com/microsoft/vscode-json-languageservice/blob/e70857a34984391c63f93bfe635cd5bc47e627e7/src/services/jsonSchemaService.ts#L725

* It's a hairy topic, especially the discussion about whether `query` is part of a resource identifier.

So: Don't use query and fragment in your resource identifiers.

No changes planed.
