### ISSUE TITLE
Zoom on firefox displaces the cursor

### ISSUE THREAD

**Issue by isidorn** [microsoft/monaco-editor#337]
monaco-editor npm version: latest from source
Browser: firefox
OS: Ubuntu 14
Refs: https://github.com/Microsoft/vscode/issues/19061

1. standalone editor, firefox 
2. Zoom in or out - the cursor is displaced, type something it is at the wrong position
3. Once there are changes to the docuement or the user changes the position of the cursor the cursor goes back to being in a good position

So the issue happens only immediatly after a zoom in / out

**Comment by dbaeumer** [comment]
Same happens on Windows 10 with FF

**Comment by dbaeumer** [comment]
![cast](https://cloud.githubusercontent.com/assets/1931590/22258978/db84bdf4-e263-11e6-8264-3015bcbeb4bd.gif)

**Comment by alexandrudima** [comment]
@dbaeumer It looks you are not testing master (i.e. not clicking the `dev` button)

**Comment by alexandrudima** [comment]
This issue happens, as Isi mentions, immediately after zoom in/zoom out. There is no way to detect that (i.e. no browser zoom event). As soon as the current viewport is scrolled out or changed (i.e. repainted) everything works correctly. We're gonna have to live with this until there exists a browser zoom event such that we can repaint.

**Comment by alexandrudima** [comment]
The exact same behaviour exists on Safari

**Comment by alexandrudima** [comment]
I cannot reproduce anymore at http://vscode-web-test-playground.azurewebsites.net/?enter=true
