### ISSUE TITLE
[Bug] Tags missing in GitHub

### ISSUE THREAD

**Issue by dlangerenken** [microsoft/monaco-editor#3372]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
/
```

### Reproduction Steps

See changelog: https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md

### Actual (Problematic) Behavior

It looks like the latest created tag is 0.32.0. Several newer versions have been published to npm since and the changelog is listing each new version.

Is it possible to create the respective missing tags for each new versions? It's a requirement for us to being able to point a version to a specific tag in order for us to use it.

### Expected Behavior

Each new version has its own tag associated. 

### Additional Context

/

**Comment by alex-ander-is** [comment]
@alexdima @hediet: Please help us to resolve, maybe ping the proper person? Thank you!

**Comment by hediet** [comment]
I just added the missing tags. We also publish tags now automatically.
