### ISSUE TITLE
[Bug] CtrlCmd key bindings don't work

### ISSUE THREAD

**Issue by ronag** [microsoft/monaco-editor#3379]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
Consider following snippet:


var editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

var myBinding = editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_Y, function () {
	alert('CMD + S pressed!');
});

// You can't dispose `addCommand`
// If you need to dispose it you might use `addAction` or `registerCommand`
```

### Reproduction Steps

Pressing `Cmd + S` on Mac OS + Chrome 106 will immediately invoke the browser save function...

**Comment by tamayika** [comment]
Repro code is registering `CtrlCmd + Y`, so `KEY_Y` should be `KeyS`

Does following code reproduce the problem on your environment?
```
var editor = monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});

var myBinding = editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, function () {
	alert('CMD + S pressed!');
});
```
