### ISSUE TITLE
The bracketPairColorization and guides not working anymore [Bug] 

### ISSUE THREAD

**Issue by abdalla-rko** [microsoft/monaco-editor#3384]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// Configures two JSON schemas, with references.

var jsonCode = ['{', '    "p1": "v3",', '    "p2": false', '}'].join('\n');
var modelUri = monaco.Uri.parse('a://b/foo.json'); // a made up unique URI for our model
var model = monaco.editor.createModel(jsonCode, 'json', modelUri);

// configure the JSON language support with schemas and schema associations
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [
		{
			uri: 'http://myserver/foo-schema.json', // id of the first schema
			fileMatch: [modelUri.toString()], // associate with our model
			schema: {
				type: 'object',
				properties: {
					p1: {
						enum: ['v1', 'v2']
					},
					p2: {
						$ref: 'http://myserver/bar-schema.json' // reference the second schema
					}
				}
			}
		},
		{
			uri: 'http://myserver/bar-schema.json', // id of the second schema
			schema: {
				type: 'object',
				properties: {
					q1: {
						enum: ['x1', 'x2']
					}
				}
			}
		}
	]
});

monaco.editor.create(document.getElementById('container'), {
	model: model,             
    guides: {
        bracketPairs: "active"
    },
    bracketPairColorization: {
        enabled: true,
        independentColorPoolPerBracketType: true
    }
});
```

### Reproduction Steps

Adding guides.bracketPairs: "active" and bracketPairColorization as options in the monaco.editor.create()

### Actual (Problematic) Behavior

The bracketPairColorization and guides not working anymore after v0.33.0.

**Comment by FSDRE** [comment]
I can confirm this regression.

What I do not understand, though, is why VSCode itself does not suffer from these regressions? VSCode 1.73.0 does not have any problems regarding bracketPairColorization and guides.
