### ISSUE TITLE
[Bug] MonacoWebpackPlugin 7.0.1 and monaco-editor 0.34.1 breaks with Terser format comments option.

### ISSUE THREAD

**Issue by xleepy** [microsoft/monaco-editor#3387]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

- clone repo: https://github.com/xleepy/monaco-test
- npm install
- npm run start

Try to remove comments option in terser config and rerun build again 

### Actual (Problematic) Behavior

getColors function removed during terser mangle process when comments option provided.
Error: Function statements require a function name.

Colleague pointed out to function in monaco-editor-core
https://github.com/microsoft/vscode/blob/ff744e89a63dcc65809d7686e1dc92946e227cc1/src/vs/editor/contrib/colorPicker/browser/color.ts#L23

### Expected Behavior

Should work as previous versions

**Comment by xleepy** [comment]
https://github.com/xleepy/monaco-test/tree/workaround 
Possible workaround is to add 
`wrap_iife: true` option to format options in terser plugin  
https://github.com/terser/terser#format-options

**Comment by xleepy** [comment]
before
`beginCompute() {
                    this._computePromise = (0,
                    r.PG)((e=>S(this, void 0, void 0, (function*() {
                        const t = this._editor.getModel();
                        if (!t)
                            return Promise.resolve([]);
                        const i = new d.G(!1)
                          , n = yield /*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
                        function(e, t, i) {
                            const n = []
                              , o = e.ordered(t).reverse().map((e=>Promise.resolve(e.provideDocumentColors(t, i)).then((t=>{
                                if (Array.isArray(t))
                                    for (const i of t)
                                        n.push({
                                            colorInfo: i,
                                            provider: e
                                        })
                            }
                            ))));
                            return Promise.all(o).then((()=>n))
                        }
                        )(this._languageFeaturesService.colorProvider, t, e);
                        return this._debounceInformation.update(t, i.elapsed()),
                        n
                    }
                    )))),
                    this._computePromise.then((e=>{
                        this.updateDecorations(e),
                        this.updateColorDecorators(e),
                        this._computePromise = null
                    }
                    ), l.dL)
                }`
`

After wrap_iife
`beginCompute() {
                    this._computePromise = (0,
                    r.PG)((e=>S(this, void 0, void 0, (function*() {
                        const t = this._editor.getModel();
                        if (!t)
                            return Promise.resolve([]);
                        const i = new d.G(!1)
                          , n = yield(/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
                        function(e, t, i) {
                            const n = []
                              , o = e.ordered(t).reverse().map((e=>Promise.resolve(e.provideDocumentColors(t, i)).then((t=>{
                                if (Array.isArray(t))
                                    for (const i of t)
                                        n.push({
                                            colorInfo: i,
                                            provider: e
                                        })
                            }
                            ))));
                            return Promise.all(o).then((()=>n))
                        }
                        )(this._languageFeaturesService.colorProvider, t, e);
                        return this._debounceInformation.update(t, i.elapsed()),
                        n
                    }
                    )))),
                    this._computePromise.then((e=>{
                        this.updateDecorations(e),
                        this.updateColorDecorators(e),
                        this._computePromise = null
                    }
                    ), l.dL)
                }`

**Comment by hediet** [comment]
Unfortunately, I don't understand the bug and we don't have the resources to investigate terser issues.
However, if you have a PR to fix this issue, we can help you getting it merged!

**Comment by xleepy** [comment]
This is looks like mostly terser issue i'll close this issue. Because looks like if comments preserved in code terser will break function call inside generator. You can see in example above without wrap_iife comments breaks code.

```
yield(/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
                        function(e, t, i) {
```
```
yield /*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
                        function(e, t, i) {
```

**Comment by xleepy** [comment]
Just interesting that it happens only in monaco-editor case at least in our project
