### ISSUE TITLE
[Bug] automaticLayout doesnt shrink to container within flex layout

### ISSUE THREAD

**Issue by tplorts** [microsoft/monaco-editor#3393]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
  value: "function hello() {\n\talert('Hello world!');\n}",
  language: 'javascript',
  automaticLayout: true,
});

.root {
    display: flex;
    align-items: stretch;
    height: 100%;
}
.sidebar {
    width: 150px;
}
#container {
    flex: 1;
}

<div class="root">
    <div class="sidebar">some sidebar</div>
    <div id="container" style="height: 100%"></div>
</div>
```

### Reproduction Steps

expand the width of your viewport and see the editor grow as expected.
now shrink the viewport width

### Actual (Problematic) Behavior

The editor is not shrinking to fit the width of the container even though it is properly expanding.

### Expected Behavior

It should shrink as the container shrinks

### Additional Context

I have only seen this problem when the editor is a part of a flex or grid layout.  This is not a problem if the width is specified as a percent of its parent rather than using flex, but there are cases where flex or grid would be the best way of laying this out.

**Comment by tamayika** [comment]
monaco-editor just uses [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver), so there is nothing monaco-editor can do...

But I found a solution in CSS Grid. 
`minmax(0px, auto)` is the magic, only `auto` does not solve the problem.

```js
monaco.editor.create(document.getElementById('container'), {
  value: "function hello() {\n\talert('Hello world!');\n}",
  language: 'javascript',
  automaticLayout: true,
});
```

```css
.root {
    display: grid;
    grid-template-columns: 150px minmax(0px, auto);
    height: 100%;
}
```

```html
<div class="root">
    <div class="sidebar">some sidebar</div>
    <div id="container" style="height: 100%"></div>
</div>
```

**Comment by tplorts** [comment]
Oh excellent, thanks for taking the time to show me @tamayika! 🙏

**Comment by medihack** [comment]
I think another option you could try is (with flexbox):

```
#container {
    flex: 1;
    min-width: 0;
}
```

**Comment by tplorts** [comment]
Nice, indeed that does the trick as well, thanks!
