### ISSUE TITLE
[Bug] provideDocumentRangeFormattingEdits does not get called by `Format Selection`

### ISSUE THREAD

**Issue by FSDRE** [microsoft/monaco-editor#3396]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.registerDocumentRangeFormattingEditProvider('javascript', {
    provideDocumentRangeFormattingEdits: (model, range, options, token) => {
        console.log('This line does not run...');
        return [
            {
                range,
                text: 'console.log'
            }
        ]
    }
});

monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});
```

### Reproduction Steps

1. Copy above code into playground and run
2. Select the word `alert`
3. Right click -> `Format Selection` or `CTRL + K -> CTRL + F`
4. The registered `provideDocumentRangeFormattingEdits` does not get called

### Actual (Problematic) Behavior

The registered document range formatter does not get called.

### Expected Behavior

The registered document range formatter should get called and trigger the returned edits.

**Comment by tamayika** [comment]
I digged vscode codebase and found the solution.
Use [LanguageFilter](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.LanguageFilter.html) and set `exclusive: true` for the 1st argument of registerDocumentRangeFormattingEditProvider.

```js
monaco.languages.registerDocumentRangeFormattingEditProvider({language: 'javascript', exclusive: true}, {
    provideDocumentRangeFormattingEdits: (model, range, options, token) => {
        console.log('This line does not run...');
        return [
            {
                range,
                text: 'console.log'
            }
        ]
    },
});

monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});
```

### Why this works?

monaco-editor manages conflicted language features with scores.
When `exclusive: tue` is set, its score is set to 1000 and other scores are set to 0.([ref](https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/languageFeatureRegistry.ts#L169-L177))
So your feature will become the 1st feature in conflicted language features and be used.

**Comment by FSDRE** [comment]
@tamayika Thank you for your input. I can confirm that the flag works and formatting is getting called, but I do not understand where the conflict is. If I use language `csharp`, there is no default formatting provider and there should not be any conflicts. The formatting provider does not work anyway without the flag.

**Comment by FSDRE** [comment]
I think I know what the problem was... I wanted to try out `Format Selection` in the playground and did not use `csharp` at all. Then `javascript` screwed me over since it has a default formatter. It worked all along in `csharp`, I just did not implement it in my project since the playground wasn't working. Mystery solved... thanks a lot!
