### ISSUE TITLE
[Bug] role="code" is not a valid aria role

### ISSUE THREAD

**Issue by SimonRBG** [microsoft/monaco-editor#3403]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

- Go to any Monaco Editor Playground
- Open the Chrome Dev Tool console and inspect the editor div

### Actual (Problematic) Behavior

The role attribute of code given to this div is not allowed, as it is not a valid aria role (seen with Access Assistant).

### Expected Behavior

This DIV should only have aria valid role attribute or no role attribute.

### Additional Context

I was not able to find any relevant information or way to change this role="code". Could you please help there? Thanks

**Comment by hediet** [comment]
[This](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles is ) looks like `role="code"` is valid.

**Comment by SimonRBG** [comment]
Indeed it is. 

Let's close this ticket as I think the problem might be on Access Assitant side.

Thanks for your help.
