### ISSUE TITLE
[Bug] registerDocumentFormattingEditProvider not working

### ISSUE THREAD

**Issue by Amir-Lotfi** [microsoft/monaco-editor#3406]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.registerDocumentFormattingEditProvider('css', {
    async provideDocumentFormattingEdits(model, options, token) {
        const text = await prettier.format(model.getValue(), {
           plugins: [postcss],
           parser: "css",
        });

        return [
            {
                text,
                range: model.getFullModelRange(),
            },
        ]
    },
})
```

### Reproduction Steps

I can register prettier as format document logic for javascript files but unfortunately it doesn't work with html and css.

### Actual (Problematic) Behavior

Can not register formatting logic for css and html files using monaco.languages.registerDocumentFormattingEditProvider() function.

### Expected Behavior

Formatting code with custom prettier function.

**Comment by tamayika** [comment]
This is because monaco editor supports css formatting by default. (ref: https://github.com/microsoft/monaco-editor/blob/main/src/language/css/cssMode.ts#L109-L116)
You can disable default formatter by `monaco.languages.css.cssDefaults.modeConfiguration.documentFormattingEdits = false;` before creating `css` model;
Below code works on monaco editor playground.

```js
monaco.languages.css.cssDefaults.modeConfiguration.documentFormattingEdits = false;
monaco.languages.registerDocumentFormattingEditProvider('css', {
    provideDocumentFormattingEdits: (model) => {
        return [{
            text: "custom formatted",
            range: model.getFullModelRange(),
        }];
    }
});
monaco.editor.create(document.getElementById('container'), {
	value: "body{height:100%}",
	language: 'css'
});
```

**Comment by tamayika** [comment]
I found alternative solution. ([Detail](https://github.com/microsoft/monaco-editor/issues/3396#issuecomment-1312477281))
This works for any languages and does not care about initialization order.

```js
monaco.languages.registerDocumentFormattingEditProvider({language: 'css', exclusive: true}, {
    provideDocumentFormattingEdits: (model) => {
        return [{
            text: "custom formatted",
            range: model.getFullModelRange(),
        }];
    }
});
monaco.editor.create(document.getElementById('container'), {
	value: "body{height:100%}",
	language: 'css'
});
```

**Comment by Amir-Lotfi** [comment]
> I found alternative solution. ([Detail](https://github.com/microsoft/monaco-editor/issues/3396#issuecomment-1312477281)) This works for any languages and does not care about initialization order.
> 
> ```js
> monaco.languages.registerDocumentFormattingEditProvider({language: 'css', exclusive: true}, {
>     provideDocumentFormattingEdits: (model) => {
>         return [{
>             text: "custom formatted",
>             range: model.getFullModelRange(),
>         }];
>     }
> });
> monaco.editor.create(document.getElementById('container'), {
> 	value: "body{height:100%}",
> 	language: 'css'
> });
> ```

Thank you so much, it worked.
