### ISSUE TITLE
Undo calls onDidChangeModelContent too many times

### ISSUE THREAD

**Issue by fzafiroski** [Microsoft/monaco-editor#341]
monaco-editor npm version: 0.8.0
Browser: Chrome
OS: Centos 7

I am using AngularJs and trying to use `editor.onDidChangeModelContent()` function properly.

Whenever I type a letter, the function executes which is ok, but the problem is when I do `editor.getModel().undo()`, which is monaco's undo function. The undo calls `editor.onDidChangeModelContent()` as many times as many letters it removed (for example, if I have written `this line will be undone` and I call `undo()`, it removes the line and calls `editor.onDidChangeModelContent()` 24 times. Shouldn't it call it only once? Is there a function that will execute only once on `undo()` and do I use `undo()` properly?

**Comment by alexandrudima** [comment]
It depends on what you'd want to do.

### If you'd want to do something when a model changes
* you can keep using `editor.onDidChangeModelContent()` and debounce on your side (i.e. set/cancel a timer that will execute x ms after the last content change event comes in)

```js
/**
 * Addds content changed listener to `editor` and invokes `callback` 100ms after the last content changed event.
 */
function onDidChangeModelContentDebounced(editor, callback) {
  var timer = -1;
  var runner = function() {
    timer = -1;
    callback();
  }
  return editor.onDidChangeModelContent(function(e) {
    if (timer !== -1) {
      clearTimeout(timer);
    }
    timer = setTimeout(runner, 100);
  });
}
```


### If you'd want to capture the model change events
* You can go off public API:
```js
/**
 * Addds content changed listener to `editor` and invokes `callback` with all change events.
 */
function onDidChangeModelContentBulk(editor, callback) {
  return editor.getModel().addBulkListener(function(events) {
    contentChangeEvents = events.filter(function(e) {
      return e.getType() === 'contentChanged2';
    }).map(function(e) {
      return e.getData();
    });
    if (contentChangeEvents.length > 0) {
      callback(contentChangeEvents);
    }
  });
}
```

**Comment by fzafiroski** [comment]
Thank you! Debouncing worked perfectly!
