### ISSUE TITLE
[Bug] security hole：

### ISSUE THREAD

**Issue by liubeilily** [microsoft/monaco-editor#3413]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
export const setTimeout0 = (() => {
    if (setTimeout0IsFaster) {
        const pending = [];
        globals.addEventListener('message', (e) => {
            if (e.data && e.data.vscodeScheduleAsyncWork) {
                for (let i = 0, len = pending.length; i < len; i++) {
                    const candidate = pending[i];
                    if (candidate.id === e.data.vscodeScheduleAsyncWork) {
                        pending.splice(i, 1);
                        candidate.callback();
                        return;
                    }
                }
            }
        });
        let lastId = 0;
        return (callback) => {
            const myId = ++lastId;
            pending.push({
                id: myId,
                callback: callback
            });
            globals.postMessage({ vscodeScheduleAsyncWork: myId }, '*');
        };
    }
    return (callback) => setTimeout(callback);
})();
```

### Reproduction Steps

1 When postMessage is used to send messages, the exact destination address is not specified, but the wildcard character is used, which causes other websites to intercept data.
2 When addEventListener is used to listen to messages, the origin or source attribute of the event is not used to verify the source. Is it possible that cross-site script estimation may occur?

**Comment by alexdima** [comment]
Thank you for contacting us. You're right that the message handler doesn't check the origin and that `postMessage` uses `*`, but this is not a security vulnerability because an attacker cannot achieve anything using these messages.

In the future, if you believe you have found a security problem, please follow the setps described at https://github.com/microsoft/monaco-editor/security/policy
