### ISSUE TITLE
[Feature Request] Be able to disable wordwrap on minified code

### ISSUE THREAD

**Issue by yaustar** [microsoft/monaco-editor#3417]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I would like to disable wordwrap for minified code but there doesn't seem to be an option to do so via the Editor. Using the option `wordWrapMinified` as shown in this [playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hard-wrapping) has no effect.

When calling `getLayoutInfo()`, `isWordWrapMinified` is returning `true`

**Comment by tamayika** [comment]
I took a quick look into vscode codebase.
I found that `wordWrapMinified` is defined and computed in EditorLayoutInfo but never used in anywhere else.
It was introduced in [2017](https://github.com/microsoft/vscode/commit/9883c987637e38ce8fe3364bd68c385f294c2ba0) and [now](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/codeEditor/browser/toggleWordWrap.ts) not used. Maybe this option is unnecessary now. (cc: @alexdima)

**Comment by yaustar** [comment]
Oh, in which case how would you prevent wordwrap on minified code? 😅

**Comment by tamayika** [comment]
Unfortunetely, there is no chance in current codebase.

**Comment by tamayika** [comment]
The same question is asked in vscode too and never resolved...
https://github.com/microsoft/vscode/issues/119947

**Comment by yaustar** [comment]
That's a shame, I wonder why it has to be a separate option 🤔

**Comment by alexdima** [comment]
You can use the option `wordWrapOverride1: 'off'`.
