### ISSUE TITLE
Trigger insert snippet programmatically

### ISSUE THREAD

**Issue by erenbaydemir** [microsoft/monaco-editor#342]
Is it possible to trigger 'insert snippet' programmatically? 

There is a class named InsertSnippetAction but it's never used in the code base. 

What we are trying to call is something like this one: 
`editor.trigger('bla', 'editor.action.insertSnippet', { text: "function {{<function_name>}} ()" });`

'editor.action.insertSnippet' is not available in editor.getActions().

**Comment by fcastill** [comment]
@erenbaydemir did you find a way to achieve this?

**Comment by Myqilixiang** [comment]
Did you make it

**Comment by moranje** [comment]
Did anyone found a way to accomplish this? Inserting by reference/id would be enough for my purposes.

**Comment by Myqilixiang** [comment]
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

**Comment by moranje** [comment]
@Myqilixiang That's the way to trigger snippets in the editor, I'm looking for a way to do so with programmatically. For instance running a snippet with a keyboard shortcut. Or am I missing something?

**Comment by gins3000** [comment]
This worked for me, using monaco-editor-core:
`editor.getContribution("snippetController2")` returns the SnippetController of the editor.
First set the cursor position, and then call the "insert" method of the snippet controller, first parameter being the template for your snippet in string form.

Still experimenting with this myself, hope it helps.

I would still like a more "official" way to do it though.

**Comment by hediet** [comment]
Closing because @gins3000 solution seems to work.

Please create a new issue if it that solution no longer works or has limitations.
