### ISSUE TITLE
中文输入法的时候，0.31.1以下的版本会出现滚动条，0.33.0以上的版本，拼音会显示不全。

### ISSUE THREAD

**Issue by yeyuliang2015** [microsoft/monaco-editor#3432]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
中文输入法的时候，0.31.1以下的版本会出现滚动条，如图：<img width="780" alt="image" src="https://user-images.githubusercontent.com/10381702/203456115-94f6e83b-a62b-4b25-b7b2-27c0822b6aac.png">
0.33.0以上的版本，拼音会显示不全，如图：
<img width="604" alt="image" src="https://user-images.githubusercontent.com/10381702/203456755-0a83048d-d584-4641-95f3-c4495952bf38.png">
```

### Reproduction Steps

中文输入法的时候，0.31.1以下的版本会出现滚动条，如图：<img width="780" alt="image" src="https://user-images.githubusercontent.com/10381702/203456115-94f6e83b-a62b-4b25-b7b2-27c0822b6aac.png">
0.33.0以上的版本，拼音会显示不全，如图：
<img width="604" alt="image" src="https://user-images.githubusercontent.com/10381702/203456755-0a83048d-d584-4641-95f3-c4495952bf38.png">

### Actual (Problematic) Behavior

中文输入法的时候，0.31.1以下的版本会出现滚动条，如图：<img width="780" alt="image" src="https://user-images.githubusercontent.com/10381702/203456115-94f6e83b-a62b-4b25-b7b2-27c0822b6aac.png">
0.33.0以上的版本，拼音会显示不全，如图：
<img width="604" alt="image" src="https://user-images.githubusercontent.com/10381702/203456755-0a83048d-d584-4641-95f3-c4495952bf38.png">

### Expected Behavior

中文输入法的时候，0.31.1以下的版本会出现滚动条，如图：<img width="780" alt="image" src="https://user-images.githubusercontent.com/10381702/203456115-94f6e83b-a62b-4b25-b7b2-27c0822b6aac.png">
0.33.0以上的版本，拼音会显示不全，如图：
<img width="604" alt="image" src="https://user-images.githubusercontent.com/10381702/203456755-0a83048d-d584-4641-95f3-c4495952bf38.png">

### Additional Context

中文输入法的时候，0.31.1以下的版本会出现滚动条，如图：<img width="780" alt="image" src="https://user-images.githubusercontent.com/10381702/203456115-94f6e83b-a62b-4b25-b7b2-27c0822b6aac.png">
0.33.0以上的版本，拼音会显示不全，如图：
<img width="604" alt="image" src="https://user-images.githubusercontent.com/10381702/203456755-0a83048d-d584-4641-95f3-c4495952bf38.png">

**Comment by yeyuliang2015** [comment]
中文输入法的拼音被截取显示不全

**Comment by hediet** [comment]
Please post your issue in English.
