### ISSUE TITLE
[Bug] weird import construct

### ISSUE THREAD

**Issue by YousefED** [microsoft/monaco-editor#3437]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Importing monaco in vitest, gives an error that monaco_editor_core_star is being used before it's imported.

Upon further inspection, I noticed the following code:

monaco-editor/esm/vs/language/typescript/tsMode.js:

```
__reExport(monaco_editor_core_exports, monaco_editor_core_star);
 import * as monaco_editor_core_star from "../../editor/editor.api.js";
```

and monaco-editor/esm/vs/language/typescript/monaco.contribution.js:

```
 // src/fillers/monaco-editor-core.ts
 var monaco_editor_core_exports = {};
 __reExport(monaco_editor_core_exports, monaco_editor_core_star);
import * as monaco_editor_core_star from "../../editor/editor.api.js";
```

This does seem a bit weird. Flipping this around fixed my issue, but I guess it's being autogenerated somewhere?

**Comment by hediet** [comment]
Can you suggest a change?
We use esbuild for bundling, which probably produces this.

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.


That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
