### ISSUE TITLE
[Bug] Monaco `model.setEOL(monaco.editor.EndOfLinePreference.LF)` makes `getValue()` return `\r\n` on Ubuntu Linux

### ISSUE THREAD

**Issue by cirosantilli** [microsoft/monaco-editor#3440]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// js

const outputElem = document.getElementById('output');
const editor = monaco.editor.create(document.getElementById('container'), {});
const model = editor.getModel()
model.setEOL(monaco.editor.EndOfLinePreference.LF);
editor.onDidChangeModelContent(async (e) => {
    outputElem.innerHTML = JSON.stringify(editor.getValue());
});

// html

<div id="container" style="height:400px;border:1px solid black;"></div>
<div id="output" style="height:400px;border:1px solid black;"></div>
```

### Reproduction Steps

type enter on editor

### Actual (Problematic) Behavior

output shows `\r\n`

### Expected Behavior

output shows `\n`

### Additional Context

Without:

```
model.setEOL(monaco.editor.EndOfLinePreference.LF);
```

I get `\n` by default.

If I modify to:

```
model.setEOL(monaco.editor.EndOfLinePreference.CRLF);
```

I also still get `\n`.

Related: https://stackoverflow.com/questions/56525822/how-to-set-eol-to-lf-for-windows-so-that-api-gets-value-with-n-not-r-n/74624712#74624712

Tested on Ubuntu 22.04, Chromium 85 and Firefox 107.

**Comment by hediet** [comment]
Use should use `monaco.editor.EndOfLineSequence` instead.
