### ISSUE TITLE
[Feature Request] editor.cursorSurroundingLines to work in Jupyter notebooks

### ISSUE THREAD

**Issue by lukasobg** [microsoft/monaco-editor#3445]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

The scroll offset option 'editor.cursorSurroundingLines' works great in normal files (first video)
But in Jupyter notebooks it doesn't work when moving in a long cell that fills the entire screen (second video).

Is it possible to change this from VSCodes side or should this request be made to the Jupyter extension team?

https://user-images.githubusercontent.com/62295460/205187131-2913a615-e2d4-4998-88cb-8ed74aa8c57f.mov

https://user-images.githubusercontent.com/62295460/205187150-2068cc1d-1002-430e-aef4-9ad4a3f5b9a6.mov

**Comment by tamayika** [comment]
monaco editor is not the library which vscode uses, but directly exported from vscode.
And its release is always deferred from vscode release, so you should create issue in vscode repository.

**Comment by lukasobg** [comment]
Thank you!
