### ISSUE TITLE
[Bug] TypeError: languageDefinitions is undefined

### ISSUE THREAD

**Issue by nileshlande12** [microsoft/monaco-editor#3447]
<img width="674" alt="Screenshot 2022-12-02 at 8 12 11 PM" src="https://user-images.githubusercontent.com/45351035/205318923-8915e877-cc14-4dbc-89af-c3c22e61f42a.png">

On production level we are facing issue on load of application where languageDefinitions is failing with undefined, but working fine in dev mode.

We are using:
monaco-editor-webpack-plugin: 7.0.1
monaco-editor: 0.34.1

Error is from:
https://github.com/microsoft/monaco-editor/blob/25e85af033388fe4825418b76a89ef617199b069/src/basic-languages/_.contribution.ts

**Comment by hediet** [comment]
Please try to reproduce this issue in the monaco playground. Thank you!
