### ISSUE TITLE
[Bug] Matching bracket is not highlighted

### ISSUE THREAD

**Issue by akphi** [microsoft/monaco-editor#3449]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

monaco.editor.create(document.getElementById('container'), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});
```

### Reproduction Steps

With the code above, when you click on the code on the left panel, the matching bracket is not highlighted properly. See the screenshots below. I'm not 100% sure if this is bug, or if I'm just missing some config. Really appreciate any guidance here. Thank you!

### Actual (Problematic) Behavior

Here, you can see the matching bracket of the function is not highlighted

<img width="427" alt="Screen Shot 2022-12-03 at 8 15 32 PM" src="https://user-images.githubusercontent.com/13574879/205469341-afc4ea1e-8f07-4414-bb24-f9c070679de3.png">

### Expected Behavior

I took this from vscode.dev, and really any VSCode

<img width="512" alt="Screen Shot 2022-12-03 at 8 16 07 PM" src="https://user-images.githubusercontent.com/13574879/205469343-40e54983-84d7-415c-a53a-7650aeb286d0.png">

### Additional Context

What I noticed is in our README

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/13574879/205469368-d97a839a-5496-4a1e-b982-0f8ebbae6de4.png">

and this old [Stackoverflow thread](https://stackoverflow.com/questions/47281690/monaco-editor-matchbrackets-do-not-highlight) this seems to use to work, so I'm somewhat suspicious this could be a bug, hence filing as such

**Comment by akphi** [comment]
@hediet thank you so much for the fix. Do you mind letting me know when this change could be released so I can do testing on my part. Thanks!

**Comment by akphi** [comment]
@hediet I have tried to patch my monaco-editor using your change in https://github.com/microsoft/vscode/pull/168884/files
I noticed these problems:
1. I have create an instance of editor that uses `json` as the format, this fix doesn't seem to work for that particular file
2. I have created my custom language (following the guide found at https://microsoft.github.io/monaco-editor/monarch.html), and created an editor using that language, however, I want to disable bracket pair colorization, and `bracketPairColorization: { enabled: false }` no longer seem to work (previous to this change, it did work and disable the bracket pair colorization).

**Comment by akphi** [comment]
> 1. I have create an instance of editor that uses `json` as the format, this fix doesn't seem to work for that particular file

I found out that this has something to do particularly with `json`, languages like `java` part of [src/basic-languages](https://github.com/microsoft/monaco-editor/tree/main/src/basic-languages) will behave just like my custom language and will work well with your fix, except for problem (2), hopefully this rules out that (2) is caused by my custom language

**Comment by hediet** [comment]
Will be released soon! Also, check out our nightly release on npm, though monaco-editor is currently broken.

**Comment by FSDRE** [comment]
Thank you a lot!!!! Nice christmas present 😄
