### ISSUE TITLE
[Bug] Cannot set property marked of object which only has getter

### ISSUE THREAD

**Issue by Zachiah** [microsoft/monaco-editor#3456]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### The Issue

Whenever I try to import monaco I get an issue relating to the `marked` library having a readonly property.

I was trying to create a reproduction and made [this stackblitz](https://stackblitz.com/edit/nextjs-yen4zm?file=components%2FCodeEditor.tsx,package.json,package-lock.json). It does not show the error unfortunately.

I'm having a really hard time diagnosing this issue but if I run this exact code (I used the download button) locally, I get this error:
<img width="1029" alt="Screenshot 2022-12-09 at 2 01 43 PM" src="https://user-images.githubusercontent.com/50641830/206802888-e6ef5928-c8df-4427-95a3-67cdba6618d9.png">

I installed the exact node and npm versions as were being used on stackblitz and that didn't help at all. (I realize stackblitz uses turbo, and I can't exactly replicate that). I'm using a 14in m1 macbook pro. I figured it must have to do with os differences so I downloaded parallels and ran it on ubuntu. I got the same error however.
<img width="1136" alt="Screenshot 2022-12-09 at 2 09 25 PM" src="https://user-images.githubusercontent.com/50641830/206803835-8e32271d-71f4-4f89-bec3-36a87ab85e5b.png">

I'm hoping someone here will be able to reproduce it on their machine and it's not just me, but I would appreciate any help.

I'm pretty confident my setup should be working as demonstrated by the stackblitz but it also could be that it is working on stackblitz when it shouldn't be I guess. If someone could take a look I would really appreciate it. I don't know how to debug this as I've replicated the environment as much as I can and I'm still getting the issue.

I just tried it on windows and it also fails, so it seems that maybe I set it up wrong. Although, the fact that it works on stackblitz very much contradicts that idea. I can't imagine that stackblitz is broken just such that this works when it shouldn't

[Github Repository](https://github.com/Zachiah/nextjs-yen4zm)

##### My laptop with latest node and npm
Fails

##### My Laptop with node v16.14.2 (the stackblitz version) and npm 7
Fails

##### Stackblitz in Brave Browser
Succeeds

##### My Windows 11 Desktop with node v16.14.2
Fails

##### Ubuntu running in parallels on my laptop with node v16.4.2 and npm 7
Fails

**Comment by hediet** [comment]
Can you reproduce it in the monaco editor playground?

**Comment by Zachiah** [comment]
I don't think so... It has to do with loading monaco. Could you take a look at the repo?

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
