### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by daidaibg** [microsoft/monaco-editor#3476]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

//Click "Enter" in the running result window to change lines, and an error will be reported
monaco.editor.create(document.getElementById('container'), {
	value: "```dasd```  ",
	language: 'markdown'
});
```

### Reproduction Steps

```dasd```

// ```You can write freely in the middle

### Actual (Problematic) Behavior

//You can enter other md syntax without problem
//However, the following syntax cannot be used

```dasd```

### Expected Behavior

//Hope to support the following writing methods

```dasd```
```

### Additional Context

//Hope to see this problem

**Comment by daidaibg** [comment]
![image](https://user-images.githubusercontent.com/55817318/209493661-ffedf769-ba2d-4f46-8c55-11c3a5ce2f16.png)

**Comment by daidaibg** [comment]
> ![图片](https://user-images.githubusercontent.com/55817318/209493661-ffedf769-ba2d-4f46-8c55-11c3a5ce2f16.png)

Click "Enter" in the running result window to change lines, and an error will be reported

**Comment by daidaibg** [comment]
> ![图片](https://user-images.githubusercontent.com/55817318/209493661-ffedf769-ba2d-4f46-8c55-11c3a5ce2f16.png)

Click "Enter" to report an error.
Uncaught Error: Language id "vs.editor.nullLanguage" is not configured nor known,
Error: Language id "vs.editor.nullLanguage" is not configured nor known.

**Comment by tanhh326** [comment]
I don't think it's a problem. There's no such editor
