### ISSUE TITLE
Default folding at specified level on editor start

### ISSUE THREAD

**Issue by mutt1973** [microsoft/monaco-editor#348]
I want to achive the following:

After creating a editor with following code : 

       var editor = monaco.editor.create(container,
                        {
                            value: '...',
                            language: 'java'
                        });

I want to fold the code at level 1. How can I achive this in javascript ?

This is how it looks at startup at the moment:
![grafik](https://cloud.githubusercontent.com/assets/25532914/22598358/85e60880-ea33-11e6-93b7-fca892d5c316.png)

But it should look like this:

![grafik](https://cloud.githubusercontent.com/assets/25532914/22598408/ac5b7586-ea33-11e6-9fbc-7d7db52e7f89.png)

**Comment by alexandrudima** [comment]
You could try using (run [here](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance)):
```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript",
    folding: true
});

editor.getAction('editor.foldLevel2').run();
```

<img width="386" alt="screen shot 2017-06-15 at 11 58 59" src="https://user-images.githubusercontent.com/5047891/27176228-0b703ade-51c2-11e7-8283-c2ae05efbf87.png">
