### ISSUE TITLE
[Feature Request] How to add left margin to content, right margin to content and linepadding for only bottom line ?

### ISSUE THREAD

**Issue by sagarkardani** [microsoft/monaco-editor#3481]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I want to add different margins/paddings to content.

Below is the normal image with dummy text with text wrapping on.
![monaco](https://user-images.githubusercontent.com/60609139/210130029-f90bbe66-b3ab-432e-81cc-71b76f721c36.png)

What I want to achieve is like below.
![Achieve](https://user-images.githubusercontent.com/60609139/210130030-d36f2d63-b6cd-4e66-8826-fbcca0fcacea.png)

What I want to apply is something like

**leftmargin** - left margin to the content i.e. margin between line numbers and content.
**rightmargin** - right margin to the content i.e. margin between content and scrollbar.
**paddingbelowlastwrappedline** - add extra padding after the last wrapped line to provide some extra gap.
**firstlineindent** - apply indent only to first line of the wrapped lines and not to others.

Also this changes should be visible in minimap also.

Some similar posts are [here](https://stackoverflow.com/questions/49431915/adding-a-padding-to-monaco-editor-area-lines-content), [here](https://stackoverflow.com/questions/59648356/monaco-editor-vertical-line-padding), [here](https://github.com/microsoft/vscode/issues/98410).

Is there any decent and elegant way to achieve this ? Current I am using [codemirror](https://github.com/codemirror/codemirror5) and I want to switch to monacoeditor for some reasons.

**Comment by hediet** [comment]
This feature is out of scope for the monaco editor, but maybe it a feature request for VS Code might have more success.
