### ISSUE TITLE
[Bug] Tooltips of error dialog toolbar buttons can't display when navigating via screen reader 

### ISSUE THREAD

**Issue by WenliNing** [microsoft/monaco-editor#3484]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), 
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: 'javascript'
});
```

### Reproduction Steps

1. Click any position of the invalid source code in code editor
2. Press F8 to display error dialog
4. Launch the a11y tool like voice over on macOS or screen reader
5. Navigate between the dialog toolbar buttons via voice over or screen reader
6. Observe that navigating with a keyboard does not reveal the tooltip "Go to Next Problem (Error, Warning, Info)" visually, but it appears when hover on it with mouse

### Actual (Problematic) Behavior

Hovering over the error dialog tooltip buttons with mouse reveal the tooltip "Go to Next Problem (Error, Warning, Info)", but navigating with a keyboard does not reveal equivalent information visually 

### Expected Behavior

Navigating with a keyboard should reveal equivalent information visually as via mouse

**Comment by hediet** [comment]
I can verify that the bug occurs in v0.34.0, but it is fixed in v0.35.0-dev.20230206.
