### ISSUE TITLE
[Bug] Positioning of suggestions incorrect when monaco editor is placed inside a Fluent panel.

### ISSUE THREAD

**Issue by cherie-q** [microsoft/monaco-editor#3486]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Here is the code pen for a min repro - https://codepen.io/cheriequek/pen/XWBjKOX
I was unable to use the monaco editor playground as it did not seem to allow me to load the fluent libraries.

Load the codepen and wait for a little bit (need to wait for monaco to load)
Then click Load editor
When the editor loads, attempt to type something that would bring up the intellisense suggestions (eg. console)

### Actual (Problematic) Behavior

The intellisense suggestions show up in the wrong location and most of it is not visible.

![image](https://user-images.githubusercontent.com/89044673/210570484-e977bd4c-208c-449d-bbbc-a63204e9d954.png)

### Expected Behavior

I expect to see the intellisense suggestions (and other widgets) to respect the size of the panel and be fully visible within the panel width.

### Additional Context

I've seen this other issue which is similar - https://github.com/microsoft/monaco-editor/issues/2503. and have attempted other user's workarounds and none of them seem to work. I've opened a different issue mainly because the positioning issue seems to be different from the screenshots provided.

**Comment by jrieken** [comment]
Sorry, but we cannot investigate issues that neither occur in vscode nor in the monaco playground
