### ISSUE TITLE
[Bug] editor breaks with language=html when the document contains a script tag with type=importmap

### ISSUE THREAD

**Issue by yurique** [microsoft/monaco-editor#3487]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById('container'), {
	value: [
        '<!DOCTYPE html>',
        '<head>',
        '</head>',
        '<body>',
        '<script type="importmap">',
        '{',
        '  "imports": {',
        '    "something": "somewhere"',
        '  }',
        '}',
        '</script>',
        '</body>',
        '</html>',
        ].join('\n'),
	language: 'html'
});
```

### Reproduction Steps

* run the playground code
* in the rendered editor, navigate the cursor to the end of the `"something": "somewhere"',` line
* try inserting a new-line

### Actual (Problematic) Behavior

Once inside that script block which has `type=importmap`, the following error is being printed into the console:

```
Error: Language id "vs.editor.nullLanguage" is not configured nor known
```

Editing partially works, but, for example, I can't insert a new-line. 

### Expected Behavior

I should be able to edit the code inside a script block with `type=importmap`, and no exceptions should be thrown and printed into the console.

**Comment by hediet** [comment]
This is the html rule:
```js
scriptWithCustomType: [
    [
        />/,
        {
            token: 'delimiter',
            next: '@scriptEmbedded.$S2',
            nextEmbedded: '$S2'
        }
    ],
    [/"([^"]*)"/, 'attribute.value'],
    [/'([^']*)'/, 'attribute.value'],
    [/[\w\-]+/, 'attribute.name'],
    [/=/, 'delimiter'],
    [/[ \t\r\n]+/], // whitespace
    [/<\/script\s*>/, { token: '@rematch', next: '@pop' }]
],
```

I think it tries to call into `@scriptEmbedded.importmap` rule, which does not exist.
Thus, it marks the text as "null" language. I don't think the null language should ever be used, instead it should mark the text as "plain text".

@alexdima what do you think?

**Comment by hediet** [comment]
Fixed https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAALSAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0C0qI7hIAsMTVidhIYOHeT-hbw5Wu66wvIw7QvGB7QN7HCJDZdNWfJb30dcTWyXAZPNItY7tGUZb_wWLTS2Ga4sFO-Z0BQJYH4WWmbISl6zLPOT0TIIVDE585M-adNr-ZzlBmEJpDwMkAcgtqvz-U5ZOyGZ0usnCTN9P5OYsGjbBA-TQoCxhXx5VLC8gIHdvgonLicrG5LhEwGhG920-tpAy07WFA0up7lnRuUC8ZOFKxeuSD5uukqpsUb6LIdxJZOGMZohX2Qgj_7gWvC0
