### ISSUE TITLE
where is the compiler

### ISSUE THREAD

**Issue by npenin** [Microsoft/monaco-editor#35]
Hi Team,

I am looking for the typescript compiler. I had a look at the typescript playground, which is using `getEmitOutput`, but I cannot find how to use it myself. Could you please guide me on how to proceed ?

Thanks,
Nicolas

**Comment by alexandrudima** [comment]
@jrieken Should we add `getEmitOutput` to `monaco-typescript` ?

**Comment by jrieken** [comment]
We should expose the whole language service API or the promise'isified version of it so folks are free to do. Only things like the program or ASTs that cannot be JSONified we shouldn't expose

**Comment by npenin** [comment]
Do you have any timeline for this ?

**Comment by paveldk** [comment]
Would be much appreciated

**Comment by jrieken** [comment]
We don't really have a timeline for this but the good news is that we are accepting PRs :-). 

Getting to the `emitOutput` is mostly about exposing this [function](https://github.com/Microsoft/monaco-typescript/blob/master/src/mode.ts#L40) and exposing more language service features in the [worker](https://github.com/Microsoft/monaco-typescript/blob/master/src/worker.ts#L109) - tho arguments and return types must JSON'able.

'Exposing' things happens in the [`createApi`](https://github.com/Microsoft/monaco-typescript/blob/master/src/monaco.contribution.ts#L126) such that others can do something like this: `monaco.languages.typescript.withWorker(uri1, uri2).getEmitOutput(fileName).then(result ...)`

**Comment by paveldk** [comment]
I'm on it :)

**Comment by jrieken** [comment]
we have it
