### ISSUE TITLE
[Bug] Follow link functionality is broken when URL ends with quotation marks

### ISSUE THREAD

**Issue by steinos** [microsoft/monaco-editor#3502]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
in javascript file:
monaco.editor.create(document.getElementById('container'), {
	value: 'function hello() {\n\talert("URL=http://google.com/");\n}',
	language: 'javascript'
});

run code
```

### Reproduction Steps

You can already see the problem - the link takes the closing quotation marks as it is part of the URL.
Hover the url, and click "Follow link" - a wrong address is opened = http://google.com/%22.

### Actual (Problematic) Behavior

The "follow link" functionality is broken

The link takes the closing quotation marks as it is part of the URL.
Hover the url, and click "Follow link" - a wrong address is opened = http://google.com/%22.

### Expected Behavior

be able to use "Follow link"

### Additional Context

We are using Monaco editor to display scripts, we cannot preprocess them as the are completely valid.
Something is wrong with the URL detection/parsing.
Using version 0.34.1

**Comment by tamayika** [comment]
This has been already resolved in the latest vscode. (by https://github.com/microsoft/vscode/commit/a81cd28ea892ce689292c5dc50ccdda5a241da2e)

**Comment by steinos** [comment]
Thank you. Do you have any time estimation for next release?

**Comment by tamayika** [comment]
@hediet Please answer this.

@steinos BTW if you don't worry about using nightly build, you can use https://www.npmjs.com/package/monaco-editor?activeTab=versions

**Comment by steinos** [comment]
I validated the fix on nightly - looks like issue is solved.
We will wait for your next formal release, what is the estimated time for it to come out?

**Comment by steinos** [comment]
> @hediet Please answer this.
> 
> @steinos BTW if you don't worry about using nightly build, you can use https://www.npmjs.com/package/monaco-editor?activeTab=versions

**Do you have any time estimation for next release?**

**Comment by CGNonofr** [comment]
I'm interested in a new official release as well, there were a few other bugfixes and improvements that got merged into vscode (like https://code.visualstudio.com/updates/v1_72#_improved-autoscroll-behavior, https://code.visualstudio.com/updates/v1_72#_improved-hover or https://code.visualstudio.com/updates/v1_71#_new-code-action-control) I'd like to see as well

The last release of monaco editor is based on https://github.com/microsoft/vscode/commit/4b8a47f3570a4a05ace9d00ae0df044b55befcd5 which is now almost 6 months old

**Comment by hediet** [comment]
/duplicate https://github.com/microsoft/vscode/issues/156875

A release will happen soon.
