### ISSUE TITLE
Is there a flag isQuickAccessOpened / isCommandPaletteOpend?

### ISSUE THREAD

**Issue by kia** [microsoft/monaco-editor#3503]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Hello,
I am using monaco in a JavaFX application. 
The scrolling behavior with the mouse wheel for scrolling through the commands in the command palette is some how unsmooth  when using the monaco editor in the browser provided by JavaFX-WebEngine. 

I would like to manipulate this behavior programmatically by capturing the mouse wheel events. But I would like to do this only if the command palette is opened by the user. How do i know the command palette is opened? Is there a function or flag like isQuickAccessOpened / isCommandPaletteOpend that i can use?

I know the best way would be to fix the WebEngine-Behaviour because in a normal modern browser every thing is fine. But for a quick solution  this would be very helpful option.
Thanks!

**Comment by kia** [comment]
I think that the value of `mouseWheelScrollSensitivity` is not adjusted when the command palette gets open. Therefor there are large jumps of the cursor when using the mouse wheel.

**Comment by kia** [comment]
Thank you very much @tamayika . You code worked!
I have still a question. Is it possible to change the `mouseWheelScrollSensitivity` for the `editor.contrib.quickInputWidget`? or is there another parameter which i could take for the opened `editor.contrib.quickInputWidget`?

**Comment by tamayika** [comment]
`mouseWheelScrollSensitivity` does not effect in quickInput scroll.
Maybe `mouseWheelScrollSensitivity` is not referenced in quickInput.

**Comment by kia** [comment]
> `mouseWheelScrollSensitivity` does not effect in quickInput scroll. Maybe `mouseWheelScrollSensitivity` is not referenced in quickInput.

i wonder why this is not a problem in a normal browser like firefox or chrome. 

Is there a way to change the scroll behavior of quickInput ? 
what i am doing now is really a dirty hack. I trigger keyDown or keyUp after capturing the scroll events when the quickInfo is open.

**Comment by tamayika** [comment]
Maybe there is a difference between modern browsers and JavaFX WebEngine in scroll behavior.

You can check monaco(vscode) scroll behavior at below codes.
https://github.com/microsoft/vscode/blob/250a8f36c93721830b0ef2e39dc065d6944d9912/src/vs/base/browser/ui/scrollbar/scrollableElement.ts
https://github.com/microsoft/vscode/blob/250a8f36c93721830b0ef2e39dc065d6944d9912/src/vs/base/common/scrollable.ts#L225

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
