### ISSUE TITLE
[Bug] [Monarch] json not working in nextEmbedded

### ISSUE THREAD

**Issue by lennybakkalian** [microsoft/monaco-editor#3507]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monarch Playground Code

```typescript
return {
  tokenizer: {
    root: [
      [/TEST:/, { token: 'keyword', nextEmbedded: 'json', next: '@body' }]
    ],
    body: [
      [/^.+$/, { token: '', log: 'body: $0' }],
      [/^end/, { token: '@rematch', next: '@pop', nextEmbedded: '@pop' }]
    ]
  },
};
```

### Actual (Problematic) Behavior

nextEmbedded: "json" does not work

### Additional Context

Unfortunately monarch does not find the json language. If I replace `nextEmbedded` with e.g. html, the syntax highlighting is correct. But it does not find JSON, although the language is registered in monaco.

**Comment by tamayika** [comment]
This is because monaco json mode does not register monarch tokenizer but tokenize by [manual tokenizer](https://github.com/microsoft/monaco-editor/blob/main/src/language/json/jsonMode.ts#L96).
You can disable manual tokenizer and register monarch tokenizer by `monaco.languages.setMonarchTokensProvider("json", {...})`.

**Comment by lennybakkalian** [comment]
Thanks for the answer. Do you know if there is already a monarch tokenizer for json somewhere?

**Comment by tamayika** [comment]
Sorry, I've never seen it.
