### ISSUE TITLE
doApplyEdits Lines inserted using splice

### ISSUE THREAD

**Issue by cdruine** [Microsoft/monaco-editor#351]
monaco-editor npm version: 0.8.1
Browser:chrome
OS: windows
Using splice for each lines in _doApplyEdits line 630
this._lines.splice(newLineNumber - 1, 0, new ModelLine(newLineNumber, op.lines[j], tabSize));
Could you use just do one insert with all lines because when i insert more than 5000 lines (a collapse/expand "button like" with decoration)  if there is text, but no lines, after the insert point it take less than 1 second but when there's even an empty line after the insert point it took more than 5 seconds ?
I change it myself and even with a lot of lines after the insert point, it's less than 1 seconde to do the insert.

**Comment by cdruine** [comment]
Can you do the modification for speed insert ?
Take a look at this change tested between local editor and the online (//runkit.com/npm/monaco-editor):
Paste more than 20 000 lines take 1 mn with this modif  => 1 sec

                    var insertedLines_1 = this._lines.slice(0, startLineNumber + editingLinesCnt);
                    for (var j = editingLinesCnt + 1; j <= insertingLinesCnt; j++) {
                        var newLineNumber = startLineNumber + j;
                        insertedLines_1.push(new modelLine_1.ModelLine(newLineNumber, op.lines[j], tabSize));
                        //the changed line : this._lines.splice(newLineNumber - 1, 0, new ModelLine(newLineNumber, op.lines[j], tabSize));
                        newLinesContent.push(op.lines[j]);
                        newLinesLengths[j - editingLinesCnt - 1] = op.lines[j].length + this._EOL.length;
                    }
                    this._lines.slice(startLineNumber + editingLinesCnt).forEach(function (item) {  insertedLines_1.push(item); });//not the best one just to show what's done
                    this._lines = insertedLines_1;

**Comment by alexandrudima** [comment]
Thank you for reporting :heart:

I will go with:
```
var before = target.slice(0, insertIndex);
var after = target.slice(insertIndex);
var result = before.concat(insertArr, after);
```

https://jsperf.com/inserting-an-array-within-an-array

**Comment by gdh1995** [comment]
@alexandrudima I find a bug of test code for `splice` in the jsperf test case (https://jsperf.com/inserting-an-array-within-an-array#comment-1) - you forgot to keep `target` readonly.

In my new test case (https://jsperf.com/inserting-an-array-within-an-array-v4/1), although `splice` still wins, the gap is not so large as yours.

In my opinon, `slice`+`concat` only overcomes `splice` **if the array to insert is large enough**, so it may be better to check its length and go into different branches.

**Comment by alexandrudima** [comment]
We now have a different text buffer implementation, so this is no longer relevant for the editor.

See https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation
