### ISSUE TITLE
[Bug] automaticLayout does not work properly inside a grid element.

### ISSUE THREAD

**Issue by sergio-calvo-devo** [microsoft/monaco-editor#3512]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
JavaScript:
let editor = monaco.editor.create(document.getElementById('editor'), {						
    automaticLayout: true,
    theme: 'vs-dark',
});

CSS:
.grid {
  display: grid; 
  padding: 3em; 
}

#editor {
  width: 100%;
  height: 100px;  
}

HTML:
<div class="grid">  
  <div class="grid-item">
    <div id="editor">
    </div>
  </div> 
</div>
```

### Reproduction Steps

Resizing the #editor element (for example, resizing the browser window). 

### Actual (Problematic) Behavior

When displayed inside a grid container and inside an element set to 100% width and enabling the automaticLayout option, the editor resizes properly if the element gets larger, but does not shrink if it gets smaller.

### Expected Behavior

The editor expands and shrinks properly, matching the container's size.

### Additional Context

If the #editor element width is set to another value, like for example 99%, the editor resizes properly.
If the editor is displayed inside a flex container, it also resizes properly.
If a border is added to the #editor element, the element grows infinitely.

**Comment by tamayika** [comment]
Please check this issue.
https://github.com/microsoft/monaco-editor/issues/3393
