### ISSUE TITLE
How does addAction precondition works? What is tokensAtPosition/wordAtPosition?

### ISSUE THREAD

**Issue by FremyCompany** [microsoft/monaco-editor#352]
Hi,

I am a bit at loss on how to achieve the following example found in the Playground gallery but apparently not implemented:

```
// Explanation:
// Try right clicking on an identifier or keyword => the action will be enabled (due to `tokensAtPosition`)
// Try right clicking on a string => the action will be disabled (due to `tokensAtPosition`)
// Try right clicking on whitespace => the action will be disabled (due to `wordAtPosition`)
```

I have the impression the features used by this example no longer works. 
Can you explain how I should use ```precondition``` to achieve the same effect?

What can you write in that string? It seems weird to write code in a string and slightly limiting, but I cannot find what the limitations are.

@alexandrudima #340

**Comment by alexandrudima** [comment]
With our tokenization work for 0.8.0 (where we binary encode tokens colors and no longer hold on to token types in the model), we have lost the ability to target only specific token types from an action -- https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md#tokens-are-styled-in-js-not-in-css-anymore

The precondition usage is similar to the one in this sample - https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance

The idea is that the editor has a context key service, which contains a set of strings -> values. Then, simple expression can be written using those strings. e.g. "findWidgetVisible && editorHasSelection" will evaluate to true only when the find widget is visible and there is something selected in the editor. The set of keys are currently not publicly documented, i.e. use them at your own risk, and can be found in sources or in [various other places](https://github.com/Microsoft/vscode-docs/blob/master/scripts/keybindings/doc.keybindings.win.json)
