### ISSUE TITLE
[Bug] monaco-editor blocks processing mouse move events in view zones

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/monaco-editor#3522]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
Select the "Listening to mouse events" example. After line 37 (in the view zone creation code) add this code, to show some text in the view zone:


    var content = document.createElement("div");
    content.innerHTML = "<div>Try to select this text</div>"
    content.style.userSelect = "text"
    domNode.appendChild(content);


This will add some text in that view zone.
```

### Reproduction Steps

Now try to select that new text. It is not possible. On my local box I can make it work be out-commenting the `e.preventDefault()` call in `mouseHandler.js` (`_onMouseMove` function).

This does not affect the mouse move handling in the editor from what I see.

It is possible to select some text by double clicking it, but of course this is not very comfortable and allows to select at most one single line.

### Actual (Problematic) Behavior

It must be possible to copy text in view zones to the clipboard.

### Expected Behavior

Pressing the left mouse button and moving the mouse should select text in a view zone. Copying selected text works as expected.

### Additional Context

Monaco should not unconditionally stop processing events. Maybe do that only if no mouse event handler is registered in the application? Otherwise, that handler can decide to stop further event processing.

**Comment by hediet** [comment]
Thanks for reporting this! Can you try to debug this? We might be open for a PR here!

**Comment by mike-lischke** [comment]
I debugged it already :-) That's how I found that commenting out the call to `e.preventDefault()` solves the issue. I can certainly file a pull request, but I'm not fully sure if disabling this call does not break anything else. But if someone knowing the internals of monaco-editor does a review then this might work out.

**Comment by mike-lischke** [comment]
I just forked the repo and wanted to fix the problem, but I see the code in `_onMouseMove` has been changed already and the call to `e.preventDefault()` is gone already. I probably just need to upgrade monaco-editor :-) Thanks for listening...
