### ISSUE TITLE
[Feature Request] Ability to load libraries dynamically from remote server

### ISSUE THREAD

**Issue by bostandyksoft** [microsoft/monaco-editor#3528]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I'm sure, that this feature is already exists, but i spent one week for researching and found nothing.

So, the following example in playground shows, that editor could analyze foreign library 

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults

But there is static addition of extra library.

Is there some way to implement dynamic addition extra libraries to editor's environment?
E.g. i have some web file storage and then i setup monaco editor to load files content from this remote file storage.

Also. Is there way to hide extra libraries until it imported?

**Comment by bostandyksoft** [comment]
I found following example, when imports works properly

```
const sourceTest = [monaco.Uri.parse('file:///test.js'), `
import {test2} from './test2';
export function test(message: string): string {
    test2.bar(\`foo \${message}\`);
}`];

const sourceTest2 = [monaco.Uri.parse('file:///test2.js'), `
export function test2(message: string): string {
    console.log(\`bar \${message}\`);
}`];

const sourceIndex = [monaco.Uri.parse('file:///index.js'), `
import {test} from './test'
test('hello world');
`];

var libSource = [monaco.Uri.parse('file:///facts.js'), `
	export class Facts {
	    /**
	     * Returns the next fact
	     */
	    static next():string
	}
    `];

monaco.editor.createModel(sourceTest[1], 'javascript', sourceTest[0]);
monaco.editor.createModel(sourceTest2[1], 'javascript', sourceTest2[0]);
monaco.editor.createModel(libSource[1], 'javascript', libSource[0]);
const model = monaco.editor.createModel(sourceIndex[1], 'javascript', sourceIndex[0]);
monaco.editor.create(document.getElementById('container'), {model});
```
Now, i need a way to dynamically import scripts into editor models collection on demand.

**Comment by tamayika** [comment]
TypeScript Playground can import remote package. (but can not run it).
ATA(Automatic Type Acquisition) is implemented [here](https://github.com/microsoft/TypeScript-Website/tree/bd806902b654ad0b547ada533dd61b0e4e756e59/packages/ata).
And it is used in [here](https://github.com/microsoft/TypeScript-Website/blob/d2e47404530336bd643f1722d505b95023beec9d/packages/sandbox/src/index.ts#L204).

1. When code is updated, ATA tries to get remote package type definition.
2. If successfully finished, update ts compiler options.

**Comment by bostandyksoft** [comment]
> TypeScript Playground can import remote package. (but can not run it). ATA(Automatic Type Acquisition) is implemented [here](https://github.com/microsoft/TypeScript-Website/tree/bd806902b654ad0b547ada533dd61b0e4e756e59/packages/ata). And it is used in [here](https://github.com/microsoft/TypeScript-Website/blob/d2e47404530336bd643f1722d505b95023beec9d/packages/sandbox/src/index.ts#L204).
> 
> 1. When code is updated, ATA tries to get remote package type definition.
> 2. If successfully finished, update ts compiler options.

Thanks for help. But i unable to load this code in my website. It fails when i tried to 

`import * as ts from 'typescript'`

to pass it into setupTypeAcquisition.

Project @typescript/sandbox is weird in my opinion. It is not ready to use by webpack, there is too much dynamic links to node_modules, that absent in runtime environment

**Comment by tamayika** [comment]
I was just giving an example. You can not use it as library.
Please copy everything what you need and modify as you want.

**Comment by bostandyksoft** [comment]
Thank you. I've published small library to parse and load content from certain endpoint 

https://www.npmjs.com/package/imports_resolver

It uses esprima-next library to parse source code.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
