### ISSUE TITLE
[Bug] npm release version is different from CHANGELOG

### ISSUE THREAD

**Issue by romainr** [microsoft/monaco-editor#3530]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Hello,

While trying to find an official npm release (i.e. not a `-dev`) containing a fix for important feature fixes like https://github.com/microsoft/monaco-editor/issues/3449 it feels like we are left in the dark:

- [https://www.npmjs.com/package/monaco-editor?activeTab=versions](https://www.npmjs.com/package/monaco-editor?activeTab=versions) shows `0.34.1`
- [https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0351](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0351) shows `0.35.1`
- Nightly npm is supposedly broken https://github.com/microsoft/monaco-editor/issues/3449#issuecomment-1348604605

What would you recommend for getting a proper build >= 0.34.1?

### Actual (Problematic) Behavior

Both are not in sync:
- [https://www.npmjs.com/package/monaco-editor?activeTab=versions](https://www.npmjs.com/package/monaco-editor?activeTab=versions) shows `0.34.1`
- [https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0351](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0351) shows `0.35.1`

### Expected Behavior

npm and changelog in sync

**Comment by akphi** [comment]
@hediet did we release `0.35.1` ?

**Comment by hediet** [comment]
No, but I will release `0.35.0` very soon.
