### ISSUE TITLE
Bracket Matching Does Not Work For Inner Languages

### ISSUE THREAD

**Issue by hediet** [microsoft/monaco-editor#3534]
[Playground](https://microsoft.github.io/monaco-editor/playground.html) Code:
```js
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

monaco.editor.create(document.getElementById('container'), {
	value: "```js\n()\n```",
	language: 'markdown'
});
```

Notice how brackets are not matched:
![image](https://user-images.githubusercontent.com/2931520/217278618-038f64d4-98a9-412a-ba91-f654c94549af.png)

I believe this is caused by this commit @alexdima (it works with the nightly release before):
https://github.com/microsoft/vscode/commit/cc527241

![image](https://user-images.githubusercontent.com/2931520/217278838-69eaaa40-6836-4879-a98b-07246c8ff7df.png)

**Comment by qqaimh** [comment]
come on ！I need this feature urgently ！

**Comment by alexdima** [comment]
Once https://github.com/microsoft/vscode/pull/175331 lands in `main`, we can adopt `onLanguageEncountered` for loading up configuration files.
