### ISSUE TITLE
[Bug] Using string comparison to highlight function parameters in provideSignatureHelp

### ISSUE THREAD

**Issue by clairewu0218** [microsoft/monaco-editor#3536]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var code = "function hello() {\n\talert('Hello world!');\n\tmyFn\n}";
var model = monaco.editor.createModel(code, 'javascript');

monaco.editor.create(document.getElementById('container'), {
	model: model
});

monaco.languages.registerSignatureHelpProvider('javascript', {
    signatureHelpTriggerCharacters: ['(', ','],
    provideSignatureHelp: function(model, position) {
      return {
         value: {
            activeSignature: 0,
            activeParameter: 0, // you need to change which parameter is typing
            signatures: [{
               label: 'blah(blah, blah, blah)', // siagnature label must be entire function signature
               documentation: 'this method does blah',
               parameters: [{
                  label: 'blah', // parameter label must be partial of signature label
                  documentation: 'this param does blah1',
               }, {
                  label: 'blah', // parameter label must be partial of signature label
                  documentation: 'this param does blah2'
               }, {
                  label: 'blah', // parameter label must be partial of signature label
                  documentation: 'this param does blah3'
               }]
            }]
         },
         dispose: () => {},
      };
   }
});
```

### Reproduction Steps

Type
```
function hello() {
	alert('Hello world!');
	myFn()
}
```

### Actual (Problematic) Behavior

It seems Monaco uses string search/comparison when highlighting function/parameter names in signature help, instead of using `activeParameter` as an index to locate the active parameter.

The first case is that if the function name is the same as any of the parameter name, it will highlight the function name instead of the parameter name.
![image](https://user-images.githubusercontent.com/104450101/217379332-38b0afd4-3fa5-4ce9-b3e5-672b6592006a.png)
In this screenshot, 'this param does blah1' shows that the active parameter is the first parameter, but it's highlighting the function name.

The second case is that for variadic functions, such as `Max(number, number, number)`, it will always only highlight the first parameter. Modify the label to be `fx(blah, blah, blah)` in the playground code, it will look like this
![image](https://user-images.githubusercontent.com/104450101/217381091-a9585105-a923-421f-94d6-af3b2bfb5a74.png)

### Expected Behavior

Monaco should highlight the correct parameter in the previous cases.

From your document, it seems that [SignatureHelp.activeSignature](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.SignatureHelp.html#signatures) and [SignatureInformation.activeParameter](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.SignatureInformation.html#activeParameter) should bring some help in locating the active parameter but it seems to be not working.

**Comment by tamayika** [comment]
You can also specify range as label.
Range is inclusive start and exclusive end.
Monaco Editor API: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.ParameterInformation.html#label

If you need more details about Monaco Editor API, please also refer VSCode Extension API and LSP Spec.
These APIs are not completely the same, but useful for understanding APIs.
VSCode Extension API: https://code.visualstudio.com/api/references/vscode-api#ParameterInformation
LSP Spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#parameterInformation

```
monaco.languages.registerSignatureHelpProvider('javascript', {
    signatureHelpTriggerCharacters: ['(', ','],
    provideSignatureHelp: function(model, position) {
      return {
         value: {
            activeSignature: 0,
            activeParameter: 0, // you need to change which parameter is typing
            signatures: [{
               label: 'blah(blah, blah, blah)', // siagnature label must be entire function signature
               documentation: 'this method does blah',
               parameters: [{
                  label: [5, 9], // signature label range
                  documentation: 'this param does blah1',
               }, {
                  label: [11, 15], // signature label range
                  documentation: 'this param does blah2'
               }, {
                  label: [17, 21], // signature label range
                  documentation: 'this param does blah3'
               }]
            }]
         },
         dispose: () => {},
      };
   }
});
```

**Comment by hediet** [comment]
@tamayika thanks for helping!
