### ISSUE TITLE
[monarch] Is there a way for the `nextEmbedded` to tell what state to start in?

### ISSUE THREAD

**Issue by AndersMad** [microsoft/monaco-editor#355]
monaco-editor npm version: 0.8.1
severity: nice to have

I call `nextEmbedded: 'css'` but I would like it to start in `@selectorbody`. The workaround have been to maintain a clone of css.ts as css-inline.ts. So e.g. `nextEmbedded: 'css.@selectorbody'` to push a state in or simply start at that state since it should never pop.

Why: Using this we can tokenize parts of a language. I have successfully added autocomplete, lint and color decorators to CSS inline `style="color: red"` attribute for Razor/HMTL - but I have had to clone some language .ts files for only a few small changes. Above could avoid some of that.

**Comment by hediet** [comment]
Can you share example grammars that show
* how you the solve your problem currently
* and how you would like to solve it with the requested feature?
Thanks!

**Comment by AndersMad** [comment]
I will close this because as in my case I ended up doing extra things (yet another macro language) inside the css-inline.ts clone anyways
