### ISSUE TITLE
[Bug] Cannot adjust minimap settings from the editor.

### ISSUE THREAD

**Issue by EmiastroCat** [microsoft/monaco-editor#3559]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

- After editor loaded, Right click minimap
- Adjust settings
- But there was no response
![gif](https://user-images.githubusercontent.com/63448263/219038266-579ab5b9-c528-4e0a-96f5-1345b4fb1584.gif)

### Actual (Problematic) Behavior

In the local development environment, devTool will report an error：`DevTools failed to load source map: Could not load content for http://localhost:4200/min-maps/vs/base/common/worker/simpleWorker.nls.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`.

### Expected Behavior

Can adjust minimap by setting in the editor

**Comment by hediet** [comment]
These options shouldn't be available in monaco editor (similar to #2940).

**Comment by EmiastroCat** [comment]
So will these options will be removed later?  These options seems to have existed since version 0.34.0.

**Comment by CGNonofr** [comment]
Note that you can still override the configurationService while creating the editor to implement the `updateValue` method
