### ISSUE TITLE
How save and open a file?

### ISSUE THREAD

**Issue by RealAquilus** [Microsoft/monaco-editor#356]
monaco-editor npm version: 0.X.Y
Browser: Chrome
OS:  Windows
I know i know, is a really noob question but i can't get out :C 
Forgive me i'm new to the JavaScript world and i wanted only to do a simple editor using this amazing framework!
Thanks to the guys that will help me.
(For now my code is the basilar for get Monaco work,
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
</head>
<body>

<div id="container" style="width:99%;height:900px;border:0px solid black"></div>

<script src="monaco-editor/min/vs/loader.js"></script>
<script>
    require.config({ paths: { 'vs': 'monaco-editor/min/vs' }});
    require(['vs/editor/editor.main'], function() {
        var editor = monaco.editor.create(document.getElementById('container'), {
            value: [
                'function x() {',
                '\tconsole.log("Hello world!");',
                '}'
            ].join('\n'),
            language: 'lua',
            theme: "vs-dark"
        });
    });
</script>
</body>
</html>
i have tryied adding two buttons and the relative fuction but still not working.
(Sorry if i did some grammatical error, my english is not so good)

**Comment by JKillian** [comment]
@RealAquilus this is basically up to you. Monaco itself doesn't tell you how files have to be saved/opened. You could save them to a server, save them to localstorage, etc etc

**Comment by RealAquilus** [comment]
I would like to save them locally, as VSCODE.
I tried adding two buttons, one to save and one to open the file.
But the "onclick" functions do not work, I tried inserting some alert here and did not take the right ...
So I would like it if someone could help me with some sample code.
I don't like ask code, but after some hours of trying i get nothing so i don't really know what do...

**Comment by NeekSandhu** [comment]
You can't save to operating system's filesystem from a browser

**Comment by alexandrudima** [comment]
From a browser, as @NeekSandhu mentions, you cannot read or write directly to the user's HDD. You would need from the browser to communicate to some sort of backend (XHR requests possibly) and save the files on your backend. You could e.g. write a node server which you would run locally and connect your browser to it via `localhost`. Then, from your browser window you can make an XHR request with the file to open / to save / etc and you could then read/write to the fs from nodejs.

**Comment by russWackyH** [comment]
Love how NO ONE answers the question.
