### ISSUE TITLE
[Bug] cannot deep link into the documentation

### ISSUE THREAD

**Issue by bolinfest** [microsoft/monaco-editor#3563]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

n/a

### Monaco Editor Playground Code

```typescript
// n/a
```

### Reproduction Steps

1. Go to https://microsoft.github.io/monaco-editor/docs.html
2. Click on links to API members

### Actual (Problematic) Behavior

URL does not change.

### Expected Behavior

URL should change so that it can be shared and return to the current page. I want to send someone a pointer to the new `registerInlineCompletionsProvider()` API, but I can't since there's no explicit URL for it.

### Additional Context

I'm pretty sure this used to work?

**Comment by bolinfest** [comment]
I'm not sure this is quite right...

1. Go to https://microsoft.github.io/monaco-editor/docs.html
2. Clicking on `IPosition` changes the URL to https://microsoft.github.io/monaco-editor/docs.html#interfaces/IPosition.html (good!)
3. Clicking on `lineNumber` changes the URL to https://microsoft.github.io/monaco-editor/docs.html#interfaces/IPosition.html#lineNumber (not so good)

**Comment by hediet** [comment]
> Clicking on lineNumber changes the URL to https://microsoft.github.io/monaco-editor/docs.html#interfaces/IPosition.html#lineNumber (not so good)

Why is this not so good?
