### ISSUE TITLE
[Bug] OnTypeFormattingEditProvider is not called (regression)

### ISSUE THREAD

**Issue by jmue** [microsoft/monaco-editor#3564]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

This a regression, it is broken since 0.35.0-dev.20221126

https://github.com/microsoft/vscode/compare/2eca6d38dede985bf6180cca64d43c16a02e9a13...fd8c9037af02c02bf0c38af008a69d78f033f942

### Monaco Editor Playground Code

```typescript
monaco.languages.register({ id: "mySpecialLanguage" });

monaco.languages.registerOnTypeFormattingEditProvider("mySpecialLanguage", {
	autoFormatTriggerCharacters: ['a', 'b', ','],
	provideOnTypeFormattingEdits: () => {
		return [{
			range: {
				startLineNumber: 1,
				endLineNumber: 1,
				startColumn: 1,
				endColumn: 3
			},
			text: "edited"
		}];
	}
});

monaco.editor.create(document.getElementById("container"), {
	value: getCode(),
	language: "mySpecialLanguage",
	formatOnType: true,
});

function getCode() {
	return [
		"hello world",
	].join("\n");
}
```

### Reproduction Steps

1. Start the sample provided 
2. type on of the trigger characters 'a', 'b' or ','
3. See that nothing happens

### Actual (Problematic) Behavior

The registered OnTypeFormattingEditProvider is not called on provided trigger characters.

### Expected Behavior

The registered OnTypeFormattingEditProvider is called on provided trigger characters.

**Comment by jrieken** [comment]
verified in code
