### ISSUE TITLE
[Bug] stickyScroll ignores maxLineCount? Only sticks 1 line

### ISSUE THREAD

**Issue by AndersMad** [microsoft/monaco-editor#3565]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#XQAAAAL4AQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0TKWpjN898w8vXcYTGSMs5sUpNh6UB0XRaMhEtbSa7F_AYLMU68VMTzjdzbgpvNt8twSv1rycxa4dRmOnhf8zLGscpbBj3ASW9PDifqh6m5IIQMyYLtU28MN9DGBsCDMKnXJJyCWpQ1PA45TQlCruVoD-ddznQDPqBZ0CYMLRQKAtBYaW73bNcLG82Lgy-NcbqMAG9IIaW4jSihFywEoliD7pc9slSBBLQHAriDPH2m9ShKH1E6LhHH73A5hr1cG7IRzldCrHwC_-puFHPCqhP_xDKII

### Monaco Editor Playground Code

```typescript
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n\nfunction hello() {\n\talert('Hello world!');\n\nfunction hello() {\n\talert('Hello world!');\n\nfunction hello() {\n\talert('Hello world!');\n\nfunction hello() {\n\talert('Hello world!');\n\n};\n};\n};\n};\n};",
	language: "javascript",
	stickyScroll: {
		enabled: true,
		maxLineCount: 5
	},
});
// no editor onReady :/
setTimeout(() => editor.trigger("setValue", "editor.action.formatDocument", null), 500);
```

### Reproduction Steps

Scroll down

### Actual (Problematic) Behavior

It only/barely sticks 1 of the lines `function hello() {`

### Expected Behavior

Each function should be sticked as it does in vscode app + vscode.dev (works in both)
![image](https://user-images.githubusercontent.com/4574570/219371932-4a5f9ac9-be90-4181-8a42-ebf19ea70f2a.png)

**Comment by hediet** [comment]
@aiday-mar can you look into this?

**Comment by AndersMad** [comment]
Just a minor FYI: Without going into reading "all the source" - I hacked it for now in `getCandidateStickyLinesIntersectingFromOutline` where I changed the `for (let i = lowerBound; i <= upperBound; i++) {` to `for (let i = 1; i <= outlineModel.children.length; i++) {`

P.S. [README.md](https://github.com/microsoft/monaco-editor#readme) has a bad link to "try it out" / playground
