### ISSUE TITLE
[Feature Request] Inherit overridden services when creating editors

### ISSUE THREAD

**Issue by FSDRE** [microsoft/monaco-editor#3569]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Until 0.34.1 we could do this in order to override what happens when executing GoToDefinition:

``` csharp
const editorService: any = (editor as any)._codeEditorService;

if (editorService == null) {
    return;
}

editorService.openCodeEditor = this.goToDefinitionAction.bind(this);
```

Sure, it is against the typing but at least it worked. In 0.35 `_codeEditorService` is not there anymore.

If I go the route of `IEditorOverrideServices` at editor creation time and provide

``` typescript
{
    codeEditorService: {
        ....
    }
}
```

I have to implement the whole thing (which I can't and honestly don't want just in order to substitute the "open" logic). Is there a possibility in 0.35 so that I can only overwrite `openCodeEditor` of the `codeEditorService`?

Wouldn't it be nice if the services only substitute the properties that are actually provided and use the original base logic for the rest?

We actually run Monaco in a CEFSharp environment and on GoToDefinition we want to jump out of the editor and do something else in the .NET host that has nothing to do with the model currently shown in the editor.

**Comment by hediet** [comment]
> I have to implement the whole thing (which I can't and honestly don't want just in order to substitute the "open" logic). Is there a possibility in 0.35 so that I can only overwrite openCodeEditor of the codeEditorService?

You could inherit from `StandaloneCodeEditorService` and override the methods you are interested in. This class is not part of the API, but it is still exported.

**Comment by FSDRE** [comment]
I'll try that then, thank you

**Comment by FSDRE** [comment]
@hediet The `StandaloneCodeEditorService` deends on 

``` typescript
constructor(contextKeyService, themeService)
```

Do I have to also extend these or is there a possibility to get those instances from the editor?

**Comment by hediet** [comment]
You can inject them somehow.
