### ISSUE TITLE
How to detect `Cannot find module` error to on-demand call addExtraLib?

### ISSUE THREAD

**Issue by czb** [Microsoft/monaco-editor#357]
I would like to detect when "Cannot find module" in Typescript occurs, get the path of the module and then on-demand download the file and and put it into `addExtraLib`.

How can I do that?

**Comment by jrieken** [comment]
You cannot do that with monaco-typescript which is purpose-fully kept simple in this regard. The design is that the *project* needs to be resolved upfront. Also, the underlying TypeScript API don't support to asynchronously feed in more source files. Things must be resolved synchronously.
