### ISSUE TITLE
SuggestionController: can't select a specific suggestion [Bug] 

### ISSUE THREAD

**Issue by mistralaix** [microsoft/monaco-editor#3576]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html#XQAAAAJnBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw6mMcLumT4xlriCr_BlYOYFvZZAb9x3ZCMQuKPOACbGU0mipQ-t5ZWpnre6lkXmgPJapLF9AR8IO7doiBBXNxjwoqm-Nkg96jWz_DHLksPGK4VM3VZw4ysSHHBdMA2LaEdnAMyJHB1I0J4kD9Q8XffhXlNbn6fKSDM9q4GyRMIJzJ2dO_qQmyo9Ks6cqf8mMG4L5aOwI5KWJv_N-bxaHaSk4frbMNEJAfst8SEKT-V5ej80jzE8gvNpsAAxUft1-3l5oUKptwLVmrVCtt8ob5DmwoEWvJFtPUpXStGSR9gQf7J3ERgs5bY1rf_Z1uTq0RqHVYHViFT-GgXUPVA5xpGYXg5xH7lIU61ZpzT1QFktw64-DFvNYOPTxN6vuE-XMAs8kVIbxSbDRhX7negpOab48m-Vafe2fn0Qh5tYl2fqTMU2_c3gujycEA1Sxokqq8fchzwmdwXTqmQYUvYyhvD6zm-Su36cNqwMN2IdK1pmbawZTd8RrapJLDf94B5Ggp8V3DbhQkyX8n_kRyHDNnb50KE2hf02w_f8NWIJbAsnKRYntF3_F5KCPuWi4QHXRhrMWDEJ3jM-dcExCEwiH_z-56yLFmVJxgWeQeaOtdMm89yXtKfZIwGPuzUBiovCij__dt8qk

### Monaco Editor Playground Code

```typescript
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

const editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
});

function selectSuggestion() {
	editor.trigger('keyboard', 'editor.action.triggerSuggest', null);

	setTimeout(() => {
		const widget = editor.getContribution('editor.contrib.suggestController').widget;

		// Move the focus to the second suggestion
		widget.next();
		// Accept the suggestion
		widget.acceptSelectedSuggestion();
	}, 100);
}

function selectSuggestion2() {
	editor.trigger('keyboard', 'editor.action.triggerSuggest', null);

	setTimeout(() => {
		const widget = editor.getContribution('editor.contrib.suggestController').widget;

		widget.select(widget.getSuggestionDetails(0), true);
	}, 100);
}

setTimeout(() => {
	// selectSuggestion();
	selectSuggestion2();
}, 5000);
```

### Actual (Problematic) Behavior

I am able to get the current suggestions thanks to this code:
`editor.getContribution("editor.contrib.suggestController")?.model?.onDidSuggest((event) => {})`

Now, I would like to manually select a specific suggestion. I provided the different methods that I've tried but none seems to work.

Thank you for your help!

**Comment by hediet** [comment]
This does not look like a bug report. Please fill out the form properly or use the form for a feature request. Thanks!
