### ISSUE TITLE
[Bug] DefaultConfigurationModel is not exported by "monaco-editor/esm/vs/platform/configuration/common/configurations.js"

### ISSUE THREAD

**Issue by dxgi** [microsoft/monaco-editor#3577]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

https://github.com/dxgi/lsp-client

### Actual (Problematic) Behavior

 DefaultConfigurationModel is not exported by "monaco-editor/esm/vs/platform/configuration/common/configurations.js", imported by "vscode/dist/polyfill.js"

![image](https://user-images.githubusercontent.com/61899298/219940191-b0aeeae6-10f1-4057-8564-9415d3e0fde6.png)

### Expected Behavior

Should work perfectly fine when building and compiling.

### Additional Context

I'm using Vite-TS

package.json
```json
{
  "name": "lsp-client",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@types/ws": "^8.5.4",
    "monaco-editor": "^0.35.0",
    "monaco-editor-core": "^0.35.0",
    "monaco-languageclient": "^4.0.3",
    "reconnecting-websocket": "^4.4.0",
    "stylua-wasm": "^0.1.4",
    "vscode-ws-jsonrpc": "^2.0.2",
    "vue": "^3.2.45",
    "ws": "^8.12.1"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "typescript": "^4.9.3",
    "vite": "^4.1.0",
    "vue-tsc": "^1.0.24"
  }
}
```

**Comment by tamayika** [comment]
This is not monaco-editor issue.
You are using monaco-languageclient and its dependency `https://github.com/CodinGame/monaco-vscode-api` as vscode.
And `CodinGame/monaco-vscode-api` does not support monaco-editor 0.35.0.
Please file the issue at `CodinGame/monaco-vscode-api` repository.
