### ISSUE TITLE
import "./test" vs import "/test" 

### ISSUE THREAD

**Issue by oldrich-s** [microsoft/monaco-editor#358]
In the [playground](https://microsoft.github.io/monaco-editor/playground.html) this works:

    monaco.languages.typescript.typescriptDefaults.addExtraLib(
        'declare module "/test" { export declare var a: number }');

    monaco.editor.create(document.getElementById("container"), {
        value: "import * as t from '/test'\nvar b = t.a",
        language: "typescript"
    });

while this does not work:

    monaco.languages.typescript.typescriptDefaults.addExtraLib(
        'declare module "./test" { export declare var a: number }');

    monaco.editor.create(document.getElementById("container"), {
        value: "import * as t from './test'\nvar b = t.a",
        language: "typescript"
    });

Why is that?

EDIT:

BTW the same goes for:

    monaco.languages.typescript.typescriptDefaults.addExtraLib(
        'declare module "/../test" { export declare var a: number }');

    monaco.editor.create(document.getElementById("container"), {
        value: "import * as t from '/../test'\nvar b = t.a",
        language: "typescript"
    });

versus

    monaco.languages.typescript.typescriptDefaults.addExtraLib(
        'declare module "../test" { export declare var a: number }');

    monaco.editor.create(document.getElementById("container"), {
        value: "import * as t from '../test'\nvar b = t.a",
        language: "typescript"
    });

**Comment by alexdima** [comment]
This is rather complex, but to get relative imports to work you need to:
* create the editor with `{ model: null}`
* create models by yourself via `monaco.editor.createModel` and then give each model an URI which makes sense, e.g. `file:///a.ts` and `file:///b.ts`.
* use `monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true)` and `monaco.languages.typescript.typescriptDefaults.setMaximumWorkerIdleTime(10000000)`
