### ISSUE TITLE
[Bug] Custom editorService is not working (for go to definition functionality)

### ISSUE THREAD

**Issue by manikantag** [microsoft/monaco-editor#3592]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#XQAAAALdAwAAAAAAAABBqQkHQ5NjdMYoy-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc-XFblIiwhHvuv03tb7swkjAYKW5fZE3JUfA7biQGIdeEJI_F3sceW5oEhyc6vHeBXt1t-TBvNgFFEPzh7EDKP_X67jcqySK8hMRBtcBf2O4ZaJgpixSt7yIQhpMVSQRmTSCU7xxs6h4IBhXBjjrIRNE5bOXJbpgw4OQS6KZjmQF_3NPR1h5BUauPLGgJblPaamyA81A3KDi5YeaUKN1UmeIf5biQM_8PT6FZIXUmItqfsstL7nx_qRry2efNOGVg_3evS5NCJCIfLIEEpc6aLprahPKckjh4o_pRbucY2_QY0QKbiNZhcCVdcg6QmwW8cRxiOQ53i_1XLuF6NhYjYMoyH4TfiZHjS19oryXFhV9BnmdpaFeEyAbvrCc897wuRFTx23EK8Mdv93NpnNxYbIGpph5m14RIlVFfElUuf_dGEoRtSVIy0r0_0lLohoM9CEqrpEPW0ydDB4bjwr4MLnQhqjtt3rHE-lPRr9fdnN7g7sZxrecc6JMd1kVEL6wnDp_uVJ_fUiQvE

### Monaco Editor Playground Code

```typescript
var openerService = {
	open: function() {
		console.log(`open called!` + JSON.stringify(arguments));
	}
};

var editorServiceOverride = {
    openEditor: function() {
        console.log(`open editor called!` + JSON.stringify(arguments));
    },
    resolveEditor: function() {
        console.log(`resolve editor called!` + JSON.stringify(arguments));
    },
    findModel:function(editor, data) {
        console.log(`resolve editor called!` + JSON.stringify(arguments));
    }
};

var model_fns = monaco.editor.createModel('function testfn() { return "1"; }', 'javascript', monaco.Uri.from({scheme: 'file', path: 'dir1/dir2/fns.js'}));
var model = monaco.editor.createModel('// http://www.microsoft.com\ntestfn();', 'javascript');

var editor = monaco.editor.create(
    document.getElementById('container'),
    { model },
    {
        openerService: openerService,
        editorService: editorServiceOverride
    }
);
```

### Reproduction Steps

Try to 'Go to Definition' on the `testfn()`

### Actual (Problematic) Behavior

No debug logs are seen in the console which means the editorService override is not working (In reality, this will try to open `model_fns` model in the editor)

### Expected Behavior

Should see the debug logs in the console.

### Additional Context

I followed below issues and comments to come up with the test code.

https://github.com/microsoft/monaco-editor/issues/291#issuecomment-310615350 (and https://github.com/microsoft/monaco-editor/issues/291#issuecomment-459502178)

I see `openerService` logs when clicked on the website link. But when I try the same with `testfn()`, `editorService` overrdies are not logging.

**Comment by manikantag** [comment]
Other suggestions like https://github.com/microsoft/monaco-editor/issues/291#issuecomment-877818216, https://github.com/microsoft/monaco-editor/issues/2407#issuecomment-804817942, https://github.com/microsoft/monaco-editor/issues/2407#issuecomment-804828273 doesn't work with `0.35.0` version as the internal API is obfuscated.

**Comment by hediet** [comment]
Can you try to find a version in which it worked?

**Comment by WNemencha** [comment]
this would be fixed by https://github.com/microsoft/vscode/pull/177064
