### ISSUE TITLE
How to add error highlights for Importing Unknown Packages or Modules in Monaco Editor for newly registered Language Java?

### ISSUE THREAD

**Issue by LavanyaBurlagadda** [microsoft/monaco-editor#3594]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual (Problematic) Behavior

Currently we are integrating Java Language Server to Monaco Editor. There when I am trying to import unknown modules or packages it is not throwing warning or errors.No Error for Unknown Package. Tried using Tokenizer but didn't worked out.

![image](https://user-images.githubusercontent.com/48449639/221093771-f420045f-eeee-4389-95c7-2524af47de8e.png)

### Expected Behavior

When I am importing any unknown package or error I want error some thing red lines below the package name. Similar to how we will get for typescript. I want to know how to add these type to monaco editor for a new language that we are registering.
![image](https://user-images.githubusercontent.com/48449639/221093835-eaefade7-e44d-48c9-8903-dc57ad8baa37.png)

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
