### ISSUE TITLE
Transpiling TypeScript to JavaScript and SASS/LESS to CSS

### ISSUE THREAD

**Issue by jonathanhotono** [microsoft/monaco-editor#36]
Is there any method to transpile/compile the typescript to javascript and SASS/LESS to CSS just like what we have in typescript playground?

Thanks

**Comment by alexandrudima** [comment]
fyi @aeschli @jrieken

**Comment by jscsharp** [comment]
It seems, the typescript object is available (ie: ts) , so it is possible to use 

ts.transpile(myTSCode);

 and get back js code.

**Comment by jonathanhotono** [comment]
Hi Guys,

#35 might be related to this and it has been closed with a pull request (https://github.com/Microsoft/monaco-typescript/pull/8).

The method that I found from typescript playground does provide a "getEmitOutput" prototype which emits the js output. Is there any sample code on the "Promise'ified " version?
![image](https://cloud.githubusercontent.com/assets/6864547/18090511/726ecbf8-6f08-11e6-8978-82442d7afd77.png)

**Comment by alexdima** [comment]
This can be done outside of the editor using existing editor API.
