### ISSUE TITLE
Diff view options for case insensitivity and intra-line whitespace difference ignore

### ISSUE THREAD

**Issue by mattgodbolt** [microsoft/monaco-editor#360]
monaco-editor npm version: 0.8.0
Browser: All
OS: All

I'm using monaco's diff view to show differences between different compiler output, and a requested feature is to ignore intra-line whitespace and make the diff case insensitive. For example: https://godbolt.org/g/rAaEha shows intra-line whitespace differences.

**Comment by olane** [comment]
+1 on whitespace insensitivity. It's possible to condense all mid-line whitespace into a single space before adding to the diff but it's not particularly elegant, and sometimes breaks formatting for things like comments.

**Comment by hediet** [comment]
You can get this feature by customizing the diff algorithm.
