### ISSUE TITLE
[Bug] [0.36.0] dependencies accidently installed?

### ISSUE THREAD

**Issue by AviVahl** [microsoft/monaco-editor#3601]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

`npm i monaco-editor`

### Actual (Problematic) Behavior

Since this commit: https://github.com/microsoft/monaco-editor/commit/10577a0641d9a12308e77a3116e5896da9f3d70f#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

3 dependencies are now installed for monaco-editor consumers:
```json
{
	"dependencies": {
		"@types/shelljs": "^0.8.11",
		"pin-github-action": "^1.8.0",
		"shelljs": "^0.8.5"
	}
}
```

### Expected Behavior

I'm guessing these should be devDeps

**Comment by artola** [comment]
Yes, I got the same. This PR introduced all these as `dependencies` when they should be declared as `devDependencies`:

https://github.com/microsoft/monaco-editor/commit/10577a0641d9a12308e77a3116e5896da9f3d70f

@hediet is it right? I got around 20 new dependencies installed.
@alexdima Are you planning a new release with a fix?

**Comment by hediet** [comment]
Thanks for point this out!
I accidentally added these dependencies as normal dependency, though they should have been dev dependencies.
