### ISSUE TITLE
[Bug] view zones fail to show at empty lines with hidden areas downside

### ISSUE THREAD

**Issue by ensorrow** [microsoft/monaco-editor#3608]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[monaco playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.0#XQAAAALJCgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxJgW9ZzFWtoIlelWaKUmXaJ2qI2Mq9sv8BEYnm73B8SrDwdJv_xsq194pRbHEUkWMZDmb8cW0IjehEwI9e-mWq-OhHc8pQC9ve4Y_AJEVpM9h5tk8zt-bHLLCWBKRs9IiLDmoU9ySEXAsGSV2JfePvN1llQHh6xs3CqPb7Ciem9xFJFg-wX03zH2ZW4sd71BPwqD9F1p1XM-NxPawOLrlzaLY1gCeq9_BopAQG_dFqV8J93Ior9x3GkFCGjEPmCd4bLXnqDGq-Vb4Jo84HVGyUYd8ryhnu3ds1mvM6r_gjaX1_cavL4HUtkx2stcOFIj8sIhzOhpJ-3XWWuQZApjndGkoHieTrL67_bI6mOzzBzI9d0LP4n10W1XuylHsT52fyA0DuEPfZsTe5dsHCMCAIdnv5d5jjIEC25ksp5Qxi-Dtqd41-7fXaIW0v96vKK0h1Uu_5oQqCahDpzH791PRDYg0eAptjj7Yf69s88NfL5xi3d5Fpz8Ny4tT2b3mgsO6iobd6XQs1BoAEJNHCUdDVTFpKXulQIPIeR5r4mJ9DC8kjcFDoyCuSGOiTH2Fv3Ksoq-z_Z3gb2jF7ROQvvuHKYvPKmgHY5Ry7fJuPE4dnjdnDHFh2JV3nojSLcv_Aa6sx_r0Mc4gdTxbDro4RtQjLZ2YGLKT6HL3F1r50Xy1-IxWfYPn9GCWeIS4MsWqsenBK-VOjRdQDvXhTN_Pqi1U3owcaB79lxsPNZZey1HZqmiPLsqDw0zg7ObLThxQnCQckUOr0AdPrYAQP3EMzAXrxLHtEB0YRc7G4eYu6NzH-sULxSFpaUKHzaglNzhQpdqmL5DygQye6nXIwWu_zIXIEU1YKYVfutS3RjBVnZvt7LnB96fmCXUk2jy0nYj7_hUjz136GlVxIH4ZOyEmF4Yp4EkbtUeiI3wkrZRhN9XG9phTe862vbd3rh5Kna_btj3IW_26G8Etu4n5HKLapBkFkuX9pwUirHmiQ914mXUM7ZpPgyVa7I2vC9_M4UrEBKy55gBtYBRXdrnY9G5ixch1-7CutQvljX2lJQ7_6Lw2ag)

<img width="1683" alt="image" src="https://user-images.githubusercontent.com/13199771/221573762-34bd1090-3628-407e-8c26-60a68bf7b8a3.png">

### Monaco Editor Playground Code

```typescript
var originalModel = monaco.editor.createModel(`html, body {
  margin: 0;
  overflow: hidden;
}

div#container {
  height: 100vh;
  width: 100vw;
} 

div#app {
  height: 100%;
}

div.repo-dashboard {
  height: 100%;
}

div.repo-header {
  height: 50px;
}

div.repo-header h1 {
  margin: 0px;
}

div.graph-viewer {
  height: calc(100% - 50px);
  overflow-y: scroll;
}

div.commit-graph {
  width: 50%;
  display: inline-block;
}

div.commit-graph canvas {
  display: block;
  float: right;
}

div.commit-list {
  width: 50%;
  display: inline-block;
}

div.commit-list ul {
  margin: 0px;
  padding-left: 20px;
  list-style: none;
  line-height: 22px;
}

div.commit-list li {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  height: 22px;
  padding-top: 3px;
  padding-bottom: 3px;
}`, "text/plain");
var modifiedModel = monaco.editor.createModel(`html, body {
  margin: 0;
  overflow: hidden;
}

div#container {
  height: 100vh;
  width: 100vw;
} 

div#app {
  height: 100%;
}

div.repo-dashboard {
  height: 100%;
}

div.repo-header {
  height: 50px;
}

div.repo-header h1 {
  margin: 0px;
}

div.graph-viewer {
  height: calc(100% - 50px);
  overflow-y: scroll;
  position: relative;
}

div.commit-graph {
  width: 50%;
  position: absolute;
  z-index: 2;
}

div.commit-graph canvas {
  display: block;
  float: right;
}

div.commit-list {
  width: 100%;
  position: absolute;
  left: 0px;
  z-index: 1;
}

div.commit-list ul {
  margin: 0px;
  padding-left: 0px;
  list-style: none;
  line-height: 22px;
}

div.commit-list li {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  height: 22px;
  padding-left: calc(50% + 20px);
  padding-top: 3px;
  padding-bottom: 3px;
}

div.commit-list li:hover {
  background: #eee;
}`, "text/plain");

const options = {
    renderSideBySide: true,
}

var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"), options);
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel
});

function createRange(start, end) {
    return {
        startLineNumber: start,
        endLineNumber: end 
    }
}

diffEditor.getOriginalEditor().setHiddenAreas([
    // createRange(1, 26),
    createRange(42, 47),
    createRange(53, 55),
])

diffEditor.getModifiedEditor().setHiddenAreas([
    // createRange(1, 26),
    createRange(44, 51),
    createRange(57, 59),
])

diffEditor.getModifiedEditor().changeViewZones((changeAccessor) => {
    function addZone(start) {
        changeAccessor.addZone({
            afterLineNumber: start,
            heightInLines: 2,
            domNode: document.createElement('div'),
        });     
    }

    addZone(10);
    addZone(43);
})
```

### Reproduction Steps

1. fold area [44,51] in modifed editor (while line 43 is empty)
2. add view zones at line 10 and line 43
3. view zone at line 43 will not show

### Actual (Problematic) Behavior

view zone at line 43 doesn't not show

### Expected Behavior

view zone at line 43 show as same as view zone at line 10

### Additional Context

I debug into the code, and found the recently added fix for [Codelens flashing after folding](https://github.com/microsoft/vscode/issues/121516), view zones in hidden areas will be hidden, that's fine. But with empty lines, the logic is weird. (If `zoneAfterModelPosition.lineNumber` is an empty line, the `zoneBeforeModelPosition` will be on the next line, and I cannot understand why)

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/13199771/221572977-afedb2d8-b3ff-4ccf-9ab6-8a5de5397f61.png">

**Comment by hediet** [comment]
Can you try out previous versions of the monaco editor in the playground? What's the last version this has been working?

**Comment by ensorrow** [comment]
This issue is introduced when fixing the issue https://github.com/microsoft/vscode/issues/121516, I use monaco 0.29.x and it works well.

**Comment by hediet** [comment]
These images look the same though:

![image](https://user-images.githubusercontent.com/2931520/222394236-37b47740-e4b3-4879-8e87-34efd11e4194.png)

![image](https://user-images.githubusercontent.com/2931520/222394277-184de6a6-bc41-4317-a905-8c59a875bc32.png)
