### ISSUE TITLE
[Feature Request] Support intellisense for AMD modules

### ISSUE THREAD

**Issue by manikantag** [microsoft/monaco-editor#3616]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I want to support intellisense with in AMD modules (which are loaded using requirejs.). I created models for all the modules, but when I refer one of the module in another, I don't get any intellisense about the available properties/functions of the dependencies. For example, given:

dep1.js:
```javascript
define("dep1", [], function () {
    return { foo: { bar: 123, aaa: 456 } } 
});
```

dep2.js:
```javascript
define(['dep1'], function (dep1) {
    console.log(dep1.foo.bar);  // <----- I want to get auto completions from `dep1`
});
```

What would be the best way to achieve this? Is there a way I can specify the prototype of a variable word? I looked at '[Configure JavaScript defaults](https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#example-extending-language-services-configure-javascript-defaults)' playground example too.

_I tried asking this [question in StackOverFlow](https://stackoverflow.com/questions/75438369/monaco-editor-intellisense-for-amd-modules) couple of weeks ago, but no luck._

Thanks.

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAKhAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4iApJ7XTDEjmw5QDdXTTvRJifGnKowyLpe43kaRSElIiG8w6DEgUzmuvsL0kjEjoFa5Br1HltYPAMn-clzdiMaA560R30IagT11lwDue0aRHVWq_aSw5zqf9Bxj5uUwxAP2_8fRS65Ve-lgxOC2AHiOKF2kNpWMPb52kgS4IVaGVU3Yprh7eqnzDFDyOb7lrfIJU8GcCWKpHK_og-BrC5ax7KK6xH-QtANBb5UddrQZhijk0eD0v3DElfEquYyzQwmO5JudaNAeJ9zzc_2GrO_bKtvF_p3yvt7FLIDkHE9RpXkgSiY1v1HalQEoqXuCxohw6sdYg3NLWZWQnVQYmiXav3EyO_WWfTbeVa1O2l4jwYEcaLdgUon_KuJX6YvIIu5A8ShNNED-Xu7EbMJs3OJfUhKmpIdpy59fYWJCtc7Z84_Za3NUXMmMylHwi4fx4Y-8maZZcfbZR5XT5NhpXAj3MTqV42_v2-iulHvqxEcafUcTwXZMbrvsGaW6EDuMjGhk2icJPDmNdP2h02gjc5O012pueYl6IRI2NlP_cGRHvVsmnqc33CsYoNQxJ_dxpIw

### Monaco Editor Playground Code

```typescript
monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ES2015,
    allowNonTsExtensions: true,
    moduleResolution: monaco.languages.typescript.ModuleResolutionKind.Classic,
    module: monaco.languages.typescript.ModuleKind.AMD,
    noEmit: true,
    esModuleInterop: true,
    strict: true,
    allowJs: true,
    isolatedModules: true, 
});

monaco.languages.typescript.javascriptDefaults.setEagerModelSync(true);

monaco.editor.createModel(
    'define("dep1", [], function () { return { foo: { bar: 123, aaa: 456 } } })',
    'javascript',
    monaco.Uri.parse(`inmemory:///mylib/dep1.js`)
);


const instance = monaco.editor.create(document.getElementById("container"), {
    language: 'javascript', 
    value: `define(['dep1'], function (dep1) {
    console.log(dep1.foo.bar);
});
`
});
```

**Comment by hediet** [comment]
I don't think is possible without significant effort.

Maybe you can achieve it by generating some d.ts files in the background.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Comment by manikantag** [comment]
I see, thanks for the update. 

Is there a way to specify the `prototype` or `type` of a word (as a class instance variable)? I have a class with jsdoc and all. Now whenever user types `this.`, I want to send the completions from the class prototype. Right now I'm sending the members from the class prototype using `registerCompletionItemProvider()`. This got 2 problems so far:

1. I need to show the Class prototype members for `this.` only at the top level, but not at any other nested function as `this` context changes by the function declaration.
2. I want to show the jsdoc documentation which is present in the Class.

Related SO questions:

https://stackoverflow.com/questions/67505426/custom-javascript-code-completion-for-this-in-monaco-editor
https://stackoverflow.com/questions/43037243/provide-type-hints-to-monaco-editor

Can you please advice? Thanks

**Comment by manikantag** [comment]
Never mind... I figured it out... using declaration files I achieved 90% of my requirement: getting proper completions in AMD module with `this` context of chosen type.

For anyone else having same requirement: [Monaco playground link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAI4BwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxApLLfnmJTiNdlbZ8DX-17E5MqcwrgRBtkia6ypHc0Ul4AlwqlmgX1Xoeu_FTd8hOyNr4Y9dzP2trx4b1ghS5pvA_mL5nbXOsa0me5jGx7h63XUrLUse3wBFfuTQjEPtIevQpN-InSspT_k_viIKffzRzy1ixqRgXLs6Eh8NRjLw6M9aRBz6weKs1xxH_s_bnnR-siFsgmi2FDXGurU-UNnoN-EH0Lx_WJC45qmVDWrOEwOJY2I5o9VGpSFK_NXznkyDATAycqvxlTZoamZEjX5BObfdths_83QXQ1_VeM1s3eM-oorapFQeB_Ru4Mrmf-BbHdspfPXaafJK50rXVNn-ETrUXclUGFP0fBo70AVgNVhuXSw0A2Jqofntow3_SCQBxIUpT2xWnqTbwo86THYesGKIuEp3NN5EwdRINEzvm2mMEz3ApCaUjAnHd-tOUpDo18JMNOQiXFM4f_VWJMO9iG2oMFWb3-f30S36EBF26kaU97nsQWUTDTO9vCK_lS-S0oC4lQYXdVEuvdR-cILIRfuYQ5xtmdpNWksjwu8Asjg7I5pwZBAWw__WbSD-kUgXZDpAyMzLtdcKQjHA9jZYbmGfrRGvc3T3MLBuEXvdb8p4CCyQTJMJ8ss9X14mymWkH2hExXyOiXrBrK3bpbFW9iX-1qd-J06JECyYfwZtmsg-gv0pSRn4VF68rXTCauTTXGWmbA-NS5y0M1zQZRufASN4Kkz1zcddhTUjsAgrIaC3d2f6hSp7BJTlVF0g_vSxyC27ZMFyxIs0zCtWZJ_4rkHttG0G1j2QMWSEcIL3MqhlQ-W40UrTgYMAnAqGdlYKS99eAihvCQbGKkDGeH7gkR0SeGdxXm_q2Vs1RH09LvCclMy9JLs5HTA_IK0bT2m-mffPzjubmylh-EEr-1fGXu9obditt02CjOVBDfwJwUy_CPjmvSr6o13Ad1cEsien72UWIRRwHLijc8lKBzAiH5pNbm7DrMsFYfB4bUFIka3Elz-QDPi_H9RqirNNCphQeVO-GdO-bwMsVeTdFkYdYrgU9fmSO5v-LhwmsHR8q_8EkhSc)

Main thing to notice is how `this` is declared to be a specific type in the declaration file which is fed to monaco as a extra lib.

```
declare function Factory (this: MvcApp, n: Number) : void;   <----- change the `this` type to whatever you want
```

Best thing is I don't have to fiddle with the current line/word based logic anymore (and no custom provider is needed), leaving all it to language worker which is best at it 👍
