### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by gil-koifman** [microsoft/monaco-editor#3621]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#example-creating-the-editor-hello-world

### Monaco Editor Playground Code

```typescript
const text = `function hello() {
	alert('Hello world!');
}`;

// Hover on each property to see its docs!
monaco.editor.create(document.getElementById("container"), {
	value: text,
	language: "javascript",
	automaticLayout: true,
});
```

### Reproduction Steps

Open Chrome.
In the preview, write the following code:
```
function hello() {
	alerst('Hello world!');
}

hell
```

Hover over the "hell" word at the buttom, and a lightbulb will appear.
Try to press "CTRL + ." shortcut.

### Actual (Problematic) Behavior

Nothing happens

### Expected Behavior

Should show the quick fixes available

### Additional Context

This works in Edge, but doesn't work in Chrome.

**Comment by hediet** [comment]
This works for me in Chrome:

![image](https://user-images.githubusercontent.com/2931520/222411633-6ed2dfc7-201c-4c00-9a6f-0f7f82133dd0.png)

**Comment by gil-koifman** [comment]
Sorry, apperently it's an issue in my machine
