### ISSUE TITLE
[Bug] json language matching brackets not highlighted

### ISSUE THREAD

**Issue by jessebluemr** [microsoft/monaco-editor#3626]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

Current Broken Version (latest):
https://microsoft.github.io/monaco-editor/playground.html?source=v0.36.1#XQAAAAI5AQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscrHQDZUcqL2Gu_y6-pesM5CAK4Rl2SA3OZZypoZAb43HgZ99s3BRMgXtreldIbr5SD4XF5Tatz5q50l9C62FqPMzPpUOWn0KyP2OajTzBZa3r3xwFuz_bvlBduMYE4EJ1jKJvqTNpAOrjRdK3jtBTzQOXj5_qIDbaqXPzfb5D1SHpUF1n8kjogmjV1xItO7tOO1PQ8z-sIBrqo5PvQKHC-agBecyvVVfLlwrxQbBp-cAedPSral5liedjr3fSsYJrtO9__96qDrw

Last Working Version (0.33.0):
https://microsoft.github.io/monaco-editor/playground.html?source=v0.33.0#XQAAAAI5AQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscrHQDZUcqL2Gu_y6-pesM5CAK4Rl2SA3OZZypoZAb43HgZ99s3BRMgXtreldIbr5SD4XF5Tatz5q50l9C62FqPMzPpUOWn0KyP2OajTzBZa3r3xwFuz_bvlBduMYE4EJ1jKJvqTNpAOrjRdK3jtBTzQOXj5_qIDbaqXPzfb5D1SHpUF1n8kjogmjV1xItO7tOO1PQ8z-sIBrqo5PvQKHC-agBecyvVVfLlwrxQbBp-cAedPSral5liedjr3fSsYJrtO9__96qDrw

### Monaco Editor Playground Code

```typescript
const text = `{
	"array-brackets": [],
	"object-brackets": {
		"value": 1
	}
}`;

// Hover on each property to see its docs!
monaco.editor.create(document.getElementById("container"), {
	value: text,
	language: "json",
	automaticLayout: true,
});
```

### Reproduction Steps

Use as language "json", open the editor with valid json data, e.g:

`{
	"array-brackets": [],
	"object-brackets": {
		"value": 1
	}
}`

If the editor is opened, move the cursor to one of the brackets, e.g `{` or `[`.
Now the bracket pairs should be highlighted.

### Actual (Problematic) Behavior

Matching Brackets are not highlighted:

![image](https://user-images.githubusercontent.com/489437/222674803-75dc4f0b-647e-419f-8ac7-72315bc99393.png)

### Expected Behavior

Expected that the matching brackets are highlighted:

![image](https://user-images.githubusercontent.com/489437/222674550-f7e5c79c-ed22-46af-a1ce-cd1457a71114.png)

### Additional Context

With the language "javascript" it is working as expected.

The difference I observed is that in case of javascript the lexer [editor/standalone/common/monarch/monarchLexer.ts](https://github.com/microsoft/vscode/blob/1ab647fd443d606e7d6b07e24512ce6de3be3e70/src/vs/editor/standalone/common/monarch/monarchLexer.ts#L318) is invoked and every token line is marked with the flag `MetadataConsts.BALANCED_BRACKETS_MASK`:

`const metadata = this._theme.match(this._currentLanguageId, type) | MetadataConsts.BALANCED_BRACKETS_MASK;`

In the case of json the [editor/standalone/browser/standaloneLanguages.ts](https://github.com/microsoft/vscode/blob/1ab647fd443d606e7d6b07e24512ce6de3be3e70/src/vs/editor/standalone/browser/standaloneLanguages.ts#L196) is analyzing the tokens and here in the method `_toBinaryTokens` is looking up the line tokens metadata from the color theme, but without combining it with the `MetadataConsts.BALANCED_BRACKETS_MASK`.

In my custom project I hacked this into the code and it solved the problem. But I'm really only guessing and have no deep understanding of the code responsibilities.

**Comment by hediet** [comment]
> In the case of json the editor/standalone/browser/standaloneLanguages.ts is analyzing the tokens and here in the method _toBinaryTokens is looking up the line tokens metadata from the color theme, but without combining it with the MetadataConsts.BALANCED_BRACKETS_MASK.

In my custom project I hacked this into the code and it solved the problem. But I'm really only guessing and have no deep understanding of the code responsibilities.

Thanks for looking into it! That seems to be exactly the issue!
It would be awesome if you could provide a PR that fixes this!

**Comment by yanny7** [comment]
When is planned release with this fix? latest version [0.39.0-dev.20230529](https://www.npmjs.com/package/monaco-editor/v/0.39.0-dev.20230529) still does not match brackets.

**Comment by hediet** [comment]
Works for me:

![chrome_T0B7zo5030](https://github.com/microsoft/monaco-editor/assets/2931520/4ee9802b-1590-4a0b-9d37-1b60b4841126)

**Comment by ShenHongFei** [comment]
I also encountered such a problem, but I defined a new language.
![image](https://github.com/microsoft/monaco-editor/assets/15074472/4bc11fe0-3982-44fe-a48d-71208ef06c5e)

**Comment by yanny7** [comment]
In my case it's related but not same problem, I have defined custom language and I'm using tokenizer. I open new issue.
