### ISSUE TITLE
wordBasedSuggestions not work with registerCompletionItemProvider

### ISSUE THREAD

**Issue by vthinkxie** [Microsoft/monaco-editor#363]
monaco-editor npm version: 0.8.1
Browser: Chrome
OS: Mac

`wordBasedSuggestions`will not work when set `monaco.languages.registerCompletionItemProvider`
can both of these work at same time?

**Comment by Leezheng357** [comment]
Do you solve the problem? Can you tell me the way to solve the  problem?

**Comment by vthinkxie** [comment]
@Leezheng357 not yet

**Comment by agustinlg** [comment]
Hi I'm struggling the same issue. Is there any known workaround?
Thanks

**Comment by jrieken** [comment]
Yes, that is the design. When a specific provider is registered for a languages we won't ask the less specific provider unless the more specific provider returns null, undefined, or the empty array.
