### ISSUE TITLE
Save does not work in OneDrive and Office365 SharePoint Document Library

### ISSUE THREAD

**Issue by Danny-Engelman** [Microsoft/monaco-editor#364]
monaco-editor npm version: 0.?.? (the one used in OneDrive, Office365/SharePoint Online)
Browser: Chrome
Tested with multiple O365 Tenants

For the past months we used the Monaco editor for *.txt (and .js and .html) files in SharePoint Document Libraries (Modern Experiences) AND OneDrive
We did not install Monaco, it opens when you edit .txt files, and we figured out the correct URL for .js and .html files .. It is a great editor.. it really is

**Since a couple of days the Save button does nothing for .TXT (and other) filetypes**
(*Users reported it didn't work for days, I confirmed the issue myself today*)

There are no error message in the dev console

Steps to reproduce:

* Upload TXT file to OneDrive or Document Library
* Click to open (in Monaco)
* Make a change
* click Save (nothing happens)
* F5 / reload gives the warning

![](http://i.imgur.com/0bJ6YP2.jpg)

**Comment by Danny-Engelman** [comment]
In the latest test .txt editing in OneDrive is working again, SharePoint Document Library is not

**Comment by alexandrudima** [comment]
I think it would be best to contact the OneDrive / SharePoint Document Library team directly from the product. 

The Save functionality is implemented by them and is probably built using editor APIs, and perhaps there is a bug somewhere, but I don't think this is the problem within the monaco editor widget.

I'm sorry I cannot help you further.
