### ISSUE TITLE
Question: How can I implement multiple cursors?

### ISSUE THREAD

**Issue by snadrus** [Microsoft/monaco-editor#366]
monaco-editor npm version: Latest
Is there an API to render multiple cursors?
I'd like these secondary cursors disconnected from keyboard input. They would be for display only.

**Comment by alexandrudima** [comment]
If you'd want to add something for display purposes only, you can use decorations. You can create decorations that *look* like cursors.
e.g.

You can run the following at https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations by replacing the JS/CSS parts with:

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

var decorations = editor.deltaDecorations([], [
    { range: new monaco.Range(3, 1, 3, 2), options: { className: 'my-cursor'} },
]);
```

```css
.my-cursor {
    background: black;
    width: 2px !important;
}
```

The vertical line on line 3 is not a cursor:

![screen shot 2017-06-08 at 09 37 51](https://user-images.githubusercontent.com/5047891/26917334-2b0473d6-4c2e-11e7-83fe-af0d68f0cff7.png)
