### ISSUE TITLE
Line numbers do not meet color contrast standards

### ISSUE THREAD

**Issue by lavanyasiv** [microsoft/monaco-editor#367]
Browser: Chrome
OS: Windows

Line numbers in the editor do not meet color contrast standards. See the numbers in the image below:
https://keros.cloudapp.net/api/screenshotapi/GetScreenshotWithElementOutlined/3ef6d223-3fe6-4ad0-90f7-882ef7262451?outlineThicknessInPixels=2&outlineType=DiagonalDashed&alternateHexColor=%23cdcdcd&hexColor=%23ff0000

![image](https://cloud.githubusercontent.com/assets/22689654/23033295/626461ec-f42c-11e6-8649-30d8f9b325b0.png)
Text must have a contrast ratio of at least 4.5:1 - here it is only 3.64:1

**Comment by jayspadie** [comment]
We have the ability to override several Monaco styles without requiring the Monaco team to make changes to their default .vs theme that would affect everyone.  Of course, the Monaco team may want to be aware of default color contrast issues, but we are not blocked on this one.  Thanks.

**Comment by alexandrudima** [comment]
Here is the CSS that allows changing line numbers colours:
```css
.monaco-editor.vs .line-numbers {
    color: red;
}
```

**Comment by alexandrudima** [comment]
This color comes from the line number color of Visual Studio. I will wait for Visual Studio to change the line number color and then I will change the color in our `vs` theme

<img width="181" alt="screen shot 2017-06-30 at 14 48 53" src="https://user-images.githubusercontent.com/5047891/27736160-4818d256-5da3-11e7-93b8-26bc01d7ec42.png">

<img width="189" alt="screen shot 2017-06-30 at 14 49 41" src="https://user-images.githubusercontent.com/5047891/27736186-691eaf02-5da3-11e7-9914-0f19a6fd1abe.png">

**Comment by alexandrudima** [comment]
The default color has been changed in the meantime:

![image](https://user-images.githubusercontent.com/5047891/70526641-57a23700-1b4a-11ea-9149-818cbcfd395d.png)
