### ISSUE TITLE
Command Palette - inspect elements

### ISSUE THREAD

**Issue by BigYu** [Microsoft/monaco-editor#370]
monaco-editor npm version: 0.8.1
Browser: Chrome
OS: Windows 10 / Windows server 2012

Hi, is there anyway to inspect the dom tree and style sheets for the **Command Palette** . It seems that right clicking behavior is overridden inside it and if I do anything under the browser's debug tool the panel will just disappear.

Btw, I am not sure if it a stupid question: can I just disable the Command Palette features if I dont need it at all? 

Thanks!

**Comment by AndersMad** [comment]
this is more a question about Chrome and its debug/developer tool... but:

- try adding break point for changed dom elements using the dev. tool
- or use what I did here #70 and write `debugger;` while having dev. tool opened

**Comment by alexandrudima** [comment]
There is no easy way to keep the Command Palette open (it closes itself on focus lost) except for the smart tricks suggested by @AndersMad
