### ISSUE TITLE
onDidChangeModelContent issue

### ISSUE THREAD

**Issue by jsveron23** [Microsoft/monaco-editor#372]
monaco-editor npm version: 0.8.1
Browser: Chrome
OS: Mac

```javascript
this.editor.onDidChangeModelContent((e) => {
  const {
    startLineNumber,
    startColumn,
    endLineNumber,
    endColumn
  } = e.range;

  console.log(endLineNumber);
});
```

There are 50 lines texts on editor. If you want to clear all texts and try to type 's' text, then you will type 's' after using cmd + a on the editor. That's what I was doing.

But when typing 's' text, onDidChangeModelContent callback gave to me 50 of endLineNumber. There is no text except 's'. Is it bug or not?

**Comment by alexandrudima** [comment]
This is not a bug. The model content changed event gives the replaced range and the text the range was replaced with.
