### ISSUE TITLE
[Bug] C# UWP Project CTRL-F is not Working in v0.9.0 beta.

### ISSUE THREAD

**Issue by hdufortlaumie** [microsoft/monaco-editor#3725]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Hello guys,

I working on UWP projet and I found that the Find feature (CTRL-F) is not working on the v0.9.0-beta but was working on the version 0.7.0-alpha.

I've try to code a workaround, but the Control did not have usefull documentation and I could not find any way to do it by reading the API.

Did I miss something?

To reproduce: 
1. New C# UWP project
2. Add Monaco Editor Nuget v0.7.0-alpha
3. Drop CodeEditor control on the xaml Page
Run Project 
CTRL-F Working perfectly
F1 Key also

4. Update Nuget Monaco Editor to v0.9.0-beta
5. Run Project
CTRL-F is not working
F1 Key work fine

**Comment by hediet** [comment]
Hello! We don't own the nuget package, so we cannot do anything about it.

**Comment by hdufortlaumie** [comment]
Oh I see. thank for the reply
