### ISSUE TITLE
how to import extensions in monaco-editor

### ISSUE THREAD

**Issue by Leezheng357** [Microsoft/monaco-editor#376]
how to import extensions in monaco-editor? i need some extensions that can be used in vs code,i want to used  them in monaco-editor too.

**Comment by abhishiv** [comment]
@Leezheng357 did you figure this out? Mind sharing it?

**Comment by Leezheng357** [comment]
@abhishiv no,i haven't figure this out,
extension don't work on the monaco editor in a browser

**Comment by Leezheng357** [comment]
@abhishiv no,i haven't figure this out,
extension don't work on the monaco editor in a browser

**Comment by alexandrudima** [comment]
VS Code extensions cannot work on the monaco editor due to the editor running in a browser, whereas the runtime for VS Code extensions is nodejs. There is also the entire vscode API which does not exist in a browser form.
