### ISSUE TITLE
How to register custom json schema which is applied on file match pattern

### ISSUE THREAD

**Issue by npenin** [Microsoft/monaco-editor#38]
Hi Team,

I am looking for registering my own schema. Additionnaly, I would like this schema automatically applied based on file uri match. I know this is doable in vscode (https://code.visualstudio.com/docs/languages/json#_json-schemas-settings) but could not find a way to do it. Could you please guide me ?

Thanks,
Nicolas

**Comment by npenin** [comment]
I also found the JSONContribution which seems interesting also in my case, but could not find a way to register my own.

**Comment by alexandrudima** [comment]
@aeschli will know

**Comment by alexandrudima** [comment]
Oh, but first we'd need to ship a new `monaco-editor` that contains the now extracted `monaco-json`.

**Comment by aeschli** [comment]
The JSON plugin has an API that lets you add schemas (and schema associations).
Check out https://github.com/Microsoft/monaco-json/blob/master/src/monaco.d.ts

**Comment by alexandrudima** [comment]
@aeschli I don't think we've shipped an editor version that contains the json language as a plugin yet

**Comment by npenin** [comment]
up ? 

I also cannot see the JsonContribution interface in https://github.com/Microsoft/monaco-json/blob/master/src/monaco.d.ts. Any chance to see it appearing ?

**Comment by aeschli** [comment]
Yes, I made the update.
Check out https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Comment by npenin** [comment]
Thanks, this is one part of the solution. The other part would be to have the posibility to apply the schema based on a file pattern (eg. package.json files).

**Comment by aeschli** [comment]
Use the fileMatch property for that...
```javascript
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	schemas: [{
        uri: "http://myserver/foo-schema.json",
        fileMatch: [ 'foo.json' ],
        schema: {
            type: "object",
            properties: {
                p1: {
                    enum: [ "v1", "v2"]
                },
                p2: {
                    $ref: "http://myserver/bar-schema.json"
                }
            }
        }
    },{
        uri: "http://myserver/bar-schema.json",
        schema: {
            type: "object",
            properties: {
                q1: {
                    enum: [ "x1", "x2"]
                }
            }
        }
    }]
});

monaco.editor.create(document.getElementById("container"), {
    model: monaco.editor.createModel("{\n}\n", 'json', "inmemory://inmemory/foo.json")
});
```

**Comment by npenin** [comment]
great ! :+1: 

Is it possible also to have custom values for intellisense (like dependencies in package.json files) ?

**Comment by aeschli** [comment]
I added https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example to show how to add custom completions.

**Comment by npenin** [comment]
awesome. 

Thanks a lot.

**Comment by npenin** [comment]
One question though, wouldn't it be cleaner to expose the Jsoncontribution interface and a way to add customs ?

It just looked better to my eyes as the retrieval of the current "node" is done in background.

**Comment by aeschli** [comment]
That's not so easy as the JSON language service runs in a web worker. Your contribution would have to be bundled as part of this web worker.
Sure possible to do, the parts are all there.

**Comment by jasonHzq** [comment]
I have tried fileMatch but useless..
