### ISSUE TITLE
Auto closing brackets - how to disable for a specific bracket?

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/monaco-editor#381]
monaco-editor npm version: 0.8.0
Browser: Chrome
OS: Mac

How can I disable auto closing of specific brackets?
I have a java mode active and Monaco is auto closing '<' to '<>'

**Comment by mattgodbolt** [comment]
Take a look at the `LanguageConfiguration`'s `autoClosingPairs` - you should be able to modify it there.

**Comment by alexandrudima** [comment]
We should remove `<`,`>` from the auto closing brackets of Java
