### ISSUE TITLE
Completion after dot

### ISSUE THREAD

**Issue by skyne98** [Microsoft/monaco-editor#382]
Hello there! I wonder if there is a way to make editor request completion items from source after the "dot" was typed? For example, provide class members (fields, methods, etc.) without user pressing Ctrl + Space for auto-completion.

**Comment by JacobEvelyn** [comment]
@Skyne98 I think (depending on what you're looking to do) you can do this by setting `triggerCharacters: ["."]` in your call to `registerCompletionItemProvider`. Something like this:

```javascript
monaco.languages.registerCompletionItemProvider('javascript', {
    triggerCharacters: ["."],
    provideCompletionItems: function(model, position) {
      return [...];
    }
});
```

**Comment by skyne98** [comment]
Thanks!
