### ISSUE TITLE
How do I add a language created on the website?

### ISSUE THREAD

**Issue by Meai1** [Microsoft/monaco-editor#384]
Hi, I edited the mylang sample .js file here: https://microsoft.github.io/monaco-editor/monarch.html
and it looks good. 
I tried putting the file with the other language files, but it doesn't work. I tried calling monaco.languages.register("mylang") but it gives me an error "alias is undefined". (it's only that descriptive when using the dev version). 
The language file from the web looks different from those in the folder anyway, so clearly there has to be a different process somehow... Why offer the website at all if it doesnt work?

I will now have to try and convert it to the .ts format in the https://github.com/Microsoft/monaco-languages repo but that isnt ideal at all... I already did all the work of creating my language syntax once.

**Comment by Meai1** [comment]
Ok I found an example here: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

**Comment by hnarisetty** [comment]
Hi,
Is there anyway you can share this with me. I am trying to build my own language  to author mathematical expresssions like
variable=sum(10,20,40)

or
let v=10;
variable=v+10
