### ISSUE TITLE
[Bug] About the abnormal positioning problem when clicking the cursor

### ISSUE THREAD

**Issue by wiseguy-sky** [microsoft/monaco-editor#3849]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
function x() {
   console.log("Hello world!");
}
```

### Reproduction Steps

version: 0.36.0

operation:
   When you click on the code area, the cursor does not appear in the correct position

analysis:
    file: `/monaco-editor/esm/vs/editor/browser/controller/mouseTarget.js` -> `function shadowCaretRangeFromPoint(shadowRoot, x, y){ ... }`
    statement: `charWidthReader.getCharWidth(text.charAt(i), font) / 2`
   **This statement leads to the final problem**。

PS: Did not test on the monaco editor playground because there does not appear to be a shadow case on it

### Actual (Problematic) Behavior

When you click on the code area, the cursor does not appear in the correct position

PS: Non-shadow does not have this problem

### Expected Behavior

The cursor rests on the correct character position

### Additional Context

/monaco-editor-0.36.0/samples/node_modules/monaco-editor/esm/vs/editor/browser/controller/mouseTarget.js

**Comment by hediet** [comment]
/duplicate https://github.com/microsoft/monaco-editor/issues/3217
