### ISSUE TITLE
[Bug] Cursor cannot accurately position with webComponent(shadow-dom) in Chrome Version 111.0.5563.65 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by forrany** [microsoft/monaco-editor#3851]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[web component example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#example-creating-the-editor-web-component)

### Monaco Editor Playground Code

```typescript
customElements.define(
	"code-view-monaco",
	class CodeViewMonaco extends HTMLElement {
		_monacoEditor;
		/** @type HTMLElement */
		_editor;

		constructor() {
			super();

			const shadowRoot = this.attachShadow({ mode: "open" });

			// Copy over editor styles
			const style = document.querySelector(
				"link[rel='stylesheet'][data-name='vs/editor/editor.main']"
			);
			shadowRoot.appendChild(style.cloneNode(true));

			const template = /** @type HTMLTemplateElement */ (
				document.getElementById("editor-template")
			);
			shadowRoot.appendChild(template.content.cloneNode(true));

			this._editor = shadowRoot.querySelector("#container");
			this._monacoEditor = monaco.editor.create(this._editor, {
				automaticLayout: true,
				language: "html",

				value: `<div>Hello World</div>`,
			});
		}
	}
);


```html

<template id="editor-template">
	<div
		id="container"
		style="overflow: hidden; width: 100%; height: 100%; position: absolute"
	></div>
</template>

<code-view-monaco></code-view-monaco>

```

### Reproduction Steps

1. Make sure Chrome version is 111.0.5563.65 ( both Mac and PC have this problem, and this type of issue has never occurred in previous versions )
2. Open the web [component example in playgroud](https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#example-creating-the-editor-web-component)
3. You will find that mouse click on editor content, cursor cannot accurately position. Especially if you want to click on a position in the middle of a long string of characters, there is a significant misalignment.

https://user-images.githubusercontent.com/29779326/226283627-8b3190f8-1470-405a-88b0-0eae126245e9.mp4

### Actual (Problematic) Behavior

Mouse click on editor content, cursor cannot accurately position. Especially if you want to click on a position in the middle of a long string of characters, there is a significant misalignment.

### Expected Behavior

The cursor should placed at exactally where the mouse click.

**Comment by hediet** [comment]
/duplicate https://github.com/microsoft/monaco-editor/issues/3217
