### ISSUE TITLE
[Bug] Home page demo is broken

### ISSUE THREAD

**Issue by tamayika** [microsoft/monaco-editor#3853]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Open https://microsoft.github.io/monaco-editor/

### Actual (Problematic) Behavior

Demo editor always shows `loading...`

### Expected Behavior

Demo editor shows correct language sample code.

### Additional Context

I noticed this when I was debugging `Critical dependency: the request of a dependency is an expression`  webpack warning.
This warning comes from https://github.com/microsoft/monaco-editor/blob/main/website/src/website/pages/home/Home.tsx#L159.
But I don't know why webpack can not load file.
I also tried `webpackMode: "eager"` or `webpackInclude: /\.txt?/` as reference mentioning [here](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import), but nothing solved.
If I specify static dependency as ``import(`../../data/home-samples/sample.typescript.txt`)``, it works correctly.

**Comment by hediet** [comment]
Thanks for reporting! It is unfortunate that this was not an error, just a warning.

**Comment by tamayika** [comment]
Thanks for the quick fix!

I found a way to adopt TS 5.0.
Please see [PR](https://github.com/microsoft/monaco-editor/pull/3860).
