### ISSUE TITLE
[Bug] No tooltip is displayed for suggestions that exceed the length

### ISSUE THREAD

**Issue by slience-y** [microsoft/monaco-editor#3857]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual (Problematic) Behavior

completionItem length exceeds hidden, tooltip is not shown on mouse hover, how to show tooltip?

### Expected Behavior

expect show tooltip

**Comment by hediet** [comment]
Please fill out the form properly. Thanks!
