### ISSUE TITLE
[Bug] potential listener LEAK detected when create many models

### ISSUE THREAD

**Issue by troy351** [microsoft/monaco-editor#3895]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

- open https://microsoft.github.io/monaco-editor/
- open devtools
- create 200 models `for (let i=0; i<200; i++) monaco.editor.createModel('')`
- warning 
<img width="989" alt="image" src="https://user-images.githubusercontent.com/8372385/230349264-236e18c0-7e40-49c9-958f-cbb5363e14cd.png">

### Actual (Problematic) Behavior

Does this warning expected or internal memory leak exists?

### Expected Behavior

No warning

**Comment by hediet** [comment]
This is expected.

**Comment by troy351** [comment]
Assume I have a 200-file project, What is the correct way to make them links to each other (correct type inference across files) without create all 200 models at the beginning?
