### ISSUE TITLE
[Bug] bracketPairColorization broken with custom monarch language

### ISSUE THREAD

**Issue by tchapeaux** [microsoft/monaco-editor#3907]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAIIAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2yoVzJL3hzpT3LDW94B5u9m6MAORaqhXKvvrp_Pv8Oju69_Qi-r2vMIy4Uf-5qj6sYQyOs2xDtYeO55hAjtw68YWgVOruQ17uMHfEQ5W0HPGgYtnF0S3228NQ0aPDVIzpOPZaJAN6EnMDbjMmwKXcSXHnfx4MZvDI_LU2zmwll3JVRAsUo7qjgv6AmtvysWLVWkYEG73TZ8G0swv35S4PisVdj-VxQhLHDitDAeglCNHRo-AXQvH0DWnhdT0sKA3UPK10nldPc8Zp_UO1W4kPM0At6UJZltw10IRJvYaI-4wO3h1UR9dzJx0qukpWMZRmL43M2ybQqGOS6bkLhbildO5nL7K1vRhYu3_E4eWRvdjELbnJQnd9WgkSkoHExTFWXeE43g6dxRctkizxLeKUX4j3X5qLqPi4O9tTxOMo8Rz6-xiZlSGd1AD58O_-RTnDKGkYaGtZeaV8mklYaIjRUn6pf-moqoj757aQQaYF1wxXxf_v98kpbM9HbIdDlGvuHKdAVikjuwFdoe7_cJhug

### Monaco Editor Playground Code

```typescript
// Register a new language
monaco.languages.register({ id: "predicates" });

// Register a tokens provider for the language
monaco.languages.setMonarchTokensProvider("predicates", {
  keywords: ["OR", "AND"],

  brackets: [
    { open: "(", close: ")", token: "delimiter.parenthesis" },
  ],


  tokenizer: {
    root: [
      [/[{}\[\]()]/, "@brackets"],

      [
        /\w+/,
        {
          cases: {
            "@keywords": "keyword",
            "@default": "identifier",
          },
        },
      ],
    ],
  }
});


monaco.editor.create(document.getElementById("container"), {
    value: '(A OR (B AND C) OR D)',
    language: "predicates",
    "bracketPairColorization": {enabled: true},
});
```

### Reproduction Steps

Check the bracket pair colorization behavior

### Actual (Problematic) Behavior

No bracket pair colorization

![image](https://user-images.githubusercontent.com/1427052/230938475-8e608229-db86-4668-931f-52b36fcd7b5e.png)

### Expected Behavior

Functioning bracket pair colorization, as we can see by changing the language to `python`

![image](https://user-images.githubusercontent.com/1427052/230938675-ab7694ce-1915-4402-a99b-e6af7ca317f9.png)

![image](https://user-images.githubusercontent.com/1427052/230938743-c9be946d-8094-4467-a0ba-ba93313a1f0b.png)

### Additional Context

I tried duplicating the Python monarch definition for my new language, and the bracket pair colorization was also broken, which makes me think the issue is not that my language definition is broken.

**Comment by spahnke** [comment]
The Monarch token provider is only used for syntax highlighting. Other language features such as the support for bracket colorization (or autoclosing of character pairs) require an additional language configuration:
```js
monaco.languages.setLanguageConfiguration("predicates", {
    brackets: [["(", ")"]],
});
```

https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAJgAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4Km6C3x0sNKcPu0Jit6fah4A22z_ji5IM-YpoZGfrOjjhdPzzHa_1-x58P3EziH9Aj_3Oim96VAz55cnfA8Hy9MqivPebf1VyYJAMemGPEMUT7AGTDVFrSzjGZZmp6pi0bXbg0TpXB-5fHvL_u_lkYoJ_MCTDlbYaG2nnMutqDO8fi933v2Eb7vdrDh12jAz49XvvJ3kZF0T7LDhtBmheYTaaPYxAn2tp2hl1tIeqESsEVCFu23JgNMP8PrTInrCSdZU8jInig1w8RVfiUa3P7ZELn04G9MS64ZXpKGdnxs6DtHm9NJYCSaXGwPSXSsHdjh-lMsLrrwh7cq0uyHfaH_sJcWJE2r9H-bYpt2Bo3CUNNH7p8I5pMdEK3xm-sVpu4J6dp6ElGcQbploI0QVbJ9hhCj51mixyi99DK3J9FmEc5SBOTxQUeF4y5dB_-MiNZRnOLojDENw45WEDHKG3y1oZKz_mERI6AOFLUQH1-pQoHABHYVFKWKUlJdLjgQUb2vkGu2HeYp5VYXauIoWT8SfbKYPF3KcCXlhQ6GbzSOkJvsEzfpF5LQ

**Comment by tchapeaux** [comment]
@spahnke Thanks, this is exactly what I needed and works perfectly! I'm closing the issue.
