### ISSUE TITLE
Edit actions are available only in IE

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#391]
Open the context menu for the editor in https://microsoft.github.io/monaco-editor/playground.html
Edit actions (copy, paste & cut) are available only IE.

**Comment by JKillian** [comment]
I don't even see it in the latest version of Edge, they only show up for me in regular IE. Looks like this is the code where they are defined:

https://github.com/Microsoft/vscode/blob/47e5582d87210a65f87e3d7922ba97fa8b2c7dc0/src/vs/editor/contrib/clipboard/browser/clipboard.ts

**Comment by octoploid** [comment]
Also on Linux pasting by pressing the middle mouse button doesn't work.

**Comment by kittaakos** [comment]
Paste does not seem to work in FF, Chrome, and Safari but on IE. Is that the reason, it is restricted [here].

I have created a very simple [example] for the cut-paste command execution.

[here]: https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/browser.ts#L133
[example]: https://jsfiddle.net/kittaakos/ftr8bgun/3/

**Comment by alexandrudima** [comment]
There we are querying the DOM api if these commands are supported. We need to revisit if browsers truthfully answer and if `document.queryCommandSupported` is implemented as expected.

**Comment by alexandrudima** [comment]
In all browsers, Ctrl+X, Ctrl+C and Ctrl+V do what they should do without any prompts.

#### IE11
* the context menu will contain Cut, Copy and Paste
* when running from `file://` or from `http://localhost`, clicking in the context menu works without any prompts.
* when running from a different origin, clicking in the context menu will prompt and ask the user if they want to grant clipboard access

#### Edge, Chrome and Firefox
* the context menu will contain Cut and Copy, and clicking in the context menu works without any prompts.
* there is no way to trigger paste from a click handler in these browsers.
