### ISSUE TITLE
[Bug] Document symbols are not working

### ISSUE THREAD

**Issue by kisstkondoros** [microsoft/monaco-editor#3923]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAL5BQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw93royzX2TCsdnO2pIhMCTyfRj--wy5DSlIBUX1GqvAaH8JMatJ3oD6eBcMyQf91t6mXAweMogaPgJwsffilU1dSzKzoGincsXXP8TgE9xQqMLiP4QMapT-8geCdu5si58VXalSecX8eHXM-lbhd94n-sGFbLjeLHSMzwn9Nfg6J8DReh0i1jgUW4xRwDev3anRRtDEQASFGPjr_YK9VwErECp890vKo07SqL4sSwLYYPRcCcP3SpaSG8EkB6KS2JM89MGjRI85SCXeWB8BJQCyGEgGrAbU6HnpJRn7JRuQmyJVHOzN-15IRP7XPwwrpwdVS7G25Gxuz9r44vFYKU2KL5zhwSM7qNqOeN6SJNVNzI0R8BeyNemNOoM-vNSdYk1kcSfG47mTwrqD27DEdRgvld1SPeugn75SnfzadpHKM3jMAOXJL_NitafdWHCrDc_QqfYHzdeSoByaLmUnKYU3e2TE_Nc35b5Gbdl55QnBYck7-W9RdVZWxh7PbUKaA6wxKic2BVE8BEir6xIFD5DMaX2H_6_q-rLVp-an7D_Ov02JnAQeQviGcKZmjZzAGqYH3JILD63VGg4R-c4MIvgYvXAO-wEz6vx11t6GmnmPjgdJtgn3_Y1yBUX_SQ6tY0uT58m6yEGuGhntf-5M3iBgqidsm_Om_kI59F3QNgUzwmDgvEti81yZC9uPF2Midda9N6JJrA2RM1_jAqqVR9ZmTpX5CNIMA5xODlhkQ8Og_-6r8sHCzXH2WQlQQpIn0QhvcVRu1aavGeACBVpCD2FBUAIbjj4Slu0DQ2Dm5vRGbn_yXymg0DTogGhZxPZsT_CQ4F4dJr2Qd-lZSbC6okIBxOHvB48ek7lhCr_uMNE7ycKX_q6K8QBM-Ym02CJtbrolKJVTtVb_wNz8ijgi-YOmbFboE1z6jd1BP7QGhq3BEqfhlkQyHJwQvgwcmsrw3hibpM4KQa4yT9j6WmFxJa315xhiHork6A5rfwxaF0_VVlLQ

### Reproduction Steps

Create the editor with the following options:
```javascript
{
    language: "typescript",
    stickyScroll: {
        enabled: true,
        maxLineCount: 3,
    },
}
```

An exception is immediately thrown due to invalid object access in https://github.com/microsoft/monaco-editor/blob/1c6f48aa7defbe06803ad47c45edf9ef7143cd4b/src/language/typescript/languageFeatures.ts#L893

### Actual (Problematic) Behavior

No document symbols are available and (at least) the sticky scroll is not working

### Expected Behavior

Document symbols are available and the sticky scroll is working

**Comment by hediet** [comment]
This looks like a serious, but easy to fix bug. Anyone up for a PR?
