### ISSUE TITLE
[Bug] In monarch language definition, regex does not support unicode match.

### ISSUE THREAD

**Issue by clairewu0218** [microsoft/monaco-editor#3926]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAJoCAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxEKvbTul7ZJri5jja903pcQn3-TX8W-r5G3guSXpqZii17LhvHr0mQ6jRWMqFY9p6zCMoITTtCU5P7psk227onswEhT8I-rlRIi01tsIstzYI7duJmxamaflzCmH3W-Hmu342CxWR_o87vjFCmxAvp55UPDetBH7jcgvIYJBSxiRrYx-_RHMyHEr7_HXFJ9k6qN0FPbluUgn1m-jm0OC4ABfNO4-C4UM4718cxBJxsdFLJGsebYS50ZEAg1cBXsl1ks0YJgIkS1jMEqWQxaklCZfDD3A9tpktclcoAJRq7kUYKHTQHHp4rAu_hc4Qgsw2ljuNSg8u-hTkX8J8TSVaZ8_u1R8B_Wr8ve0WZnSH35d_T-YjlupAVhcReEzbrY5yUwfp8_zEV_Pu5yUGzaUjrM7Ju5niNoP73uTko1LaJvAgpdbtdWfSUDI3_8NhPQzQu62nZPiZKFoWnyyrctPmeD4wm0G7Q8YRpUmI6WH7hgf_8W0gX42dBqUkABHzDkCbBrDj49vBR_WNszCMZd_vn7n2e2oYqD0vCxfRE35FcfxE0kTTQJY2PRD9ZOx0EhQQ8mu0V-z25Xd2PpGYfbczWtJMimsk0YvRxBnmfDCVe6igjnNQPC7BkzuB80bYH8dQfc_FJWC2PG6CIijCRA2KvvCk42la2MKpkG0e2o4FGj8gbiCbAdTYRTZXBW1a_vmhX2CKNSDsLocaEGJqmRaVjnCu3fClCJjWba4iLWQvzAluCGbL566s_4OoOLBjCiG_auB6n__YWpS4o8tjNu84jx2nLwZVLu3kcoUVrbXIWuLwNbHxi7TgQyd262NGO491ndMxfZe59r4iidmM9gSouWemC__KqRH0_wRk8Ymaq8j9D6F2vebU-zzOFFjxAHz4yQNmAGdSUYHmxfLUcdPqBxutWjiYLxdQ6s2OTljWLwhdANpKwqIOxc3R009drn67Kn64nGJeaT71cFceKX2qTMIqdo2dKKTaKOeUmopZ1vd3jG1TJc4eaLtbOgFBdwLsDANh2iviS5hTq_g74g8x5yjbT61AAN--BrAVqllg-v3ZOlP-fclr

### Monaco Editor Playground Code

```typescript
// Register a new language
monaco.languages.register({ id: "mySpecialLanguage" });

// Register a tokens provider for the language
monaco.languages.setMonarchTokensProvider("mySpecialLanguage", {
	tokenizer: {
		root: [
			[/\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}/, "unicode"],
			[/\[error.*/, "custom-error"],
			[/\[notice.*/, "custom-notice"],
			[/\[info.*/, "custom-info"],
			[/\[[a-zA-Z 0-9:]+\]/, "custom-date"],
		],
	},
});

// Define a new theme that contains only rules that match this language
monaco.editor.defineTheme("myCoolTheme", {
	base: "vs",
	inherit: false,
	rules: [
		{ token: "unicode", foreground: "99EEEE" },
	],
	colors: {
		"editor.foreground": "#000000",
	},
});

// Register a completion item provider for the new language
monaco.languages.registerCompletionItemProvider("mySpecialLanguage", {
	provideCompletionItems: (model, position) => {
		var word = model.getWordUntilPosition(position);
		var range = {
			startLineNumber: position.lineNumber,
			endLineNumber: position.lineNumber,
			startColumn: word.startColumn,
			endColumn: word.endColumn,
		};
		var suggestions = [
			{
				label: "simpleText",
				kind: monaco.languages.CompletionItemKind.Text,
				insertText: "simpleText",
				range: range,
			},
			{
				label: "testing",
				kind: monaco.languages.CompletionItemKind.Keyword,
				insertText: "testing(${1:condition})",
				insertTextRules:
					monaco.languages.CompletionItemInsertTextRule
						.InsertAsSnippet,
				range: range,
			},
			{
				label: "ifelse",
				kind: monaco.languages.CompletionItemKind.Snippet,
				insertText: [
					"if (${1:condition}) {",
					"\t$0",
					"} else {",
					"\t",
					"}",
				].join("\n"),
				insertTextRules:
					monaco.languages.CompletionItemInsertTextRule
						.InsertAsSnippet,
				documentation: "If-Else Statement",
				range: range,
			},
		];
		return { suggestions: suggestions };
	},
});

monaco.editor.create(document.getElementById("container"), {
	theme: "myCoolTheme",
	value: getCode(),
	language: "mySpecialLanguage",
});

function getCode() {
	return "Ⅰ";
}
```

### Reproduction Steps

`[/\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}/, "unicode"],` is supposed to match the roman number in text, but it doesn't.
I also tried `[/\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}/u, "unicode"],` but it won't work.

The monarch document (https://microsoft.github.io/monaco-editor/monarch.html) doesn't provide detailed information on the regex. It might be that I didn't find the right way to use it.

With other tools, this expression is able to match the roman numbers.
![image](https://user-images.githubusercontent.com/104450101/233489008-78cf1405-3e1f-499f-91c0-2bc5286af18e.png)
Source: https://regex101.com/

### Expected Behavior

Regex should work with unicode

**Comment by hediet** [comment]
```js
/\p{Lu}|\p{Ll}|\p{Lt}|\p{Lm}|\p{Lo}|\p{Nl}/.test("Ⅰ")
```

![chrome_VmPTPOjlbE](https://user-images.githubusercontent.com/2931520/235665808-076a9251-bd0b-4205-b0a2-33925da43436.png)

Seems like a JS regexp limitation? I'm not an export with js regexps, but this does not seem to be a monaco editor issues.
