### ISSUE TITLE
[Bug] createDecorationsCollection.className doesn't work with selection when using backgroundColor

### ISSUE THREAD

**Issue by dlitsman** [microsoft/monaco-editor#3929]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#example-interacting-with-the-editor-rendering-glyphs-in-the-margin

It seems there is no way to make selection work together with `createDecorationsCollection.className` which sets backgroundColor. When I select a text over decorated line I don't see selection range.

https://user-images.githubusercontent.com/963490/233871151-11bd5f67-4726-414f-9629-9c154a001c05.mov

However, I can still see similar words are selected

<img width="181" alt="image" src="https://user-images.githubusercontent.com/963490/233871323-a9fe23c1-73ea-4594-92a1-a992dda0169e.png">

### Monaco Editor Playground Code

```typescript
Default one from the link above
```

### Reproduction Steps

1. Select a part of text on line 3
2. Make a change to it

### Actual (Problematic) Behavior

 It is not possible to tell what is the current selection

### Expected Behavior

I can always see which part of the line is selected

**Comment by hediet** [comment]
You can use a transparent background color!
