### ISSUE TITLE
[Bug] Minimap context menu items don't work?

### ISSUE THREAD

**Issue by mjswan** [microsoft/monaco-editor#3932]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

1. right-click inside Minimap to display context menu
![image](https://user-images.githubusercontent.com/7586315/234385303-6c102db3-2816-4adc-b6b8-a3c4f4079cb3.png)
2. attempt to use any of the menu items, for example: Minimap

### Actual (Problematic) Behavior

Context menu items don't work, for example: if Minimap is checked, I expected selecting this menu item to disable the Minimap. Instead it does nothing and the Minimap item is still checked.

### Additional Context

The Minimap context menu does work when I tried it in vscode.dev. The context menu is not present in the monaco editor playground, so I couldn't test it there. I'm not setting any complicated options when setting up the editor:

```
var editorDiv = $scope.selector("#CMpopoutJavaScript").get(0);
$scope.monacoObjText = monaco.editor.create(editorDiv, {
          value: null, language: 'javascript', automaticLayout: true
});

```
Using version 0.36.1 of monaco on both Chrome and Firefox running on Mac OS.

**Comment by hediet** [comment]
See https://github.com/microsoft/monaco-editor/issues/3559
