### ISSUE TITLE
[Feature Request] Breadcrumbs code navigaton

### ISSUE THREAD

**Issue by pedrolamas** [microsoft/monaco-editor#3936]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

VSCode provides a neat code breadcrumbs navigation style on the top of the editor box:

https://code.visualstudio.com/docs/editor/editingevolved#_breadcrumbs

![image](https://user-images.githubusercontent.com/85504/234903272-8fc8b2e3-04d7-4d91-b616-dc63bf36d122.png)

Would be really great to have this on Monaco too!

**Comment by hediet** [comment]
This is out of scope for this project.
