### ISSUE TITLE
Could not add specific libraries using typescript compileroption 

### ISSUE THREAD

**Issue by anandanand84** [Microsoft/monaco-editor#394]
Typescript compiler option does not honor "lib".

With below config

```
monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
	target: monaco.languages.typescript.ScriptTarget.ES5,
       noLib : true,
       lib : ['ES5'],
    allowNonTsExtensions: true
});
```

Expected : All ES5 classes and its functions are available.

Actual : None

**Comment by jrieken** [comment]
In order to keep the bundled size low we don't ship *all* version of `lib.xyz.d.ts` but only some. To get a specific library into the worker use the `addExtraLib`-function.

**Comment by TedDriggs** [comment]
Is there a way to see which libraries are available using the `lib` property? I haven't been able to get any of them to work, nor have I found a source of the strings except for pulling it directly out of `monaco-typescript`
