### ISSUE TITLE
[Bug] Invalid `monaco.d.ts` link in README.md

### ISSUE THREAD

**Issue by domesticmouse** [microsoft/monaco-editor#3941]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

The link [`monaco.d.ts`](https://github.com/microsoft/monaco-editor/blob/main/website/typedoc/monaco.d.ts) link in [README.md](https://github.com/microsoft/monaco-editor/blob/main/README.md) is invalid.

And I'm not finding it in the Monaco repo via GitHub search. Should it be linked to https://github.com/Microsoft/vscode/blob/main/src/vs/monaco.d.ts instead?

**Comment by hediet** [comment]
> https://github.com/microsoft/vscode/blob/main/src/vs/monaco.d.ts

This one only includes the editor features, not the language features.

You can use this: https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/monaco.d.ts

Or the doc here: https://microsoft.github.io/monaco-editor/docs.html

Feel free to create a PR to update the readme.
I suggest to link to the docs, as the d.ts file is shipped with the npm module.
