### ISSUE TITLE
[Bug] ColorProvider updates incorrect range

### ISSUE THREAD

**Issue by DavidMulder0** [microsoft/monaco-editor#3949]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[Monaco Editor Playground Link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAALYBQAAAAAAAABBqQkHQ5NjdMpUO-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWS9TrQEnwCsFkDrlnyHAsCqtmpLMjNqpSmi7zbo-IpEwkAszovIW6EUyfTBOkFz3UPeztusX5jNwiQ7Y2WzawxXUqkI5J75eYmQhssIqo2L879ZGa_f2J4lty7YRnjeFILb-L89QNEzQxuBCaG58tEgUUylLMmC3Q9KYU8PPcndPt0aBHAH0AhTqGoaIKPA0R94jbthpmDLD2Yh5FysNpupCsV5A8L03yQkoEDJf0C0WWJAbLAi9B24VVxDhsPH2wJNHpT5S2ZjA-HLN8ZEhdDkYlHu-cBsNY6KEoiyRvA9AiZ3syNwSxIbNw0HWyX5430rPAqdbdDqfvClOASC05CysxoqXg6Xa0lT2eY3GE-3_b4aka4FZ-MbALoVLSIPCTnCvvx94Vpwr1q1OzVbpsDD54z87339BPcNpGZ53SzvCf8ouiYk8BOlnmZPT0Kfgjd6Pu0LS6rCg6sTYk9pkmQoAU89z1XvG_KqvRFCs0XI7R8UwanX2YL0ClFY3pdYg60tmKMLHc069dBONy7Ulhx9RjVsJY_LPa9eJbxDm9pSohyc2c0ODFfyA-u6vSasZ1qx6MbR3achrpKVEngMCubj_XR9CvY63hDUiXchm-SHug5ElEubWrwghPTFUoawxn6ONwlVmkJ_xzjbM)

### Monaco Editor Playground Code

```typescript
monaco.languages.register({
	id: "colorLanguage",
});

monaco.editor.create(document.getElementById("container"), {
	value: "red\nblue\ngreen",
	language: "colorLanguage",
	colorDecorators: true,
});

monaco.languages.registerColorProvider("colorLanguage", {
	provideColorPresentations: (model, colorInfo) => {
		var color = colorInfo.color;
		var red256 = Math.round(color.red * 255);
		var green256 = Math.round(color.green * 255);
		var blue256 = Math.round(color.blue * 255);
		var label;
		if (color.alpha === 1) {
			label = "rgb(" + red256 + ", " + green256 + ", " + blue256 + ")";
		} else {
			label =
				"rgba(" +
				red256 +
				", " +
				green256 +
				", " +
				blue256 +
				", " +
				color.alpha +
				")";
		}

		return [
			{
				label: label,
			},
		];
	},

	provideDocumentColors: () => {
		return [
			{
				color: { red: 1, blue: 0, green: 0, alpha: 1 },
				range: {
					startLineNumber: 1,
					startColumn: 0,
					endLineNumber: 1,
					endColumn: 999,
				},
			},
			{
				color: { red: 0, blue: 1, green: 0, alpha: 1 },
				range: {
					startLineNumber: 2,
					startColumn: 0,
					endLineNumber: 2,
					endColumn: 999,
				},
			},
			{
				color: { red: 0, blue: 0, green: 1, alpha: 1 },
				range: {
					startLineNumber: 3,
					startColumn: 0,
					endLineNumber: 3,
					endColumn: 999,
				},
			},
		];
	},
});
```

### Reproduction Steps

1. Hover over one of the colors
2. Select a color
3. Select a different color

### Actual (Problematic) Behavior

Observe how the end brackets are not replaced:

![monaco-color-provider](https://user-images.githubusercontent.com/20395438/236825872-b8f3bed8-0916-49c6-ad83-48b817dc5fa5.gif)

### Expected Behavior

`endColumn` is set to 999 (I also tried setting it exactly based on the model value), so I would expect the entire line to update.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. I believe the PR https://github.com/microsoft/vscode/pull/200626 should have fixed this issue. If you continue seeing this error please let us know. I will close this issue in the meantime.

**Comment by hediet** [comment]
I can verify this is fixed by https://github.com/microsoft/vscode/pull/200626
