### ISSUE TITLE
How to start the code at a specific line 

### ISSUE THREAD

**Issue by sandranrivas** [microsoft/monaco-editor#3952]
I want to have a readonly code editor. that starts on line two. how can I do this?
 It should add an empty line at the beginning and one at the bottom

<img width="267" alt="image" src="https://github.com/microsoft/monaco-editor/assets/48434421/0b26b493-5b87-443e-9c59-b6c0f514043f">

**Comment by hediet** [comment]
You can use `setHiddenRanges`
