### ISSUE TITLE
学习Monaco Editor 的一些中文资料，系列专栏。

### ISSUE THREAD

**Issue by PmcFizz** [microsoft/monaco-editor#3958]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

首先感谢微软运营的该项目，让无数前端有了一个非常好的开发工具。
如果你在学习Monaco，但觉得官方的文档写的不太详细，或者很多api不会使用，抑或是案例不够丰富。
我这里有一个Monaco Editor的专栏，欢迎阅读。
链接 http://t.csdn.cn/wRpUa  

该专栏已经有30篇文章，作为官方文档的补充，详细讲解各个核心api。并配合具体的示例。非常易学，上手。

再次感谢官方开发人员。

### Monaco Editor Playground Link

http://t.csdn.cn/wRpUa  

### Monaco Editor Playground Code

```typescript
http://t.csdn.cn/wRpUa
```

**Comment by hediet** [comment]
Please fill out the form properly and use English. Thanks!
