### ISSUE TITLE
[Bug] character "%" cannot trigger autocompleteion

### ISSUE THREAD

**Issue by susan88323** [microsoft/monaco-editor#3959]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAJICgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxIxSFp4kvaOOJg31mfFOK7C2IZ9ULMA9OQW1hLl2XYM8HcOonEhsPUCwzj4uhL-tiTBTYEySg-g65KMManKvh2SxJxfhi81vQefZfgBBEfDQ7NzbO6sEFI9MsdDNoIn9yawCD7y4vZGj9oiLNXVlbUj1WjuhCvwAsLYyvklNgod6n-RLyoWN7sqy-0BEckqLKcSbPCTRrAhqaXSKsEzGr17UUed6uf2b9rHYXsY9ce4-MR8_GCtEB1IzG3WicKddiHew6k8K82t6vV8lPMVxD9tOk8znNwZ-Vz3GcV8M235m_QV8j2sjUoIH086AeDA70LF-Tu9gSAQgFf-KtQpV-MBknNxL3VUnySz7oO_CS7mJIrSuzaagjleYA_k0tZpoZxePQ-PPgzih_ulnuzG075IwL5dEtZRz-usexSld-zLpExc7sVJHqOrxla_NHeioyJ9Ww95dvWdPUmlQdjvYhH-r2mporZXK1gVSBdKNwotscuZSirRjs6Qo3gefdz7AH6ar9jXuoVQ0MBhaFo5OsjKhNXN6QaxmgR54erl9Y6c5-eQsku4G1P31pEPrkmIXZU4p3_PFkdJf3ItMYrX0NMxNEo3TZvJZwFvh5EfxGXYCBochN_Yynq9sZAyStOyvPOderRkv2q1vP7A8jvxmWkDl2WimWcZUMcWukKJvKbVEKRh_y4LkhevG6VtUUU-hYJvFl9Y_TKy___qE5PC-3ybrUgQenoZ7cd93RQZZ7QENnTAuErib2j29HHXsldxOpglEyNAPg-QEK5T4rJTXRrNzDxlF94hqPKPA5XvkMgUOsOnWHIPWji5AX7ehwM3v-RZRI

### Reproduction Steps

1. Set up autocompletion rule that if the last word start with "{%", we show a list of auto completion options

### Actual (Problematic) Behavior

After typing "{%", there should be a list of auto completion options

### Expected Behavior

Nothing is shown up

**Comment by hediet** [comment]
![chrome_VIX7iOI42I](https://github.com/microsoft/monaco-editor/assets/2931520/30a2448f-dc7a-4e44-907a-18766d14f7da)

https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAJSCgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxI0355UAZUjrya5rh8lOFg_UQ_MDYMSQrG0UsgwiNPlruLImcjI-65n-ZkHyunv53gg2nabsukgtANcPHysbeoLpjt_6dR7MFGPbSWaIe73wltTj3A0kbczh2dwR-reOJ7Hk77D61lLtIOuxTJhUOe4ctOYSY3EcMowSLeQUbVvQS6qAt1K5M9sZRL14AqesgHK7SJNmeemMa2J9-5ArGrHQZsGzeLdZAtDERyC5d3u-wgq4yTzE-a1Aowy5hgxV0XJHp8S10iFJvPnp7s-abyWGEsV8PPOXyoUrirUHAfhRe82aoEtz_7grPrItXvG0J3NzQp3rB6eVgyu3Z7AfRjrOAOx7owNORdWB_wkrXGXQLDY-n3v70AYyc98KtG1x3Z6o2MLntlKAFFlIIN_b2JV6fLmMInOM3aHouVxepn3hTBlBat0A4k0x-3wSn6j9n_DoGOMNwewy_u-qS5cpG7mARXK3dPGZ9PMvJyZELSCMdFgYs2Kkw7x9S6yBGxxmTN4QgdF_uSMDhVOZTTcEtN6SYPpLppFJvjwrVp33oZkpDVCreZ0vkx3AJ9deP3onxfuzxEfof_iYMxqB1SIy5qyqmFjjg2HLuu4eJzRMTsPMNEyzMWUnFYYmd16lksjHfNa1J1niDXpdrcTVPatd9mOhAqS6V7sIFoiiZtTPGoaepggDUwKQozFal-e51LIiWnS9iSSfQVCM8nikhROLYmVWBmWE3B8L4TG83X3XneZq0J0h78ErbFBk2GzD2qRI8NRW-iG9ZSrUragbBN7oFIJdSAKliZrSGHZrE57BJ89EaYP9pNkqEhA0tPqNYfYT_70wcdg
