### ISSUE TITLE
Text in Monaco is sometimes blurry due to misaligned/subpixel text

### ISSUE THREAD

**Issue by JesperTreetop** [Microsoft/monaco-editor#396]
monaco-editor version: [whichever is shipped with TFS 2017 Update 1]
Browser: Chrome 56
OS: Windows 10 (Anniversary Update)
Steps or JS usage snippet reproducing the issue:
[See video demonstrating issue](http://recordit.co/LuTW5XmY6D). Look at the characters in `var` - the text looks smeared, and it is not due to compression. The movement is accomplished by scrolling up and down one notch with the scroll wheel. On every other notch, the blur appears. When the page loads, the text is fine. My hypothesis is that the text ends up on a fractional offset somehow. 

The only Monaco editor that I've seen do this is the one used in Microsoft Team Foundation Server. (The monaco-editor div has integral size.) The Monaco editor on the [Monaco editor site](https://microsoft.github.io/monaco-editor/) doesn't do this, nor does the [TypeScript playground](https://www.typescriptlang.org/play/index.html) or Visual Studio Code.

**Comment by alexandrudima** [comment]
Resolved via the changes pushed for #426. The editor no longer uses `translate3d`. You can workaround on your side by using the option `disableTranslate3d: true`.
