### ISSUE TITLE
[Bug] Suggestion dropdown has invalid aria-activedescendant attribute

### ISSUE THREAD

**Issue by dickwyn** [microsoft/monaco-editor#3961]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAItAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscqpoBB77H9Q9THIoLKcz1i5d20PZyLmqXXTWKyT1GfrJ3XAwToPtHwWASnqo0pHyQuUtEB9lm9JEtWglqicIVz8ubhlhasVItALBSn_gU6cMy2SI3m2J-EDr3vwQFeRnf3etFIwgFp2lTIrvVuQm0jQDMl-xgKtw7LTCrZQI5vUMUoQEkqN5MOuOUf_g6I4Y2TRXB-m16fP1HUc0XpODLbNO3pTJYb1GCyC2fdTRoMYUEUEsX-_u0ADpiCiv7bVOg

![image](https://github.com/microsoft/monaco-editor/assets/11251672/815ef9c1-587f-440f-bb53-a604aff1830d)

### Actual (Problematic) Behavior

the suggestion dropdown was flagged by the Accessibility Insights for Web extensions for not having the correct `aria-activedescendant` attribute

![Screenshot 2023-05-15 142703](https://github.com/microsoft/monaco-editor/assets/11251672/9b8c1977-5617-406e-90f6-e1a66d141b20)
![error-description](https://github.com/microsoft/monaco-editor/assets/11251672/9963515b-b6d8-4142-920e-b28ec202c322)

### Additional Context

Browser: Chrome Version 113.0.5672.93 (Official Build) (64-bit)
Accessibility Insights for Web: Version 2.38.1 | Powered by  4.6.3

**Comment by jrieken** [comment]
This seems to be an issue with the list, unless its accessibility provider implements `getActiveDescendantId` (which I think only the explorer does) the list uses some dom id of which I am unsure if it is correct

**Comment by benibenj** [comment]
@jrieken it seems like the suggest widget was setting custom ids on the list items instead of using the ones which are set by the list.

**Comment by jrieken** [comment]
Thanks @benibenj
