### ISSUE TITLE
[Feature Request] Clear the undo / redo stack.

### ISSUE THREAD

**Issue by Ivorforce** [microsoft/monaco-editor#3963]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I'd like a function with which I can clear the undo / redo stack:

`editor.clearUndoStack()`

I want to do this because in the background, a task completed from which there can be no undo (side effects). The user expects not to be able to undo past this point.

Note: This is related to, but NOT the same, as this issue: https://github.com/microsoft/monaco-editor/issues/686
I don't need to fully manipulate the undo / redo stack, I just need to clear it.

### Monaco Editor Playground Code

Workaround:

```typescript
function clearUndoRedoStack(editor: monaco.editor.ICodeEditor) {
    let model = editor.getModel()!;
    (model as any)._undoRedoService._editStacks.get(model.uri.toString())._past = [];
}
```

**Comment by hediet** [comment]
You can use model.setValue. This clears the undo stack.

**Comment by Ivorforce** [comment]
@hediet That function has a lot of side effects that are unacceptable for my use-case, like clearing decorations and cursor position.

**Comment by hediet** [comment]
Afaik there is no other way at the moment.

**Comment by Ivorforce** [comment]
That's unfortunate. All the more I'd be grateful if the feature could be added.
