### ISSUE TITLE
[Bug]     editor.action.triggerSuggest doesn't work when calling multiple times.

### ISSUE THREAD

**Issue by sina-nasiri** [microsoft/monaco-editor#3966]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://github.com/microsoft/monaco-editor

### Monaco Editor Playground Code

```typescript
In angular:

this._editor.trigger('', 'editor.action.triggerSuggest', {});

before loading data:
{suggestions: [{label: 'Loading...', kind: MonacoCompletionItemKind.Text, insertText: ''}]}

after loading data:
{suggestions: [my data]}

it doesn't change it from loading... to data. need to change cursor or click ctrl space
```

### Expected Behavior

it should display the new suggestion items automatically after calling trigger method

**Comment by hediet** [comment]
Please fill out the issue form properly. Thanks!
