### ISSUE TITLE
[Feature Request] Make hover window of Monaco Editor accept streaming data

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#3974]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I have a web application by ReactJS and NodeJS. It contains a Monaco Editor. I register a hover provider by [registerHoverProvider](https://microsoft.github.io/monaco-editor/typedoc/functions/languages.registerHoverProvider.html), then hovering on a text triggers a diagnostic window containing useful information. I also call OpenAI APIs to enrich this information, it works.

Now, the problem is that the execution of OpenAI APIs takes time. After hovering on a text, users see `Loading...` in the diagnostic window for several seconds before seeing the final result. I'm thinking if it's possible to use the streaming API of OpenAI so that users can see the streaming result progressively in the diagnostic window.

I made the following code to simulate a streaming data, `simulateStreamData` returns the same data structure as streaming data returned by OpenAI APIs.

When loading this code in the [playground](), we can see in the console that `handleStream` works fine. Now, the question is if it's possible to display these streaming data progressively in the diagnostic window when hovering on the text.

Does anyone know how to achieve this?

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/NdnHK.png

### Monaco Editor Playground Link

[link](
https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAJXCAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxEEp56BuzMt6m3zM8ThvdxGObU1HpA1sMWUB64RJ4HH_ycd2xvOGo2AcNKH50ZjwSmTVt56ipSjVv2khkP2Psav7M5HBCagzmeLXJ6nGZMeF9YQjP4P5f74Yc5iaAK_1ndxk55lgTL1zb8O9uVHjOo9jjfYJB6oC2ezA5qXv3HEv50pg7EsaTAnMADA6WYLZvHNi2K8lW7oBTD9xnGNCQ52mTY2F_ok36Jkwxz4sPTPuFiBqeCcg5zUUmNAsoRIClNx2LJXZce7IIDY9JutzmjRHxS35-UszXK8dSLsh97usiEi6OcvfH-goxwl1YbLKNCcWCyfj1KrIqQn9Wod2lrIu4l3xt5T1xyopcoNLcYpCav2QQ0aw1HG9OZesLSXena4ZEHrz-EVG92ccsqYjoeg-zD4Ccmm5wd9ro582M-owDw6iCFdeXWM5aTROPVEGdksg6JGdcuH-MRc1extQjthbVQYBsrtDAMjDbt_vuDxyV8MK3g24kdBfbwJXgaaAzX8uwYFhLMBTq1WcftBbJ9nKO5QE4C6hKfOzzdWX-J0M-PD5_ZAXqp2E1XG2-rfTgs2w5GYOHJkYsT77u8fhcA9E6mCsEHj7LFM6ykQRgHbTwAPE-vRoR0fEdHnHHoknjCv7hfSorY6DSNcNyGkUYNa2Y8pGvpND44DAemLpZexQPd7qdIh8L2QrwFyZIfgJpl-mQGJ18iprquXs7LoP7c6Of9EfzooYq7EQ7pY0BH-nCYM9b5rUuO8ZbWD3LedF9Vm9CUp7RRqZlqtYlO92ktls_3Q4MF5csg_0MX5Wc8iE-NuGHTKaEtCEvFzIDt5Zy9LO4Ay5ES_cK5km-7eRb3z7HxqUK7nw3cpcm_dl5aSBBpIOOfvW5Ep7udo16-_8tdBnIkhR1G2BprY1rpDYJ2K_SKkghuRWyCSv4JghSlzso6xRSfNKACUgOUGXr17o0GLqQywy8Py4wMR2KIu8Os_zvTWGSlMv9aBp_SsnQiYy8NTIvchhFJR7J_TD-3Wtseco9eNM0Xb41lWg1dw2JMTGpI2E_Ez58PKEj3_Qk8gOd0LasEmjzxzWeiKYVX_cWuKd3aEyq5I8BEfFhtJUdVUg0fm6jYsc_zUMShszj_6JL6m7C2dJudZPtyXAWdSs0vK4DzFWncznHq8qYgoXNgczANTSblWm90lYTJwzV-79B1SOTvH65VI_dkd-tIvm7MsxrDfuJlAwbB_SpgMDaP81YNWBsM57fshCtHVhjGTBfV4SZlC__xofbhQ)

### Monaco Editor Playground Code

```typescript
async function* simulateStreamData() {
    const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

    // Mock 5 data streams
    for (let i = 0; i < 5; i++) {
        await delay(1000);  // wait for a second

        // yield a random object similar to the expected structure of the response
        const jsonStr = JSON.stringify({
            choices: [{
                delta: {
                    content: `Stream Data ${i}`
                }
            }]
        }) + "\n";

        // Convert string to Uint8Array
        const uint8array = new TextEncoder().encode(jsonStr);

        yield uint8array;
    }

    // Indicate the end of the stream
    const doneMsg = new TextEncoder().encode("[DONE]");
    yield doneMsg;
}

monaco.languages.register({ id: "mySpecialLanguage" });

monaco.languages.registerHoverProvider("mySpecialLanguage", {
	provideHover: function (model, position) {		

		async function handleStream() {
			const decoder = new TextDecoder("utf-8");
			const streamData = simulateStreamData();

			for await (let chunk of streamData) {
				const decodedChunk = decoder.decode(chunk)
				const lines = decodedChunk.split("\n")
				const parsedLines = lines
					.map((line) => line.replace(/^data: /, "").trim())
					.filter((line) => line !== "" && line !== "[DONE]")
					.map((line) => JSON.parse(line));

				for (const parsedLine of parsedLines) {
					const { choices } = parsedLine;
					const { delta } = choices[0];
					const { content } = delta;
					if (content) {
						console.log("stream, ", content)
					}
				}

				if (decodedChunk === "[DONE]") {
					break;
				}
			}
		}

		handleStream().catch(console.error);

		return {
			range: new monaco.Range(
				1,
				1,
				model.getLineCount(),
				model.getLineMaxColumn(model.getLineCount())
			),
			contents: [
				{ value: "is it possible to see the result of handleStream progressively here?" }
			],
		};
	},
});

monaco.editor.create(document.getElementById("container"), {
	value: "\n\nHover over this text",
	language: "mySpecialLanguage",
});
```

**Comment by hediet** [comment]
We don't have the resources to implement this feature (just) for the monaco editor.
We are open for small change PRs though.

Alternatively, you can try to convince us why it makes sense to have this feature in VS Code (as feature request in the vs code repo).
