### ISSUE TITLE
how to custom shortcuts

### ISSUE THREAD

**Issue by WinfredWang** [microsoft/monaco-editor#398]
Now, I want to custom shortcuts，Which Api should I call? 
For example:
the hotkey `Ctrl + /`  to add comment，how to do use `Ctrl + Shift + /`  instead.
Thanks very much.

**Comment by kevcodes** [comment]
https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance

**Comment by alexdima** [comment]
Let's track in #102
