### ISSUE TITLE
[Bug] Regression: Hover Provider not working in Shadow DOM

### ISSUE THREAD

**Issue by DrNiels** [microsoft/monaco-editor#3983]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

I load Monaco within a shadowDOM, similar to the corresponding sample code (https://github.com/microsoft/monaco-editor/blob/main/samples/browser-amd-shadow-dom/index.html) and try to add a hover provider.

### Actual (Problematic) Behavior

The result from the hover provider is not shown and the function not even executed.

### Expected Behavior

I expect the corresponding hover function to be executed and its content be displayed

### Additional Context

For Monace Version 33.0 or lower, this is working just fine, but not for higher versions as of 34.0. You can check an example with version 38.0 here: https://codepen.io/DrNiels/pen/WNaBJdj which does not provide hover. If you load the same example, only with monaco 33.0, everything is working fine: https://codepen.io/DrNiels/pen/BaqeqvP
Due to the console.log within the hover provider, you can see, that the hover provider is not even executed.

**Comment by DrNiels** [comment]
Ah, sorry for that, I thought it was easier with an example where you can compare the different versions. I edited my initial description and added a link to the playground. Is that fine? Do you want me to open another issue or will you reopen this one?

**Comment by hediet** [comment]
/duplicate #3409

I recommend to use the labels to search for duplicates.

> Ah, sorry for that, I thought it was easier with an example where you can compare the different versions

The playground allows to do a bisect on all the monaco versions and also allows to debug from source.
It is an environment we control to rule out a bunch of user-configuration issues and it shows that the bug is serious enough for the bug-author to attempt a reproduction in the playground.
