### ISSUE TITLE
Using selenium in C#, how to write code to do basic input/edit/delete?

### ISSUE THREAD

**Issue by BigYu** [microsoft/monaco-editor#399]
Working on e2e automation test using Selenium.

The editor is not a text area. Each line is a separated div element.
Given some "code" in string format(or retrieve it from some static files) how can I do the input/edit/delete? Anyone please has some ideas or experience? Do I have to parse the input and update the inner html following the original format?

**Comment by alexandrudima** [comment]
The editor I/O is done via a `<textarea>` that always has focus. If you click in an editor, the browser focus resides in a very tiny `<textarea>`. In 0.8.3. the textarea is placed at the top left of the editor, in the upcoming release the `<textarea>` will move with the editor's primary cursor (when it is visible). You can find the `<textarea>` by clicking in an editor and using `document.activeElement` in a browser console.

To simulate editing, etc. you would need to send correct browser events to the `<textarea>`.

**Comment by alexandrudima** [comment]
@joaomoreno Perhaps you remember what you had to do to get spectron to like our editor?
