### ISSUE TITLE
[Bug] registerEditorOpener not present when building from source

### ISSUE THREAD

**Issue by CareyJWilliams** [microsoft/monaco-editor#3997]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual (Problematic) Behavior

I noticed when building from source (this repo, not vs code) that the resulting build doesn't have the new 0.38.0 registerEditorOpener method.

Does monaco-editor-core need bumping?
https://github.com/microsoft/monaco-editor/blob/8bb1a4e8636d1dd88e3cfa4a3556b315011dac57/package.json#L55

### Expected Behavior

To get builds representative of the version/release notes.

**Comment by hediet** [comment]
Should be fixed now. Thanks for reporting!
