### ISSUE TITLE
Insert parentheses on autocompleting functions and methods

### ISSUE THREAD

**Issue by martinhiller** [microsoft/monaco-editor#400]
In our usage scenario for the Monaco editor, it would be a big plus if triggering an autocomplete entry for a function or a method automatically inserted the parentheses required to call it.

![monaco-completion](https://cloud.githubusercontent.com/assets/7996680/24241595/9d87c544-0fb5-11e7-83d1-521f593c2f3d.png)

After pressing enter (current behavior):
![monaco-completion2](https://cloud.githubusercontent.com/assets/7996680/24241631/bff5ac54-0fb5-11e7-9429-cd46fff69f69.png)

After pressing enter (desired behavior):
![monaco-completion3](https://cloud.githubusercontent.com/assets/7996680/24241649/cfc279be-0fb5-11e7-918b-d13a8cc13ae7.png)

If this is currently not possible via some API or configuration option, would you consider it a feature request?

**Comment by jrieken** [comment]
Unsure, while I can understand the desire in parts, TS/JS allows for passing functions around, e.g. as event-listeners etc, and in those case filling in the invocation-operator would be wrong

**Comment by martinhiller** [comment]
I agree that considering the functional nature of TS/JS, it might not be the most reasonable default behavior to insert the invocation operator automatically. But in our specific scenario, calling a function/method is the right thing to do in 99% of the use cases, so I would like to optimize the user experience towards this assumption, if somehow possible.

**Comment by jrieken** [comment]
We are open for a PR that adds an option to enable this for user that want this behaviour

**Comment by dennis-yemelyanov** [comment]
Looks like this is supported in vscode using `useCodeSnippetsOnMethodSuggest`: https://github.com/Microsoft/vscode/issues/1021

Does Monaco editor share the same internal API as vscode? If so, any pointers on how to this feature exposed from Monaco editor?

**Comment by nic-hartley** [comment]
I've been digging into how this works in vscode, and it _looks_ like it'll be possible to hook something in relatively easily. I'm happy to keep digging and try to submit a PR, but I can't guarantee I'll find anything worthwhile.

That said, there are a couple things I'm struggling to find:

* Are there currently any options being passed to autocomplete, outside of the `options` passed to `monaco.editor.create`? (This is mostly so I don't need to design an API for it)
* Does anything else inject settings into vscode? If so, it'll make it much easier to implement -- I can just follow that example.

**Comment by rsegner** [comment]
@nic-hartley, did you manage to find a solution to this one. I am having the same issue.

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
