### ISSUE TITLE
[Bug] Uncaught (in promise) Canceled: Canceled with vue3 and vite

### ISSUE THREAD

**Issue by SuperManito** [microsoft/monaco-editor#4009]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Errors that occur after overwriting new content, not during the first load

### Actual (Problematic) Behavior

![image](https://github.com/microsoft/monaco-editor/assets/68613938/b60ac858-62f7-4039-b0c2-a873c59e8ec7)

### Expected Behavior

no error

### Additional Context

This bug has been present since version 0.37. This have to stay in the old version of 0.36.1. Please fix this bug. I used vite and Vue3.

**Comment by hediet** [comment]
Please try to reproduce in the monaco editor playground. Thanks!
