### ISSUE TITLE
[Bug] registerLinkProvider not working with custom language

### ISSUE THREAD

**Issue by TNtube** [microsoft/monaco-editor#4013]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
monaco.languages.registerLinkProvider('ludoscript', {
  provideLinks: model => {
    console.log('link resolved')
    return { links: [{ range: { startLineNumber: 1, startColumn: 0, endLineNumber: 1, endColumn: 10 } }] }
  },
  resolveLink: (link, _) => {
    console.log('link resolved')
    return { range: link.range }
  }
})
```

### Actual (Problematic) Behavior

I recently updated monaco editor, and by doing as so, all my uses of the `monaco.languages.registerLinkProvider` method stopped working.

Neither `provideLinks` nor `resolveLink`  are working, but they used to work before.

Also, this is the only service that stopped working. All the others like `monaco.languages.setMonarchTokensProvider`  or `monaco.languages.registerHoverProvider` are still working as supposed to

### Additional Context

Old monaco version : 0.34.0

Current monaco version : lastest

**Comment by hediet** [comment]
Thanks for your bug report! Can you provide an example that reproduces in the monaco editor? Thanks!

**Comment by TNtube** [comment]
Hello, sorry for the delay.
I just published [a small reproduction on my github](https://github.com/TNtube/MonacoLinkTest). A small precision, i'm using the package [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react), but the problem doesn't seems to be from there.

As shown in my screenshot here :
![image](https://github.com/microsoft/monaco-editor/assets/51389578/0824d346-78eb-4ce7-8ef2-813caed4069e)

Even if I register a link providern the method `provideLinks` is never called. Am I doing something wrong ?

**Comment by hediet** [comment]
Please reproduce in the monaco editor playground and share the link. Thanks!

**Comment by TNtube** [comment]
Sorry, I though i couldn't reproduce this behavior but after some test I could ! 

[Here's the reproduction](https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0#XQAAAAJ2AgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw15qYu_1uhs0-3YGTBOsBx7SQ5xvgFFp3edsF0bktt_d2hJGgOvjcNzsqqBrcJeE79X-NjfWpGLGTonTi3yh9Rk3Pr6hdWJWxtwXWZS8ffEiVmOEnAazZNo8fm22-nMWcBwHMIvJ7eDcVEesuUrcTrL1dWOE5lgj5-rfwznNONiEMdDV9zKkyBCtGPN5VPRutSjEPUOEajlIms_MEpBmS41twgqhpNSVev--RawkLr6oR8hGoW0L7Bo_Meql_LKF7CoqU7NShX1CvdcaTgtXD1wVTQMv4SgISmvdvCtoWSO5gqawScRy7Buox5OEvfaGKWJ5UaI9ZeysRYqmo5_ioq8fSTm1uJ7NbnjzqneAfD_AeXQ4A6XrG8i0yORhZ9SOEQCfaeI7euQSXD0awurbRza9dTWRqxISZEg26Rd1-LWAEbereYsy2EgO-EJTD0Y4uG8noInFhs3Mpbeh5aXtBDRf_YOzwFfjvQk3_8Rklqw)

Also, I just noticed that it works just fine if i replace my custom language by `javascript`.

**Comment by hediet** [comment]
Your code never worked.

[This works](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230612#XQAAAAKvAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2OIkTJuetpg8d5BCIdoMyp72QowdQSZ1jb_Ht9w-6UP0rs_qQp3Did9fKgPRxxrSWdzzYs1TuN0Nc_2I0ySnngwL75XyFLzRQzVws5BBBSOdx8A3XCZS2tRmZt3GePs4wzDBOyeSQr9GbKeHOYDsY8zw45Gk4PWgVK4lIuLxCj7YJ_NerspZyE75v538pd6qRSyeE1r9kwkvvJc-A1CfHcW-u0dTfbLMzJVmaRxYDwvFxlJusBz_sU40Xlnqo3Xh-uKQcG7YFxdsDm6KR__fztpmTutTGTHY8vHOd3psxVwfB2v6a-jZgOCtvNpBU-xm72ft7SLCGWDebYF63nc6A5Yxjg8XZcqb6CaXzvJNzruzyP2VDtWeLBdvyIdptuPwJkV9eVbwDh2W_ql_OEMD2EWTQv8uBf8Bjpre6U86h5VbDIBMU3VYfg1wgkL7byUpoDXPJcIh9XFKO7yI1wyYNE2VuVlzF5BdH_UtWusVoaW1UdAxKqPAYbn_DV3iAA).

**Comment by TNtube** [comment]
Oh, I'm really sorry I totally forgot that this was necessary.

However, it still doesn't work in my main project, but I think i did something else that broke off this part.

Sorry again for waisting your time.
