### ISSUE TITLE
[Bug] Missing contrib files in 0.39

### ISSUE THREAD

**Issue by mattgodbolt** [microsoft/monaco-editor#4015]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

n/a

### Monaco Editor Playground Code

```typescript
n/a
```

### Reproduction Steps

webpack an app that uses 0.39 and observe the error:

```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 42:0-63
Module not found: Error: Can't resolve './contrib/copyPaste/browser/copyPasteContribution.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
 @ ./static/themes.ts 29:22-46
 @ ./static/main.ts 47:34-56

ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 46:0-73
Module not found: Error: Can't resolve './contrib/dropIntoEditor/browser/dropIntoEditorContribution.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
 @ ./static/themes.ts 29:22-46
 @ ./static/main.ts 47:34-56

ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 60:0-72
Module not found: Error: Can't resolve './contrib/inlineCompletions/browser/ghostText.contribution.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
 @ ./static/themes.ts 29:22-46
 @ ./static/main.ts 47:34-56
```

### Actual (Problematic) Behavior

I upgraded from 0.36.1 to 0.39 and some contrib files seem to be missing from the package. They are imported from `editor.all.js` but do not exist in the `contrib` directory:

```
contrib/copyPaste/browser/copyPasteContribution.js
contrib/dropIntoEditor/browser/dropIntoEditorContribution.js
contrib/inlineCompletions/browser/ghostText.contribution.js
```

e.g.
```
$ pwd
/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor
$ ls contrib/inlineCompletions/browser/
commandIds.js       hoverParticipant.js                  inlineCompletionsHintsWidget.css  singleTextEdit.js
commands.js         inlineCompletionContextKeys.js       inlineCompletionsHintsWidget.js   suggestWidgetInlineCompletionProvider.js
ghostText.css       inlineCompletions.contribution.d.ts  inlineCompletionsModel.js         utils.js
ghostText.js        inlineCompletions.contribution.js    inlineCompletionsSource.js
ghostTextWidget.js  inlineCompletionsController.js       provideInlineCompletions.js
```

there are no `.contribution.js` files there.

### Additional Context

Of course like all things this might be something I missed elsewhere, so please if you realise my mistake let me know!

**Comment by mattgodbolt** [comment]
For context, this is for https://github.com/compiler-explorer/compiler-explorer and can be repro'd fairly easily with a `npm install monaco-editor@latest monaco-vim@latest; && make dev`

**Comment by mattgodbolt** [comment]
For context, this is for https://github.com/compiler-explorer/compiler-explorer and can be repro'd fairly easily with a `npm install monaco-editor@latest monaco-vim@latest; && make dev`

**Comment by hediet** [comment]
Thanks for reporting! Can you figure out in which version this broke?

**Comment by mattgodbolt** [comment]
I will take a look, sure!

**Comment by mattgodbolt** [comment]
In 0.38.0 there's only one missing:
```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 60:0-72
Module not found: Error: Can't resolve './contrib/inlineCompletions/browser/ghostText.contribution.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
 @ ./static/themes.ts 29:22-46
 @ ./static/main.ts 47:34-56
```
Likewise 0.37.0
```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js 60:0-72
Module not found: Error: Can't resolve './contrib/inlineCompletions/browser/ghostText.contribution.js' in '/home/matthew/dev/ce/compiler-explorer/node_modules/monaco-editor/esm/vs/editor'
 @ ./static/themes.ts 29:22-46
 @ ./static/main.ts 47:34-56
```
though the webpack continued in this case (I'm very confused as to how)

I'm beginning to suspect there's some webpack cache thing going on here, so will clear caches in between builds.
