### ISSUE TITLE
[Feature Request] Expose capability to set HTML "required" property on textarea

### ISSUE THREAD

**Issue by raharri** [microsoft/monaco-editor#4021]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

For some use cases of the monaco editor, the editor's input area is a required property (for example, if the user must input a SQL query to fetch results). Currently the monaco editor doesn't expose a way to set the `required` or `aria-required` HTML property on the textarea element, which is an accessibility requirement for these use cases.

(This came up in an accessibility pass and @isidorn asked me to file a feature request here.)

**Comment by fsteffi** [comment]
**GitHub Tags:**#A11yTCS;#A11y_VSCode;#CAITestPass_May2020; #DesktopApp;#Win11;#MAS3.3.2;#Benchmark;#FTP;#A11yMAS;#A11ySev2;#AINotInScope;#Keyboard;#Visual Studio Code;

**Comment by hediet** [comment]
You can now set ariaRequired: true in the editor options.

[Monaco editor example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0-dev.20230707#XQAAAAJzAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzfibW_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAetfeRrm3VHdSe7_Etv6WpgzlH4vE8EOD3EPhJDl6tDpOO8RxKZbUytKns3T0NFFloo9Q21KsEBT298I6cyZc5-Glup9UHU6QTpv2Hjab6pZzB3ZO2RH-WGhzXse2-hNlgz6zCgsG8AjiqGg0ZzWzND7z09NmCQOQd6pfkNvO2zmMzFvHpTY8RFEy1urlQcQMb1HHLEESBi8m3Rr3UzFlKzY51hfYcz__QCePc) (use latest nightly)

**Comment by isidorn** [comment]
@hediet awesome! Should we go ahead and close this then?

**Comment by hediet** [comment]
It will be closed automatically once the implementing PR gets merged. Somehow the build timed out Friday.

**Comment by Tyriar** [comment]
No error on latest 0.41:

<img width="629" alt="Screenshot 2023-07-25 at 12 16 17 pm" src="https://github.com/microsoft/monaco-editor/assets/2193314/985ae7c8-983f-4e5f-ae69-12e6860c7680">
