### ISSUE TITLE
[Bug] autocomplete not work in json string value

### ISSUE THREAD

**Issue by YuJianghao** [microsoft/monaco-editor#4027]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[playground link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0#XQAAAALCAAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscmghGmlnuV4I7F1s5OnMdIbGePFKg2onkKBscfYHzqCyxL3X64pHtircOtrMMsdAxGtmwIVKL4G0s6K-2JAXMe2f7dY0thSBfAjOTEqgb8dlGFwNSWMPJqVYFf1qGsBeOA9_k3Wnc-NTTpvuVPm8T9msNA)

### Monaco Editor Playground Code

```typescript
monaco.editor.create(document.getElementById("container"), {
	value: '{\n\t"a": "kaaa",\n\t"b": ""\n}\n',
	language: "json",
});
```

### Reproduction Steps

1. create a new json key-value pair
2. move cursor inside value string
3. no autocompletion appear

### Actual (Problematic) Behavior

https://github.com/microsoft/monaco-editor/assets/17293034/7b55afb9-fa0f-4b76-86cc-5852570e9b84

### Expected Behavior

https://github.com/microsoft/monaco-editor/assets/17293034/98754c3b-cf1c-4e24-9d94-20703c9044a6

### Additional Context

Seems that vscode has fixed this problem.
vscode issue: https://github.com/microsoft/vscode/issues/32480
related pull request: https://github.com/microsoft/vscode/pull/151754

**Comment by hediet** [comment]
Thanks for the issue! I can reproduce. Your playground link points to a different example though.

**Comment by YuJianghao** [comment]
Sorry for the wrong link.
And It will be great if monaco can give me some instructions and let me fix it myself :p. Can I have the chance?

**Comment by hediet** [comment]
No worries! Here are some docs: https://github.com/microsoft/monaco-editor/blob/main/CONTRIBUTING.md

**Comment by YuJianghao** [comment]
Ah i mean instructions about hot to fix the bug. I tried word patterns but it doesn’t work.

**Comment by YuJianghao** [comment]
Tried something but failed. I think maybe the tokenizer cause this.

monaco-editor: https://github.com/microsoft/monaco-editor/blob/d514ddaa8d0ac3a3c11bffe6d3ca1bf9ee822228/src/language/json/tokenization.ts#L239
vscode: https://github.com/microsoft/vscode/blob/7ee813703ac68cc4fca333cd4ffead2d6dc64b22/extensions/json/syntaxes/JSON.tmLanguage.json#L138-L189

**Comment by YuJianghao** [comment]
@hediet hi, are there any plan to fix this bug?

**Comment by aeschli** [comment]
By default, quick suggestions do not show in strings. This can be changed with the options:
```
const editor = monaco.editor.create(document.getElementById("container"), {
	value: '{\n\t"a": "kaaa",\n\t"b": ""\n}\n',
	language: "json",
});
editor.updateOptions({ quickSuggestions: { strings: true }});
```
