### ISSUE TITLE
How can we disable a predefined shortcut ?

### ISSUE THREAD

**Issue by dengkunli** [Microsoft/monaco-editor#403]
I read through the API doc (```monaco.d.ts```) but cannot find a way to disable predefined shortcuts shipped with Monaco. Am I missing something ? How can we disable a shortcut (for example ctrl/cmd + e) ?

If there's no interface for disabling shortcut currently, will it be supported in the near future ?  Having no such interface makes the editor much less customizable.

**Comment by bcherny** [comment]
Related to https://github.com/Microsoft/monaco-editor/issues/287

**Comment by rebornix** [comment]
It's a dup of #287 and as that one is created earlier so let's track it there. Thanks @dengkunli for your input, I'll put them there.
