### ISSUE TITLE
[Bug] Paste events no longer bubble up in 0.39 (as of first dev version)

### ISSUE THREAD

**Issue by richardtallent-erm** [microsoft/monaco-editor#4030]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link
First Broken Version: v0.39.0-dev.20230503

https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0-dev.20230503#XQAAAAJyAQAAAAAAAABBqQkHQ5NjdQd7-lU4WDmTRXNufC05PLPEQjB1e8r-l0VdYxGK6eWVYpbIbNSq4i9Z0rF3EojW4Ao3327N24blVIRBFbIivSzhNslSXiPg1LaYPLkAJWurthMbpP-c9At9Uslz6tY071oM_09ZUihZkYdlgU8fsIL2O1uUGpc7YhKY3EHg6jXQkpfeJpyrNhLruzwhKO7g-jbI1cVKUOvdqCn9IDRaKeGp3fq3YQ1KHpTpMHSM8bM7VwLrR2vDOxhxpttC6WcSVir4lZFIAedyW7ekCu_fN9NrmkSUH-heWpANZ8rcke-n0khPnEUnOdL9Yfz8KSEI

Working Version: v0.38.0
https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAJyAQAAAAAAAABBqQkHQ5NjdQd7-lU4WDmTRXNufC05PLPEQjB1e8r-l0VdYxGK6eWVYpbIbNSq4i9Z0rF3EojW4Ao3327N24blVIRBFbIivSzhNslSXiPg1LaYPLkAJWurthMbpP-c9At9Uslz6tY071oM_09ZUihZkYdlgU8fsIL2O1uUGpc7YhKY3EHg6jXQkpfeJpyrNhLruzwhKO7g-jbI1cVKUOvdqCn9IDRaKeGp3fq3YQ1KHpTpMHSM8bM7VwLrR2vDOxhxpttC6WcSVir4lZFIAedyW7ekCu_fN9NrmkSUH-heWpANZ8rcke-n0khPnEUnOdL9Yfz8KSEI

### Monaco Editor Playground Code

```typescript
const value = "Hello"

const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
});

const myWrapper = document.getElementById("wrapper")
myWrapper.onpaste = () => alert("paste!")


<div id="wrapper" style="height: 100%"><div id="container" style="height: 100%"></div></div>
```

### Reproduction Steps

Try to paste text, an image, etc. into the playground preview editor.

### Actual (Problematic) Behavior

The paste event does not bubble up to the DOM parent (`wrapper` in this example).

### Expected Behavior

Paste events should bubble up to the DOM parent for detection and further processing.

### Additional Context

We use an `onpaste` event on the wrapper to detect what the user has pasted and make changes as needed in the editor.
For example, when editing markdown:
- if a user attempts to paste an image, we create a file for the image and insert a reference to it in the markdown.
- If a user pastes a link internal to our site, we replace it with a relative link.
This all hinges on access to the original event so we can inspect the clipboard and take action if appropriate.

This all worked beautifully in 0.38.0, but broke as of the first dev version of 0.39. There's nothing in the changelog about any related changes.

**Comment by mjbvz** [comment]
Try either disabling `editor.pasteAs.enabled` or hooking into the [new `Paste as...` support](https://code.visualstudio.com/updates/v1_79#_paste-as)

Disabling the paste as feature should bring back the old event
