### ISSUE TITLE
[Feature Request] Release monaco-editor-webpack-plugin

### ISSUE THREAD

**Issue by sonallux** [microsoft/monaco-editor#4032]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

The [CHANGELOG.md](https://github.com/microsoft/monaco-editor/blob/d514ddaa8d0ac3a3c11bffe6d3ca1bf9ee822228/CHANGELOG.md#L15) of `monaco-editor@0.39.0` mentions a bug fix for the `monaco-editor-webpack-plugin`. But unfortunately, no new release of `monaco-editor-webpack-plugin` with that change is available. Could you please release a new version of `monaco-editor-webpack-plugin`?

**Comment by hediet** [comment]
I just published [7.1.0](https://www.npmjs.com/package/monaco-editor-webpack-plugin/v/7.1.0).
