### ISSUE TITLE
I think it's an obvious bug.

### ISSUE THREAD

**Issue by powerumc** [Microsoft/monaco-editor#404]
monaco-editor npm version: 0.8.3
Browser: Chrome
OS: MacOS Sierra

I think it's an obvious bug. #330 

Step 1. Selection 3 line using mouse or keyboard.
Step 2. input Ctrl+/ for the comments.

![](https://content.screencast.com/users/POWERUMC/folders/Snagit/media/6be382a2-56d7-4141-84cb-eb2223c58ba8/2017-01-21_18-36-23.png)

I expected following's model.getValue()

1.
```js
function x() {
    console.log("Hello World");
// }
```

2.
```js
function x() {
//     console.log("Hello World");
// }
```

3.
```js
// function x() {
//     console.log("Hello World");
// }
```

**Comment by AndersMad** [comment]
I would not call that a bug - the model has changed and you get the changed events?.. enough for you to do undo per line..

maybe try the hidden `onDidChangeModelRawContent` since it will give you the full changed line(s) if that makes it easier..

**Comment by alexandrudima** [comment]
You can easily check when you are in sync with the model using `model.getVersionId()` and `e.versionId`. Also, in the upcoming release, the event shape has changed and a single event containing all the changes will be fired via `onDidChangeContent`:

```ts
	/**
	 * An event describing a change in the text of a model.
	 */
	export interface IModelContentChangedEvent {
		readonly changes: IModelContentChange[];
		/**
		 * The (new) end-of-line character.
		 */
		readonly eol: string;
		/**
		 * The new version id the model has transitioned to.
		 */
		readonly versionId: number;
		/**
		 * Flag that indicates that this event was generated while undoing.
		 */
		readonly isUndoing: boolean;
		/**
		 * Flag that indicates that this event was generated while redoing.
		 */
		readonly isRedoing: boolean;
		/**
		 * Flag that indicates that all decorations were lost with this edit.
		 * The model has been reset to a new value.
		 */
		readonly isFlush: boolean;
	}
```

**Comment by alexandrudima** [comment]
The upcoming release will get this new change event shape.
