### ISSUE TITLE
[Feature Request] Add DBML as a language

### ISSUE THREAD

**Issue by StathisKap** [microsoft/monaco-editor#4040]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

There's is this language called the DataBase Markup Language, which is very good for outlining the schemas of DBs, and the relationships between them. I'm trying to use it for a project of mine, but it isn't natively supported in monaco. I don't really know how to add it so if anyone else could help out I'd appreciate it.

Here's the specification
https://dbml.dbdiagram.io/home/

**Comment by hediet** [comment]
Let's add this language once it has its own wiki article to prevent a big bundle size of the monaco-editor.
