### ISSUE TITLE
[Feature Request] HOCON support

### ISSUE THREAD

**Issue by bkrajendra** [microsoft/monaco-editor#4043]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Add support for HOCON data.
Its JSON like format -  HOCON (Human-Optimized Config Object Notation) is an easy-to-use configuration format.
More information can be found here https://docs.spongepowered.org/stable/en/server/getting-started/configuration/hocon.htmlJSON-like

**Comment by hediet** [comment]
Let's add it once HOCON takes off. A good indicator for this is when there is a wiki page for it.
