### ISSUE TITLE
[Bug] Mobile Delete

### ISSUE THREAD

**Issue by Moritz-Deiaco** [microsoft/monaco-editor#4044]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual (Problematic) Behavior

When I try to delete code in my monaco editor at an android and ios phone, it doesnt works

### Expected Behavior

The code should get deleted when i press delete on the keyboard

```[tasklist]
### Tasks
```

**Comment by hediet** [comment]
The monaco editor does not support mobile.
