### ISSUE TITLE
[Feature Request]  we need the ability to customize completionItemkind

### ISSUE THREAD

**Issue by chl3188** [microsoft/monaco-editor#4046]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

When developing a new language by adding it to the Monaco editor, the basic completionItemkind is not enough to express automatic completion.
It's a feature that several developers have already requested, but please consider adding the feature again.
thanks.

**Comment by hediet** [comment]
Unfortunately, you have to fork the monaco-editor (vscode) for this.
