### ISSUE TITLE
[Feature Request] Support full-width horizontal scrollbars

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/monaco-editor#4048]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

A video is worth a thousand words:

https://github.com/microsoft/monaco-editor/assets/1812093/f367657e-c59a-4858-9eb1-4672cd36a9d5

Basically I like horizontal scrollbars that can span the entire width of the scrollable container, so in edge cases where both the horizontal and vertical scrollbars are fully scrollable there's a little bit of overlap.

I can't seem to be able to achieve the desired effect in Monaco though, because the scrollable thumb is positioned absolutely, and there's no option for making the scrollbar go full-width.

If an option for making the scrollbar full-width were added, or alternatively if the thumb was positioned relatively, e.g. with percentage units, I'd be able to achieve the styling that I want.

**Comment by hediet** [comment]
This seems to be styling for quite an edge case to me? I'd suggest to request this feature for VS Code, if more people are interested in this maybe we can prioritize it - otherwise it is unlikely we will work on this.
