### ISSUE TITLE
[Bug] Some css vars not set resulting in broken styles

### ISSUE THREAD

**Issue by JPlumridge** [microsoft/monaco-editor#4051]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

This is present in the "Hello Diff World" built in example:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0#example-creating-the-diffeditor-hello-diff-world

### Reproduction Steps

Create a diff editor using `monaco.editor.createDiffEditor`

### Actual (Problematic) Behavior

Certain css variables are showing up as not set, causing some styles to be broken.
I've only noticed issues in the diff editor.

E.g. `--vscode-scrollbarSlider-background` is not set, causing the diff editor ruler overview slider to be invisible, and `--vscode-scrollbar-shadow` is not set, meaning there's no box shadow between the original and modified diff panes.

Errors from playground:
No background set for slider:
![image](https://github.com/microsoft/monaco-editor/assets/5411573/edd58dcd-c0c6-4788-8555-2a3dad544486)

No box shadow for modified side editor, 
![image](https://github.com/microsoft/monaco-editor/assets/5411573/ba95a4d1-5c59-47c0-a2ed-43c7315181e6)

Both visible here:
![image](https://github.com/microsoft/monaco-editor/assets/5411573/17aaddad-74b3-4eba-9c72-f08e44de1bf9)

This screenshot is taken from the `browser-esm-webpack` sample, updated to use monaco-editor 0.39.0, and modified to create a diff editor.

### Expected Behavior

Expected box shadow separating original/modified diff views, and diff overview slider:
![image](https://github.com/microsoft/monaco-editor/assets/5411573/26932a02-ab3a-4708-9eb0-a4e1d24b46b9)

This is taken from the `browser-esm-webpack` sample, using monaco-editor 0.32.1, which I modified to create a diff editor.

### Additional Context

All the examples in the samples folder are using monaco-editor `0.32.1`, and the styles are working correctly. When I update to `0.39.0`, they are broken.

I've tested these samples, updated to create a diff editor where necessary:
`browser-esm-webpack`
`browser-esm-webpack-monaco-plugin`
`browser-amd-diff-editor`

I've tried setting what seems to be the relevant colour theme values, which has no effect.

**Comment by hediet** [comment]
This broke in https://github.com/microsoft/vscode/compare/39ff7eb93b513976b85b69085414cab11f8ed4cc...f730160c5d5fe36a7ad8db51f74f40a9d316e8b2
(v0.35.0-dev.20221116 is last working version)

**Comment by benjaminmillhouse** [comment]
Agree with the above - this seems related to where / how the new variables are defined / scoped.
If I define them in my own CSS file at the root they are applied properly.
Example:
```css
.monaco-diff-editor.monaco-editor-background.vs-dark {
  --vscode-editor-background: #1e1e1e;
}
```

**Comment by benjaminmillhouse** [comment]
To piggyback on this one.... the .diffViewport element is no longer being given any height either:
<img width="771" alt="image" src="https://github.com/microsoft/monaco-editor/assets/13835886/63c1e208-374b-4760-9ebb-11d43dfeeb3e">
