### ISSUE TITLE
[Bug] Runtime time error on editor click "Uncaught Error: g.getOccurrencesAtPosition is not a function"

### ISSUE THREAD

**Issue by mayarafernandes** [microsoft/monaco-editor#4053]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Click on the editor to change text

### Actual (Problematic) Behavior

We have a Javascript editor and sometimes when we click on it we get an error

```
errors.ts:26 Uncaught Error: g.getOccurrencesAtPosition is not a function

TypeError: g.getOccurrencesAtPosition is not a function
    at L.provideDocumentHighlights (tsMode.js:16:165)
    at errors.ts:26:12
```

I'm not sure it's relevant but we also have another editor set for JSON that doesn't thrown an error.

This is the code for the editor throwing the error

```
<MonacoEditor
    defaultLanguage='javascript'
    height='500px'
    value={javaScriptCode}
    options={{ formatOnPaste: true, formatOnType: true, autoIndent: 'advanced' }}
    onMount={handleJSMonacoEditorMounted}
/>
```

### Expected Behavior

No errors

**Comment by hediet** [comment]
Please provide a monaco edietor playground link to reproduce your problem. Thanks!
