### ISSUE TITLE
[Feature Request] editor.getLineWrapCount() and editor.getLinesWrapCount()

### ISSUE THREAD

**Issue by BubbaJoe** [microsoft/monaco-editor#4056]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

With the removal of `editor.viewModel.lines.getViewLineCount()`, there is no way to fetch the number of line wraps for each lines. So i would like to propose 2 function: `editor.getLineWrapCount(): number` and `editor.getLinesWrapCount(): number[]`

Context: 
https://github.com/Microsoft/monaco-editor/issues/947

Use case:
change the height of the editor based on the line count (with line wraps).

**Comment by hediet** [comment]
> change the height of the editor based on the line count (with line wraps).

Maybe contentHeight is what you are looking for?

**Comment by BubbaJoe** [comment]
@hediet Thanks, this is exactly what i needed!
