### ISSUE TITLE
API:getTargetAtClientPoint() doesn't work until the editor to be created after a while

### ISSUE THREAD

**Issue by dandingol03** [Microsoft/monaco-editor#406]
i need some help!!!!here is the case:
1.i call getTargetAtClientPoint immediately after  i create the editor ,but the API seems to output a wrong column
2.if i call the api after some seconds,it would works fine

**Comment by alexandrudima** [comment]
It is possible the editor is not yet painted on the DOM. you can force a paint via `editor.render()`
