### ISSUE TITLE
[Feature Request] option.attributeName

### ISSUE THREAD

**Issue by raphaelbastide** [microsoft/monaco-editor#4076]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I find `options.className` way too restrictive. A possible `options.attributeName` would allow adding any HTML attribute such as `data-`, `id`… One of the many use cases of adding such data to lines, would be to allow styling lines depending on their content and location, for instance:

- adding `data-line:'3';` for the line number 3
- adding `data-key:'id'` and `data-value:'10'` for line with a content such as `- id: 10`, previously parsed.

Why exposing data this way? My project is related to live coding and I need to target specific with specific content, line numbers to style them, in real time outside the editor’s scope. My case may be very specific and niche, but I am sure extending options with `options.attributeName` would be useful in other cases.

CodeMirror equivalent: https://codemirror.net/docs/ref/#view.Decoration%5Eline%5Espec.attributes

**Comment by hediet** [comment]
I don't think this is easy to implement unfortunately, as class names are broken up and combined with token styles.
Maybe line attributes are feasible, but without a use-case for VS Code we cannot prioritize such a feature.
