### ISSUE TITLE
[Bug] Json schema not working without `$schema` tag in json file itself

### ISSUE THREAD

**Issue by himanshupal** [microsoft/monaco-editor#4079]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

I've the code available [here](https://github.com/himanshupal/editors) with the config available [here](https://github.com/himanshupal/editors/blob/dev/src/workers.ts), current behavior of the app can be seen at [https://editors-ten.vercel.app](https://editors-ten.vercel.app)

### Actual (Problematic) Behavior

The schema provided in config doesn't get into action unless the same schema URI is used within the JSON file, which is not the expected behaviour IMO, once provided the schema in config, it should provide suggestions based on the schema (which happens in playground example too) without needing to specify any "$schema" key in JSON file being edited.

### Expected Behavior

I wanted it work as it is working in the playground, i.e. when provided with a schema in config, it shouldn't ask for the '$schema' in json file itself (in hover suggestion) but instead the keys from the schema provided in json config.

### Additional Context

IDK if it's relevant here, but I tried it on @monaco-editor/react too & got the same issue there too, don't know if I'm missing something or it's just buggy.

Already asked it on [StackOverflow](https://stackoverflow.com/questions/76656362/json-schema-not-working-without-schema-tag-in-json-file-itself) & couldn't get any answer there, that's why I had to open an issue.

**Comment by aeschli** [comment]
Schema associations can also be made in the settings. See https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#example-extending-language-services-configure-json-defaults

**Comment by himanshupal** [comment]
@aeschli Tried that already, not working until I manually specify the schema in editor too.
