### ISSUE TITLE
Hover widget shows no text in Safari 10.1

### ISSUE THREAD

**Issue by sandyarmstrong** [Microsoft/monaco-editor#408]
monaco-editor version: 0.8.1 (and also whatever's on the official playground)
Browser: Safari 10.1
OS: macOS 10.12.4

## Steps to reproduce

1. Open https://microsoft.github.io/monaco-editor/playground.html
2. Hover over any element that should show a hover tooltip.

## Expected results

Hover widget tooltip shows.

## Actual results

Empty box of the correct size shows, but text is not visible.

## Workaround

Click hover widget.

## Notes

From what I can tell this worked fine in Safari 10.0, but last week 10.1 was released and broke this.

It is also broken in WebKit apps on macOS 10.12.4 (but I believe works on 10.11 and earlier 10.12 releases).

**Comment by sandyarmstrong** [comment]
This seems to be some sort of animation regression. The following fix works for me:

```css
.monaco-editor .monaco-editor-hover {
    animation: none !important;
}
```

Interestingly, getting rid of `display:none` in the `monaco-editor-hover.hidden` class also worked.

In the playground, these changes only seem to work on the left editor. I guess that has something to do with the `iframe`'d nature of the other editor?

**Comment by rebornix** [comment]
It shares the same root cause as https://github.com/Microsoft/monaco-editor/issues/417.
