### ISSUE TITLE
[Feature Request] Follow "Keep a Changelog" format for CHANGELOG.md

### ISSUE THREAD

**Issue by schallm** [microsoft/monaco-editor#4080]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Would love to see you follow the [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) format.  I really like to see dates by the version number so I can quickly see how often you are releasing and the size of changes.

**Comment by hediet** [comment]
>  I really like to see dates by the version number so I can quickly see how often you are releasing and the size of changes.

We release stable every month and nightly every day.
