### ISSUE TITLE
[Bug] Completion items show underlines in website

### ISSUE THREAD

**Issue by alexdima** [microsoft/monaco-editor#4081]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [x] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

* open https://microsoft.github.io/monaco-editor/
* do ctrl+space

### Actual (Problematic) Behavior

> <img width="637" alt="image" src="https://github.com/microsoft/monaco-editor/assets/5047891/79730084-0963-4b87-917b-282bdc72f912">

### Expected Behavior

> <img width="546" alt="image" src="https://github.com/microsoft/monaco-editor/assets/5047891/825a8a1f-539a-427f-b6f5-244cac3f5f53">

**Comment by hediet** [comment]
This is fixed now.
