### ISSUE TITLE
[Feature Request] Explain basic concepts

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/monaco-editor#4084]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

On my repositories that contain Monaco editor, I sometimes get questions about Monaco editor from users who don’t understand some of the basic concepts. People think of it as a code editor, but really to use Monaco editor, people must have some basic understanding of:

- URIs
- Models
- Editor instances
- Providers
- Disposables

A little write-up on this would be nice. I could provide one if you want. Just let me know if this belongs on the wiki or readme.

**Comment by hediet** [comment]
> A little write-up on this would be nice. I could provide one if you want. Just let me know if this belongs on the wiki or readme.

That would be very nice!

Maybe even some diagrams could help (see CONTRIBUTING.md for inspiration).

I'd like to avoid docs that outdate quickly though, as we don't have the resources to keep them updated. The concepts you mentioned are very unlikely to become stale, so I don't think that's going to become a problem.
