### ISSUE TITLE
[Bug] colorizeElement doesn't work in shadow DOM

### ISSUE THREAD

**Issue by lucasMarioza** [microsoft/monaco-editor#4092]
### Reproducible in vscode.dev or in VS Code Desktop?

- [ ] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#XQAAAAJ8BgAAAAAAAABBqQkHQ5NjdYzqEXhNewrSKZslyM_G2I4bTkHQYW1lB1MplPA6z0speGDFvgRIQQx0HI9zdEFZdk3ipJqwzu6RT44vPXZPcpCKxnvgE9TYAtuAi9VQr3EAhbQJCn4JPD8EaFYCtRcYWa8_pnHjN-uDjxrhmN3g8tmx0iWUz1zF7VMROnGNjfHj2TFmcBooqFj0KG-T22ZUYX6V47dtQOs2ug0hkqY-bH884HzQTw7glMhVrANOxoMOevmMpD1j3QzduIqnxVxhrfGvmxxBviYbLqKEpoHhiDrP1KiZHiqV9S2vE-5x61fjaRQXOWjKysCswiOuDDqsItWHlNZBCpGywm1XXO1TBg8gWfxMoCeYYJHEM1x8bFE0BViHda5gjFeWTVarBmhwEntPuErIjNj8V4DJMpPiYeDBTb1Y7JContMWub0_JlzciiYjj_OlLNe-h7_hefM7aS3-wjmuct-utu8PY-xWvY9L1Hlk3b4Bb1UiNLfCCb5ZVOdGB-n_iWZ_Ky3j7KvwUXhvgqES6fxyxF10FoLyrTnTWuQpZigpwzWE6IHVzouDEMx7CEsO5uO5kvUJ051gcB8xcbX0_PAJvXV_-j9YXGEDhQEcl5vZ0AM0JoDt6uRz8I8hzyjIsOT9taKrJ_JmHg6Mw6lO1cIxNsh0fVZyTW2naTKM9tHfYI0MBcKT2aK6NkQtSa1O9VelT3pxKCKp3IjN-Re-RwxQudJQjllu3YVBtWhTIe8M4nrP3uoI9PbKGNUDTyKmPAkFUZivet0rYB1rFtUs-V9IdlYpA8MtRjAnJ90GdmLuSQkIjNK62-mlDNvk8ziLx6GKoez8QxDzDQigQ7JbC7LBz2Vb33cMyPOrhdfqNVs9_mAC1SsqbLJo-y5GmTutQKawyox2CnDUlgpJBf4TEJ-tnFkBKyTW3XeXoXbxeveGV0eKsyuiwGsE7U2nWwITvMHHTHTWLQL-dcz_RBLNr3hXICwhT2YcXpDpZ7eCOp1cI6kPnitacq56UhhtwYQ5zGCxpmkdGA0nIl37-LeqOD43Tk1XDD9C03CQ7e-TBcebOgo_8jgFy3kn-lGATnPEVJBH3cP3WZ49AnW6PgbLzDGlE_3AGQagzXB0R8_dba4m8l-ynWT46CVh8ZlFc_7_6wk

### Monaco Editor Playground Code

```typescript
const content = '/* Some example CSS */\n\
\n\
@import url("something.css");\n\
\n\
body {\n\
  margin: 0;\n\
  padding: 3em 6em;\n\
  font-family: tahoma, arial, sans-serif;\n\
  color: #000;\n\
}\n\
\n\
#navigation a {\n\
  font-weight: bold;\n\
  text-decoration: none !important;\n\
}\n\
\n\
h1 {\n\
  font-size: 2.5em;\n\
}\n\
\n\
h2 {\n\
  font-size: 1.7em;\n\
}\n\
\n\
h1:before, h2:before {\n\
  content: "some contents";\n\
}\n\
\n\
code {\n\
  font-family: courier, monospace;\n\
  font-size: 80%;\n\
  color: #418A8A;\n\
}\n\
'

customElements.define(
	"code-view-monaco",
	class CodeViewMonaco extends HTMLElement {

		constructor() {
			super();

			const shadowRoot = this.attachShadow({ mode: "open" });

			// Copy over editor styles
			const styles = document.querySelectorAll(
				"link[rel='stylesheet'][data-name^='vs/']"
			);
			for (const style of styles) {
				shadowRoot.appendChild(style.cloneNode(true));
			}

			const template = /** @type HTMLTemplateElement */ (
				document.getElementById("editor-template")
			);
			shadowRoot.appendChild(template.content.cloneNode(true));

			const container = shadowRoot.querySelector("#container");
			
			let pre = document.createElement('pre');
			pre.id="code";
			pre.style.width=  '500px'
			pre.textContent=content;
			container.appendChild(pre)
			pre.setAttribute('data-lang', 'text/css')
			monaco.editor.setTheme('vs')
			monaco.editor.colorizeElement(pre, {});
		}
	}
);
```

### Reproduction Steps

just run the code above.

### Actual (Problematic) Behavior

The code is not colorized

### Expected Behavior

the code should have been colorized

### Additional Context

I followed with some investigations and it's not being colorized because the theme styles is not in DOM.

Debugging the code, I found that the [`styles` element is actually being created as a child of the DOM element to be colorized](https://github.com/microsoft/vscode/blob/main/src/vs/editor/standalone/browser/standaloneThemeService.ts#L287).

Later, the[ text to be colorized is extracted using `domNode.firstChild.nodeValue`](https://github.com/microsoft/vscode/blob/main/src/vs/editor/standalone/browser/colorizer.ts#L43), so ignoring the `styles` that is the last child at this point.

But, after processing the text, it's [re-inserted back into the original domNode by `domNode.innerHTML = trustedhtml`](https://github.com/microsoft/vscode/blob/main/src/vs/editor/standalone/browser/colorizer.ts#L47). This replaces not only the colorized text, but every children of the domNode, including the `styles` element that was just generated.

**Comment by lucasMarioza** [comment]
Also, it works if you have an editor instance in the same shadow DOM ([playground link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#XQAAAAKpBwAAAAAAAABBqQkHQ5NjdYzqEXhNewrSKZslyM_G2I4bTkHQYW1lB1MplPA6z0speGDFvgRIQQx0HI9zdEFZdk3ipJqwzu6RT44vPXZPcpCKxnvgE9TYAtuAi9VQr3EAhbQJCn4JPD8EaFYCtRcYWa8_pnHjN-uDjxrhmN3g8tmx0iWUz1zF7VMROnGNjfHj2TFmcBooqFj0KG-T22ZU8_yilur7V4L1ukMUgfsN_RvW1Y-SJKhdONb-W5FrHlCQkH3NEpCBPRoBKOOEH3-cph124rjRYvGdEo3ArMMUv-25vm9KAd1VTsoBdVcQ_FR0aupepU3weYQVG2qtEOzIBtn_usoyFTPzdcXNd3Tn6VK_GIUqOJsy_ROBVJ7fgH28gylxLcBfBkogqjN1-1sDEf-saag2Z3tOvzKbCBXL2ZHc8lX6w64FGwinFFrvzPF4w72M6uv6Sm592WQrbXlkRN_dkhayKrFmIaxyn7txKRAVy8jnRLbiBbBNMh-8hi-RzrcYceHfBxA1VIC22SJxW0Z71xk3eTc2ufJh6NMBqhB25D1OU-jW8-N2x-KnmrbXI6ITXWKWXi2E0yMcqwBdO5JDzm0lBJUTOMSvVX1Ukjmclef1WbHnvjsUEnwhH07IBwIQXtHavyOXIAOQxgk8dbCx7Opv9wDb1619N7VH1fHDTriv8rOmlBEUmlgRD3dNBBNedFrvnbT5wJ43pzzFLbSPtea4SBKgnFVlMqvJJsT5HVZvsFAlpYjpQP9O6RmVChdsop5TmxwJuhCHTNEXDel3q-zZYNoTJJsg_AHEKqlOBpIS3zoij8TReKTmcLsGS_1mb5dbNzGIDMUnC2YJFcmH6vP_KoOSfsdamQH6n9dVrt-f2rxavbplZhYziL1fLgo4j_R74X4823QTaOEx5_t0lYGTB0y6YH32FETY8YU3lA1rXj01ff-R00_jS_7Vqj_9v_AK95UCm492fR8G4f7RfNGZaF-rdsvBLML4-F9BwL1MOxQLwcf7Wi9fykv7ASl4mU6sdJePDcBSDUPr0fTLZ2ZYR7kSc-khCVDNCY9nmycPPJoWGSFfqFDCLgmQ1nsCa-gd4boU8iVezDTXzCMYpzDBezlkp46Ay0hd1Y_3B4v3WbUnCBl_vrNO8gdk8cDRtBmB4n8gXARNyo-LMVws58gCmci2XsIvWlqLgKyc9XtvCA8vO2MGRfqfmBZ57fy5ms81ml777BDpKgllwwxhMDOZ6pgxDeiCaWCBglFzI-sbCPqnJbtnbY4KKQhfDS6ljpDK59LPKHmg__mNUbU))

**Comment by romainr** [comment]
On way could be to reapply/add the `styles` to the `domNode` after it has been processed so that they don't disappear?
