### ISSUE TITLE
Getting compilation error when compiled with latest version of monaco editor

### ISSUE THREAD

**Issue by ManojkumarV** [microsoft/monaco-editor#4093]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

 node_modules/monaco-editor/monaco.d.ts(1668,28): error TS1005: ',' expected.
 
 Getting the above error when compiling with the latest version of monaco editor npm module in a typescript project. 

blockPadding?: [top: number, right: number, bottom: number, left: number] | null;

The above property is used in the interface IModelDecorationOptions which is throwing the error.

**Comment by hediet** [comment]
You are most likely using an old version of typescript.
I recommend to update or to enable skipLibCheck.
