### ISSUE TITLE
[Bug] Setting an empty Modified model on a DiffEditor when Original model has blank line breaks diff rendering

### ISSUE THREAD

**Issue by JPlumridge** [microsoft/monaco-editor#4094]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#XQAAAAL8AQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0U-3bu-n-4FNw7EJFXfE5zHCAAPkGl4JHQWBB-9rQk5cWb5_-IQthYi5LkNLGwByA0lY9_5bFqLg0Rhf7FI8nzEerlnRL193_Y2XJVskftR8-vnUgl96V7R47U3HydIbScTg_w1_VtOLh0Hyq4eT5iHcsyMevVAj7I1sZb9vm1fwdepUam03KL71RuIOKMYaSgPQABiYarXNkBpR_q2YE8Za7KYVueD1B-5YhNJzlbqDIuNawTh7bx388o2-LwyNT2DmHfxCci1Cxnco8MW2CJ7kHtNfmt7942laKaG6DlQJlysW5Ons_dk7QMDI2ojHfLQe_jgREg

### Monaco Editor Playground Code

```typescript
const originalModel = monaco.editor.createModel(
	['function x() {', '\tconsole.log("Hello world!");', '', '}'].join('\n'),
	"javascript"
);
const modifiedModel = monaco.editor.createModel(
	'',
	"javascript"
);

const diffEditor = monaco.editor.createDiffEditor(
	document.getElementById("container"),
	{
		originalEditable: true,
		automaticLayout: true,
	}
);
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel,
});
```

### Reproduction Steps

1. Use `monaco.editor.createDiffEditor` to create a DiffEditor
2. Create an Original model via `monaco.editor.createModel` that includes a blank line in the middle of some lines with text
3. Create a Modified model via `monaco.editor.createModel` with an empty string
4. Set these models on the DiffEditor using `diffEditor.setModel`

### Actual (Problematic) Behavior

The original, left hand model matches its blank line with the empty line 1 on the modified, right hand model, and these lines receive no colour highlighting:

![image](https://github.com/microsoft/monaco-editor/assets/5411573/bed5e5b0-9100-4539-9d9e-f3b98fd8cf46)

### Expected Behavior

A single, empty, green line is rendered on the modified, right hand side.

Screen shot from v0.37.0, which I found to be the last working version:

![image](https://github.com/microsoft/monaco-editor/assets/5411573/7d7d1841-a03a-4985-8247-d53bf9605b6e)

### Additional Context

If the test data is swapped so it's the Original model that is set to empty, current v0.40.0 works fine:
![image](https://github.com/microsoft/monaco-editor/assets/5411573/fc182547-58ad-440b-9031-31ac4d48c5b9)

In VS Code, when I try to reproduce this using a deleted file in Git, it's not reproducible because when the modified model is empty (i.e. the file is deleted), no RHS is rendered at all. Whereas for new files, the LHS shows up as a single, empty red line.

**Comment by hediet** [comment]
Fixed in the latest dev release.
