### ISSUE TITLE
[Bug] (In 0.19.0+) When scrolling the mouse wheel over the editor and reaching the top or bottom end, the parent element does not scroll

### ISSUE THREAD

**Issue by hiuny** [microsoft/monaco-editor#4097]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://codepen.io/Hwihun-Cho/pen/gOQdKNQ

### Reproduction Steps

Scroll down with the mouse wheel over the editor until you reach the end, then scroll down further.

### Actual (Problematic) Behavior

Even if you reach the top or bottom of the editor, the parent element does not scroll.

### Expected Behavior

After reaching the top or bottom of the editor, the parent element should be scrolled.

### Additional Context

- I wrote a codepen demo because it could not be reproduced in vscode.dev or monaco editor playground.
- It works normally in 0.18.0, but it doesn't work from version 0.19.0.

**Comment by stefandobre** [comment]
Have you tried setting `alwaysConsumeMouseWheel` to `false`?
https://microsoft.github.io/monaco-editor/docs.html#interfaces/editor.IEditorScrollbarOptions.html#alwaysConsumeMouseWheel

**Comment by hiuny** [comment]
@stefandobre 
Thank you for answer. I just tried putting false in alwaysConsumeMouseWheel and it's the same.
