### ISSUE TITLE
[Feature Request] alwaysConsumeMouseWheel touch equivalent

### ISSUE THREAD

**Issue by ayroblu** [microsoft/monaco-editor#4108]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I wanted to use `alwaysConsumeMouseWheel` for both scroll and touch events. However I noticed that only scroll events are supported. This means that if you set `alwaysConsumeMouseWheel: false`, it works correctly for scroll events, but tap and drag still mimics the "true" behaviour.

Same applies to `handleMouseWheel: false`, where the editor will no longer scroll, but the tap and drag gesture still scrolls it.

I couldn't find any touch equivalent of these options, happy to be directed there

**Comment by hediet** [comment]
I'm not the author of `alwaysConsumeMouseWheel`, thus I lack some knowledge.

> This means that if you set alwaysConsumeMouseWheel: false, it works correctly for scroll events, but tap and drag still mimics the "true" behaviour.

Can you clarify what you mean with "mimics the true behaviour"?

**Comment by ayroblu** [comment]
Sorry for the confusion! I meant it has the same effect as if the value for `alwaysConsumeMouseWheel` is true as in the Boolean

**Comment by CGNonofr** [comment]
For what it's worth, here's a hack:

```typescript
function preventAlwaysConsumeTouchEvent(editor: monaco.editor.IStandaloneCodeEditor) {
  let previousX = 0
  let previousY = 0
  let atTop = false
  let atBottom = false
  let atLeft = false
  let atRight = false
  let useBrowserBehavior: null | boolean = null

  const domNode = editor.getDomNode()!
  domNode.addEventListener('touchstart', (e) => {
    const firstTouch = e.changedTouches.item(0)
    if (firstTouch == null) {
      return
    }

    // Prevent monaco-editor from trying to call preventDefault on the touchstart event
    // so we'll be able to use the default behavior of the touchmove event
    e.preventDefault = () => {}

    previousX = firstTouch.clientX
    previousY = firstTouch.clientY

    const layoutInfo = editor.getLayoutInfo()
    atTop = editor.getScrollTop() <= 0
    atBottom = editor.getScrollTop() >= editor.getContentHeight() - layoutInfo.height
    atLeft = editor.getScrollLeft() <= 0
    atRight = editor.getScrollLeft() >= editor.getContentWidth() - layoutInfo.width
    useBrowserBehavior = null
  })
  domNode.addEventListener('touchmove', (e) => {
    const firstTouch = e.changedTouches.item(0)
    if (firstTouch == null) {
      return
    }

    const dx = firstTouch.clientX - previousX
    const dy = firstTouch.clientY - previousY

    if (useBrowserBehavior == null) {
      if (Math.abs(dx) > Math.abs(dy)) {
        // It's an horizontal scroll
        useBrowserBehavior = (dx < 0 && atRight) || (dx > 0 && atLeft)
      } else {
        // It's a vertical scroll
        useBrowserBehavior = (dy < 0 && atBottom) || (dy > 0 && atTop)
      }
    }
    if (useBrowserBehavior) {
      // Stop the event before monaco tries to preventDefault on it
      e.stopPropagation()
    }
    previousX = firstTouch.clientX
    previousY = firstTouch.clientY
  })
  domNode.addEventListener('touchend', (e) => {
    if (useBrowserBehavior ?? false) {
      // Prevent monaco from trying to open its context menu
      // It thinks it's a long press because it didn't receive the move events
      e.stopPropagation()
    }
  })
}
```

**Comment by hediet** [comment]
Closing, since the relevance of this is unclear and there seems to be a workaround.

**Comment by ayroblu** [comment]
I don't agree with the hack, is there something I can do to help make this clearer? I'm not sure what I'm missing. Basically you can't scroll the screen on a touch screen if you're not a full screen Monaco app
