### ISSUE TITLE
[Bug] GlyphMarginWidget does not render on correct line with wordwrap

### ISSUE THREAD

**Issue by Cakedonut** [microsoft/monaco-editor#4110]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0-dev-20230802#XQAAAAKwBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw7AljjfGetpg8d5BCIdogK6CBmgyKHIOVjH6uO-oA-RA-rcpQdGBlgwMT7NDeGjyzFr76MYz0c_YZhkfVact8aTrKHuAnAkqJpMk6UhIwJtZVTQC9B4mvWfKjuRkq43LUQV5kh87LmwrTRb1C2RhKXHf6Of5m38DlZLIqz-vPTwHKgnOzvU7wPeNRKcGVqROb7_-9jrRt5y0vf93MIrr5T4NKYBeSdR1D83Q2gEG3KUz3BC5Inr_H50o0PPCTzJotO8rv9JncxNh8ggdtHazxLXLXy0y9heEfFC60DrTsFsJbYsrxVOviHfTtdSRidSJICbWMUqp9V51pYRYaYZEKocoGuZKQAVBgyjWPJKE1QKxY68GVceP4s9PPLBnf35-Y56jE6bxwZyT9_ZInAsfE1fzv-YdbjfyF3tBaDcQA7KbVLiW7bcS49fD2CSc5EFdoUhZ8Eb3QsPkl7Ur7pDOU0O9H38Zd1DHstV6dYQPNCGzZ0UE6m4ya9DBK94cGQtx8soPv7BRK9sODW9eeCtHs0wucRinOmqruMPL8sIQegt4UwEq7E5iPxHo4kpb2tC90p_2eh6rJZWM2J-lVON-rpf2zvaA0QY11ougLpFKBVOSPG5xtQ-SQEQh8eLLTSX01NQhPa6lHkdVGQNOPPzLvCx_WhJUuu9-1tp4-4y4-KlbDf_DoCmcDOm__yN9A4g

### Monaco Editor Playground Code

```typescript
const value = /* set from `myEditor.getModel()`: */ `function hello() {function hello() {function hello() {function hello() {function hello() {function hello() {function hello() {function hello() {function hello() {function hello() {function hello() {
	alert('Hello world!');
}`;

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
	glyphMargin: true,
});

myEditor.updateOptions({ wordWrap: 'on' });

var widget = {
	domNode: (function () {
		var domNode = document.createElement("div");
		domNode.innerHTML = "A";
		domNode.style.background = "red";
		domNode.style.display = 'block';
		return domNode;
	})(),

	getId: function () {
		return 'some-id';
	},

	getDomNode: function () {
		return this.domNode
	},

	getPosition: function () {
		return {
			lane: monaco.editor.GlyphMarginLane.Left,
			range: {
				startLineNumber: 2,
				endLineNumber: 2,
				startColumn: 1,
				endColumn: 2,
			},
			zIndex: 100,
		}
	}
};

myEditor.addGlyphMarginWidget(widget)
myEditor.layoutGlyphMarginWidget(widget);
```

### Reproduction Steps

1. Create an editor that has wordWrap on
2. Add a bunch of text that causes wordwrapping
3. Add a glyph margin widget to a line that is below wordwrap
4. Notice glyph margin widget is not placed correctly due to the wordwrapping

### Actual (Problematic) Behavior

GlyphMarginWidget is not placed correctly when the editor has wordWrap on and there are lines which are wrapped.

### Expected Behavior

The GlyphMarginWidget should place itself correctly based on the range passed in, even when there is wordwrapping occurring.

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode/issues/198674
