### ISSUE TITLE
[Feature Request] Allow delay configuration for inlineSuggestions similar to quickSuggestionsDelay.

### ISSUE THREAD

**Issue by rissato** [microsoft/monaco-editor#4119]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Please consider adding configuration for delay to trigger inlineSuggestion providers. I played with quickSuggestionsDelay option and it does what I want but for quick suggestions instead.

The end goal is to be able to configure activation delay to reduce the number of backend API requests.

Or if there is any other way to identify the cursor (not) moving over a period of time that would be ok as well.

Thanks,

**Comment by hediet** [comment]
> to reduce the number of backend API requests.

You can do a await waitMs(1000) in your provide inline completions implementation. After that delay you have to check the cancelation token.
That way, you can increase the debounce rate.
