### ISSUE TITLE
[Bug] "Configuring language defaults and IntelliSense broken in 0.41.0

### ISSUE THREAD

**Issue by larshp** [microsoft/monaco-editor#4120]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

0.40.0 example works,

https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#example-extending-language-services-configure-json-defaults

while 0.41.0 is broken,

https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0#example-extending-language-services-configure-json-defaults

no errors or warnings in console

Expected result: syntax highlighting and schema validation working, however, the text is just grey with no annotations/diagnostics,
![image](https://github.com/microsoft/monaco-editor/assets/5888506/99c5b43f-de18-41c2-947e-617c1915f585)

while it works in 0.40.0:
![image](https://github.com/microsoft/monaco-editor/assets/5888506/f29428cb-641e-4eb3-b369-ddd2160133de)

**Comment by blutorange** [comment]
Seems this does not apply to JSON only, I noticed the same for JavaScript / TypeScript in primefaces-extensions/primefaces-extensions#1267 From what I've seen, the entire IntelliSense for JavaScript / TypeScript seems to be gone when it happens. I also noticed it a few time for CSS. Perhaps it's also a timing issue, as for some cases, it was working sometimes and sometimes not.

Can also be reproduced on the playground. [Playground link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#XQAAAAJDBgAAAAAAAABBqQkHQ5NjdMpUO-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSwDRSrPoYmS0boheFzzsv5XK2WZ0xqh2VljNhzGSXaZ4DFcKQ0yO-9KGlWqhcUp66DqLbGj4TjZxlrp6T3xzZ8DSLIrXtHpvsssKTqPq3LSW3DBiUNFIXAgG6qKysQ74z49pxpU2SsXU3xB9hCpelREoFA_7-OqE8Bgb2J-MM9jR2rBhPG8HV5hXJGg__u_ybkgKKJa65_kss98b50s_uWt_aEECmjLrxUYaiDlGkVRsDz3HbIRwgwhK7fMFIou8XvgGwVlmDDnxumhr5EWTU9wcZoe_Qn2fOaCUvocfoKXLuBd9S59VrRY_ZIhLF1KUYdacwpdUYTUT0NC0nPd5pmA7OZDIk7DdFHn7olMasJVjbvhjqURr06XwumVhBmJJ-g7Lbo8F7IMdKPu_xqavQ6LSM-gl_-xGAGwsQZPd7sYGxczq5mH_-WmIezMuwwavN9hM2QfW8BRum-YEpgQq83o5KmPYUcfbArRZ_1XCkg2aLJzLH8sqmMS2lhxbWjALjwJWwVKTAw8ccrCgQVPc2Vb5sRh7XZojWakLqoYx4gQu2GeAQF6rQxM748lPLSV5TMYwxVrunyPkKvkr84j0qjP_aQEZZfWVhBzgLlXMWd4lDiZrma8rdtQ9I_6lGrjJ9Z74Kwgrq7Tsex91mGf2-FmOVzsrqz84OGjJ3bQiuDnlHvQ2kqyDTp-yYH8XO3_qQp2NUyC9JNsqbHPbTJLJf2M36IXFTqxaE_w5GzyGgQN5j-zKca_thPc1K_IkimxPC65t2MamABGtizIa1deka3IZ_4737Xp3av705_l54FP_zEV3MA)

 The following loads the type declarations for JQuery and applies them. It should show the `ready` method as deprecated. This is working with version 0.40.0

![image](https://github.com/microsoft/monaco-editor/assets/2456413/7cba84ca-4cf2-47a4-91ae-34bf970ae42d)

but not with 0.41.0

![image](https://github.com/microsoft/monaco-editor/assets/2456413/902e3fde-1615-4f10-98a7-65c3a1516262)

**Comment by bragle** [comment]
Seems like this stopped working in `0.41.0-dev.20230714`. Installing `monaco-editor@0.41.0-dev.20230713` should temporarily fix the issue

**Comment by alexolivier** [comment]
+1 on this being fixed please

**Comment by lmcsu** [comment]
Got the same issue with TypeScript syntax.
Rollback to 0.40 works

**Comment by 4MOR3** [comment]
i ran into this problem too.
I'm using amd to load monaco-editor, and the language's worker.js would not be load when the model/editor is created

**Comment by AviVahl** [comment]
Saw the same when loading monaco using esm.

**Comment by marcellobarile** [comment]
I chime in with the 0.41.0 issue with syntax highlight and validation. Downgrading to 0.40.0 seems to be a wise choice.

**Comment by blutorange** [comment]
@larshp Perhaps you could change the title of this issue to `[Bug] "Configuring language defaults and IntelliSense broken in 0.41.0`, seeing that this problem appears to be more wide-spread?

**Comment by larshp** [comment]
updated

**Comment by hediet** [comment]
Sorry, I wasn't aware of this issue. I'm quite sure this broke with https://github.com/microsoft/vscode/commit/52d462293dba671b3d2417a299d3b61dfd4c8124.
