### ISSUE TITLE
[Bug] Diff is not computed properly when you update existing models (with version 2 only)

### ISSUE THREAD

**Issue by jairbubbles** [microsoft/monaco-editor#4129]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0#XQAAAALjAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0KH7IAlP8kaQWFkq7cA4EKkbm30oUWchkQnEl18uqd9AAhuyh39JLK0caIu2YQCgQR3BhQzfeC9wvEfH-6-MewTiA4AfDvBc1YbRrx70D9AiokBllD7_hNSqBddPhbOo2CtCJ-CsGHu0-2gf6ulNXx1OTDKQq82XxedZ5LtZ8HuyhESakJutip-0Ep-7LrWuiHN1mRNUCIVOHEBhmATUfOTEZ6WMxCZIIy5MhokfWdp8CAqN1tmYS_sNGnRooflt5CYTYgrkFmsjIcG5pMG3UaQA37BA_4WAWP_2-0AJ

### Monaco Editor Playground Code

```typescript
const diffEditor = monaco.editor.createDiffEditor(
	document.getElementById("container"),
	{
		experimental:
		{
			"useVersion2": true,
		}
	}
);

const originalModel = monaco.editor.createModel("a\nb\nc",	"text/plain");
const modifiedModel = monaco.editor.createModel("a\nb\nc\nd",	"text/plain");

diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel,
});

modifiedModel.setValue("a\nb\nc\nd");
```

### Reproduction Steps

Just open the playground and observe that the diff is not correct:

![image](https://github.com/microsoft/monaco-editor/assets/15875066/9ed8b0c1-2927-4f69-9b9a-a8c168615ae9)

If you comment `"useVersion2": true,` it will work correctly.
Also, as soon as you edit the right content, the diff will refresh correctly.

### Actual (Problematic) Behavior

All lines appear modified

### Expected Behavior

Only line 4 appears modified

### Additional Context

This is a simplified example but I did experience the issue in a more complex application where files are automatically reloaded when externally changed.

**Comment by jairbubbles** [comment]
If I set the model afterwards it fixes the diff:

```javascript
const diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"),	{experimental:{ "useVersion2": true, }});

const originalModel = monaco.editor.createModel("a\nb\nc",	"text/plain");
const modifiedModel = monaco.editor.createModel("a\nb\nc\nd",	"text/plain");

diffEditor.setModel({original: originalModel,modified: modifiedModel});

modifiedModel.setValue("a\nb\nc\nd");

diffEditor.setModel({original: originalModel, modified: modifiedModel});
```

**Comment by hediet** [comment]
Thanks for reporting! Should be fixen in the next nightly build once the PR got merged.

**Comment by jairbubbles** [comment]
Awesome! 🥳

**Comment by hediet** [comment]
Fixed in https://github.com/microsoft/vscode/pull/190802
