### ISSUE TITLE
[Bug] completion item documentation doesn't show in Chrome

### ISSUE THREAD

**Issue by LyqXMU** [microsoft/monaco-editor#4132]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.40.0#example-extending-language-services-completion-provider-example

**Comment by LyqXMU** [comment]
Actual (Problematic) Behavior
You need to click the arrow in the right to open manually
Expected Behavior
documentation shows when item selected

**Comment by hediet** [comment]
Please fill out the form properly. Also please share screenshots. Thanks!
