### ISSUE TITLE
Intellisense doesn't work in typescript until the model is changed

### ISSUE THREAD

**Issue by darind** [microsoft/monaco-editor#414]
Hello,

I create the 2 typescript models like and load the first model into the editor:

```typescript
require(["vs/editor/editor.main"], () => {
    var model1 = monaco.editor.createModel(`
        import { Model2 } from "./model2";
        export class Model1 {
        }
    `, "typescript", monaco.Uri.parse("model1.ts"));

    var model2 = monaco.editor.createModel(`
        export class Model2 { 
        }
    `, "typescript", monaco.Uri.parse("model2.ts"));

    var editor = monaco.editor.create(document.getElementById("code-editor"));
    editor.setModel(model1);
});
```

The Intellisense doesn't recognize the import on the first line and a red squiggle is shown on the `"./model2"` import statement. If I make a change to the editor (for example insert a space somewhere), the error disappears and the Intellisense starts working as expected.

Is this a known issue and is there a way to force the editor reload its decorations?

---

UPDATE:

I managed to get this working by adding the files as extra libraries as well:

```typescript
monaco.languages.typescript.typescriptDefaults.addExtraLib(`
    import { Model2 } from "./model2";
    export class Model1 {
    }
`, "model1.ts");
monaco.languages.typescript.typescriptDefaults.addExtraLib(`
    export class Model2 { 
    }
`, "model2.ts");
```

The problem with this approach is that I get errors when I try to compile the model:

```typescript
monaco.languages.typescript.getTypeScriptWorker().then(worker => {
    worker(model1.uri).then(client => {
        client.getEmitOutput(model1.uri.toString()).then(result => {
            // result.emitSkipped is true here
        });
    });
});
```

and I suspect that this is because of the duplicate class definitions. So I suppose that this is not the correct way of handling this issue.

**Comment by joewood** [comment]
I see something similar. When I add those external models it seems to work OK, in that TypeScript code in the editor can reference the other model's file URIs:
```typescript
import * as Model1 from "./model1"
```

However, if I leave the editor running I will suddenly see the red squiggles under the import filename and the reference is broken.

**Comment by WinfredWang** [comment]
I have the same problem，looking forward to the correct answer. Thanks.

**Comment by darind** [comment]
It seems that setting the following option will resolve the issue and the `addExtraLib` calls are no longer necessary:

```
monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true);
```
