### ISSUE TITLE
[Bug] Word wrap allows for horizontal scroll

### ISSUE THREAD

**Issue by mma-qualtrics** [microsoft/monaco-editor#4143]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual (Problematic) Behavior

After setting `wordWrap: 'on'`, text in the monaco-editor does not wrap when it overflows in the container. As a result, there is a horizontal scroll bar and text is hidden.

![Screenshot 2023-08-28 at 1 06 56 PM](https://github.com/microsoft/monaco-editor/assets/143443295/725b7420-c7df-48d2-b4aa-605cd23a43dd)

![Screenshot 2023-08-28 at 1 06 11 PM](https://github.com/microsoft/monaco-editor/assets/143443295/7627d88d-e733-4de7-8bbd-699898294732)

### Expected Behavior

When `wordWrap: 'on'` is set in the monaco config, there should be no horizontal scroll and all text is visible in the editor regardless of resizing.

![Screenshot 2023-08-28 at 12 53 44 PM](https://github.com/microsoft/monaco-editor/assets/143443295/d019f67e-45d2-4031-bab6-15c079342f8c)

### Additional Context

This is the monaco-editor config 
```
componentDidMount() {
    import(/* webpackChunkName: "monaco-editor" */ 'monaco-editor').then((m) => {
      monaco = m
      this.editor = monaco.editor.create(this.editorEl.current, {
        value: code,
        language,
        readOnly,
        wordWrap: 'on',
        // automaticLayout: true,
        minimap: { enabled: false },
        padding: { bottom: 5, top: 15 } // Configure padding around code within code editor
      })
  })
}
```

monaco package version
```
"monaco-editor": "^0.23.0",
"monaco-editor-webpack-plugin": "^3.0.1",
```

There are no css rules applied to the monaco-editor itself. 

When minimap is enabled, the same problem exists
![Screenshot 2023-08-28 at 1 16 42 PM](https://github.com/microsoft/monaco-editor/assets/143443295/3913d5c7-a145-4463-9c68-7e14ec40a4c5)

**Comment by KirtiKamal** [comment]
@mma-qualtrics I want to work on this issue please assign me . As I am new to opensource please help me to work on this issue

**Comment by mma-qualtrics** [comment]
@KirtiKamal theres no option for me to assign. Am I missing soething?
![Screenshot 2023-08-29 at 10 59 15 AM](https://github.com/microsoft/monaco-editor/assets/143443295/0d5f83ad-421f-4a9b-948a-3003126e8e57)

**Comment by KirtiKamal** [comment]
Ok you can suggest the changes that you actually want to say so that I can give a PR and after PR if it will merged no need of assign I think...

**Comment by KirtiKamal** [comment]
How can I setup this project in my local system??

**Comment by mma-qualtrics** [comment]
let me look into setting up a sandbox

**Comment by KirtiKamal** [comment]
Have you done a setup in your local system??
