### ISSUE TITLE
[Bug] Lane parameter of GlyphMarginWidget seems to be configured and cannot work

### ISSUE THREAD

**Issue by NWYLZW** [microsoft/monaco-editor#4144]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0-dev-20230802#XQAAAALRAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw40qQnc4m7jWi3uGQetsfyL9Rw59E2COVxnxnvCRAg0kwCdQb8ogwu-POzKkkdtD5T7ftMOciItf5sNfdz3glkVyhab3fb-vdOYqBGSKPB_xWM4Wo2Qm9AVrnpr3IpkaLL4w8STWIndQuehaZZLzSPXLcjAkbrNOQeVkwRHWE87KjOFSQIjx5Qlkz4pMkOeRml_6A2u39zNX8rlNvqsv0SnIGiPn3kUGzyeMs8upiIU6zxlVTJm5Zs1DOdRU6kihKafPf_VyYS-XKV-jrxRNeEfffwyzFVFBk_qXkqxlkBnOA4AkTz2UGfeYaRJoro1Z96cVA5KzrLmHF4_DLtzn2Tct9_9QbCYJloEnDZim6HSnsjwupRXfI0IfHxL61i56B-u9xXhWgng-5Pr3CNc9zcu2v3R5HOi3ZY5zAB9eKsb-AT1oRYhACTaoisiDzpylI4Lc6Q_RIp5YyzC0oD3heAOVqH64ZL6invYgvnk1zNzkKPIqI0kYO0hb0Ki-NdYzE_acmba26CDmzU1VEmz8VG-QdBcdqZIvws5zyXfizmT7sUH4cfOUYsXHJppJ3fad7LWbdAyGv22qxvtrme0pqg2yoVHWCCkH4gcjCxcsRLXiOufrQookx8MYFIG1S5aQy-2ZFhx1xAIP_AEKHAA

### Monaco Editor Playground Code

```typescript
function hello() {
	alert('Hello world!');
}
```

### Reproduction Steps

1. create GlyphMarginWidget instance and configure its `position.lane` to `monaco.editor.GlyphMarginLane.Right`
2. add the widget to an editor

### Actual (Problematic) Behavior

The effect is the same whether the lane is configured as left or right

### Expected Behavior

Displayed on the right of the line number when the lane is set to the right

**Comment by hediet** [comment]
The lane does not refer to line numbers.

[See here for the difference.](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#XQAAAAJMBgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw_OxARgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAgXlY_7qrl-bneKcRl678u_4fOATAds3iVeKMU8SiDL1HEKQGJa8vD551712ToUmAQ4azNL-soFijQdHjDJ-tXK_iBmCqMqpG6C1N3LVbR3PT1-db3Lc7MgkI9PkKZdBt2IbTKwATn9NQyVbaxfmrRGso9UL8LcjRhd-eDTiWpZKXCyhFveFnzm-i3uDfWVnbuvo45GFxQpBUiDCVXgo8qcQeY_vN5ECgcNbBYks2Qv176PPN3uyeYG54JIU_LgnEXdWGAAt0f1pPe-1-HSzpNceYDRqDkDBu8bWL8laaSXFVnaQsUQ45L_pBlHkIWQUoSsiwhHq3NP3PCP-_TF2x0NUz9ZDe5GuBe-HluZj0-m0-Es7boJM3iFvT165ZTkuwvHjV-4C7o1ElVWBxHhja8KwKcJO5IonUQ5MW8u15I3yd3XBojLJaeviHDzY7IB0FWVBeW3DGf1BPbKGBYQHH9K_zZDNztoZ0u3THEBayI1ma7V0JhympS8AaPrvl0K41sB2umklG-Yo7MUFcEFzmw-eM0Wm1xb2bkorbI0Ald5hHwziNrCNM6qVRCYgQBoQz3k0TUNa3P9P58uGxoJ_JzgQ3D_7X2CrA)
