### ISSUE TITLE
[Feature Request] Can you guys enhance the Documentation?

### ISSUE THREAD

**Issue by ymrdf** [microsoft/monaco-editor#4149]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

I think the current [documentation ](https://microsoft.github.io/monaco-editor/docs.html#modules/languages.html) are not good enough. First, it's very deficult to find whether monaco-editor have a function or not? For example, when I want to know how to remove the "No suggestion" tip of the completion. I have to read all APIs about completion. It's very painful.Second, there are so many conceptions that lack explain or have no explain. It's hard for beginner to use.Can you guys enhance the Documentation?

**Comment by hediet** [comment]
Unfortunately, we currently don't have the resources to maintain up-to-date docs for the monaco editor.
