### ISSUE TITLE
Scrolling from an empty diff line selects text

### ISSUE THREAD

**Issue by jayspadie** [Microsoft/monaco-editor#415]
monaco-editor version: 0.8.3
Browser: Any
OS: Windows 10

If you click and drag the Monaco scrollbar starting from an area over an empty line in a diff, it will select the text.  Shown below, you can see this text selection when starting from an empty line, followed by a normal scroll when not started over an empty line.  This is reproduced from the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-multi-line-example) example using Chrome.
![monacoscollingselectstext](https://cloud.githubusercontent.com/assets/5246869/24963557/eb7219e6-1f6c-11e7-8402-2b2c5c963555.gif)

**Comment by alexandrudima** [comment]
This has been fixed on master in the meantime and the fix will come out with the upcoming release.

![editor-415](https://user-images.githubusercontent.com/5047891/26979881-ab11a712-4d30-11e7-99ba-6934f22a3572.gif)
