### ISSUE TITLE
[Bug] TypeScript intellisense doesn't work

### ISSUE THREAD

**Issue by danieltroger** [microsoft/monaco-editor#4159]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0#XQAAAALYAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0FgUyEChknxTyhsOtw_oZuoS-bntDRvUjkOwcRtcHNwKoOpD9hqF1FLGw7nCYILel5cLzQMfYt3mxLaHSv8Y4NtKYwJeDNvJQDMZZBFfNwswgc3TfBQrZYMJx4rLxen4gtBkFX2rnFutOgwHAcV0M_szFptGlNEihDIJgGqXDQNuMXCML2PLTJZrbn7B84_y19Bu-ylW0zd9Imn3N_IcI3zyHauIFhtUIMamWJT0vZsXjzAK6jIIDu7LNHsWetuQeRqnUsZDQmuOSe4vXdBrjCZldhxr0rXji9wcYf413kpAHk9WQnZq3laLRniOM3d7iQ1DLZjSNx5h69Fy8-DsUqU8pCcBe7XcLMdIgfqX_hw

### Monaco Editor Playground Code

```ts
const value = /* set from `myEditor.getModel()`: */ `let a: number = "hi";`;


const uri = monaco.Uri.file("source.tsx"); // need to have a model that ends on .tsx or we don't get JSX/TSX support
    const model = monaco.editor.createModel(value, "typescript", uri);

  const myEditor = monaco.editor.create(container, {
          model,
          theme: "vs-dark",
		  automaticLayout: true,
        });

```

### Reproduction Steps

1. Go to playground link above, inspect variable a

### Actual (Problematic) Behavior

There's no type-error thrown even though a is a number and assigned to a string

### Expected Behavior

The typescript language service starts properly and provides intellisense

### Additional Context

I've had this issue ever since I figured out I need to first create a model and then an editor to get TSX/JSX support working and have not had any luck figuring out what's wrong with my code or Monaco in the last few hours

**Comment by paul-sachs** [comment]
I've noticed a similar issue with json highlighting and auto complete disabled in 0.41.0. My file however, did end with `.json` so workaround didn't seem to work 😢

**Comment by hediet** [comment]
This is fixed in the latest dev release.
