### ISSUE TITLE
Clicking the horizontal scrollbar in an empty diff line scrolls down and selects text

### ISSUE THREAD

**Issue by jayspadie** [Microsoft/monaco-editor#416]
monaco-editor version: 0.8.3
Browser: Any
OS: Windows 10

If you click the horizontal scrollbar in Monaco over an empty diff area, it will scroll down the page and select text for as long as you hold down the mouse button. Shown below using Chrome, you can see this vertical scrolling and text selection when clicking over an empty area.

![monacohorizontalscrollbug](https://cloud.githubusercontent.com/assets/5246869/24970263/b4000d28-1f81-11e7-90b8-2c622fd3457c.gif)

**Comment by alexandrudima** [comment]
This has been fixed in the meantime on master and the fix will come out with the upcoming release:

![ezgif-1-9dfb252ed6](https://user-images.githubusercontent.com/5047891/26979909-cdf8bfd6-4d30-11e7-8e46-dac822c7a50b.gif)
