### ISSUE TITLE
[Bug] Monaco editor in a parent with contain: strict renders suggest-details-container at incorrect position

### ISSUE THREAD

**Issue by samarthgulati** [microsoft/monaco-editor#4160]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[link of playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.43.0#XQAAAALXAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0FFnZ6DddtbtyhsOtw_oZuoS-bntDRvUjkOwcRtcHNwKoOpD9hqF1FLGw7nCYILel2Pa8v_zJ3fSGF5dVzmbj45xm9DS0quUH1uxuaQU24y-oAP3uzM4CmIAWXXDmELK8bCh6e_KB-znQbEcJI1Ki05sTRNtawYBD69LxQoQ2a0XBU9teAXQo9QNFvYtFf8FA4fBrbCQ7Crqn68UeJ3YcDaJOknkDuw-oeEaNI6Im2lNb_pnvf86ifL6ygDwnu_x64_yOCPs8-1q53-HMJqXslFyUSqGRzXhCo7q_1zu_zTfkiFIM-eJJA3KxOk116EOefQQ98XGVWkCyCxcysHS8y918Yt4Rk30ZmPX7o46pbQ__8zibsA) with the same issue.

![Image](https://github.com/microsoft/monaco-editor/assets/2931520/1ea7f146-685d-4f7c-a788-fded74c51700)

### Reproduction Steps

1. open code suggest (ctrl + space on Mac)
2. trigger suggest on `alert`
3. suggest details renders with an offset of `top` `left` value of the `contain: strict` element

### Actual (Problematic) Behavior

by default `suggest-details-container` is being rendered with `position: fixed` where as `suggest-widget` is rendered with `position: absolute` in `monaco-overflowing-widgets-container` and the position of `suggest-details-container` is calculated using `suggest-widget` 's position as an anchor and assuming page coordinates are top left 0,0. Whereas if any ancestor of the element has `contain: strict` it resets the origin, making the position calculation incorrect.

I could find that there is a way to set a custom parent element for `suggest-widget` where it can be rendered as fixed position, but couldn't find for `suggest-details-container`

### Expected Behavior

`suggest-details-container` should render with one of its edge touching `suggest-widget`

`_placeAtAnchor` function should either accommodate for scenarios where the origin of the parent is reset, or allow consumers to render `suggest-details-container` in a custom container element

### Additional Context

In the previous versions `suggest-details-container` was rendered in the same parent as `suggest-widget`. Thereby allowing the consumer to render them in a custom element which isn't affected by `contain: strict`. 

monaco-editor version: 0.39.0
Browser: Chrome
OS: MacOS

**Comment by simonebeets** [comment]
We have also encountered this issue and would appreciate it being looked into. We had to modify `placeAnchor` and `_placeAnchor` to consider offsets (and any other values/settings of spacing influencing the location/placement of the popovers) of parent elements to correct the value of the left setting for the suggest widget, which is not ideal.

**Comment by hediet** [comment]
Please provide a link to the monaco editor playground.

**Comment by samarthgulati** [comment]
Hello @hediet I have pasted the jsfiddle link in the first comment. Pasting here again for your convenience:
https://jsfiddle.net/5kmzbgq9/


Here's a screenshot of how it appears:
<img width="582" alt="Screenshot 2023-10-05 at 7 15 02 PM" src="https://github.com/microsoft/monaco-editor/assets/8597017/b6e0a472-f769-4c41-8a02-9d098752a5b7">


As you can see the offset at which the editor is rendered is transferred on to the suggest-detail widget.

**Comment by hediet** [comment]
We can only investigate issues if they are reproducible in the monaco editor playground.

**Comment by samarthgulati** [comment]
Okay, here's a [link of playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.43.0#XQAAAALXAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0FFnZ6DddtbtyhsOtw_oZuoS-bntDRvUjkOwcRtcHNwKoOpD9hqF1FLGw7nCYILel2Pa8v_zJ3fSGF5dVzmbj45xm9DS0quUH1uxuaQU24y-oAP3uzM4CmIAWXXDmELK8bCh6e_KB-znQbEcJI1Ki05sTRNtawYBD69LxQoQ2a0XBU9teAXQo9QNFvYtFf8FA4fBrbCQ7Crqn68UeJ3YcDaJOknkDuw-oeEaNI6Im2lNb_pnvf86ifL6ygDwnu_x64_yOCPs8-1q53-HMJqXslFyUSqGRzXhCo7q_1zu_zTfkiFIM-eJJA3KxOk116EOefQQ98XGVWkCyCxcysHS8y918Yt4Rk30ZmPX7o46pbQ__8zibsA) with the same issue.

**Comment by samarthgulati** [comment]
While the above link reproduces the issue, I discovered the issue persists for `transform` without `contain: strict`. So I have created another playground which specifically highlights the issue when the editor is positioned `absolute` with a `contain: strict` [link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.43.0#XQAAAAJYAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw1u40RgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAfWyxxqJxKmhw1cKTUXC0tx2LpbUNTPnITgLAYRgt88RZFdUEDQ61m0T_mAsEXf-sk6A7oo1oLPt4RC1VLK8cHFoLsBhGfV-AGKBv2OE9v1BJnRDX6cL2ZARp3BtXRs0kgUnkT_6-5jDFyAf0IhCaPM_MewUau04n5Mbc7KVCmu5iLCncB9p0Y5n76UiTSqmYwdcHefpdhMO0_goJq6mqMlLar_VayqBr8AbWpyIB-LXHz6pAV8VstPvcv9RAvUHOAFlvqip0Z7bO5TMmu12KVVTKIJV_2DXEpVgpJ2lMKDfqNKrPMufT9XnDn41tpDtORQcevSevj6__s4moQ)

**Comment by samarthgulati** [comment]
@hediet as the rendering offset is reproducible in monaco-playground can we reopen the issue?
