### ISSUE TITLE
[Bug] Range decoration with background-color hides all text

### ISSUE THREAD

**Issue by RobertBleyl** [microsoft/monaco-editor#4176]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.0-dev.20230301#XQAAAAJPAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0f5AiAEiAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8ulrCVzjWBVWZVl-YrARXWjHX0-tquUNesdygYRbQM1JUnAt3YmW0VSCWkY6ZkmLprhqNukEK_gFKBPwMtDrHypTK9MJxCpcT5NeztAM2FWUNPvskdfuQ0f51oo3cFTqHKAXgyhUK3zNO3cUIIl9SwAHijYFg9S0wxOoWEXGJDsJo2VubTorndRXmsPtjD5UDW0oGiZlza0AgEZiLRy0N6b-W_nKkIH8M2jk5Mhcq29TWIzxum1auhSfUI1MKe4uhOcLVXwHiVio13hcDOaqp5fkaZJ2sfARnmJiRTliYvbfDjFMXsXIfM3o3jaft9abF_ythgFseBgyontWW1sTCNvO1hZrIPgQkKZ21ab20BO9HLMYZV6py7dCD7b3ph3wbGiqXtUf8jnp-zKz-_7zpedM

### Monaco Editor Playground Code

```typescript
const value = /* set from `myEditor.getModel()`: */ `function hello() {
	alert('Hello world!');
}`;

const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
});

const decoration = {
      range: myEditor.getVisibleRanges()[0],
      options: {
        blockClassName: 'editor-highlight'
      }
}

myEditor.createDecorationsCollection([decoration]);



----------------------------
CSS:
.editor-highlight {
    background-color: lightgray;
}
```

### Reproduction Steps

Since version 0.37.x when creating a decoration collection that styles the background of the editor using "background-color" the text is not visible anymore. It used to work up until version 0.36.1.

### Actual (Problematic) Behavior

![actual_behavior](https://github.com/microsoft/monaco-editor/assets/69863893/aebe269c-a3d0-48ca-8c2b-cc10e04316c2)

### Expected Behavior

![expected_behavior](https://github.com/microsoft/monaco-editor/assets/69863893/3c7f2e11-cc65-42fb-a258-7d850049267c)

**Comment by hediet** [comment]
This commit changed this behavior: https://github.com/microsoft/vscode/commit/c4b5ade9eb1569a698f60e7e311a6b24d56b81c7

I think this is by design.
You should use a transparent background or not use block decorations.

**Comment by RobertBleyl** [comment]
Using a transparent background like this solved our issue:
```
.editor-highlight {
    background: rgba(0, 0, 0, 0.1);
}
```
