### ISSUE TITLE
in 2023，will tsx syntax highlighting 

### ISSUE THREAD

**Issue by Mari-yun** [microsoft/monaco-editor#4177]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

in 2023 year
want implement tsx syntax highlighting，except web worker 
Is there a better way?

Didn't find any help from lssus
I had to come here to get some help. thank

**Comment by danieltroger** [comment]
In the meantime you can copy how https://github.com/solidjs/solid-playground did TSX syntax highlighting. I did and it works but is very fragile, right now it stops working for me if I create another monaco instance (to have two at the same time)

**Comment by hediet** [comment]
/duplicate https://github.com/microsoft/monaco-editor/issues?q=is%3Aissue+is%3Aopen+tsx
