### ISSUE TITLE
Intelligenc and Code error marker not working

### ISSUE THREAD

**Issue by PJ254** [microsoft/monaco-editor#418]
not display intelligence or error mark when try to add two different editors on a single page with a unique language. when pressing the Ctrl + Space it display the suggestion box but does not show any data in that box. is there any configuration settings are required for fix this issue?

**Comment by AndersMad** [comment]
works fine here with many same or/and different editors on same page

**Comment by alexandrudima** [comment]
There might be something specific with your environment, could you reproduce this in a standalone HTML page?
