### ISSUE TITLE
After enabling the text spacing text in ‘Preview’ is getting truncated.

### ISSUE THREAD

**Issue by msftedad** [microsoft/monaco-editor#4186]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[Monaco Editor (microsoft.github.io)](https://microsoft.github.io/monaco-editor/playground.html?source=v0.42.0-dev-20230901#XQAAAAJiAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw1yeqRgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKi2Ej5cnSVboBg9CyozatOzDH3E9tWPTZl_NBNEBvi0EHoUzILAf1hALFydK2aeQUqERz5WxlOM79ePP0z_yCANpSkEw04zalxBSQbh-1_S1xj2LMDTy-gO5QA7HukP82J5yZZlhrb1rjcJMe1UuAX8vk8ijuR-nQfRJBlFprFc4W92jtJP-VIgFMOhJMlzNNfDzQo2b1GFfX9JxTj9AWbttIJzS0cGw-5lkj__o9Meo)

### Monaco Editor Playground Code

```typescript
const value = /* set from `myEditor.getModel()`: */ `test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test `;

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
	readOnly: true,
	wordWrap: "on",
});


HTML
<div id="container" style="height: 100%"></div>
```

### Reproduction Steps

1. Open the Above URL.
2. Monaco Editor page will appear navigate inside 'Preview' Section.
3. Enable text spacing using stylus app and observe the issue.

Attachments:
![After enabling the text spacing text in ‘Preview’ is getting truncated](https://github.com/microsoft/monaco-editor/assets/93735775/300d9eaa-e369-4a5e-8d3a-7e40c5e1f1de)

### Actual (Problematic) Behavior

'Text view' source code text is getting truncated, when enabling the text spacing.
Here there is no alternative way to read all the content.

### Expected Behavior

On activating text spacing, source code text present in the 'Text view' tab should be clearly visible without any truncation or without any overlapping.

**Comment by hediet** [comment]
> Enable text spacing using stylus app and observe the issue.

This is unsupported.

**Comment by msftedad** [comment]
Hi @hediet, Text spacing is applied by the low vision users. If text spacing is applied the low vision users can able to see the text clearly.
To apply text spacing use stylus tool.
**Steps to use stylus tool:**

1. Go to - [https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fstylus%2Fclngdbkpkpeebahjckkjfobafhncgmne%3Fhl%3Den&data=05%7C01%7Cmandaasha_latha%40hcl.com%7C07c402197cad43c5eb0908db708fcaad%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C638227535114984394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jbYJq8Fa7rqeMk7weeKcLlU7nrxDtM2l%2B%2BXNN7UabYs%3D&reserved=0).
2. Click on ‘Add to Chrome’ button.
3. After adding, you should find Stylus icon on the tool bar, click it to open drop down menu.
4. Select ‘Manage Styles’ from the menu.
5. On the manage styles screen, click on ‘Create new Style’.
6. The New style screen would open, here give a suitable name for your new style, e.g. ‘text spacing’.
7. Add following CSS under ‘Code’ field –
 * {
 line-height: 1.5 !important;
 letter-spacing: 0.12em !important;
word-spacing: 0.16em !important;
}
 p {
   margin-bottom: 2em !important;
 }
8. Click on ‘Save’.

If any further information needed feel free to ask. Thanks
