### ISSUE TITLE
[Feature Request] Export TypeScriptWorker and related utility functions

### ISSUE THREAD

**Issue by hmd-ai** [microsoft/monaco-editor#4188]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Please export `TypeScriptWorker` class and the utility function `fileNameIsLib` which is used inside `TypeScriptWorker`.
Exporting would make creating custom TS workers easier without having to manually define the type.

Furthermore, the utility function `fileNameIsLib` that is used inside many of the methods of `TypeScriptWorker` would be useful when overriding these methods.

**Comment by hediet** [comment]
I think this has been implemented with https://github.com/microsoft/monaco-editor/pull/3488.
