### ISSUE TITLE
How to disable (or externalize) command pallete?

### ISSUE THREAD

**Issue by FancyBanana** [microsoft/monaco-editor#419]
hi,
I'm writing an app that has it's own command pallete, and i wanted to use Monaco-editor in it instead of implementing my own inferior solution, but your editor already has it's own command-pallete. Is there any way to disable it or to extract it to use as global function for my project?

**Comment by alexandrudima** [comment]
You could disable it by "stealing" its keybindings via `addCommand`. The used keys are:

```js
		super(nls.localize('quickCommandActionInput', "Type the name of an action you want to execute"), {
			id: 'editor.action.quickCommand',
			label: nls.localize('QuickCommandAction.label', "Command Palette"),
			alias: 'Command Palette',
			precondition: null,
			kbOpts: {
				kbExpr: EditorContextKeys.focus,
				primary: (browser.isIE ? KeyMod.Alt | KeyCode.F1 : KeyCode.F1)
			},
			menuOpts: {
			}
		});

```
