### ISSUE TITLE
[Bug] hideUnchangedRegions feature not supported in Monaco editor

### ISSUE THREAD

**Issue by HitendraSinghRathore** [microsoft/monaco-editor#4196]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[Playground link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.43.0#XQAAAAKNDAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxN8ZDRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTwPyPDY1IBeJL_Xrbs1KKyeqLKZPBn0ReUGdf3GCX0E5fOjobC1gO-Gs_tWPtf8Kc2pyFEsuajrzISjO__HXK0zh1WHy05Ke7FkVtouSZxeCTxyFvUHefvs3mpLifnyfnk6CRHqeeI6IeV4eEKZYFmCOuCIdU8HMNnrqgRp_qKa3ZXMWA-KsVsQ4qfGKl110NcSnumZteetmavGeLroTfjOrTRfzT2UqEq3A_W9RIOLvllWCYqiHy9KA0Tlu1LEr1f5NMBrH7OnhEKlCIRGRIaVVF-kd-x0YTxjir1s0g_y8dPbtkVea0aZ5beVgodYeATvKuknPafnO0iKq43aApM0pqC51z_vqbGgwf-1yNpntqJ6qXXNlTHytqXhaixzjMYft9acJJcUjqcqp2z9uQgzDOjDJokQastD9TjjcNQS8OHR68PqE-kiSDjVhMJpRgosVUHvSbP_-VKLDLzPvG1KW4fRShNCvfggYv7VUhyDN_aDQMqhH4k8ADPJrBp48iT_xK_S498unqGbE_vKqtfsXAoB9lI2xZCJBjmoQPyM9DgyOPTv6djeySo6mGaaj7bnLqsXYZY52ih8umPbu8PBMKgtMuydkRnuuLl5msUmWCVGPghmGLSSTm0QwjryyoR5L2FYs0XZc42_ntbCzpfnuGUX8GCHIh8U-JAiRZBjjGHqO3CjFu4fWfs13lyFfhcYQk18x0cm7TPCpB0j72pgZwdOVfqmsHcrmhWGI2MUJBcFyccalt5R8RLn7JkMGuyn-h5MPwGUaAVOU8mgbqaDOcg3fKt4dUIghWrm-oUpVdaK-RYIu1UmgV8L1GpwCUMS1sinFl7XV2BF7E1_L69pkTsItJWBD-EakYdmEZ4Qp01XozkOmaAAO6Apt91CfSjxrXO_yHcj3Nv7HxK2YkxMq3-vlomh5Zm4IbhfEsV9sSKcj1MC_Mo4cIFzt_bvk6sNoRD4V32PJBGEdVgRpDqdALVrPc_MKzOlHZocpW7Hh7dsp2Ou6kfSGComSIv3GJXKK3ucuzK9WWfUN-RK83eS0RVVtqTCqnfpqgn1ZASB6m5oSl1WmscmbUEHpIUL2aXcgyb1LnWRKmiM89UTBU-9sgRLGO3EZ_7LAFDAdB_f6EE--Q_bB7epIQswK4D8ZKBNzb8HUGz0u6Mfpcf_ixn_w)

### Monaco Editor Playground Code

```typescript
const originalModel = monaco.editor.createModel(
	/* set from `originalModel`: */ `[
  {
    "_id": "651d1c1e7375a78f810eb946",
    "index": 0,
    "guid": "23d98f76-46b2-499b-b4e0-1b4dbb94461e",
    "isActive": true,
    "balance": "$2,805.46",
    "picture": "http://placehold.it/32x32",
    "age": 29,
    "eyeColor": "green",
    "address": "717 Borinquen Pl, Deputy, Arkansas, 7694",
    "about": "Aliquip eu consectetur consequat sint sit amet labore culpa ea consectetur non. Ea tempor minim Lorem ad sint non anim amet reprehenderit. Est enim officia quis aliqua sunt eiusmod. Veniam enim est esse eiusmod aute excepteur et ex labore enim id deserunt. Id nulla cupidatat dolor anim aute id. Aute sint exercitation et ipsum consectetur incididunt quis aute magna ad do.\r\n",
    "registered": "2020-02-13T12:45:41 -06:-30",
    "latitude": -81.908386,
    "longitude": 29.700776,
    "tags": [
      "cupidatat",
      "laborum",
      "ex",
      "tempor",
      "non",
      "aliquip",
      "labore"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Charlene Kelley",
        "gender": 0
      },
      {
        "id": 1,
        "name": "Frieda Yang",
        "gender": 1
      },
      {
        "id": 2,
        "name": "Marietta Olson",
        "gender": 2
      }
    ],
    "greeting": "Hello, undefined! You have 5 unread messages.",
    "favoriteFruit": "banana"
  }
]`,
	"json"
);
const modifiedModel = monaco.editor.createModel(
	/* set from `modifiedModel`: */ `[
  {
    "_id": "651d1c1e7375a78f810eb946",
    "index": 0,
    "guid": "23d98f76-46b2-499b-b4e0-1b4dbb94461e",
    "isActive": true,
    "balance": "$2,805.46",
    "picture": "http://placehold.it/32x32",
    "age": 29,
    "eyeColor": "green",
    "address": "717 Borinquen Pl, Deputy, Arkansas, 7694",
    "about": "labore culpa ea consectetur non. Ea tempor minim Lorem ad sint non anim amet reprehenderit. Est enim officia quis aliqua sunt eiusmod. Veniam enim est esse eiusmod aute excepteur et ex labore enim id deserunt. Id nulla cupidatat dolor anim aute id. Aute sint exercitation et ipsum consectetur incididunt quis aute magna ad do.\r\n",
    "registered": "2020-02-13T12:45:41 -06:-30",
    "latitude": -81.908386,
    "longitude": 29.700776,
    "tags": [
      "cupidatat",
      "laborum",
      "ex",
      "tempor",
      "non",
      "aliquip",
      "labore"
    ],
    "friends": [
      {
        "id": 0,
        "name": "Charlene Kelley",
        "gender": 0
      },
      {
        "id": 1,
        "name": "Frieda Yang",
        "gender": 1
      },
      {
        "id": 2,
        "name": "Marietta Olson",
        "gender": 2
      }
    ],
    "greeting": "Hello, undefined! You have 5 unread messages.",
    "favoriteFruit": "banana"
  }
]`,
	"json"
);

const diffEditor = monaco.editor.createDiffEditor(
	document.getElementById("container"),
	{
		originalEditable: false,
		folding: true,
        hideUnchangedRegions: {
			enabled: true,
			revealLineCount: 40,
			minimumLineCount: 1,
			contextLineCount: 1

		}
}
	
);
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel,
});
```

### Reproduction Steps

add hideUnchangedRegions flag in the diff editor constructor

### Actual (Problematic) Behavior

The code does not hide the unchanged regions

### Expected Behavior

the editor should hide the unchanged parts as it does in vs code

**Comment by HitendraSinghRathore** [comment]
Any help on the above will be appreciated

**Comment by hediet** [comment]
This works in the latest dev version.

**Comment by naivefun** [comment]
@hediet   still not working in [0.45.0-dev-20231025](https://www.npmjs.com/package/monaco-editor/v/0.45.0-dev-20231025)

**Comment by hediet** [comment]
It works here: https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAKNDAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxN8ZDRgmSatbNyrNa50VLHWwDOn0YI7IfU0xJ0CGYU1vRtgnKPmZzQcQ1F9I-F9YcvQUj8HivueDk6xk10aTwPyPDY1IBeJL_Xrbs1KKyeqLKZPBn0ReUGdf3GCX0E5fOjobC1gO-Gs_tWPtf8Kc2pyFEsuajrzISjO__HXK0zh1WHy05Ke7FkVtouSZxeCTxyFvUHefvs3mpLifnyfnk6CRHqeeI6IeV4eEKZYFmCOuCIdU8HMNnrqgRp_qKa3ZXMWA-KsVsQ4qfGKl110NcSnumZteetmavGeLroTfjOrTRfzT2UqEq3A_W9RIOLvllWCYqiHy9KA0Tlu1LEr1f5NMBrH7OnhEKlCIRGRIaVVF-kd-x0YTxjir1s0g_y8dPbtkVea0aZ5beVgodYeATvKuknPafnO0iKq43aApM0pqC51z_vqbGgwf-1yNpntqJ6qXXNlTHytqXhaixzjMYft9acJJcUjqcqp2z9uQgzDOjDJokQastD9TjjcNQS8OHR68PqE-kiSDjVhMJpRgosVUHvSbP_-VKLDLzPvG1KW4fRShNCvfggYv7VUhyDN_aDQMqhH4k8ADPJrBp48iT_xK_S498unqGbE_vKqtfsXAoB9lI2xZCJBjmoQPyM9DgyOPTv6djeySo6mGaaj7bnLqsXYZY52ih8umPbu8PBMKgtMuydkRnuuLl5msUmWCVGPghmGLSSTm0QwjryyoR5L2FYs0XZc42_ntbCzpfnuGUX8GCHIh8U-JAiRZBjjGHqO3CjFu4fWfs13lyFfhcYQk18x0cm7TPCpB0j72pgZwdOVfqmsHcrmhWGI2MUJBcFyccalt5R8RLn7JkMGuyn-h5MPwGUaAVOU8mgbqaDOcg3fKt4dUIghWrm-oUpVdaK-RYIu1UmgV8L1GpwCUMS1sinFl7XV2BF7E1_L69pkTsItJWBD-EakYdmEZ4Qp01XozkOmaAAO6Apt91CfSjxrXO_yHcj3Nv7HxK2YkxMq3-vlomh5Zm4IbhfEsV9sSKcj1MC_Mo4cIFzt_bvk6sNoRD4V32PJBGEdVgRpDqdALVrPc_MKzOlHZocpW7Hh7dsp2Ou6kfSGComSIv3GJXKK3ucuzK9WWfUN-RK83eS0RVVtqTCqnfpqgn1ZASB6m5oSl1WmscmbUEHpIUL2aXcgyb1LnWRKmiM89UTBU-9sgRLGO3EZ_7LAFDAdB_f6EE--Q_bB7epIQswK4D8ZKBNzb8HUGz0u6Mfpcf_ixn_w
