### ISSUE TITLE
Server Side Rendering (Prerender of Monaco Editor)

### ISSUE THREAD

**Issue by rohmanhm** [microsoft/monaco-editor#420]
Does it support for SSR?

**Comment by alexandrudima** [comment]
What do you mean by SSR? (sorry it's an acronym I haven't heard of so far)

**Comment by tarr11** [comment]
I believe this means server side rendering.

**Comment by alexandrudima** [comment]
I'm not 100% sure what the OP means, but I suspect it means something like coloring a text file using a language on the server side and sending down to the browser a colorized file.

**Comment by rebornix** [comment]
@rohmanhm right now we don't support SSR, to make that happen we need 

* Handle gracefully with browser api (DOM) on server (similar to Angular's server module or so)
* Monaco can recover from some random state (load model/viewmodel/services from the SSR result)

It would be a good addition to having languages services running elsewhere and have Monaco editor prerendered.

At this moment, we only support server side colorization, `monaco.editor.colorize()` doesn't require Browser environment so you can get HTML for viewlines of the editor. However, `monaco.editor.colorizeModelLine()` requires a model for a specific language, which makes call to Browser API and makes it not useful from server side.

**Comment by lcswillems** [comment]
Do you have an example of how we could do server side colorization with Monaco Editor?

I tried the following in NodeJS:

```
monaco.editor.colorize(
    "function hello() {\n\talert('Hello world!');\n}",
    "javascript",
    {}
)
.then(html => console.log(html));
```

But I get this error:

```

  | 4:  *--------------------------------------------------------------------------------------------*/
-- | --
  | 5:
  | 6: .monaco-editor .accessibilityHelpWidget {
  | ^
  | 7:   padding: 10px;
  | 8:   vertical-align: middle;

```

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
