### ISSUE TITLE
[Bug] JSON Schema: markdownDescription rendered by hover but not in the suggestion details

### ISSUE THREAD

**Issue by kokovtsev** [microsoft/monaco-editor#4209]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAKQAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4b6edHDvqPO_68xRV--3NT2MM2834uyP1NFQSuE5MZ_Nq3KbJ8knXgkBtVcJlXvFpqi52nEJOlHHOW4TnpixJdt1LWadSDDzk_yi19xmFJNMskikeS2E_YG9wvp5Jt4Lpt9c9ATGWrgOSRS2rgR9K_qvQYsnk-OsXhTdW-pFYg0t-byPbeao-mnu48nwbQmq1mh5PlY4U_a9xMUkEC649ZOQIqyzc9mEBiJH7vsT8lWL453MoHyfvKzmkrsP27yaMdeHWFco2JBjA9oD74oKe4P6gvgcKQF9q5LDR-vfDmA1dOIhj-bUXpGCBZ_8-DMfW92oLbZdKYMKu2Hi6Yux8bcmpkOWgrj91T8oKHh4-DnGfYIL0ZjKQL9FD1WFCEAPq4YXsOXuJiyhRqjocuf2g93DHCKtbmFJsUOVnYTi8m-tUgWVOtUxJRL4zvoQEvy8cx0EhlLrO9O0YQbMAJKe8dvojeAgyT9lucMzDVPdNd45npt6Mc_NgHa0iRCWrKZ1j5UMVN3dX3mp7C-7uYnOhEVmZm95lFAnCMGOdQb121UrOaSvbxLJ9zSsFGZL8BXRHl5pu9aLkVOwg5IF4hZrN2qCiT79mdde

### Monaco Editor Playground Code

```typescript
monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [
		{
			uri: "http://myserver/foo-schema.json", // id of the first schema
			"fileMatch": [
				"*"
			],
			"schema": {
				"type": "object",
				"properties": {
					"hello": {
						"markdownDescription": "This is **markdown**",
						"type": "string"
					}
				}
			}
		}
	],
});
```

### Reproduction Steps

Case 1: hover the `hello` property in the editor
Case 2: put the cursor inside the `hello` key, press Ctrl-Space to trigger the suggestion box and Ctrl-Space once again to show the details

### Actual (Problematic) Behavior

Case 1: the markdown documentation is displayed correctly
Case 2: suggestion details do not appear at all

### Expected Behavior

In both cases, the same properly formatted description should be shown

### Additional Context

Please note that if I provide both `description` and `markdownDescription`, the former is displayed in suggestion details and the latter - on hover

Thanks for your great work!

**Comment by codercoin98** [comment]
Has this problem been solved? I want to know how to display the description in the schema completion.

**Comment by kokovtsev** [comment]
Apparently it's not...

@hediet sorry for reaching out to you directly but it seems that you've been active in this repo, and I am not the only one interested in this fix. Could you please help us getting the linked PR reviewed and solved?

**Comment by TylerLeonhardt** [comment]
@hediet can you give us some steps on how to verify?

**Comment by TylerLeonhardt** [comment]
I think I figured it out. Looks verified:
![image](https://github.com/microsoft/monaco-editor/assets/2644648/37739d8b-8f8e-4db2-a721-2a8ca5f3bf22)
