### ISSUE TITLE
How can i custom worker for python intellisense?

### ISSUE THREAD

**Issue by jacobyf** [microsoft/monaco-editor#421]
Hello, i have integrated monaco-editor into our projects. it's a wondeful tools, repectively. But my projects member mainly want to support python code. how can i custom a worker for this task?

**Comment by svenefftinge** [comment]
You can use this : 
- https://github.com/palantir/python-language-server
Together with : 
- https://github.com/TypeFox/monaco-languageclient
- https://github.com/TypeFox/vscode-ws-jsonrpc
- https://github.com/TypeFox/vscode-languageserver-node

**Comment by pkpp1233** [comment]
@jacobyf or @alexandrudima  did you end up setting this up? We're about to start building this out ourselves.

**Comment by akosyakov** [comment]
@pkpp1233 Look at the example in [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient). It shows how to connect the Monaco editor with the JSON language server, you can do the same for python. Also [this blog post](http://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor) exlpains it.

**Comment by Jandou6** [comment]
I had try to use Python-language-server.And pyls  may use TCP connect.

So, if I use the code like JSON-server ,it can not  work..

Area there anybody workout?

**Comment by akosyakov** [comment]
@Jandou6 The example in monaco-languageclient shows how to connect the external JSON server process:
https://github.com/TypeFox/monaco-languageclient/blob/b901301fe10c7a51e3b6faa35863bb69c93fcd11/example/src/json-server-launcher.ts#L17-L28

You should be able to spawn pyls process and connect to it in the same way.

**Comment by sriramks85** [comment]
I am trying to do the same as @Jandou6 and as suggested by you, but I am getting this error:
Launching PYTHON Server failed: Error: spawn pyls --tcp --host 0.0.0.0 --port 5000 ENOENT

**Comment by aatish** [comment]
Hi
I am able to run all these language server(through monaco language client + monaco editor):
https://github.com/palantir/python-language-server
https://github.com/sourcegraph/javascript-typescript-langserver
https://github.com/felixfbecker/php-language-server
https://github.com/sourcegraph/go-langserver

but somehow not able to run this:
https://reviews.llvm.org/diffusion/L/browse/clang-tools-extra/trunk/clangd/

do I need to do something different?
