### ISSUE TITLE
[Bug] Disposing the Editor does not dispose the global key event listener

### ISSUE THREAD

**Issue by demoversionOo** [microsoft/monaco-editor#4213]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

1. Open an editor
2. Open the Suggestions (Ctrl + Space)
3. Dispose of the editor

Result: The 'keydown' eventlistener in dom.ts still triggers every input in my web application and even fires exceptions on chrome auto fill events.

### Actual (Problematic) Behavior

The eventlisterner, although written as a disposable, is not correctly disposed of on disposing the complete editor.

Stacktrace of the exception after filling an input with chrome autocomplete (omitted Angular junk): 
TypeError: e.getModifierState is not a function
    at new StandardKeyboardEvent (keyboardEvent.ts:111:24)
    at dom.ts:1165:18

### Expected Behavior

1. The eventlistener should stop listening to events after the editor is disposed.
2. Also the constructor of StandardKeyboardEvent should not throw exceptions on auto fill events.

### Additional Context

We embedded monaco in an angular app, handling multiple instances in a [stepper]https://material.angular.io/components/stepper/overview). Some of the steps contain simple input elements which cause the issues.

**Comment by Adaer** [comment]
After entering content in the Monaco editor, clicking on another input box triggers an error in the console
`
Uncaught TypeError: e.getModifierState is not a function 
at new StandardKeyboardEvent (keyboardEvent.js:66:30)  this.altGraphKey = e.getModifierState('AltGraph');
`

**Comment by sdt-jpollard** [comment]
Seeing the same issue. Upgraded to the latest version and it still occurs. Any updates?

`Uncaught TypeError: e.getModifierState is not a function  at new StandardKeyboardEvent (keyboardEvent.js:66:30)  this.altGraphKey = e.getModifierState('AltGraph');`

**Comment by ben519** [comment]
I'm battling the same error

```
Unhandled Runtime Error
TypeError: e.getModifierState is not a function

Call Stack

new StandardKeyboardEvent
node_modules/monaco-editor/esm/vs/base/browser/keyboardEvent.js (66:0)

HTMLBodyElement.eval
node_modules/monaco-editor/esm/vs/base/browser/dom.js (118:0)
```

Anybody have a workaround for this?

**Comment by hediet** [comment]
Please provide a monaco editor playground example so that we can reproduce this issue.

**Comment by demoversionOo** [comment]
As i wrote before: The error is **_NOT_** reproducable in the playground - as there is no real way to dispose the editor. Also the error triggers explicitly on Auto-Fill Events (which the editor _should_ ignore) as those miss some of the properties of a Keyboard Event.

**Comment by mjswan** [comment]
FWIW, I have also encountered this issue.

**Comment by IQZoe** [comment]
In which version is this problem solved？

**Comment by demoversionOo** [comment]
I dont think it was. The issue was just closed. :(
