### ISSUE TITLE
locale:ko but This setting does not work

### ISSUE THREAD

**Issue by Yuppiezero** [microsoft/monaco-editor#4214]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

"monaco-editor": "^0.44.0",
"monaco-editor-nls": "^3.1.0",
"monaco-editor-webpack-plugin": "^7.1.0",
"monaco-languages": "^2.11.1",

After multiple attempts, it was found that the right mouse button on XX cannot be modified to switch to a different country language，
But I found the file monaco-editor \ dev \ vs \ editor \ editor.main.nls.ko.js in node_modules，It should have already been integrated，I don't know how to set it up，Set the copy and cut text on the right-click display panel to Korean

```
import { setLocaleData } from 'monaco-editor-nls';
import ko from 'monaco-editor-nls/locale/ko';
setLocaleData(ko);
import * as monaco from "monaco-editor"
import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker'
import JsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker'
```
#### **This setting does not work**
```
monaco.editor.create(container, {
  value: "",
  language: "javascript",
  locale: "ko",
});
```

**Comment by hediet** [comment]
Please provide a monaco editor playground example so that we investigate this issue. Thanks!
