### ISSUE TITLE
[Bug] import statements break split panes

### ISSUE THREAD

**Issue by bautistaaa** [microsoft/monaco-editor#4219]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

not a playground link but the deployed app

https://monaco-split.vercel.app/

### Monaco Editor Playground Code

```typescript
n/a
```

### Reproduction Steps

clone: https://github.com/Hacksore/monaco-ata/tree/sandbox

`pnpm i`
`pnpm dev`

add import statement to the top pane and see that the type can no longer be inferred in the second pane

<img width="380" alt="CleanShot 2023-10-18 at 15 14 43@2x" src="https://github.com/microsoft/monaco-editor/assets/3660667/1652582a-6371-4bd1-b015-7f19ba04b179">

### Actual (Problematic) Behavior

import statements shouldn't break type inference across instances

### Expected Behavior

type inference should remain intact

### Additional Context

Unsure if we potentially just doing something wrong. We aren't leveraging `ata` so I'd think import statements shouldn't really impact anything but would love some advice on how we can avoid this.

**Comment by bautistaaa** [comment]
actually after consulting with some folks it’s expected behavior

**Comment by hediet** [comment]
Please provide a monaco editor playground example so we can debug this issue. Thanks for understanding!

**Comment by Hacksore** [comment]
@bautistaaa it seems working now 🥴😵‍💫🫥

![2023-12-13_15-04-15](https://github.com/microsoft/monaco-editor/assets/996134/a9bb397f-8318-4638-a3a2-6b14b9b70d43)

**Comment by maxdemaio** [comment]
> @bautistaaa it seems working now 🥴😵‍💫🫥
> 
> ![2023-12-13_15-04-15](https://private-user-images.githubusercontent.com/996134/290328497-a9bb397f-8318-4638-a3a2-6b14b9b70d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDE4ODMsIm5iZiI6MTcwMjUwMTU4MywicGF0aCI6Ii85OTYxMzQvMjkwMzI4NDk3LWE5YmIzOTdmLTgzMTgtNDYzOC1hM2EyLTZiMTRiOWI3MGQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMTA2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjYyZDA5MzJjZDhmZDAzZDVmNThiMWJhNDhiZjNlNmQ4ODRlMDc3YzU4NWQyYzkzY2Q4OTBhYzA1NmU5NGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.du4UbTfGTSfPJdfgF-hHxR2lUKrnVQlvd0jHw5pK-9g)

Blocker: unclear verbiage

> **it seems working now**

**Comment by bautistaaa** [comment]
> @bautistaaa it seems working now 🥴😵‍💫🫥
> 
> ![2023-12-13_15-04-15](https://private-user-images.githubusercontent.com/996134/290328497-a9bb397f-8318-4638-a3a2-6b14b9b70d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDE4OTMsIm5iZiI6MTcwMjUwMTU5MywicGF0aCI6Ii85OTYxMzQvMjkwMzI4NDk3LWE5YmIzOTdmLTgzMTgtNDYzOC1hM2EyLTZiMTRiOWI3MGQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QyMTA2MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODJlMGI4N2M2NWMzNDA1ODVjMzI1ZWU0ZmNiOTAxOWJlYWYxOTAzMTgxYTkxOThjM2EzYWU5ODdjOWRiMTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x4gyVT-6DFCkp7ZBE5AmSteO9RxY7qpFSsxleFNV2Y0)

yeah i closed this a while ago, found a workaround but it’s flakey
