### ISSUE TITLE
Hardcoded styles in Scrollbar

### ISSUE THREAD

**Issue by den1k** [Microsoft/monaco-editor#422]
The canvas element with class `.decorationsOverviewRuler` has a hardcoded top and left border as can be seen here:

![image](https://cloud.githubusercontent.com/assets/4651810/25154361/5753c402-245e-11e7-929a-c113bba24270.png)

Because this is canvas, these can only be changed by finding the canvas element and over-drawing the scroll-bar. I'm not sure what the reasoning is behind putting borders into canvas instead of css, but it would be nice to make them borders optional or customizable.

**Comment by alexandrudima** [comment]
I think there is an option for this on master...

**Comment by den1k** [comment]
@alexandrudima you're right, pass this to options to remove it:

```
hideCursorInOverviewRuler: true
```

closing.
