### ISSUE TITLE
Can we open multiple files to view the code?

### ISSUE THREAD

**Issue by gituserjava** [microsoft/monaco-editor#4220]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Additional Context

I want to use this editor as an online editor where I can open multiple graph ql files online and edit and save. Is that possible?

I also need to do some customization of the code to invoke some custom plugins. Is that possible?

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
