### ISSUE TITLE
[Feature Request] Official guide for writing Textmate grammar with embedded language

### ISSUE THREAD

**Issue by BeishaoCao-db** [microsoft/monaco-editor#4226]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Hello everyone, I am struggling to find a solution to wire in Textmate grammar with embedded language. I successfully introduced Textmate grammar with [vscode-textmate](https://github.com/microsoft/vscode-textmate). However, I cannot make it works as perfectly as the `monarch` nextEmbedded. 

To be more specific, I want to embed sql into python. Currently I manually add a section in [MagicPython](https://github.com/MagicStack/MagicPython/blob/master/grammars/MagicPython.tmLanguage) grammer file to include `"source.sql"` when specific situation is satisfied. 

e.g. 
`a = sql(' SQL COMMAND here ')`

Then the `tokenize` function can successfully return tokens with the corresponding SQL scope name for SQL COMMAND above, however, the language in the tokens are all python rather than sql, which means the `tokenization` stored in editor model also consider the language for them to be python rather than sql.

Since the langauge for the token is added in the editor package, so I post the issue here rather than in vscode-textmate. Is it possible this is something on the roadmap or in the meantime there is a solution to workaround this until official guides/utilities might be available? I appreciate any help and understand there are a lot of moving parts here to make this all work.

**Comment by hediet** [comment]
As of now, Textmate does not ship with the monaco editor.
