### ISSUE TITLE
Drag and Drop feature missing in Editor

### ISSUE THREAD

**Issue by wewake4** [Microsoft/monaco-editor#423]
monaco-editor version: 0.8.3
Browser: Chrome
OS: Win 7

Visual studio code has drag and drop feature. But Monaco editor lacks this feature. Whether it is planned ?
[Issue 1046](https://github.com/Microsoft/vscode/issues/1046)

It will be great to have this awesome feature implemented ASAP.

**Comment by alexandrudima** [comment]
This will come out with the next monaco editor release.

**Comment by ravinsinghd** [comment]
@alexandrudima  which commit added this feature, i just pull master but i cant use the drag feature

**Comment by alexandrudima** [comment]
@ravinsinghd Please see https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#a-brief-explanation-on-the-source-code-structure -- the editor source code is not in this repository.

**Comment by ravinsinghd** [comment]
@alexandrudima my bad. thanks for info

**Comment by ThorstenBux** [comment]
@alexandrudima was Drag and Drop already released? I cannot find it in the documentation anywhere.

Cheers

**Comment by viccsjain** [comment]
Any work is going on this feature ?
Do we have any update on this ?
