### ISSUE TITLE
[Bug] `setExtraLibs` not working in some cases related to spelling fix suggestions

### ISSUE THREAD

**Issue by suchipi** [microsoft/monaco-editor#4232]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Repro Repo Link

This issue is not reproducible in the monaco editor playground because it does not expose an interface for calling `setExtraLibs`. However, I have created a very minimal monaco application which reproduces the issue here: https://github.com/suchipi/monaco-extralib-bug-repro/tree/625f2943d6c9e4bfabe48d243c05c7733b74dee2

### Relevant Code Loaded into Monaco

```typescript
// extra lib file "v1.ts" contains:
interface api {
  version: "1"
  something(): boolean;
}
declare const api: api;

// extra lib file "v2.ts" contains:
interface api {
  version: "2",
  something(): boolean;
  somethingElse(): boolean;
}
declare const api: api;

// the default monaco editor in the app contains:
type VERSION = typeof api.version;
const blah = api.somethingElse();

// and the app sets the extra libs to "v1.ts" at app launch.
```

### Reproduction Steps

There is a [repro repo](https://github.com/suchipi/monaco-extralib-bug-repro/tree/625f2943d6c9e4bfabe48d243c05c7733b74dee2) with more detailed instructions, but the high-level steps are:

- Use `monaco.languages.typescript.typescriptDefaults.setExtraLibs` to load a type definition for a variable named "something".
- Attempt to reference the non-existent variable "somethingElse". A diagnostic error will be shown, with a spelling fix suggestion.
- Use `monaco.languages.typescript.typescriptDefaults.setExtraLibs` again, to replace the loaded type definitions with new ones which define both `something` and `somethingElse`.

### Actual (Problematic) Behavior

The diagnostic error does not go away, and the new extra libs are not used.

### Expected Behavior

The diagnostic error goes away, and the new extra libs are used elsewhere in the program.

### Additional Context

At work, I embed the monaco editor to allow users to author scripts. There are different versions of our API which they can develop against. We use `setExtraLibs` to change the loaded type definitions for our API depending on which API version the user's script targets (which they can change with a drop-down). We recently added a new API version which includes new functions, one of which whose name starts with the name of an older, existing function. Ever since that change, changing the selected API version has not been functioning properly due to the described problematic behavior.

**Comment by hediet** [comment]
I am very sure `setExtraLibs` is available in the monaco editor playground (please also check other issues).

I'll close for now, but feel free to reopen/create a new issue with an example for the playground.
Without the example we cannot debug this unfortunately.

**Comment by suchipi** [comment]
My mistake; here it is in the editor playground: https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#XQAAAAK7BQAAAAAAAABBqQkHQ5NjdzmeoQhbELdK4LJ3dVhQNmdymDlXD9sGVgT1xF3OY4smV0Qv_H8uUJC4shpDcmYB-4MKcwIrhJEGTbIOEGTE4SOD_zwYVEpAKtd-TB3N_LKKIXnCXY0gIfnuVI0sqTEHDB97Mc56k0-jnqJmsJVahlVh2UYdFswhmY2jY4hOq2bwbwN79ghDMHtbkcMC5XqpbqXoV8yOHBE8vtoYTAygJI87VLu693TID-Vea_MLAH7ZGypyzheM8U-44eYswUE8sJgz6FLPHegxx6y4cPKLrlASjujjMc3zhchFxJWaLw4A9AkjO7QnvSZtU5MaSDosGWubOr7NTHIMwujRZbSR5X_bG6KLvA13Y6t3yyO09pzOAmBjyXX2HthP1G-DFLbuvALqxjE5HEjMr8IwT-VMQucaYHanmdy3kFsDogtyeIc00jLriyWF6cD1fhm3x_MFXWiZlHeH7JG9p6GTtKrJxZIqV5uVBYsQHRbAf6DLNGP6vgis44dc9jjGgKEwwgUqK8NalxCheObC4ogJxVTiYFJTdMxgLPZoPQsRlWBtfTclyJf-d9Lp0QQ13fM-7lk2UfAVJ7TUpPkIN1lgA8lZflb2MVDIhf5YTgXTjEoG2DFtiCgnz6iKCftIkdC3k_9gEiZUsyNDZxMwiZput3PBUDuesbeJqzADCPXjm2haXlo-cAa-fiOKzYgnkYMpVA1PocdxYMElizcsxXYyRjFWSwB8i19uV3lzgOiwBH1NU-vZ5OMUDekMBQkHH2LSeQz9LrfJkrovLeKKf8EiKjfUQahG8TA2sYS8hZQIfLU7oUw4tt4daUj0sDdAnnQeO4pULuaLwmfdyXAY0WHMClHjkIQUsYqzs67ZKUDvM2Pbo_YwE5PhTfhn5F_VAOzynP8DSgwA

Could you reopen this issue, please?
