### ISSUE TITLE
[Bug] The context menu for the Monaco editor within WebView2 is non-functional after upgrading to Windows App SDK 1.4 

### ISSUE THREAD

**Issue by Jimex** [microsoft/monaco-editor#4233]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

To replicate the issue, kindly execute the code available at https://github.com/Jimex/TestWebView2MonacoEditor .

### Actual (Problematic) Behavior

Nothing happens after clicking the "TEST CLICK" menu item on the context menu

https://github.com/microsoft/microsoft-ui-xaml/assets/3145858/f30c307b-e49e-4eb0-a5fa-d1a61d7f8942

### Expected Behavior

An alert appears after clicking the "TEST CLICK" menu item on the context menu

https://github.com/microsoft/microsoft-ui-xaml/assets/3145858/e71dc3c8-81e1-45ba-a022-67cad425fde1

**Comment by hediet** [comment]
This seems to be a problem of web view 2 (which we don't support actively).

If you can track it down to some monaco editor issue, please create an issue with more specific bug information!
