### ISSUE TITLE
[Bug] - Regression (>= 0.42.0-dev) - CompletionItemProvider deactivates overridden services in monaco.editor.IEditorOverrideServices

### ISSUE THREAD

**Issue by FSDRE** [microsoft/monaco-editor#4245]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAKrAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw4ll8XcBhacwDslNw4_eBo2Jgiod2Mxx7ntOp1d26TW_0wSxXOolGCXSTq3Ttn3oG1MVn5TpfZGspcAGjZbwzisX-BnXtpfz1Axoy-IapzxwaSmBTDu-5GYpXDQzb5rSze181SC3Oca4C0M-O1Qd9VHGsFI5oofqlCo36Tul7ibJ2oG_Ux76C81V_USSICQAdKFhoBgQYGbmw2NKE6rg0MGBqDCyLnA18TJm7o2NRJT6e-o-YUrXpO9-hMlJ75n8_CjWRB-OkQATqsFYiGDzd1d_fusLq6uW0v7cExv8Wi-5B51eV05cRWFdWt53gx9RILPSPO7AcyS9cJRQQCLyOAIprosxEMkTfmCe9cQEWUqXXjYBdEgy101DwlzW9REXjILgnsS51bvyQJy1wF9ZAcGrl_59FKfH7NoehYTAd4IaS_1nxpDSLJip-brFqA3TCmwW9U6fVJ7jm5ykJ4iW_AWJhXdgVxFYF4UHOXLSReoQ58oYiEgXicJyc9gUiBA5MeMQyXJ9F6z2L7cPPZQjcZFwk2XLc_DtsO3fXNZeuf7kJjKR4BD_Sn7cuk6EaKoRFmqkt6f-NfAcWTvCXD5YNTibv_S-fVEo-DY_o0B2X3Pz5cwm2tkNG0BYy4NayaET_-y0MmA

### Monaco Editor Playground Code

```typescript
class StorageService {
	showDetails = true;

	get() { }

	remove() { }

	getBoolean(key) {
		if (key === 'expandSuggestionDocs') {
			return this.showDetails;
		}
	}

	getNumber() {
		return 0;
	}

	store(key, value) {
		if (key === 'expandSuggestionDocs') {
			this.showDetails = value;
		}
	}

	onWillSaveState() {
		return () => { };
	}

	onDidChangeStorage() {
		return () => { };
	}

	onDidChangeValue() {
		return () => { };
	}
}

// monaco.languages.registerCompletionItemProvider('javascript', {
// 	provideCompletionItems: (model, pos, ctx, token) => {
// 		return null;
// 	}
// });

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n    alert('Hello world!');\n}",
	language: "javascript",
	automaticLayout: true,
}, {
	storageService: new StorageService()
});
```

### Reproduction Steps

1. Try the code with commented out CompletionItemProvider
2. Hit CTRL + SPACE and the suggestion details will show on first try because of the StorageService implementation
3. Comment in the CompletionItemProvider
4. Hit CTRL + Space -> The suggestion details do not show and the StorageService never gets called

### Actual (Problematic) Behavior

When using a CompletionItemProvider in Monaco >= 0.42-dev, the overridden StorageService does not get used.

### Expected Behavior

Like in <= 0.41.0 the overridden services should get called.

### Additional Context

[Comment from @alexdima](https://github.com/microsoft/monaco-editor/issues/2241#issuecomment-764694521) is not valid anymore from >= 0.42.0-dev

**Comment by hediet** [comment]
You have to create the editor before registering the completion item provider.
You can still set the model after you create the editor.

**Comment by FSDRE** [comment]
That was easy, thanks a lot for the support!
