### ISSUE TITLE
[Bug] Icon button used to fold/unfold a part of content is not tab key accessible

### ISSUE THREAD

**Issue by Jing29** [microsoft/monaco-editor#4250]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAJ3AwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2ZTDdnHMhA0in7Wfnzy_K06BVBbg-G6Fj0xlkbux3V6T0TXesnuKuF292VcXpWPf_2OP9PWDE32-RfwdAZCfpbzAFFkXmce1M_OVZ8LTayVim2hUYfJz_dkr8djUhGYBFO_RToXPuyQFVqhsBswTZMkk1PNzB_j3tnwX0dm3HwyQ1ea-km23aUuR_-l-JpS_hXDNlPIRm769JvIayxvsid4HxCjsIlNRE2nwMkoplR_MU_am7vyb25T4tLLQadHylVFsrb_MUzDr5XygmzL2MZrMDDh6ri3SJTa69jpsKJ7-d4XfdfzaUSJJec2DaDYJ0clrr4xxCz503W0DQqWsUjuoEzFZxxXYjz5B7qAuClq434s0qRsUkV-ph-4fiLaQpcg8M8Q4CHQ1tVSJvC04bEKZjSkPBf4DOt1NVwwyOFg3AUId91faA39gnmM8X9CBKtQyhsI-QSnDaBe-FkkvB5QOH5RGm5BPB1D9sto_1tlj-77F1T9Jv9yR7D3nCrAVlwoLBaqZ6k01Jh7cuCo-jDbl9e7f-KxuG3FtOhaAmS9uhxriakNO-RgZ76LHFvz1mTdgN0HJ-3m2l13LUvajTSNBRKTrVx1HNF4u-HsnbR_jAp0Co9oRntqhP3IA_-hJKCs

![image](https://github.com/microsoft/monaco-editor/assets/19400548/7c7c3ced-eff9-4708-b8f8-36f3dad429a8)
Highlighted icon buttons are not tab key accessible.

### Monaco Editor Playground Code

```typescript
// Main js code:
var jsCode = [
	'"use strict";',
	"function Person(age) {",
	"	if (age) {",
	"		this.age = age;",
	"	}",
	"}",
	"Person.prototype.getAge = function () {",
	"	return this.age;",
	"};",
].join("\n");

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript",
	glyphMargin: true,
	readOnly: true,
});

var decorations = editor.createDecorationsCollection([
	{
		range: new monaco.Range(3, 1, 3, 1),
		options: {
			isWholeLine: true,
			className: "myContentClass",
			glyphMarginClassName: "myGlyphMarginClass",
		},
	},
]);

// You can now use `decorations` to change or remove the decoration
```

### Reproduction Steps

No

### Actual (Problematic) Behavior

![image](https://github.com/microsoft/monaco-editor/assets/19400548/7c7c3ced-eff9-4708-b8f8-36f3dad429a8)
Highlighted icon buttons are not tab key accessible.

### Expected Behavior

![image](https://github.com/microsoft/monaco-editor/assets/19400548/7c7c3ced-eff9-4708-b8f8-36f3dad429a8)
Highlighted icon buttons should be t tab key accessible in order to meet the compliance.

### Additional Context

No

**Comment by hediet** [comment]
The "toggle fold" command can be used for this.

**Comment by Jing29** [comment]
What do you mean that toggle fold can be used for this? Can you share the example?

**Comment by Jing29** [comment]
@hediet How to understand the status not planned? Can I understand that it is an issue while we don't have plan to handle it? 
![image](https://github.com/microsoft/monaco-editor/assets/19400548/8405bca8-72f3-4528-9a88-2ce913005141)
