### ISSUE TITLE
[Bug] Comments inside C++ template arguments are sometimes not parsed as such

### ISSUE THREAD

**Issue by OfekShilon** [microsoft/monaco-editor#4253]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0-dev-20231025#XQAAAAKdAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzunzRgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKid_xhsXSuKhlGTxLUGE_paGdzKGZl7Nk25SIpp_ncCLxicsd1a8owg6BYQ3AeHyAvKoyxQF38Qeno_n3VUkZhJFr-Um4jLvm9WpAm8PLKf5d6R5PlE0fyTK74hQ2qlJn14eaQJX2i_Dyr2ych0qgPCYL1WkpZuwUpF1y6NTw2xs4p2APjti9EiwbvZ4C71gUCFTQPacKokwbZf5y_s6CnPwHMPID2euJf8jMiWHWJHsDUg4PC5QdRgcuPfEH3_0njQuJ8ZM-SE3_wtFAAA

### Monaco Editor Playground Code

```typescript
const value = /* set from `myEditor.getModel()`: */ `#include <vector>

int main() {
              /* const */ int  i;
  std::vector</* const */ int> v;
}`;

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "cpp",
	automaticLayout: true,
});
```

### Actual (Problematic) Behavior

`std::vector</* const */ int>` does not color the `const` as a comment. 

With an additional space ( `std::vector< /* const */ int>` ) it does.

### Expected Behavior

Commented code should be colored as such.

### Additional Context

Coming originally from this compiler-explorer bug:
https://github.com/compiler-explorer/compiler-explorer/issues/5299

**Comment by OfekShilon** [comment]
ping?

**Comment by TylerLeonhardt** [comment]
@hediet can you give us some steps on how to verify?

**Comment by TylerLeonhardt** [comment]
Actually I think I've figured it out. Looks verified.
![image](https://github.com/microsoft/monaco-editor/assets/2644648/648d25c5-76e7-4412-b723-e20d2b379608)
