### ISSUE TITLE
[Feature Request] customized Diff-Algorithm, needed for diff-editor.

### ISSUE THREAD

**Issue by skysefall-1234** [microsoft/monaco-editor#4264]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Is there a way to customized the diff-algorithm to achieve IgnoreCase, ignoreWhitespaceAtStart, ignoreWhitescapeAtEnd, IgnoreLineFeed APIs. The below code is not going to work when monaco version increase, so is there a way to acheive a permanent customized solution.

### Monaco Editor Playground Code

```typescript
const m1 = monaco.editor.createModel(`
1
2
3
4
5
6
7
8
9`);

const m2 = monaco.editor.createModel(`
1
2
x
4
5
6
8
9`);

const standaloneServices = require("vs/editor/standalone/browser/standaloneServices");
const WorkerBasedDocumentDiffProvider = require('vs/editor/browser/widget/workerBasedDocumentDiffProvider').WorkerBasedDocumentDiffProvider;
const provider = standaloneServices.StandaloneServices.initialize().createInstance(WorkerBasedDocumentDiffProvider, {});

const diffEditor = monaco.editor.createDiffEditor(document.getElementById('container'), {
	diffAlgorithm: {
		onDidChange: () => ({ dispose: () => {} }),
		computeDiff: async (original, modified, options) => {
			const result = await provider.computeDiff(original, modified, options);
			console.log("xyz ",result);
			result.changes.shift(); // Remove first diff
			return result;
		}
	},
});
diffEditor.setModel({
	original: m1,
	modified: m2,
});
```

**Comment by hediet** [comment]
[See here](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0-dev-20231025#XQAAAALmBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw7WseOAmRG9g_uOvArGQzPIhiY4OqtfluBPejRaWVSvclJVq_aHKR9qU4iZU2nJGtT_MEDGiM-4XIuc5oWCxgV76UsY2OovTBOGYcoKcQhPcJc143T3lIJR_cYgs06RWKj1Pz4P5-W0czIh-LD_VxTa4spqtP_lja6MvlGLHEanDZ_vdKh1zwJLDV020-zNcLz_ulneYAaK08zMMVfobO_BjWzF8GwtseOFkMDea6vR7l43h12Y0Wx0e7xKKqq5FS7LKVEpMVYDwYs67CMlvnxqqz9gXulAVkGdatXyol1GafQkOu0LcnLIdHkPHFiAtaGTOXMHrWJTqP8hl7plVHzfDdshn-v2YE_MPqc0GhTTrx_2Ap3WycHd5-Y1zzWncwX1zhbroHJ8_JUTcRbvCBPQhIUMY6GXZc62Mxq6awy5vE0EEq7nwQHQyeuspAEAKrEkuA_0BkTYThbbiXqIMANeHMQrqFCT1MFJr0kmXFZEy89y2mtbbWktRS77obo7srmosBOnT9yunS_4o32tBlbqOeDOpmylOVlnOlNanwZfoyyYSyiBCt0S1MB_QbV3QdvbntoVXKqeHZK9MikZgRe2jJoAETt3ASiq2VgWgGeIy3oPVYYGCuWQ-KliCVwNopcYbrrZInP-gHGounWh4_JpPC8REn1DxZ8e7l_-81_1Q)

**Comment by skysefall-1234** [comment]
Is there a way to compare Contented of both the editor, instead of manupilating it on basis of line-change. because i need to tackle a tricky/teadious task of Masking Expression(example :  inside the file wherever this <any-tag /> present that whole line should be ignored. Sorry if i sound confusing.

**Comment by skysefall-1234** [comment]
> [See here](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0-dev-20231025#XQAAAALmBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw7WseOAmRG9g_uOvArGQzPIhiY4OqtfluBPejRaWVSvclJVq_aHKR9qU4iZU2nJGtT_MEDGiM-4XIuc5oWCxgV76UsY2OovTBOGYcoKcQhPcJc143T3lIJR_cYgs06RWKj1Pz4P5-W0czIh-LD_VxTa4spqtP_lja6MvlGLHEanDZ_vdKh1zwJLDV020-zNcLz_ulneYAaK08zMMVfobO_BjWzF8GwtseOFkMDea6vR7l43h12Y0Wx0e7xKKqq5FS7LKVEpMVYDwYs67CMlvnxqqz9gXulAVkGdatXyol1GafQkOu0LcnLIdHkPHFiAtaGTOXMHrWJTqP8hl7plVHzfDdshn-v2YE_MPqc0GhTTrx_2Ap3WycHd5-Y1zzWncwX1zhbroHJ8_JUTcRbvCBPQhIUMY6GXZc62Mxq6awy5vE0EEq7nwQHQyeuspAEAKrEkuA_0BkTYThbbiXqIMANeHMQrqFCT1MFJr0kmXFZEy89y2mtbbWktRS77obo7srmosBOnT9yunS_4o32tBlbqOeDOpmylOVlnOlNanwZfoyyYSyiBCt0S1MB_QbV3QdvbntoVXKqeHZK9MikZgRe2jJoAETt3ASiq2VgWgGeIy3oPVYYGCuWQ-KliCVwNopcYbrrZInP-gHGounWh4_JpPC8REn1DxZ8e7l_-81_1Q)

Is this work when there is any version upgradation.
