### ISSUE TITLE
[Bug] Hover tooltip dimensions is incorrect for the fist time appear

### ISSUE THREAD

**Issue by BusinessDuck** [microsoft/monaco-editor#4265]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html#example-extending-language-services-model-markers-example

### Reproduction Steps

1. Refresh the page via CTRL+R
2. Hover mouse pointer at the `abcd` token with diagnostic problems

### Actual (Problematic) Behavior

Calculated width is not correct, actions was moved to the next line

<img width="704" alt="image" src="https://github.com/microsoft/monaco-editor/assets/10143411/8b019a82-0f1b-4c7a-8d5d-dc54efa1a35d">

### Expected Behavior

Calculated width is correct and all content fits

<img width="734" alt="image" src="https://github.com/microsoft/monaco-editor/assets/10143411/b0201ac3-2411-47aa-b443-c26d4220915f">

**Comment by hediet** [comment]
@aiday-mar can you look into this?
It works in https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0-dev.20230126#example-extending-language-services-model-markers-example - you can use the bisect feature of the playground to identify when it broke.

**Comment by aiday-mar** [comment]
Hi I have made several improvements to the editor hover since then. Do you still see this issue?
