### ISSUE TITLE
[Bug] duplication of editors

### ISSUE THREAD

**Issue by awwar** [microsoft/monaco-editor#4268]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Use code from my repo for reproduce: https://github.com/awwar/monaco-bug

This strange behavior occurs if you follow a link specifying http authorization data in the url.
The problem started in `Chromium` browsers on `November 10, 2023`.

How to reproduce:

1) `npm i`
2) `npm run build`
3) `python3 -m http.server 8000 -d "./build"` - **It is very important to run not on a dev server**
4) Open `http://user:password@127.0.0.1:8000`

Accurately reproduced in the browsers `Google Chrome` and `Microsoft Edge`
My versions: 
- `Google Chrome` `119.0.6045.159`
- `Microsoft Edge` `119.0.2151.58`

### Actual (Problematic) Behavior

![img](https://github.com/microsoft/monaco-editor/assets/28871876/8adb4646-212d-4d73-8554-c973f5f07769)

### Expected Behavior

![image](https://github.com/microsoft/monaco-editor/assets/28871876/5d88bf41-e199-4e48-9009-2ef4790ffc12)

### Additional Context

monaco-editor@`0.44.0` | MIT | deps: none | versions: 635

npm `9.6.4`

node `v20.0.0`

Google Chrome `119.0.6045.159`

Microsoft Edge `119.0.2151.58`

**Comment by hediet** [comment]
Unfortunately, we can only investigate issues that are reproducible in the monaco editor playground. Thanks for understanding!
