### ISSUE TITLE
[Bug] Monaco editor wordWrap problem with CJK characters

### ISSUE THREAD

**Issue by Sunyuzu** [microsoft/monaco-editor#4270]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAL7AQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0UkGlZmn-5ctzOK0Uo_OoWMOa4kdjBQIo4UQeK366lCw9QWZDHtw3_iKUka_Yh_SpXYthONT3PHkXELFwH48wSnlFrCBmJD91KLgBE0oLQ1R3uiGqSLvF2OaXe7ljVwzPKKIYbJbhkQNl_hFM6zZLNTsfytInrcWKd1F8pNL4QI2U9eMQVaWv8q5giu0f8B0Bm2S2ntpIi1d99vO5Y7VG9JqQxSMzjpLkv_kHr6-EOd1BguLWrv95mqoZOTXoY2d3TVfrU5SWWlOXfSIC8uWtcdgK6GCga9cZquRKo04wrwOHU06ugSbilQIv7JRKtRhZv8xwjU-wW4q8lMSYaeAhFivHiGXXWYzZF_K9UZ24jnmJdmwppYBkeVgD8SI9_9jRYsA

### Monaco Editor Playground Code

```typescript
const value = /* set from `myEditor.getModel()`: */ `function hello() {
	alert('Hello world!가나다라 가나다라 가나다라 가나다라다라다가다라다가나 다라자다라 日本語日本語に言語가나다라다라');
}`;

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
	wordWrap: "on",
});
```

### Reproduction Steps

Just create Monaco Editor's instance by using `wordWrap: "on"` option.
```
const myEditor = monaco.editor.create(document.getElementById("container"), {
	// ...
	wordWrap: "on",
	// ...
});
```
Then input texts in Korean, Japanese or Chinese with Google Chrome, Firefox and Safari on OSX Sonoma 14.1.1.

### Actual (Problematic) Behavior

My editor options:
```
MonacoEditor = Monaco.editor.create(ConfigEditorEl, {
	theme: 'vs',
	fontSize: 16,
	minimap: { enabled: false },
	"autoIndent": 'full',
	automaticLayout: true,
	"formatOnPaste": true,
	"formatOnType": true,
	wordWrap: "on",
	value: ApiKeySettingContents,
});
```
On my page
![CJK Languages wordWrap input problem](https://i.esdrop.com/d/f/bh8rwl3bwU/80bdjlabPB.gif "CJK Languages wordWrap input problem")

On Playground
![CJK Languages wordWrap input problem on Playground](https://i.esdrop.com/d/f/bh8rwl3bwU/iijHWpAXy8.gif "CJK Languages wordWrap input problem on Playground")

### Expected Behavior

When you set wordWrap to "on" and input text, it should automatically display on the next line. However, when entering CJK (Chinese, Japanese, Korean) text, the line doesn't break until a non-CJK character, such as a space or enter, is entered after the CJK text.

Does anyone know why? Please help me it is quite inconvenient to input CJK text in Markdown... even Code...

### Additional Context

With non-CJK characters like English is totally fine.

**Comment by xuelingkang** [comment]
I have the same problem, do you have any solution?

**Comment by xueerli** [comment]
@xuelingkang @Sunyuzu 
Hi, I'm also having this issue. Did you fix it?

**Comment by xuelingkang** [comment]
> @xuelingkang @Sunyuzu Hi, I'm also having this issue. Did you fix it?

Not yet, I am considering switching to another WebIDE.

**Comment by xueerli** [comment]
@xuelingkang @Sunyuzu 
I solved the problem by setting `accessibilitySupport: 'off'`.

**Comment by xuelingkang** [comment]
> @xuelingkang @Sunyuzu I solved the problem by setting `accessibilitySupport: 'off'`.

I don't know where the problem is, this isn't a perfect solution. I tried CodeMirror, I think it's more suitable for me.

![codemirror](https://github.com/microsoft/monaco-editor/assets/42362195/17c6d721-0b26-4c96-880a-15473e490859)

**Comment by Sunyuzu** [comment]
> @xuelingkang @Sunyuzu I solved the problem by setting `accessibilitySupport: 'off'`.

@xueerli  @xuelingkang Thank you for your sharing! I've also confirmed `accessibilitySupport: 'off'` option almost worked.

![](https://i.esdrop.com/d/f/bh8rwl3bwU/M7qCl1DU5h.gif)

My test env. is MacOS. When I use Safari is only okay. But this solution works on Chrome and Firefox either!
