### ISSUE TITLE
I tried this code but it not working as i expected

### ISSUE THREAD

**Issue by VeeralakshmiMuruganandham** [microsoft/monaco-editor#4273]
I tried the below code for undo operation, but it's not working as i expected
editor.trigger('whatever...','undo');

This line is reverting the changes but word by word.

For Example: I have added the statement in the editor
"Create '112'"

This code is undoing 112, then space and then Create. But what I expecting is whenever I click undo the last added line should be reverted (It should revert entire "Create '112'" line).

Is there any way to undo the last added line but not word by word.

_Originally posted by @alexdima in https://github.com/microsoft/monaco-editor/issues/451#issuecomment-305445971_

**Comment by hediet** [comment]
Please use the form to report a bug.
