### ISSUE TITLE
Error "ResizeObserver loop completed with undelivered notifications" with automaticLayout option

### ISSUE THREAD

**Issue by marigold-kfrederix** [microsoft/monaco-editor#4277]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

1. `git clone https://github.com/kfrederix/monaco-resizeobserver-error.git`
2. `npm i`
3. `npm run dev`
4. open the page in chrome
5. open the dev tools (and make sure they are docked to the bottom)
6. drag the dev tools up and down (to force the re-layout)

Following above steps will result in below error:

![image](https://github.com/microsoft/monaco-editor/assets/136071243/efc30aa3-6ec6-4467-8a76-6926b2a46624)

### Actual (Problematic) Behavior

The ResizeObserver code (which lives in vscode repo) produces an error "ResizeObserver loop completed with undelivered notifications" when option automaticLayout is enabled. This error becomes visible when using webpack dev-server.

### Expected Behavior

No ResizeObserver error when using webpack dev-server.

### Additional Context

This bug is a duplicate of: https://github.com/microsoft/vscode/issues/183324 
But I'm re-creating it here, since the one on vscode repo got closed while the issue is not yet fixed.

(+ also duplicated by https://github.com/microsoft/vscode/issues/197629)

**Comment by simonh1000** [comment]
I beelive the issue is linked to webpack devserver. Its a major pain point for me too

**Comment by marigold-kfrederix** [comment]
@simonh1000 yes with webpack dev-server it becomes visible from that overlay, as shown in the screenshot. (Without webpack dev-server the error is also there but it doesn't get in your way (so it's less of an issue...)

**Comment by hediet** [comment]
This could even be a bug in the webpack devserver. Please provide a monaco editor playground example so that we can reproduce and debug this issue.

**Comment by lucach** [comment]
This is **not** related to the devserver. With the reproduction above, the error becomes always visible by installing an explicit handler on `window.onerror`, irrespective of the devserver:  

```js
window.onerror = console.log
```

**Comment by simonh1000** [comment]
How can we get this reopened - this is a catastrophic that the issue is dismissed

**Comment by marigold-kfrederix** [comment]
I am able to reproduce it also on the playground now. I will open a new issue with playground repo so it can not be ignored anymore.

**Comment by marigold-kfrederix** [comment]
FYI: re-opened, including playground repro case: #4311
