### ISSUE TITLE
[Bug] Scrollbar visibility doesn't respect mac os system setting `Show scroll bars: always`

### ISSUE THREAD

**Issue by CharlesHGong** [microsoft/monaco-editor#4278]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

Just any monaco editor with a scrolling content.

https://microsoft.github.io/monaco-editor/playground.html?source=v0.34.1#XQAAAAIDBAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw5J-maAEiAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8ubYWGGeZ6At8nwtfu4tuzE0f8mcITrTwzSIeH30GciX8_LLoXEPAeFI19SZAzAnfyMrMVDdzKtLyol3wcdZxVdMcF-CsE3VoUz0v6nMQrWuxZuh-sSY7HGoicajlvH6ghAQOLl_g2YFygY8l_O_SSPN_RdzRNxpTjtnwKgb3qHMiGHg-OZ-QPy-EJBtuzQhqLhxgONTq6uziZyn7wlvK9g26txI_PEYBiqeL2IVZHnB1XLOSyCdeqB__0xircA

### Monaco Editor Playground Code

```typescript
function hello() {
  alert('Hello world!');
}
```

### Reproduction Steps

1. Have a long enough content that the editor can scroll vertically
2. Set mac os `Appearance` => `Show scroll bars` to `Always`

### Actual (Problematic) Behavior

Scrollbar still not visible when not hovered.

### Expected Behavior

Scrollbar should always visible

**Comment by hediet** [comment]
I don't think webpages can read the flag. The monaco editor renders its own scroll bars.
