### ISSUE TITLE
[Bug] Clicking inside monaco editor and releasing the mouse button on a link outside activates the link

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/monaco-editor#4279]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-creating-the-editor-hello-world

(any link should work)

### Reproduction Steps

Click inside the editor (e.g. to select some text), then release the mouse button while the cursor is over a link outside the editor. This could be "Read the announcement" on vscode.dev or "Home" in the playground.

### Actual (Problematic) Behavior

The link is activated and navigation to its target is triggered

### Expected Behavior

Nothing should happen because releasing the mouse button on a link should not do anything unless the mouse button was already pressed on that link

### Additional Context

I had to incorrectly check "Not reproducible in [vscode.dev](https://vscode.dev/) or VS Code Desktop" because that field is required, but I believe that this is a problem with monaco-editor and not vscode, even though both have the same problem. Of course trying to reproduce it in vscode desktop makes no sense because vscode desktop is not embedded on a website with other stuff around it.

**Comment by ThiefMaster** [comment]
hmm after reading that this package is extracted from the vscode sources I'll open an issue there as well just in case. i thought vscode is downstream of monaco, not upstream.

**Comment by hediet** [comment]
Closing as this is also a problem for vscode.
