### ISSUE TITLE
[Feature Request] my project need  support  aviatorscript language

### ISSUE THREAD

**Issue by Eadela** [microsoft/monaco-editor#4280]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

AviatorScript is a high-performance and lightweight dynamic scripting language that relies on the JVM virtual machine. 
my project use it, and edit it in monaco-editor, but not support currently；

**Comment by hediet** [comment]
Unfortunately, this feature request it out of scope for the monaco editor.
