### ISSUE TITLE
[Bug] Playground Color Provider Example is broken

### ISSUE THREAD

**Issue by MichaelKapustey** [microsoft/monaco-editor#4284]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

Current (not working):
https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-extending-language-services-color-provider-example
First not working:
https://microsoft.github.io/monaco-editor/playground.html?source=v0.31.0-dev.20211210#example-extending-language-services-color-provider-example
Latest working:
https://microsoft.github.io/monaco-editor/playground.html?source=v0.31.0-dev.20211209#example-extending-language-services-color-provider-example

### Reproduction Steps

Open the playground link and see that color squares are not displayed

### Actual (Problematic) Behavior

No color squares

### Expected Behavior

Color squares present

**Comment by hediet** [comment]
[This broke here](https://github.com/microsoft/vscode/compare/15415b6de68f3fcfefcd264ac37cc3c3d54a378b...a1842c8f633237d6d850ada5772359ad32480655)

I don't see which commit did that. @aiday-mar can you look into this?

**Comment by aiday-mar** [comment]
yep will do

**Comment by aiday-mar** [comment]
Hi I have investigated the code and I notice that with the following example, the colors are shown as expected:

```
monaco.languages.register({
	id: "colorLanguage",
});

monaco.editor.create(document.getElementById("container"), {
	value: "red\nblue\ngreen",
	language: "colorLanguage",
	colorDecorators: true,
});

monaco.languages.registerColorProvider("colorLanguage", {
	provideColorPresentations: (model, colorInfo) => {
		var color = colorInfo.color;
		var red256 = Math.round(color.red * 255);
		var green256 = Math.round(color.green * 255);
		var blue256 = Math.round(color.blue * 255);
		var label;
		if (color.alpha === 1) {
			label = "rgb(" + red256 + ", " + green256 + ", " + blue256 + ")";
		} else {
			label =
				"rgba(" +
				red256 +
				", " +
				green256 +
				", " +
				blue256 +
				", " +
				color.alpha +
				")";
		}

		return [
			{
				label: label,
			},
		];
	},

	provideDocumentColors: () => {
		return [
			{
				color: { red: 1, blue: 0, green: 0, alpha: 1 },
				range: {
					startLineNumber: 1,
					startColumn: 1,
					endLineNumber: 1,
					endColumn: 2,
				},
			},
			{
				color: { red: 0, blue: 1, green: 0, alpha: 1 },
				range: {
					startLineNumber: 2,
					startColumn: 1,
					endLineNumber: 2,
					endColumn: 2,
				},
			},
			{
				color: { red: 0, blue: 0, green: 1, alpha: 1 },
				range: {
					startLineNumber: 3,
					startColumn: 1,
					endLineNumber: 3,
					endColumn: 2,
				},
			},
		];
	},
});

```

The change here is that the start and end columns are not 0 and endColumn is strictly bigger than startColumn. 

I believe that colors should locations should be defined in the following way:

- The range of the color should be the text associated to the color. In essence that means that if I have the color defined by the text `red` then start column would be 1 and end column would be 4. This way when the color picker is used to change the color, the text associated to the color will change. In you example the start and end column numbers were exactly equal, meaning that no text was selected as being associated to the color
- The column number should also be 1-based. I noticed in your example that the line number is 1-based but the column number is 0-based. 

I think the previous behavior you saw in the earlier monaco release was buggy. You may adopt the range convention as defined above. Please let me know if this has answered your concerns.

**Comment by hediet** [comment]
@aiday-mar can you update the monaco editor example in this repository?

**Comment by MichaelKapustey** [comment]
Thank you so much. I can see the working example in the playground now.
