### ISSUE TITLE
'Expand/Collapse' buttons present in code section are not keyboard accessible.

### ISSUE THREAD

**Issue by msftedad** [microsoft/monaco-editor#4285]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAJ3AwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2ZTDdnHMhA0in7Wfnzy_K06BVBbg-G6Fj0xlkbux3V6T0TXesnuKuF292VcXpWPf_2OP9PWDE32-RfwdAZCfpbzAFFkXmce1M_OVZ8LTayVim2hUYfJz_dkr8djUhGYBFO_RToXPuyQFVqhsBswTZMkk1PNzB_j3tnwX0dm3HwyQ1ea-km23aUuR_-l-JpS_hXDNlPIRm769JvIayxvsid4HxCjsIlNRE2nwMkoplR_MU_am7vyb25T4tLLQadHylVFsrb_MUzDr5XygmzL2MZrMDDh6ri3SJTa69jpsKJ7-d4XfdfzaUSJJec2DaDYJ0clrr4xxCz503W0DQqWsUjuoEzFZxxXYjz5B7qAuClq434s0qRsUkV-ph-4fiLaQpcg8M8Q4CHQ1tVSJvC04bEKZjSkPBf4DOt1NVwwyOFg3AUId91faA39gnmM8X9CBKtQyhsI-QSnDaBe-FkkvB5QOH5RGm5BPB1D9sto_1tlj-77F1T9Jv9yR7D3nCrAVlwoLBaqZ6k01Jh7cuCo-jDbl9e7f-KxuG3FtOhaAmS9uhxriakNO-RgZ76LHFvz1mTdgN0HJ-3m2l13LUvajTSNBRKTrVx1HNF4u-HsnbR_jAp0Co9oRntqhP3IA_-hJKCs (Opens in new window or tab)](https://github.com/microsoft/monaco-editor/issues/url)

### Monaco Editor Playground Code

```typescript
// Main js code:
var jsCode = [
'"use strict";',
"function Person(age) {",
" if (age) {",
" this.age = age;",
" }",
"}",
"Person.prototype.getAge = function () {",
" return this.age;",
"};",
].join("\n");

var editor = monaco.editor.create(document.getElementById("container"), {
value: jsCode,
language: "javascript",
glyphMargin: true,
readOnly: true,
});

var decorations = editor.createDecorationsCollection([
{
range: new monaco.Range(3, 1, 3, 1),
options: {
isWholeLine: true,
className: "myContentClass",
glyphMarginClassName: "myGlyphMarginClass",
},
},
]);
```

### Reproduction Steps

1. Open URL: [Monaco Playground (codepen.io)](https://codepen.io/lijinglin29/pen/abXYZJR)
2. Navigate to 'Run' button present in top right corner and invoke it.
3. Navigate inside the code section present below.
4. Tab to expand/collapse button and observe the functionality using tab key.

### Actual (Problematic) Behavior

'Expand/Collapse' buttons present in code section are not keyboard accessible present inside the Log tab.
**Observation:** It is only accessible via mouse.

https://github.com/microsoft/monaco-editor/assets/93735775/025013e9-6cde-4cbc-8de4-28fa0576dedc

### Expected Behavior

'Expand/Collapse' buttons present in code section should be accessible through keyboard present inside the Log tab.

### Additional Context

NA

**Comment by hediet** [comment]
/duplicate https://github.com/microsoft/monaco-editor/issues/4250
