### ISSUE TITLE
[Bug] Render Side By Side is not working on v0.44.0

### ISSUE THREAD

**Issue by vincent-caraccio** [microsoft/monaco-editor#4286]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAKiAgAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2JVMdHDtEFhYrMR1dkphGG8TTFC5uoYXCC1StgsOS4KZxfxcegah7ZqzCvf0LDdGpA8g1PEo5-egMf8b0BULvVOK-yFe3MEioSDw1l0THUzjOATqg98GhyMByPlZpj8SH46Fi0fvCKc2GgRPlGiTLS7YTIOxk0CAa757dit5qD3s2iSlVG7IYq9i767xhFOv2C9WWliK53rmOshoS1WzjD1crVD-qo-3x9sPRDjxVYm4EHftyebwainQ2LZMNTeAomXwfdPUHJJbf3PYV0xQiNe9h1FoSD1CTAwicnyNLZgETjI5iTRKsokvwnO_VkDd6g_B9nR7b3p6UkEhfkEjSTbANcmtA2HphMZ2Z7EJPDQsAQ17HAb6FMbX9IS7dLGKsy8yay-LySD0BG2EV50WJAZh9pNjbl1IhGq1jfX51j_-kCKc

### Monaco Editor Playground Code

```typescript
var originalModel = monaco.editor.createModel(
	"This line is removed on the right.\njust some text\nabcd\nefgh\nSome more text",
	"text/plain"
);
var modifiedModel = monaco.editor.createModel(
	"just some text\nabcz\nzzzzefgh\nSome more text\nThis line is removed on the left.",
	"text/plain"
);

var diffEditor = monaco.editor.createDiffEditor(
	document.getElementById("container"),
	{
		// You can optionally disable the resizing
		enableSplitViewResizing: false,

		// Render the diff inline
		renderSideBySide: true,
	}
);
diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel,
});
```

### Reproduction Steps

Nothing special to do. 

### Actual (Problematic) Behavior

The renderSideBySide option has no effect, the diff view is still inline.

### Expected Behavior

when renderSideBySide is set to true, the rendering should be side by side (like in previous versions)

**Comment by hediet** [comment]
You have to set `useInlineViewWhenSpaceIsLimited: false`
