### ISSUE TITLE
[Feature Request] The diff component supports expanding and collapsing

### ISSUE THREAD

**Issue by Ji-github** [microsoft/monaco-editor#4289]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Hope the diff component supports expansion and folding, the same diff code defaults to fold and can be expanded to see all the code in the current folding area, and the expanded code can also be folded.

### Monaco Editor Playground Link

No link.
Please look description.

### Monaco Editor Playground Code

```typescript
No code.
It's feature.
```

**Comment by hediet** [comment]
This is already requested for VS Code (and thus a duplicate).
