### ISSUE TITLE
Completion widget does not automatically close when opened via keyboard

### ISSUE THREAD

**Issue by foxable** [Microsoft/monaco-editor#429]
monaco-editor version: 0.8.3
Browser: IE/Chrome/Firefox
OS: Windows

**Steps reproducing the issue:**
1. Open the "Hello world!"-example on the [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html)
2. Place the cursor anywhere in the editor and open the completion widget using Ctrl + Space
3. Type "foobar"

**Expected behavior:**
The completion widget is closed, since there are no completion items matching "foobar".

**Actual behavior:**
The completion widget stays open, showing the completion items for the last matched string. However, when closed explicitly using Esc and then reopening it using Ctrl + Space, it shows "No suggestions".

Note: When the completion widget is triggered by typing, it closes as soon as you have typed "fooba", which is the expected behavior.

**Comment by jrieken** [comment]
Yes, that is designed behaviour. If you explicitly trigger completion via Ctrl+Space the widget doesn't close when nothing matches anymore (but shows the last good matches). With 24x7 IntelliSense that just comes while  you type we hide the widget again.
