### ISSUE TITLE
[Bug] Safari browser unable to render Monaco editor

### ISSUE THREAD

**Issue by DreamGhostStar** [microsoft/monaco-editor#4293]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-creating-the-editor-hello-world

### Reproduction Steps

Open any editor in Safari to reproduce

### Expected Behavior

monaco-editor version: 0.44.0
<img width="1786" alt="image" src="https://github.com/microsoft/monaco-editor/assets/48384290/8afc85ea-b5ac-4a67-8849-d7518c12f41a">

**Comment by sakshi-kapstan** [comment]
Facing the same issue, it's in the 0.45.0 as well FWIW.

**Comment by DreamGhostStar** [comment]
> I upgraded to 0.45.0 and it appears to be working so far.

Yes, monaco editor core has fixed this issue in 0.45.0. https://github.com/microsoft/vscode/pull/198717/files

**Comment by hediet** [comment]
Closing as this has been fixed.
