### ISSUE TITLE
where is inmemory:// ?

### ISSUE THREAD

**Issue by jiron12** [Microsoft/monaco-editor#43]
`/// <reference path="typings/test.d.ts"/>`

Gives me "file 'inmemory://model/typings/test.d.ts' not found."

Where and how can I put this file, in order for it to be found like this?

Thank you very much for any hint!

**Comment by jrieken** [comment]
references additional resources via `///`-references, `require`, or `from` calls isn't supported because there isn't a way to source additional files to the language service.
