### ISSUE TITLE
Integrate VS Code extensions in the Monaco editor

### ISSUE THREAD

**Issue by HelderGoncalves92** [Microsoft/monaco-editor#430]
The FAQ section of the Monaco repository says that it is not possible to execute VS Code extensions on the Monaco Editor in browser. If I understand correctly, the extensions have server dependencies. Thus, it should be possible to integrate an extension in the Monaco editor with a server (ex. npm run simpleserver).

As example, I would like the integrate the [Better Merge](https://github.com/pprice/vscode-better-merge) extension in the Monaco editor. Is that possible? How may I do it?

**Comment by alexandrudima** [comment]
The vscode extensions are built on top of the vscode API. The vscode API is built on top of the monaco editor API. One would need to build things on the monaco editor API or implement the vscode API from scratch on top of the monaco editor API.
