### ISSUE TITLE
[Bug] Editor not resizing properly on React render

### ISSUE THREAD

**Issue by StephaneAdeso** [microsoft/monaco-editor#4306]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

1- clone and install the repo
2- press F5 to launch the extension
3- Click on "new Request" 
4- open and close the first Details

(steps to reproduce are also in the attached video)

### Actual (Problematic) Behavior

I am developing an open source extension for vscode in typescript and react.
It is an alternative to thunderclient and postman that is still being designed.
In my view I have 2 details, the first shows or hides the query configuration.
The second details shows or hides the response. The second is where I use Monaco editor and where I have the problem.
When I open and close the first details, the second one does not resize.
If I remove the Monaco editor, or set max-height:100px, everything works fine, but as soon as I let it take up all the space,
it is not resized.

I have seen this problem happen to more people. Here is a [link to stackoverflow](https://stackoverflow.com/questions/59963794/monaco-editor-force-resize-editor) of people complaining about the same thing. 

This is the repo: https://github.com/StephaneAdeso/adeso-seeker.git . ( Use the branch: `develop`)
I also add a shot video showing the issue and steps to reproduce. 

https://github.com/microsoft/monaco-editor/assets/55595063/95344a92-aabe-4d5a-8096-7d80166efdcd

The code of the Monaco editor is on the `Editor.tsx` file. This is the code:
```tsx
// Code editor. Used to display the response of the request or other code.
// https://microsoft.github.io/monaco-editor/docs.html
// https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorOptions.html

import * as monaco from 'monaco-editor';
import { useEffect, useRef, useState } from 'react';

interface EditorProps {
  value: object;
  language?: string;
  className?: string;
}

export const SkrEditor = ({
  value = {},
  language = 'json',
  className = ''
}: EditorProps): JSX.Element => {
  const editorRef = useRef<HTMLDivElement>(null);

  const [monacoEditor, setMonacoEditor] =
    useState<monaco.editor.IStandaloneCodeEditor>();

  // create the editor element
  useEffect(() => {
    const handleResize = () => {
      if (monacoEditor) {
        monacoEditor.layout();
      }
    };

    if (!monacoEditor && editorRef.current) {
      const editor = monaco.editor.create(editorRef.current, {
        autoIndent: 'full',
        automaticLayout: true,
        formatOnPaste: true,
        formatOnType: true,
        language,
        minimap: { enabled: false },
        quickSuggestions: false,
        readOnly: true,
        scrollbar: {
          verticalScrollbarSize: 10,
          horizontalScrollbarSize: 10
        },
        scrollBeyondLastLine: false,
        theme: 'vs-dark',
        value: JSON.stringify(value, null, 2)
      });
      setMonacoEditor(editor);
      window.addEventListener('resize', handleResize);
      // Clean editor on unmount
      return () => editor.dispose();
    }
  }, []);

  // update value
  useEffect(() => {
    if (monacoEditor) {
      monacoEditor.setValue(JSON.stringify(value, null, 2));
    }
  }, [value, monacoEditor]);

  // update language
  useEffect(() => {
    if (monacoEditor) {
      const model = monacoEditor.getModel();
      if (model) {
        monaco.editor.setModelLanguage(model, language);
      }
    }
  }, [language, monacoEditor]);

  return (
    <div className={` ${className}`} id="MonacoRootElement" ref={editorRef} />
  );
};

```

### Expected Behavior

Monaco editor should resize when React re-render.

**Comment by hediet** [comment]
Unfortunately, we cannot look into this without having an example that reproduces in the monaco editor. Thanks for understanding!
