### ISSUE TITLE
IE 11 shows a popup for accessing clipboard by the website

### ISSUE THREAD

**Issue by inspiredjw** [Microsoft/monaco-editor#431]
**IE 11** shows an alert for accessing clipboard by the website.

It is easily reproducible through  Monaco editor webpage and just select random thing and press `CTRL + C  ` in **IE 11**.

![ie11](https://cloud.githubusercontent.com/assets/1109087/25503073/d5257920-2b4d-11e7-96df-77cff40e44aa.png)

I thought this is common behavior of any other web editors.

Some other famous editors like [TinyMCE](https://www.tinymce.com/) and [CKEditor](http://ckeditor.com/) did not ask me to allow extra permission to access clipboard.

**Comment by alexandrudima** [comment]
Interestingly, this does not reproduce on Edge or Chrome
