### ISSUE TITLE
[Bug] Error "ResizeObserver loop completed with undelivered notifications" with automaticLayout option

### ISSUE THREAD

**Issue by marigold-kfrederix** [microsoft/monaco-editor#4311]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#XQAAAAKrAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzohERgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKimARHSWlrTPOQHROITHxmAeFEs9_m3VHdSe7_Etv6WpgzlH4suqcRwO2cnFLtaZLR4F0JFm8KVkxk-4Ch5aQ5cUcW42GDEo1TLlRBA6ZuApl5HQvRce9vFBHq-nuG9Nsza8eABif3xxAynXtZ66klrxMxOOBdRgwC_p0bCI3uVg9_wpXuzaz2FQwYVXRsSY1isaTy1ClRWhGxr6BxU2PeuOcknKeki4oluDieGxneoptFJeb3DvsZX93ZAJjfKPqL8j_z0Nr8f4K93t7fBsn4pg1bFDtp9blk5m2gtFdhNOA_6kUP2A

### Monaco Editor Playground Code

```typescript
/******************
/* JavaScript
/******************
const value = /* set from `myEditor.getModel()`: */ `function hello() {
  alert('Hello world!');
}`;

const myEditor = monaco.editor.create(document.getElementById("container"), {
  value,
  language: "javascript",
  automaticLayout: true,
});

// Log uncaught errors to console.
// This will make the ResizeObserver error visible from the console.
window.onerror = (err) => console.error(err);

/******************
/* CSS
/******************
body {
  /* counter for overflow: hidden which it has on the playground by default */
  overflow: unset;
}
```

### Reproduction Steps

1. Open dev tools (tested with chrome)
2. toggle the fullscreen button a few times

### Actual (Problematic) Behavior

Error: "ResizeObserver loop completed with undelivered notifications"

![image](https://github.com/microsoft/monaco-editor/assets/136071243/d239d6be-37c1-4936-be98-2bf80680a735)

### Expected Behavior

No error.

### Additional Context

There exist a few duplicates of this one (all of which are closed).
This was the original one, where I originally provided already a PR with fix: https://github.com/microsoft/vscode/issues/183324
@alexdima was helpful there. He made some changes on my PR to improve it (which I appreciate) but unfortunately the fix did not work anymore after those changes.

**Comment by rbertels** [comment]
We're also experiencing this issue but only in Edge and Chrome. Firefox seems okay somehow.
Would be great to see @marigold-kfrederix  's original PR go through.

**Comment by simonh1000** [comment]
This is a huge issue for us. Hope this can get merged quickly

**Comment by CGNonofr** [comment]
FYI, I'm still able to reproduce that issue on a big project. I've backported [that fix](https://github.com/microsoft/vscode/pull/201406)

**Comment by simonh1000** [comment]
yikes - me too. I tried https://github.com/microsoft/monaco-editor/releases/tag/v0.46.0-dev-20240202 with our dev environment (webpack) and still seeing `ResizeObserver loop completed with undelivered notifications.`

**Comment by CGNonofr** [comment]
I don't think [this fix](https://github.com/microsoft/vscode/pull/201406) is included on monaco-editor@0.46-dev versions though

**Comment by goliney** [comment]
@alexdima seems like this ticket should be reopened 😞

**Comment by marigold-kfrederix** [comment]
Indeed, the issue is still reproducible on the monaco playground (0.46.0) using the exact same code sample

**Comment by jamesjulich** [comment]
Can confirm that this issue is still present.

**Comment by SoulKa** [comment]
Also getting this issue with monaco in my react electron application on version 0.48.0
