### ISSUE TITLE
[Bug] CodeAction triggered inside of the codeAction panel

### ISSUE THREAD

**Issue by samirzubi-db** [microsoft/monaco-editor#4313]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

[Playground link](https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#XQAAAAKqBwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxCJbqwwLINgRABDcFm89fBOSueOLTYt0aaEwnsLoPwmLxwedOn8Q8TDA7HdG2A53dB9AMwMH_c2UsEDCPbL8A4cbHi-okxRHELlz_oRlSAIcPe7oQadXXoN_j9_hwGqgZ68l3b3CX1ajWzJJ7BXZacWCjzQrmmozs2JJ-6TkQeTBMYbxAtfLQemYj1MwBJpwIyu89-Q601yXTDUWsu3sidZ4_70nFWVytDSetO94O2vOfYSUN1U_OfJi95noQ5Xam9gaqHs6-__WJop5BM5VtDhoGAiVkq-rSHlnWFo6a7RT7tIoNrcucAuvEBtvsdSw6BMWcGODaJv7SvenQW90k09SwQrECxBRv56vqv7fsLZUIrbDMtNRvSoza8uSi0rzXWdKMp5bzXsR41Sy4ZrRADgseyMYmzCkYe3M5cB1mUCPNAuUCrm47V-l0USX_-_vbLJNKW3nD39bLswi7FAvn9qxzgbrBC3LQLt5hHQWQEayLDwBrEsHSZMQQfVzetTDz--xUOhPADbyVG-bruj4Jp8HhPxs9koQzbzGOjwXTHsqucbP-p9w03iJpU4a-BrNh8xKeD1aVmKAHeobx8gr4lSsmcllLprA7VE_LxX_qmIp8c1WD6EJzNrWYSXzxfFTc0GQirVqE1yV0Cgu2ZvBO-KP6_q8jOAn8aUz7rPV2OJbJpqtIe00L4KnQN0-8GFuPdj33cQWFMZkLFJ13CdhJ8cPKg16Oiicl0YQ3VP9DIyn0apnzeOHDU2oYJIAAfYifn0gh8U82Mr47C3-TSnDPD5AhvLAvXNtWFktNvuDJqgYROI08HbpvW06mFKKcmqjYZk7z873kquOkAe-6TQk9dfJp2YmL9pq566RQRKs9D5c0zbWsMuugK8mHjvUyPB6ffzcBGFKhHUk-ea6autb-G6cZTbE3htSYcSyWfPmE3GW3QENi8ZS07x6a9pVBrsrLcvBqJ7TbuEmpHbqv6isVMsAi_ZfuTRHbfaLV73GguXXB9qDzQdZQ7o2I4_eizATHQWZ7fNrdBs5hIuaForkzvOLXekjZSre9Aiymrh2f_Lac_L_sXQ)

### Monaco Editor Playground Code

```typescript
function validate(model) {
	const markers = [];
	// lines start at 1
	for (let i = 1; i < model.getLineCount() + 1; i++) {
		const range = {
			startLineNumber: i,
			startColumn: 1,
			endLineNumber: i,
			endColumn: model.getLineLength(i) + 1,
		};
		const content = model.getValueInRange(range).trim();
		const number = Number(content);
		if (Number.isNaN(number)) {
			markers.push({
				message: "not a number",
				severity: monaco.MarkerSeverity.Error,
				startLineNumber: range.startLineNumber,
				startColumn: range.startColumn,
				endLineNumber: range.endLineNumber,
				endColumn: range.endColumn,
			});
		} else if (!Number.isInteger(number)) {
			markers.push({
				message: "not an integer",
				severity: monaco.MarkerSeverity.Warning,
				startLineNumber: range.startLineNumber,
				startColumn: range.startColumn,
				endLineNumber: range.endLineNumber,
				endColumn: range.endColumn,
			});
		}
	}
	monaco.editor.setModelMarkers(model, "owner", markers);
}

const value = `12345
abcd
234.56
12345
abcd
234.56`;
const uri = monaco.Uri.parse("inmemory://test");
const model = monaco.editor.createModel(value, "python", uri);
const editor = monaco.editor.create(document.getElementById("container"), {
	model,
});
validate(model);
model.onDidChangeContent(() => {
	validate(model);
});

function sleepOneSecond() {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve('Resolved after 1 second');
        }, 1000); // 1000 milliseconds = 1 second
    });
}

monaco.languages.registerCodeActionProvider('python', {
	provideCodeActions: (model, range, context, token) => {
		console.log('>>> codeAction triggered');
		// console.log('>>>', model, range, context, token);
		return sleepOneSecond().then(value => {
    		return {
				actions: [
					{
						title: 'a',
						kind: 'quickfix',
					}
				],
				dispose: () => { },
			};
		})
	}
})
```

### Reproduction Steps

1. Open up the console
2. Try to hover over a warning
3. There should be a console log that the code action is triggered 
4. Move the mouse to the panel
5. The code action is triggered again (This is the unexpected behaviour)

### Actual (Problematic) Behavior

Hovering over a codeAction panel will trigger the codeAction again.

### Expected Behavior

Expected that the codeAction is triggered only once on the initial hover.

### Additional Context

Video description of the issue:
https://github.com/microsoft/monaco-editor/assets/108306317/923749b1-5e58-4348-842b-c917919ea052

**Comment by hediet** [comment]
provideCodeActions can be called multiple times. Probably the context is different for the second call.
