### ISSUE TITLE
[Bug] setExtraLibs does not work for globals in javascript mode

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/monaco-editor#4323]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0-dev-20231214#XQAAAAKTAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzrB9RgmSaumWUF-TBOs7rE9XbZp0QEljbc6k5igJtayNyZFpJFm_mM5nJyGtaYVSA8LYfNAiH0H_SKfgOTkv8DlUboExY7GbKPnbhroY0B24jmS2R92JnItIzQGMHZXUjqq2hvRdCNtfoSooq76YgWgU381BhoMHe_tSoK2stAoyBGGGs841oh94ws9qhUvlnfPqRBj0LWu3ww-xZFSq3-X32-aYE6JaXdqOxkbXJc8xhxp32Zw9fTR5S_h0LAYlicKOopRGu9sTsR9_OkBwEjpxHxubth1Dhe2QmdfyP6LMT3m25ylnESchgP6jfFJ0Qq0yyW5wSTELD7CvokVqGtzM_9kU5SQ

### Monaco Editor Playground Code

```typescript
const value = `a`;

monaco.languages.typescript.typescriptDefaults.setExtraLibs(
[
{content:'declare var a : { b: "aa", c: {d:"e"}} ', filePath:''}
]);

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
});
```

### Reproduction Steps

Try the playground, you get no completition for the object 'a'
switch to typescript, and the completition works

### Actual (Problematic) Behavior

No codecompletition for global objects in javascript mode

### Expected Behavior

code completition should work

**Comment by HolgerJeromin** [comment]
A short googling gave me `monaco.languages.typescript.javascriptDefaults.setExtraLibs()`
But I have never used monaco myself...

**Comment by jogibear9988** [comment]
thanks, didn't find this....

**Comment by HolgerJeromin** [comment]
Could you edit your comment in typescript repo so this issue over there is not derailed? Thanks.
