### ISSUE TITLE
[Bug] LightBulbWidget throws exception on last line

### ISSUE THREAD

**Issue by ckorherr** [microsoft/monaco-editor#4330]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.45.0#XQAAAAJOAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscwzSP-RgmSaumWUF-TBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKinRRqkRw2DahfcIuqkMpqjQzb4EWA-ZQCZ02zgj2FTCOhizdIecjP3y38tU6aforYL6fz5xgVlwgQ9dghQO1sha8AnbQK9AQwkrcSmuqh6qfmfyKo3-2dUTksZ1t1mTZHqDLCrTq3j0LZP6erkFenD-JY5GvsLplamwbKMRrekj2FVnSk65-0MUGEyuff1rUt3d1frmasTog_wd87z2nh1__LKYLAA

### Monaco Editor Playground Code

```typescript
const value = /* set from `myEditor.getModel()`: */ `import x from "some-package"`;

// Hover on each property to see its docs!
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "typescript",
	automaticLayout: true,
});
```

### Reproduction Steps

Put the cursor into the first line.

### Actual (Problematic) Behavior

Throws exception:
Uncaught (in promise) Error: Illegal value for lineNumber
    at TextModel.getLineContent (textModel.ts:749:10)
    at LightBulbWidget.update (lightBulbWidget.ts:208:65)
    at CodeActionController.update (codeActionController.ts:157:32)

### Expected Behavior

Guess what...

### Additional Context

Found this bug on vscode:
https://github.com/microsoft/vscode/issues/201812

This PR in VS Code should address the problem by taking the existing line count into account:
https://github.com/microsoft/vscode/commit/29d7057198d2cc47cfea416c3c3c454b672a87f1 -> See lightBulbWidget.ts line 204

Problem is fixed on the latest monaco-editor DEV build!

It would be great to get a new version, as we are relying on light bulbs in a single-line editor.

**Comment by aiday-mar** [comment]
Hi @ckorherr as I mentioned in the issue https://github.com/microsoft/vscode/issues/201812, I believe this issue should be resolved with PR https://github.com/microsoft/vscode/pull/200051. I am not exactly sure how monaco editor versioning works in the playground, but the issue should be resolved in latest VS Code Insiders (not stable however). I suppose the issue should be resolved with the next monaco editor release on the playground.

@hediet

**Comment by aiday-mar** [comment]
Hi I believe this issue should be resolved so I will close this issue.
