### ISSUE TITLE
[Feature Request] JSON diff (custom diff algorithm)

### ISSUE THREAD

**Issue by tomasbruckner** [microsoft/monaco-editor#4343]
### Context

- [X] This issue is not a bug report. *(please use a different template for reporting a bug)*
- [X] This issue is not a duplicate of an existing issue. *(please use the [search](https://github.com/microsoft/monaco-editor/issues) to find existing issues)*

### Description

Based on the discussion https://github.com/microsoft/monaco-editor/issues/4036

It would be great if we could define our own diff algorithms. One of the use cases is that I have 2 JSON files and I want to make a diff if the JSON is semantically the same (not necessarily the same characters used).

Example:

```json
{
  "foo": 1,
  "bar": 2
}
```

is same as

```json
{
                                    "bar":               2,
  "foo": 1
}
```
Even though the spacing is not the same and properties have different order

**Comment by hediet** [comment]
That is possible. Please search in the issue tracker, thanks!
