### ISSUE TITLE
[Bug] CtrlCmd not working on mac os, but WinCtrl is

### ISSUE THREAD

**Issue by ben519** [microsoft/monaco-editor#4387]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.46.0#XQAAAAL8BAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw7f-aAjN898w8vXcYTGSMs5sUpNh6UB0XRaMhEtbSa7F_AYLMU68VMTzjdzbgpvNt8twSv1rycxa4dRmOnhf7XcYWRThk7aZGpHgQrcXxdu7G_l3dffVF61eSzIgiC7Jq5Yg_ygoouQf2EHhHSHGtAJLh98WBB9q4m6KtM8Sx2C0zS6UqCM0ivNQYkd5y8e8LiwT5o36x_Ewah6iARkQFNL4FRtAypnuEg5ukVr6SgKpLKRe-5FFuREZBMc4_ZQKgZD70kxgSPVGQrsPFkwETtCYbYVUN04vnRw4qHM9ctmSapY8u9Vi2H36EmlDiqTF13Lgi1B4E50qA0xK8osMq1KYICvt1Rhd1eEh2R21bZ7HP9e4FmsMnAVG-Fi1fhWZ3Tu55dHpQfgBSmpidn3fZxu28tmcCzNR54wLEGGoDBos4moxj3gBQfJ5HLP2WcZI1-qQeOOeFDfSzU_-8cKioowIRl9Yxj4yDzpVM0bYfKnuyZY6Wv-avqVtBCHC5rCcxKPXMDjca9Kj76tFm61Yww8APSurvjTH56Zn_Dj2bnHboP9BOr54Wojgj4Jvy4h4dm-aDZh6G1p6wxut-I_H-WbAYdt2sEKyb0CpDjqcv4WqLNaH0b3znhyBdbZHs9RWsQ-_ZEPTnFCBzw1Heub22mBIJqQmd_mScE0CBan2vtqTFHO775UpLpBYvOQXYpXVy3T1y5Eal905TKkfVCegF6VJzdrFhFR94h48tpFuklE8QAFYF4lFaD1n0NDEi1Co2iK3N03zrmqyRagURupRm2UhFMoML3WrccIMGT6pEZ3Xc-G_Mo3rdQ6GbBSex7fa2WQbtmA7d5BeINSz9MN6JRjdbDFYn29JCqQCWnIHB76D_bnKtAA

### Monaco Editor Playground Code

```typescript
var editor = monaco.editor.create(document.getElementById("container"), {
	value: [
		"",
		"class Example {",
		"\tprivate m:number;",
		"",
		"\tpublic met(): string {",
		'\t\treturn "Hello world!";',
		"\t}",
		"}",
	].join("\n"),
	language: "typescript",
});

// Explanation:
// Press F1 => the action will appear and run if it is enabled
// Press Ctrl-F10 => the action will run if it is enabled
// Press Chord Ctrl-K, Ctrl-M => the action will run if it is enabled

editor.addAction({
	// An unique identifier of the contributed action.
	id: "my-unique-id",

	// A label of the action that will be presented to the user.
	label: "My Label!!!",

	// An optional array of keybindings for the action.
	keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS],

	// A precondition for this action.
	precondition: null,

	// A rule to evaluate on top of the precondition in order to dispatch the keybindings.
	keybindingContext: null,

	contextMenuGroupId: "navigation",

	contextMenuOrder: 1.5,

	// Method that will be executed when the action is triggered.
	// @param editor The editor instance is passed in as a convenience
	run: function (ed) {
		alert("i'm running => " + ed.getPosition());
	},
});
```

### Reproduction Steps

Not reproducible

### Actual (Problematic) Behavior

When I use `monaco.KeyMod.CtrlCmd`, my browser (Chrome on Mac OS) registers the `control` key, not the `command` key. You can even see it when I right click, opening up the command palette.

<img width="300" alt="Screenshot 2024-02-16 at 4 34 25 PM" src="https://github.com/microsoft/monaco-editor/assets/723099/3bb23e3b-738e-4689-89b9-3b3e82bb6767">

Contrast this with the command palette for the same code in the Monaco Editor Playground.

<img width="287" alt="Screenshot 2024-02-16 at 4 34 36 PM" src="https://github.com/microsoft/monaco-editor/assets/723099/cfd93e61-4231-4260-88ef-04149ae56c13">

This is weird because the same code worked for me a month ago. (I did upgrade monaco editor from 45.0 to 46.0, but even after downgrading, the issue persists.)

_However_ I figured out that if I change `monaco.KeyMod.CtrlCmd` to `monaco.KeyMod.WinCtrl`, the Command key works (but the key label is incorrect).

**Note: I can't reproduce the issue in the Monaco Editor Playground**. That leads me to believe it has something to do with my setup (Webpack + ESM).

**Comment by dmnsgn** [comment]
> Note: I can't reproduce the issue in the Monaco Editor Playground. That leads me to believe it has something to do with my setup (Webpack + ESM).

I am getting the same bug. The change in node process detection might be the culprit for our bundling setup: #4378

**Comment by ben519** [comment]
@dmnsgn great catch. I think you're right. I downgraded to 0.45.0 and the key codes work again. Going to close this issue, as #4375 is the one that needs attention.

**Comment by Fabioni** [comment]
Downgrading to 0.45.0 worked for me, thanks for that hint! However I would keep this issue open, since downgrading can't be the solution, right?

**Comment by mike-lischke** [comment]
In what sense is that other bug a duplicate. It does not address this issue here (0.49 still has it) and from the description nobody would expect it has to do with a UI issue. I suggest to reopen this issue here, until the problem is really solved.

**Comment by dmnsgn** [comment]
FYI, looks like it is fixed in v49.
