### ISSUE TITLE
Two hover messages displayed when hovering between two tokens (adjacent decorations)

### ISSUE THREAD

**Issue by JeanPerriault** [microsoft/monaco-editor#4393]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript
var jsCode = [
	'"use strict";',
	"function Person(age) {",
	"	if (age) {",
	"		this.age = age;",
	"	}",
	"}",
	"Person.prototype.getAge=function () {",
	"	return this.age;",
	"};",
].join("\n");

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript",
});

var decorations = editor.createDecorationsCollection([
	{
		range: new monaco.Range(3, 1, 5, 1),
		options: {
			isWholeLine: true,
			linesDecorationsClassName: "myLineDecoration",
		},
	},
	{
		range: new monaco.Range(7, 1, 7, 24),
		options: { hoverMessage: { value: 'TEST' } },
	},
	{
		range: new monaco.Range(7, 24, 7, 25),
		options: { hoverMessage: { value: 'TEST22' } },
	},
]);
```

### Reproduction Steps

Hover between two tokens line 7 character 24. Both adjacent decoration messages are displayed.

![Screenshot 2024-02-10 at 23 38 43](https://github.com/microsoft/monaco-editor/assets/435856/7e8b1772-f826-4f1b-9c3b-a0ba6c4b5b0b)

**Comment by rzhao271** [comment]
The issue seems to be resolved in the latest stable version of Monaco editor.
