### ISSUE TITLE
How to highlight a range/selection in the editor

### ISSUE THREAD

**Issue by waywaaard** [Microsoft/monaco-editor#44]
I want to highlight a specific range/selection within the editor with a special background color. Is this currently supported?

For examples does the diff editor highlight lines. I want to highlight only a range/selection and not a complete line.

**Comment by waywaaard** [comment]
Solution: https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations

**Comment by Symbolk** [comment]
@ebertmi @ebertmi Hi, I want to highlight conflict blocks like VSCode does, do you know how to do it? 
https://stackoverflow.com/questions/57246356/how-to-highlight-merge-conflict-blocks-in-monaco-editor-like-vscode
