### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by ragnard** [Microsoft/monaco-editor#441]
How are monaco-editor releases planned and scheduled? Is there any public information on roadmap and release planning?

Asking because I'm affected by a number of bugs fixed in vscode, and I'm wondering when I can expect a new monaco-editor release where they are included.

Great project by the way, best embeddable JS text editor I've found and I've tried a few.

**Comment by ryanlin1986** [comment]
Curious for me too

**Comment by jacobyf** [comment]
The version v0.8.3 has beed released for a long long time

**Comment by alexandrudima** [comment]
We are planning to do a release in the ~ next few days/weeks. I'm sorry for the delays, we've been all kept quite busy by vscode.

**Comment by ragnard** [comment]
@alexandrudima Thanks for the reply! To be clear, I'm not asking you make a release ASAP, or release more often in general, just whether it would be possible to provide some more information regarding the intended release schedule and roadmap of monaco. Great work with vscode!

**Comment by mattgodbolt** [comment]
@alexandrudima Thanks so much for the update. I know I was just starting to wonder if Monaco had been abandoned, so I'm super-glad things are still progressing. Thanks for all the hard work!

**Comment by aoto** [comment]
I want a roadmap too, i am plan to use Monaco-editor in my product soon.

**Comment by alexandrudima** [comment]
The editor can always be extracted from VS Code master and it is not that complicated [once you understand what's going on](https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#shipping-a-new-monaco-editor-npm-module). The editor always works on master.

But the trouble with that is that there might be some browser-specific regressions, as we test our daily changes in VS Code (running on Chromium). When we do an official monaco editor release, we go through open issues and try to address them, bring in PRs, and then do a lot of browser-specific testing. Sometimes we tweak some changes to try to keep the API stable or sometimes we need to think how to expose internal changes with new API and what is the migration path.

Depending on things, or the amount of breakage, this might take ~1 week. The trouble is to find a good time to fit in this ~1 week of work. We're trying to do this every ~3 months.

If there's some critical bug coming in, we're doing fix-releases (like e.g. 0.8.3).

If you would like to help, we're happy to take any PRs :heart:

**Comment by alexandrudima** [comment]
Let's track the 0.9.x release in #467
