### ISSUE TITLE
monaco-edito is only 5px tall

### ISSUE THREAD

**Issue by wlLeblanc** [microsoft/monaco-editor#4411]
monaco-edito is only 5px tall

**Comment by paustint** [comment]
If you can provide a reproduction and your code it would make it much easier for people to assist you.

You need to explicitly set the height of the container - looks at the plethora of examples in the codebase: https://github.com/microsoft/monaco-editor/tree/main/samples

**Comment by yymm120** [comment]
same issue.

**Comment by rzhao271** [comment]
\gifPlease
