### ISSUE TITLE
deltaDecorations loss when editor executeEdits

### ISSUE THREAD

**Issue by dandingol03** [microsoft/monaco-editor#442]
Monaco:0.8.3
Browser:chrome
OS: mac
Hi
  there are some deltaDecorations among those modified lines,here is my code:
```js
 editor.executeEdits('danding', [
     { identifier: 'modify' , range: new monaco.Range(
                         component2.loc.start.line, component2.loc.start.column+1,
                         component2.loc.end.line, component2.loc.end.column+1),
                         text:line1, forceMoveMarkers: false }
      ]);
```
  However,deltaDecorations get into a mess,how can i fix this.
  Thanks for your time.

**Comment by alexandrudima** [comment]
I'm not sure what you mean that `deltaDecorations` gets into a mess.

Any decorations that you create will be "live tracked". i.e. they will flow with the text. So, for example if you create a decoration on line 10, and then the user (or you, programatically, via `executeEdits`) modify the buffer, to e.g. insert a new line on line 2, then the decorations will move to line 11.

**Comment by TobiasBreuer** [comment]
Hi @alexandrudima, I'm not sure if what I experience are the same issues as @dandingol03 has, but I'm also struggling with the way `deltaDecorations` are being handled by the editor. Let's assume you start with the following setup (one decoration added in line 3):
![image](https://user-images.githubusercontent.com/17617068/34813307-c345e488-f6a9-11e7-81b3-06e3595a5813.png)
When you now place the cursor on line 2 and hit enter, the result will be as expected:
![image](https://user-images.githubusercontent.com/17617068/34813373-1cb90b80-f6aa-11e7-8bd4-78221a1312d8.png)

The issues are with hitting enter while the cursor is on **line 3** however:
**Issue 1: Decoration not moved when cursor is not in column 1 when hitting enter**
When you place the cursor right in front of `Console...` and hit enter the result will be:
![image](https://user-images.githubusercontent.com/17617068/34813490-783b4a90-f6aa-11e7-9518-e3954f49afe2.png)
i.e. the decoration did not move alongside with the code.

**Issue 2: Decoration duplicated when cursor is on column 1 when hitting enter**
In contrast, when you place the cursor on **column 1** in **line 3** the decoration will be duplicated?!
![image](https://user-images.githubusercontent.com/17617068/34813576-bfb01bb2-f6aa-11e7-87d2-8ea2e50c9b3e.png)

In my code I'm only handling the `deltaDecorations` within the mouse down event of the editor. So the shown behavior seems to be within the editor itself (however within VS-Code I cannot reproduce this behavior).
But in fact, the same behavior can be seen within the demo of the playground at [Rendering glyphs in the margin](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin)

Any advice how to handle this issue?

**Comment by akosyakov** [comment]
@TobiasBreuer you should configure decorations stickiness, e.g. `stickiness: monaco.editor.TrackedRangeStickiness.NeverGrowsWhenTypingAtEdges`

**Comment by TobiasBreuer** [comment]
@akosyakov Thanks for the quick reply. This indeed solves issues number 2. Now only issue number 1 remains to be a problem.

**Comment by akosyakov** [comment]
@TobiasBreuer try the following in the playground:
```ts
const column = editor.getModel().getLineFirstNonWhitespaceColumn(3);
var decorations = editor.deltaDecorations([], [
	{
		range: new monaco.Range(3, column, 3, column + 1),
		options: {
			isWholeLine: true,
			className: 'myContentClass',
			glyphMarginClassName: 'myGlyphMarginClass',
            stickiness: monaco.editor.TrackedRangeStickiness.NeverGrowsWhenTypingAtEdges
		}
	}
]);
```

It should behaves exactly as in VS code.

**Comment by TobiasBreuer** [comment]
:bulb: Now I got it.  
My problem was in fact, that I didn't realize that the column parameter of the range property is actually important also for setting breakpoints. As the glyph margin when clicked always reveals a value of 1 for the column in the targets location property of the event, I ignored it completely and always set the range to have a start and end-column of 1.   
When using the `getLineFirstNonWhitespaceColumn` method to determine the column correctly it now works as expected.

Old code (broken):  
```javascript
newDecorations.push({
    range: new monaco.Range(line, 1, line, 1),
    options: this.breakpointDecorationOptions
});
```
New code (working):  

```javascript
const column = this.editor.getModel().getLineFirstNonWhitespaceColumn(line);
newDecorations.push({
    range: new monaco.Range(line, column, line, column),
    options: this.breakpointDecorationOptions
});
```
Thank you very much @akosyakov for your help!

**Comment by neoncom** [comment]
@akosyakov does not work.

steps to reproduce:
1. goto https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin
2. replace decorations with your example
3. click run
4. delete "if (age) {" (do not just overwrite it)
5. type something new
6. press return

expected result: breakpoint does not move
actual result: breakpoint moves :(

visual studio code does not show this behavior.

any ideas?

**Comment by alexandrudima** [comment]
The good news is that vscode is open source and the sources can be used as reference. Here are the options used by breakpoints in VS Code: https://github.com/Microsoft/vscode/blob/93028e44ea7752bd53e2471051acbe6362e157e9/src/vs/workbench/parts/debug/browser/debugEditorModelManager.ts#L280
