### ISSUE TITLE
Malformed completion item can cause browser to freeze

### ISSUE THREAD

**Issue by JKillian** [Microsoft/monaco-editor#448]
monaco-editor version: 0.8.2
Browser: Chrome58
OS: macOS Sierra

We had a `CompletionItemKind` returned by a `provideCompletionItems` that looked like this:

```
{
    label: "config",
    kind: monaco.languages.CompletionItemKind.Function,
    detail: "Configuration settings",
    insertText: [
        "config {",
        '    profile: "{{profileName}}"',
        '    strategy: "{{strategyName}"',
        "}",
    ].join("\n"),
}
```

When a user hits enter to accept this autocomplete suggestion, the whole browser would freeze/hang permanently. This was caused by the missing `}` after `strategyName`.

Not sure why a missing `}` caused this to happen, but wanted to report this issue since we encountered it.

**Comment by jrieken** [comment]
We deleted the code that would interpret {{ and }} as snippet placeholders.

**Comment by JKillian** [comment]
Got it, so in the future we'll have to change the syntax of completion items some? Looks like this is the relevant PR you're referring too: https://github.com/Microsoft/vscode/pull/26042

**Comment by jrieken** [comment]
Yeah, the old syntax was never meant to be used by others. We have documented the real syntax here: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax
