### ISSUE TITLE
[Bug] Trying to fetch loader script get 403/421 cloudflare cdn link is probably broken

### ISSUE THREAD

**Issue by CosmicSpectrum** [microsoft/monaco-editor#4489]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.41.0#example-creating-the-editor-hello-world
version 0.41.0 gets 403 when trying to access the cdn
after testing a bit with other versions I see that all versions under the latest version doesn't work at all

### Reproduction Steps

just try and load the editor.. you get this fetch error

### Actual (Problematic) Behavior

unaccessable editor...

**Comment by Danhiler** [comment]
Seems like the CDN is down

**Comment by CosmicSpectrum** [comment]
I see that jsdelivr status page saying that some systems experiencing some issues... can find any other details.. and especially no ETA for a fix... this is a production issue on my end.. super not fun

**Comment by Danhiler** [comment]
There is temporary solution here:
https://www.reddit.com/r/webdev/comments/1ci43x4/jsdelivr_cdn_is_down/

**Comment by CosmicSpectrum** [comment]
@Danhiler thanks taking a look

**Comment by Danhiler** [comment]
Seems like jsdelivr updated their certificates, it is working well now
