### ISSUE TITLE
How to make a decoration which looks like a cursor in the editor?

### ISSUE THREAD

**Issue by dandingol03** [Microsoft/monaco-editor#454]
hi,team.
i am writing a prototype tool which could allow user to drag code into the editor. Basically,i want to make a decoration which would be updated which user move their mouse.However,there is a problem.when i make a decoration,the decoration will override the character where it is placed .here is my code:
```js
{range: new monaco.Range(7,1,7,2), options: { inlineClassName: 'myInlineDecoration' }}
```
i want to place the decoration between the column-1 and column-2,how can i implement that.
thanks for your time.

**Comment by dandingol03** [comment]
yeah ,

**Comment by alexandrudima** [comment]
Here is an example - https://github.com/Microsoft/monaco-editor/issues/366#issuecomment-307024628
