### ISSUE TITLE
BUG: ReferenceError: event is not defined - Firefox error when trying to click autocomplete menu item.

### ISSUE THREAD

**Issue by aarinsmith** [microsoft/monaco-editor#456]
monaco-editor version: 0.8.2
Browser: Firefox Developer Edition 54.0b12 (64-bit)
OS: Mac OSX Sierra 10.12.1

Type in editor to display autocomplete menu. Click an item to select for autocompletion insert:

Expected output (functionality as in Chrome 58):
Word is autocompleted and inserted at the cursor, autocomplete menu is closed.

Actual output:
Autocomplete menu disappears and word is not inserted. The following error is displayed in the console.

![image](https://cloud.githubusercontent.com/assets/5971758/26748392/3b0fc4ae-47b2-11e7-96c1-1ab9d1c88778.png)

**Comment by aarinsmith** [comment]
Any updates on progress of this bug??

**Comment by rebornix** [comment]
@aarinsmith can you still reproduce this? I tried on Firefox 60 but didn't reproduce, maybe a detailed reproduce steps can help me troubleshoot.
