### ISSUE TITLE
[Bug] "browser-esm-vite-react" code sample not working with monaco-editor v0.49.0

### ISSUE THREAD

**Issue by scebotari66** [microsoft/monaco-editor#4561]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

Try to start https://github.com/microsoft/monaco-editor/tree/c49fdf9f0c131909ca1b661ca3ff4113c42f1c09/samples/browser-esm-vite-react code sample with monaco-editor v0.49.0 (there is ^0.32.0 version specified)

### Actual (Problematic) Behavior

Error in console when trying to run `npm run dev`
![image](https://github.com/microsoft/monaco-editor/assets/329976/7ebc6bcd-e06f-4b4c-8ad0-15f3da11fd50)

### Expected Behavior

`npm run dev` to start the dev server

**Comment by qirong77** [comment]
Updating VITE to a more recent version, such as 5.0, can resolve this issue.

**Comment by scebotari66** [comment]
Indeed! Thanks, @qirong77
