### ISSUE TITLE
How can i get notified when the content has been undo to origin value 

### ISSUE THREAD

**Issue by dandingol03** [Microsoft/monaco-editor#457]
monaco-editor version: 0.8.3
Browser: chrome
OS: mac
Scenario:

1.  the user types something,and use ctrl+z to do undo operation
2. the user may recover the content to the origin one.
3. i register the onDidChangeContent callback to get the content-change event

However,i cannot get the information about the content whether it has been recovered to origin value.

**Comment by alexandrudima** [comment]
There is [`model.getAlternativeVersionId()`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#getalternativeversionid):
> Get the alternative version id of the model. This alternative version id is not always incremented, it will return the same values in the case of undo-redo.

So to implement a dirty indicator for example:
* initialize `lastSavedVersionId = model.getAlternativeVersionId()`
* when the user saves, save the file and record `lastSavedVersionId = model.getAlternativeVersionId()`
* when the content changes (`model.onDidChangeContent(...)`), you can determine `fileIsDirty = (lastSavedVersionId !== model.getAlternativeVersionId())`
