### ISSUE TITLE
Is there any way to load code from a url or a local path on disk?

### ISSUE THREAD

**Issue by jacobsologub** [Microsoft/monaco-editor#459]
I'm embedding the editor in a MacOS native app. Everything is working well except when trying to set text that has "\n" characters. I'm a little lost as to how to go about this since I only see one way to set text using `setValue()`

https://cl.ly/0H0J280G2y2B

```js
const _code = `
//  cues.js

var cues = function() {

    const _cues = [
        "CUE \n ONE",
        "CUE \n TWO",
        "CUE \n THREE"
    ];

    return _cues;
}`;

window.editor.setValue (_code);

```

**Comment by alexandrudima** [comment]
In this specific example, `\n` will be interpreted by the JavaScript runtime as a line break. So to get literally the characters `\` and `n` in the editor you need to escape them. e.g.:

```js
const _code = `
//  cues.js

var cues = function() {

    const _cues = [
        "CUE \\n ONE",
        "CUE \\n TWO",
        "CUE \\n THREE"
    ];

    return _cues;
}`;

window.editor.setValue (_code);

```

I don't think this is a monaco editor issue, the same happens if `console.log(_code)` is used.

**Comment by jacobsologub** [comment]
right. thanks @alexandrudima , got it all sorted now.
