### ISSUE TITLE
not loading dev editor - only min version

### ISSUE THREAD

**Issue by mbana** [Microsoft/monaco-editor#46]
these lines aren't correct - please correct me if I am wrong.
can we possibly just default to the dev version - i am assuming anyone wanting to run monaco well be a dev anyway? not sure.
cheers

---

open http://localhost:8080/monaco-editor/test/?monaco-typescript=dev

`window.location.search = "?monaco-typescript=dev"
`
```
function loadDevEditor() {
	return (getQueryStringValue('editor') === 'dev');
}

function getQueryStringValue (key) {
	return unescape(window.location.search.replace(new RegExp("^(?:.*[&\\?]" + escape(key).replace(/[\.\+\*]/g, "\\$&") + "(?:\\=([^&]*))?)?.*$", "i"), "$1"));
}
```

**Comment by alexandrudima** [comment]
Added controls to the test page:

![image](https://cloud.githubusercontent.com/assets/5047891/18026788/e1a1ad10-6c51-11e6-82c7-f9265e689463.png)
