### ISSUE TITLE
Error reporting issue

### ISSUE THREAD

**Issue by bolismauro** [Microsoft/monaco-editor#462]
monaco-editor version: HEAD
Browser: Chrome (any)

----------

I'm typing the following snippet of code in monaco, expecting an error
```
declare interface A {}

declare interface B {
	test(a: A)
}

let test: B

test.test(1)
```

but the editor doesn't show any error. I can't figure out why and if I'm doing something wrong..

This is the source code of the page

```
	require.config({ paths: { 'vs': 'node_modules/monaco-editor/release/min/vs' }});
	
	require(['vs/editor/editor.main'], function() {
		monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
				noSemanticValidation: false,
				noSyntaxValidation: false
		});

		window.editor = monaco.editor.create(document.getElementById('container'), {
			value: [
				///source code as above
			].join('\n'),
			language: 'typescript'
		});		
	});
```

Note that the hint in the autocompletion is correct..

**Comment by bolismauro** [comment]
I discovered that this "problem" (I'm not sure anymore) is reproducible also in other environments.

A workaround is to add a variable/function to "A". This solves the issue.

Should I open an issue in typescript or is this behaviour intended?

**Comment by alexandrudima** [comment]
I think this is how TypeScript works. TypeScript uses structural typing and by declaring `interface A` with no members it means that there are no constraints from something to be of type `A`. Therefore, anything is of type `A`, including a number, such as `1`.
