### ISSUE TITLE
[Bug] 0.51.0 only: Could not create web worker

### ISSUE THREAD

**Issue by AndersMad** [microsoft/monaco-editor#4647]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Reproduction Steps

If I update from `0.50.0` to `0.51.0-rc2` I get these errors:

```
simpleWorker.ts:36 
 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
simpleWorker.ts:38 
 Uncaught SyntaxError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL './node_modules/monaco-editor/dev/vs/base/worker/workerMain.js#css' is invalid.
simpleWorker.ts:38 
 Uncaught SyntaxError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL './node_modules/monaco-editor/dev/vs/base/worker/workerMain.js#editorWorkerService' is invalid.
...
 ```

Downgrade and it works again.
Using requirejs as loader - everything has worked fine for years.

I know its RC - just a heads up.

**Comment by AndersMad** [comment]
now also in `0.51.0`

**Comment by EdiWang** [comment]
This is also happening on the monaco editor official website:

![image](https://github.com/user-attachments/assets/72b65930-9e35-45e0-806e-eff1926259fc)

**Comment by realwugang** [comment]
try like this
`import EditorWorker from  worker-loader?inline=no-fallback!./node_modules/monaco-editor/esm/vs/editor/editor.worker`

**Comment by mattgodbolt** [comment]
We're seeing this in the released version too (0.52.0), but only on `diffEditor`s

**Comment by AndersMad** [comment]
in v0.52 this has been fixed if you use absolute paths: `requirejs.config({ paths: { "vs": window.location.origin + "/scripts/modelyn-editor/vs" ..` (I am using requirejs) and @mattgodbolt I also tested the diff and that works fine.

**Comment by mattgodbolt** [comment]
@AndersMad we're using `webpack`; any advice on that welcomed.
