### ISSUE TITLE
[Bug]. Accessibility. Alt+f1 shortcut doesn't trigger accessibility help dialogue.

### ISSUE THREAD

**Issue by sevapopov2** [microsoft/monaco-editor#4656]
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/

### Monaco Editor Playground Code

```typescript
Not applicable.
```

### Reproduction Steps

Preconditions:
Screenreader enabled.

Steps to reproduce:
1. Open the link with editor provided above.
2. Enter the edit field. Focus mode will be enabled.
3. Press Alt+f1 shortcut.

### Actual (Problematic) Behavior

Nothing happens when pressing alt+f1 in editor while screenreader's focus mode is enabled.

### Expected Behavior

Accessibility help dialogue opens as described in [Monaco's accessibility guide](https://github.com/microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide).

### Additional Context

Reproduced on:
NVDA v2024.3 (2024.3.0.33433)
Windows 11, 64 Bit.
Google chrome v128.0.6613.85 (Official build), (64 бит).

**Comment by meganrogge** [comment]
No, it does not support alt+f1. Updated docs, thanks @rzhao271
