### ISSUE TITLE
How do you change the function of "TAB" key

### ISSUE THREAD

**Issue by ee-** [Microsoft/monaco-editor#466]
Instead of inserting the `whitespace`, I want it to insert a `horizontal tab` or `\t`.
I have checked `interface IEditorOptions`, but I didn't find anything useful there other than "tabSzie".

Thanks.

**Comment by alexandrudima** [comment]
`editor.getModel().updateOptions({ insertSpaces: false, tabSize: 4 })`.

**Comment by ee-** [comment]
Thanks!
