### ISSUE TITLE
[Bug] 中文字符输入，特定情况下会闪烁。

### ISSUE THREAD

**Issue by tingjiangcao** [microsoft/monaco-editor#4671]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

很明确，挺严重的问题。为什么一点反应没有啊：
https://github.com/microsoft/monaco-editor/issues/4602
https://github.com/microsoft/monaco-editor/issues/4592

这已经是我提出这个问题的第三次了。文字描述、图片描述、视频，都有。
线上也一堆知名产品有这个bug。搞得我都怀疑，是不是就我一个人能看到这个bug。

描述：
一行长代码或注释，横向滚动条拖到最后，光标任意位置，输入文字，字符会跳动。vscode没问题。

**Comment by troy351** [comment]
试了下原文足够长就行，不一定要是中文。应该是由于输入法composition事件没有特殊处理导致的。
---
@aiday-mar Could you please take a look at this issue, it looks like similar to microsoft/vscode#211856

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/monaco-editor/issues/4592
