### ISSUE TITLE
How may I add HIVE intellisense?

### ISSUE THREAD

**Issue by zanecat** [Microsoft/monaco-editor#468]
Hi Monaco team,

Thanks for the fabulous editor.
May I ask if I want to implement an online editor for HIVE(actually SQL) with intelli sense (regarding to the DB structure) and syntax check, what should I do first? Just want to get some ideas, thanks!

**Comment by alexandrudima** [comment]
You can use the APIs the editor provides to register "smartness" providers.

There are some examples for specific providers:
 * [completion provider](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example)
 * [hover provider](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example)
 * our built-in languages use the same APIs e.g. [TypeScript/Javascript](https://github.com/Microsoft/monaco-typescript/blob/9b5c885b40c385b726f70627c7957c2e1436aa0e/src/mode.ts#L67)

The principle is very simple. The UI will adopt to reflect the existing providers for a certain language. For example Find all references is not shown in context menus if the language does not have a definition provider, etc.

**Comment by zanecat** [comment]
Thanks that helps a lot!
