### ISSUE TITLE
location of the typings file is not listed in the package.json / not named index.d.ts

### ISSUE THREAD

**Issue by NatashaOS** [Microsoft/monaco-editor#47]

**Comment by danistrebel** [comment]
as an intermediate workaround you could add this to your `typings.json` file:

```json
{
  "globalDependencies": {
    "monaco-editor": "github:Microsoft/monaco-typescript/src/monaco.d.ts#73295879a4048dcebf585f320f0a3034cf35b131"
  }
}
```

**Comment by shzhng** [comment]
Is this as simply fixed as adding the `"typings"` field into the `package.json`?
https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by NatashaOS** [comment]
Yep that's one way to fix it :)

Natasha
