### ISSUE TITLE
`monaco.languages.html.handlebarDefaults` and `monaco.languages.html.razorDefaults` are swapped

### ISSUE THREAD

**Issue by CnSimonChan** [Microsoft/monaco-editor#470]
monaco-editor version: 0.8.3
Browser: Electron 1.6.11 x64
OS: Windows 10 x64

At [monaco-html/src/monaco.contribution.ts#L88-L89](https://github.com/Microsoft/monaco-html/blob/f1b96cadd5996161d6caaa3dfdf7c39b381053e8/src/monaco.contribution.ts#L88-L89), you have assigned `handlebarDefaults` to `monaco.languages.html.razorDefaults` and `razorDefaults` to `monaco.languages.html.handlebarDefaults`.

I found this when I was researching a workaround to Microsoft/monaco-html#3, finally I set the `language` of `editor` to `handlebars` to get rid of Angular suggestions I didn't need.

**Comment by aeschli** [comment]
Thanks for catching this!
