### ISSUE TITLE
how to implement  full-scope search ,i just need a idea

### ISSUE THREAD

**Issue by dandingol03** [microsoft/monaco-editor#473]
Hi
  recently,i write a prototype-design tool ,and i integrate monaco-editor to it.
  However,i need a function which can help user to find places in project directory which match search-text.
  thanks for your time.

**Comment by alexandrudima** [comment]
There is [`IModel.findMatches'](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.imodel.html#findMatches)
