### ISSUE TITLE
[Bug] onDidCompositionStart and onDidCompositionEnd all not work

### ISSUE THREAD

**Issue by carly1987** [microsoft/monaco-editor#4756]
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.52.0#XQAAAALcAQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw0HLKUEChknxTyhsOtw_oZuoS-bntDRvUjkOwcRtcHNwKoOpD9hqF1FLGw7nCYILel2Pa8v_zJ3fSGF5dVzmbj45xm9DS0quUH1uxuaQU24y-oAP3vtx5M3HalpxMzXI2y1eGEyRt5HKHPqfiOzW11I7ogt2fw-2rKRw6yTv4W3f7jX5s0pQNBMs-Pv8eG9wBi258C1v91Lugaj0nCHgFusOpjMH0mhTNiVMNj3wx71Q62ADaTXMrjnG5_9Irg8GSe341YKZJ2wrOk2zz-SueEwjYj5zLdk_H96tiyJq_A_bHoo0g41bZADxo4uvor8llAZ0ofiOXHss0iBf3hVaJdTvaaOzGc4w583AivT0MBNNBcRRe_2jGqAA

### Monaco Editor Playground Code

```typescript
const myEditor = monaco.editor.create(document.getElementById("container"), {
	value,
	language: "javascript",
	automaticLayout: true,
});

myEditor.onDidCompositionStart(() => {
	alert('start')
})

myEditor.onDidCompositionEnd(() => {
	alert('end')
})
```

**Comment by rzhao271** [comment]
The event handlers work for me using Microsoft Pinyin IME on Microsoft Edge on Windows.
I believe that the event handlers are for IME composition. Did you try using an IME, and if so, which?
