### ISSUE TITLE
Unable to properly type or delete text when using monaco on Android

### ISSUE THREAD

**Issue by rymate1234** [microsoft/monaco-editor#48]
Hopefully this is the right place for this issue.

I'm having trouble using this editor on Android mobile devices - I am unable to type or delete text when using the on screen keyboard. This is within the Chrome browser on Android 6.0. 

This issue does not occur on my Lumia 435 I have for WP development.

Attached is a gif demonstrating the issue on the monaco editor homepage: [Link](https://cloud.githubusercontent.com/assets/581104/16561055/fdadca80-41ee-11e6-9b77-1d32ac1770d2.gif)

**Comment by smellai** [comment]
Yes typing is not working on Android, seems working on mobile iOS but just in landscape mode, in portrait mode the editor is not displayed at all
![image](https://cloud.githubusercontent.com/assets/1763268/18474338/e10e47c8-79c1-11e6-80b9-61a3a3ad8d80.png)

**Comment by tarr11** [comment]
It seems to display now in Android Chrome, but it is not consistently correctly displaying keystrokes. 

 Hard to say but it seems related to the jntellisense?  

If you immediately start typing numbers, it works.
Once you type a letter, it seems to start losing keystrokes.

**Comment by baguio** [comment]
MakeCode version of Monaco seems to have fixed this. It works on the live demo site

**Comment by Pictor13** [comment]
In the playground the behaviour is still buggy and blocking, on Android devices.

Try at:
https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-multi-line-example

Tested on Chrome over Android 7:
the backspace key doesn't sort any effect; no character is deleted.

Any info or update about this?

**Comment by alexdima** [comment]
We would love to get a PR to fix this. Unfortunately I am not in possession of an Android device, so I cannot investigate this.

**Comment by seanpoulter** [comment]
There's a little bit of overhead to get Android Studio and an emulator set up, but no physical device shouldn't be a barrier. I can confirm that we can reproduce in a virtual device. I'm happy to trade notes if it'll help. I don't much capacity to investigate myself though. :/

<img width="514" alt="Screen Shot 2020-09-17 at 08 31 23" src="https://user-images.githubusercontent.com/2585460/93470703-4ef04580-f8c0-11ea-83b1-6b84592254f5.png">
