### ISSUE TITLE
tooltips are 

### ISSUE THREAD

**Issue by Spongman** [Microsoft/monaco-editor#480]
monaco-editor version: 0.8.3
Browser: chrome 58
OS: linux/windows
Steps or JS usage snippet reproducing the issue:

when hovering over symbols near the right edge of the editor, the tooltips are being shrunk horizontally resulting in unreadable text.

![image](https://user-images.githubusercontent.com/1088194/27527074-b32af2c0-59fe-11e7-9cb6-0b7420194dec.png)

there needs to be a way to specify which container should be used to size the overflowingContentWidgets, so that those widgets can expand comfortably into any additional space on the page surrounding the editor.

there's no problem with overflow  in this example (unlike with the playground). see, the context menu displays correctly:

![image](https://user-images.githubusercontent.com/1088194/27527121-de6decee-59fe-11e7-876b-2d3e74dbfbcc.png)

**Comment by alexandrudima** [comment]
You can try the option `fixedOverflowWidgets: true`.

**Comment by Spongman** [comment]
thanks, that's much better!

**Comment by pinksky** [comment]
Great! This option helped to solve my two problems about hover and contextMenu.
