### ISSUE TITLE
Narrator is not reading suggest-widget pop up items

### ISSUE THREAD

**Issue by Micbu** [Microsoft/monaco-editor#481]
monaco-editor version: 0.7.3
Browser: Edge
OS: Win 10

Same issue does not exist with FF + NVDA
Steps or JS usage snippet reproducing the issue:
1. Type a char in editor which opens suggest-widget
2. Move between the suggestions via keyboard
**Current behavior:**
Narrator reads "down arrow"
**Expected behavior:**
Narrator should read the suggestions items content

**Comment by galyech** [comment]
I just integrated the new version, 0.9.0.
There is an issue with this fix, sometimes it reads "end of line" instead of the suggestion while pressing down-arrow to navigate the list.
Moving to another element (down-arrow key) , and returning back to the element (up-arrow key) reads it properly.

**Comment by alexandrudima** [comment]
@galyech May I kindly point out that you please read https://github.com/Microsoft/monaco-editor/wiki/Accessibility-Guide-for-Integrators

which links to https://github.com/Microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide

In there, it is explained that:

<img width="723" alt="screen shot 2017-07-06 at 08 31 05" src="https://user-images.githubusercontent.com/5047891/27898282-93ff1c1c-6225-11e7-8d69-36594791156a.png">

Have you tried using `ctrl+up` and `ctrl+down` ?
