### ISSUE TITLE
Screen reader is not informing menu appears on Query editor

### ISSUE THREAD

**Issue by Micbu** [Microsoft/monaco-editor#482]
monaco-editor version: 0.7.3
Browser: Edge
OS: Win10
Steps or JS usage snippet reproducing the issue:
1. Type in Editor.
2.  press Right click or context menu inside the query editor to activate the context menu
**Actual Behavior:**
Screen reader is not informing context menu appears on query editor after pressing context menu button. It is reading some page information

**Expected Behavior:**
Screen reader should read context menu appears on query editor after pressing context menu button

**Comment by alexandrudima** [comment]
This works for me as expected on master. 

Once the Screen Reader is silent on an editor (hint: press Ctrl after focusing in if you are not patient for it to read the current page of text), when I invoke the context menu, the first focused item is called out, on a TS file, "Go to Definition menu item" is read when opening the context menu.
