### ISSUE TITLE
Using monaco-editor in web components (Polymer).

### ISSUE THREAD

**Issue by grunenwflorian** [Microsoft/monaco-editor#483]
monaco-editor version: 0.8.3
Browser: Chrome 59
OS: macOS

**Type : vscode Feature**

It is currently impossible to use monaco-editor in polymer web components. The reason is that the rendering is prevented by a check on the presence of the container in the DOM.

line 400: vs/editor/view/viewImpl.ts
```javascript
private _actualRender(): void {
		if (!dom.isInDOM(this.domNode.domNode)) {
			return;
		}
               /*...*/
  }
```
When meeting a shadow root isInDOM returns false, this function should look like this.

line 49 : vs/base/browser/dom.ts
```javascript
export function isInDOM(node: Node): boolean {
	while (node) {
		if (node === document.body) {
			return true;
		} else if (node.host == null) {
			node = node.parentNode;
		} else {
                        // it's a polymer element
			node = node.host;
		}
	}
	return false;
}
```

Even with this modification there are still some rendering issues (no style colorization ...), probably caused by the strict way polymer isolate css rules.

You can find a small polymer project (obviously not working) using monaco editor [*here*](https://github.com/grunenwflorian/monaco-web-components).

I intend to submit a PR to, at least, allow the rendering. Feel free to comment or suggest proper ways to do that.

**Comment by paresy** [comment]
Have a look at my comment. Shadow DOM support is completely broken for all browsers: https://github.com/Microsoft/monaco-editor/issues/308#issuecomment-284389162
