### ISSUE TITLE
Typescript worker is loaded from "wrong" path

### ISSUE THREAD

**Issue by ddelbondio** [microsoft/monaco-editor#487]
monaco-editor version: 0.8.3
Browser: Firefox
OS: OSX

When configuring the loader to map `vs` to a path which does not end in `vs`, loading of `vs/language/typescript/src/worker.js` fails, since it always replaces the last part of the base path it loads from with `vs`

Easy reproducable with following example:
```javascript
require.config({ paths: { 'vs': '/static/monaco-editor' }});
require(['vs/editor/editor.main'], function() {
  var editor = monaco.editor.create(document.getElementById('container'), {
    value: '',
    lannguage: 'javascript'
  });
});
```
it should load `/static/monaco-editor/language/typescript/src/worker.js`, but instead tries to load `/static/vs/language/typescript/src/worker.js`

**Comment by andyg8180** [comment]
i ran into this same issue when i upgraded from 0.8.1 to 0.8.3.

**Comment by taicho** [comment]
I'm now running into this as well. Any easy workarounds either of you have found besides downgrading before I dig in to it?

**Comment by ddelbondio** [comment]
@taicho: If the base path ends with `vs` it works.

**Comment by rebornix** [comment]
TypeScript Language Service is running in a web worker and we don't honor `paths` or `baseUrl` config in that worker, see here https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/worker/simpleWorker.ts#L343...L346 .

Then it's based on relative path, which is `../../../` in your case, resolving module `vs/language/typescript/src/worker` will get `static/vs/language/typescript/src/worker` finally. @ddelbondio already provides a good workaround for this.
