### ISSUE TITLE
Space key creates a new line on key press.

### ISSUE THREAD

**Issue by arjunraj1523** [microsoft/monaco-editor#488]
Hi,
While I was initially working with Monaco it worked fine, but recently, after I upgraded chrome and I have noticed that every time i press the "Space" key, it creates/moves the cursor by one position (expected). but also invokes a new line key press. I've tried downgrading chrome, updating/downgrading Monaco, but this error persists. Also this issue is limited to the chrome browser, I have tested it out on Firefox and IE and Edge. 
Eg:
```
Function 
                test()
```
This is how it creates a function while i'm typing it. 
After stepping through the code, I was able to find something odd, that space key code is 10, which turns out to be the ASCII code for a New Line Char. This may be interfering with my application and causing it to break. It would be really great if you guys could look into this issue as this seems to a very severe bug and make the editor rather unusable.

**Comment by alexandrudima** [comment]
@arjun-raj1523  I cannot reproduce.

Here I try typing spaces at https://microsoft.github.io/monaco-editor/

![spaces](https://user-images.githubusercontent.com/5047891/27735523-5de937e0-5da0-11e7-8411-b8e3fa0778ae.gif)

I am trying with Chrome v59.0.3071.115 on Windows 10. Is it possible there is something special on your machine? Have you tried on a different machine? Do you use software that would typically interfere with typing e.g. AutoHotKey. Do you use a specific keyboard layout where you use composition that triggers this issue?

**Comment by winduptoy** [comment]
We had the same problem. Make sure you don't have any `white-space` CSS targeting a `textarea`. For us, `textarea { white-space: normal; }` was causing this behavior.
