### ISSUE TITLE
Do we have a logo?

### ISSUE THREAD

**Issue by raghav710** [microsoft/monaco-editor#491]
Hi
Thanks for the monaco editor experience :) Looking at the website and the github repo, I wasn't able to find any logo for the monaco editor. Do we have a logo already? If no, do any of the following look interesting? (Done using MS Paint, in case we're open to it, we could have a logo contributing event to get more creative inputs!)
![image](https://user-images.githubusercontent.com/6886543/27840252-1b9b3190-6115-11e7-9cbb-5f8152b42d29.png)

**Comment by raghav710** [comment]
@chrisdias any thoughts on this?

**Comment by hediet** [comment]
Thanks for your suggestions, but we don't have plans to add a logo for the monaco editor.
