### ISSUE TITLE
Languages (js, html, css, ...) are not enabled by default in v0.9.0, how to enable ?

### ISSUE THREAD

**Issue by dengkunli** [Microsoft/monaco-editor#492]
After upgrading to v0.9.0, I found 2 problems: 

1. No language is enabled by default, the result of `monaco.languages.getLanguages()` only returns the plain text. How to enable js, html, css, etc ?

2. `monaco.languages.typescript.javascriptDefaults.addExtraLibs`, `monaco.languages.typescript.javascriptDefaults.setCompileOptions` , `monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions` cannot be used anymore, what is the new way of using it ?

**Comment by alexandrudima** [comment]
@dengkunli I cannot reproduce.

The page at https://microsoft.github.io/monaco-editor/ uses `monaco.languages.getLanguages()` to populate the dropdown of languages: https://github.com/Microsoft/monaco-editor/blob/7d0be081d068668ee64e672c72505f48eca032b7/website/index/index.js#L10 and it works correctly for me.

Also, the page at https://microsoft.github.io/monaco-editor/playground.html uses `monaco.languages.typescript.javascriptDefaults.addExtraLibs` to add to the left hand-side editor all the `monaco.d.ts` such that `monaco.editor.` gets autocompletions. 

Also, the sample at https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults uses the same API to define the `Facts` symbol and that works correctly for me.

Do you have any additional info for me to try to reproduce ?

**Comment by dengkunli** [comment]
So sorry for the bother, it's my mistake, I have used the files in monaco-editor-core, which is incorrect.

Thank you very much for your response. @alexandrudima
