### ISSUE TITLE
[0.9.0] update theme async

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/monaco-editor#493]
monaco-editor version: 0.9.0
Browser: Chrome
OS: OSX
Steps or JS usage snippet reproducing the issue:

With this new release, we're no longer able to call editor.updateOptions with a theme.
Any idea if there's still a way to update the theme dynamically, as we want to load the editor and then update the theme async.

**Comment by alexandrudima** [comment]
Yes. See https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md#090-03072017
<img width="934" alt="screen shot 2017-07-05 at 10 31 27" src="https://user-images.githubusercontent.com/5047891/27856086-2f3b93b8-616d-11e7-80d5-fdf120a26683.png">

For an example, the theme switcher at https://microsoft.github.io/monaco-editor/ changes the theme dynamically: https://github.com/Microsoft/monaco-editor/blob/7d0be081d068668ee64e672c72505f48eca032b7/website/index/index.js#L167

**Comment by microsoftsam** [comment]
Thanks, Alex. I hadn't read too far past the "New & Noteworthy" section in the Change Log :)
