### ISSUE TITLE
completionItemProvider with TextMate snippet syntax

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/monaco-editor#495]
monaco-editor version: 0.9.0
Browser: Chrome
OS: OSx
Steps or JS usage snippet reproducing the issue:

With the removal of the built in snippets support in monaco editor 0.9.0, how would one go about using provideCompletionItems to return a snippet that uses the TextMate syntax? 

For example, I would image this: 
```

// Register a completion item provider for the new language
monaco.languages.registerCompletionItemProvider('mySpecialLanguage', {
	provideCompletionItems: () => {
		return [
			{
				label: 'simpleText',
				kind: monaco.languages.CompletionItemKind.Text
			}, {
				label: 'testing',
				kind: monaco.languages.CompletionItemKind.Keyword,
				insertText:'testing({{condition}})'
			},
			{
				label: 'ifelse',
				kind: monaco.languages.CompletionItemKind.Snippet,
				insertText: [
					'if ({{condition}}) {',
					'\t{{}}',
					'} else {',
					'\t',
					'}'
				].join('\n'),
				documentation: 'If-Else Statement'
			}
		]
	}
});
```

would get converted into: 

```

// Register a completion item provider for the new language
monaco.languages.registerCompletionItemProvider('mySpecialLanguage', {
	provideCompletionItems: () => {
		return [
			{
				label: 'simpleText',
				kind: monaco.languages.CompletionItemKind.Text
			}, {
				label: 'testing',
				kind: monaco.languages.CompletionItemKind.Keyword,
				insertText:'testing(${1:condition})'
			},
			{
				label: 'ifelse',
				kind: monaco.languages.CompletionItemKind.Snippet,
				insertText: [
					'if (${1:condition}) {',
					'\t$0',
					'} else {',
					'\t',
					'}'
				].join('\n'),
				documentation: 'If-Else Statement'
			}
		]
	}
});
```

but throughout my testing, that just inserted the plain text version, without parsing ``insertText`` as a snippet.

It'd be great if you could update the sample at: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

**Comment by microsoftsam** [comment]
Figured out the issue, need to use SnippetString instead of string. 

insertText:
{
value: string
}

The playground example needs updating.

**Comment by microsoftsam** [comment]
PR updating the playground: https://github.com/Microsoft/monaco-editor/pull/497

**Comment by alexandrudima** [comment]
Thank you! I missed updating that sample :heart:
