### ISSUE TITLE
Where is isAutoWhitespaceCommand property in TextOperations._enter function

### ISSUE THREAD

**Issue by powerumc** [Microsoft/monaco-editor#498]
monaco-editor version: 0.9
Browser: Chrome
OS: macOS
Steps or JS usage snippet reproducing the issue:

Monaco Editor 0.8.3 Version's _enter function.
I have been used set false value of isAutoWhitespaceCommand property.
Because I developing ot.js Monaco Editor Adapter and it need false value.

    shouldPushStackElementBefore: true,
    shouldPushStackElementAfter: false,
    isAutoWhitespaceCommand: false

But in the Monaco Editor 0.9 version in _enter function that isAutoWhitespaceCommand property is not exists.

How, where it, Can I change isAutoWhitespaceCommand property value.

**Comment by alexandrudima** [comment]
@powerumc Wouldn't it be cleaner to use `editor.getModel().updateOptions({ trimAutoWhitespace: false })` such that you don't need to patch the source code. You would need to do this for every model instance that you create or that the editor creates on your behalf.
