### ISSUE TITLE
Mouse click on selection 

### ISSUE THREAD

**Issue by galyech** [microsoft/monaco-editor#499]
monaco-editor version: 0.9.0
Browser: Chrome
OS: Windows 10
Steps or JS usage snippet reproducing the issue:
1. Select text (from bottom to top)
2. Verify selected text highlighted in blue color. 
2. Click outside the selection

Expected behavior:
1. The cursor's position should be at the end of the text.
2. Highlight color should be gone.

Actual behavior:
1. Selected text is still highlighted in blue
2. Cursor's position is still at the beginning of the selected text. 

This is happening also in the playground in Chrome. 
It is working properly on Edge. 

* I debugged this issue and found out the event :
 editor.onDidChangeCursorSelection(function(e) {
    console.log(e.selection);
})

 won't fire in Chrome, when the text is selected and I click inside\outside the text.

**Comment by rebornix** [comment]
@galyech we added a new feature called Drag and Drop on selections, which blocks you on seleletion change event in this case

![image](https://user-images.githubusercontent.com/876920/27936767-6080d3fc-6267-11e7-90cb-6c537efad2a0.png)

You can disable it by setting `editor.dragAndDrop` to `false` to have it turned off.

**Comment by joaofernandes** [comment]
shouldn't the D&D behavior be compatible with clicking outside the selection? Many editors know the difference between dragging text selection and clicking outside a selection (and removing the highlight), It seems you can only get one of the 2 behaviors.
