### ISSUE TITLE
The right-pointing mouse pointer is oversized in high DPI

### ISSUE THREAD

**Issue by be5invis** [Microsoft/monaco-editor#5]
![qq 20160621031257](https://cloud.githubusercontent.com/assets/240091/16207140/350e4db0-375e-11e6-835d-9609e7dbe066.jpg)
(I have to take a photo because there is no software can take a correct snapshot)

**Comment by joaomoreno** [comment]
Hehe was coming here to say the same thing: happens on OS X too, retina display.

![2016-06-20](https://cloud.githubusercontent.com/assets/22350/16207693/caf3fb20-372e-11e6-965c-9afd5a8cf71a.jpg)

**Comment by alexandrudima** [comment]
I'm thinking it is caused by https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/lineNumbers/lineNumbers.css#L22 I wonder why we don't see this in vscode too.

**Comment by csinco** [comment]
Wowzers 😅

**Comment by somewhatabstract** [comment]
I was going to try this on my high DPI Windows machine, but I don't even get a right-facing pointer in that scenario. (Using Chrome Version 53.0.2767.4 dev-m (64-bit))

**Comment by Haroenv** [comment]
On Safari (9.1) I get a proper sized pointer on a high dpi screen

**Comment by nikikante** [comment]
It shows big pointer even in normal dpi when zoom is applied. Tested on chrome

**Comment by bpasero** [comment]
@alexandrudima I am still getting this when using a newer electron (with Chrome 51) in VS Code:

![editors](https://cloud.githubusercontent.com/assets/900690/16552286/0ca0d02a-41c0-11e6-902a-83a51c32c7dd.gif)

**Comment by bpasero** [comment]
Ok I think your fix solves this for the standalone editor by just changing the CSS rule to be workbench specific. I will create an issue in VS Code repository.
