### ISSUE TITLE
Avoid usages of `.row` in command palette

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/monaco-editor#500]
Extracted from https://github.com/Microsoft/monaco-editor/issues/496#issuecomment-313557683

The tree no longer uses `.row`, but the command palette internals still uses `.row`.

This is problematic because bootstrap has rules for `.row`. It would be nice if we would avoid using `.row` as a class name.

**Comment by bpasero** [comment]
I assume you meant this usage: https://github.com/Microsoft/vscode/commit/52febdaabe32c25e5eab40e70e3c774431277fe3

**Comment by alexandrudima** [comment]
Nice! :heart:
