### ISSUE TITLE
Description for suggestion 

### ISSUE THREAD

**Issue by galyech** [microsoft/monaco-editor#501]
monaco-editor version: 0.9.0
Browser: Edge, Chrome
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

Hi, 
The suggestion used to have a short description.
How can I enable this in the current version?

![image](https://user-images.githubusercontent.com/29915265/27993320-5ca8a16e-64b1-11e7-86fd-b6293119a2a2.png)

**Comment by CnSimonChan** [comment]
Now the detail will show side-by-side with the suggest list when the user hit `Ctrl` + `Space`, just like vscode.

![image](https://user-images.githubusercontent.com/1330321/28048546-46a18c0e-6624-11e7-9f25-4926998c1ff3.png)

To open it programmatically, you can use

```` ts
(this.editor.getContribution("editor.contrib.suggestController") as any)._widget.expandSuggestionDocs = true;
````

To disable toggling with `Ctrl` + `Space`, you can use

```` ts
Object.defineProperty((this.editor.getContribution("editor.contrib.suggestController") as any)._widget, "expandSuggestionDocs", { get() { return true; } });
````

(though it is some internal things so it may change or fail in future versions)

**Comment by galyech** [comment]
Hi, 
I'm aware of that.
But is there a way to show the description in the same window as before?

**Comment by rebornix** [comment]
cc @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@galyech We no longer show the one line description below the suggestion and there is no option to bring that back
