### ISSUE TITLE
occurrencesHighlight: false

### ISSUE THREAD

**Issue by galyech** [Microsoft/monaco-editor#502]
monaco-editor version: 09.0
Browser: Chrome
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

I set this flag to false in the configuration. AccessibilitySupport is "auto" by default, and still the occurrences are highlighted. 
How can I disable the highlights on occurrences? the flag doesn't help.

**Comment by rebornix** [comment]
`occurrencesHighlight` is used to disable the occurrences highlighting on the scrollbar. To make the occurrences in the editor disappear, you may want to set `selectionHighlight` to `false` as well.

Close it first as I played with two options and both of them work properly. Let me know if you see issues with these two options set.
