### ISSUE TITLE
Missing suggestion in code completion that defined in extra lib

### ISSUE THREAD

**Issue by nico-1986** [microsoft/monaco-editor#503]
monaco-editor version: 0.9
Browser: Chrome/Firefox
OS: Win 7
Steps or JS usage snippet reproducing the issue:

Please do testing from here: [https://jsfiddle.net/updywc7f/4/](https://jsfiddle.net/updywc7f/4/)

**test1.d.ts (extra lib)**
```
type noCodeSuggestionType =
    "noCodeSuggestion1" |
    "noCodeSuggestion2"

interface interfaceA {
    no_code_suggestion?: noCodeSuggestionType
}

interface interfaceB {
    interface_a?: interfaceA
}

interface TEST {
    find_by(attrs: interfaceB): void
    find_by_b(attrs: noCodeSuggestionType): void
}

declare var $test: TEST
```

**codes in monaco-editor**
```
$test.find_by({interface_a: {no_code_suggestion: ""}})
```

**issue**

As you see: 
We have code suggestion for $m.find_by_b
![image](https://user-images.githubusercontent.com/23517611/28053867-50a3c282-6645-11e7-99b9-b0817823290c.png)

But we don't have correct code suggestion for $m.find_by
No code suggestion for "no_code_suggestion". (i.e. Users cannot know available values of noCodeSuggestionType)
![image](https://user-images.githubusercontent.com/23517611/28053821-175a06c6-6645-11e7-98d3-c12972f85196.png)

**Comment by alexandrudima** [comment]
Is this something that works at http://www.typescriptlang.org/play/index.html

If not, one idea would be to open a feature request against the TypeScript language at https://github.com/Microsoft/TypeScript
