### ISSUE TITLE
[?] CompletionItemProvider based on d.ts definitions for other languages

### ISSUE THREAD

**Issue by joaofernandes** [microsoft/monaco-editor#504]
I'm currently evaluating monaco-editor as a code editor for both javascript and vb.net. I've used addExtraLib() to append typescript d.ts definitions so the editor can provide code hinting. It works perfectly for JS but for VB(.NET) as soon I activate language = VB, I get the code coloring but lose the code hinting since it's for Typescript/Javascript.

I'm looking to use the typescript CompletionItemProvider because it already has optimized search and code hinting which recognizes generics, param position in a function call and so on, all based on typed declarations.

Is there anyway to get the engine based on typescript declarations to provide intellisense for other languages?

**Comment by alexandrudima** [comment]
You can fork the project at [`monaco-typescript`](https://github.com/Microsoft/monaco-typescript), as it only uses public API, which you can use too.

If you choose a different language identifier than `typescript`, your fork and the original `monaco-typescript` should work well together. Alternatively, you can look into consuming [`monaco-editor-core`](https://www.npmjs.com/package/monaco-editor-core), which is the monaco editor without any of the languages.

**Comment by osmedd** [comment]
I am looking at providing 'vb' language support to monaco-editor that includes code hinting/intellisense/completion provider functionality.  Forking monaco-typescript is one path, I imagine, but is there a writeup somewhere that has the high level "cookbook" requirements on how to support the features beyond what is provided in a 'basic' language?

**Comment by rcjsuen** [comment]
@osmedd I'm not sure what you are looking for. What is a "basic" language and what are these features you speak of that are "above and beyond"?

If I'm planning to support tooling for a programming language I would probably implement the [language server protocol](https://microsoft.github.io/language-server-protocol/). Many clients (both desktop and browser-based) would then get your features "for free". If you want to hook it up to Monaco you can use TypeFox's [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient/) library.
