### ISSUE TITLE
Find widget input has 0 width in IE11

### ISSUE THREAD

**Issue by RoboPhred** [Microsoft/monaco-editor#505]
monaco-editor version: 0.9.0 / Playground
Browser: Internet Explorer 11.413
OS: Windows 10

Open the monaco playground in IE11, focus editor, hit Ctrl+F.
The input field and associated search mode buttons will be collapsed to zero with.

![monaco-bug-1](https://user-images.githubusercontent.com/6816874/28093807-ec28225e-664d-11e7-971e-16b15478bebd.png)

Playing around with the dev tools, it seems the .monaco-findInput > .monaco-inputbox div has a calculated width of 0px.  Digging deeper, it is configured to be 100% of the width of its parent, findInput, which also has a 0px width.  This is baffling, as IE shows the computed property of the 0px width as being derived from an inline style of "width: 221px".
The issue seems to be related to the flexbox in IE, as disabling the Flex property of the monaco-inputbox element will allow the size to expand.  Interestingly, disabling flex on the parent findInput element is not enough to fix the issue.

**Comment by rebornix** [comment]
@RoboPhred thanks for reporting this issue, nice catch! Flexbox width/height inheritance behaves differently from browsers to browsers.
