### ISSUE TITLE
Adding Extra lib execution to fast for key naming convention

### ISSUE THREAD

**Issue by JohannWNel** [microsoft/monaco-editor#507]
monaco-editor version: 0.9.0
Browser: Google Chrome Version 61.0.3154.0 (Official Build) canary (64-bit)
OS: Windows 10 Enterprise
Steps assume monaco editor is already installed and createEditor has already been called.
Steps or JS usage snippet reproducing the issue:

Load libraries statically:
```typescript
// this._typescriptExtraLibs is used to dispose later
this._typescriptExtraLibs = monaco.languages.typescript.typescriptDefaults.addExtraLib(person.toString());
this._typescriptExtraLibs = monaco.languages.typescript.typescriptDefaults.addExtraLib(animal.toString());
this._typescriptExtraLibs = monaco.languages.typescript.typescriptDefaults.addExtraLib(flee.toString());
this._typescriptExtraLibs = monaco.languages.typescript.typescriptDefaults.addExtraLib(color.toString());
```
**Receive error at:**
line 39, column 1220 (minified script)
**Error:**
Uncaught Error: ts:extralib-1499848020086 already a extra lib
**My conclusion:**
I stepped through the code and notice that due to the way that the keys in the this._extraLibs are generated using the date it has conflicts due to "too fast" processing.

**Comment by rebornix** [comment]
Yes you get the same value from `Date.now()` as it's too fast ... Maybe we can add another `Math.random()` to further reduce the possibility of collision

**Comment by JohannWNel** [comment]
Yes that would relieve this issue, but since that check is executed on the creation and there would be a random value involved i think that check would be redundant, if you wanted to check that the item is not replicated would it not be best to **hash** the lib being added then use that as the key instead, then the duplicate check would be more applicable accurate.

**Comment by JohannWNel** [comment]
@jrieken Is there any progess on this? as currently I have to have some ugly hacks in place to provide properly.

Thanks in advance.

**Comment by dasco144** [comment]
Is there an update on this? I'm getting this issue as well

**Comment by Klustre** [comment]
@jrieken I'm also running into this issue. Is there a fix planned?

@JohannWNel What hacks are you using to make it work?

**Comment by JohannWNel** [comment]
Hi @Klustre 

So I have noticed in their code that when you specify the file name when using that function then they use that as the key of that lib, thus there are no confilcts then, so I used a GUID as file names and works great for me.

I hope this helps.

**Comment by Klustre** [comment]
@JohannWNel That indeed solved it. Thanks a lot!

**Comment by alexandrudima** [comment]
Closing as this will not be fixed.
