### ISSUE TITLE
Extending the Editor-Pane

### ISSUE THREAD

**Issue by fdeitelhoff** [Microsoft/monaco-editor#508]
monaco-editor version: 0.9.0
Browser: Chrome
OS: Windows

This is more a question or maybe a feature request?

Is it possible to extend the Editor-Pane (or whatever it is called where there lines are on)?

For example I want to show a value one line above a variable. So there should be an extra line above that line with this specific variable but this line should not count as a line (respecting line numbers). Is there a way to add those additional lines/information in the Monaco Editor?

I'm aware of those features shown in the playground but could not find any good solution or anchor point I can start at.

**Comment by rebornix** [comment]
You can register a [CodelensProvider](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registercodelensprovider) which allows you add things similar to

![image](https://user-images.githubusercontent.com/876920/28133500-28d03032-66f5-11e7-993d-36d2052c06de.png)

A line doesn't count as part of the document.

**Comment by fdeitelhoff** [comment]
@rebornix Many thanks! Wasn't aware of this feature.

Is there somewhere a minimal example? Of course I'll try to get my own example working. Maybe we can add this to the playground later to rise the awareness of this feature.

**Comment by rebornix** [comment]
@fdeitelhoff here we are https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-codelens-provider-example

**Comment by fdeitelhoff** [comment]
@rebornix That is just super awesome! :)

Many thanks and I owe you something!
