### ISSUE TITLE
Force autocomplete widget to re-render with new data which is an ajax response

### ISSUE THREAD

**Issue by dragfire** [Microsoft/monaco-editor#509]
monaco-editor version: 0.8.3
Browser: Chrome
OS: MacOSX Captain
Steps or JS usage snippet reproducing the issue:

When a dot(`.`) is pressed after a word then an ajax request is made to fetch some data. When the data arrives, I want to show autocomplete widget with the response got from ajax.

An example would be: 
In most SQL editors, when a `.` is pressed after a `table name` then it shows all the `column names` for that particular table name. Fetching `column names` is an ajax request.

Is there anyway that I can re-render autocomplete widget with this new data?

**Comment by rebornix** [comment]
@dragfire Method `provideCompletionItems` of [CompletionItemProvider](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registercompletionitemprovider) can be thenable, which means you can fetch completions from ajax and then resolve the items result.
