### ISSUE TITLE
import in Angular2 Appliaction

### ISSUE THREAD

**Issue by windischb** [microsoft/monaco-editor#51]
Hi!

Has anybody an Idea how to use the Monaco Editor inside of an Angular2 Application??
I can't figure it out how to import the Editor using SystemJS! >.<
Like "import { monaco } from 'monaco-editor/monaco'" or something similar..

Many thanks for every hint or idea!

**Comment by fedoranimus** [comment]
I would like to know this as well - a simple way to use this editor in a modern Typescript application would be prudent.

**Comment by waywaaard** [comment]
see Matthias247  answer here: https://github.com/Microsoft/monaco-editor/issues/18#issuecomment-231788869

**Comment by fedoranimus** [comment]
That's acceptable for Angular, I suppose. I'm looking for something more generic; see [this issue](https://github.com/Microsoft/monaco-editor/issues/60)

**Comment by 0plus1** [comment]
I just created an npm package for an NG2 Monaco editor component: https://github.com/0plus1/ng2-monaco-editor it works and it's ugly. Please feel free to contribute, I will actively develop this component as it's being used in a project.

**Comment by pderks** [comment]
Being able to import monaco into an Angular application would be incredibly helpful instead of having to use the workaround suggested in issue #18 [.](https://github.com/Microsoft/monaco-editor/issues/18)  Will this feature make it into v0.9.0?

**Comment by Renhj90520** [comment]
I'm using it in an angular2+ project, and this is my solution:
import * as monaco from 'monaco-editor';
I get the editor.worker.bundle.js from [](https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack), put it under assets/js folder,
then in the constructor
constructor() {
    (<any>window).MonacoEnvironment = {
      getWorkerUrl: function(modelId, label) {
        return './assets/js/editor.worker.bundle.js';
      }
    };
}
It seems all right, but I don't know whether it's a good solution or not.

**Comment by alexdima** [comment]
There is an angular wrapper at https://github.com/atularen/ngx-monaco-editor

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
