### ISSUE TITLE
Async create monaco-editor

### ISSUE THREAD

**Issue by naturtle** [Microsoft/monaco-editor#511]
monaco-editor version: 0.9.0
Browser:chrome50
OS: win10

I want async create a monaco-editor,but I got this:
 `<div class="monaco-editor vs-dark" style="width: 5px; height: 5px;">`

**Comment by rebornix** [comment]
@naturtle can you provide more info about 

> async create a monaco-editor

Monaco modules can be loaded asynchronously by AMD loader. Not sure if you did it this way.

**Comment by naturtle** [comment]
@rebornix 
The monaco modules is on ready,my case more like that

    function createMonacoEditor(){
        monaco.editor.create(document.body,{
            theme:"vs-dark",
            value: "...",
            language: "html"
        });
    }
    
    createMonacoEditor();//sync,work


    //document.body.onclick=createMonacoEditor;//async
    //setTimeout(createMonacoEditor,1000);//async
    //got this:   <div class="monaco-editor vs-dark" style="width: 5px; height: 5px;">

Thank you for your attention

**Comment by naturtle** [comment]
@rebornix 
可能是我其他js影响了monaco，我在sample项目里改setTimeout是没问题的，回头搞清楚了我再来处理这个帖子

**Comment by naturtle** [comment]
@rebornix 问题不在monaco身上，这问题过了......

**Comment by 0mkara** [comment]
@naturtle could you find why it was happening ?
