### ISSUE TITLE
Curly brackets when typing "" 

### ISSUE THREAD

**Issue by galyech** [Microsoft/monaco-editor#512]
monaco-editor version: 0.9.0
Browser: Edge
OS: Windows 
Steps or JS usage snippet reproducing the issue:

When I press "enter" on suggestion "==" I get  == "{{}}"  
How to disable these curly brackets? 

thanks!

**Comment by rebornix** [comment]
Can you provide some more details about how I can get `==` suggestions?

**Comment by galyech** [comment]
Yes. 
for example:
![curlyexample1](https://user-images.githubusercontent.com/29915265/28207704-577fbf2a-6893-11e7-8954-b0a26c2eccaf.png)

![curlyexample2](https://user-images.githubusercontent.com/29915265/28207709-5b3d819c-6893-11e7-849d-e4ffc90aa4ae.png)
******************************************************************************
another example:
![screenshot 17](https://user-images.githubusercontent.com/29915265/28208303-b59bc534-6895-11e7-9ac7-9ec968f227ea.png)

in older version:
![screenshot 19](https://user-images.githubusercontent.com/29915265/28208348-e1908ba2-6895-11e7-878c-dad7002fc95a.png)


in current version: 
![screenshot 18](https://user-images.githubusercontent.com/29915265/28208349-e2d33ad2-6895-11e7-85e0-85a990b0c8f4.png)



******************************************************************************
In older version of the editor, when I press enter to accept the suggestion:  "==" I got : " =="" " and the cursor would blinking between the quotation marks. 

I debugged that and saw that every suggestion has a "insertText" attribute and for the older version, the insert text for == was =="" and for this version is =="{{}}". 

I hope I made it clear this time.
also, I'm using "Kusto" language for the Monaco editor. 

How can I change/disable this behavior of those curly brackets?

**Comment by microsoftsam** [comment]
The latest monaco editor version v0.9.0 discontinued  support for the custom built in snippet syntax. (one of which was the {{}} syntax)
Whoever owns the Kusto language service for monaco will need to update their SuggestAdapter to use the TextMate style snippet syntax instead, see:
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax
