### ISSUE TITLE
IE11: find widget mode select checkboxes appear visibly selected when unchecked

### ISSUE THREAD

**Issue by RoboPhred** [Microsoft/monaco-editor#513]
monaco-editor version: 0.9.0 / playground
Browser: IE11
OS: Windows 10

(Note: To see this on the monaco playground, the fix for #505 must be applied manually with the IE dev tools.)

The check boxes in the find widget for case sensitivity, whole word, and regex gain a blue border when checked and loose it when unchecked.  However, in IE11, the blue border remains after any of the three are unchecked.

This can be seen in the markup, as the element gains a style rule on check, which remains on uncheck.

Checkbox in its default, unchecked state.
```
<div tabindex="0" title="Match Case (Alt+C)" class="custom-checkbox monaco-case-sensitive unchecked" role="checkbox" aria-checked="false" aria-disabled="false" aria-label="Match Case (Alt+C)"></div>
```

Checkbox when checked.  Note addition of style="..."
```
<div tabindex="0" title="Match Case (Alt+C)" class="custom-checkbox monaco-case-sensitive checked" role="checkbox" aria-checked="true" aria-disabled="false" style="border-color: rgb(0, 122, 204);" aria-label="Match Case (Alt+C)"></div>
```

Checkbox when unchecked.  Note that the checked class is removed and unchecked class added, but the style="..." remains.
```
<div tabindex="0" title="Match Case (Alt+C)" class="custom-checkbox monaco-case-sensitive unchecked" role="checkbox" aria-checked="false" aria-disabled="false" style="border-color: rgb(0, 122, 204);" aria-label="Match Case (Alt+C)"></div>
```

If we check then uncheck the box in chrome, we can see that while the style attribute remains, its content is blanked out.
```
<div title="Match Case (Alt+C)" class="custom-checkbox monaco-case-sensitive unchecked" role="checkbox" aria-checked="false" aria-label="Match Case (Alt+C)" aria-disabled="false" style="" tabindex="0"></div>
```

**Comment by rebornix** [comment]
@RoboPhred nice catch, thank you!

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/43ff658e2a8c20464c3779b4020f30d9f876e7d5
