### ISSUE TITLE
Shift + Delete shortcut isn't working on Edge browser

### ISSUE THREAD

**Issue by sigalvo** [Microsoft/monaco-editor#514]
monaco-editor version: 0.9.0
Browser: Microsoft Edge 40.15063.0.0 Microsoft EdgeHTML 15.15063
OS: Windows 10
Steps or JS usage snippet reproducing the issue:
Shift + Delete shortcut stopped working on Edge new version.

**Comment by rebornix** [comment]
Didn't reproduce on Microsoft Edge 38.14393.1066.0 , it's possible that this might be an issue with Edge 40.15063.0.0

**Comment by mihula** [comment]
Replicated, workaround Ctrl+X works as expected, Shift+Delete deletes selection but did not store deleted content to clipboard.

**Comment by danhadari74** [comment]
Any update on this defect? Are you going to solve this?

**Comment by alexandrudima** [comment]
This works for me as expected in `Microsoft Edge 41.16299.15.0`
