### ISSUE TITLE
Unable to select removed code from inline diff

### ISSUE THREAD

**Issue by DrQuailMan** [Microsoft/monaco-editor#517]
If you're using an inline diff, you can neither select red/removed lines, nor find them via ctrl-F.

This is bad since when you're reading through a diff, the most important things that you're going to want to select or find are those that have been changed.  For example, you might see in file A that a function definition was removed, so you want to go to file B and make sure that the references to that function were also removed.  The best way to do that would be to select and copy the function name from file A, then do a ctrl-F in file B, but neither of these steps are possible using an inline diff.

monaco-editor version: 0.9.0
Browser:  Microsoft Edge and Google Chrome both have this issue
OS: Windows 10
Steps or JS usage snippet reproducing the issue:
Visit the sample editor page and check the "inline diff" checkbox: https://microsoft.github.io/monaco-editor/index.html

**Comment by rebornix** [comment]
dup of https://github.com/Microsoft/vscode/issues/8226 , let's track it there. Thank you!
