### ISSUE TITLE
the playground is out of date

### ISSUE THREAD

**Issue by Spongman** [Microsoft/monaco-editor#518]
for example, the version of `QuickInfoAdapter` that the playground uses contains this code:

````
      return {
                        range: i._textSpanToRange(a, e.textSpan),
                        contents: [o, t + (r ? "\n\n" + r : "")]
                    }
````

which results in doc comments appearing in the hover tooltip for functions.

however, AFAICT the monaco-typescript repo **never** contained this code.

**Comment by rebornix** [comment]
@Spongman do you mind pointing me to the example you are playing with?
