### ISSUE TITLE
 css/scss document format

### ISSUE THREAD

**Issue by dynameis** [Microsoft/monaco-editor#519]
need a css/scss formating feature , is this in your plan?

**Comment by rebornix** [comment]
A feature request for https://github.com/Microsoft/monaco-css .

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by aeschli** [comment]
@dynameis Sorry, not on the plan. But the monaco editor has API that lets you add formatters.

Marking as dup of https://github.com/Microsoft/vscode/issues/19166
