### ISSUE TITLE
How to know if the Suggestion window is open?

### ISSUE THREAD

**Issue by galyech** [microsoft/monaco-editor#520]
Is there an explicit, quick way to know if the suggestion window is open (visible to user) ? 

Thanks!

**Comment by microsoftsam** [comment]
@galyech Dont think theres a supported way to do it, but I do it like so:
'''
(this.editor as any)._view.contentWidgets._widgets["editor.widget.suggestWidget"].isVisible
'''
where this.editor is an instance of monaco.editor.IStandaloneCodeEditor

**Comment by rebornix** [comment]
@microsoftsam 👍

**Comment by AndersMad** [comment]
For Actions you can use `precondition` - this is what I use for ESC key actions e.g. to close main - but not if "children" is open (like a cancel bubble):

	myEditor.addAction(<monaco.editor.IActionDescriptor>{
		id: "my-close",
		label: "Close",
		keybindings: [monaco.KeyCode.Escape],
		precondition: "!suggestWidgetVisible && !markersNavigationVisible && !parameterHintsVisible && !findWidgetVisible",
		run: (ed: monaco.editor.ICommonCodeEditor): monaco.Promise<void> => {
			...
		}
	});
