### ISSUE TITLE
Editor high contrast support

### ISSUE THREAD

**Issue by mvegaca** [microsoft/monaco-editor#521]
I'm trying to add high contrast support in a project that use Monaco editor, but I can't. I've specified the property accessibilitySupport: true but document ignore high contrast colors.
Is there any solution?

**Comment by rebornix** [comment]
@mvegaca did you try set the theme as High Contrast Dark? 

```
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
    theme: "hc-black"
});
```

**Comment by mvegaca** [comment]
It works fine, thank you very much.
