### ISSUE TITLE
Folded section shows weird characters instead of '...'

### ISSUE THREAD

**Issue by gmantri** [Microsoft/monaco-editor#522]
monaco-editor version: 0.9.0
Browser: Opera/Electron (Chrome)
OS: Windows 10

I am trying out Monaco editor in the playground area. Modified basic options example (https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-editor-basic-options) to include folding. Folding works great! However what I am noticing is that instead of showing "..." to expand the folded section, it is showing weird characters (please see the screenshot below).

![monaco-editor-issue](https://user-images.githubusercontent.com/2417437/28456627-a4f45a62-6e20-11e7-84f3-55535f62c4ac.png)

This is happening in Opera browser and the Electron app I am building. I tested it on IE & Chrome and there it is working perfectly fine.

![monaco-editor-issue](https://user-images.githubusercontent.com/2417437/28456749-f51f9d9e-6e20-11e7-98da-be38afd16b42.png)

Here's the JS code I am using:

```
// Through the options literal, the behaviour of the editor can be easily customized.
// Here are a few examples of config options that can be passed to the editor.
// You can also call editor.updateOptions at any time to change the options.

var editor = monaco.editor.create(document.getElementById("container"), {
	value: "// First line\nfunction hello() {\n\talert('Hello world!');\n}\n// Last line",
	language: "javascript",
    folding: true,
	lineNumbers: false,
	roundedSelection: false,
	scrollBeyondLastLine: false,
	readOnly: false
});
setTimeout(function() {
	editor.updateOptions({
		lineNumbers: true
	});
}, 2000);

```

**Comment by alexandrudima** [comment]
@gmantri Do you define the charset in the `<head>` of the HTML page: `<meta charset="utf-8" />` ?

**Comment by gmantri** [comment]
@alexandrudima I haven't defined it. That seems to have done the trick. Once I added it, I am no longer seeing the weird characters. Thanks!
