### ISSUE TITLE
completion snippet + signature help

### ISSUE THREAD

**Issue by ribrdb** [Microsoft/monaco-editor#523]
monaco-editor version: 0.9.0
Browser: Chrome
OS:  mac

Steps or JS usage snippet reproducing the issue:
I have a signature help provider triggered on `'('` and` ','`.
I would like to have my completion provider return a snippet like `'foo(${1:bar})'`. This places the cursor after the (, but because the user didn't type it the signature help doesn't open. Same thing if I return multiple arguments and tab between them (`'foo(${1:bar}, ${2:baz})'`): there's no signature help because they never type `','`.
It seems typescript/javascript gets around this by only providing the signature help but no snippet. However it would be nice to be able to combine them.

**Comment by jrieken** [comment]
Your completion item can trigger signature help, Use this `editor.action.triggerParameterHints` as completion command.
