### ISSUE TITLE
Japanese IME not working on Android Chrome

### ISSUE THREAD

**Issue by gfx** [microsoft/monaco-editor#528]
monaco-editor version: 0.9.0 (in demo site as of 2017/07/27)
Browser: Chrome for Android
OS: Android 6.0
IME: Google Japanese IME for Android
Steps or JS usage snippet reproducing the issue:

To input: "こんにちは"
The editor shows: "んにちはこ" (seemingly random order)

<img src="https://user-images.githubusercontent.com/101800/28651252-b305afe4-72bb-11e7-86f0-41cf04a7a014.png" width="300"/>

This issue occurs on  the very demo site: https://microsoft.github.io/monaco-editor/

**Comment by belcherj** [comment]
https://github.com/microsoft/vscode/issues/87199
