### ISSUE TITLE
TypeScript: source file resolution (over HTTP)

### ISSUE THREAD

**Issue by sinclairzx81** [Microsoft/monaco-editor#530]
Hi,

I apologise in advance as this may have been asked before, but I am having some difficulty understanding file resolution / acquisition for multiple TypeScript source files within monaco.

For some background, I am currently looking to embed monaco inside a small web application and the application will be backed by a REST web service which will serve TypeScript source files over HTTP. So I am curious how to approach resolving source files on behalf of monaco (or typescript) in this scenario.

My first thought would be that there might be a IEnvironmentHost interface or similar that could be implemented, something that monaco could call out to when attempting to resolve a file. Something that would execute when monaco discovers a ```import``` or ```<reference>``` directive inside a TypeScript source file, but I am not exactly sure where to look, or indeed if such a function exists.

I guess the end goal would be to automatically resolve the red squiggles for imports, and to avoid having to pull down the codebase on page load, instead leaving monaco to request the files it needs from the environment when discovering a import.

If anyone could provide guidance on this it would be greatly appreciated.

Many Thanks
sinclair

**Comment by czb** [comment]
Any news on that?

**Comment by jrieken** [comment]
Sorry, but we have no plans of doing that. From the [monaco-typescript](https://github.com/Microsoft/monaco-typescript):

> Note that this project focuses on single-file scenarios and that things like project-isolation, cross-file-features like Ranme etc. are outside the scope of this project and not supported.


Closing, as question
