### ISSUE TITLE
Problem with scale3d

### ISSUE THREAD

**Issue by maierfelix** [microsoft/monaco-editor#531]
monaco-editor version: 0.9.0
Browser: Chrome
OS: Windows
Steps or JS usage snippet reproducing the issue:
````js
let z = 0.5;
editor.domElement.style.transform = `scale3d(${z}, ${z}, ${z})`;
````

When clicking inside the editor there are like "invisible blocks" overflowing from the left side.

Edit: Also some lines are impossible to click, the cursor jumps either to the line above or below but not to the expected line.

**Comment by alexandrudima** [comment]
Indeed, we make quite some assumptions in mouse hitting that we are not scaled w.r.t. mouse coordinates.

... If you are feeling brave (be warned there are a lot of browser quirks and workarounds needed) ... PR welcome in https://github.com/Microsoft/vscode/blob/35dc28625a1a4d93e5d47d79c788dcb54780acb3/src/vs/editor/browser/controller/mouseTarget.ts#L433

**Comment by sajeerAhamed15** [comment]
Any plan for this to be fixed? Given that it was raised back in 2017. It would be great if we get this fixed

**Comment by sajeerAhamed15** [comment]
Similar issue: https://github.com/microsoft/monaco-editor/issues/2347

**Comment by xpl** [comment]
Hello there, I'm facing the same issue. Would be nice to get it fixed.

**Comment by devnix** [comment]
Hi @alexdima, is the issue fixed or just abandoned?

**Comment by alexdima** [comment]
This was fixed by https://github.com/microsoft/vscode/pull/139282
