### ISSUE TITLE
Open search panel programmatically 

### ISSUE THREAD

**Issue by owennicol** [Microsoft/monaco-editor#532]
When you do cmd+f in the Monaco Editor, you get the find/search box appear.

Is there a way to have this open when the editor loads, with pre-populated text?

monaco-editor version: 0.9.0
Browser: chrome
OS: macOS 
Steps or JS usage snippet reproducing the issue:

**Comment by rebornix** [comment]
You can run `editor.getAction('actions.find').run()`.

**Comment by Cederfjard** [comment]
Is it at all possible to prepopulate the search box with arbitrary strings, like @owennicol asks? The only thing I've managed to do so far with the function you mentioned, @rebornix, is to search for the text that is currently selected.

**Comment by stanislavgeorgiev** [comment]
@owennicol I already added an answer to your question on SO:
https://stackoverflow.com/a/51291297/596082

**Comment by ijse** [comment]
how to close the search panel programmatically?

**Comment by fi3ework** [comment]
@ijse I found the event ID is `closeFindWidget` in this useful snippets. https://github.com/Microsoft/monaco-editor/issues/823#issuecomment-470754000
