### ISSUE TITLE
AngularJS integration

### ISSUE THREAD

**Issue by jack-arms** [microsoft/monaco-editor#534]
Does anyone have a working example of using Monaco with AngularJS? I got the basic example of Monaco to work with this code:

```
        require.config({
            paths: { 'vs': 'file:///path_to_project/bower_components/monaco-editor/release/min/vs/' }
        });

	require(['vs/editor/editor.main'], function() {
		var editor = monaco.editor.create(document.getElementById('container'), {
			value: [
				'function x() {',
				'\tconsole.log("Hello world!");',
				'}'
			].join('\n'),
			language: 'javascript'
		});
	});

```

Trying to translate this to an AngularJS directive:

```
angular
      .module('mymodule')
      .directive('monacoEditor', monacoEditor);

    function monacoEditor() {
        require.config({
            paths: { 'vs': 'http://localhost:20000/bower_components/monaco-editor/release/min/vs' }
        });
        require(['vs/editor/editor.main'], function () {
            console.log(monaco);
            var editor = monaco.editor.create(document.getElementById('container'), {
                value: [
                    'function x() {',
                    '\tconsole.log("Hello world!");',
                    '}'
                ].join('\n'),
                language: 'javascript'
            });
        });
        var directive = {
            ...
        };

        return directive;
    }
```

However `monaco` is always undefined.

I have checked that `http://localhost:20000/bower_components/monaco-editor/release/min/vs/editor/editor.main.js` can definitely be accessed by the browser. Is this an issue of 'http://' vs. 'file:///'? If the second `require` is failing to load the editor and leaves `monaco` undefined, how can I see what the error is?

**Comment by SoftTimur** [comment]
I want to make manaco editor with angularjs 1.X as well...

**Comment by jack-arms** [comment]
I have been able to get Monaco to work with angular to some degree by doing the sync load of Monaco rather than the code I posted above. At the beginning of `<body>` I put:

```
<script>var require = { paths: { 'vs': '../node_modules/monaco-editor/dev/vs' } };</script>
<script src="../node_modules/monaco-editor/dev/vs/loader.js"></script>
<script src="../node_modules/monaco-editor/dev/vs/editor/editor.main.nls.js"></script>
<script src="../node_modules/monaco-editor/dev/vs/editor/editor.main.js"></script>
<script src="../node_modules/monaco-editor/dev/vs/basic-languages/src/sql.js"></script>
```

and in `<head>` I put:

```
<link rel="stylesheet" data-name="vs/editor/editor.main" href="../node_modules/monaco-editor/dev/vs/editor/editor.main.css" />
```

And this makes `monaco` a global variable. I Then I make this a constant for my module:

```
angular
      .module('mymodule')
      .constant('monaco', monaco)
```

So that it can be injected into other places in the normal angular way. You can make a directive that uses a `link` function to create an editor around the element the directive is attached to, so you can write something like:

`<div class="monaco-container" monaco-editor={...}></div>`

I'm not able to load the languages I need dynamically, so I just put the script tag with the editor stuff for SQL in the body along with the other scripts. Still trying to integrate this process in with gulp as this definitely does not seem like the best way to load Monaco, but it at least works.

**Comment by rebornix** [comment]
Haven't played with Monaco in AngularJS 1.x for two years but if I remember correctly, NG 1.x has its own `require` so it overrides our amd-loader's require. To make it work smoothly, you can do 

1. AMD load Angular 1.x http://marcoslin.github.io/angularAMD/#/home 
2. Hold a reference to Monaco's require before loading angularjs. For example, add a script block `var monacoRequire = global.require` before loading angularjs.

**Comment by SoftTimur** [comment]
@rebornix In your comment, do you mean 1 or 2, or 1 and 2?

I wanted to look for a solution other than AMD loader or RequireJS... I will test what @jack-arms proposed...

**Comment by rebornix** [comment]
@SoftTimur I'm referring to 1.x only. I haven't ever played with 2 yet so not sure what's going on there.

**Comment by SoftTimur** [comment]
Sorry, I was not clear... I asked if you mean `1. AMD load... **and** 2. Hold a reference` or `1. AMD load... **or** 2. Hold a reference`?

**Comment by SoftTimur** [comment]
@jack-arms Thank you very much for your solution, it works so far... here is a working [JSBin](https://jsbin.com/cahijegute/2/edit?html,output).

Additionally, I have at least syntax for `javascript`, `html` and `css`. I don't know why you need to load `sql.js`...

**Comment by jack-arms** [comment]
I was loading the `sql.js` file because I was using SQL highlighting, and specifying 'sql' as the language would not automatically load this file. Although I'm not sure if it's supposed to be automatically loaded. I suspected that due to the way I was loading monaco I would have to load these types of things manually, but I will need to experiment more.

**Comment by chengtie** [comment]
@jack-arms @rebornix @joaomoreno @jongalloway Guys, what was proposed previously worked fine, whereas it does not work with `ocLazyLoad`. Here is my question: https://github.com/Microsoft/monaco-editor/issues/845 and https://stackoverflow.com/questions/50017351/lazy-load-monacoeditor

Do you have any idea?

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
