### ISSUE TITLE
Use Monaco Editor in AngularJS 1.X

### ISSUE THREAD

**Issue by SoftTimur** [Microsoft/monaco-editor#535]
I can well run [this sample of Monaco Editor](https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-editor/index.html). But I don't know how to make it work with AngularJS 1.X. 

For example, I want to bind `ng-if`, `ng-model` and `ng-change` to the editor, to decide when and what to display, and run a function if there is any change. With [ui-codemirror](https://github.com/angular-ui/ui-codemirror), we could write with a directive:

    <textarea ng-if="condition" ng-change="change(content)" ng-model="content" ui-codemirror="{ mode: 'application/json' }"></textarea>

So does anyone know if there is such `ui-` directive for Monaco Editor? Is there any workaround to achieve the same thing within angular framework?

Thank you

**Comment by rebornix** [comment]
ui-codemirror is an angular library which wraps codemirror, what you need is one for monaco.

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/monaco-editor/issues/534 .
