### ISSUE TITLE
Max lines

### ISSUE THREAD

**Issue by joaopgg** [microsoft/monaco-editor#536]
Hi guys,

Is there any easy way to limit the number of lines / chars that the user can use in monaco editor? (e.g 1000 lines)

Best regards

**Comment by alexandrudima** [comment]
@joaopgg You can enforce this in a similar way you would enforce a character limit to a native `<textarea>`. i.e. you would listen to events and react to them.

You can use `editor.onDidChangeModelContent(function(e) { ... });` and then check `editor.getModel().getLineCount()` and react as you see fit.

**Comment by joaopgg** [comment]
Ok. Thanks for the answer. 

Best regards
