### ISSUE TITLE
Example for kebindings with chord

### ISSUE THREAD

**Issue by mbarkhau** [Microsoft/monaco-editor#538]
I had a difficult time figuring out how chords work when adding a new action. Would it be possible to add an example to the documentation which uses code like this:

```javascript
editor.addAction({
    keybindings: [monaco.KeyMod.chord(
        monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_K,
        monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_E,
    )],
```

**Comment by rebornix** [comment]
@mbarkhau you can see the change once we update the website. for now you can take a look at https://github.com/Microsoft/monaco-editor/commit/8ef75ad01c3c5c9b4283e43846e1b8482f70afde#diff-b72de1c29245036f936763f9f3f470d9R69 for how to make chord work.
