### ISSUE TITLE
Change the language of an existing editor

### ISSUE THREAD

**Issue by SoftTimur** [Microsoft/monaco-editor#539]
I am making [a directive](https://jsbin.com/qagativuwe/1/edit?html,output) to help using Monaco Editor in AngularJS 1.X framework. One feature should be updating the language based on the option. But I cannot change the language.

It seems that the type of `monacoeditor` in my code is `ICommonCodeEditor`, I tried `monacoeditor.updateOptions({ "language": newValues[key] })`, it did nothing. I tried `monacoeditor.getModel().updateOptions({ "language": newValues[key] })`, it did nothing either. I tried also `monacoeditor.setModelLanguage(monacoeditor.getModel(), newValues[key])`, it gave an error `TypeError: monacoeditor.setModelLanguage` is not a function.

Note that it is not the problem of the directive, because it works well to change options like `lineNumbers`.

Could anyone help?

**Comment by rebornix** [comment]
![image](https://user-images.githubusercontent.com/876920/29143559-7eb3c312-7d0a-11e7-9149-127d2380b0ec.png)

`monaco.editor.setModelLanguage` works as expected. Please make sure you are setting language names correctly.

**Comment by SoftTimur** [comment]
My friend... can you just make sure if your comment answered my question before closing the issue? Otherwise, it just gives the feeling that your mission is to close issues as quickly as possible...

Let me check the languages names...

**Comment by SoftTimur** [comment]
I think the name `javascript` is fine...

In your screenshot, you used `monaco.editor.createModel("var a = 1;")`, whereas in my code I use `monaco.editor.create(document.getElementById('container'), { ... }`, whose type is different, so it gave an error `TypeError: monacoeditor.setModelLanguage` is not a function.

If I want to use `createModel` like you, how could I specify the `domElement`?

**Comment by rebornix** [comment]
@SoftTimur from you snippet, it seems you create the editor from string (if you create a model first then my previous comment answers your question IMO). `setModelLanguage` is a function we exposed in module `monaco.editor`, it's not a method of the editor object. So in your case, you can do

```
var model = monacoeditor.getModel(); // we'll create a model for you if the editor created from string value.
monaco.editor.setModelLanguage(model, "javascript")
```

Hope this helps you out, if it still doesn't solve it, I'll reopen this issue. BTW, you may want to refer `monaco.d.ts` file for typings reference.

**Comment by SoftTimur** [comment]
Got it, I should use `monaco.editor.setModelLanguage(monacoeditor.getModel(), newValues[key])` rather than `monacoeditor.setModelLanguage(monacoeditor.getModel(), newValues[key])`, where `monacoeditor` is my editor, and its type is probably `ICommonCodeEditor`, and does not have the `setModelLanguage` function.

Here is a working [JSBin](https://jsbin.com/fohirojuko/1/edit?html,output)

Thank you...

**Comment by mrbormeth** [comment]
I'm changing the file used for the template. 

Like this: https://pastehero.com/view/8184a131-1d3b-420-8fbe-4a0c8910f78a
And using the file like this: https://pastehero.com/view/fbaac015-84a1-420-92cc-6f2f23512309

Thou might required ngx-monaco (https://github.com/SamVerschueren/ngx-monaco)

Hope it helps. :)

**Comment by Symbolk** [comment]
Anyone know how to change the language according to code file extension or first line like "#!/usr/bin/env python"?

**Comment by iamwhitebox** [comment]
This does not work with multiple editors on a page, like in split panes (a requirement for any IDE)

Is there a way to change the color theme for an existing instance of IStandaloneCodeEditor

**Comment by iamwhitebox** [comment]
> Anyone know how to change the language according to code file extension or first line like "#!/usr/bin/env python"?

```
const languages = {
  'js': 'javascript',
  'ts': 'typescript',
  'html': 'html',
  'htm': 'html',
  'txt': 'text',
  'css': 'css'
}
const ext = node.name.match(/([^\.])+$/g)[0];

// this.editorComponent.instance.options.language = languages[ext];

(window as any).monaco.editor.setModelLanguage((window as any).monaco.editor.getModels()[0], languages[ext]);

```
