### ISSUE TITLE
Is there a way to set monaco-editor readonly?

### ISSUE THREAD

**Issue by uadnan** [Microsoft/monaco-editor#54]
Hi, 

I wonder if there is a way to disable editing i.e. enter into read only mode.

Thanks,

**Comment by uadnan** [comment]
Sorry I found that we can pass `readonly` option while creating editor.

```
var editor = monaco.editor.create(element.nativeElement, {
    model: null,
    readOnly: true
});
```

**Comment by James9074** [comment]
Has anyone seen a reliable way to change this post-creation? Not seeing the editorOptions exposed in the editor object afterwards.

**Comment by andyg8180** [comment]
@James9074  try this action on the code editor:
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#updateoptions

and then check out readonly here:
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html

**Comment by alexandrudima** [comment]
@James9074  `editorInstance.updateOptions({ readOnly: true })` or `editorInstance.updateOptions({ readOnly: false })` as @andyg8180 mentions will do the trick.

**Comment by James9074** [comment]
Hey that actually worked! Thanks @elAndyG and @alexandrudima. I was getting caught up in the doc's typing and forgot I could just pass a json object into `updateOptions` to make that work.
