### ISSUE TITLE
Alternative of require

### ISSUE THREAD

**Issue by SoftTimur** [Microsoft/monaco-editor#540]
I would like to understand `require` in the samples like [this](https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-editor/index.html)... Is it `RequireJS`?

It creates trouble when we want to use Monaco Editor with angularJS, eg, [here](https://stackoverflow.com/questions/45588356/require-in-a-directive) and [there](https://stackoverflow.com/questions/45599619/watch-is-not-trigger-in-the-beginning). Isn't it possible to just load everything in any case rather than using `require`?

**Comment by rebornix** [comment]
We are using inhouse amd loader and you can use requirejs to load monaco as well. Please details I put in https://github.com/Microsoft/monaco-editor/issues/534#issuecomment-321375985.
