### ISSUE TITLE
Copy with formatting doesn't work in IE 11 (copies without formatting)

### ISSUE THREAD

**Issue by Zlatkovsky** [microsoft/monaco-editor#541]
In the [Changelog](https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md) for version 0.9.0, the "New and noteworthy" mentions the "Copy text with formatting" feature.

However, it looks like it doesn't work in Internet Explorer.  Is there any way to enable it there?  (Context:  my team created [Script Lab](https://aka.ms/scriptlab), an Office Add-in that leverages Monaco and that runs inside of Office.  But Office Add-ins are hosted by an IE process on Windows, so the copy-with-formatting -- which is something we were really excited about, and we've had requests for -- doesn't work there.

Thanks!
- Michael

monaco-editor version: 0.9.0
Browser: IE 11
OS: Win 8.1/Win10

**Comment by alexandrudima** [comment]
IIRC @rebornix hit some issues on IE/Edge and disabled it there -- https://github.com/Microsoft/vscode/blob/7494a1b944e9a81c504a0a6f1bc33f5522cd81cc/src/vs/editor/browser/controller/textAreaInput.ts#L452

**Comment by rebornix** [comment]
For IE/Edge, changing the clipboard programmatically will ask users for permission every time so right now we didn't support this feature on IE/Edge. We may be able to put that behind a setting/command then users can choose if they really want to do so but the experience is not consistent.

**Comment by Zlatkovsky** [comment]
@rebornix , is it once per *tab session*, or *every single time you press ctrl+c*?

If it's just once per tab, that may be ok for us, as inside of Office Add-ins, that prompt happens regardless (even for regular plain-text copy-paste in Monaco 0.8.3).  If so, if it's possible to put under environment options (e.g., `enableCopyWithFormattingOnIEEdge`), that would be totally fine with us, and we can set that option to `true` and everyone else can do as they wish.

If it's once per ctrl+c, that's a different story, that's too annoying to be useful.

Thanks!
- Michael

**Comment by alexdima** [comment]
The Monaco Editor is generated from the source code of VS Code and in order to improve VS Code we must be able to use modern browser features, like Flexbox, which has a number of bugs that we cannot workaround in IE11.

We have investigated the cost of fixing all the problems of IE11 and have decided to discontinue support for IE 11. The last Monaco Editor version that was tested on IE 11 is `0.18.1`.

Thank you for your understanding.
