### ISSUE TITLE
Disable minimap

### ISSUE THREAD

**Issue by SoftTimur** [Microsoft/monaco-editor#542]
I have a code to create an editor in an AngularJS directive:

    function newMonacoeditorEditor(iElement, monacoeditorOptions) {
        var editor = monaco.editor.create(iElement[0], {
            language: monacoeditorOptions.language,
            lineNumbers: monacoeditorOptions.lineNumbers
        });
        console.log("newMonacoeditorEditor")
        return editor
    }

I would like to know how to always disable the minimap?

Thank you

**Comment by alexandrudima** [comment]
e.g.

```js
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
 	minimap: {
		enabled: false
	}
});
```

**Comment by SoftTimur** [comment]
It works, thank you very much @alexandrudima

**Comment by David-Carty** [comment]
How does one disable minimap once the editor has been created?

**Comment by rcjsuen** [comment]
@David-Carty You can use the [`updateOptions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#updateoptions) API for that.

```JavaScript
editor = monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript",
    minimap: {
        enabled: true
    }
});

setTimeout(() => {
    alert("Disabling")
    editor.updateOptions({
        minimap: {
            enabled: false
        }
    })
}, 3000);
```

**Comment by David-Carty** [comment]
Thank you.  Is there anyway of detecting if the minimap is enabled as I want to create a toggle?

**Comment by alexandrudima** [comment]
@David-Carty You can track the minimap enablement on your side in a variable.
