### ISSUE TITLE
Multi column editoring seems to be a bug.

### ISSUE THREAD

**Issue by powerumc** [Microsoft/monaco-editor#544]
monaco-editor version: 0.9.0
Browser: Chrome
OS: MacOS Sierra
Steps or JS usage snippet reproducing the issue:

I developing ot.js monaco adapter.

0.9 version, multi line editoring bug resolved.

But there seems to be a bug is multi column editoring in version 0.9.

![untitled](https://user-images.githubusercontent.com/1943755/29204876-77dd52c8-7eb4-11e7-85f4-2879f834aa0b.gif)

**Comment by alexandrudima** [comment]
This issue does not appear to be Monaco Editor related, but rather in the `ot.js` adapter.
