### ISSUE TITLE
[BUG] document.activeElement.blur() can not blur the currently focused editor

### ISSUE THREAD

**Issue by dengkunli** [microsoft/monaco-editor#548]
Calling document.activeElement.blur() can not blur the currently focused editor, can reproduce directly on monaco website.

For example, in Monaco webview Hello World example,

```javascript
window.e = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
```

then open devtools and type in the console:
```javascript
e.focus()
```

after seeing the cursor blinking
```javascript
document.activeElement.blur()
```

then the editor is not blurred and the cursor is still blinking. calling `e.isFocused()` will return true as well.

----
Monaco v0.9.0

**Comment by alexandrudima** [comment]
This works perfectly fine for me:

* Step1: Ensure there is some other element in that `<iframe>`
  * edit the HTML tab: `<input /><div id="container" style="height:80%;"></div>`
* Step2: Blur the editor after a certain time it receives focus:
```js
var ed = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

ed.onDidFocusEditorText(function() {
    setTimeout(function() {
        document.activeElement.blur();
    }, 3000);
});

```

This works fine for me in, e.g. Firefox:
![548](https://user-images.githubusercontent.com/5047891/32503918-cdd3795e-c3de-11e7-86c0-96b9bfbb23fe.gif)
