### ISSUE TITLE
Find panel unusable in Internet Explorer

### ISSUE THREAD

**Issue by joechung-msft** [Microsoft/monaco-editor#549]
monaco-editor version: 0.9.0
Browser: Internet Explorer 11
OS: Windows 10

Visit [https://microsoft.github.io/monaco-editor/playground.html](https://microsoft.github.io/monaco-editor/playground.html)

Press Ctrl-F to open the Find panel.

The panel looks like this, and its input box is unusable; text does not show up when you type.
![find-ie](https://user-images.githubusercontent.com/26208574/29311920-336cec3c-8168-11e7-836a-1a8026e3ea08.PNG)

**Comment by rebornix** [comment]
@joechung-msft this is fixed in master and the fix will be out with our next update this week.
