### ISSUE TITLE
Korean IME issues with IE11

### ISSUE THREAD

**Issue by jayspadie** [Microsoft/monaco-editor#552]
monaco-editor version: 0.9.0
Browser: IE11
OS: Windows 10

When editing in Monaco using IE11 and Windows Input Method Editor (IME) for Korean, the last character is not committed until hitting the space bar - it is lost when Monaco loses focus.  And when focus is returned to Monaco after that, then it accepts no further input.

Shown below I am hitting the D key 3 times, then clicking outside Monaco to lose focus (losing the last ㅇ), then back again.  At that point, I cannot enter anything.  Following that, I refresh the page and do the same thing but also hitting the space bar after the last ㅇ.  In this case, all characters are retained and I am also able to continue inputting characters.

![koreanime-monaco](https://user-images.githubusercontent.com/5246869/29466126-b4a30f0e-8409-11e7-9d6e-27388eaa9932.gif)

**Comment by rebornix** [comment]
It's an interesting bug in IE11.

If you type Chinese or Japanese, focus on another element when it's still in composition mode. Then you get events in following sequences

* blur
* composition end

If you type Korean, in Edge or Chrome, what you get is 

* composition update
* composition end
* blur

*blur* comes last and there is one additional update event, but it's okay as we get the correct composition end event.

Now it comes to Korean IME on IE11

* composition update
* blur

We didn't get a chance to update `isDoingComposition` then next time we focus the editor, we can no longer type in anything as our code thinks it's doing composition.

**Comment by rebornix** [comment]
For Japanese, it's okay that leaving the editor and coming back with the composition popup open, so my change to clean the composition state when blur is wrong.

I'll test later to see if this is just a problem with Korean IME on IE11. If so, we need this bad *if* statement and not break anything else.
