### ISSUE TITLE
Javascript Block comments are parsed incorrectly

### ISSUE THREAD

**Issue by mofux** [microsoft/monaco-editor#554]
## Environment
monaco-editor version: 0.10.0, 0.9.0
Browser: Chrome
OS: MacOS Sierra

## What's wrong
For jsdoc comments, the `comment.doc` token is parsed incorrectly. The closing line is marked as `comment` rather than `comment.doc`.

This problem is invisible to most users because the monaco editor uses the same color for the `comment` and `comment.doc` token. 

Here is a fiddle that demonstrates the issue:
https://jsfiddle.net/bwgkr6uq/14/

![jsdoc](https://user-images.githubusercontent.com/2785983/29467373-956a567e-8440-11e7-84b9-9ae0cb0cd157.gif)

**Comment by mofux** [comment]
I'd love to work on a PR that fixes this issue, but I'm unable to locate the file / repository of the javascript tokeniser that needs to be modified. Any hints would be very appreciated!

**Comment by alexandrudima** [comment]
I think this is where the decision is made:

https://github.com/Microsoft/monaco-typescript/blob/fd172013f77fa599e03a1c17b79aab62637569fa/src/tokenization.ts#L103

and it might have something to do with the member `inJsDocComment `.

**Comment by alexdima** [comment]
This is now obsolete since we moved to Monarch tokenization for TS/JS
