### ISSUE TITLE
Wrong highlighting for Matlab models

### ISSUE THREAD

**Issue by hsommer** [microsoft/monaco-editor#555]
Hi,
we are using VSTS and the syntax highlighting for matlab models is wrong when browsing th  file content (e.g. keywords are highlighted in comments). In this case it would be helpful to add a selection for these models or being able to disable highlighting for certain filetypes.

monaco-editor version: VSTS
The issue is independent of browser and OS.

**Comment by alexandrudima** [comment]
@hsommer What file extensions are you having trouble with ?

Can you also include here a piece of code that exhibits the problem ?

Here are the files / languages the Monaco Editor recognizes: https://github.com/Microsoft/monaco-languages/blob/master/src/monaco.contribution.ts#L54

All the syntax highlighters are in the same folder, so if you'd like to even create a PR that would be great !
