### ISSUE TITLE
How to diable Monaco Editor right navigation view?

### ISSUE THREAD

**Issue by mokeyish** [Microsoft/monaco-editor#561]
![baidushurufa_2017-8-23_9-21-45](https://user-images.githubusercontent.com/16131917/29594641-cf8371ae-87e4-11e7-998d-96b81c0b2b81.png)

monaco-editor version: 0.X.Y
Browser:
OS: 
Steps or JS usage snippet reproducing the issue:

**Comment by mofux** [comment]
This feature is called the `minimap` and you can disable it using the configuration:

```javascript
let editor = monaco.editor.create(element, {
  minimap: { enabled: false }
});
```

**Comment by mokeyish** [comment]
@mofux Thankyou ,I've got it.
