### ISSUE TITLE
Android 6+ delete key

### ISSUE THREAD

**Issue by samelhusseini** [microsoft/monaco-editor#563]
monaco-editor version: 0.10.0
Browser: Chrome 50
OS: Android 6.1
Steps or JS usage snippet reproducing the issue:

Typing anything into the monaco editor and then attempting to delete it using the keyboard fails. 
Debugging this shows that onKeyDown on Android is raising keyCodes with 229 for the back key. 

Potentially in vscode/textAreaInput: 
https://github.com/Microsoft/vscode/blob/05f7db06b22a5a66c58435cf78a529bd40b8dbe7/src/vs/editor/browser/controller/textAreaInput.ts#L251
you could handle the scenario where text == "" and replaceCharCnt == 1 and do a replacePreviousChar in that case. 

Although this might fix the issue for one line, it's best if there was a way we could trigger a deleteLeft command in that case, as that would work across multiple lines.

More info: https://bugs.chromium.org/p/chromium/issues/detail?id=118639

**Comment by microsoftsam** [comment]
Potentially related to #529

**Comment by karlhorky** [comment]
Thanks @alexdima !! 💯 This was a really annoying issue.
