### ISSUE TITLE
editor.addCommand swallows meta keys

### ISSUE THREAD

**Issue by uqee** [microsoft/monaco-editor#565]
monaco-editor version: 0.9.0
Browser: Chrome, FF, Safari
OS: macOS
Steps or JS usage snippet reproducing the issue:

```javascript
editor.addCommand(monaco.KeyCode.XXX, () => console.log('fired'));
```
**Examples** for `XXX`:
`Meta`, `Ctrl`, `Alt`, `Shift` -- not working,
`Tab`, `Space`, `KEY_X` -- works.

`KeyMod.chord` works for regular keys too.

**Docs**:
+ [addCommand](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#addcommand)
+ [KeyCode](https://microsoft.github.io/monaco-editor/api/enums/monaco.keycode.html)
+ [chord](https://microsoft.github.io/monaco-editor/api/classes/monaco.keymod.html#chord)

**Update**:
Seems like just wrong `monaco.KeyCode` values:

key | KeyCode (wrong) | actually working (right)
--- | --- | ---
Ctrl | 5 | 256
Alt | 6 | 512
Shift | 4 | 1024
Meta | 57 | 2048

**Comment by alexandrudima** [comment]
Indeed, we need better doc for those. `KeyCode.Ctrl`,  `KeyCode.Alt`,  `KeyCode.Shift` and  `KeyCode.Meta` generally should not be used directly, but rather `KeyMod.CtrlCmd | KeyCode.Tab` for `ctrl+tab` on Win/Linux and `cmd+tab` on OSX, etc. We need to improve the doc in this area.
