### ISSUE TITLE
Configuration for wordBasedSuggestions not working

### ISSUE THREAD

**Issue by kenans** [Microsoft/monaco-editor#567]
monaco-editor version: >=0.9.0
Browser: Chrome
OS: Windows 7
Steps or JS usage snippet reproducing the issue:

Hi, I'm not sure if this is a bug or I've wrongly configured something, because there's no word based completion at all even though I explcitly set contribInfo.wordBasedSuggestions to true. I searched the [change log](https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md) and[ related github issues](https://github.com/Microsoft/monaco-editor/issues) but I didn't find any clue.

I noticed this issue because I've been using an old version v0.8.3 and the word based completion worked fine just with a very simple editor creation, 

```
let editor = monaco.editor.create(document.getElementById("container"), {
  value: "<aaa>abbb</aaa>",
  language: "xml"
});
```

Once I upgraded to v0.9.0 or later version, the above code snippet doesn't work. The issue can also be easily reproduced on [monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html).

Thanks

**Comment by kenans** [comment]
Just to update some of my new findings. This issue seems to be a bug since v0.9.0. In editor/common/services/editorWorkerServiceImpl.ts, line 95,
`
const { wordBasedSuggestions } = this._configurationService.getConfiguration<IEditorOptions>(model.uri, position, 'editor');
`

It seems the destructing is not able to go down to the editor level, which causes wordBasedSuggestions always to be undefined.

**Comment by RWeigelt** [comment]
I have a problem that fits the title "Configuration for wordBasedSuggestions not working", but in my case its that I cannot turn OFF the word-based completion.

If I visit the [Monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html), and set the option `wordBasedSuggestions` to `false`...
```js
// The Monaco Editor can be easily created, given an
// empty container and an options literal.
// Two members of the literal are "value" and "language".
// The editor takes the full size of its container.

monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
	wordBasedSuggestions: false
});
```
...and hit "run", then I would expect to *not* get word-based suggestions if I e.g. add a variable to the code on the right:
```
function hello() {
	alert('Hello world!');
	var example="Test"; // added
	
}
```
...and then type `example.` in the next line.
At that point, I get a list of suggestions that make sense for a string variable *and* the words "hello", "alert" and "example" - which I don't want.
