### ISSUE TITLE
Support watermark/placeholder text

### ISSUE THREAD

**Issue by derek1ee** [microsoft/monaco-editor#568]
When embedding Monaco editor as a in-line control, we'd like to show a placeholder text before any value is entered, similar to how textbox works, so user sees an example of the expected value for the said parameter.

Derek, Azure Logic Apps

**Comment by jjoc007** [comment]
Did you find something?

**Comment by cwtuan** [comment]
anything updated?

**Comment by cwtuan** [comment]
need this feature too

**Comment by vikyd** [comment]
Here is my solution: **add another element to simulate placeholder**

https://codesandbox.io/s/monaco-editor-placeholder-vue-1lurc?file=/src/components/MonacoPlaceholder.vue

**Comment by bultas** [comment]
The solution is a simple overlay element linked to the basic Monaco events like: 
- `onDidBlurEditorWidget`
- `onDidFocusEditorWidget`

You can check my simplified version of Monaco build (added ES modules support) repo where I have placeholder example:

Demo:
https://bultas.github.io/monaco-component/dist/placeholder.html

Source:
https://github.com/bultas/monaco-component/blob/master/dist/placeholder.js

Repo:
https://github.com/bultas/monaco-component

**Comment by ClearSeve** [comment]
Is this feature now supported?

**Comment by cwtuan** [comment]
is placeholder supported?

**Comment by stefan-lacatus** [comment]
Based on the VSCode implementation, i've come up with the following `IContentWidget`:

```typescript
/**
 * Represents an placeholder renderer for monaco editor
 * Roughly based on https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint/untitledTextEditorHint.ts
 */
class PlaceholderContentWidget implements monaco.editor.IContentWidget {
    private static readonly ID = 'editor.widget.placeholderHint';

    private domNode: HTMLElement | undefined;

    constructor(
        private readonly placeholder: string,
        private readonly editor: monaco.editor.ICodeEditor,
    ) {
        // register a listener for editor code changes
        editor.onDidChangeModelContent(() => this.onDidChangeModelContent());
        // ensure that on initial load the placeholder is shown
        this.onDidChangeModelContent();
    }

    private onDidChangeModelContent(): void {
        if (this.editor.getValue() === '') {
            this.editor.addContentWidget(this);
        } else {
            this.editor.removeContentWidget(this);
        }
    }

    getId(): string {
        return PlaceholderContentWidget.ID;
    }

    getDomNode(): HTMLElement {
        if (!this.domNode) {
            this.domNode = document.createElement('div');
            this.domNode.style.width = 'max-content';
            this.domNode.textContent = this.placeholder;
            this.domNode.style.fontStyle = 'italic';
            this.editor.applyFontInfo(this.domNode);
        }

        return this.domNode;
    }

    getPosition(): monaco.editor.IContentWidgetPosition | null {
        return {
            position: { lineNumber: 1, column: 1 },
            preference: [monaco.editor.ContentWidgetPositionPreference.EXACT],
        };
    }

    dispose(): void {
        this.editor.removeContentWidget(this);
    }
}
```

Should be initialized with
```typescript
 new PlaceholderContentWidget('The value for placeholder', editorReference);
```

**Comment by hediet** [comment]
Thanks @stefan-lacatus!
[You can try it out in the playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.37.1#XQAAAAJ4BwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxB3nW-_1uhs0-3YGTBOsVJ4S4FwfCDQb5-2uUHXTVAefbVSd9IzaZ_vv9VR9KugsKijNW9wwRd5DtiDWSZ6tDTYuY32_qmQ-RLcMDMLJBHRvRV_4CZNmAA6CP36vruVnkwOir6k8Nn1qh9YFCmUIGWP0qbj_tu9087RAQGZY2JwV5BY9dOy1lDELs-6fhKm4NO7kfrDjsFUfR7mNZY2hHvgndklABbjoF0LGRZQp00vPoncuBlGaA9_ja6rK5oOUrVHcdQ9YvxT5EC7wS1-3iCmwwMWk-zYCSUpOeb7q6k4bfvDFD1SlxRkRjXY7ZI7F_4HEtujQUyEex3S3wPIrzu2rDPRIW9UhXwv3U62nvvK-2Hiwk1Dev90U18Ok_MjPD_DRXIrNlxiJUS-IiH289_NEwHuX-sQ56EBTJKX7NBZd53rLjQ8bCzi_p9X-n2O4C4odm10q6QtAZ63t4F6BsdJo2qnqSkPkClOyW9_4jezN2ZHyaoxm4qHJSn_2sPTLyEgN7mB-DE4B8Xp54Hd_0Ahgspt5uxgG6_d7NF03TEjvgLR5yMBkh6h91NDdkI5HCJAOR_5UcvDb2gy8ETW-qqwpDHtxTWR82OLpgvcwrwXotgTvEBXIyl3gfM9_fDe0UN0_Tt1egW0fsKTZ077xl30fiJE4wwqmJdgP3b3KQ8xBAYU2iMrJsW91l2nOAQZaIzZMmZpqNhGvh8FeK-LMw8TdJ_S5Tp9zzvqEb_hxG4gXupPhOAAqI0C16-K0_I9E-LXKz9P_D3329Gn9hiWL9XH6-7QoSZGEomTha1arxJOdb5RoX6Sv3eGIHg-KWowgC6NJld-vaaH03K98EtXVsFuCXroHPQkAXwfkowwYzjqBWFLmiEVfsknL9ab0LSI7AYvxgaqpGkZOO0n5L_NOH0vBZaq5VShfQzjDmzcI6f_ODBXfQXmb_hBzLSJLVpFDBp0g-id17T_eroW1YlS0VOkDmOy4xDFndJTx0RF_8pXkciCVoLlwRfbIApR7-KMfrqReBXZFW-VP8h0sNh7zjbGL3Oc3_89KGuw).

I recommend to use injected text though or to disable cursor interaction, as clicking on the placeholder won't focus the editor though.

Closing this issue, as this can be easily implemented.

**Comment by stefan-lacatus** [comment]
> I recommend to use injected text though or to disable cursor interaction, as clicking on the placeholder won't focus the editor though.

Correct, I fixed this a while back by just setting `pointerEvents = 'none'` on the dom node. Seems to create a good enough UX. 
I've updated the post above.
