### ISSUE TITLE
How to show line decorators in the scrollbar

### ISSUE THREAD

**Issue by gimenete** [Microsoft/monaco-editor#569]
monaco-editor version: 0.10.0
Browser: electron/chromium
OS: osx

Hi. I'm using line decorators. It is possible to show them in the scrollbar like occurrences or the blocks in the diff editor?

![2017-08-28 at 19 39](https://user-images.githubusercontent.com/50486/29785789-25f11e0e-8c29-11e7-9b29-f6fa5a4b4757.png)

Thanks for this awesome project!

**Comment by alexandrudima** [comment]
The diff editor overview ruler is private to the diff editor and cannot be contributed from the outside via public API. But the overview ruler of the regular editor is accessible and decorations can be painted there via the `overview` decoration option.

**Comment by gimenete** [comment]
Awesome, thanks. I've found the `overviewRuler` in `IModelDecorationOptions` and it works!
