### ISSUE TITLE
Inline diff has no horizontal scroll bar if only "before" lines exceed width of editor

### ISSUE THREAD

**Issue by brkerr** [microsoft/monaco-editor#570]
monaco-editor version: 0.X.Y
Browser: Chrome, edge
OS: Windows
Steps or JS usage snippet reproducing the issue:

In an inline diff, the horizontal scrollbar does not appear until added or existing text hits the edge of the window. Removed seems to be ignored. Also, as the window is resized I can see the horizontal scrollbar appearing but it immediately disappears. Are removed lines in the diff factored into whether or not this scrollbar should be displayed?

![image](https://user-images.githubusercontent.com/17860625/29793006-55361d18-8c10-11e7-82bf-3e8702b3d6ff.png)

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.
