### ISSUE TITLE
Code highlighting is broken after a multiline template literal with the `}` on a new line

### ISSUE THREAD

**Issue by ArtemGovorov** [microsoft/monaco-editor#571]
monaco-editor version: 0.10.0
Browser: All
OS: All
Steps or JS usage snippet reproducing the issue:
Code highlighting is broken after the multiline template string with the `}` on a new line (for both JavaScript and TypeScript). Insert the following code:
```javascript
`${`
}`}`;

a();
b();
c();
```
into https://microsoft.github.io/monaco-editor/, and you'll get:
![screen shot 2017-08-29 at 11 41 18 am](https://user-images.githubusercontent.com/979966/29800727-fef0cbf2-8cae-11e7-9854-1803678b4be5.png)

This however works as expected in VS Code (both stable and insiders):
<img width="180" alt="screen shot 2017-08-29 at 11 42 59 am" src="https://user-images.githubusercontent.com/979966/29800771-3a7a0706-8caf-11e7-8b24-77a5cc0f0113.png">

Is it possible that Monaco JS/TS tokenizer is not up-to-date (not the one used in VS Code)?

**Comment by alexandrudima** [comment]
I think this might be a limitation of using the TS tokenizer for coloring... The difference is that in VS Code we use a TM grammar and in the Monaco Editor we use the TS tokenizer.

https://github.com/Microsoft/monaco-typescript/blob/master/src/tokenization.ts

**Comment by alexdima** [comment]
This has been fixed since we switched to Monarch for TS coloring.
