### ISSUE TITLE
C# Intellisense does not work with the sample page

### ISSUE THREAD

**Issue by satyajit-behera** [microsoft/monaco-editor#572]
In the sample page, the intellisense does not show up (using csharp editor). Nothing pops up when si. is typed. Or even System. is typed, nothing pops up.

https://microsoft.github.io/monaco-editor/index.html

**Comment by rcjsuen** [comment]
This is to be expected. Intellisense for C# is not mentioned on the [website](https://github.com/Microsoft/monaco-editor/blob/06c48a7281d5728ad9f46185330be6e2ada29334/website/index.html#L83-L84) and Monaco doesn't ship with a C# language server so...

**Comment by satyajit-behera** [comment]
@rcjsuen thanks. Can you guide if there are any resources which guide us to implement a miniature version of code editor in our own web application with full intellisense support (c#) or any other language of our choice.

**Comment by akosyakov** [comment]
@satyajit-behera The Monaco Editor cannot provide full intellisense support for C# out of the box, only syntax coloring. You should connect it with [the language server for C#](https://github.com/OmniSharp/csharp-language-server-protocol), that provides intellisense, by means of [monaco-languageclient](https://www.npmjs.com/package/monaco-languageclient). [Here](http://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor) is an article explaining how to do it. You can also find the example in monaco-languageclient repo.

**Comment by akshay-zz** [comment]
Did any one has implemented that? The way @akosyakov has guided. If any one can write a doc for the same that will be very helpful.

**Comment by karayakar** [comment]
I have sample page published at https://sqlrestapi.azurewebsites.net/monacoeditor.html
Build and formatting with Intellisense  that supports c# using roslyn. There is no need to implement extra language server* , application is .net Core 3.0, Currently intellisense works slow because I am not caching resolved libraries each call evaluates all front end code again. 

*Front end posts code to back-end and get compilation evaluation result. Language server implementation described as dependent libraries are overhead. This is just simple demonstration solution for c#. 

![image](https://user-images.githubusercontent.com/2394360/76124291-5c9b4900-5fc8-11ea-8f62-52c9c5d64e10.png)

**Comment by akshay-zz** [comment]
@satyajit-behera I have recently created intelligence for Csharp . You can check out the project [here].(https://github.com/akshay-zz/Intellisense)  <br>
I have also added a working demo. Hope this will help you.

**Comment by enragez** [comment]
@karayakar Can you post your back-end code please?

**Comment by tavisca-skhaire** [comment]
@karayakar Can you please post your back-end code?

**Comment by karayakar** [comment]
@enragez @tavisca-skhaire 

from below method you can get an idea of implementation. When I have time I'll publish full code. There is a separate nuget package downloader you can skip that.


		public static dynamic CompileRos(SourceInfo sourceInfo)
        {
            var usings = new List<string>();
            var allusingsInCode = sourceInfo.SourceCode.Split(new string[] { "using " }, StringSplitOptions.None);
            foreach (var item in allusingsInCode)
            {
                if (!String.IsNullOrWhiteSpace(item))
                {
                    usings.Add(item.Split(';')[0]);
                }
            }

            List<Assembly> assemblies = new List<Assembly>
        {
            Assembly.Load("Microsoft.CodeAnalysis"),
            Assembly.Load("Microsoft.CodeAnalysis.CSharp"),
            Assembly.Load("Microsoft.CodeAnalysis.Features"),
            Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features"),
        };

            var assembliesList = DownloadNugetPackages.LoadPackages(sourceInfo.Nuget);
            foreach (var item in assembliesList)
            {
                var fname = item.FullName.Split(',')[0];
                if (assemblies.Where(x => x.FullName.Split(',')[0] == fname).FirstOrDefault() == null)
                {
                    try
                    {

                        var asm = item.FullName.Split(',')[0];
                        var loadAssembly = Assembly.Load(asm);
                        assemblies.Add(loadAssembly);
                    }
                    catch (Exception ex)
                    {
                        //assemblies.Add(item);
                    }
                }
            }

            var assembliest = AppDomain.CurrentDomain.GetAssemblies()
                      .Where(a => !a.IsDynamic && File.Exists(a.Location));
            //MefHostServices.DefaultAssemblies.AddRange (assembliest);

            var partTypes = MefHostServices.DefaultAssemblies.Concat(assemblies)
                    .Distinct()?
                    .SelectMany(x => x?.GetTypes())?
                    .ToArray();

            var compositionContext = new ContainerConfiguration()
                .WithParts(partTypes)
                //.WithAssemblies(assemblies)
                //.WithAssemblies(assembliest)
                .CreateContainer();

            var host = MefHostServices.Create(compositionContext);

            var workspace = new AdhocWorkspace(host);

            var scriptCode = sourceInfo.SourceCode;// "Guid.N";

            var _ = typeof(Microsoft.CodeAnalysis.CSharp.Formatting.CSharpFormattingOptions);

            var compilationOptions = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, usings: usings);

            if (_ref == null || _ref.Length == 0)
            {



                //.GroupBy(a => a.GetName().Name)
                //.Select(grp =>
                //     grp.First(y => y.GetName().Version == grp.Max(x => x.GetName().Version)))
                //.Select(a => MetadataReference.CreateFromFile(a.Location));


                MetadataReference[] _refs2 = assembliest
                 .Select(asm => MetadataReference.CreateFromFile(asm.Location))
                 .ToArray();

                MetadataReference[] _refs = assembliesList
                 .Select(asm => MetadataReference.CreateFromFile(asm.Location))
                 .ToArray();


                _ref = new MetadataReference[0];

                try
                {

                    try
                    {
                        foreach (var item in DependencyContext.Default.CompileLibraries)
                        {
                            try
                            {
                                var arr = item.ResolveReferencePaths().Select(asm => MetadataReference.CreateFromFile(asm))?
                         .ToArray();
                                _ref = _ref.Concatenate(arr);
                            }
                            catch (Exception ex)
                            {


                            }

                        }

                    }
                    catch (Exception ex)
                    {

                    }



                }
                catch (Exception ex)
                {

                }
                _ref = _ref.Concatenate(_refs);
                _ref = _ref.Concatenate(_refs2);

            }
            if (_ref != null && _ref.Length > 0)
            {
                _ref = _ref.Concatenate(new[]
                 {
                  MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
                  });
                var scriptProjectInfo = ProjectInfo.Create(ProjectId.CreateNewId(), VersionStamp.Create(), "Script", "Script", LanguageNames.CSharp, isSubmission: true)
                    .WithMetadataReferences(_ref)
                   .WithCompilationOptions(compilationOptions);


                var scriptProject = workspace.AddProject(scriptProjectInfo);
                var scriptDocumentInfo = DocumentInfo.Create(
                    DocumentId.CreateNewId(scriptProject.Id), "Script",
                    sourceCodeKind: SourceCodeKind.Script,
                    loader: TextLoader.From(TextAndVersion.Create(SourceText.From(scriptCode), VersionStamp.Create())));
                var scriptDocument = workspace.AddDocument(scriptDocumentInfo);

                // cursor position is at the end
                var position = sourceInfo.LineNumberOffsetFromTemplate;// scriptCode.Length - 1;

                var completionService = CompletionService.GetService(scriptDocument);

                var results = completionService.GetCompletionsAsync(scriptDocument, position).Result;
                if (results == null && sourceInfo.LineNumberOffsetFromTemplate < sourceInfo.SourceCode.Length)
                {

                    sourceInfo.LineNumberOffsetFromTemplate++;
                    CompileRos(sourceInfo);
                }

                if (sourceInfo.SourceCode[sourceInfo.LineNumberOffsetFromTemplate - 1].ToString() == "(")
                {
                    sourceInfo.LineNumberOffsetFromTemplate--;
                    //CompileRos(sourceInfo);
                    results = completionService.GetCompletionsAsync(scriptDocument, sourceInfo.LineNumberOffsetFromTemplate).Result;


                }
                //Method parameters

                List<string> overloads = GetMethodParams(scriptCode, position);
                if (overloads != null && overloads.Count > 0)
                {

                    ImmutableArray<CompletionItem>.Builder builder = ImmutableArray.CreateBuilder<CompletionItem>();
                    foreach (var item in overloads)
                    {
                        string DisplayText = item;
                        string insertText = item.Split('(')[1].Split(')')[0];
                        CompletionItem ci = CompletionItem.Create(insertText, insertText, insertText);
                        builder.Add(ci);

                    }

                    if (builder.Count > 0)
                    {
                        ImmutableArray<CompletionItem> itemlist = builder.ToImmutable();
                        return CompletionList.Create(new Microsoft.CodeAnalysis.Text.TextSpan(), itemlist);

                    }
                }

                return results;
            }
            return null;
        }

**Comment by enragez** [comment]
@karayakar thanks, really useful

**Comment by Augustukas** [comment]
@karayakar please publish whole code :)

**Comment by Cch25** [comment]
@karayakar could you please publish the entire code, it would be really useful. Thanks

**Comment by Augustukas** [comment]
My take on karayakar back end code.

        using Microsoft.CodeAnalysis;
        using Microsoft.CodeAnalysis.Completion;
        using Microsoft.CodeAnalysis.CSharp;
        using Microsoft.CodeAnalysis.Host.Mef;
        using Microsoft.CodeAnalysis.Text;
        using System;
        using System.Web;
        using System.Collections.Generic;
        using System.Collections.Immutable;
        using System.Composition.Hosting;
        using System.IO;
        using System.Linq;
        using System.Reflection;
        using System.Threading;
        using System.Threading.Tasks;

        namespace RouteHandlers
        {
            [RouteUrl("api/getautocompletedata/csharp")]
            public class ScriptsAutocomplete : ReusableRouteHandlerBase
            {
                protected override void Process(RequestContext ctx)
                {
                    try
                    {
                        ctx.Response.Cache.SetNoStore();
                        ctx.Response.ContentType = "application/json";

                        SourceInfo sourceInfo = new SourceInfo();
                        sourceInfo.SourceCode = Convert.ToString(ctx.JsonParameters["SourceCode"]) + "\r\n///";
                        sourceInfo.LineNumberOffsetFromTemplate = Convert.ToInt32(ctx.JsonParameters["lineNumberOffsetFromTemplate"]);

                        var suggestions = GetSuggestions(sourceInfo);
                        JSON.Serializer.Serialize(ctx.Response.Output, suggestions);

                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex);
                        throw;
                    }
                }

                public static CompletionList GetSuggestions(SourceInfo sourceInfo)
                {
                    AdhocWorkspace workspace = CreateWorkspace();
                    MetadataReference[] references = CreateReferences();
                    CompletionList suggestions = null;

                    if (references != null && references.Length > 0)
                    {
                        List<string> usings = createUsingsFromSource(sourceInfo);

                        var compilationOptions = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, usings: usings);

                        Document scriptDocument = SetupWorkspaceDocument(sourceInfo, workspace, references, compilationOptions);

                        var completionService = CompletionService.GetService(scriptDocument);

                        suggestions = completionService.GetCompletionsAsync(scriptDocument, sourceInfo.LineNumberOffsetFromTemplate).Result;
                        if (suggestions == null && sourceInfo.LineNumberOffsetFromTemplate < sourceInfo.SourceCode.Length)
                        {
                            sourceInfo.LineNumberOffsetFromTemplate++;
                            GetSuggestions(sourceInfo);
                        }

                        if (sourceInfo.SourceCode[sourceInfo.LineNumberOffsetFromTemplate].ToString() == "(")
                        {
                            sourceInfo.LineNumberOffsetFromTemplate--;
                            suggestions = completionService
                                .GetCompletionsAsync(scriptDocument, sourceInfo.LineNumberOffsetFromTemplate).Result;
                        }

                    }

                    return suggestions;
                }

                private static Document SetupWorkspaceDocument(SourceInfo sourceInfo, AdhocWorkspace workspace, MetadataReference[] references, CSharpCompilationOptions compilationOptions)
                {
                    var scriptProjectInfo = ProjectInfo.Create(
                                        ProjectId.CreateNewId(),
                                        VersionStamp.Create(),
                                        "Script", "Script",
                                        LanguageNames.CSharp,
                                        isSubmission: true)
                                    .WithMetadataReferences(references)
                                    .WithCompilationOptions(compilationOptions);


                    var scriptProject = workspace.AddProject(scriptProjectInfo);
                    var scriptDocumentInfo = DocumentInfo.Create(
                        DocumentId.CreateNewId(scriptProject.Id),
                        "Script",
                        sourceCodeKind: SourceCodeKind.Script,
                        loader: TextLoader.From(TextAndVersion.Create(SourceText.From(sourceInfo.SourceCode), VersionStamp.Create())));
                    var scriptDocument = workspace.AddDocument(scriptDocumentInfo);
                    return scriptDocument;
                }

                private static MetadataReference[] CreateReferences()
                {
                    var references = new MetadataReference[0];
                    if (references == null || references.Length == 0)
                    {
                        MetadataReference[] innerReferences = AppDomain.CurrentDomain.GetAssemblies()
                            .Where(a => !a.IsDynamic && File.Exists(a.Location))
                            .Select(asm => MetadataReference.CreateFromFile(asm.Location))
                            .ToArray();

                        references = references.Concat(innerReferences).ToArray();
                    }

                    if (references != null && references.Length > 0)
                    {
                        references = references.Concat(new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) }).ToArray();
                    }

                    return references;
                }

                private static AdhocWorkspace CreateWorkspace()
                {
                    List<Assembly> assemblies = new List<Assembly>
                                            {
                                                Assembly.Load("Microsoft.CodeAnalysis, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"),
                                                Assembly.Load("Microsoft.CodeAnalysis.CSharp, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"),
                                                Assembly.Load("Microsoft.CodeAnalysis.Features, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"),
                                                Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features, Version=1.3.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"),
                                            };



                    var partTypes = MefHostServices.DefaultAssemblies.Concat(assemblies)
                        .Distinct()
                        .SelectMany(x => x.GetTypes())
                        .ToArray();

                    var compositionContext = new ContainerConfiguration()
                        .WithParts(partTypes)
                        .CreateContainer();

                    var host = MefHostServices.Create(compositionContext);
                    var workspace = new AdhocWorkspace(host);
                    return workspace;
                }

                private static List<string> createUsingsFromSource(SourceInfo sourceInfo)
                {
                    var usings = new List<string>();

                    var allusingsInCode = sourceInfo.SourceCode.Split(new string[] { "using " }, StringSplitOptions.None);
                    foreach (var item in allusingsInCode)
                    {
                        if (!String.IsNullOrWhiteSpace(item))
                        {
                            usings.Add(item.Split(';')[0]);
                        }
                    }

                    return usings;
                }
            }


            public class SourceInfo
            {
                public string SourceCode { get; set; }
                public string Nuget { get; set; }
                public Int32 LineNumberOffsetFromTemplate { get; set; }
            }



        }

**Comment by karayakar** [comment]
Hello friends,
you can clone from my repo.  https://github.com/karayakar/monacoeditor

[](https://github.com/karayakar/monacoeditor)

**Comment by CuriousDrive** [comment]
Peeps,

There's this repo too. It worked for me - https://github.com/dotnetprojects/MonacoRoslynCompletionProvider

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
