### ISSUE TITLE
Cmd+Y (redo) opens the History tab in Chrome

### ISSUE THREAD

**Issue by azcn2503** [Microsoft/monaco-editor#578]
monaco-editor version: 0.10.0
Browser: Chrome 60.0.3112.113
OS: Mac OS Sierra
Steps or JS usage snippet reproducing the issue:

* Go to the [demo page](https://microsoft.github.io/monaco-editor/) and type some text
* press Cmd+Z to undo - undo is executed successfully
* press Cmd+Y to redo - History tab opens, redo is not executed

Update: I notice that Cmd+Shift+Z works. Is there a way to configure Monaco so that Cmd+Y works?

**Comment by alexandrudima** [comment]
Here is one way to do it:

* Paste at https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-a-command-to-an-editor-instance
```
var jsCode = [
    '// Type something and then hit Tab to undo!',
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

editor.addCommand(monaco.KeyCode.Tab, function() {
    editor.trigger('blablabla', 'undo');
});

```

**Comment by azcn2503** [comment]
Thanks :smile:
