### ISSUE TITLE
Please create monaco.github.io as IDE for github

### ISSUE THREAD

**Issue by Thaina** [microsoft/monaco-editor#58]
I would like to write code in monaco on github into github. Github has all api to let us work on browser directly. So we could just have github.io host monaco and it would be the best IDE in the world

**Comment by nojvek** [comment]
That would be really cool. Showing the github file list as tree on left and being able to edit code and commit right from browser would be nice.

I'm happy to hack on this if someone is willing to help. Its going to be a great learning exercise to understand how monaco and VSCode work under the hood.

**Comment by creationix** [comment]
I made something similar using the ace editor.  This actually went a bit farther and synced all the git objects locally (in indexeddb) for offline editing and then could later sync up with git using their API.

https://tedit.creationix.com/ - https://github.com/creationix/tedit

**Comment by Thaina** [comment]
I too made my own prototype here

https://editing.github.io/

Was playing around with github pages and found that, we could write github page for organization. And make gh-pages for project under that organization, then that project will became a path of that org.github.io

And that project could reuse whole library from the organization domain

I was made  [cloudant project page](https://github.com/editing/cloudant) into https://editing.github.io/cloudant/ and it has only index.html/js. It reference monaco from my [editing organization page](https://github.com/editing/editing.github.io)

**Comment by eribertt** [comment]
Hi there any update to this?

**Comment by phil294** [comment]
Since Github now even belongs to Microsoft, will this be done?

**Comment by rcjsuen** [comment]
Does [Gitpod](https://www.gitpod.io/) satisfy this use case?

**Comment by Thaina** [comment]
This seem to be already done as github.dev with vscode
