### ISSUE TITLE
findMatches, findNextMatch and findPreviousMatch have incorrect typings

### ISSUE THREAD

**Issue by gatesn** [Microsoft/monaco-editor#580]
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ireadonlymodel.html#findmatches

The docs state to pass `null` for `wordSeparators` to avoid forcing full word matches, but the typings do not allow nulls.

**Comment by alexandrudima** [comment]
PR welcome.

**Comment by alexandrudima** [comment]
[PR welcome](https://github.com/Microsoft/vscode/blob/27e9d4c196fb38edc3a630732dd221c7aaff7634/src/vs/editor/common/editorCommon.ts#L693).

**Comment by rcjsuen** [comment]
I think this can be closed since #44353 got merged. Thanks for the help, @alexandrudima!
