### ISSUE TITLE
Link to Monaco on CDN

### ISSUE THREAD

**Issue by vanillajonathan** [microsoft/monaco-editor#583]
It would be convenient if Monaco was hosted one or more CDNs and that the Monaco website had references to the CDNs.

Could it get hosted on the Microsoft JavaScript CDN?
https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview

Hosted at:
* https://cdnjs.com/libraries/monaco-editor
* https://unpkg.com/monaco-editor@0.10.0/min/vs/loader.js
* https://cdn.jsdelivr.net/npm/monaco-editor@0.10.0/min/vs/loader.js

**Comment by NiloCK** [comment]
As I understand it, this isn't feasible. Monaco relies on dispatching webworkers for much of its functionality. Browsers don't like spawning webworkers from external domains (eg, CDNS) for security reasons.

**Comment by vanillajonathan** [comment]
I see. Maybe Yarn or Bower should be mentioned in that case?

https://yarnpkg.com/en/package/monaco-editor

**Comment by alexandrudima** [comment]
Loading from a CDN should work fine if you spawn the web workers on a same-origin script and then import the monaco web worker code from a CDN.

See https://github.com/Microsoft/monaco-editor#integrate-cross-domain

**Comment by alexdima** [comment]
We now have built-in support for cross domain web workers in the `amd` case, so loading from a CDN should work fine out of the box.

**Comment by vanillajonathan** [comment]
@alexdima 
> We now have built-in support for cross domain web workers in the `amd` case, so loading from a CDN should work fine out of the box.

Great, can the Monaco team get it hosted on CDNs now (maybe Microsofts own CDN)?
With links from the Monaco website to the CDN?

**Comment by alexdima** [comment]
@vanillajonathan There are multiple CDNs that already do this as you already pointed out. We have no plans to add another one from Microsoft.

**Comment by vanillajonathan** [comment]
@alexdima It's a bit odd that Microsoft have their own CDN yet Monaco is not available from it.
Also, it would be nice if the Monaco website linked to one of the existing CDNs so you could find information on the Monaco website on how to embed it.
