### ISSUE TITLE
How to insert text into mouse cursor

### ISSUE THREAD

**Issue by lwinhong** [Microsoft/monaco-editor#584]
monaco-editor version: 0.10.0
Browser: CEF3
OS: win10 x64
Steps or JS usage snippet reproducing the issue:

How do I use js to insert text at the mouse cursor

**Comment by lwinhong** [comment]
i found use editor.executeEdits
https://github.com/Microsoft/monaco-editor/issues/172
https://github.com/Microsoft/monaco-editor/issues/192

**Comment by Panhaiwei** [comment]
@lwinhong  How do you insert it at the cursor position?

**Comment by lwinhong** [comment]
@Panhaiwei 我是这样写的
`var insertTextToEditor = function(value) {
    if (monacoEditor) {
        monacoEditor.focus();

        var result = getVText(value);
        var p = monacoEditor.getPosition();
        monacoEditor.executeEdits("",
            [
                {
                    range: new monaco.Range(p.lineNumber,
                        p.column,
                        p.lineNumber,
                        p.column),
                    text: result
                }
            ]
        );
    }
};`

**Comment by Panhaiwei** [comment]
@lwinhong  谢谢
