### ISSUE TITLE
How do I insert text at the cursor position of the mouse?

### ISSUE THREAD

**Issue by Panhaiwei** [Microsoft/monaco-editor#585]
monaco-editor version: 0.10.0
Browser:Google Chrome
OS: windows 7
////
How do I insert text at the cursor position of the mouse?

**Comment by H3dz** [comment]
I use this

`editor.trigger('keyboard', 'type', {text: "test"});`

**Comment by Panhaiwei** [comment]
@H3dz Thank you very much. I have solved the problem.
