### ISSUE TITLE
Custom event trigger

### ISSUE THREAD

**Issue by Theo-** [microsoft/monaco-editor#588]
Hi,

I am using the `registerCodeLensProvider`. However, my code lense provider calls a server-side endpoint and then register the message.

I would like to be able to trigger a render of code lenses, to show the server-side rendered text. Is there any way I can trigger an event to make the editor re-render those code lenses?

**Comment by alexandrudima** [comment]
`CodeLensProvider` can have an `onChange` event. See https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.codelensprovider.html:

```ts
    export interface CodeLensProvider {
        onDidChange?: IEvent<this>;
        provideCodeLenses(model: editor.IReadOnlyModel, token: CancellationToken): ICodeLensSymbol[] | Thenable<ICodeLensSymbol[]>;
        resolveCodeLens?(model: editor.IReadOnlyModel, codeLens: ICodeLensSymbol, token: CancellationToken): ICodeLensSymbol | Thenable<ICodeLensSymbol>;
    }
```
