### ISSUE TITLE
Avoid text completions for a custom language if a specialized CompletionItemProvider is registered

### ISSUE THREAD

**Issue by Matthias247** [Microsoft/monaco-editor#59]
I have written a custom completion provider and registered it with `registerCompletionItemProvider` at Monaco. It is working just fine.

However if I don't have completions and return an empty list from the provider Monaco seems to ask another provider and returns the list of all tokens in the editor window. Can this somehow be disabled in order to let Monaco really show no suggestions for that place?

**Comment by jrieken** [comment]
There is a setting `editor.wordBasedSuggestions` which controls this.

**Comment by Matthias247** [comment]
@jrieken Thanks. I can see this setting in VS Code. But I don't see where to apply it in monaco. Passing `wordBasedSuggestions: false` to monaco.editor.create does not work and monaco.d.ts does not list the setting at all. Any additional hint?

**Comment by jrieken** [comment]
That's true - it's only exposed via the configuration service but not yet as an explicit editor setting

**Comment by aarinsmith** [comment]
@jrieken can you tell me how I would go about setting this to false through the configuration service? I don't seem to be able to see how I can turn off the word based suggestions.

**Comment by jrieken** [comment]
We don't expose the configuration service here but 're-export' each editor specific setting via the editor. We must do the same once again for this setting

**Comment by jrieken** [comment]
fix in https://github.com/Microsoft/vscode/commit/4d37b86195ec077eca40ab3abc290bde4b69bcf5

**Comment by zanecat** [comment]
Oops, still have this problem. I set wordBasedSuggestions to false but when my provider returns nothing the editor will popup word based suggestions according to the existing input.
