### ISSUE TITLE
DragAndDrop from Outside

### ISSUE THREAD

**Issue by frenkiesmart** [microsoft/monaco-editor#590]
Hello everyone

I see that DragAndDrop is available from Version 0.9. But this works only whe dragging the content inside the editor. How can we enable DragAndDrop from outside the Editor. I tried the mouse events, but the only information there is e.target, but nothing like e.source? How can I find out what is being dragged into the Editor?

**Comment by sajorgee** [comment]
Ace editor have something like this; check following example: https://plnkr.co/edit/Gv6pN3oJBj17906PKcZX?p=preview

**Comment by hediet** [comment]
This is now supported:

http://localhost:8080/playground.html?source=v0.35.0#XQAAAALAAwAAAAAAAABBqQkHQ5NjdTxLeHhepyeply1uewY4Eqs_V-0yaEJ1UdzWFC7yLjY8rwW48ZJpa0Hdy499NeF2gY2h-y85vIlyAuYfc4eWDb70K05WHH8kTXmTkbs0me_mFV4i_2E3PUapLMsp0esUU8UxJ_bFI-BjEijumZDggnFVgLifjEt8FfZj548al9u8sri-bW4HQztnCD6CqGMEn76IfKcaIxm86--UsdWHVDMuvEbP16Et80Gy2iOPzEkk4MpqW2bbXgt97UTGB3VHLaMPNPlofG18z8TnWpSVulIoKGVhkmZbyw1emIeWafau_pExm7djmPwyqvJNm31zmPEVqd_6exLj0DZhyQ4vBlldjPU6tyBVvI6-6Vzsb4k5AgBfWx_8wdSgxiQQ8kDhwJbJoCbWPV5JrSbhCOkuSpo0Wth8FPiWZ2bGhzQJavxoI5BXc6W_CfK_DNJyt917zwbbxDvy72DMDMRc3atLAEvBH5JvEaU6qc1o_i6NRTtwm7xJl4NCnLJjxez-Sz03NA6UQGfhrkbtTpgZiPQaDaImBEdlOs0ha5ocb4umgxe1HFceh5O4ErRjx5RfKz880tpxyjutNFBjV80sUlipdyGO029FRECx-phIIw7Y2X7Wv8QMpiX9owM9_wtrUPxuRQZHtJMb5VNSmML7xg9N5IhjexzY4K017zRO1CN4sB05_W_SjUrm8WhIouRt4bSDRq5WQZ19mbgvt-enGk8DwDRnGVpqX5KmRIPZNfiz_5G--sjVvNH-4-TDOLC1RldTXc8lnk0YtxG5lHDDHBx6BNGEz7MW-sg5QHb_yFHpdg
