### ISSUE TITLE
The constructor shorthand property gets assigned twice when explicitly declared inside the `constructor` body

### ISSUE THREAD

**Issue by serbanghita** [Microsoft/monaco-editor#591]
monaco-editor version: the online version
Browser: Version 61.0.3163.100 (Official Build) (64-bit)
OS: Mac OS
Steps or JS usage snippet reproducing the issue:

The constructor shorthand property gets assigned twice if I explicitly assign `this.form = form;` in the constructor. Is this an expected behaviour?

1. Go to [link](http://www.typescriptlang.org/play/index.html#src=class%20MyService%20%7B%0D%0A%20%20%20%20constructor(private%20form%3A%20HTMLFormElement)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.form%20%3D%20form%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

or write the following code in the TypeScript Playground:

```typescript
class MyService {
    constructor(private form: HTMLFormElement) {
        this.form = form;
    }
}
```

the output will be

```javascript
var MyService = /** @class */ (function () {
    function MyService(form) {
        this.form = form;
        this.form = form;
    }
    return MyService;
}());
```

Expected output:

```javascript
var MyService = /** @class */ (function () {
    function MyService(form) {
        this.form = form;
    }
    return MyService;
}());
```

**Comment by alexandrudima** [comment]
This is how the TypeScript compiler behaves. When you use `constructor(private form: HTMLFormElement)` the TS compiler will emit the assignment for you. So the line `this.form = form` is redundant.

Use:
```ts
class MyService {
    constructor(private form: HTMLFormElement) {
    }
}
```
