### ISSUE TITLE
The `noLib` editor option still returns some autocomplete items

### ISSUE THREAD

**Issue by probablycorey** [Microsoft/monaco-editor#596]
monaco-editor version: The version used in the Monaco sandbox at https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults
Browser: Chrome 61
OS: macOS Sierra 

I'm trying to get Monaco to only return completion items that I specify. This mostly works by using `monaco.languages.typescript.javascriptDefaults.setCompilerOptions({ noLib: true,  allowNonTsExtensions: true });` but I still get some JS completions, shown below:

![monaco editor playground 2017-10-02 11-12-45](https://user-images.githubusercontent.com/596/31092253-a42be4d0-a762-11e7-8470-724f147cd4f2.png)

Is this not the correct way to remove all the default completion items, or is this a bug?

You can recreate this by adding the line `monaco.languages.typescript.javascriptDefaults.setCompilerOptions({ noLib: true,  allowNonTsExtensions: true });` to the sandbox file in https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults

**Comment by programmingforthepuzzled** [comment]
Any update on this issue?

**Comment by jrieken** [comment]
> Is this not the correct way to remove all the default completion items, or is this a bug?

That is keyword completion which is unrelated to `noLib` which is only about symbol completions.

**Comment by joshuathompson** [comment]
@jrieken @alexandrudima is there any way to disable keyword completion without a custom build of monaco-editor? The `noLib` option clearly isn't right, but is there some hidden option that we can use?

**Comment by VasilisNikiforidis** [comment]
If you create custom completion items with registerCompletionItemProvider, the list you create should overwrite the default one, so you will not get any suggestions. Happened to me while I was trying to merge the list with my own custom suggestions

**Comment by sagho0or** [comment]
Any update on this issue?
