### ISSUE TITLE
Should call .preventDefault on click events fired from embedded links in the Intellisense popup

### ISSUE THREAD

**Issue by TimHambourger** [microsoft/monaco-editor#597]
monaco-editor version: 0.10.0
Browser: Chrome 61.0.3163.100
OS: Windows 10 Pro 14393.447
Steps or JS usage snippet reproducing the issue:

When using `LanguageServiceDefaults.addExtraLib` with a Javascript editor, I'm finding it handy to embed html links into the doc comments in my custom d.ts file:
```js
monaco.languages.typescript.javascriptDefaults.addExtraLib([
    '/**',
    ' * Creates a new wrapper around MomentJS.',
    ' * See https://momentjs.com/docs/',
    ' */',
    ' declare function MomentWrapper(): any;'
].join('\n'));

monaco.editor.create(document.getElementById('container'), {
    value: [
        '// Hover over \'MomentWrapper\' then click the provided link!',
        'MomentWrapper();'
    ].join('\n'),
    language: 'javascript'
});
```
This renders a nice link in the Intellisense popup (which, I should add, is an awesome feature).

However, Monaco currently doesn't call `.preventDefault()` on the click event triggered by this link, with the effect that my site navigates to '#'. I'm embedding Monaco in a large single-page app, so this triggers my client-side routing and destroys the user's editing context.

For now, I'm working around this via:
```js
this.editor.getDomNode().addEventListener('click', e => {
    if (e.target.tagName.toLowerCase() === 'a' && e.target.href) {
        // preventDefault on click events fired from links within the Intellisense popup
        e.preventDefault();
    }
});
```

But this feels like something Monaco should handle out of the box.

**Comment by alexdima** [comment]
I can no longer reproduce this, so I believe it was fixed in the meantime.
