### ISSUE TITLE
Minimap doesn't respect visibility settings in diff editor

### ISSUE THREAD

**Issue by IMcD23** [Microsoft/monaco-editor#598]
monaco-editor version: 0.10.0
Browser: Safari 11
OS: macOS
Steps or JS usage snippet reproducing the issue:
I'm constructing a monaco diff editor using roughly the following code. With the minimap setting's `enabled` property set to false, a minimap is still shown in the editor. Anything I can try?

```
        const editor = monaco.editor.createDiffEditor(
            document.getElementById("container"),
            {
            lineNumbers: "off",
            minimap: {
                enabled: false
            },
            scrollbar: {
                horizontalScrollbarSize: 5,
                verticalScrollbarSize: 5
            },
            scrollBeyondLastLine: true,
            wordWrap: "off",
            fontFamily: "SFMono",
            fontSize: 12,
            theme: "vs-dark",
            renderSideBySide: false,
            readOnly: true,
            }
        );

        editor.setModel({
            original: monaco.editor.createModel(file1Value, undefined, monaco.Uri.parse(file1)),
            modified: monaco.editor.createModel(file2Value, undefined, monaco.Uri.parse(file2))
        });
```
<img width="451" alt="screen shot 2017-10-04 at 9 33 27 pm" src="https://user-images.githubusercontent.com/1221567/31211152-b8ba667a-a94b-11e7-8537-1cc68cee001f.png">

**Comment by IMcD23** [comment]
Upon further investigation, this is not a minimap, but instead a "diff overview ruler". It's working as intended.

**Comment by Luiz-N** [comment]
@IMcD23 did you find a way to disable or edit this diff ruler somehow?
