### ISSUE TITLE
Node.js render for unit/snapshot testing

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/monaco-editor#599]
Hi, is it somehow possible to load monaco and render on server (in node.js). 
I want to save the rendered html into a snapshot for unit testing.

I tried to bend the AMD loader but no luck.
I have never used it before so am having problems.

**Comment by alexandrudima** [comment]
Here I am doing it for the tests of `monaco-languages` which use the tokenization part of the editor: https://github.com/Microsoft/monaco-languages/blob/master/test/all.js#L1

The rendering part might fail.

**Comment by tomitrescak** [comment]
Looks intriguing .. will give it a go and reopen if necessary,
