### ISSUE TITLE
Create ES6-Compliant Distribution

### ISSUE THREAD

**Issue by fedoranimus** [Microsoft/monaco-editor#60]
While AMD is useful, it can be a pain to use in modern web applications, especially those using Typescript.

It would be excellent for this project to support an ES6 Distribution so that the following syntax (or similar) can be used:
`import * as monaco from 'monaco-editor'`

This would greatly ease the difficulty of implementing this tool moving forward and also help it stay standards-compliant.

Edit: Grammar

**Comment by marxo** [comment]
This would be preferable to existing solutions. We're using Meteor and using AMD modules results in conflict with other modules sometimes. Can @alexandrudima or someone else from the team explain why this would be difficult to integrate as labeled?

**Comment by alexandrudima** [comment]
Sorry, I struggled with the label name.

I tried to classify issues that concern how easy/difficult it is for the editor to be consumed/integrated.

**Comment by PascalPrecht** [comment]
Can we expect an update on this soon? Unfortunately, I'm not very familiar with module loading approaches, so I won't be a great help here when it comes to contributions... however, since this issue is a couple of months old, I'm wondering if there's any progress here.

Otherwise I'll see if there are other alternatives. But I think too that for Monaco's adoption, getting rid off AMD dependency is a good idea.

**Comment by DinkDonk** [comment]
This should absolutely get top priority. Would love to be able to - sanely - use monaco in a TypeScript environment.

**Comment by jarben** [comment]
Any updates on this?

**Comment by jurajhrib** [comment]
+1

**Comment by jiron12** [comment]
+1

**Comment by devmondo** [comment]
+1

**Comment by nadavwix** [comment]
+1

**Comment by MatxBerg** [comment]
+1

**Comment by NeekSandhu** [comment]
I think the one of the main reasons `monaco` is AMD based is probably because how it handles `Worker`s. `monaco` internally uses `require.toUrl` to resolve paths to worker files. It'd huge progress towards this goal if `monaco` "outsources" this mechanism instead of doing it by itself.

**Comment by alexandrudima** [comment]
Done with #18
