### ISSUE TITLE
Snippet syntax for tabstops not working in completion items

### ISSUE THREAD

**Issue by foxable** [Microsoft/monaco-editor#602]
monaco-editor version: 0.10.1
Browser: IE, Chrome, Firefox
OS: Windows

I recently upgraded from monaco-editor 0.8.3 and was using completion items using the old snippet syntax to mark the new cursor position (`{{}}`) in the insertText. As can be read in the [Release Notes](https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md), monaco now uses a [new Snippet Syntax](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax). However, when trying to mark a cursor position with either `$1` or `${1}`, this placeholder does not seem to be parsed at all. It is inserted as plain text and the cursor gets placed at the end of the insertText. This can be reproduced with the [completion provider example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example) in the Playground.

**Comment by salcosta** [comment]
Also seeing the same issue, tab stops do not function and it looks like the Markdown parse does not function correctly either.

Thought the solution would be to create new SnippetString but the interface is not exposed in `languages` as was expected.

**Comment by salcosta** [comment]
Found a resolution in case anyone else is looking by setting the value of `insertText` to an object with a value property.

    insertText: {
	    value: 'foo(${1:bar},frob)'
    }

**Comment by foxable** [comment]
Thank you, good finding. I didn't realize the `insertText` API got extendend until you mentioned it. According to the API DOC, an `insertText` can either be of type `string` or [`SnippetString`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.snippetstring.html).

Nevertheless, I still find it confusing that we need a different type to define an `insertText` containing snippet syntax. The referenced [Grammar](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) explicitly allows escaping `$`. So, is the additional type just there to improve performance by avoiding unnecessary parsing?
