### ISSUE TITLE
`wordSeparators` doesn't work as expected

### ISSUE THREAD

**Issue by JacobEvelyn** [Microsoft/monaco-editor#603]
monaco-editor version: 0.10.1
Browser: Safari
OS: macOS

When I pass in a `wordSeparators` param into `monaco.editor.create()` I expect those separators to be used to separate words, but it appears that for things that use `getWordAtPosition()` (which is a lot of things) those separators aren't taken into account and the default separators are always used, because there's no way for the parameter to [createWordRegExp()](https://github.com/Microsoft/vscode/blob/0aee8cee1af618a6083c5f6c3c356d6de4549d82/src/vs/editor/common/model/wordHelper.ts#L18) to actually get passed in (the [only place it's used](https://github.com/Microsoft/vscode/blob/0aee8cee1af618a6083c5f6c3c356d6de4549d82/src/vs/editor/common/model/wordHelper.ts#L32) it's given no param).

This feels like a bug to me. Additionally I'm surprised that setting the separators is an option on the editor and not the language definition but there could be some context that I'm missing.

**Comment by alexandrudima** [comment]
`wordSeparators` are currently used for word navigation mostly (double click or ctrl + arrows).
`IModel.getWordAtPosition()` uses the word pattern as defined by the mode(language) currently associated with the model. 

The `wordPattern` is something each language defines in language configurations.

e.g. https://github.com/Microsoft/monaco-languages/blob/3c5417b252692cba96cf06fe14eb95c53a848715/src/java.ts#L13

**Comment by JacobEvelyn** [comment]
Thanks for the response! I'm not sure I follow though. When I use the [Monaco Playground custom language exampe](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages) and add this code:

```
monaco.languages.setLanguageConfiguration('mySpecialLanguage', {
    // Allow square brackets to be part of a word.
    wordPattern: /(-?\d*\.\d\w*)|([^\`\~\!\#\%\^\&\*\(\)\-\=\+\{\}\\\|\;\:\'\"\,\.\<\>\/\?\s]+)/g,
})
```

double-clicking on `[notice]` still doesn't highlight the square brackets as I'd expect. This matches what I saw in the code, where as I mentioned earlier it looks like [`createWordRegExp()` in `wordHelper.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/model/wordHelper.ts#L18) compiles the `RegExp` that actually controls this behavior, and yet it's hardcoded to only use `USUAL_WORD_SEPARATORS` regardless of the language configuration because no `allowInWords` argument is ever passed in. (All of the behavior I'm talking about is in `wordHelper.ts`.)

Does that make sense?

**Comment by alexandrudima** [comment]
@JacobEvelyn There are two distinct "word definitions".

---

### 1. One used for double clicking and word navigation (ctrl+arrows)
`` monaco.editor.create(..., { wordSeparators: '`~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?' }) ``
or
`` editorInstance.updateOptions({ wordSeparators: '`~!@#$%^&*()-=+[{]}\\|;:\'",.<>/?' }) ``

---

### 2. One defined by the language associated to the current buffer
This one is used in more places (in code) than the previous one.
```
monaco.languages.setLanguageConfiguration('mySpecialLanguage', {
    // Allow square brackets to be part of a word.
    wordPattern: /(-?\d*\.\d\w*)|([^\`\~\!\#\%\^\&\*\(\)\-\=\+\{\}\\\|\;\:\'\"\,\.\<\>\/\?\s]+)/g,
})
```
Notice here how `[` or `]` are not in the regex, so the cursor word highlights `[` and `]` too:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/5047891/33202733-e6597c86-d0fd-11e7-9958-7f2b6412a223.png">

---

Please change 1., or 2., or both to your liking.

P.S. It might seem very weird that there are two of them. I agree, initially we had only 2., but soon found that VS Code users want to navigate words according to their word separators list and not according to what makes necessarily an identifier in the language they are editing.

**Comment by JacobEvelyn** [comment]
Ah, I see, thanks! I was missing the fact that `wordHelper.ts` exports `DEFAULT_WORD_REGEXP` but `DEFAULT_WORD_REGEXP` can be overridden by passing those in.
