### ISSUE TITLE
Feature Request: Option for editor control to go full height and let container do the scrolling

### ISSUE THREAD

**Issue by Arlen22** [microsoft/monaco-editor#605]
monaco-editor version: 0.10.1
Browser: Chrome
OS: Windows 7

I would like to be able to specify that the monaco editor overflows its container such that the container is forced to deal with the overflow. I should be able to specify this in either direction or both, and editor would resize itself to make sure there is no scrollbar in that direction. The code to do it would not be hard, and it should not be enabled by default. 

I'm not talking about the container getting resized -- that's a separate issue that's been addressed ad nauseum. I want the container to resize to the desired height of the content so that the browser scrolls instead of the editor in the specified directions. 

The use case is that I want to use the editor in a note management app where the entire content of the note is edited in the normal position in a page instead of in a popup, etc. So I have a specified width, but I want the height to be the full height of the content, which the browser could easily do if the editor would stop setting its height according to the container and just set it so there is no scroll bar.

**Comment by alexdima** [comment]
Let's track in #794
