### ISSUE TITLE
Feature Request: hope to have a markers change event ?

### ISSUE THREAD

**Issue by linhuiw** [Microsoft/monaco-editor#607]
monaco-editor version: 0.10.1
Browser: Chrome
OS: Mac

Hope to have a event to know when modelMarkers changed?
so i can rapidly deal with this markers, or notice user?

Hope have a event, like i can write like this:
```javascript
this.editor.onDidChangeMarkers(evt => {
     const oldMarkers = evt.oldMarkers;
     const markers = monaco.editor.getModelMarkers();
     dealWithMarkers(markers);
});
```

**Comment by JKillian** [comment]
dup of https://github.com/Microsoft/monaco-editor/issues/313

**Comment by linhuiw** [comment]
#313

**Comment by linhuiw** [comment]
#313

**Comment by linhuiw** [comment]
@JKillian Tks.
