### ISSUE TITLE
Where can I find the complete tokenclass list

### ISSUE THREAD

**Issue by janryWang** [microsoft/monaco-editor#609]
These are just a very limited tokenclass list，I need more.
![image](https://user-images.githubusercontent.com/4060976/31853001-2076bae0-b647-11e7-8fae-4a44195dc1b1.png)

**Comment by janryWang** [comment]
@alexandrudima

**Comment by alexandrudima** [comment]
There is no complete token name list that we maintain.

You can get inspired by our default themes -- https://github.com/Microsoft/vscode/blob/913e891c34f8b4fe2c0767ec9f8bfd3b9dbe30d9/src/vs/editor/standalone/common/themes.ts#L13

Most of our built-in colorizers are defined in [`monaco-languages`](https://github.com/Microsoft/monaco-languages)
