### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by canaanjin** [Microsoft/monaco-editor#615]
I get an error message whenever I move cursor to the commented code in the  [editor](https://microsoft.github.io/monaco-editor/).
```
errors.ts:84 Uncaught Error: Cannot read property 'kind' of undefined

TypeError: Cannot read property 'kind' of undefined
```
I've tried many times.
![GIF](https://raw.githubusercontent.com/canaanjin/NETJQuery/master/GIF.gif)

![image](https://user-images.githubusercontent.com/12317236/32094498-7f0d9232-bb32-11e7-986d-4724ed245328.png)

monaco-editor version:  0.10.1
Browser: 62.0.3202Chrome
OS:  windows10
Steps or JS usage snippet reproducing the issue:

**Comment by rebornix** [comment]
Let's track it in #621.
