### ISSUE TITLE
i18n is not included

### ISSUE THREAD

**Issue by alexlur** [Microsoft/monaco-editor#616]
monaco-editor version: 0.10.1
Browser: Chrome
OS: High Sierra

**Expected behavior:**
Monaco Editor menus and other texts are localized according to the browser locale.

**Actual behavior:**
They are currently not.

**Comment by PyvesB** [comment]
Hello,

I am also facing the same issue. Not sure whether this is a bug or whether the locales have to be enabled in a different way.

Cheers,

Pyves

**Comment by alexandrudima** [comment]
The locale can be configured. Here is a full working sample that configures it to be in German:

https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-localized/index.html

The browser configured locale is something that reaches your servers via HTTP request headers. You can use that information in your server logic to detect which language the browser desires. Then, you can configure the monaco editor with that language.

**Comment by alexlur** [comment]
Thanks!

**Comment by courage007** [comment]
@alexandrudima sry to trouble you, but your link about configuring the editor's locale shows 404 error. Any suggest about configuring the editor's locale?
