### ISSUE TITLE
Couldn't read UTF-16 LE string

### ISSUE THREAD

**Issue by zanecat** [Microsoft/monaco-editor#617]
monaco-editor version: 0.10.0
Browser: Chrome
OS: OSX
Steps or JS usage snippet reproducing the issue:

When I set value to monaco editor, if the string is UTF16LE encoded, then there will be some unreadable things in monaco.
![image](https://user-images.githubusercontent.com/7372786/32157454-d0958f58-bd97-11e7-9fa0-0a9f5c74114e.png)

**Comment by alexandrudima** [comment]
@zanecat Encoding is something you need to deal with before you create a JavaScript string. i.e. you would have the same problem if you would use a simple `<textarea>` to display your data.

**Comment by zanecat** [comment]
Yep I noticed that it's my issue, sorry for this.
