### ISSUE TITLE
How to import module by require?

### ISSUE THREAD

**Issue by zhumaohua** [microsoft/monaco-editor#618]
```ts
monaco.languages.typescript.javascriptDefaults.addExtraLib([
"declare module 'foo' {",
" export default class bar {",
' public getDate():string;',
' }',
'}',
].join('\n'), 'foo.d.ts');

var jsCode = [
"var bar = rquire('foo')",
"var b = new bar();",
"var t = b.getDate();"
].join('\n');

monaco.editor.create(document.getElementById("container"), {
value: jsCode,
language: "javascript"
});
```
I declare a module and add to lib by addExtraLib method,and i import this module by require,but it not work ,how can do it?

**Comment by hediet** [comment]
I'm sorry it doesn't seem to be working, but with so many requests that we get here and in the [VS Code issue tracker](https://github.com/microsoft/vscode/issues), we just cannot provide the support we would like to offer.

You can try asking your question on [stackoverflow](https://stackoverflow.com/questions/tagged/monaco-editor).

That said, if you can track down your issue to a specific problem of the Monaco editor, we are more than welcoming a PR by the community! Please use the bug-report issue template to report the issue.

Thanks for your understanding!
