### ISSUE TITLE
Use in custom elements (web components)

### ISSUE THREAD

**Issue by claytongulick** [microsoft/monaco-editor#619]
With the way the css is being included, the editor can't be used in the shadow dom for a custom element. It would be great to be able to wrap this fantastic editor as a web component that could be easily reused in projects. That'll probably end up needing more architecture thought than just scoping the css though.

**Comment by eterna2** [comment]
I like that also. But it is tough. For the css, it is easy to just insert the style into the shadowroot.

But there is a lot of parts of the code that check against document.body or insert into the body. I managed to patch that part, but there are still many parts not working.

I am still looking thru the codes. The caret api to select text also dun exist in the shadowRoot.

I am not optimistic.

**Comment by alexandrudima** [comment]
AFAIK the blocker is that `document.caretRangeFromPoint` is not 100% working with shadow dom.

**Comment by claytongulick** [comment]
I've got it sort of hackishly wrapped, I put the editor container in the light dom, create the editor on connectedCallback and the whole thing goes into a slot in shadow. Working pretty well, but dependent on light dom and global monaco since I can't `import` it. This approach lets me wrap the api and use it as a component though, so good enough for now.

**Comment by eterna2** [comment]
Actually I made a polymer component already. 
https://github.com/PolymerVis/monaco-editor

Your approach only works if the components is used in the light Dom, but not when the component itself is used within another component.

So what I did is, if root is document.body, I do the same as what u did. Else I create an iframe inside the shadowRoot, then I proxy some of the common functions between the component and the iframe.

**Comment by simonh1000** [comment]
Per https://github.com/microsoft/monaco-editor/issues/1676 we also need to take into account the extra div being created outside of the webcomponent. I was looking at a monaco webcomponent so that I could use Monaco in an Elm program but this extra div seems to be affecting Elm's virtual dom handling

**Comment by codeStryke** [comment]
I'm currently working on wrapping monaco-editor in a web component for an internal product at work. I used https://github.com/microsoft/monaco-editor-samples/blob/master/browser-amd-shadow-dom/index.html and https://github.com/microsoft/monaco-editor/blob/master/test/shadow-dom.html for inspiration.

I notice a `<div class="monaco-aria-container">` on the `document` and I suspect it's being created by https://github.com/microsoft/vscode/blob/master/src/vs/base/browser/ui/aria/aria.ts. I'm wondering what is the intended use of this and what is it's impact if it leaks out of the `shadowRoot`? Any information / explanation is greatly appreciated and thank you for your time.

**Comment by alexdima** [comment]
@codeStryke That dom node is used for accessibility purposes. It has an `aria-live` role and it is used to "prompt" to screen readers.

**Comment by ernsheong** [comment]
Please allow seamless usage of Monaco in web components.

**Comment by simonh1000** [comment]
> That dom node is not visible.

Yes, but it breaks at least some virtual dom based renderers

**Comment by crackalak** [comment]
@alexdima is there a reason why the aria node can't be created using the `domElement` from the `StandaloneCodeEditor` constructor, instead of `document.body`?

https://github.com/microsoft/vscode/blob/476484061bd64a788d2f464e87b4972cf67f4a90/src/vs/editor/standalone/browser/standaloneCodeEditor.ts#L241

**Comment by alexdima** [comment]
:+1: PR welcome. A new property i.e. `ariaContainerElement` could be added to `IStandaloneEditorConstructionOptions`. Currently, `document.body` is used because the aria live element is shared between all editor instances.

**Comment by hediet** [comment]
We have an example now in the playground:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.35.0#XQAAAAIFBAAAAAAAAABBqQkHQ5NjdYzqEXhNewrSKZslyM_G2I4bTkHQYW1lB1MplPA6z0speGDFvgRIQQx0HI9zdEFZdk3ipJqwzu6RT44vPXZPcpCKxnvgE9TYAtuAi9VQr3EAhbQJCn4JPD8EaFYCtRcYWa8_pnHjN-uDjxrhmN3g8tmx0iWUz1zF7VMROnGNjfHj2TFmcBooqFj0KG-T22ZTMhTuebWAKwtN_PzaTmIn83sxr9iG_rCToVGZ0s8Aqq4FCtsWBjMFVvarCcsgdWatYDG40I2zD8RTtWuNHNnY7c7IoNZIQlbLuUY6eiWdTFPiXUP1O8oaah0Csz8RlRcIa1l9lhCgWLmDqqOL08Y3F0K8dVIo69eyZtcffV2oBXpdc3VTcdsCp1Y898LUMwBEQMRkIvbz7CBuaqOSacXtrQdqhAqjekP8a0fHRClj00Ayniiid1DDyNpyEfu6SGdPfBH6LkLC5i7FXsHHUvO1GnCc1irro7YZl39IXXoeMqNUFgbEUptiN43oiqtTzYUtpRD_hLxuaVJ3UBWtHaMFjPD1kiQWekYju4V_l4LrUn6-kyOw7QUwiPlt7ljIjAAdnoanwDrlkEMdEUK0bYRb7stBpL36u_IfrqKwRX66TqjGZFKZjd4wpg9wQ_V08GvGVO_sZ-vV8jiQVjqz6p76A1HXqKVruW_iDZcR4kOjwCipGlD-wPPGPsb6tkJb7u1HivuQXwLwrFXSnGNcWqPpEkEj4QmkPJ7Q9vEEgKJzRf_uUJ3h
