### ISSUE TITLE
Where is full api references?

### ISSUE THREAD

**Issue by Shpiller** [Microsoft/monaco-editor#62]
I see only playground
https://microsoft.github.io/monaco-editor/playground.html

**Comment by npenin** [comment]
The API is generated when you install from npm. If you are cloning the repo, then you have to follow the step on the readme: release with `npm run release`

**Comment by aeschli** [comment]
If you just want to browse the API, then you can find it [here](https://github.com/Microsoft/monaco-editor/blob/master/website/playground/monaco.d.ts.txt).
To programm against it follow the steps of the readme, as @npenin mentioned
