### ISSUE TITLE
Rewriting rule and duplicate definition of monaco-editor

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#620]
I have a mean-stack application. At the moment, I have the following rewriting rule in Nginx, to rewrite eg, from `www.myweb.com/home` to `www.myweb.com/v1/home`, where `v1` means "version 1". The goal of having `js`, `socket.io`, etc. is to prevent from rewriting the loading of local static files.

    location ~* ^/\b(?!v1|js|socket.io|monaco-editor|javascripts|ui)\w+\b/? {
        rewrite .* /v1$request_uri redirect;
    }

The rewriting seems to work. However, running the website gives me the following warning and errors

[![enter image description here][1]][1]

[![enter image description here][2]][2]

When i hover over `loader.js`, it gives `https://www.myweb.com/monaco-editor/min-maps/vs/vs/vs/loader.js`, whereas i can not find `monaco-editor/min-maps/vs/vs/vs/loader.js` in the production. Here is the code with regard to monaco-editor:

	<link rel="stylesheet" data-name="vs/editor/editor.main" href="/monaco-editor/min/vs/editor/editor.main.css" />
	<script src="/monaco-editor/min/vs/loader.js"></script>
	<script src="/monaco-editor/min/vs/editor/editor.main.nls.js"></script>
	<script src="/monaco-editor/min/vs/editor/editor.main.js"></script>
	<script> require.config({ paths: { 'vs': '/monaco-editor/min/vs' }}) </script>

Does anyone know what's happening? Is this error related to the rewriting rule? How could we fix it?

  [1]: https://i.stack.imgur.com/DbjeXm.png
  [2]: https://i.stack.imgur.com/UscBOm.png

**Comment by alexdima** [comment]
I'm sorry, but we don't have the expertise to help you with this specific question.
