### ISSUE TITLE
I can't override the default text completions with for the built-in javascript langauge.

### ISSUE THREAD

**Issue by probablycorey** [microsoft/monaco-editor#624]
I'm using Monaco to edit ES6 code and want to have syntax coloring with custom auto-completion suggestions. Monarch provides a basic JavaScript tokenizer at https://microsoft.github.io/monaco-editor/monarch.html, but it is very basic and isn't ES6 compliant. The typescript languages tokenizer is ES6 compliment, but when it comes with a lot of extra features I don't want like code completion and type hints.

Is it possible to use only the typescript tokenizer, or is there a monarch tokenizer for ES6?

**Comment by alexandrudima** [comment]
Yes, it is possible to use only the tokenization part from typescript.

You can find an example how this is done in the built-in plugin `monaco-typescript`. You need to implement a specific interface:

https://github.com/Microsoft/monaco-typescript/blob/master/src/tokenization.ts

It is then registered to Monaco via [monaco.languages.setTokensProvider](https://github.com/Microsoft/monaco-typescript/blob/fd172013f77fa599e03a1c17b79aab62637569fa/src/mode.ts#L78)

**Comment by alexdima** [comment]
In the meantime, we have a TS Monarch tokenizer.
