### ISSUE TITLE
I want to know how to import external js file in monaco editor!!

### ISSUE THREAD

**Issue by Kang-Jun-sik** [Microsoft/monaco-editor#625]
How to import js file.... m.m
And how to achieve the intelligent code-completion?
Please let me Know....

**Comment by alexandrudima** [comment]
Please read our documentation. Here is the minimal example showing how to display JS code in the editor: https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world

Here is the minimal HTML to integrate the editor: https://github.com/Microsoft/monaco-editor#integrate

Here are complete working samples https://github.com/Microsoft/monaco-editor-samples

**Comment by appqui** [comment]
This is the answer, I guess:
https://github.com/Microsoft/monaco-editor/issues/967
