### ISSUE TITLE
Setting window.opener to null only works in browsers

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/monaco-editor#628]
Extracted from https://github.com/Microsoft/monaco-editor/issues/601#issuecomment-343846591
From @hawkerm 

Regarding #601

---

I'm running Monaco in a x-ms-webview, so 10.1.0 broke that as I wouldn't get the uri in the new window request anymore (only about:blank).

Saw there were some updates for this code path in the vscode tree to detect if it was a 'native' platform.  Not sure if that'll detect the x-ms-webview case as well, but want to make sure this scenario can be covered too.

**Comment by alexandrudima** [comment]
I'm not sure how to detect running in an `x-ms-webview`...

**Comment by alexandrudima** [comment]
@hawkerm Is there any way at runtime for us to detect this special case? For example, this is how we detect the `isNative` case:

https://github.com/Microsoft/vscode/blob/52007064712fb8e74e8b7dd00903beaabcd79648/src/vs/base/common/platform.ts#L45

`if (typeof process === 'object' && typeof process.nextTick === 'function' && typeof process.platform === 'string') `

Perhaps there is a way for us to detect running under an `x-ms-webview` ?

**Comment by hawkerm** [comment]
@alexandrudima how about just looking at the user agent string?  It has `WebView` in the platform:

Mozilla/5.0 (Windows NT 10.0; WOW64; **WebView/3.0**) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

Compared to the browser in Edge:

Mozilla/5.0 (Windows NT 10.0; _Win64; x64_) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

The Windows WebView has an event for opening new windows which requires the developer using the webview to decide what to do with the requested new window.  It doesn't pass a reference or have any context from the requesting page, so its not susceptible to the opener issue.

**Comment by hawkerm** [comment]
Awesome, thanks for working towards a solution!
