### ISSUE TITLE
Out-of-the box suggestions not working after upgrade to 0.10.0

### ISSUE THREAD

**Issue by mnayan** [Microsoft/monaco-editor#632]
monaco-editor version: 0.10.0
Browser: Chrome 62
OS: MacOS
Steps or JS usage snippet reproducing the issue:

We recently upgraded our monaco version from 0.8.3 to 0.10.0 and the monaco built-in autocomplete stopped working in our app. 

We're relying on the out-of-the box auto complete (provided by monaco) that simply suggests all words in the code. Below are the before and after screenshots.

**Before:** 
![screen shot 2017-11-15 at 3 00 55 pm](https://user-images.githubusercontent.com/19375144/32858503-b1847ece-ca19-11e7-8914-2037afafce1c.png)

**After:**
![screen shot 2017-11-15 at 3 13 42 pm](https://user-images.githubusercontent.com/19375144/32858522-c0314736-ca19-11e7-85c1-836bc50c725a.png)

Our editor creation is as follows:
```
const editor =  monaco.editor.create(this.container, {
      language: "python",
      automaticLayout: true,
      renderLineHighlight: "none",
      quickSuggestions: true,
      snippetSuggestions: 'top',
      wordBasedSuggestions: true
    });
```

Has the behavior changed in any way in the newer version, or am I missing something here?

Thanks!

**Comment by AndersMad** [comment]
dupe - see here: https://github.com/Microsoft/monaco-editor/issues/567
