### ISSUE TITLE
Screen reader do not provide confirmation message that command is executed

### ISSUE THREAD

**Issue by DasaradhaKamjula** [microsoft/monaco-editor#637]
**User Experience:**
User with vision disability will not be able to know the that command selected from the palate is executed.

**Test Environment:**
OS Build: 16299.19
Excel version:1712(8808.1000)

**Attachments:**
[MAS1.3.1 Command confirmation.zip](https://github.com/Microsoft/monaco-editor/files/1487363/MAS1.3.1.Command.confirmation.zip)

**Repro Steps:**
1.Open url https://microsoft.github.io/monaco-editor/playground.html
2.Navigate to editor press F1
3.Navigate to "Delete all left".
4.Verify that after deleting the all the left content , screen reader do not inform that all the left content is deleted.

**Current Behavior:**
Screen reader do not inform the end user about the command is executed. 

**Expected Behavior:**
After deleting all the content from the left of the cursor , screen reader should read "Deleted all the left" . thus it should read the confirmation about all the commands.

**Note:**
Bug was found while doing Script Lab Testing.

**MAS Reference:**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Suggested Fix:**
https://microsoft.sharepoint.com/teams/msenable/mas/pages/mas-details.aspx?masid=1.3.1

**Comment by alexdima** [comment]
I have tested other editors on macOS (where the delete all left command exists natively in text editors via cmd + backspace and where it has a keybinding for the editor). No editor announces that an editing command has been applied.

From other interactions with users that use a screen reader, they have expressed the opposite that this issue requests. I have understood that they would like the editor to alert them as rarely as possible when doing editing or navigating.
