### ISSUE TITLE
Cannot decorate original model of diff editor when renderSideBySide is false

### ISSUE THREAD

**Issue by nomeyer** [microsoft/monaco-editor#638]
Hi there

monaco-editor version: `0.10.1`
Browser: Chromium via electron `1.7.9`
OS: macOS Sierra `10.12.6`
Steps or JS usage snippet reproducing the issue:
```javascript
const editor = monaco.editor.createDiffEditor(someContainer, { renderSideBySide: false });
const modifiedModel = monaco.editor.createModel('test', 'javascript');
const originalModel = monaco.editor.createModel('hello', 'javascript');
editor.setModel({ original: originalModel, modified: modifiedModel });
originalModel.deltaDecorations([], [{
  range: { startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 1 },
  options: { isWholeLine: true, className: 'some-class-name' },
}]); 
```

Whatever CSS I apply to `some-class-name`, I can only get the decoration to show when `renderSideBySide: true`. Is there some option I'm missing? Is this a bug or is this intentional?

Thanks

**Comment by alexandrudima** [comment]
When the diff editor is rendered inline, there is effectively only one editor being rendered and the original deleted lines are rendered as red view zones inside the modified editor. 

Currently, only text is rendered from the original file inside those view zones.
