### ISSUE TITLE
Documentation - how to get the selected text ? 

### ISSUE THREAD

**Issue by ststeiger** [Microsoft/monaco-editor#639]
I'm able to get the text of the editor with
`window.editor.getValue()`

And I'm able to get the currently selected text-positions with
`window.editor.getSelection()`

​But how do I get the text-value of the currently selected text ? 

Like when I have multiple sql statements, select one statement, and press F5 to execute it - I need the actual text ;)

**Comment by ststeiger** [comment]
Works like a charm. 
Thanks !

**Comment by RajaduraiAzhagudurai** [comment]
@kristianoye Thanks It's saved my time
