### ISSUE TITLE
Monaco Editor Autocomplete suggestions show blank entires

### ISSUE THREAD

**Issue by hilar47** [Microsoft/monaco-editor#640]
monaco-editor version: 0.10.1
Browser: Chrome
OS: Mac OSX
Issue:
The Monaco editor plugin that I use in my Ionic 2 project shows blank  auto-suggestions. The dropdown shows up but with all empty entries. (see screenshot below)
![mnqx2](https://user-images.githubusercontent.com/10907477/33165715-d99d7740-d05d-11e7-8757-43963dc29adc.png)

Initially I thought this was a css issue as all the may be of the same color as the background, but that doesn't seem to be the case as I tried changing the font color as well as checked the entire dropdown in the Developer tool and it does shows me empty entries with no text.

Can anyone help me on this.

**Comment by alexandrudima** [comment]
@hilar47 Can you reproduce this with any language (e.g. word completions too?) Perhaps the completion provider registered by you returns invalid objects or objects with empty string labels ?

**Comment by hilar47** [comment]
Yes. Besides CSS, the empty string labels show up for javascript and typescript too.

**Comment by alexandrudima** [comment]
Ok, then this sounds like a CSS issue to me. Perhaps the suggestion list CSS collides with other CSS on your webpage ?

You could try dumping your CSS into one of the playground pages to check... or perhaps simply use inspect element on those list rows to see which CSS selectors apply to them...

**Comment by hilar47** [comment]
Thanks @alexandrudima It was a CSS issue. I knocked off all external stylesheets to check and turns out .main{} class were clashing in css. 

It has been fixed now. Thanks again.
