### ISSUE TITLE
Add `command` and `additionalTextEdits` to `CompeltionItem`.

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#642]
It is required for the LSP: https://github.com/TypeFox/monaco-languageclient/issues/39.

It looks like the conversion should be done here:
https://github.com/Microsoft/vscode/blob/63efefc7c279e7c963d223123d7248137034252a/src/vs/editor/standalone/browser/standaloneLanguages.ts#L626

@alexandrudima is there a reason not doing it?

**Comment by alexandrudima** [comment]
@akosyakov The Monaco Editor API `CompletionItemProvider` tries to keep on par with the vscode API one. If they fall out of sync, it is only because somebody changed the vscode one, but forgot to change the Monaco Editor one.

**Comment by akosyakov** [comment]
Would it be possible to sync them and publish a new patch version of monaco-editor?

**Comment by alexandrudima** [comment]
PR welcome.

**Comment by akosyakov** [comment]
@alexandrudima ok, i am looking into it
