### ISSUE TITLE
Touch scrolling broken in Microsoft Edge

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/monaco-editor#644]
Moved from https://github.com/Microsoft/vscode/issues/33117
From @jacobrossi 

---

Steps to Reproduce:

1. Open any Monaco test page in Edge
2. Attempt to scroll with touch

---

Monaco uses window.navigator.pointerEnabled to feature detect standard Pointer Events. This property was [deprecated in the standard](https://www.w3.org/Bugs/Public/show_bug.cgi?id=22890) and is being removed from Microsoft Edge as of build 16271.

I have a PR coming shortly with a fix. Note that this also breaks the F12 tools in Edge (which use monaco-editor).

**Comment by DanielRuf** [comment]
Any update on this?

**Comment by alexandrudima** [comment]
@DanielRuf Are you perhaps using a device with a precision touchpad ? It might be a dup of #325

**Comment by DanielRuf** [comment]
Just wanted to know if this is fixed as I also use Windows.
