### ISSUE TITLE
Cannot change default command palette keybinding from F1 to F2

### ISSUE THREAD

**Issue by jdelmas** [microsoft/monaco-editor#649]
Hi, 
Is there a proper way to change the default command palette keybinding from F1 to F2 including menus entries  ? 
![image](https://user-images.githubusercontent.com/12957739/33325393-69617276-d452-11e7-9236-e6ce62fcf4ad.png)

Thanks for your help and for providing such a great editor.

**Comment by RoboPhred** [comment]
I am interested in knowing of a proper solution to this as well, but I can share a hack we used to accomplish something similar:

```
var quickCommandAction = lib.monacoEditor.getAction("editor.action.quickCommand");
lib.monacoEditor.addCommand(monaco.KeyCode.F1, quickCommandAction._run);
```
We use this code to force the command prompt to F1 in IE11, where monaco defaults it to Alt+F1.

Replace monaco.KeyCode.F1 with the key that you want.  This will not update the hotkey listed in the right click menu, but it will add an additional binding to whatever you want.

It may be possible to edit the hotkey on the quickCommandAction object; I have not tried this.

**Comment by jdelmas** [comment]
I've found this very hacky way to solve my use case:
`				editor._standaloneKeybindingService._getResolver()._lookupMap.get("editor.action.quickCommand")[0].resolvedKeybinding._firstPart.keyCode=monaco.KeyCode.F2;
				editor._standaloneKeybindingService.updateResolver();`

It would be nice to have a cleaner solution.

**Comment by gpetrov** [comment]
is there a better way now to handle key bindings? now almost two years later ...

**Comment by larshp** [comment]
very hacky example above updated to run on 0.18.1:

```typescript
// @ts-ignore
      this.editor._standaloneKeybindingService._getResolver()._lookupMap.get(
        "editor.action.quickCommand")[0].resolvedKeybinding._parts[0].keyCode = monaco.KeyCode.F2;
// @ts-ignore
      this.editor._standaloneKeybindingService.updateResolver();
```

**Comment by alexdima** [comment]
Let's track in #102
