### ISSUE TITLE
Accessibility: Inspect: Name property value is too verbose for the items in "Command Pallete"

### ISSUE THREAD

**Issue by Sachin077** [Microsoft/monaco-editor#653]
monaco-editor version: 0.X.Y
Browser: All
OS: Windows 10

Name property value for the items is too verbose. for eg: "Add Cursor Above. Commands. Picker"

**Comment by bpasero** [comment]
@Sachin077 this is nothing we set explicitly, it is just how the screen reader decides to announce items I guess. It seems to travel up to the outer context (Commands, Picker).

**Comment by bpasero** [comment]
I am closing this as designed, this is how every list and tree item aria label works in VS Code.
