### ISSUE TITLE
autocompletions not including this properties correctly

### ISSUE THREAD

**Issue by nickaversano** [Microsoft/monaco-editor#655]
When I use autocompletions in the monaco editor, this member variables don't seem to autocomplete correctly. For example:
```javascript
function myFunc() {
    this.foo = []
    this.foo. // I would expect autocompletions here
    var bar = []
    bar. // this works, showing array methods
}
```
How can I get the this member variables to also show up in autocompletions?

**Comment by akosyakov** [comment]
Because `this` type is any, you should specify it explicitly: 
```ts
function myFunc(this: { foo: string [] }) {
}
```

It is a TypeScript question, you are better to ask them here: https://github.com/Microsoft/typescript
