### ISSUE TITLE
Accessibility: Inspect: Access key is not defined for the commands in the command palate.

### ISSUE THREAD

**Issue by Sachin077** [Microsoft/monaco-editor#657]
monaco-editor version: 0.X.Y
Browser: Chrome/Edge/Firefox
OS: Windows 10

"Access Key" property value is empty for "Add Cursor Above" command.

![capture](https://user-images.githubusercontent.com/7456601/33538274-55f3b102-d8e6-11e7-86ac-49572c929e97.PNG)

**Comment by bpasero** [comment]
@Sachin077 any clue how to set this attribute? I have not found any ARIA role for it yet (though I found the [`accesskey`](https://webaim.org/techniques/keyboard/accesskey) HTML attribute).

**Comment by alexandrudima** [comment]
@bpasero I guess if the shortcut would be read by Narrator it would already be better ? i.e. not necessarily in the field called `AccessKey`

**Comment by bpasero** [comment]
@alexandrudima but we do that already using keybinding.getAriaLabel(): https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/quickopen/browser/commandsHandler.ts#L232

**Comment by alexandrudima** [comment]
@bpasero Oh, cool! 

@Sachin077 Can you please let us know how to affect the `AccessKey` property that you are showing in your screenshot ?

**Comment by bpasero** [comment]
Closing due to no response in any time.
