### ISSUE TITLE
can't delete registerCodeLensProvider and set same commands for every language

### ISSUE THREAD

**Issue by lyudad** [Microsoft/monaco-editor#659]
monaco-editor version: ^0.10.0
Browser: any
OS: mac

use React

I have same commands, but in different lines in different editor files.  Started from simple - added same command for every files that will be opened.

```
  private editorDidMount = (editor, monaco) => {
       const selectCurrentChanges = editor.addCommand(0,() => alert('my command is 1!'), '');
       const selectIncomingChanges = editor.addCommand(0, () => alert('my command is 2!'), '');
 
       monaco.languages.registerCodeLensProvider('javascript', {
         provideCodeLenses: function(model, token) {
             return [
                 {
                   range: { startLineNumber: 1 },
                   id: 0,
                   command: {
                       id: selectCurrentChanges,
                       title: 'Accept Current Changes',
                   },
                 }, {
                   range: { startLineNumber: 1 },
                   id: 1,
                   command: {
                        id: selectIncomingChanges,
                       title: 'Accept Incomin Changes',
                   },
                 },
             ];
         },
         resolveCodeLens: function(model, codeLens, token) {
                     return codeLens;
                 },
             },
      );
         
   }
 
```

expected see (in all files)
![2017-12-06 18 35 05](https://user-images.githubusercontent.com/25103090/33673081-80cdba24-dab4-11e7-9f56-2043bd667900.png)

but when open second file have 

![2017-12-06 18 36 31](https://user-images.githubusercontent.com/25103090/33673097-8e95c048-dab4-11e7-8b99-cf78ec7865f4.png)

third time added same again, so on.

Also can't understand how set commands to every languages, not only for specific one

**Comment by lyudad** [comment]
found way how delete registerCodeLensProvider

>
> const res = monaco.languages.registerCodeLensProvider('javascript', {
>     provideCodeLenses: function(model, token) {
>         return [
>             {
>               range: { startLineNumber: 1 },
>               id: 0,
>               command: {
>                   id: selectCurrentChanges,
>                   title: 'Accept Current Changes',
>               },
>             }
>         ];
>     },
>     resolveCodeLens: function(model, codeLens, token) {
>                 return codeLens;
>             },
>         },
>   );
> 
> res..dispose(); //will delete registerCodeLensProvider
>

**Comment by akosyakov** [comment]
@lyudad HI! Could you debug `editorDidMount`? It looks like it gets called several times, like for each file.

You can move code lens provider code of `editorDidMount` to make sure that it is registered only once. It should be straightforward.

You can access all languages with: `monaco.languages.getLanguages()` and then iterate and register a provider for each, something like here: https://github.com/TypeFox/monaco-languageclient/blob/7a2963e7b808d42b50cee5225b32c712a2c134d2/src/languages.ts#L250-L257.

**Comment by lyudad** [comment]
thank's that help
