### ISSUE TITLE
can't reload ExtraLib for LanguageService

### ISSUE THREAD

**Issue by Shpiller** [Microsoft/monaco-editor#66]
delete this._extraLibs[filePath] return false
and not delete this._extraLibs[filePath]

see here https://github.com/Microsoft/monaco-typescript/issues/5

**Comment by Shpiller** [comment]
is a reason
` get extraLibs(): { [path: string]: string; } { return Object.freeze(this._extraLibs); } `

**Comment by jrieken** [comment]
see here Microsoft/monaco-typescript#5
