### ISSUE TITLE
hoverProvider range doesn't work (even in the playground example)

### ISSUE THREAD

**Issue by bluelightning2k** [Microsoft/monaco-editor#663]
Hi, the hoverProvider doesn't respect range, even in the example given here: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example

Whatever you change line 8 to, the range applies to everything. There seems to be no way at all to actually limit the hover provider to some subsection.

This is a real shame because it could otherwise be an amazing feature.

Hopefully this is something you can fix.

PS: The Monaco editor is AMAZING, thank you so much for your work on this, it's easily one of my 5 favourite modules anywhere - maybe number 1.

**Comment by akosyakov** [comment]
You should take the given position into the account, otherwise, you return `Hover` for any position. Try the following code in the playground:
```ts
monaco.languages.register({ id: 'mySpecialLanguage' });

monaco.languages.registerHoverProvider('mySpecialLanguage', {
	provideHover: function(model, position) {
        const range = new monaco.Range(1, 1, 1, 4);
        if (range.containsPosition(position)) {
            return {
                range,
                contents: [
                    {
                        language: 'html',
                        value: '<h>Hello Wordl!</h>'
                    }
                ]
            }
        }
        return null;
    }
});

monaco.editor.create(document.getElementById("container"), {
	value: 'Hover over this text',
	language: 'mySpecialLanguage'
});
```

**Comment by alexandrudima** [comment]
@bluelightning2k The second argument of the `provideHover` function is a `position`. That is where the mouse sits when the hover wants to be shown.

Thank you @akosyakov
