### ISSUE TITLE
HI everyone!! I have a Q. How to hide some area of code??

### ISSUE THREAD

**Issue by Kang-Jun-sik** [Microsoft/monaco-editor#664]
HI everyone!! I have a Question about monaco-editor.

main Q : How to hide some code of the monaco-editor??

for Example)

var userInfo = self.user;  
var def_cdPcDataSource = [];
def_cdPcDataSource.push({CD_PC : userInfo.profitCenterCode,NM_PC : userInfo.profitCenterName});

I wrote above 3 line in monacoEditor! but I don't want to show 3 lines to user... 
Could you let me know ....?

**Comment by nekitozzz** [comment]
@Kang-Jun-sik I found that there is an internal method (non API way and might get removed in the future) that can be applied to editor:

`setHiddenAreas(ranges: IRange[]): void;`

**Comment by Kang-Jun-sik** [comment]
![q1](https://user-images.githubusercontent.com/20898356/33922129-e46289aa-e00b-11e7-8778-dd1c591aa402.png)
![q2](https://user-images.githubusercontent.com/20898356/33922130-e48d3b32-e00b-11e7-8192-3ef69673c01c.png)
![q3](https://user-images.githubusercontent.com/20898356/33922131-e4b9d17e-e00b-11e7-8d13-a39b30152dce.png)
![q4](https://user-images.githubusercontent.com/20898356/33922132-e4e3ac6a-e00b-11e7-8c4f-cd18a0305de2.png)


Thank you very much for your apply!! But I have a another problem. when I use delete all of the content in monaco Editor, I can see that error and editor can't execute anymore.. how can i solve it...

**Comment by Kang-Jun-sik** [comment]
I solve it!!! you have to write the code .setEditableChange(Range) 
Thank you very much!!
