### ISSUE TITLE
how add notes

### ISSUE THREAD

**Issue by lyudad** [Microsoft/monaco-editor#666]
monaco-editor version: ^0.10.0
Browser: any
OS: mac

use React

![2017-12-12 14 56 48](https://user-images.githubusercontent.com/25103090/33885758-eff1ab30-df4c-11e7-9dd3-855f1f9b970b.png)

Does monaco-editor has opportunity to add notes (description) similar to vscode - 'Current changes'

**Comment by akosyakov** [comment]
It is not exposed via monaco API. But it should be there, you can augment `monaco.editor` module by adding the following `monaco.d.ts` file to your sources:
```ts
/// <reference types='monaco-editor-core/monaco'/>

declare module monaco.editor {

    export interface IDecorationOptions {
        range: IRange;
        renderOptions?: IDecorationInstanceRenderOptions;
    }

    export interface IDecorationInstanceRenderOptions {
        before?: IContentDecorationRenderOptions;
        after?: IContentDecorationRenderOptions;
    }

    export interface IContentDecorationRenderOptions {
        contentText?: string;
        contentIconPath?: string;

        border?: string;
        borderColor?: string;
        textDecoration?: string;
        color?: string;
        backgroundColor?: string;

        margin?: string;
        width?: string;
        height?: string;
    }

    export interface ICommonCodeEditor {
        setDecorations(decorationTypeKey: string, decorationOptions: IDecorationOptions[]): void;
        removeDecorations(decorationTypeKey: string): void;
    }

}
```

For doc, it is better to look at vscode API: https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namethemabledecorationattachmentrenderoptionsaspan-classcodeitem-id269themabledecorationattachmentrenderoptionsspan

@alexandrudima Could it be exposed?

**Comment by lyudad** [comment]
First parameter in `setDecorations` function is `decorationTypeKey`, which should be register.
I have this error 
![2017-12-18 16 10 37](https://user-images.githubusercontent.com/25103090/34110077-3cbb9b72-e40e-11e7-83e9-2af59ad1b6b8.png)

I found in VsCode method that generate this error (CodeEditorServiceImpl class)
```
public resolveDecorationOptions(decorationTypeKey: string, writable: boolean): IModelDecorationOptions {
		let provider = this._decorationOptionProviders[decorationTypeKey];
		if (!provider) {
			throw new Error('Unknown decoration type key: ' + decorationTypeKey);
		}
		return provider.getOptions(this, writable);
	}
```
This class also have method `registerDecorationType(key: string, options: IDecorationRenderOptions, parentTypeKey?: string): void`. But I can't doing something like `editor.registerDecorationType()`, as it's not editor method.
How can I register new Decoration type?

**Comment by lyudad** [comment]
Found necessary method editor._registerDecorationType
