### ISSUE TITLE
import  module  How to use the relative path?

### ISSUE THREAD

**Issue by qingruibin** [Microsoft/monaco-editor#667]
monaco-editor version: 0.10.1
Browser:Chome
OS: Window
Steps or TS usage snippet reproducing the issue:

my extralib:
```
monaco.languages.typescript.typescriptDefaults.addExtraLib(
`declare module '/test/test1'{
        export class test1{         
            constructor();
            show(): void;
        }
    }
 declare module '/Code/User'{
        export class User {
            private name;
            private age;
            constructor(name: string, age: number);
            show(): void;
        }
    }`
);
```

my tyescript code:
**"./Code/User"**
```
// It is possible to use this
//import {User} from "/Code/User"
// It's wrong to use this   But I want to use it this way
//import {User} from "./Code/User"
class Main{
    constructor()
      {
      }
}

```
other :
//this User class
 **"../test/test1"**
```
//The same can not be used in this way
import {test1} from "../test/test1'"
//How to use the relative path correctly? for  import from  ../ ??
export class User
{
      private name;
      private age;
      constructor(name: string, age: number)
      {
      }
      show(): void{
     }
}

```

**Comment by qingruibin** [comment]
Who can give a right example

**Comment by qingruibin** [comment]
My problem has been jueji.

The following is my solution.

By the way, share it with you

**Comment by qingruibin** [comment]
monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
    noSemanticValidation: false,
    noSyntaxValidation: false
});

monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ES6,
    module: monaco.languages.typescript.ModuleKind.System,
    allowNonTsExtensions: true,
});

// extra libraries
monaco.languages.typescript.typescriptDefaults.addExtraLib([
    `
//  declare module "./common/User" {
     export class User {
        private name;
        private age;
        constructor(name: string, age: number);
        show(): void;
    }
//  }
    `,
].join('\n'),"/common/User.d.ts");

monaco.languages.typescript.typescriptDefaults.addExtraLib([
    `
     export class Util {
      public static test()
      {

      }
    }

    `,
].join('\n'),"/common/utils/Util.d.ts");

var jsCode = [
    `
import { User } from "./common/User"
export class Main
{
    constructor()
    {
        let u:User;
        u.show();
    }
}
    `
].join('\n');

//Here you need to create a model to distinguish the path  *****
// let curModel = monaco.editor.createModel(jsCode,"typescript",monaco.Uri.parse("/main.ts"));

//Of course, we can do that.
let curModel = monaco.editor.createModel(jsCode,"typescript",monaco.Uri.parse("/app/main.ts"));


let editor = monaco.editor.create(document.getElementById("container"), {
    model:curModel,    
    language: "typescript"
});

let model =  editor.getModel();

console.log(model);

**Comment by agentcooper** [comment]
Working example:

```typescript
const files = {
  "services/user.d.ts": `
    import { Profile } from "./profile";

    export function getUserProfile(uuid: string): Profile {
        return { firstName: "John", lastName: "Doe" };
    }
    `,

  "services/profile.d.ts": `
    export interface Profile { firstName: string, lastName: string };
    `
};

for (const fileName in files) {
  const fakePath = `file:///node_modules/@types/${fileName}`;

  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    files[fileName],
    fakePath
  );
}

const model = monaco.editor.createModel(
  `
import { getUserProfile } from 'services/user';
const profile = getUserProfile("some-id");
console.log(profile.firstName);
    `.trim(),
  "typescript",
  monaco.Uri.parse("file:///main.tsx")
);

monaco.editor.create(document.getElementById("container"), { model });
```

You can paste it in [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults).

**Comment by farskid** [comment]
@agentcooper This saved me after weeks of digging. Thank you.
