### ISSUE TITLE
Setting custom typescript libraries breaks the standard lib

### ISSUE THREAD

**Issue by TyOverby** [microsoft/monaco-editor#669]
monaco-editor version: 0.10.1 (and whatever version is on the monaco playground.
Browser: Firefox | Safari
OS: OSX
Steps or JS usage snippet reproducing the issue:

* Paste and run the following into the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html)

```
monaco.editor.create(document.getElementById("container"), {
	value: "var x = [1,2,3];\n",
	language: "typescript"
});

monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
    target: monaco.languages.typescript.ScriptTarget.ES5,
    lib: ["DOM", "ES5", "ScriptHost"] // these are the default libraries for the ES5 target
});
```

* In the demo editor, type `x.` and notice that Array autocomplete does not show up.
* Retype the first line to `var x: number[] = [1,2,3]`.
* Retype `x.` and notice that Array autocomplete does not show up.

It looks like the only way to get working standard library features like Array is to not use custom `lib`   options.

**Comment by TyOverby** [comment]
Workaround: use `        monaco.languages.typescript.typescriptDefaults.addExtraLib(<>, "lib.d.ts");` with the entire source of [lib.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts)

**Comment by TedDriggs** [comment]
Thanks for the workaround! I ran into the same issue back in September: #579

**Comment by dennis-yemelyanov** [comment]
Are there any plans to address this issue in the near future?

**Comment by dennis-yemelyanov** [comment]
@TyOverby , the workaround to use `addExtraLib(<>, "lib.d.ts")` doesn't seem to work for me and results in a syntax error because of "<>" (the first parameter). Is there a way to avoid this error?

**Comment by TyOverby** [comment]
@dennis-yemelyanov: you aren't supposed to literally put `<>`, you should put 

| the entire source of lib.d.ts

**Comment by dennis-yemelyanov** [comment]
Ah I see. Was trying to figure out a way do avoid downloading the source myself, but looks like that's the only option for now.

**Comment by attaboy** [comment]
This bug cost me several hours of confusion today as I tried to understand why neither `Array<T>` nor `T[]` worked but also didn't cause any obvious errors.

I'm trying to build a Typescript editor for editing Node.js modules, so I don't want the DOM or other browser-specific stuff.

**Comment by strutcode** [comment]
For anyone else still having this issue in 2019, here's a work around I came up with for Webpack:
```ts
// Reduce all the .d.ts files to a filename => content object
// Note this will add all of those files to your build even if you don't use them
const ctx = require.context('typescript/lib', true, /\.d\.ts$/)
const allLibs = ctx.keys().reduce((acc, k) => {
  acc[k] = ctx(k).default
  return acc
}, {})

monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
  target: monaco.languages.typescript.ScriptTarget.ES5,
  allowNonTsExtensions: true,
  noLib: true,
})

// Add every lib from the typescript source
Object.entries(allLibs).forEach(([filename, content]) => {
  // Potentially exclude some libs here

  monaco.languages.typescript.typescriptDefaults.addExtraLib(content, filename)
})
```

**Comment by IamFonky** [comment]
> This bug cost me several hours of confusion today as I tried to understand why neither `Array<T>` nor `T[]` worked but also didn't cause any obvious errors.
> 
> I'm trying to build a Typescript editor for editing Node.js modules, so I don't want the DOM or other browser-specific stuff.

I'm currently doing the same kind of project. Be aware that using noLib option will kill the typescript inference capabilities.

I just opened an issue for that #1673

**Comment by alexdima** [comment]
Choosing custom `lib`s is not supported and will not be supported. There are workarounds described in this thread, where it is possible to add them on your side via `addExtraLib`.
