### ISSUE TITLE
Inconsistent handling of Markdown embedded in displayed JSDoc comments

### ISSUE THREAD

**Issue by CGJennings** [Microsoft/monaco-editor#670]
monaco-editor version: 0.10.1
**Note:** VS Code (tested in 1.18.1 and 1.19.0) behaves as expected.

When the editor displays a pop-up showing a type description extracted from a doc comment that contains Markdown, sometimes it coverts the Markdown and sometimes it displays it as raw text. Another symptom of this is that in cases where the Markdown *is* processed, a long doc comment that is split over multiple lines is treated as a single paragraph (as expected), but in cases where the Markdown *is not* processed each line in the comment becomes a separate line in the popup.

Paste the following into a suitable Monaco editor instance, such as the Typescript example on the [Monaco Editor](https://microsoft.github.io/monaco-editor/) demo page.
```
class Test {
  /**
   * A property named `property`. And this is
   * another line in the same paragraph.
   */
  property;
}
let t = new Test();
// Hover over property and the popup processes the `property` MD as expected
t.property;
// Use code completion after the . below, click the (i) button, `property` is plain text
t.
```

As noted in the comments, if you hover the pointer over `t.property`, the popup description will convert the Markdown in the doc comment to a code element. But when you use code completion for `t.` and request more details on `property` using the (i) information button, the Markdown in the same doc comment is displayed as plain text.

**Comment by joaomoreno** [comment]
Excellent!
