### ISSUE TITLE
Monaco Extension

### ISSUE THREAD

**Issue by ShalokShalom** [Microsoft/monaco-editor#671]
In your Readme, you declare that it is not possible to use VS Extensions.
Well, is there another way to extend Monaco?

I am especially interesting into porting Ionide. Thanks

**Comment by akosyakov** [comment]
One can connect Monaco with language servers by means of [the language server protocol](https://github.com/Microsoft/language-server-protocol) and [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient).

**Comment by ShalokShalom** [comment]
Oh fine. Ionide and other extensions are portable in some ways?

**Comment by akosyakov** [comment]
No, generally there is no way to port extensions. I am not familiar with Ionide, but if you are looking for F# support in Monaco then you could try to look for fsharp language server, maybe someone had already extracted it.

**Comment by ShalokShalom** [comment]
Like this? https://github.com/georgewfraser/fsharp-language-server
