### ISSUE TITLE
Diff editor doesn't dispose correctly

### ISSUE THREAD

**Issue by rart** [Microsoft/monaco-editor#672]
When you dispose/destroy a regular editor, I can see that the element is left clean and I can reuse it immediately after calling dispose (for example to replace it with a new diff editor). In the case of the diff editor, when disposing, it leaves dirty dom and likely other things since I can still see the attribute `data-keybinding-context` on the dom.

monaco-editor version: 0.10.1 (taken from editor.main.js)
Browser: Chrome, Safari, Firefox
OS: Mac (High Sierra)
Steps or JS usage snippet reproducing the issue:

1. Go to https://microsoft.github.io/monaco-editor/playground.html
2. Paste the code snippet below
3. Hit the "run" button
4. Notice:
- After 2 seconds, the regular editor destroys and a diff editor is created reusing the same element (all good)
- After 4 seconds (2 after diff is created), dispose is called on the diff editor but you can see it leaves a _dirty_ UI and the regular editor which creates over the same element is not usable.

```
var normal;
var diff;

function createRegular() {
    
    var editor = monaco.editor.create(document.getElementById("container"), {
        value: "// First line\nfunction hello() {\n\talert('Hello world!');\n}\n// Last line",
        language: "javascript"
    });

    return editor;

}

function createDiff() {

    var originalModel = monaco.editor.createModel("just some text\n\nHello World\n\nSome more text", "text/plain");
    var modifiedModel = monaco.editor.createModel("just some Text\n\nHello World\n\nSome more changes", "text/plain");

    var diffEditor = monaco.editor.createDiffEditor(document.getElementById("container"));

    diffEditor.setModel({
        original: originalModel,
        modified: modifiedModel
    });

    return diffEditor;

}

normal = createRegular();

setTimeout(function() {
    normal.dispose();
    diff = createDiff();
    setTimeout(function() {
        diff.dispose();
        createRegular();
    }, 2000);
}, 2000);
```

Note: I took the version from my local `vs/editor/editor.main.js` header file.

**Comment by rart** [comment]
Was the issue fixed?

**Comment by alexandrudima** [comment]
Yes, above your comment there is a link to the commit which fixed it.
