### ISSUE TITLE
HI everyone!! I have a Question about intellisensing problem

### ISSUE THREAD

**Issue by Kang-Jun-sik** [microsoft/monaco-editor#674]
HI guys!! Christmas is coming. 
I have a Question about intellisensing problem. I attached two picture below.
![intell_visual_code](https://user-images.githubusercontent.com/20898356/34185485-efc3e53e-e568-11e7-9a6d-37e7b7dad139.png)
 ↑↑↑↑↑ This is a editor in Visual Code. I think visual code editor works contextual(?) intellisensing.

![monaco_visual_code](https://user-images.githubusercontent.com/20898356/34185515-290bcc08-e569-11e7-83af-91237cf357c4.png)
↑↑↑↑↑ This is a Monaco Editor. but monaco-editor doesn't work contextual intellisensing.
How can i use contextual intellisensing?
Thank you for reading and good luck!!!

**Comment by akosyakov** [comment]
I tried it on the playground and it is working. How do you create the editor? Could it be that you pass `false` as `wordBasedSuggestions`?
