### ISSUE TITLE
How to convert vscode theme json file to monaco editor theme

### ISSUE THREAD

**Issue by powerumc** [Microsoft/monaco-editor#675]
monaco-editor version: 0.10.
Browser: Chrome lastest
OS: Sierra

VSCode theme file is json file type.
Json file content format is not equals json format of monaco editor.

How to convert to monaco editor theme?

**Comment by alexandrudima** [comment]
They are not compatible. VSCode themes work with TM grammars. The monaco editor does not execute TM grammars, so the tokens produced by the standalone editor are not the same as the ones produced by a TM grammar. Therefore, there is no automatic way to transform one to another, short of picking colors from one, and adopting to the other....

**Comment by brijeshb42** [comment]
@powerumc You can use https://bitwiser.in/monaco-themes/ to generate theme for monaco from `tmTheme` files that picks colors from theme files and generates a json to be used directly with `monaco.editor.defineTheme`
