### ISSUE TITLE
How to show the picture like vscode?

### ISSUE THREAD

**Issue by Dr-Harris** [Microsoft/monaco-editor#676]
monaco-editor version: 0.9.0
Browser: chrome 64 dev
OS: win 10
I want to show pictures in the editor(jpg/png/gif/svg...), what should I do?

**Comment by Dr-Harris** [comment]
![1](https://user-images.githubusercontent.com/22830171/34206762-dc20383e-e5c2-11e7-9421-644aed827067.png)
show pictures like this (like vscode)

**Comment by mofux** [comment]
It's not part of the monaco editor. VSCode provides its own panel (they call it opener) to show things like pictures.

**Comment by Dr-Harris** [comment]
@mofux thank you~
