### ISSUE TITLE
Accessibility: Focus is not trapped inside the Dialog if monaco editor is used in the dialog to show text.

### ISSUE THREAD

**Issue by Sachin077** [Microsoft/monaco-editor#677]
monaco-editor version: 0.X.Y
Browser: Chrome/Edge/Firefox
OS: Windows
Steps or JS usage snippet reproducing the issue:
If monaco editor is used to show files in a dialog (Office fabric dialog), then after the focus is in the editor, the focus is no longer trapped inside the dialog, but is spread to the whole webpage (including address bar).

**Comment by alexandrudima** [comment]
@Sachin077 This sounds like a problem with the page integrating the Monaco Editor. The Monaco Editor is not aware that it is integrated in an Office fabric dialog and does not do anything special about it. If something special needs to be done, then the responsibility lies with the integrator.
