### ISSUE TITLE
vscode git diff should highlight the correct code block on traversing the changes

### ISSUE THREAD

**Issue by nidhinmtw** [Microsoft/monaco-editor#679]
In VSCode when i do changes and open the Git diff view to see the changes done, the editor opens the compare mode and highlight all the changed blocks of code.
Using the top right arrow buttons, we can traverse the blocks.
But, this traversal is not really highlighting which block is currently being focused.
If cursor is placed in the editor,  then cursor is being moved correctly, otherwise there is no way to know which block is being highlighted.
VSCode 1.18.1
OS: Win 7

**Comment by alexandrudima** [comment]
The VS Code actions move the cursor to the next diff. They do not highlight the next diff. Also, please create VS Code issues at the VS Code repository at https://github.com/Microsoft/vscode
