### ISSUE TITLE
Highlighting error for C++ preprocessor statements

### ISSUE THREAD

**Issue by jayspadie** [Microsoft/monaco-editor#687]
monaco-editor version: 0.10.1
Browser: Chrome
OS: Windows 10

A user of VSTS provided the following feedback regarding C++ syntax highlighting in Monaco:

Adding whitespaces after sharp (#) character is legal in C++. But in TFS and VSTS [Monaco] web console, such statements are not detected as preprocessor clause.

In Monaco:
![image](https://user-images.githubusercontent.com/5246869/34845194-070f999c-f6e2-11e7-9873-af4fed2b3b32.png)

In VS Code:
![image](https://user-images.githubusercontent.com/5246869/34845220-248407ec-f6e2-11e7-862a-271eca1ff5d6.png)

**Comment by jayspadie** [comment]
Cross referenced from VSTS Developer Community:  https://developercommunity.visualstudio.com/content/problem/174965/highlighting-error-for-c-preprocessor-statements.html

**Comment by evakili** [comment]
Shall this issue be moved to [Microsoft/monaco-languages](https://github.com/Microsoft/monaco-languages)?

**Comment by alexandrudima** [comment]
Fixed by https://github.com/Microsoft/monaco-languages/pull/28
