### ISSUE TITLE
Add a new language and its formatter to Monaco Editor

### ISSUE THREAD

**Issue by chengtie** [Microsoft/monaco-editor#690]
I want to add a language of Excel formulas to Monaco Editor. I understand I need to follow [this approach](https://github.com/Microsoft/monaco-languages/blob/master/README.md#dev-adding-a-new-language) and especially add `excelformulas.ts`.

One important functionality I want to realise is to format a formula. For example, given `=sum(1, 2, 3)`, I want to format it to 

```
=sum(1,
     2,
     3)
```
So somewhere I need to add a **formatter**. There are a lot of formatters in VSCode marketplace, and I understand we could follow [this way](https://code.visualstudio.com/docs/extensions/overview) to make a VSCode extension. But could anyone tell me how to make a formatter extension for Monaco Editor? Otherwise, how could we integrate the formatting functionality directly into Monaco Editor?

Thank you

**Comment by akosyakov** [comment]
@chengtie you can register formatting providers for your language with following api:
```ts
monaco.languages.registerDocumentFormattingEditProvider(...)
monaco.languages.registerDocumentRangeFormattingEditProvider(...)
monaco.languages.registerOnTypeFormattingEditProvider(...)
```

**Comment by AnnaNaumova416** [comment]
Hi. @chengtie. I read your problem. I have an exactly same problem like that. Want to add Excel formula but don't know where to start. Is there anyone can help me out?

Thank you.

**Comment by ButuzGOL** [comment]
may be somebody know exists open source formatting lib or example for excel ?

**Comment by marek-baranowski** [comment]
I'm also trying to add formulas - please share your solution if you've figured it out :)

**Comment by ButuzGOL** [comment]
I did my own language based on https://github.com/Microsoft/monaco-editor

**Comment by marek-baranowski** [comment]
Would you share a gist? I would greatly appreciate :)

**Comment by stanislavgeorgiev** [comment]
@ButuzGOL How do you make Monaco load your new language? I also tried to clone of those languages but then the loader doesn't know about it.

**Comment by ButuzGOL** [comment]
https://github.com/Microsoft/monaco-editor/blob/master/test/playground.generated/extending-language-services-custom-languages.html

**Comment by OmkarRa** [comment]
A playground demonstrating how to do this:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages
