### ISSUE TITLE
set editable range messes up undo stack

### ISSUE THREAD

**Issue by anandanand84** [Microsoft/monaco-editor#693]
After you set editable range undo, redo doesnt work.

# Steps to reproduce:

In monaco editor playground, use the below code, undo redo wont work

```
var editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});


editor.onDidChangeModelContent(()=> {
    let count = editor.getModel().getLineCount();
    editor.getModel().setEditableRange(new monaco.Range(2,1,count,1));
})

```

**Comment by alexandrudima** [comment]
`setEditableRange` has been removed.

**Comment by AndersMad** [comment]
Any hints on what to use instead of `setEditableRange`? or is that functionality gone now and in future? 

E.g. for editing a body of a typescript function but not letting the user change the function name/params (still with linting and completion from param objects, return type etc.)
