### ISSUE TITLE
Support for MarkdownString in CompletionItem

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/monaco-editor#695]
monaco-editor version: 0.10.1
Browser: Chrome
OS: macOS

I'm building a custom completion provider and want to have support for some styling. I guess this can be done with [`MarkdownString`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#MarkdownString) as documented in the [VSCode CompletionItem API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#CompletionItem.new CompletionItem).

The [monaco API](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html#documentation) does not seem to expose `MarkdownString`.

**Comment by rcjsuen** [comment]
Duplicate of #689.

**Comment by SamVerschueren** [comment]
Wow, totally missed that one. Thanks!
