### ISSUE TITLE
How set coloring macros in editor?

### ISSUE THREAD

**Issue by InokentiyVas** [microsoft/monaco-editor#697]
monaco-editor version: 0.10.1
Browser: Chrome
OS: Windows 7
Steps or JS usage snippet reproducing the issue:
How to highlight your macros?
```
<div id="container" style="width:800px;height:600px;border:1px solid grey"></div>
<script src="monaco-editor/min/vs/loader.js"></script>
<script>
	require.config({ paths: { 'vs': 'monaco-editor/min/vs' }});
	require(['vs/editor/editor.main'], function() {
		var editor = monaco.editor.create(document.getElementById('container'), {
			value: [
				'<html></html>'
			].join('\n'),
			language: 'html'
		});
	});
</script>
```
How macro {%DATE%} set color red or other color.
How set macro color {%unknown_length_this_macro%} set other color exmp blue.

**Comment by akosyakov** [comment]
For the custom coloring, you have to define a monarch tokenizer: https://microsoft.github.io/monaco-editor/monarch.html

Look at [monaco.languages.setMonarchTokensProvider](https://github.com/Microsoft/monaco-editor/blob/bad3c34056624dca34ac8be5028ae3454172125c/monaco.d.ts#L3978) and for examples at [monaco-languages](https://github.com/Microsoft/monaco-languages).
