### ISSUE TITLE
Any update to the latest sources planned?

### ISSUE THREAD

**Issue by raedle** [Microsoft/monaco-editor#701]
The editor source in the vscode project is quite far ahead of the monaco-editor project. The last update was in October 2017. When is the next pull and update of monaco-editor planned?

Also, in case now update is planned. How can the community pull updates from vscode to update the monaco-editor project and build it?

Thanks!

**Comment by raedle** [comment]
Ok, I found the answer to my last question in the contribution section.

My first question remains, though ;). Is an update by the project owners planned soon?

**Comment by raedle** [comment]
Following the instructions on [CONTRIBUTING.md](https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md), I was able to run the editor from vscode tag [1.19.2](https://github.com/Microsoft/vscode/tree/1.19.2). 

However, the reason why I was asking for an update on this project is the language support for `javascript`, which is different in vscode 1.19.2 than in the latest [monaco-languages](https://github.com/Microsoft/monaco-languages). For example, vscode 1.19.2 can distinguish between `variable.other.property.js`, `variable.other.object.js`, `support.class.builtin.js`, `entity.name.function.js` or `support.function.js` while monaco-languages only shows `identifier.js` (see screenshots below from token inspector in vscode and monaco-editor).

Is it possible to use language support already implemented in [vscode extensions](https://github.com/Microsoft/vscode/tree/1.19.2/extensions)?

vscode `javascript` language support
<img width="232" alt="vscode-tokens" src="https://user-images.githubusercontent.com/489051/35248668-48d95a98-ffcf-11e7-84e1-c528eb38db0e.png">

monaco-editor `javascript` language support
<img width="220" alt="monaco-editor-tokens" src="https://user-images.githubusercontent.com/489051/35248667-48bf7754-ffcf-11e7-92e8-826fbf559259.png">

**Comment by AndersMad** [comment]
The October release was just a tiny security thing - so it dates back to mid August. I too would love to know if any updates are planed or we should start (try) doing it our self from now on :) I could not find anything in the vscode milestones nor roadmap.

**Comment by David-Carty** [comment]
Why is nobody responding to the question on update.  Fab editor but CodeMirror is updated religiously each month.  Zero response to this question does not instill confidence when considering serious commercial product implementation.

**Comment by akosyakov** [comment]
https://github.com/Microsoft/monaco-editor/issues/510#issuecomment-364520170

**Comment by David-Carty** [comment]
Update on next release?

**Comment by alexandrudima** [comment]
Hi, we are working on it and it will be based on the stable February branch of vscode (stabilizing as we speak).

**Comment by alexandrudima** [comment]
Thank you for your patience! :heart:

monaco-editor@0.11.0 is out! See what's new in the [changelog](https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md)
