### ISSUE TITLE
mouse can't click within selected area

### ISSUE THREAD

**Issue by troy351** [microsoft/monaco-editor#704]
monaco-editor version: 0.10.1
Browser: Chrome 63
OS: Windows 10
Steps or JS usage snippet reproducing the issue:
open [https://microsoft.github.io/monaco-editor](https://microsoft.github.io/monaco-editor).
find the editor, select any area.
Then, `left click` event doesn't work within the selected area any more, but `right click` or `double left click` works fine.

Is this a feature or a bug?

**Comment by alexandrudima** [comment]
Left click on a selection will drag that selection by default.

You can construct the editor with the option `dragAndDrop: false` if you don't want that. e.g.:

```js
monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
    dragAndDrop: false
});
```

**Comment by troy351** [comment]
In most editors including vscode, `dragAndDrop` and normal left click both works.
Is there any reason why monaco can't achieve this?

**Comment by alexandrudima** [comment]
@troy351 I don't understand what exactly the problem you are pointing out is.

On a default editor, such as the one at https://microsoft.github.io/monaco-editor/
* I can double click to select a word:
![kapture 2018-03-02 at 14 17 19](https://user-images.githubusercontent.com/5047891/36900654-736a619e-1e24-11e8-9dee-29051b3ee9a6.gif)

* I can press mouse down on the selection and move the mouse and release mouse up to drag and dropit:
![kapture 2018-03-02 at 14 18 19](https://user-images.githubusercontent.com/5047891/36900685-978bbbc2-1e24-11e8-939c-e92849f16698.gif)

* I can press mouse on the word and release mouse up it and then a cursor is set:
![kapture 2018-03-02 at 14 19 39](https://user-images.githubusercontent.com/5047891/36900732-c6c17422-1e24-11e8-9f58-27ac4d2b007a.gif)

What exactly does not work for you?

**Comment by troy351** [comment]
Sorry for bothering you, the third one doesn't work both on my project and the demo in doc when I asked this question. 
But it gets right now and I still don't know what happened exactly.
Thanks again.

**Comment by troy351** [comment]
@alexandrudima I can reproduce the problem now!
Simply just open [https://microsoft.github.io/monaco-editor](https://microsoft.github.io/monaco-editor) twice (with 2 tabs) on latest Chrome. And the third one won't work anymore.

Only happens on Chrome with more than two tabs containing `monaco-editor`

**Comment by alexandrudima** [comment]
This works fine for me even with the editor opened in 3 tabs.

**Comment by Fearify** [comment]
Also having this issue on chrome, but seems to be working on Edge and Firefox.

**Comment by troy351** [comment]
@Fearify Any idea how to reproduce it stably?

**Comment by yfwz100** [comment]
I encounter this problems too. It seems that the problem is related to multiple tabs containing monaco editor. when I just take the monaco editor tab away from the other tabs, the editor behave normally. however, when I put it back into the tabs, the problem occurs again.
