### ISSUE TITLE
[Screen Reader - Data Factories - ADF Editor] Narrator in item and scan mode is reading as image at ruler of the editor

### ISSUE THREAD

**Issue by sonimishra** [Microsoft/monaco-editor#705]
Blade Name: Data Factories - ADF Editor

User Experience:
If Narrator in item mode and scan mode is reading only as image at ruler then the person with visual related disability will confuse to navigate through the blade.
 
Test Environment:
OS: Win 10 RS3
Build: 16299.15
Platform: Edge, Firefox
Screen Reader: Narrator, NVDA
 
Repro Steps:
1-Navigate to https://portal.azure.com/ and login using valid credentials.
2-Navigate to More Services option and select "data Factory" option.
3-Navigate to various Data factories listed and select anyone
4-Navigate to the Actions section lying on the blade opened and select "Author and Deploy" option.
5-Navigate to New Pipeline option lying on the blade opened and select it.
6-Navigate to ADF Editor screen in Scan mode(Caps + Space bar) and verify the issue.
 
Actual Result:
Narrator in item and scan mode is reading as image at ruler of the editor.
 
Expected result:
Narrator in item and scan mode should give complete information at ruler of the editor.
 
Note:
Same issue exists with NVDA.
 
MAS Reference:
MAS 1.3.1 - Info and Relationships (40)
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame2.aspx?sourcedoc=%7b54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7d
 
![mas1 3 1_data factories_information at ruler image of the editor](https://user-images.githubusercontent.com/30456910/35375737-2993855e-01ce-11e8-9cb9-617396112b43.png)

**Comment by sonimishra** [comment]
Azure Data Factory Bug Reference Id : Bug 1826280

https://msazure.visualstudio.com/One/_workitems?_a=edit&newQuery=true&id=1826280&triage=true

**Comment by AndreyMitsyk** [comment]
@sonimishra It's not the best idea to send msazure links on github...
