### ISSUE TITLE
[Visual Requirements - Data Factories - ADF Editor] There is no textual detail provided for information conveyed using color in Editor screen.

### ISSUE THREAD

**Issue by sonimishra** [Microsoft/monaco-editor#706]
Blade Name : Data Factories - ADF Editor

User Experience: 
If correct/error is conveyed only by means of color then User with visual/Cognitive disabilities will not able to interpret information passed using color's.

Test Environment:
OS: Win 10 RS3
Build: 16299.15
Platform: Edge, Firefox
Screen Reader: Narrator, NVDA

Repro Steps:
1-Navigate to https://portal.azure.com/ and login using valid credentials.
2-Navigate to More Services option and select "data Factory" option.
3-Navigate to various Data factories listed and select anyone
4-Navigate to the Actions section lying on the blade opened and select "Author and Deploy" option.
5-Navigate to New Pipeline option lying on the blade opened and select it.
6-Navigate to ADF Editor screen and edit the field with wrong input then an error indication will red color is displayed on right of the editor field.
7-Verify that correct /error information is conveyed only by means of color.

 
Actual Result:
There is no textual detail provided for information conveyed using color in Editor screen. Correct /Error information is conveyed only by means of color.

Expected result:
There should be textual detail provided for the correct /error information conveyed using color in Editor screen.
![mas1 4 1_datafactories_information is conveyed only by means of color](https://user-images.githubusercontent.com/30456910/35376384-e5eaf186-01d0-11e8-8c9f-3b489ccef252.png)

MAS Reference:
MAS 1.4.1 - Use of Color (16)

https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b9f1f0271-42a1-45b1-be00-31473ba2e579%7d

**Comment by sonimishra** [comment]
Azure Data Factory Bug reference ID : Bug 1826254 (https://msazure.visualstudio.com/One/_workitems?_a=edit&newQuery=true&id=1826254&triage=true)

**Comment by alexandrudima** [comment]
There is the keybinding `F8` that loops through and presents in textual format all the warnings and errors in the editor.
