### ISSUE TITLE
Positive/negative lookbehind syntax is being identified as invalid in Monaco find dialog

### ISSUE THREAD

**Issue by KirkMunro** [Microsoft/monaco-editor#708]
monaco-editor version: `v0.10.1` latest (see editor, here: https://microsoft.github.io/monaco-editor/index.html)
Browser: firefox, also VS Code editor
OS: Windows 10

#### Issue

In the Monaco sample editor (linked above), try to find any i's that are not immediately preceded by the letter r using the Find dialog with a regular expression. Steps:

1. Navigate to https://microsoft.github.io/monaco-editor/index.html.
1. In the embedded sample editor, press Ctrl+F.
1. Click the regex button.
1. In the search field, enter the following:
    (?<!r)i

The editor currently shows an error, indicating that the search string contains an invalid regular expression group.

#### Expected behavior

The Monaco editor should support both positive and negative lookbehind in regular expressions, so that you can use those in your search strings.

**Comment by alexandrudima** [comment]
This will work once JavaScript implements support for lookbehinds. i.e. this is nothing implemented in the Monaco Editor.

See https://v8project.blogspot.com/2016/02/regexp-lookbehind-assertions.html
https://github.com/goyakin/es-regexp-lookbehind
