### ISSUE TITLE
Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by salileo** [Microsoft/monaco-editor#710]
monaco-editor version: 0.10.0
Steps or JS usage snippet reproducing the issue:
Seeing the following 2 console errors at random times during usage -

```
message: Unable to get property 'length' of undefined or null reference
number: -2146823281
stack: TypeError: Unable to get property 'length' of undefined or null reference
   at e._getEOL (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:354170)
   at e.fromRawTextSource (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:354310)
   at e.resolveCreationData (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:707846)
   at e (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:707290)
   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:796791)
   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:808443)
   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:812455)
   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:825837)
   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:837412)
   at e.prototype._createModelData (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:1010464)
```

```
TypeError: Unable to get property 'length' of undefined or null reference
   at t.prototype.getLineCount (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:143753)
   at e.computeLinks (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:131490)
   at t.computeLinks (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:132159)
   at e.prototype.computeLinks (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:148068)
   at t.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110446)
   at handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110099)
   at e.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:108181)
   at e.prototype.handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:107706)
   at t.prototype.onmessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110172)
   at self.onmessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:150787)
message: Unable to get property 'length' of undefined or null reference
```

**Comment by alexandrudima** [comment]
Deminified stacks:

---

TypeError: Unable to get property 'length' of undefined or null reference
[   at e._getEOL (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:354170)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/textSource.ts#L113)
[   at e.fromRawTextSource (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:354310)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/textSource.ts#L127)
[   at e.resolveCreationData (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:707846)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/textModel.ts#L50)
[   at e (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:707290)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/textModel.ts#L105)
[   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:796791)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/textModelWithTokens.ts#L74)
[   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:808443)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/textModelWithMarkers.ts#L32)
[   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:812455)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/textModelWithDecorations.ts#L150)
[   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:825837)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/editableTextModel.ts#L61)
[   at t (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:837412)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/model/model.ts#L47)
[   at e.prototype._createModelData (monaco-editor/0.10.0/min/vs/editor/editor.main.js:31:1010464)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/services/modelServiceImpl.ts#L352)

---

TypeError: Unable to get property 'length' of undefined or null reference
[   at t.prototype.getLineCount (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:143753)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/services/editorSimpleWorker.ts#L108)
[   at e.computeLinks (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:131490)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/modes/linkComputer.ts#L175)
[   at t.computeLinks (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:132159)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/modes/linkComputer.ts#L281)
[   at e.prototype.computeLinks (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:148068)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/editor/common/services/editorSimpleWorker.ts#L410)
[   at t.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110446)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L329)
[   at handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110099)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L311)
[   at e.prototype._handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:108181)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L157)
[   at e.prototype.handleMessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:107706)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L119)
[   at t.prototype.onmessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:110172)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/common/worker/simpleWorker.ts#L316)
[   at self.onmessage (monaco-editor/0.10.0/min/vs/base/worker/workerMain.js:7:150787)](https://github.com/Microsoft/vscode/blob/9b725bd7807ee959240b4af7906fae119b0fbf9e/src/vs/base/worker/workerMain.ts#L28)

**Comment by alexandrudima** [comment]
`MirrorModel._lines` is never assigned null or undefined, so this stack trace does not make sense to me...
