### ISSUE TITLE
[Keyboard Navigation - Data Factories - ADF Editor] Tooltip does not render while setting focus using keyboard at the editor under ADF Editor Screen

### ISSUE THREAD

**Issue by sonimishra** [Microsoft/monaco-editor#713]
Blade Name : Data Factories - ADF Editor

User Experience:
If Tool tip is not accessible through Keyboard then the users with visual and motion disabilities will not able to access the information present in the Tool tip.

Test Environment:
OS: Win 10 RS3
Build: 16299.15
Platform: Edge, Firefox
Screen Reader: Narrator, NVDA

Repro Steps:
1-Navigate to https://portal.azure.com/ and login using valid credentials.
2-Navigate to More Services option and select "data Factory" option.
3-Navigate to various Data factories listed and select anyone
4-Navigate to the Actions section lying on the blade opened and select "Author and Deploy" option.
5-Navigate to New Pipeline option lying on the blade opened and select it.
6-Navigate to ADF Editor screen and verify the issue.
 
Actual Result:
Tool tip is not accessible through Keyboard at the editor fields under ADF Editor Screen.

Expected result:
Tool tip should be accessible through Keyboard at the editor fields under ADF Editor Screen.

MAS Reference:
MAS 2.1.1 - Keyboard (36)
![mas2 1 1_datafactories_tootipnotaccessible](https://user-images.githubusercontent.com/30456910/35508832-cfebc23a-0517-11e8-9c9c-cbcc41ee8901.png)

**Comment by sonimishra** [comment]
Azure Data Factory Bug Reference Id : BUG 1826186
https://msazure.visualstudio.com/One/_workitems?id=1826186&_a=edit

**Comment by egamma** [comment]
The command ´Show Hover´ is exposed by the Monaco Editor. It is bound to CTRL K + CTRL I. This keybinding also works in the Azure portal.
