### ISSUE TITLE
Website footer copyright info out of date

### ISSUE THREAD

**Issue by FabianLauer** [Microsoft/monaco-editor#716]
Seems like the website copyright is out of date, it shows 2017 on both on the playground and the normal page as well as the license (1c96b05095b26d408e949165818b5bd494e31d4f) :wink:

**Comment by rebornix** [comment]
@FabianLauer thanks for the remind!

**Comment by jjyyxx** [comment]
Why one of the dates is changed to 2019?

**Comment by rcjsuen** [comment]
I mentioned this in #707 also but it looks like no one has had a chance to look at this yet.

**Comment by jjyyxx** [comment]
Yes, it's somewhat frustrating. New features are introduced to vscode repo frequently but this repo remains motionless.

**Comment by rebornix** [comment]
@jjyyxx Thanks for pointing it out, my fat finger.

@rcjsuen sorry for not being able to merge your PR, I should look through them next time, thanks again for your help.

**Comment by rcjsuen** [comment]
@rebornix You don't need to apologize to me. I wasn't the one that opened the #707 pull request.

I see that you've fixed the date with a9a9a486ce14ba1b0b8957f478b92f88e6e0ce55 now though so I think you can close it.

**Comment by FabianLauer** [comment]
Didn't see that there was a PR about this already at the time I created the issue, sorry bout that.
