### ISSUE TITLE
Error loading typescript Worker

### ISSUE THREAD

**Issue by j-lnaddef** [Microsoft/monaco-editor#717]
I git cloned monaco-typescript, installed everything, and opened the test/index.html in my favorite browser : everything works perfectly.

Then I launched http-server, went to `http://localhost:8080/monaco-typescript/test/`, and I get : 
`GET http://localhost:8080/monaco-typescript/node_modules/monaco-editor-core/out/src/worker.js 404 (Not Found)`
`{errorCode: "load", moduleId: "vs/language/typescript/src/worker", neededBy: Array(1), detail: {…}}`

It seems the path to worker.js is not resolved correctly as it should be in `http://localhost:8080/monaco-typescript/out/src/worker.js` instead.

I browsed the opened issues and saw similar problems, about the fact that the WebWorker code is not resolving the relative paths correctly or something like that, but I could not find how to solve that.

So, any way to solve this? @alexandrudima

**Comment by alexandrudima** [comment]
I've added support for that test page to run under `http`. When running under `http`, a web worker will be created and the `paths` settings must be absolute, as the roots are different for the main thread and the worker.
