### ISSUE TITLE
Change ILink's url to be optional 

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/monaco-editor#719]
Currently, `ILink` is defined as an interface with two properties, a `range` and a `url`. Both of these properties are not optional. The `DocumentLink` in the language server protocol however is defined almost identically with a `range` and an optional `target?`. This seems reasonable given that the range of text to be clicked on should be identifiable visually. On the other hand, the actual "place" of where the link will lead to is not necessarily needed until the user hovers over it or clicks on it.

https://github.com/Microsoft/monaco-editor/blob/bad3c34056624dca34ac8be5028ae3454172125c/monaco.d.ts#L4790-L4793
If neither of the two properties in `ILink` are intended to be optional, then what is the point of the `resolveLink` function? If `provideLinks` is just going to make links that are fully usable, then what's the point of "resolving" a link?

If there are no plans to make changes to `ILink`, could some documentation please be added to `LinkProvider` then?

**Comment by alexandrudima** [comment]
It is a typing mistake. It should be:
```ts
export interface ILink {
	range: IRange;
	url?: string;
}
```
 The `ILink` will go through `resolveLink` if it is missing an `url`.
