### ISSUE TITLE
TextMate - OnigurumaJS

### ISSUE THREAD

**Issue by snadrus** [microsoft/monaco-editor#722]
The Oniguruma C library is a significant limit. 

 https://github.com/bcoe/onigurumajs 
... solves this with a pure JS implementation that maps to native regex (for performance).

**Comment by hediet** [comment]
We currently do not plan to adopt OnigurumaJS.

However, we would be very interested in this if you could show that using OnigurumaJS over Oniguruma wasm speeds up tokenization in VS Code.
