### ISSUE TITLE
Expose access to JSON worker

### ISSUE THREAD

**Issue by TedDriggs** [microsoft/monaco-editor#727]
`monaco.languages.typescript` has methods for getting the JS and TS workers, but there is no analogous method for JSON. This seems to imply that getting access to the diagnostic messages requires mining the decorator information or running a second language server.

**Comment by rcjsuen** [comment]
I think you need to open an issue in the [Microsoft/monaco-json repository](https://github.com/Microsoft/monaco-json) instead.

**Comment by TedDriggs** [comment]
@rcjsuen that repo doesn't accept issues; [it says to file them here](https://github.com/Microsoft/monaco-json#issues).

**Comment by rcjsuen** [comment]
@TedDriggs Oh, you are right! Don't I feel stupid. Sorry... (><)

**Comment by aeschli** [comment]
@TedDriggs Please describe what you are trying to achieve.

There's `monaco.languages.json` that let you configure the JSON worker, e.g. if you want validation or not.

To get access to the diagnostic messages, use `monaco.editor.getModelMarkers`:

You can try this on the Monaco playground:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults
```
// Configures two JSON schemas, with references.

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
    validate: true,
    schemas: [{
        uri: "http://myserver/foo-schema.json",
        schema: {
            type: "object",
            properties: {
                q1: {
                    type: "string"
                }
            },
            required: [ 'q1']
        }
    }]
});


var jsonCode = [
    '{',
    '    "$schema": "http://myserver/foo-schema.json"',
    "}"
].join('\n');

monaco.editor.create(document.getElementById("container"), {
    value: jsonCode,
    language: "json"
});

setInterval(() => {
    console.log(monaco.editor.getModelMarkers({}).map(m => m.message).join(', '));
}, 2000);

```

**Comment by TedDriggs** [comment]
@aeschli can I get markers for a model, or do I have to get them for the currently-loaded document?

**Comment by TedDriggs** [comment]
@aeschli I'm trying that, but it's always a character behind, and I'm not sure how to mitigate that without adding a timeout and hoping for the best.

**Comment by aeschli** [comment]
Oh, I see. Can you describe what you need the markers for?
A marker change event makes sense. An API on the JSON worker to compute markers would not be hard to add, but it's not something we have at other places.

**Comment by TedDriggs** [comment]
It's easiest to explain with a picture:

![schema editor](https://user-images.githubusercontent.com/4805575/37102424-a8e56aba-21dc-11e8-9dc0-1404351e867d.png)

The error that you currently see is a semantic error I've implemented on my own worker thread. I'd like to show schema and syntax errors alongside my semantic errors. Since the other non-Monaco form fields can also have errors, I'm keeping the source-of-truth diagnostics list in the redux store.

(As an aside, I'm planning to figure out the character ranges for those and add my own model markers, but I've run into Microsoft/node-jsonc-parser#7 which has stymied that ambition for now.)

**Comment by pcasa** [comment]
Any progress with this?  Going through the same goal of trying to validate JSON via the worker vs getModelMarkers.

**Comment by pcasa** [comment]
This provided a workaround https://github.com/Microsoft/monaco-editor/issues/30#issuecomment-316418679
