### ISSUE TITLE
Clearing hover provider

### ISSUE THREAD

**Issue by solemnify** [Microsoft/monaco-editor#728]
monaco-editor version: 0.X.Y
Browser: Chrome
OS:  Win 10
Steps or JS usage snippet reproducing the issue:
Similar to clearing delta decorations, is there any way to clear the hover provider? Every time I register additional hover providers, looks like the content gets added to the provider, which seems valid based on the documentation. I want to replace the content every time I register the hover provider instead of amending, was wondering if this is possible.

**Comment by rcjsuen** [comment]
@solemnify Isn't that what the returned `IDisposable` is for? If you call its `dispose()` function then that hover provider won't be registered anymore.

**Comment by rcjsuen** [comment]
@solemnify Sounds great! If you have no further questions, please close this issue.

Good luck with your project!
