### ISSUE TITLE
Custom white color that Monaco Editor shows before render the control

### ISSUE THREAD

**Issue by mvegaca** [Microsoft/monaco-editor#729]
Hi

We are integrating Monaco Editor in [Microsoft Windows Template](https://github.com/Microsoft/WindowsTemplateStudio) Studio project to show new files and modified files when a developer is adding new pages or features to an existing project.

On this new release, we are integrating Visual Studio Color Service in the wizard, adding Dark Theme support. We are adding the setting `theme: "vs-black"` to Monaco editor, but it quickly shows a white screen before rendering the control, and it produces a strange effect because the layout is on dark theme.
It also happens on [Monaco Playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world) if I add the dark theme and click on run button.

Is there any way to avoid this white screen before render the control or custom that color?
We are loading Monaco editor in [this HTML file](https://github.com/Microsoft/WindowsTemplateStudio/blob/dev/code/src/UI/Assets/Html/Document.html) displayed on a Web Browser control inside the WPF application.

Thank you so much.

**Comment by alexandrudima** [comment]
@mvegaca I don't observe any flashing when running at https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world the following sample:

* js:
```js
setTimeout(function() {
    monaco.editor.create(document.getElementById("container"), {
        value: "function hello() {\n\talert('Hello world!');\n}",
        language: "javascript",
        theme: "vs-dark"
    });
}, 1000);
```

* html:
```html
<div id="container" style="height:100%;background:#1e1e1e"></div>
```

Notice how there is a white flash, but that happens before the monaco editor executes anything. The creation of the editor (which is delayed by 1s) makes no background flash:

![kapture 2018-03-02 at 15 09 11](https://user-images.githubusercontent.com/5047891/36902698-b1bc72a0-1e2b-11e8-80d2-f8710f2faf9d.gif)

**Comment by mvegaca** [comment]
The white color displayed is, in this case, the background color of the web browser, the gif image you added shows it: White Screen -> Black Screen -> Code Displayed.

The following Image shows the effect on WTS Wizard.

![darktheme-issue](https://user-images.githubusercontent.com/5556784/36963582-22717624-2054-11e8-8047-4ce427601c40.jpg)

I think it is caused because the Web browser is loaded as a white control, and then Monaco starts using the dark theme.

**Comment by mvegaca** [comment]
We've done a visibility updates implementation to fix it. Thank you.
