### ISSUE TITLE
Autosuggest with JSON Schema does not work for patternProperties 

### ISSUE THREAD

**Issue by viccsjain** [Microsoft/monaco-editor#730]
monaco-editor version: tried on [playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults).
Browser:  Chrome
OS:  Windows

1. Go to [playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults).
2.  Add following schema:
   ```
schema: {
            type: "object",
            properties: {
                q1: {
                    type: "object",
                    patternProperties: {
                        '^[a-z0-9-_]+$': {
                            type: "object",
                            required: [
                                "Name"
                            ],
                            properties: {
                                "Name": {
                                    type: "string"
                                }
                            }
                        }
                    }

                },

            },
        }
   ```
3. Click on run.
4. On RHS, Select the `$schema` under which above schema was added.
5.  Hit `ctrl + space`.
6. It should suggest `q1`. 
   Then inside this, for any key it does not provide any autosuggestion according to schema.

**Ideal Case:**
Ideally Inside `q1` Property, If I add any key, it should autosuggest me `Name`
like this:

```
  {
    "$schema": "//SCHEMA URL",
    "q1": {
        "Key": {
            // it should autosuggest Name here.
        }
    }
}
```

**Comment by aeschli** [comment]
@viccsjain The regular expression in your example only matches lowercase characters, so `Key` is not matching.
If you change the sample to `key` it works as expected:

![image](https://user-images.githubusercontent.com/6461412/36902996-9c048dde-1e2c-11e8-8bce-cf3587c69374.png)

**Comment by viccsjain** [comment]
Thanks @aeschli .
This worked for me.
Thanks again.
