### ISSUE TITLE
Code snippets

### ISSUE THREAD

**Issue by Myqilixiang** [Microsoft/monaco-editor#734]
I'd like to ask for how to set user code snippets in monaco editor,such as we can make it in vscode through create javascript.json.

**Comment by alexandrudima** [comment]
You can register a completion item provider

e.g. 

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

**Comment by FateRiddle** [comment]
@alexandrudima Sorry but I don't understand the example, what does it do? I tried a bit, not seeing autocompletion. Can you elaborate a bit?

**Comment by rcjsuen** [comment]
@FateRiddle Did you try looking at the example that was linked? Doesn't code completion work there?

If you have issues you should share your code so people can try to reproduce the problem.
