### ISSUE TITLE
Some clairifcation  about models and their relation to the editor its self

### ISSUE THREAD

**Issue by kingerking** [Microsoft/monaco-editor#736]
I couldn't help to notice that the documentation of a lot of what seems to be important constructs of the monaco editor API is a bit bland and doesn't really help, one of which is the IModel interface, I searched around the internet for awhile trying to fully grasp what A IModel is. The reason why I would like clarification is that I want to implement multiple editors on my webpage and I'm not sure of the correct way of achieving this.

**Comment by rcjsuen** [comment]
@kingerking The model is the actual document that is being shown in the Monaco Editor. If you are editing multiple files then you are probably going to have multiple models.

**Comment by kingerking** [comment]
Ohh, i see. that makes sense. Thank you for help.
