### ISSUE TITLE
trigger auto-complete (suggestions) programmatically

### ISSUE THREAD

**Issue by jefflevinson** [Microsoft/monaco-editor#74]
I have a suggestion as follows:
insertText: 'sum({{}})'
When the text is inserted the cursor is within the parenthesis appropriately. However, as soon as the text is inserted, I want to pop up the suggestions for what should go there without the user taking an action. I could not figure out how to accomplish this with a suggestion trigger which seems to have to be typed in by the user.

Thanks.

**Comment by alexandrudima** [comment]
`editor.trigger('source - use any string you like', 'editor.action.triggerSuggest', {});`

**Comment by jefflevinson** [comment]
I tried the above and it doesn't seem to trigger the suggestion. In addition, it's a strange construct. The text matching matches the line to the current point (supposedly) but it actually returns "sum()" instead of "sum(" which I would have expected since the cursor is in-between the parenthesis. But even when I change the match to "sum()" it still doesn't actually show the auto-complete even though I'm returning a list.

**Comment by alexandrudima** [comment]
@jrieken This touches on the support to execute something/a command (that just happens to be to pop up suggestions again) when a completion item is accepted. Maybe you keep this request also in mind when designing it?

**Comment by aoto** [comment]
@alexandrudima how to send suggest items when do the triggerSuggest?

**Comment by aoto** [comment]
My case is when I input the `.`, it tips the table column list, and the language is SQL.
```ts
editor.onDidChangeModelContent(e => {
  if (e.text === '.') {
    monaco.languages.registerCompletionItemProvider('sql', {
      provideCompletionItems: () => {
        return [
          {
            label: 'column1',
            kind: monaco.languages.CompletionItemKind.Text
          },
          {
            label: 'column2',
            kind: monaco.languages.CompletionItemKind.Text
          }
        ]
      }
    });
    editor.trigger('source - use any string you like', 'editor.action.triggerSuggest', {});
  }
})
```
if i use registerCompletionItemProvider, it should input `col...` then completion show, bug I want auto show the column1, column2 completetion.  

I have researsh this case for about two days, i need some tip. Thanks!

**Comment by aoto** [comment]
@alexandrudima Some response？

**Comment by lidermanrony** [comment]
Any update on this feature? I would love to have the possibility to re-open suggestion dialog once user accepts a previous completion item.

any other workaround to know when suggestion was accepted?

**Comment by jrieken** [comment]
> I would love to have the possibility to re-open suggestion dialog once user accepts a previous completion item

We can do that, set `editor.action.triggerSuggest` as command on a suggestion.

**Comment by Hamund** [comment]
Is this fixed by this: https://github.com/Microsoft/vscode/issues/34565 ? If so, any chance monaco-editor-core version could be bumped?

**Comment by jrieken** [comment]
A new release will come eventually (not sure yet). Closing this issue because the underlying issue is fixed
