### ISSUE TITLE
Bug: In Microsoft Edge, copy-paste queries is loosing its coloring

### ISSUE THREAD

**Issue by rogarfel** [Microsoft/monaco-editor#741]
monaco-editor version: 0.9.0 and the latest version
Browser: Microsoft edge
Steps reproducing the issue:
1. Write a query in Microsoft Edge
2. Copy the query text (using Ctrl-C)
3. Paste this text in e-mail.

The style and the colors of the query don't saved.

**Comment by rebornix** [comment]
We didn't turn this feature on for Edge as it's either impossible (stable) or buggy (Edge insider) at this moment, per https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11780845/

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/563c459e7b296c4961fac399c511ff1b37381117 (typo...)
