### ISSUE TITLE
Controlling view zone's position

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#744]
Are there ways:
- to add a view zone before the line
- to add a view zone before/after another view zone by id, given that rendering of a referenced zone is not under control, e.g. to add a view zone after a deleted line (view zome) in a modified editor

**Comment by akosyakov** [comment]
@alexandrudima Thank you! I will give it a try.

**Comment by phuctm97** [comment]
Hi everybody. Btw this issue, I am new to monaco editor and playing around view zones but I can not interact with the view zone (e.g. add textarea to view zone), is the view zone designed for "view only" purpose? Although there are content widgets which are interactable but the behavior is different, content widgets will overlay on the editor while view zones will sit right on the editor. Thanks in advance.
