### ISSUE TITLE
TS coloring does not support the latest syntax

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#746]
For example, `readonly` is not colored as a keyword.

**Comment by alexandrudima** [comment]
The TS lexer returns `identifier.ts` for it in the following example:
```ts
export class Cell {
	public readonly row: number;
}
```

So perhaps TypeScript allows to have a variable called `readonly` and the lexer choses to not mark this as a keyword.

**Comment by alexdima** [comment]
This has been fixed in the meantime, we are now using a Monarch colorizer for TS.
