### ISSUE TITLE
Adding a new Class to the Autocompletion

### ISSUE THREAD

**Issue by siyahrichard** [microsoft/monaco-editor#747]
I want to register many user defined Classes and their methods and properties. but the following code just can define the Class name only... 

> How Can I add The Class Methods and Properties as a type

```
monaco.languages.registerCompletionItemProvider('javascript', {
	provideCompletionItems: () => {
		return [
       		   {
				label: 'someClass',
				kind: monaco.languages.CompletionItemKind.Class,
				insertText: {
					value: 'someClass'
				},
				documentation: '?How to add methods and fields to the user defined class?'
			}
		]
	}
});```

does this process reduces the run-time performance?

**Comment by rcjsuen** [comment]
Maybe take a look at the [Configure JavaScript Defaults](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-javascript-defaults) example?

You can also look at the example's JavaScript code directly [in the repository](https://github.com/Microsoft/monaco-editor/blob/52ca2e17cdc7b95d93f0ae36f777611357d5da49/playground/new-samples/extending-language-services/configure-javascript-defaults/sample.js).
