### ISSUE TITLE
[Microsoft Edge] Copying content that is protected by Windows Information Protection is blocked

### ISSUE THREAD

**Issue by meni-braun** [microsoft/monaco-editor#748]
monaco-editor version: 0.10.1
Browser: Microsoft Edge 41.16299.248.0
OS: Window 10 1709 (OS Build 16299.248)

Steps or JS usage snippet reproducing the issue:
1. On an application that is protected by Windows Information Protection (i.e. Microsoft Outlook), copy corporate content and paste it to Monaco code editor in Microsoft Edge.
2. A dialog box is shown, asking "Use work content here?" - choosing "Yes" does nothing.
3. Pasting 2nd time, and clicking "Yes" doesn't do anything as well, but
4. Pasting the 3rd time the same copied text (that was copied on step #1) - the text is finally pasted

Copying another piece of data to an <input type="text"> element, works after the first paste (after clicking "yes" in the "Use work content here" dialog).

**Expected behavior:**
Copied text that is pasted, should be pasted after the first attempt (after clicking "yes" in Windows Information Protection dialog)

**Actual behavior:**
Pasting text to Monaco editor behaves differently than other textboxes.

**Comment by alexdima** [comment]
Closing, as Microsoft Edge Legacy has reached end of support on March 9, 2021. See [the end of support for Microsoft Edge Legacy announcement](https://docs.microsoft.com/en-us/lifecycle/announcements/edge-legacy-eos-details)
