### ISSUE TITLE
Add link to autocompletion's documentation

### ISSUE THREAD

**Issue by fnando** [Microsoft/monaco-editor#749]
Is there a way of having a clickable link on [autocompletion's documentation](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitem.html#documentation)? I tried adding raw HTML and it's being escaped for security reasons (and that's a good thing).

If that's not possible, consider this a feature request.

Cheers!

[![Autocompletion's documentation escapes HTML][1]][1]

[1]: https://i.stack.imgur.com/m83lQ.png

**Comment by rcjsuen** [comment]
See #689 for Markdown support.

**Comment by ryanlin1986** [comment]
This is much needed for my scenario as well, I'm not using link, but want signature color, as following:
![image](https://user-images.githubusercontent.com/11850439/38391041-afe0bc26-3955-11e8-9679-356174c83b8d.png)
Currently I can only get:
![image](https://user-images.githubusercontent.com/11850439/38391061-bfe70922-3955-11e8-8a79-1ec4943ddb7e.png)

**Comment by rcjsuen** [comment]
@ryanlin1986 If you want HTML support (full or partial) I suggest you open a new GitHub issue.

**Comment by ryanlin1986** [comment]
Got it ,thanks
