### ISSUE TITLE
Can't use "Enter" key to accept an IntelliSense item

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/monaco-editor#756]
monaco-editor version: 0.11 on the website I'm assuming
Browser: Version 64.0.3282.186 (Official Build) (64-bit)
OS: Windows 10
Steps or JS usage snippet reproducing the issue:
1. Open the [playground](https://microsoft.github.io/monaco-editor/playground.html) website.
2. Hit <kbd>Ctrl</kbd>+<kbd>Space</kbd>
3. Hit <kbd>Enter</kbd>
4. A newline is inserted instead of the proposal.

I feel like it wasn't like this before...

**Comment by rcjsuen** [comment]
Thanks for fixing this so quickly, @alexandrudima. Will you be publishing an update to npm?

**Comment by alexandrudima** [comment]
Yes, I just have a couple more things to do

**Comment by rcjsuen** [comment]
Great to hear! Thank you and everyone else for the new release!

**Comment by alexandrudima** [comment]
Just published 0.11.1

**Comment by rcjsuen** [comment]
Things look good in the Monaco Editor Playground. Thanks, Alexandru! :)
