### ISSUE TITLE
Cannot require contents of '.d.ts' files as string in browser for addExtraLib method

### ISSUE THREAD

**Issue by jacobdlewis** [microsoft/monaco-editor#758]
*monaco-editor version:* 0.X.Y

*Browser:* Chrome Version 64.0.3282.186 (Official Build) (64-bit)

*OS:* High Sierra 10.13.2

# Issue
I want to get autocomplete functionality for a third-party library, like `lodash,` in my Monaco instance. I'm using the [addExtraLib method](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.typescript.languageservicedefaults.html#addextralib) to make this happen, and I'm having trouble getting access to a valid `content` argument to provide to it.

It seems that the `content` argument needs to be the actual content of whatever `.d.ts` file you want to use, and I am unable to require the typings file via `import` in the browser.

Examples where `content` is defined in the file work just fine for me:

    monaco.languages.typescript.javascriptDefaults.addExtraLib([
        'delcare class Facts {',
        '    /**',
        '     * Returns the next fact',
        '     */',
        '     static next():string',
        '}',
    ].join('\n'), 'filename/facts.d.ts');

<img width="630" alt="screen shot 2018-03-14 at 3 51 37 pm" src="https://user-images.githubusercontent.com/10276361/37430300-c1e73980-279f-11e8-9ca4-215555014d1d.png">

However, this won't work for a larger library, as this would require manually updating the hardcoded `content` value any time the definitions file is changed.

Attempting to import the type definitions with `import * as _ from '@types/lodash` results in the following error `[ts] Cannot import type declaration files. Consider importing 'lodash' instead of '@types/lodash'.` However, importing `lodash` itself and providing that as the `content` argument for `addExtraLib` doesn't work either. It's importing the actual javascript library and doesn't communicate any type information to Monaco.

How can I require the contents of a `d.ts` file as a string in the browser/how can I add auto-complete for a third-party library in Monaco?

**Comment by cdrini** [comment]
I was able to get lodash working using `raw-loader`. Definitely doesn't feel like the right solution, but it's currently the only working one I was able to find :P Here are the steps: https://gist.github.com/cdrini/9de507f6ac19da30fd27c5f618783b31

**Comment by hediet** [comment]
We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!
