### ISSUE TITLE
Mention removal of IResourceCreate, IResourceEdit, and IResourceRename in the changelog

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/monaco-editor#761]
`IResourceCreate`, `IResourceEdit`, and `IResourceRename` were all removed in 0.11 but not mentioned as a breaking change in the changelog. `WorkspaceEdit` was also updated to reflect the new changes.

These changes were introduced in https://github.com/Microsoft/vscode/commit/dc31fa213be87c0c937324ec608e42157dbb4418.

**Comment by alexandrudima** [comment]
`IResourceCreate`, `IResourceEdit`, and `IResourceRename` were never released in the monaco editor. Here is the previous [`monaco.d.ts`](https://raw.githubusercontent.com/Microsoft/monaco-editor/v0.10.1/monaco.d.ts) from 0.10.1.

Unfortunately, 0.11.0 does introduce `ResourceFileEdit`. To my knowledge that is not honoured by the editor, as the editor rename functionality knows only how to apply `ResourceTextEdit`s and not `ResourceFileEdit`s... I will mention this in the changelog.

**Comment by rcjsuen** [comment]
@alexandrudima I see `IResourceEdit` in the file you linked to. You are right though that `IResourceCreate` and `IResourceRename` cannot be found. Sorry for the confusion.

https://github.com/Microsoft/monaco-editor/blob/2e880e008915b278482f8ee1ddbb3792e5320364/monaco.d.ts#L4795-L4799
