### ISSUE TITLE
simpleWorker reporting "Cannot read property 'vsWorker' of undefined"

### ISSUE THREAD

**Issue by jjyyxx** [Microsoft/monaco-editor#766]
monaco-editor version: 0.11.1
Browser: Chrome 64
OS: Windows 10
Steps or JS usage snippet reproducing the issue: Configure a develop environment using `webpack` and `webpackDevServer`. The dev server would post a message with type `webpackOk` (when the client-side dev server plugin is ready, I think). 
```javascript
    self.postMessage({
        type: 'webpack' + type,
        data: data
    }, '*');
```

In `editor.worker.js`, the worker received the message and passed the message to `simpleWorker.js` to handle. 
```javascript
    SimpleWorkerProtocol.prototype.handleMessage = function (serializedMessage) {  // got an object
        var message;
        try {
            message = JSON.parse(serializedMessage);
        }
        catch (e) {
            // nothing
        }
        if (!message.vsWorker) {
            return;
        }
        if (this._workerId !== -1 && message.vsWorker !== this._workerId) {
            return;
        }
        this._handleMessage(message);
    };
```

So in line 9 in `simpleWorker.js`, "Cannot read property 'vsWorker' of undefined" is thrown.

I think maybe we shall check if `message === undefined` first or simply ignore message with type prefix `webpack`?

If anyone thinks the webpack config file is necessary to provide more information, I would be happy to post it.

**Comment by TheLarkInn** [comment]
I think this would be a great PR opportunity! I also came across this and had to patch locally. Would you mind submitting a PR to the vscode repo where this code is located (and please reference this issue?)

**Comment by jjyyxx** [comment]
Thanks for the suggestion! I created a pr but I am afraid monaco editor won't release a version like 0.11.2 soon. I can patch my code locally, but I have a few collaborators and I don't think ask them to do the same is a good idea. Is there a better way to fix the issue for my team(something like a fork)?

**Comment by alexandrudima** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/46012
