### ISSUE TITLE
The esm worker support needs to more details

### ISSUE THREAD

**Issue by jjyyxx** [Microsoft/monaco-editor#769]
monaco-editor version: 0.11.1
Browser: Chrome 64
OS: Windows 10
Steps or JS usage snippet reproducing the issue: 
If I write as the esm-integrate document ask to, I run into two issues:

1. The editor.worker.js and other xxx.worker.js is injected to the output html, causing the files being loaded before I actually need them. I use webpack code splitting to lazyload the `editor.main`, so I don't want the `worker` to be loaded before I actually need it.

2. The output file is generated by webpack as `js/[name].[chunkhash].js`, which leads to unpredictable file name of the editor.worker. I currently have to change the naming rule to `js/[name].js` or manually get the `chunkhash` of the editor.worker and return sth like `'editor.worker.e639bdc616778c4ab39d.js'` in the getWorkerUrl method. I think it's a dirty solution and I want to keep the hash in the filename. Any suggestion on the issue (like using defineplugin) ?

**Comment by FrankFang** [comment]
As to your issue 2:
1. Use [webpack-manifest-plugin](https://www.npmjs.com/package/webpack-manifest-plugin) to generate a map to list all your entries.
2. Pass the map to window.manifest or whatever.
3. use window.manifest['js.worker.js']

That's it.

**Comment by gunn4r** [comment]
@jjyyxx Would love to see your solution here. I have the same problems for #1 and #2.

**Comment by jjyyxx** [comment]
@gunn4r It has been a long time since I experimented with this issue. Have you tried [monaco-editor-webpack-plugin](https://github.com/microsoft/monaco-editor-webpack-plugin)? I think it could solve your problem. If it does not help, I will try to recall how I dealt with it.
