### ISSUE TITLE
Ability to customize the completionItemKind?

### ISSUE THREAD

**Issue by jefflevinson** [microsoft/monaco-editor#77]
Is there a way to provide our own icons for this list? the Monaco.d.ts file doesn't contain anything in the interfaces that really jump out at me.

Thanks.

Maybe this is just a suggestion then?

**Comment by sam-1994** [comment]
Is there some update on this feature?
I would also like to create custom completionItemKind Icons or just use a colored block.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/63802

The developer who owns this feature is available there.
