### ISSUE TITLE
How does DocumentColorProvider work?

### ISSUE THREAD

**Issue by gujiman** [Microsoft/monaco-editor#775]
monaco-editor version: 0.11.1
Browser: chrome
OS: win 10
Steps or JS usage snippet reproducing the issue:

How does DocumentColorProvider work? Can someone provide us an example I can try out on the playground?
ref: https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L4945

Cheers in advance!

**Comment by AndersMad** [comment]
Did you register it? E.g. `monaco.languages.registerColorProvider("css", new MyCssColorProvider());`. 

The  cssWorker.js has a `findDocumentColors` - but I think there are some missing pieces to use that (?) - but I did not look much into that as I have made a custom find colors using tokens to also support SCSS vars and inline style in HTML etc.

**Comment by gujiman** [comment]
@AndersMad Any chance you can let us view your code so we can test it out in the playground (anything basic to start us off)? cheers!

**Comment by gujiman** [comment]
@rcjsuen brilliant starting point for anyone that wants to use this feature

**Comment by alexandrudima** [comment]
Thank you for the code snippet, I've added a sample with it.
