### ISSUE TITLE
Double quotes in javascript

### ISSUE THREAD

**Issue by kemalbirinci** [Microsoft/monaco-editor#777]
Hi,

I use monaco editor 0.11.6 for my javascript editing page. I take content from db and regex split rule is "\r\n|\r|\n"

**var a='1';** is working (single quotes)
**var a="1";** is not working (double quotes)

This is the error in the console.

Uncaught SyntaxError: missing ) after argument list

Do you have an idea for this?

**Comment by rcjsuen** [comment]
@kemalbirinci How can this bug be reproduced? It's not clear to me where Monaco fits in this bug. Are you getting an error when you are typing in the editor or when you are initializing the editor with some content?

**Comment by kemalbirinci** [comment]
Hi @rcjsuen There is no any error while typing. I save js content in database. And when I try to set js content to monaco editor, I get that error, if I typed double quote for strings.

**Comment by rcjsuen** [comment]
@kemalbirinci I suggest you try to extract some code from your project and reproduce the bug in the [playground](https://microsoft.github.io/monaco-editor/playground.html).

**Comment by kemalbirinci** [comment]
Thank you @rcjsuen . I understand now why I see this error. 

This was my code. 
jsArr.push("@Html.Raw(jsCode)");

Replace with
jsArr.push("@Html.Raw(jsCode.Replace("\"", "\\\""))");

And its working now. 

I waste your time. Thank you so much for helping.

**Comment by rcjsuen** [comment]
@kemalbirinci I'm glad your problem has been resolved. Please close this issue.

Good luck with your project!
