### ISSUE TITLE
"Find All References" doesn't work in Monaco 0.11.1

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/monaco-editor#779]
monaco-editor version: 0.11.1
Browser: Chrome, Firefox, Edge, IE 11
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

* Open the [Monaco webpage](https://microsoft.github.io/monaco-editor/index.html).
* In the sample TypeScript code, right-click on `Cell` and select "Find All References":
![monaco-findallreferences](https://user-images.githubusercontent.com/13289184/37600393-7d083cc4-2b87-11e8-8f6a-dc6ffa8419be.png)
* Nothing will happen. If you open the console, you can see the following error printed:
![grafik](https://user-images.githubusercontent.com/13289184/37600427-93e33084-2b87-11e8-8e17-21dadee0cc5e.png)

Note: The same problem occurs when selecting "Peek Definition".

Note also that the error message in IE 11 is a bit different than the one in Edge, Firefox and Chrome, as in IE, it says "undefined depends (...)", instead of "n depends (...)":

![monaco-error-ie](https://user-images.githubusercontent.com/13289184/37601219-bc9fbacc-2b89-11e8-80ac-df67d3354f4a.png)

I also experienced this problem after runnin `npm install monaco-editor` and running the local version of Monaco 0.11.1

Thanks!

**Comment by qingruibin** [comment]
The same question

**Comment by qingruibin** [comment]
There's a way to solve your mistakes
Need to modify the JS file.
open: monaco-editor/dev/vs/editor/editor.main.js
goto : 68895 line.

Replace the code:
```

  SimpleEditorModelResolverService.prototype.findModel = function (editor, resource) {
            var model = editor.getModel();
            if (model.uri.toString() !== resource.toString()) {
                return null;
            }
            return model;
        };

```

change to:

  SimpleEditorModelResolverService.prototype.findModel = function (editor, resource) {
      return monaco.editor.getModel(resource); 
  };

**Comment by gujiman** [comment]
@qingruibin your fix doesnt work for v0.11.1. I think your ref code is from v0.10.1 (editor.main.js, goto : 68895 line)

**Comment by qingruibin** [comment]
![image](https://user-images.githubusercontent.com/11595237/37748462-ea17cabc-2dbe-11e8-927f-ece4a3f264ef.png)

**Comment by qingruibin** [comment]
@gujiman  
yes  What I'm using code is  from v0.10.1

**Comment by qingruibin** [comment]
![image](https://user-images.githubusercontent.com/11595237/37759542-e347894a-2dee-11e8-8b5e-ca2e15014942.png)

**Comment by qingruibin** [comment]
![image](https://user-images.githubusercontent.com/11595237/37759591-066b9fb0-2def-11e8-92d2-b5eb73ea56e9.png)

**Comment by qingruibin** [comment]
need fix source code :
\vs\editor\standalone\browser\standaloneServices.ts

model:
  StaticServices

add code to [StaticServices] last:
       export const listService = define(IListService, (o: any) => new ListService(o));

**Comment by qingruibin** [comment]
Of course, you can also modify the JS file:
![image](https://user-images.githubusercontent.com/11595237/37769612-84691ba0-2e0c-11e8-9a21-a808ae41e083.png)

1 step:
  fond keyword:  ` StaticServices.logService = define `
2 step:
   insert code to :
   `StaticServices.listService = define(listService_1.IListService, function (o) { return new listService_1.ListService(o); });`

**Comment by Viatorus** [comment]
I had to add this:
```
StaticServices.listService = define(IListService, function (o) { return new ListService(o); });
StaticServices.logService = define(ILogService, function (o) { return new NullLogService(o); });
```
