### ISSUE TITLE
Click lightbulb context menu && How to register a command with the specified id?

### ISSUE THREAD

**Issue by vincentLiuxiang** [Microsoft/monaco-editor#782]
Hi all, when I develop a webide via lsp and monaco-editor, I encountered this difficulty.

When I click the lightbulb, the context menu shows (all the codeAction infomation get from back end via lsp ).

The lsp server response:
<img width="1047" alt="2018-03-21 4 28 09" src="https://user-images.githubusercontent.com/10772305/37700185-82bdc8ba-2d25-11e8-91cd-b3f56bbbb62d.png">

<img width="567" alt="2018-03-21 11 50 51" src="https://user-images.githubusercontent.com/10772305/37699762-d33530aa-2d23-11e8-8f61-7fec96b6ae0c.png">

however, when I click any menu, an error occurred:

<img width="500" alt="2018-03-21 4 06 05" src="https://user-images.githubusercontent.com/10772305/37699845-3e9252ba-2d24-11e8-868f-279fc380ecda.png">

the `simpleServices.ts` file:

```ts
public executeCommand<T>(id: string, ...args: any[]): TPromise<T> {
		const command = (CommandsRegistry.getCommand(id) || this._dynamicCommands[id]);
		if (!command) {
			return TPromise.wrapError<T>(new Error(`command '${id}' not found`));
		}

		try {
			this._onWillExecuteCommand.fire({ commandId: id });
			const result = this._instantiationService.invokeFunction.apply(this._instantiationService, [command.handler].concat(args));
			return TPromise.as(result);
		} catch (err) {
			return TPromise.wrapError<T>(err);
		}
	}
```

How could I register a command with the specified id `java.apply.workspaceEdit` ?

**Comment by vincentLiuxiang** [comment]
@akosyakov could you give some help?

**Comment by akosyakov** [comment]
@vincentLiuxiang java LS expects that a client registers some commands, you will need to implement and register this command for Monaco.
