### ISSUE TITLE
Set margin´s width.

### ISSUE THREAD

**Issue by antoniopol06** [microsoft/monaco-editor#783]
monaco-editor version: 0.11.0
Browser: Chrome
OS: MacOS High Sierra

Is there any way to custom margin´s width when editor is instantiated?

If I modified the margin´s width after editor is mounted, the content of editor will not resize  depend on the margin and the icons that I added appear over numberLines.

Any suggestions?

Thanks.

**Comment by alexandrudima** [comment]
@antoniopol06 You can call `editor.layout` and pass in the width/height you want the editor to take.

**Comment by Bear1110** [comment]
@alexandrudima 

I use ```editor.layout({glyphMarginWidth:100})```, but it doesn't work.
If you can tell more detail or not?
Thank you a lot.

**Comment by wufeng87** [comment]
+1 thanks!
