### ISSUE TITLE
CompletionItemProvider, how to Insert text of CompletionItem using 'space' key, (same as it works with Enter and Tab)

### ISSUE THREAD

**Issue by IsraelZablianov** [Microsoft/monaco-editor#785]
monaco-editor version: 0.10.1
Browser: Chrome
OS: Window

**Comment by rcjsuen** [comment]
If you are creating your own `CompletionItem`s, you can use the use the `commitCharacters` property.

https://github.com/Microsoft/monaco-editor/blob/32f54336573831e97bfd1ac07da625eb6c7133fd/monaco.d.ts#L4190-L4195

**Comment by IsraelZablianov** [comment]
Thanks, 
I just checked it out and it doesn't exists on my monaco version (0.10.1)
Time to update:)

**Comment by rcjsuen** [comment]
@IsraelZablianov You can use the following code in the [playground](https://microsoft.github.io/monaco-editor/playground.html) and try it if you wish.

Run the program, use <kbd>Ctrl</kbd>+<kbd>Space</kbd> and when you see the `insert` option, hit <kbd>Space</kbd> and it should insert it for you!

```JavaScript
monaco.languages.register({
    id: "test"
});

monaco.editor.create(document.getElementById("container"), {
	value: "ins",
	language: "test"
});

monaco.languages.registerCompletionItemProvider("test", {
    provideCompletionItems: () => {
        return [
            {
                label: "insert",
                commitCharacters: [ " "]
            }
        ];
    }
});
```
