### ISSUE TITLE
Incorrect YAML highlighting after value with two opening curly braces

### ISSUE THREAD

**Issue by cmeury** [Microsoft/monaco-editor#786]
monaco-editor version: VSCode 1.21.1
OS: macOS High Sierra 10.13.3

This minimal YAML file:

```yaml
key1: highlighted
key2: "{{"
key3: not-highlighted
```

is highlighted incorrectly, while it looks like [valid YAML](https://yaml-online-parser.appspot.com/?yaml=key1%3A+highlighted%0Akey2%3A+%22%7B%7B%22%0Akey3%3A+not-highlighted%0A&type=json).

![screen shot 2018-03-22 at 13 53 56](https://user-images.githubusercontent.com/1318986/37771636-80b0a1ec-2dd8-11e8-8b0d-6e5637f52ba3.png)

**Comment by rcjsuen** [comment]
@cmeury It looks okay on the [website](https://microsoft.github.io/monaco-editor/) to me.

![image](https://user-images.githubusercontent.com/15629116/37801172-e635310a-2e68-11e8-8806-d5fe5e2862ab.png)

**Comment by cmeury** [comment]
Looks like it. Is there a large difference in progress between VSCode and the monaco-editor component? How do I find out what version of the editor my VSCode installation uses?

**Comment by rcjsuen** [comment]
@cmeury Well, the reality is that VS Code uses a [TextMate grammar](https://github.com/Microsoft/vscode/blob/af21dc79255e351a45fd4ad00a92699acaaa130c/extensions/yaml/syntaxes/yaml.tmLanguage.json) whereas Monaco uses [Monarch tokens](https://github.com/Microsoft/monaco-languages/blob/d2db3faa76b741bf4ee822c403fc355c913bc46d/src/yaml/yaml.ts) so they're not really the same thing.

**Comment by rcjsuen** [comment]
@cmeury I think you should open a bug in the [Microsoft/vscode repository](https://github.com/Microsoft/vscode/issues).

**Comment by rcjsuen** [comment]
@cmeury Actually, Martin already opened a bug about your exact problem! See textmate/yaml.tmbundle#18!

**Comment by cmeury** [comment]
Thanks for the background and pointing me in the right direction @rcjsuen, much appreciated. Closing this one.
