### ISSUE TITLE
wrappingColumn does not work in diffEditor

### ISSUE THREAD

**Issue by jpxd** [microsoft/monaco-editor#79]
In a normal monaco editor one can limit the maximum horizontal length of a line with the `wrappingColumn` option. But this doesn't work in a diffEditor.

Example:

```
var diffEditor = monaco.editor.createDiffEditor(document.getElementById('container'), {
    wrappingColumn: 100
});
diffEditor.setModel({
    original: monaco.editor.createModel("textWithLongLines", 'text/plain'),
    modified: monaco.editor.createModel("anotherTextWithLongLines", 'text/plain'),
});
```

**Comment by alexandrudima** [comment]
That is a limitation we impose, otherwise the diff regions would get out-of-sync horizontally.

**Comment by victor-homyakov** [comment]
Word wrapping still does not work in diff editor. Please, fix it or at least add some explanation in documentation https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.idiffeditorconstructionoptions.html#wordwrap to prevent wasting developer's time.

**Comment by liudonghua123** [comment]
I have the same issue about wordwrap in diff editor.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/11387
