### ISSUE TITLE
Cannot use JSON/CSS/HTML language without workers

### ISSUE THREAD

**Issue by neoncom** [microsoft/monaco-editor#793]
monaco-editor version: 0.11.1
Browser: chrome latest
OS: win 10 64bit
Steps or JS usage snippet reproducing the issue:

Run browser-esm-webpack-small sample with following changes:

in index.js:
- editor language "json"
- enable (uncomment) " import 'monaco-editor/esm/vs/language/json/monaco.contribution';"

I also changed mode to delelopment in webpack config.

Result: 

```
Error: self.require is not a function
    at eval (editorSimpleWorker.js:395)
    at new Promise_ctor (winjs.base.js:1660)
    at EditorSimpleWorkerImpl.BaseEditorSimpleWorker.loadForeignModule (editorSimpleWorker.js:393)
    at SimpleWorkerServer._handleMessage (simpleWorker.js:259)
    at Object.handleMessage (simpleWorker.js:245)
    at SimpleWorkerProtocol._handleMessage (simpleWorker.js:117)
    at SimpleWorkerProtocol.handleMessage (simpleWorker.js:89)
    at SimpleWorkerServer.onmessage (simpleWorker.js:249)
    at self.onmessage (editor.worker.js:23)
```

Why do i get this error?

It seems like the json worker is needed. But **why**? JSON syntax highlighting works perfectly without it. I don't want the this json worker :)

BTW, I am not running from "file://", i am using "npm run simpleserver". The standard language "python" (from that sample) works without issue.

This issue looks a bit like #759 but that issue requires a worker to fail due to some reason **before** it throws "self.require is not a function". This is **not** the case in this issue.

**Comment by kqadem** [comment]
Did you set `globalobject: self` in your webpack config like [here](https://github.com/Microsoft/monaco-editor-samples/blob/779a88524d1755ad087420ce459b37199bf4df0e/browser-esm-webpack-small/webpack.config.js#L16)? 

The webworkers are responsible for enhanced suggestions and syntax errors etcs. With setting the editor language to JSON everything is going to be loaded, not only the colors. 

However you can customize the imports and decide yourself what should be loaded and what not. [Example](https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-esm-webpack-small/index.js)

**Comment by alexdima** [comment]
I believe this now works.
