### ISSUE TITLE
Including monaco-editor into a page where requirejs is already loaded/available

### ISSUE THREAD

**Issue by estruyf** [Microsoft/monaco-editor#797]
Is there a way to include the loader.js in an environment where `requirejs` is already loaded?

As `monaco-editor` is using its own loader, which also uses `require`. It will always use the one from `requirejs` which results in an error that `monaco is not defined`.

Is there a way to initialize the one from the loader or rename the global require variable? 

Already tried to call AMDLoader.init(), but in that case, I'm unable to configure the config. Once I do this: `require.config({paths: {'vs': 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.11.1/min/vs'}});`, I get the following error:

```TypeError: Cannot read property 'configure' of null```

BTW: I cannot remove requirejs, as this is what the platform provides me.

**Comment by alexandrudima** [comment]
@estruyf Yes, simply don't load the `loader.js` shipped with the editor. The monaco editor should load fine with `requirejs` !

**Comment by estruyf** [comment]
Thanks @alexandrudima for your response. If I do that, I get the following error:

```
Uncaught ReferenceError: monaco is not defined
```

I see that the `editor.main.js` file gets loaded, nothing more. In case it matters, version of `requirejs` which is by default loaded: `2.1.20`.

**Comment by alexandrudima** [comment]
@estruyf I have put together here a full working example:
https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-requirejs/index.html

The only diff from the amd sample is to use requirejs instead of the shipped `loader.js`:

![image](https://user-images.githubusercontent.com/5047891/38568323-aaedba52-3ce8-11e8-8140-ff310611a9d1.png)

**Comment by estruyf** [comment]
Thanks, I can confirm the sample works, although it doesn't change anything to my issue while I try to use it. In that case, it might be the application is blocking something.

**Comment by alexandrudima** [comment]
Sorry I cannot help you further with the information you have currently provided.

**Comment by estruyf** [comment]
Closing this, as its probably an issue in the application itself and cannot make any changes to it. Thanks again.
