### ISSUE TITLE
'getExtraLibs' method is missing in the monaco.d.ts and documentation

### ISSUE THREAD

**Issue by DenisVuyka** [Microsoft/monaco-editor#798]
monaco-editor version: 0.11.1
Browser: All
OS: All
Steps or JS usage snippet reproducing the issue:

`monaco.languages.typescript.typescriptDefaults.getExtraLibs()` is not present in the `monaco.d.ts` file, and also not documented.

**Comment by alexandrudima** [comment]
@DenisVuyka I believe you are supposed to use `monaco.languages.typescript.typescriptDefaults.addExtraLib` to add additional libs.

**Comment by DenisVuyka** [comment]
@alexandrudima Adding an existing library causes exception. What is the correct way then testing the lib has not been previously added?

**Comment by DenisVuyka** [comment]
Are we talking about the same api? The one I'm looking at has two parameters
https://github.com/Microsoft/monaco-typescript/blob/master/src/monaco.contribution.ts#L43

**Comment by DenisVuyka** [comment]
There are two problems with that implementation: 1) needlessly throws exceptions 2) has no support for bulk imports (without restarting worker on each line call)

**Comment by DenisVuyka** [comment]
Feel free to close this ticket if it's not going to get into the .d.ts schema. At this point I think it's easier to rewrite the pretty rubbish (sorry) "LanguageServiceDefaultsImpl" at my side than building hacks and workarounds on top of that API.

**Comment by alexandrudima** [comment]
:+1:
