### ISSUE TITLE
Issue with the editor surface in Edge

### ISSUE THREAD

**Issue by jefflevinson** [Microsoft/monaco-editor#80]
For whatever reason, my implementation works fine in chrome but in edge I can't actually focus it and type in it. In IE it's a whole different issue - I can't even programmatically access it.

I did read the known issue and while I'm calling the script that loads Monaco from with the body tags, the actual createEditor statement is in a separate js file.

I can grant access to my implementation for MS employees.

**Comment by nojvek** [comment]
Ping me (mapatel). I have a working version of latest monaco in edge. Happy to help you out.

**Comment by joelday** [comment]
I've noticed this where if the body element height is set to 100% and the editor is taller than or lower than the height of the viewport, clicks are recognized, but treated as if the pointer location is at the bottom of the viewport bounds relative to the top of the page.

**Comment by alexandrudima** [comment]
Are you perhaps hitting this known issue:

https://github.com/Microsoft/monaco-editor#known-issues

![image](https://cloud.githubusercontent.com/assets/5047891/17664365/c891c268-62f3-11e6-8dcd-2f4d05d8a81c.png)

**Comment by jefflevinson** [comment]
No, it's definitely wrapped in the body element completely. I double-checked the output.

**Comment by alexandrudima** [comment]
@jefflevinson Please let me know if I can help further. If you could provide a HTML sample that shows the problem I could debug it.

**Comment by jefflevinson** [comment]
Granted access to the instance and sent a separate e-mail.

**Comment by jefflevinson** [comment]
It turns out that in the project I was using it in was hosting everything in an IFrame. A teammate of mine suggested going into the Body (thanks also to Alexandru also who hinted at this) and changing the height and width in the CSS To 2000, then it worked around the problem with Edge.
