### ISSUE TITLE
Hovers don't support syntax highlighting like VS Code

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/monaco-editor#802]
**monaco-editor version:** 0.11.x in the playground
**Browser:** Version 65.0.3325.181 (Official Build) (64-bit)
**OS:** Windows 10

```TypeScript
monaco.languages.register({ id: 'typescript' });

monaco.editor.create(document.getElementById("container"), {
	value: 'var xxxx = ""\nxxxx.toString();',
	language: 'typescript'
});
```
If you try to hover over `toString()`, you'll get no syntax highlighting in the browser but you'll get something in VS Code.

**VS Code 1.21.1**

![image](https://user-images.githubusercontent.com/15629116/38393185-0e84b64c-3965-11e8-9077-e456afbb358c.png)

**Monaco playground**

![image](https://user-images.githubusercontent.com/15629116/38393202-1bb87e70-3965-11e8-87bd-ef648c8b0e60.png)

**Comment by ryanlin1986** [comment]
This is very important code editing feature I believe.
Please consider this feature.

**Comment by rcjsuen** [comment]
Just in case I tried writing a code block explicitly in Markdown but it didn't colour anything.

![image](https://user-images.githubusercontent.com/15629116/38408194-733fa13a-39b7-11e8-8e15-0c9189d54ad6.png)

```JavaScript
monaco.languages.register({ id: 'mySpecialLanguage' });

monaco.languages.registerHoverProvider('mySpecialLanguage', {
	provideHover: function(model, position) {
        return {
            range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
            contents: [
                { value: '**asdf**' },
                { value:
                        '```js\n' + 
                        'var x = blah.toString();\n' + 
                        '```\n'
                },
                { value:
                        '```JavaScript\n' + 
                        'var x = blah.toString();\n' + 
                        '```\n'
                }
            ]
        }
	}
});

monaco.editor.create(document.getElementById("container"), {
	value: 'Hover over this text',
	language: 'mySpecialLanguage'
});
```

**Comment by AlexTugarev** [comment]
@rcjsuen could you try with another example? the one from `monaco-languageclient` for instance. I looks like it's working there for me.

**Comment by rcjsuen** [comment]
@AlexTugarev I'm not sure what case you would like tested exactly but it seems like Monaco is very selective about what "language" it supports in its Markdown code blocks. Consider the following piece of code where `js` and `javascript` works but `JavaScript` doesn't. Perhaps things are working on your end for the same reason.

![image](https://user-images.githubusercontent.com/15629116/38420000-5bb0daae-39dd-11e8-83ea-fab3fc25de3f.png)

```JavaScript
monaco.languages.registerHoverProvider('javascript', {
	provideHover: function(model, position) {
        return {
            range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
            contents: [
                { value:
                        '```js\n' + 
                        'var x = "string";\n' + 
                        '```\n'
                },
                { value:
                        '```javascript\n' + 
                        'var x = "string";\n' + 
                        '```\n'
                },
                { value:
                        '```JavaScript\n' + 
                        'var x = "string";\n' + 
                        '```\n'
                }
            ]
        }
	}
});

monaco.editor.create(document.getElementById("container"), {
	value: '// hover here',
	language: 'javascript'
});
```

**Comment by ryanlin1986** [comment]
monaco.languages.register({ id: 'bpl' });

monaco.languages.registerHoverProvider('bpl', {
	provideHover: function(model, position) {
        return {
            range: new monaco.Range(1, 1, model.getLineCount(), model.getLineMaxColumn(model.getLineCount())),
            contents: [
                { value:
                        '```bpl\n' + 
                        'var x = blah.toString();\n' + 
                        '```\n'
                }
            ]
        }
	}
});

monaco.editor.create(document.getElementById("container"), {
	value: 'Hover over this text',
	language: 'bpl'
});

This works for me, that's enough for me right now

**Comment by alexandrudima** [comment]
The discrepancy is because in `monaco-typescript` we are not using a fenced code block in markdown: https://github.com/Microsoft/monaco-typescript/blob/5d8e7bfc6abc35387d091da2fafcc400ad28b363/src/languageFeatures.ts#L332-L334

PR welcome.

**Comment by rcjsuen** [comment]
I tried wrapping the content in a code block but it's not quite the same as what's in VS Code.

![image](https://user-images.githubusercontent.com/15629116/38610629-6c70a4bc-3d4f-11e8-95a2-11fbbce6b402.png)

**Comment by alexandrudima** [comment]
The coloring is given by the tokenizer.

VS Code uses a TM grammar for TypeScript:

![image](https://user-images.githubusercontent.com/5047891/38614395-47e41fb4-3d8d-11e8-8ee0-35f039bac7c7.png)

While the editor uses the TS lexer to generate tokens:

![image](https://user-images.githubusercontent.com/5047891/38614411-5f719580-3d8d-11e8-96b6-7ac5d3e6e8f6.png)

They will never match, given the source code is tokenized with two different tokenization engines.
