### ISSUE TITLE
Monaco editor content is flickering when you update the content of editor

### ISSUE THREAD

**Issue by nikhilexe** [microsoft/monaco-editor#803]
Posted the same question here https://stackoverflow.com/questions/48784508/monaco-editor-content-is-flickering-when-you-update-the-content-of-editor but didn't get reply hence raising issue here. Appreciate if anyone can answer below question

I am using monaco editor to show live logs. The logs contains various tokens such as Error, Warning, Info etc.

Based on the token I am assigning a specific color to that line.

Problem:

When the same data is flushed again to monaco editor I see some flicker. Flicker is due to to lines first coming as white and then color gets applied based on token. Since it is the same line you see a flicker.

Is there way i can avoid the flicker ? Can the lines be painted before they are visible?

Note: I cannot pass diff lines as the amount of data is huge and I dont want to compare which line got added and which got deleted.

monaco-editor version: 0.10.1
Browser: Chrome
OS: Windows

**Comment by alexandrudima** [comment]
You can:

1. use other API than `setValue` to update the content of the model. If you use `model.applyEdits` to push edits (like append lines in a live log situation), tokens will not be thrown out.

2. (or) Force tokenization after calling `setValue` via unofficial API. `model.forceTokenization(model.getLineCount())`. 

I would personally recommend option 1.

**Comment by nikhilexe** [comment]
Thanks @alexandrudima, I'll give a try with this API and let you know. I am assuming this API can take entire text instead of only diff lines. Currently we get entire text for the live logs which we wanted to render in monaco editor instead of just new lines of live logs

**Comment by antoniopol06** [comment]
@alexandrudima any update on this?

I load monaco-editor through ESM sample and some Firefox that has enable 'uses hardware acceleration when available' flickers the content. I try to use model.applyEdits but does not work.

Any suggestions?

Thanks!

**Comment by alexandrudima** [comment]
@antoniopol06 There is no update on the answer to this question. The editor will drop tokens if `model.setValue` is called. If you are not calling `model.setValue` and are experiencing some form of flicker, perhaps you are running into another issue and you can create a new issue with complete steps.

**Comment by antoniopol06** [comment]
Hi @alexandrudima !

I found the possible issue. I use Vue, if div element is into vue component, diff editor is flickering in Firefox.
