### ISSUE TITLE
CSS hovers include leading and trailing backticks

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/monaco-editor#805]
**monaco-editor version:** 0.11.x Monaco playground
**Browser:** Chrome Version 65.0.3325.181 (Official Build) (64-bit)
**OS:** Windows 10

Use the following snippet in the playground. Hover over `.cssClass` and you will see strange leading and trailing backtick characters.

![image](https://user-images.githubusercontent.com/15629116/38409168-47917064-39bb-11e8-8c47-094e5ad8a110.png)

```JavaScript
monaco.editor.create(document.getElementById("container"), {
	value:
`.cssClass {
	background: red;
}`,
	language: "css"
});
```

**Comment by rcjsuen** [comment]
I've opened Microsoft/monaco-css#5 which fixes this problem.

**Comment by alexandrudima** [comment]
Fixed via https://github.com/Microsoft/monaco-css/pull/5
