### ISSUE TITLE
Is there a way to set contentLeft?

### ISSUE THREAD

**Issue by FrankFang** [Microsoft/monaco-editor#807]
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.editorlayoutinfo.html#contentleft

I want to customize contentLeft but don't know how to make it.

**Comment by alexandrudima** [comment]
That is a computed property, so there is no direct way to manipulate, except to manipulate the values it is computed from.

Here it is computed: https://github.com/Microsoft/vscode/blob/f2edfdc20b43602df8bbb155c988f50c0cd5ba5a/src/vs/editor/common/config/editorOptions.ts#L2050

**Comment by FrankFang** [comment]
It makes sense. Thank you.
