### ISSUE TITLE
is there a method or api to control  search/replace widget show or hide ?

### ISSUE THREAD

**Issue by liyann** [Microsoft/monaco-editor#808]
monaco-editor version: 0.10.1
Browser: chrome 65.0.3325.181
OS: Windows 7
Steps or JS usage snippet reproducing the issue:

![image](https://user-images.githubusercontent.com/14969581/38489263-6b7906d6-3c18-11e8-8f05-63dea44aca6e.png)
I want to hide this widget after user save there content ,is there a method or api to control  search/replace widget show or hide ?

**Comment by alexandrudima** [comment]
You could execute a command, e.g. `editor.trigger('closeFindWidget')` or reach into the find controller and close it e.g. `editor.getContribution('editor.contrib.findController').closeFindWidget()`

**Comment by liyann** [comment]
thanks,I use ` editor.trigger('keyboard','closeFindWidget') ` clsoe it
