### ISSUE TITLE
Text overflows parameter info widget

### ISSUE THREAD

**Issue by joechung-msft** [microsoft/monaco-editor#810]
monaco-editor version: 0.10.0 or later (including 0.13.1)
Browser: Edge, Firefox
OS: Windows 10
Steps or JS usage snippet reproducing the issue: 

Create a Web page with a narrow editor, e.g.,

````html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <style>
        #app {
            border: 1px solid grey;
            height: 400px;
            width: 240px;
        }
    </style>
</head>
<body>
    <div id="app"></div>
    <script src="https://unpkg.com/monaco-editor@0.10.0/min/vs/loader.js"></script>
    <script>
        require.config({
            paths: {
                'vs': 'https://unpkg.com/monaco-editor@0.10.0/min/vs'
            }
        });

        require(['vs/editor/editor.main'], function () {
            var editor = monaco.editor.create(
                document.getElementById('app'),
                {
                    language: 'javascript',
                    value: [
                        'function x() {',
                        '\tconsole.log("Hello, world!");',
                        '}'
                    ].join('\n')
                })
        });
    </script>
</body>
</html>
````

When viewing this page with the browser also sized to be narrow, the text overflows the bounds of the parameter info widget.

![monaco-editor-edge-bug](https://user-images.githubusercontent.com/26208574/38515124-2b678746-3be8-11e8-8c0a-2e65116dc7d0.GIF)

NOTE: This also happens if the `fixedOverlayWidgets` option is set to true.

**Comment by joechung-msft** [comment]
I corrected the 'vs' import in the repro.  Apologies.

**Comment by joechung-msft** [comment]
Adding an `overflow-y: auto` setting to the `parameter-hints-widget` CSS class results in this on Edge:
![image](https://user-images.githubusercontent.com/26208574/42923568-ee438094-8ada-11e8-83b1-2cb29e47b47d.png)

I don't know if you would consider that an acceptable fix, but that is what we wound up doing as a mitigation.

**Comment by alexandrudima** [comment]
@joaomoreno Would adding `overflow-y: auto` to the widget hurt VS Code in any way ? Would you take a PR for that ?

**Comment by joaomoreno** [comment]
The question is why aren't the scrollbars working in the standalone editor. In VS Code we get our scrollbars:

![screenshot from 2018-08-07 12-08-33](https://user-images.githubusercontent.com/22350/43769710-aa1d6e38-9a3a-11e8-998c-dc177cfab104.png)

I'd make our scrollbars work instead of having the browser scrollbars.

**Comment by joechung-msft** [comment]
If I add a `max-height: 250px` on the `.wrapper` class, I see the custom scrollbars:
![image](https://user-images.githubusercontent.com/26208574/43771867-5387ea70-99f5-11e8-8cf8-c6d36560a559.png)

250px is the `max-height` set on the `.wrapper` DIV's parent element (`.editor-widget parameter-hint-widget`).

**Comment by joaomoreno** [comment]
Yeah something's off in Edge's layout code... Chrome and FF seem OK.

**Comment by joechung-msft** [comment]
The fixedOverflowWidgets setting works in 0.14.3 so this is only an issue when that setting is `false` (its default value).

**Comment by joechung-msft** [comment]
Any progress to report on this issue?

**Comment by joechung-msft** [comment]
Good news! This does not repro in Firefox on Windows 11 using the most recent version of monaco-editor.

![image](https://user-images.githubusercontent.com/26208574/159615801-242d8f1d-0414-44c3-8687-05dc2efb0f4d.png)

Given non-Chromium Edge's deprecated state, I'm going to close this.
