### ISSUE TITLE
ESM distribution misses folding.css

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/monaco-editor#811]
Because of https://github.com/Microsoft/vscode/blob/f2edfdc20b43602df8bbb155c988f50c0cd5ba5a/src/vs/editor/contrib/folding/folding.ts#L5

Found via https://github.com/Microsoft/monaco-editor-samples/pull/20

**Comment by danmarshall** [comment]
Great work @alexandrudima ! Can you tell me how long until this gets to NPM?

**Comment by alexandrudima** [comment]
Just published 0.12.0
