### ISSUE TITLE
monaco-json: possibility to set diagnostic per editor instance

### ISSUE THREAD

**Issue by pengx17** [Microsoft/monaco-editor#814]
monaco-editor version: 0.10.1

AFAIK monaco-json could set schema based on `fileMatch` expression. Is it possible to set the diagnostic per editor instance to allow setting different schema files based on different scenarios?

This is because in a web based environment there is no real file name associated with the editor, or do I miss something that there could be a workaround for my need?

**Comment by aeschli** [comment]
@pengx17 When you create a model, you give the model any uri you wish.
Just use that uri in the filematch.
See the code example in https://github.com/Microsoft/monaco-editor/issues/755.
