### ISSUE TITLE
Ruby syntax highlighter bug. Tilde (<~) type here-doc affected.

### ISSUE THREAD

**Issue by avanhecke2** [microsoft/monaco-editor#819]
This issue was originally reported on the Bitbucket issue tracker. After further investigation, it seemed to be related to a bug in the monaco library.  I have sent this issue link to the original reporter. 

> After apostrophe symbol after word "font" rest of the code will became red like it is text-type literal.

![example1](https://user-images.githubusercontent.com/38221731/38748774-db057d6e-3f14-11e8-8225-7623f0696ede.jpg)
![example2](https://user-images.githubusercontent.com/38221731/38748776-ddc0acf4-3f14-11e8-9236-b0183faa3541.jpg)

**Comment by rebornix** [comment]
I didn't see any issue with latest version of Monaco in our online playground

![image](https://user-images.githubusercontent.com/876920/39548745-61f0bfdc-4e10-11e8-8baa-e69d0e414e56.png)

Can you provide more detailed reproduce steps?
