### ISSUE TITLE
Find references, go to declaration dose not work in playground with following code

### ISSUE THREAD

**Issue by LucaGabi** [microsoft/monaco-editor#821]
```js
var model1 = monaco.editor.createModel("function hello1() {\n\talert('111!');\n}\nhello1();\n\nhello2();", "javascript", "hello1.js");
var model2 = monaco.editor.createModel("function hello2() {\n\talert('222!');\n}", "javascript", "hello2.js");


var e = monaco.editor.create(document.getElementById("container"), {
	// value: "function hello() {\n\talert('Hello world!');\n}",
	// language: "javascript"
    folding:true
});

e.setModel(model1);
```

**Comment by gujiman** [comment]
@LucaGabi i had the same issues ages ago and got it working: https://github.com/Microsoft/monaco-editor/issues/217

**Comment by LucaGabi** [comment]
Thanks, it dose work, but trying to compile the editor from sources it works while on testing page only from src if I try with the release-dev I get a console error (I think I don't do something right to build the package):

Uncaught Error: octiconLabel_1.renderOcticons is not a function

TypeError: octiconLabel_1.renderOcticons is not a function
    at HighlightedLabel.render (highlightedLabel.ts:78)
    at HighlightedLabel.set (highlightedLabel.ts:49)
    at Renderer.renderElement (suggestWidget.ts:155)
    at PipelineRenderer.renderElement (listWidget.ts:816)
    at ListView.insertItemInDOM (listView.ts:310)
    at ListView.render (listView.ts:267)
    at ListView.onScroll (listView.ts:383)
    at Emitter.fire (event.ts:142)
    at scrollableElement.ts:177
    at Emitter.fire (event.ts:140)
    at HighlightedLabel.render (highlightedLabel.ts:78)
    at HighlightedLabel.set (highlightedLabel.ts:49)
    at Renderer.renderElement (suggestWidget.ts:155)
    at PipelineRenderer.renderElement (listWidget.ts:816)
    at ListView.insertItemInDOM (listView.ts:310)
    at ListView.render (listView.ts:267)
    at ListView.onScroll (listView.ts:383)
    at Emitter.fire (event.ts:142)
    at scrollableElement.ts:177
    at Emitter.fire (event.ts:140)
    at errors.ts:81
(anonymous) @ errors.ts:81
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.ts:79
ErrorHandler.onUnexpectedError @ errors.ts:116
onUnexpectedError @ errors.ts:135
Emitter.fire @ event.ts:145
(anonymous) @ scrollableElement.ts:177
Emitter.fire @ event.ts:140
Scrollable._setState @ scrollable.ts:332
Scrollable.setScrollDimensions @ scrollable.ts:222
AbstractScrollableElement.setScrollDimensions @ scrollableElement.ts:258
ListView.layout @ listView.ts:250
List.layout @ listWidget.ts:970
SuggestWidget.updateListHeight @ suggestWidget.ts:983
SuggestWidget.show @ suggestWidget.ts:926
SuggestWidget.setState @ suggestWidget.ts:656
SuggestWidget.showSuggestions @ suggestWidget.ts:734
(anonymous) @ suggestController.ts:108
Emitter.fire @ event.ts:140
SuggestModel._onNewContext @ suggestModel.ts:472
(anonymous) @ suggestModel.ts:391
notifySuccess @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
CompletePromise_then @ winjs.base.js:1581
enter @ winjs.base.js:762
_run @ winjs.base.js:1083
_setCompleteValue @ winjs.base.js:1067
notifySuccess @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
argDone @ winjs.base.js:1828
(anonymous) @ winjs.base.js:1853
notifySuccess @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
notifySuccess @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
notifySuccess @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
notifySuccess @ winjs.base.js:1185
enter @ winjs.base.js:867
_run @ winjs.base.js:1083
_completed @ winjs.base.js:1051
SimpleWorkerProtocol._handleMessage @ simpleWorker.ts:151
SimpleWorkerProtocol.handleMessage @ simpleWorker.ts:125
(anonymous) @ simpleWorker.ts:205
WebWorker.worker.onmessage @ defaultWorkerFactory.ts:42

**Comment by alexandrudima** [comment]
I have fixed something like that recently in https://github.com/Microsoft/vscode/commit/7929e6252045f9f735109f6f28f667f649cf33d8

The fix is available on `master` and in the `0.12.0` release, so I guess perhaps you were on some intermediate state, before https://github.com/Microsoft/vscode/commit/7929e6252045f9f735109f6f28f667f649cf33d8, but after https://github.com/Microsoft/vscode/commit/bb1f0f0407d73b882ac2ffd5be811f7c10430fbf (the latter one introduced the mismatch between the real octiconsLabel and the mock one used in the standalone editor)

**Comment by LucaGabi** [comment]
Yes, you are right it works now, thanks!

**Comment by gujiman** [comment]
@alexandrudima @LucaGabi and for 0.12.0. Here is the changes i made for it to work:

https://github.com/gujiman/monaco-0.12.0-feature/commit/b3b5387741adc540b2361c0554592fa7f49ebdf5

(you might have to edit it)

You will also be able to toggle errors [F8], for example try it on:

var model1 = monaco.editor.createModel("function hello1() {\n\talert('111!');\n}\nhello1();\n\nhello2(); var p = ;", "javascript", "hello1.js");
var model2 = monaco.editor.createModel("function hello2() {\n\talert('222!');\n}", "javascript", "hello2.js");

var e = monaco.editor.create(document.getElementById("container"), {
// value: "function hello() {\n\talert('Hello world!');\n}; var a = ;",
// language: "javascript"
folding:true
});

e.setModel(model1);

**Comment by trevorade** [comment]
@gujiman, do you want to make a PR out of: https://github.com/gujiman/monaco-0.12.0-feature/commit/b3b5387741adc540b2361c0554592fa7f49ebdf5?

It would be helpful if it were possible to auto-navigate to the correct model in the editor.

**Comment by gujiman** [comment]
@trevorade that was a quick fix i used in a previous version of monaco (0.12.0) for a client. When i get time ill prob update the code to match the latest version of monaco (no promises). in the mean time you can use the stated code above however you wish. Enjoy!
