### ISSUE TITLE
List of keyboard shortcuts? - find/replace?

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/monaco-editor#823]
I'm probably being stupid, but I can't figure out how to show the find/replace widget in the Azure editor.

It definitely exists:
<img width="187" alt="screen shot 2018-04-17 at 12 48 23 am" src="https://user-images.githubusercontent.com/807580/38816281-12e89ff6-41d9-11e8-8e0f-4dc46736c948.png">

…and pressing F3 or Ctrl+F does show the find widget.

In [your playground](https://microsoft.github.io/monaco-editor/playground.html:), there is a little ▷ to show the replace box from the find view:
<img width="422" alt="screen shot 2018-04-17 at 12 49 53 am" src="https://user-images.githubusercontent.com/807580/38816398-53ccdd52-41d9-11e8-8a9c-250ce7c36e96.png">

But this isn't the case in Azure:
<img width="417" alt="screen shot 2018-04-17 at 12 50 07 am" src="https://user-images.githubusercontent.com/807580/38816391-5093bd22-41d9-11e8-9c33-91f79029e4d2.png">

Pressing all kinds of keyboard shortcuts is doing different things (by trial-and-error); but I can't seem to find the one for find/replace.

PS: Ran a `grep -R` for `editor.addCommand`; `keybinding` & `replace`; `findController`; `closeFindWidget` on this repo, but couldn't find anything relevant.

**Comment by alexandrudima** [comment]
AFAIK the button is disabled if the editor is read-only. i.e. replace is disabled in a read-only editor

**Comment by SamuelMarks** [comment]
The Azure one I'm working with is read/write.

**Comment by mofux** [comment]
@SamuelMarks Are you able to edit text in that editor component? It also looks to me like the editor is in readOnly mode, in which case it will hide the little expand arrow.

**Comment by SamuelMarks** [comment]
Yes I am able to edit the text. I am not able to find/replace though.

**Comment by alexandrudima** [comment]
@SamuelMarks 

Here is the code that disables/enables that find/replace toggle:
https://github.com/Microsoft/vscode/blob/09f3922283dfad507e1f13eb92803e5e17d5189c/src/vs/editor/contrib/find/findWidget.ts#L363:L365

Given **you have now forked the editor**, it should be built from those sources, and the find/replace toggle should be disabled only when the editor is read-only.

**Comment by fabiospampinato** [comment]
Hopefully there's a better way to this that I wasn't able to find, but in order to get the list of all registered commands one could add the following line:

```js
console.log ( this.id, this._kbOpts );
```

Right before the `KeybindingsRegistry.registerCommandAndKeybindingRule` call in `node_modules/monaco-editor/esm/vs/editor/browser/editorExtensions.js`.

**Comment by masad-frost** [comment]
Is there a way to turn those `primary`s into the KeyMod/KeyCode combo?
