### ISSUE TITLE
ES2015 class properties are not recognized by Monaco

### ISSUE THREAD

**Issue by dennis-yemelyanov** [microsoft/monaco-editor#824]
When defining a standard ES2015-style class with a constructor, the properties it sets are not being recognized properly:

![image](https://user-images.githubusercontent.com/10681271/38840399-3d842d9c-4194-11e8-84ee-6f372680babe.png)

The same code works fine and the editor doesn't display any errors in VS Code 1.22.2.

**monaco-editor version:**
0.12.0
**Browser:**
Stable repro in latest Edge, Chrome etc.
**OS:** 
Windows 10
**Steps or JS usage snippet reproducing the issue:**
 copy this code into the Monaco Editor playground at https://microsoft.github.io/monaco-editor/playground.html and click Run. Monaco says that "property "greeting" does not exist on type 'Greeter'", even though it's being set in the constructor using the standard JavaScript syntax.

```
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({});

monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
	allowNonTsExtensions: true
});

var jsCode = [	
    'class Greeter {',
    '    constructor(message) {',
    '        this.greeting = message;',
    '    }',
    '    greet() {',
    '       return "Hello, " + this.greeting;',
    '   }',
    '}'
].join('\n');

monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});
```

**Comment by rcjsuen** [comment]
@dennis-yemelyanov I see a TypeScript error with VS Code 1.22.2.

![image](https://user-images.githubusercontent.com/15629116/38841062-926feb22-41b0-11e8-9153-3fd2bd5f9768.png)

**Comment by rcjsuen** [comment]
Oh, sorry, never mind. I made a TypeScript file instead of a JavaScript file. :(

**Comment by dennis-yemelyanov** [comment]
Yep, since I already took a screenshot, here it is :)

![image](https://user-images.githubusercontent.com/10681271/38841184-17e4ae1e-4198-11e8-9c21-f161b69063e4.png)

**Comment by nrayburn-tech** [comment]
Using the code above,
If you remove the `setCompilerOptions`, the error is gone and properties work as expected.
If you remove the `setDiagnosticsOptions`,  the error is gone, but so are the properties.
If you remove `setCompilerOptions` and `setDiagnosticOptions`, the error is gone and the properties work as expected.

I don't exactly know what the options do that are being used, but they seem to have some odd interaction together.

**Comment by dennis-yemelyanov** [comment]
@nrayburn-tech , right, basically we want Monaco editor to have the same behavior as VS code, which is to show an error for `greeting2` (since it's an invalid property name), but show no error for `greeting` (since it's valid property defined in the constructor):

```
class Greeter {
    constructor(message) {
        this.greeting = message;
    }
    greet() {
       return "Hello, " + this.greeting; // should show no error
    }
    greet2() {
       return "Hello, " + this.greeting2; // should show error "Property 'greeting2' does not exist on type 'Greeter'."
    }
}
```

But we are not able to figure out the right options to set to achieve that. Either both errors are shown (if `setCompilerOptions` is present) or no error is shown event for `greeting2` (if `setCompilerOptions` is removed).

**Comment by nrayburn-tech** [comment]
Gotcha, I missed the greet2 method.

I will look at it and see if I can find anything out.

**Comment by nrayburn-tech** [comment]
I believe this does what you are looking for.

```
monaco.languages.typescript.javascriptDefaults.setDiagnosticsOptions({});

monaco.languages.typescript.javascriptDefaults.setCompilerOptions({
    allowNonTsExtensions: true,
    allowJs: true,
    checkJs: true
});
```

@alexdima is there a reason that the `allowNonTsExtensions` isn't documented in the compiler options?

**Comment by dennis-yemelyanov** [comment]
Yep, that seems to do the trick! Looks like this `checkJs` option wasn't available when the issue was opened and was added to monaco.d.ts later in [this commit](https://github.com/microsoft/monaco-editor/commit/b04ceadff21243259e91c21b9ade3934fb78de52).

**Comment by alexdima** [comment]
No reason, PR welcome if something is missing.
