### ISSUE TITLE
Disable typescript support for javascript language

### ISSUE THREAD

**Issue by BigYu** [microsoft/monaco-editor#825]
monaco-editor version: 0.10.1
Browser: Chrome
OS: Windows 10/Windows Server 2016

When I set the language to "javascript" the editor also support typescript syntax support. However our service does not support typescript. Is it doable to disable typescript support for javascript?

**Comment by mkapiczy** [comment]
+1 

I also need pure javascript editor. How can I disable typescript support?

**Comment by alexdima** [comment]
Yes, it is possible. But you need to package your own `monaco-editor`:

1. If you use the `amd` variant from `/min`. You can fork this repository and edit the top level file called `metadata.js`. There, you can delete the `monaco-typescript` plugin. Then, you can run `gulp release`

2. If you use the `esm` variant from `/esm`. You can include in your files directly `monaco-editor/esm/vs/editor/editor.api` and other components and bundle a subset of the editor only, thus excluding `monaco-typescript`. There is a sample on how to do this here -- https://github.com/microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-small
