### ISSUE TITLE
Many samples won't load on the Monaco website

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/monaco-editor#826]
1. Open the [Monaco website](https://microsoft.github.io/monaco-editor/index.html).
2. Click the 'Language' combo box.
3. Select 'Rust'.
4. You'll now see an error that says "Failed to load rust sample".

There is an error in the console.

```
index/samples/sample.rust.txt Failed to load resource: the server responded with a status of 404 ()
```

Rust support was added in Microsoft/monaco-languages#31 but it seems like the website isn't quite right...?

**Comment by rcjsuen** [comment]
I have found that there are many other samples that won't load.

- csp
- mysql
- pgsql
- redis
- redshift
- sb

**Comment by alexandrudima** [comment]
Yes, these languages were added to `monaco-languages` but then we forgot to add a sample in https://github.com/Microsoft/monaco-editor/tree/master/website/index/samples

If you have some time, PR welcome! :heart:
