### ISSUE TITLE
monaco-editor polute the global variables, making incompatible with other JS libraries, such as CodeMirror, RequireJS, SeaJS, etc.

### ISSUE THREAD

**Issue by bnuzhouwei** [Microsoft/monaco-editor#827]
monaco-editor creates some global variables, such as **require**, and **define**, which lead to the following error:

```
Uncaught Error: Can only have one anonymous define call per script file
    at s.enqueueDefineAnonymousModule (loader.js:1148)
    at o (loader.js:1611)
    at closebrackets.js:8
    at closebrackets.js:11
```

Can change it to within a namespace, such as **monaco.require** and **monaco.define** to make no conflicts?

**Comment by amily666** [comment]
@alexandrudima i use ngx-monoca-editor in angular7, and have same problem. what should i do?
