### ISSUE TITLE
Inline Results Widget

### ISSUE THREAD

**Issue by mikeball** [Microsoft/monaco-editor#83]
The ability to add inline blocks of html and have the editor display and not overlay other lines allows extensions to build very rich and interactive experiences, versus just writing something to a console. 

An issue for this feature was created in the main vscode project (https://github.com/Microsoft/vscode/issues/3220) but I suspect that the functionality to add this feature would need to be added to Monaco, so I've created an issue here. Please see the comments on vscode issue for additional discussion.

Here's an example of what the inline results might look like
- https://cloud.githubusercontent.com/assets/3878949/13206676/8e2dcb02-d90b-11e5-829a-bab589bdbb8c.png

Atom has also implemented a similar feature called Block Decorations which appears to be used by a plugin already.
- http://blog.atom.io/2016/02/03/introducing-block-decorations.html
- https://github.com/nteract/hydrogen

**Comment by alexandrudima** [comment]
The editor has the view zone API: `editor.changeViewZones((accessor) => { ... })`

**Comment by mattgodbolt** [comment]
I'd be interested in this too. I can't see how `changeViewZones` works (there doesn't appear to be much documentation on what this function does or how it could allow placement of inline blocks).

It's not clear if ContentWidgets could cover this use case either.

My use case: implementing inline error widgets much like these: https://godbolt.org/g/6Y90j3 (I'm currently using the CodeMirror editor but am considering moving to Monaco).

**Comment by alexandrudima** [comment]
You can set error/warning markers on a model and the editor's built-in Error widget can kick in via `F8`:

![image](https://cloud.githubusercontent.com/assets/5047891/21924446/8068edf2-d979-11e6-94fd-979363a1387d.png)

That widget is implemented by using both a view zone and an overlay widget. The trick is to listen to the view zone's callbacks in order to align the overlay widget on top of the view zone.

**Comment by mattgodbolt** [comment]
That's fantastic: thanks @alexandrudima
