### ISSUE TITLE
editor.addCommand default fallback

### ISSUE THREAD

**Issue by myfoxtail** [Microsoft/monaco-editor#831]
Hi, I could not find in the documentation and source code if it's possible to call addCommand of editor and fire a fallback for the default behaviour?

For example, I'm creating a handler for the "DELETE" button, but it's conditional and I want to use the normal browser behaviour if the condition does not satisfy.

**Comment by troy351** [comment]
you can create a context key like
`const ctxKey = editor.createContextKey('condition', false)`
then you can use `ctxKey.set(true)` or `ctxKey.set(false)` to set its state.

finally use `addCommand` like:
```
  editor.addCommand(
    monaco.KeyCode.Delete,
    () => {
      // your hander here
    },
    'condition',
  )
```
only `condition` set to `true` will trigger your `delete` command, otherwise it will fallback to default functionality.
btw. you could also use multiple condition like `condition1 && !condition2`

**Comment by myfoxtail** [comment]
Thanks @troy351. Is it the only one option? In my case the condition is being defined inside "onDelete" handler. So basically when I hit delete I check the cursor position and if it is under some rules I what to perform my own version of code, otherwise - normal delete.

More detailed example. I'm trying to use ranges as immutable entities in the editor. That means that if someone wants to delete the range they can delete only the entire range, otherwise they remove character by character.

**Comment by troy351** [comment]
@myfoxtail you may check cursor position and set context key state in `onDidChangeCursorPosition` event, command handler only do the `delete` thing.
That's what I do in my `emmet` plugin, though it will check whenever cursor moves.
Maybe @alexandrudima could suggest a better way.

**Comment by myfoxtail** [comment]
Ok, I'll play with it more.. Thanks guys.

**Comment by myfoxtail** [comment]
I've tried with ```onDidChangeCursorPosition``` it works perfectly. I'm closing this question.

**Comment by annmariely** [comment]
Hi, I have a question sort of related to this but is it possible to create an addCommand that does the default behavior as well as my additional command? For example, I want the backspace key to backspace but then trigger the suggestions drop down as well. I can't seem to write an addCommand for backspace without it disabling backspace in general. 

I've also tried just triggering the suggestions dropdown on every change in the editor (so not using addCommand) but oddly enough, my suggestions box doesn't stay open. Maybe something small I'm missing here.

I'm using this as my command for triggering the box:
`editor.trigger('triggerSuggestForErrorFix', 'editor.action.triggerSuggest');`
