### ISSUE TITLE
monaco.languages.registerDefinitionProvider don't trigger cancel  token

### ISSUE THREAD

**Issue by vincentLiuxiang** [Microsoft/monaco-editor#832]
monaco-editor 0.12.0

Hi, all

when I press cmd + click an api in an editor, 

This api `provideDefinition` has a very high frequency of invoke, but never

trigger `token.onCancellationRequested(cancelHanlder)`

```js
monaco.languages.registerDefinitionProvider('java', {
      provideDefinition: (model, position, token) => {
        console.log(new Date(), model.uri.toString())
        return this.getConnection(model)
          .sendRequest('textDocument/definition',
            convert.MonacoToLsp.textDocumentPositionParams(model, position), token)
          .then(def => convert.LspToMonaco.definition(def))
      }
    });
```

<img width="1044" alt="2018-04-19 5 31 20" src="https://user-images.githubusercontent.com/10772305/38984109-75010338-43f8-11e8-90f8-2c9dd10e1b33.png">

I want to confirm whether this is an bug ?

if the onCancellationRequested called, I can cancel my request, but now, my front-end code will send a lot same request to the back-end in an very short time (<300ms).

**Comment by alexandrudima** [comment]
I believe our UI does not cancel go to definition requests at this time.
