### ISSUE TITLE
To Fit content height by a configurable option.

### ISSUE THREAD

**Issue by equiclouds** [microsoft/monaco-editor#834]
The scroll is amazing and effect. But some times, We need to edit all code without scroll.

Can add a key
`fitContentHeight: true/false`
to make the editor's height auto fit the content?

Just like CodeMirror does.

[http://codemirror.net/demo/resize.html](http://codemirror.net/demo/resize.html)

**Comment by cc189** [comment]
very handy feature

**Comment by alexdima** [comment]
Let's track in #794
