### ISSUE TITLE
Misaligned indentation guides with font ligatures

### ISSUE THREAD

**Issue by mlajtos** [Microsoft/monaco-editor#836]
Hi Alexandru :)

monaco-editor version: 0.12.0
Browser: Chrome Canary
OS: macOS 10.13.3

Relevant config:
```javascript
{
    fontFamily: "Fira Code",
    fontLigatures: true
}
```

Illustration:
![screenshot 2018-04-20 15 33 04](https://user-images.githubusercontent.com/1047512/39053883-739d69f6-44b0-11e8-9626-ba160077cdc4.png)

I turned them off for now with:
```javascript
{
    renderIndentGuides: false
}
```
Thanks

**Comment by alexandrudima** [comment]
The indent guides are rendered every N space widths.
https://github.com/Microsoft/vscode/blob/01169b16171dd381816f08daec793792be7d9151/src/vs/editor/browser/viewParts/indentGuides/indentGuides.ts#L135

https://github.com/Microsoft/vscode/blob/01169b16171dd381816f08daec793792be7d9151/src/vs/editor/browser/viewParts/indentGuides/indentGuides.ts#L107

Perhaps you are using a lazy loaded font family i.e. are you running into #392 ?

**Comment by mlajtos** [comment]
You are right. Waiting for the font helped. Thank you :)
