### ISSUE TITLE
Webpack bundle is missing the typescript worker

### ISSUE THREAD

**Issue by lucat1** [microsoft/monaco-editor#837]
monaco-editor version: 0.12.0
Browser: Any
OS: Any
Steps or JS usage snippet reproducing the issue:

Build the ESM example with webpack that can be found [here](https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack)

![screen shot 2018-04-20 at 16 05 31](https://user-images.githubusercontent.com/29304787/39055508-b4b1eecc-44b4-11e8-9f7f-600438f155b2.png)

The error reported in the Devtools is about a missing package, but I beleive it is related to this webpack warning, and so to the issue #759.

![screen shot 2018-04-20 at 16 03 24](https://user-images.githubusercontent.com/29304787/39055380-5f7dfa5e-44b4-11e8-82f7-06a98c43aaea.png)

**Comment by alexandrudima** [comment]
We have several fully working examples like e.g. here:
https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack
https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-small
or here
https://github.com/Microsoft/monaco-editor-webpack-plugin#using

I'm sorry I cannot help you out with webpack specific questions, simply because I am not a webpack expert. I suggest to start with a sample.

**Comment by LucaT1** [comment]
Indeed this issue is reproducible in the linked example. Tough I forgot to say you have to set the language to typescript. Try typing in the editor and errors should pop up

**Comment by alexandrudima** [comment]
@LucaT1 The sample works fine if you follow all the steps:

![kapture 2018-04-23 at 11 02 29](https://user-images.githubusercontent.com/5047891/39116917-e8c8ee58-46e5-11e8-8be7-2948d6785fdb.gif)

**Comment by kqadem** [comment]
For the Critical Dependency you can try this [solution](https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/13#issuecomment-390806320).
Regarding ts.Worker: Are you sure, that the specific workers have been built?

**Comment by youwenda** [comment]
https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack

this example is OK because It satisfy Work Same Origin Policy, But If I place webpack bundle files in CDN.  it will cause `new Worker( ... )` run error and console  missing the typescript worker

**Comment by alexdima** [comment]
HTML5 does not allow to launch web workers from a different domain. In this case, you would need to have some piece of code that bootstraps things either inlined as base64 or in a `.js` on the same domain as the HTML.
