### ISSUE TITLE
Diff editor triggers or emits some event when diff area (view zone with diagonal-fill class) is created

### ISSUE THREAD

**Issue by antoniopol06** [Microsoft/monaco-editor#841]
monaco-editor version: 0.11.10
Browser: Chrome 65
OS: OS High Sierra

I insert numbers through viewzone next to lineNumber. The problem is when editor is diffEditor and it generates diff view zone (with diagonal-fill class). My custom view zone appears into first line of diff area instead of the line that I expected.

<img width="333" alt="screen shot 2018-04-24 at 10 41 39" src="https://user-images.githubusercontent.com/3017821/39176122-4a2d8782-47ac-11e8-822c-bf4397202acc.png">

I would like to know if diff editor emits some event or trigger when these areas are created (diagonal-fill), I will add my custom view zones after own diff editor view zones.

Any suggestions?

Thanks!!

**Comment by alexandrudima** [comment]
You could try to use `diffEditor.onDidUpdateDiff`, shortly after that the view zones/decorations should be updated.

**Comment by antoniopol06** [comment]
Hi @alexandrudima ,

I tried it and the result is the same that image of above. 

I add view zone with margin dom node to line 5, and it is appeared next to diagonal-diff area instead of next to line 5.

**Comment by alexandrudima** [comment]
View zones which are after the same line number are sorted by `zone.afterColumn`. Use e.g. `zone.afterColumn: 1000000`.

**Comment by alexandrudima** [comment]
https://github.com/Microsoft/vscode/blob/7b531850bf1218f56fbd07ad30eae8a3cdb9678a/src/vs/editor/browser/viewParts/viewZones/viewZones.ts#L127:L134

**Comment by antoniopol06** [comment]
Thanks again @alexandrudima !

I close the issue.
