### ISSUE TITLE
[Monarch] nextEmbedded and matching delimiters

### ISSUE THREAD

**Issue by agentcooper** [microsoft/monaco-editor#842]
Hello.

I am building a highlighter for a custom DSL. The language consists of blocks which are defined as `blockName { ... blockContent ... }`.

One of the blocks contains arbitrary JavaScript code inside of it:

```
...
script {
  let foo = "bar";
  if (foo === "baz") {
    foo = "quux";
  }
}
...
```

Can this be done with Monarch? I am looking into `nextEmbedded`, but can't figure out what should I match to properly `@pop` from JavaScript mode back into DSL.

**Comment by alexandrudima** [comment]
Well, it looks like your DSL is in the business of counting brackets. i.e. there is no clear token to end an embedded language (like e.g. `</script>` is for HTML).

This reminds me of Razor.

I guess you're going to need to build a state machine that counts brackets e.g. https://github.com/Microsoft/monaco-languages/blob/6f34b63e4006c357717a7639a1c6f0ea3cf68333/src/razor/razor.ts#L245-L251
