### ISSUE TITLE
Expose event for completion item selected

### ISSUE THREAD

**Issue by TheRealPiotrP** [microsoft/monaco-editor#843]
monaco-editor version: 0.12.0
Browser: Any
OS: Any

Monaco Editor should expose an event that notifies hosts when a user selects a completion item. This would likely be implemented as a callback property on a CompletionItem:
```
export interface CompletionItem {
        /**
         * The callback to invoke when this CompletionItem is selected.
         */
        label: () => void;
```
or as a new API on CompletionItemProvider:
```
export interface CompletionItemProvider {
        triggerCharacters?: string[];

        /**
         * Notification that the user accepted a CompletionItem
         */
        resolveCompletionItem?(item: CompletionItem): void;

        /**
         * Given a completion item fill in more data, like [doc-comment](#CompletionItem.documentation)
         * or [details](#CompletionItem.detail).
         *
         * The editor will only resolve a completion item once.
         */
        resolveCompletionItem?(item: CompletionItem, token: CancellationToken): CompletionItem | Thenable<CompletionItem>;
    }
```

## Justification
Some extensions are able to improve user experience over time by adapting to a user's coding style. One opportunity for such improvement is via the styling and sort order of a completion list. In order to understand the effectiveness of the improvement, these extensions need to be notified regarding the user's eventual choice of a completion item.

**Comment by TheRealPiotrP** [comment]
@rebornix we had chatted about this some time back. Opening this issue to track progress.

**Comment by rebornix** [comment]
Related issue https://github.com/Microsoft/vscode/issues/46451
