### ISSUE TITLE
ngx-monaco-editor is showing no Suggestions

### ISSUE THREAD

**Issue by manasagirinatham** [Microsoft/monaco-editor#844]
I went through [ngx-monaco-editor]: https://github.com/atularen/ngx-monaco-editor

Cloned the project & customizing the same - Word Suggestions are coming only for Css & JavaScript languages as they are default.But requirement is Java,Csharp editors.

Html code -

    <ngx-monaco-editor [options]="options" [(ngModel)]="displaycode" (onInit)="onInit($event)"></ngx-monaco-editor>

TypeScript code -

    options = {theme: 'vs-dark'};
    onInit(editor) {
      this.editor = editor;
    }
I tried 

    1) options = {theme: 'vs',quickSuggestions: true,wordBasedSuggestions: true};

    2) inside ngOnInit function:
  
    this.options = Object.assign({}, this.options, {theme: 'vs',language: java});
Theme changes are reflecting & if i debug language is updated in options.

[Image of editor showing - no Suggestions ][1]

i went through github links like https://github.com/Microsoft/monaco-editor/issues/632, but didn't find any help

  [1]: https://i.stack.imgur.com/A6EeA.jpg

How can i get word Suggestion working in the editor for Java & cSharp ?
Thanks in advance.

**Comment by alexandrudima** [comment]
@manasagirinatham If you are using a not official monaco editor distribution, perhaps you should ask questions on the not official monaco editor distribution repository.

**Comment by manasagirinatham** [comment]
At first i tried with official monaco ediotor to integrate with angular 5 - But Editor is not initialized at all.
Displaying error as monaco is not defined.

Any help on integrating with angular5 ?

**Comment by manasagirinatham** [comment]
Hi @alexandrudima ,

As i want Monaco-editor in my angular 5 project i went through https://github.com/Microsoft/monaco-typescript  

I want to the editor to support C sharp & Java on a toggle button.
Auto-suggestion, indentation & other things are fine.
But the entire code is in same color. Am expecting Keywords in different color.

I went through 

1. https://github.com/Microsoft/monaco-editor/blob/master/test/playground.generated/customizing-the-appearence-tokens-and-colors.html 
2.  https://github.com/Microsoft/monaco-css

But no changes are reflected.
Any help on this ?

**Comment by manasagirinatham** [comment]
![csharpeditor no color difference for keywords](https://user-images.githubusercontent.com/20989813/39415889-e2dc2c3c-4c65-11e8-83fe-fbfa6543df4c.JPG)
![java editor single color](https://user-images.githubusercontent.com/20989813/39415890-e32aa9d4-4c65-11e8-973b-576bf9f17120.JPG)

**Comment by alexandrudima** [comment]
Looks like discussion continues in #854

**Comment by manasagirinatham** [comment]
True , As you closed this(#844)  issue - i thought no one will respond here.
So created a new one -  Happy to see some response , But still didn't get any help. :-(
