### ISSUE TITLE
How could I add space around content?

### ISSUE THREAD

**Issue by chhpt** [microsoft/monaco-editor#853]
Because of some reasons, I want to add some space around the content(view-lines). I found the way to add space on the left of the content using the API lineDecorationsWidth, but I have no idea how to add space on the other side, top, bottom and right and keep the action work well, such as copy, select all, input...

**Comment by myfoxtail** [comment]
@chhpt may be you're looking for the `lineHeight`?

**Comment by chhpt** [comment]
@myfoxtail Could the `lineHeight` change the space on the left or right? I can't find the usage that show it could change the space around the content. It only change the space between the line. I don't think the `lineHeight` is the proper way.

**Comment by myfoxtail** [comment]
@chhpt I guess you can try to create a decoration and apply it to the particular range if your content. Every decoration has it's own css class which I guess you can fill with margins and paddings.

```
const decorationId = this.editor.deltaDecorations([], [
        {
          range: new monaco.Range(
              lineNumberStart
            , columnStart
            , lineNumberEnd
            , columnEnd),
          options: {
            inlineClassName: 'sqleditor-dsp-link', // use this class to add some paddings
            stickiness     : 1,
            hoverMessage   : {value: 'hello my friend'}
          }
        }
      ]);
```

**Comment by chhpt** [comment]
@myfoxtail  I have tried it. It seems that it is not working. The `inlineClassName` has effect on the inline block. But when I add padding on it, it cause the content chaos. And I also have tried the `className`, it is not work as expect.

**Comment by alexandrudima** [comment]
You could try with decorations that use `::before` and `::after` css selectors, like e.g. `beforeContentClassName`

```js
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

var decorations = editor.deltaDecorations([], [
	{ range: new monaco.Range(7,1,7,24), options: { beforeContentClassName: 'myInlineDecoration' }},
]);

```

```css
.myInlineDecoration::before {
    content: " ";
    background: red;
    width: 100px;
    display: inline-block;
}
```

**Comment by chhpt** [comment]
@alexandrudima  

Maybe I should show my thoughts more clearly. First please see this pic. If I don't do anything, it look like this. This doesn't look so good. 

![](http://test-1252710547.cosgz.myqcloud.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-30%20%E4%B8%8B%E5%8D%8816.11.46%20%E4%B8%8B%E5%8D%88.png)

So I decided to add some space around the content. I add a `padding` attribute on the  parent container, it became like this:

![](http://test-1252710547.cosgz.myqcloud.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-30%20%E4%B8%8B%E5%8D%8816.00.44%20%E4%B8%8B%E5%8D%88.png)

All is well except the scrollbar. I want to find way that could make it work like this but make the scrollbar on the edge. May like this:

![](http://test-1252710547.cosgz.myqcloud.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-30%20%E4%B8%8B%E5%8D%8816.10.13%20%E4%B8%8B%E5%8D%88.png)

The `beforeContentClassName` API is something else, it make cause like this. it is not what I except.
And if edit the content, such as delete something, it work weird. Is there a way could change the position of the scrollabr?

```JavaScript
var decorations = editor.deltaDecorations([], [
    { range: new monaco.Range(1,1,10,24), options: { beforeContentClassName: 'myInlineDecoration' }},
]);
```

![](http://test-1252710547.cosgz.myqcloud.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-04-30%20%E4%B8%8B%E5%8D%8816.23.41%20%E4%B8%8B%E5%8D%88.png)

**Comment by alexandrudima** [comment]
Thanks for posting screenshots, it makes it clearer for me what you're trying to do. 

At this time, the editor doesn't support any form of padding inside the content (such that the scrollbar stays put).

**Comment by chhpt** [comment]
@alexandrudima  Do you have a plan to realize it? I hope the feature could be come ture.

**Comment by Mani-108** [comment]
Any update related this feature? @alexdima

**Comment by diyyap** [comment]
How do I get to put a consistent single space between words on the same line. I am using a plaintext editor. Please help me . I want to use create a data like tab separated files. Eg. 
Name    address
Johnd    london
Dhdhb   Newyork
