### ISSUE TITLE
Monaco editor entire code is in single color - No color difference for keywords.

### ISSUE THREAD

**Issue by manasagirinatham** [microsoft/monaco-editor#854]
As i want Monaco-editor in angular 5 project i went through https://github.com/Microsoft/monaco-typescript  

I want the editor to support C sharp & Java on a toggle button.
Auto-suggestion, indentation & other things are fine.
But the entire code is in same color. Am expecting Keywords (like 'import' ) in different color.

I went through 

1. https://github.com/Microsoft/monaco-editor/blob/master/test/playground.generated/customizing-the-appearence-tokens-and-colors.html 
2.  https://github.com/Microsoft/monaco-css
3. monaco.editor.colorizeElement(document.getElementById('container'));
4. https://github.com/TypeFox/monaco-languageclient

But no changes are reflected.
Any help on this ?

**Comment by manasagirinatham** [comment]
![csharpeditor no color difference for keywords](https://user-images.githubusercontent.com/20989813/39415894-f6f047bc-4c65-11e8-9240-0c20bb9dde91.JPG)
![java editor single color](https://user-images.githubusercontent.com/20989813/39415895-f747bf88-4c65-11e8-9a70-5bb20bac560f.JPG)

**Comment by alexandrudima** [comment]
@manasagirinatham The "Monaco Editor TypeScript test page" from [here](https://github.com/Microsoft/monaco-typescript/blob/master/test/index.html) contains the core editor and only the TypeScript language support, so if you check out that repository and run that page, you will only get TypeScript/JavaScript support.

Please start from a sample that uses the entire editor e.g. at https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-amd-editor

**Comment by rcjsuen** [comment]
Perhaps https://github.com/Microsoft/monaco-editor/issues/375#issuecomment-366485412 can help you. It shows you how to change the language from JavaScript to HTML but you should be able to apply the same concept to C# and Java.
