### ISSUE TITLE
Please help me to build new language syntax highlights

### ISSUE THREAD

**Issue by Serhioromano** [Microsoft/monaco-editor#856]
I am trying to add highlight support for Structured Text (IEC 61131-3 standard) language for PLC. I understand how to register and create my tokenizer file. This is not the problem.

What I cannot understand how to test it flowerless. How to have editor opened in the browser, and after changing my files, refresh it and see how highlights works. If I run `npm run watch` I do not see any server to be created or any note where can I see an output. 

I try to do in in monaco-languages repository.

I am sorry I know it is not an issue as you expect but it is an issue for me. I asked question on stackoverflow, but I was not able to get desired answer. I have other place to turn in.

**Comment by alexandrudima** [comment]
@Serhioromano if you use Monarch, you can use https://microsoft.github.io/monaco-editor/monarch.html . If you use a manual written tokenizer, then you need to build your own interactive playground. It should not be too difficult.

**Comment by Serhioromano** [comment]
> @alexandrudima if you use Monarch, you can use https://microsoft.github.io/monaco-editor/monarch.html.

So, I start building in Monarch, and when I finish, simply copy\paste to monaco-languages repository. Right?

**Comment by alexandrudima** [comment]
Yes, that is my workflow.

**Comment by Serhioromano** [comment]
Thank you. Works fine for me too.
