### ISSUE TITLE
editor.upadteOptions can't change the scrollbar visible

### ISSUE THREAD

**Issue by chhpt** [microsoft/monaco-editor#859]
monaco-editor version: 0.X.Y
Browser: Chrome 68.0.3416.0
OS: macOS 10.13.4
Steps or JS usage snippet reproducing the issue:

To show the issue, you can chagne the js code in the [monaco editor playground scrollbar demo](https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-scrollbars) to this:

```JavaScript
// Remember to check out the CSS too!
var htmlCode = "<html><!--long linelong linelong linelong linelong linelong linelong linelong linelong linelong line-->\n<head>\n	<!-- HTML comment -->\n	<style type=\"text/css\">\n		/* CSS comment */\n	</style>\n	<script type=\"javascript\">\n		// JavaScript comment\n	</"+"script>\n</head>\n<body></body>\n</html>";

var editor = monaco.editor.create(document.getElementById("container"), {
	value: htmlCode,
	language: "text/html",
	theme: "vs",
	scrollbar: {
		useShadows: false,
		verticalHasArrows: true,
		horizontalHasArrows: true,
                // set scrollbar hidden
		vertical: 'hidden',
		horizontal: 'hidden',

		verticalScrollbarSize: 0,
		horizontalScrollbarSize: 17,
		arrowSize: 30
	}
});

// 2s later, set the scrollbar show
setTimeout(() => {
    editor.updateOptions({
        scrollbar: {
            vertical: 'auto',
            verticalScrollbarSize: 17
        }
    });
}, 2000);
```
After 2 seconds, the scrollbar did show but the slider disappeared. 

Is it a **bug**?

**Comment by alexandrudima** [comment]
The scrollbars currently only react to a subset of options (`handleMouseWheel` and `mouseWheelScrollSensitivity`).

i.e.

https://github.com/Microsoft/vscode/blob/1efa98226cc6100e3bccd8e382035d11f2516c7f/src/vs/editor/browser/viewParts/editorScrollbar/editorScrollbar.ts#L128:L134

and not to all of the possible options:

https://github.com/Microsoft/vscode/blob/1efa98226cc6100e3bccd8e382035d11f2516c7f/src/vs/editor/browser/viewParts/editorScrollbar/editorScrollbar.ts#L35:L52

**Comment by mertdeg2** [comment]
updateOptions seem to be not working at all for scrollbars..

This is what i tried:

```
// Remember to check out the CSS too!
var htmlCode = "aa<html><!--long linelong linelong linelong linelong linelong linelong linelong linelong linelong line-->\n<head>\n	<!-- HTML comment -->\n	<style type=\"text/css\">\n		/* CSS comment */\n	</style>\n	<script type=\"javascript\">\n		// JavaScript comment\n	</"+"script>\n</head>\n<body></body>\n</html>";

var editor = monaco.editor.create(document.getElementById("container"), {
	value: htmlCode,
	language: "text/html",
	theme: "vs",
	scrollbar: {
		useShadows: false,
		verticalHasArrows: true,
		horizontalHasArrows: true,
		vertical: 'hidden',
		arrowSize: 30
	}
});

// 2s later, set the scrollbar show
setTimeout(() => {
    editor.updateOptions({
        scrollbar: {
            vertical: 'visible',
        }
    });
}, 2000);
```

**Comment by EnderAdel** [comment]
When will this get fixed?

**Comment by sabine19** [comment]
how is the state of this issue?

I have a similar issue with editor.updateOptions method. 
I enable the minimap and it is rendering for a moment, but then it disappears.
So the update is not working properly...

I guess this is a bug in the Monaco Editor.

**Comment by vinuthakaranth** [comment]
Hello Team, Any update on this issue?

**Comment by alexdima** [comment]
Done via https://github.com/microsoft/vscode/pull/127788
