### ISSUE TITLE
Tooltip shown on Alt + F1 keypress is not properly visible in 200% zoom.

### ISSUE THREAD

**Issue by sagar17sep** [microsoft/monaco-editor#861]
BUG-

Provide detailed reproduction steps (if any)

1. Bring focus on Monaco editor in 200% zoom.
2. Press Alt + F1 to open its custom tooltip.

**Expected result**
Tooltip shown on Alt + F1 keypress should be properly visible in 200% zoom. 

**Actual result**
Tooltip shown on Alt + F1 keypress is not properly visible in 200% zoom.

Other details
Browser: …Edge 41.16299.248.0 
OS: …Windows 10
Monaco Editor version: 0.10.1

**Comment by alexandrudima** [comment]
The Alt + F1 tooltip is meant for users using Screen Readers.

I don't believe it is important for the tooltip to render correctly in all cases, as it only presents information for Screen Readers.

**Comment by sagar17sep** [comment]
We are looking for complete accessibility and for our scenario and for person with less visibility, we are expecting it to work fine when we Zoom up to 200%.

**Comment by sagar17sep** [comment]
Could you please look to the above mentioned issue.

**Comment by alexandrudima** [comment]
@sagar17sep There are two possible cases.

Case 1. The user is running a Screen Reader. In this case, the aria label of the editor presents that Alt + F1 will have information for the Screen Reader. The user can press Alt + F1 and the Screen Reader will read that information. It does not matter how the information is painted.

Case 2. The user is not running a Screen Reader. In this case, the user can use 200% zoom to operate the editor. The user does not even know about the existence of Alt + F1, as that is a shortcut presented only to Screen Readers.
