### ISSUE TITLE
Diff editor's UI is not proper when integrating with Angular

### ISSUE THREAD

**Issue by shwetanotani** [microsoft/monaco-editor#864]
monaco-editor version: 0.12.0
Browser: Google Chrome Version 66.0.3359.139
OS: Windows 10 Pro
Angular version: 1.6.2

On integrating monaco-editor with Angular, the diff editor UI does not work properly.
UI issues observed:
1. Line numbers are appearing below the code 
2. Highlighting of the text is below it

I have tried with following combinations of Angular and monaco-editor versions in order to resolve the issue:

monaco-editor   version | Angular   version
-- | --
0.12.0 | 1.6.2
0.12.0 | 1.7.4
0.12.0 | 6.0.0
0.11.1 | 1.7.4
0.10.1 | 1.6.2
0.10.1 | 1.7.4

All of the above combinations did not work.

Below is the code snippet that I am using:
![image](https://user-images.githubusercontent.com/39054833/39701876-7c12c4fa-5220-11e8-9085-78cdf870fe69.png)

This is how the code editor is being displayed on the browser:
![image](https://user-images.githubusercontent.com/39054833/39701622-7e4a08ec-521f-11e8-95b8-9b27a68c1af6.png)

**Comment by alexandrudima** [comment]
@shwetanotani This looks like a CSS conflict of some sorts. Can you try removing all the CSS on your webpage.

For example, if you have a CSS rule like the following:
```
.line-numbers {
  position: relative !important;
}
```

It will break the positioning of the line numbers inside the editor.

**Comment by shwetanotani** [comment]
@alexandrudima  I am using Monaco editor with Angular2 application configured with Angular CLI. The node module for monaco-editor resolves to the esm folder, which does not contain the editor.main.css file.
I have explicitly added the reference in styles in .angular-cli.json file and it resolved the issue. However, I am not sure if this is the right way to resolve this issue.

Below is the snapshot of .angular-cli.json file:
![image](https://user-images.githubusercontent.com/39054833/39804546-f3a54778-5391-11e8-9be6-d68218eb69d5.png)

**Comment by alexandrudima** [comment]
@shwetanotani Can you verify that absolutely all the CSS rules from `editor.main.css` make it to the resulting css?

**Comment by giannik** [comment]
I am having the same visual appearance in the diff editor . In all other cases the editor shows properly , only in diff view it is shrinked.
I verified editor.main.css is included and no other css is included. 
Any hints what else could be wrong ?

**Comment by giannik** [comment]
ok , found it. 
Container needs to be eg  height:600px;
not min-height:600px

**Comment by prabal77** [comment]
@shwetanotani Could you let me know how did you integrate monaco-editor with Angular using ESM. I am having issues configuring the web workers, as i don't have seperate webpack config
