### ISSUE TITLE
Refactor keybinding is wrong

### ISSUE THREAD

**Issue by AlexTugarev** [Microsoft/monaco-editor#865]
monaco-editor version: 0.12.0
Browser: Chrome
OS: Linux

`Refactor` keybinding is configured as `shift + R`, which prevents of entering `R` into the editor.

**Comment by AlexTugarev** [comment]
Is this the same as https://github.com/Microsoft/vscode/issues/49225?

**Comment by alexandrudima** [comment]
Looks like a dup of #49225

**Comment by AlexTugarev** [comment]
Thanks for verifying! Would it make into next release? I've spotted the `standalone/0.13.x` branch.

**Comment by AlexTugarev** [comment]
@alexandrudima is there any chance, this could make it into `0.13.x`?
