### ISSUE TITLE
changeDecorations missing from monaco.d.ts

### ISSUE THREAD

**Issue by roblourens** [Microsoft/monaco-editor#87]
This API is on the model and editor, and I assume it's meant to be public, because it's used in this example - https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin

**Comment by AndersMad** [comment]
i use `deltaDecorations` and `onDidChangeDecorations`

**Comment by roblourens** [comment]
Huh, I didn't notice that `deltaDecorations` changes the decorations. Would make sense to update the example with that API.
