### ISSUE TITLE
Function Signature Intellisense is cut off on first and second lines

### ISSUE THREAD

**Issue by mastasky** [microsoft/monaco-editor#870]
![image](https://user-images.githubusercontent.com/20715863/39923270-3d170dbe-5523-11e8-8538-a31bb2bcb7ba.png)

monaco-editor version: 0.12.0
Browser: Chrome
OS: Win10

Steps or JS usage snippet reproducing the issue:

- Open a monaco editor of your choice
- Enter console.log( in the first line. The function signature is invisible
- Move it to line 3 and see the full signature

**Comment by mastasky** [comment]
Your screenshot looks ok indeed. In our implementation (and also Visual Studio Team Services), the popup appears always above and cut off (if on line 2) or even invisible (on line 1).

Is there a setting to make it appear below?

**Comment by alexandrudima** [comment]
I also cannot reproduce

![image](https://user-images.githubusercontent.com/5047891/40051542-70d88202-583b-11e8-880c-2e52652225cd.png)


Perhaps you have some CSS on your website interacting (selecting) some of the hover elements?
