### ISSUE TITLE
Make smaller webpack bundles

### ISSUE THREAD

**Issue by chengtie** [microsoft/monaco-editor#872]
I have followed [this page](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md#option-2-using-plain-webpack) to integrate the esm version by using plain webpack.

The file generated, `app.bundle.js`, has `2.1Mb`. What I need is the editor for `.js`, `.json`, `.css` and `.html`.

Does anyone know if it is possible to make smaller bundles that can be loaded faster?

**Comment by myfoxtail** [comment]
@chengtie I would suggest you to use the lazy load approach with `webpack`.

For example this will load a monaco bundle separately.

```
import(/* webpackChunkName: "monaco-editor" */ 'monaco-editor').then(() => {
      // your code here
});
```

As you can also notice while building the project that webpack generates a lot of 1.js, 2.js, etc files (which contain language set ups [js, css, python, etc]). They are also being loaded asynchronously inside monaco.

**Comment by kqadem** [comment]
You can also skip unnecessary features from the build. You can find an example [here](https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-small).
