### ISSUE TITLE
setEditableRange removed

### ISSUE THREAD

**Issue by LoganDark** [microsoft/monaco-editor#874]
`setEditableRange` was useful.

Why remove it? Is there an alternative to it?

**Comment by LoganDark** [comment]
Hello?

**Comment by alexandrudima** [comment]
We have removed this method and there are no plans to bring it back. We were not using editable ranges for the past 4 years and found the burden of maintaining that too high.

**Comment by LoganDark** [comment]
Okay.

> Is there an alternative to it?

**Comment by alexandrudima** [comment]
Unfortunately not. You could attempt to listen to model content changes and to look at those in order to prevent edits that would change the regions that you don't want to have changed (you could call `undo` to undo the changes)

**Comment by LoganDark** [comment]
That's a hack, makes for a bad user experience, and does something unnecessary (modifies the model first and then undoes it). There's also no indication as to what lines are off limits.

**Comment by David-Mulder** [comment]
That was indeed unexpected... :/

**Comment by Progyan1997** [comment]
I was trying to obtain the using the hack specified in real-time collaborative text editor on monaco but the text became so much unpredictable. :sob:

**Comment by alexandrudima** [comment]
Let's continue tracking the feature request in #953

**Comment by LoganDark** [comment]
Yes, because this issue is newer and it totally should be closed and marked as a duplicate.

Please remove the duplicate label at least, that's just insulting.

I don't mind moving to another issue but please don't do something like that.
