### ISSUE TITLE
_this.mouseMoveEventMerger is not a function

### ISSUE THREAD

**Issue by Luiz-N** [Microsoft/monaco-editor#875]
monaco-editor version: 0.13.1 (according to comment box at top of source code)
Browser: Chrome + FF
OS: High Sierra 10.13.4

Steps:
1. Use AMD version to load `loader.js` then `editor.main`. (This works without error and web workers start without issue)
2. Create text models & diffEditor
3.  diffEditor renders correctly and can update underlying models
4. Clicking on editor then triggers this in the console .
```
Uncaught TypeError: _this.mouseMoveEventMerger is not a function
    at globalMouseMoveMonitor.ts:99
```
5. all future mouse movements spam the same error

**Comment by alexandrudima** [comment]
@Luiz-N I cannot reproduce. I am trying with Firefox and Chrome on the version at https://microsoft.github.io/monaco-editor/ (the latest).

**Comment by Luiz-N** [comment]
It ended up being a weird dependency order issue between raven.js and rollbar.... All is good now. Thanks for the checking!
