### ISSUE TITLE
Letters with accents written twice

### ISSUE THREAD

**Issue by RJ64** [microsoft/monaco-editor#876]
monaco-editor version: 0.13.0
Browser: Firefox
OS: Ubuntu

When you write a letter with an accent (such as á) it is written twice on Firefox under Ubuntu.

I've made tests and it happens with the last few Firefox 64-bit versions up to the newest (60.0) under Ubuntu 16.04 xenial x86-64. Also tested on an Ubuntu 16.04 live usb that includes firefox 64-bit version 51.0.1 to discard a particular problem with the first firefox.

Also checked with chromium in this ubuntu version and firefox in windows and works fine.

I've performed the tests here: https://microsoft.github.io/monaco-editor/index.html so it is not a problem with my implementation of monaco

**Comment by jitao13** [comment]
Hi,Have you solved this problem? Or do you have any good ideas to deal with this problem?
Thank you

**Comment by RJ64** [comment]
monaco-editor version: 0.16.2
Browser: Firefox v66.0.3
OS: Mac Mojave v10.14.3

Found out it also happens in firefox with mac

**Comment by alexdima** [comment]
I could no longer reproduce on the latest at https://vscode-web-test-playground.azurewebsites.net/ so I believe this was resolved with https://github.com/microsoft/vscode/pull/106873
