### ISSUE TITLE
Cannot debug Monaco Editor on Visual Studio Code

### ISSUE THREAD

**Issue by daneel0livaw** [microsoft/monaco-editor#880]
Hi there,

I try to debug Monaco Editor on VS Code to see how it works, but when I try to click "Launch Program" I get this error message: 

![image](https://user-images.githubusercontent.com/19150760/40071763-07a0ee96-5872-11e8-83b6-9b1860d4288f.png)

I tried setting an empty outFiles property, but then I got this:

![image](https://user-images.githubusercontent.com/19150760/40071805-27ba3ca0-5872-11e8-9da9-1f59b648df66.png)

This is my launch configuration:

![image](https://user-images.githubusercontent.com/19150760/40071825-337aecc4-5872-11e8-8a38-78c161da1ec4.png)

**Comment by alexandrudima** [comment]
The `launch.json` file you have authored is one that will attempt to execute `node.exe`. But the Monaco Editor is not a node application, it is a library that runs on web browsers.

**Comment by daneel0livaw** [comment]
Oh, I see. So could you help how I can see how it works in debug mode? Sorry, I'm kind of new at JavaScript.

**Comment by alexandrudima** [comment]
The easiest is probably to debug using the browser's built-in developer tools.

So, clone this repository, run `npm install`, run `npm run simpleserver` and then open a browser at `http://localhost:8080/monaco-editor/test/`.

Then, press <kbd>F12</kbd> to get the browser tools started. You can search online for tips & tricks on how to use the browser tools efficiently depending on your browser of choice.
