### ISSUE TITLE
onDidChangeContent decorations in the range in case of deleting

### ISSUE THREAD

**Issue by myfoxtail** [Microsoft/monaco-editor#881]
Hey guys, quick question. 

When we do `editor.getModel().onDidChangeContent` the callback returns an event with the range of updated area in the editor.

If I delete content and call `onDidChangeContent` the ranges in decorations are already updated and I cannot figure out the easy way to know which decorations fall under the range of removed content.

Do you know how to do that?

**Comment by alexandrudima** [comment]
You can store on your side the previous ranges your decorations had.

Then, when a content change event comes in, you can read the new ranges for your decorations from the model, and compare/use also the previous ranges... Then, you can "update" the previous ranges.

```
let oldDecorationRange = new Range(1,1,5,1);
let decorationId = model.deltaDecorations([], [{range:oldDecorationRange,options:{}}])[0];
model.onDidChangeContent((e) => {
  let currentRange = model.getDecorationRange(decorationId);
  // previous range is available in `oldDecorationRange`
  // set for next time
  oldDecorationRange = currentRange;
});
```

**Comment by myfoxtail** [comment]
Hi @alexandrudima, yep... that's what I'm currently doing. 

In my case it's not the most convenient and easy way because I have to store the new version of decorations every time I make a change in the editor content. That made me thought you had had the same situation and had came up with another type of event.. for example `onBeforeContentChange` or something like that.

Thank you for your help!
