### ISSUE TITLE
Some find contrib commands not working through trigger

### ISSUE THREAD

**Issue by masad-frost** [microsoft/monaco-editor#883]
I'm trying to execute the following commands using `trigger`, but it does't work `editor.action.replaceOne` ,`editor.action.replaceAll` ,`editor.action.selectAllMatches`. It's weird because `closeFindWidget` works fine and has the same preconditions and creation/registration.

**Comment by alexandrudima** [comment]
Have you tried to debug into them? Some of those commands require valid values in the find widget. (e.g. they can be disabled when the inputs are empty):

![image](https://user-images.githubusercontent.com/5047891/40163995-a2e12f14-59b8-11e8-993f-be7f87240f63.png)

**Comment by masad-frost** [comment]
Yeah I've tried adding valid values, to no avail. I'll try to debug properly over the weekend.

I've also ran into an issue where `actions.find` doesn't focus the input, I'll open up another issue once I have more detail. But even `HTMLInputElement.focus()` isn't working on it :confused:
