### ISSUE TITLE
Stickiness is ignored with isWholeLine for DeltaDecorationOptions

### ISSUE THREAD

**Issue by hawkerm** [microsoft/monaco-editor#887]
monaco-editor version: 0.13.0
Browser: Edge
OS: Win 10 16299
Steps or JS usage snippet reproducing the issue:

If I setup two decorations (from the [playground example](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-line-and-inline-decorations)):
```
var decorations = editor.deltaDecorations([], [
	{ range: new monaco.Range(5,1,5,10), options: { isWholeLine: true, inlineClassName: 'myInlineDecoration', stickiness: 1 }},
	{ range: new monaco.Range(7,1,7,50), options: { inlineClassName: 'myInlineDecoration', stickiness: 1 }},
]);
```

They behave differently with respect to how the decoration expands around the decoration.  It seems like `isWholeLine` overrides the `stickiness` setting, as I was expecting in the first case for the decoration not to continue when I started adding to the line.  

Is this expected?  Otherwise it should be called out in the documentation.

**Comment by alexandrudima** [comment]
Yes, this is expected.

The `range` + `stickiness` are the ones that drive typing and growing behaviour.

`isWholeLine` is only a rendering-time flag for the `className` option. In conjuction with `inlineClassName`, `isWholeLine` doesn't do anything AFAICT.
