### ISSUE TITLE
provideDocumentFormattingEdits still uses default formatter

### ISSUE THREAD

**Issue by domoritz** [microsoft/monaco-editor#889]
I am providing my own custom json formatter with `provideDocumentFormattingEdits`. However, when I use it, the default json formatter is still active and so my formatting gets overridden. Can I set my formatter as the only formatter somehow? 

```ts
provideDocumentFormattingEdits(model: Monaco.editor.ITextModel, options: Monaco.languages.FormattingOptions, token: Monaco.CancellationToken): Monaco.languages.TextEdit[] {
  return [
    {
      range: model.getFullModelRange(),
      text: stringify(JSON.parse(model.getValue())),
    },
  ];
},
```

cc @aeschli from https://github.com/Microsoft/monaco-json

**Comment by aeschli** [comment]
That's currently not possible. We would need a new setting `json.format.enable` to the json monaco api. If you want to make a PR, that would be awesome.

**Comment by domoritz** [comment]
I see. What's the suggested way to get JSON syntax highlighting and completion but a custom formatter until that flag is added?

**Comment by nesterone** [comment]
FYI: I'm going to try with extending monaco api with `json.format.enable`

**Comment by algomaster99** [comment]
@nesterone Has this issue been resolved?
