### ISSUE TITLE
ES6 string interpolation incorrectly parsed

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/monaco-editor#89]
![screen shot 2016-08-02 at 6 24 19 pm](https://cloud.githubusercontent.com/assets/979966/17321986/a8fdddac-58de-11e6-82cf-3434d091f414.png)

This is the file where it happens: https://github.com/mdreizin/webpack-cluster/blob/master/src/CompilerStrategyPrettyEvents.js

The issue is reproducible in the latest published version of monaco-editor 0.5.3, however the latest VS Code doesn't seem to be affected.

**Comment by alexandrudima** [comment]
@jrieken Perhaps we don't hande multi-line interpolation in the tokenization adapter correctly?

**Comment by alexandrudima** [comment]
@jrieken 

Minimal repro:
```
`${{
x:5}.x}`;//comment
```

I think this hits the limits of what the TS lexer can do, perhaps forward them the issue...

**Comment by jrieken** [comment]
This is now fixed. @alexandrudima implemented a new tokeniser for TypeScript
