### ISSUE TITLE
Syntax highlighting monarch match rule regex word boundary ignored

### ISSUE THREAD

**Issue by roonyh** [Microsoft/monaco-editor#890]
I want to highlight only "int" when appearing has a whole word.

Here is my tokenizer
```javascript
return {
  tokenizer: {
    "root": [
      [
        /\bint\b/, "type"
      ]
    ]
  }
};
```
but it also highlights the "int" part of "print". The leading word boundary seems to be ignored.

![image](https://user-images.githubusercontent.com/3872221/40418417-f89540f8-5e9f-11e8-81c3-1ecee0824087.png)

monaco-editor version: 0.13.1
Browser: Chrome
OS: Ubuntu

**Comment by rcjsuen** [comment]
Maybe you can try this?
```JavaScript
return {
  keywords: [ 'int' ],
  tokenizer: {
    root: [
      [/[a-z_$][\w$]*/, { cases: { '@keywords': 'keyword' } }]
    ]
  },
};
```

**Comment by roonyh** [comment]
Thanks. That works.

But above seems to be a bug right?

We have both an online editor and a vscode plugin for our language and I'm trying to generate both tmLanguage and monarch grammars from the same yaml-tmLanguage file. This is pretty much the only thing thats blocking it. If this works as expected it would be awesome!

**Comment by roonyh** [comment]
@alexandrudima Thanks for the explanation. I now understand why it happens.
But when I use a similar tmlanguage grammar with a vscode extension it works.
~~~json
{
	"name": "mylang",
	"patterns": [
		{
			"name": "keyword.control.mylang",
			"match": "\\b(int)\\b"
		}
	],
	"scopeName": "source.mylang"
}
~~~
![image](https://user-images.githubusercontent.com/3872221/40835407-01465b3e-65b1-11e8-9616-be469dcdb1ec.png)

Do you know if the tokenizer in vscode for tmlanguage grammar behaves differently from the above?

**Comment by alexandrudima** [comment]
@roonyh Yes, the tmlanguage uses a different tokenization engine, based on the documentation of the TextMate editor. They are distinct implementations, using different concepts, and ultimately using different regular expression libraries.

**Comment by roonyh** [comment]
Thanks for the insights. I understand this is expected behavior. Hence closing the issue.
