### ISSUE TITLE
how to make a new theme ?

### ISSUE THREAD

**Issue by mengdu** [Microsoft/monaco-editor#893]
I want to know how to define a new theme through API.
I saw a [definetheme](https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#definetheme) API that defines the theme, but I don't know the definition rules. 

monaco-editor version: 0.13.1

**Comment by alexandrudima** [comment]
Here are the built-in themes

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/standalone/common/themes.ts#L13

**Comment by mengdu** [comment]
@alexandrudima thank's

**Comment by brijeshb42** [comment]
@mengdu You can use https://bitwiser.in/monaco-themes/ to generate theme for monaco from `tmTheme` files.

**Comment by mengdu** [comment]
that's so good. @brijeshb42
