### ISSUE TITLE
JS Modules distribution contains invalid imports of .css files

### ISSUE THREAD

**Issue by justinfagnani** [Microsoft/monaco-editor#894]
monaco-editor version: 0.13.1
Browser: All
OS: All
Steps or JS usage snippet reproducing the issue: See the jsbin here: https://jsbin.com/yixowakila/1/edit?html,console,output

When you try to run the sample you get many errors of the type:

> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.

It looks like the "esm" build is using some non-standard WebPack conventions which prevents the modules from actually running in the browser.

Since it's not possible to load CSS in this way, can these imports be build out before publishing to npm?

**Comment by alexandrudima** [comment]
See discussion in https://github.com/Microsoft/monaco-editor/issues/886
