### ISSUE TITLE
`monaco-editor/esm/` contains some non ES module files

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/monaco-editor#895]
monaco-editor version: 0.13.1
Browser: -
OS: -
Steps or JS usage snippet reproducing the issue:

1. `npm install monaco-editor`
2. check the files:
    - `node_modules/monaco-editor/esm/vs/language/html/_deps/vscode-html-languageservice/beautify/beautify-css.js`
    - `node_modules/monaco-editor/esm/vs/language/html/_deps/vscode-html-languageservice/beautify/beautify-html.js`

----

I found those files when I tried to build monaco editor by [rollup.js](https://rollupjs.org/). The bundler handles only ES modules by default, so it reported errors on those files. Eventually, I made [a rollup-plugin](https://github.com/mysticatea/vue-eslint-editor/blob/818157e5613a22606ca5aab9c9b32d27fc4078e2/scripts/rollup-plugin/mod-beautify-html.js) to modify those files to ES modules.

It would be useful if `monaco-editor/esm/` doesn't contain non ES module files.

**Comment by alexandrudima** [comment]
This will be fixed with the next version of the editor, once we pick up a new `monaco-html`.

The fix was done in https://github.com/Microsoft/vscode-html-languageservice/commit/d7c8214943eb0b6c7bfcab57a90d13a93b9b74bd
