### ISSUE TITLE
JSON autocompletion creates invalid JSON

### ISSUE THREAD

**Issue by domoritz** [Microsoft/monaco-editor#897]
monaco-editor version: latest

Start with the following json file and autocomplete the string "ordinal".

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"values": []},
  "mark": "bar",
  "encoding": {
    "x": {
      "type": "ord, "field": "a"
    }
  }
}
```

![moncao](https://user-images.githubusercontent.com/589034/40633522-03286ed8-62a5-11e8-990e-d47b41918afc.gif)

Notice how the autocomplete action "eats" the `"` of the following property. 

CC @aeschli from https://github.com/Microsoft/monaco-json

**Comment by rcjsuen** [comment]
I can reproduce this in VS Code 1.23.1. It's probably a bug in [Microsoft/vscode-json-languageservice](https://github.com/Microsoft/vscode-json-languageservice).

**Comment by rcjsuen** [comment]
Looks similar to Microsoft/vscode/issues/47197.

**Comment by aeschli** [comment]
From a scanner's perspective, you are competing in the middle of a string literal `"ord, "`.
So not really a bug, but I guess we can improve the heuristic. Dup of #47197 (thanks @rcjsuen)
