### ISSUE TITLE
How can I emulate click on line?

### ISSUE THREAD

**Issue by oleg-webdev** [Microsoft/monaco-editor#898]
I need to get focus on some line.
How can set focus to editor and place my cursor(carret) to certain position in editor?
Some sort of simulating user clicks to editor.
For example get editor focused in first line?

**Comment by alexandrudima** [comment]
```
editor.setSelection(new monaco.Selection(1,2,1,2));
editor.focus();
```

Have you seen the [API doc](https://microsoft.github.io/monaco-editor/api/index.html) ?
