### ISSUE TITLE
Website editor 404 mishandled, results in permanent error message

### ISSUE THREAD

**Issue by muddletoes** [Microsoft/monaco-editor#9]
As you'll be able to see quite quickly for yourself, the editor in the website suggests that it supports SCSS, but the related file ('/index/sample.scss.txt') is missing, resulting in a 404 error.

Using Chrome 49.0.2623.110, I selected SCSS through the menu.  This failed silently.  On my next selection and thereafter, the samples loaded but were displaced downwards by an error message that could not be dismissed by any means I could discover.

**Comment by alexandrudima** [comment]
Thank you for the heads up! :heart:
