### ISSUE TITLE
Registering/Providing custom Commands/CodeActions

### ISSUE THREAD

**Issue by nikeee** [microsoft/monaco-editor#900]
I am creating an editor which uses some language server implementation in JS. It provides two methods: `getCodeActions(...): Command[]` and `executeCommand(...): ...`. The first one gets the possible code actions on a position. This is essentially what the `CodeActionprovider#provideCodeActions` method does. The latter gets the `TextEdit`s when a command is actually executed (and applies them to the workspace using `applyEdit`). There is no pendant in the public monaco API for that.

As `provideCodeActions` can also return `CodeAction[]`, it is possible to compute the `TextEdit`s while providing the code actions. However, as this happens on basically every key press, this could get really heavy.

I've tried using non-public API. In this approach, I'm registering the commands and the handlers as soon as the editor is initialized:

```TypeScript
(editor as any)._commandService.addCommand({ 
		id: "command-id", 
		handler: (_: any, ...args: any[]) => {
			return myLspService.executeCommand("command-id", args);
		},
});
```

As this is a private API this feels very hacky. Is there a better solution for this? If not, what is the recommended way of doing this?

I think the easiest way for Monaco's API consumers would be to extend the `CodeActionProvider` to something like this:

```TypeScript
export interface CodeActionProvider {
	provideCodeActions(
		model: editor.ITextModel, 
		range: Range, 
		context: CodeActionContext,
		token: CancellationToken
	 ): (Command | CodeAction)[] | Thenable<(Command | CodeAction)[]>;
	executeCommand(
		model: editor.ITextModel, 
		command: string, 
		args: any[], 
		token: CancellationToken
	): CodeAction[] | Thenable<CodeAction[]>; // or return void | Thenable<void> and apply the command using model.pushEditOperations()
}
```

**Comment by rcjsuen** [comment]
For some additional context to this issue, the use of the internal `_commandService` is done because the [`addCommand` function](https://github.com/Microsoft/monaco-editor/blob/d7ef525b1d2ab817b9542644bf53af7ce2bd4042/monaco.d.ts#L1054-L1058) does not take an `id` as one of its argument. As pointed out, this is quite unfortunate.

Personally I would be in favour of changing that function to allow an id to go through but perhaps this was an intentional design decision.

**Comment by rcjsuen** [comment]
Was looking at this some more. Just realized that [`addCommand`](https://github.com/Microsoft/monaco-editor/blob/f6fb545dc9b61fbe2e44598ae3a1f1e6f9d6fe72/monaco.d.ts#L1055) takes a `number`, an `ICommandHandler`, and a `string` but a `monaco.editor.ICommand` actually doesn't define those properties at all but instead just [declares two functions](https://github.com/Microsoft/monaco-editor/blob/f6fb545dc9b61fbe2e44598ae3a1f1e6f9d6fe72/monaco.d.ts#L1841-L1858).

I'm hoping that the names here can be improved but I guess that would be a different issue.

**Comment by jrieken** [comment]
`addCommand` isn't the right abstraction, you should be able to provide an instance of the `ICommandService` when creating the editor. Then return commands as code actions.

**Comment by ToonvanStrijp** [comment]
Is there a better solution for adding a custom command? Cause I rather not use the private API for this. I'm searching for solutions but this is the only solution I found.

**Comment by ToonvanStrijp** [comment]
@jrieken, @nikeee can you explain me how I add conditions to the command when using:
```
(editor as any)._commandService.addCommand({ 
		id: "command-id", 
		handler: (_: any, ...args: any[]) => {
			return myLspService.executeCommand("command-id", args);
		},
});
```
