### ISSUE TITLE
Code Completion not working when embedding typescript in another language?

### ISSUE THREAD

**Issue by khoshrou** [microsoft/monaco-editor#901]
Hi guys, thank you for awesome product
Its a few days I am checking monaco and its pretty powerful. 
I am trying to embed typescript in another simple language. its working fine, coloring is OK. But I am losing code completion for type script (my own code completion provider works fine). If you check you sample for HTML you can see this problem there too. Is there any way we can have a full typescript support when its embedded?

monaco-editor version: 0.13.1
Browser: chrome
OS: win10
Steps or JS usage snippet reproducing the issue:
please check the HTML language .

**Comment by alexandrudima** [comment]
You can look into using the typescript compiler in your project. Here is the documentation: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API

Here is how we are using it: https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts

You can build a language service for your custom language and decide how you want to process the document to strip your custom language and leave only valid typescript. Once you are left with valid typescript, you can use directly the TypeScript Compiler API and the TypeScript Services API to ask TypeScript to provide you with completions, hovers, diagnostics, etc.

**Comment by khoshrou** [comment]
thanks alex, I am going to check this, but it would be wonderful if you provide a sample for this.
another suggestion would be samples for (angular 6) and (angular 6 + electron) i am having hard time using monaco in and angular electron project.
