### ISSUE TITLE
Any way to add selection class to deltaDecorations

### ISSUE THREAD

**Issue by antoniopol06** [Microsoft/monaco-editor#902]
monaco-editor version: 0.11.10
Browser: Chrome
OS: HighSierra
<img width="605" alt="screen shot 2018-05-30 at 17 54 39" src="https://user-images.githubusercontent.com/3017821/40732015-a7979adc-6432-11e8-996c-6edbcf4cc60b.png">

This [Sample](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-mouse-events) , I selected from line 2 to line 8, but line 3 that is deltaDecoration does not appear as selected. Is there any way to mark selected deltaDecorations?

Thanks @alexandrudima !

**Comment by antoniopol06** [comment]
Ok I resolved adding zIndex to  `.monaco-editor .selected-text`  

In this file [selections.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/selections/selections.ts#L413) appears the selector is applied by `editor.selectionBackground` .

**Comment by alexandrudima** [comment]
@antoniopol06 An alternative would be to use transparent colors in your decorations.

**Comment by antoniopol06** [comment]
That´s good idea but In the project that I work on, this kind of data is received from server. But I take this point for other features.

Thanks @alexandrudima !
