### ISSUE TITLE
wordBasedSuggestions: false does not turn off word-based completion

### ISSUE THREAD

**Issue by aromanovich** [Microsoft/monaco-editor#907]
monaco-editor version: 0.13.1
Browser: Version 66.0.3359.139
OS: Mac OS X 10.12.6

Though the original issue #334 is resolved, setting `wordBasedSuggestions: false` still does not turn off word-based completion.
The issue can be reproduced in the [playground](https://microsoft.github.io/monaco-editor/playground.html):
<img width="847" alt="screen shot 2018-06-02 at 20 28 48" src="https://user-images.githubusercontent.com/891264/40877998-ac84aee0-66a3-11e8-83b2-e19d7112f3f5.png">
When I hit Ctrl+Space after `//` I expect to not see word-based completion items such as `Hello`.

**Comment by alexandrudima** [comment]
The bug is fixed, we just need to ship a new version of the editor.

**Comment by FintechOS** [comment]
Hi, I can still repro this problem in 0.17
suppressing the word based suggestions works in typescript but not in javascript.
Any ideas for a workaround?
