### ISSUE TITLE
Color name is lacking for the minimap

### ISSUE THREAD

**Issue by Etendard7** [microsoft/monaco-editor#908]
Hi,

I am trying to define a theme for Monaco. This page describes every color I can customize :
https://github.com/Microsoft/monaco-editor/blob/master/test/playground.generated/customizing-the-appearence-exposed-colors.html

It seems there is no way to customize the minimap or scrollbar colors. I've tried them all.
Can you add these parameters ?
Thanks !

**Comment by cport1** [comment]
Has anyone been able to color the background of the canvas of the minimap?

**Comment by Etendard7** [comment]
Yes. It seems you can't set it in the "colors" field of your custom theme, but you can set it in the "rules" field as the "background" color of the "" token.

```
yourcustomtheme = {
    base: 'vs',
    colors: {        
        /*Set here the colors you want... except for the minimap*/
    },
    rules: [
        { token: '',
            background: yourdesiredcolorhere}
        /*Set here the other rules*/
    ]
}

monaco.editor.defineTheme('yourcustomtheme', yourcustomtheme);
```

**Comment by cport1** [comment]
Ah yes, that works!!! Thank you @Etendard7 !!
