### ISSUE TITLE
Parent scrollbar moves on editor scrolling when using the touchpad

### ISSUE THREAD

**Issue by jeradrutnam** [microsoft/monaco-editor#909]
**Issue**
Parent scrollbar moves on editor scrolling. Works fine with the standard mouse. Only happening when using the laptop touchpad and scroll slowly.

![monaco_scroll_issue](https://user-images.githubusercontent.com/7569427/40964075-c9faf094-68c7-11e8-9e13-2764a66c555d.gif)

**Monaco Editor Version:**
v0.11.6

**Browser:**
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

**OS:**
Windows 10 (64 Bit)

**Steps or JS usage snippet reproducing the issue:**
1. Navigate to: https://microsoft.github.io/monaco-editor/
2. Move mouse cursor on the editor in the home page and scroll slowly using the touchpad.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/commit/185d71b615e529b154c76907764bfda9270cb42f
