### ISSUE TITLE
ModelMarkers message not fully shown

### ISSUE THREAD

**Issue by Matthias247** [Microsoft/monaco-editor#91]
I have the problem that my for some ModelMarkers that I add to the model during validation the message that I assign to it is not fully displayed. 

E.g. in the following picture I assign message "Expected identifier", but only "Expected" and lots of whitespace is displayed.

![](https://abload.de/img/monacomzusf.png)

Not really sure if this is a monaco or a usage error. My markerdata looks as follows:

```js
{ severity: 3, code: null, source: null, startLineNumber: 1, startColumn: 1, endLineNumber: 1, endColumn: 2, message: "Expected identifier" }
```

Don't really know what I should assign to `code` and `source` since that doesn't seem to documented so I'm using null. Is this maybe related? 

However for other error messages it works correctly.

**Comment by alexandrudima** [comment]
@Matthias247 it looks like a rendering issue in the hover widget. What browser are you on and can you boil down a small repro HTML that shows the problem so we can debug and figure out what's wrong

**Comment by Matthias247** [comment]
@alexandrudima After looking at it once again and discovering how to pause the browsers debug tools while some mouseover is active I discovered that it seems to be due to some conflict with stylesheets and especially the box-sizing property:

In my css I have set the following:
````cs
body {
  box-sizing: border-box;
}

*,
*:before,
*:after {
  box-sizing: inherit;
}
```

Adding this in the css of the playground and e.g. using a javascript like the following shows the issue:

```js
monaco.languages.register({ id: 'mySpecialLanguage' });

var editor = monaco.editor.create(document.getElementById("container"), {
	value: getCode(),
	language: 'mySpecialLanguage'
});

var model = editor.getModel();
var markers = [{
    severity: monaco.Severity.Error,
    code: null,
    source: null,
    startLineNumber: 1,
    startColumn: 1,
    endLineNumber: 1,
    endColumn: 2,
    message: 'Expected identifier',
}];

setInterval(() => monaco.editor.setModelMarkers(model, 'mySpecialLanguage', markers), 1000);

function getCode() {
	return [
        '9asdfasd',
	].join('\n');;
}
```

**Comment by Matthias247** [comment]
I guess some measuring goes wrong here. Then the text does not fit in the first line and, the browser will put it into a second line which is not shown because the `<div class="monaco-editor-hover monaco-editor-background" widgetid="editor.contrib.modesContentHoverWidget">` is using an absolute size for only a single line.

Resetting `box-sizing` to `initial` for the monaco widget seems to fix it partially for me. The text is fully readable but in my full application not completely vertically centered. I guess I need to reset a view other properties. 

I'm using foundation UI as a base stylesheet if that's interesting to you.

**Comment by Matthias247** [comment]
Ok, fixed by setting the following css properties for the div into which I put the editor:

````css
box-sizing: initial;
font-family: initial; 
font-weight: initial;
font-size: initial;
line-height: initial;
```

The question is whether this should belong into Monacos bundled stylesheet.
Or whether the measuring and layout algorithms should be improved to accommodate user stylesheet changes.

**Comment by alexandrudima** [comment]
This is how the hover widget computes its width:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/hover/browser/hoverWidgets.ts#L78
```
var renderedWidth = Math.min(editorMaxWidth, this._domNode.clientWidth + 5);
```

I'm thinking that's wrong when using `box-sizing: border-box;`. Perhaps it should use [`offsetWidth`] (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth)
