### ISSUE TITLE
Missing language-definition for Julia

### ISSUE THREAD

**Issue by ststeiger** [microsoft/monaco-editor#911]
Monaco is missing a language-defintion for the statistics/ML & distributed-linear-algebra language [Julia](https://julialang.org/). 

Ace and Codemirror both have built-in support for [Julia](https://julialang.org/). 
https://codemirror.net/mode/julia/
https://ace.c9.io/kitchen-sink.html

**Comment by cossio** [comment]
Hope this gets added soon.

**Comment by Pocket-titan** [comment]
To anyone finding this issue: version [0.21.0](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0210-21092020) shipped with a built-in Julia mode, so this issue can be closed.
