### ISSUE TITLE
Monaco Editor throwing cannot read property make error

### ISSUE THREAD

**Issue by imzubair10** [microsoft/monaco-editor#912]
I installed monaco-editor package and following along [Option 1: Using the Monaco Editor Loader Plugin  example](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md), 

```
npm install monaco-editor
npm install monaco-editor-webpack-plugin
```

**index.js**
import * as monaco from 'monaco-editor';

**webpack.config.js**

```
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
module.exports = {
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'app.js'
  },
  plugins: [
    new MonacoWebpackPlugin()
  ]
};
```

but it throws an error as you could see in the below pic

![monaco-erro-webpack](https://user-images.githubusercontent.com/17908661/41126975-3075a0e8-6a5e-11e8-888f-4c0325b460c4.PNG)

**Comment by jjyyxx** [comment]
Your webpack version?

**Comment by imzubair10** [comment]
3.10.0

**Comment by imzubair10** [comment]
any updates on this please??

**Comment by jjyyxx** [comment]
currently it seems to support webpack 4 only according to
[this issue](https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/5)

**Comment by imzubair10** [comment]
ah, so it means i cant use it until update to webpack 4

**Comment by jjyyxx** [comment]
in that issue, mheavenor provided a version compatible with webpack 3. Maybe you can  give it a try.
Or you can update to webpack4, It's not so painful, I hope.

**Comment by imzubair10** [comment]
i see, let me try
