### ISSUE TITLE
Duplicate decorators when user has press enter for new line

### ISSUE THREAD

**Issue by oleg-webdev** [Microsoft/monaco-editor#913]
[Accordingly to guide](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin), I've set markers with deltaDecorations like so:
When gutter has been clicked
```
editor.onMouseDown((e) => {
        const { target: { element, range } } = e;
        if (element.className === 'line-numbers') {
          //...
        }
      });
```
doing some checks and set marker:
```
editor.deltaDecorations(
      [], [{
        range: new monaco.Range(line, 1, line, 1),
        options: {
          isWholeLine: true,
          className: 'myContentClass',
          linesDecorationsClassName: 'breakpointStyle'
        }
      }]);
```
All is fine till "enter" has been pressed on line, which contains a decorator.
This action has side effect - new line inserted with decorator
[Preview](https://media.giphy.com/media/uinNvspvNyimbyQ1GD/giphy.gif)
https://media.giphy.com/media/uinNvspvNyimbyQ1GD/giphy.gif
Why does it happend and how can I prevent duplicated decorators?

**Comment by alexandrudima** [comment]
@oleg-webdev The decorations you are creating via a call to `editor.deltaDecorations` will be alive until you remove them (via `editor.deltaDecorations`) or until the model is disconnected from the editor (either via model disposing, editor disposing, or `editor.setModel` with a different model).

In other words, you need to keep track of the identifiers returned by `deltaDecorations`, as they are handles to the decorations you have created.

```
var decorations = [];
decorations = editor.deltaDecorations(decorations, ....);
...
decorations = editor.deltaDecorations(decorations, ....);
```

A call to `deltaDecorations` will remove the decorations with the handles passed in as the first argument and will create the decorations described in the second argument. It will then return the handles to those new decorations. (For optimization purposes, it will sometimes reuse the same handles)
