### ISSUE TITLE
About the difference between getConfiguration() and updateOptions()

### ISSUE THREAD

**Issue by nishlumi** [microsoft/monaco-editor#917]
Is IStandaloneCodeEditor.getConfiguration () and IStandaloneCodeEditor.updateOptions () available in different settings?
  I tried both. However, I thought that the structure of some setting items is different.
  When using IStandaloneCodeEditor.getConfiguration (), make sure to use the setting name with the same structure as updateOptions ().
  Also make sure to use getConfiguration () in IStandaloneDiffEditor.

(example) same as getOptions()/setOptions() in the Ace editor

monaco-editor version: 0.13.1
Browser: Chrome 67.0.3396.87
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

**Comment by alexandrudima** [comment]
`editor.getConfiguration()` gives the **validated configuration**.
`editor.getRawConfiguration()` (non public API) gives the **raw configuration**, as provided to the editor, before validation.
