### ISSUE TITLE
IModel.tokenIterator not present in monaco.d.ts

### ISSUE THREAD

**Issue by Alexendoo** [microsoft/monaco-editor#92]
I couldn't find a way to access tokens nicely using only the API specified in manoco.d.ts so I'm not sure if this is meant to be public or not, but I do hope so as it's very useful

**Comment by AndersMad** [comment]
indeed - I manually added (copied) the `interface ILineTokens` and extended the model with `getLineTokens` and other hidden gems.. maybe they are not public yet because they are in the flux or just not added yet.

**Comment by alexandrudima** [comment]
We're planning quite some refactorings in how tokens are stored to better support nested scopes. Today tokens are binary encoded in a number, but that might not be the best representation. That's why the tokens API is sort of private, but of course you can use it as @AndersMad nicely describes :)

**Comment by alexdima** [comment]
This got deleted from the source altogether.
