### ISSUE TITLE
Syntax highlighting disappears

### ISSUE THREAD

**Issue by ReginaldBull** [microsoft/monaco-editor#923]
monaco-editor version: 0.13.1
Browser: Chrome/Firefox
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

This only happens when using the monaco not in bundled version.
Syntax higlighting disappears when using the editor in a browser and reloading the page. After debugging I think the problem is on modesRegistry.ts line 33. When reloading the page an entry for the language is added again to this._languages. Solution for this could be to check the array if there is already an existing entry for the language.

**Comment by alexandrudima** [comment]
@ReginaldBull 

It would be helpful if I could reproduce what you are describing. The `registerLanguage` method you are pointing to should be called once for each language supported by the monaco editor and AFAICT that method is implemented correctly.
