### ISSUE TITLE
Can markers support html display just like hoverProvider do ?

### ISSUE THREAD

**Issue by datou0412** [Microsoft/monaco-editor#924]
Now I use `setModelMarkers` just like this : 

``` javascript
const markers = [];
markers.push({
        severity,
        startColumn,
        startLineNumber,
        endColumn,
        endLineNumber,
        message,
        source,
        code,
});
this.monaco.editor.setModelMarkers(
      this.editor.getModel(),
      'eslint',
      markers
);
```

I want to show eslint errors the way just like in vscode (highlight the prat `var console: Console`)
![image](https://user-images.githubusercontent.com/5847142/41595487-8a3fae62-73f9-11e8-9f43-5f4d7e2a0f70.png)

My questions are :
- How can i do this (display html in markers) with `setModelMarkers` ? 
- By the way, what does the property `code` use for ?

**Comment by alexandrudima** [comment]
You can't use directly HTML, but you can use markdown in the message for a marker.

AFAICT `code` isn't used anywhere. @jrieken what is the purpose of `IMarker.code` ?

**Comment by jrieken** [comment]
`code` (as error_code) is used to feed information back to code action provider. that's how they often link errors to fixes
