### ISSUE TITLE
Brief method description while user is typing

### ISSUE THREAD

**Issue by oleg-webdev** [Microsoft/monaco-editor#927]
Let's assume I need to create my custom intellisense for js
For example I have some environment and there is available some global variables, let's call it web.
And this var has methods, so we can declare it as kinda module:
```
// extra libraries
monaco.languages.typescript.javascriptDefaults.addExtraLib([
        '/**',
        ' * Lorem ipsum dolor sit...',
        ' */',
        'declare var web = (function(){',
        '/**',
        ' * Returns nextigeee',
        ' */',
        'function nextAction(){',
        'console.log(\'somestring\');',
        '}',
        'return {',
        'nextAction: nextAction',
        '}',
        '}());'
].join('\n'), 'filename/facts.d.ts');

var jsCode = [
	'web.nextAction()',
].join('\n');

monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});
```
It works and I got my 'nextAction' autocomplete for 'web' module.
But description of a method will be shown onmouseover.
Is there any possibility to add at least brief description when user is typing any method of this module?
Something more informative than (propery) nextAction: ()=> void

https://i.imgur.com/EWF534h.png

**Comment by alexandrudima** [comment]
The JSDoc appears if you click on the `i` icon. Or if you press Ctrl+Space again.
