### ISSUE TITLE
[Tokenization] Accept array of scope names

### ISSUE THREAD

**Issue by NeekSandhu** [microsoft/monaco-editor#929]
Tokenizer passed to `monaco.languages.setTokensProvider` won't accept array of scope names.

https://github.com/theia-ide/theia/pull/2118#issuecomment-398462578

[NeekSandhu/monaco-editor-textmate/src/index.ts:50](https://github.com/NeekSandhu/monaco-editor-textmate/blob/397483c2b0e09a0f556763b5496a5a3ac7d41564/src/index.ts#L50)

https://github.com/NeekSandhu/monaco-editor-textmate/issues/3

**Comment by svenefftinge** [comment]
This change should solve it:
https://github.com/Microsoft/vscode/commit/1f79465e8c28b9cbb8486cd5d99fb9a41bdb63fc

Any idea when this will land here?

**Comment by alexdima** [comment]
That change has been shipped.
