### ISSUE TITLE
Diff Editor not disposable if it hasn't been given a model

### ISSUE THREAD

**Issue by Mr-Wallet** [Microsoft/monaco-editor#931]
1. Construct a diff editor using `window.monaco.editor.createDiffEditor`
2. Do not call `setModel` on the editor.
3. Once some async call finishes it turns out we pre-emptively mounted the editor for nothing, go ahead and `dispose` of it.
4. An error is thrown in `DiffEditorWidget.prototype.dispose` because of an unguarded call to `this._originalOverviewRuler.getDomNode` - the rulers do not exist if the editor has no model.

Presumably there is at least some stuff to dispose on the editor, even if it doesn't have a model yet. I'm not very familiar with Monaco yet, but it seems like either it should be properly disposable immediately after construction in all cases, or it shouldn't be constructable without models.

**Comment by alexandrudima** [comment]
Fixed via 60553906f7f54322bb041fac48097796e18a563d
