### ISSUE TITLE
Setting multiple line comments

### ISSUE THREAD

**Issue by nikeee** [Microsoft/monaco-editor#937]
I'm trying to use the API `monaco.languages.setLanguageConfiguration(id, config)` where config is a [`LanguageConfiguration`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.languageconfiguration.html). It offers the possibility to define how comments are made using `comments.lineComment` and `comments.blockComment`.
I'm creating a language configuration for Graphviz/DOT, which has multiple ways for doing a single-line comment (`// comment` and `# comment`). Is it possible to support both? `comments.lineComment` is of type `string`, not `string[]`, so I cannot define multiple ways for comments. Will this be supported some day or do I need to use a workaround? DOT is not the only language to have multiple single line comments, PHP also has both: `//` and `#`.

monaco-editor version: `0.13.1`

**Comment by alexandrudima** [comment]
I suggest you use the most popular and established form...

That setting is limited to impact only the toggle line comment action (`ctrl+/`)...

**Comment by nikeee** [comment]
Well, I guess specifying multiple ways for single line comments doesn't make any sense.
