### ISSUE TITLE
Error highlighting for custom language

### ISSUE THREAD

**Issue by naumanumer** [Microsoft/monaco-editor#94]
i am using monaco in my electron application and want to support an custom language with error highlighting and true intellisence . i come to know that i have to write language parser for it. and i want to know that how to write custom language parser OR is there any other way to highlight syntax errors and provide true intellisence.

**Comment by RoboPhred** [comment]
Both are possible.  The language parser is responsible for syntax highlighting, and errors / intellisense can be added in as additional handlers.

For syntax highlighting and some basic intellisense, see the [custom language example](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages).

A great example on how to add intellisense and error highlighting is the [monaco-typescript](https://github.com/Microsoft/monaco-typescript) project.  It handles parsing using its own copy of the typescript compiler, then pushes the output into monaco.  Take a look at [languageFeatures.ts](https://github.com/Microsoft/monaco-typescript/blob/master/src/languageFeatures.ts) for how this is done, especially DiagnostcsAdapter._doValidate (highlights errors with editor.setModelMarkers) and SuggestAdapter (registered in mode.ts via monaco.languages.registerCompletionItemProvider).

Unfortunately, the tokenizer in monaco doesn't seem to be exposed, I am still looking into that myself.  As far as I can tell, you are on your own for parsing your language.
