### ISSUE TITLE
what's the diff between monaco-editor and monaco-editor-core?

### ISSUE THREAD

**Issue by harkue** [Microsoft/monaco-editor#941]
what's the diff between monaco-editor and monaco-editor-core?

can i use some platform interface/API as monaco.platform.xx in monaco-editor?

**Comment by rcjsuen** [comment]
@harkue I am not familiar with the full details but `monaco-editor` includes the languages definitions in [Microsoft/monaco-languages](https://github.com/Microsoft/monaco-languages) and other such support. `monaco-editor-core` is just the editor and its APIs and there is no out-of-the-box language support.

**Comment by harkue** [comment]
@rcjsuen I see. Thanks a lot.
Yes,  i should copy language plugins into output path if i used `monaco-editor-core` .

I am working on building a custom editor for vue.
Some language feature works such as suggestion and completions, but it can't go to definition from other file in workspace.

I am trying to implement API of `monaco-editor-core`, but these API related to the platform and workbench API, so I was wondering if  I should use interface/API as monaco.platform.xx and migrate some implements from VSCode to make it work.

**Comment by alexandrudima** [comment]
See https://github.com/Microsoft/monaco-editor/blob/master/CONTRIBUTING.md#a-brief-explanation-on-the-source-code-structure

`monaco-editor-core` has 95% the same API surface as `monaco-editor`. `monaco-editor` consists of `monaco-editor-core` and another 5 plugins, that add support for various programming languages.

**Comment by harkue** [comment]
@alexandrudima  Got it, thank you very much.
