### ISSUE TITLE
editor.addCommand returns a command id string instead of a disposable

### ISSUE THREAD

**Issue by brijeshb42** [microsoft/monaco-editor#942]
monaco-editor version: 0.13.1
Browser: Chrome 67
OS: macOS

In this [file](https://github.com/Microsoft/vscode/blob/a6e28b0be061f27a5ea179aa675e7d8e23d6cfd3/src/vs/editor/standalone/browser/standaloneCodeEditor.ts#L195), `StandaloneCodeEditor.addCommand` returns a `commandId` instead of a disposable. Is there any specific reason for it? If yes, then how do I remove a manually added command with public api?

**Comment by troy351** [comment]
@alexandrudima I got the same question.
And is there a way to dispose added command?

**Comment by alexandrudima** [comment]
You could simply switch to `addAction` and also define a label. The only real difference is that the `F1` list will then show your command, which is not that bad...

**Comment by bryanl** [comment]
@alexdima What you prescribe won't work for code lens out of the box unless you created some other machinery.

**Comment by 929853209** [comment]
I don't found a method to reject ```addCommand``` ，but I found it won't be called multiply by repeat define ```addCommand```in a react hook.  Was the ```addCommand```just like a Singleton? And I still want to know how to reject it.

**Comment by alexdima** [comment]
The upcoming editor release will add `monaco.editor.registerCommand` to cover this usecase. (via https://github.com/microsoft/vscode/commit/7c937a7a383ca131c5e36811d4440878c97a1191)
