### ISSUE TITLE
Completion provider not being called whilst typing

### ISSUE THREAD

**Issue by samdenty** [microsoft/monaco-editor#943]
When using a custom completion provider, Monaco will only call the `provideCompletionItems` when typing if there are no more suggestions available for the chosen language. The only way to get the suggestions to appear, is to press `CTRL-SPACE`

Is there a way to make it call the `provideCompletionItems` method on each keypress regardless of whether suggestions already exist?

## Versions

monaco-editor version: 0.13.1
Browser: Chrome 68

## Reproducing

```ts
monaco.languages.registerCompletionItemProvider('javascript', {
  provideCompletionItems: (model, position) => {
    const match = model.getValue().includes('Te')
    if (!match) return []

    return [
      {
        label: 'Test',
        kind: monaco.languages.CompletionItemKind.String,
        insertText: 'Test'
      }
    ]
  }
})

monaco.editor.create(document.getElementById('container'), {
  value: '',
  language: 'javascript'
})

```

## Demo
![](https://i.imgur.com/kVUSaLW.gif)

**Comment by alexandrudima** [comment]
I think [`isIncomplete`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionlist.html#isincomplete) would cover your case.
