### ISSUE TITLE
Internally referencing ids not possible in JSON schemas

### ISSUE THREAD

**Issue by lukasbach** [Microsoft/monaco-editor#944]
monaco-editor version: 0.13.1 and playground
Browser: Chrome 67.0.3396.99
OS: Windows 10
Steps or JS usage snippet reproducing the issue:

Using the following snippet in the playground editor:

```
// Configures two JSON schemas, with references.

var id = "foo.json";

monaco.languages.json.jsonDefaults.setDiagnosticsOptions({
	validate: true,
	schemas: [{
        uri: "http://myserver/foo-schema.json",
        fileMatch: [id],
        schema: {
            type: "object",
            properties: {
                p1: {
                    id: "#a1",
                    enum: [ "v1", "v2"]
                },
                p2: {
                    "$ref": "#a1"
                }
            }
        }
    }]
});


var jsonCode = '';

var model = monaco.editor.createModel(jsonCode, "json", id);

monaco.editor.create(document.getElementById("container"), {
	model: model
});
```

![image](https://user-images.githubusercontent.com/4140121/42332127-83bc28a6-8077-11e8-9efd-88461b68158d.png)

I expect to get the same json schema validation and the same suggestion popup for p1 and for p2, as both should follow the same schema, but monaco does not show proper suggestions for p2, whereas monaco does show the possibilities v1 and v2 for p1.

**Comment by aeschli** [comment]
See https://spacetelescope.github.io/understanding-json-schema/structuring.html how the `$ref` is working.

In your case it would be `"$ref": "#/references/p1"`

But maybe I don't know about the syntax you are using. If you have any pointers specifying that syntax, please let me know.
