### ISSUE TITLE
How to get the line count including line wraps

### ISSUE THREAD

**Issue by raedle** [Microsoft/monaco-editor#947]
Is it possible to get the line count of a modal + the lines added when the editor wraps a line due to characters exceeding word wrap column?

**Comment by raedle** [comment]
I tried to calculate the effective lines based on the wrapping column, but that only works when lines are wrapped exactly at the wrapping column.

```
let lineCount = model.getLineCount();
const wrappingColumn = wrappingInfo.wrappingColumn;
if (wrappingColumn > -1) {
    let additionalLines = 0;
    const lines = model.getLinesContent();
    for (let i = 1; i <= lineCount; i++) {
        const lineLength = model.getLineLength(i);
        additionalLines += (lineLength / wrappingColumn) | 0
    }
    lineCount += additionalLines;
}
```

However, as Monaco wraps lines based on certain characters even before the wrapping column is reached.

Does anyone know how Monaco calculates line wraps and where I can find the code for it?

Thanks!

**Comment by MonirAbuHilal** [comment]
Not sure if there is a better way but the `editor.viewModel.lines.getViewLineCount()` method seems to be returning the count for all lines (including the auto-wrapped ones).

Live Demo:
https://codepen.io/monir/pen/72958128d822b228ba0245b16171c293?editors=0010

**Comment by raedle** [comment]
@MonirAbuHilal, that works like a charm. Thanks.

One more thing: What option to set if line breaks should happen at editor width instead of a pre-defined wrapping column?

Out of curiosity: this is an undocumented API. What was your strategy to find it?

**Comment by raedle** [comment]
I looked in the #vscode repo and found that `editor.viewModel.getLineCount();` returns the same result than `editor.viewModel.lines.getViewLineCount()`.

@MonirAbuHilal here is a live demo on the basis of your CodePen: https://codepen.io/raedle/pen/rrNMRN

**Comment by vthinkxie** [comment]
Hi @MonirAbuHilal it seems that monaco editor has removed viewModel in the latest version, is there any method to get `getViewLineCount` now?

**Comment by moranje** [comment]
Hmmm there is `editor.getModel().getLineCount` but that return the line count irrespective the wrapped extra lines.
