### ISSUE TITLE
How to remove padding-top of IntelliSense

### ISSUE THREAD

**Issue by Alsmile** [microsoft/monaco-editor#948]
![image](https://user-images.githubusercontent.com/1797302/42379764-60dbd236-815e-11e8-85ad-984cbe20db10.png)

`.monaco div {
  padding-top: 0;
}`
This is work, but is proper?

**Comment by alexandrudima** [comment]
By default, we don't ship with that padding. IMHO there is some other selector on your page that adds the padding to begin with.
