### ISSUE TITLE
How to use it on browserify

### ISSUE THREAD

**Issue by mimorisuzuko** [Microsoft/monaco-editor#95]
When I try to use it on `browserify(gulp-browserify)`, other modules is not imported.
I think `require` is overwritten by `loader.js`.

I ask you to how to use it on `browserify` correctly.

**Comment by joelday** [comment]
Agreed, I'd like to be able to bundle this so that everything can be loaded synchronously and so the bundle can be limited to the specific dependencies that I want.

**Comment by mimorisuzuko** [comment]
For example, you can rename `loader.js` require? So that, prevent require conflict.

**Comment by qballer** [comment]
Maybe you can draw ideas from #40, it's a webpack discussion but it might help.

**Comment by ohmygod12121212** [comment]
rename loader.js require is a good idea
webpack bundle require into one file, but loader.js require should be running dynamicly at runtime

**Comment by mimorisuzuko** [comment]
Fixed by https://github.com/Microsoft/monaco-editor/issues/18?

**Comment by yuanliwei** [comment]
In my case, I just replaced `require` with `window['require']`, and it worked.

```html
<script src="https://cdn.bootcss.com/monaco-editor/0.17.1/min/vs/loader.js"></script>
```
```javascript
window['require'].config({ paths: { 'vs': 'https://cdn.bootcss.com/monaco-editor/0.17.1/min/vs' } })
window['require'](['vs/editor/editor.main'], function () {
    const monaco = window.monaco || require('monaco-editor'); // for IntelliSense
    var editor = monaco.editor.create(document.querySelector('.editor-container'), {
        language: "javascript",
        roundedSelection: false,
        scrollBeyondLastLine: false,
        readOnly: false,
        theme: "vs",
        fontSize: 20,
    });
});
```

**Comment by jamesgibson14** [comment]
Thanks @yuanliwei your solution worked for me only I changed the cdn url to unpkg:
`https://unpkg.com/monaco-editor@0.18.1/min/vs/loader.js`
