### ISSUE TITLE
Custom Intellisense Get Info From DataBase, Is Possible?

### ISSUE THREAD

**Issue by crashangelbr** [microsoft/monaco-editor#950]
monaco-editor version: 0.13.1
Browser: Firefox
OS: Arch linux
Steps or JS usage snippet reproducing the issue:

I am making an application that generates speech and conversation scripts for ChatBots .. I would like to know if I have a custom Intellisense where I load a list of words from a database ...

**Comment by rcjsuen** [comment]
@crashangelbr Yes, that is possible. The suggestions can be anything you want them to be.
