### ISSUE TITLE
QuickOpenController should not always return focus to editor on close

### ISSUE THREAD

**Issue by gins3000** [Microsoft/monaco-editor#951]
monaco-editor-core version: 0.13.1

Can be reproduced in Monaco Playground:

1. Press F1 to summon the command bar on the right side
2. Press into any other input area, e.g. the editor on the left side

**Expected:**
I clicked on some new text input element, and expect to be able to type into it

**Observed:**
The focus is on the editor that belongs to the F1 command bar, so my typing happens there.
I have to click twice, in order to type in the position I want.

Tracked it down to this line:
https://github.com/Microsoft/vscode/blob/adfa9ce9778a6e79197477fcc60cb5420a31979a/src/vs/editor/standalone/browser/quickOpen/editorQuickOpen.ts#L72

I quickfixed the issue for our (electron) project by applying the following condition, which works, because at this point, the element is gone and focus has been returned to the document body, unless the reason for the blur was the focus of another element.

```
if (document.activeElement === document.body) {
	this.editor.focus();
}
```

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/9c2c8d9bb1e2808c9d5cfdd27241cfc246402be9
