### ISSUE TITLE
Is C++ autocomplete supported?

### ISSUE THREAD

**Issue by hifall** [microsoft/monaco-editor#955]
monaco-editor version: 0.13.1
Browser: Google Chrome Version 67.0.3396.99
OS: macOS 10.12

Steps or JS usage snippet reproducing the issue:
Go to the official demo at: https://microsoft.github.io/monaco-editor/, switch language to C++, then enter this code:

```
#include <iostream>
using namespace std;

int main()
{
    std::
}
```

I was expecting there would be some autocomplete widget that popped up after `std::`, but nothing happened.

**Comment by hifall** [comment]
Hmm, thought it was since the documentation doesn't say otherwise. But anyway, good to know. Thanks!

**Comment by hifall** [comment]
Now that it's not supported at the moment -- is C++ support on the roadmap?

Guess C++ support would be pretty reasonable since some other languages less popular than C++ are already supported officially by monaco.

Would be awesome to have it!

**Comment by rcjsuen** [comment]
@hifall Supporting C++ is a huge undertaking given the complexities of the language. Just for `std::` you need to consider which C++ specification the person is targeting as that will change which functions are available to the user.

I don't work for Microsoft or anyone that actively contributes to Monaco...but I wouldn't hold my breath. You should really look into hooking up a C++ language server instead. Just sayin'...

**Comment by hifall** [comment]
@rcjsuen, I am not suggesting implementing a C++ language server. I am proposing hooking up with a C++ language server like this one: https://clang.llvm.org/extra/clangd.html. Therefore, much of the huge undertaking would be already implemented in the server.

**Comment by rcjsuen** [comment]
@hifall Ah, I see. So you are hoping someone do the hooking to [TypeFox/monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) for C++ support.

What is your end goal? Are you just trying to create a C++ sandbox for a single file? I feel like analyzing references to include headers and so on will be non-trivial for a C++ project stored in the cloud.

**Comment by hifall** [comment]
We are trying to build some web app to provide some PL (including C++) smarts to our users. One of the goals is to enable them to use autocompletion feature.

I am not too familiar with monaco/LSP in general yet, but we might look deeper later.

Cheers!
