### ISSUE TITLE
Why abc symbols?

### ISSUE THREAD

**Issue by hifall** [microsoft/monaco-editor#956]
monaco-editor version: 0.13.1
Browser: Google Chrome Version 67.0.3396.99
OS: macOS 10.12

Steps or JS usage snippet reproducing the issue:
Go to the official demo at: https://microsoft.github.io/monaco-editor/, switch language to Go (and some other languages), then enter some code to bring up the completion widget, you will see all icons are displayed as abc symbols.

The symbols for Javascript are correctly displayed.

**Comment by rcjsuen** [comment]
@hifall Those are just dictionary/word matches local to the code I think.

Code completion is not supported by default for many languages in Monaco.
