### ISSUE TITLE
Add an option to enable "Use Regular Expressions" on the Find Widget

### ISSUE THREAD

**Issue by stanislavgeorgiev** [microsoft/monaco-editor#958]
monaco-editor version: 0.13.1

I would be really happy if there was an option to programmatically select the Use Regex option.

![untitled](https://user-images.githubusercontent.com/1253469/42767506-370bdf48-88eb-11e8-9cce-deb746bb8d9b.jpg)

**Comment by brijeshb42** [comment]
There already is -

```js
controller = editor.getContribution('editor.contrib.findController');
controller.toggleRegex();
```

**Comment by stanislavgeorgiev** [comment]
Thanks @brijeshb42, you're a life saver! 
I wish there was more documentation and more examples on Monaco's website.
