### ISSUE TITLE
Suggested way to determine text ranges for a JSON CodeLensProvider

### ISSUE THREAD

**Issue by foxable** [Microsoft/monaco-editor#959]
Hi,

I would like to implement a CodeLensProvider for a dictionary-like JSON structure. Therefore I need to determine the text ranges of the properties on a given JSON object. My first thought was to use the JSON tokenizer I assumed to be coming with monaco-editor. However, it seems to be encapsulated inside the JSON worker (`monaco.editor.tokenize(input, "json")` returns just one token including the complete input).

What, in your opinion, would be a good way to determine the text ranges for a JSON CodeLensProvider? Maybe implementing a simple MonarchTokensProvider for JSON?

Thank you in advance!

**Comment by alexandrudima** [comment]
You can use a JSON parser on your side and parse the text again. Currently, the JSON web worker is not pluggable with custom functionality, so it is not easy possible for you to inject custom logic that takes advantage of the built-in JSON AST.

**Comment by aeschli** [comment]
Our JSON parser is available as separate node module: `https://www.npmjs.com/package/jsonc-parser`, giving you an AST for your JSON with and without comments. It's also consumable by webpack.
