### ISSUE TITLE
Intellisense box (Ctrl+Space) is broken in IE11

### ISSUE THREAD

**Issue by T18970237136** [Microsoft/monaco-editor#96]
Hi,

I noticed a problem with the Monaco Editor in IE11, where the "intellisense box" (sorry, I don't know the correct terminology) doesn't show correctly in IE11.

Steps to reproduce:

1. Open the [Demo Page](https://microsoft.github.io/monaco-editor/) and select **TypeScript** as language.
2. At the top of the file, type `Math.` <br>Result in IE11 and Edge (OK):
![monaco-before](https://cloud.githubusercontent.com/assets/9880824/17443695/5af6c0b4-5b3c-11e6-9a0a-c7d3e6662302.png)
<br><br>

3. Now press **Ctrl + Space**.

Actual (IE 11):
![monaco-ie11](https://cloud.githubusercontent.com/assets/9880824/17443741/892d8c9c-5b3c-11e6-89eb-bd2263e0e494.png)

Expected (Edge):
![monaco-edge](https://cloud.githubusercontent.com/assets/9880824/17443653/17900074-5b3c-11e6-9065-a92d3e3a0091.png)

Note that after pressing Ctrl+Space, even the other Intellisense window doesn't work again if you move the cursor somewhere and type `Math.` just like above.

We are using the Monaco Editor in the embedded WebBrowser control in a WPF which unfortunately is bound to IE11 instead of Edge, so it would be nice if Monaco shows correctly in IE11.

Thanks!

**Comment by sandyarmstrong** [comment]
There are a few ways to trigger this. They key for me seems to make sure that at some point the completion provider returns no results. From that point on, subsequent displays of the completion widget will result in invisible completion items (as displayed above).

Relatedly, on other browsers, if there are no completion results the widget will display "No suggestions." IE11 will not do this.

**Comment by sandyarmstrong** [comment]
I wanted to debug this issue but then ran into https://github.com/Microsoft/monaco-editor/issues/97.

**Comment by sandyarmstrong** [comment]
Cool, turns out debugging works in Windows 8.1. In the scenario originally reported, the issue is that the `tree` child of `suggest-widgets` has `display:none`.

The `message` child of `suggest-widgets` has `display:none` when the suggest box works and when it malfunctions as described in the original report. But interestingly, it has a text child of "No suggestions" in the latter case. Even though `monaco-list-rows` is identically populated in both scenarios.

I'll keep digging.

**Comment by sandyarmstrong** [comment]
Yay, easy fix. In https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/dom.ts#L963, in the `show` function, just change `element.style.display = null` to `element.style.display = ''`.

I'll submit a PR.

**Comment by T18970237136** [comment]
Thank you!
