### ISSUE TITLE
JavaScript tokenisation not identifying regular expressions

### ISSUE THREAD

**Issue by johnkennedy9147** [microsoft/monaco-editor#961]
Originally noticed this while implementing a theme on freeCodeCamp where we are using Monaco.

But same behaviour is seen in Monaco playground:

![image](https://user-images.githubusercontent.com/26827682/42852583-3aa8c38e-8a29-11e8-9640-8501e14910be.png)

Expected behaviour only seen on Monarch  page:
![image](https://user-images.githubusercontent.com/26827682/42852612-64ac55e2-8a29-11e8-853e-5800c0bc5e77.png)

Should the tokeniser not be implementing this?
https://github.com/Microsoft/monaco-typescript/blob/c7b54325fd700fe5c44849a11a8e549296b03951/src/tokenization.ts#L154

**Comment by alexdima** [comment]
This now works because we have switched to Monarch for tokenization of JS and TS.
