### ISSUE TITLE
How to compile all this into a single file the way MS did for VS Code?

### ISSUE THREAD

**Issue by orionflame** [microsoft/monaco-editor#963]
Hi,

I couldn't find an answer to this. If anyone knows would appreciate it.

Thanks a lot.

**Comment by alexdima** [comment]
The editor is bundled at `/min`. There are also many webpack samples available at https://github.com/microsoft/monaco-editor-samples

**Comment by orionflame** [comment]
Thanks for replying. I am not familiar with this. What's min? I noticed VS code is doing something similar i.e. it's an exe but when I used spy I can see it's a compiled web based control.

What I am trying to do is basically integrate your editor into an app like Maya as a script editor, using the provided qt/pyqt interface. Not sure if it's possible but I would appreciate any pointers.
