### ISSUE TITLE
Which features of Azure Cloud Shell editor are in monaco

### ISSUE THREAD

**Issue by beriberikix** [microsoft/monaco-editor#965]
https://azure.microsoft.com/en-in/blog/cloudshelleditor/

The new Azure Cloud Shell editor is a great use of Monaco. If I wanted to make my own lightweight editor that has similar Code-like features for light editing on the web, how much is already implemented in Monaco and how much will I have to develop on my own? I noticed a command palette, snippets, auto completion...I'm sure there's more.

I can imagine using it just about anywhere my apps need to edit a config!

**Comment by rcjsuen** [comment]
@beriberikix The Monaco Editor can do many of the same things that Visual Studio Code can. I suggest you try things in out in the [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html) and see for yourself what it is capable of while running on the web.
