### ISSUE TITLE
On document format event

### ISSUE THREAD

**Issue by darind** [Microsoft/monaco-editor#968]
I would like to apply some custom document formatting to an **existing** language (`html`). For this reason I tried registering a custom formatting provider:

```
monaco.languages.registerDocumentFormattingEditProvider("html", {
    provideDocumentFormattingEdits: () => {
        console.log("ok");
        return [];
    }
});
```

Unfortunately the `registerDocumentFormattingEditProvider` method is never called for existing languages (this works only for newly defined custom languages).

Is there a way to execute some custom formatting after the default formatter has executed? Maybe there's some other event we can hook into the existing language provider?

**Comment by alexandrudima** [comment]
@jrieken Can you please clarify what the semantics of `registerDocumentFormattingEditProvider` are? Does the last registered one win?

**Comment by jrieken** [comment]
Yes, the last wins when there a multiple. There is an issue on the VS Code side to explore allowing multiple formatters
