### ISSUE TITLE
CompletionModel / CompletionList : Allow not sorting in client side

### ISSUE THREAD

**Issue by shanielh** [Microsoft/monaco-editor#974]
monaco-editor version: 0.13.1

Hi! I have a special `CompletionItemProvider` which return items with `sortText` in each item, and `isIncomplete` set to `true` so it will be called on every char that the user add/delete.

The problem is that the `CompletionModel` re-sorts the items in [CompletionModel.ts:223](https://github.com/Microsoft/vscode/blob/1005872bf14196a255121356db0748bf90e95d7d/src/vs/editor/contrib/suggest/completionModel.ts#L223
), is there a way to disable this sort?

**Comment by jrieken** [comment]
> is there a way to disable this sort?

No. As soon as the user types something (after intellisense has been invoked and into the range suggestions select), that text is used to sort and filter the list. Only, when no prefix has been typed, e.g. after only manually triggering suggest, the suggestions are sorted as defined by the sortText.

**Comment by shanielh** [comment]
@jrieken thanks for the answer, would you consider a pull request that will allow disabling this behavior by a new Boolean property in the CompletionList?

**Comment by jrieken** [comment]
> disabling this behavior by a new Boolean property in the CompletionList?

No, this is nothing an extension decides. Filtering and resorting is one of the key features and only a user should decide to turn that off. So, yeah we can talk about adding a user setting that disables sort-by-prefix but not an API.
