### ISSUE TITLE
How can i custom margin like vscode?

### ISSUE THREAD

**Issue by cctv1005s** [microsoft/monaco-editor#975]
I am sorry to ask question here, but there is no relevant question or answer in stackoverflow.

as you see, when you open user setting in vscode, mouse hovering the setting, there is a pen you can click and do sth.

How can i realize the feature using Monaco editor, Is there **any api** for this?

I tried to read the code of vscode of this page, but it's to complex for me to realize a small feature.

![image](https://user-images.githubusercontent.com/16508727/43211114-569b0c1a-9063-11e8-9965-5d6bfce53e53.png)

Thanks for your time!

**Comment by yln99517** [comment]
HI , 
 You can refer this sample [glyph margin](https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-rendering-glyphs-in-the-margin
)

-Thanks

**Comment by cctv1005s** [comment]
@yln99517 
Thank you.

But in this sample, i can only set the className of margin.
Is there any option to set a dom margin?
