### ISSUE TITLE
how monaco editor  autocomplete hints based namespace?

### ISSUE THREAD

**Issue by wangning0** [microsoft/monaco-editor#976]
I know monaco editor can auto complete hints according to your custom rules.But I don't know how to auto complete based namespace;

like this:

![image](https://user-images.githubusercontent.com/9164818/43256874-bbe4dc7a-9100-11e8-8bb1-18027d118723.png)

Thanks for your time!

**Comment by rcjsuen** [comment]
@wangning0 I don't understand your question. Just write your custom rule so that period characters (and really, anything you want) are handled and then you can make the code completion show whatever it is that you want it to show.
