### ISSUE TITLE
How to store undo/redo history?

### ISSUE THREAD

**Issue by oleg-webdev** [Microsoft/monaco-editor#977]
I'm trying to implement tabs for editor and I'm storing viewState of prev file before switch to new tab
```prevFile.historyData = editorInstance.saveViewState();```
so, when user switches back to this tab, Im restoring viewstate of this file thru:
`newEditorInstance.restoreViewState(curFile.historyData);`
It works perfectly for scroll position, selection e.t.c, but undo/redo history is gone and user is not able to  get his undo/redo history, that was before switching tabs.

I'm trying to do same trick with setModel in order to return undo/redo history back, but it doesnt works.
`prevFile.model = editorInstance.getModel()`
`newEditorInstance.setModel(prevFile.model)`

I got an error: **Uncaught TypeError: this.model.getLanguageIdentifier is not a fuction**

What does it means, what is wrong and how can I restore edits history?

Thanks!

**Comment by mlynch** [comment]
I am also struggling with this and #604 doesn't seem to do undo/redo. It does preserve cursor and scroll position. Is there another option?

**Comment by mlynch** [comment]
Nevermind, I was storing my models wrong and they were `undefined`. This works great!
