### ISSUE TITLE
Once an editor has become read only no formatting can happen, even if switched back to read only = false

### ISSUE THREAD

**Issue by galusben** [Microsoft/monaco-editor#978]
monaco-editor version: 0.13.1
Browser: electron (chromion? chrome?)
OS: Windows
Steps or JS usage snippet reproducing the issue:

* Create an editor.
```
const editor = monaco.editor.create(element[0], {
            value: text,
            language: mode,
            automaticLayout: true,
            autoIndent: true,
            contextmenu: false,
            formatOnType: true
        });
```
* Switch to read only
```
editor.updateOptions({ readOnly: true})
```
* Switch back to readOnly = false
```
editor.updateOptions({ readOnly: fasle})
```
* Execute formatting - No formatting happens
```
editor.trigger('any', 'editor.action.formatDocument');
```

**Comment by galusben** [comment]
The problem seems to be that I am switching back to readOnly mode before the formatting has finished.
If I change my code to switch back to readOnly 300 milliseconds after triggerring the format, everything works.

Is there a way to pass a callback to the format trigger, or to catch and event that the formatting has finished?

**Comment by alexandrudima** [comment]
You could use `editor.getAction('editor.action.formatDocument').run().then(() => console.log('finished'));`

**Comment by galusben** [comment]
This works great!
