### ISSUE TITLE
Model markers with severity Warning have 'squiggly-info' styling

### ISSUE THREAD

**Issue by mkapiczy** [Microsoft/monaco-editor#979]
Model markers when severity is set to Warning have 'squiggly-info' styling instead of 'squiggly-warning'.

<img width="711" alt="screen shot 2018-07-27 at 13 22 17" src="https://user-images.githubusercontent.com/16140337/43318198-27fad488-91a0-11e8-8377-7e172f8c2756.png">

The code to reproduce in the playground:

```
var jsCode = [
	'"use strict";',
	'function Person(age) {',
	'	if (age) {',
	'		this.age = age;',
	'	}',
	'}',
	'Person.prototype.getAge = function () {',
	'	return this.age;',
	'};'
].join('\n');

var editor = monaco.editor.create(document.getElementById("container"), {
	value: jsCode,
	language: "javascript"
});

monaco.editor.setModelMarkers(editor.getModel(), 'jshint', [{
    startLineNumber:7,
            startColumn: 1,
            endLineNumber: 7,
            endColumn: 100,
            message: 'Bla bla',
            severity: monaco.Severity.Warning
}])

```

It's a problem when I for instance want to modify the color of the 'editorWarning.foreground' style because instead I have to modify 'editorInfo.foreground'.

**Comment by alexandrudima** [comment]
https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md#breaking-changes

![image](https://user-images.githubusercontent.com/5047891/43830679-2aba14d4-9b02-11e8-8762-0fdee0a6940c.png)

**Comment by mkapiczy** [comment]
That solves my issue. Thanks.
