### ISSUE TITLE
loader.js SyntaxError and error 80020101

### ISSUE THREAD

**Issue by matjazmav** [Microsoft/monaco-editor#98]
I'm trying to load Monaco editor with Edge extension to some web page. But I'm strugling to do so.

I have created cdn with Monaco source code and proxy (https://github.com/matjazmav/monaco-editor-cdn). I'm using https://rawgit.com/ to access to this resources.

I have injected `require.js` to head of html and then on page load I'm calling this function:

```
function renderMonacoEditor() {
    require.config({ paths: { 'vs': 'https://cdn.rawgit.com/matjazmav/monaco-editor-cdn/master/min/vs' }});

    window.MonacoEnvironment = {
        getWorkerUrl: function(workerId, label) {
            return 'monaco-editor-worker-loader-proxy.js';
        }
    };

    require(['vs/editor/editor.main'], function() {
        var editor = monaco.editor.create(document.getElementById('code-eye-container'), {
            value: [
                'function x() {',
                '\tconsole.log("Hello world!");',
                '}'
            ].join('\n'),
            language: 'javascript'
        });
    });
}
```

**I get following errors:**
![image](https://cloud.githubusercontent.com/assets/9011654/17463072/f1298458-5cbe-11e6-8bbe-7be136b4329b.png)

**Comment by alexandrudima** [comment]
It looks like `loader.js` cannot load the code due to a security error?
