### ISSUE TITLE
How to register an opener?

### ISSUE THREAD

**Issue by mofux** [microsoft/monaco-editor#980]
When clicking on links in the monaco editor, they are by default opened using a pre-configured opener that handles http and https links and delegates to `window.open`. 

Is it somehow possible to overwrite this opener with my own implementation? For example, I'd like to open `file://` links in my own app.

I found a way to make it work by requiring `vs/platform/opener/browser/openerService`, and then overwriting `OpenerService.prototype.open`, but that's obviously a dirty hack.

**Comment by mofux** [comment]
Another way to do it on an editor instance:

```javascript
editor.getContribution('editor.linkDetector').openerService.open = (url) => {
  // handle it yourself
}
```
Is there a better way to do it?

**Comment by dna2github** [comment]
you can overwrite `textModelService` when you create editor like `monaco.editor.create(..., ..., { textModelService: <your_model_service> })` to handle your protocol
