### ISSUE TITLE
Can expose the contextmenu interface?

### ISSUE THREAD

**Issue by htyoung** [microsoft/monaco-editor#982]
monaco-editor version: 0.13.1
Browser:chrome
OS: windows 10
Steps or JS usage snippet reproducing the issue:
now,I want to customize the contextmenu included the embedded contextmenu(eg:copy ,cut),but I just only can add addtional contextmenu and can't remove or update the contextmenu which is embedded.

**Comment by e-xch** [comment]
I had the same problem with typescript

**Comment by xchange-api** [comment]
I solved the problem with patch-package, it can overwrite third-party libraries
