### ISSUE TITLE
Removing lines and Undo removes additional lines

### ISSUE THREAD

**Issue by DrNiels** [Microsoft/monaco-editor#983]
monaco-editor version: 0.13.1
Browser: Chrome
OS: Windows 10
Steps or JS usage snippet reproducing the issue: I use a small code snippet to remove the currently selected line:
`let line = editor.getPosition().lineNumber;
editor.executeEdits('', [{ range: new monaco.Range(line, 1, line + 1, 1), text: null }]);`

The first time it works fine. But when I undo the removal and remove the line again, additional lines get removed, which is not intended.

For example, when I have five lines of code, remove the third row, undo the removal and remove the third row again, the fourth line is removed as well.

I'm using the editor within an iframe with language as PHP.

Thanks for your help!

**Comment by troy351** [comment]
` editor.pushUndoStop()` can manually create an undo stop, use it before and after `editor.executeEdits`

**Comment by DrNiels** [comment]
I didn't know about the shortcut, thanks for that. That probably suffices for my issue.

However, using pushUndoStop does not solve the error. The undo itself already works fine, the problem occurs when I remove a line again after undoing the operation by executing the script above again (not using redo)

**Comment by troy351** [comment]
It's wired, using the demo [here](https://microsoft.github.io/monaco-editor/)
- switch language to `php`
- click any line of the php code
- open devtools and run `line = editor.getPosition().lineNumber; editor.executeEdits('', [{ range: new monaco.Range(line, 1, line + 1, 1), text: null }]);` in console
- press `ctrl+z` to undo remove line
- run the code above again

Every thing works just as expected.

**Comment by DrNiels** [comment]
I just realized it's my bad. I run the script on Ctrl + Y, which is also Redo. Since I didn't block the event, it removes a line and does a Redo, in this case removing another line. Thanks a lot for your help!
