### ISSUE TITLE
zero-based FoldingRange

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/monaco-editor#984]
from monaco.d.ts:
```ts
export interface FoldingRange {
        /**
         * The zero-based start line of the range to fold. The folded area starts after the line's last character.
         */
        start: number;
```

`zero-based` is a mistake? asking because `Position` is 1-based

**Comment by aeschli** [comment]
It's a mistake, should say 1-based, will fix

**Comment by rcjsuen** [comment]
@akosyakov @aeschli Am I misreading something? Isn't `Position` zero-based?

https://github.com/Microsoft/vscode-languageserver-node/blob/5f9c993ff38f5c369949aeb359b3e9b178172dbc/types/src/main.ts#L19-L24

https://github.com/Microsoft/language-server-protocol/blob/9d64e8cb88f66832a0b262af1dfc187aa3e6d3d2/specification.md

**Comment by rcjsuen** [comment]
Never mind, false alarm. I talked to Anton and he explained to me that Monaco is one-based but the LSP is zero-based.

Sorry for the noise!
