### ISSUE TITLE
DocumentSymbol are not exposed by DocumentSymbolProvider

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#986]

**Comment by alexandrudima** [comment]
@akosyakov Not sure, what do you mean?

**Comment by akosyakov** [comment]
`DocumentSymbolProvider.provideDocumentSymbols` returns only `SymbolInformation`, but in vscode api it supports `DocumentSymbol` as well.
https://github.com/Microsoft/monaco-editor/blob/946bbab82041aad76c2d571d707483621804a837/monaco.d.ts#L4866-L4875

**Comment by alexandrudima** [comment]
I don't think there's any real ask here besides that we ship a new version of the editor?

The `monaco.d.ts` in the pipeline will contain this:

https://github.com/Microsoft/vscode/blob/dcd17d8b8b6930f9a1547c2322ae2fdb3dcdf2a8/src/vs/monaco.d.ts#L5012:L5018

**Comment by alexandrudima** [comment]
@akosyakov I can't find any `SymbolInformation` in the `monaco.d.ts` from master. I'm not sure what the real change is here. @jrieken can you please explain what the change is.
