### ISSUE TITLE
CodeAction.kind is not of CodeActionKind type

### ISSUE THREAD

**Issue by akosyakov** [microsoft/monaco-editor#987]

**Comment by alexdima** [comment]
This is how it appears in our sources at https://github.com/microsoft/vscode/blob/85d031105b7e81f002d772293216145cae02bfe2/src/vs/editor/common/modes.ts#L544 so I think our `monaco.d.ts` generation is fine.

If that is incorrect, IMHO that is not Monaco Editor specific. I suggest to open an issue against VS Code directly.
