### ISSUE TITLE
Where is the place to discuss monaco-editor?

### ISSUE THREAD

**Issue by philcockfield** [microsoft/monaco-editor#988]
I can't see any references to IRC or other chat forums for discussing this project?  In particular, details on the API and the intricacies of configuring behaviors such as intillisense etc.

I started a channel `#monaco-editor` on https://vscode-dev-community.slack.com which seems to be an unofficial community initiated slack group.

I wonder if the team behind this project could either point to that - or point to whatever the official community discussion channel is on the root README so a critical mass of folks assemble in the one place to help each other out.

Thanks!

PS: I ❤️ that you've open-sourced and isolated this module...incredible work!!

**Comment by dernhelm7** [comment]
Would love to get an answer to this as well! In the meantime, how could I get an invite to your channel in vscode-dev-c?

**Comment by hediet** [comment]
We just created https://github.com/microsoft/monaco-editor/discussions for this!

We will also move issues with question characteristics there and concentrate on actionable bugs and some popular feature requests.
