### ISSUE TITLE
Edge/IE Issues w/ Canvas

### ISSUE THREAD

**Issue by alexledbetter** [Microsoft/monaco-editor#99]
I have a page that is binding Monaco Editors into the page for users to modify scripts, everything works great in Chrome/Firefox but in both Edge and IE things are wonky.  

In IE it seems to not work for the mouse detection, I read the note in the issues section, in my case the editors are a decedent of the body but not a direct child.

Often for IE when I add a second editor, the first one will work but the second one has the mouse problem.

In edge it seems not to let me click on the canvas or edit it at all.

**Comment by joelday** [comment]
I think this is a duplicate of #80. It seems to happen when the body element has an explicit height other than auto, such as 100%.

**Comment by alexledbetter** [comment]
Yes, changing the value from 100% to auto solved the problem for me. Thanks Joel

**Comment by alexledbetter** [comment]
Closing as duplicate of #80
