### ISSUE TITLE
Switching the editor from a ".ts" file to a ".js" file causes invalid overloads to be cached

### ISSUE THREAD

**Issue by AlCalzone** [Microsoft/monaco-editor#990]
monaco-editor version: 0.13.1
Browser: Firefox 61
OS: Windows 7
Steps or JS usage snippet reproducing the issue:

1. Run the following in the Monaco playground:
```ts
var indexJSValue = `/**
 * @param {string} a
 * @param {number} [b]
 */
function foo(a, b) {

}
foo(1)`;
var lang = 'typescript';
// first typescript
var model = monaco.editor.createModel(
    indexJSValue, lang, monaco.Uri.from({path: "index.ts"})
);
const editor = monaco.editor.create(document.getElementById("container"), {
	model: model,
});
// now javascript
editor.setModel(
    monaco.editor.createModel(
        indexJSValue, lang, monaco.Uri.from({path: "index.js"})
    )
);

var tsOp = monaco.languages.typescript.typescriptDefaults['getCompilerOptions']();
tsOp.allowJs = true;
tsOp.checkJs = true;
monaco.languages.typescript.typescriptDefaults.setCompilerOptions(tsOp);
```

2. Hover `function foo()`. It shows `any`, `any` as param types, and another overload.
3. Hover `foo(1)`. It shows two possible overloads (string, number?) and (any, any).

I expect only one overload to exist after switching to JS: `string, number` as determined by the JSDoc comments. The `any, any` one comes from the first typescript invocation where JSDoc is not active.

**Comment by AlCalzone** [comment]
Or alternatively:

```js
var indexJSValue = `/**
 * @param {string} a
 * @param {number} [b]
 */
function foo(a, b) {

}
foo(1)`;
var lang = 'typescript';
// first typescript
const tsModel = monaco.editor.createModel(
    indexJSValue, lang, monaco.Uri.from({path: "index.ts"})
);
const jsModel = monaco.editor.createModel(
    "foo(1, 2)", lang, monaco.Uri.from({path: "index.js"})
);

// load the ts Model
const editor = monaco.editor.create(document.getElementById("container"), {
	model: tsModel,
});
// now javascript
editor.setModel(jsModel);

var tsOp = monaco.languages.typescript.typescriptDefaults['getCompilerOptions']();
tsOp.allowJs = true;
tsOp.checkJs = true;
monaco.languages.typescript.typescriptDefaults.setCompilerOptions(tsOp);
```

Result:
The editor shows
```js
foo(1, 2);
```
without any errors. A workaround is to set the `tsModel` value to "" explicitly before switching models.

**Comment by alexandrudima** [comment]
All models travel to the web worker and take part in the same language service. Currently, there is no isolation between them. You can empty or dispose them as you noticed.

**Comment by AlCalzone** [comment]
I find it weird that seemingly multiple models can be active at any given time, although I can only access one via `getModel` and `setModel`. I would assume that setting a new model causes the old one to be "forgotten".

**Comment by alexandrudima** [comment]
@AlCalzone That is not the case. A model can be held in memory and not be attached to an editor. It is desirable to have models in memory in order to keep their decorations, undo-redo stacks, tokenization information, etc.

That is how tabs are implemented in VS Code:

![image](https://user-images.githubusercontent.com/5047891/43838515-d89fbf22-9b1b-11e8-9ffb-7d6b24c9b1fd.png)


There is a single editor, but, depending on some factors, 1 or more models in memory.

**Comment by AlCalzone** [comment]
I see, thanks.
