### ISSUE TITLE
SuggestWidget _isVisible is always true.

### ISSUE THREAD

**Issue by mkapiczy** [microsoft/monaco-editor#991]
monaco-editor version: 0.13.1
Browser: Google Chrome
OS: OSX High Sierra
Steps or JS usage snippet reproducing the issue:
```
let editor = monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});

editor.onKeyDown(e => {
    console.log('Suggest visible', editor._view.contentWidgets._widgets['editor.widget.suggestWidget']._isVisible)
})
```

Before showing the suggestion box the above console.log will throw an error because the widget is undefined. That's all right.

However, when the widget gest shown for the first time, the value isVisible is staying true even when the widget is now shown.

**Comment by Baitula** [comment]
Fine
