### ISSUE TITLE
JSON validation tooltips are always "undefined"

### ISSUE THREAD

**Issue by DenisVuyka** [Microsoft/monaco-editor#992]
monaco-editor version: 0.13.1
Browser: Firefox 62
OS: macOS
Steps or JS usage snippet reproducing the issue:

I am trying to reproduce JSON editing as per the following example: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

Everything seems to be working fine, I have auto-completion for enums on Ctrl+Space, and validation is correct. The only problem I can't figure out how to solve is tooltips that always say 'undefined'

![screen shot 2018-08-07 at 14 33 45](https://user-images.githubusercontent.com/503991/43779302-fcfc4894-9a4f-11e8-9982-b18951615d86.png)

The code online has correct tooltips:

![screen shot 2018-08-07 at 14 41 47](https://user-images.githubusercontent.com/503991/43779340-14bf8702-9a50-11e8-91b1-f0904f190b39.png)

Can anyone please give me any clue on what settings should I be looking at or how to address the validation text?

**Comment by alexandrudima** [comment]
@DenisVuyka Do you have any additional steps to reproduce? Are there any errors in the console?

**Comment by DenisVuyka** [comment]
@alexandrudima while trying to create steps to reproduce I got it working in the sandbox: https://stackblitz.com/edit/monaco-json?file=index.html. 

I guess it is somehow related to the scenario I'm using and Angular 6 (https://github.com/ngstack/core/blob/master/projects/code-editor/src/lib/services/code-editor.service.ts#L61).

Thanks anyway, I think the ticket can be closed.

**Comment by DenisVuyka** [comment]
@alexandrudima The issue I've been struggling with is related to this: https://github.com/Microsoft/monaco-editor/issues/790
