### ISSUE TITLE
Monarch tokenizer regex doesn't recognize function name

### ISSUE THREAD

**Issue by tidus2102** [microsoft/monaco-editor#993]
Hi, I use Monaco editor to edit js code and I customized editor theme. I want to highlight js function name but the default tokenizer only recognize them as **identifier**, now I need to update it to token "function". So first I try to modify js tokenizer in [Monarch playground](https://microsoft.github.io/monaco-editor/monarch.html). But I got a problem: the tokenizer can't detect js function name no matter how I try. Here are some screenshot:

First, I tested with a sample regex to see how it works: `function [a-z_$][\w$]*`
![screen shot 2018-08-07 at 20 55 39](https://user-images.githubusercontent.com/7001637/43780216-48180ece-9a84-11e8-8e0a-4a1acd0a87bd.png)
And the result is ok, tokenizer can detect this regex correctly
![screen shot 2018-08-07 at 20 42 34](https://user-images.githubusercontent.com/7001637/43780399-b596443e-9a84-11e8-83f3-fce65dcf1eb2.png)

Then I tested with the regex detect function name ONLY: `(?<=function )[a-z_$][\w$]*`
![screen shot 2018-08-07 at 20 45 30](https://user-images.githubusercontent.com/7001637/43780450-cf982f14-9a84-11e8-83e1-ab5431358355.png)
But this time, **the tokenizer doesn't recognize function name**
![screen shot 2018-08-07 at 21 00 58](https://user-images.githubusercontent.com/7001637/43780672-4e1858dc-9a85-11e8-884f-4e60335ec95f.png)

I tried and researched all resource as possible but still can't find the solution. Please help me check it!

Just one more question: How to modify default js tokenizer instead of creating new language like js2 to use my custom tokenizer? Because I only want to modify default js tokenizer (change it a little bit), no need to create new language.

Thanks!

monaco-editor version: 0.13.1
Browser: Google Chrome 68.0.3440.84
OS: OSX El Capitan 10.11.3

**Comment by alexandrudima** [comment]
- the JS tokenizer is implemented by using the TS lexer; but for the upcoming version we are moving to a Monarch based tokenizer for JS.
- I don't think JS regexes support lookbehinds, so you are going to need to build a few more states in your state machine. i.e. look for function, then enter a state "afterFunction", then eat up whitespace, then look for the identifier. One example would be the handling of `<script>` tags in HTML from [here](https://github.com/Microsoft/monaco-languages/blob/6fc362e75a0a6fcf2ec813883a336d0e03d8793f/src/html/html.ts#L78)

**Comment by RailRunner166** [comment]
since chrome 62 it should, however it doesn't. idek if this is a bug with react or monaco, but i doubt it's react because many other sites use it with react, and that leaves me with monaco. one way i tried doing this different was i made a capturing group around what i wanted highlighted, maybe support this as an option in the future?
