### ISSUE TITLE
Inner textarea having zero area causes errors

### ISSUE THREAD

**Issue by greyhillman** [microsoft/monaco-editor#994]
monaco-editor version: 0.12.0
Browser: IE 11
OS: Windows 10

The width and height for the `textarea` in the monaco-editor are both 0 for IE 11, Firefox, and Edge. However, Chrome has width and height of 1.

This has caused automated tests to fail since the element is not displayed (ie. it has zero area).

**Comment by greyhillman** [comment]
The issue I just linked explains a bit more about how monaco-editor causes errors to be thrown in WebDriver.

Would it be possible to make all the browsers consistent by having a 1x1 area? Looking at the CSS, it says the text and background color are both transparent and overflow is hidden. Looking at this [fiddle](https://jsfiddle.net/ghill/2zy4cmwL/) in all the browsers shows nothing. So making them all have 1x1 area wouldn't change the look of the editor at all.

If that makes sense, I can even do the work and submit a PR.

Thanks for giving the background info about why it's 1x1 in Chrome!

**Comment by alexandrudima** [comment]
No, I would not want to have a 1x1 textarea everywhere.

I would like to have a 0x0 textarea everywhere because the textarea is just an input/output driver and is not meaningfully displayed unless composition is taking place.

**Comment by alexdima** [comment]
This can be worked around from the embedder CSS, so closing at this point.
