### ISSUE TITLE
How to trigger a paste event to paste the clipboard's content into the editor?

### ISSUE THREAD

**Issue by Cuishibing** [Microsoft/monaco-editor#999]
Browser:chrome
OS: windows 10

**Comment by Cuishibing** [comment]
I use editor.getSupportedActions(); get all support actions,There are only the following items about the clipboard.

1. editor.action.clipboardCutAction
2. editor.action.clipboardCopyAction
3. editor.action.clipboardCopyWithSyntaxHighlightingAction

**Comment by alexandrudima** [comment]
AFAIK, for security reasons, it is not possible to programmatically trigger pasting from the user's clipboard.

**Comment by Cuishibing** [comment]
Thank you very much for your answer and solved my doubts.
